### ISSUE TITLE
[mingw-w64-qt6-tools] qmake missing

### ISSUE THREAD

**Issue by Amphaal** [msys2/MINGW-packages#10018]
Some tools included in this package (like windeployqt) still require qmake at runtime for some reasons. I've reported the need to drop this requirement upstream :
https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-97998.

**Comment by MehdiChinoune** [comment]
> Some tools included in this package (like windeployqt) still require qmake at runtime for some reasons. I've reported the need to drop this requirement upstream : https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-97998.

Could you elaborate, qmake is part of qt6-base which is a dependency of qt6-tools the package that contains windeployqt.
What problem do you faced when using windeployqt-qt6?

**Comment by Amphaal** [comment]
Yeah my bad, didnt notice the qmake rename into qmake6... Since qt6-static package has both "qmake" and "qmake6", I assumed something was missing. windeployqt allows overriding of default qmake executable path, so the executable duplication done on the qt6-static package convinience is not that mandatory.

**Comment by Amphaal** [comment]
Simply running windeployqt-qt6 without specifying any "--qmake <path>" leads to an error because it expects qmake.exe to be named qmake, and not qmake6. Worked out of the box with qt5 windeployqt.
