### ISSUE TITLE
libavif 0.9.3 update-request

### ISSUE THREAD

**Issue by novomesk** [msys2/MINGW-packages#10010]
Hello,

Please, when you have time, upgrade libavif package to 0.9.3

I am sure that rebuild of `kimageformats-qt5` will be needed afterwards and most probably also for `darktable` and `libgd`

Thanks!

**Comment by Biswa96** [comment]
Would you like to test the new packages from the linked pull request?

**Comment by novomesk** [comment]
I will test (from the PR or new packages) but probably only after weekend.

I'll tell you if there is some problem.

Thanks again.

**Comment by novomesk** [comment]
I tried following two and they work for me:
`mingw-w64-x86_64-libavif-0.9.3-1-any.pkg.tar.zst`
`mingw-w64-x86_64-kimageformats-qt5-5.85.0-3-any.pkg.tar.zst`
