### ISSUE TITLE
Why is there a circular dependency to 'mingw-w64-x86_64-x264'?

### ISSUE THREAD

**Issue by WyvernZhao** [msys2/MINGW-packages#10034]
Package 'mingw-w64-x86_64-x264' has a circular dependency as:
mingw-w64-x86_64-x264 -> mingw-w64-x86_64-ffms2 -> mingw-w64-x86_64-ffmpeg -> mingw-w64-x86_64-x264

This is a bug, right?

**Comment by Biswa96** [comment]
* x264 requires ffms2, see https://code.videolan.org/videolan/x264/-/blob/master/configure

**Comment by WyvernZhao** [comment]
> * x264 requires ffms2, see https://code.videolan.org/videolan/x264/-/blob/master/configure

Anyway, there must be a better way to solve this problem, right? As I don't want to install a bunch of "not real" dependent packages (over 80 packages, including ffmpeg & opencv) along with libx264. Besides, 'mingw-w64-x86_64-x265' doesn't have this circular dependency issue.

**Comment by raedrizqie** [comment]
optdepends will be automatically linked if found while compiling.. @Biswa96 is there a better way to handle this?

**Comment by lazka** [comment]
splitting would work I guess (?)

**Comment by Naine** [comment]
> This is a bug, right?

It is certainly not a bug. x264 CLI uses ffmpeg (via ffms2) to decode input, and ffmpeg uses libx264 as an encoder.

**Comment by WyvernZhao** [comment]
At least it is a flaw in x264 project. It'll be better if they could seperate x264 CLI out from libx264, as an individual project. Including such a big project ffmpeg as dependency brings a lot of inconvenients during developing.

**Comment by Biswa96** [comment]
As Christoph said, we can split the x264 package as x264-bin and x264-lib (or something like that). But it may create a little confusion among users. I am thinking to explore some well known Linux distributions.

**Comment by Biswa96** [comment]
The library from x264 package was split into separate libx264 package in this commit https://github.com/msys2/MINGW-packages/commit/b7bd614ea59cdce2174fd232a2576609d54df39c
