### ISSUE TITLE
MINGW64  x86_64-pc-msys/bin/ld  glib-2.0  undefined reference to `g_vsnprintf' 

### ISSUE THREAD

**Issue by macoomac** [msys2/MINGW-packages#10047]
MINGW64  ld  glib-2.0  undefined reference to `g_vsnprintf'

#gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-msys/10.2.0/lto-wrapper.exe
Target: x86_64-pc-msys
Configured with: /c/_/S/gcc/src/gcc-10.2.0/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --disable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.0 (GCC)

#ld -v
GNU ld (GNU Binutils) 2.36.1

#pkg-config --modversion glib-2.0
2.70.0

#pkg-config --cflags --libs glib-2.0
-I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include -mms-bitfields -I/mingw64/include -L/mingw64/lib -lglib-2.0 -lintl

# make
gcc -O2 -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include -mms-bitfields -I/mingw64/include  -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -L/mingw64/lib -lglib-2.0 -lintl   gftp-text.c   -o gftp-text
/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: /tmp/cc8RP1k6.o:gftp-text.c:(.text+0x7b): undefined reference to `g_vsnprintf'
/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: /tmp/cc8RP1k6.o:gftp-text.c:(.text+0x13e): undefined reference to `g_vsnprintf'
/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: /tmp/cc8RP1k6.o:gftp-text.c:(.text+0x184): undefined reference to `gftp_string_from_utf8'
......

**Comment by lazka** [comment]
You are using msys gcc/pkgconf in a mingw64 environment, which is not compatible. Try `pacman -S mingw-w64-x86_64-toolchain`

**Comment by macoomac** [comment]
pacman -Sl | grep toolchain  
NULL

**Comment by Biswa96** [comment]
> pacman -Sl | grep toolchain
> NULL

The correct command would be `pacman -Ss mingw-w64-x86_64-toolchain`. Toolchain is a package group which installs all the compiler, linker and its related programs. For example, you can find more information about mingw-w64-x86_64-toolchain here https://packages.msys2.org/group/mingw-w64-x86_64-toolchain

Also some hints here https://www.msys2.org/wiki/Creating-Packages/#build-software
