### ISSUE TITLE
MSYS   gtk+-2.0  Does msys have a GKT library

### ISSUE THREAD

**Issue by macoomac** [msys2/MINGW-packages#10060]
MSYS   
#pacman -Sl | grep gtk
....
msys gtk-doc 1.33.2-1

not mingw64  mingw-w64-x86_64-gtk2 

compiling the source code depends on GTK and ioctl.h, and msys must be used.
Is there any way to deal with it?

**Comment by lazka** [comment]
We don't have any gtk related cygwin packages, and there are no plans to, sorry.
