### ISSUE TITLE
MinGW GCC package size growth due to unstripped debug info

### ISSUE THREAD

**Issue by karen-arutyunov** [msys2/MINGW-packages#10093]
While packaging MinGW GCC 11.2.0 for build2 toolchain, we have discovered that debug info is not stripped from static libraries in the `lib/gcc/x86_64-w64-mingw32/11.2.0` directory of the `mingw-w64-x86_64-gcc-11.2.0-1-any.pkg.tar.zst` package archive. 

So, for example `libstdc++.a` size is 32,5M in contrast to that for GCC 10.2.0 (`mingw-w64-x86_64-gcc-10.2.0-1-any.pkg.tar.zst`), which is only 6,5M.

Running `strip -d libstdc++.a` brings the size back to normal (6,9M).

I believe that the GCC package size growth from 26M to 38M is largely due to this issue.

**Comment by MehdiChinoune** [comment]
see: https://github.com/msys2/msys2-pacman/issues/7

**Comment by MehdiChinoune** [comment]
Should gcc be rebuilt after the pacman issue is now fixed?
