### ISSUE TITLE
Bootstrap GCC for CLANG64.

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#10095]
Could someone bootstrap GCC for CLANG64.
I mean build it on UCRT64 and package it for CLANG64, and then bootstrap it on CLANG64, so GCC got built by itself, as I failed to build it with Clang compiler.
There are some missing packages on for CLANG64 because of Ada.

**Comment by jeremyd2019** [comment]
No.  GCC would not be fully interoperable with CLANG*, that's why it has a new 'subsystem' and not just using clang from ucrt64.

**Comment by MehdiChinoune** [comment]
> No. GCC would not be fully interoperable with CLANG*, that's why it has a new 'subsystem' and not just using clang from ucrt64.

I want to use gcc in CLANG64 like BSD* OSs, where the main compiler is clang and gcc is an option.

**Comment by mati865** [comment]
The biggest issue with GCC is it doesn't support native TLS on Windows. Lesser issues like lack of support for libc++ and libunwind probably would be easily patchable.
