### ISSUE TITLE
Unable to import PyQt6 modules after installation

### ISSUE THREAD

**Issue by el07694** [msys2/MINGW-packages#10131]
Hi,

I am trying to update from PyQt5 to PyQt6.
When i run 
`from PyQt6 import QtCore` 
an error oquers:

```
>>> from PyQt6 import QtCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing QtCore: Δεν ήταν δυνατό να εντοπιστεί η καθορισμένη διαδικασία.
>>>

```

I have installed all qt6 packages i found in msys package list but the problem consists.

**Comment by MehdiChinoune** [comment]
I couldn't reproduce the issue!
Which OS are you using? (Windows 7, 8.1, 10 1809...) (32bit or 64bit)
which environment? (mingw32, mingw64...)

**Comment by el07694** [comment]
Ok i solve it.
1. I just install all qt6 packages from https://packages.msys2.org/search?q=qt6 .
2. I download [winpython](https://winpython.github.io/) and extract all qt6* files in C:\msys64\mingw64\bin and in C:\msys64\mingw64\lib\python3.9\site-packages\PyQt6
3. Finally i update  all msys2 packages running the command `pacman -Qqn | pacman -S -`

Then i can run from PyQt6 import QtCore and open a simple PyQt6 app with no errors.

**Comment by Biswa96** [comment]
Please provide the details about your current working environment. e.g. OS version, mingw32 or mingw64 etc. That workaround should not be required while using mingw packages. pyqt6 has many optional dependencies which are not installed automatically. You can use [Process Monitor][1] to find out which DLL can not be found while importing pyqt6.

[1]: https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

**Comment by el07694** [comment]
Msys2 (Mingw64 bit)
Python: 3.9.7
OS: Windows 11 Home 21H2

**Comment by MehdiChinoune** [comment]
> Msys2 (Mingw64 bit) Python: 3.9.7 OS: Windows 11 Home 21H2

How did you install pyqt6 for the first time?

**Comment by MehdiChinoune** [comment]
I couldn't reproduce the issue on Windows 11 Home 21H2 (VirtualBox Machine).

**Comment by el07694** [comment]
First i try with 

`pip install PyQt6-sip`
`pip install PyQt6 PyQt6-tools`

and then with:

`pacman -S mingw-w64-x86_64-python-pyqt6`
`pacman -S mingw-w64-x86_64-python-pyqt6-sip`

**Comment by MehdiChinoune** [comment]
I think with the first try using pip, some dlls were installed.
Try to reinstall msys2 and install pyqt6 only using pacman.

**Comment by el07694** [comment]
Ok done, (after a lot of pacman commands)

There is no problem when i installed it directly from msys packages.
Now i just wait to release the QtWebEngine msys version :)
