### ISSUE TITLE
Virgil3D for QEMU on Windows 10

### ISSUE THREAD

**Issue by kjliew** [msys2/MINGW-packages#10144]
Require supporting package mingw-w64-virglrenderer. It is available at
https://github.com/kjliew/qemu-3dfx/tree/master/virgil3d/MINGW-packages

**Comment by Biswa96** [comment]
Hi @kjliew, would you like to test the package from the linked pull request? You can download the test package from GitHub Actions artifacts and install it with `pacman -U` command.

**Comment by lazka** [comment]
See #10173
