### ISSUE TITLE
Clang32 packages unavailable

### ISSUE THREAD

**Issue by shermp** [msys2/MINGW-packages#10157]
pacman can't seem to find any `clang-i686` packages, and it doesn't appear to sync with any clang32 package database.

Is this by design, or has something gone wrong somewhere?

Tested on both local MSYS2, and in the Github `setup-msys2` action.

**Comment by heljkon** [comment]
Add the clang32 section to /etc/pacman.conf 

```
[clang64]
Include = /etc/pacman.d/mirrorlist.mingw

[clang32]
Include = /etc/pacman.d/mirrorlist.mingw

[msys]
Include = /etc/pacman.d/mirrorlist.msys
```

**Comment by Biswa96** [comment]
> Is this by design, or has something gone wrong somewhere?

clang32 is somewhat in testing stage and incomplete. You may find many packages are unavailable there. So, it was not added in pacman.conf file yet. But feel free to experiment with it.

**Comment by MehdiChinoune** [comment]
Just a Question: Why do you need CLANG32?

**Comment by shermp** [comment]
Thanks everyone. I was a bit confused, because I could see packages on https://packages.msys2.org/package/ but couldn't download them via pacman, or with `setup-msys2`.

> Just a Question: Why do you need CLANG32?

I'm creating build of dosbox-staging via MSYS2, Always useful to keep 32 bit windows builds available for now.

**Comment by Biswa96** [comment]
You can build 32bit binary with mingw32 environment also.

**Comment by shermp** [comment]
> You can build 32bit binary with mingw32 environment also.

Yeah, we are doing that. It's nice to get compiler warnings and stuff for different compilers though.
