### ISSUE TITLE
CI: Change to windows-2022 and use `release: false`?

### ISSUE THREAD

**Issue by naveen521kk** [msys2/MINGW-packages#10163]
Windows 2022 image from GHA is generally available https://github.com/actions/virtual-environments/issues/4488 and the changes related to msys2 is that by default none of the packages is installed https://github.com/actions/virtual-environments/issues/3949. So, can we move to that as CI so that it will save some time?

**Comment by lazka** [comment]
I guess possible. The only downside is that we currently build in a "non-default" path, also in autobuild, which might help to expose path bugs.

**Comment by Biswa96** [comment]
CI was changed to windows-2022 in this commit https://github.com/msys2/MINGW-packages/commit/e43a0ec6ae936adecb01e0006b22a0718afb54da
