### ISSUE TITLE
packages to upgrade pacman

### ISSUE THREAD

**Issue by sdarwin** [msys2/MINGW-packages#10168]
Hi,
We are running CI (continuous integration) on Appveyor.  Their Visual Studio 2017 images were failing because pacman was out-of-date.  So, upgraded pacman:

```
pacman --noconfirm -U "http://repo.msys2.org/msys/x86_64/libzstd-1.4.4-2-x86_64.pkg.tar.xz"
pacman --noconfirm -U "http://repo.msys2.org/msys/x86_64/zstd-1.4.4-2-x86_64.pkg.tar.xz"
pacman --noconfirm -U "http://repo.msys2.org/msys/x86_64/pacman-5.2.1-6-x86_64.pkg.tar.xz"
```

Recently, those very packages were removed.

So, I have updated the command again, to this:

```
pacman --noconfirm -U "http://repo.msys2.org/msys/x86_64/libzstd-1.4.5-2-x86_64.pkg.tar.xz"
pacman --noconfirm -U "http://repo.msys2.org/msys/x86_64/zstd-1.4.5-2-x86_64.pkg.tar.xz"
pacman --noconfirm -U "http://repo.msys2.org/msys/x86_64/pacman-5.2.1-12-x86_64.pkg.tar.xz"
```

If those also become unavailable, and are dropped, it seems we will be at the end of the line, without a fix.

The reason is that newer packages use zst, but pacman cannot upgrade itself using zst.   That's the root of the whole problem. I would suggest you leave the remaining xz packages as-is, and not remove them.  But I suppose their time is very limited.

The following xz packages, and maybe others, say "Invalid or corrupted package (PGP signature)"

pacman-5.2.2-5-x86_64.pkg.tar.xz                   20-Dec-2020 12:24     11M
pacman-5.2.2-5-x86_64.pkg.tar.xz.sig               20-Dec-2020 12:32     438

libzstd-1.4.7-1-x86_64.pkg.tar.xz                  20-Dec-2020 12:23    252K
libzstd-1.4.7-1-x86_64.pkg.tar.xz.sig              20-Dec-2020 12:32     438

zstd-1.4.7-1-x86_64.pkg.tar.xz                     20-Dec-2020 12:23    307K
zstd-1.4.7-1-x86_64.pkg.tar.xz.sig                 20-Dec-2020 12:32     438

Just wanted to mention the situation, you are welcome to close the issue.

**Comment by raedrizqie** [comment]
i think pacman can be linked to zst statically, so only one package to deal with problem like this

**Comment by Biswa96** [comment]
The issue is with Appveyor CI. Have you asked them to update the CI build environment? You can use `pacman -Syyu` command to update packages.

**Comment by lazka** [comment]
Appveyor has stopped updating the 2017 image two years ago. Not much we can do there.

We currently remove old packages after 1.5 years. I guess we could add an exception for those three package somehow..

**Comment by lazka** [comment]
> i think pacman can be linked to zst statically, so only one package to deal with problem like this

We already do. But the zstd binary is a dependency for building packages (via makepkg)

**Comment by MehdiChinoune** [comment]
@sdarwin Isn't possible for you to use `Visual Studio 2019` or `Visual Studio 2022` images which should contain a newer MSYS2?

**Comment by sdarwin** [comment]
@MehdiChinoune , that's a good idea.  

I suppose the reason is that multiple repositories in the organization have their CI configured with Visual Studio 2017, and rather than having them all crash, it would be nice if they would keep running...   In the meantime, when upgrading a configuration, change it to Visual Studio 2019 or Visual Studio 2022, as you suggest.

**Comment by lazka** [comment]
If all fails you can also install a fresh MSYS2 yourself to a different location on the old image: https://www.msys2.org/docs/ci/#other-systems

**Comment by sdarwin** [comment]
Well, it happened. 
http://repo.msys2.org/msys/x86_64/pacman-5.2.1-12-x86_64.pkg.tar.xz disappeared.   
CI jobs crashed, again.
The solution is upgrading to Visual Studio 2019.   So in that sense, it's fixed.

We are running tests as far back as possible, to ensure the software is compatible with older copies of software that end-users might still have.  Many repositories such as Ubuntu or Redhat keep packages available for 10 years or more.  1.5 years is a very short time.  Anyway.
