### ISSUE TITLE
mingw-w64-x86_64-ocaml-findlib: ocamlfind doesn't find its config file

### ISSUE THREAD

**Issue by sosh72** [msys2/MINGW-packages#1017]
$ ocamlfind.exe list
ocamlfind: Config file not found - neither D:\develop\msys64\mingw64\etc\findlib.conf nor the directory D:\develop\msys64\mingw64\etc\findlib.conf.d

This cannot work on my machine. D: happens to be my DVD drive...

Asking Google for help, it seems the location of the config file is hardcoded at compile time.

As a workaround, one can do (in my case)
export OCAMLFIND_CONF=/mingw64/etc/findlib.conf

Not sure what would be the cleanest way to get around this.

**Comment by MehdiChinoune** [comment]
ocaml-findlib no longer available.
