### ISSUE TITLE
unable to link to static glib2

### ISSUE THREAD

**Issue by flinco** [msys2/MINGW-packages#10211]
I use MinGW on MSYS2 for compiling a couple of small C applications, ported from Linux.
Both the applications:
- link to glib2;
- are statically linked.

Up to some days ago I was able to compile and link.
Few days ago I ran `pacman -Syuu` to make the environment up to date and surprisingly I can not link anymore.
The linker reports what follows (for both applications):
```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglib-2.0.a(gutils.c.obj):(.rdata$.refptr.FOLDERID_LocalAppData[.refptr.FOLDERID_LocalAppData]+0x0): undefined reference to `FOLDERID_LocalAppData'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglib-2.0.a(gutils.c.obj):(.rdata$.refptr.FOLDERID_ProgramData[.refptr.FOLDERID_ProgramData]+0x0): undefined reference to `FOLDERID_ProgramData'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglib-2.0.a(gutils.c.obj):(.rdata$.refptr.FOLDERID_InternetCache[.refptr.FOLDERID_InternetCache]+0x0): undefined reference to `FOLDERID_InternetCache'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglib-2.0.a(gutils.c.obj):(.rdata$.refptr.FOLDERID_Profile[.refptr.FOLDERID_Profile]+0x0): undefined reference to `FOLDERID_Profile'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglib-2.0.a(gutils.c.obj):(.rdata$.refptr.FOLDERID_Videos[.refptr.FOLDERID_Videos]+0x0): undefined reference to `FOLDERID_Videos'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglib-2.0.a(gutils.c.obj):(.rdata$.refptr.FOLDERID_Templates[.refptr.FOLDERID_Templates]+0x0): undefined reference to `FOLDERID_Templates'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglib-2.0.a(gutils.c.obj):(.rdata$.refptr.FOLDERID_PublicDocuments[.refptr.FOLDERID_PublicDocuments]+0x0): undefined reference to `FOLDERID_PublicDocuments'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglib-2.0.a(gutils.c.obj):(.rdata$.refptr.FOLDERID_Public[.refptr.FOLDERID_Public]+0x0): undefined reference to `FOLDERID_Public'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglib-2.0.a(gutils.c.obj):(.rdata$.refptr.FOLDERID_Pictures[.refptr.FOLDERID_Pictures]+0x0): undefined reference to `FOLDERID_Pictures'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglib-2.0.a(gutils.c.obj):(.rdata$.refptr.FOLDERID_Music[.refptr.FOLDERID_Music]+0x0): undefined reference to `FOLDERID_Music'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglib-2.0.a(gutils.c.obj):(.rdata$.refptr.FOLDERID_Downloads[.refptr.FOLDERID_Downloads]+0x0): undefined reference to `FOLDERID_Downloads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglib-2.0.a(gutils.c.obj):(.rdata$.refptr.FOLDERID_Documents[.refptr.FOLDERID_Documents]+0x0): undefined reference to `FOLDERID_Documents'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglib-2.0.a(gutils.c.obj):(.rdata$.refptr.FOLDERID_Desktop[.refptr.FOLDERID_Desktop]+0x0): undefined reference to `FOLDERID_Desktop'
collect2.exe: error: ld returned 1 exit status
```

I searched on the Internet about this, but I found nothing about undefined references to FOLDERID_xxxxxx.

For both the applications, the calls to pkg-config are made as follow:
`PKG_CFLAGS  := $(shell pkg-config --cflags  $(pkg_packages))`
`PKG_LDFLAGS := $(shell pkg-config --libs --static $(pkg_packages))`

Dynamic linking works, but I need static linking.
I can provide you with more information at any time.

**Comment by Biswa96** [comment]
Add `-luuid` linking option. libuuid.a is provided by mingw-w64-crt. It contains all the exported GUIDs.

**Comment by flinco** [comment]
It works. Many many thanks!

**Comment by Biswa96** [comment]
Would it be correct to add `-luuid` option in pkgconfig file of glib2? @lazka

**Comment by lazka** [comment]
Looks like it, yeah

**Comment by Biswa96** [comment]
I have sent a merge request in upstream to fix this issue https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2384. When it will be approved I shall import the patch here.

**Comment by revelator** [comment]
probably more packages that need uuid as a dependency, ran into this quite a few times over the years with different packages.

**Comment by revelator** [comment]
gcc by default links to the bare minimal required system libraries when linking statically, sadly it seems these where added around Win9x / NT4 and newer changed to keep up with internal changes in windows :S NT4 actually used 3 different uuid libraries whereas current windows just uses one. Moreover it was newer added as a dependency back then. 

Should be possible making a small patch for gcc which takes care of this, id software had an extensive list of system libraries possibly needed when linking statically (quake was actually developed on gcc :P)

**Comment by revelator** [comment]
here is the list of libraries quake uses, ofc not all of them are nessesary or even linked but i found that most projects who otherwise would barf when trying to link statically will build no problem using this list.

kernel32
user32
gdi32
winspool
comdlg32
psapi 
advapi32
shell32
ole32
oleaut32
uuid
odbc32
odbccp32
comctl32
shlwapi
winmm
wsock32

compare to gcc which by default only links to these ->

gdi32 
comdlg32 
psapi 
advapi32 
shell32 
user32 
kernel32

**Comment by Biswa96** [comment]
@flinco Apology for late reply. Upstream has just accepted my patch. I have sent a pull request here to import that fix in the package. See the linked pull request above.
