### ISSUE TITLE
DNS constants and functions are old, don't include multicast options

### ISSUE THREAD

**Issue by cminyard** [msys2/MINGW-packages#10223]
I was trying to use DnsStartMulticastQuery() in a program, and under MINW-w64 it was failing.  I can't find that or other DNS things that were added in Windows 10.  I don't know if there's some constant I need to define to get Windows 10 support, but I can't find any of these things grepping in mingw64.

I did see the following: https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/1454573540-16936-2-git-send-email-songdongsheng%40live.cn/#msg34821863
where someone posted support for this back in 2016, and it seemed to be accepted.

**Comment by Biswa96** [comment]
Are you compiling any open source project? Do you have a sample program? Just asking to reproduce your issue.

**Comment by cminyard** [comment]
Sure, here's a small program I'm playing with trying to learn how this interface works.  Compiles in Visual Studio.

`#include <stdio.h>
#include <wchar.h>
#include <windows.h>
#include <windns.h>

static HANDLE waiter;

static void WINAPI
handler(PVOID pQueryContext,
    PMDNS_QUERY_HANDLE pQueryHandle,
    PDNS_QUERY_RESULT results)
{
    PDNS_RECORD rec = results->pQueryRecords;

    printf("Got result:\n");
    while (rec) {
        printf("  name: %ls\n", rec->pName);
        printf("  type: 0x%x\n", rec->wType);
        printf("  length: %d\n", rec->wDataLength);
        rec = rec->pNext;
    }
    fflush(stdout);
}

int
main(int argc, char* argv[])
{
    MDNS_QUERY_REQUEST req;
    MDNS_QUERY_HANDLE hnd;
    DNS_STATUS rv;
    wchar_t wbuf[100];

    swprintf(wbuf, 100, L"%hs", argv[1]);
    wprintf(L"A: %ls\n", wbuf);
    fflush(stdout);

    waiter = CreateSemaphoreA(NULL, 0, 1, NULL);
    if (waiter == NULL) {
        fprintf(stderr, "CreateSemaphoreA failed\n");
        return 1;
    }

    memset(&req, 0, sizeof(req));
    req.Version = DNS_QUERY_REQUEST_VERSION1;
    req.Query = wbuf;
    req.QueryType = DNS_TYPE_ALL;
    req.QueryOptions = DNS_QUERY_STANDARD;
    req.InterfaceIndex = 0;
    req.pQueryCallback = handler;

    rv = DnsStartMulticastQuery(&req, &hnd);
    if (rv != ERROR_SUCCESS) {
        fprintf(stderr, "DnsStartMulticastQuery failed: %d\n", rv);
        return 1;
    }

    WaitForSingleObject(waiter, INFINITE);

    return 0;
}`

**Comment by Biswa96** [comment]
Thanks. I shall send a patch to mingw-w64 mailing list and notify you here.

**Comment by Biswa96** [comment]
I have sent a patch in upstream mingw-w64 mailing list to add those function definitions here https://sourceforge.net/p/mingw-w64/mailman/message/37394322/. For a quick fix, you can apply that patch file to your current msys2/mingw64 setup with `patch -p1 -i <patch-file>` command.

**Comment by cminyard** [comment]
On Wed, Dec 01, 2021 at 11:52:48AM -0800, Biswapriyo Nath wrote:
> I have sent a patch in upstream mingw-w64 mailing list to add those function definitions here https://sourceforge.net/p/mingw-w64/mailman/message/37394322/. For a quick fix, you can apply that patch file to your current msys2/mingw64 setup with `patch -p1 -i <patch-file>` command.
> 

Looks good; thanks.

-corey

**Comment by Biswa96** [comment]
The patch is applied in upstream in this commit https://sourceforge.net/p/mingw-w64/mingw-w64/ci/4fc52607b006d13f28ee563da6dc472903c8a0ec/. As a quick workaround, the patch file can be applied in current msys2/mingw64 setup.

**Comment by lazka** [comment]
Fixed via #10240
