### ISSUE TITLE
[ucrt] Unable to call some gcc components outside the environment, due to libraries not found

### ISSUE THREAD

**Issue by ZeroAurora** [msys2/MINGW-packages#10262]
I tried to use gcc (targeting ucrt) with the Nim language, which requires a CC to work. I modified the config file to make it use `/ucrt64/bin/gcc` outside msys2 but unfortunately it didn't work. I also tried to directly call gcc against a small C source file and it didn't work as well.
By reading verbose logs (sorry for my not saving them), I noticed that gcc exited when calling **cc1**, which **shouted for lots of dlls** and turned out unable to run outside msys2. 
These problems don't exist in mingw64.
I can provide more information if needed (but may delay).

**Comment by MehdiChinoune** [comment]
From where are trying to call gcc?
You have to add `/ucrt64/bin/` (absolute path) to your PATH. so gcc could find the dlls.

**Comment by ZeroAurora** [comment]
> From where are trying to call gcc? You have to add `/ucrt64/bin/` (absolute path) to your PATH. so gcc could find the dlls.

From cmd. gcc itself didn't crash but cc1 did.

**Comment by jeremyd2019** [comment]
cc1.exe is not in `/ucrt64/bin`, so it does not benefit from Windows' default behavior of searching in the same directory as the exe for dlls.  Therefore, you have to add `cygpath -w /ucrt64/bin` to your `PATH`.

**Comment by ZeroAurora** [comment]
Thanks for explanation! But why in mingw64 environment it just works?

**Comment by ZeroAurora** [comment]
I still don't understand why manually invoking cc1 gives the same result (under ucrt it doesn't work and in mingw64 it does).

**Comment by jeremyd2019** [comment]
I don't know - it should have the same behavior in mingw64 as in ucrt64.  Maybe /mingw64/bin is already in your path?  That would cause ucrt64's cc1.exe to actually crash, rather than simply fail to start due to missing DLLs.

**Comment by ZeroAurora** [comment]
No, I did remove it from path and it behaved the same.

**Comment by ZeroAurora** [comment]
I would reinstall ucrt toolchain and have a try again.

**Comment by MehdiChinoune** [comment]
What is the output of `echo %PATH%` (or `$Env:PATH`)?

**Comment by ZeroAurora** [comment]
It's... quite weird. After reinstallation it works as fine as before.
I thought I had removed /mingw64/bin from path but Windows seems not applying it until logging out.
Sorry for inconvinience and thank you for patiently answering me!
