### ISSUE TITLE
GDB 11.1 issue with QtCreator

### ISSUE THREAD

**Issue by Alexpux** [msys2/MINGW-packages#10279]
QtCreator fail to start debugger:
1. If qt5-translations package installed then when you run executable for debugging it show error that cant find libraries. I see in runned executable environment duplicate PATH variable:
![gdb broken](https://user-images.githubusercontent.com/1898153/144837365-70363b92-b5be-4fee-89b3-a35605480bfd.png)
2. If no qt6-translations package installed starting debugging session just crash.

**Comment by Alexpux** [comment]
This is seems problem of GDB itself. Downgrading GDB from 11.1 to 10.2 fix the issue

**Comment by MehdiChinoune** [comment]
Maybe It's fixed with 6.0.1 https://code.qt.io/cgit/qt-creator/qt-creator.git/tree/dist/changes-6.0.1.md?h=6.0#n45

**Comment by Alexpux** [comment]
Maybe, will test when new qtcreator arrive

**Comment by Alexpux** [comment]
QtCreator 6.0.1 fix issue
