### ISSUE TITLE
[gcc] - Antivirus Notification

### ISSUE THREAD

**Issue by rnicolas** [msys2/MINGW-packages#10301]
After installing mingw-w64-x86_64-gcc I get a notification about a virus. After some checks, the antivirus is removing cc1.exe, cc1plus.exe, and lto1.exe, making gcc unusable.

![image](https://user-images.githubusercontent.com/6086463/145450892-d2ea5196-c6c6-4e13-9318-583a9b406da1.png)

Everytime I reinstall the package, those files are removed. And I get this message during the installation:

![image](https://user-images.githubusercontent.com/6086463/145451272-966be333-f1be-4894-a607-1e89a2c9a37b.png)

**Comment by dr-scsi** [comment]
See report #10295.

**Comment by lazka** [comment]
duplicate
