### ISSUE TITLE
Attempting to manually build ZLib with GCC 11.2.0 results in configure error

### ISSUE THREAD

**Issue by brisingraerowing** [msys2/MINGW-packages#10311]
(I'm building manually as I'm making some statically linked utility programs)

When running Zlib's configure script with GCC 11.2.0, I get the following error:

```text
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
```

I'm not exactly sure what this means, or how to fix it.

**Comment by Biswa96** [comment]
Try to import the patches from here https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-zlib. Also the configure command has some intricacies in PKGBUILD file.

**Comment by BrisingrAerowing** [comment]
I already applied the patches, and I copy-pasted the command from the PKGBUILD (and changed the --shared to --static).

**Comment by brisingraerowing** [comment]
I forgot about this. The issue was that the compiler wasn't on the path, and ZLib's configure is a bit stupid about errors.

**Comment by brisingraerowing** [comment]
And now it's happening again. GCC returns with exit code 1, but the -pass-exit-codes option returns 190. I have no idea what 190 could mean or what program it comes from.

**Comment by Biswa96** [comment]
zlib had been updated recently in this commit https://github.com/msys2/MINGW-packages/commit/3d5f68df62da887010ed870bb5a44ddd69ae976e. There could be some issue in your setup/system.

**Comment by brisingraerowing** [comment]
I'm going to fully kill and recreate my setup.

**Comment by brisingraerowing** [comment]
Well this is a rather stupid error. I had an extra / at the start of the PATH segment for the compiler, which was breaking things.
