### ISSUE TITLE
Latest ncurses update broke linking using pkg-config

### ISSUE THREAD

**Issue by shermp** [msys2/MINGW-packages#10312]
The latest ncurses update (#10285) seems to have broken linking when using pkg-config. 

Minimal test program (from https://tldp.org/HOWTO/NCURSES-Programming-HOWTO/helloworld.html):

```c
#include <ncurses.h>

int main()
{	
	initscr();			/* Start curses mode 		  */
	printw("Hello World !!!");	/* Print Hello World		  */
	refresh();			/* Print it on to the real screen */
	getch();			/* Wait for user input */
	endwin();			/* End curses mode		  */

	return 0;
}
```

Compile with:
```sh
gcc $(pkg-config ncursesw --cflags) ncurses.c -o ncurses-test $(pkg-config ncursesw --libs)
```

Results in the following output
```
$ gcc $(pkg-config ncursesw --cflags) ncurses.c -o ncurses-test $(pkg-config ncursesw --libs)
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccCrSAYo.o:ncurses.c:(.text+0x10): undefined reference to `__imp_initscr'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccCrSAYo.o:ncurses.c:(.text+0x23): undefined reference to `__imp_printw'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccCrSAYo.o:ncurses.c:(.text+0x2c): undefined reference to `__imp_stdscr'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccCrSAYo.o:ncurses.c:(.text+0x39): undefined reference to `__imp_wrefresh'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccCrSAYo.o:ncurses.c:(.text+0x42): undefined reference to `__imp_stdscr'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccCrSAYo.o:ncurses.c:(.text+0x4f): undefined reference to `__imp_wgetch'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccCrSAYo.o:ncurses.c:(.text+0x58): undefined reference to `__imp_endwin'
collect2.exe: error: ld returned 1 exit status
```

The issue was first noticed when the msys2 CI builds of [dosbox-staging](https://github.com/dosbox-staging/dosbox-staging) started failing.

**Comment by jeremyd2019** [comment]
It looks like the package only includes a static libncurses, but the headers default to trying to dllimport it.  ncurses_dll.h seems to have changed between the versions, no longer defining NCURSES_STATIC

**Comment by naveen521kk** [comment]
This broke python build https://github.com/msys2-contrib/cpython-mingw/runs/4492454357?check_suite_focus=true#step:5:1428

**Comment by lazka** [comment]
https://github.com/mirror/ncurses/commit/04d942c3d98cf0a929c6afb17be8c10d4ae39af0

**Comment by lazka** [comment]
We could add back the define for now.

In the long run maybe look into shared builds and defining `Cflags.private: -DNCURSES_STATIC` in the .pc file?

**Comment by lazka** [comment]
Fix is in the repo

**Comment by shermp** [comment]
Confirmed working again. Thank you!

**Comment by lazka** [comment]
just a little follow-up and heads-up: #11586 enables shared builds for ncurses. In theory this shouldn't change anything besides switching the default to shared linking. At least Python is happy with that..

If there are any ncurses related issues, please let me know.

**Comment by zhguyu** [comment]
I don't know if the problem is related, but when I try to build LAME with the latest ncurses the following error occurs:

'''
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -Wall -pipe -O3 -DNDEBUG -ffast-math -flto      -s -all-static -o lame.exe lame_main.o main.o brhist.o console.o get_audio.o lametime.o parse.o timestatus.o ../lameres.o ../libmp3lame/libmp3lame.la -lncurses  -liconv -lm
libtool: link: gcc -Wall -pipe -O3 -DNDEBUG -ffast-math -flto -s -static -o lame.exe lame_main.o main.o brhist.o console.o get_audio.o lametime.o parse.o timestatus.o ../lameres.o  ../libmp3lame/.libs/libmp3lame.a -lncurses -liconv
lto-wrapper.exe: warning: using serial compilation of 4 LTRANS jobs
lto-wrapper.exe: note: see the '-flto' option documentation for more information
D:/MSYS2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\MSYS2\tmp\ccCRcXtL.ltrans2.ltrans.o:<artificial>:(.text+0x968e): undefined reference to `__imp_tgetstr'
D:/MSYS2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\MSYS2\tmp\ccCRcXtL.ltrans2.ltrans.o:<artificial>:(.text+0xd7da): undefined reference to `__imp_tgetent'
D:/MSYS2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\MSYS2\tmp\ccCRcXtL.ltrans2.ltrans.o:<artificial>:(.text+0xd7f0): undefined reference to `__imp_tgetnum'
collect2.exe: error: ld returned 1 exit status
'''

**Comment by Biswa96** [comment]
Please provide the necessary steps to reproduce the issue.

**Comment by zhguyu** [comment]
Upon a fresh MSYS2 install, the following packages/groups were installed:

MSYS2: base-devel automake autoconf libtool git subversion
MinGW64: mingw-w64-x86_64-toolchain mingw-w64-x86_64-nasm

The following commands were executed (in a script I wrote myself. It worked in January this year.)

```
rm -rf lame
svn checkout https://svn.code.sf.net/p/lame/svn/trunk/lame lame
cd lame
autoreconf -Wnone
# Assembly code is for i386 only, --enable-nasm will be ignored for x86_64 target
CFLAGS="-O3 -DNDEBUG -ffast-math -flto" \
    ./configure --disable-shared \
                --enable-static \
                --enable-nasm \
                --disable-decoder \
                --disable-rpath \
                --disable-analyzer-hooks
# The GNU configure and makefile won't link the Windows resources into the final executable
# Thus we manually compile the .rc resource file and add it to the linking stage
libtool --tag=RC --mode=compile windres --target=pe-x86-64 -o lameres.lo libmp3lame/lame.rc
sed -i 's|timestatus.$(OBJEXT)|timestatus.$(OBJEXT) ../lameres.$(OBJEXT)|g' frontend/Makefile
# To statically link the executable, with libtool
sed -i 's|LDFLAGS =   -static |LDFLAGS = -s -all-static|g' frontend/Makefile
make
```
The error quoted in my last comment occurred.

**Comment by Biswa96** [comment]
> The following commands were executed (in a script I wrote myself. It worked in January this year.)

It previously worked before because static linking was default back then. But from this commit https://github.com/msys2/MINGW-packages/commit/c1625c546c71ebe8110ab402092b7b7a9e7ef88f the static linking flag was added in pkgconfig file.

**Comment by hlittler** [comment]
For MSYS2 you need to link the library ncurses  (-lncurses) as STATIC.

gcc hello.c  -o hello.exe  -lncurses -DNCURSES_STATIC

**Comment by hlittler** [comment]
Also

#include  <ncurses/ncurses.h>

**Comment by MarkOates** [comment]
Also note!

If you are compiling your program and have multiple objects that you are building in isolation (e.g. `myobj1.o`, `myobj2.o`, you must also define the flag (`-DNCURSES_STATIC`) for each of those build stages as well.

I was attempting to compile the objects separately and only at the final link stage added `-DNCURSES_STATIC` and the issue would still appear.

**Comment by ProxyPlayerHD** [comment]
this issue still exists in the newest version of ncurses that MSYS2 installs (mingw-w64-x86_64-ncurses v6.4.20231217-1).

though thanks for explaining out a "temporary" fix!
adding `#define NCURSES_STATIC` before including the ncurses header file resolves the issue.

**Comment by bardware** [comment]
I tried to build lame and got several errors. One error, eventually, went away, when I started with a certain configure calll in a revision from the past, I got from SVN

`./configure CPPFLAGS="-DNCURSES_STATIC"`
