### ISSUE TITLE
g++ is broken in gcc 11.2.0-4

### ISSUE THREAD

**Issue by OliverSCE** [msys2/MINGW-packages#10313]
$ gcc main.cpp -o main.exe
gcc.exe: fatal error: cannot execute 'cc1plus': CreateProcess: No such file or directory
compilation terminated.

Do I do something wrong, or is this an knwon issue?

Oliver

**Comment by mati865** [comment]
It's an issue with Windows Defender, see here: https://github.com/msys2/MINGW-packages/issues/10295

**Comment by OliverSCE** [comment]
Ah, thanks. 
I did not recognize by the headlines that his is the quarantine issue.
