### ISSUE TITLE
[curl] libcurl doesn't link correctly to libopenssl

### ISSUE THREAD

**Issue by TheNewJavaman** [msys2/MINGW-packages#10328]
Discovered while investigating an issue with Ktor ([ticket](https://youtrack.jetbrains.com/issue/KTOR-1058)). libcurl links to version 1.1.1 of openssl, although it's only built to support version 3.0.0. This discrepancy results in openssl being unable to load local certificates (ca-bundle.crt). To fix, I built libcurl on master, which does link to the correct openssl version.

Repro example:

```kotlin
import libcurl.*
fun main() {
    val curl = curl_easy_init();
    curl_easy_setopt(curl, CURLOPT_URL, "https://www.myip.com")
    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L)
    curl_easy_perform(curl)
    curl_easy_cleanup(curl)
}
```

```
*   Trying 104.21.23.5:443...
* Connected to www.myip.com (104.21.23.5) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
```

Proof that libcurl is built for openssl 3.0.0:

```kotlin
import kotlinx.cinterop.pointed
import kotlinx.cinterop.toKString
import libcurl.*
fun main() {
    val versionInfo = curl_version_info(CURLversion.CURLVERSION_LAST)?.pointed?.ssl_version?.toKString()
    println(versionInfo)
}
```

```
OpenSSL/3.0.0 (Schannel)
```

Finally, libcurl dll links to wrong openssl:

```bash
$ ldd libcurl-4.dll | grep libssl
```

```
libssl-1_1-x64.dll => /mingw64/bin/libssl-1_1-x64.dll (0x7ff993e00000)
```

**Comment by lazka** [comment]
(openssl) curl gives me this:

```
$ curl -V
curl 7.80.0 (x86_64-w64-mingw32) libcurl/7.80.0 OpenSSL/1.1.1l (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.1 libpsl/0.21.1 (+libidn2/2.3.1) libssh2/1.10.0 nghttp2/1.45.1
Release-Date: 2021-11-10
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM PSL SPNEGO SSL SSPI TLS-SRP zstd
```

which seems fine. Not sure what to look for.

**Comment by TheNewJavaman** [comment]
@lazka Thanks for checking this out. I'm not sure about your curl.exe being version 7.80.0, but the libcurl dll that is shipped through msys/mingw is definitely version 7.78.0. Regardless of curl's version, mingw's next curl release should be built with openssl 3.0.0, which your curl doesn't seem to support.

**Comment by lazka** [comment]
> msys/mingw is definitely version 7.78.0

doesn't look like it: https://packages.msys2.org/search?q=curl

I'm afraid I don't know how to test with kotlin. Maybe someone else has an idea?

> Regardless of curl's version, mingw's next curl release should be built with openssl 3.0.0, which your curl doesn't seem to support.

What do you mean? We don't have openssl 3.0.0 right now, and I doubt curl will require it any time soon as openssl 1.1.1 has 2 years of support left, at least.

**Comment by lazka** [comment]
ok, let us track back a bit: Are you sure you are using MSYS2 at all? :)

**Comment by TheNewJavaman** [comment]
Haha, probably a smart idea. Yes, I'm using MSYS2 MSYS console on Windows 11.

**Comment by Biswa96** [comment]
Both msys and mingw openssl packages are now version 3.x.
