### ISSUE TITLE
netcdf weird build error

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#10324]
CMake Error at liblib/CMakeLists.txt:124 (TARGET_LINK_LIBRARIES):
  The "optimized" argument must be followed by a library.

well there is no optimized flag in that place ?!? :S

**Comment by Biswa96** [comment]
Which version? Source link?

**Comment by revelator** [comment]
4.8.1 from here https://www.unidata.ucar.edu/software/netcdf/ from latest PKGBUILD

**Comment by revelator** [comment]
looks like some cmake changes broke this, but must have been pretty far back since cmake-3.19 is also not able to compile it.

**Comment by Biswa96** [comment]
I can build the mingw-w64-netcdf package as is without any issue. Please provide all the steps to reproduce your issue. Also try to update packages to latest versions.

**Comment by revelator** [comment]
hmm updated the hdf5 and hdf4 packages beforehand, so i doubt it is them.
standard makepkg-mingw -c -i --skippgp --nocheck command used-
