### ISSUE TITLE
[munt-mt32emu] needs update to version 2.5.3

### ISSUE THREAD

**Issue by DominusExult** [msys2/MINGW-packages#10321]
2.5.3 was released in August and AFAICT it just needs a version bump.

**Comment by Biswa96** [comment]
Thank you for reporting this issue. The package is in [update queue] and will be in pacman repository after some days.

[update queue]: https://packages.msys2.org/queue

**Comment by Biswa96** [comment]
The new version of the package is available in pacman repository. Would you like to test it?
