### ISSUE TITLE
PySide6 support?

### ISSUE THREAD

**Issue by ubitux** [msys2/MINGW-packages#10327]
Can we expect PySide6 support to land in MinGW packages in the future?

**Comment by MehdiChinoune** [comment]
Which environment (mingw64, ucrt64 or clang64) are working on?

**Comment by ubitux** [comment]
MinGW64; PySide2 is already available there so we are using that, but we want to bump to PySide6 in our project. We currently can't because it's not yet packaged (we were considering dropping support for MinGW because of this).

**Comment by MehdiChinoune** [comment]
I have asked because I have packaged it for CLANG64 (fails to build with UCRT64)

**Comment by MehdiChinoune** [comment]
I was able to build pyside6 for both CLANG64 and UCRT64 (with some hacks), I have uploaded them to https://sourceforge.net/projects/mingw-updates/files

**Comment by mati865** [comment]
What was the error in MINGW64 or UCRT64?

**Comment by MehdiChinoune** [comment]
> What was the error in MINGW64 or UCRT64?

#10358
