### ISSUE TITLE
[qt5-pkgs] QSqlite driver not functioning

### ISSUE THREAD

**Issue by CarVac** [msys2/MINGW-packages#10343]
I've been using MSYS2's Qt5 package for building my program Filmulator for a while and sometime between 2021-07-07 and 2021-10-29 the Windows builds stopped functioning, saying that the `QSQLITE driver not loaded` despite the list of drivers still including QSQLITE in it.

Everything online told me that I had to have the DLL installed in a `sqldrivers` directory adjacent to the executable, and it was, but today I finally figured out that the `qsqlite.dll` file in the later builds is actually significantly smaller than those from earlier builds.

The one in the latest version is 155 kB instead of 1349 kB.

When I take the larger, older `qsqlite.dll` file from my older builds and use it to replace the newer version's `qsqlite.dll`, the program works.

Why might this be? What caused the file to change?

You can see versions that work and don't work here: https://discuss.pixls.us/t/filmulator-nightly-builds-now-for-windows-and-linux/12838

Version 0.11.2rc4 is the last working Windows build, and everything since then has been nonfunctional for this reason, so you can check with those if necessary. Of note is that the size of the entire installer decreased dramatically at the same time, so it's probably not just `qsqlite.dll` that shrunk...

**Comment by MehdiChinoune** [comment]
@CarVac Do you still encounter this issue?
