### ISSUE TITLE
[RFC] More GTK3 updates (VCS package)

### ISSUE THREAD

**Issue by lb90** [msys2/MINGW-packages#10344]
I would like to ask about making GTK3 a VCS package, i.e. pointing to git tips instead of released tarballs, much like Arch Linux does since a long time.

GTK3 only accepts bug fixes today, as development has shifted towards GTK4. In addition to that the latest GTK3 release is from about 6 month ago. It may makes sense then to update GTK3 more often by downloading git snapshots.

Any comment is welcome! 🙂

**Comment by lazka** [comment]
Sounds good in this case.

**Comment by Biswa96** [comment]
Are there any programs which bundle gtk3 with their released binaires?

**Comment by lb90** [comment]
Yes, most projects that I know use MSYS2 to author their installation bundles.
