### ISSUE TITLE
Qt6: Some symbols were not dll-exported by gcc

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#10358]
While I was trying to package pyside6 I discovered that GCC does not export some symbols declared as `static constexpr`.
https://invent.kde.org/qt/qt/qtbase/-/blob/6.2.1/src/network/kernel/qhostaddress.h#L99
https://invent.kde.org/qt/qt/qtmultimedia/-/blob/6.2.1/src/multimedia/video/qvideoframeformat.h#L103
https://invent.kde.org/qt/qt/qtmultimedia/-/blob/6.2.1/src/multimedia/qmediametadata.h#L96

UCRT64:
```
$ nm /ucrt64/bin/Qt6Network.dll | grep UnknownNetworkLayerProtocol

$ nm /ucrt64/bin/Qt6Network.dll | grep AnyIPProtocol

$ nm /ucrt64/bin/Qt6Network.dll | grep IPv4Protocol

$ nm /ucrt64/bin/Qt6Network.dll | grep IPv6Protocol

```
CLANG64:
```
$ nm /clang64/bin/Qt6Network.dll | grep UnknownNetworkLayerProtocol
000000018011463c r .rdata$_ZN12QHostAddress27UnknownNetworkLayerProtocolE
000000018011463c R _ZN12QHostAddress27UnknownNetworkLayerProtocolE

$ nm /clang64/bin/Qt6Network.dll | grep AnyIPProtocol
0000000180114638 r .rdata$_ZN12QHostAddress13AnyIPProtocolE
0000000180114638 R _ZN12QHostAddress13AnyIPProtocolE

$ nm /clang64/bin/Qt6Network.dll | grep IPv4Protocol
0000000180114630 r .rdata$_ZN12QHostAddress12IPv4ProtocolE
0000000180114630 R _ZN12QHostAddress12IPv4ProtocolE

$ nm /clang64/bin/Qt6Network.dll | grep IPv6Protocol
0000000180114634 r .rdata$_ZN12QHostAddress12IPv6ProtocolE
0000000180114634 R _ZN12QHostAddress12IPv6ProtocolE
```
Is it a bug from GCC or from Qt6?
Does someone has an idea how fix this issue? I mean a way to make/force GCC exporting them.

**Comment by mati865** [comment]
If this code uses C++17 those `static constexpr` could be turned into `inline constexpr`. Also could be useful to test if works when building with Clang+BFD or GCC+LLD.

**Comment by MehdiChinoune** [comment]
Minimal reproducer:
dll_constexpr.cpp
```cpp
#include <QObject>

class __declspec(dllexport) empty {
    Q_GADGET
public:
    static constexpr auto constant = 1;
};
```
CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.16)
project( foo CXX )
find_package( Qt6 COMPONENTS Core REQUIRED )
add_library( const SHARED "dll_constexpr.cpp" )
target_link_libraries( const Qt6::Core )
```
UCRT64
```
$ nm libconst.dll | grep constant

```
CLANG64
```
$ nm libconst.dll | grep constant
180003048 r .rdata$_ZN5empty8constantE
180003048 R _ZN5empty8constantE
```

Without Qt declarations nothing get exported.

Getting the preprocessed files:
UCRT64
```cpp
// after 94000 lines

class __attribute__((dllexport)) empty {
    public: static const QMetaObject staticMetaObject; void qt_check_for_QGADGET_macro(); typedef void QtGadgetHelper; private:
# 5 "../../dll_constexpr.cpp"
#pragma GCC diagnostic push
# 5 "../../dll_constexpr.cpp"
   
# 5 "../../dll_constexpr.cpp"
#pragma GCC diagnostic ignored "-Wattributes"
# 5 "../../dll_constexpr.cpp"
    static void qt_static_metacall(QObject *, QMetaObject::Call, int, void **);
# 5 "../../dll_constexpr.cpp"
#pragma GCC diagnostic pop
# 5 "../../dll_constexpr.cpp"
   
public:
    static constexpr auto constant = 1;
};
```
CLANG64
```cpp
after // 74000 lines

class __attribute__((dllexport)) empty {
    public: static const QMetaObject staticMetaObject; void qt_check_for_QGADGET_macro(); typedef void QtGadgetHelper; private:
# 5 "../../dll_constexpr.cpp"
#pragma clang diagnostic push
# 5 "../../dll_constexpr.cpp"
 static void qt_static_metacall(QObject *, QMetaObject::Call, int, void **);
# 5 "../../dll_constexpr.cpp"
#pragma clang diagnostic pop
public:
    static constexpr auto constant = 1;
};
```

**Comment by MehdiChinoune** [comment]
> If this code uses C++17 those `static constexpr` could be turned into `inline constexpr`. Also could be useful to test if works when building with Clang+BFD or GCC+LLD.

I don't think it is related to the linker, as the object file itself doesn't contain the exported symbol
with the above reproducer I get:
UCRT64:
```
$ nm CMakeFiles/const.dir/dll_constexpr.cpp.obj | grep constant

```
CLANG64
```
$ nm CMakeFiles/const.dir/dll_constexpr.cpp.obj | grep constant
00000000 R _ZN5empty8constantE
```
clang doesn't export `constant` with `std=c++14`.

**Comment by MehdiChinoune** [comment]
A workaround is to redeclare these variables as `constexpr type class::variable` outside of the class.
```cpp
class __declspec(dllexport) empty {
public:
    static constexpr auto constant = 1;
};
constexpr int empty::constant;
```

**Comment by jeremyd2019** [comment]
It's been a bit since I was looking at that section of the C++ spec, but I believe that would actually be a definition of the static member, and as such would need to only be in one translation unit, or you'd have the potential for multiple definition errors at link time.

**Comment by jeremyd2019** [comment]
Where things go really sideways is when that class `empty` is a template, which is what I was trying to deal with in kirigami IIRC.

**Comment by Biswa96** [comment]
Little question. Should that symbol be exported from a library? Wouldn't that symbol be resolved from the header file?

**Comment by jeremyd2019** [comment]
It's apparently complicated:
https://en.wikipedia.org/wiki/One_Definition_Rule#Definitions_of_static_const_data_members.  Then throw in the non-standard concept of `dllexport`/`dllimport`...

**Comment by MehdiChinoune** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54483
