### ISSUE TITLE
Add lib2geom package for Inkscape

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#10393]
build seems to default to an external library which we dont supply a package for (lib2geom)
so while it does build it complains about a missing lib2geom.dll.

can be fixed by adding -DWITH_INTERNAL_2GEOM=ON to cmake flags.

**Comment by Biswa96** [comment]
Would it be right to provide lib2geom package?

**Comment by revelator** [comment]
dunno, maybe if requested by other packages ?.

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/1694113479

**Comment by revelator** [comment]
no need i trust it will be ok :)
