### ISSUE TITLE
openexr and openimageio need separate imath package

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#10396]
missing dependency iMath formerly part of openexr needs to be built seperatly now -> https://github.com/AcademySoftwareFoundation/Imath.
fails to find openjpeg2 upstream issue.

**Comment by Biswa96** [comment]
I tried to build IMath in CI. But CLANG64 fails with error ld.lld: error: too many exported symbols (max 65535).

**Comment by revelator** [comment]
looks like it will need a def with clang then.

**Comment by revelator** [comment]
also something to consider namely building it as a static library.
the limit will be tough to work around as it is not imposed by the build utils but is a hard windows limit, maybe use -Wl,--needed with the linker ?.

**Comment by revelator** [comment]
hmm another bug cropped up the git version needs either drand48 or rand_s, had to hack in the drand48 from openbsd.
openvdb also blows up on the new tbb and despite getiing told to use the mingw python it forces use of the /usr/bin/python.exe instead.

**Comment by revelator** [comment]
small fix for imath -> put this in half_perf_test.cpp

```
// neither drand48 nor s_rand exist for mingw-w64 tagets so emulate it.
#ifdef __MINGW32__
#define drand48() (((double)rand())/((double)RAND_MAX))
#endif
```

got it to build now, i still had the older python3.8 which for some reason is none to happy with the msys2 version being higher, had to update all python packages.

**Comment by kmilos** [comment]
> small fix for imath -> put this in half_perf_test.cpp

Seems they [reimplemented drand48() already which should be preferred](https://github.com/AcademySoftwareFoundation/Imath/blob/304288542b6d3d7b4555539a0a1e2dd9da571c53/src/Imath/ImathRandom.cpp)? Have you tried replacing w/ Imath::drand48() instead?

I guess this could also be [reported upstream](https://github.com/AcademySoftwareFoundation/Imath/issues/new/choose)?

**Comment by Biswa96** [comment]
I have already sent a pull request to upstream. It's pending. They have some weird legal mess.

**Comment by Biswa96** [comment]
openexr can be built with imath. But all the dependent packages have to be rebuilt and those are so huge for my tiny old box.

**Comment by Biswa96** [comment]
Last query before adding the package. openexr has many patches which add version number with DLL names. Should I continue those patching? Or keep the default name without version number set by build system?

**Comment by Biswa96** [comment]
Any opinion about the DLL name? ☝️
