### ISSUE TITLE
[mingw-w64-qt5-webchannel] Build with KDE patch collection

### ISSUE THREAD

**Issue by msarehn** [msys2/MINGW-packages#10399]
Like qt5base, qtwebchannel has backported patches that are maintained by KDE: https://invent.kde.org/qt/qt/qtwebchannel/-/tree/kde/5.15

The patches are rather critical. It would be very nice if msys2 would build the packages with the KDE-provided patches, just like it does for qt5base.

**Comment by MehdiChinoune** [comment]
If you use UCRT64 or CLANG64 you can update it from my external repo https://sourceforge.net/projects/mingw-updates/files/

**Comment by msarehn** [comment]
@MehdiChinoune thanks a lot! Unfortunately we're depending on the standard MINGW64 toolchain.
