### ISSUE TITLE
flashrom pkgbuild help?

### ISSUE THREAD

**Issue by mightymos** [msys2/MINGW-packages#10405]
I've attached a starter PKGBUILD file that does complete successfully.
However, I know the build is only (partially) working because I've previously installed libftdi and libusb make dependencies.
Similarly at runtime flashrom.exe requires libusb-1.0.dll, but it isn't found.

On the other hand, I have successfully built from source manually with all dependencies.
And then run exe with real CP210x USB to UART hardware successfully.
So it appears to be my (in)experience with package managing to blame rather than a build problem.

Here are the manual steps for building used previously if that helps any:

```install msys2-x86_64-latest.exe
# in MSYS2 MINGW64 shell

# get latest
pacman -Syu

# gcc, make, etc.
pacman -S --needed base-devel mingw-w64-x86_64-toolchain

# msys2-runtime-devel for librt
pacman -S git msys2-runtime-devel
# for flashrom support of additional hardware (FTDI, etc.)
pacman -S mingw-w64-x86_64-libusb mingw-w64-x86_64-libftdi

cp /usr/lib/librt.a /mingw64/lib/

git clone https://github.com/flashrom/flashrom
cd flashrom
make

# for CP210x based USB to UART chips use zadig-2.7.exe to replace silicon labs driver with WinUSB (libusb)
# try ./flashrom.exe -p developerbox
# mine says no eeprom found because not hooked up to any flash chip (yet)
```

[PKGBUILD.zip](https://github.com/msys2/MINGW-packages/files/7767219/PKGBUILD.zip)

**Comment by mightymos** [comment]
*sigh* already found some typos that would have just added to confusion. Attaching newer starter PKGBUILD:
[PKGBUILD.zip](https://github.com/msys2/MINGW-packages/files/7767379/PKGBUILD.zip)

**Comment by neheb** [comment]
Why not post it on gist.github.com ?

**Comment by mightymos** [comment]
> Why not post it on gist.github.com ?

Done, see here:
https://gist.github.com/mightymos/cdb9e2b44e44ada1bef2e472d5d783e4

**Comment by neheb** [comment]
flashrom has a meson builds. you should really be using that.

pkgrel starts at 1.

prepare() section is unnecessary, unless you're patching something.

**Comment by mightymos** [comment]
> flashrom has a meson build. you should really be using that.
> 
> pkgrel starts at 1.
> 
> prepare() section is unnecessary, unless you're patching something.

Thanks fixed those issues and more. Package is now building with applied patch:
https://gist.github.com/mightymos/c3b80e0fddbcfa1f7925985ffa76a350

Only problem seems to be that flashrom.exe is not found in path.
I'm assuming mingw64/sbin/ is not the correct install location?

**Comment by kmilos** [comment]
Can't you use `meson configure` in the build() step instead of patching these options?

Also, don't need to require `msys2-runtime-devel` - you're not building for msys but for mingw-w64...

And yes, there is no /sbin in the default filesystem, and certainly not on the default $PATH.

**Comment by mightymos** [comment]
> Can't you use `meson configure` in the build() step instead of patching these options?
> 
> Also, don't need to require `msys2-runtime-devel` - you're not building for msys but for mingw-w64...
> 
> And yes, there is no /sbin in the default filesystem, and certainly not on the default $PATH.

Fixed what I could, I tried:
meson configure -Dpciutils=false -Dconfig_linux_mtd=false -Dconfig_linux_spi=false

However, it doesn't seem to work even though meson configure lists all those as valid boolean options?

https://gist.github.com/mightymos/fd0033d55d5fb53ea83464e75174cffb

**Comment by heljkon** [comment]
Using your PKGBUILD I was able to build locally for MINGW64 using https://github.com/heljkon/MINGW-packages/commit/b853ef8c83b9658f77a9c6e5c087b06f391bcb7e

Feel free to copy it from https://github.com/heljkon/MINGW-packages/commits/mingw-w64-flashrom-1.2-1 to your repository and to create a PullRequest for it after fixing your fixmes.

**Comment by mightymos** [comment]
> Based on your PKGBUILD I was able to build locally for MINGW64 using enhanced [PKGBUILD](https://github.com/heljkon/MINGW-packages/commit/b853ef8c83b9658f77a9c6e5c087b06f391bcb7e)
> 
> Feel free to copy it from https://github.com/heljkon/MINGW-packages/commits/mingw-w64-flashrom-1.2-1 to your repository and to create a PullRequest for it after fixing your fixmes.

I could use another hint...I think sbin install directory is specified on lines 1548 and 1550 of the Makefile.
I don't see any mention of sbin in meson related files though could have missed something.
I'm not sure if I should patch this file to change to a standard MSYS2 bin location or somehow override when calling meson install in PKGBUILD?

**Comment by heljkon** [comment]
In my opinion it it perfectly OK to move it to {MINGW_PREFIX}/bin manually in package() if there is no way to configure it in meson (I did not check). For example take a look at mingw-w64-qemu/PKGBUILD: much moving is done afterwards. I don't think a patch would be reasonable.

In general I would like to propose that you check other PKGBUILD-files in https://github.com/msys2/MINGW-packages for ideas how to handle problems.

Take a few minutes to read https://www.msys2.org/wiki/Creating-Packages/ as well, if you haven't done yet.

**Comment by obskyr** [comment]
I can't seem to get this to run – it built just fine using `MINGW_ARCH=mingw32 makepkg-mingw -sCLf`, but when I attempt to run it, it only gives me the following error:

```
~/MINGW-packages/mingw-w64-flashrom
$ pkg/mingw-w64-i686-flashrom/mingw32/bin/flashrom.exe
C:/msys64/home/Username/MINGW-packages/mingw-w64-flashrom/pkg/mingw-w64-i686-flashrom/mingw32/bin/flashrom.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

Manually copying `libftdi1.dll` and `libusb-1.0.dll` into the same directory as the EXE doesn't help either. Does anyone have any idea as to how I might fix this?

**Comment by Biswa96** [comment]
I think the package is missing libwinpthread dependency. You can check the missing DLL with ntdll tool. Just download `$MINGW_PACKAGE_PREFIX-ntldd`. Then run `ntldd path/to/flashrom.exe`.

**Comment by obskyr** [comment]
@Biswa96 OH THANK THE HOLY MOLY! Thanks a ton. Turns out, my *main* issue was that I was running in plain MSYS2 – I didn't realize I had to run a different shell (MinGW x64). However, your advice helped me greatly in getting the program to run on Windows outside of MSYS2, so it'll run for people who don't have MSYS2 installed.

**Comment by Biswa96** [comment]
flashrom package has been added many days ago. The main topic of this issue has been resolved. Feel free to create new issue if this or any package has any problem. Closing... 👋

**Comment by obskyr** [comment]
For posterity, here's a `PKGBUILD` that builds the latest commit – the number of Meson options required has grown considerably. When it comes time to update to v1.3, perhaps it'll help as reference! Hopefully, though, the build flow will have been simplified by then – see flashrom/flashrom#245 for progress on that.

```bash
# Maintainer: Jonathan Armstrong <jda2158@gmail.com>

commit=b9e8b898c03a0ee5a6d54ab9f1b2910fe75559ea

_realname=flashrom
pkgbase=mingw-w64-${_realname}
pkgname=("${MINGW_PACKAGE_PREFIX}-${_realname}")
pkgver=1.2
pkgrel=1
pkgdesc='Utility for detecting, reading, writing, verifying and erasing flash chips (mingw-w64)'
arch=('any')
mingw_arch=('mingw32' 'mingw64' 'ucrt64' 'clang64' 'clang32')
url='https://github.com/flashrom/flashrom'
license=('GPL2')
depends=("${MINGW_PACKAGE_PREFIX}-libftdi"
         "${MINGW_PACKAGE_PREFIX}-libusb"
         "${MINGW_PACKAGE_PREFIX}-libwinpthread-git")
makedepends=("${MINGW_PACKAGE_PREFIX}-meson"
             "${MINGW_PACKAGE_PREFIX}-cc"
             "${MINGW_PACKAGE_PREFIX}-pkg-config")
source=("https://github.com/flashrom/flashrom/archive/${commit}.tar.gz"
        "https://raw.githubusercontent.com/flashrom/flashrom/${commit}/util/getrevision.sh")
sha256sums=('SKIP' 'SKIP')

prepare() {
  # To fix a bug in the current meson.build. As soon as the patch below has been merged, this won't be needed.
  # https://review.coreboot.org/c/flashrom/+/62061
  mv getrevision.sh ${_realname}-${commit}/util/

  # Required for `flashrom --version` to report correctly when compiled directly from the git repo.
  printf "VERSION = v${pkgver}-$(expr substr ${commit} 1 7);\nMAN_DATE = $(date -u -r ${_realname}-${commit}/flashrom.8.tmpl +%Y-%m-%dT%H:%M:%SZ);" > ${_realname}-${commit}/versioninfo.inc
}

build() {
  mkdir -p build-${MSYSTEM} && cd build-${MSYSTEM}

  MSYS2_ARG_CONV_EXCL="--prefix=" \
    meson \
      -Dpciutils=false \
      -Dconfig_atahpt=false \
      -Dconfig_atapromise=false \
      -Dconfig_atavia=false \
      -Dconfig_drkaiser=false \
      -Dconfig_gfxnvidia=false \
      -Dconfig_internal=false \
      -Dconfig_it8212=false \
      -Dconfig_linux_mtd=false \
      -Dconfig_linux_spi=false \
      -Dconfig_lspcon_i2c_spi=false \
      -Dconfig_mediatek_i2c_spi=false \
      -Dconfig_nic3com=false \
      -Dconfig_nicintel=false \
      -Dconfig_nicintel_eeprom=false \
      -Dconfig_nicintel_spi=false \
      -Dconfig_nicnatsemi=false \
      -Dconfig_nicrealtek=false \
      -Dconfig_ogp_spi=false \
      -Dconfig_rayer_spi=false \
      -Dconfig_realtek_mst_i2c_spi=false \
      -Dconfig_satamv=false \
      -Dconfig_satasii=false \
      --prefix="${MINGW_PREFIX}" \
      --wrap-mode=nodownload \
      --auto-features=enabled \
      --buildtype=plain \
      ../${_realname}-${commit}
  
  meson compile
}

check() {
  cd "${srcdir}/build-${MSYSTEM}"

  # TODO: check once master branch gets numbered release (i.e., tests/)
  meson test
}

package() {
  cd "${srcdir}/build-${MSYSTEM}"

  DESTDIR="${pkgdir}" meson install

  # To enable usage relative paths for next operations
  cd "${pkgdir}"/${MINGW_PREFIX}

  # Move content to standard dirs
  mv -v sbin/flashrom.exe bin/

  install -Dm644 "${srcdir}/${_realname}-${commit}/COPYING" "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}/COPYING"

  # echo replace USB-UART drivers (if needed) with WinUSB (libusb) using zadig [https://zadig.akeo.ie/]
}
```

**Comment by Biswa96** [comment]
Latest flashrom requires pciutils. Without it meson fails like this:

```
../meson.build:178:2: ERROR: Problem encountered: pciutils is disabled but one or more enabled programmer requires PCI access
```

The change was added here https://github.com/flashrom/flashrom/commit/748943d77460ecfa49d5d1a85a5f58bf99b22f3f

**Comment by obskyr** [comment]
@Biswa96 Hmm. As I understood. it, PCI isn't actually supported on Windows – though I can't find a source on that, so perhaps it's a misapprehension. According to the Flashrom wiki, however, *internal* programming does not work on Windows, and a few others on the list in that issue are definitely not supported on Windows – so at the very least, some of the `-Doption_…` flags in the PKGBUILD need to be present.

**Comment by mightymos** [comment]
> @Biswa96 Hmm. As I understood. it, PCI isn't actually supported on Windows – though I can't find a source on that, so perhaps it's a misapprehension. According to the Flashrom wiki, however, _internal_ programming does not work on Windows, and a few others on the list in that issue are definitely not supported on Windows – so at the very least, some of the `-Doption_…` flags in the PKGBUILD need to be present.

https://github.com/libv/flashrom/blob/master/README
"PCI-based programmers (internal etc.) are not supported on Windows."

**Comment by obskyr** [comment]
Ah, there it is! Thank you. The only other candidate for “potentially supported” is the I²C programmers – though if I recall, I looked into Flashrom's code for that and found it to be OS-specific. If that's the case, *all* of these flags do indeed need to be present.
