### ISSUE TITLE
GDB TUI broken

### ISSUE THREAD

**Issue by GitMensch** [msys2/MINGW-packages#10434]
I have no clue since when this occurs or if this was never working, I guess so, because it is already referenced in #1744...

`gdb ./myconsole.exe -x start` --> works fine
`gdb ./myconsole.exe -tui -ex start` --> results in "During startup program exited with code 0xc0000142."

As also analyzed in the referenced issue by @dimztimz this is related to the console handles. The only thing that looks bad is the following, seeing this issue persists over 5 years later:

> a new feature that is buggy in a very specific case and that will be sorted out in the future

Maybe the future is now :-)

The work around, as mentioned by him still works:

     gdb ./myconsole.exe -tui -ex 'set new-console on' -ex start

If we can't get that to work reliably I suggest we add a patch to always enable new-console when in tui-mode.

Note: if we do it the other way around it _does_ work:

     gdb ./myconsole.exe -ex start -ex 'tui enable'
     
(in this case you "obviously" need to temporarily disable the tui to see the display because that doesn't happen on the same console)

**Comment by ssbssa** [comment]
If ncurses is updated to [the latest patch](https://lists.gnu.org/archive/html/bug-ncurses/2023-02/msg00005.html), then this bug should be fixed (the `CreateConsoleScreenBuffer()` call was the problem).

**Comment by Biswa96** [comment]
Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/4156876469
