### ISSUE TITLE
undefined references  when linking with libSDL2main.a [mingw-w64-x86_64-SDL2 2.0.18-2]

### ISSUE THREAD

**Issue by Guigz2000** [msys2/MINGW-packages#10459]
Hi,

I try to compile my project with mingw64 on to use SDL2.

MSYS2 installed packages:
mingw64/mingw-w64-x86_64-SDL2 2.0.18-2
mingw64/mingw-w64-x86_64-SDL2_gfx 1.0.4-1 

The whole project is using opengl and was previously using FreeGlut successfully (guess it's not related to my project which properly compile my program )
Dear Imgui is used for the interface and I'm using the unmodified SDL2 interface provided to ensure the compilation settings are ok.

Compilation of the project do pass but linking fails with:

>g++ -o (lot of object files)  -limm32 -lstdc++ -lopengl32 -lglu32 -lfreeglut -lwsock32 -lcrypto -lssl -lcurl -lmincore -lshlwapi -luuid -lmingw32 -lSDL2 -lSDL2main 
>
>E:/Software/Eclipse-Mingw/AddonTools/Toolchains/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/Software/Eclipse-Mingw/AddonTools/Toolchains/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0x94): undefined reference to `SDL_strlen'
> 
> E:/Software/Eclipse-Mingw/AddonTools/Toolchains/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/Software/Eclipse-Mingw/AddonTools/Toolchains/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0xe1): undefined reference to `SDL_wcslen'
> 
> E:/Software/Eclipse-Mingw/AddonTools/Toolchains/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/Software/Eclipse-Mingw/AddonTools/Toolchains/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0xf5): undefined reference to `SDL_iconv_string'
> 
> E:/Software/Eclipse-Mingw/AddonTools/Toolchains/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/Software/Eclipse-Mingw/AddonTools/Toolchains/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0x11b): undefined reference to `SDL_ShowSimpleMessageBox'
> 
> E:/Software/Eclipse-Mingw/AddonTools/Toolchains/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/Software/Eclipse-Mingw/AddonTools/Toolchains/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0x151): undefined reference to `SDL_SetMainReady'
> 

I tried both with libSDL2.a and libSDL2.dll.a and got the same result

Those functions are never called in my code.

I'm not a specialist of compilation.
It seems the functions are called in "SDL_windows_main.c" located in "libSDL2main.a" and is a dependency issue in the SDL2 packages.
Looks to me that the those functions weren't properly included in the libraries or linked when building "libSDL2main.a" or "libSDL2.a"

**Comment by Guigz2000** [comment]
Dirty workaround:

I created a simple c file I added to my project with the missing functions source I found in SDL sources.
The project now compile and properly launch.

Dirty...,Especially since last function do switch a static variable of the SDL.c module...
It's working with it.

> 
> #include <stdint.h>
> #include <SDL2/SDL.h>
> 
> size_t SDL_wcslen(const wchar_t *string)
> {
>     size_t len = 0;
>     while (*string++)
>     {
>         ++len;
>     }
>     return len;
> }
> 
> size_t SDL_strlen(const char *string)
> {
>     size_t len = 0;
>     while (*string++)
>     {
>         ++len;
>     }
>     return len;
> }
> 
> char* SDL_iconv_string(const char *tocode, const char *fromcode, const char *inbuf, size_t inbytesleft)
> {
>     SDL_iconv_t cd;
>     char *string;
>     size_t stringsize;
>     char *outbuf;
>     size_t outbytesleft;
>     size_t retCode = 0;
> 
>     cd = SDL_iconv_open(tocode, fromcode);
>     if (cd == (SDL_iconv_t) -1)
>     {
>         /* See if we can recover here (fixes iconv on Solaris 11) */
>         if (!tocode || !*tocode)
>         {
>             tocode = "UTF-8";
>         }
>         if (!fromcode || !*fromcode)
>         {
>             fromcode = "UTF-8";
>         }
>         cd = SDL_iconv_open(tocode, fromcode);
>     }
>     if (cd == (SDL_iconv_t) -1)
>     {
>         return NULL;
>     }
> 
>     stringsize = inbytesleft > 4 ? inbytesleft : 4;
>     string = (char*) SDL_malloc(stringsize);
>     if (!string)
>     {
>         SDL_iconv_close(cd);
>         return NULL;
>     }
>     outbuf = string;
>     outbytesleft = stringsize;
>     SDL_memset(outbuf, 0, 4);
> 
>     while (inbytesleft > 0)
>     {
>         const size_t oldinbytesleft = inbytesleft;
>         retCode = SDL_iconv(cd, &inbuf, &inbytesleft, &outbuf, &outbytesleft);
>         switch (retCode)
>         {
>             case SDL_ICONV_E2BIG :
>             {
>                 char *oldstring = string;
>                 stringsize *= 2;
>                 string = (char*) SDL_realloc(string, stringsize);
>                 if (!string)
>                 {
>                     SDL_iconv_close(cd);
>                     return NULL;
>                 }
>                 outbuf = string + (outbuf - oldstring);
>                 outbytesleft = stringsize - (outbuf - string);
>                 SDL_memset(outbuf, 0, 4);
>             }
>                 break;
>             case SDL_ICONV_EILSEQ :
>                 /* Try skipping some input data - not perfect, but... */
>                 ++inbuf;
>                 --inbytesleft;
>                 break;
>             case SDL_ICONV_EINVAL :
>             case SDL_ICONV_ERROR :
>                 /* We can't continue... */
>                 inbytesleft = 0;
>                 break;
>         }
>         /* Avoid infinite loops when nothing gets converted */
>         if (oldinbytesleft == inbytesleft)
>         {
>             break;
>         }
>     }
>     SDL_iconv_close(cd);
> 
>     return string;
> }
> 
> int SDL_ShowSimpleMessageBox(Uint32 flags, const char *title, const char *message, SDL_Window *window)
> {
> #ifdef __EMSCRIPTEN__
>     /* !!! FIXME: propose a browser API for this, get this #ifdef out of here? */
>     /* Web browsers don't (currently) have an API for a custom message box
>        that can block, but for the most common case (SDL_ShowSimpleMessageBox),
>        we can use the standard Javascript alert() function. */
>     if (!title) title = "";
>     if (!message) message = "";
>     EM_ASM_({
>         alert(UTF8ToString($0) + "\n\n" + UTF8ToString($1));
>     }, title, message);
>     return 0;
> #else
>     SDL_MessageBoxData data;
>     SDL_MessageBoxButtonData button;
> 
>     SDL_zero(data);
>     data.flags = flags;
>     data.title = title;
>     data.message = message;
>     data.numbuttons = 1;
>     data.buttons = &button;
>     data.window = window;
> 
>     SDL_zero(button);
>     button.flags |= SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT;
>     button.flags |= SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT;
>     button.text = "OK";
> 
>     return SDL_ShowMessageBox(&data, NULL);
> #endif
> }
> 
> void SDL_SetMainReady(void)
> {
>    // SDL_MainIsReady = SDL_TRUE;
> }

**Comment by Biswa96** [comment]
I think the linking order is wrong in your given command. An easy solution would be to use pkg-config. Here are some examples:

* For dynamic linking: 
 
```
gcc -Wall `pkg-config -cflags SDL2` test.c `pkg-config -libs SDL2`
```

* For static linking:

```
gcc -static -Wall `pkg-config -static -cflags SDL2` test.c `pkg-config -static -libs SDL2`
```

**Comment by Guigz2000** [comment]
Ok..

I declared SDL2main library before SDL2 and it compile properly without my workaround file.(should have tried iut but sometimes you just can't see what's under your nose)
Thanks for the guidance 

Regards

**Comment by iyadahmed** [comment]
> Ok..
> 
> I declared SDL2main library before SDL2 and it compile properly without my workaround file.(should have tried it but sometimes you just can't see what's under your nose) Thanks for the guidance
> 
> Regards

worked for me too

**Comment by Backslash0001** [comment]
> Ok..
> 
> I declared SDL2main library before SDL2 and it compile properly without my workaround file.(should have tried it but sometimes you just can't see what's under your nose) Thanks for the guidance
> 
> Regards

Works for me too.
