### ISSUE TITLE
[mingw-w64-file] file and libmagic stuck at version 5.39

### ISSUE THREAD

**Issue by lz-dc** [msys2/MINGW-packages#10472]
mingw-w64-file is still stuck at 5.39, whereas file package is at 5.41.
Manual build fails with following error:

```
magic.c: In function 'file_or_fd':
magic.c:466:23: warning: implicit declaration of function 'fcntl' [-Wimplicit-function-declaration]
  466 |                 (void)fcntl(fd, F_SETFD, FD_CLOEXEC);
      |                       ^~~~~
magic.c:466:23: warning: nested extern declaration of 'fcntl' [-Wnested-externs]
magic.c:466:33: error: 'F_SETFD' undeclared (first use in this function)
  466 |                 (void)fcntl(fd, F_SETFD, FD_CLOEXEC);
      |                                 ^~~~~~~
```

**Comment by 1480c1** [comment]
`fcntl` doesn't exist on windows, so I assume that's where an issue would arise from. You might want to check to see if there's some way around that or see if there's a replacement

**Comment by Biswa96** [comment]
I am not sure if this has any negative effect. The fcntl call can be hidden with `#ifdef __MINGW32__`. Something like this https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-file/0001-file-5.38-mingw-build.patch

**Comment by lz-dc** [comment]
Indeed, was wondering as to how does base file (5.41) https://github.com/msys2/MSYS2-packages/blob/master/file/PKGBUILD build without any patch.

**Comment by lz-dc** [comment]
> I am not sure if this has any negative effect. The fcntl call can be hidden with `#ifdef __MINGW32__`. Something like this https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-file/0001-file-5.38-mingw-build.patch

Thanks, will try that.

**Comment by lz-dc** [comment]
> `fcntl` doesn't exist on windows, so I assume that's where an issue would arise from. You might want to check to see if there's some way around that or see if there's a replacement

Indeed, was wondering as to how does base file (5.41) https://github.com/msys2/MSYS2-packages/blob/master/file/PKGBUILD build without any patch.

**Comment by lz-dc** [comment]
> > I am not sure if this has any negative effect. The fcntl call can be hidden with `#ifdef __MINGW32__`. Something like this https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-file/0001-file-5.38-mingw-build.patch
> 
> Thanks, will try that.

funcs.c have couple of functions wrapped around `fcntl`, as you rightly said that would mean side effect.

**Comment by revelator** [comment]
hmm though it shouldnt fcntl.h does exist in the mingw-w64-api, it only exposes the flags not the actual interface though.

**Comment by MehdiChinoune** [comment]
mingw-w64-file is now at 5.45 https://packages.msys2.org/base/mingw-w64-file
