### ISSUE TITLE
libzip: pkgconfig seems wrong for static build

### ISSUE THREAD

**Issue by BLumia** [msys2/MINGW-packages#10483]
package name and version: mingw-w64-x86_64-libzip 1.8.0-1

While working on an attempt to static linking libzip, I found it's `.pc` file for pkg-config seems wrong. The content of it's pkg-config pc file is:

``` plain
prefix=/mingw64
exec_prefix=${prefix}
bindir=/mingw64/bin
libdir=/mingw64/lib
includedir=/mingw64/include

zipcmp=/mingw64/bin/zipcmp

Name: libzip
Description: library for handling zip archives
Version: 1.8.0
Libs:  -L${libdir} -lzip
Libs.private:  -ladvapi32 -lbz2 -llzma -lZstd::Zstd -lbcrypt -lz
Cflags: -I${includedir}
```

We can see there is a `-lZstd::Zstd` which probably should be just `-lZstd`. Following is the current state:

- If we use it with pkg-config (`pkg-config --static --libs libzip`), the output will be `-LC:/msys64/mingw64/lib -lzip -ladvapi32 -lbz2 -llzma -lZstd::Zstd -lbcrypt -lz` which will cause `ld` cannot find `-lZstd::Zstd`.
- If we use it together with meson (`dependency('libzip', static:true)`), it will warn user about not finding Zstd::Zstd: `WARNING: Static library 'Zstd::Zstd' not found for dependency 'libzip', may not be statically linked`
- If we use CMake with PkgConfig module, it will also complain about Zstd::Zstd not found.

If we change the `-lZstd::Zstd` in `libzip.pc` to `-lZstd`, everything will works fine.

I'm not sure if it's an upstream bug so I reported it here. Let me know if you need any other information. Thanks,

**Comment by Biswa96** [comment]
Thank you for reporting this issue. I apologize. I have not noticed it before updating the package. I have created a pull request to fix this issue ☝️ You can test the unsigned packages from GitHub Actions artifacts here https://github.com/msys2/MINGW-packages/actions/runs/1663465412
