### ISSUE TITLE
Please update vulnerable uriparser 0.9.5 to 0.9.6

### ISSUE THREAD

**Issue by hartwork** [msys2/MINGW-packages#10494]
Hi!

I found an vulnerable copy of uriparser 0.9.5 in here at [`mingw-w64-uriparser/PKGBUILD`](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-uriparser/PKGBUILD). uriparser 0.9.6 with security fixes has been released, the [change log](https://github.com/uriparser/uriparser/blob/uriparser-0.9.6/ChangeLog) has more details. Would be awesome if you could update to 0.9.6.  Thank you! :pray:

Best, Sebastian

**Comment by hartwork** [comment]
@Biswa96 thank you!

**Comment by Biswa96** [comment]
Be thankful to @1480c1 who actually did it. I was sleeping at that time. Blame Circadian rhythm! 😄

**Comment by hartwork** [comment]
Good point. Thanks @1480c1!
