### ISSUE TITLE
[vapoursynth] Python can't import `vapoursynth` module and can't initialize VSScript when trying to run `vspipe`

### ISSUE THREAD

**Issue by CaffeineViking** [msys2/MINGW-packages#10528]
Steps to reproduce:

1. `pacman -S mingw-w64-x86_64-vapoursynth`
2. `vspipe -v`
3. Fails with: `Failed to initialize VSScript`

I've been running into some issues when trying to use `vapoursynth` from this package: [`mingw-w64-x86_64-vapoursynth`](https://packages.msys2.org/package/mingw-w64-x86_64-vapoursynth?repo=mingw64). The version I have is 57-2. AFAIK I'm running the latest packages for its dependencies, of which Python is 3.9.7 (I think that's the most relevant dependency at least).

`vapoursynth` consists of two things: a Python module `vapoursynth` and the command-line tool `vspipe`. This is what I get when using them:

```python
$ python
Python 3.9.7 (default, Nov 21 2021, 22:02:56)  [GCC 11.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vapoursynth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'vapoursynth'
```

and

`$ vspipe -v` → `Failed to initialize VSScript`

The [VapourSynth documentation](http://www.vapoursynth.com/doc/installation.html) points to it being caused by the `PYTHONPATH` being incorrectly configured. However, I can see that these paths look OK because `sys.path` reports this:

```python
$ python
Python 3.9.7 (default, Nov 21 2021, 22:02:56)  [GCC 11.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print('\n'.join(sys.path))
C:/msys64/mingw64/lib/python39.zip
C:/msys64/mingw64/lib/python3.9
C:/msys64/mingw64/lib/python3.9/lib-dynload
C:/msys64/home/Erik
C:/msys64/mingw64/lib/python3.9/site-packages
```

and in `C:/msys64/mingw64/lib/python3.9/site-packages` I can see `vapoursynth.dll`. So it must be something more complicated than just the Python path being incorrect. I'll also ask in the `vapoursynth` repo. about this, but it sounds like there is something funky going on...

**Comment by CaffeineViking** [comment]
Probably the same issue as in #6630.

**Comment by Biswa96** [comment]
The vspipe.exe program fails at `PyImport_ImportModule("vapoursynth")` call. Is there any way to get an error message like GetLastError + FormatMessage?

**Comment by raedrizqie** [comment]
try renaming `C:/msys64/mingw64/lib/python3.9/site-packages/vapoursynth.dll` to vapoursynth.pyd

**Comment by Biswa96** [comment]
> try renaming `C:/msys64/mingw64/lib/python3.9/site-packages/vapoursynth.dll` to vapoursynth.pyd

Working now.

```
$ python.exe
Python 3.9.7 (default, Nov 21 2021, 22:04:05)  [GCC UCRT 11.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vapoursynth
>>> vapoursynth.core.version()
'VapourSynth Video Processing Library\nCopyright (c) 2012-2021 Fredrik Mellbin\nCore R57\nAPI R4.0\nAPI R3.6\nOptions: -\n'
>>>
```

**Comment by CaffeineViking** [comment]
Yup, I can confirm that importing `vapoursynth` works for me too! `vspipe` still gives me `Failed to initialize VSScript` though.

I guess this is something that should be fixed at the package-level? (both the naming of the library and so that `vspipe` works)

**Comment by CaffeineViking** [comment]
I'll try to figure out what's wrong in [mingw-w64-vapoursynth/PKGBUILD ](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-vapoursynth/PKGBUILD) and see if it needs some additional patching maybe.

**Comment by Biswa96** [comment]
Hi @CaffeineViking, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/1683122616

**Comment by CaffeineViking** [comment]
@Biswa96 yup, that works! I just patched my `PKGBUILD` with your changes as I was looking into the other issue with `vspipe`. I have build it with debug symbols and I can see with `gdb` that it gets busted inside `real_init` in `vsscript.cpp` over [lines 43-117](https://github.com/vapoursynth/vapoursynth/blob/master/src/vsscript/vsscript.cpp#L43-L117). I think the issue is that for Windows it assumes the DLLs are called `python3.9.dll` when in fact they are references as `libpython3.9.dll` when I look at it through `ldd`.

**Comment by CaffeineViking** [comment]
ah, nvm I see you patch also fixes it! Thanks!

**Comment by Biswa96** [comment]
> I think the issue is that for Windows it assumes the DLLs are called python3.9.dll

Exactly. Who said that physic power does not exist! 😄 If you don't mind I would like to upstream the patch file first before fixing the package here.

**Comment by CaffeineViking** [comment]
No problem for me at least, I'll just use `PKGBUILD` + patches for now 👍🏻 

And thanks again for the help, that was some really fast response time!

**Comment by Biswa96** [comment]
@naveen521kk Upstream does not support mingw toolchain as stated here https://github.com/vapoursynth/vapoursynth/pull/841. I am not familiar with python build scripts. Would you like to investigate about the .dll vs .pyd thing?

**Comment by Biswa96** [comment]
The setup.py searches registry and current directory for the libvapoursynth.dll. It has to be replaced with build directory and somehow provide the corresponding import library (.dll.a) path for linking.

**Comment by raedrizqie** [comment]
> The setup.py searches registry and current directory for the libvapoursynth.dll. It has to be replaced with build directory and somehow provide the corresponding import library (.dll.a) path for linking.

correct

**Comment by CaffeineViking** [comment]
Hey, for those that are interested in also getting [vapoursynth/vsrepo](https://github.com/vapoursynth/vsrepo) I've quickly hacked together a PKGBUILD and patch over [here](https://gist.github.com/CaffeineViking/24fea78a01ccb6f38fbba3a7ed9072b8).

This is enough for me, but I think it would need some additional love in order to be published as an actual MinGW package (that's why this is a Gist and not a PR). I'm not sure how "package manager"-like things are supposed to work in MinGW (and if `pacman` is supposed to know about the files that `vsrepo` creates). There's another problem in that it's placing packages and such in "bizarre" locations because VapourSynth thinks this is a regular Window environment. As an example of some of the problems that happen:

```
$ vsrepo.py paths
Paths:
Definitions: C:\Users\Erik\AppData\Roaming/VapourSynth/vsrepo/vspackages3.json
Binaries: C:\Users\Erik\AppData\Roaming/VapourSynth/plugins64
Scripts: C:/Users/Erik/.local/lib/python3.9/site-packages
Dist-Infos: C:/Users/Erik/.local/lib/python3.9/site-packages
```

i.e. paths are setup in Windows-oriented directories when they should probably be in the actual MinGW `site-packages` directory.

Anyway, plugins and such work, even if they are placed in `%APPDATA%` so it's good enough for me at least. If anyone wants to take this further feel free to use the `PKGBUILD` and `0001-apply-python3-environment.patch` as a starting point. I think some changes to `vsrepo.py` are at least needed to get it to recognize this as a Unix-like environment. Since `vspipe` somehow found those plugins, some kind of change to `vapoursynth` itself would also be needed for it to start working with plugins in another directory. I think vs likes to have plugins and such under a so called `$libdir` (which seems to be configurable AFAIK through autotools `configure`).

btw feel free to close this ticket as solved, both the python-side and `vspipe` have been working splendidly on my side at least.
