### ISSUE TITLE
gettext: can no longer work with nul files

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#10520]
```
$ echo -e "msgid \"a\"\nmsgstr \"a\"" > a.po
$ msgfmt.exe a.po -o nul -v
C:\msys64\mingw64\bin\msgfmt.exe: error while opening "nul" for writing: Invalid argument
1 translated message.
```

**Comment by revelator** [comment]
shouldnt that be /dev/nul ?

**Comment by 1480c1** [comment]
I'm assuming since this is for mingw-w64, it would try to open window's `nul` file

**Comment by revelator** [comment]
not sure we can access the windows nul from bash easily ?

**Comment by 1480c1** [comment]
From bash and anything linking to cygwin, `nul` is just a normal file that it can create, write to, delete, etc, it has no special handling of `nul`, meaning I can create a file called `nul` and edit it in nano, but not be able to delete it from powershell etc.

**Comment by revelator** [comment]
well it should actually work, tested it this way ->

```
Revelator@DESKTOP-BPM81CH MINGW32 ~
$ echo test >nul

Revelator@DESKTOP-BPM81CH MINGW32 ~
$ cat nul
test
```

**Comment by lazka** [comment]
I'm seeing the issue without any cygwin involved. I just used bash here for the reproducer.

**Comment by revelator** [comment]
well that is odd then :/

**Comment by kmilos** [comment]
Just hit this as well when building darktable:

```
[275/917] Generating de/darktable.pod
FAILED: doc/man/de/darktable.pod C:/msys64/home/kmilos/darktable/build/doc/man/de/darktable.pod
cmd.exe /C "cd /D C:\msys64\home\kmilos\darktable\doc\man && sh -c "C:/msys64/usr/bin/site_perl/po4a-translate -f pod -m darktable.pod -p po/de.po -l C:/msys64/home/milkom01/darktable/build/doc/man/de/darktable.pod -k 0""
Invalid po file po/de.po:
C:\msys64\ucrt64\bin\msgfmt.exe: error while opening "nul" for writing: Invalid argument
```

**Comment by lazka** [comment]
the problem is in gnulib, `fopen_supersede()` with` supersede_if_does_not_exist=true` fails

**Comment by lazka** [comment]
Yes, that fixes things. Needs to be backported.

**Comment by lazka** [comment]
Fix is in the repo
