### ISSUE TITLE
qt6 problem with icu

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#10558]
basically it refuses to link to icu (latest version) all dependencies have been rebuild several times to no avail.
had to turn icu off in qt6-base because of this.

**Comment by revelator** [comment]
great :)

**Comment by MehdiChinoune** [comment]
@revelator you have many open issues, could you please close the ones already fixed!

**Comment by revelator** [comment]
ofc. and good job :)

**Comment by revelator** [comment]
should be cleared now.
