### ISSUE TITLE
expat: Please update from vulnerable 2.4.2 to 2.4.3

### ISSUE THREAD

**Issue by hartwork** [msys2/MINGW-packages#10559]
Hi!

[libexpat 2.4.3](https://github.com/libexpat/libexpat/releases/tag/R_2_4_3) with **security fixes** has been released, the upstream [change log](https://github.com/libexpat/libexpat/blob/R_2_4_3/expat/Changes) has more details.

Thanks for updating! :pray: 

Best, Sebastian

**Comment by lazka** [comment]
* https://github.com/msys2/MSYS2-packages/pull/2816
* https://github.com/msys2/MINGW-packages/pull/10560

**Comment by hartwork** [comment]
@lazka cool, thank you!

**Comment by lazka** [comment]
thanks, will be in the next repo update
