### ISSUE TITLE
Cannot install Clang32 toolchain

### ISSUE THREAD

**Issue by pschneider1968** [msys2/MINGW-packages#10569]
I tried to install the Clang32 compiler toolchain as a package group, but obviously, the package group definition is missing in the repo.

```
Peter@bolide MSYS ~
$ pacman -Su
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
Peter@bolide MSYS ~
$ pacman -S mingw-w64-clang-i686-toolchain
error: target not found: mingw-w64-clang-i686-toolchain

Peter@bolide MSYS ~
$
```

**Comment by pschneider1968** [comment]
The MSYS2 website states it should be there:

[https://packages.msys2.org/group/mingw-w64-clang-i686-toolchain](https://packages.msys2.org/group/mingw-w64-clang-i686-toolchain)

**Comment by pschneider1968** [comment]
Even when I try to install the group's packages one by one, it fails, because the also seem to be amiss:

```
Peter@bolide MSYS ~
$ pacman -S mingw-w64-clang-i686-clang
error: target not found: mingw-w64-clang-i686-clang

Peter@bolide MSYS ~
$ pacman -S mingw-w64-clang-i686-llvm
error: target not found: mingw-w64-clang-i686-llvm

Peter@bolide MSYS ~
$

```

**Comment by 1480c1** [comment]
Seems the clang32 repo is not in the pacman.conf by default, mine currently looks like
```conf
[mingw32]
Include = /etc/pacman.d/mirrorlist.mingw

[mingw64]
Include = /etc/pacman.d/mirrorlist.mingw

[ucrt64]
Include = /etc/pacman.d/mirrorlist.mingw

[clang64]
Include = /etc/pacman.d/mirrorlist.mingw

[msys]
Include = /etc/pacman.d/mirrorlist.msys

```

**Comment by jeremyd2019** [comment]
clang32 (and clangarm64) repos are not in pacman.conf by default.  That's under discussion, but for now you can add them manually like the others that use mirrorlist.mingw

**Comment by pschneider1968** [comment]
Thanks for helping me out, that worked! I searched the issues before opening mine, but there was none. Seems nobody is really missing 32bit nowadays...
