### ISSUE TITLE
Requesting libepub aka ebook tools to be added

### ISSUE THREAD

**Issue by jointri** [msys2/MINGW-packages#10563]
Ebook tools or libepub would be a great addition to add if one needs epub support in programs such as okular compiling from source.
https://sourceforge.net/projects/ebook-tools/
Could it please be added as a mingw package?

**Comment by Biswa96** [comment]
The project does not look like maintained anymore. Last Update: 2016-05-03

**Comment by jointri** [comment]
The okular docs for example links to it.
https://okular.kde.org/build-it/
If you know a different epub library that works as a drop in alternative I'm all ears.

**Comment by Biswa96** [comment]
I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/1708956465

**Comment by jointri** [comment]
I downloaded the github actions, put the mingw64 into my msys2 installation, and did test compilation of okular and it found libepub the very first time. Success. Just needs someone to approve of the pull request and we'll be good to go.
