### ISSUE TITLE
[vapoursynth]

### ISSUE THREAD

**Issue by LuisB79** [msys2/MINGW-packages#10575]
There is no VSScript.lib in C:\msys64\mingw64\lib, thus failing in some compilations like av1an, i had to manually add the vsscript.lib from vapoursynth portable

**Comment by 1480c1** [comment]
1. the .lib extension is msvc specific, thus would not be part of a library produced by mingw-w64 gcc, normally
2. looking at https://packages.msys2.org/package/mingw-w64-x86_64-vapoursynth?repo=mingw64, the package provides
    ```
    /mingw64/lib/libvapoursynth-script.a
    /mingw64/lib/libvapoursynth-script.dll.a
    ```
    Are you sure it needs `VSScript.lib` as typed?

It seems you might need to take it up with https://github.com/redzic/vapoursynth-rs based on
https://github.com/redzic/vapoursynth-rs/blob/master/vapoursynth-sys/build.rs#L36 to only have msvc use `vsscript`

**Comment by LuisB79** [comment]
oh, that's new, av1an does ask for vsscript.lib
