### ISSUE TITLE
lxml works incorrectly with libxml2 2.9.12

### ISSUE THREAD

**Issue by norstbox** [msys2/MINGW-packages#10576]
Serialisation with libxml2 2.9.12 returns extra closing tags. This causes both real-life breakage (such as #8864) and a lot of test failures.

This is known compatibility issue with libxml2 2.9.12 release:
https://gitlab.gnome.org/GNOME/libxml2/-/issues/255
https://bugs.launchpad.net/lxml/+bug/1928795

Please consider to apply the following workaround: https://gitlab.gnome.org/nwellnhof/libxml2/-/commit/7955b0d6fbbe49392ccc2e511edd00fbbfcb5a10

BTW, there are some MINGW specific [unit test](https://github.com/lxml/lxml/blob/master/test.py) failures, not related to the above issue. For example, Gzip tests.

**Comment by lazka** [comment]
Sounds good

**Comment by lazka** [comment]
somewhat related, libxml2 is now maintained again, so things should improve shortly: https://gitlab.gnome.org/GNOME/libxml2/-/issues/319#note_1351807
