### ISSUE TITLE
Build eclipseclp using gcc

### ISSUE THREAD

**Issue by manugoswami** [msys2/MINGW-packages#10590]
Hello Developers ,

I wish to build eclipseclp project built using x86_64-w64-mingw32-gcc  with gcc, that is without cross compiling but unable to do the same.

The question is how to build some project built on x86_64-w64-mingw32-gcc with gcc without cross compiling?

Please clarify most urgently.

Thanks and regards,
Manu

**Comment by Biswa96** [comment]
The procedure to install compiler toolchain is provided here https://www.msys2.org/. The mingw gcc is a native compiler.
