### ISSUE TITLE
Impossible to compile okular with msys2.

### ISSUE THREAD

**Issue by jointri** [msys2/MINGW-packages#10620]
There isn't an error with the cmake making the makefile, but one issue that arises at one point be it 30% or 99% is that kf.doctools.core: Error: Could not find kdoctools catalogs, which would result in terminating the compilation. I even did the prefix.sh script like I was supposed to, so this seems to be a msys2 issue. Is there any kdoctools calalogs package? If not, can it please be added. It's the missing piece to be able to compile okular from source because the cmake was satisfied with dependencies, but not the makefile it generated.

**Comment by Biswa96** [comment]
Did you install the [kdoctools-qt5][1] package?

[1]: https://packages.msys2.org/base/mingw-w64-kdoctools-qt5

**Comment by MehdiChinoune** [comment]
I think this is an upstream bug, Their cmake setup should detect kdoctools before building.

**Comment by jointri** [comment]
> Did you install the [kdoctools-qt5](https://packages.msys2.org/base/mingw-w64-kdoctools-qt5) package?

Yes. I had this installed among one of my first tries with compiling okular.



> I think this is an upstream bug, Their cmake setup should detect kdoctools before building.

Are you sure?

**Comment by MehdiChinoune** [comment]
> Are you sure?

If the failure was due the absence of a package, then yes.
The role of CMake is to generate projects (Makefiles, ninja-files, VS ...) and check dependencies.

**Comment by jointri** [comment]
> > Are you sure?
> 
> If the failure was due the absence of a package, then yes. The role of CMake is to generate projects (Makefiles, ninja-files, VS ...) and check dependencies.

The reason why I'm skeptical is that the KDE buildbot is able to generate nightly releases for windows without issues. I wonder why I cannot do that with my msys2 on windows.

**Comment by MehdiChinoune** [comment]
Another possibility is that kdoctools has an issue on MSYS2/MINGW, for that we need a minimized reproducer.

**Comment by jointri** [comment]
> Another possibility is that kdoctools has an issue on MSYS2/MINGW, for that we need a minimized reproducer.

I got a theory. We should have kf5 and other KDE libraries under /usr as well because I think kdoctools is looking for a hardcoded /usr/share/so on/and/so forth. I think I'll try a fresh profile and see how the results turn out moving kf5 from /mingw64 to /usr.

**Comment by MehdiChinoune** [comment]
> > Another possibility is that kdoctools has an issue on MSYS2/MINGW, for that we need a minimized reproducer.
> 
> I got a theory. We should have kf5 and other KDE libraries under /usr as well because I think kdoctools is looking for a hardcoded /usr/share/so on/and/so forth. I think I'll try a fresh profile and see how the results turn out moving kf5 from /mingw64 to /usr.

This couldn't happen `/usr` is reserved for MSYS2 environment, if your theory is true then kdoctools should be patched to look into ${MINGW_PACKAGE_PREFIX} (mingw64, clang64 ...)

**Comment by Biswa96** [comment]
This issue has been fixed with this commit https://github.com/msys2/MINGW-packages/commit/0900785a1f4e4146ab9561fb92a1c70fa70fcfc4. Please check if you can reproduce the issue with okular build. The mingw-w64-kdoctools-qt5 package version 5.97.0-2 has the fix.
