### ISSUE TITLE
gtk3-demo special characters @, # not displayed in entry field

### ISSUE THREAD

**Issue by mrichez** [msys2/MINGW-packages#10622]
When using alt-gr key to display # or @ in entry field in gtk3-demo, nothing is displayed.

**Comment by mrichez** [comment]
Still working with package mingw-w64-x86_64-gtk3-3.24.30-5
Issue opened here: https://gitlab.gnome.org/GNOME/gtk/-/issues/4665

**Comment by lazka** [comment]
we can update to the latest upstream commit to see if it has been fixed already

**Comment by mrichez** [comment]
It is solved with the latest gtk-3-24 head : https://gitlab.gnome.org/GNOME/gtk/-/issues/4665#note_1369555

**Comment by lazka** [comment]
Thanks! Let's update then :)

**Comment by mrichez** [comment]
:+1:

**Comment by mrichez** [comment]
@lb90 Will you update package with latest commit ? Thanks!

**Comment by lb90** [comment]
Already updated, thanks @lazka! :)

**Comment by mrichez** [comment]
Thanks @lazka :-)
