### ISSUE TITLE
A reportedly broken i2pd here (I don't know whether this is true or not, this report needs validation)

### ISSUE THREAD

**Issue by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [msys2/MINGW-packages#10625]
@R4SAS tells: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-i2pd

`<R4SAS>` [They added a flag] USE_MESHNET [into] make

1. `<e.g.ph.>` `USE_MESHNETS` (plural) wording would be smarter I think; the rationale is that this would open the road to MANY mesh networks at i2pd, and this singular wording should be deprecated I think.

2. `<R4SAS>` [The bigger problem is not the 1. above. The presence of this flag disables the NAT detection, therefore these [MINGW i2pd router] users always get the `OK` status.  And in fact, [these MINGW i2pd routers are] not accessible [via the network] because even the peer test is not being done.]

`<R4SAS>` @i2orignal: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-i2pd/0001-i2pd-endian.patch

e.g.ph. adds: Wrong?

(Translated into English by e.g.ph. AKA @ANANTASHESHALOKAGREENTARAEGPTRANSHOLON)

**Comment by r4sas** [comment]
I'll do PR soon. Testing changes with Endianess.

**Comment by r4sas** [comment]
@Biswa96, @lazka, https://github.com/msys2/MINGW-packages/pull/10626

**Comment by Biswa96** [comment]
Hi @ANANTASHESHALOKAGREENTARAEGPTRANSHOLON, Thank you for reporting the issue. A pull request has been added to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/1766431883

**Comment by r4sas** [comment]
You can just close this, he's not using windows.
