### ISSUE TITLE
Cannot download py2exe under MSYS2 in Win. 11

### ISSUE THREAD

**Issue by FairyballYT** [msys2/MINGW-packages#10623]
I'm using MSYS2 MinGWx64 on my Acer Predator Helios 300 (PH315-52) running Windows 11, and everytime I try to ask MSYS2 MinGWx64 to download and install the package "mingw-w64-x86_64-python-py2exe", MSYS2 complains that it can't find the package. Am I doing something wrong, or does the package no longer exist? I have Python 3.9 installed, so perhaps py2exe relies on an installation of Python 2 to be there.
![Screenshot 2022-01-28 161456 - JJ - MSYS2 MinGWx64 cannot find the package py2exe](https://user-images.githubusercontent.com/81061935/151628999-fbbd5414-36d1-491b-bc3e-e7da8ce696a2.png)

**Comment by ZachBacon** [comment]
Might I suggest you run pacman -Syu first and then try the command

**Comment by FairyballYT** [comment]
> Might I suggest you run pacman -Syu first and then try the command

Thanks alot! I didn't realize I had to update Minx64's list of

**Comment by FairyballYT** [comment]
> Might I suggest you run pacman -Syu first and then try the command

Thanks a lot! I didn't realize that I had to update MSYS2 MinGWx64's list of known packages sing this command. Now I can try installing nrsc5-gui and nrsc5-dui.
![image](https://user-images.githubusercontent.com/81061935/151640378-c9b4e6bf-44d4-4d94-87f5-c7b059d2d618.png)
