### ISSUE TITLE
libtiff static I think is linking to jbigkit shared

### ISSUE THREAD

**Issue by ZachBacon** [msys2/MINGW-packages#10628]
libtiff static build I think might be linking to jbig shared library. After my coworker fixed linking to wxwidgets statically there was two remaining issues, it was in regards to jbig being a shared library requirement, which them pulls in lzma as well.

**Comment by Biswa96** [comment]
Is it possible to reproduce the issue with a minimal sample code? I have tried to static link a test file, ascii_tag.c from libtiff repository and it compiled without any issue.

```
gcc -static -Wall ascii_tag.c `pkgconf -static -libs libtiff-4` -lstdc++
```

**Comment by ZachBacon** [comment]
This is just an observation when I'm compiling vba-m with -DVBAM_STATIC=ON those were the only two issues we had.

**Comment by Biswa96** [comment]
Can you provide the source repository url?

**Comment by ZachBacon** [comment]
https://github.com/visualboyadvance-m/visualboyadvance-m

**Comment by ZachBacon** [comment]
Though most of our fixes landed in the clang64-static branch

**Comment by ZachBacon** [comment]
figured out the issue, took some linking and link order shinnanigans, downsides of trying to support every viable compiler.

**Comment by Biswa96** [comment]
Just curious. What was the solution?

**Comment by ZachBacon** [comment]
basically had to match suffix stuff so that we force lld/ld to use .a instead of shared .dll.a libraries
