### ISSUE TITLE
Group mingw-w64-x86_64-vulkan-devel doesn't work well on windows

### ISSUE THREAD

**Issue by hybcloud** [msys2/MINGW-packages#10632]
Package `group mingw-w64-x86_64-vulkan-devel` (in fact the clang version doesn't work, either) seems like a pre-compiled vulkan SDK from LunarG. And I tried to use it as vulkan SDK from LunarG. So I write CMakeLists.txt below:

```cmake
cmake_minimum_required(VERSION 3.21)
project(MsysVulkanIssue)

set(CMAKE_CXX_STANDARD 17)

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME}
        vulkan
        glfw3
        )
```

You can aquire the main.cpp code from [https://vulkan-tutorial.com/code/05_window_surface.cpp](https://vulkan-tutorial.com/code/05_window_surface.cpp).
The error doesn't occur until I try to create an surface on window. The function call `glfwCreateWindowSurface(instance, window, nullptr, &surface) != VK_SUCCESS)` simply return `-7`, which is `VK_ERROR_EXTENSION_NOT_PRESENT`.
So I modify the `populateDebugMessengerCreateInfo` function in order to listen to error message only, and get validation layer's message below:
```plain
validation layer: loader_scanned_icd_add: Driver C:\windows\System32\DriverStore\FileRepository\nvltsi.inf_amd64_8080a39
6e580822b\.\nvoglv64.dll says it supports interface version 6 but still exports core entrypoints (Policy #LDP_DRIVER_6)
```

I think I might misused the package, or it should be something wrong in the package. Cause if I link to the precompiled vulkan lib download from LunarG instead of that from msys repository, everything works fine. Here is the CMakeList.txt that works:
```cmake
cmake_minimum_required(VERSION 3.21)
project(MsysVulkanIssue)

set(CMAKE_CXX_STANDARD 17)

add_executable(${PROJECT_NAME} main.cpp)
target_link_directories(${PROJECT_NAME} PUBLIC C:/VulkanSDK/1.2.198.1/Lib) # specify vulkan sdk location
target_link_libraries(${PROJECT_NAME}
        vulkan-1    # vulkan-1 instead of vulkan
        glfw3
        )
``` 

Addtional information:

My vulkan installation:
![My vulkan installation](https://user-images.githubusercontent.com/43987901/151747028-94fb87af-56d0-457b-a78c-ae17b6c11803.png)
My GLFW installation:
![My GLFW installation](https://user-images.githubusercontent.com/43987901/151747141-8e95ae3b-1f12-487b-b80a-7c9a7c62b29c.png)

**Comment by robotogre** [comment]
I seem to be facing the same issue.

**Comment by Biswa96** [comment]
Does the sample code in OP require a discrete GPU?

**Comment by hybcloud** [comment]
> misused the package, or it should be something wrong in the package. Cause if I link to the precompiled vulkan lib download fro

When received your reply, I had an software update on msys, and all works well now. I think it might be a problem that is already solved now.

**Comment by hybcloud** [comment]
> Does the sample code in OP require a discrete GPU?

Sorry, but I don't really understand what you mean. Could you explain in another way?

**Comment by Biswa96** [comment]
> I had an software update on msys, and all works well now.

Well, then this issue was likely similar with https://github.com/msys2/MINGW-packages/issues/2673.
