### ISSUE TITLE
SVT-AV1 support of ffmpeg

### ISSUE THREAD

**Issue by wszqkzqk** [msys2/MINGW-packages#10637]
`SVT-AV1` is a new `av1` encoder with high performance. And now can add it to ffmpeg. May add `${MINGW_PACKAGE_PREFIX}-svt-av1` to the `dependence` and `--enable-libsvtav1` to the `common_config`.

**Comment by Biswa96** [comment]
Hi @wszqkzqk, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/1782084610

**Comment by Biswa96** [comment]
I have added a pull request to add zimg dependency with ffmpeg. The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/1800246850

**Comment by wszqkzqk** [comment]
> I have added a pull request to add zimg dependency with ffmpeg. The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/1800246850

But when I tried to compile, it showed this error:
![``NAHH9X@$X653PFB961> I have added a pull request to add zimg dependency with ffmpeg. The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/1800246850

But when I tried to compile, it showed this error:
5](https://user-images.githubusercontent.com/12961135/152677660-09b376ad-325d-4c76-a0ca-cd041d4df9e0.png)

**Comment by Biswa96** [comment]
I am unaware of your build environment and how you set that up. The new ffmpeg package has been uploaded to pacman repository. You can download it using `pacman -Syu` command.

**Comment by wszqkzqk** [comment]
> I am unaware of your build environment and how you set that up. The new ffmpeg package has been uploaded to pacman repository. You can download it using `pacman -Syu` command.

I just tries to run `makepkg-mingw -si`……

**Comment by wszqkzqk** [comment]
> I am unaware of your build environment and how you set that up. The new ffmpeg package has been uploaded to pacman repository. You can download it using `pacman -Syu` command.

It seems that there is a mistake about relative path.
