### ISSUE TITLE
gcc-libs in clang envs does not pull in openmp

### ISSUE THREAD

**Issue by kmilos** [msys2/MINGW-packages#10649]
`gcc-libs` is provided by `libc++` in clang environments, but it does not also pull in `openmp` (`libomp`); in GCC toolchain environments OTOH `gcc-libs` does also contain `libgomp`...

This is related to https://github.com/msys2/MINGW-packages/pull/9884

The [workaround for now is to also explicitly require `openmp` for those environments](https://github.com/msys2/MINGW-packages/blob/5fc83fe2dd234957cc0de37db2d9c309104eb70c/mingw-w64-gmic/PKGBUILD#L17-L18), but it would be convenient to have the same behavior for all packages that already require only `gcc-libs` so the recipes don't have to be updated? I guess it would be quite a job to figure out [which of these dependants](https://packages.msys2.org/package/mingw-w64-x86_64-gcc-libs?repo=mingw64) actually need the explicit `openmp` addition for clang.

Alternatively, this can also be handled by some new pseudo-package like it was done w/ `cc` recently...

**Comment by MehdiChinoune** [comment]
This is not related to #9884 at all.
The reason why those builds fail, is that CI was installing `${MINGW_PACKAGE_PREFIX}-toolchain` (which contains openmp on CLANG envs) before building.
@lazka has removed that and add explicit make-dependency on `${MINGW_PACKAGE_PREFIX}-cc`.

I think the solution is to add a package called `${MINGW_PACKAGE_PREFIX}-omp` provided by `gcc-libs` on GCC envs and `openmp` on CLANG envs.

**Comment by lazka** [comment]
hm, something like "cc-libs" which depends on all those things?

> I guess it would be quite a job to figure out [which of these dependants](https://packages.msys2.org/package/mingw-w64-x86_64-gcc-libs?repo=mingw64) actually need the explicit `openmp` addition for clang.

Do you mean if it would have been installed it would have been used?

**Comment by kmilos** [comment]
> Do you mean if openmp would have been installed during the build it would have been used?

Probably, because that package supplies both the header and the library for -clang- envs

**Comment by lazka** [comment]
here is a list of packages actually linking against libgomp (with gcc): https://github.com/lazka/package-grokker/runs/5057107592?check_suite_focus=true#step:4:9

**Comment by kmilos** [comment]
Thanks for that. It's not the hugest list, so not inconceivable to do by explicitly for now...

**Comment by kmilos** [comment]
Hm... mingw-w64-clang-x86_64-graphicsmagick-1.3.37-1 was already linked against libomp on my system so no difference there. I'm not sure where this came from in the dependency chain, unless the whole mingw-w64-clang-x86_64-toolchain group was installed by default at build time back then (there was no explicit dependency on -cc)? In any case, would still need the dependency on openmp at runtime.

**Comment by lazka** [comment]
> unless the whole mingw-w64-clang-x86_64-toolchain group was installed by default at build time back then (there was no explicit dependency on -cc)?

yes, toolchain was always present in the build env at that time.

**Comment by kmilos** [comment]
Thanks, that makes sense. I might look for another example then that was built after this change...

> hm, something like "cc-libs" which depends on all those things?

This sounds like a sensible option indeed.

**Comment by lazka** [comment]
> > hm, something like "cc-libs" which depends on all those things?
> 
> This sounds like a sensible option indeed.

OK. I'd prefer more explicit dependencies in the long run, but I guess that'll do for now.

**Comment by kmilos** [comment]
> I'd prefer more explicit dependencies in the long run

Sure, but I don't see how this can fit e.g. GH setup-msys2 actions and pacboy `:p` today - you'd still have to somehow if-then-else gcc-libs vs libc++ & openmp etc. depending on MSYSTEM, which is not very practical...

**Comment by lazka** [comment]
e.g. we could have a "cc-openmp" virtual package that provides the default one in each environment.

**Comment by kmilos** [comment]
Ah, you mean make current gcc-libs even more granular somehow? Sure, that works as well.

Note that gcc-libs currently provides (for 64-bits):

libatomic-1.dll
libgcc_s_seh-1.dll
libgomp-1.dll
libquadmath-0.dll
libssp-0.dll
libstdc++-6.dll

(notice no headers for any, those you get anyway w/ cc I guess)

So cc-openmp would be an empty metapackage just pulling in gcc-libs on MINGW64/UCRT64?

For -clang- envs that gcc-libs currently provided by libc++ which depends on libunwind so what you end up with is just 

libc++.dll
libunwind.dll

I'm not a GCC nor LVM expert either so I don't know what is equivalent where exactly. For sure libomp.dll is missing from this list, but not sure if there are more missing equivalent libraries compared to gcc-libs?

E.g. it seems you'll also need cc-atomics as well (for makedepends only though): https://clang.llvm.org/docs/Toolchain.html#atomics-library and possibly cc-libssp?

**Comment by lazka** [comment]
> So cc-openmp would be an empty metapackage just pulling in gcc-libs on MINGW64/UCRT64?

or we split out libgomp from gcc-libs into its own package

> I'm not a GCC nor LVM expert either so I don't know what is equivalent where exactly. For sure libomp.dll is missing from this list, but not sure if there are more missing equivalent libraries compared to gcc-libs?

Me neither. So I kinda tend to just do the cc-libs thing for now and go from there.

**Comment by mati865** [comment]
I don't think libomp is worth trouble splitting it, it's 0.9 MiB after installation.

**Comment by raedrizqie** [comment]
i think its better bundled with clang toolchain, sama as gcc-libs does..

**Comment by kmilos** [comment]
Related to https://github.com/msys2/MINGW-packages/issues/10833 (missing `libwinpthread` and `openmp`) @MehdiChinoune
