### ISSUE TITLE
packages in CLANG64 depending or makedepending on gcc

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#10658]
Looks like I missed some. We need to get rid of them, and rebuild everything in the DB runtime depending on gcc.

_Originally posted by @lazka in https://github.com/msys2/MINGW-packages/pull/10651#discussion_r798994804_

Packages in the clang64.db that depend on `${MINGW_PACKAGE_PREFIX}-gcc`:
- [x] mingw-w64-gnucobol
- [x] mingw-w64-msmpi
- [x] mingw-w64-rust
- [x] mingw-w64-uasm

PKGBUILDs in the srcinfo.json that depend or makedepend on `${MINGW_PACKAGE_PREFIX}-gcc` in clang64:
- [x] mingw-w64-libmangle-git
- [x] mingw-w64-tl-expected
- [x] mingw-w64-gtkwave
- [x] mingw-w64-lua-luarocks
- [x] mingw-w64-opencollada
- [x] mingw-w64-lmdbxx
- [x] mingw-w64-catch
- [X] mingw-w64-argtable
- [X] mingw-w64-windows-default-manifest
- [X] mingw-w64-rust
- [X] mingw-w64-unittest-cpp
- [X] mingw-w64-hlsl2glsl-git
- [X] mingw-w64-eigen3
- [X] mingw-w64-styrene
- [X] mingw-w64-msmpi
- [X] mingw-w64-winstorecompat-git
- [X] mingw-w64-mhook
- [X] mingw-w64-sparsehash
- [X] mingw-w64-ensmallen
- [X] mingw-w64-pqp
- [X] mingw-w64-libbsdf
- [X] mingw-w64-hicolor-icon-theme
- [X] mingw-w64-iverilog
- [X] mingw-w64-cgal
- [X] mingw-w64-asciidoctor
- [X] mingw-w64-libiptcdata
- [X] mingw-w64-meld3
- [X] mingw-w64-ghc
- [X] mingw-w64-crt-git
- [X] mingw-w64-spice-protocol
- [X] mingw-w64-ruby-ronn
- [X] mingw-w64-mumps
- [X] mingw-w64-mypaint-brushes2
- [X] mingw-w64-leveldb
- [X] mingw-w64-trompeloeil
- [X] mingw-w64-libtomcrypt
- [X] mingw-w64-pystring
- [X] mingw-w64-openFPGALoader
- [X] mingw-w64-gtk-elementary-theme
- [x] mingw-w64-uasm
- [X] mingw-w64-nana
- [X] mingw-w64-asio
- [X] mingw-w64-tiny-dnn
- [X] mingw-w64-mypaint-brushes

<details>
<summary>Script that generated these lists</summary>

```python
#!/usr/bin/env python

import pacdb


clang64 = pacdb.mingw_db_by_name('clang64')

seen = set()
for pkg in clang64:
    if 'mingw-w64-clang-x86_64-gcc' in pkg.depends:
        if pkg.base not in seen:
            seen.add(pkg.base)
            print(pkg.base)

print("%d package bases\n" % len(seen))


import json
from urllib.request import urlopen

with urlopen("https://github.com/msys2/MINGW-packages/releases/download/srcinfo-cache/srcinfo.json") as fp:
    srcinfos = json.load(fp)

count = 0
for pkg in srcinfos.values():
    if 'clang64' in pkg['srcinfo']:
        srcinfo = pkg['srcinfo']['clang64']
        for line in srcinfo.split("\n"):
            line = line.lstrip()
            if not line:
                continue

            (name, value) = line.split(" = ", 1)
            if name in ('depends', 'makedepends') and value == 'mingw-w64-clang-x86_64-gcc':
                print(pkg['path'])
                count += 1

print("%d PKGBUILDs" % count)
```
</details>

**Comment by MehdiChinoune** [comment]
I couldn't execute that code:
```
Traceback (most recent call last):
  File "D:\dev\pkgs.py", line 3, in <module>
    import pacdb
ModuleNotFoundError: No module named 'pacdb'
```
I couldn't find pacdb module in msys2/mingw packages
```
pacman -Fx pacdb

```
shows nothing!

**Comment by lazka** [comment]
https://github.com/jeremyd2019/pacdb

**Comment by lazka** [comment]
fixed now

**Comment by jeremyd2019** [comment]
https://github.com/jeremyd2019/pacdb/issues/1
