### ISSUE TITLE
Can't install FFmpeg 

### ISSUE THREAD

**Issue by MozartWolfgang** [msys2/MINGW-packages#10663]
pacman -S mingw-w64-x86_64-ffmpeg does not work and gives this error every time i try to use it.

error: mingw-w64-x86_64-eigen3: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-openblas: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-suitesparse: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-ceres-solver: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-lcms2: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-libraw: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-SDL2: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-pugixml: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-jansson: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-lz4: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-libarchive: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-libbluray: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-libsoxr: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-libvorbis: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-srt: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-ffms2: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: failed to commit transaction (invalid or corrupted package)

**Comment by MehdiChinoune** [comment]
Update pacman package databases before installing any package
```
$ pacman -Syuu
$ pacman -S mingw-w64-x86_64-ffmpeg
```

**Comment by lazka** [comment]
Is this an old installation? If not where did you get the installer from?

**Comment by MozartWolfgang** [comment]
It is used in the program "tartube" i updated the terminal but i still get errors.

error: mingw-w64-x86_64-ceres-solver: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-pugixml: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-lz4: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-libsoxr: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-libvorbis: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw-w64-x86_64-ffms2: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: failed to commit transaction (invalid or corrupted package)

**Comment by ZachBacon** [comment]
try running 

`pacman-key --init`

and after when that is finished executing, run

`pacman-key --populate`

**Comment by MozartWolfgang** [comment]
> try running
> 
> `pacman-key --init`
> 
> and after when that is finished executing, run
> 
> `pacman-key --populate`

nothing happens when typing those commands :/

**Comment by ZachBacon** [comment]
Try running this

`pacman-key --refresh-keys`

**Comment by MozartWolfgang** [comment]
> Try running this
> 
> `pacman-key --refresh-keys`

Still nothing, i guess i have a scuffed version or something :/

**Comment by MozartWolfgang** [comment]
> Not at all, even archlinux users sometimes run into this problems. I'm just doing basic debug stuff. So first thing first So what we are going to do is in your msys2 folder, go to your etc/pacman.d directory and remove the folder labled gnupg, and then the commands I told you to run before, the pacman-key commands, run the init and populate commands and it should in theory fix that. And if that doesn't fix there, chances are the keyserver might still be pointed to the old gnupg keyserver. Anyways let me know your progress.

That didnt do anything so i tried to update again and now i get the error "gpg: can't connect to the agent: IPC connect call failed
"

**Comment by ZachBacon** [comment]
Humour me one more time, Do you mind rebooting your computer and then trying again those commands?

**Comment by ZachBacon** [comment]
@MozartWolfgang Everything alright?

**Comment by MozartWolfgang** [comment]
> @MozartWolfgang Everything alright?

As silly as it sounds i must admit defeat on this, i have tried for multiple days and i even rebooted before you suggested it to see if it fixed the errors and it didnt but thanks to everyone in the thread that tried to help :)

**Comment by ZachBacon** [comment]
> > @MozartWolfgang Everything alright?
> 
> As silly as it sounds i must admit defeat on this, i have tried for multiple days and i even rebooted before you suggested it to see if it fixed the errors and it didnt but thanks to everyone in the thread that tried to help :)

Do not admit defeat so easily. I'm not giving up

**Comment by MozartWolfgang** [comment]
> > > @MozartWolfgang Everything alright?
> > 
> > 
> > As silly as it sounds i must admit defeat on this, i have tried for multiple days and i even rebooted before you suggested it to see if it fixed the errors and it didnt but thanks to everyone in the thread that tried to help :)
> 
> Do not admit defeat so easily. I'm not giving up

i sadly am since it was just for tartube (a program to download youtube videos) which is honestly just too much of a hassle for me right now :) i might return back in a week or two but for now it just seems like too much work for such a program :)

**Comment by ZachBacon** [comment]
> > > > @MozartWolfgang Everything alright?
> > > 
> > > 
> > > As silly as it sounds i must admit defeat on this, i have tried for multiple days and i even rebooted before you suggested it to see if it fixed the errors and it didnt but thanks to everyone in the thread that tried to help :)
> > 
> > 
> > Do not admit defeat so easily. I'm not giving up
> 
> i sadly am since it was just for tartube (a program to download youtube videos) which is honestly just too much of a hassle for me right now :) i might return back in a week or two but for now it just seems like too much work for such a program :)

Then, at least try this one last ditch effort.

http://repo.msys2.org/distrib/msys2-x86_64-latest.exe

Try installing that (assuming you used an installer for your current version) and if it doesn't work. Then I'll leave it be till you want to try again.

**Comment by welpdx** [comment]
I having similar issues with Tartube v2.4.077. 
[Reddit post](https://www.reddit.com/r/youtubedl/comments/t0lmmk/tartube_wont_install_ffmpeg_invalid_or_corrupted/) mentions [tartube #371](https://github.com/axcore/tartube/issues/371) thread.

Who is david.macek.0@gmail.com? lol

**Comment by axcore** [comment]
FFmpeg install fails with `msys2-x86_64-20220319.exe` (the version that Tartube installers are using), but succeeds with `msys2-x86_64-20220603.exe`.

**Comment by AndrewTPiotrowski** [comment]
> Try running this
> 
> `pacman-key --refresh-keys`

I have been having a completely a similar issue with an unrelated library. For some reason this fixed my issue. Thank you so much

**Comment by axcore** [comment]
@AndrewTPiotrowski Thanks, I will try that the next time FFmpeg becomes uninstallable.
