### ISSUE TITLE
Update to python-setuptools-52.0.0-1: file conflict

### ISSUE THREAD

**Issue by SiliconWizard** [msys2/MINGW-packages#10684]
Updating to the latest python-setuptools-52.0.0-1 fails (a lot of file conflicts in /usr/lib/python3.9/site-packages/... )

**Comment by lazka** [comment]
which files?

**Comment by SiliconWizard** [comment]
python-setuptools : /usr/lib/python3.9/site-packages/_distutils_hack/__init__.py
python-setuptools : /usr/lib/python3.9/site-packages/_distutils_hack/__pycache__/__init__.cpython-39.pyc
python-setuptools : /usr/lib/python3.9/site-packages/_distutils_hack/__pycache__/override.cpython-39.pyc
...
python-setuptools : /usr/lib/python3.9/site-packages/setuptools/_vendor/packaging/_typing.py

**Comment by lazka** [comment]
This likely means you updated setuptools with pip instead of pacman at one point. You can pass `--overwrite '*'` to pacman to replace those files.

**Comment by SiliconWizard** [comment]
Thanks for the tip - I may have used pip at some point indeed...
