### ISSUE TITLE
Re-building `openssl` fails in clang environments

### ISSUE THREAD

**Issue by mmuetzel** [msys2/MINGW-packages#10681]
Rebuilding `mingw-w64-openssl` is currently failing in clang environments with the error:
```
  /bin/sh: line 1: gcc: command not found
```

See also e.g.:
https://github.com/msys2/MINGW-packages/runs/5083521152?check_suite_focus=true#step:9:276

That is probably because `gcc` is no longer installed as an alias in the clang environments. I guess the build rules are hard coding `gcc`. They should probably be using `$CC` (and `$CXX`).

**Comment by Biswa96** [comment]
Removing the `!buildflags` from options fixes the issue. My assumption is that negating the build flags option prevents getting CC and CXX variables from makepkg_mingw.conf file. But I am not sure if it will cause any further issue.

**Comment by MehdiChinoune** [comment]
`CC` and `CXX` were not exported because of `!buildflags`. You could export them before configuring the project.
Something like:
```SHELL
export CC=${MINGW_PREFIX}/bin/cc.exe
export CXX=${MINGW_PREFIX}/bin/c++.exe
```
or
```SHELL
if [[ ${MINGW_PACKAGE_PREFIX} == *-clang-* ]]; then
  export CC=${MINGW_PREFIX}/bin/clang.exe
  export CXX=${MINGW_PREFIX}/bin/clang++.exe
fi
```

**Comment by mmuetzel** [comment]
I found 43 PKGBUILD files that contain `!buildflags` and a `depends` or `makedepends` on `${MINGW_PACKAGE_PREFIX}-cc`.
Should all of them add commands to export `CC` and `CXX`?

**Comment by MehdiChinoune** [comment]
It depends on the build-systems and the assumption made by the project maintainers. Some assume that mingw==gcc.
CMake and meson (I think also qmake) build-systems they autodetect the compiler depending on the environment. for example CMake search first for GCC then for the other compilers on MINGW.
Some Autotools projects search first for cc/c++ which are provided.

**Comment by mmuetzel** [comment]
> It depends on the build-systems and the assumption made by the project maintainers.

Understood. That probably means that it might be best to wait for a failing package build and fix that on a per-case basis?

**Comment by MehdiChinoune** [comment]
> Understood. That probably means that it might be best to wait for a failing package build and fix that on a per-case basis?

That's my opinion.

**Comment by lazka** [comment]
Maybe we shouldn't unset "CC CXX" in case of "!buildflags"? https://github.com/msys2/msys2-pacman/commit/87d6d92836be00bbf65686df9a4911768bf76461

**Comment by lazka** [comment]
> Maybe we shouldn't unset "CC CXX" in case of "!buildflags"? [msys2/msys2-pacman@87d6d92](https://github.com/msys2/msys2-pacman/commit/87d6d92836be00bbf65686df9a4911768bf76461)

I've created https://github.com/msys2/msys2-pacman/issues/12
