### ISSUE TITLE
mingw-w64-x86_64-wxWidgets3.1 does not include wxWidget github \include\wx\msw\private\graphicsd2d.h file

### ISSUE THREAD

**Issue by acotty** [msys2/MINGW-packages#10691]
I am trying to build CodeBlocks IDE using MSYS2 via a configure/makefile process as done on Linux. On Windows I got the error below as the \include\wx\msw\private\graphicsd2d.h file that is in the Wxwidget gitHub repo for 3.1.5 is not included in the mingw-w64-x86_64-wxWidgets3.1 pacman install. The normal CodeBlocks build process for Windows is to grab the 3.1.5 source that includes the file and build the wxWidget DLL's from the source and use the source directory in the build, which works as the file exists.

It looks like the real problem is that the following github directory is missing from the MSYS2 package: 
https://github.com/wxWidgets/wxWidgets/tree/master/include/wx/msw/private

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../../src/include -IC:/msys64/mingw64/lib/wx/include/msw-unicode-3.1 -IC:/msys64/mingw64/include/wx-3.1 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMSW__ -fpermissive -I./include -I./src/scintilla/include -I./src/scintilla/lexlib -I./src/scintilla/src -DSCI_LEXER -DLINK_LEXERS -DGTK -D__WX__ -DCB_AUTOCONF -DCB_PRECOMP -DPIC -I../../../src/include/tinyxml -DTIXML_USE_STL=YES -O2 -ffast-math -Winvalid-pch -fPIC -fexceptions -MT src/PlatWX.lo -MD -MP -MF src/.deps/PlatWX.Tpo -c src/PlatWX.cpp  -DDLL_EXPORT -DPIC -o src/.libs/PlatWX.o
In file included from src/PlatWX.cpp:53:
src/PlatWX.h:66:10: fatal error: wx/msw/private/graphicsd2d.h: No such file or directory
   66 | #include "wx/msw/private/graphicsd2d.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

```

**Comment by Biswa96** [comment]
The include path `wx/msw/private/` does not match with any WxWidgets packages. It seems that CodeBlocks is using the bundled WxWidgets source files which does not have graphicsd2d.h.

**Comment by acotty** [comment]
If you download the wxWidgets source then it includes all of the include\ sub directories, but the mingw64/mingw-w64-x86_64-wxmsw3.1 3.1.5-6 package does not include all of the include\ sub directories.

**Comment by Biswa96** [comment]
My speculation is that the header files in `wx/msw/private/` are meant to be used within wxWidgets project, not by other projects.

> use the source directory in the build, which works as the file exists.

Hence, CodeBlocks suggest to use wxWidgets from source.

**Comment by asmwarrior** [comment]
https://github.com/wxWidgets/wxWidgets/blob/db3e54b3dc5a4af812dea6e3945a2339ab01cbe2/src/stc/PlatWX.h#L167-L203

It looks like the ` wxUSE_GRAPHICS_DIRECT2D` should be defined.

My question is: Does the mingw64/mingw-w64-x86_64-wxmsw3.1 3.1.5-6 package has this option enabled?

If  this option is enabled, and I think it would better to ship this header file.

The reason why Code::Blocks need this wx/msw/private/graphicsd2d.h is that Code::Blocks has its own implementation of wxScintilla in it's source, when bulding Code::Blocks, the wx/msw/private/graphicsd2d.h is needed.

**Comment by asmwarrior** [comment]
Well, it looks like the option is disabled.

See this pull request:

[wxWidgets3.1: Remove setting wxUSE_GRAPHICS_DIRECT2D by stahta01 · Pull Request #9396 · msys2/MINGW-packages](https://github.com/msys2/MINGW-packages/pull/9396)

**Comment by Biswa96** [comment]
@stahta01 Can d2d be enabled in wxWidgets? Wondering if the issue is in wxWidgets or in CodeLite.

**Comment by stahta01** [comment]
It worked for me; so I guess you are doing something different than I did.

Are you using the MSys2 MinGW wxWidgets3.1 package to install wxWidgets 3.1?
Did you also install wxWidgets or not?
The wx-config is in wxWidgets.

Tim S.

**Comment by acotty** [comment]
As per my original post I was back then using the mingw-w64-x86_64-wxWidgets3.1 package.
Back then I was not using the local wxWidgets build, but trying to use the mingw-w64-x86_64-wxWidgets3.1 package.
The wx-config used for the build back then was what ever was in the MSYS2 directory structure.

When you say "It worked for me", what package did you use, what build process did you use and were there any changes needed or made to get it to work?

**Comment by stahta01** [comment]
I forget; it been about 6 months ago. And, CodeLite has changed a lot and maybe wxWidgets has changed enough to break something. And, I likely also used either an MSys2 package or cmake to build CodeLite since configure/make is not the proper way to build CodeLite.

The patch that was removed was only needed when building using makefile.gcc instead of configure/make method of build wxWidgets.

Tim S.

**Comment by stahta01** [comment]
FYI: Getting Code::Blocks to build requires work!
CodeLite is not Code::Blocks!

Tim S.

**Comment by stahta01** [comment]
You might ask if having a separate wx package for the private headers would be acceptable. Then the wxWidgets3.1 package  could create the separate private headers needed by Code::Blocks.
The likely method would be a split package instead of an separate package. But, I think adding the private wx headers to an Code::Blocks package is cleaner.

Tim S.
