### ISSUE TITLE
Not installing libosmgps

### ISSUE THREAD

**Issue by programmin1** [msys2/MINGW-packages#10703]
It's not installing libosmgps openstreetmap display library: 

error: target not found: mingw-w64-osm-gps-map

Do I need to add a repository somehow for this?

**Comment by Biswa96** [comment]
The package name is wrong. See the package list here https://packages.msys2.org/base/mingw-w64-osm-gps-map. For example, 64 bit gcc compiled package is [mingw-w64-x86_64-osm-gps-map](https://packages.msys2.org/package/mingw-w64-x86_64-osm-gps-map?repo=mingw64).
