### ISSUE TITLE
sys/socket.h: No such file or directory

### ISSUE THREAD

**Issue by zhangjp0405** [msys2/MINGW-packages#10712]
I get the following error fatal error: sys/socket.h: No such file or directory
![微信截图_20220209125348](https://user-images.githubusercontent.com/48978473/153124671-840bb5e7-6779-43f9-b44d-fb7c2bf036c8.png)

**Comment by Biswa96** [comment]
sys/socket.h is not for native Windows platform. The Windows alternative will be winsock.h or winsock2.h. Either port the program for native Windows platform or use cygwin/msys2 environment to compile it.
