### ISSUE TITLE
nul: invalid argument

### ISSUE THREAD

**Issue by zap8600** [msys2/MINGW-packages#10730]
Hi. I'm trying to compile gcc 7.1.0. It fails running `s-selftest`. It gives me the error: `nul: invalid argument`. How do I fix it?

**Comment by Biswa96** [comment]
Why are you trying to compile older compiler?

**Comment by Biswa96** [comment]
> I am trying to build another person port of GCC 6 that targets 6502 CPU.

Not related to msys2 or mingw-packages repository.

> No idea why the OP was trying to build gcc 7.1.0.

**Comment by stahta01** [comment]
> > I am trying to build another person port of GCC 6 that targets 6502 CPU.
> 
> Not related to msys2 or mingw-packages repository.
> 
> > No idea why the OP was trying to build gcc 7.1.0.
> 
> OP did not explained it as well 🤷

Since, it works with MINGW64 and MINGW32; but, not with UCRT64 I do think the argument is that it is related to MSys2 MinGW project. But, it is not closely related. This was the top hit when searching on the bug, I was expecting an GCC hit somewhere. 

Tim S.

**Comment by Biswa96** [comment]
gcc 6[^1] and gcc 7[^2] is no longer supported.

[^1]: https://gcc.gnu.org/gcc-6/
[^2]: https://gcc.gnu.org/gcc-7/
