### ISSUE TITLE
Building mingw32 gnutls/PKGBUILD   error: you must have sys_stat.h on your system

### ISSUE THREAD

**Issue by macoomac** [msys2/MINGW-packages#10754]
download  https://mirrors.kernel.org/sourceware/cygwin/x86_64/release/gnutls/gnutls-3.6.9-1-src.tar.xz

patch -p1 -i ${srcdir}/gnulib-weak.patch
autoreconf -vfi
./configure \
    --build=x86_64-w64-mingw32 \
    --prefix="$HOME/prefix" \
	--disable-tests \
    --enable-shared \
    --enable-static \
    --disable-guile \
    --enable-cxx \
    --disable-hardware-acceleration \
    --enable-heartbeat-support \
	--with-included-unistring \
    --with-default-trust-store-file=/usr/ssl/certs/ca-bundle.crt

....
configure:62345: error: you must have sys_stat.h on your system

**Comment by Biswa96** [comment]
For mingw32, the target triplet should be i686-w64-mingw32. Also check if you are in correct build environment, the prompt text should have mingw32.

**Comment by macoomac** [comment]
> For mingw32, the target triplet should be i686-w64-mingw32. Also check if you are in correct build environment, the prompt text should have mingw32.

./configure \
    --build=x86_64-w64-mingw32 \
    --prefix="$HOME/prefix" \
....
configure:62345: error: you must have sys_stat.h on your system

**Comment by class101** [comment]
Possible releated issue
https://github.com/msys2/MINGW-packages/issues/10761#issuecomment-1041432136

(let me know if more convenient to open a newer ticket for this, as of writing, I'm unaware if this is a known/unknown issue)

**Comment by macoomac** [comment]
https://github.com/msys2/MINGW-packages/issues/10761#issuecomment-1041432136
