### ISSUE TITLE
binutils 2.38-1 issue with thin static library archives

### ISSUE THREAD

**Issue by lb90** [msys2/MINGW-packages#10860]
Since upgrading to mingw-w64-x86_64-gcc version 11.2.0-9, gcc-ar cannot create static library archives anymore. This can be seen while running Meson:

```
[3/36] Linking static target gdk/win32/libgdk-win32.a
FAILED: gdk/win32/libgdk-win32.a
"gcc-ar" "csrDT" gdk/win32/libgdk-win32.a gdk/win32/libgdk-win32.a.p/gdkcairocontext-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkcursor-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkclipboard-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkclipdrop-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkdevicemanager-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkdevice-virtual.c.obj gdk/win32/libgdk-win32.a.p/gdkdevice-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkdevice-winpointer.c.obj gdk/win32/libgdk-win32.a.p/gdkdevice-wintab.c.obj gdk/win32/libgdk-win32.a.p/gdkdisplay-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkdisplaymanager-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkdrag-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkdrop-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkevents-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkglcontext-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkglcontext-win32-wgl.c.obj gdk/win32/libgdk-win32.a.p/gdkglobals-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkhdataoutputstream-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkinput-winpointer.c.obj gdk/win32/libgdk-win32.a.p/gdkkeys-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkkeys-win32-impl.c.obj gdk/win32/libgdk-win32.a.p/gdkkeys-win32-impl-wow64.c.obj gdk/win32/libgdk-win32.a.p/gdkwin32langnotification.c.obj gdk/win32/libgdk-win32.a.p/gdkmain-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkmonitor-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkproperty-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkscreen-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkvulkancontext-win32.c.obj gdk/win32/libgdk-win32.a.p/gdkwin32id.c.obj gdk/win32/libgdk-win32.a.p/gdksurface-win32.c.obj
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ar.exe: gdk/win32/libgdk-win32.a: malformed archive
[4/36] Linking static target gdk/libgdk.a
FAILED: gdk/libgdk.a
"gcc-ar" csrDT gdk/libgdk.a @gdk/libgdk.a.rsp
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ar.exe: gdk/libgdk.a: malformed archive
ninja: build stopped: subcommand failed.
```

In fact the generated libgdk-win32.a archive contains no code at all: [libgdk-win32.a.txt](https://github.com/msys2/MINGW-packages/files/8140282/libgdk-win32.a.txt)

To make it work I have to remove the "T" argument that specifies to create thin static libraries. Without that argument gcc-ar generates libgdk-win32.a correctly (it contains all object files).

**Comment by lb90** [comment]
How to reproduce:

1. git clone https://gitlab.gnome.org/GNOME/gtk.git
2. mkdir gtk4-build && cd gtk4-build
3. meson ../gtk4 --buildtype=debug -Dintrospection=disabled -Dbuild-tests=false
4. ninja

The first ninja run completes correctly.

Now edit a file, e.g. `gdk/win32/gdkevents-win32.c`, and trigger a rebuild with `ninja`. Rebuilding will fail with the "malformed archive" error. Note `how gdk/win32/libgdk-win32.a` is too small in size and contains no object code at all.

**Comment by lb90** [comment]
I have `ccache` installed and Meson automatically makes use of that. I'm going to try now if disabling it makes any difference.

**Comment by lazka** [comment]
(we also updated binutils recently)

**Comment by lb90** [comment]
Disabling ccache did not make any difference. Now I'm going to downgrade gcc or binutils

**Comment by lb90** [comment]
Downgrading `mingw-w64-x86_64-binutils` from `2.38-1` to `2.37-5` fixes it for me! \o/

Thank you

**Comment by lb90** [comment]
@lazka out of curiosity, were you able to reproduce?

**Comment by lazka** [comment]
I just tried https://github.com/msys2/MINGW-packages/issues/10860#issuecomment-1050723820 in both mingw64 and ucrt64 and I can't reproduce.

```
$ touch ../gdk/win32/gdkevents-win32.c
$ ninja
...
$ ls -lh ./gdk/win32/libgdk-win32.a
-rw-r--r-- 1 user None 13K Feb 25 14:56 ./gdk/win32/libgdk-win32.a
```

**Comment by lb90** [comment]
If the content does not change it worked even for me. Try adding an (unused) variable inside a function. Whatever changes the object code

**Comment by lazka** [comment]
I see, with that I can reproduce.

**Comment by lb90** [comment]
Do you think I should open an issue in sourceware bugzilla?

**Comment by lb90** [comment]
Opened a ticket upstream about this issue: https://sourceware.org/bugzilla/show_bug.cgi?id=28929
