### ISSUE TITLE
Python fails calling a Fortran DLL compiled by gfortran in MinGW x64

### ISSUE THREAD

**Issue by XiaodongLiangDTU** [msys2/MINGW-packages#10875]
I have a Fortran package, from which a DLL can be successfully compiled by the Intel Fortran Compiler. The built DLL can be called successfully by MATLAB and Python (in both VS and VS Code) codes in Windows (the Python code is also tested working in Linux). Recently, I am trying to use MinGW x64 (gfortran) to build the software for Windows. I can successfully compile the Fortran DLL. This Fortran DLL can be successfully called by the MATLAB code, but it cannot be called by the Python code (in neither VS nor VS Code). However, the Python code can run successfully in the MinGW x64 environment (can also plot normally). The error of the Python code (in both VS and VS Code) is "FileNotFoundError: Could not find module 'XXX.DLL' (or one of its dependencies)". I checked (using dumpbin) that the built DLL depends on KERNEL32.dll, msvcrt.dll, libgcc_s_seh-1.dll and libgfortran-5.dll. After copying the last two DLL files (from C:\msys64\mingw64\bin to the same folder of the Fortran DLL), it is still not working. Any advices/suggestions/comments I can solve the problem? Thank you.

**Comment by Biswa96** [comment]
Try to add the `C:\msys64\mingw64\bin` in PATH environment variable. Maybe you are missing some other dependent DLLs. This tool can help to find the dependencies https://github.com/lucasg/dependencies

**Comment by MehdiChinoune** [comment]
Are you using the official Python (built against MSVC) or the MINGW one (mingw-w64-x86_64-python).
I don't think the MSC Python could load MINGW DLLs. Try to execute your code from MINGW shell.

**Comment by XiaodongLiangDTU** [comment]
> Try to add the `C:\msys64\mingw64\bin` in PATH environment variable. Maybe you are missing some other dependent DLLs. This tool can help to find the dependencies https://github.com/lucasg/dependencies

Thanks, but it is still not working after adding that folder in to the PATH environment variable.

**Comment by XiaodongLiangDTU** [comment]
> Are you using the official Python (built against MSVC) or the MINGW one (mingw-w64-x86_64-python). I don't think the MSC Python could load MINGW DLLs. Try to execute your code from MINGW shell.

Thanks. Yes, it is working with the MinGW Shell.

**Comment by raedrizqie** [comment]
try copying libwinpthread-1.dll also..

**Comment by XiaodongLiangDTU** [comment]
> try copying libwinpthread-1.dll also..

Thank you. I have tried, and it is not working, either.

**Comment by raedrizqie** [comment]
did you copied libquadmath-0.dll also?

**Comment by XiaodongLiangDTU** [comment]
> did you copied libquadmath-0.dll also?

Thanks, fantastic! It seems that it is working now... But when I added "C:\msys64\mingw64\bin" into $PATH$, it was not working. Why?

**Comment by XiaodongLiangDTU** [comment]
> did you copied libquadmath-0.dll also?

So I have made a few more tests, and it seems that both DLL files you mentioned are needed. Is there any possibility to included all these DLLs (libs) into a single DLL file (something similar to Intel ifort's option /MT)? Thanks again.

**Comment by raedrizqie** [comment]
maybe you could try linking your dll with static gfortran lib.. but there is no way (i think) to automatically link to static libgfortran, as opposed to '-static-libgcc' for gcc lib, because there no no '-static-libgfortran' option..

you can, try linking like this: '-l:libgfortran.a -l:libquadmath.a -l:libpthread.a' to remove dependencies of those 3 dlls
