### ISSUE TITLE
How to bump the python-coverage package to 6.3?

### ISSUE THREAD

**Issue by Paebbels** [msys2/MINGW-packages#10877]
The Package `***-python-coverage` is outdated (since 25.01.2022).  
How can I help to bump the version to v6.3.x?

Package: https://packages.msys2.org/package/mingw-w64-x86_64-python-coverage
Source: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-python-coverage

According to the package list:
* it's not in the queue: https://packages.msys2.org/queue 
* But also not outdated: https://packages.msys2.org/outofdate

**How are outdated packages detected?**
PyPI: https://pypi.org/project/coverage/
GitHub: https://github.com/nedbat/coveragepy/releases

------------------
I have an interest in this package being provided via pacman, because it contains binary code and can't be installed via PIP in MSYS2.

-----------------
/cc @umarcor

**Comment by MehdiChinoune** [comment]
> The Package `***-python-coverage` is outdated (since 25.01.2022). How can I help to bump the version to v6.3.x?

- clone this repo
- create a new branch
- edit `mingw-w64-python-coverage/PKGBUILD` file by bumping `pkgver` to 6.3 and changing sha256sums of its source archive.
- push your branch
- open a pull-request

> * it's not in the queue: https://packages.msys2.org/queue

because It was not updated
> * But also not outdated: https://packages.msys2.org/outofdate
> **How are outdated packages detected?** 

because It was not updated in ArchLinux as MSYS2 check its databases.

**Comment by Paebbels** [comment]
How to find the `sha256sums`?

Is it provided by GitHub?
Or should i compute my self on a local machine (this would break the idea of the checksum ...)?
