### ISSUE TITLE
ruby: broken in CLANG32 on Windows 11/Server 2022

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#10896]
yeah, ruby is broken there, just running it gives the same error. Downgrading it doesn't help.

_Originally posted by @lazka in https://github.com/msys2/MINGW-packages/issues/10878#issuecomment-1057397880_

Results of investigation:
https://github.com/ruby/ruby/blob/v3_0_3/win32/win32.c#L2591 😱

wow, yeah, `ucrtbase!_isatty` disassembly is majorly different on win11 
I think the code would actually still work, except they no longer use `pop ebp` as the last instruction before `ret`, but rather `leave`
so the pattern no longer finds the end of the function
but given the code is majorly changed, there's a chance the internal struct has changed too
but this is not limited to us, either.  32-bit upstream ruby should be broken on Windows 11 too.  Maybe there's not much use of that?

**Comment by lazka** [comment]
I've filed a bug upstream: https://bugs.ruby-lang.org/issues/18605

**Comment by jeremyd2019** [comment]
There's also a high likelihood this will break on Windows on ARM.  In addition to requiring new patterns to match the ARM64 and ARM32 assembly, the x64/x32 running under emulation would see something strange because Microsoft supports 'thunks' for calling from emulated x64/x32 into ARM64 DLLs, and I saw evidence of that in ucrtbase.dll.

**Comment by Biswa96** [comment]
Depending on exact CPU instructions to get a hidden structure pointer is itself a broken idea. They have to rewrite all the `__pioinfo` related code.
