### ISSUE TITLE
[nlohmann-json] lacks `json_fwd.hpp`

### ISSUE THREAD

**Issue by That-Human-Being** [msys2/MINGW-packages#10902]
I was trying to build a project that required [json_fwd.hpp](https://raw.githubusercontent.com/nlohmann/json/develop/include/nlohmann/json_fwd.hpp) from the nlohmann-json repo, it goes in `mingw64\include\nlohmann` it should be included in the package downloaded with pacman

**Comment by Biswa96** [comment]
The nlohmann-json package is built without JSON_MultipleHeaders option. So, there is only one header file json.hpp. The project need to include that file only. If multiple headers file are required it can be enabled.
