### ISSUE TITLE
`libglut.a` exists only on x86 environments!

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#10915]
Rebuilding `mingw-w64-partio` to fix its runtime dependencies failed because it picks `libglut.a` in i386 environments when searching for `GLUT` library.
It turns out that `libglut.a` exists only in i386 envs as a part of `mingw-w64-crt-git` package.
This failure didn't occur before because `mingw-w64-crt-git` was installed under `${MINGW_PREFIX}/${MINGW_CHOST}`.

**Comment by MehdiChinoune** [comment]
Fixed by passing `-DGLUT_glut_LIBRARY_RELEASE=${MINGW_PREFIX}/lib/libfreeglut.dll.a` to cmake.

**Comment by sskras** [comment]
Was this not a bug, or was this bug just fixed ?
