### ISSUE TITLE
wxWidgets is not found from CMake when using Ninja in MSYS

### ISSUE THREAD

**Issue by MarBg92** [msys2/MINGW-packages#10963]
I have installed the packages `mingw64/mingw-w64-x86_64-wxmsw3.1` and `mingw64/mingw-w64-x86_64-cmake`

CMake does find wxWidgets only if using the „MSYS Makefiles“, but not when using any other generator like „Ninja“ or „MinGW Makefiles“:

```
$ cmake -S . -B build_ninja/ -G "Ninja"
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES wxWidgets_INCLUDE_DIRS)
-- WIN32 = 1
-- CYGWIN =
-- MSYS =
-- CMAKE_CROSSCOMPILING = FALSE
-- wxWidgets_FIND_STYLE = win32
-- Configuring done
-- Generating done
-- Build files have been written to: C:/msys64/home/Mario/wxDemo/build_ninja
```

```
$ cmake -S . -B build_mingwmakefiles/ -G "MinGW Makefiles"
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES wxWidgets_INCLUDE_DIRS)
-- WIN32 = 1
-- CYGWIN =
-- MSYS =
-- CMAKE_CROSSCOMPILING = FALSE
-- wxWidgets_FIND_STYLE = win32
-- Configuring done
-- Generating done
-- Build files have been written to: C:/msys64/home/Mario/wxDemo/build_mingwmakefiles
```

```
$ cmake -S . -B build_msysmakefiles/ -G "MSYS Makefiles"
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found wxWidgets: -LC:/msys64/mingw64/lib;;;-pipe;-Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high;-Wl,--subsystem,windows;-mwindows;-lwx_mswu_xrc-3.1;-lwx_mswu_html-3.1;-lwx_mswu_qa-3.1;-lwx_mswu_core-3.1;-lwx_baseu_xml-3.1;-lwx_baseu_net-3.1;-lwx_baseu-3.1 (found version "3.1.5")
-- WIN32 = 1
-- CYGWIN =
-- MSYS = 1
-- CMAKE_CROSSCOMPILING = FALSE
-- wxWidgets_FIND_STYLE = unix
-- Configuring done
-- Generating done
-- Build files have been written to: C:/msys64/home/Mario/wxDemo/build_msysmakefiles
```

The CMakeLists.txt I used:
```
cmake_minimum_required(VERSION 3.20)

project(Demo)

find_package(wxWidgets)

message(STATUS "WIN32 = ${WIN32}")
message(STATUS "CYGWIN = ${CYGWIN}")
message(STATUS "MSYS = ${MSYS}")
message(STATUS "CMAKE_CROSSCOMPILING = ${CMAKE_CROSSCOMPILING}")
message(STATUS "wxWidgets_FIND_STYLE = ${wxWidgets_FIND_STYLE}")
```

I suspect the root cause is how the FindwxWidgets.cmake script (https://github.com/Kitware/CMake/blob/master/Modules/FindwxWidgets.cmake) determinates the path styles, which it uses:

```
#=====================================================================
# Determine whether unix or win32 paths should be used
#=====================================================================
if(WIN32 AND NOT CYGWIN AND NOT MSYS AND NOT CMAKE_CROSSCOMPILING)
  set(wxWidgets_FIND_STYLE "win32")
else()
  set(wxWidgets_FIND_STYLE "unix")
endif()
```

The MSYS variable is only set if the the „MSYS Makefiles“ generator is used, which sets the wxWidgets_FIND_STYLE to "unix". In all other cases wxWidgets_FIND_STYLE is set to "win32". But because MSYS emulates an Unix environment, the MSYS variable should be always set to 1, so the if-statement will set the wxWidgets_FIND_STYLE to "unix".

**Comment by MarBg92** [comment]
It works with this patch. Thank you!

```
$ cmake -S . -B build_ninja/ -G "Ninja"
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found wxWidgets: -LC:/msys64/mingw64/lib;;;-pipe;-Wl,--subsystem,windows;-mwindows;-lwx_mswu_xrc-3.0;-lwx_mswu_webview-3.0;-lwx_mswu_html-3.0;-lwx_mswu_qa-3.0;-lwx_mswu_adv-3.0;-lwx_mswu_core-3.0;-lwx_baseu_xml-3.0;-lwx_baseu_net-3.0;-lwx_baseu-3.0 (found version "3.0.5")
-- WIN32 = 1
-- CYGWIN =
-- MSYS =
-- CMAKE_CROSSCOMPILING = FALSE
-- wxWidgets_FIND_STYLE = unix
-- Configuring done
-- Generating done
-- Build files have been written to: C:/msys64/home/Mario/wxDemo/build_ninja
```

**Comment by asmwarrior** [comment]
Hi, guys, it looks like currently, the mingw64 cmake can't find wxWidgets 3.1 if you have both wxWidgets 3.0 and 3.1 libraries installed by pacman.

I wrote some logs here: https://github.com/msys2/MINGW-packages/issues/9182#issuecomment-1112947021

BTW: I see that the patch get merged: [FindwxWidgets: set wxWidgets_FIND_STYLE to unix on MINGW (!7162) · Merge requests · CMake / CMake · GitLab](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7162)
I'm not sure, but for builds with MinGW compilers, does all kinds libs and includes has the same structure?
The wx library under msys2 is build with `configure` command, while in other cases, for example people may build wx library under Windows `CMD` by the `mingw32-make.exe`, so there result file/folder structure is not the same.

**Comment by asmwarrior** [comment]
> I have installed the packages `mingw64/mingw-w64-x86_64-wxmsw3.1` and `mingw64/mingw-w64-x86_64-cmake`
> 
> CMake does find wxWidgets only if using the „MSYS Makefiles“, but not when using any other generator like „Ninja“ or „MinGW Makefiles“:
> 
> ```
> $ cmake -S . -B build_ninja/ -G "Ninja"
> -- The C compiler identification is GNU 11.2.0
> -- The CXX compiler identification is GNU 11.2.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES wxWidgets_INCLUDE_DIRS)
> -- WIN32 = 1
> -- CYGWIN =
> -- MSYS =
> -- CMAKE_CROSSCOMPILING = FALSE
> -- wxWidgets_FIND_STYLE = win32
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/msys64/home/Mario/wxDemo/build_ninja
> ```
> 
> ```
> $ cmake -S . -B build_mingwmakefiles/ -G "MinGW Makefiles"
> -- The C compiler identification is GNU 11.2.0
> -- The CXX compiler identification is GNU 11.2.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES wxWidgets_INCLUDE_DIRS)
> -- WIN32 = 1
> -- CYGWIN =
> -- MSYS =
> -- CMAKE_CROSSCOMPILING = FALSE
> -- wxWidgets_FIND_STYLE = win32
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/msys64/home/Mario/wxDemo/build_mingwmakefiles
> ```
> 
> ```
> $ cmake -S . -B build_msysmakefiles/ -G "MSYS Makefiles"
> -- The C compiler identification is GNU 11.2.0
> -- The CXX compiler identification is GNU 11.2.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found wxWidgets: -LC:/msys64/mingw64/lib;;;-pipe;-Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high;-Wl,--subsystem,windows;-mwindows;-lwx_mswu_xrc-3.1;-lwx_mswu_html-3.1;-lwx_mswu_qa-3.1;-lwx_mswu_core-3.1;-lwx_baseu_xml-3.1;-lwx_baseu_net-3.1;-lwx_baseu-3.1 (found version "3.1.5")
> -- WIN32 = 1
> -- CYGWIN =
> -- MSYS = 1
> -- CMAKE_CROSSCOMPILING = FALSE
> -- wxWidgets_FIND_STYLE = unix
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/msys64/home/Mario/wxDemo/build_msysmakefiles
> ```
> 
> The CMakeLists.txt I used:
> 
> ```
> cmake_minimum_required(VERSION 3.20)
> 
> project(Demo)
> 
> find_package(wxWidgets)
> 
> message(STATUS "WIN32 = ${WIN32}")
> message(STATUS "CYGWIN = ${CYGWIN}")
> message(STATUS "MSYS = ${MSYS}")
> message(STATUS "CMAKE_CROSSCOMPILING = ${CMAKE_CROSSCOMPILING}")
> message(STATUS "wxWidgets_FIND_STYLE = ${wxWidgets_FIND_STYLE}")
> ```
> 
> I suspect the root cause is how the FindwxWidgets.cmake script (https://github.com/Kitware/CMake/blob/master/Modules/FindwxWidgets.cmake) determinates the path styles, which it uses:
> 
> ```
> #=====================================================================
> # Determine whether unix or win32 paths should be used
> #=====================================================================
> if(WIN32 AND NOT CYGWIN AND NOT MSYS AND NOT CMAKE_CROSSCOMPILING)
>   set(wxWidgets_FIND_STYLE "win32")
> else()
>   set(wxWidgets_FIND_STYLE "unix")
> endif()
> ```
> 
> The MSYS variable is only set if the the „MSYS Makefiles“ generator is used, which sets the wxWidgets_FIND_STYLE to "unix". In all other cases wxWidgets_FIND_STYLE is set to "win32". But because MSYS emulates an Unix environment, the MSYS variable should be always set to 1, so the if-statement will set the wxWidgets_FIND_STYLE to "unix".

Hi, this issue lasts for a very long time. I have a post here: [Re: Using wxWidgets with Win10, msys2, mingw64 and CLion](https://forums.wxwidgets.org/viewtopic.php?p=202984#p202984) .

The reason why "unix" style is needed is that the wx package installed by pacman is built by the `configure` and `build` steps, and its result file structure is just the same as under unix/linux systems.

But if you build wx by mingw compiler under normal Windows `cmd` command line by the `mingw32-make`, the result is different. So, I guess this patch( [FindwxWidgets: set wxWidgets_FIND_STYLE to unix on MINGW (!7162) · Merge requests · CMake / CMake · GitLab](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7162) ) may cause some side effects.






But please not that the change of the wxWidgets_FIND_STYLE to "unix" may cause other issues.

**Comment by MehdiChinoune** [comment]
Your issue has nothing to with this one.

CMake prefer WxWidgets 3.0 over 3.1 because it searches first for non-suffixed wx-config then for the suffixed wx-config-X.Y
see: https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindwxWidgets.cmake#L776
There are two options to solve your issue:
1- Mark WxWidgets 3.0 and 3.1 as conflicting packages.
2- Rename wx-config from 3.0 version instead of 3.1

**Comment by asmwarrior** [comment]
> Your issue has nothing to with this one.
> 
> CMake prefer WxWidgets 3.0 over 3.1 because it searches first for non-suffixed wx-config then for the suffixed wx-config-X.Y see: https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindwxWidgets.cmake#L776 There are two options to solve your issue: 1- `export WX_CONFIG=${MINGW_PREFIX}/bin/wx-config-3.1` before calling cmake for the first time. 1- Mark WxWidgets 3.0 and 3.1 as conflicting packages. 2- Rename wx-config from 3.0 version instead of 3.1

Hi, @MehdiChinoune thanks for the reply.
With the patch:  [FindwxWidgets: set wxWidgets_FIND_STYLE to unix on MINGW (!7162) · Merge requests · CMake / CMake · GitLab](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7162)
Now, I can use cmake.exe to correctly find wx 3.0 library in mingw64, under both the normal Windows `cmd` (I have mingw64/bin folder in the PATH) and the shell started by the `mingw64.exe`. This is great.

I will try the method you suggested to distinguish the different wx version installed by pacman.

BTW: Is there any way that I can set the `wx-config` inside the `CMakeFiles.txt`? Thanks.

**Comment by asmwarrior** [comment]
> Mark WxWidgets 3.0 and 3.1 as conflicting packages.

I just searched for a while, and I can't find how to do this, can you give me a direction? Thanks.

**Comment by MehdiChinoune** [comment]
> > Mark WxWidgets 3.0 and 3.1 as conflicting packages.
> 
> I just searched for a while, and I can't find how to do this, can you give me a direction? Thanks.

This is for maintainers, for you remove WxWidgets 3.0

**Comment by asmwarrior** [comment]
The method one dose not work if I set the env to either `wx-config` or `wx-config-3.1`

See the log below if I set to `wx-config`

~~~~
#  cmake -G"MinGW Makefiles" ../
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: F:/code/msys2-64/mingw64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: F:/code/msys2-64/mingw64/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(176): wxWidgets_FIND_COMPONENTS : core;base
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(176): wxWidgets_SELECT_OPTIONS=--debug=no;--static=no
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(180): wxWidgets_CXX_FLAGS=-IF:/code/msys2-64/mingw64/lib/wx/include/msw-unicode-3.0 -IF:/code/msys2-64/mingw64/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMSW__ -fpermissive
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(180): wxWidgets_DEFINITIONS=_FILE_OFFSET_BITS=64;WXUSINGDLL;__WXMSW__
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(180): wxWidgets_INCLUDE_DIRS=F:/code/msys2-64/mingw64/lib/wx/include/msw-unicode-3.0;F:/code/msys2-64/mingw64/include/wx-3.0
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(180): wxWidgets_CXX_FLAGS=-fpermissive
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(180): wxWidgets required components : core;base
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(180): wxWidgets optional components :
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(180): wxWidgets_LIBRARIES=-LF:/code/msys2-64/mingw64/lib;;;-pipe;-Wl,--subsystem,windows;-mwindows;-lwx_mswu_core-3.0;-lwx_baseu-3.0
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(180): wxWidgets_LIBRARY_DIRS=F:/code/msys2-64/mingw64/lib
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(176): _wx_filename:  F:/code/msys2-64/mingw64/include/wx-3.0/wx/version.h
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(176): wxWidgets_VERSION_STRING:    3.0.5
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(176): wxWidgets_FOUND           : TRUE
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(176): wxWidgets_INCLUDE_DIRS    : F:/code/msys2-64/mingw64/lib/wx/include/msw-unicode-3.0;F:/code/msys2-64/mingw64/include/wx-3.0
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(176): wxWidgets_LIBRARY_DIRS    : F:/code/msys2-64/mingw64/lib
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(176): wxWidgets_LIBRARIES       : -LF:/code/msys2-64/mingw64/lib;;;-pipe;-Wl,--subsystem,windows;-mwindows;-lwx_mswu_core-3.0;-lwx_baseu-3.0
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(176): wxWidgets_CXX_FLAGS       : -fpermissive
-- F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake(176): wxWidgets_USE_FILE        : F:/code/msys2-64/mingw64/share/cmake/Modules/UsewxWidgets.cmake
CMake Error at F:/code/msys2-64/mingw64/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: core base) (found suitable version
  "3.0.5", minimum required is "3.0")
Call Stack (most recent call first):
  F:/code/msys2-64/mingw64/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  F:/code/msys2-64/mingw64/share/cmake/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
  CMakeLists.txt:36 (find_package)


-- Configuring incomplete, errors occurred!
See also "F:/code/v3.0.5.1samples/minimal/build/CMakeFiles/CMakeOutput.log".

~~~~

**Comment by MehdiChinoune** [comment]
The important thing is that issue is not related to this issue, So go back to your original issue and complain there.

**Comment by asmwarrior** [comment]
> The important thing is that issue is not related to this issue, So go back to your original issue and complain there.

OK, I will start a new issue, since the original issue is not the exact one either.
