### ISSUE TITLE
[netcdf] CMake config refers to missing libszip.dll.a

### ISSUE THREAD

**Issue by dg0yt** [msys2/MINGW-packages#10993]
The CMake config file for  mingw-w64-x86_64-netcdf has a dependency on libszip.dll.a:
~~~
$ grep -R szip /mingw64/lib/cmake/netCDF/
/mingw64/lib/cmake/netCDF/netCDFTargets.cmake:  INTERFACE_LINK_LIBRARIES "hdf5_hl-shared;hdf5-shared;${_IMPORT_PREFIX}/lib/libszip.dll.a;${_IMPORT_PREFIX}/lib/libcurl.dll.a"
~~~

AFAIU this file doesn't exist. There is only libsz.dll.a from libaec.
(I assume that netCDFTarget.cmake is simply exported from the CMake build of netcdf. This makes me wonder how it can export an import library which doesn't exist...)

(Detected in GDAL CI while switching from a netcdf find module to cmake config.)

**Comment by Biswa96** [comment]
Yes, I confirm this issue. Rebuilding the package solves it but there is an issue in netcdf cmake file. Let me ask that in upstream quickly.

**Comment by Biswa96** [comment]
Opps, it seems to be a different issue but not related with this. If libzip present the cmake shows this:

```
-- Found Zip: headers at F:/msys64/ucrt64/include, libraries at F:/msys64/ucrt64/lib
--      library is debug;F:/msys64/ucrt64/lib/libzip.dll.a;optimized;F:/msys64/ucrt64/lib/libzip.dll.a
```

Then errors with this:

```
CMake Error at liblib/CMakeLists.txt:124 (TARGET_LINK_LIBRARIES):
  The "optimized" argument must be followed by a library.
```

It find libzip.dll.a twice as debug and optimized builds.
