### ISSUE TITLE
cairo on clangarm64 failed

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#11053]
```
2022-03-20T18:32:56.9153375Z ../cairo-1.17.6/src/win32/cairo-dwrite-font.cpp:726:30: error: use of undeclared identifier '_CW_DEFAULT'
2022-03-20T18:32:56.9154012Z         _controlfp_s(&control_word, _CW_DEFAULT, MCW_PC);
2022-03-20T18:32:56.9154493Z                                     ^
2022-03-20T18:32:56.9155306Z ../cairo-1.17.6/src/win32/cairo-dwrite-font.cpp:733:30: error: use of undeclared identifier '_CW_DEFAULT'
2022-03-20T18:32:56.9155958Z         _controlfp_s(&control_word, _CW_DEFAULT, MCW_PC);
2022-03-20T18:32:56.9156417Z                                     ^
```

https://github.com/msys2-arm/msys2-autobuild/commit/6c9a611fc18ea4ba8517104b12957cba6ee0bd58/checks/5618923356/logs

**Comment by jeremyd2019** [comment]
win10 sdk header defines `_CW_DEFAULT` to the same thing for AMD64, ARM, and ARM64, so probably mingw-w64 needs a patch to do the same

**Comment by jeremyd2019** [comment]
Maybe something like this.  I'll try to test this in a bit
```patch
diff --git a/mingw-w64-headers/crt/float.h b/mingw-w64-headers/crt/float.h
index ac534a49a..da8717b83 100644
--- a/mingw-w64-headers/crt/float.h
+++ b/mingw-w64-headers/crt/float.h
@@ -245,7 +245,7 @@
 #define _CW_DEFAULT (_RC_NEAR+_PC_53+_EM_INVALID+_EM_ZERODIVIDE+_EM_OVERFLOW+_EM_UNDERFLOW+_EM_INEXACT+_EM_DENORMAL)
 #elif defined(__ia64__)
 #define _CW_DEFAULT (_RC_NEAR+_PC_64+_EM_INVALID+_EM_ZERODIVIDE+_EM_OVERFLOW+_EM_UNDERFLOW+_EM_INEXACT+_EM_DENORMAL)
-#elif defined(__x86_64__)
+#elif defined(__x86_64__) || defined(__arm__) || defined(__aarch64__)
 #define _CW_DEFAULT (_RC_NEAR+_EM_INVALID+_EM_ZERODIVIDE+_EM_OVERFLOW+_EM_UNDERFLOW+_EM_INEXACT+_EM_DENORMAL)
 #endif
 
```

**Comment by jeremyd2019** [comment]
huh, MS docs say MCW_PC flags are not supported on x64 or ARM.  Regardless, _CW_DEFAULT should be defined.

**Comment by jeremyd2019** [comment]
https://github.com/freedesktop/cairo/blob/359afa3e88883082b615f36734cadb4800c5aa82/src/win32/cairo-dwrite-font.cpp#L719-L731

Apparently not in an ifdef, but MS docs say:
> On the ARM and x64 architectures, changing the infinity mode or the floating-point precision isn't supported. If the precision control mask is used on the x64 platform, the function raises an assertion and the invalid parameter handler is invoked, as described in [Parameter Validation](https://docs.microsoft.com/en-us/cpp/c-runtime-library/parameter-validation?view=msvc-170).

**Comment by jeremyd2019** [comment]
> Maybe something like this. I'll try to test this in a bit

cairo builds with that change at least.

**Comment by jeremyd2019** [comment]
https://sourceforge.net/p/mingw-w64/mailman/message/37628214/

**Comment by jeremyd2019** [comment]
cairo built now for clangarm64 after #11057
