### ISSUE TITLE
MSYS2 doesnt begin installation upon "pacman -syu" command

### ISSUE THREAD

**Issue by JazD1** [msys2/MINGW-packages#11079]
$ pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 ucrt64 is up to date
 clang64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do

I recieve this before a prompt for a new command, why isnt the installation started as mentioned on the msys2 webpage?

**Comment by Biswa96** [comment]
It means that all packages are up to date.

**Comment by JazD1** [comment]
> It means that all packages are up to date.

I am beginning to learn C programming, this is my first time downloading a compiler, do I just continue with the following steps mentioned on the site or?

**Comment by Biswa96** [comment]
Yes, absolutely.
