### ISSUE TITLE
unable to bootstrap gcc after path change

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#11095]
putting the system headers and libraries in common sysroot seems to have caused some problems, stage 2 bootstrap cannot find the system libraries and this old ugly bug has reared its head again to -> `C:\Msys2\tmp\cccer6AJ.ltrans0.ltrans.o:<artificial>:(.text+0x524d): undefined reference to `stpcpy'`

not really sure why this change was made ?

**Comment by revelator** [comment]
also causes other problems like overwriting libgdiplus if the mono package is installed, and same for unixodbc.
i got around the stpcpy problem by linking to libiberty from binutils which is quite weird as gcc has its own version of that.

**Comment by MehdiChinoune** [comment]
> also causes other problems like overwriting libgdiplus if the mono package is installed, and same for unixodbc. i got around the stpcpy problem by linking to libiberty from binutils which is quite weird as gcc has its own version of that.

We fixed all of those issues, We removed the conflicts and rebuilt packages when required.

**Comment by revelator** [comment]
ah i see you have it logged in conflicts newer mind then.

**Comment by revelator** [comment]
the stpcpy problem however is still there, this first appeared several years back but was newer fixed due to it not happening to all users (seems im one of the lucky ones). funny thing this has been plauging clang as well where the workaround was to use -fno-builtin-stpcpy, sadly this flag does nothing on gcc.

**Comment by revelator** [comment]
took me a bit of patching but i finally beat that damn stpcpy problem, had to make some rather nasty changes to libiberty's makefile.in as well as gcc's makefile.in basically disabling stpcpy completely. the funny thing here is that gcc's libiberty does not even export this symbol but binutils libiberty does, however gcc should not pick this up as binutils libiberty.a is not located in a path searched by ld so this had me somewhat stumped. only thing i can think of is that gcc is picking it up from some library in /usr/lib or the fact that binutils actually exports this maybe causes ld to think it is there.

**Comment by revelator** [comment]
it builds but boy oh boy is it slow... one weird thing i newer seen before is it bickering about jobserver-auth missing (seems to be lto related) and it is actually doing the bootstrap using lto which i dont recall it doing before. 

stage 2 thus far is not even done yet and it has taken 4 hours Oo

**Comment by revelator** [comment]
yep was lto related, for some reason i cannot decern it was running the bootstrap-lto path which does not work out of the box on windows due to various problems. cant say i ever had problems with how mingw-w64 was usually setup with the change to paths we just need to lobotomize the arch description in binutils and we have a new mingw.org compiler xD.
