### ISSUE TITLE
aclocal disappeared?

### ISSUE THREAD

**Issue by Jehan** [msys2/MINGW-packages#11114]
Hi!

We have a dependency on `aalib`, an old ascii-art library which I was building locally in our CI (because it's not in MSYS2) for quite some time without problem.
Our script is here: https://gitlab.gnome.org/GNOME/gimp/-/blob/master/build/windows/gitlab-ci/build-deps-msys2.sh#L53

It used to work without a problem until now, but today I rebuilt and got this error:

```
+ aclocal
./build/windows/gitlab-ci/build-deps-msys2.sh: line 63: aclocal: command not found
```

(if I recall, we needed to run `aclocal` explicitly because the tarball was very old and we needed to update some files in there, to work on modern machines, which invalidated the build system; anyway `aclocal` is pretty basic tool and should stay available 🙂)

I can see we had a successful build with the same script at least on March 25 (so 3 days ago). Something seems to have happened, and aclocal disappeared from whichever package it used to be in. Or maybe it got moved to another MSYS2 package we now need to install?

P.S.: by the way, if you ever wanted to package `aalib`, it would be nice too. Not sure why I never asked. But it would not invalidate this report, `aclocal` is a needed tool! 😛

**Comment by Biswa96** [comment]
I assume that it is part of `$MINGW_PACKAGE_PREFIX-autotools` package.

```
$ pacman -F /usr/bin/aclocal
usr/bin/aclocal is owned by msys/automake-wrapper 11-4
```

There were some reshuffle with toolchain and base-devel packages.

> if you ever wanted to package aalib, it would be nice too

Always welcomed! 🤗 But need some testing.

**Comment by Jehan** [comment]
Awesome, thanks. Would be nice if https://packages.msys2.org had a by-file package search (like https://packages.debian.org/ does for instance), for the people who don't have easy access to the CLI tools (I build for Windows through a CI). :-)

Anyway I now pushed installing the `autotools` package (because I'm guessing that `automake-wrapper` won't be the only one needed and I see `autotools` depends on this one anyway). Let's see. I'll close the report if everything goes well.

**Comment by Biswa96** [comment]
> Would be nice if https://packages.msys2.org/ had a by-file package search

Yeah, that would be useful. But pacman already does that job. i.e. user preference.

**Comment by Jehan** [comment]
> Yeah, that would be useful. But pacman already does that job. i.e. user preference.

As I said, I don't have access to pacman. Well I could push a test commit in some feature branch, just have our CI pull a full runner all this just to run the command you proposed above, whose answer I would look parsing manually long CI logs. But it would be a bit overboard, right. ;-)

**Comment by Biswa96** [comment]
For file search, you can follow this issue https://github.com/msys2/msys2-web/issues/5

**Comment by Jehan** [comment]
We also had to install `intltool` explicitly, but now it's ok. The CI build is working again. Thanks. Closing!

**Comment by CiteClimb** [comment]
For me, installing the wrapper solved the issue: https://packages.msys2.org/packages/automake
