### ISSUE TITLE
pango + harfbuzz > 4.x.y: access violation

### ISSUE THREAD

**Issue by kmilos** [msys2/MINGW-packages#11124]
Nightly CI and manual master builds of darktable produce the attached backtrace with access violation in module libharfbuzz-0.dll, see also https://github.com/darktable-org/darktable/issues/11407. This started happening with harfbuzz-4.0.1-1 and most recent 4.1.0-1 didn't change the behaviour.

[darktable_bt_6DEXJ1.txt](https://github.com/msys2/MINGW-packages/files/8370710/darktable_bt_6DEXJ1.txt)

Rebuilding pango for latest harfbuzz-4.1.0-1 doesn't help either, really need to manually downgrade to both harfbuzz-3.4.0-1 and pango-1.50.5-1 for a working darktable build.

**Comment by kmilos** [comment]
Also reported to Pango as per harfbuzz developer instructions: https://gitlab.gnome.org/GNOME/pango/-/issues/680

**Comment by lazka** [comment]
the fixed package is now in the repo

**Comment by kmilos** [comment]
Nice one, thanks!
