### ISSUE TITLE
32-bit libmng does not work

### ISSUE THREAD

**Issue by Jehan** [msys2/MINGW-packages#11136]
When building our MNG plug-in against MSYS2 32-bit libmng, it fails with `undefined reference` to various `mng_*` API.

A much more basic test is the one run by the autotools to detect if `mng_create` function exists. Here is the test file as generated by autotools: [conftest.c.txt](https://github.com/msys2/MINGW-packages/files/8384442/conftest.c.txt) (rename it as `.c` as Github doesn't even accept `.c` files, which is ridiculous for a development tracker!)

Now if you try to compile it with this command line:

```
$ i686-w64-mingw32-gcc -o conftest.exe -g -O2 -Wall -Wdeclaration-after-statement -Wmissing-prototypes -Werror=missing-prototypes  -Wmissing-declarations -Winit-self -Wpointer-arith  -Wmissing-format-attribute -Wformat-security -Wlogical-op -Wtype-limits -fno-common -fdiagnostics-show-option -Wreturn-type   -mms-bitfields   conftest.c -lmng -lz -lm
/usr/bin/i686-w64-mingw32-ld: /tmp/cce3dbrJ.o: in function `main':
/home/jehan/.local/share/crossroad/artifacts/w32/gimp/gimp-autotools/conftest.c:66: undefined reference to `mng_create'
collect2: error: ld returned 1 exit status
```

… whereas the same with `x86_64-w64-mingw32-gcc` and the 64-bit libmng counterpart works fine.

Note that it's not the test which is wrong or anything like this. On our meson build, we don't have such advanced test (only the basic `pkg-config` test), so `libmng` is wrongly detected (well… rightly but actually it's a broken libmng), then we have the same "undefined reference" errors when it builds actual code with libmng API.

**Comment by Jehan** [comment]
Note that this issue has been happening for a long time. It's not new. We just never really investigated on it, and in our scripts, we were just not installing the MNG plug-in on 32-bit.

**Comment by Jehan** [comment]
That's an example of the errors we get when building actual code with libmng in 32-bit: https://gitlab.gnome.org/GNOME/gimp/-/jobs/1925160

```
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: plug-ins/common/file-mng.exe.p/file-mng.c.obj: in function `mywritedata':
C:\_r\_builds\k3_3muaB\0\GNOME\gimp\_build-w32/../plug-ins/common/file-mng.c:463: undefined reference to `mng_get_userdata'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: plug-ins/common/file-mng.exe.p/file-mng.c.obj: in function `mng_save_image':
C:\_r\_builds\k3_3muaB\0\GNOME\gimp\_build-w32/../plug-ins/common/file-mng.c:878: undefined reference to `mng_initialize'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:\_r\_builds\k3_3muaB\0\GNOME\gimp\_build-w32/../plug-ins/common/file-mng.c:885: undefined reference to `mng_setcb_openstream'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:\_r\_builds\k3_3muaB\0\GNOME\gimp\_build-w32/../plug-ins/common/file-mng.c:1557: undefined reference to `mng_cleanup'
[…]
```

**Comment by jeremyd2019** [comment]
looks like you need to define `MNG_USE_DLL`, or the headers don't define the functions as stdcall, which they are in the DLL.  This seems to be a pretty messed up idea, to have the calling convention differ between the shared and static builds...

Perhaps the linker option `--enable-stdcall-fixup` could help, but as long as you need to mess with options may as well fix it right.

on x86_64, there is only one calling convention and stdcall annotation is ignored.

**Comment by jeremyd2019** [comment]
Is there a way to add `-DMNG_USE_DLL` to the .pc file so that it is only defined on shared builds?  I've only ever seen using `Cflags.private` to add a special define for static builds...

**Comment by jeremyd2019** [comment]
Oops, it already is:
```
$ cat /mingw32/lib/pkgconfig/libmng.pc
prefix=/mingw32
exec_prefix=/mingw32
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libmng
Description: Loads PNG/MNG/JNG files
Version: 2.0.3
Libs: -L${libdir} -lmng
Libs.private:  -ljpeg -lz -llcms2 -lm
Cflags: -I${includedir} -DMNG_USE_DLL
Cflags.private: -UMNG_DLL -UMNG_USE_DLL
```

So that then begs the question, if you are configuring usage of libmng via pkgconf, why you didn't get `-DMNG_USE_DLL`?

**Comment by lazka** [comment]
It's not using pkg-config: https://github.com/GNOME/gimp/blob/ae36d20c417d53fda79fbf87bd705a7e2d7ab094/configure.ac#L1613

So likely using pkg-config there like for other deps could help. You can even test that on Linux first.

**Comment by Jehan** [comment]
The `./configure` test does not use `pkg-config` because it is not building a real program. It only checks for a symbol existence. 

This being said, I was gonna answer that the meson build has the same problem and uses `pkg-config`, but actually it doesn't! It uses [cc.find_library()](https://gitlab.gnome.org/GNOME/gimp/-/blob/master/meson.build#L661) which doesn't get any info from `pkg-config`. I was just completely confused.

I made a test, switching to `dependency()` (which uses pkg-config as first resolution method, AFAIR) and now it works! So what I'm going to do now is: first the pkg-config test, then (only if the pc test fails), a library test (to continue supporting older libmng without pc files) augmented with a function test (so that the test is relevant; i.e. it might continue to fail with 32-bit using older libmng, but now we'll know at configure time, not build time).

In any case, now the MNG plug-in can build on 32-bit as long as we use a recent libmng (which we obviously does). Thanks for the hints, and sorry for the false report. I should have paid more attention to the details.

**Comment by lazka** [comment]
> (to continue supporting older libmng without pc files)

With the last release being 7 years old I wonder why you mean by that :)

One more thing: turns out we patch the .pc file accordingly, so that's not upstream: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libmng/pkg-config-extra-flags.patch

**Comment by Jehan** [comment]
> With the last release being 7 years old I wonder what you mean by that :)

I don't know myself. I tried to search for a repository to make some log archeology but couldn't really find anything really satisfying (though I didn't search thoroughly).

In GIMP, we are pretty conservative and if there is no reason to bump a dependency requirement, we don't bump it just for the sake of it. There are all kinds of people, platforms we never heard of and weird use cases where GIMP were heard to be built in. Maybe just doing the pkg-config check would not break these cases, but maybe it would. Why even bother testing if handling the older cases is not a problem to also supporting the newer case?

> So I wouldn't support the broken case.

It's not necessarily broken. For instance it works for Windows 64-bit, for Linux, for macOS, and for many other platforms (AFAIK it only didn't work for Win 32-bit). And then there are other platforms too where the old test might be suitable while the pkg-config might not. Seriously I don't know but the cost of supporting the old case (cost which is just: not deleting these tests) is very low. So why risking it? :-)

**Comment by Biswa96** [comment]
`-DMNG_USE_DLL` option can be added to CFLAGS before testing instead of pkg-config checks. It is project's own requirement, not msys2's modification.

**Comment by Biswa96** [comment]
For Windows platform only irrespective of architecture or bitness.

<details><summary>Code from libmng_types.h</summary>

```c
#ifndef MNG_DLL
#if defined(MNG_BUILD_DLL) || defined(MNG_USE_DLL)
#define MNG_DLL
#endif
#endif

#define MNG_LOCAL static

#if defined(MNG_DLL) && defined(WIN32) /* setup DLL calling conventions */ 
#define MNG_DECL __stdcall
#if defined(MNG_BUILD_DLL)
#define MNG_EXT __declspec(dllexport)
#elif defined(MNG_USE_DLL)
#define MNG_EXT __declspec(dllimport)
#else
#define MNG_EXT
#endif
#ifdef MNG_STRICT_ANSI
#undef MNG_STRICT_ANSI                 /* can't do strict-ANSI with this DLL-stuff */
#endif
#else
#define MNG_DECL                       /* dummies for non-DLL */
#define MNG_EXT
#endif /* MNG_DLL && WIN32 */
```

</details>

**Comment by Jehan** [comment]
Thanks everyone. Indeed defining `MNG_USE_DLL` then including `libmng.h` works fine. So I added this additional tweak and now even the old test allows to build this plug-in on Win 32-bit. I'll still leave also the `pkg-config` test, but it's good that this test works fine.

Actually I even realized that, for instance the [Debian package of libmng doesn't even have the `.pc` file](https://packages.debian.org/bookworm/amd64/libmng-dev/filelist). So you see @lazka, that's why we really need to keep such old (not so broken!) tests. 😜

Note: actually I added this new tweak only in the meson test because their [`prefix` arg](https://mesonbuild.com/Compiler-properties.html#does-a-function-exist) allows to define the macro and include the header (which is necessary to set the correct calling convention), but it doesn't look like [AC_CHECK_LIB()](https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Libraries.html] has the same ability. I can only tweak the CFLAGS, but how would I include? Anyway it's ok. I have been thinking of making the meson build the default on meson at least because as I understand, this is where it is the most obviously useful (in terms of build speed in particular).

**Comment by lazka** [comment]
> Actually I even realized that, for instance the [Debian package of libmng doesn't even have the `.pc` file](https://packages.debian.org/bookworm/amd64/libmng-dev/filelist). So you see @lazka, that's why we really need to keep such old (not so broken!) tests. 😜

They are shipping a 15 year old release of course :D Now I see what you mean.

**Comment by jeremyd2019** [comment]
> For Windows platform only irrespective of architecture or bitness.

At least of the currently supported Windows architectures, stdcall decoration is a no-op anywhere except i686, which is why x86_64 worked without it.  But the header *also* enables dllimport with `MNG_USE_DLL` which makes calling the functions exported from the DLL somewhat more efficient (if you care why, https://docs.microsoft.com/en-us/cpp/build/importing-function-calls-using-declspec-dllimport?view=msvc-170 goes into it, though on mingw dllimport is *not* "always required to access exported DLL data").

Note that if you wanted to support statically linking libmng on Windows, you would need to *not* define `MNG_USE_DLL` in that case...  The `.pc` file included in the package here does that by adding `-UMNG_USE_DLL` to the `Cflags.private` entry.  Hopefully that is not something you want/need to support, the logic in combination with the fallback cases would probably get out of hand.

**Comment by Jehan** [comment]
> Note that if you wanted to support statically linking libmng on Windows, you would need to not define MNG_USE_DLL in that case... The .pc file included in the package here does that by adding -UMNG_USE_DLL to the Cflags.private entry. Hopefully that is not something you want/need to support, the logic in combination with the fallback cases would probably get out of hand.

Yeah no, dynamic linking is good enough for us indeed. :-)
