### ISSUE TITLE
Libarchive doesn't actually depend on OpenSSL

### ISSUE THREAD

**Issue by brisingraerowing** [msys2/MINGW-packages#11157]
The Libarchive configure script looks for the library names `libeay64` and `libeay32`, then fails to find them as they don't exist. This causes the library to not link against OpenSSL. Why the configure script still looks for those old names I don't know.

**Comment by Biswa96** [comment]
Which crypto library should we link with libarchive?

* ArchLinux uses `--without-nettle` configure option to link with openssl.
* Debian uses `--without-openssl --with-nettle` configure option to link with nettle.

**Comment by brisingraerowing** [comment]
The statically linked build I did (where I noticed this issue) used Win32 crypto APIs (which it checks for right after the broken OSSL check).

**Comment by Biswa96** [comment]
This upstream commit added the _broken_ openssl check here https://github.com/libarchive/libarchive/commit/045e5c5a4460020e513516a5d1f3087094e67da3. I can try to ask upstream about it. BTW, do you know in which _era_ the openssl libraries were named eay64 or eay32?

**Comment by Biswa96** [comment]
Do you have any opinion about which crypto library libarchive should link with? options - native windows library (bcrypt) or openssl or nettle. @lazka

**Comment by lazka** [comment]
No sure. Since they default to openssl I'd use that.

**Comment by Biswa96** [comment]
Hi @brisingraerowing, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2085772980

**Comment by brisingraerowing** [comment]
Checked with Dependency Walker and that version is linked against OpenSSL.

**Comment by Biswa96** [comment]
Now static linking failed due to this change. See linked issue ☝️
