### ISSUE TITLE
gspawn-win64-helper.exe producing 'Failed to dup() in child process (Bad file descriptor)'

### ISSUE THREAD

**Issue by ThosRTanner** [msys2/MINGW-packages#11159]
I've been trying to build pan newsreader for windows, which uses gtk2. I've got it working successfully when running under MSYS2, but if I try to create a windows package, when I get to a place where it spawns a windows process (to open a URL), via gspawn-win64-helper.exe (from g_spawn_command_line_async), I get the above message. 

So I'm clearly not providing something I ought to be, but I'm not sure what. I've copied all the necessary dlls over (after a few exciting sessions with ldd).

Meant to say this is windows 10, building with mingw x64

**Comment by lazka** [comment]
Afair you have to ship gspawn-win64-helper.exe and gspawn-win64-helper-console.exe in the directory of the glib DLL.

**Comment by lazka** [comment]
here is a recent related glib regression here: https://gitlab.gnome.org/GNOME/glib/-/issues/2628

**Comment by ThosRTanner** [comment]
that does look pretty much like what I'm seeing, yes

**Comment by jeremyd2019** [comment]
> here is a recent related glib regression, maybe that is related: https://gitlab.gnome.org/GNOME/glib/-/issues/2628

ooh, shades of https://github.com/pypa/pip/issues/10444... Let's hope they don't fall down that same rabbit hole.
