### ISSUE TITLE
mingw creduce fails to find creduce_config.pm

### ISSUE THREAD

**Issue by fracting** [msys2/MINGW-packages#1116]
Hi,

I was following the guide in https://embed.cs.utah.edu/creduce/using/ to play with creduce. It works on Linux and failed on msys2.

Here is the output of `$ creduce ./test1.sh small.c`

```
Can't locate creduce_config.pm in @INC (you may need to install the creduce_config module) (@INC contains: /mingw32/bin /usr/share/creduce/perl /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at /mingw32/bin/creduce line 60.
BEGIN failed--compilation aborted at /mingw32/bin/creduce line 60.
```

I tried copy /mingw32/share/creduce/perl to /usr/share/creduce/perl but it fails with `prereqs not found for pass pass_indent at /mingw32/bin/creduce line 238.`

Would be nice to have it fixed ;)

**Comment by mingwandroid** [comment]
Hi @fracting. Is this working now? I've used it a few times since this report - though I admit to building it locally usually as whenever I want to use it I always want the latest version.

**Comment by MehdiChinoune** [comment]
Closing due to the inactivity and not responding to the maintainer.
