### ISSUE TITLE
OpenCV load time linking dependency on GPL code: avformat-58.dll

### ISSUE THREAD

**Issue by wstnturner** [msys2/MINGW-packages#11160]
The current Msys2 build of OpenCV is built with a load time linking dependency on GPL licensed code (avformat library et al/ffmpeg). The Msys2 OpenCV, due to the load time GPL linking, is no longer BSD licensed.

Users who incorporate the current Msys2 OpenCV into their code assuming the BSD license are inadvertently forcing their (potentially closed source code) to be subject to the GPL.

https://packages.msys2.org/package/mingw-w64-x86_64-opencv

Package: mingw-w64-x86_64-opencv

Upstream URL: https://opencv.org/
License(s): BSD
Version: 4.5.5-1

- avformat-58.dll DLL load time dependency, parent package:

https://packages.msys2.org/package/mingw-w64-x86_64-ffmpeg

Package: mingw-w64-x86_64-ffmpeg

Upstream URL: https://ffmpeg.org/
License(s): GPL
Version: 4.4.1-12

# Dependency detection

Running dependencies on: libopencv_videoio.dll
See: https://github.com/lucasg/Dependencies

Listing dependency modules for: libopencv_videoio.dll

```
Dependencies.exe -modules libopencv_videoio.dll
...
[Environment] avformat-58.dll : C:\msys64\mingw64\bin\avformat-58.dll
...
```

**Comment by Biswa96** [comment]
It is also true for ArchLinux https://archlinux.org/packages/extra/x86_64/opencv/.

**Comment by MehdiChinoune** [comment]
I don't think we could solve this issue for you. The only solution I see here for you is to build OpenCV yourself without ffmpeg dependency.
Someone has filled a issue before about another package #9240

**Comment by lazka** [comment]
> The current Msys2 build of OpenCV is built with a load time linking dependency on GPL licensed code (avformat library et al/ffmpeg), OpenCV does not comply with GPL due to its BSD license.

GPL and  BSD-3-Clause are compatible.

> Users who incorporate the current Msys2 OpenCV into their code assuming the BSD license are inadvertently forcing their (potentially closed source code) to be subject to the GPL.

Correct. Assuming they release it to the public.

**Comment by wstnturner** [comment]
I'm not sure indicating that the current Msys2 OpenCV package is BSD licensed is compatible with the GPL. By combining it with a load time linking dependency on GPL code, the released software becomes subject to the GPL license (paragraph 2 part b of GPL). The OpenCV project's source code may be BSD, but the Msys2 OpenCV is now in effect GPL. I'm aware that I may simply rebuild OpenCV with a configuration that preserves its BSD license features. Though, up until recently the Msys2 OpenCV (up to version 4.5.2) was I believe not subject to the GPL license, and thus more versatile with respect to integrating into closed source projects.

Thanks for the information about Arch and Debian's libopencv_videoio GPL dependency. Maybe this "issue" should be dealt with elsewhere. I understand that the work done to maintain Msys2 is all volunteer and mostly in people's spare time,  and I really appreciate it! Thank you so much and for responding to the issue I created.

**Comment by MehdiChinoune** [comment]
Just to clarify with prior to thiversion OpenCV was downloading ffmeg dll libraries (built against MSVC) during configuration time, link to them and then install them with its licenses, that's why there wasn't a dependency on the MINGW libs. With 4.5.5 I have disabled that and forced it to link to the MINGW ones.
PKGBUILD:
```diff
+    -DOPENCV_FFMPEG_USE_FIND_PACKAGE=ON \
+    -DOPENCV_FFMPEG_SKIP_DOWNLOAD=ON \
```
filediff:
```diff
 /mingw64/bin/opencv_version.exe
 /mingw64/bin/opencv_version_win32.exe
-/mingw64/bin/opencv_videoio_ffmpeg452_64.dll
 /mingw64/bin/opencv_visualisation.exe
 /mingw64/bin/opencv_waldboost_detector.exe
 /mingw64/include/
...
 /mingw64/share/licenses/opencv4/
 /mingw64/share/licenses/opencv4/ade-LICENSE
-/mingw64/share/licenses/opencv4/ffmpeg-license.txt
-/mingw64/share/licenses/opencv4/ffmpeg-readme.txt
 /mingw64/share/licenses/opencv4/opencl-headers-LICENSE.txt
 /mingw64/share/licenses/opencv4/quirc-LICENSE
```
You were using ffmpeg, through opencv_videoio_ffmpeg452_64.dll

**Comment by jeremyd2019** [comment]
Would delayimp help, or is that still too tightly coupled with GPL code?  (Disclaimer: I have not tried to do delayed import on mingw-w64)

**Comment by wstnturner** [comment]
It was previously possible to use libopencv_videoio452.dll to open a camera device without any dependency on ffmpeg. That build of opencv was generally useful for image streaming from a capture device and image processing without a GPL load time link dependency. The Dependencies program shows no ffmpeg dependency:

```
Dependencies.exe -modules libopencv_imgproc452.dll | grep ffmpeg

```

Ideally we include dlfcn.h and use dlopen/dlsym to optionally runtime load code that would affect the license of a project. I'm not sure about delayimp, seems like a windows thing. I believe the videoio module is capable of runtime loading based on debug output such as:

```
[DEBUG:0] global C:/_/M/mingw-w64-opencv/src/opencv-4.5.2/modules/videoio/src/videoio_registry.cpp (191) VideoBackendRegistry VIDEOIO: Builtin backends(8): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); MSMF(970); DSHOW(960); CV_IMAGES(950); CV_MJPEG(940); UEYE(930)
[DEBUG:0] global C:/_/M/mingw-w64-opencv/src/opencv-4.5.2/modules/videoio/src/videoio_registry.cpp (215) VideoBackendRegistry VIDEOIO: Available backends(8): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); MSMF(970); DSHOW(960); CV_IMAGES(950); CV_MJPEG(940); UEYE(930)
[ INFO:0] global C:/_/M/mingw-w64-opencv/src/opencv-4.5.2/modules/videoio/src/videoio_registry.cpp (217) VideoBackendRegistry VIDEOIO: Enabled backends(8, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); MSMF(970); DSHOW(960); CV_IMAGES(950); CV_MJPEG(940); UEYE(930)
[ WARN:0] global C:/_/M/mingw-w64-opencv/src/opencv-4.5.2/modules/videoio/src/cap.cpp (235) open VIDEOIO(GSTREAMER): trying capture cameraNum=0 ...
[ INFO:0] global C:/_/M/mingw-w64-opencv/src/opencv-4.5.2/modules/videoio/src/backend_plugin.cpp (335) getPluginCandidates Found 2 plugin(s) for GSTREAMER
[ INFO:0] global C:/_/M/mingw-w64-opencv/src/opencv-4.5.2/modules/core/src/utils/plugin_loader.impl.hpp (67) libraryLoad load opencv_videoio_gstreamer452_64.dll => FAILED
[ WARN:0] global C:/_/M/mingw-w64-opencv/src/opencv-4.5.2/modules/videoio/src/cap.cpp (296) open VIDEOIO(GSTREAMER): backend is not available (plugin is missing, or can't be loaded due dependencies or it is not compatible)
[ WARN:0] global C:/_/M/mingw-w64-opencv/src/opencv-4.5.2/modules/videoio/src/cap.cpp (235) open VIDEOIO(DSHOW): trying capture cameraNum=0 ...
[ WARN:0] global C:/_/M/mingw-w64-opencv/src/opencv-4.5.2/modules/videoio/src/cap.cpp (248) open VIDEOIO(DSHOW): created, isOpened=1

```

In this case, the gstreamer backend is not available and thus is not used and the DSHOW backend is finally used, as far as I can tell there is no load time linking dependency on ffmpefg (or gstreamer in this case). Since those DLLs are not present in the local working directory and the code is not being run via Msys2/MinGW (so no ability to resolve libraries in the msys system paths)

**Comment by 1480c1** [comment]
> $ Dependencies.exe -modules libopencv_videoio452.dll | grep ffmpeg

Shouldn't the grep be for `libav`?

**Comment by MehdiChinoune** [comment]
> > $ Dependencies.exe -modules libopencv_videoio452.dll | grep ffmpeg
> 
> Shouldn't the grep be for `av`?

Previously
That was before updating OpenCV to 4.5.5

**Comment by wstnturner** [comment]
> > $ Dependencies.exe -modules libopencv_videoio452.dll | grep ffmpeg
> 
> Shouldn't the grep be for `av`?

Grep on avformat, also no load time linking dependency there either for 4.5.2
```
$ Dependencies.exe -modules libopencv_videoio452.dll | grep avformat

```

**Comment by Biswa96** [comment]
Is it possible to replace ffmpeg with native [WMF][1]. There is a option in cmake file:

```cmake
OCV_OPTION(WITH_MSMF "Build VideoIO with Media Foundation support" NOT MINGW
  VISIBLE_IF WIN32
  VERIFY HAVE_MSMF)
```

[1]: https://docs.microsoft.com/en-us/windows/win32/medfound/about-the-media-foundation-sdk

**Comment by crackwitz** [comment]
why is this not handled by lawyers? OpenCV is intentionally [licensed under Apache 2](https://opencv.org/license/) because that license is ["compatible to GPL"](https://www.gnu.org/licenses/license-list.en.html)

**Comment by MehdiChinoune** [comment]
I don't think we can do something about it!
You could disable rebuild OpenCV with ffmpeg disabled

**Comment by mlt** [comment]
We probably could delay load it to avoid hard dependency #28593.
