### ISSUE TITLE
rebuilds for llvm 14

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#11262]
Split a tracking issue from #11087

LLVM projects:
- [x] #11221
- [x] #11263

Dependents:
- [x] #11277
- [x] #11278
- [x] #11276

**Comment by mati865** [comment]
Also Rust statically links LLVM. Support for LLVM 14 will be added in 1.60 that is expected to be released on 7.04.2022.

**Comment by jeremyd2019** [comment]
there are a few packages that seem like they ought to need to be rebuilt that didn't show up, like blender, ghdl-llvm, python-llvmlite.  Perhaps they statically link also.

**Comment by mati865** [comment]
Yeah, IIRC ghdl links statically. No idea about python but blender is surprising to me.

**Comment by MehdiChinoune** [comment]
include-what-you-use: https://github.com/include-what-you-use/include-what-you-use/releases/tag/0.18
lldb, polly and openmp: #11263

**Comment by jeremyd2019** [comment]
thanks, I missed openmp

**Comment by jeremyd2019** [comment]
Confirmed blender and python-llvmlite both statically link llvm.

**Comment by lazka** [comment]
Anything else we should wait for?

**Comment by jeremyd2019** [comment]
That's everything I know of.

**Comment by filnet** [comment]
and rust could be stripped (?)

**Comment by jeremyd2019** [comment]
Looks like everything is done and llvm 14 is published 🚀

**Comment by lazka** [comment]
thanks everyone

**Comment by lazka** [comment]
> and rust could be stripped (?)

It seems to be fixed now, yes.
