### ISSUE TITLE
clang32 produces currupt executables

### ISSUE THREAD

**Issue by Tanishq-Banyal** [msys2/MINGW-packages#11377]
clang32 is producing currupt .exe files, attempting to run them gives `bash: exec format error`.

Flags i Used:-
```
clang++ -std=c++20 -O2 -s -flto test.cpp -o test.exe
```

clang64 works fine tho.

**Comment by MehdiChinoune** [comment]
show code!

**Comment by Tanishq-Banyal** [comment]
> show code!

```cpp
#include <cstdio>

int main()
{
    std::puts("testing clang32");
}
```

**Comment by Biswa96** [comment]
Programs are being compiled in CI with clang32 environment without any issue. Please make sure that there is no third party programs like antimalware or antivirus corrupting the compilation process.

**Comment by msink** [comment]
on CLANG32:
```
CLANG32 ~
$ c++ --version
clang version 14.0.0
Target: i686-w64-windows-gnu
Thread model: posix
InstalledDir: F:/msys64/clang32/bin

CLANG32 /f/msys64-clang
$ clang++ -std=c++20 -O2 -s -flto test.cpp -o test.exe

CLANG32 /f/msys64-clang
$ ./test
testing clang32

CLANG32 /f/msys64-clang
$ file test.exe
test.exe: PE32 executable (console) Intel 80386, for MS Windows
```

on MINGW32 something broken:
```
MINGW32 ~
$ clang++ --version
clang version 14.0.0
Target: i686-w64-windows-gnu
Thread model: posix
InstalledDir: F:/msys64/mingw32/bin

MINGW32 ~
$ cd /f/msys64

MINGW32 /f/msys64
$ clang++ -std=c++20 -O2 -s -flto test.cpp -o test.exe
clang++: error: 'i686-w64-windows-gnu': unable to pass LLVM bit-code files to linker
```

**Comment by MehdiChinoune** [comment]
> MINGW32 ~
> $ clang++ -std=c++20 -O2 -s -flto test.cpp -o test.exe
> clang++: error: 'i686-w64-windows-gnu': unable to pass LLVM bit-code files to linker
> ```

LTO is known to be broken on MINGW32.

**Comment by msink** [comment]
btw, maybe offtop here, but - are there plans to enable CLANG32 in default distribution?
for now to test it I had to append `etc/pacman.conf` by
```
[clang32]
Server = http://repo.msys2.org/mingw/clang32/
```
and replace `ParallelDownloads = 5` to `ParallelDownloads = 1`

**Comment by Tanishq-Banyal** [comment]
@msink where did you get clang 14 ? For me, latest in repo was clang 13

**Comment by mati865** [comment]
@msink it should work with `-fuse-ld=lld`, `ld.bfd` doesn't understand LLVM bitcode.

**Comment by msink** [comment]
> where did you get clang 14
> in repo was clang 13

it was updated to 14 today :)

**Comment by Tanishq-Banyal** [comment]
I seem have found the cause of that error, CLANG32 mode in msys2 doesn't play nicely with ext4 disks mounted inside a windows VM using Virualbox Shared Folder functionality.

I copied my project to /home and now it seems to compile fine.

Its still wierd because MINGW32 mode works fine in that mounted folder as well.
