### ISSUE TITLE
meson glade bug

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#11382]
seems the latest meson deprecated some stuff that the glade source is using so it fails to build.

`../glade-3.38.2/data/meson.build:4:5: ERROR: Function does not take positional arguments.`

after what i could find out about it it is @noposarg that triggers this bug.

**Comment by Biswa96** [comment]
Thank you for reporting this issue. The fix was suggested in this merge request https://gitlab.gnome.org/GNOME/glade/-/merge_requests/117. It has not been merged yet. So, I import the patch file from there.

**Comment by revelator** [comment]
thx :)
