### ISSUE TITLE
{i686,x86_64}-w64-mingw32-gcc -print-sysroot outputs nothing

### ISSUE THREAD

**Issue by lbmeng** [msys2/MINGW-packages#11387]
## Describe the issue

The mingw-w64 gcc toolchain seems not able to print out its sysroot.

## Steps to Reproduce the Problem

Run 'x86_64-w64-mingw32-gcc -print-sysroot' or 'i686-w64-mingw32-gcc -print-sysroot'

Nothing is output. It should output either /mingw64 or /mingw32.

**Comment by Biswa96** [comment]
Should it print something? According to the [docs][1],

> Print the target sysroot directory that is used during compilation. This is the target sysroot specified either at configure time or using the --sysroot option, possibly with an extra suffix that depends on compilation options. If no target sysroot is specified, the option prints nothing.

The gcc [PKGBUILD][2] does not have any `--sysroot` option.

[1]: https://gcc.gnu.org/onlinedocs/gcc/Developer-Options.html
[2]: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gcc/PKGBUILD

**Comment by revelator** [comment]
unless its a cross compiler then no...

**Comment by lbmeng** [comment]
I see the mingw gcc was configured with '--with-native-system-header-dir=/mingw64/include'

From the [docs](https://gcc.gnu.org/install/configure.html),

```
--with-native-system-header-dir=dirname

    Specifies that dirname is the directory that contains native system header files, rather than /usr/include. This option is most useful if you are creating a compiler that should be isolated from the system as much as possible. It is most commonly used with the --with-sysroot option and will cause GCC to search dirname inside the system root specified by that option.

```

It looks '--with-native-system-header-dir' is normally used with '--with-sysroot', but we don't provide sysroot hence '/mingw64/include' is used directly.

My original intent behind this issue was to figure out where the .dll files reside in. It looks like I can use $MINGW_PREFIX/bin environment variable to do this.

**Comment by revelator** [comment]
aye $MINGW_PREFIX/bin is on path by default if running from the mingw* msys shell's, if you want to redistribute a program without the msys2 shell you would have to figure out which dll's it depends on and copy those out of $MINGW_PREFIX/bin to where the program is located, adding $MINGW_PREFIX/bin to the windows path would be asking for trouble so avoid that.
ntldd can be used for getting the dependencies from msys shell or if you prefer a more visual tool use depends.exe from the microsoft sdk or the newer dependencies.exe from here https://github.com/lucasg/Dependencies/tags as the old depends.exe does not work to well on win10
