### ISSUE TITLE
al_init_acodec_addon causes error 'while loading shared libraries: allegro_ttf-5'

### ISSUE THREAD

**Issue by dotoscat** [msys2/MINGW-packages#11438]
I don't know if it was right place, this issue is the same as https://github.com/liballeg/allegro5/issues/1325.

I use Windows 10, with msys2 mingw64 updated.

And I attach a minimal example to reproduce the problem.
[msys2-allegro_ttf5-error.zip](https://github.com/msys2/MINGW-packages/files/8456848/msys2-allegro_ttf5-error.zip)

I don't know what am I doing wrong. Please help.

**Comment by Biswa96** [comment]
Thanks for reporting the issue. The problem seems to be from msys2 side, not an upstream issue. The dependencies of allegro packages are set as optional dependencies. Those should be in main dependency list. Let me discuss this with others.

By the way, I have compiled the example program after uncommenting al_init_acodec_addon() call. The output from main.exe does not show anything. Is that expected behaviour?

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2140878623. Follow these steps:

1. Scroll down and download the correct artifact. It'll be a zip file.
2. Extract the package (.tar.zst) from zip file.
3. Install it with `pacman -U the-package-name.tar.zst` command. This command should install the missing dependencies.
4. Retest the example program.

**Comment by dotoscat** [comment]
> Thanks for reporting the issue. The problem seems to be from msys2 side, not an upstream issue. The dependencies of allegro packages are set as optional dependencies. Those should be in main dependency list. Let me discuss this with others.
> 
> By the way, I have compiled the example program after uncommenting al_init_acodec_addon() call. The output from main.exe does not show anything. Is that expected behaviour?

The example should play a sound and nothing more or an error message if it can't play the sound. So yes, this is the expected behavior.

**Comment by dotoscat** [comment]
> I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2140878623. Follow these steps:
> 
> 1. Scroll down and download the correct artifact. It'll be a zip file.
> 2. Extract the package (.tar.zst) from zip file.
> 3. Install it with `pacman -U the-package-name.tar.zst` command. This command should install the missing dependencies.
> 4. Retest the example program.

Thank you! I gonna test it and I will tell something.

**Comment by dotoscat** [comment]
> I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2140878623. Follow these steps:
> 
> 1. Scroll down and download the correct artifact. It'll be a zip file.
> 2. Extract the package (.tar.zst) from zip file.
> 3. Install it with `pacman -U the-package-name.tar.zst` command. This command should install the missing dependencies.
> 4. Retest the example program.

No, same error.
"error while loading shared libraries: allegro_ttf-5.2.dll: cannot open shared object file: No such file or directory".

I tried again restarting msys2 mingw64, just in case and is the same.

The libraries related with allegro_ttf-5.2 are already installed, so is the very library. 
Here is the update process:

```
$ pacman -U mingw-w64-x86_64-allegro-5.2.6.0-3-any.pkg.tar.zst
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (7) mingw-w64-x86_64-dumb-2.0.3-2  mingw-w64-x86_64-flac-1.3.3-3
             mingw-w64-x86_64-libtheora-1.1.1-6  mingw-w64-x86_64-opus-1.3.1-4
             mingw-w64-x86_64-opusfile-0.12-2  mingw-w64-x86_64-physfs-3.0.2-1
             mingw-w64-x86_64-allegro-5.2.6.0-3

Total Download Size:    1.51 MiB
Total Installed Size:  14.03 MiB
Net Upgrade Size:       9.32 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 mingw-w64-x86_64...   154.3 KiB   103 KiB/s 00:02 [#####################] 100%
 mingw-w64-x86_64...   484.3 KiB   260 KiB/s 00:02 [#####################] 100%
 mingw-w64-x86_64...   396.0 KiB   208 KiB/s 00:02 [#####################] 100%
 mingw-w64-x86_64...   136.6 KiB  72.2 KiB/s 00:02 [#####################] 100%
 mingw-w64-x86_64...   284.1 KiB   147 KiB/s 00:02 [#####################] 100%
 mingw-w64-x86_64...    90.6 KiB  30.7 KiB/s 00:03 [#####################] 100%
 Total (6/6)          1545.9 KiB   290 KiB/s 00:05 [#####################] 100%
(7/7) checking keys in keyring                     [#####################] 100%
(6/7) checking package integrity                   [#####################] 100%
(6/7) loading package files                        [#####################] 100%
(7/7) checking for file conflicts                  [#####################] 100%
(7/7) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/7) installing mingw-w64-x86_64-dumb             [#####################] 100%
(2/7) installing mingw-w64-x86_64-flac             [#####################] 100%
(3/7) installing mingw-w64-x86_64-libtheora        [#####################] 100%
(4/7) installing mingw-w64-x86_64-opus             [#####################] 100%
(5/7) installing mingw-w64-x86_64-opusfile         [#####################] 100%
(6/7) installing mingw-w64-x86_64-physfs           [#####################] 100%
(7/7) upgrading mingw-w64-x86_64-allegro           [#####################] 100%
```

Thank you for your time.

**Comment by Biswa96** [comment]
If I use the package from CI build the program shows "No valid" output. The `al_install_audio()` call fails. I need to debug more.

Can you test if all the dependent DLLs are present using these commands?

```
pacman -S $MINGW_PACKAGE_PREFIX-ntldd
ntldd $MINGW_PREFIX/bin/allegro_ttf-5.2.dll
ntldd $MINGW_PREFIX/bin/allegro_audio-5.2.dll
```

**Comment by dotoscat** [comment]
> If I use the package from CI build the program shows "No valid" output. The `al_install_audio()` call fails. I need to debug more.
> 
> Can you test if all the dependent DLLs are present using these commands?
> 
> ```
> pacman -S $MINGW_PACKAGE_PREFIX-ntldd
> ntldd $MINGW_PREFIX/bin/allegro_ttf-5.2.dll
> ntldd $MINGW_PREFIX/bin/allegro_audio-5.2.dll
> ```

Yes, this is the output

```
$ ntldd $MINGW_PREFIX/bin/allegro_ttf-5.2.dll
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x0000020972900000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x0000020972900000)
        libfreetype-6.dll => C:\msys64\mingw64\bin\libfreetype-6.dll (0x0000020972900000)
        allegro-5.2.dll => C:\msys64\mingw64\bin\allegro-5.2.dll (0x0000020972dc0000)
        allegro_font-5.2.dll => C:\msys64\mingw64\bin\allegro_font-5.2.dll (0x0000020972620000)

$ ntldd $MINGW_PREFIX/bin/allegro_audio-5.2.dll
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x000001e71d130000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x000001e71d130000)
        USER32.dll => C:\WINDOWS\SYSTEM32\USER32.dll (0x000001e71d2f0000)
        DSOUND.dll => C:\WINDOWS\SYSTEM32\DSOUND.dll (0x000001e71d130000)
        libopenal-1.dll => C:\msys64\mingw64\bin\libopenal-1.dll (0x000001e71d2f0000)
        allegro-5.2.dll => C:\msys64\mingw64\bin\allegro-5.2.dll (0x000001e71d2f0000)

```

**Comment by Biswa96** [comment]
With debug mode allegro shows this error, is there any issue with the audio file?

```
warning: stdio    D         file_stdio.c:110  file_stdio_fopen                 [   0.67780] opening clear.wav rb
warning: wav      E                wav.c:121  wav_open                         [   0.68593] Bad RIFF type.
warning: dtor     D               dtor.c:196  _al_register_destructor          [   0.69368] added dtor for sample 000001C014259630, func 00007FFE63C2BA28
```

**Comment by dotoscat** [comment]
> With debug mode allegro shows this error, is there any issue with the audio file?
> 
> ```
> warning: stdio    D         file_stdio.c:110  file_stdio_fopen                 [   0.67780] opening clear.wav rb
> warning: wav      E                wav.c:121  wav_open                         [   0.68593] Bad RIFF type.
> warning: dtor     D               dtor.c:196  _al_register_destructor          [   0.69368] added dtor for sample 000001C014259630, func 00007FFE63C2BA28
> ```

No, I don't have any problem playing it. Just in case replace it with this one, unzip it first:

[clear.zip](https://github.com/msys2/MINGW-packages/files/8457824/clear.zip)

Is a 1 sec white noise.

**Comment by Biswa96** [comment]
Same "Bad RIFF type" error with that clear.wav file. By the way, I have tested the demo and example programs in allegro with the package from CI in a clean mingw64 environment and those worked. Some examples uses welcome.wav and those ran fine too.

**Comment by dotoscat** [comment]
> Same "Bad RIFF type" error with that clear.wav file. By the way, I have tested the demo and example programs in allegro with the package from CI in a clean mingw64 environment and those worked. Some examples uses welcome.wav and those ran fine too.

I can play it without problems. By the way, I took that welcome.wav rename it "clear.wav" and still I have issues. 'al_init_acodec_addon' is necessary to load sound files.

I did two executable versions. One calling that function 'w_main.exe' and another without calling the function 'wo_main.exe' and then I used ntldd on them.

Calling 'al_init_acodec_addon'

```
$ ntldd ./w_main.exe
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x0000028b47780000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x0000028b47780000)
        libstdc++-6.dll => C:\msys64\mingw64\bin\libstdc++-6.dll (0x0000028b47980000)
        allegro-5.2.dll => C:\msys64\mingw64\bin\allegro-5.2.dll (0x0000028b47980000)
        allegro_acodec-5.2.dll => C:\msys64\mingw64\bin\allegro_acodec-5.2.dll (0x0000028b474c0000)
        allegro_audio-5.2.dll => C:\msys64\mingw64\bin\allegro_audio-5.2.dll (0x0000028b47780000)
        allegro_font-5.2.dll => C:\msys64\mingw64\bin\allegro_font-5.2.dll (0x0000028b474c0000)
        allegro_primitives-5.2.dll => C:\msys64\mingw64\bin\allegro_primitives-5.2.dll (0x0000028b47780000)
        allegro_ttf-5.2.dll => C:\msys64\mingw64\bin\allegro_ttf-5.2.dll (0x0000028b474c0000)
```

No calling 'al_init_acodec_addon'

```
$ ntldd ./wo_main.exe
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x000002a1018b0000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x000002a1018b0000)
        libstdc++-6.dll => C:\msys64\mingw64\bin\libstdc++-6.dll (0x000002a101af0000)
        allegro-5.2.dll => C:\msys64\mingw64\bin\allegro-5.2.dll (0x000002a1018b0000)
        allegro_audio-5.2.dll => C:\msys64\mingw64\bin\allegro_audio-5.2.dll (0x000002a1018b0000)
        allegro_font-5.2.dll => C:\msys64\mingw64\bin\allegro_font-5.2.dll (0x000002a1018b0000)
        allegro_primitives-5.2.dll => C:\msys64\mingw64\bin\allegro_primitives-5.2.dll (0x000002a1018b0000)
        allegro_ttf-5.2.dll => C:\msys64\mingw64\bin\allegro_ttf-5.2.dll (0x000002a1018b0000)
```

I think 'allegro_acodec-5.2.dll' is messing with the linker for a reason.

**Comment by Biswa96** [comment]
I copy-paste some sample code from googlefu and it works with clear.wav file from original post. I have no idea what the code does. At least it is calling `al_init_acodec_addon()` 😄 

```c
#include <allegro5/allegro.h>
#include <allegro5/allegro_audio.h>
#include <allegro5/allegro_acodec.h>

int main() {
  ALLEGRO_DISPLAY *display = NULL;
  ALLEGRO_SAMPLE *sample = NULL;
  ALLEGRO_SAMPLE_INSTANCE *instance = NULL;

  al_init();
  al_install_audio();
  al_init_acodec_addon();
  al_reserve_samples(1);
  sample = al_load_sample("clear.wav");
  instance = al_create_sample_instance(sample);
  al_attach_sample_instance_to_mixer(instance, al_get_default_mixer());
  al_play_sample_instance(instance);
  while (al_get_sample_instance_playing(instance)) {}
  al_destroy_sample_instance(instance);
  al_destroy_sample(sample);
  al_uninstall_audio();
}
```

**Comment by dotoscat** [comment]
With the last msys2 update, allegro 5.2.7, this issue is solved.
