### ISSUE TITLE
 'mingw-w64-i686-cjson' and 'mingw-w64-i686-jansson' static libraries have problems running errors

### ISSUE THREAD

**Issue by fxqy** [msys2/MINGW-packages#11462]
I compiled the test with cjson and cjson, there is a problem with 'mingw-w64-i686-cjson' and 'mingw-w64-i686-jansson' , it should be a problem with libjansson and libcjson.' mingw-w64-x86_64-jansson' is working properly.
The compilation & links are all normal,  the errors at run time are as follows
![图片](https://user-images.githubusercontent.com/42601163/162744836-5575fbcc-aa49-4074-b03d-7f8d61ee6fc3.png)

**Comment by Biswa96** [comment]
Thank you for reporting the issue. Would you like to provide the sample code and commands to compile it?
