### ISSUE TITLE
Catching exception when running under gdb (gdbserver)

### ISSUE THREAD

**Issue by clauderobi** [msys2/MINGW-packages#11476]
Hi, 
I am cross compiling my project on Ubuntu 20.04. I am doing a static link. 
When running my code on Windows exception handling work just fine. However, when running under gdbserver, I get this:

`terminate called after throwing an instance of 'helper::fileops::fileOps::fileNotFound'`

This happens even though I have a break point inside the catch block. I guess, somehow, gdbserver is interfering with the normal try/catch operation.

I am actually compiling with mingw-w64 so this may not be the correct place. But I am not sure if the problem is at compilation or in gdb itself.

**Comment by 1480c1** [comment]
Are you able to test compilation on windows with msys2? Alternatively, could you provide a minimal reproduction sample that can be used to test this behavior?

**Comment by clauderobi** [comment]
Ok , here is what I did

Source code
`
#include<iostream>
#include <stdexcept>
int main()
{
    std::cout<<"Before the try block" << std::endl;

    try {
      throw std::runtime_error("Test exception");
    } catch (...) {
      std::cout << "Catched the exception" << std::endl;
    }
    
    std::cout<<"After the try block" << std::endl;
    return 0;
}
`
Compiled with
`x86_64-w64-mingw32-g++ -static hello.cpp -static-libstdc++ -static-libgcc -o hello`

Copied to my Windows machine and run

`gdbserver.exe 0.0.0.0:2345 hello.exe`

Stated gdb (inside eclipse) and hit Resume and I got 

Listening on port 2345
Remote debugging from host 192.168.70.8, port 44782
Before the try block
terminate called after throwing an instance of 'std::runtime_error'

Child exited with status 3


If I run the program outside gdbserver, I get 

`Before the try block
Catched the exception
After the try block`

**Comment by 1480c1** [comment]
try using triple backtick, like
````md
```c++
#include <cstdio>
```
````

**Comment by clauderobi** [comment]
The solution is simple, just upgrade gdb or gdbserver to version 12.

**Comment by clauderobi** [comment]
The solution is simply to switch to gdbserver version 12 (still upcoming at time of writing). Anything before has the same problem.
