### ISSUE TITLE
Possible to add  https://github.com/lldb-tools/lldb-mi.git package

### ISSUE THREAD

**Issue by acotty** [msys2/MINGW-packages#11479]
With the lldb-mi being split out of LLVM a while ago the current LLVM MSYS2 package do not include the lldb-mi.exe anymore (as expected btw).

The following web site build's it, so you may be able to borrow dome of the files if someone has the time to add it.
    https://github.com/mstorsjo/llvm-mingw

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2175913511. Follow these steps:

1. Scroll down and download the correct artifact. It'll be a zip file.
2. Extract the package (.tar.zst) from zip file.
3. Install it with `pacman -U the-package-name.tar.zst` command.

**Comment by acotty** [comment]
The lldb-mi.exe works like one from the https://github.com/mstorsjo/llvm-mingw. I checked the date of the file I used and it was from yesterday, so I used the correct  lldb-mi.exe.

Thanks for so quickly adding the package.
