### ISSUE TITLE
Incorrent package.path and package.cpath in luajit

### ISSUE THREAD

**Issue by FractalU** [msys2/MINGW-packages#11482]
The package path and cpath is misconfigured in luajit. See below.

package.path: .\?.lua;C:\msys64\mingw64\bin\lua\?.lua;C:\msys64\mingw64\bin\lua\?\init.lua;
package.cpath: .\?.dll;C:\msys64\mingw64\bin\?.dll;C:\msys64\mingw64\bin\loadall.dll

In lua 5.4

package.path: C:\msys64\mingw64\bin\..\share\lua\5.4\?.lua;C:\msys64\mingw64\bin\..\share\lua\5.4\?\init.lua;C:\msys64\mingw64\bin\..\lib\lua\5.4\?.lua;C:\msys64\mingw64\bin\..\lib\lua\5.4\?\init.lua;C:\msys64\mingw64\bin\..\share\lua\5.4\\?.lua;C:\msys64\mingw64\bin\..\share\lua\5.4\\?\init.lua;.\?.lua;.\?\init.lua
package.cpath: C:\msys64\mingw64\bin\..\lib\lua\5.4\?.dll;C:\msys64\mingw64\bin\..\lib\lua\5.4\..\lib\lua\5.4\\?.dll;C:\msys64\mingw64\bin\..\lib\lua\5.4\loadall.dll;.\?.dll

Luajit's package path points to '/msys64/mingw64/bin/lua' for lua modules and to '/msys64/mingw64/bin' for dynamic libraries.
There is a problem with that. The 'jit' module is located in 'msys64/mingw64/share/luajit-2.1.0-beta3'. When I type the command 'luajit -b' I get the following error message.

luajit: unknown luaJIT command or jit.* modules not installed

When I copy the jit module from 'msys64/mingw64/share/luajit-2.1.0-beta3' to '/msys64/mingw64/bin/lua' and type 'luajit -b' again then everything works.
Another issue is that I need to copy all the luarocks to '/msys64/mingw64/bin/lua' and dynamic libraries '/msys64/mingw64/bin'. Especially the dynamic libraries clobber up with the installed binaries.

The fix for luajit's package path and cpath would be something like below.

package.path: .\?.lua;.\?\init.lua;C:\msys64\mingw64\share\luajit-2.1.0-beta3\?.lua;C:\msys64\mingw64\share\luajit-2.1.0-beta3\?\init.lua;C:\msys64\mingw64\share\lua\5.1\?.lua;C:\msys64\mingw64\share\lua\5.1\?\init.lua;C:\msys64\mingw64\lib\luajit-2.1.0-beta3\?.lua;C:\msys64\mingw64\lib\luajit-2.1.0-beta3\?\init.lua;C:\msys64\mingw64\lib\lua\5.1\?.lua;C:\msys64\mingw64\lib\lua\5.1\?\init.lua
package.cpath: .\?.dll;C:\msys64\mingw64\lib\luajit-2.1.0-beta3\?.dll;C:\msys64\mingw64\lib\luajit-2.1.0-beta3\loadall.dll

I don't know whether luajit can load lua 5.1 dynamic libraries.

**Comment by FractalU** [comment]
Package path and cpath can easily be printed. See below.

print(package.path)
print(package.cpath)

**Comment by FractalU** [comment]
Now I see the problem.

The package path and cpath of luajit is stored in 'src/luaconf.h'. Below is a portion of it


`/* Default path for loading Lua and C modules with require(). */
#if defined(_WIN32)
/*
** In Windows, any exclamation mark ('!') in the path is replaced by the
** path of the directory of the executable file of the current process.
*/
#define LUA_LDIR	"!\\lua\\"
#define LUA_CDIR	"!\\"
#define LUA_PATH_DEFAULT \
  ".\\?.lua;" LUA_LDIR"?.lua;" LUA_LDIR"?\\init.lua;"
#define LUA_CPATH_DEFAULT \
  ".\\?.dll;" LUA_CDIR"?.dll;" LUA_CDIR"loadall.dll"
#else
/*
** Note to distribution maintainers: do NOT patch the following lines!
** Please read ../doc/install.html#distro and pass PREFIX=/usr instead.
*/
#ifndef LUA_MULTILIB
#define LUA_MULTILIB	"lib"
#endif
#ifndef LUA_LMULTILIB
#define LUA_LMULTILIB	"lib"
#endif
#define LUA_LROOT	"/usr/local"
#define LUA_LUADIR	"/lua/5.1/"
#define LUA_LJDIR	"/luajit-2.1.0-beta3/"

#ifdef LUA_ROOT
#define LUA_JROOT	LUA_ROOT
#define LUA_RLDIR	LUA_ROOT "/share" LUA_LUADIR
#define LUA_RCDIR	LUA_ROOT "/" LUA_MULTILIB LUA_LUADIR
#define LUA_RLPATH	";" LUA_RLDIR "?.lua;" LUA_RLDIR "?/init.lua"
#define LUA_RCPATH	";" LUA_RCDIR "?.so"
#else
#define LUA_JROOT	LUA_LROOT
#define LUA_RLPATH
#define LUA_RCPATH
#endif

#define LUA_JPATH	";" LUA_JROOT "/share" LUA_LJDIR "?.lua"
#define LUA_LLDIR	LUA_LROOT "/share" LUA_LUADIR
#define LUA_LCDIR	LUA_LROOT "/" LUA_LMULTILIB LUA_LUADIR
#define LUA_LLPATH	";" LUA_LLDIR "?.lua;" LUA_LLDIR "?/init.lua"
#define LUA_LCPATH1	";" LUA_LCDIR "?.so"
#define LUA_LCPATH2	";" LUA_LCDIR "loadall.so"

#define LUA_PATH_DEFAULT	"./?.lua" LUA_JPATH LUA_LLPATH LUA_RLPATH
#define LUA_CPATH_DEFAULT	"./?.so" LUA_LCPATH1 LUA_RCPATH LUA_LCPATH2
#endif`


The problem is that the preprocesser detects that the platform is windows. It sets 'LUA_PATH_DEFAULT ' and 'LUA_CPATH_DEFAULT ' to the windows specific ones. Luajit supports windows with visual studio and other developement environments as well. For Visual studio that path would make sense, however on msys2 the linux options must be used instead. The simple fix would be to patch '#if defined(_WIN32)' to '#if 0'.

**Comment by FractalU** [comment]
Almost forgotten. 'LUA_LROO' needs to be adjusted as well with patching from '#define LUA_LROOT	"/usr/local"' to
'#define LUA_LROOT	"!\\.."'

**Comment by revelator** [comment]
could probably patch in the mingw path with a sed command in PKGBUILD.

**Comment by FractalU** [comment]
BTW I checked out PKGBUILD. There I see that it uses luajit from the download page.

> source=("https://luajit.org/download/LuaJIT-${pkgver//_/-}.tar.gz"
>         001-make-import-library.patch
>         002-fix-pkg-config-file.patch)

The 2.1.0-beta3 version is about 5 years old and outdated. The project is currently being developed in the 2.1 brand of the luajit git repository. In the download page it's written that distros should do a snapshot of a branch.

In luajit download page:

>  The git master branch will be phased out and is pinned to the v2.0 branch. Please follow the versioned branches v2.1 or v2.0 instead.
> ### Releases of Actively Developed Branches
> 
> Releases are only made occasionally. You're strongly encouraged to follow the git branches.
> 
> Distros that require releases should do regular snapshots of a branch. Do not attempt to cherry-pick or backport individual changes, no matter how self-standing individual changes look (because they often are not). 

Even mike pall (the creator of luajit) admitted in a git issue the he won't do releases anymore. The comment can be found under the link '665 (comment)' in 'PGP sign releases' git issue.

Mike pall comment in 'Project status':
> Look at the git v2.1 history and judge yourself. Releases are an antiquated concept. Most everyone is using v2.1, anyway.

Its really unfortunate that he doesn't put releases anymore. All the later improvments and bug fixes are now in the 2.1 branch.
