### ISSUE TITLE
Regenerate libzip and other zlib-dependent packages

### ISSUE THREAD

**Issue by rolandlo** [msys2/MINGW-packages#11498]
The package `zlib` has recently been [updated](https://github.com/msys2/MINGW-packages/commit/3d5f68df62da887010ed870bb5a44ddd69ae976e) to version 1.12.12, thereby including an important security fix. 
The package `libzip` depends on  `zlib`, but has [not been updated since January 8](https://github.com/msys2/MINGW-packages/commits/master/mingw-w64-libzip), so it does not contain the security fix. I would therefore ask for a regeneration of the `libzip`-package. Probably other `zlib`-dependent packages should be regenerated, too.

**Comment by MehdiChinoune** [comment]
Why should dependent packages be rebuilt?

**Comment by rolandlo** [comment]
Looks like it is not necessary. I was wrongly assuming that `zlib` was baked into `libzip` during the build process, which is not the case. Sorry for the noise.
