### ISSUE TITLE
[cmake] can't find its CMAKE_ROOT with mingw-w64-x86_64-cmake

### ISSUE THREAD

**Issue by carenas** [msys2/MINGW-packages#11507]
showing:

```
$ cmake --version
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/mingw64/share/cmake-3.22.1
cmake version 3.22.1
```

duplicating the /ming64/share/cmake directory with that name seems to be enough to "fix" this

**Comment by Biswa96** [comment]
It seems that you are using older cmake package. Here is the output in my system.

```
$ cmake --version
cmake version 3.23.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by carenas** [comment]
3.22.1 was the version from msys cmake (3.22.1-2) which somehow got this one confused, removing that package seems to have helped as well

**Comment by Biswa96** [comment]
Yeah, msys and mingw packages should not be mixed most of the caes.
