### ISSUE TITLE
problem with Msys Makefiles and alure

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#11506]
bails out when using Msys Makefiles, changing it to use ninja and it builds.
not really sure why but seems ninja is doing some wrapping that this package works better building with.

**Comment by 1480c1** [comment]
From what I understand, it's preferred to use Ninja instead of Msys Makefiles since Msys Makefiles was designed for the Msys from MinGW, so not MSYS2 nor mingw-w64

**Comment by Biswa96** [comment]
It fails with some weird error.

```
[  2%] Building CXX object CMakeFiles/ALURE32.dir/src/codec_fluidsynth.obj
g++.exe: fatal error: no input files
compilation terminated.
/bin/sh: line 1: -IF:/msys64/ucrt64/include/glib-2.0: No such file or directory
/bin/sh: line 1: -IF:/msys64/ucrt64/lib/glib-2.0/include: No such file or directory
/bin/sh: line 1: -mms-bitfields: command not found
/bin/sh: line 1: -IF:/msys64/ucrt64/include/opus: No such file or directory
make[2]: *** [CMakeFiles/ALURE32.dir/build.make:258: CMakeFiles/ALURE32.dir/src/codec_fluidsynth.obj] Error 127
```

Wondering what the cause will be 🤔

**Comment by revelator** [comment]
thx :)
