### ISSUE TITLE
python-binwalk - pwdpp dependency?

### ISSUE THREAD

**Issue by mightymos** [msys2/MINGW-packages#11517]
Could someone confirm whether or not python-binwalk runs when installed via pacman?

Seems on Windows, binwalk extractor.py should be importing [pwdpp] rather than [pwd].
Also [pwdpp] requires a fix to install_requires in setup.py to work.
https://bitbucket.org/hhsprings/pwdpp/src/master/
https://pypi.org/project/pwdpp/

Finally am able to run binwalk after these fixes and installed via pip.
Would just like some confirmation I'm not missing something prior to attempting PRs.

**Comment by Biswa96** [comment]
This question should be asked in upstream. There is already two open issues about that topic https://github.com/ReFirmLabs/binwalk/issues?q=is%3Aissue+is%3Aopen+pwd

**Comment by mightymos** [comment]
Closed due to fixes being implemented upstream.
