### ISSUE TITLE
Static linking with libssh and libsrt

### ISSUE THREAD

**Issue by msink** [msys2/MINGW-packages#11513]
If both `libssh.a` and `libsrt.a` have to be linked in application - linker error:
```
...\lib\libssh.a(libcrypto.c.obj):(.text+0x1000): multiple definition of `md5_init'; ...\lib\libsrt.a(md5.cpp.obj):md5.cpp:(.text+0x850): first defined here
```
To repoduce: see https://github.com/msys2/MINGW-packages/issues/8824#issuecomment-1087561620
replace `-l:libssh.dll.a` to `-lssh`

**Comment by Biswa96** [comment]
Those are two totally different object files in different libraries i.e. libcrypto.c.obj and md5.cpp.obj. Can we do anything from packaging side?

**Comment by msink** [comment]
Somehow make `md5_init` function prefixed in `libssh` or `libstr` (or both)?

**Comment by Biswa96** [comment]
That should be asked in upstream.

**Comment by Biswa96** [comment]
How can we make sure that no other project is using that function from libssh or libsrt?

**Comment by Biswa96** [comment]
I have sent a pull request in srt project https://github.com/Haivision/srt/pull/2301.
