### ISSUE TITLE
cmake-gui.exe: error while loading shared libraries: libuv-1.dll:

### ISSUE THREAD

**Issue by JaiSoone** [msys2/MINGW-packages#11526]
NateJoe@TinkeringAround UCRT64 ~
$ pwd
/home/NateJoe
$ whence cmake
cmake is /ucrt64/bin/cmake
$ whence cmake-gui
cmake-gui is /ucrt64/bin/cmake-gui
$ pacman -Qo /ucrt64/bin/cmake.exe
/ucrt64/bin/cmake.exe is owned by mingw-w64-ucrt-x86_64-cmake 3.23.1-1
$ pacman -Qo /ucrt64/bin/cmake-gui.exe
/ucrt64/bin/cmake-gui.exe is owned by mingw-w64-ucrt-x86_64-cmake 3.23.1-1
$ cmake-gui
C:/msys64/ucrt64/bin/cmake-gui.exe: error while loading shared libraries: libuv-1.dll: cannot open shared object file: No such file or directory
$ whence libuv-1.dll
libuv-1.dll is /ucrt64/bin/libuv-1.dll
$ pacman -Qo /ucrt64/bin/libuv-1.dll
/ucrt64/bin/libuv-1.dll is owned by mingw-w64-ucrt-x86_64-libuv 1.42.0-3

My MSYS2 setup is otherwise working rather well, but this is the first time I've had to use cmake-gui.
I'm assuming it aught to at least print out an error message if it finds something that it doesn't like and exit gracefully.

**Comment by MehdiChinoune** [comment]
Did you install qt6-base?

**Comment by JaiSoone** [comment]
I'm trying to build QGIS and they asked for qt5; so, I downloaded it via pacman:
pacman -S --needed mingw-w64-ucrt-x86_64-qwt-qt5
pacman -S --needed mingw-w64-ucrt-x86_64-qca-qt5

Do I need more?

**Comment by MehdiChinoune** [comment]
What that to do with cmake-gui?

**Comment by MehdiChinoune** [comment]
BTW, qgis is available as a package.

**Comment by JaiSoone** [comment]
QGIS says to make certain make file adjustments via ccmake which is a tui interface to the make files and I was guessing I could do the same thing via cmake-gui, but cmake-gui --help doesn't eve work. I looked for a qgis package in the Base Packages page and found no hits on "qgis" via firefox's "Find in page .." search machanism. What's the proper name to search under for QGIS?

**Comment by MehdiChinoune** [comment]
as I said you have to install qt6-base? It is mentioned as an optional dependency when you install cmake.

**Comment by JaiSoone** [comment]
I missed where for mingw-w64-ucrt-x86_64-cmake it says that "mingw-w64-ucrt-x86_64-qt6-base  CMake Qt GUI)" is an Optional Dependency.

**Comment by JaiSoone** [comment]
I still haven't found where qgis is available as a package. What makes you think that?

**Comment by MehdiChinoune** [comment]
> I still haven't found where qgis is available as a package. What makes you think that?

There is not, I was mistaken. I thought you wouldn't read the comment after I deleted it immediatly.
Sorry!

**Comment by JaiSoone** [comment]
Thanks, nonetheless. I'll have to pay more attention to optional dependencies in the future.

**Comment by JaiSoone** [comment]
My bad, Thanks

**Comment by MehdiChinoune** [comment]
@JaiSoone qgis is now available as a package.
