### ISSUE TITLE
App crashed with pango-1.50.4 and above version 

### ISSUE THREAD

**Issue by taozuhong** [msys2/MINGW-packages#11527]
pango-1.50.4 and above version has an issue:
app crashed while installing them, but pango-1.50.3 works fine.

The package size could show the difference:
```
Package(1) mingw-w64-x86_64-pango-1.50.7-1
Download size：        0.54 MiB
All Install size：    3.59 MiB
Net update size：    -10.74 MiB

Package(1) mingw-w64-x86_64-pango-1.50.3-1
All Install size：  14.33 MiB
Net update size：    10.74 MiB
```

**Comment by Biswa96** [comment]
Can you provide the steps about how to reproduce your issue please?

> The package size could show the difference

Pango package was split into pango and pango-docs in this commit https://github.com/msys2/MINGW-packages/commit/72907b8c0e58e8a990398980db0433f0c22af29f. Hence the size reduction.

**Comment by lazka** [comment]
Do demo apps like gtk3-widget-factory.exe work for you?

**Comment by taozuhong** [comment]
1. gtk4-demo and gtk4-widget-factory work fine with pango-1.50.3-1
2. Then install pango-1.50.7-1, and they all crashed.

```
$ pacman -S mingw-w64-x86_64-pango
正在解析依赖关系...
正在查找软件包冲突...

软件包 (1) mingw-w64-x86_64-pango-1.50.7-1

下载大小：        0.54 MiB
全部安装大小：    3.59 MiB
净更新大小：    -10.74 MiB

:: 进行安装吗？ [Y/n] Y
:: 正在获取软件包......
 mingw-w64-x86_64...   554.0 KiB   385 KiB/s 00:01 [#####################] 100%
(1/1) 正在检查密钥环里的密钥                       [#####################] 100%
(1/1) 正在检查软件包完整性                         [#####################] 100%
(1/1) 正在加载软件包文件                           [#####################] 100%
(1/1) 正在检查文件冲突                             [#####################] 100%
(1/1) 正在检查可用存储空间                         [#####################] 100%
:: 正在处理软件包的变化...
(1/1) 正在更新 mingw-w64-x86_64-pango              [#####################] 100%

MINGW64 /d/Codelabs/GitHub/kangaroo/build
$ gtk4-demo &
[1] 3352

MINGW64 /d/Codelabs/GitHub/kangaroo/build
$
[1]+  退出 127              gtk4-demo

MINGW64 /d/Codelabs/GitHub/kangaroo/build
$ gtk4-widget-factory.exe &
[1] 3353

MINGW64 /d/Codelabs/GitHub/kangaroo/build
$
[1]+  退出 127              gtk4-widget-factory.exe

```

**Comment by lazka** [comment]
Does `PANGOCAIRO_BACKEND=fontconfig gtk4-widget-factory.exe` work?

**Comment by taozuhong** [comment]
gtk4-demo and gtk4-widget-factory with PANGOCAIRO_BACKEND are crashed too.

**Comment by Biswa96** [comment]
In my system, both gtk4-demo & gtk4-widget-factory work falwlessly with & without `PANGOCAIRO_BACKEND=fontconfig` environment.

**Comment by lb90** [comment]
Hi @taozuhong! It would be very helpful to get a stacktrace with gdb. If you mind, you could also build a debug version of pango. To do that, open an MSYS2 MSYS shell and run:

* pacman -S --needed git
* git clone https://github.com/msys2/MINGW-packages.git
* cd MINGW-packages/mingw-w64-pango
* Edit PKGBUILD and change the options array, removing 'strip' and adding 'debug':
   ```diff
   -options=('staticlibs' 'strip' 'emptydirs')
   +options=('staticlibs' 'debug' 'emptydirs')
   ```
* MINGW_ARCH=mingw64 makepkg-mingw
* pacman -U mingw-w64-x86_64-pango-*.pkg.tar.zstd

**Comment by taozuhong** [comment]
Thanks for your advice, I've tried to compile from the source on my machine, compiled successfully and install it, then run gtk4-demo and gtk4-widget-factory, they all work fine.

**Comment by lb90** [comment]
If the bug only happens with release builds, you can recompile the package with only the option 'strip' removed:

```diff
-options=('staticlibs' 'strip' 'emptydirs')
+options=('staticlibs' 'emptydirs')
```

That should give enough informations in the stacktrace

**Comment by Biswa96** [comment]
@taozuhong Is this exist/reproducible now?

**Comment by taozuhong** [comment]
Not exist anymore after I recompile it from source.
