### ISSUE TITLE
"gcc -dumpmachine" returns wrong value

### ISSUE THREAD

**Issue by Miazite** [msys2/MINGW-packages#11530]
I have a build system that depends on the CPU model. However, I can't get it because "gcc -dumpmachine" returns a value that normally should not be returned:
![image](https://user-images.githubusercontent.com/103771360/164264019-ec825b5a-0c31-4e3b-b72a-620e5ef5a1a8.png)
The documentation I read said a "target triplet" is returned containing the CPU model, vendor, and operating system name.
Strangely enough, it worked before updating to Windows 11. Any ideas?

Thank you!

**Comment by lazka** [comment]
hm, I get `x86_64-w64-mingw32` here

**Comment by 1480c1** [comment]
just to confirm, can you run `command -v gcc` and `gcc -v`?

**Comment by revelator** [comment]
same here.. not sure what is up with that Oo

**Comment by brisingraerowing** [comment]
GCC 11.3.0 spits out the normal target triplet for me (on Win11). What GCC version do you have installed?

**Comment by MehdiChinoune** [comment]
no response!
