### ISSUE TITLE
ncurses references `nanosleep`

### ISSUE THREAD

**Issue by lhmouse** [msys2/MINGW-packages#11543]
```text
lhmouse-pc ~ # nm --undefined-only /mingw64/lib/libncurses.a  | fgrep nanosleep
                 U nanosleep
```

This is undesired, as anything that requires **ncurses** will have another dependency on **winpthreads**.

I tried rebuilding it locally and the symbol was gone. I am not sure whether it should be rebuilt.

**Comment by lazka** [comment]
In theory we try to disable it:

* https://github.com/msys2/MINGW-packages/blob/20373c1101faa44a908054bc8415a0be71334d0e/mingw-w64-ncurses/PKGBUILD#L53
* https://github.com/msys2/MINGW-packages/blob/20373c1101faa44a908054bc8415a0be71334d0e/mingw-w64-ncurses/PKGBUILD#L64

**Comment by lhmouse** [comment]
Yes I had noticed it. I was curious why it didn't have an effect.
