### ISSUE TITLE
darktable fails builds with graphicsmagick 1.3.38-2

### ISSUE THREAD

**Issue by gi-man** [msys2/MINGW-packages#11541]
@kmilos downgrading to 1.3.38-1 does work on my system.

**Comment by kmilos** [comment]
I know, a dt PR to fix the installer is on the way...

**Comment by todd-prior** [comment]
Do I need to upgrade graphics magick??  

Trying to build tonight failing on WIndow with MSYS2

CMake Error at C:/msys64/home/xxxxxx/darktable/build/bin/cmake_install.cmake:1025 (file):
  file INSTALL cannot find
  "C:/msys64/mingw64/bin/../lib/GraphicsMagick-1.3.37/modules-Q16/coders": No
  error.
Call Stack (most recent call first):
  C:/msys64/home/xxxxxx/darktable/build/cmake_install.cmake:43 (include)


CPack Error: Error when generating package: darktable
FAILED: CMakeFiles/package.util
cmd.exe /C "cd /D C:\msys64\home\xxxxxx\darktable\build && C:\msys64\mingw64\bin\cpack.exe --config ./CPackConfig.cmake"
ninja: build stopped: subcommand failed.

**Comment by todd-prior** [comment]
How did you do this??  thx


> @kmilos downgrading to 1.3.38-1 does work on my system.

**Comment by gi-man** [comment]
This should fix it or install the previous version from the repo with pacman -U

**Comment by gi-man** [comment]
And i just did a build with the current package and using master and it worked.

**Comment by todd-prior** [comment]
@gi-man  I will go back and check i had to hack it....my install only Had Q-8 with v 1.3.37...I updated all of my Msys2 and then I had 1.3.38 with Q-16 but my build kept looking for 1.3.37 with Q16...so I just renamed the directory for now and it seemed to work...its a hack but it worked.... previously I tried to delete my build folder and go from scratch  and it was still trying to find 1.3.37 so only the hack worked....

**Comment by Biswa96** [comment]
This issue was fixed in upstream as mentioned https://github.com/msys2/MINGW-packages/issues/11541#issuecomment-1106031631
