### ISSUE TITLE
godot incompatible with new mbedtls

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#11563]
building godot with mbedtls-3.4.4 fails due to changes in the source which are incompatible with godots layout.

**Comment by revelator** [comment]
removing mbedtls from the files pkgconfig searches from PKGBUILD allows it to build again, but a patch to fix this would probably be better in the long run.

**Comment by Biswa96** [comment]
Is it reported in upstream? For example, ffmpeg has a patch for mbedtls v3 https://ffmpeg.org/pipermail/ffmpeg-devel/2022-April/295578.html

**Comment by revelator** [comment]
patch looks like it could be used as a basis for fixing this as missing config.h is one of the things godot complains about.
not reported upstream havent had the time yet sorry.

**Comment by revelator** [comment]
seems to be working now closing issue.
