### ISSUE TITLE
[Package-Request] Raylib

### ISSUE THREAD

**Issue by jacknicklenson** [msys2/MINGW-packages#11565]
Hi,

Would it be possible to include a package raylib ?
https://github.com/raysan5/raylib

Thanks,
Jack.

**Comment by Biswa96** [comment]
Hi @jacknicklenson, I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2226878748. Follow these steps:

1. Scroll down and download the correct artifact. It'll be a zip file.
2. Extract the package (.tar.zst) from zip file.
3. Install it with `pacman -U the-package-name.tar.zst` command.
