### ISSUE TITLE
Quick query on the libraries in the lib folder

### ISSUE THREAD

**Issue by TheShermanTanker** [msys2/MINGW-packages#11593]
Not sure if this is the right place for this, but currently I have the ucrt build of gcc installed, and in the /lib folder are libraries, as expected, but what I'm unsure of is whether the corresponding Windows libraries like wsock32.dll or psapi.dll (libwsock32.a and libpsapi.a in /lib) are entirely different static implementations or not. When I do -lpsapi or -lwinmm for instance, am I statically linking them into the resulting binary directly (I don't wish to do this), or are they just a list of symbols which let the linker know that it has to resolve the actual names in the real dlls at runtime?

**Comment by 1480c1** [comment]
To verify @Biswa96 point, you can run nm on it and see that all the addresses are `0x0`, indicative of the fact that the "library" doesn't actually provide any code, just names

```bash
nm -CAg --defined-only C:\msys64\ucrt64\lib\libws2_32.a
C:\msys64\ucrt64\lib\libws2_32.a:libws2_32t.o:0000000000000000 I __lib64_libws2_32_a_iname
C:\msys64\ucrt64\lib\libws2_32.a:libws2_32h.o:0000000000000000 I _head_lib64_libws2_32_a
C:\msys64\ucrt64\lib\libws2_32.a:libws2_32s00196.o:0000000000000000 I __imp_socket
C:\msys64\ucrt64\lib\libws2_32.a:libws2_32s00196.o:0000000000000000 T socket
C:\msys64\ucrt64\lib\libws2_32.a:libws2_32s00195.o:0000000000000000 I __imp_shutdown
C:\msys64\ucrt64\lib\libws2_32.a:libws2_32s00195.o:0000000000000000 T shutdown
...
C:\msys64\ucrt64\lib\libws2_32.a:lib64_libws2_32_a-WspiapiLoad.o:0000000000000000 T WspiapiLoad
C:\msys64\ucrt64\lib\libws2_32.a:lib64_libws2_32_a-WspiapiGetAddrInfo.o:0000000000000000 T WspiapiGetAddrInfo
C:\msys64\ucrt64\lib\libws2_32.a:lib64_libws2_32_a-WspiapiGetNameInfo.o:0000000000000000 T WspiapiGetNameInfo
C:\msys64\ucrt64\lib\libws2_32.a:lib64_libws2_32_a-WspiapiFreeAddrInfo.o:0000000000000000 T WspiapiFreeAddrInf
```

**Comment by 1480c1** [comment]
Another indicator is the fact that they also have `__imp_` prefixes in some symbols, which usually means the symbol is inside a shared library

**Comment by TheShermanTanker** [comment]
> For normal questions, [discussions](https://github.com/msys2/MINGW-packages/discussions) are preffered.

My bad, I didn't see the discussions tab when writing this.  I'll move over there instead and close this issue
