### ISSUE TITLE
fatal error - add_item

### ISSUE THREAD

**Issue by jsh562** [msys2/MINGW-packages#11616]
Hello, I get this type of error many times when installing gems.
Tried on either Ruby 2.7 and 2.6 on Windows, both installed with the dev kit.
Occurs with many different gems. around 10-40% of the bundle does this depending on circumstances.

`Installing puma 5.6.4 with native extensions
      0 [main] locale (9392) D:\Ruby26-x64\msys64\usr\bin\locale.exe: *** fatal error - add_item ("\??\D:\Ruby26-x64\msys64", "/", ...) failed, errno 1
Stack trace:
Frame        Function    Args
000FFFFCD30  001800627DE (0018029394A, 0018026EE41, 00800000000, 000FFFF8B30)
000FFFFCD30  0018004846A (00000000000, 000FFFFCD30, 00180020010, 000FFFFABF0)
000FFFFCD30  001800484A2 (000FFFF9BC0, 00000000001, 00800000000, 00000000001)
000FFFFCD30  001800E7167 (00000000000, 00040000024, 00000000000, 00000000000)
000FFFFCD30  0018012C705 (001800D63F4, 00000000000, 00000000000, 00000000000)
000FFFFCD30  00180048AB8 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180047716 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  001800477C4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
      0 [main] make (9020) D:\Ruby26-x64\msys64\usr\bin\make.exe: *** fatal error - add_item ("\??\D:\Ruby26-x64\msys64", "/", ...) failed, errno 1
      0 [main] make (4616) D:\Ruby26-x64\msys64\usr\bin\make.exe: *** fatal error - add_item ("\??\D:\Ruby26-x64\msys64", "/", ...) failed, errno 1
      0 [main] make (10056) D:\Ruby26-x64\msys64\usr\bin\make.exe: *** fatal error - add_item ("\??\D:\Ruby26-x64\msys64", "/", ...) failed, errno 1`

Not sure how to work around this and do not really understand how it impacts the final state.

**Comment by adalisk-emikhaylov** [comment]
Had a similar error, fixed it by adding the MSYS2 installation directory to Windows Defender exceptions, and rebooting.

**Comment by Biswa96** [comment]
The path `D:\Ruby26-x64\msys64` does not seem from msys2 installation. Please try with the latest installer from msys2.org.

**Comment by jsh088** [comment]
Yes, because that is from 2022 with ruby 2.6 as shown.... Have you installed 2.6 devkit before? I didn't change the msys folder in any way or the installation other than the root path.
I have also tried with ruby 3.0, 3.1, 3.2

**Comment by jsh562** [comment]
Yes, because that is from 2022 with ruby 2.6 as shown... Have you installed 2.6 devkit before? I didn't change the msys folder in any way or the installation, other than the root path.
I have also recently tried ruby 3.0, 3.1, 3.2 and they all give me similar issues....
