### ISSUE TITLE
qtcreator not work on win8.1

### ISSUE THREAD

**Issue by yuryfdr** [msys2/MINGW-packages#11613]
## Describe the issue

qtcreator and qt6 related gui tools cannot initialize platform plugins ater update on windows 8.1 (win10 all works good)

- OS: [Windows 8.1 64bit]

**Comment by yuryfdr** [comment]
but qtcreator-6 before update works on win8.1 
is the way to build qt-creator with qt5? version 6 successfully builds and work on gentoo with qt-5.15.3
for example add package qt-creator-qt5?

**Comment by lazka** [comment]
> but qtcreator-6 before update works on win8.1

it was witched to qt6 ~6 months ago

> is the way to build qt-creator with qt5? version 6 successfully builds and work on gentoo with qt-5.15.3
> for example add package qt-creator-qt5?

maybe, it was switched here: https://github.com/msys2/MINGW-packages/commit/894e976ff3789b497653584fe985d9fa29639612

I doubt anyone cares enough though, with Windows 8.1 being so close to EOL.

**Comment by yuryfdr** [comment]
> > but qtcreator-6 before update works on win8.1
> 
> it was witched to qt6 ~6 months ago
> 

but it worked in march with qt6-6.2.3 (approximately) (mingw-w64-x86_64-qt-creator-6.0.2-1-any.pkg.tar.zst)

**Comment by lazka** [comment]
Just a guess, but could be that Qt 6.3 started depending on Windows 10 features.

**Comment by stevenclarke9** [comment]
It was Qt 6.2 LTS that changed to needing Windows 10.
