### ISSUE TITLE
Result of gcc complie does't follow the correct sequence of "printf"

### ISSUE THREAD

**Issue by chentian4477** [msys2/MINGW-packages#11624]
Hello, everyone.
I found a problem about the wrong sequence of the "printf" when using gcc compiler in Msys2.
There are no prints when I call the "printf" function in the "menu" block.
In Msys2, using command " ./a.exe ", there are no prints at first, when I input the digits, but the prints appears after I quit the program.
In Window10, double click the a.exe, it prints the message, prints again when I input the digits again. It alway print the messages until I quit the program. (correct running)
In Debian11.3, complie with the same code, run the result "./a.out", running is correct too, just like in Windows10.

The c codes are from "C Primer Plus (6th Edition)"-chapter 9: 
Listing 9.9  usehotel.c
Listing 9.10  hotel.c
Listing 9.11  hotel.h

Running in Msys2(wrong running): 
![Running in Msys2(wrong running)](https://user-images.githubusercontent.com/36390300/167280888-e11d2f63-b305-4f35-ae70-c86cf9754275.png)

Running in Debian11 3(correct running):
![Running in Debian11 3(correct running)](https://user-images.githubusercontent.com/36390300/167280884-aaef8745-234c-4e74-98cb-486cc2ac3d65.png)

Running in Windows10(correct running):
![Running in Windows10(correct running)](https://user-images.githubusercontent.com/36390300/167280889-c7f10343-9d79-49d0-ae89-dc7bb6c6fc9d.png)

Something wrong with Msys2 gcc?  How to fix it?
[hotel.zip](https://github.com/msys2/MINGW-packages/files/8646294/hotel.zip)

**Comment by 1480c1** [comment]
Aside from mintty, perhaps you might require a `fflush(stdout);` after your printfs.

Afaik, mintty (the terminal emulator msys2 uses) handles stdout, stdin, and stderr in a bit special way as they are actually just piped "files" or something, so that might be the reason why?

**Comment by chentian4477** [comment]
>

**Comment by chentian4477** [comment]
> Aside from mintty, perhaps you might require a `fflush(stdout);` after your printfs.
> 
> Afaik, mintty (the terminal emulator msys2 uses) handles stdout, stdin, and stderr in a bit special way as they are actually just piped "files" or something, so that might be the reason why?

Do you have ideas to fix this problem?  Install the `fflush(stdout)`,  I have no ideas.

**Comment by chentian4477** [comment]
Aside from mintty, perhaps you might require a fflush(stdout); after your printfs.

Afaik, mintty (the terminal emulator msys2 uses) handles stdout, stdin, and stderr in a bit special way as they are actually just piped "files" or something, so that might be the reason why?

Do you have ideas to fix this problem? Install the fflush(stdout), I have no ideas.

**Comment by brisingraerowing** [comment]
This might be a MinTTY quirk. Try running the program using WinPTY.

**Comment by Jolyk** [comment]
I confirm this bug on Windows 8.1

**Comment by chentian-4477** [comment]
Will the MinTTY fix this problem?

**Comment by chentian-4477** [comment]
> This might be a MinTTY quirk. Try running the program using WinPTY.

Will the MinTTY fix this problem?

**Comment by mmuetzel** [comment]
Maybe try adding `fflush(stdout);` every time before calling `scanf` to tell the terminal that the output buffer should be flushed. Otherwise, the behavior of your example is implementation dependent (iiuc).

**Comment by oltolm** [comment]
Can this be closed?
