### ISSUE TITLE
Where does gtk find its config files on msys2

### ISSUE THREAD

**Issue by ThosRTanner** [msys2/MINGW-packages#11621]
Apologies if this is the wrong place to open this, but it seems to be windows specfic.

I have built a gtk3 program under windows using msys2/mingw64. It runs fine, and if I call all the necessary stuff to another directory outside mingw control, it runs fine there. So far so good.

For the 'standalone' version of the program, I can make an etc/gtk-3.0/settings.ini file in the same directory as the program and it recognises that. This is what I expected, as the lib directory with necessary dlls also lives with the standalone copy

However, if I try to run the program I've built, it also needs the etc directory in the same directory as the executable. This is confusing to say the least. I've tried creating the file in /etc/gtk-3.0 and ~/.config/gtk-3.0 and it isn't recognised in either of those places.

**Comment by Biswa96** [comment]
It's possible to find the search directory with programs like Process Hacker or Process Monitor. Can you provide an example code to reprosuce the issue?

**Comment by lazka** [comment]
https://gitlab.gnome.org/GNOME/gtk/-/blob/08d386844a0bd2967edc3ff6a99c310d208c4201/gtk/gtkwin32.c#L219

https://gitlab.gnome.org/GNOME/glib/-/blob/91407cd7efec344f6bb5fd88fd7f771afb4fed25/glib/gwin32.c#L234

**Comment by ThosRTanner** [comment]
Ugh. That sort of sucks, as it means I can't have a global config for gtk under windows at all

**Comment by lazka** [comment]
What do you need it for? Most things should either be configurable via the C API anyway, or derived from the System.

**Comment by ThosRTanner** [comment]
It certainly doesn't inherit the scrollbar settings from windows. You always get the collapsed ones which I find incredibly difficult to deal with.

Also I like my menus to have icons.

Which apparently means I need a settings.ini file for every gtk3 program :-(

**Comment by ThosRTanner** [comment]
feel free to close this though, because it's clearly not an msys2 problem

**Comment by lazka** [comment]
> It certainly doesn't inherit the scrollbar settings from windows. You always get the collapsed ones which I find incredibly difficult to deal with.

There happens to be an env var for this: `GTK_OVERLAY_SCROLLING=0`

**Comment by lazka** [comment]
> It certainly doesn't inherit the scrollbar settings from windows. You always get the collapsed ones which I find incredibly difficult to deal with.

Ah, I see, you can switch this globally on Windows. I think you could file a bug report with GTK and ask them to respect the global Windows setting for this.

**Comment by ThosRTanner** [comment]
Fingers crossed: https://gitlab.gnome.org/GNOME/gtk/-/issues/4899

**Comment by ThosRTanner** [comment]
For those who find this ticket in the future, I found another ticket, that says that gtk actually will use %LOCALAPPDATA%\gtk-3.0\settings.ini if it exists, and that works (which was a surprise given the code referenced above!)

Can't find that in any documentation, but it is useful to know!

**Comment by lazka** [comment]
Oh, I didn't know that :)
