### ISSUE TITLE
gcc.exe: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory

### ISSUE THREAD

**Issue by nyambol** [msys2/MINGW-packages#11622]
Since last August, I have compiled the latest emacs about once a month. Last time was on 24 March, and it worked as expected.  Today, `.\configure` puked with the message that gcc couldn't compile an executable.

I'm now in the state of can't use, can't upgrade, can't remove & reinstall gcc. How does this happen? Is there a way to fix this, short of a complete reinstallation of MSYS? My most common usage is running git in bash, because the windows version causes issues with some things I work on. AFAIK, I haven't done anything to the system itself in the past month. I certainly haven't moved around any of the gcc files.

```
micha@OPTI-9010-WIN10 MINGW64 /c/Emacs/emacs-src/lib
$ gcc --version
gcc.exe (Rev3, Built by MSYS2 project) 11.2.0
```

The error:

```
micha@OPTI-9010-WIN10` MINGW64 /c/Emacs/emacs-src/lib
$ gcc nansleep.c
gcc.exe: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
compilation terminated.
```

App upgrade:

```
micha@OPTI-9010-WIN10 MINGW64 /c/Emacs/emacs-src/lib
$ pacman -S mingw-w64-x86_64-gcc
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing mingw-w64-x86_64-gcc (11.3.0-1) breaks dependency 'mingw-w64-x86_64-gcc=11.2.0-3' required by mingw-w64-x86_64-gcc-objc
:: installing mingw-w64-x86_64-gcc (11.3.0-1) breaks dependency 'mingw-w64-x86_64-gcc=11.2.0-3' required by mingw-w64-x86_64-libgccjit
```

Through the looking glass:
```
micha@OPTI-9010-WIN10 MINGW64 /c/Emacs/emacs-src/lib
$ pacman -S mingw-w64-x86_64-gcc-objc
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing mingw-w64-x86_64-gcc (11.3.0-1) breaks dependency 'mingw-w64-x86_64-gcc=11.2.0-3' required by mingw-w64-x86_64-libgccjit

micha@OPTI-9010-WIN10 MINGW64 /c/Emacs/emacs-src/lib
$ pacman -S mingw-w64-x86_64-libgccjit
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing mingw-w64-x86_64-gcc (11.3.0-1) breaks dependency 'mingw-w64-x86_64-gcc=11.2.0-3' required by mingw-w64-x86_64-gcc-objc
```

Files:
```
micha@OPTI-9010-WIN10 MINGW64 /c/Emacs/emacs-src/lib
$ gcc -print-search-dirs
install: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/
programs: =C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/;C:/msys64/mingw64/bin/../lib/gcc/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/x86_64-w64-mingw32/11.2.0/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/
libraries: =C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/;C:/msys64/mingw64/bin/../lib/gcc/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/lib/x86_64-w64-mingw32/11.2.0/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/lib/../lib/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../x86_64-w64-mingw32/11.2.0/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../lib/;D:/a/msys64/mingw64/x86_64-w64-mingw32/lib/x86_64-w64-mingw32/11.2.0/;D:/a/msys64/mingw64/x86_64-w64-mingw32/lib/../lib/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/lib/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../;D:/a/msys64/mingw64/x86_64-w64-mingw32/lib/

micha@OPTI-9010-WIN10 MINGW64 /c/Emacs/emacs-src/lib
$ locate cc1
/mingw64/lib/gcc/x86_64-w64-mingw32/11.2.0/cc1.exe
/mingw64/lib/gcc/x86_64-w64-mingw32/11.2.0/cc1obj.exe
/mingw64/lib/gcc/x86_64-w64-mingw32/11.2.0/cc1objplus.exe
/mingw64/lib/gcc/x86_64-w64-mingw32/11.2.0/cc1plus.exe
```

System upgrade:
```
micha@OPTI-9010-WIN10 MINGW64 /c/Emacs/emacs-src/lib
$ pacman -Syu
:: Synchronizing package databases...
[ ... ]
:: Starting full system upgrade...
:: Replace autoconf with msys/autoconf-wrapper? [Y/n]
:: Replace mingw-w64-x86_64-libtool with mingw64/mingw-w64-x86_64-libltdl? [Y/n]
[ ... ]
Total Download Size:    261.78 MiB
Total Installed Size:  1674.59 MiB
Net Upgrade Size:       -41.30 MiB
[ ... ]
error: failed to commit transaction (conflicting files)
mingw-w64-x86_64-emacs: /mingw64/share/applications/emacs-mail.desktop exists in filesystem
mingw-w64-x86_64-emacs: /mingw64/share/applications/emacsclient.exe-mail.desktop exists in filesystem
mingw-w64-x86_64-emacs: /mingw64/share/applications/emacsclient.exe.desktop exists in filesystem
mingw-w64-x86_64-emacs: /mingw64/share/metainfo/emacs.metainfo.xml exists in filesystem
Errors occurred, no packages were upgraded.
```

What? What can the existence of these files possibly have to do with upgrading system files? Why would I expect them to not be there, if I'm doing an _upgrade_?

Environment:

> Device name	OPTI-9010-WIN10
Processor	Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz   3.40 GHz
Installed RAM	20.0 GB (19.9 GB usable)
System type	64-bit operating system, x64-based processor

> Edition	Windows 10 Pro
Version	21H2
Installed on	‎9/‎4/‎2021
OS build	19044.1645

Thanks.

mp

**Comment by Biswa96** [comment]
Please make sure if any antivirus or antimalware program (including Windows Defender) is deleting or prohibiting access to any file due to false positive issues.

**Comment by nyambol** [comment]
> Please make sure if any antivirus or antimalware program (including Windows Defender) is deleting or prohibiting access to any file due to false positive issues.

Hello,

Actually, I had this thought, it was my first thought when I saw the "can't compile an executable" message from configure. So,  I turned off Windows Defender completely.  I've had this problem in the past, having dropped AVG, Kaspersky, and BitDefender because of it. ☹️   I'm not particularly keen on WD, but 🤷  .

I just compiled a C# project on the Windows side, without issue. FWIW.

**Comment by Biswa96** [comment]
We are not suggesting to disable security products entirely. It may bring negative effects in certain situations. Just make sure msys2 is in exclusion list of that security product. Even it would be better to report the false positive issues to that security product vendor. There was an issue where gcc was reported as a malware https://github.com/msys2/MINGW-packages/issues/10295

> I just compiled a C# project on the Windows side, without issue

Hint: the C# toolchain is created and provided by a well-know corporation 😄

**Comment by nyambol** [comment]
> We are not suggesting to disable security products entirely. It may bring negative effects in certain situations. Just make sure msys2 is in exclusion list of that security product. Even it would be better to report the false positive issues to that security product vendor. There was an issue where gcc was reported as a malware #10295
> 
> > I just compiled a C# project on the Windows side, without issue
> 
> Hint: the C# toolchain is created and provided by a well-know corporation 😄

No, don't worry, I'm only a partial idiot. I just turned it off long enough to see that it didn't resolve the issue. The usual problem is configure compiling its tests for features, and idiot software telling me that it blocked the program from running because it's a threat.   True enough about C#, though.  I'll keep looking. Thanks.

**Comment by sridhar6994** [comment]
for general
    -Make target
        x86_64-w64-mingw32-gcc.exe: error: CreateProcess: No such file or directory 
kind of errors,  
please check that no duplicate include paths are present in common, diab & gcc
Also make sure that no invalud header file folder path is included

this resolved my errors

**Comment by David-Samir-Luis** [comment]
What is the solution for this problem guys i am trying to solve it since 2 hours

**Comment by Biswa96** [comment]
You have to exclude the msys2 installation directory in currently running antivirus programs. If that does not work try to reinstall the toolchain once more, because antivirus program may remove any msys2/mingw related files.
