### ISSUE TITLE
CMake package doesn't work with the default generator without installing ninja

### ISSUE THREAD

**Issue by ccawley2011** [msys2/MINGW-packages#11620]
The CMake package doesn't have a dependency on ninja, however when building without specifying a generator, it'll fail if ninja can't be found. Ideally, CMake should either:
- Specify ninja in the `depends` section of the PKGBUILD file.
- Fall back on the MSYS Makefiles generator when ninja isn't installed.

**Comment by lazka** [comment]
Depending on ninja sounds good
