### ISSUE TITLE
advancecomp ported as msys2 package request

### ISSUE THREAD

**Issue by Craw93L** [msys2/MINGW-packages#11649]
I need someone to port advanecomp to works as msys2 package
Some games are using advpng from it (its PNG Compression Utility)
I just started to use msys2 and I don't know how to do it
https://github.com/amadvance/advancecomp/releases/download/v2.3/advancecomp-2.3.tar.gz (source)
https://github.com/amadvance/advancecomp/releases/download/v2.3/advancecomp-2.3-windows-x64.zip (binary x64)
https://github.com/amadvance/advancecomp/releases/download/v2.3/advancecomp-2.3-windows-x86.zip (binary x86)

**Comment by lazka** [comment]
https://aur.archlinux.org/packages/advancecomp

**Comment by Biswa96** [comment]
Hi @Craw93L, I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2311920283. Please follow these steps:

1. Scroll down and download the correct artifact. It'll be a zip file.
2. Extract the package (.tar.zst) from zip file.
3. Install it with `pacman -U the-package-name.tar.zst` command.
