### ISSUE TITLE
Enable libjxl in ffmpeg and gimp

### ISSUE THREAD

**Issue by ccicnce113424** [msys2/MINGW-packages#11697]
https://github.com/libjxl/libjxl

**Comment by Biswa96** [comment]
libjxl package is already available as mingw package. See details here https://packages.msys2.org/base/mingw-w64-libjxl

**Comment by ccicnce113424** [comment]
libjxl is available in gimp and ffmpeg. Please enable libjxl in ffmpeg and gimp.

**Comment by Biswa96** [comment]
Are ffmpeg and gimp ready to enable libjxl in mingw packages? @Jehan @novomesk

**Comment by ccicnce113424** [comment]
In fact, libjxl contains a gimp extension that enables gimp to support the jpeg xl format. And ffmpeg recently added support for jpeg xl format.

**Comment by novomesk** [comment]
We use libjxl in GIMP 2.99.8 and newer.

MSYS2 have only GIMP 2.10.30, where JXL plug-in is not included.

There is another plug-in for GIMP 2.10 in libjxl package, but it needs that GIMP 2.10 is installed prior building the libjxl (and the plug-in). It means that libjxl would depend on old GIMP 2.10.x

However when we build 2.99.x for Windows we do not want to install old GIMP 2.10 as a would-be dependency of mingw-w64-x86_64-libjxl

**Comment by Jehan** [comment]
@Biswa96 @ccicnce113424 As a conclusion of what @novomesk says, unless you plan to package the development version of GIMP (where we use already the libjxl package for our official installer), this report is probably off-topic, because we simply don't have core support of JPEG-XL in the GIMP 2.10 series. So there is nothing to "enable" in your GIMP package.

Now what can be done is build the JPEG-XL third-party plug-in available in libjxl itself, allowing people to have JPEG-XL support in 2.10.x. Basically: in 2.10, the support exists as a third-party plug-in made by libjxl devs; whereas in 2.99/3.0, it (will) exist as a core plug-in by GIMP devs.

**Comment by ccicnce113424** [comment]
Therefore, you can provide gimp extension of libjxl instead of gimp supporting JPEG XL format, right?

**Comment by Jehan** [comment]
> Therefore, you can provide gimp extension of libjxl instead of gimp supporting JPEG XL format, right?

Yes for 2.10, that's probably the way to go. :-)

**Comment by Biswa96** [comment]
First need some opinion if the following patch is correct or not.

<details><summary>Click here to see the diff</summary>

```diff
diff --git a/lib/jxl.cmake b/lib/jxl.cmake
index 17096bd..4e8967a 100644
--- a/lib/jxl.cmake
+++ b/lib/jxl.cmake
@@ -526,7 +526,7 @@ endif()  # JPEGXL_ENABLE_TCMALLOC
 
 # Install the static library too, but as jxl.a file without the -static except
 # in Windows.
-if (NOT WIN32)
+if (NOT WIN32 OR MINGW)
   set_target_properties(jxl-static PROPERTIES OUTPUT_NAME "jxl")
   set_target_properties(jxl_dec-static PROPERTIES OUTPUT_NAME "jxl_dec")
 endif()
diff --git a/lib/jxl/libjxl.pc.in b/lib/jxl/libjxl.pc.in
index a2a6cb5..4a7af65 100644
--- a/lib/jxl/libjxl.pc.in
+++ b/lib/jxl/libjxl.pc.in
@@ -10,3 +10,4 @@ Requires.private: @JPEGXL_LIBRARY_REQUIRES@
 Libs: -L${libdir} -ljxl
 Libs.private: -lm
 Cflags: -I${includedir}
+Cflags.private: -DJXL_STATIC_DEFINE
diff --git a/lib/jxl_threads.cmake b/lib/jxl_threads.cmake
index 037a88d..dfa1fee 100644
--- a/lib/jxl_threads.cmake
+++ b/lib/jxl_threads.cmake
@@ -40,7 +40,7 @@ set_target_properties(${_target} PROPERTIES
 
 # Always install the library as jxl_threads.{a,so} file without the "-static"
 # suffix, except in Windows.
-if (NOT WIN32)
+if (NOT WIN32 OR MINGW)
   set_target_properties(${_target} PROPERTIES OUTPUT_NAME "jxl_threads")
 endif()
 install(TARGETS ${_target}
diff --git a/lib/threads/libjxl_threads.pc.in b/lib/threads/libjxl_threads.pc.in
index 4abd783..50b937a 100644
--- a/lib/threads/libjxl_threads.pc.in
+++ b/lib/threads/libjxl_threads.pc.in
@@ -10,3 +10,4 @@ Requires.private: @JPEGXL_THREADS_LIBRARY_REQUIRES@
 Libs: -L${libdir} -ljxl_threads
 Libs.private: -lm
 Cflags: -I${includedir}
+Cflags.private: -DJXL_THREADS_STATIC_DEFINE
```
</details>

The changes with cmake file install static libraries without `-static` prefix. And the pkgconfig files add Cflags.private for static linking.

**Comment by novomesk** [comment]
I think it is OK, I use JXL_STATIC_DEFINE JXL_THREADS_STATIC_DEFINE too in my static build using MSVC:
https://github.com/novomesk/qt-jpegxl-image-plugin/blob/73d24cd4dc472457b75f91b90c9aba52fd0b7edc/qt-jpegxl-image-plugin_appveyor.pro#L3

**Comment by thebombzen** [comment]
Do note that there's a longstanding bug in mingw-w64 relating to AVX2 code generation on Win64 - namely that it generates aligned instructions like `vmovaps` instead of the corresponding unaligned ones (like `vmovups`) even when there's no guarantee that the input is aligned to the required 32 bits (only 16). It might be necessary to compile highway with `-DHWY_COMPILE_ONLY_SCALAR` if building with MinGW. This should not be necessary when building with clang or MSVC.

**Comment by Biswa96** [comment]
> It might be necessary to compile highway with `-DHWY_COMPILE_ONLY_SCALAR` if building with MinGW. 

It is already done in libjxl [PKGBUILD](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libjxl/PKGBUILD) file. Should it be done in highway package? Then it may help to remove the conflict bewteen libjxl and highway package.

**Comment by kmilos** [comment]
Yep, I just created the highway w/ OOTB configuration as an anticipation of the libjxl dependency. As there are no other packages using it ATM, feel free to configure it as needed.

**Comment by novomesk** [comment]
libjxl 0.6.1 do not work with new highway, because legacy functions were removed.
libjxl from git works with new highway again.

**Comment by Biswa96** [comment]
I have tried to add `--enable-libjxl` option. But the configure command output shows this:

```
Unknown option "--enable-libjxl".
```

**Comment by Biswa96** [comment]
I have added a pull request to add the plugins. Would anyone like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2386574951. Please follow these steps:

1. Scroll down and download the correct artifact. It'll be a zip file.
2. Extract the package (.tar.zst) from zip file.
3. Install it with `pacman -U the-package-name.tar.zst` command.
