### ISSUE TITLE
OpenSSL 3.0

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#11702]
Any plan to upgrade OpenSSL to 3.0.
https://fedoraproject.org/wiki/Changes/OpenSSL3.0 (Fedora-36)
https://discourse.ubuntu.com/t/jammy-jellyfish-release-notes/24668 and https://discourse.ubuntu.com/t/openssl-3-0-transition-plans/24453 (Ubuntu 22.04)
https://archlinux.org/todo/openssl-30 (Arch Linux - TODO)

**Comment by lazka** [comment]
Affected packages:

```
mingw-w64-gst-plugins-bad
mingw-w64-cjose
mingw-w64-libpcap
mingw-w64-python2
mingw-w64-libwebsockets
mingw-w64-apr-util
mingw-w64-hexchat
mingw-w64-openssl
mingw-w64-wt
mingw-w64-python
mingw-w64-cyrus-sasl
mingw-w64-sqlcipher
mingw-w64-spice
mingw-w64-libssh2
mingw-w64-i2pd
mingw-w64-osslsigncode
mingw-w64-libsrtp
mingw-w64-opusfile
mingw-w64-winsparkle
mingw-w64-postgresql
mingw-w64-curl
mingw-w64-paho.mqtt.c
mingw-w64-libtorrent-rasterbar
mingw-w64-libgit2
mingw-w64-libmowgli
mingw-w64-ldns
mingw-w64-fossil
mingw-w64-freetds
mingw-w64-spice-gtk
mingw-w64-libshout
mingw-w64-python3.10
mingw-w64-libssh
mingw-w64-openldap
mingw-w64-grpc
mingw-w64-libevent
mingw-w64-glib-networking
mingw-w64-unbound
mingw-w64-civetweb
mingw-w64-arrow
mingw-w64-xmlsec
mingw-w64-poco
mingw-w64-freerdp
mingw-w64-python-pygit2
mingw-w64-aria2
mingw-w64-wget2
mingw-w64-libarchive
mingw-w64-hiredis
mingw-w64-tor
mingw-w64-gdcm
mingw-w64-rabbitmq-c
mingw-w64-wget
mingw-w64-podofo
mingw-w64-restbed
mingw-w64-mosquitto
mingw-w64-capnproto
mingw-w64-libimobiledevice
mingw-w64-transmission
mingw-w64-live-media
mingw-w64-qca-qt5
mingw-w64-librdkafka
mingw-w64-neon
mingw-w64-srt
mingw-w64-htslib
mingw-w64-idevicerestore
mingw-w64-python-pycurl
mingw-w64-qbittorrent
mingw-w64-libgda
mingw-w64-python-cryptography
mingw-w64-pdal
```

**Comment by mati865** [comment]
DLLs are versioned so they can coexist. Other things will be harder.

**Comment by lazka** [comment]
Arch recently did something similar with ffmpeg, where it namespaced everything and old packages have to set a "PKG_CONFIG_PATH": https://archlinux.org/packages/extra/x86_64/ffmpeg4.4/

**Comment by lazka** [comment]
We can try in msys first, everything there should work in theory: https://github.com/msys2/MSYS2-packages/issues/3013

**Comment by MehdiChinoune** [comment]
All the packages mentioned above rebuild with OpenSSL 3.0, so there is no need for openssl-1.1

**Comment by Biswa96** [comment]
I think openssl-1.1 should be added. It may not require in our dependencies but others may use it.

**Comment by SlySven** [comment]
The project I code for still uses Qt 5.15 and that uses OpenSSL 1.x (Qt doesn't switch to OpenSSL until 6.4 or .5) so is there a way to still get a 1.x library/development package?

**Comment by MehdiChinoune** [comment]
> The project I code for still uses Qt 5.15 and that uses OpenSSL 1.1 (Qt doesn't switch to OpenSSL until 6.4 or .5) so is there a way to still get a 1.1 library/development package?

Qt6 supports OpenSSL 3.0 since 6.2.0 https://www.qt.io/blog/moving-to-openssl-3-in-binary-builds-starting-from-qt-6.5-beta-2, they just started packaging their official binaries against OpenSSL 3.0 with Qt6 6.5.0, They backported it at some point to Qt5.
Our Qt5 was built against OpenSSL 3.x, there shouldn't be any issue.

**Comment by SlySven** [comment]
🤦‍♂️ 
That is a problem then - I use `gitk` and `git-gui` for managing the work on the project I code for. However they haven't (AFAICT) completed upgrading from OpenSSL 1.1 to 3 - and since I use SSH to talk to my GitHub repository I cannot push commits to it since the packages they provide want the `msys-crypto-1_1.dll` (not `msys-crypto-3.dll`) and fall over when they can't find it...
😢
