### ISSUE TITLE
Error when reading image file with GraphicsMagick in Octave

### ISSUE THREAD

**Issue by mmuetzel** [msys2/MINGW-packages#11709]
Octave's test suite on Windows using MSYS2 MINGW32 and MINGW64 is crashing while reading an image with GraphicsMagick since recently. The error message in the logs is:
https://github.com/gnu-octave/octave/runs/6545228528?check_suite_focus=true#step:13:435
```
D:/a/octave/octave/.build/src/.libs/octave.exe: Arg list too long
make[4]: *** [Makefile:2844: check-local] Error 127
  image\imread.m .................................................make[4]: Leaving directory '/d/a/octave/octave/.build/test'
make[3]: *** [Makefile:2696: check-am] Error 2
```

That test was completing successfully before that. The last successful run started on May 21 at 9:05 CEST. The first failing run started on May 22 19:40 CEST. The change in Octave that triggered the first failing run was a documentation change (in an unrelated function fwiw). So, it is pretty unlikely that something in Octave's codebase has caused the error.

Between these dates, GCC was updated to 12.1 afaict.
The error message is pretty confusing ("Arg list too long" at a point where Octave has already started and executed several tests successfully). 
Could it be that graphicsmagick (or some other dependency) needs rebuilding after the GCC update?

**Comment by mmuetzel** [comment]
This crash also happens with the version of Octave that is distributed by MSYS2.

Easier steps to reproduce locally:
Install and run Octave
```
pacman -S mingw-w64-x86_64-octave
octave
```
At the Octave prompt execute the following:
```
test imread
```

Re-building graphicsmagick doesn't help.

**Comment by mmuetzel** [comment]
With a non-stripped debug version of GraphicsMagick, the top of the backtrace is the following here:
```
[Thread 16176.0x475c exited with code 0]
warning: Critical error detected c0000374

Thread 22 received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 16176.0x3c74]
0x00007ffdfe26c6b3 in ntdll!RtlIsZeroMemory () from C:\Windows\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffdfe26c6b3 in ntdll!RtlIsZeroMemory () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00007ffdfe275512 in ntdll!.misaligned_access () from C:\Windows\SYSTEM32\ntdll.dll
#2  0x00007ffdfe2757fa in ntdll!.misaligned_access () from C:\Windows\SYSTEM32\ntdll.dll
#3  0x00007ffdfe27fce5 in ntdll!.misaligned_access () from C:\Windows\SYSTEM32\ntdll.dll
#4  0x00007ffdfe188715 in ntdll!RtlGetCurrentServiceSessionId () from C:\Windows\SYSTEM32\ntdll.dll
#5  0x00007ffdfe1879e1 in ntdll!RtlFreeHeap () from C:\Windows\SYSTEM32\ntdll.dll
#6  0x00007ffdfdc2c6ac in msvcrt!free () from C:\Windows\System32\msvcrt.dll
#7  0x00007ffd94c69420 in PixelIterateMonoRead (call_back=call_back@entry=0x7ffd94be3053 <GetImageChannelDepthPixels>, options=options@entry=0x0,
    description=description@entry=0x7ffd94cb3764 <__func__.18+820> "[%s] Get channel depth...", mutable_data=mutable_data@entry=0x7b155f643c,
    immutable_data=immutable_data@entry=0x7b155f6468, x=x@entry=0, y=y@entry=0, columns=3, rows=3, image=image@entry=0x25286054180,
    exception=exception@entry=0x7b155f6480) at ../GraphicsMagick-1.3.38/magick/pixel_iterator.c:210
#8  0x00007ffd94be3929 in GetImageChannelDepth (image=0x25286054180, channel=<optimized out>, exception=0x7b155f6480)
    at ../GraphicsMagick-1.3.38/magick/channel.c:604
#9  0x00007ffdb665c476 in Magick::Image::channelDepth (this=0x2528606c350, channel_=MagickLib::RedChannel)
    at ../GraphicsMagick-1.3.38/Magick++/lib/Image.cpp:564
#10 0x00007ffd9953ef91 in ?? () from C:\msys64\mingw64\bin\liboctinterp-10.dll
#11 0x00007ffd99544d15 in ?? () from C:\msys64\mingw64\bin\liboctinterp-10.dll
#12 0x00007ffd993e3794 in ?? () from C:\msys64\mingw64\bin\liboctinterp-10.dll
```

I don't know if this is helpful...

**Comment by lazka** [comment]
likely related to https://github.com/msys2/MINGW-packages/issues/11729

**Comment by mmuetzel** [comment]
No longer segfaults after updating to mingw-w64-x86_64-gcc-12.1.0-2. 🎉
