### ISSUE TITLE
Ninja 1.11.0 does not seem to output progress status until compilation is over

### ISSUE THREAD

**Issue by shithappens2016** [msys2/MINGW-packages#11711]

**Comment by lazka** [comment]
I can't reproduce

**Comment by Biswa96** [comment]
AFAIK, ninja does not show the progress if the standard I/O handles are console handles. i.e. when pseudo console is enabled or when msys2 is launched from command prompt.

**Comment by shithappens2016** [comment]
Maybe that's why it happens
![无标题](https://user-images.githubusercontent.com/13523412/169954541-3b1b0246-207b-447a-9a56-268c8942a438.jpg)

**Comment by Biswa96** [comment]
But I am used to this type of behaviour with ninja since the before 1.11.0.

**Comment by shithappens2016** [comment]
@Biswa96

I did not find such a problem with the previous version.
maybe they don't remember why they disable stdout buffering on Windows in the first place.

**Comment by pal1000** [comment]
The problem seams to be with Ninja running inside Mintty Terminal. If you invoke MSYS2 with `<path-to-MSYS2-install>\usr\bin\bash -l <script>` or `<path-to-MSYS2-install>\usr\bin\bash -lc <command(s)>`, you should be fine.

**Comment by shithappens2016** [comment]
ninja-build/ninja#2143

**Comment by Biswa96** [comment]
> [ninja-build/ninja#2143](https://github.com/ninja-build/ninja/pull/2143)

And here comes the performance impact 😰

**Comment by orgads** [comment]
@Biswa96 did you experience a performance impact? I only ran my performance test on Linux. Should have done it also in msys.

How bad is it?

**Comment by Biswa96** [comment]
I have neither notice any performance impact in my system nor seen the output glitch that you had mentioned in the upstream issue. My machine is too old to measure any performance difference. But isn't it know fact that flushing the buffer in I/O should be done when required?

**Comment by orgads** [comment]
This was discussed in my PR, and it should be negligible wrt the actual build. I measured (on Linux) with dry-run, and even then the impact was nearly 0.

**Comment by orgads** [comment]
I ran the same test now on msys2, and the impact is ~6% for dry-run (prints only). Printing ~1900 files takes on average 0.98s without flush, and 1.04s with flush. Full build of this project on my machines takes at least 20m, so the practical difference on real compilation scenario is ~0.005%.
