### ISSUE TITLE
cmake couldn't generate "MSYS Makfiles" or "MinGW Makfiles" project on CLANG64

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#11710]
Reported upstream https://gitlab.kitware.com/cmake/cmake/-/issues/23542

related issue: #10800

**Comment by stahta01** [comment]
Which cmake is being used?
`/usr/bin/cmake`
or
`/clang64/bin/cmake`

Tim S.

**Comment by mati865** [comment]
The only think we can do is making `clang` depend on https://packages.msys2.org/package/mingw-w64-clang-x86_64-gcc

**Comment by MehdiChinoune** [comment]
> The only think we can do is making `clang` depend on https://packages.msys2.org/package/mingw-w64-clang-x86_64-gcc

I think we have discussed that before, We have changed that so users don't get confused about CMake reporting that gcc/g++ are used instead of clang/clang++
It's the assumption made by CMake that MINGW=="GCC on Windows" that should be fixed.

**Comment by revelator** [comment]
> > The only think we can do is making `clang` depend on https://packages.msys2.org/package/mingw-w64-clang-x86_64-gcc
> 
> I think we have discussed that before, We have changed that so users don't get confused about CMake reporting that gcc/g++ are used instead of clang/clang++ It's the assumption made by CMake that MINGW=="GCC on Windows" that should be fixed.

aye that makes sense :)

**Comment by MehdiChinoune** [comment]
I have opened a MR in https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7297.
Need someone with a good English to convince them.

**Comment by Biswa96** [comment]
The maintainer suggested that

> CC=clang CXX=clang++ env vars, or -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ command-line options, is the official way

If we differ with official documentation we can have our own patch file. There are also too many assumptions. e.g.

```cpp
  locations.push_back("/mingw/bin");
  locations.push_back("c:/mingw/bin");
```
