### ISSUE TITLE
Conditional OpenMP directive fails w/ GCC 12

### ISSUE THREAD

**Issue by kmilos** [msys2/MINGW-packages#11729]
See https://github.com/msys2/MINGW-packages/issues/11730 for my minimal reproducer and https://github.com/darktable-org/darktable/issues/11889

This was previously ok w/ GCC 11.3 and is ok on Linux GCC 12.1

**Comment by mati865** [comment]
Please report it to GCC upstream.

**Comment by ntamas** [comment]
We have the same issue with [igraph](https://github.com/igraph/igraph) in MinGW with gcc 12.1. Our minimal repro is as follows:

```c
#include <stdio.h>

int main(int argc, char* argv[]) {
    #pragma omp for schedule(dynamic)
    for (int i = 0; i < 100; i++) {}
    printf("OK\n");
    return 0;
}
```

Works fine in gcc 12.1 Docker image and also works fine with GCC 11.3 in MinGW but fails with GCC 12.1 in MinGW.

@kmilos if you report it upstream, please cross-link the issue here so I can follow it.

**Comment by MehdiChinoune** [comment]
The equivalent Fortran program to the first example crashes:
```Fortran
program main
  implicit none
  integer :: i
  !$omp parallel do if(.false.)
  do i = 1, 10
  end do
  print*, "OK"
end program
```
but the equivalent to the second one doesn't
```Fortran
program main
  implicit none
  integer :: i
  !$omp parallel do schedule (dynamic)
  do i = 1, 100
  end do
  print*, "OK"
end program
```

**Comment by lazka** [comment]
I added a regression test: https://github.com/msys2/msys2-tests/pull/1

@kmilos I can also report it upstream if you want

**Comment by kmilos** [comment]
Yes, please!

**Comment by lazka** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105745

Replacing "libgomp-1.dll" with the one from GCC 11.3 also makes things work again.

**Comment by lazka** [comment]
Fix is in the repo now

**Comment by kmilos** [comment]
Confirming the darktable CI is back to green, thanks again.

**Comment by ntamas** [comment]
igraph is also back to green, thanks!
