### ISSUE TITLE
gcc/ld can't deal with full path in library -l/mingw64/lib/libgomp.a

### ISSUE THREAD

**Issue by Jolyk** [msys2/MINGW-packages#11727]
```
$ gcc 1.c -l/mingw64/lib/libgomp.a
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/msys64/mingw64/lib/libgomp.a: Invalid argument
collect2.exe: error: ld returned 1 exit status

$ ls -l /mingw64/lib/libgomp.a  #check the file existence
-rw-r--r-- 1 rig rig 382K May 21 12:38 /mingw64/lib/libgomp.a

```
May be semicolon acts as some special symbol. It converts path to absolute (why?), then tries to combine with other paths, like this (notice "C:" in the middle):
`attempt to open c:\msys64\mingw64\bin\../../mingw64/usr/lib\C:/msys64/mingw64/lib/libgomp.a.a failed`

"-l:" can't help.

I can fix it by isolating path to -L and truncating ".a" at the end. But code above is generated by cmake, and I can't change it.

I'm under Windows 8.1

**Comment by mmuetzel** [comment]
IIUC, `-l` doesn't take a file path as an argument. The command should probably either be `gcc 1.c -lgomp` (maybe including a `-L` argument for the path) or `gcc 1.c /mingw64/lib/libgomp.a`. But even more likely, something like `gcc 1.c -fopenmp` would be more correct.

**Comment by Jolyk** [comment]
Yes, main problem here is path in -l param and not related to mingw. I wonder how it generated like that. Also I didn't ask to convert path to DOS.
I solved the problem with adding parameter to cmake -G "MinGW Makefiles". Now it generates like "-lgomp" and built is ok.
