### ISSUE TITLE
Requesting mingw-w64-x86_64-python-keystone package

### ISSUE THREAD

**Issue by MarioPossamato** [msys2/MINGW-packages#11742]
The mingw-w64-capstone base package has mingw-w64-x86_64-python-capstone, but mingw-w64-keystone does not have an equivalent.

**Comment by lazka** [comment]
thanks.

https://archlinux.org/packages/community/x86_64/python-keystone/

**Comment by Biswa96** [comment]
Hi @MarioPossamato, I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2407059368. Please follow these steps:

1. Scroll down and download the correct artifact. It'll be a zip file.
2. Extract the package (.tar.zst) from zip file.
3. Install it with `pacman -U the-package-name.tar.zst` command.

**Comment by MarioPossamato** [comment]
It works perfectly! :)  Thank you!
