### ISSUE TITLE
Requesting perl bindings for GTK2/3/4.

### ISSUE THREAD

**Issue by ghost** [msys2/MINGW-packages#11740]
It's a massive PITA to setup perl stuff on windows compared to linux. Could you please ship the perl bindings to GTK along with any other necessary modules like glib/cairo/pango/anything else needed?

**Comment by Biswa96** [comment]
Is it possible to test those packages? Do you have any projects which uses those or depends on?

**Comment by Biswa96** [comment]
We have not received any response regarding this issue.
