### ISSUE TITLE
libvlc not rendering video.

### ISSUE THREAD

**Issue by tswain555** [msys2/MINGW-packages#11769]
I am seriously scratching my head with libvlc.  I have the example code it links and runs; have audio; no video.
I have a video of the issue. https://www.youtube.com/watch?v=rQOshUfYe6c
Code is here...
http://[multiversesocial.com/VLCChannel.c](http://multiversesocial.com/VLCChannel.c)
Any advice appreciated; everything qualifies in the code.  NO callbacks being called.

**Comment by Biswa96** [comment]
How did you compile it? I see this error.

```
VLCChannel.c:13:10: fatal error: vlc/vlc_config.h: No such file or directory
   13 | #include <vlc/vlc_config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by Biswa96** [comment]
@tswain555 any reply on thia topic?

**Comment by Biswa96** [comment]
No further comment from author. Feel free to re-open the issue.

**Comment by tswain555** [comment]
Make sure that file is in your include PATH

**Comment by Biswa96** [comment]
What file? Please explain the issue properly and provide all the steps to reproduce the issue.
