### ISSUE TITLE
Broken ffmpeg after upgrading gnutls to 3.7.6

### ISSUE THREAD

**Issue by lmorand** [msys2/MINGW-packages#11776]
After upgrading mingw-w64-x86_64-gnutls to 3.7.6-1, ffmpeg (mingw-w64-x86_64-ffmpeg 4.4.2-4) started crashing with no output at all and running it through gdb showed a segmentation fault. Everything seems back to normal after downgrading to 3.7.5-1.

It looks like the problem is related to libavformat, because before downgrading I replaced avformat-58.dll with the one from [gyan.dev](https://www.gyan.dev/ffmpeg/builds/) and the segmentation fault went away.

**Comment by Biswa96** [comment]
There is a new gnutls 3.7.6-2 package. Please update all the packages with `pacman -Syyu` command.

**Comment by lazka** [comment]
See #11743, 3.7.6-1 was broken, please update.

**Comment by lmorand** [comment]
Ok, that fixed it. I had already updated, but my pacman was fetching the package from git-for-windows's repository, which doesn't include that fix. Thank you and sorry for the unnecessary noise.
