### ISSUE TITLE
Imagemagick: `-list format` doesn't output anything

### ISSUE THREAD

**Issue by webbedspace** [msys2/MINGW-packages#11777]
Here's the output when I run `magick -version`:
```
% magick -version
Version: ImageMagick 7.1.0-35 Q16-HDRI x86_64 20062 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5)
Delegates (built-in): bzlib cairo djvu fftw flif fontconfig freetype gslib gvc heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf xml zlib
Compiler: gcc (12.1)
```
Here's the output when I run `magick -list format`
```
% magick -list format

%
```
Most other `-list` commands work correctly (haven't checked all of them)

**Comment by Biswa96** [comment]
Want to try the suggestion here https://github.com/ImageMagick/ImageMagick/discussions/5219 ?

**Comment by kmilos** [comment]
[Moving the config file as described here](https://github.com/msys2/MINGW-packages/issues/3444) does solve the `magick -list configure` problem, but not the format/coders access...

> Want to try ...

Unfortunately can't find the time to go down that rabbit hole now.

**Comment by Biswa96** [comment]
> but not the format/coders access...

Can you provide any hint about that issue? Like any error output and what will be the expected result.

**Comment by Biswa96** [comment]
The search path of configure.xml file is missing a slash.
