### ISSUE TITLE
I can't find 'yelp' (the help viewer)

### ISSUE THREAD

**Issue by ThosRTanner** [msys2/MINGW-packages#11788]
I've installed gtk2, gtk3 and yelp-tools. But I can't find yelp anywhere and I'd like to check some changes I've done to some help files.

Or does yelp require an entire gnome desktop environment to run, which might make it a bit tricky on windows...

**Comment by mmuetzel** [comment]
I don't know anything about yelp. But looking at the names of the binaries that, e.g., `[mingw-w64-x86_64-yelp-tools](https://packages.msys2.org/package/mingw-w64-x86_64-yelp-tools?repo=mingw64)` installs, would `yelp-check` work for you?

**Comment by lazka** [comment]
yelp depends on webkit2gtk and that doesn't support windows, so there is now way.
