### ISSUE TITLE
Package python-soundfile doesn't work

### ISSUE THREAD

**Issue by thesword53** [msys2/MINGW-packages#11780]
Package: `mingw-w64-x86_64-python-soundfile`
```
Python 3.9.13 (main, May 19 2022, 07:22:26)  [GCC 11.3.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import soundfile
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.9/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.9/site-packages/soundfile.py", line 162, in <module>
    _snd = _ffi.dlopen(_os.path.join(
OSError: cannot load library 'C:/msys64/mingw64/lib/python3.9/site-packages/_soundfile_data/libsndfile64bit.dll': error 0x7e
```

**Comment by Biswa96** [comment]
Hi @thesword53, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2440524384. Please follow these steps:

1. Scroll down and download the correct artifact. It'll be a zip file.
2. Extract the package (.tar.zst) from zip file.
3. Install it with `pacman -U the-package-name.tar.zst` command.

**Comment by thesword53** [comment]
I installed and tested `mingw-w64-x86_64-python-soundfile 0.10.3.post1-3` and now it's working.
