### ISSUE TITLE
WinGW64 on Windows 10 does not print anything with printf();

### ISSUE THREAD

**Issue by danielwangksu** [msys2/MINGW-packages#11784]
Hi all,
 
Not sure if this is the right repo for this question. I have a couple C program compiled using `GCC 11`, `CMake`, and `mingw32-make`, the program can build without issues, but when I execute it in the MSYS2 MinGW x64 terminal nothing was output to the console. 

The same binary can print out thing as expected on cmd though. I have the latest MSYS and MinGW64 installed. It only impact C, C++ with `std::cout` works perfectly fine. My system is Win10 Enterprise 20H2 19042.631.

Here is the basic structure of my program I will try to create a minimal sample for this issue, but a simple program without external library does not capture this issue. The CMakeList.txt is pretty straightforward: 

```
if (WIN32)
add_executable()
target_link_libraries()
endif()
```

I build with `cmake .. -G "MinGW Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++`, `mingw-make`/

`which gcc` shows the path at `/mingw64/bin/gcc`

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-11.3.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev1, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Rev1, Built by MSYS2 project)
```

I'm not sure if this is related to linker. The reason I'm using `mingw-make` is because one of the external C library, `tpm2-tss` that links to my program is built using Virtual Studio 2022, clang-cl, legacy MSVC, I'm also linking an prebuilt older openssl library that I downloaded. 

I also want to mention that calling `free()` on an object created by the external library, `tpm2-tss`  cause the program to crash. However, calling a wrapper function of free() from `tpm2-tss` library works perfectly fine. I'm not sure if this is related to my setup. I though using `mingw-make` in this case would match the `tpm2-tss` library better.

Thank you for your help!

Edit: Sorry for the confusion, I edited this question hope it is more clear.

**Comment by Biswa96** [comment]
Author did not provide any information to reproduce the issue and gone forever. Please re-open the issue if the issue is reproducible.
