### ISSUE TITLE
winnetwk can not binding 

### ISSUE THREAD

**Issue by v-h-giang** [msys2/MINGW-packages#11800]
I got this error when bind Wnetaddconnection2w in gfortran . Compile was ok with other header file  : FindFirstFileW,
FindNextFileW, MultiByteToWideChar, WideCharToMultiByte, GetLastError, FileTimeToSystemTime  ( in fileapi.h )

undefined reference to `WNetAddConnection2W' 
collect2.exe: error: ld returned 1 exit status

i think this is a bug ?  or not . Binding  interface : 

      TYPE,bind(c)      :: NETRESOURCEW
            INTEGER(DWORD)                                    :: dwScope;
            INTEGER(DWORD)                                    :: dwType;
            INTEGER(DWORD)                                    :: dwDisplayType;
            INTEGER(DWORD)                                    :: dwUsage;
            INTEGER(WCHAR),DIMENSION(1000)                    :: lpLocalName;
            INTEGER(WCHAR),DIMENSION(1000)                    :: lpRemoteName;
            INTEGER(WCHAR),DIMENSION(1000)                    :: lpComment;
            INTEGER(WCHAR),DIMENSION(1000)                    :: lpProvider;
      END TYPE 
     INTERFACE
      FUNCTION WNetAddConnection2W(lpNetResource,lpPassword,lpUserName,dwFlags) &
            bind(c,name='WNetAddConnection2W')
            import :: NETRESOURCEW, WCHAR, DWORD
            implicit none
            !GCC$ ATTRIBUTES STDCALL                 :: WNetAddConnection2W
            INTEGER(DWORD)                           :: WNetAddConnection2W
            type(NETRESOURCEW)                       :: lpNetResource
            INTEGER(WCHAR), DIMENSION(*),optional    :: lpPassword
            INTEGER(WCHAR), DIMENSION(*),optional    :: lpUserName
            INTEGER(DWORD), VALUE                    :: dwFlags
      END FUNCTION WNetAddConnection2W
      END INTERFACE

**Comment by Biswa96** [comment]
How did you fix this issue?

**Comment by v-h-giang** [comment]
Because the linker can not find library "Mpr" (libmpr.a for fortran language )  when compile,  then i add option "-lMpr" when compile with gfortran
The "requirements" for this function is written in documents of microsoft :
https://docs.microsoft.com/en-us/windows/win32/api/winnetwk/nf-winnetwk-wnetaddconnection2w

Just confusing why do not need add link option "-lKernel32"  when complie with function FindFirstFileW or others
