### ISSUE TITLE
`vkEnumeratePhysicalDevices` fails with mingw-w64-x86_64-vulkan-loader-1.3.211-1

### ISSUE THREAD

**Issue by Zapeth** [msys2/MINGW-packages#11830]
After upgrading `mingw-w64-x86_64-vulkan-loader`  from version 1.2.179-2 to 1.3.211-1 my vulkan application fails when calling `vkEnumeratePhysicalDevices`, returning `VK_ERROR_INITIALIZATION_FAILED` error.

Additionally the following message appears in stdout:
`[VK] Loader Message (0): setup_loader_term_phys_devs:  Failed to detect any valid GPUs in the current config`

The GPU in the system is an NVIDIA GeForce GTX 670, which should support Vulkan up to version 1.2 (but I wouldn't expect the version jump of the loader to 1.3 to be a problem?)

Downgrading to version 1.2.179-2 fixes the issue.

**edit:** Just tried with other recent versions that are available, they all work (including 1.3.207-1)

**Comment by Biswa96** [comment]
Does this issue occurs with latest vulkan packages? Please try to update packages with `pacman -Syyu` command.

**Comment by Zapeth** [comment]
Thanks for the response, just tried with version 1.3.228-1 and it seems to work again (loader library name changed from libvulkan-1.dll to vulkan-1.dll though, so I had to update those portions in my code too), so I'll close this.
