### ISSUE TITLE
msys2 python with no admin

### ISSUE THREAD

**Issue by bunzel** [msys2/MINGW-packages#11841]
Hello everyone,

I'm running msys2 on a windows machine without admin privilege. Everything works fine until I try to install python packages via pip.
In particular I would like to install packages in venv.

steps to reproduce:
1. Follow msys2 installation instructions.
2. pacman -S mingw-w64-x86_64-python
3. Setting user path accordingly
4. check python version. which python /mingw64/bin/python
5. cd into random dir at home and create venv --> python -m venv .env
6. activate venv and install package e.g. numpy --> pip install numpy or python -m pip install numpy

This generally fails with building wheel. 
Any ideas how to fix that? 

Full output is:

Collecting numpy
  Using cached numpy-1.22.4.zip (11.5 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml): started
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): finished with status 'error'
Failed to build numpy

 note: This error originates from a subprocess, and is likely not a problem with pip.                                    ERROR: Failed building wheel for numpy                                                                                ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

**Comment by lazka** [comment]
Since we don't support binary wheels from pypi all packages need to be built from source. This only works for simple packages. IN case of numpy we have to patch various things to get it to build: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-python-numpy
