### ISSUE TITLE
[libheif] issue when used with dav1d 1.0.0

### ISSUE THREAD

**Issue by novomesk** [msys2/MINGW-packages#11869]
Hello,

This is related to problem in GIMP unable to open AVIF images now:
https://gitlab.gnome.org/GNOME/gimp/-/issues/8280

The is issue is incompatibility between released libheif 1.12 and latest dav1d 1.0.0

The fix is in libheif's commit:
https://github.com/strukturag/libheif/commit/0f8496f22d284e1a69df12fe0b72f375aed31315

Can you please include the patch?

Or alternatively, it would be possible to temporarily build libheif without dav1d. AVIF decoding would probably work via libaom.

**Comment by Biswa96** [comment]
Hi @novomesk, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2519443408

**Comment by novomesk** [comment]
Thanks, I will test next week and in case there is some problem, I'll tell you.
