### ISSUE TITLE
[libtiff] Static link failure with libdeflate v1.12

### ISSUE THREAD

**Issue by matthiakl** [msys2/MINGW-packages#11876]
After libdeflate has been updated from 1.10 to 1.12 static linking of libtiff fails with this error:
```
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../lib\libtiff.a(tif_lerc.o):(.text+0x1d1): undefined reference to `libdeflate_free_decompressor@4'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../lib\libtiff.a(tif_lerc.o):(.text+0x1e3): undefined reference to `libdeflate_free_compressor@4'
... (more of the kind)
```

**Comment by lazka** [comment]
hm, libtiff builds fine here under mingw32

**Comment by matthiakl** [comment]
`mingw-w64-x86_64` still builds without problems, but `mingw-w64-i686` does not (on Github runner `windows-2022`).

**Comment by Biswa96** [comment]
Can you provide the build command or the repository link which has the error?

**Comment by matthiakl** [comment]
Building with cmake, so I cannot provide the relevant command, but here are the logs:
Last successful build (libdeflate 1.10): https://github.com/widelands/widelands/runs/6947553227?check_suite_focus=true
Failing build (libdeflate 1.12): https://github.com/widelands/widelands/runs/6952865063?check_suite_focus=true
x64 still working: https://github.com/widelands/widelands/runs/6952865019?check_suite_focus=true

**Comment by lazka** [comment]
hm, seems like libdeflate had a ABI break for the static library (see https://github.com/ebiggers/libdeflate/blob/master/NEWS.md#version-111 re stdcall). I'll trigger some rebuilds.

**Comment by lazka** [comment]
Please try again now

**Comment by matthiakl** [comment]
The build is successful again. Thanks.
