### ISSUE TITLE
Would it be possible to create autoconf archive packages for mingw64/clang64/ucrt64 please?

### ISSUE THREAD

**Issue by ThosRTanner** [msys2/MINGW-packages#11883]
As per title.

**Comment by Biswa96** [comment]
[autoconf-archive][1] is a single package that can be used in any MSYSTEM [environment][2]. It does not have any mingw or clang specific code.

[1]: https://packages.msys2.org/base/autoconf-archive
[2]: https://www.msys2.org/docs/environments/
