### ISSUE TITLE
asan and ubsan appear to be missing for clang under mingw64 environment

### ISSUE THREAD

**Issue by ThosRTanner** [msys2/MINGW-packages#11899]
Using clang under mingw64 with -fsanitize=address -fsanitize=undefined compiles but won't link, giving:

```
C:/Apps/msys64/mingw64/bin/ld: cannot find C:/Apps/msys64/mingw64/lib/clang/13.0.1/lib/windows/libclang_rt.asan_dynamic-x86_64.dll.a: No such file or directory
C:/Apps/msys64/mingw64/bin/ld: cannot find C:/Apps/msys64/mingw64/lib/clang/13.0.1/lib/windows/libclang_rt.asan_dynamic_runtime_thunk-x86_64.a: No such file or directory
C:/Apps/msys64/mingw64/bin/ld: cannot find C:/Apps/msys64/mingw64/lib/clang/13.0.1/lib/windows/libclang_rt.asan_dynamic_runtime_thunk-x86_64.a: No such file or directory
```

I have installed the mingw64 compiler-rt and clang packages

**Comment by 1480c1** [comment]
```bash
pacman -Fy libclang_rt.asan_dynamic_runtime_thunk-x86_64.a
:: Synchronizing package databases...
 staging                                      87.0 KiB   110 KiB/s 00:01 [#######################################] 100%
 mingw32                                       5.0 MiB  1357 KiB/s 00:04 [#######################################] 100%
 mingw64                                       5.0 MiB  3.07 MiB/s 00:02 [#######################################] 100%
 ucrt64                                        5.0 MiB  3.04 MiB/s 00:02 [#######################################] 100%
 clang64                                       4.8 MiB  1316 KiB/s 00:04 [#######################################] 100%
 msys                                       1076.0 KiB  1385 KiB/s 00:01 [#######################################] 100%
clang64/mingw-w64-clang-x86_64-compiler-rt 14.0.4-3 (mingw-w64-clang-x86_64-toolchain) [installed]
    clang64/lib/clang/14.0.4/lib/windows/libclang_rt.asan_dynamic_runtime_thunk-x86_64.a
```

seems only clang64's compiler-rt provides the files

**Comment by oscarfv** [comment]
@ThosRTanner : as far as I know Clang' s ASAN/UBSAN are not missing from mingw64 by mistake, but because those features are not supported there.

If this answers your question, please close this issue. Thanks.

**Comment by MehdiChinoune** [comment]
see https://www.msys2.org/docs/environments/#gcc-vs-llvmclang

**Comment by GitMensch** [comment]
Can we have a nice target error? Compare 

~~~
me@Computer MINGW64 ~
$ clang t.c -fsanitize=address -fsanitize=undefined
D:/dev/msys2/mingw64/bin/ld: cannot find D:/dev/msys2/mingw64/lib/clang/18/lib/windows/libclang_rt.asan_dynamic-x86_64.dll.a: No such file or directory
D:/dev/msys2/mingw64/bin/ld: cannot find D:/dev/msys2/mingw64/lib/clang/18/lib/windows/libclang_rt.asan_dynamic-x86_64.dll.a: No such file or directory
D:/dev/msys2/mingw64/bin/ld: cannot find D:/dev/msys2/mingw64/lib/clang/18/lib/windows/libclang_rt.asan_dynamic_runtime_thunk-x86_64.a: No such file or directory
D:/dev/msys2/mingw64/bin/ld: cannot find D:/dev/msys2/mingw64/lib/clang/18/lib/windows/libclang_rt.asan_dynamic_runtime_thunk-x86_64.a: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
~~~
with
~~~
me@Computer UCRT64 ~
$ clang t.c -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer
clang: error: unsupported option '-fsanitize=address' for target 'x86_64-pc-windows-msys'
~~~

**Comment by ovidiugabriel** [comment]
This link https://www.msys2.org/docs/environments/#gcc-vs-llvmclang
states **"Clang provides ASAN support"** 

but I still have the same problem as @GitMensch 

The site provides false information?

**Comment by oscarfv** [comment]
@ovidiugabriel : Clang in **LLVM/Clang based environments** provides ASAN support, that's correct. CLANG64 is a clang based environment.

In GCC based environments, it doesn't. MINGW64 is a GCC-based environment, despite it also providing clang.

**Comment by ovidiugabriel** [comment]
@oscarfv I see, so you say that MSYS CLANG64 accounts for GCC environment?

```
$ echo $MSYSTEM
CLANG64

```

I see that with my installation the following files are missing
```
clang_rt.asan_*
```

**Comment by ovidiugabriel** [comment]
@oscarfv I am using the **CLANG64** environment and I checked the `$MSYSTEM` variable also.
I am not building with the **MINGW64** environment.

It looks like `clang_rt.asan_*` files are missing from the **C:\msys64\mingw64\lib\clang\19\lib\windows** folder

The **pacman** is not delivering the following files:

- clang_rt.asan-preinit-x86_64.lib
- clang_rt.asan-x86_64.lib
- clang_rt.asan_cxx-x86_64.lib
- clang_rt.asan_dll_thunk-x86_64.lib
- clang_rt.asan_dynamic-x86_64.dll
- clang_rt.asan_dynamic-x86_64.lib
- clang_rt.asan_dynamic_runtime_thunk-x86_64.lib
- clang_rt.asan_static-x86_64.lib

**Comment by rimrul** [comment]
> I am not building with the MINGW64 environment.

> C:\msys64\mingw64\…

That's the wrong folder then

**Comment by ovidiugabriel** [comment]
@rimrul 

If I installed the clang tools from the CLANG64 environment why libclang_rt files are in stored in C:\msys64\mingw64\lib\clang\19\lib\windows and not under C:\msys64\clang64\lib ?

I don't know how clang files got under C:\msys64\mingw64 ...
