### ISSUE TITLE
cmake returns different values for CMAKE_SYSTEM_VERSION on CLANG64 and UCRT64

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#11891]
```CMake
cmake_minimum_required(VERSION 3.16)
project(test CXX)
message( STATUS "CMAKE_HOST_SYSTEM: ${CMAKE_HOST_SYSTEM}")
message( STATUS "CMAKE_HOST_SYSTEM_NAME: ${CMAKE_HOST_SYSTEM_NAME}")
message( STATUS "CMAKE_HOST_SYSTEM_VERSION: ${CMAKE_HOST_SYSTEM_VERSION}")
message( STATUS "CMAKE_SYSTEM: ${CMAKE_SYSTEM}")
message( STATUS "CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
message( STATUS "CMAKE_SYSTEM_VERSION: ${CMAKE_SYSTEM_VERSION}")
```
on UCRT64:
```
$ cmake -Bbuild
-- Building for: Ninja
-- The CXX compiler identification is GNU 12.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Programs/msys64/ucrt64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_HOST_SYSTEM: Windows-10.0.19044
-- CMAKE_HOST_SYSTEM_NAME: Windows
-- CMAKE_HOST_SYSTEM_VERSION: 10.0.19044
-- CMAKE_SYSTEM: Windows-10.0.19044
-- CMAKE_SYSTEM_NAME: Windows
-- CMAKE_SYSTEM_VERSION: 10.0.19044
-- Configuring done
-- Generating done
-- Build files have been written to: D:/dev/Bugs/cmake_code/build
```
on CLANG64
```
$ cmake -Bbuild
-- Building for: Ninja
-- The CXX compiler identification is Clang 14.0.4
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Programs/msys64/clang64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_HOST_SYSTEM: Windows-6.2.9200
-- CMAKE_HOST_SYSTEM_NAME: Windows
-- CMAKE_HOST_SYSTEM_VERSION: 6.2.9200
-- CMAKE_SYSTEM: Windows-6.2.9200
-- CMAKE_SYSTEM_NAME: Windows
-- CMAKE_SYSTEM_VERSION: 6.2.9200
-- Configuring done
-- Generating done
-- Build files have been written to: D:/dev/Bugs/cmake_code/build
```
UCRT64 returns the same value as MSVC
```
$ cmake -Bbuild
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
-- The CXX compiler identification is MSVC 19.32.31328.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_HOST_SYSTEM: Windows-10.0.19044
-- CMAKE_HOST_SYSTEM_NAME: Windows
-- CMAKE_HOST_SYSTEM_VERSION: 10.0.19044
-- CMAKE_SYSTEM: Windows-10.0.19044
-- CMAKE_SYSTEM_NAME: Windows
-- CMAKE_SYSTEM_VERSION: 10.0.19044
-- Configuring done
-- Generating done
-- Build files have been written to: D:/dev/Bugs/cmake_code/build
```

**Comment by MehdiChinoune** [comment]
C++ reproducer:
```CXX
#include <windows.h>
#include <iostream>
#include <sstream>

int main() {
    OSVERSIONINFOEXW osvi;
    ZeroMemory(&osvi, sizeof(osvi));
    osvi.dwOSVersionInfoSize = sizeof(osvi);
    GetVersionExW((OSVERSIONINFOW*)&osvi);
    std::ostringstream windowsVersionString;
    windowsVersionString << osvi.dwMajorVersion << "."
                         << osvi.dwMinorVersion << "."
                         << osvi.dwBuildNumber;
    std::cout << "Windows version: " << windowsVersionString.str() << std::endl;
}
```

**Comment by mati865** [comment]
According to MSDN Clang is right:
> With the release of Windows 8.1, the behavior of the GetVersionEx API has changed in the value it will return for the operating system version. The value returned by the GetVersionEx function now depends on how the application is manifested.
>
> Applications not manifested for Windows 8.1 or Windows 10 will return the Windows 8 OS version value (6.2). ...

https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexw

I guess GCC doesn't set some flag or sets it to too low value which triggers some kind of Windows compatibility mode.

**Comment by Biswa96** [comment]
ucrt64 one adds a manifest file with the executable which looks like in this https://packages.msys2.org/base/mingw-w64-windows-default-manifest package. That API has some weird relation with manifest file being present or not, according to the docs.

**Comment by MehdiChinoune** [comment]
> ucrt64 one adds a manifest file with the executable

which executable are you talking about? cmake, gcc or every executable built by gcc on UCRT64?

**Comment by Biswa96** [comment]
> which executable are you talking about? 

I have checked both the C++ code and cmake tests. In both cases, the executable compiled in ucrt64 has a manifest file. For the cmake example, the executable file is in `bin/CMakeFiles/3.23.2/CompilerIdCXX/a.exe`.

**Comment by MehdiChinoune** [comment]
> BTW, this issue is not related to whether the manifest file contains Windows Vista in supported ID list in the manifest file. The API is related to if the manifest file present or absent.

No one talked about Vista!

**Comment by equeim** [comment]
This is still an issue. cmake.exe from mingw-w64-clang-x86_64-cmake does not contain the manifest in resources which causes CMake to report wrong Windows version. This is an issue with cmake package specifically. The manifest should be added during CMake's build process. My guess that something wrong goes here: https://gitlab.kitware.com/cmake/cmake/-/blob/master/Source/CMakeLists.txt. See ManifestLib target
