### ISSUE TITLE
`cmocka` static linking

### ISSUE THREAD

**Issue by msink** [msys2/MINGW-packages#11912]
```
$ ls /mingw64/lib | grep cmocka
libcmocka-static.a
libcmocka.dll.a

$ pkg-config --static --libs cmocka
-lcmocka
```

here should be either 
- `libcmocka.a` installed instead of `libcmocka-static.a`, or
- `-lcmocka-static` in `pkg-config` output

**Comment by Biswa96** [comment]
Hi @msink, Thank you for reporting the issue. I have added a pull request to fix it. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2542797703

**Comment by msink** [comment]
Thanks, now in simple scenarions it works, but I failed to force `meson` to use static version:
https://github.com/libui-ng/libui-ng/pull/116#issuecomment-1164071725

**Comment by Biswa96** [comment]
For the record, I have sent the _non-controversial_ part of the patch in upstream MR here https://gitlab.com/cmocka/cmocka/-/merge_requests/48
