### ISSUE TITLE
Bug in FindGLEW module

### ISSUE THREAD

**Issue by chrismile** [msys2/MINGW-packages#11932]
## Describe the issue

When using the GLEW CMake package, the following error is triggered:
```
CMake Error at D:/a/_temp/msys64/mingw64/share/cmake/Modules/FindGLEW.cmake:84 (select_library_configurations):
  Unknown CMake command "select_library_configurations".
```

I would guess this problem can probably be attributed to the recent commit [1a060cdaa2059734d7cf91038b5bf6d71ef6aace](https://github.com/msys2/MINGW-packages/commit/1a060cdaa2059734d7cf91038b5bf6d71ef6aace) by @mmuetzel, as this commit adds a `select_library_configurations` call.

## Steps to Reproduce the Problem

1. Install mingw-w64-cmake and mingw-w64-x86_64-glew.
2. Use `find_package(GLEW REQUIRED)` in the CMakeLists.txt file of a project.
3. Get the following output when running `cmake` for the project:
```
CMake Error at D:/a/_temp/msys64/mingw64/share/cmake/Modules/FindGLEW.cmake:84 (select_library_configurations):
  Unknown CMake command "select_library_configurations".
```

## Additional Context: Operating System, Screenshots

- OS: Windows 10 (tested both on a "real" Windows 10 PC and a GitHub Actions server)

**Comment by lazka** [comment]
@mmuetzel is this missing `include(SelectLibraryConfigurations)` ?

**Comment by mmuetzel** [comment]
> @mmuetzel is this missing `include(SelectLibraryConfigurations)` ?

Looks like that is the issue.

See #11938 for a possible fix.

@chrismile: Could you please check with the build artifacts of that PR (if it builds successfully)?

**Comment by chrismile** [comment]
> @chrismile: Could you please check with the build artifacts of that PR (if it builds successfully)?

Thanks for the quick fix! I installed the built package from the build artifacts of the PR, and it looks like your changes solve the problem. Feel free to close this issue when it is merged.
