### ISSUE TITLE
`libcurl` static linking - missed libs in `pkg-config` output

### ISSUE THREAD

**Issue by msink** [msys2/MINGW-packages#11953]
Really tried only `libcurl-winssl` variant.
```
$ pacman -S mingw-w64-x86_64-curl-winssl
$ pkg-config --static --libs-only-l libcurl
-lcurl -lidn2 -lssh2 -lssh2 -lpsl -ladvapi32 -lcrypt32 -lwldap32 -lzstd -lzstd -lbrotlidec -lbrotlidec -lz -lws2_32
```
When building minimal application with libcurl - linker fails until more libs added:
```
   -lbcrypt
   -lbrotlicommon
   -lunistring
   -liconv
```

Added:
`pkgconf --static --cflags` output is broken too - it should contain 
```
 -DCURL_STATICLIB
```

**Comment by lazka** [comment]
Yeah, upstream doesn't support static linking via pkgconf. We patch it in the msys package.. Could be copied over probably.

**Comment by revelator** [comment]
the problem is that for linking statically you need the full library name + path to the static library not just -llibname and if both static and shared versions exist it will allways default to linking to the shared version. cmake does support it i think so something similar could possibly be done for pkgconfig.

**Comment by msink** [comment]
With `--static` option `-lfoo` means `/mingw64/lib/libfoo.a`, without - `/mingw64/lib/libfoo.dll.a`
Of cource I use `--static` when linking statically.

My test project (in Kotlin/Native): https://github.com/msink/hello-curl

**Comment by revelator** [comment]
i meant in regards to pkgconfig lazka is right actually, and there are probably more packages with this problem.

**Comment by revelator** [comment]
indeed though would be nice if we could avoid some of these steps but that depends a lot on the source maintainers willingness to make it so ;)

**Comment by msink** [comment]
Btw, why
```
$ pkg-config --static --libs-only-l libbrotlidec
-lbrotlidec -lbrotlicommon
```
here it contains `-lbrotlicommon`, but in libcurls `pkgconf` it missed?

**Comment by mmuetzel** [comment]
Looking at the .pc file of libcurl, these flags appear in the `Libs.private` section. It might be better to add `libbrotlidec` to a `Requires.private` instead. IIUC, that would automatically pull in all flags from the dependency tree of the `libbrotlidec.pc` file automatically...

**Comment by mmuetzel** [comment]
I opened PR #11971 that adds a patch that is partly based on the one @lazka pointed out.
It additionally adds `-lbcrypt` to the static linker flags and `-DCURL_STATICLIB` to the static CFLAGS.

Could you please check with the build artifacts from that PR if those changes fixes it for you? (That is if it builds correctly...)

**Comment by msink** [comment]
Fixed, thanks:
```
$ pkg-config --static --libs-only-l libcurl
-lcurl -lidn2 -lssh2 -lssh2 -lpsl -ladvapi32 -lcrypt32 -lbcrypt -lwldap32 -lzstd -lzstd -lbrotlidec -lz -lws2_32 -lidn2 -liconv -lunistring -lbrotlidec -lbrotlicommon

$ pkg-config --static --cflags libcurl
-IF:/msys64/mingw32/include -DCURL_STATICLIB
```
