### ISSUE TITLE
`mingw-w64-x86_64-gdb 12.1-2` seems broken

### ISSUE THREAD

**Issue by zufuliu** [msys2/MINGW-packages#11951]
Can't find entry point `DllMain` on `mingw64\bin\libncursesw6.dll`.

**Comment by oscarfv** [comment]
It starts fine here.

It is difficult to answer your report because it has no context.

Does gdb start correctly when executed from the MSYS64-MinGW console?

Please provide information about how to reproduce the problem. If you already fixed it, please close this issue. Thanks.

**Comment by zufuliu** [comment]
![gdb-libncursesw6](https://user-images.githubusercontent.com/2289926/183430867-007dd77c-b305-4c5a-a55a-cd890da50b50.png)

**Comment by zufuliu** [comment]
Closed as invalid, caused somewhat outdated `libintl-8.dll`.
