### ISSUE TITLE
Cannot launch meld

### ISSUE THREAD

**Issue by lb90** [msys2/MINGW-packages#11966]
If I try to launch meld from the MinGW 64bit shell, it fails with the error message `Meld requires pycairo 1.15 or higher.` I don't quite know why, as pycairo is at version 1.21.0

$ pacman -Q mingw-w64-x86_64-python-cairo
mingw-w64-x86_64-python-cairo 1.21.0-2

**Comment by lb90** [comment]
Strange, it works even for me on UCRT x86_64! I may have accidentally screwed up my mingw64\bin directory during development, don't know. Can you also test on MSVCRT x86_64 to confirm that it's not a real issue?

**Comment by lb90** [comment]
Scratch that, it was my fault! Very sorry for the noise :|

**Comment by Biswa96** [comment]
May I ask what was the fault? Just curious. Maybe there is some hidden issue or dependency 🤔

**Comment by lb90** [comment]
Yeah. I copied a custom-built Cairo DLL into `mingw64\bin`. Not sure, but maybe the version checks in meld don't work with the unstable version numbers of cairo?
