### ISSUE TITLE
Could MSYS2 support to customize MINGW architect?

### ISSUE THREAD

**Issue by taozuhong** [msys2/MINGW-packages#11978]
Now MSYS2 support five architects:
`'mingw32' 'mingw64' 'ucrt64' 'clang64' 'clang32'`

but I do want to use one of them, so could I choose MINGW architect like `mingw64` only?

**Comment by Biswa96** [comment]
Yes, it's possible since the beginning. You just only download the mingw64 packages.

**Comment by MehdiChinoune** [comment]
> Now MSYS2 support five architects: `'mingw32' 'mingw64' 'ucrt64' 'clang64' 'clang32'`

Actually they are six (+`clangarm64`)
I would call them environments or variants instead of architects

https://www.msys2.org/docs/environments/#overview

**Comment by taozuhong** [comment]
Sorry, I mean that user can set the primary architect, then `pacman` command will use it as a filter to query packages.

**Comment by taozuhong** [comment]
> > Now MSYS2 support five architects: `'mingw32' 'mingw64' 'ucrt64' 'clang64' 'clang32'`
> 
> Actually they are six (+`clangarm64`) I would call them environments or variants instead of architects
> 
> https://www.msys2.org/docs/environments/#overview

I think more architects will coming soon.

**Comment by Biswa96** [comment]
The [package prefixes](https://www.msys2.org/docs/package-naming/) act as a filter to query packages. For example, mingw64 packages are prefixed with mingw-w64-x86_64-

**Comment by taozuhong** [comment]
> You can edit `./etc/pacman.conf` and comment out all the repos but ` mingw64` (and ` msys`).

Maybe it's the solution to solve this problem.
