### ISSUE TITLE
Please fix the waf package so, it works with mingw python instead of requiring msys2/cygwin python!

### ISSUE THREAD

**Issue by stahta01** [msys2/MINGW-packages#11989]
The recent waf package is broken because it looks for MSVC on CI server unless it thinks it is not running under Win32 as result of an waf script ran under msys2/cygwin python.

The "check-c-compiler=gcc" fails to work because it checks for MSVC on CI server and errors out.

Tim S.

**Comment by MehdiChinoune** [comment]
waf works with mingw python. It is wxPython that default to MSVC and not searching for anything else.
mpv built successfully:
UCRT64:
```
...
  Checking for 'msvc' (C compiler)         : not found 
  Checking for 'gcc' (C compiler)          : D:/M/msys64/ucrt64/bin/cc.exe 
  Detected target OS:                      : os-win32 
...
```
CLANG64
```
...
  Checking for 'msvc' (C compiler)         : not found 
  Checking for 'gcc' (C compiler)          : not found 
  Checking for 'clang' (C compiler)        : D:/M/msys64/clang64/bin/cc.exe 
  Detected target OS:                      : os-win32 
...
```

**Comment by stahta01** [comment]
> waf works with mingw python. It is wxPython that default to MSVC and not searching for anything else. mpv built successfully: UCRT64:
> 
> ```
> ...
>   Checking for 'msvc' (C compiler)         : not found 
>   Checking for 'gcc' (C compiler)          : D:/M/msys64/ucrt64/bin/cc.exe 
>   Detected target OS:                      : os-win32 
> ...
> ```
> 
> CLANG64
> 
> ```
> ...
>   Checking for 'msvc' (C compiler)         : not found 
>   Checking for 'gcc' (C compiler)          : not found 
>   Checking for 'clang' (C compiler)        : D:/M/msys64/clang64/bin/cc.exe 
>   Detected target OS:                      : os-win32 
> ...
> ```

How did you get that output from the CI Server?
Because it fails on the CI server for me when used; it does work on my local PC.

Tim S.

**Comment by MehdiChinoune** [comment]
> > waf works with mingw python. It is wxPython that default to MSVC and not searching for anything else. mpv built successfully: UCRT64:
> > 
> > ```
> > ...
> >   Checking for 'msvc' (C compiler)         : not found 
> >   Checking for 'gcc' (C compiler)          : D:/M/msys64/ucrt64/bin/cc.exe 
> >   Detected target OS:                      : os-win32 
> > ...
> > ```
> > 
> > CLANG64
> > 
> > ```
> > ...
> >   Checking for 'msvc' (C compiler)         : not found 
> >   Checking for 'gcc' (C compiler)          : not found 
> >   Checking for 'clang' (C compiler)        : D:/M/msys64/clang64/bin/cc.exe 
> >   Detected target OS:                      : os-win32 
> > ...
> > ```
> 
> How did you get that output from the CI Server?
> Because it fails on the CI server for me when used; it does work on my local PC.
> 
> Tim S.

https://github.com/msys2/MINGW-packages/actions/runs/2605697611

**Comment by stahta01** [comment]
Okay, I wonder why wxPython has the issue.

Is it a waflib version issue. Possible; but, not likely true.

Tim S.
