### ISSUE TITLE
MSVC support using waf, needed or not?

### ISSUE THREAD

**Issue by stahta01** [msys2/MINGW-packages#11988]
I just wanted to know if MSVC support is needed in "mingw-w64-waf"?

Likely the code here cause the issue I had with MSVC detection failing on CI Server when using MinGW python.

From waflib/Tools/compiler_c.py
```
c_compiler = {
'win32':  ['msvc', 'gcc', 'clang'],
```
I am guessing removing 'msvc' would be a possible fix to avoid checking for msvc or maybe even just moving it to the end of the three entries.

See also #11982

Tim S.

**Comment by MehdiChinoune** [comment]
I didn't see this issue when building mpv with waf. It's wxPython that supports only msvc on Windows

https://github.com/wxWidgets/Phoenix/blob/master/buildtools/build_wxwidgets.py#L180
https://github.com/wxWidgets/Phoenix/blob/master/wscript#L37
https://github.com/wxWidgets/Phoenix/blob/master/wscript#L72

As I said before you should report this issue to the upstream.

**Comment by stahta01** [comment]
Anyway to add you to ignore since your feedback is most often useless since it does not answer the question!

So, do you want me to report it to the MSys2 team, the WAF team, or the github team?

Tim S.

**Comment by stahta01** [comment]
And, FYI wxPython is the only package that does not have an local copy of waflib!!!
So, you tests are comparing apples to oranges.

Tim S.

**Comment by stahta01** [comment]
Please the waf package so, it works with mingw python instead of requiring msys2/cygwin python!

**Comment by stahta01** [comment]
@MehdiChinoune
Per, my post else where I suggested you report it to the WAF team since you, MehdiChinoune, act like an expert on it.
All I know is that you told me to fix my working wxPython PR to not use /usr/bin/python and I then wasted more than 20 hours to get it working once more! And, you keep saying report the problem upstream that was reported over 2 years ago. And, you ignore my fix in the PR tp wxPython.

Tim S.

**Comment by MehdiChinoune** [comment]
> you ignore my fix in the PR to wxPython.

How?
If you mean I haven't merge your PR, I think I told you before that don't have any access to this repo.

**Comment by stahta01** [comment]
> > you ignore my fix in the PR to wxPython.
> 
> How? If you mean I haven't merge your PR, I think I told you before that don't have any access to this repo.

NO ! My PR to wxPython.org git repo.

Tim S.

**Comment by MehdiChinoune** [comment]
> > > you ignore my fix in the PR to wxPython.
> > 
> > 
> > How? If you mean I haven't merge your PR, I think I told you before that don't have any access to this repo.
> 
> NO ! My PR to wxPython.org git repo.
> 
> Tim S.

Sorry, I didn't see it.

**Comment by stahta01** [comment]
So, you are ignorant of wxPython; please STOP saying report it upstream or I will find a way to ask for you to be limited in what you can do. Because as I have stated if you read my PR to this repo that reporting a problem without a fix is useless to wxPython.org! And, since the problem was already reported 2 years ago and is still open all I did was link my PR to wxPython.org/wxWidgets git repo to the old issue.

Tim S.

> 

So, you are ignorant of wxPython; please STOP saying report it upstream or I will find a way to ask for you to be limited in what you can do. Because as I have stated if you read my PR to this repo that reporting a problem without a fix is useless to wxPython.org! And, since the problem was already reported 2 years ago and is still open all I did was link my PR to wxPython.org/wxWidgets git repo to the old issue.

Tim S.

**Comment by stahta01** [comment]
> > > > you ignore my fix in the PR to wxPython.
> > > 
> > > 
> > > How? If you mean I haven't merge your PR, I think I told you before that don't have any access to this repo.
> > 
> > 
> > NO ! My PR to wxPython.org git repo.
> > Tim S.
> 
> Sorry, I didn't see it.

So, you are ignorant of wxPython; please STOP saying report it upstream or I will find a way to ask for you to be limited in what you can do. Because as I have stated if you read my PR to this repo that reporting a problem without a fix is useless to wxPython.org! And, since the problem was already reported 2 years ago and is still open all I did was link my PR to wxPython.org/wxWidgets git repo to the old issue.

Tim S.

**Comment by MehdiChinoune** [comment]
> I will find a way to ask for you to be limited in what you can do.

Well, there is a way. just go to my profile and block me. I will not be able to comment to any of your issues or PRs.
