### ISSUE TITLE
[Suggest] Move pthread imp lib to indivial package

### ISSUE THREAD

**Issue by eebssk1** [msys2/MINGW-packages#12014]
It seems gcc 12 from msys2 lost the ability to link winpthread statically if dep comes from c++ even with tricks.
Pls see https://stackoverflow.com/questions/13768515/how-to-do-static-linking-of-libwinpthread-1-dll-in-mingw/72903594#72903594
The way I'm doing is renaming the libwinpthread.dll.a to force gcc use static version of it.This is the only way I found working normally.

There's no win32 thread version of the toolchain so we also can not use alternative library on github to provide the support.
It's maybe better to remove the imp lib from default installion since the pthread is small and most people do static link unless there's extra condition. Those who really want to dynamically link pthread can install the package to restore it.

**Comment by MehdiChinoune** [comment]
see: https://stackoverflow.com/a/14031444

**Comment by eebssk1** [comment]
> see: https://stackoverflow.com/a/14031444

Well if you check you'll find my answer in that thread..
The whole point here is making winpthread to static linked without using(-static) that will make all deps to statically linked.
Using such flag is not really good if just for winpthreads, also many software that only supports dynamic link to some components  to work will be confused if add (-static).

if you mean the (-Bstatic,xxx,-Bdynamic) thing...Nope,it doesn't work,gcc still links to the imp lib instead of the real static one.
The only solution for now is fully delete or rename the libwinpthread.dll.a and another same one with different name.

**Comment by eebssk1** [comment]
FYI:I tried to explicit specific the real static winpthread lib on the gcc command line. however it still links to the imp lib, ignoring the user request.

**Comment by MehdiChinoune** [comment]
We rely on dynamic linking when packaging, and giving That hundreds of packages that depends on `libwinpthreads`. Renaming will break the entire MSYS2 packaging.
Deleting the importing lib or renaming it is not possible.

If you encounter any difficulty about static linking `libwinpthreads`, Please show a minimal reproducible example.
