### ISSUE TITLE
Question: can you provide an instruction how to use this on Linux (for cross-compile to Win)

### ISSUE THREAD

**Issue by rilian-la-te** [msys2/MINGW-packages#12027]
I tried it, and it does not work outside Arch-based distros, and even in Arch-based, it is difficult to setup development environment which points to msys2 sysroot.

**Comment by eebssk1** [comment]
Why not just use the mingw toolchain provided by your distro?
I suppose this project is only oriented to run mingw toolchain natively and provide nearly compelete build environment directly on windows.

**Comment by rilian-la-te** [comment]
@eebssk1 because I want to install devel packages from msys2 and toolchain from distro. And I do not know how to do it. I want to use msys2 as MXE replacement mostly

**Comment by 1480c1** [comment]
https://github.com/msys2/MINGW-packages/issues/11913 this would probably be close to what you are asking about

**Comment by rilian-la-te** [comment]
@1480c1 this in not the same. They want all toolchain, I want only development libraries. I will try it myself again.

**Comment by 1480c1** [comment]
You can get only development libraries as well through the same path as getting the toolchain? Not sure if I understand what distinction you are trying to make

**Comment by rilian-la-te** [comment]
@eebssk1 because I want to install devel packages from msys2 and toolchain from distro. And I do not know how to do it. I want to use msys2 as MXE replacement mostly. Like I use Debian sysroot, If I want to cross-compile from Arch to Debian.

**Comment by Freed-Wu** [comment]
> even in Arch-based, it is difficult to setup development environment which points to msys2 sysroot.

I install msys2 in archlinux <https://aur.archlinux.org/packages/msys2-keyring> <https://aur.archlinux.org/packages/pacman-mirrors>. But when I try to use msys2's mingw to compile a program but get null output. Is it related to this point?

**Comment by Biswa96** [comment]
> Is it related to this point?

Probably not. It depends on how much level of integration you want. For example, cygwin/msys2 layer do not work flawlessly. But mingw packages may work with wine. To compile Windows binary, you can try the mingw-w64-gcc package in ArchLinux with mingw packages from here. Theoretically it should work 🤞

**Comment by Freed-Wu** [comment]
>  It depends on how much level of integration you want. For example, cygwin/msys2 layer do not work flawlessly.

Thanks. I have tried `/mingw64/bin/gcc.exe` which return null output:

```c
$ cat main.c
int main(int argc, char *argv[])
{
	return 0;
}
$ /mingw64/bin/gcc.exe main.c
$ echo $?
1
```

> But mingw packages may work with wine

I have tested `/mingw64/bin/python.exe`, `/mingw64/bin/x264.exe` can work. More programs need to test.


```
$ /mingw64/bin/x264.exe --preset ultrafast /mnt/yuv/352x288.yuv -o b.mp4
yuv [info]: 352x288p 0:0 @ 25/1 fps (cfr)
x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x264 [info]: profile Constrained Baseline, level 1.3, 4:2:0, 8-bit
x264 [info]: frame I:1     Avg QP:20.00  size: 36485
x264 [info]: frame P:9     Avg QP:24.78  size:  5018
x264 [info]: mb I  I16..4: 100.0%  0.0%  0.0%
x264 [info]: mb P  I16..4:  0.3%  0.0%  0.0%  P16..4: 47.5%  0.0%  0.0%  0.0%  0.0%    skip:52.2%
x264 [info]: coded y,uvDC,uvAC intra: 97.8% 96.6% 88.5% inter: 28.5% 18.2% 6.7%
x264 [info]: i16 v,h,dc,p: 29% 32% 25% 14%
x264 [info]: i8c dc,h,v,p: 30% 33% 30%  8%
x264 [info]: kb/s:1632.94

encoded 10 frames, 1428.57 fps, 1645.48 kb/s
$ /mingw64/bin/python.exe
Python 3.10.9 (main, Dec 10 2022, 09:13:58)  [GCC 12.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

> To compile Windows binary, you can try the mingw-w64-gcc package in ArchLinux with mingw packages from here. Theoretically it should work

I see. It looks like msys2 also can provide software ecosystem for wine. :+1:

I just try it out of curiosity :smile:

**Comment by Freed-Wu** [comment]
Is it also means I can install Arch Linux's package (include AUR) in msys2, right? If so, it sounds amazing!

**Comment by Biswa96** [comment]
> Is it also means I can install Arch Linux's package (include AUR) in windows msys2, right?

Those will not work. Because there is no counterpart of wine in Windows. You can use WSL1 or WSL2 but that does not need msys2 or mingw related programs.

**Comment by Freed-Wu** [comment]
I know, but some package is not linux elf program. such as font, text scripts, translation of manpage, backgrounds of desktop environment. I can install them in windows msy2 without repackage them. right?

**Comment by Freed-Wu** [comment]
According to <https://www.msys2.org>

> the main focus of MSYS2 is to provide a build environment for native Windows software and the Cygwin-using parts are kept at a minimum.

> such as font, text scripts, translation of manpage

These resources will not be accepted by msys2. That's why I think it can be amazing :smile:

**Comment by Freed-Wu** [comment]
> I have tried /mingw64/bin/gcc.exe which return null output:

I found the reason. Add `/mingw/bin` to wine's PATH can fix.
