### ISSUE TITLE
Using pip3.exe inside activated virtual environment crashes

### ISSUE THREAD

**Issue by legends2k** [msys2/MINGW-packages#12035]
On my MinGW64 environment, I've the following Python packages installed

``` bash
$ pacman -Qs python | grep '^local' | sed -e 's;local/;;g'

mingw-w64-x86_64-python 3.10.5-2
mingw-w64-x86_64-python-distlib 0.3.4-1
mingw-w64-x86_64-python-filelock 3.6.0-2
mingw-w64-x86_64-python-pip 22.0.4-2
mingw-w64-x86_64-python-platformdirs 2.5.1-2
mingw-w64-x86_64-python-setuptools 63.1.0-1
mingw-w64-x86_64-python-six 1.16.0-3
mingw-w64-x86_64-python-virtualenv 20.14.0-2
```

Running `pip3` works fine:

``` bash
$ pip3 list

Package            Version
------------------ ----------
asciidoc           10.2.0
certifi            2022.6.15
charset-normalizer 2.1.0
distlib            0.3.4
filelock           3.7.1
idna               3.3
pip                22.0.4
platformdirs       2.5.2
requests           2.28.1
requests-file      1.5.1
setuptools         63.1.0
six                1.16.0
urllib3            1.26.10
virtualenv         20.14.0
```

I'm able to create a Python virtual environment thus

``` bash
$ virtualenv -p python3 hello

created virtual environment CPython3.10.5.final.0-64 in 659ms
  creator CPython3Windows(dest=E:/hello, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:/Users/testuser/AppData/Local/pypa/virtualenv)
    added seed packages: pip==22.1.2, setuptools==62.4.0, wheel==0.37.1
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

$ cd test_venv && source bin/activate

(hello)
$ pip3 list

E:/hello/bin/pip.exe: error while loading shared libraries: MSVCR120.dll: cannot open shared object file: No such file or directory
```

I've [all MSVC x64 runtime libraries][msvcdll] installed.

[msvcdll]: https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by legends2k** [comment]
Just for completeness, I can do `python -m pip list`, etc. inside the activated environment.  However, running `pip` directly from the activated environment's `bin` doesn't work.

**Comment by Biswa96** [comment]
> E:/hello/bin/pip.exe: error while loading shared libraries: MSVCR120.dll

Are the python and pip executable coming from mingw packages? mingw packages does not link with that dll.

**Comment by legends2k** [comment]
> > E:/hello/bin/pip.exe: error while loading shared libraries: MSVCR120.dll
> 
> Are the python and pip executable coming from mingw packages? mingw packages does not link with that dll.

Python is definitely coming from MinGW package.  I verified by hashing:

``` bash
$ xxhsum -H64 $(which python pip3)

558f6e48f157851d  /mingw64/bin/python
20a02351c000d82e  /mingw64/bin/pip3
```

While from within the environment

``` bash
(hello)
$ xxhsum -H64 $(which python pip3)

558f6e48f157851d  /e/hello/bin/python
f6cc68f84fc51f29  /e/hello/bin/pip3
```

Notice that `python`'s hashes tally while `pip3`'s doesn't.

**Comment by mati865** [comment]
> > E:/hello/bin/pip.exe: error while loading shared libraries: MSVCR120.dll
> 
> Are the python and pip executable coming from mingw packages? mingw packages does not link with that dll.

At least one package does: https://github.com/msys2/MINGW-packages/blob/ca2b50deb22f285b2cadc6cf1ceb6b7fac7c78ca/mingw-w64-python-distlib/PKGBUILD#L47

**Comment by naveen521kk** [comment]
Shouldn't `MSVCR120.dll` be installed by default, or am I missing something?

> Not sure where pip3 is coming from. Any other way to find it?

I think it's because some script is appended to the end of the executable. Also, `pip.exe` (in the mingw64 folder) is from setuptools launchers which don't link to that DLL, but the one virtual venv creates is from the `distlib` package and it links to that DLL.

**Comment by lazka** [comment]
We can likely do something similar as https://github.com/msys2/MINGW-packages/commit/5cd6e5619c4f308714b5065f5674e748fe023919

**Comment by lazka** [comment]
Please try again now

**Comment by lazka** [comment]
I assume this is fixed now then.

**Comment by legends2k** [comment]
> I assume this is fixed now then.

This is fixed now, thanks!  Sorry, your comment fell through the net; missed it earlier.
