### ISSUE TITLE
Qt 5 package update

### ISSUE THREAD

**Issue by mcallegari** [msys2/MINGW-packages#12044]
Hello!
First off many thanks for the hard work you're carrying on the Qt packages. 
I've been a MSYS2 contributor myself in the past and I know the degree of complexity of the matter.

I'd like to request an update of the qt5 package to the latest version (5.15.5):
https://download.qt.io/official_releases/qt/5.15/5.15.5/

The current version 5.15.3 has build issues with GCC 12.x so perhaps they patched Qt in the meantime.
Thanks in advance!

**Comment by DioEgizio** [comment]
wanted to add qt6 is outdated too (6.3.1 is latest, msys2 has qt 6.3.0) so perhaps that should be updated too 🙂
