### ISSUE TITLE
Build gcc

### ISSUE THREAD

**Issue by Efreets** [msys2/MINGW-packages#12049]
I'd like to build gcc-11.3 step by step in the mingw-w64 enviroment, but I still not know how it works,
so yours can help me to build gcc by steps, more details wanted, especial the command with comment better.
Thanks.

**Comment by mmuetzel** [comment]
I can't give detailed step-by-step instruction. But maybe the build rules when GCC was still at 11.3 could be helpful:
https://github.com/msys2/MINGW-packages/blob/fc660082fabe2181cae188cb10a99566d8301768/mingw-w64-gcc/PKGBUILD
