### ISSUE TITLE
mingw-w64-x86_64-alure 'al.h' file not found

### ISSUE THREAD

**Issue by 3N4N** [msys2/MINGW-packages#12056]
In `msys64/mingw64/include/AL/alure.h`:

```c
#ifdef _WIN32
#include <al.h> // this file isn't found
#include <alc.h> // this file isn't found
// ... some elseif for other oses
#endif
```

The `al.h` and `alc.h` files are in `AL` folder, not in the `include` folder. But [in the upstream](https://github.com/kcat/alure/tree/master/include) I see that these files are supposed to be in the parent `include` folder.

I think the building of this package is incorrect.

**Comment by Biswa96** [comment]
The al.h and alc.h files come from openal package.
```

**Comment by Biswa96** [comment]
The al.h and alc.h files come from openal package.

```
$ pacman -F /mingw64/include/AL/alc.h /mingw64/include/AL/al.h
mingw64/include/AL/alc.h is owned by mingw64/mingw-w64-x86_64-openal 1.22.0-1
mingw64/include/AL/al.h is owned by mingw64/mingw-w64-x86_64-openal 1.22.0-1
```

alure should install openal as its dependency. Either include the openal directory with your project or use pkgconfig file to get correct include directory as following.

```
$ pkgconf -cflags alure
-IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/AL
```

**Comment by 3N4N** [comment]
I don't understand what you're saying. Did you read my issue? I said `AL/alure.h` is including `al.h` and `alc.h` instead of `AL/al.h` and `AL/alc.h`. Why are you telling me to install `openal`?

**Comment by 3N4N** [comment]
And I shouldn't have to add `.../include/AL` directory to my include directories. I should be able to just do this:

```c
#include <AL/alure.h>
```

**Comment by Biswa96** [comment]
> And I shouldn't have to add .../include/AL directory to my include directories.

That's how the library was written and it expects that include directory.

**Comment by 3N4N** [comment]
Oh. Okay. If I add `AL` to include directories then obviously this problem is fixed. But it's still weird that a header file from a directory is including another header from the same directory but it's depending on the user to include the directory instead of prepending the directory itself. But I guess that's not an issue for msys team.

Thanks.
