### ISSUE TITLE
mathgl update

### ISSUE THREAD

**Issue by milen-prg** [msys2/MINGW-packages#12201]
Please, update the MathGL package. In the MSYS2 system is 2.4.4-6 version, the official is version 8! (from 2.5 version were big changes).

Thank you, in advance!

**Comment by MehdiChinoune** [comment]
I tried once to upgrade it in #11134 , but for unknown reason it stayed for almost 3 weeks without being reviewed or merged, so I decided to close it.

**Comment by MehdiChinoune** [comment]
shouldn't this be closed!

**Comment by Biswa96** [comment]
@milen-prg [mingw-w64-mathgl][1] package has been updated to version 8.0.1. Would you like to test the new package? You can update packages with `pacman -Syyu` command.

[1]: https://packages.msys2.org/base/mingw-w64-mathgl

**Comment by milen-prg** [comment]
I tested this update with base mathgl examples (write chart to file, draw in qt and fltk window) and it works fine.

Thank you, very much for the fast update!
