### ISSUE TITLE
mingw-w64-x86_64-rust virus?

### ISSUE THREAD

**Issue by stefan-misik** [msys2/MINGW-packages#12267]
Hi,
Is this a false-positive: https://www.virustotal.com/gui/file/a4ec64c3c8b35e32302daa3d5f2a2a7711be2ab1ffca320f40591254b11218ce/detection

Thanks.

**Comment by Biswa96** [comment]
Yes, it is false positive. Packages are compiled in GitHub CI. It's common for mingw or cygwin related programs.

**Comment by stefan-misik** [comment]
Thanks, I submitted it to ESET to investigate the false-positive.
