### ISSUE TITLE
error with .a PARDISO (Intel MKL) library (when Linux is OK)

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#12282]
Hi,
I am trying to compile CalculiX (ccx) using INTEL MKL PARADISO static libraries .a in mingw but I have this error:

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ccx_PardisoMKL_gcc.a(pardiso.o): in function `pardiso_factor':
C:\msys64\usr\local\CalculiX\ccx_2.15\src/pardiso.c:288: undefined reference to `pardiso_'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ccx_PardisoMKL_gcc.a(pardiso.o): in function `pardiso_solve':
C:\msys64\usr\local\CalculiX\ccx_2.15\src/pardiso.c:319: undefined reference to `pardiso_'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ccx_PardisoMKL_gcc.a(pardiso.o): in function `pardiso_cleanup':
C:\msys64\usr\local\CalculiX\ccx_2.15\src/pardiso.c:341: undefined reference to `pardiso_'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ccx_PardisoMKL_gcc.a(pardiso_as.o): in function `pardiso_factor_as':
C:\msys64\usr\local\CalculiX\ccx_2.15\src/pardiso_as.c:161: undefined reference to `pardiso_'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ccx_PardisoMKL_gcc.a(pardiso_as.o): in function `pardiso_solve_as':
C:\msys64\usr\local\CalculiX\ccx_2.15\src/pardiso_as.c:184: undefined reference to `pardiso_'
```

I would like to add that I managed to compile the Linux version with the same Makefile. I also compiled in the "mingw" environment with the .dll libraries but now I want to compile with .a library.

```
ccx_PardisoMKL_gcc: $(OCCXMAIN) ccx_PardisoMKL_gcc.a \
./date.pl; $(CC) $(CFLAGS) -c ccx_2.15.c; \
$(FC) $(OPT) $(FFLAGS) -o $@ $(OCCXMAIN) ccx_PardisoMKL_gcc.a $(LIBS) $(LDFLAGS) \
-Wl,--start-group \
$(MKL_LIB)/libmkl_gf_lp64.a \
$(MKL_LIB)/libmkl_gnu_thread.a \
$(MKL_LIB)/libmkl_core.a \
-Wl,--end-group \
-lgomp -lpthread -lm -ldl
```

When I delete the library libmkl_gf_lp64.a on Linux, I have similar error:

```
ccx_2.15.c:61:22: warning: ‘nxstate’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     *ipoinpc=NULL,mt,nxstate,nload0,iload,*iuel=NULL;
                      ^~~~~~~
ccx_PardisoMKL_gcc.a(pardiso.o): In function `pardiso_factor':
/usr/local/ccx_2.15/src_t1/pardiso.c:288: undefined reference to `pardiso_'
ccx_PardisoMKL_gcc.a(pardiso.o): In function `pardiso_solve':
/usr/local/ccx_2.15/src_t1/pardiso.c:319: undefined reference to `pardiso_'
ccx_PardisoMKL_gcc.a(pardiso.o): In function `pardiso_cleanup':
/usr/local/ccx_2.15/src_t1/pardiso.c:341: undefined reference to `pardiso_'
ccx_PardisoMKL_gcc.a(pardiso_as.o): In function `pardiso_factor_as':
/usr/local/ccx_2.15/src_t1/pardiso_as.c:161: undefined reference to `pardiso_'
ccx_PardisoMKL_gcc.a(pardiso_as.o): In function `pardiso_solve_as':
/usr/local/ccx_2.15/src_t1/pardiso_as.c:184: undefined reference to `pardiso_'
ccx_PardisoMKL_gcc.a(pardiso_as.o):/usr/local/ccx_2.15/src_t1/pardiso_as.c:200: more undefined references to `pardiso_' follow
collect2: error: ld returned 1 exit status
Makefile_mkl:43: recipe for target 'ccx_PardisoMKL_gcc' failed
make: *** [ccx_PardisoMKL_gcc] Error 1
```

**Comment by Biswa96** [comment]
How to reproduce the issue?

**Comment by 3rav** [comment]
> How to reproduce the issue?

1. Download oneAPI for Linux from: https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux&distributions=webdownload&options=offline
2. install or simply copy the required libraries (libmkl_gf_lp64.a; libmkl_gnu_thread.a; libmkl_core.a)

to copy (I use 7zip): 
`D:\PARDISO_static\l_BaseKit_p_2022.2.0.262_offline.sh\qcmmf.tar\.\packages\intel.oneapi.lin.mkl.devel,v=2022.1.0-223\cupPayload.cup\_installdir\mkl\2022.1.0\lib\intel64\`

see attach (source for windows and for linux; they differ only in the ccx_2.15.c file): [CalculiX.zip](https://github.com/msys2/MINGW-packages/files/9212103/CalculiX.zip)

3. Change in Makefile_mingw (for windows)  or Makefile_mkl (for linux) path: MKL_LIB
4. Compile the ccx: make -f Makefile_mingw

**Comment by MehdiChinoune** [comment]
> > How to reproduce the issue?
> 
> 1. Download oneAPI for Linux from: https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux&distributions=webdownload&options=offline
> 2. install or simply copy the required libraries (libmkl_gf_lp64.a; libmkl_gnu_thread.a; libmkl_core.a)
> 
> to copy (I use 7zip): `D:\PARDISO_static\l_BaseKit_p_2022.2.0.262_offline.sh\qcmmf.tar\.\packages\intel.oneapi.lin.mkl.devel,v=2022.1.0-223\cupPayload.cup\_installdir\mkl\2022.1.0\lib\intel64\`
> 
> see attach (source for windows and for linux; they differ only in the ccx_2.15.c file): [CalculiX.zip](https://github.com/msys2/MINGW-packages/files/9212103/CalculiX.zip)
> 
> 3. Change in Makefile_mingw (for windows)  or Makefile_mkl (for linux) path: MKL_LIB
> 4. Compile the ccx: make -f Makefile_mingw

You can't link Linux static libraries to the Windows (mingw) ones. It's impossible.

**Comment by 3rav** [comment]
I have a two questions:
1. May I use .lib files from Windows version in mingw to have full static exe?
2. Is it possible somehow to merg .dll files with .exe in mingw (like in Enigma Virtual Box)?

**Comment by ImperatorS79** [comment]
> I also compiled in the "mingw" environment with the .dll libraries

How did you manage to link the MKL librairies with mingw ? Last time I tried linking the MKL librairies in a program which was using Eigen, I had problems with `__security_cookie`, `__GSHandlerCheck` and `__security_check_cookie` not being defined.

**Comment by guanglei1wang** [comment]
similar issue with ipopt + MKL pardiso (static lib). 
![image](https://user-images.githubusercontent.com/8190450/210315302-59ec50cb-696a-49fd-b389-e2ae4e0f0a00.png)

**Comment by Biswa96** [comment]
Please provide the steps to reproduce the issue. Also make sure that the library is not compiled with MSVC as OP did.
