### ISSUE TITLE
[spdlog] fatal error: spdlog/fmt/bundled/core.h: No such file or directory 

### ISSUE THREAD

**Issue by maged-hanna** [msys2/MINGW-packages#12286]
![image](https://user-images.githubusercontent.com/90328110/181617756-75191ab8-3a03-4041-b8a6-3530d3ec85a1.png)
It looks like the mingw-w64-x86_64-spdlog packaged is missing some dependencies like spdlog/fmt/bundled directory

**Comment by Biswa96** [comment]
How to reproduce this issue? Please provide a sample code for that.

**Comment by maged-hanna** [comment]
![image](https://user-images.githubusercontent.com/90328110/181620520-6e1e335f-11bc-4c4e-aa49-7f4fdfc26356.png)
![image](https://user-images.githubusercontent.com/90328110/181621285-bb1a57b0-0c15-4a04-ac4f-9dae4a97ce6a.png)

- Install spdlog on MSYS2  with $pacman -S mingw-w64-x86_64-spdlog 
- configure clion toolchains  to run using mingw64 as it is showing in the attached image 
- Try to run the [ Usage Example ](https://spdlog.docsforge.com/master/#usage-example)

**Comment by Biswa96** [comment]
It requires all the required macro to be enabled. pkgconfig can help. For example,

```
$ g++ `pkgconf -cflags spdlog` example.cpp `pkgconf -libs spdlog`
```

But now I get a bunch of different errors. Like this one and more,

```
example.cpp:17:29: error: 'stdout_color_mt' is not a member of 'spd'
   17 |         auto console = spd::stdout_color_mt("console");
      |                             ^~~~~~~~~~~~~~~
```

**Comment by Biswa96** [comment]
I have compiled the new example code from the spdlog repository and it works. Source https://github.com/gabime/spdlog/blob/v1.x/example/example.cpp. Command:

```
g++ `pkgconf -cflags spdlog` example.cpp `pkgconf -libs spdlog` -lws2_32
```

**Comment by maged-hanna** [comment]
Where did you compile this example on MSYS2?

**Comment by Biswa96** [comment]
In mingw environment.

**Comment by maged-hanna** [comment]
![image](https://user-images.githubusercontent.com/90328110/181816460-ca2bc5d9-b27e-4390-a816-d0ca1c856bf7.png)
I got it, I had to add the macro as you described in my Cmake file as it showing in the image. 
@Biswa96  Thank you for your help
