### ISSUE TITLE
scipy-1.9.0 failures / segfaults

### ISSUE THREAD

**Issue by carlkl** [msys2/MINGW-packages#12409]
scipy-1.9.0 emits failures in the stats, special, sparse, signal. linalg submodules and seqfaults in the optimize submodule.

This (or most of the test failures) are due to the fact, that the C modules are compiled with the `-mlong-double-64` flag - see `scipy/meson.build`. This flag was introduced to circumvent compatibility problems with the original CPython distribution that is build with MSVC. I propose patching `scipy/meson.build` to remove this flag for the msys2/<arch> builds, as this flag results in incompatibilities. 

BTW: the latest PYPI deployed binary windows version of scipy are not yet build with scipy-meson.

**Comment by lazka** [comment]
Thank
