### ISSUE TITLE
Add Libpanel to Packages

### ISSUE THREAD

**Issue by Zacharymk1213** [msys2/MINGW-packages#12432]
Libpanel is required for certain packages such as Gnome Builder which is in the process of being ported. I was able to compile it with a subproject. To make it'd easier it'd be better to package it officially.

Link: https://gitlab.gnome.org/GNOME/libpanel

**Comment by Biswa96** [comment]
@Zacharymk1213 I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2798198980. Please follow these steps:

1. Scroll down and download the correct artifact. It'll be a zip file.
2. Extract the package (.tar.zst) from zip file.
3. Install it with `pacman -U the-package-name.tar.zst` command.

**Comment by Zacharymk1213** [comment]
@Biswa96 I just tested all the packages and they all installed without incident.

**Comment by Biswa96** [comment]
The package is now available in Pacman repository https://packages.msys2.org/base/mingw-w64-libpanel. It can be installed with `pacman -S` command.
