### ISSUE TITLE
freetype2 not found 

### ISSUE THREAD

**Issue by Alice-Thirty** [msys2/MINGW-packages#12446]
```
Package zlib was not found in the pkg-config search path.
Perhaps you should add the directory containing `zlib.pc'
to the PKG_CONFIG_PATH environment variable
Package 'zlib', required by 'freetype2', not found
Package 'libpng', required by 'freetype2', not found
Package 'harfbuzz', required by 'freetype2', not found
Package 'libbrotlidec', required by 'freetype2', not found
ERROR: freetype2 not found using pkg-config
```

https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/

I follow the step to include freetype2

**Comment by lazka** [comment]
We don't provide Visual Studio compatible libraries, so you'd have to ask Nvidia.

**Comment by lazka** [comment]
We have a package for nv-codec-headers though: https://packages.msys2.org/base/mingw-w64-ffnvcodec-headers

**Comment by lazka** [comment]
If you can give us more information on what you are trying to build/achieve then maybe someone can help, otherwise I'll close this.

**Comment by MehdiChinoune** [comment]
MSYS2 doesn't support MSVC
