### ISSUE TITLE
PkgConf file of OpenBLAS has incomplete/nonexisting path.

### ISSUE THREAD

**Issue by bigla** [msys2/MINGW-packages#12453]
## Describe the issue

When trying to compile software using cmake and pkgconfig of petsc, I found out the `-I` Flag (IncludeDir) of openblas' PkgConf was `-I/mingw64/include/openblas` instead of `-IC:/msys64/mingw64/include/openblas`

## Steps to Reproduce the Problem

1. Run `pkgconf.exe --cflags-only-I openblas`  yields `-I/mingw64/include/openblas`
2. Compare with other Packages (e.g. regex, zlib, superlu ...) `pkgconf.exe --cflags-only-I superlu` yields `-IC:/msys64/mingw64/include/superlu -I/mingw64/include/openblas`
3. The missing `C:/msys64` becomes evident.

## Steps to fix
Look at another *.pc file e.g. `/mingw64/lib/pkgconfig/petsc-smo.pc` and compare with `/mingw64/lib/pkgconfig/openblas.pc`
Notice the missing usage of `prefix=` in the latter file.

Fixed lines
```
prefix=/mingw64
libdir=${prefix}/lib
libsuffix=
includedir=${prefix}/include/openblas
```
## Result of fix
`pkgconf.exe --cflags-only-I openblas` yields `-IC:/msys64/mingw64/include/openblas`

**Comment by Biswa96** [comment]
Hi @bigla, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2805533572 Please follow these steps:

1. Scroll down and download the correct artifact. It'll be a zip file.
2. Extract the package (.tar.zst) from zip file.
3. Install it with `pacman -U the-package-name.tar.zst` command.
