### ISSUE TITLE
Cannot find gnome-keyring or gcr packages

### ISSUE THREAD

**Issue by ThosRTanner** [msys2/MINGW-packages#12457]
I'm trying to build something that (optionally) uses these on windows with mingw64 and either i've got the wrong name or they're not here. Any particular reason? Or am I looking for the wrong name?

**Comment by revelator** [comment]
i think gnome keyring is linux only ?.

**Comment by lazka** [comment]
gcr is also unix only

**Comment by revelator** [comment]
for windows it is probably better to use the native interfaces even if they suck eg. regedit etc.

**Comment by MehdiChinoune** [comment]
Question answered.
