### ISSUE TITLE
[package request] YUView

### ISSUE THREAD

**Issue by Freed-Wu** [msys2/MINGW-packages#12484]
<https://github.com/IENT/YUView/issues/382> I try to package this program but failed.

Thanks!

**Comment by 1480c1** [comment]
@Freed-Wu could you try https://github.com/msys2/MINGW-packages/suites/7714724822/artifacts/322998750 from https://github.com/msys2/MINGW-packages/pull/12486 to see if that works?

**Comment by Freed-Wu** [comment]
Sorry, my virtual machine for windows has crashed :cry:

**Comment by Freed-Wu** [comment]
> @Freed-Wu could you try https://github.com/msys2/MINGW-packages/suites/7714724822/artifacts/322998750 from #12486 to see if that works?

Hey. It can work! Great!
