### ISSUE TITLE
clang-cpp: request static library

### ISSUE THREAD

**Issue by pal1000** [msys2/MINGW-packages#12488]
There is a libclang.a  static library but not a libclang-cpp.a static library. Mesa3D attempts to link against clang-cpp first before attempting to link against individual modules:

https://gitlab.freedesktop.org/search?search=clang-cpp&nav_source=navbar&project_id=176&group_id=1155&search_code=true&repository_ref=main

Also Meson fails to warn when `--prefer-static` is set and a find_library call has `required : false` set and corresponding static library is missing.

**Comment by mati865** [comment]
I think it's not possible to create static clang-cpp library: https://github.com/llvm/llvm-project/blob/5674a3c88088e668b684326c2194a6282e8270ff/clang/tools/clang-shlib/CMakeLists.txt#L45

**Comment by pal1000** [comment]
In that case the solution needs to come from Meson as an option to force non-required libraries / dependencies that cannot honor `--prefer-static` to return not found dependency.  There is also the missing warning problem. Meson printed a warning when it couldn't honor `--prefer-static`  for `llvmspirvlib` in #12306

**Comment by MehdiChinoune** [comment]
Not an MSYS2 issue.
