### ISSUE TITLE
[gtk4] Missing several static GTK files (.a)

### ISSUE THREAD

**Issue by selax** [msys2/MINGW-packages#12512]
Hi! I think the same problem as with gtk3 ( #9556 ) in gtk4. If i compile without static flags - all ok, if i add static flags - there is error:

```
[build] <msys path>/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgtk-4: No such file or directory
[build] <msys path>/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgraphene-1.0: No such file or directory
```

the <msys path>/ucrt64/lib folder does not contain the necessary ones .a files for gtk-4 and graphene-1.0

**Comment by Biswa96** [comment]
Static library for GTK4 was disabled in this upstream commit https://gitlab.gnome.org/GNOME/gtk/-/commit/14f0a0addb9a195bad2f8651f93b95450b186bd6. Let me ask to enable that in upstream.

**Comment by Biswa96** [comment]
Upstream does not want to install static library. See this discussion https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3107. I am thinking to apply the following patch but not sure if it is right way.

```diff
--- a/gtk/meson.build
+++ a/gtk/meson.build
@@ -1227,7 +1227,7 @@
   link_with: [libgtk_css, libgdk, libgsk ],
 )
 
-libgtk = shared_library('gtk-4',
+libgtk = library('gtk-4',
   c_args: gtk_cargs + common_cflags,
   include_directories: [confinc, gdkinc, gskinc, gtkinc],
   dependencies: gtk_deps + [libgtk_css_dep, libgdk_dep, libgsk_dep],
```

**Comment by selax** [comment]
I'm not very experienced in this matter, I don't know if it's right. But if it works, then why not?

**Comment by lazka** [comment]
With upstream explicitly no supporting this I'm unsure. We could patch it, but note that it could get removed with any update in the future if it stops working, and likely no one will look into fixing it then.

**Comment by selax** [comment]
Okay, this option suits me. Thx

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2895895640. Please follow these steps:

1. Scroll down and download the correct artifact. It'll be a zip file.
2. Extract the package (.tar.zst) from zip file.
3. Install it with `pacman -U the-package-name.tar.zst` command.

I have only added static library for gtk4 and graphene. If you can provide the project link I can test whether any other package also need static libraries.

**Comment by selax** [comment]
I test this, but got many "undefined reference" errors. 😢
I try to compile simple gtkmm example with -static option

Project here:
[main.txt](https://github.com/msys2/MINGW-packages/files/9388576/main.txt)
[CMakeLists.txt](https://github.com/msys2/MINGW-packages/files/9388580/CMakeLists.txt)

If u use
`set(CMAKE_EXE_LINKER_FLAGS "-mwindows")`
all works, but if i use
`set(CMAKE_EXE_LINKER_FLAGS "-static -mwindows")`
i got many "undefined reference" errors. 😢

**Comment by Biswa96** [comment]
With your example, I get this error:

```
F:/msys64/ucrt64/include/glibmm-2.68/glibmm/base64.h:23:10: fatal error: string: No such file or directory
   23 | #include <string>
      |          ^~~~~~~~
```

If I tried to compile the example main.c file manually, I get this error:

```
$ gcc -static -static-libgcc `pkgconf -cflags gtkmm-4.0` main.c `pkgconf -libs -static gtkmm-4.0`
-bash: /ucrt64/bin/gcc: Argument list too long
```

**Comment by Biswa96** [comment]
I get the same `multiple definition of DllMain` error as mentioned in https://github.com/msys2/MINGW-packages/issues/9556 issue.

```
ld.exe: lib\libgdk_pixbuf-2.0.a(gdk-pixbuf-io.c.obj):(.text+0x1f80): multiple definition of `DllMain'; F:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libgtk-4.a(gtkwin32.c.obj):(.text+0x50): first defined here
```

Let me check if that DllMain issue can be in upstream.

**Comment by Biswa96** [comment]
I can not use static linking with gtk4.  cmake does not pull all the dependencies. The list of static libraries are too much. If I try to manually compile it, this happens

```
$ g++ -c `pkgconf -cflags -static gtkmm-4.0` main.cpp
$ g++ -static -static-libgcc -mwindows main.o `pkgconf -libs -static gtkmm-4.0`
-bash: /ucrt64/bin/g++: Argument list too long
```

**Comment by selax** [comment]
What can be done about it?

**Comment by mati865** [comment]
Generally response files are the solution for such problems but probably there is no easy way to use it with pkgconf.

**Comment by selax** [comment]
Okay. Then I will use wxWidgets instead of GTK for now. There are no problems with it and it works great in MSYS with static libraries.
