### ISSUE TITLE
[clang] Clang in CLANG64 fails to link programs using __float128

### ISSUE THREAD

**Issue by dimztimz** [msys2/MINGW-packages#12517]
Steps to reproduce:

Open shell under CLANG64 prefix. Then run:
```
pacboy -S clang:c
echo 'int main() { __float128 x = 0.123; x *= x; }' > float.c
clang float.c
```

I get the following error:

```
ld.lld: error: undefined symbol: __multf3
```

Clang under CLANG64 prefix uses [compiler-rt](https://compiler-rt.llvm.org/) instead of [libgcc](https://gcc.gnu.org/onlinedocs/gccint/Libgcc.html#Libgcc). Clang under the prefix MINGW64 uses libgcc and has no problem.

**Comment by kmilos** [comment]
Indeed, in the defined macros for CLANG64 I see `#define __LDBL_MANT_DIG__ 64 `, which would cause `CRT_LDBL_128BIT` to be not defined here:

https://github.com/llvm/llvm-project/blob/ab6a0823afc7e4cc660f0fd3bd07f791fe9e103f/compiler-rt/lib/builtins/fp_lib.h#L107-L109

which in turn leads to this missing symbol:

https://github.com/llvm/llvm-project/blob/ab6a0823afc7e4cc660f0fd3bd07f791fe9e103f/compiler-rt/lib/builtins/multf3.c#L17

**Comment by mati865** [comment]
I have also check it but I doubt `#define __LDBL_MANT_DIG__ 64` is the reason, the same value is defined on Linux by GCC and Clang.

**Comment by kmilos** [comment]
@mati865 W/ GCC you have `#define __FLT128_MANT_DIG__ 113` (not present for LLVM), as they seem to handle [`__Float128` as an explicit, bulit-in type and not an alias of long double on x86_64](https://gcc.gnu.org/onlinedocs/gcc/Floating-Types.html) (which indeed also seems to be 80-bit on x86_64 regardless of platform and compiler). `__Float128` does not exist on LLVM.

**Comment by mati865** [comment]
AFAIK Clang/LLVM supports float128 (except in MSVC mode because MSVC doesn't support it either) but they aren't eager to follow mess that GCC created. `_Float128` should be already working in C++ mode and there is diff for enabling it in C mode: https://reviews.llvm.org/D111382

**Comment by mati865** [comment]
I believe the best action we can take here is reporting this issue upstream.

**Comment by brad0** [comment]
I believe this https://github.com/llvm/llvm-project/commit/d2ce3e9621411f3391def327f89e3a650918989f should fix the issue you're experiencing.

**Comment by dimztimz** [comment]
I was able to reproduce this issue on Linux by specifying the compiler flag `--rtlib=compiler-rt`. So, it is not specific to MSYS2. Here is Godbolt link that tests both clang 17 and clang trunk https://godbolt.org/z/8xM1nzjzM, seems fixed on trunk.
