### ISSUE TITLE
Rename gtk-update-icon-cache-3.0 to gtk-update-icon-cache

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#12527]
This came up on meson IRC, because some meson project needed patching for MSYS2:

https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-gtk-update-icon-cache?repo=ucrt64

Tools expect the gtk-update-icon-cache naming, so we should provide that too. Needs a rename in the gtk2 package to avoid clashes. And copy for now to keep the old name working.

**Comment by eli-schwartz** [comment]
The gtk-update-icon-cache package manually `mv`'s this to a custom name, which seems interesting and isn't upstream behavior.

Meanwhile the gtk2 package depends on gtk-update-icon-cache but also ships a copy? Sounds like it should simply be *removed* from the gtk2 package. You don't need a renamed gtk2 copy of this program under a name that no software anywhere tries to use.
