### ISSUE TITLE
mingw-w64-ngspice: wrong paths to XSPICE code-model libraries in spinit script

### ISSUE THREAD

**Issue by taras-rosa** [msys2/MINGW-packages#12535]
When I run Ngspice I'm getting the following errors:

<img width="535" alt="err_msgs" src="https://user-images.githubusercontent.com/36680649/184256630-438a52aa-1cf6-481d-a59a-18c8ca32594a.png">

Which means that Ngspice cannot locate XSPICE-code model libraries. 
The load commands is defined in "/mingw64/share/ngspice/scripts/spinit" file which is executing by the Ngspice at startup:

<img width="389" alt="spinit_bad_path" src="https://user-images.githubusercontent.com/36680649/184257031-03bcda4d-c28f-424b-90c3-63c3187d0043.png">

The problem arises because the Ngspice is launching as a standalone program and cannot handle MSYS-referenced paths like /mingw64/...
The solution might be to change paths to the code-model libraries to the relative ones:

<img width="310" alt="spinit_fixed_path" src="https://user-images.githubusercontent.com/36680649/184258119-a3ea629c-e82d-4106-b8cc-db05ae507511.png">

After that all libraries are loaded properly which can be checked with "devhelp" command in the Ngspice command window
<img width="536" alt="devhelp" src="https://user-images.githubusercontent.com/36680649/184258615-cddd7d25-13cf-46fd-9f04-2b35e559c3cb.png">

**Comment by Biswa96** [comment]
@umarcor Is it possible to add the workaround that OP mentioned?
