### ISSUE TITLE
mingw-w64-86_64-python-matplotlib weird plt.show() bug (I guess)

### ISSUE THREAD

**Issue by mikamyara** [msys2/MINGW-packages#12567]
Dear all,
working from a fresh msys2 install from chocolatey, then `choco install msys2`, then in msys2 terminal :
```
pacman -Syu
pacman -S mingw-w64-x86_64-freeglut mingw-w64-x86_64-toolchain mingw-w64-x86_64-python3-pip mingw-w64-x86_64-python-scipy mingw-w64-x86_64-python-matplotlib
``` 

let's consider the following simple python lines, that simply plot a sine wave :

```
import numpy as np
import matplotlib.pyplot as plt
t = np.linspace(0,10,1000)
plt.plot(t,np.sin(t))
plt.show()
```
If I write these lines in a notepad-like script.py file, then in msys2:
```
python3 script.py
```
everything works, I get the sine wave in a matplotlib window.

BUT

if I run python in interactive mode, like `python3`, and then, in the python console write every single line the one after the other, everything is ok EXCEPT when I write the last line `plt.show()` : the python console "freezes" (it takes no input anymore, which can be normal) BUT does NOT display the Matplotlib window.

To compare, this however works in Linux or with Anaconda on Windows. Any idea ?

regards,
    Mike

**Comment by lol** [comment]
Facing the same issue. Anybody with a solution?

**Comment by Biswa96** [comment]
I can not reproduce the issue. Please check if all packages are updated with `pacman -Syyu` command.

**Comment by Biswa96** [comment]
The issue does not happen with the given script in original post. It shows the following window.

![image](https://github.com/msys2/MINGW-packages/assets/31443074/0f7ac9e1-ae5e-420a-b47b-ee19e0620683)

Feel free to reopen the issue if the problem persists.
