### ISSUE TITLE
missing `rust.description` for mingw-w64-rust

### ISSUE THREAD

**Issue by Zapeth** [msys2/MINGW-packages#12569]
Normally this would be set in the `config.toml` when compiling the toolchain ([reference](https://github.com/rust-lang/rust/blob/4916e2b9e6ef8cee6f9c6abb75bd01ba9dc07e5c/config.toml.example#L521-L524)), but if I understand the compilation steps correctly it should also be possible via `--release-description` parameter when calling `configure` ([reference](https://github.com/rust-lang/rust/blob/4916e2b9e6ef8cee6f9c6abb75bd01ba9dc07e5c/src/bootstrap/configure.py#L152)).

I guess it would make most sense to set this the same as the package name, ie `mingw-w64-x86_64-rust` or `mingw-w64-clang-x86_64-rust`?

**Comment by filnet** [comment]
I am working on it.
