### ISSUE TITLE
Building libpng Under Clang Fails

### ISSUE THREAD

**Issue by AntumDeluge** [msys2/MINGW-packages#12688]
`libpng` build is looking for `gcc` compiler. I assume under Clang it should be looking for `clang`?

```
==> Starting build()...
configure: loading site script /etc/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for x86_64-w64-mingw32-gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/Jordan/Development/MSYS/MINGW-packages/mingw-w64-libpng/src/build-x86_64-w64-mingw32':
configure: error: C compiler cannot create executables
See `config.log' for more details
==> ERROR: A failure occurred in build().
    Aborting...
```

```
$ echo $MSYSTEM
CLANG64

$ which gcc
which: no gcc in (/clang64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)

$ which clang
/clang64/bin/clang
```

**Edit:** The same error occurs with `bzip2`, `libiconv`, `readline`, & `termcap` packages.

**Comment by Biswa96** [comment]
It's working fine in my system. Here is the similar log to compare with OP.

```
==> Starting build()...
configure: loading site script /etc/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for x86_64-w64-mingw32-gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
```

How did you start the building process? Try with a clean msys2 install, if possible.

**Comment by Biswa96** [comment]
But the second step failed in libpng due to gcc being added in CC variable.

**Comment by AntumDeluge** [comment]
> How did you start the building process? Try with a clean msys2 install, if possible.

```
$ cd mingw-w64-libpng/
$ makepkg
```

My install is only a few days old.

It also fails in GitHub CI: https://github.com/AntumDeluge/MINGW-packages/actions/runs/2886871710

**Comment by Biswa96** [comment]
Agree. Many PKGBUILDs have gcc hardcoded. I shall try to fix those.

**Comment by AntumDeluge** [comment]
`libpng` & the other packages I listed use `${MINGW_PACKAGE_PREFIX}-cc`.

```
$ pacman -Si mingw-w64-clang-x86_64-cc
error: package 'mingw-w64-clang-x86_64-cc' was not found
```

Interestingly, `makepkg` doesn't report a missing build dependency.

**Comment by MehdiChinoune** [comment]
Use `makepkg-mingw` to build MINGW-packages.

**Comment by AntumDeluge** [comment]
> Use `makepkg-mingw` to build MINGW-packages.

`makepkg-mingw` runs a new login shell. So I don't use it because I have special commands read from `.bashrc`.

**Comment by MehdiChinoune** [comment]
> `makepkg-mingw` runs a new login shell. So I don't use it because I have special commands ~read from~ executed in `.bashrc`.

If `makepkg-mingw` is not possible, then you should pass `--config /etc/makepkg_mingw.conf` to `makepkg`.

**Comment by AntumDeluge** [comment]
> If `makepkg-mingw` is not possible, then you should pass `--config /etc/makepkg_mingw.conf` to `makepkg`.

Thanks. Problem persists though with a clean `src` dir.

```
checking for x86_64-w64-mingw32-gcc... clang
checking whether the C compiler works... no
configure: error: in `MINGW-packages/mingw-w64-libpng/src/build-x86_64-w64-mingw32':
configure: error: C compiler cannot create executables
See `config.log' for more details
==> ERROR: A failure occurred in build().
    Aborting...
```

But it's looking for the right compiler at least.

**Comment by AntumDeluge** [comment]
CI fails in a different location:

```
  /clang64/bin/gcc -c -I/C/_/mingw-w64-libpng/src/libpng-1.6.37 -I/C/_/mingw-w64-libpng/src/build-x86_64-w64-mingw32  -march=x86-64 -mtune=generic -O2 -pipe png2pnm.c
  make: /clang64/bin/gcc: No such file or directory
  make: *** [Makefile:37: png2pnm.o] Error 127
  ==> ERROR: A failure occurred in build().
      Aborting...
```

I'm guessing that is what @Biswa96 referred to:
> But the second step failed in libpng due to gcc being added in CC variable.
