### ISSUE TITLE
gcc: Rewriting of "Enable shared gnat implib" in progress

### ISSUE THREAD

**Issue by stahta01** [msys2/MINGW-packages#12756]
I am starting work on replace GCC change "0011-Enable-shared-gnat-implib.patch"

Edit: This thread is an attempt to avoid two people working on a solution at the same time.

Reason: Enabling GCC Ada and GCC Plugin support with this patch exceeds memory size supported.

I know of no reason for GCC Plugin support to be used under MinGW; so, this will be a very back burner project.

If anyone knows of an GCC plugin that is useful under MinGW please link to it in this thread.

If anyone knows how to test my future replacement changes of "0011-Enable-shared-gnat-implib.patch"; please post them also in this thread.

I am going to go with two patch files and two def files as my default long term solution. The hard work will be figuring out what goes into the two def files.

Tim S.

**Comment by revelator** [comment]
dragonegg maybe ? would be a nice one to have :)

**Comment by stahta01** [comment]
I see no sign that dragonegg ever worked under MinGW GCC.

Tim S.

**Comment by revelator** [comment]
it did once i worked together with one of the mingw-w64 devs way back on it and we managed to port it, sadly it newer made it into the public as such because using the plugin was rather irksome on windows :/

**Comment by stahta01** [comment]
Okay, nice to know; but, I would prefer a plugin that is know to work when trying to get our GCC to support plugins once more.

Tim S.

**Comment by stahta01** [comment]
> understandable not even sure if our port works with later versions of gcc as development on dragonegg halted around gcc-4.8... strangely gcc-9 had working plugin support but later versions seems to grouch on ordinals being to large.

That is because MinGW is second class and it uses export all symbols instead of just the needed symbols; my current testing is not show progress. But, I hope if I create enough def files to export a sub-set of symbols the ordinals will no longer be to large. I had one test run that implied even without Ada being enable the number of ordinals was over 64K which I think is the max allowed before it error out. I just disable Ada support to confirm the issue still exists.

Tim S.

**Comment by stahta01** [comment]
I have decide to use the GCC plugin "ODB: C++ Object-Relational Mapping (ORM)" for testing my changes.
I still have to get GCC to compile with gcc plugin enabled; I may have to revert back to GCC version 9/8/7 to get that to work and proceed to later versions once I get a version that used to work building and running.

Tim S.

**Comment by revelator** [comment]
sounds like a worthy goal :) maybe we can even get lucky and get the gcc_xml plugin working.

**Comment by stahta01** [comment]
Turns out 12.1.1 builds with gcc plugin enabled and without Ada support.

Tim S.

**Comment by stahta01** [comment]
I had to comment out a lot of configure options that was needed back in GCC 8 and 9 to get it to build with GCC plugin support. It might have run-time issues.

**Comment by revelator** [comment]
ouch :S

**Comment by stahta01** [comment]
I am now building gcc11-git package and seeing what error I get; if it works I will try to use the same type of changes in gcc12-git. GCC git master was broken a week or so back by adding things that are not defined under MinGW CRT headers. I am expecting errors; but, I do not remember ever trying this exact GCC configuration.

Tim S.

**Comment by revelator** [comment]
could leave out the bootstrap step if testing, should make things a little faster :)

**Comment by revelator** [comment]
D lang would be great but i think it will be pretty hard porting it, quite a lot of changes nessesary and from what i could glean you need a patched version of libphobos replacing the one that comes with gcc. If you manage it ill salute you :)

**Comment by stahta01** [comment]
> could leave out the bootstrap step if testing, should make things a little faster :)

I am doing that already using MinGW64 for testing. I have decided to try using older version of GCC if I can get that to work in the next three days. I have tried to get Ada to build on older versions of GCC and always failed.
After it fails this time, I will work on getting GCC Plugin to work using GCC 12 without Ada. If I can not get that to work will likely give up on getting GCC Plugin to work; but, if I get it to work will go bad to getting Ada and GCC Plugin to work together.

NOTE: UCRT64 does not like non bootstrap builds. Not tried MinGW32 lately; but, it used to work okay.

Tim S.

**Comment by stahta01** [comment]
> D lang would be great but i think it will be pretty hard porting it, quite a lot of changes nessesary and from what i could glean you need a patched version of libphobos replacing the one that comes with gcc. If you manage it ill salute you :)

Then, sounds like D Lang is too much for me to try at present. Tim S.

**Comment by revelator** [comment]
you need an older binutils as well if trying with an older gcc model, the new version goes bonkers with the old dwarf2 exception model found that out the hard way :S

**Comment by revelator** [comment]
to bad about Dlang but yeah will probably be to hard for one man, sadly im not fluent in D programming though i do know its creator :)

**Comment by stahta01** [comment]
Found directions on how to do an Ada GCC plugin:
[Ada dirrections](https://blog.adacore.com/bindings-gcc-plugins).
I plan to use GCC 8 git branch and after I get that to work will try GCC 9 or 12 git branch.

GCC 8 was reported on the Internet as the first time MinGW GCC Plugins worked.

So, I hope all I need to do is port the Ada GCC plugin directions to MinGW.
I already have gotten GCC Ada version 8 to build.

Tim S.

**Comment by revelator** [comment]
nice :)

**Comment by revelator** [comment]
interresting about clang in that article though a few pitfalls i noticed early on if using that approach, ada is a nogo since you need a working ada compiler to bootstrap gnat (no exceptions i know of). i can allready bootstrap gcc itself with clang if i leave out ada, not sure if it nets any benefits besides better error checking in the bootstrap.  gnat is pretty cool but does not seem to be used a lot on windows :/ and gtkada seems to be broken atleast i could newer get it working maybe due to lacking the correct opengl output library which seems to be patched out in our version but should really be changed to link to libopengl32.a instead of libgl.a. it does build if doing that but im still having problems getting the gui up.

**Comment by stahta01** [comment]
I have already reversed boot strap Ada down to GCC 6; I am working on try to install the GCC to /opt subfolders and that is failing; will try to install to /opt for a few hours. If it fails will revert back to normal /mingw64 like install locations. One of my long term projects is to revert bootstrap Ada to GCC 4.6.
I will see if gtkada works for me at some future time. I remember installing it; but, I have no idea why I installed it.

**Comment by stahta01** [comment]
So, it is clang64/32 that is having the problem; I did not understand that.
I am not really doing an GCC cross-compiler; just an local GCC with a different major version.
Are you trying to make "mingw-w64-clang-x86_64-gcc-ada" package?
That is what I would try in order to make progress on an clang Ada.

Tim S.

**Comment by revelator** [comment]
ae that was my intent :) though so far no luck.

**Comment by revelator** [comment]
gnat-llvm tried this some years back and yeah though they provide instructions for a windows build i suspect it to be for msvc :S cause following it to the letter with gcc fails.

**Comment by revelator** [comment]
i have a ready to use bootstrap compiler based on gcc-11.3.0 if you need one ?, it uses static libgmp isl mpfr mpc zlib winpthreads and zstd so does not rely on any externals.

**Comment by stahta01** [comment]
> i have a ready to use bootstrap compiler based on gcc-11.3.0 if you need one ?, it uses static libgmp isl mpfr mpc zlib winpthreads and zstd so does not rely on any externals.

I have no need for it.

Tim S.

**Comment by revelator** [comment]
oki :) just wanted to let you know in case you rather focus on some of the other work.

**Comment by revelator** [comment]
btw any idea why i get this in the last stage of the bootstrap with gcc-12.2.0 ?

xgcc.exe: internal compiler error: Aborted signal terminated program gnat1

**Comment by stahta01** [comment]
> btw any idea why i get this in the last stage of the bootstrap with gcc-12.2.0 ?
> 
> xgcc.exe: internal compiler error: Aborted signal terminated program gnat1.
> 
> kindof looks like the bug we had with gcc-8 ?!? but has grep been updated again without me noticing.

I have no idea why you are getting it.

Tim S.

**Comment by revelator** [comment]
at first i suspected my bootstrap compiler might be at fault but i tried the official package as well and no matter which one it allways fails on that particular step :S gcc bug maybe ?

**Comment by stahta01** [comment]
I have decided to try porting gnat-llvm to CLANG64.
Planned steps are
port mingw-w64-clang-x86_64-gcc-ada package 
(This package will not contain libada and will be missing a lot of other stuff)
port gprbuild-bootstrap to CLANG64

If I can get both of above done, I might be able to port gnat-llvm to CLANG64.

I hope to get GCC-Ada version 9 for MING32 built before switching tasks. A weird build bug is happening only for MINGW32; MINGW64 builds without any problem.

Tim S.

**Comment by stahta01** [comment]
> internal compiler error

An "internal compiler error" is almost always an 

> at first i suspected my bootstrap compiler might be at fault but i tried the official package as well and no matter which one it allways fails on that particular step :S gcc bug maybe ?

An ICE "internal compiler error" is almost always a GCC bug.

Tim S.

**Comment by revelator** [comment]
ouch looks like the change to let the C++ compiler run the bootstrap still needs some bugs ironed out then :S

does the bug happen in building llvm-ada ? when using the 32 bit compiler ? or do you mean a bug building gcc itself.

**Comment by stahta01** [comment]
> ouch looks like the change to let the C++ compiler run the bootstrap still needs some bugs ironed out then :S
> 
> does the bug happen in building llvm-ada ? when using the 32 bit compiler ? or do you mean a bug building gcc itself.

My mingw32 build bug is not an internal GCC bug, it is an function prototype conflict between an system and an liberty [v] printf type function. I decided to ignore the mingw32 for now; will only build mingw64 and only after I get that to work will try mingw32 for my GCC plugin and Ada version backports to older GCC versions.
I am for today trying to get CLANG64 GCC Ada to build using UCRT64 GCC Ada; if I make no progress in the next few hours I will switch back to my GCC plugin and Ada version backports projects.

Tim S.

**Comment by revelator** [comment]
ah ok yeah that might be prudent though since most of the bugs that crop up seem to affect the 32 bit compiler maybe we should focus on that ?. the bug i have with ada seems to be because gnat now relies on exception propagation and it is also broken on darwin with current gcc version, for some odd reason it seems my build environment passes static-libgcc to the build chain thus breaking exceptions :S, no idea why though as im not using that flag.

**Comment by revelator** [comment]
the fix was per the thread for darwin's failed ada bootstrap

```
-GCC_LINK=$(LINKER) $(GCC_LINKERFLAGS) $(LDFLAGS)
-GCC_LLINK=$(LLINKER) $(GCC_LINKERFLAGS) $(LDFLAGS)
+GCC_LINK=$(LINKER) $(GCC_LINKERFLAGS) -shared-libgcc $(LDFLAGS)
+GCC_LLINK=$(LLINKER) $(GCC_LINKERFLAGS) -shared-libgcc $(LDFLAGS)
```
in gcc/ada/gcc-interface/make-lang.in

**Comment by stahta01** [comment]
If I get an Ada related build issue adding "-shared-libgcc" to gcc/ada/gcc-interface/make-lang.in might be worth trying. I have not gotten far enough on my cross-environment build of GCC with Ada (without libada); from UCRT64 to CLANG64 project to have that problem.

**Comment by revelator** [comment]
feel free to use it if you run into trouble :) worked for mine so im back up.

**Comment by revelator** [comment]
whoops i just discovered a mighty bug in gcc-12.2.0 :O

extern std::terminate_handler __terminate_handler;
extern std::terminate_handler __unexpected_handler;

in unwind-cxx.h

should be ->

extern std::terminate_handler __terminate_handler;
extern std::unexpected_handler __unexpected_handler;

so yeah exceptions are indeed broken in this version :S

**Comment by revelator** [comment]
reported upstream here https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106908

**Comment by revelator** [comment]
not a bug it turns out, C++17 has no unexpected handler so it was done to allow it to build even if unsupported.
turns out the declarations are the same for both of these.

**Comment by revelator** [comment]
also been getting a lot of requests for a tdm based gcc as a plugin to msys2 though due to a rather irksome bug in tdm's shared pointer code i been holding of on trying to get it in. After a lot of debugging i found out it was the mutex locking mechanism that was broken in tdm's code, had to do a lot of reading on mutexes and process synchronization to get it working right but it does now :D very very well actually. The benefit of this ? well code linked to the static gcc runtimes can now throw exceptions across dll boundaries :).

**Comment by stahta01** [comment]
The TDM based GCC sounds good; I got side tracked updating wxWidgets GUI Library and CodeLite IDE.
Failed on the CodeLite IDE it still seg faults in the wxcrafter plugin. I have decided to do GCC for a while and then try the suggested CodeLite build directions and see if the work.

Tim S.

**Comment by revelator** [comment]
still investigating a possible bug in the TDM code, so far it only seems to affect gdk-pixbuf2 but it is a deal breaker cause it renders the 32 bit version unusable :S.
may also be that it exposes a bug in the gdk-pixbuf2 code but im having a hard time debugging it with the new gdb.

**Comment by revelator** [comment]
[0160-shared-memory.zip](https://github.com/msys2/MINGW-packages/files/9642352/0160-shared-memory.zip)

my current version of TDM's shared pointers code, having a hard time with the current gdb which seems to think that the executables do not exist ?!? tried windows paths posix paths cygpath -m style paths i even tried running them directly from the same dir and it keeps complaning that the damn things are not there but they are sigh... 
have a look and if you spot anything i might have missed let me know.

**Comment by revelator** [comment]
finally got gdb working again, looks like the crash happens in libyuv strangely only on the 32 bit version and only if linked to the static runtimes. so i tried building it with the official gcc and linking it to the static runtimes from that and i get the same failure ?!? so i guess i can rule out the TDM patch as the culprit there.

**Comment by revelator** [comment]
well everything else builds though it is time consuming i have allmost all other packages from us built with the TDM based gcc now, a few packages needed some workarounds due to the build tools not being good at getting dependencies from statically linked runtimes but otherwise it seems to be good now.

**Comment by revelator** [comment]
btw the segfault you get in wxcrafter sounds awfully like the bug codeblocks was running into when built with the TDM based gcc, could ofc be unrelated but maybe worth investgating ?.

**Comment by stahta01** [comment]
> btw the segfault you get in wxcrafter sounds awfully like the bug codeblocks was running into when built with the TDM based gcc, could ofc be unrelated but maybe worth investgating ?.

I am thinking that would be a long shoot; not worth trying right now. If the posted directions have the crash I will post the issue upstream for the CodeLite Author to fix. If the directions work I will try to locate the compiling option that differs and work on the package.

Tim S.
