### ISSUE TITLE
Shared Mime Info 2.2 is available

### ISSUE THREAD

**Issue by brisingraerowing** [msys2/MINGW-packages#12754]
(And has been for a while)

Both patches are no longer needed. I have built this myself successfully with the current instructions (minus the patches).

**Comment by Biswa96** [comment]
Hi @brisingraerowing, I have added a pull request to update the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2899166050.
