### ISSUE TITLE
[plplot] libcsirocsa.dll.a cannot be found when importing with cmake find_package

### ISSUE THREAD

**Issue by adamkhonat** [msys2/MINGW-packages#12770]
When trying to build PLplot example [00](http://plplot.sourceforge.net/examples.php?demo=00) with the following top level cmake file, the following error occurs. 
```
cmake_minimum_required(VERSION 3.0.0)
project(Example VERSION 0.1.0)
project(Example C)

add_executable(Example main.c)

find_package(plplot)

target_include_directories(Example PUBLIC
                          "${PROJECT_BINARY_DIR}"
                          "${PROJECT_SOURCE_DIR}"
                          )
```
```
[build] CMake Error at C:/msys64/mingw64/lib/cmake/plplot/export_csirocsa.cmake:64 (message):
[build]   The imported target "PLPLOT::csirocsa" references the file
[build] 
[build]      "/mingw64/lib/libcsirocsa.dll.a"
[build] 
[build]   but this file does not exist.  Possible reasons include:
[build] 
[build]   * The file was deleted, renamed, or moved to another location.
[build] 
[build]   * An install or uninstall procedure did not complete successfully.
[build] 
[build]   * The installation package was faulty and contained
[build] 
[build]      "C:/msys64/mingw64/lib/cmake/plplot/export_csirocsa.cmake"
[build] 
[build]   but not all the files it references.
[build] 
[build] Call Stack (most recent call first):
[build]   C:/msys64/mingw64/lib/cmake/plplot/plplot_exports.cmake:11 (include)
[build]   C:/msys64/mingw64/lib/cmake/plplot/plplotConfig.cmake:20 (include)
[build]   CMakeLists.txt:13 (FIND_PACKAGE)
[build] 
[build] 
[build] -- Configuring incomplete, errors occurred!
```

**Comment by Biswa96** [comment]
Hi @adamkhonat, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2905618947. Please follow these steps:

1. Scroll down and download the correct artifact. It'll be a zip file.
2. Extract the package (.tar.zst) from zip file.
3. Install it with `pacman -U the-package-name.tar.zst` command.

The example code can not be compiled even when the cmake files are fixed.

**Comment by adamkhonat** [comment]
@Biswa96 I get the following error from pacman when I follow the steps 
```
$ pacman -U mingw-w64-x86_64-plplot-5.15.0-17-any.pkg.tar.zst
loading packages...
resolving dependencies...
warning: cannot resolve "mingw-w64-x86_64-wxwidgets3.0-msw-libs", a dependency of "mingw-w64-x86_64-plplot"
:: The following package cannot be upgraded due to unresolvable dependencies:
      mingw-w64-x86_64-plplot

```

**Comment by Biswa96** [comment]
It seems that you have not updated packages for a while. Try to update packages with `pacman -Syyu` **twice**. Then install the package from GitHub Actions artifact.

**Comment by adamkhonat** [comment]
Thanks that solved it. The example now builds without cmake errors I will close this.

**Comment by Biswa96** [comment]
> The example now builds without cmake errors I will close this.

How? Please provide the steps to fix the example code.
