### ISSUE TITLE
[libssh] entrypoint error

### ISSUE THREAD

**Issue by vivision1** [msys2/MINGW-packages#12772]
The libssh here https://packages.msys2.org/package/mingw-w64-x86_64-libssh?repo=mingw64
gives entrypoint error

Had to download this https://packages.msys2.org/package/libssh?repo=msys&variant=x86_64
and rename to libssh.dll in the application folder in order to work

Thanks

**Comment by Biswa96** [comment]
Would you like to provide an minimal sample code to reproduce the error?

**Comment by vivision1** [comment]
I use opencv, I dont add libssh.dll on ld, but it needs it
The previous version of libssh has that entry point
---------------------------
frobot.exe - Ponto de entrada não encontrado
---------------------------
Não foi possível localizar o ponto de entrada do procedimento EVP_PKEY_get_raw_private_key na DLL (dynamic-link library) c:\msys64\mingw64\bin\libssh.dll.

**Comment by Biswa96** [comment]
I did not fully understand your last comment. EVP_PKEY_get_raw_private_key is exported by openssl (libcrypto-1_1-x64.dll). That API is used in libssh.dll. It would be easier to reproduce the issue if you can provide any sample code or program.

**Comment by vivision1** [comment]
the code I used is this [https://github.com/spmallick/learnopencv/blob/master/ObjectDetection-YOLO/object_detection_yolo.cpp](url)
I've debugged a bit and found that 
    VideoWriter video;
lauches the error

**Comment by Biswa96** [comment]
So, the issue is not from libssh, right?

**Comment by vivision1** [comment]
The issue it throws missing entrypoint of libssh.dll when I run the code

**Comment by Biswa96** [comment]
What command do I have to use to reproduce the issue? The cpp file seems to generate an executable linked with opencv and it expects some A/V or image files. I can not clone the entire repository, it's so huge. So, it would be helpful if you provide which files are required with the executable.

**Comment by vivision1** [comment]
It's only that file linked with opencv4. No need to put any file to see the error

**Comment by Biswa96** [comment]
I have compiled that cpp file with this command

```
g++ `pkgconf -cflags opencv4` object_detection_yolo.cpp `pkgconf -libs opencv4`
```

And here is the output if I simply run the executable

```
$ ./a.exe
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.6.0) Error: Parsing error (Failed to open NetParameter file: yolov3.cfg) in readNetFromDarknet, file C:/M/mingw-w64-opencv/src/opencv-4.6.0/modules/dnn/src/darknet/darknet_importer.cpp, line 210
```

**Comment by vivision1** [comment]
well, that in bash links fine, don't throw error, but that in common cmd of windows, that I use, throws error
`g++ -Ic:/msys64/mingw64/include/opencv4 object_detection_yolo.cpp -Lc:/msys64/mingw64/lib -lopencv_gapi -lopencv_stitching -lopencv_alphamat -lopencv_aruco -lopencv_barcode -lopencv_bgsegm -lopencv_ccalib -lopencv_cvv -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_intensity_transform -lopencv_line_descriptor -lopencv_mcc -lopencv_ovis -lopencv_quality -lopencv_rapid -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_sfm -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_highgui -lopencv_datasets -lopencv_text -lopencv_plot -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_wechat_qrcode -lopencv_xfeatures2d -lopencv_shape -lopencv_ml -lopencv_ximgproc -lopencv_video -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_dnn -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core`
I use makefile

**Comment by Biswa96** [comment]
I did not understand the "common cmd of windows" terminology. Are you compiling and running in mingw environment? The executable need to find all the DLLs from PATH variable. I have test with a makefile and it shows same result

```makefile
CXXFLAGS = `pkgconf -cflags opencv4`
LDFLAGS = `pkgconf -libs opencv4`

yolo: object_detection_yolo.cpp
	$(CXX) $(CXXFLAGS) $< -o $@ $(LDFLAGS)
```

Also try to reinstall the mingw-w64-libssh package, if that helps.

**Comment by Biswa96** [comment]
Tried with CMD, same error

```
> PATH=%PATH%;F:\msys64\ucrt64\bin
> F:\msys64\home\x\test\yolo.exe
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.6.0) Error: Parsing error (Failed to open NetParameter file: yolov3.cfg) in readNetFromDarknet, file C:/M/mingw-w64-opencv/src/opencv-4.6.0/modules/dnn/src/darknet/darknet_importer.cpp, line 210
```

**Comment by vivision1** [comment]
I tried with CMD the follow, that is the setup I use

> SET PATH=%PATH%;c:/msys64/mingw64/bin
C:\msys64\mingw64\bin\g++ -Ic:/msys64/mingw64/include/opencv4 objdetectyolo.cpp -Lc:/msys64/mingw64/lib -lopencv_gapi -lopencv_stitching -lopencv_alphamat -lopencv_aruco -lopencv_barcode -lopencv_bgsegm -lopencv_ccalib -lopencv_cvv -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_intensity_transform -lopencv_line_descriptor -lopencv_mcc -lopencv_ovis -lopencv_quality -lopencv_rapid -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_sfm -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_highgui -lopencv_datasets -lopencv_text -lopencv_plot -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_wechat_qrcode -lopencv_xfeatures2d -lopencv_shape -lopencv_ml -lopencv_ximgproc -lopencv_video -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_dnn -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core

and that throw libssh entrypoint error

**Comment by Biswa96** [comment]
I have tried the same command and got same errors as my previous comments. Though I am not sure why you are compiling a simple program in so complicated way. There may be some issue in your system.

**Comment by vivision1** [comment]
I compile all apps with the same makefile, that's why it seems complicated but its not.
The issue I don't understand what could it be, I've installed fresh msys2 last version and installed and updated all the packages I need, then all programs compile well, unless this sample app that I need.

**Comment by Biswa96** [comment]
Try to make sure that no 3rd party programs, like antivirus or anitmalware, did not corrupt the files in msys2/mingw. You can also build the project in CI. This [docs](https://www.msys2.org/docs/ci/) may help in that case.

**Comment by vivision1** [comment]
But it compiles well in bash, its not corrupted.
Only in CMD it compiles but seeks libssh dont know why

**Comment by mati865** [comment]
> I tried with CMD the follow, that is the setup I use
>> SET PATH=%PATH%;c:/msys64/mingw64/bin

You should put `c:/msys64/mingw64/bin` first in `PATH`, otherwise something else might overshadow binaries.
I believe you will get the same results in CMD as in BASH if you create clean environment (in terms of `PATH` and other environment variables).

**Comment by vivision1** [comment]
> You should put c:/msys64/mingw64/bin first in PATH, otherwise something else might overshadow binaries.
I believe you will get the same results in CMD as in BASH if you create clean environment (in terms of PATH and other environment variables).

Well that solves the problem, well viewed, thanks
