### ISSUE TITLE
Mingw gcc 12.0 does not work

### ISSUE THREAD

**Issue by waruqi** [msys2/MINGW-packages#12791]
I update mingw gcc to 12.0 (latest version), and it does not work.

```console
$ pacman -Sy mingw-64-x86_64-toolchain
```

I try run `gcc` to build a simple c++ code, it does not work. and nothing output.  no any binary is generated.

```console
$ x86_64-w64-mingw32-gcc -otest src/main.cpp
no any output
$ ls
nothing
```

**Comment by MehdiChinoune** [comment]
Are you using MSYS2?

**Comment by waruqi** [comment]
yes

**Comment by MehdiChinoune** [comment]
Could you show minimal reproducer.

**Comment by MehdiChinoune** [comment]
I tried a simple program and It works perfectly:
```C
#include "stdio.h"

int main() {
    printf("Hello World");
    return 0;
}
```
```
$ x86_64-w64-mingw32-gcc main.c -otest

$ ./test.exe
Hello World
```

**Comment by waruqi** [comment]
It does not work for me.

![image](https://user-images.githubusercontent.com/151335/186579033-f223cfa3-a7f4-4f12-bcfa-9a85e4265468.png)

**Comment by waruqi** [comment]
No any errors if cpp file does not exists.

![image](https://user-images.githubusercontent.com/151335/186579353-bdbbc7fe-7461-4787-b411-918f6ecd0e75.png)

**Comment by MehdiChinoune** [comment]
Could you use `.c` instead of `.cpp`, just to confirm.

**Comment by waruqi** [comment]
same issue

![image](https://user-images.githubusercontent.com/151335/186579826-4ff13860-c467-471d-a1f7-a3677d7e49d2.png)

**Comment by Biswa96** [comment]
gcc is working fine in my system. No issue at all.

**Comment by MehdiChinoune** [comment]
Which Windows version are you using?
Is your MSYS2 installation up-to-date (run `pacman -Syuu` twice)

**Comment by waruqi** [comment]
the previous gcc 10 work for me, but it does not work when I run `$ pacman -Sy mingw-64-x86_64-toolchain` to update them to gcc-12.

**Comment by waruqi** [comment]
> Which Windows version are you using?

win7

**Comment by MehdiChinoune** [comment]
> > Which Windows version are you using?
> 
> win7

Is your MSYS2 up-to-date?
Run `pacman -Syuu` twice to make sure.

**Comment by waruqi** [comment]
> Run pacman -Syuu twice to make sure.

I am running it, but it is failed now.

**Comment by MehdiChinoune** [comment]
> I am running it, but it is failed now.

What is failing, updating or compilation?

**Comment by waruqi** [comment]
> > I am running it, but it is failed now.
> 
> What is failing, updating or compilation?

file exists conflict, but I have fixed it. It (gcc) works fine now. Thanks!
