### ISSUE TITLE
Darktable fails to build against SDL2 2.24.0

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#12874]
### Description

Darktable now fails to build against SDL2 2.24.0
MINGW64:
```
  [555/910] Linking C shared module lib\darktable\plugins\lighttable\libgamepad.dll
  FAILED: lib/darktable/plugins/lighttable/libgamepad.dll 
  cmd.exe /C "cd . && D:\M\msys64\mingw64\bin\gcc.exe -march=x86-64 -mtune=generic -O2 -pipe -Wall -Wno-format -Wshadow -Wtype-limits -Wvla -Wold-style-declaration -Wno-unknown-pragmas -Wno-error=varargs -Wno-format-truncation -Wno-error=address-of-packed-member -std=c99 -fopenmp -mtune=generic -msse2 -g -mfpmath=sse -O3 -DNDEBUG -O3 -ffast-math -fno-finite-math-only -fexpensive-optimizations  -pipe -Wl,--enable-runtime-pseudo-reloc   -Wl,--undefined=WinMain -shared -o lib\darktable\plugins\lighttable\libgamepad.dll -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\gamepad.rsp  && cmd.exe /C "cd /D C:\_\mingw-w64-darktable\src\build-MINGW64\lib\darktable\plugins\lighttable && D:\M\msys64\mingw64\bin\cmake.exe -E make_directory .debug && objcopy --only-keep-debug C:/_/mingw-w64-darktable/src/build-MINGW64/lib/darktable/plugins/lighttable/libgamepad.dll C:/_/mingw-w64-darktable/src/build-MINGW64/lib/darktable/plugins/lighttable/libgamepad.dll.dbg && objcopy --strip-debug C:/_/mingw-w64-darktable/src/build-MINGW64/lib/darktable/plugins/lighttable/libgamepad.dll && objcopy --add-gnu-debuglink=libgamepad.dll.dbg C:/_/mingw-w64-darktable/src/build-MINGW64/lib/darktable/plugins/lighttable/libgamepad.dll""
  D:/M/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/M/msys64/mingw64/lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0x152): undefined reference to `SDL_main'
```
CLANG64:
```
  [554/910] Linking C shared module lib\darktable\plugins\lighttable\libgamepad.dll
  FAILED: lib/darktable/plugins/lighttable/libgamepad.dll 
  cmd.exe /C "cd . && D:\M\msys64\clang64\bin\clang.exe -march=x86-64 -mtune=generic -O2 -pipe -fopenmp-version=45 -Wall -Wno-format -Wshadow -Wtype-limits -Wvla -Wthread-safety -Wno-unknown-pragmas -Wno-error=varargs -Wno-error=address-of-packed-member -std=c99 -fopenmp=libomp -mtune=generic -msse2 -g -O3 -DNDEBUG -O3 -ffast-math -fno-finite-math-only  -pipe -Wl,--enable-runtime-pseudo-reloc   -Wl,--undefined=WinMain -shared -o lib\darktable\plugins\lighttable\libgamepad.dll -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\gamepad.rsp  && cmd.exe /C "cd /D C:\_\mingw-w64-darktable\src\build-CLANG64\lib\darktable\plugins\lighttable && D:\M\msys64\clang64\bin\cmake.exe -E make_directory .debug && objcopy --only-keep-debug C:/_/mingw-w64-darktable/src/build-CLANG64/lib/darktable/plugins/lighttable/libgamepad.dll C:/_/mingw-w64-darktable/src/build-CLANG64/lib/darktable/plugins/lighttable/libgamepad.dll.dbg && objcopy --strip-debug C:/_/mingw-w64-darktable/src/build-CLANG64/lib/darktable/plugins/lighttable/libgamepad.dll && objcopy --add-gnu-debuglink=libgamepad.dll.dbg C:/_/mingw-w64-darktable/src/build-CLANG64/lib/darktable/plugins/lighttable/libgamepad.dll""
  ld.lld: error: undefined symbol: SDL_main
  >>> referenced by libSDL2main.a(SDL_windows_main.c.obj):(main_getcmdline)
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows Server 2022
 10.0.20348
 Datacenter

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

Succeeds

### Actual behavior

Fails

### Repro steps

Rebuild darkatable against the last updates.

**Comment by gi-man** [comment]
@kmilos Could this be an issue in darktable? Like it needs an update in the cmake?

**Comment by kmilos** [comment]
Why is it trying to link against a static lib anyway?

**Comment by kmilos** [comment]
`target_link_libraries(gamepad ${SDL2_LIBRARIES})`

It looks like `SDL2_LIBRARIES` now includes both `SDL2::SDL2main` (static only) and `SDL2::SDL2` targets? I don't have the old package lying around to see how it was before...

**Comment by MehdiChinoune** [comment]
SDL2 2.0.22 https://github.com/libsdl-org/SDL/blob/release-2.0.22/sdl2-config.cmake.in#L11
SDL2 2.24.0 https://github.com/libsdl-org/SDL/blob/release-2.24.0/SDL2Config.cmake.in#L54 and https://github.com/libsdl-org/SDL/blob/release-2.24.0/SDL2Config.cmake.in#L61

Maybe changing `${SDL2_LIBRARIES}` to `SDL2::SDL2` could fix the issue.

**Comment by kmilos** [comment]
Thanks! Would be good to know what `set(SDL2_LIBRARIES "-L${SDL2_LIBDIR} @SDL_RLD_FLAGS@ @SDL_LIBS@")` was actually replaced with in the previous MinGW package... I'll download it somewhere and do more checks.

**Comment by MehdiChinoune** [comment]
> Thanks! Would be good to know what `set(SDL2_LIBRARIES "-L${SDL2_LIBDIR} @SDL_RLD_FLAGS@ @SDL_LIBS@")` was actually replaced with in the previous MinGW package... I'll download it somewhere and do more checks.

https://github.com/libsdl-org/SDL/blob/release-2.0.22/CMakeLists.txt#L277
https://github.com/libsdl-org/SDL/blob/release-2.0.22/CMakeLists.txt#L1818 (SDL2main!)

**Comment by kmilos** [comment]
Looks like the same libs are used in CMakeCache.txt,

2.0.22: `gamepad_LIB_DEPENDS:STATIC=general;C:/msys64/ucrt64/lib/libSDL2main.a;general;C:/msys64/ucrt64/lib/libSDL2.dll.a;general;lib_darktable;`

2.24.0: `gamepad_LIB_DEPENDS:STATIC=general;SDL2::SDL2main;general;SDL2::SDL2;general;lib_darktable;`

but the linker options are different:

2.0.22: `LINK_FLAGS = -Wl,--enable-runtime-pseudo-reloc`

2.24.0: `LINK_FLAGS = -Wl,--enable-runtime-pseudo-reloc   -Wl,--undefined=WinMain`

**Comment by Biswa96** [comment]
@madebr Do we need to add those removed patch file?

**Comment by kmilos** [comment]
Confirmed that removing `-Wl,--undefined=WinMain` from `SDL2mainTargets.cmake` makes the build pass again (haven't verified if it works though, no gamepad here).

**Comment by madebr** [comment]
> Why is it trying to link against a static lib anyway? @madebr

`SDL2main.a` contains the entry point for platforms that require it (e.g. Windows, PS2, psp, ...
What changed in the latest SDL2 releases is that linking to `${SDL2_LIBRARIES}` now requires you to define SDL_main somewhere.
Usually, SDL replaces the `main` entry method with `SDL_main`, using a macro.
Previous releases of SDL2 assigned something like `-lmingw32 libSDL2main.dll.a libSDL2.a` to `SDL2_LIBRARIES`, which we have now changed with targets.
The previous method becomes rapidly unmaintainable when considering a mix of shared and static libraries.

The error occurs here:
https://github.com/darktable-org/darktable/blob/a5fa576a7a3422d7771044f95e80431658473baa/src/libs/CMakeLists.txt#L106
Linking to `${SDL2_LIBRARIES}` means implicitly building a function, including main.

BUT, since this is a shared library, the entry main function is not present at all. Hence the error.
So instead, I propose to apply the following patch to link to `SDL2::SDL2` directly, which will not do anything entry-function-related.
```patch
--- src/libs/CMakeLists.txt
+++ src/libs/CMakeLists.txt
@@ -97,13 +97,13@@
   target_link_libraries (midi ${PORTMIDI_LIBRARY})
 endif()
 
-find_package(SDL2)
+find_package(SDL2 CONFIG REQUIRED)
 if(SDL2_INCLUDE_DIRS)
   add_definitions("-DHAVE_SDL")
-  include_directories(${SDL2_INCLUDE_DIRS})
+  #include_directories(${SDL2_INCLUDE_DIRS})
   set(MODULES ${MODULES} gamepad)
   add_library(gamepad MODULE "tools/gamepad.c")
-  target_link_libraries(gamepad ${SDL2_LIBRARIES})
+  target_link_libraries(gamepad SDL2::SDL2)
 endif()

if(BUILD_BATTERY_INDICATOR)
```
https://github.com/darktable-org/darktable/blob/a5fa576a7a3422d7771044f95e80431658473baa/src/libs/CMakeLists.txt#L97-L109

**Comment by kmilos** [comment]
Thanks for the explanation!

> If darktable is welcome to requiring the latest SDL2 release, this patch can be upstreamed.

What is the minimal release where the CMake config mode is available and SDL2::SDL2 target defined?

**Comment by madebr** [comment]
It's only in the latest SDL2 release we made it available in ALL releases (including autotools, pre-built MSVC/MinGW releases).
So it would be requiring SDL2 from last week...

On the other hand, it looks like darktable [does not provide a `FindSDL2.cmake` itself](https://github.com/darktable-org/darktable/tree/master/cmake/modules).
So it does require an SDL release providing `SDL2Config.cmake` or some user providing `FindSDL2.cmake`.
By looking at the git history, it looks like starting from 2.0.12, cmake config files including targets were installed.
Starting from 2.0.6, CMake config files were installed, but not in all cases targets are available.

Maybe drop the `CONFIG`. This allows people to create their own `FindSDL2.cmake` cmake module.

**Comment by kmilos** [comment]
Thanks - I think I'll just check for `if(TARGET SDL2::SDL2)` then, otherwise leave the old code.

**Comment by madebr** [comment]
That seems reasonable!

**Comment by madebr** [comment]
SDL2 2.24.1 has just been released containing a fix, which should make the patch not needed anymore.
