### ISSUE TITLE
Optimization levels above -O0 break setting & getting extern thread_local variables

### ISSUE THREAD

**Issue by BlueCannonBall** [msys2/MINGW-packages#12877]
### Description

Setting or getting thread_local variables causes a segmentation fault if the program is compiled at an optimization level above -O0.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19044.1766]

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

The program should exit successfully

### Actual behavior

The program segfaults upon trying to set or get thread_local variables.

### Repro steps

1. Create 3 files: main.cpp, test.hpp, and test.cpp
2. In test.hpp, declare an extern thread_local variable
3. In test.cpp, define that variable
4. In main.cpp, include test.hpp and try operating on that variable
5. Compile with any optimization level above -O0
6. Run the program

### Are you willing to submit a PR?

Yes, though I do not know my way around the source code of GCC or mingw.

**Comment by BlueCannonBall** [comment]
Upstream bug report: https://sourceforge.net/p/mingw-w64/bugs/947/

**Comment by MehdiChinoune** [comment]
Your MSYS2 is not up-to-date, You are using GCC 11.2.0

Please show source code in repro steps.

**Comment by MehdiChinoune** [comment]
Couldn't reproduce with GCC 12.2.0.

Please don't check something you haven't verified!

**Comment by BlueCannonBall** [comment]
> Your MSYS2 is not up-to-date, You are using GCC 11.2.0
> 
> Please show source code in repro steps.

Interesting. I did not think that in the past few days GCC 12 would become available. I'll check for real next time.

**Comment by MehdiChinoune** [comment]
> Interesting. I did not think that in the past few days GCC 12 would become available. I'll check for real next time.

It was available since months.

We updated GCC to
11.3.0 on April 22
12.1.0 on May 20
12.2.0 on August 19

**Comment by BlueCannonBall** [comment]
That can't be right unless MinGW comes with an old version or something went wrong during installation. Could be because I had less than a gigabyte of available space after I installed MinGW and now I have over 10 GB. Either way though, I can't reproduce the issue anymore.

**Comment by MehdiChinoune** [comment]
Because you didn't update MSYS2 databases before installing packages, So pacman used the outdated databases and download the old packages.

**Comment by BlueCannonBall** [comment]
Oh, I see. Thank you for all the help.
