### ISSUE TITLE
[kimageformats-qt5] enable JPEG XL plug-in

### ISSUE THREAD

**Issue by novomesk** [msys2/MINGW-packages#12880]
Hello,

I think it would be enough to add `libjxl` dependency and the JXL Qt plug-in will be built too.

**Comment by novomesk** [comment]
I don't know how it works in ARCH.

On Gentoo, user must must enable corresponding use flags `avif eps heif jpegxl openexr` to enable compilation of the specific plug-ins.

**Comment by Biswa96** [comment]
Optional dependency means that libjxl (and others) will not be installed automatically when kimageformats-qt5 is installing. Users have to install libjxl (and others) manually after that.

**Comment by novomesk** [comment]
Does it mean that `kimg_jxl.dll` would be installed via kimageformats-qt5 but it will not work until `libjxl.dll` and `libjxl_threads.dll` are installed via libjxl package?

**Comment by Biswa96** [comment]
Yes.

**Comment by novomesk** [comment]
If there is some message that user could consider installing those optional libraries, then it is OK for me.

**Comment by Biswa96** [comment]
After installing kimageformat-qt5, pacman will show a message like the following in terminal 

```
(1/1) installing mingw-w64-i686-kimageformats-qt5                        [#######################################] 100%
Optional dependencies for mingw-w64-i686-kimageformats-qt5
    mingw-w64-i686-karchive-qt5>=5.97.0: plugin for Krita and OpenRaster images [installed]
    mingw-w64-i686-libavif: AVIF format support [installed]
    mingw-w64-i686-libheif: HEIF format support [installed]
    mingw-w64-i686-libjxl: JPEG-XL format support [installed]
    mingw-w64-i686-openexr: EXR format support [installed]
```

**Comment by novomesk** [comment]
It is fine so.

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2958618052
