### ISSUE TITLE
[cmake] MSYS2 CMake version 3.24.1 doesn't find Boost libraries anymore

### ISSUE THREAD

**Issue by Mr-Rayman** [msys2/MINGW-packages#12897]
My MSYS2 installation based on clang64 hasn't changed. Starting with recent updates to version 3.24 cmake doesn't find my MSYS2 boost libraries anymore.  Running version 3.23 in the same environment is fine and the boost libraries are beeing found.

All the boost libraries are available in my MSYS2 installation, see screenshot attached.
See output of cmake 3.24.1 and failure to find boost attached.

[cmake_findboost_output.txt](https://github.com/msys2/MINGW-packages/files/9473697/cmake_findboost_output.txt)
[CMakeError.log](https://github.com/msys2/MINGW-packages/files/9473699/CMakeError.log)
[CMakeOutput.log](https://github.com/msys2/MINGW-packages/files/9473700/CMakeOutput.log)

![libboost_available](https://user-images.githubusercontent.com/54250320/188021871-75121ece-c0b7-457e-9b0f-f6e8fb423e14.PNG)

**Comment by Biswa96** [comment]
Please provide a minimal sample CMakeLists.txt file to reproduce the issue.

**Comment by MehdiChinoune** [comment]
CMake is used to build many packages that depends on boost, and It finds them without any issue.
After we updated boost to 1.80 we patched CMake to support it.

**Comment by MehdiChinoune** [comment]
It seems that the issue comes from https://github.com/emweb/wt/blob/master/cmake/WtFindBoost.txt

A minimal example works perfect:
```CMake
cmake_minimum_required(VERSION 3.16)
project(test CXX)

add_executable(main main.cpp)

find_package(Boost REQUIRED filesystem program_options thread)
```

```
$ cmake -Bbuild/clang
-- Building for: Ninja
-- The CXX compiler identification is Clang 14.0.6
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Programs/msys64_test/clang64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Boost: D:/Programs/msys64_test/clang64/include (found version "1.80.0") found components: filesystem program_options thread chrono atomic
-- Configuring done
-- Generating done
```

Without a minimal reproducer we could do nothing.

**Comment by Mr-Rayman** [comment]
Thank you very much! Over the weekend I wasn't fast enough to provide a minimal sample. The minimal sample posted by MedDiChinoune yesterday works on my system. So the error might be in the Wt (Web Toolkit) package WtFindBoost.

The source code package Wt 4.8.0 for compilation with CMake environment can be downloaded here:
https://github.com/emweb/wt/releases
But I will inform the Wt team separately about this.

**Comment by Mr-Rayman** [comment]
Thank you very much! Over the weekend I wasn't fast enough to provide a minimal sample. The minimal sample posted by MedDiChinoune yesterday works on my system. So the error might be in the Wt (Web Toolkit) package WtFindBoost.

The source code package Wt 4.8.0 for compilation with CMake environment can be downloaded here:
https://github.com/emweb/wt/releases
But I will inform the Wt team separately about this.
