### ISSUE TITLE
PIP build error for any package

### ISSUE THREAD

**Issue by milen-prg** [msys2/MINGW-packages#12961]
### Description

I have mingw64 python3 and several its packages from the msys repository, but:
Trying to install other python package with pip in standard way, always finishes with build error, failed installation.

for example:
pip install --upgrade pygame
ot
pip install --upgrade vpython
etc.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19044.1889]

Windows 10 Pro 64bit

All updated!

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

expect
successful python package adding
 

### Actual behavior

failed build, errors

### Repro steps

command from mingw64 command prompt:

pip install --upgrade pygame

finish with error

**Comment by Biswa96** [comment]
> Trying to install other python package with pip in standard way, always finishes with build error, failed installation

This is an expected behavior. "C extensions are not compatible with the official CPython, which means pip can't use binary wheels from PyPI and packages have to be build when installing them."[^1]

[^1]: https://www.msys2.org/docs/python/
