### ISSUE TITLE
Add [quassel-core]

### ISSUE THREAD

**Issue by SonaliBendre** [msys2/MINGW-packages#12967]
### Package name

quassel-core

### Brief description of package

Next-generation distributed IRC client - core only

### URL for package's homepage

https://archlinux.org/packages/community/x86_64/quassel-core/

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
It is already available, see https://packages.msys2.org/base/mingw-w64-quassel

**Comment by SonaliBendre** [comment]
> It is already available, see https://packages.msys2.org/base/mingw-w64-quassel

No dude, thats quassel-mono+client+core. I Want quassel-core only so need to build with this flags 
```
-DCMAKE_BUILD_TYPE="Release" \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DWANT_CORE=ON \
	-DWANT_MONO=OFF \
	-DWANT_QTCLIENT=OFF \
	-DWITH_KDE=OFF
```

**Comment by Biswa96** [comment]
Understood. You want split packages. Let me see how it goes.

**Comment by MehdiChinoune** [comment]
> No dude, thats quassel-mono+client+core. I Want quassel-core only so need to build with this flags

Could elaborate why? Do you encounter any issue when using the whole `quassel` package or you just want a package with less size.

**Comment by SonaliBendre** [comment]
> > No dude, thats quassel-mono+client+core. I Want quassel-core only so need to build with this flags
> 
> Could elaborate why? Do you encounter any issue when using the whole `quassel` package or you just want a package with less size.

I want a package with less size. I don't need the gui client because I use android app. I only need quassel-core which is cli only

**Comment by SonaliBendre** [comment]
Can you package it also? https://aur.archlinux.org/packages/smuxi-server-git
Only smuxi-server not smuxi-gnome-frontend

**Comment by MehdiChinoune** [comment]
> > > No dude, thats quassel-mono+client+core. I Want quassel-core only so need to build with this flags
> > 
> > 
> > Could elaborate why? Do you encounter any issue when using the whole `quassel` package or you just want a package with less size.
> 
> I want a package with less size. I don't need the gui client because I use android app. I only need quassel-core which is cli only

I don't think this is a valid reason to create a new package.
We all need some packages with less size. Personally I asked before to minimize packages size by disabling static libraries or split them.
Some packages were built with some extra features that requires extra-dependencies => more size. We could do nothing about that.
