### ISSUE TITLE
Bug(?) with Update Request template

### ISSUE THREAD

**Issue by brisingraerowing** [msys2/MINGW-packages#12997]
### Description

The Update request template has a text area for the new version number, and a single line input for the other information. I think those should be swapped, as a text area is overkill for a version number, and more space is needed for additional info.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

N/A (Repo issue)

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

N/A

### Actual behavior

N/A

### Repro steps

N/A

**Comment by Biswa96** [comment]
Feel free to create a pull request with the required changes.
