### ISSUE TITLE
[Sed] update to 4.8

### ISSUE THREAD

**Issue by brisingraerowing** [msys2/MINGW-packages#12996]
### Package name

Sed

### New version number

4.8

### Other information that may be useful

Current patch obsolete, need to remove gnulib-tests from SUBDIRS in makefile.

### Are you willing to submit a PR?

Not sure how to actually create a patch, so no.

**Comment by Biswa96** [comment]
I have added a pull request to update the package. The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/3020406845
