### ISSUE TITLE
[mingw gcc]: __builtin_memcpy() offset is out of the bounds

### ISSUE THREAD

**Issue by igagis** [msys2/MINGW-packages#13104]
### Description

Recently, my build started to fail with the following errors:
```
error: 'void* __builtin_memcpy(void*, const void*, long long unsigned int)' offset [16, 19] is out of the bounds [0, 16] of object '<anonymous>' with type 'r4::matrix<int, 2, 2>' [-Werror=array-bounds]
```

See full build log here:
https://github.com/igagis/r4/actions/runs/3164166676/jobs/5152269889#step:4:11

This looks like a problem in the compiler.
No such errors happen when building on other environments (linux, macos) using different compilers (gcc, clang).

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

 Microsoft Windows Server 2022
  10.0.20348

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

builds without erros

### Actual behavior

there are compiler errros

### Repro steps

run the build described by github workflow of https://github.com/igagis/r4 repo.
This repo contains minimal producer example.

**Comment by MehdiChinoune** [comment]
Please, show a minimal reproducer. Don't expect other people to do your job!

**Comment by igagis** [comment]
is this fixed?

**Comment by MehdiChinoune** [comment]
No, I have closed it because you didn't provide a minimal reproducer.

**Comment by igagis** [comment]
I didn't have time to do it yet

**Comment by MehdiChinoune** [comment]
Reopen the issue when you could provide a minimal reproducer.

**Comment by igagis** [comment]
I can't reopen it, there's no such button here.

**Comment by MehdiChinoune** [comment]
I will reopen it when you provide a minimal reproducer.

**Comment by igagis** [comment]
@MehdiChinoune I have updated the bug description with minimal reproducing example. Please reopen the bug.

**Comment by igagis** [comment]
@MehdiChinoune perhaps remove the `needinfo` label from the issue?

**Comment by Biswa96** [comment]
gcc has been updated to 13.1.0. Is this issue still reproducible?

**Comment by igagis** [comment]
no, not reproducible, looks like it is fixed now. Closing the issue, thanks!
