### ISSUE TITLE
llvm-config returns build time path for libzstd

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#13108]
```console
$ llvm-config.exe --link-static --system-libs
-lpsapi -lshell32 -lole32 -luuid -ladvapi32 -lpthread -lz D:/a/msys64/ucrt64/bin/libzstd.dll -lxml2
```

This breaks meson tests: https://github.com/mesonbuild/meson/pull/10816#issuecomment-1248725385

With 14.0.6 the output was:

```console
$ llvm-config.exe --link-static --system-libs
-lpsapi -lshell32 -lole32 -luuid -ladvapi32 -lpthread -lz -lxml2
```

The source of that value is the `LLVM_SYSTEM_LIBS` macro

**Comment by mstorsjo** [comment]
I'm not very familiar with the cmake code here (I didn't dive in and try to see what's going on here), but there's been some recent discussion on `LLVM_SYSTEM_LIBS`, including zstd, at https://reviews.llvm.org/D132799. (There, I had the opposite experience; `LLVM_SYSTEM_LIBS` did contain `-lzstd` even if that wouldn't be found, while the full build time path would have been preferred.)

**Comment by eli-schwartz** [comment]
Full build time paths must NEVER EVER be mandated as the only way to find a dependency.

There are too many ways for it to not be the same as the install time path. MSYS2 demonstrates only one way for this to happen, there are others.

It's a (very) crude hack to accommodate people with broken toolchains that install multiple versions of software all jumbled together and don't explicitly add the non-default ones to the dependency lookup path *when desired*, but do so unconditionally.

> CMake manages to find a custom-installed libzstd in a nondefault location (`/home/linuxbrew/.linuxbrew/lib/libzstd.so.1.5.2`),

CMake should simply not do that unless explicitly told to. :p
