### ISSUE TITLE
[binutils] gprof does not produce any result

### ISSUE THREAD

**Issue by felixaszx** [msys2/MINGW-packages#13102]
### Description

gmon.out does not contain any profiling information with -pg flag.
I am sure that -pg is used for both compiling and linking. 

### Verification

- [x] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19044.2006]
a.k.a Windows 10 21H2

### MINGW environments affected

- [X] MINGW64
- [X] UCRT64
- [x] CLANG64
- [ ] MINGW32
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

gprof aaa.exe gmom.out

should provide profiling information

### Actual behavior

profiling information is none

### Repro steps

1.write any source file aaa.cpp

2.compile with command: ```g++ aaa.cpp -o aaa.exe -pg```

3;Run the program and ```gmon.out``` is generated

4.use command ```gprof aaa.exe gmon.out```

5.some information will be output to console, but do not include profiling information

**Comment by mayd** [comment]
Duplicate of #8503

**Comment by oltolm** [comment]
`-pg` alone is not enough `-no-pie` is necessary as well, see https://stackoverflow.com/questions/42620074/gprof-produces-empty-output.
