### ISSUE TITLE
Add pre-commit

### ISSUE THREAD

**Issue by winterz** [msys2/MINGW-packages#13111]
### Package name

python-precommit

### Brief description of package

can I get a precommit package for mingw python?

in response to the problems I'm encountering with https://github.com/msys2/msys2.github.io/issues/221
it would be nice to have a formal package for pre-commit that uses mingw python

### URL for package's homepage

https://github.com/pre-commit/pre-commit

### Provide a basic test case to validate the package's functionality.

% pacman -S $MINGW_PACKAGE_PREFIX-python $MINGW_PACKAGE_PREFIX-python-pip $MINGW_PACKAGE_PREFIX-precommit
warning: mingw-w64-x86_64-python-3.10.7-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-python-pip-22.2.2-1 is up to date -- reinstalling
error: target not found: mingw-w64-x86_64-precommit

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
It requires three other packages (https://github.com/pre-commit/pre-commit/blob/v2.20.0/setup.cfg#L25):
```
    cfgv>=2.0.0
    identify>=1.0.0
    nodeenv>=0.11.1
```
