### ISSUE TITLE
[highfive] package contains no files (recent changes probably don't install where they should)

### ISSUE THREAD

**Issue by eudoxos** [msys2/MINGW-packages#13116]
### Description

This is for 2.4.1 - might have been the case before (don't know) but the [change for 2.4.1](https://github.com/msys2/MINGW-packages/commit/a079445f42a63c63d6d07a8e9ecefe7af7552de6) (by @MehdiChinoune) did change some lines with install commands.

![image](https://user-images.githubusercontent.com/1029876/190876009-ba35a0f8-f483-4896-a934-8f8792f8fbb9.png)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

(gitlab CI, so not sure - sorry)

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Expected behavior

Package containing headers and other files as before

### Actual behavior

Package is empty

### Repro steps

Download the package e.g. [here](https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-highfive-2.4.1-1-any.pkg.tar.zst) and list contents - contains only metadata and LICENSE.

**Comment by brisingraerowing** [comment]
I mentioned this on the original commit, but the DESTDIR is typoed. It reads DESDIR instead (notice the missing T)
