### ISSUE TITLE
[protobuf] CMake-files not included in install

### ISSUE THREAD

**Issue by jonasbhjulstad** [msys2/MINGW-packages#13123]
### Description

Cmake files not installed to /mingw64/lib/cmake
(pkg-config files are correctly installed)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Edition	Windows 10 Pro N
Version	21H2
Installed on	‎12/‎02/‎2022
OS build	19044.2006
Experience	Windows Feature Experience Pack 120.2212.4180.0

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

Installation of the following files:
/mingw64/lib/cmake/protobuf/protobuf-config-version.cmake
/mingw64/lib/cmake/protobuf/protobuf-config.cmake
/mingw64/lib/cmake/protobuf/protobuf-module.cmake
/mingw64/lib/cmake/protobuf/protobuf-options.cmake
/mingw64/lib/cmake/protobuf/protobuf-targets-release.cmake
/mingw64/lib/cmake/protobuf/protobuf-targets.cmake

### Actual behavior

No installation of mentioned files

### Repro steps

pacman -S mingw-w64-x86_64-protobuf

**Comment by jonasbhjulstad** [comment]
Issue was solved by allowing pacman to overwrite existing files

pacman -S mingw-w64-x86_64-protobuf --overwrite '/mingw64/*'

**Comment by Biswa96** [comment]
List of files in protobuf package can be found online, here https://packages.msys2.org/package/mingw-w64-x86_64-protobuf?repo=mingw64
