### ISSUE TITLE
rust build failure with clang 15.0.0

### ISSUE THREAD

**Issue by IdrisKalp** [msys2/MINGW-packages#13192]
### Description

Rust build fails on clang64 base. Using official repo PKGBUILD.

Output:

https://wtools.io/paste-code/bFfo

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.25201.1000]

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

Builds

### Actual behavior

Fails due to probably API mismatch

### Repro steps

1. Upgrade packages
2. Start build via makepkg

**Comment by Biswa96** [comment]
Try to use `makepkg-mingw` instead of `makepkg`.

**Comment by IdrisKalp** [comment]
> makepkg-mingw

Problem persists.

**Comment by mati865** [comment]
Support for LLVM 15 is added in Rust 1.64 which will be released on 22/09/2022.
