### ISSUE TITLE
[clang] update to 15.0.1

### ISSUE THREAD

**Issue by mobius217** [msys2/MINGW-packages#13195]
### Package name

clang

### New version number

15.0.1

### Other information that may be useful

https://discourse.llvm.org/t/llvm-15-0-1-released/65380
https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.1

**Comment by lazka** [comment]
Any particular fix listed there that you'd like to see?

**Comment by mobius217** [comment]
> Any particular fix listed there that you'd like to see?

[Clang] Fix crash in coverage of if consteval. (3a08ad21ce89)
https://github.com/llvm/llvm-project/commit/3a08ad21ce89174f4ecdf1aad8ed7a161ef52a65

[clang] Skip re-building lambda expressions in parameters to consteval fns.
https://github.com/llvm/llvm-project/commit/1c73596d345481de957e5ccc0bedf1fb9d9f643a
