### ISSUE TITLE
Using PkgConfig to find grpc++ took a very long time

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#13207]
### Description

When I was working on #13208 I have observed that finding grpc took a long time on CLANG64
```
Wed, 21 Sep 2022 19:07:55 GMT
  -- Providing CMake module for gRPCAlt
Wed, 21 Sep 2022 19:28:18 GMT
  -- Found hdfs.h at: C:/_/mingw-w64-arrow/src/apache-arrow-9.0.0/cpp/thirdparty/hadoop/include/hdfs.h
```
That's doesn't happen on UCRT64:
```
Wed, 21 Sep 2022 19:07:00 GMT
  -- Providing CMake module for gRPCAlt
Wed, 21 Sep 2022 19:07:27 GMT
  -- Found hdfs.h at: C:/_/mingw-w64-arrow/src/apache-arrow-9.0.0/cpp/thirdparty/hadoop/include/hdfs.h
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19044.2006]

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [X] CLANG32
- [ ] CLANGARM64

### Expected behavior

To have the same behavior as the other environments

### Actual behavior

Take a long time, at first time I thought  it was hanging forever.

### Repro steps

1- Install the required packages:
```
$ pacboy -S grpc:p cc:p cmake:p pkgconf:p
``` 
2- Create a CMakeLists.txt file with this content:
```CMake
cmake_minimum_required(VERSION 3.16)
project(test CXX)
find_package(PkgConfig REQUIRED)
pkg_check_modules(grpc_PC grpc++ REQUIRED)
```
3- Configure the project:
```
$ cmake -Bbuild
-- Building for: Ninja
-- The CXX compiler identification is Clang 15.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Programs/msys64_test/clang64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: D:/Programs/msys64_test/clang64/bin/pkg-config.exe (found version "1.8.0")
-- Checking for module 'grpc++'
--   Found grpc++, version 1.48.1
```

**Comment by MehdiChinoune** [comment]
Is it because abseil-cpp has static libraries on CLANG* environments?
I have to build abseil as static libraries on UCRT64 and see.

**Comment by Biswa96** [comment]
Agree, I can reproduce the issue. If I narrow it down I can see `pkg-config.exe --cflags-only-I grpc++` command is actually taking the time. The `Requires` field in grpc++.pc has billions entries.

**Comment by MehdiChinoune** [comment]
`pkg-config -libs` doesn't take much time. It's the `-cflags` that take much time.

**Comment by MehdiChinoune** [comment]
pkgconf is now at 1.9.5
