### ISSUE TITLE
[gtkmm-4.0][gtk4] example/filechooserdialog generates runtime assertion failures

### ISSUE THREAD

**Issue by swanah** [msys2/MINGW-packages#13270]
### Description

I built the gtkmm [filechooserdialog example](https://gitlab.gnome.org/GNOME/gtkmm-documentation/tree/master/examples/book/dialogs/filechooserdialog) in the mingw64 environment.

Running the executable leads to the following runtime messages on the console every time I close the dialog:

`(example.exe:6384): Gtk-CRITICAL **: 14:48:40.250: gtk_widget_dispose_template: assertion 'template != NULL' failed`

The example runs without this message on a linux box I briefly set up for testing.

Installed Versions:
mingw-w64-x86_64-gtkmm-4.0 4.8.0-1
mingw-w64-x86_64-cairomm-1.16 1.16.1-1
mingw-w64-x86_64-glibmm-2.68 2.72.1-1
mingw-w64-x86_64-gtk4 4.8.1-1
mingw-w64-x86_64-pangomm-2.48 2.50.0-1

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19044.2006]

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

no assertion failure

### Actual behavior

(example.exe:6384): Gtk-CRITICAL **: 14:48:40.250: gtk_widget_dispose_template: assertion 'template != NULL' failed
when closing the file chooser dialog.

### Repro steps

build the [example](https://gitlab.gnome.org/GNOME/gtkmm-documentation/tree/master/examples/book/dialogs/filechooserdialog) and run the resulting executable in MSYS2-MINGW64
click on of the buttons to open the file/folder chooser and close the dialog.

**Comment by Biswa96** [comment]
Would you like to re-check the [filechooserdialog example](https://gitlab.gnome.org/GNOME/gtkmm-documentation/tree/master/examples/book/dialogs/filechooserdialog) program please? I have tried that in my system and it works without any error. The gtkmm-4.0 and its dependencies were updated.
