### ISSUE TITLE
qt6-tools bug

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#13279]
### Description

cannot build current qt6-tools due to a missing const, fixed upstream it seems though https://bugreports.qt.io/browse/QTBUG-103930

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19044.2006]

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

no error atleast.

### Actual behavior

```
G:/mingw-w64-qt6-tools/src/qttools-everywhere-src-6.3.2/src/assistant/qlitehtml/src/container_qpainter.cpp: In constructor 'DocumentContainer::DocumentContainer()':
G:/mingw-w64-qt6-tools/src/qttools-everywhere-src-6.3.2/src/assistant/qlitehtml/src/container_qpainter.cpp:461:13: error: invalid new-expression of abstract class type 'DocumentContainerPrivate'
  461 |     : d(new DocumentContainerPrivate)
```

### Repro steps

makepkg-mingw -c -i --skippgp --nocheck

**Comment by Biswa96** [comment]
I can not reproduce the issue in MINGW64. That cpp file is compiled without any error, see

```
$ find . -name 'container_qpainter*'
./src/build-MINGW64/src/assistant/qlitehtml/src/CMakeFiles/qlitehtml.dir/container_qpainter.cpp.obj
./src/qttools-everywhere-src-6.3.2/src/assistant/qlitehtml/src/container_qpainter.cpp
./src/qttools-everywhere-src-6.3.2/src/assistant/qlitehtml/src/container_qpainter.h
./src/qttools-everywhere-src-6.3.2/src/assistant/qlitehtml/src/container_qpainter_p.h
```

**Comment by revelator** [comment]
well thats odd ? i get the exact same error the qt dev got when trying to build it, strangely the rest of qt6 builds without any problems.

**Comment by revelator** [comment]
hmm ok i found out where that error comes from it is located in litehtml/html.h and had this type virtual int					pt_to_px(int pt) const = 0; if i change it to virtual int					pt_to_px(int pt) = 0; it works.

**Comment by Biswa96** [comment]
New qt6-tools version 6.4.0 has been uploaded https://packages.msys2.org/base/mingw-w64-qt6-tools and it was built without any compiler error.

**Comment by revelator** [comment]
guess it was some leftovers from the older version which was changed in the new one.
thanks for looking into it though :).
