### ISSUE TITLE
[RFC] Recommend/Default to UCRT64 instead of MINGW64

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#13371]
This mainly means:

* [x] Starting a UCRT64 shell after the installer finishes -> https://github.com/msys2/msys2-installer/commit/1012614b7aee53f3dcf9ef76fdb9b5162bacd189
* [x] Using ucrt64 in examples in the docs and recommend it there -> https://github.com/msys2/msys2.github.io/commit/0ecd2cf22781a05c7bc2d0c1381ed63df7c9d17b
* [x]  Run package-grokker etc for ucrt64 -> https://github.com/msys2/MINGW-packages/commit/e6df55ca1c417dd541df783eb547deef9d259ece
* [x] Build source packages in an ucrt64 env -> https://github.com/msys2/msys2-autobuild/commit/9d582e19b17368bc18db181a095a71869aae3dc8
* [x] Release a new installer with the new defaults -> https://github.com/msys2/msys2-installer/releases/tag/2022-10-28
* [x] Using ucrt64 in the installation guide -> https://github.com/msys2/msys2.github.io/pull/227
* [x] Advertising the change in NEWS/on twitter etc. -> https://github.com/msys2/msys2.github.io/pull/228

What needs to be done first:

There are 11 packages not built for ucrt64 right now: https://packages.msys2.org/repos

* Figure out which packages
* Try to fix them
* ???

**Comment by MehdiChinoune** [comment]
For the package not available on UCRT64, if they are unbuildable with both MINGW64 and UCRT64 just drop them especially if they are too old or abandoned.

**Comment by jeremyd2019** [comment]
`{'mingw-w64-arm-none-eabi-newlib', 'mingw-w64-flexdll', 'mingw-w64-creduce', 'mingw-w64-julia', 'mingw-w64-usbview-git', 'mingw-w64-riscv64-unknown-elf-gcc', 'mingw-w64-arm-none-eabi-gcc', 'mingw-w64-riscv64-unknown-elf-newlib', 'mingw-w64-advancecomp', 'mingw-w64-dnscrypt-proxy', 'mingw-w64-globjects'}`

<details>
<summary>Python script to generate</summary>

```python
#!/usr/bin/env python

import re
import pacdb

pfxre = re.compile(r'^mingw-w64(?:-clang|-ucrt)?-(?:x86_64|i686|aarch64)-')

mingw64 = pacdb.mingw_db_by_name('mingw64')
ucrt64 = pacdb.mingw_db_by_name('ucrt64')


mingw64names = {pfxre.sub('mingw-w64-', pkg.name) for pkg in mingw64}

ucrt64names = {pfxre.sub('mingw-w64-', pkg.name) for pkg in ucrt64}

updates = mingw64names - ucrt64names


print(updates)
```
</details>

**Comment by Biswa96** [comment]
One liner

```sh
grep -r mingw_arch --include PKGBUILD | grep mingw64 | grep -v ucrt64 
```

**Comment by stahta01** [comment]
I am trying to build mingw-w64-arm-none-eabi-gcc, mingw-w64-arm-none-eabi-newlib, and mingw-w64-arm-none-eabi-binutils for UCRT64.

Tim S.

**Comment by MehdiChinoune** [comment]
dnscrypt-proxy: source is not available anymore, don't know why. They recommend to build dnscrypt-wrapper https://www.dnscrypt.org/#dnscrypt-server, but I don't know if it could be considered as replacement or not!
globjects: Couldn't be built in all envs, maybe we should try git!
creduce: same as globjects

**Comment by stahta01** [comment]
I am also trying to add UCRT64 support to 'mingw-w64-riscv64-unknown-elf-gcc' and 'mingw-w64-riscv64-unknown-elf-newlib'.

Tim S.

**Comment by wszqkzqk** [comment]
Will there be `ucrt32` to take the place of `mingw32`?

**Comment by stahta01** [comment]
The newlib PRs are #13404 and #13403 the GCC packages take so long that the build times out.
Once the changes to mingw-w64-arm-none-eabi-newlib and mingw-w64-riscv64-unknown-elf-newlib are in the repo I hope the GCC changes will run without timeout on the CI server.

Tim S.

**Comment by lazka** [comment]
> Will there be `ucrt32` to take the place of `mingw32`?

There are no plans for a `ucrt32` atm

**Comment by kmilos** [comment]
How about defaulting `MINGW_ARCH=ucrt64` in `makepkg-mingw` as well?

**Comment by lazka** [comment]
> How about defaulting `MINGW_ARCH=ucrt64` in `makepkg-mingw` as well?

hm, good point. I'm worried that this will break things though. There is already a warning printed that calling it in a way that makes it use the default is deprecated. https://github.com/msys2/MSYS2-packages/blob/390cd56562eca024dcf2164d9444e5aa7cf7c6a8/pacman/makepkg-mingw#L94

**Comment by lazka** [comment]
I think we can leave the two remaining packages as is for now (mingw-w64-julia, mingw-w64-usbview-git), they don't even build under MINGW32/64 right now.

The next steps would be to create a new installer and merge https://github.com/msys2/msys2.github.io/pull/227 and https://github.com/msys2/msys2.github.io/pull/228 (feedback on those PRs welcome)

The only known issue left is #13608, but we can look at that later.

**Comment by lazka** [comment]
All done now. If any related issues come up, please let us know, or create new issues.
