### ISSUE TITLE
Remove libssp / replace with dummy lib

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#13401]
As pointed out here: https://github.com/msys2/MINGW-packages/pull/13398#issuecomment-1270214458

**Comment by jeremyd2019** [comment]
There probably needs to be some sort of transition for the DLL, as existing binaries would still link to it.

**Comment by Biswa96** [comment]
Wouldn't only import lib and static lib be replaced with dummy files? Then there will be no issue as DLL are present, right?

**Comment by MehdiChinoune** [comment]
Packages to be rebuilt

- [ ] mingw-w64-spice
- [ ] mingw-w64-cjson
- [ ] mingw-w64-virt-viewer
- [ ] mingw-w64-mkvtoolnix
- [ ] mingw-w64-libotr
- [ ] mingw-w64-opus
- [ ] mingw-w64-libvirt
- [ ] mingw-w64-libdsm
- [ ] mingw-w64-v8
- [ ] mingw-w64-mxml
- [ ] mingw-w64-gtk-vnc
- [ ] mingw-w64-sed
- [ ] mingw-w64-starpu
- [ ] mingw-w64-libressl
- [ ] mingw-w64-flac
- [ ] mingw-w64-libgusb
- [ ] mingw-w64-tor
- [ ] mingw-w64-xapian-core
- [ ] mingw-w64-gcab
- [ ] mingw-w64-embree
- [ ] mingw-w64-vlc
- [ ] mingw-w64-inkscape

**Comment by lazka** [comment]
I've added a NEWS entry: https://www.msys2.org/news/#2022-10-10-libssp-is-no-longer-required feedback welcome.

**Comment by MehdiChinoune** [comment]
all packages were rebuilt.

**Comment by MehdiChinoune** [comment]
Remaining:
#13527 
#13528

**Comment by MehdiChinoune** [comment]
Shouldn't this issue be closed?

**Comment by lazka** [comment]
Yes, thanks for all the package updates.

Followup here https://github.com/msys2/MSYS2-packages/pull/3222 as suggested here https://github.com/msys2/MINGW-packages/issues/5803#issuecomment-1273777694
