### ISSUE TITLE
mingw-w64-opencl-icd should install /msys_env/usr/lib/pkgconfig/OpenCL.pc

### ISSUE THREAD

**Issue by CarterLi** [msys2/MINGW-packages#13524]
### Description

[opencl-icd](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-opencl-icd/PKGBUILD) should install OpenCL.pc but it doesn't, which makes pkg-config unable to find it.

The archlinux package [ocl-icd](https://archlinux.org/packages/extra/x86_64/ocl-icd/) does install it

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.22623.730]

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Expected behavior

`/msys_env/usr/lib/pkgconfig/OpenCL.pc` exists and `pkg-config OpenCL --cflags` works

### Actual behavior

`/msys_env/usr/lib/pkgconfig/OpenCL.pc` doesn't exist

### Repro steps

1. pacman -S mingw-w64-clang-x86_64-opencl-icd
2. pkg-config OpenCL --cflags

**Comment by mmuetzel** [comment]
ArchLinux and MSYS2 are packaging two different implementations of an OpenCL ICD loader.
ArchLinux packages an (older) implementation by independent developers:
https://github.com/OCL-dev/ocl-icd
MSYS2 packages the (more official) implementation by the Khronos Group (which is a group of industry partners with the goal of creating "royalty-free open standards for 3D graphics, Virtual and Augmented Reality, Parallel Computing, Machine Learning, and Vision Processing"):
https://github.com/KhronosGroup/OpenCL-ICD-Loader

The latter seems more actively developed. IIUC, it is also the "reference" implementation by the group that is defining those standards.
However, that implementation doesn't contain a pkg-config file.

You could probably open an issue upstream to ask if they'd consider adding one:
https://github.com/KhronosGroup/OpenCL-ICD-Loader/issues

**Comment by CarterLi** [comment]
Thanks for your information. Filed an issue upstream https://github.com/KhronosGroup/OpenCL-ICD-Loader/issues/187
