### ISSUE TITLE
Unexpected file conflict error during routine update

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#13534]
### Description

libssp from crt conflicts with libssp package, and pacman errors out on this instead of offering to remove libssp package.  I suspect there needs to be a `conflicts`/`replaces` libssp in crt-git?

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19044.2130]

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

Successful upgrade

### Actual behavior

```
error: failed to commit transaction (conflicting files)
mingw-w64-clang-x86_64-crt-git: /clang64/lib/libssp.a exists in filesystem (owned by mingw-w64-clang-x86_64-libssp)
mingw-w64-clang-x86_64-crt-git: /clang64/lib/libssp_nonshared.a exists in filesystem (owned by mingw-w64-clang-x86_64-libssp)
Errors occurred, no packages were upgraded.
```

### Repro steps

`pacman -Syuu`

**Comment by lazka** [comment]
oh, I guess because there is no libssp more in the repo without the conflicting files to update to. yeah we need conflict/replaces now.

**Comment by lazka** [comment]
I whish pacman would default to removing conflicting packages in case they are no longer in the repo..

**Comment by jeremyd2019** [comment]
Yep, that allowed the update to proceed as expected, removing libssp.
