### ISSUE TITLE
Add gnulib

### ISSUE THREAD

**Issue by lygstate** [msys2/MINGW-packages#13612]
### Package name

gnulib

### Brief description of package

gnulib provide so much functions that belongs glibc, can we provide it with mingw?

### URL for package's homepage

http://git.savannah.gnu.org/gitweb/?p=gnulib.git

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by mmuetzel** [comment]
@Biswa96 is right. That's not how gnulib works. It's not a standalone library or something similar that would make sense to package. Also, there aren't any released versions. There are different ways that projects can use gnulib. But all of them involve some form of bundling (part of) the source code provided by the gnulib project with their own sources.

**Comment by lygstate** [comment]
OK, gotcha.

**Comment by goyalyashpal** [comment]
[user:msys2 gnulib]: https://github.com/search?q=user%3Amsys2+gnulib&type=issues "user:msys2 gnulib"


coming here from github/search 🔍 : [user:msys2 gnulib]

**Comment by goyalyashpal** [comment]
* i was trying to compile on win10 a `c` language program written for linux. 
* it does `#include <sys/resource.h>` in the entry-point file
* i tried replacing it with `#include "sys_resource.in.h"` (by pasting this file in the directory of the project) but this spawned the following error:

<details><summary>Details</summary>
<p>

```
./sys_resource.in.h:18:1: error: expected identifier or '('
   18 | @PRAGMA_SYSTEM_HEADER@
      | ^
./sys_resource.in.h:22:10: error: extra tokens at end of #ifndef directive [-Werror,-Wextra-tokens]
   22 | #ifndef _@GUARD_PREFIX@_SYS_RESOURCE_H
      |          ^
      |          //
./sys_resource.in.h:24:5: error: invalid token at start of a preprocessor expression
   24 | #if @HAVE_SYS_RESOURCE_H@
      |     ^
./sys_resource.in.h:36:10: error: extra tokens at end of #ifndef directive [-Werror,-Wextra-tokens]
   36 | #ifndef _@GUARD_PREFIX@_SYS_RESOURCE_H
      |          ^
      |          //
./sys_resource.in.h:37:10: error: ISO C99 requires whitespace after the macro name [-Werror,-Wc99-extensions]
   37 | #define _@GUARD_PREFIX@_SYS_RESOURCE_H
      |          ^
./sys_resource.in.h:41:3: error: "Please include config.h first."
   41 |  #error "Please include config.h first."
      |   ^
./sys_resource.in.h:44:6: error: invalid token at start of a preprocessor expression
   44 | #if !@HAVE_SYS_RESOURCE_H@
      |      ^
./sys_resource.in.h:111:5: error: invalid token at start of a preprocessor expression
  111 | #if @GNULIB_GETRUSAGE@
      |     ^
```

</p>
</details> 

i am trying for several hours and can't figure out how to do it correctly,

* i did `git clone https://git.savannah.gnu.org/git/gnulib.git --depth=1` and then navigated to project directory and ran `gnulib-tool --import`, it showed error `cannot find .\configure.ac` as the project uses plain `Makefile` and i don't know autotools either
* the examples given in `gnulib\examples\hello-c-gnulib\` dir also contain the autotools files which flew over my head
* searching on the internet for "gnulib on windows [with mingw]" doesn't yield any meaningful result other than gnulib documentation

```console
$ # v~~~ gnulib dir      
$ ../gnulib/gnulib-tool --import
D:\Desktop_moved\CS50\gnulib\gnulib-tool.py: *** cannot find .\configure.ac - make sure you run gnulib-tool from within your package's directory
D:\Desktop_moved\CS50\gnulib\gnulib-tool.py: *** Stop.
```

so, are there any hints or helping vectors u may share to get the project building?

**Comment by mmuetzel** [comment]
You cannot include the .in.h files directly. They need to be preprocessed according to test results on the platform for which you are building.
Gnulib requires running some configure tests. Without it, it won't work.

For some documentation, see, e.g.: https://www.gnu.org/software/gnulib/manual/gnulib.html

**Comment by goyalyashpal** [comment]
> For some documentation, see, e.g.: https://www.gnu.org/software/gnulib/manual/gnulib.html

yeah, that doesn't help at all. i am trying to understand that and it feels written in a different language.

**Comment by goyalyashpal** [comment]
hi @mmuetzel and others

can u share the configuration file(s) required for this to work? 

i know this is not nice to ask for a ready made solution... but like, if this is a trivial task for u or u have it lying around already, then it would help a lot if u could share them.

**Comment by mmuetzel** [comment]
IIUC, your project doesn't use autotools currently (no `configure.ac`, no `Makefile.am`, ...). So, the first step to be able to integrate gnulib into your project would be to re-write its build system with autotools. See, e.g., https://www.gnu.org/software/gnulib/manual/gnulib.html#Initial-import.
Another important step would probably be to include `config.h` in all compilation units: https://www.gnu.org/software/gnulib/manual/gnulib.html#Source-changes
Then, find the modules that you need and add them to the `bootstrap.conf`: https://www.gnu.org/software/gnulib/manual/gnulib.html#Modules and subsequent chapters.

I'm probably missing some important steps (read the manual for more info). But overall this is a major change to your project. Nothing that could be done by adding a couple of files...

**Comment by goyalyashpal** [comment]
the steps u shared won't help as the project is to be used in an automated checking system, so, it has to be compatible with the existing build steps

will using cygwin help to run that project on my win pc?
