### ISSUE TITLE
leveldb lots of undefined references

### ISSUE THREAD

**Issue by Zipdox** [msys2/MINGW-packages#13659]
### Description

When I try to compile something with leveldb I get lots of undefined references. It worked before.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19044.1706]

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

It compiles

### Actual behavior

[msys2 leveldb errors.log](https://github.com/msys2/MINGW-packages/files/9832469/msys2.leveldb.errors.log)

### Repro steps

1. `git clone -b refactor git@gitlab.com:zipdox/librediscord.git`
2. Install [these dependencies](https://gitlab.com/zipdox/librediscord/-/blob/refactor/dependencies.md)
3. `make -j 4`

### Are you willing to submit a PR?

I don't know how to

**Comment by mmuetzel** [comment]
It looks like `gcc` is used to link C++ files. Does it work if you use `g++` in that step?

**Comment by Zipdox** [comment]
Hmmm that works, but why do I need to do that? I don't need to do that on Linux or MacOS.

**Comment by mmuetzel** [comment]
Not sure if this is the reason for why this isn't failing on Linux (or macOS): On Windows, symbols need to be resolved on link time. On Linux (and probably also on macOS), symbol resolution can be deferred to when the program is loaded afaict.

**Comment by Zipdox** [comment]
I found that this one also doesn't work in MSYS2: https://github.com/emnl/leveldb-c-example
It does on Linux.

**Comment by Biswa96** [comment]
leveldb does not have a shared library. Let me check it.

**Comment by Zipdox** [comment]
> leveldb does not have a shared library. Let me check it.

I beg to differ, at least on GNU/Linux.
![image](https://user-images.githubusercontent.com/42157341/197037234-0bbe5c1e-a988-4a80-8a75-e5e8dc835ddf.png)

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/3292398412

**Comment by Zipdox** [comment]
It appears to be working now :+1:
