### ISSUE TITLE
ImageMagick can't open files whose filename or filepath include diacritics

### ISSUE THREAD

**Issue by dustwanderer** [msys2/MINGW-packages#13658]
### Description

Hi,
I have installed ImageMagick from the [ucrt64 Repo](https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-imagemagick?repo=ucrt64).

This version of ImageMagick can't open files whose filename or filepath contain diacritics.

The [ImageMagick Windows binary release](https://imagemagick.org/archive/binaries/ImageMagick-7.1.0-51-Q16-HDRI-x64-dll.exe) can open files with diacritics in their names. Unfortunately, the Windows release lacks the FFT delegate, among other things.

Thank you for MSYS2 and its packages, and best regards.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.22000.1098]

### Expected behavior

`magick.exe identify páramo.jpg` should give information about the image "páramo.jpg".

### Actual behavior

`magick.exe identify páramo.jpg` outputs and error message: "identify: unable to open image 'páramo.jpg': No such file or directory @ error/blob.c/OpenBlob/3570."

### Repro steps

I open a bash shell.

I type `locale.exe`. The output is...
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=

I type `magick.exe identify moor.jpg`. It works.

I type `mv.exe moor.jpg páramo.jpg` to add a diacritic.

I type `magick.exe identify páramo.jpg`. I get the error message.

If I type `export LC_ALL="en_US.UTF-8"` and then try again, the problem persists.

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I have found the cause. The unicode entry point was disable for magick.exe in mingw environment. I shall add a pull request to fix this.
