### ISSUE TITLE
Pipe not Working

### ISSUE THREAD

**Issue by adam-grant-hendry** [msys2/MINGW-packages#13662]
### Description

First discovered in [MinGW bug report #2303](https://sourceforge.net/p/mingw/bugs/2303/), pipes seem to fail in certain circumstances in the bash that ships with Git for Windows:

### Example 1

```sh
$ x=$(echo a | grep a)
$ echo a=$x
```

**Expected Output:** `a=a`
**Actual Output:** `a=`

https://user-images.githubusercontent.com/59346180/197073522-7cd1b187-0ca0-4fa7-b5dd-af011c5e90bd.mp4

### Example 2

For reference, please see [`commitizen` PR #605](https://github.com/commitizen-tools/commitizen/pull/605)

```sh
$ poetry run python -m pydocstyle --convention=google --add-ignore=D1,D415 --match-dir='^(?![.]|venv).*'
```

**Expected Output:** _Runs and passes (no output)_
**Actual Output:** `'venv).*' is not recognized as an internal or external command, operable program or batch file.`

```sh
$ poetry run python -m pydocstyle --convention=google --add-ignore=D1,D415 --match-dir="^(?![.]|venv).*"
```

**Expected Output:** _Runs and passes (no output)_
**Actual Output:** `bash: ![.]: event not found`

https://user-images.githubusercontent.com/59346180/197074552-a5440d1b-366a-493b-b58c-5499dda12864.mp4

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

**OS:** _determined with `cmd.exe /c ver`_

```
Microsoft Windows [Version 10.0.19044.2006]
```

**Git:** _determined with `git --version`_

```
git version 2.36.1.windows.1
```

**Bash:** _determined with `uname`:_

    kernel-name: MINGW64_NT-10.0-19044
    kernel-release: 3.3.4-341.x86_64
    kernel-version: 2022-05-09 11:56 UTC
    machine: x86-64
    operating-system: Msys

### MINGW environments affected

- [x] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

Please see details in `Description`.

### Actual behavior

Please see details in `Description`.

### Repro steps

Please see details in `Description`.

### Are you willing to submit a PR?

If I know how to fix it, yes.

**Comment by sskras** [comment]
On my machine it works:
![image](https://user-images.githubusercontent.com/7887758/197077295-39951dcb-ee5e-43be-a9c5-d612999cb281.png)

My version looks 2 months later:
```
kernel-name: MINGW64_NT-10.0-19044
kernel-release: 3.3.5-341.x86_64
kernel-version: 2022-07-04 21:33 UTC
machine: x86-64
operating-system: Msys
```

**Comment by adam-grant-hendry** [comment]
@sskras Thank you for the quick reply!

Interesting...I also see this on my CI in GitHub Actions with `windows-latest` (i.e. Windows Server 2022), so `git` probably needs an update.

On my local machine, I updated Git to `2.36.1.windows.1 -> 2.38.1.windows.1` and can confirm `Example #1` works, but `Example #2` is still failing:

https://user-images.githubusercontent.com/59346180/197081718-7c84570e-a915-4b99-a0d3-8e8eed77e2e6.mp4

Is there a command that accepts a regex as a string we could test so I can narrow down whether the issue is with MinGW or the repo?

**Comment by jeremyd2019** [comment]
```bash
x=$(echo a | grep -E 'a|b')
echo x=$x
```

?  I suspect `poetry run` is not properly handling quoting/escaping somehow (maybe it's trying to use CMD rules for bash or vice-versa)

**Comment by adam-grant-hendry** [comment]
> `x=$(echo a | grep -E 'a|b')`
> `echo x=$x`

Ya, I can confirm the above works for me as expected.

> maybe it's trying to use CMD rules for bash or vice-versa

That's funny, I was thinking the exact same thing. If you run

```
$ poetry run python -m pydocstyle --convention=google --add-ignore=D1,D415 --match-dir='^(?![.]|venv).*'
```

in Command Prompt, you'll get the same error

```
'venv).*' is not recognized as an internal or external command, operable program or batch file.
```

but if you switch it with double-quotes it works, whereas Git Bash is outputting the strange error

```
bash: ![.]: event not found
```

When I first came across this issue, I was thinking it was a Command Prompt-related issue, which is why I tried switching to double-quotes.

**Comment by adam-grant-hendry** [comment]
It's definitely reading the `!` as history expansion, but if you turn it off with `set +H`, you get the original error:

```
'venv).*' is not recognized as an internal or external command, operable program or batch file.
```

so definitely something parsing-wise is going on...

**Comment by adam-grant-hendry** [comment]
Since GitHub `Discussions` doesn't link, here is the question I posted on the `poetry` repo: [`python-poetry/poetry` Discussion #6856](https://github.com/python-poetry/poetry/discussions/6856).

Glad updating MinGW solved the first problem. For the second, I'm leaning toward this being an issue on `poetry`'s end (particularly as I specify the `bash` shell in my CI scripts; not sure if that implies `MinGW`/`Git Bash` are run or a `WSL` variant as I've never used Windows Server 2022 locally).

Feel free to close and I can re-open if it turns out to be a `MinGW` problem.
