### ISSUE TITLE
CLANG64 Clang can't build LLVM?

### ISSUE THREAD

**Issue by 3oheicrw** [msys2/MINGW-packages#13667]
### Description

I'm trying to build mulle-clang-project with the CLANG64 environment.

https://github.com/mulle-cc/mulle-clang-project

Note: at the time of this writting, it's currently failed to build on the CLANG64 Shell.

The error is about missing of libgcc_s and libgcc:

```
Linking CXX shared library lib\clang\14.0.6\lib\windows\libclang_rt.asan_dynamic-x86_64.dll
FAILED: lib/clang/14.0.6/lib/windows/libclang_rt.asan_dynamic-x86_64.dll lib/clang/14.0.6/lib/windows/libclang_rt.asan_dynamic-x86_64.dll.a
cmd.exe /C "cd . && C:\Active\msys64\clang64\bin\c++.exe -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -ffunction-sections -fdata-sections -O3 -DNDEBUG  -m64 -nodefaultlibs -shared -o lib\clang\14.0.6\lib\windows\libclang_rt.asan_dynamic-x86_64.dll -Wl,--out-implib,lib\clang\14.0.6\lib\windows\libclang_rt.asan_dynamic-x86_64.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\clang_rt.asan-dynamic-x86_64.rsp  && cd ."
lld: error: unable to find library -lgcc_s
lld: error: unable to find library -lgcc
lld: error: unable to find library -lgcc_s
lld: error: unable to find library -lgcc
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 6.3.9600]

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

It should build out of the box like on MINGW64 environment.

### Actual behavior

I have no idea why it's looking for libgcc_s and libgcc.

### Repro steps

Same commands were used to build on CLANG64 environment. All of them failed with the same error.

https://gist.github.com/3oheicrw/b2cc0a3365354c915f1887175e44b595

### Are you willing to submit a PR?

It's out of my ability.

**Comment by mmuetzel** [comment]
Does setting `CC='clang'` and `CXX='clang++'` help?

**Comment by 3oheicrw** [comment]
> Does setting `CC='clang'` and `CXX='clang++'` help?

No. BTW cmake already correctly detected the compiler is Clang.

**Comment by mmuetzel** [comment]
> BTW cmake already correctly detected the compiler is Clang.

In the error message you quoted, it is using `C:\Active\msys64\clang64\bin\c++.exe`. I'm not familiar with LLVM's build system. But it might be that it infers from the compiler name which libraries it should link. Maybe, it is (erroneously) assuming that `c++` is a GCC compiler.

What is the error message with those environment variables being set?

**Comment by 3oheicrw** [comment]
> > BTW cmake already correctly detected the compiler is Clang.
> 
> In the error message you quoted, it is using `C:\Active\msys64\clang64\bin\c++.exe`. I'm not familiar with LLVM's build system. But it might be that it infers from the compiler name which libraries it should link. Maybe, it is (erroneously) assuming that `c++` is a GCC compiler.
> 
> What is the error message with those environment variables being set?

Here you are:

```
Linking CXX shared library lib\clang\14.0.6\lib\windows\libclang_rt.asan_dynamic-x86_64.dll
FAILED: lib/clang/14.0.6/lib/windows/libclang_rt.asan_dynamic-x86_64.dll lib/clang/14.0.6/lib/windows/libclang_rt.asan_dynamic-x86_64.dll.a
cmd.exe /C "cd . && C:\Active\msys64\clang64\bin\clang++.exe -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -ffunction-sections -fdata-sections -O3 -DNDEBUG  -m64 -nodefaultlibs -shared -o lib\clang\14.0.6\lib\windows\libclang_rt.asan_dynamic-x86_64.dll -Wl,--out-implib,lib\clang\14.0.6\lib\windows\libclang_rt.asan_dynamic-x86_64.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\clang_rt.asan-dynamic-x86_64.rsp  && cd ."
lld: error: unable to find library -lgcc_s
lld: error: unable to find library -lgcc
lld: error: unable to find library -lgcc_s
lld: error: unable to find library -lgcc
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by MehdiChinoune** [comment]
Could you show the cmake configuration output.

**Comment by 3oheicrw** [comment]
Update: the same error with vanilla llvm (https://github.com/llvm/llvm-project). I'm testing with llvm-project-llvmorg-14.0.6

**Comment by 3oheicrw** [comment]
> Could you show the cmake configuration output.

Here you are.

[foo.txt](https://github.com/msys2/MINGW-packages/files/9839045/foo.txt)

**Comment by MehdiChinoune** [comment]
Try passing these options to cmake:
```
-DCLANG_DEFAULT_RTLIB=compiler-rt
-DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON
-DCLANG_DEFAULT_UNWINDLIB=libunwind
```

**Comment by mati865** [comment]
LLVM requires you to pass `-DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON` if you want to build it without dependency on libgcc.
There is nothing to do on our side so closing this issue but you can report it upstream.
