### ISSUE TITLE
Automake is no longer generating CXXFLAGS for C++ projects, causing unexpected slowdowns

### ISSUE THREAD

**Issue by ThosRTanner** [msys2/MINGW-packages#13678]
### Description

Possibly related to https://github.com/msys2/MINGW-packages/issues/13448

I have an automake project. Up till the time I updated my install it was compiling C++ stuff with -g -O2 as it automatically set CXXFLAGS to this.

Since then, it has been compiling with an empty CXXFLAGS making debugging difficult and noticeably affecting performance of compiled programs.

I backed out to https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-autotools-2021.12.14-1-any.pkg.tar.zst.sig and lo and behold, CXXFLAGS got -g -O2 set.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19044.2130]

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

By default C++ programs built with automake should have debugging information and a reasonable level of optimisation, and CXXFLAGS should be set to -g -O2 in the generated Makefiles

### Actual behavior

CXXFLAGS is empty in the generated makefiles, there is no debugging information and programs run noticably slower than they ought.

### Repro steps

1. Take a project (e.g. https://gitlab.gnome.org/GNOME/pan) that uses automake
2. Run autoconf
3. Run `grep CXXFLAGS Makefile`. It should have `CXXFLAGS = -g -O2` + whatever the project defines. Currently it just has whatever the project defines.

**Comment by Biswa96** [comment]
Here is my output:

```
$ grep CXXFLAGS Makefile
CXXFLAGS = -g -O2 -mms-bitfields -Wreorder -Wzero-as-null-pointer-constant
```

**Comment by lazka** [comment]
Same here:

```console
$ ./autogen.sh
$ grep CXXFLAGS Makefile
CXXFLAGS = -g -O2 -mms-bitfields -Wreorder -Wzero-as-null-pointer-constant
```

**Comment by lazka** [comment]
> I backed out to https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-autotools-2021.12.14-1-any.pkg.tar.zst.sig and lo and behold, CXXFLAGS got -g -O2 set.

That is a meta package that doesn't have any content, so reverting shouldn't change anything in theory.

**Comment by ThosRTanner** [comment]
umf. i've moved it forward again and it's still working. I have no idea what changed >.<

I'm going to close this off under the circumstances. Sorry for that
