### ISSUE TITLE
pkg-config adds root system include path

### ISSUE THREAD

**Issue by loonycyborg** [msys2/MINGW-packages#13691]
### Description

pkg-config adds -IC:/msys64/mingw64/include at least for pango, this is root system include path. pkg-config is supposed to filter it away. In my build I autoconvert -I to -isystem to get rid of otherwise unfixable warnings from dependencies. -isystem causes compile to break if used with root system include path.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19045.2130] (Running in QEMU/KVM)

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

Root system include path shouldn't be returned by pkg-config unless --keep-system-cflags is passed.

### Actual behavior

pkg-config adds -IC:/msys64/mingw64/include when doing `pkg-config --cflags pango`

### Repro steps

$ pkg-config --cflags pango
-IC:/msys64/mingw64/include/pango-1.0 -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/glib-2
.0 -IC:/msys64/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64
/include/freetype2 -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/fribidi -IC:/msy
s64/mingw64/include/cairo -IC:/msys64/mingw64/include/lzo -IC:/msys64/mingw64/include/pixman-1

$ which pkg-config
/mingw64/bin/pkg-config

**Comment by mmuetzel** [comment]
That might be coming from the pkg-config file for gobject-2.0:
```
prefix=/mingw64
includedir=${prefix}/include
libdir=${prefix}/lib

Name: GObject
Description: GLib Type, Object, Parameter and Signal Library
Version: 2.74.0
Requires: glib-2.0
Requires.private: libffi >=  3.0.0
Libs: -L${libdir} -lgobject-2.0
Libs.private: -lintl
Cflags: -I${includedir}
```

I don't know how upstream could solve that in general. (The package might not be installed at the default prefix.) But maybe we could just remove `Cflags: -I${includedir}` here...

**Comment by loonycyborg** [comment]
Also I noticed that passing --dont-define-prefix makes that particular -I flag disappear. I wonder why that happens. Does pkg-config do own autofiltering that got broken when prefix is substituted?

**Comment by mmuetzel** [comment]
There are lots of package config files that contain that line.
I'm not sure if that is an error in those files.

Why are those `-I` flags converted to `-isystem` for you? *That* might be the real issue here...

See: https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html
> The -isystem and -idirafter options also mark the directory as a system directory, so that it gets the same special treatment that is applied to the standard system directories.
>
> If a standard system include directory, or a directory specified with -isystem, is also specified with -I, the -I option is ignored. The directory is still searched but as a system directory at its normal position in the system include chain. This is to ensure that GCC’s procedure to fix buggy system headers and the ordering for the #include_next directive are not inadvertently changed. If you really need to change the search order for system directories, use the -nostdinc and/or -isystem options.

**Comment by loonycyborg** [comment]
That's something I do on purpose because being in -isystem path makes gcc not show warnings from those third party headers, I can't fix them anyway and they can trip up -Werror. Now in particular glib seems to spam them. There's no issue doing this for linux builds, only problem on msys2 because of this wrong -I option that trips up this gcc issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129 . Most likely linux pkg-config just succeeds at stripping this -I flag away.

**Comment by mmuetzel** [comment]
I'm not sure it is always save to translate all `-I` to `-isystem`. Just because it happens to cause no issue for some platform distributions by some vendors doesn't necessarily mean it is supposed to work on all platforms.
A more portable "fix" would be to not mess with the output from pkg-config and build without `-Werror`.

**Comment by loonycyborg** [comment]
Well given `--keep-system-cflags` exists pkg-config is supposed to filter them away, and actually does so for msys2 if `--dont-define-prefix` is passed, so restoring this behavior for pkg-config would help all packages that use -isystem to get rid of warnings. Many projects insist on warning-free builds. Irrelevant warnings often make you miss real problems.

**Comment by mmuetzel** [comment]
Sorry. Got it now.
I don't know how pkg-config determines the default include paths. But it might be a relocation issue of `gcc`. At least for me, I get this (where the relevant directories seem to get ignored):
```
$ gcc -xc -E -v -
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gcc.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-12.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev4, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --disable-libstdcxx-debug --with-boot-ldflags=-static-libstdc++ --with-stage1-ldflags=-static-libstdc++
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Rev4, Built by MSYS2 project)
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
 C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/cc1.exe -E -quiet -v -iprefix C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/ -D_REENTRANT - -mtune=generic -march=x86-64 -dumpbase -
ignoring nonexistent directory "C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/include"
ignoring duplicate directory "C:/msys64/mingw64/lib/gcc/../../lib/gcc/x86_64-w64-mingw32/12.2.0/include"
ignoring nonexistent directory "D:/a/msys64/mingw64/include"
ignoring nonexistent directory "/mingw64/include"
ignoring duplicate directory "C:/msys64/mingw64/lib/gcc/../../lib/gcc/x86_64-w64-mingw32/12.2.0/include-fixed"
ignoring nonexistent directory "C:/msys64/mingw64/lib/gcc/../../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/include"
ignoring nonexistent directory "D:/a/msys64/mingw64/include"
#include "..." search starts here:
#include <...> search starts here:
 C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/include
 C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../include
 C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/include-fixed
End of search list.
```
I'm not sure where those `D:/a/msys64/mingw64/include` come from. Maybe that is from the build system?

**Comment by mmuetzel** [comment]
Ok. The `gcc` thing was probably a red herring.
I might have gotten one step further though. When manually setting `PKG_CONFIG_SYSTEM_INCLUDE_PATH` to the mixed Windows path, it is working:
```
$ PKG_CONFIG_SYSTEM_INCLUDE_PATH=$(cygpath -m /mingw64/include) pkg-config.exe --cflags pango
-IC:/msys64/mingw64/include/pango-1.0 -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/fribidi -IC:/msys64/mingw64/include/cairo -IC:/msys64/mingw64/include/lzo -IC:/msys64/mingw64/include/pixman-1
```
IIUC, the system include path is hard coded into the binary as `/mingw64/include`. It looks like that fails to literally match the Windows paths in the `-I` flags.

Is there some kind of (library) function that can be used by MinGW binaries (`pkgconf.exe` in this case) to convert from the hard-coded UNIX path to the mixed Windows path?

**Comment by mmuetzel** [comment]
I opened https://github.com/msys2/MSYS2-packages/pull/3259 with a proposal how that could be fixed.
