### ISSUE TITLE
kitemmodels qml plugin installed to the incorrect path

### ISSUE THREAD

**Issue by BLumia** [msys2/MINGW-packages#13698]
### Description

The qml plugin provided by `mingw-w64-x86_64-kitemmodels-qt5` installed to the incorrect path and file name.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.22000.1098]

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

The QML plugin should be installed to:

-  `/mingw64/share/qt5/qml/org/kde/kitemmodels`
 
instead of:

- `/mingw64/lib/qml/org/kde/kitemmodels/`

Also, `libitemmodelsplugin.dll` should remove the `lib` prefix, as `itemmodelsplugin.dll`.

### Actual behavior

The qml plugin was installed to `/mingw64/lib/qml/org/kde/kitemmodels/` which will cause it cannot be found by apps that rely on it:
`module "org.kde.kitemmodels" is not installed`

The `lib` prefix of the dll will cause the plugin could not be loaded:
`module "org.kde.kitemmodels" plugin "itemmodelsplugin" not found` if we move the plugin dir to the correct place

### Repro steps

Just see the file list of this package: https://packages.msys2.org/package/mingw-w64-x86_64-kitemmodels-qt5

If you want to reproduce the issue manually, you can clone https://github.com/KDE/kirigami-gallery , build it and try to run it. Building can be successed, the error messages provided above will be shown if you try to run it.

### Are you willing to submit a PR?

Maybe yes if I know how to fix it correctly :)

**Comment by BLumia** [comment]
> Just curious. How did you find that the patch should be in share directory?

I have a little experience developing a QML plugin for Linux and MSYS2 is uses very similar folder structure :)

A patch has been submitted, I only wrote some PKGBUILD for Arch Linux before and never wrote one for MSYS2 so please let me know if anything is wrong. btw the patch didn't fix the `lib` prefix issue, but it might be an upstream issue as well. I might take some time to investigate it tomorrow.

**Comment by Biswa96** [comment]
I can reproduce the issue. With the 'lib' prefixed plugin DLL, I get the following error while configuring kirigami-gallery.

```
-- qmlplugindump failed for org.kde.kitemmodels.
-- Could NOT find org.kde.kitemmodels-QMLModule (missing: org.kde.kitemmodels-QMLModule_FOUND)
```

Removing the 'lib' prefix from the DLL plugin name fixes that issue.

**Comment by Biswa96** [comment]
I found the fix. I have compare the kitemmodels cmake files with kactivities. In kactivities, CMakeLists.txt uses `ecm_add_qml_module()` function from ECMQmlModule.cmake. That function removes the 'lib' prefix from the plugin DLL name. So, I copy the logic to kitemmodels  and it fixes the issue.

Try to apply this patch in kitemmodules source directory.

```diff
--- a/src/qml/CMakeLists.txt
+++ b/src/qml/CMakeLists.txt
@@ -40,6 +40,10 @@
         KF5::ItemModels
 )
 
+if(MINGW)
+    set_target_properties(itemmodelsplugin PROPERTIES PREFIX "")
+endif()
+
 install(TARGETS itemmodelsplugin DESTINATION ${KDE_INSTALL_QMLDIR}/org/kde/kitemmodels)
 install(FILES qmldir DESTINATION ${KDE_INSTALL_QMLDIR}/org/kde/kitemmodels)
 ```

**Comment by Biswa96** [comment]
Would you mind if I upstream the changes to KDE? That would be my first baby step to KDE project.

**Comment by BLumia** [comment]
> Would you mind if I upstream the changes to KDE? That would be my first baby step to KDE project.

Oh, I actually submitted a patch earlier today to replace the current implementation to use `ecm_add_qml_module()` :joy: (patch is [here](https://invent.kde.org/frameworks/kitemmodels/-/merge_requests/49)).

But there is another similar issue which is also caused by `lib` prefix that maybe you can work on, see https://github.com/msys2/MINGW-packages/issues/7393 for the issue and https://invent.kde.org/frameworks/plasma-framework for upstream code. If you are willing to give it a try then I'm happy to help :)
