### ISSUE TITLE
[gcc] Latest 12.2.0-6 does not produce any output file if isl is not installed

### ISSUE THREAD

**Issue by cowo78** [msys2/MINGW-packages#13922]
### Description

If `mingw-w64-x86_64-gcc==12.2.0-6` from mingw64 repo but `mingw-w64-x86_64-isl==0.25-1` is not then GCC is not able to produce either object files or executable ones. Meaning that i.e. `gcc -c main.c` does not create any `main.o`. No error messages are shown.
If I run `strace -o log gcc -c main.c` then a windows linker popup says that `libisl-23.dll` is missing. I would suggest isl to be a dependency of gcc.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Versione 10.0.19043.1237]

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

gcc -c main.c should create a main.o

### Actual behavior

gcc -c main.c does NOT create ANY file.

### Repro steps

1. Repo mingw64
2. Make sure that isl is not installed
3. Craft a main.c like `int main(int, char*[]) {return 0;}`
4. Run `gcc -c main.c`
5. main.o is NOT created

**Comment by Biswa96** [comment]
mingw-w64-isl is a dependency of mingw-w64-gcc. Isn't it obvious that removing a dependency would break a program? See the package details here https://packages.msys2.org/package/mingw-w64-x86_64-isl?repo=mingw64

**Comment by MehdiChinoune** [comment]
That was the case since we start building shared isl (https://github.com/msys2/MINGW-packages/commit/44b0a126ce and https://github.com/msys2/MINGW-packages/commit/9f3ded2d)
But pacman Shouldn't let you remove mingw-w64-isl.

**Comment by MehdiChinoune** [comment]
Installing MSYS2 packages by other than pacman is not supported.
