### ISSUE TITLE
Add pymupdf

### ISSUE THREAD

**Issue by jointri** [msys2/MINGW-packages#13940]
### Package name

pymupdf

### Brief description of package

There are official python bindings for mupdf called pymupdf complete with documentation online. They should be available through msys2 install the pymupdf bindings.

### URL for package's homepage

https://github.com/pymupdf/PyMuPDF

### Provide a basic test case to validate the package's functionality.

Python is a wonderful language that can be extended further with other python packages. To complete the mupdf packages available on msys2, pymupdf should be available as well.

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Upstream does not support mingw environment. It is possible to modify the setup.py for mingw but need some effort. I would like to upstream the changes first.

**Comment by Biswa96** [comment]
Can you provide any step to test the python module?

**Comment by Biswa96** [comment]
The package is working fine in my system. Here are some output.

* Module loading

```
$ python
Python 3.10.8 (main, Nov  6 2022, 23:26:47)  [GCC UCRT 12.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
>>> print(fitz.__doc__)

PyMuPDF 1.21.0: Python bindings for the MuPDF 1.21.0 library.
Version date: 2022-11-08 00:00:01.
Built for Python 3.10 on win32 (64-bit).
```

* Loading a PDF

```
>>> doc = fitz.open("D:\Books\The_C_Programming_Language_2nd.pdf")
>>> doc.metadata['format']
'PDF 1.2'
>>> ^Z
```

The package will be available soon. Please report any issue if present.
