### ISSUE TITLE
CMake stopped working with MSYS2 paths

### ISSUE THREAD

**Issue by legends2k** [msys2/MINGW-packages#13958]
### Description

CMake used to accept paths like `/mingw64/include` and now it errors out saying

> CMake Error in CMakeLists.txt:
>  Imported target "PkgConfig::ncurses" includes non-existent path
>
>    "/mingw64/include"
>
>  in its INTERFACE_INCLUDE_DIRECTORIES.

**This used to work couple of weeks back.**  `git log` on all involved MINGW-packages:

* CMake
* pkgconf
* ncurses

showed only CMake was changed recently (2022 Nov 2).  `$MINGW_PACAKGE_PREFIX-ncurses` installs a `/mingw64/lib/pkgconfig/ncursesw.pc` which has had the following contents since 2021 Dec:

``` config
Cflags:  -D_XOPEN_SOURCE=600 -D_POSIX_C_SOURCE=199506L -I${includedir} -I/mingw64/include
```

So it was always giving out relative paths to `pkgconf`.  CMake, which used to accept relative paths, no longer seems to accept it.  Hence the error.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.22000.978]

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

CMake builds should work fine with MSYS2 include paths like `/mingw64/include`.  It shouldn't expect all build scripts to give full Windows path like the official Win32 CMake build does.

### Actual behavior

CMake errors out with

``` shell
-- Building for: Ninja
-- The CXX compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/apps/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: C:/apps/msys64/mingw64/bin/pkg-config.exe (found version "1.8.0")
-- Checking for one of the modules 'ncursesw'
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "PkgConfig::ncurses" includes non-existent path

    "/mingw64/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

### Repro steps

Here's a sample CMake script demonstrating the problem:

``` cmake
cmake_minimum_required(VERSION 3.14)

project(Hellow
  VERSION 0.0.1
  LANGUAGES CXX)

find_package(PkgConfig REQUIRED)
pkg_search_module(ncurses REQUIRED IMPORTED_TARGET ncursesw)

add_executable(hello main.cpp)  # main.cpp's contents can be anything
target_link_libraries(hello PRIVATE PkgConfig::ncurses)
```

Try to build it using CMake

``` shell
cmake -B build
```

### Are you willing to submit a PR?

Yes

**Comment by legends2k** [comment]
@MehdiChinoune I see that you've recently changed CMake's `PKGBUILD`.  Any clues on how this could have regressed?

**Comment by Biswa96** [comment]
The issue is in ncurses pkgconfig files, not in cmake. Let me check proper way to fix it.

**Comment by MehdiChinoune** [comment]
Sorry, I have deleted a comment by mistake

>@legends2k said:
>MehdiChinoune I see that you've recently changed CMake's PKGBUILD. Any clues on how this could have regressed?

**Comment by legends2k** [comment]
> The issue is in ncurses pkgconfig files, not in cmake. Let me check proper way to fix it.

However, I don't see any recent changes to ncurses' PKGBUILD.  CMake was building fine with ncurses a couple of weeks back.  It's a regression that happened in these two weeks.  The only changes I see are in CMake package.

**Comment by Biswa96** [comment]
Hi @legends2k, I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/3425597124. Please follow these steps:

1. Scroll down and download the correct artifact. It'll be a zip file.
2. Extract the package (.tar.zst) from zip file.
3. Install it with `pacman -U the-package-name.tar.zst` command.

**Comment by legends2k** [comment]
@Biswa96 Tested and building succeeded!

However, unrelated to this issue, the built binary, when run on mintty/MINGW64 errors out with

> Error opening terminal: xterm.

**Comment by mmuetzel** [comment]
> However, I don't see any recent changes to ncurses' PKGBUILD. CMake was building fine with ncurses a couple of weeks back. It's a regression that happened in these two weeks.

It might be that the following change exposed this error in the pkg-config file:
https://github.com/msys2/MSYS2-packages/pull/3259
