### ISSUE TITLE
can't lauch spyder after upgrading packages

### ISSUE THREAD

**Issue by lott999** [msys2/MINGW-packages#13960]
This is a duplicate of https://github.com/msys2/MSYS2-packages/issues/3288#issue-1441739671 but from what I see the spyder package lies in this repo

----
Hi,

I just updated my packages and I get the following when I try to launch spyder from the shell.

```
myuser@MYHOST UCRT64 ~
$ spyder
Could not exec D:\a\msys64\ucrt64\bin\pythonw.exe
```
but in my case MSYS2 is installed in C:\msys64

Here is the list of installed packages related to spyder
```$ pacman -Qs spyder
local/mingw-w64-ucrt-x86_64-python-pyls-spyder 0.4.0-2
    Spyder extensions for the python-lsp-server (mingw-w64)
local/mingw-w64-ucrt-x86_64-python-spyder 5.4.0-1
    The Scientific Python Development Environment (mingw-w64)
local/mingw-w64-ucrt-x86_64-python-spyder-kernels 2.4.0-1
    Jupyter Kernels for the Spyder console (mingw-w64)
```

**Comment by Biswa96** [comment]
There is a pending pull request which may fix the issue. Please wait for the fix.

**Comment by lazka** [comment]
should be fixed
