### ISSUE TITLE
Unbundle minizip-ng from OpenColorIO

### ISSUE THREAD

**Issue by kmilos** [msys2/MINGW-packages#14029]
It would seem [minizip-ng 3.0.x](https://github.com/zlib-ng/minizip-ng) is just an update of the existing [mingw-w64-minizip](https://packages.msys2.org/base/mingw-w64-minizip) package...

**Comment by MehdiChinoune** [comment]
Couldn't link ocio to minizip-ng because of symbols not exported https://github.com/zlib-ng/minizip-ng/issues/475

**Comment by MehdiChinoune** [comment]
Fixed in #14028
