### ISSUE TITLE
cmake error in clang32 for mingw-w64-dcmtk

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#14043]
```
  -- Looking for socket in socket - not found
  CMake Error at CMake/GenerateDCMTKConfigure.cmake:1433 (message):
    Exit code 0xc0000139
  -- Configuring incomplete, errors occurred!
  
  See also "C:/_/mingw-w64-dcmtk/src/build-CLANG32/CMakeFiles/CMakeOutput.log".
  Call Stack (most recent call first):
    CMakeLists.txt:52 (INSPECT_FUNDAMENTAL_ARITHMETIC_TYPES)
  
  
  See also "C:/_/mingw-w64-dcmtk/src/build-CLANG32/CMakeFiles/CMakeError.log".
  ==> ERROR: A failure occurred in build().
```

This only seems to happen in clang32.  https://github.com/jeremyd2019/MINGW-packages/actions/runs/3448053806/jobs/5754703669

**Comment by jeremyd2019** [comment]
This still fails the same way in 3.6.7-2

**Comment by raedrizqie** [comment]
I think maybe its a bug in cmake.. it detects clang32 as Win64-Windows

**Comment by revelator** [comment]
also causes openscenegraph to fail building :S if installed before compiling it, this seems to happen because it references test executables that do not exist in the build.
