### ISSUE TITLE
mingw-w64-python update to 3.11.0

### ISSUE THREAD

**Issue by MarioPossamato** [msys2/MINGW-packages#14094]
### Package name

mingw-w64-python

### New version number

3.11.0

### Other information that may be useful

I'm not sure what to put here.

### Are you willing to submit a PR?

No.

**Comment by lazka** [comment]
See https://github.com/msys2-contrib/cpython-mingw/issues/101

**Comment by Biswa96** [comment]
python was updated to 3.11.4 in this commit https://github.com/msys2/MINGW-packages/commit/d822c484c7e71069ac13916058edd21d3563152d
