### ISSUE TITLE
Add [libcpr/cpr]

### ISSUE THREAD

**Issue by Sniperq2** [msys2/MINGW-packages#14314]
### Package name

libcpr/cpr

### Brief description of package

libcpr is a wrapper around libcurl for easy using curl library.
It's like python requests but for C++ developers.

### URL for package's homepage

https://github.com/libcpr/cpr

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Hi @Sniperq2, I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/3599055746

**Comment by Sniperq2** [comment]
404

**Comment by Biswa96** [comment]
The cpr package is available now in pacman repository, see https://packages.msys2.org/base/mingw-w64-cpr. You can install the package with `pacman -S <pacakge-name>` command as usual.

**Comment by Sniperq2** [comment]
Ok. Build my own packages using PKGBUILD and makepkg.

Package works fine with clang64 and mingw64. Thank you a lot.
