### ISSUE TITLE
vapi files not available 

### ISSUE THREAD

**Issue by aatsoftware** [msys2/MINGW-packages#14329]
### Description

/mingw64/share/vala/vapi/template-glib-1.0.deps
/mingw64/share/vala/vapi/template-glib-1.0.vapi

not generating template-glib-1.0 

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 10 /11

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

generate error Package `template-glib-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories""

### Actual behavior

Package `template-glib-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories""

### Repro steps

NOthing

### Are you willing to submit a PR?

Yes

**Comment by Biswa96** [comment]
Can you provide sample code and steps to reproduce the issue?

**Comment by MehdiChinoune** [comment]
No reproducer!
