### ISSUE TITLE
C library function fwrite - odd behavior in CLANG64 and MINGW64 environments

### ISSUE THREAD

**Issue by emtneutrino** [msys2/MINGW-packages#14373]
### Description

The following program produces incorrect arr.bin files when compiled and run in the CLANG64 and MINGW64 environments:
```
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {
        uint8_t b[2];
        FILE *f;

        b[0] = 10;
        b[1] = 0x0A;
        f = fopen("arr.bin", "w+");
        fwrite(b, 1, 2, f);
        fclose(f);
        return 0;
}
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19045.2311]

### Expected behavior

`hexdump -C arr.bin` should display the following in the CLANG64 and MINGW64 environments:

00000000  0a 0a                                             |..|
00000002

### Actual behavior

`hexdump -C arr.bin` displays the following in the CLANG64 and MINGW64 environments:

00000000  0d 0a 0d 0a                                       |....|
00000004

### Repro steps

I updated MSYS and reproduced the following behavior.

The following program produces different arr.bin files when compiled and run in different environments:

filename: write.c
```
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {
        uint8_t b[2];
        FILE *f;

        b[0] = 10;
        b[1] = 0x0A;
        f = fopen("arr.bin", "w+");
        fwrite(b, 1, 2, f);
        fclose(f);
        return 0;
}
```
The program is compiled with the following command in each environment:
$ make write

I run the program in each environment:
$ ./write

I display the contents of file arr.bin in each environment:
$ hexdump -C arr.bin

In the CLANG64 and MINGW64 environments the following contents are displayed:
00000000  0d 0a 0d 0a                                       |....|
00000004

In the MSYS, MINGW32 and UCRT64 environments the following contents are displayed:
00000000  0a 0a                                             |..|
00000002

Something is going wrong in the CLANG64 and MINGW64 environments.  It seems that the value 0x0A is not written properly to the file.  It doesn't seem to have the same problem with other values that I've tested.  It's almost as if it is trying to substitute a line feed character with carriage return + line feed characters.

**Comment by mmuetzel** [comment]
Maybe, `fopen` is converting between codepages when a file is opened in text mode? The output in MINGW64 and CLANG64 would be consistent if the output is converted from ISO8859-1 to UTF-8.
Does it make a difference if you open the file in binary mode (e.g., with `f = fopen("arr.bin", "w+b");`)?
See also here:
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-170
> If `t` or `b` isn't given in mode, the default translation mode is defined by the global variable [_fmode](https://learn.microsoft.com/en-us/cpp/c-runtime-library/fmode?view=msvc-170). If `t` or `b` is prefixed to the argument, the function fails and returns `NULL`.

**Comment by jeremyd2019** [comment]
> Maybe, `fopen` is converting between codepages when a file is opened in text mode? The output in MINGW64 and CLANG64 would be consistent if the output is converted from ISO8859-1 to UTF-8. Does it make a difference if you open the file in binary mode (e.g., with `f = fopen("arr.bin", "w+b");`)? See also here: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-170

No code-page conversion needed.  Windows has always been that in 'text mode' it converts `\n` (`LF` `0x0A`) to `\r\n` (`CRLF` `0x0D 0x0A`) on writing and vice versa on reading.  This has been a source of considerable strangeness over the years, not least because the amount of data you can read via `fread` is different than the size of the file from `stat`.

**Comment by emtneutrino** [comment]
I've verified that using `fopen("arr.bin", "w+b")` fixes the issue in CLANG64 and MINGW64 environments, but is not necessary for MSYS, MINGW32 and UCRT64 environments.

**Comment by jeremyd2019** [comment]
> I've verified that using `fopen("arr.bin", "w+b")` fixes the issue in CLANG64 and MINGW64 environments, but is not necessary for MSYS, MINGW32 and UCRT64 environments.

That doesn't make any sense.  Are you sure you have toolchains installed for MINGW32 and UCRT64, and aren't just falling back to MSYS `/usr/bin/gcc`?  MSYS env is Cygwin, which tries to act more like UNIX and doesn't do that conversion

**Comment by emtneutrino** [comment]
> > I've verified that using `fopen("arr.bin", "w+b")` fixes the issue in CLANG64 and MINGW64 environments, but is not necessary for MSYS, MINGW32 and UCRT64 environments.
> 
> That doesn't make any sense. Are you sure you have toolchains installed for MINGW32 and UCRT64, and aren't just falling back to MSYS `/usr/bin/gcc`? MSYS env is Cygwin, which tries to act more like UNIX and doesn't do that conversion

Sorry, I don't know how to verify this.

**Comment by emtneutrino** [comment]
In the CLANG64 environment, using gcc to compile the program using `fopen("arr.bin", "w+")` creates a program that produces the correct file.  Using cc to compile creates a program that produces the extra 0x0D bytes.  `which gcc` produces `/usr/bin/gcc' and `which cc` produces `/clang64/bin/cc`

In the MINGW64 environment, using either compiler produces the extra 0x0D bytes. `which gcc` produces `/mingw64/bin/gcc` and `which cc` produces `/mingw64/bin/cc`.

**Comment by mmuetzel** [comment]
> No code-page conversion needed. Windows has always been that in 'text mode' it converts `\n` (`LF` `0x0A`) to `\r\n` (`CRLF` `0x0D 0x0A`) on writing and vice versa on reading.

Dou! 🤦That was too obvious. So, I had to come up with some winding explanation. 🤣

> In all other environments `which gcc` produces `/usr/bin/gcc` and `which cc` produces `/usr/bin/cc`.

That means you are falling back to using the MSYS2/Cygwin compiler instead of using a native one.

**Comment by emtneutrino** [comment]
After installing the UCRT64 toolchain, compiling the program with `fopen("arr.bin", "w+")` with gcc or cc produces a program that creates a file with 0x0D bytes.  `which gcc` produces `/ucrt64/bin/gcc` and `which cc` produces `/ucrt64/bin/cc`.  I'm assuming the same thing happens with the MINGW32 toolchain.

**Comment by emtneutrino** [comment]
I'm guessing this behavior is as designed and not a bug.  The "fix" is to add "b" to the file open mode.

**Comment by emtneutrino** [comment]
Another annoying behavior is that fwrite does not count the extra 0x0D bytes in the number of bytes written value that fwrite returns.

**Comment by alvinhochun** [comment]
It's all documented behaviour:

https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-170

> In text mode, carriage return-line feed (CRLF) combinations are translated into single line feed (LF) characters on input, and LF characters are translated to CRLF combinations on output. [...]
> If `t` or `b` isn't given in `mode`, the default translation mode is defined by the global variable [_fmode](https://learn.microsoft.com/en-us/cpp/c-runtime-library/fmode?view=msvc-170). [...]

https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fwrite?view=msvc-170

> If `stream` is opened in text mode, each line feed is replaced with a carriage return-line feed pair. The replacement has no effect on the return value.

**Comment by emtneutrino** [comment]
Closing issue because behavior is as designed.
