### ISSUE TITLE
Problems related with MSYS library

### ISSUE THREAD

**Issue by AlexUser97** [msys2/MINGW-packages#14376]
### Description

Problem related with installation of PyFrac package which is ise OpenBLAS and have to be installed via MSYS

In the process of installation I see this error. Which library of MSYS package should I install?

```
-- Configuring done
-- Generating done
-- Build files have been written to: /d/PyFrac/TI_Kernel
[ 77%] Building CXX object CMakeFiles/TI_elasticity_kernel.dir/src/AssemblyDDM.cpp.o
[ 88%] Building CXX object CMakeFiles/TI_elasticity_kernel.dir/src/Selfcorr.cpp.o
[100%] Linking CXX executable build/TI_elasticity_kernel.exe
/usr/lib/gcc/x86_64-pc-msys/11.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lopenblas: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/TI_elasticity_kernel.dir/build.make:209: build/TI_elasticity_kernel.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/TI_elasticity_kernel.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.14393]

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

The PyFrac should be installed

### Actual behavior

Issues in installation

### Repro steps

Steps to solve the issue:
1. Added libraries in CmakeLists.txt file

**Comment by Biswa96** [comment]
Please use mingw packages. msys and mingw packages should not be linked together. For the mingw compiler toolchain, run `pacman -S $MINGW_PACKAGE_PREFIX-toolchain` command.
