### ISSUE TITLE
No include path

### ISSUE THREAD

**Issue by Fribir45** [msys2/MINGW-packages#14462]
### Description

I did some programming years ago and tried to start anew with C++.

I installed mingw exactly as described and tried to compile a simple test program:

#include <stdio.h>
int main()
{
	printf("Hello World!\n");
	return 0;
}

I received the following response: see attache screenshot:

![Zwischenablage01](https://user-images.githubusercontent.com/119846263/205593158-b5ec0bea-2314-444e-9ccf-e640faabe79d.jpg)

I would appreciate any help!

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 10 Home
21H2
Build: 19044.2251
SerialN: R3048RXJ

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

MINGW 64 to compile a siple program

#include <stdio.h>
int main()
{
	printf("Hello World!\n");
	return 0;
}

### Actual behavior

I received this message:
![Zwischenablage01](https://user-images.githubusercontent.com/119846263/205594295-1b49d3b5-1b16-4a8d-84ed-8cb20e8d9b19.jpg)

### Repro steps

1. Download and install MINGW64
2. Try testprogram
#include <stdio.h>
int main()
{
	printf("Hello World!\n");
	return 0;
}

**Comment by Biswa96** [comment]
Use the ucrt64 terminal environment. Click on the ucrt64 icon in start menu then follow the steps from here https://www.msys2.org/

**Comment by Biswa96** [comment]
Do you have any other gcc mingw realtes toolchain in your system's PATH variable?

**Comment by Fribir45** [comment]
How should I check? (Sorry, but I am mainly a windows user, my times using command-lines are long past)

**Comment by Biswa96** [comment]
Provide the output of `echo %PATH%` command in command prompt. If the output contains any sensitive user information you can hide it with abcd like string.

**Comment by Fribir45** [comment]
See screenshot!
The output is (of course) in Geman and means : "The command "C\Program" is either spelled wrong or could not be found"
![Zwischenablage03](https://user-images.githubusercontent.com/119846263/205919304-aa0ec16b-e221-4849-8889-e6f2c958ea0d.jpg)

**Comment by Fribir45** [comment]
Sorry, I did not recognize echo to be the command!
![Zwischenablage04](https://user-images.githubusercontent.com/119846263/205921207-b106afd7-b0f3-4d06-81ff-0a9601967e26.jpg)

**Comment by Biswa96** [comment]
Does `where gcc` command show any path in command prompt?

**Comment by Fribir45** [comment]
See below

![Zwischenablage05](https://user-images.githubusercontent.com/119846263/205923903-f12a3b8b-73f0-4f04-8770-3699776bdf2d.jpg)

**Comment by Biswa96** [comment]
>  how do I remove this path?

This article may help https://www.howtogeek.com/787217/how-to-edit-environment-variables-on-windows-10-or-11/. 

> Is this correct?

Yes.

**Comment by Fribir45** [comment]
Sorry to be here again! 
Accessing the environment variable Path as described I get the following

![Zwischenablage06](https://user-images.githubusercontent.com/119846263/205930818-96f37a7d-9778-4294-a46c-885650e96a2f.jpg)

This seems to be much less than waht I got with the echo command. In particular there is no c:\FPC.... path!

**Comment by Fribir45** [comment]
Now gcc is not found at all!

![Zwischenablage08](https://user-images.githubusercontent.com/119846263/205940858-5cf47ef5-c233-40c4-bfea-58a942f22de1.jpg)

**Comment by Fribir45** [comment]
Maybe I should unistall the whole package and try a new installation?

**Comment by Biswa96** [comment]
If you have installed msys2 from the installer run the ucrt64 from Start menu, not from the command prompt.

**Comment by Biswa96** [comment]
That's a different way of using msys2 but it may not be easier for first time user.

**Comment by Fribir45** [comment]
Hello! 
Sorry to be here again!
I now uninstalled the whole package and cheched PATH for any msys2 related paths; there were none.
I then installed the package from the downloadpage exactly following the instructions.
For the result plese see the attached!
I would really appreciate any help!

![screen1](https://user-images.githubusercontent.com/119846263/206418649-189c4a1f-6156-4991-8007-c218a5984cfd.jpg)
![screen2](https://user-images.githubusercontent.com/119846263/206418680-eb9e90f2-38b0-4155-961a-0fe727b088f5.jpg)
![screen3](https://user-images.githubusercontent.com/119846263/206418700-6af40bcd-70f5-407a-b70f-b8539a27a5bb.jpg)
![screen4](https://user-images.githubusercontent.com/119846263/206418715-bda0ce73-60ff-4d69-9779-4ead0f426ab0.jpg)
![screen5](https://user-images.githubusercontent.com/119846263/206418753-407b13d8-3a45-4cd9-a31d-69f8780510c6.jpg)
![screen6](https://user-images.githubusercontent.com/119846263/206418766-e6a67cd7-a9cc-4597-be36-4dea54a428fd.jpg)
![screen7](https://user-images.githubusercontent.com/119846263/206418780-12e05281-581e-4cca-a1f1-c2fe211d128c.jpg)

**Comment by mmuetzel** [comment]
The easiest for you might be to *not* use the Windows "Eingabeaufforderung" for compilation. Use the UCRT64 shell that you used for installing the compiler instead.
Just `cd` to the folder with the source file like you'd do in the Windows Command Prompt (i.e., `cd C:/Users/fried/Desktop`).
Or alternatively: The UCRT64 bash starts up in your `$HOME` folder by default. If you used the default settings during installation, that is `C:\msys64\home\fried` (where the last part is your Windows user name). Just save your source files in that folder and compile them there.

**Comment by MehdiChinoune** [comment]
not an issue.
