### ISSUE TITLE
mingw-w64-x86_64-qt5-declarative-5.15.7+kde+r274-1 breaks trivial QML program

### ISSUE THREAD

**Issue by mvzlb** [msys2/MINGW-packages#14466]
### Description

Running a simple QML program fails after upgrading `mingw-w64-x86_64-qt5-declarative` to `5.15.7+kde+r274-1`.

Downgrading to `mingw-w64-x86_64-qt5-declarative` to `5.15.7+kde+r257-1` makes `qmlscene` display the window again.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 6.3.9600]

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

`qmlscene` displays an empty window

### Actual behavior

`qmlscene` fails with a runtime loader error:

```
# qmlscene.exe hello.qml 
file:///C:/msys64/home/Mike/hello.qml:2 plugin cannot be loaded for module "QtQuick.Controls": Die Bibliothek C:\msys64\mingw64\share\qt5\qml\QtQuick\Controls.2\qtquickcontrols2plugin.dll kann nicht geladen werden: Die angegebene Prozedur wurde nicht gefunden.
```

### Repro steps

```
$ cat >> hello.qml 
import QtQuick 2.15
import QtQuick.Controls 2.15

Item {}
```
```
$ qmlscene hello.qml
```

**Comment by lazka** [comment]
Please try again now (after a `pacman -Suy`)
