### ISSUE TITLE
Scrolling through command history in GDB gives garbage output

### ISSUE THREAD

**Issue by alvinhochun** [msys2/MINGW-packages#14484]
### Description

Pressing up/down arrows in GDB to scroll through the command history in GDB gives something like this:

```
(gdb) 觠觠觠觢觢觢觠觠觠觠觢觢
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

10.0.19041.1415

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

The prompt should change to previous commands without garbage characters.

### Actual behavior

The prompt shows garbage characters.

### Repro steps

1. Run `gdb`
2. Enter a command (e.g. `bt`)
3. Press up and down arrows as many times as you like

**Comment by lazka** [comment]
Reverting to readline-8.2.001-2 seems to fix it here, so a regression in readline-8.2.001-2. @mmuetzel

**Comment by mmuetzel** [comment]
I didn't see those Asian characters. But the arrow keys didn't work for me either.

Could you please test with the build artifact from #14542 when it is ready?
