### ISSUE TITLE
HexChat plugins cannot compile without a global variable named "ph"

### ISSUE THREAD

**Issue by mcendu** [msys2/MINGW-packages#14579]
### Description

The following code fails to compile under GCC 12.2.0 as provided by MSYS2:

```c
#include <hexchat-plugin.h>

static hexchat_plugin *hexchat;

int hexchat_plugin_init(hexchat_plugin *handle, char **plugin_name,
		char **plugin_desc, char **plugin_version, char *arg)
{
	hexchat = handle;

	*plugin_name = "xyzzy";
	*plugin_desc = "Foos";
	*plugin_version = "1.bar";

	hexchat_print(hexchat, "Nothing happened.");
	return 1;
}
```

Here is `hexchat_print` as declared in the `hexchat-plugin.h`, for reference:

```c
void
hexchat_print (hexchat_plugin *ph,
	     const char *text);
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.22621.819]

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

The plugin would compile normally, no matter if the `hexchat_plugin` object was named `ph` or not.

### Actual behavior

For some reason, the GCC build requires the `hexchat_plugin` to be named `ph` and not anything else. Otherwise it fails with the following confusing message:

```console
$ gcc -c -o xyzzy.o xyzzy.c
In file included from xyzzy.c:1:
xyzzy.c: In function 'hexchat_plugin_init':
xyzzy.c:14:9: error: 'ph' undeclared (first use in this function)
   14 |         hexchat_print(hexchat, "Nothing happened.");
      |         ^~~~~~~~~~~~~
xyzzy.c:14:9: note: each undeclared identifier is reported only once for each function it appears in
```

### Repro steps

1. Install `mingw-w64-x86_64-gcc` and `mingw-w64-x86_64-hexchat`.
2. Copy the above code into a file.
3. Compile it with GCC.

### Are you willing to submit a PR?

No

**Comment by mcendu** [comment]
HexChat devs apparantly knows this issue (see <https://hexchat.readthedocs.io/en/latest/plugins.html#plugins-on-windows-win32>). I am not sure why &ndash; would changing this behavior break backwards compatibility? Closing as not planned.

**Comment by Biswa96** [comment]
> Caveat: plugins compiled on Win32 must have a global variable called ph

I think it is required for this weird macro in hexchat_plugin.h 🤦 

```c
#if !defined(PLUGIN_C) && (defined(WIN32) || defined(__CYGWIN__))
#ifndef HEXCHAT_PLUGIN_HANDLE
#define HEXCHAT_PLUGIN_HANDLE (ph)
#endif
#define hexchat_hook_command ((HEXCHAT_PLUGIN_HANDLE)->hexchat_hook_command)
...
```

**Comment by mcendu** [comment]
Yeah I noted the later windows-only macros. Probably related to quirks in the underlying OS (Windows).
