### ISSUE TITLE
skia missing modules directory

### ISSUE THREAD

**Issue by kezsoy** [msys2/MINGW-packages#14585]
### Description

Hi,
After installing mingw-w64-ucrt-x86_64-skia using pacman, I tried using skia in a cpp project. However I run into this error from g++

    C:/msys64/ucrt64/include/skia/include/core/SkColorSpace.h:14:10: fatal error: modules/skcms/skcms.h: No such file or directory
       14 | #include "modules/skcms/skcms.h"
         |          ^~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make: *** [Makefile:96: src/main.o] Error 1

It doesnt look like the modules directory is included in the pacman package. Could this be added to make skia work?

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.22621.963]

### Expected behavior

Skia to be included properly

### Actual behavior

g++ throws an error due to missing modules directory

### Repro steps

Download skia from
pacman -Sy mingw-w64-ucrt-x86_64-skia
There is no modules directory, so headers are missing

**Comment by Biswa96** [comment]
It seems that modules are not built. We'll look into that.

**Comment by kezsoy** [comment]
Thanks, a useful thread here too https://groups.google.com/g/skia-discuss/c/RAs9yedISpM

**Comment by kezsoy** [comment]
Looking at the skia build at https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-skia/PKGBUILD, the `package()` function looks like its not copying over some of the skia directories. Ive been comparing it to the skia build from jet-brians https://github.com/JetBrains/skia-pack/blob/main/script/archive.py, where `modules`, `third_party` and and `src` folders seem to be packaged

**Comment by Biswa96** [comment]
Would you like to test the packages from GitHub Actions artifacts here https://github.com/msys2/MINGW-packages/actions/runs/3738664786 ?

**Comment by kezsoy** [comment]
Thanks, I will try and test it today

**Comment by kezsoy** [comment]
The old error message has now been bypassed - thanks!

However, im getting some more linking errors - it looks like skia cant find webp symbols and harfbuzz. I tried installing webp and harfbuzz from pacman, but it didnt solve the issue. I noticed that for the jetbrains skia binaries package, libwebp and libharfbuz are packaged along with several other libs - could this be arranged for the mingw build? 

        C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFdataSt10unique_ptrI9hb_blob_t17SkFunctionWrapperIFvPS0_EXadL_Z15hb_blob_destroyEEEEENUlPKvPvE_4_FUNES7_S8_+0x4): undefined reference to `hb_blob_destroy'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x44): undefined reference to `hb_face_create'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x58): undefined reference to `hb_subset_input_create_or_fail'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x78): undefined reference to `hb_subset_input_glyph_set'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x101): undefined reference to `hb_set_add'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x152): undefined reference to `hb_blob_create'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x164): undefined reference to `hb_face_create'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x17a): undefined reference to `hb_blob_destroy'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x17f): undefined reference to `hb_subset_input_create_or_fail'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x1a3): undefined reference to `hb_subset_input_destroy'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x1b9): undefined reference to `hb_subset_input_set_flags'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x1c6): undefined reference to `hb_subset_or_fail'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x1da): undefined reference to `hb_face_reference_blob'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x1f3): undefined reference to `hb_blob_get_data'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x22b): undefined reference to `hb_blob_destroy'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x233): undefined reference to `hb_face_destroy'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x23b): undefined reference to `hb_subset_input_destroy'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x245): undefined reference to `hb_face_destroy'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x281): undefined reference to `hb_subset_input_destroy'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x2df): undefined reference to `hb_set_add'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_encode.SkWeN13SkWebpEncoder6EncodeEP9SkWStreamRK8SkPixmapRKNS_7OptionsE+0x187): undefined reference to `WebPNewInternal'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_encode.SkWeN13SkWebpEncoder6EncodeEP9SkWStreamRK8SkPixmapRKNS_7OptionsE+0x19a): undefined reference to `WebPMuxSetImage'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_encode.SkWeN13SkWebpEncoder6EncodeEP9SkWStreamRK8SkPixmapRKNS_7OptionsE+0x1b0): undefined reference to `WebPMuxDelete'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_encode.SkWeN13SkWebpEncoder6EncodeEP9SkWStreamRK8SkPixmapRKNS_7OptionsE+0x26b): undefined reference to `WebPMuxSetChunk'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_encode.SkWeN13SkWebpEncoder6EncodeEP9SkWStreamRK8SkPixmapRKNS_7OptionsE+0x281): undefined reference to `WebPMuxAssemble'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_encode.SkWeN13SkWebpEncoder6EncodeEP9SkWStreamRK8SkPixmapRKNS_7OptionsE+0x2bd): undefined reference to `WebPMuxDelete'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_encode.SkWeN13SkWebpEncoder14EncodeAnimatedEP9SkWStream6SkSpanIKN9SkEncoder5FrameEERKNS_7OptionsE+0x4f): undefined reference to `WebPAnimEncoderNewInternal'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_encode.SkWeN13SkWebpEncoder14EncodeAnimatedEP9SkWStream6SkSpanIKN9SkEncoder5FrameEERKNS_7OptionsE+0xf1): undefined reference to `WebPAnimEncoderAdd'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_encode.SkWeN13SkWebpEncoder14EncodeAnimatedEP9SkWStream6SkSpanIKN9SkEncoder5FrameEERKNS_7OptionsE+0x11e): undefined reference to `WebPAnimEncoderDelete'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_encode.SkWeN13SkWebpEncoder14EncodeAnimatedEP9SkWStream6SkSpanIKN9SkEncoder5FrameEERKNS_7OptionsE+0x14c): undefined reference to `WebPAnimEncoderDelete'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_encode.SkWeN13SkWebpEncoder14EncodeAnimatedEP9SkWStream6SkSpanIKN9SkEncoder5FrameEERKNS_7OptionsE+0x164): undefined reference to `WebPAnimEncoderAdd'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_encode.SkWeN13SkWebpEncoder14EncodeAnimatedEP9SkWStream6SkSpanIKN9SkEncoder5FrameEERKNS_7OptionsE+0x178): undefined reference to `WebPAnimEncoderAssemble'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_encode.SkWeN13SkWebpEncoder14EncodeAnimatedEP9SkWStream6SkSpanIKN9SkEncoder5FrameEERKNS_7OptionsE+0x1a2): undefined reference to `WebPAnimEncoderDelete'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkDeflate.o)eiP10z_stream_sP9SkWStreamPhy+0x49): undefined reference to `deflate'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkDeflate.o)WStreamC2EP9SkWStreamib+0xaa): undefined reference to `deflateInit2_'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkDeflate.o)WStream8finalizeEv+0x62): undefined reference to `deflateEnd'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkDeflate.o)WStream8finalizeEv+0x188): undefined reference to `deflateEnd'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(fontmgr_win.SkFoa$.refptr.IID_IUnknown[.refptr.IID_IUnknown]+0x0): undefined reference to `IID_IUnknown'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec20onGetRepetitionCountEv+0x12): undefined reference to `WebPDemuxGetI'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec20onGetRepetitionCountEv+0x2c): undefined reference to `WebPDemuxGetI'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodecD1Ev[_ZN11SkWebpCodecD1Ev]+0x86): undefined reference to `WebPDemuxDelete'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodecD0Ev[_ZN11SkWebpCodecD0Ev]+0x86): undefined reference to `WebPDemuxDelete'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec11onGetPixelsERK11SkImageInfoPvyRKN7SkCodec7OptionsEPi+0x73): undefined reference to `WebPDemuxGetFrame'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec11onGetPixelsERK11SkImageInfoPvyRKN7SkCodec7OptionsEPi+0x6fd): undefined reference to `WebPDemuxReleaseIterator'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec14MakeFromStreamESt10unique_ptrI8SkStreamSt14default_deleteIS1_EEPN7SkCodec6ResultE+0x99): undefined reference to `WebPDemuxInternal'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec14MakeFromStreamESt10unique_ptrI8SkStreamSt14default_deleteIS1_EEPN7SkCodec6ResultE+0xc4): undefined reference to `WebPDemuxDelete'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec14MakeFromStreamESt10unique_ptrI8SkStreamSt14default_deleteIS1_EEPN7SkCodec6ResultE+0xf9): undefined reference to `WebPDemuxGetI'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec14MakeFromStreamESt10unique_ptrI8SkStreamSt14default_deleteIS1_EEPN7SkCodec6ResultE+0x109): undefined reference to `WebPDemuxGetI'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec14MakeFromStreamESt10unique_ptrI8SkStreamSt14default_deleteIS1_EEPN7SkCodec6ResultE+0x154): undefined reference to `WebPDemuxGetChunk'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec14MakeFromStreamESt10unique_ptrI8SkStreamSt14default_deleteIS1_EEPN7SkCodec6ResultE+0x16d): undefined reference to `WebPDemuxReleaseChunkIterator'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec14MakeFromStreamESt10unique_ptrI8SkStreamSt14default_deleteIS1_EEPN7SkCodec6ResultE+0x18d): undefined reference to `WebPDemuxGetChunk'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec14MakeFromStreamESt10unique_ptrI8SkStreamSt14default_deleteIS1_EEPN7SkCodec6ResultE+0x19d): undefined reference to `WebPDemuxReleaseChunkIterator'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec14MakeFromStreamESt10unique_ptrI8SkStreamSt14default_deleteIS1_EEPN7SkCodec6ResultE+0x1ad): undefined reference to `WebPDemuxGetFrame'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec14MakeFromStreamESt10unique_ptrI8SkStreamSt14default_deleteIS1_EEPN7SkCodec6ResultE+0x1cb): undefined reference to `WebPDemuxReleaseIterator'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec14MakeFromStreamESt10unique_ptrI8SkStreamSt14default_deleteIS1_EEPN7SkCodec6ResultE+0x4ad): undefined reference to `WebPDemuxReleaseIterator'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec15onGetFrameCountEv+0x20): undefined reference to `WebPDemuxGetI'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec15onGetFrameCountEv+0x7f): undefined reference to `WebPDemuxGetI'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec15onGetFrameCountEv+0x1a0): undefined reference to `WebPDemuxReleaseIterator'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec15onGetFrameCountEv+0x1bd): undefined reference to `WebPDemuxGetFrame'
    C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(webp_decode.SkWe1SkWebpCodec15onGetFrameCountEv+0x1d4): undefined reference to `WebPDemuxReleaseIterator'

**Comment by Biswa96** [comment]
Those dependencies are mentioned in pkgconfig file. So, you have to use pkgconf tool to get the correct libraries. For example, the command may be like this 

```
g++ `pkgconf -cflags skia` test.cpp `pkgconfig -libs skia`
```

**Comment by kezsoy** [comment]
Thanks thats really helpful! I think that solved most of the issues. Im still left with a few link errors from harfbuzz which is a bit confusing, can you spot anything else wrong with my link command? 

          g++ -g  ./src/drawing.o  ./src/glfw_keys.o  ./src/hts_funcs.o  ./src/main.o  ./src/parser.o  ./src/plot_controls.o
     ./src/plot_manager.o  ./src/segments.o  ./src/term_out.o  ./src/themes.o  ./src/utils.o \
         -L/usr/local/lib -L/lib -L/ucrt64/lib -L/home/nopel/gw_build/ucrt64/lib \
         -lskia -lm -ldl -ljpeg -lpng -lsvg -lhts -lfontconfig -lpthread \
         -L../ucrt64/lib -lskia -lgdi32 -lopengl32 -lole32 -loleaut32 -luuid -lfontsub -luser32 -lusp10 -lexpat -lpng16 -lz -lwebpmux -lwebpdecoder -lwebpdemux -lwebp -ljpeg -lharfbuzz -licuin -licuuc -licudt  -lglfw3 -o gw
      
      C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFont.o):(.text$_Z15SkPDFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x58): undefined reference to `hb_subset_input_create_or_fail'
      C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFont.o):(.text$_Z15SkPDFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x78): undefined reference to `hb_subset_input_glyph_set'
      C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFont.o):(.text$_Z15SkPDFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x17f): undefined reference to `hb_subset_input_create_or_fail'
      C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFont.o):(.text$_Z15SkPDFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x1a3): undefined reference to `hb_subset_input_destroy'
      C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFont.o):(.text$_Z15SkPDFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x1b9): undefined reference to `hb_subset_input_set_flags'
      C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFont.o):(.text$_Z15SkPDFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x1c6): undefined reference to `hb_subset_or_fail'
      C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFont.o):(.text$_Z15SkPDFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x23b): undefined reference to `hb_subset_input_destroy'
      C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/home/nopel/gw_build/ucrt64/lib/libskia.a(pdf.SkPDFSubsetFont.o):(.text$_Z15SkPDFSubsetFont5sk_spI6SkDataERK13SkPDFGlyphUseN5SkPDF8Metadata9SubsetterEPKci+0x281): undefined reference to `hb_subset_input_destroy'

I have `mingw-w64-ucrt-x86_64-harfbuzz-6.0.0-1` from pacman. Thanks for the help!

**Comment by Biswa96** [comment]
Probably you also need `-lharfbuzz-subset` option.

**Comment by kezsoy** [comment]
Thanks so much!
