### ISSUE TITLE
[fluidsynth] 32-bit version not working for dll objects that link to libfluidsynth at compile-time

### ISSUE THREAD

**Issue by pd-l2ork** [msys2/MINGW-packages#14586]
### Description

Compiling an dll that is linked to libfluidsynth spawns following error when instantiated:

fluid~.dll: The specified module could not be found.
 (126)

Curiously, when trying to run the program installed in C:/Program Files (x86)/Pd-L2Ork/bin/pd-l2ork.exe from the MINGW32 shell and then trying to create a fluid~ object, this works. But clicking on the program icon it does not. This suggests something is not installed in a way for the object to find it.

In running:

strings libfluidsynth-3.dll | grep -i '\.dll$'

I get:

libgcc_s_dw2-1.dll
libfluidsynth-3.dll
dsound.dll
libgcc_s_dw2-1.dll
KERNEL32.dll
msvcrt.dll
ole32.dll
libstdc++-6.dll
USER32.dll
WINMM.DLL
WS2_32.dll
libglib-2.0-0.dll
libgomp-1.dll
libportaudio.dll
libreadline8.dll
SDL2.dll
libsndfile-1.dll

I tried copying all of these (except for those with capital names into the install folder inside C:/Program Files (x86)/Pd-L2Ork/extra/fluid~ (where fluid~.dll is located) and that did not help.

How do I go about troubleshooting this?

Please note I am using 32-bit version of these libraries due to project's limitations (the whole project is compiled as 32-bit app using exclusively i686 packages).

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 10 Pro with latest updates (64bit)

MSYS2 MinGW is 32-bit

All supporting libs necessary for compiling the project are also 32-bit libs

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

The object should work like it did in the past (the dll object is effectively a wrapper for the fluidsynth inside a Pd-L2Ork visual programming environment for real-time multimedia, based on Pure-Data).

### Actual behavior

The object compiles without errors but when one tries to instantiate it, user gets the error above. On Linux and OSX this is not the issue (although there we use native build environment).

### Repro steps

Unfortunately, the only way to reproduce is to use the Pd-L2Ork environment. You can download source from the github which also offers step-by-step build instructions for Windows.

### Are you willing to submit a PR?

Yes. But need help in understanding how to build my own msys package and how to troubleshoot this.

**Comment by pd-l2ork** [comment]
[SOLUTION]
So, I found the solution to the problem. As far as I can tell, the library is packaged in an incorrect way because it does not show dependency on the following two libraries:

libgomp-1.dll
libpcre2-8-0.dll

When I copy these into the C:/Program Files (x86)/Pd-L2Ork/extra/fluid~ folder, everything works once again fine. Had to manually copy the entire mingw32/bin/ folder into there and then iteratively remove files until I could pinpoint ones that the library is missing.

So, the question is why is the library packaged without having this dependency explicitly stated in it, so that when scrubbing library files, the installer can catch those and include them with the install?

**Comment by brisingraerowing** [comment]
Those seem to be dependencies of dependencies. Glib2 uses PCRE2. I'm not sure what uses libgomp. There's a program called Dependency Walker that is *very* useful for identifying issues like this.

**Comment by pd-l2ork** [comment]
Thanks. So,, why were those not pulled by the regular polling of dependencies?

**Comment by pd-l2ork** [comment]
These were linked to a dll compiled against libfluidsynth. The rest of the program runs just fine without these, which leads me to believe these are somehow only needed by this dll due to its linking against libfluidsynth. The dll itself is plain c and has no additional dependencies (other than application's dll, which is also used by over a thousand of other objects, none of which have this issue). So, it stands to reason these are needed only for this object due to its dependence on libfluidsynth... More so, this was not an issue with libfluidsynth-2, so something must've changed between major revisions 2 and 3.

**Comment by Biswa96** [comment]
> As far as I can tell, the library is packaged in an incorrect way because it does not show dependency on the following two libraries:
> 
> libgomp-1.dll libpcre2-8-0.dll

I agree with brisingraerowing's answer.

libfluidsynth-3.dll depends on libgomp-1.dll and the later one is part of mingw-w64-gcc-libs package which is mentioned as a dependency. See the [fluidsynth PKGBUILD](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-fluidsynth/PKGBUILD).

But libfluidsynth-3.dll does **not** directly depends on libpcre2-8-0.dll and the later one comes from glib2. So, the dependency hierarchy is like libpcre2-8-0.dll → libglib-2.0-0.dll → libfluidsynth-3.dll.
