### ISSUE TITLE
[7zip] 7z.dll missing?

### ISSUE THREAD

**Issue by prgwiz** [msys2/MINGW-packages#14637]
### Description / Steps to reproduce the issue

E:\msys64\mingw64\bin>7z a "c:\swap\test" "c:\swap\uttpd2-main\*"

7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Codec Load Error: E:\msys64\mingw64\bin\7z.dll : The specified module could not be found.

System ERROR:
Not implemented

### Expected behavior

Would expect 7z to archive the files in the dir.

### Actual behavior

Either the 7z.exe does not need a 7z.dll or is missing from the package.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Would you like to test the packages from https://github.com/msys2/MINGW-packages/actions/runs/3723571555 ?

**Comment by prgwiz** [comment]
Tested and works.  Thank you.
