### ISSUE TITLE
`_LIBCPP_DEBUG` doesn't work in CLANG* environments

### ISSUE THREAD

**Issue by HolyBlackCat** [msys2/MINGW-packages#14655]
### Description / Steps to reproduce the issue

Trying to use `-D_LIBCPP_DEBUG` in the CLANG64 environment produces a compilation error.

Check by compiling a file with `#include <iterator>` in it, with `clang++ 1.cpp -D_LIBCPP_DEBUG`.

The same macro does work in MINGW64 and UCRT64.

Looking at the [PKGBUILD file](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libc%2B%2B/PKGBUILD), I don't immediately see it being disabled there. :thinking: 

### Expected behavior

No compilation error.

### Actual behavior

```none
# clang++ 1.cpp -D_LIBCPP_DEBUG
In file included from 1.cpp:1:
In file included from /clang64/include/c++/v1/iterator:679:
/clang64/include/c++/v1/__debug:24:5: error: "Enabling the debug mode now requires having configured the library with support for the debug mode"
#   error "Enabling the debug mode now requires having configured the library with support for the debug mode"
    ^
1 error generated.
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

cross-compiling from Linux

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
libc++ debug-mode is off by default, see https://github.com/llvm/llvm-project/blob/llvmorg-15.0.6/libcxx/docs/DesignDocs/DebugMode.rst
Enabling it will slow our programs and break ABI.
