### ISSUE TITLE
Header conflict between angleproject and mingw-w64-headers package

### ISSUE THREAD

**Issue by ZachBacon** [msys2/MINGW-packages#14665]
### Description / Steps to reproduce the issue

Seems mingw-w64-headers include /KHR/khrplatform.h where angleproject also includes that in that package before

### Expected behavior

file conflict resolution

### Actual behavior

File conflicts since both headers are included in each package.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [ ] CLANGARM64

**Comment by raedrizqie** [comment]
maybe we had to remove khrplatform.h from angle package like mesa did..
```
  # Remove KHR include, fixes conflict with mingw-w64
  rm -rf "${pkgdir}${MINGW_PREFIX}"/include/KHR
```
