### ISSUE TITLE
python-llvmlite update to 0.39.0

### ISSUE THREAD

**Issue by wlph17** [msys2/MINGW-packages#14670]
### Package name

python-llvmlite

### New version number

0.39.0

### Other information that may be useful

numba require >=0.39.0 version llvmlite to be able to import

**Comment by MehdiChinoune** [comment]
We couldn't because llvm-0.39 could only built against LLVM<=11. MSYS2 LLVM is at 15.0.5.

**Comment by wlph17** [comment]
I see, can we roll back to older version of numba?

**Comment by MehdiChinoune** [comment]
> I see, can we roll back to older version of numba?

Older numba versions are not compatible (couldn't work) with latest numpy.

**Comment by wlph17** [comment]
ok then

**Comment by MehdiChinoune** [comment]
Should be fixed by #15242
