### ISSUE TITLE
can not read utf-8 charter from stdin 

### ISSUE THREAD

**Issue by pangguoming** [msys2/MINGW-packages#14718]
### Description / Steps to reproduce the issue

i am doing a  C language project with MINGW64 \ GCC 10.2.0  on windows.
when i read a UTF-8 or gbk string from stdin ( fgets(buf, QUERYBUF_LEN, stdin)  ),   it just read the top byte of UTF-8 or gbk  charter

### Expected behavior

i want to read and get UTF-8 or gbk  charter

### Actual behavior

i am doing a  C language project with MINGW64 \ GCC 10.2.0  on windows.
when i read a UTF-8 or gbk string from stdin ( fgets(buf, QUERYBUF_LEN, stdin)  ),   it just read the top byte of UTF-8 or gbk  charter

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MinGW-w64 8.0.0

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

YES

**Comment by Biswa96** [comment]
Are you using msys2 environment? If yes the gcc version should be 12.2.0.

**Comment by pangguoming** [comment]
> Are you using msys2 environment? If yes the gcc version should be 12.2.0.

No, i am using mingw64 only

**Comment by Biswa96** [comment]
Yes, I am asking about that. If you are using mingw64 the gcc version should be 12.2.0.

**Comment by MehdiChinoune** [comment]
It looks like you are using gcc from https://sourceforge.net/projects/mingw-w64/ not the one from MSYS2.
Or your MSYS2 is not up to date.

**Comment by pangguoming** [comment]
> Yes, I am asking about that. If you are using mingw64 the gcc version should be 12.2.0.

ok, i got it

**Comment by pangguoming** [comment]
> It looks like you are using gcc from https://sourceforge.net/projects/mingw-w64/ not the one from MSYS2. Or your MSYS2 is not up to date.

thanks i got it
