### ISSUE TITLE
hdf5 pc files are invalid

### ISSUE THREAD

**Issue by bgamari** [msys2/MINGW-packages#14740]
### Description / Steps to reproduce the issue

The `pkg-config` files included in `hdf5-1.12.2` appear to be invalid:
```
$ pacman -Suy mingw-w64-x86_64-hdf5
$ pkg-config --libs hdf5_cpp
Package hdf5-1.12.2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `hdf5-1.12.2.pc'
to the PKG_CONFIG_PATH environment variable
Package 'hdf5-1.12.2', required by 'hdf5_cpp', not found
```
The problem is that `hdf5_cpp.pc` includes `Requires: hdf5-1.12.2`, which is incorrect as the name of the package is simply `hdf5`. I suspect this field should rather be `Requires: hdf5 = 1.12.2`. The same issue is exhibited by `hdf5_fortran.pc`, `hdf5_hl.pc`, `hdf5_hl_cpp.pc`, and `hdf5_hl_fortran.pc`.

### Expected behavior

`pkg-config --libs hdf5_cpp` should work.

### Actual behavior

`pkg-config` complains about missing dependencies (as seen above).

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19042

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes, although it's a bit unclear where the affected .pc files are generated, so I'm not sure I  will be able to.

**Comment by Biswa96** [comment]
Thank you for reporting the issue. This was fixed in upstream commit https://github.com/HDFGroup/hdf5/commit/dcccc355261e305a1d877a798d7fd46556b3cbce. The patch will be imported to mingw packages.

**Comment by Biswa96** [comment]
Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/3774581944
