### ISSUE TITLE
Skia cannot include its own headers

### ISSUE THREAD

**Issue by X1nto** [msys2/MINGW-packages#14745]
### Description / Steps to reproduce the issue

Skia fails to `#include` its own headers due to unresolved references.
`SkSurface.h`:
![image](https://user-images.githubusercontent.com/48173186/209472991-c1d5025d-066c-4c49-864a-d3ea89f83cec.png)

1. Install Skia using `pacman -S mingw-w64-clang-x86_64-skia` (ucrt64 and mingw64 are also affected)
2. Try including Skia classes into the project

### Expected behavior

Skia should be able to resolve its own headers

### Actual behavior

Skia can't resolve it's own headers, resulting in incomplete classes and generally messed up header files.
![image](https://user-images.githubusercontent.com/48173186/209473213-7f0c15d9-44af-42b5-a1f3-addb61901614.png)
![image](https://user-images.githubusercontent.com/48173186/209473249-e305f50a-305c-4427-9e15-cd856ee28c2f.png)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Can you provide a sample code to reproduce your issue?

**Comment by X1nto** [comment]
Sure!
```cpp
#include "skia/include/core/SkCanvas.h"
#include "skia/include/core/SkSurface.h"

class sample
{
    SkCanvas canvas; //Field has incomplete type 'SkCanvas'
    
public:
    SkCanvas& get_canvas();
};
```

**Comment by Biswa96** [comment]
You have to use pkgconfig file to get the include directory. For example, try the following command.

```
g++ -c -Wall `pkgconf -cflags skia` test-skia.cpp `pkgconf -libs skia`
```

**Comment by X1nto** [comment]
Oh, I see. For anyone using CMake, this is basically how it looks like:
```cmake
find_package(PkgConfig REQUIRED)
pkg_check_modules(SKIA_LIBS REQUIRED skia)

target_link_directories(${PROJECT_NAME} PRIVATE ${SKIA_LIBS})
target_include_directories(${PROJECT_NAME} PRIVATE ${SKIA_LIBS_INCLUDE_DIRS})
```

**Comment by wuxianggujun** [comment]
> 我懂了。对于任何使用 CMake 的人来说，这基本上是这样的：
> 
> ```cmake
> find_package(PkgConfig REQUIRED)
> pkg_check_modules(SKIA_LIBS REQUIRED IMPORTED_TARGET skia)
> target_link_libraries(${PROJECT_NAME} PUBLIC PkgConfig::SKIA_LIBS)
> target_include_directories(${PROJECT_NAME} PUBLIC PkgConfig::SKIA_LIBS_INCLUDE_DIRS)
> ```

Can I use skia installed with Msys2 on Windows?

**Comment by Biswa96** [comment]
Yes, please try. If there is any issue please report it.
