### ISSUE TITLE
boost update to include CMake configuration files

### ISSUE THREAD

**Issue by slavaandrejev** [msys2/MINGW-packages#14785]
### Package name

boost

### Other information that may be useful

Boost provides CMake configuration files. These files are the ultimate truth about how Boost libraries are to be compiled. It's better to rely on them, then on CMake provided `FindBoost.cmake` module. The latter can become stale, or it can contain bugs, which will make users dependent on the ability of CMake authors to fix it. Boost provided configuration files are always up-to-date and tested with the version we are installing.

I understand there was issue #5233 in the past, if it is relevant today, maybe we can perform a more thorough investigation of the issue. I am going to try to build 3DTK with Boost's CMake configuration files.

**Comment by slavaandrejev** [comment]
I checked 3DTK, it seems to me they use their own script to find Boost. I also installed boost from the source code using
```
b2 -j14 --toolset=gcc --prefix=$MSYSTEM_PREFIX link=shared,static release install
```
and tried a simple test project with the following `CMakeLists.txt`:
```
cmake_minimum_required(VERSION 3.16)

project(test)

find_package(Boost CONFIG
    REQUIRED program_options
    REQUIRED iostreams
    REQUIRED filesystem
)

add_executable(test
    test.cpp
)

target_link_libraries(test
    Boost::program_options
    Boost::iostreams
    Boost::filesystem
)
```
Everything works like clock, I don't see any problems. Any objections to adding CMake configuration files for boost back?

**Comment by lazka** [comment]
Sure, we can give it a try

**Comment by slavaandrejev** [comment]
Let me prepare a PR.

**Comment by slavaandrejev** [comment]
I am curious about all the patches inside `PKGBUILD`. In my experiment, everything was built from a single command, no patches, no `bootstrap.sh`, no custom `.jam` files. I see from the patches, the biggest effort was about Python and ICU. I'll check if it works without all the patches. It would be nice not to have them because they have to be updated with every Boost release.

**Comment by slavaandrejev** [comment]
I think we can close it now.
