### ISSUE TITLE
provide package "bear"

### ISSUE THREAD

**Issue by yashpalgoyal1304** [msys2/MINGW-packages#14861]
> [Bear] is a tool to generate a "compile_commands.json" file 
> [required by `clangd` Language Server] by recording a complete build. 
> For a `make`-based build, you can run `make clean; bear -- make` 
> to generate the file (and run a clean build!).
>
> \- [`clangd`/installation]

[bear/install]: https://github.com/rizsotto/Bear/blob/master/INSTALL.md
[msys2/bear]: https://packages.msys2.org/search?q=bear
[`clangd`/installation]: https://clangd.llvm.org/installation#:~:text=systems%2C%20using%20Bear-,Bear,-is%20a%20tool
[Bear]: https://github.com/rizsotto/Bear
[bear-versions]: https://repology.org/project/bear-clang/versions

* 🔍: [msys2/bear]
* Bear build instructions: [bear/install]
* [bear-versions] upstream

**Comment by yashpalgoyal1304** [comment]
> bear is mentioned in clangd docs https://clangd.llvm.org/installation. A

* yep, i came from there itself (mentioned in description links). 
* infact, i came to know about `compiledb` from clangd official repo itself. 
* the person (per) reported that `compiledb` is even better than `bear`. 
* So... i think it's better to leave it that way maybe.... 
* But ofc, it would have been better if `clangd` adds it on their official documentation page too

see this: https://github.com/clangd/clangd/discussions/1170#discussioncomment-4563121

**Comment by Biswa96** [comment]
The compiledb repository does not look like in maintenance. The last commit was in 2019. I think it should not be added here.

**Comment by yashpalgoyal1304** [comment]
> should not be added *h*ere.

i said their/there, but yeah, "not add" will apply there too..

**Comment by Biswa96** [comment]
It seems that Bear project does not support native Windows platform. See this issue https://github.com/rizsotto/Bear/issues/431. I get many *nix like build errors in mingw

```
Bear/source/libsys/include/libsys/Signal.h:39:9: error: 'pid_t' does not name a type
   39 |         pid_t pid_;
      |         ^~~~~
Bear/source/libsys/source/Signal.cc: In function 'constexpr bool {anonymous}::shall_forward(int)':
Bear/source/libsys/source/Signal.cc:30:18: error: 'SIGKILL' was not declared in this scope; did you mean 'SIGILL'?
   30 |             case SIGKILL:
      |                  ^~~~~~~
      |                  SIGILL
Bear/source/libsys/source/Signal.cc:31:18: error: 'SIGCHLD' was not declared in this scope
   31 |             case SIGCHLD:
      |                  ^~~~~~~
```

So, it can not be added, I guess.

**Comment by yashpalgoyal1304** [comment]
> this issue [rizsotto/Bear#431](https://github.com/rizsotto/Bear/issues/431). I g

so, this issue too is duplicate of https://github.com/msys2/MINGW-packages/issues/7411 then 😅
