### ISSUE TITLE
[mpv] build halts as subprocess.Popen.wait is in deadlock state

### ISSUE THREAD

**Issue by Biswa96** [msys2/MINGW-packages#14888]
### Description / Steps to reproduce the issue

Try to build mingw-w64-waf package as usual. The build process halts after waf configure command. After pressing Ctrl+C, it shows the following message

```
 'configure' finished successfully (36.271s)
Exception ignored in atexit callback: <function atexit_pool at 0x6fffffb40d30>
Traceback (most recent call last):
  File "mingw-w64-mpv/src/mpv-0.34.1/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Utils.py", line 620, in atexit_pool
    k.wait()
  File "/usr/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1943, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.10/subprocess.py", line 1901, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt:

==> ERROR: Aborted by user! Exiting...
```

According to [python docs](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait), it was suggested to use [Popen.communicate()](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate). So, after applying the following diff in same Utils.py file

```diff
@@ -617,7 +617,14 @@
 		except OSError:
 			pass
 		else:
-			k.wait()
+			try:
+				outs, errs = k.communicate(timeout=15)
+			except TimeoutExpired:
+				k.kill()
+				outs, errs = k.communicate()
+			print(outs)
+			print(errs)
+			#k.wait()
 if(sys.hexversion<0x207000f and not is_win32)or sys.hexversion>=0x306000f:
 	atexit.register(atexit_pool)
 if os.environ.get('WAF_NO_PREFORK')or sys.platform=='cli'or not sys.executable:
```

The output became like this and the build process continues as usual.

 ```
'configure' finished successfully (35.988s)
b''
None
b''
None
Waf: Entering directory `mingw-w64-mpv/src/build-x86_64-w64-mingw32'
[1/1] Compiling version.sh
...
```

### Expected behavior

The build process should continue without any deadlock.

### Actual behavior

The build process halts at configure command.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
Maybe `export WAF_NO_PREFORK=1` is an easier workaround?

**Comment by Biswa96** [comment]
> Maybe export WAF_NO_PREFORK=1 is an easier workaround?

That worked. Thanks.
