### ISSUE TITLE
[libpsl] static library linked to dynamic libunistring.dll.a

### ISSUE THREAD

**Issue by psyke83** [msys2/MINGW-packages#14882]
### Description / Steps to reproduce the issue

Hello,

It seems that `libpsl.a` from mingw-w64-x86_64-libpsl 0.21.2-1 is linked to a dynamic library:

```
nm -C /mingw64/lib/libpsl.a | grep -i "__imp_u"
                 U __imp_uninorm_nfkc
```

This makes static building of [Sunshine](https://github.com/LizardByte/Sunshine), which depends on libcurl, to be impossible. Would it be possible to fix this so that static builds are possible again? 

### Expected behavior

Static builds that use libpsl.a (via libcurl) should link without issue.

### Actual behavior

```
[100%] Linking CXX executable sunshine.exe
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libpsl.a(psl.c.obj):(.text+0x141b): undefined reference to `__imp_uninorm_nfkc'
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libpsl.a(psl.c.obj):(.text+0x1497): undefined reference to `__imp_uninorm_nfkc'
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes (but I am not 100% certain how to fix this issue).

**Comment by shithappens2016** [comment]
@MehdiChinoune 

![sdfsdf](https://user-images.githubusercontent.com/13523412/210948116-005f310f-0af0-4d56-93d6-aa4b79353f0a.gif)

**Comment by MehdiChinoune** [comment]
Could you at least change your user identifier, It's inappropriate.

**Comment by MehdiChinoune** [comment]
Could you try the packages built on #14950

**Comment by shithappens2016** [comment]
![无标题](https://user-images.githubusercontent.com/13523412/210953540-7352b66c-a880-4c85-958b-d6b56b073775.png)
it should be ok
