### ISSUE TITLE
mold and mingw

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#14957]
Please see this: https://github.com/rui314/mold/issues/622#issuecomment-1214899251

**Comment by Biswa96** [comment]
Could you provide the steps to build and test it with mingw-w64 toolchain?

**Comment by 3rav** [comment]
A PKGBUILD file will suffice?

[pkg_mold.zip](https://github.com/msys2/MINGW-packages/files/10362649/pkg_mold.zip)

**Comment by Biswa96** [comment]
Probably. Does mold support creating PE binary?

**Comment by MehdiChinoune** [comment]
mold doesn't support Windows https://github.com/rui314/mold/issues/190

**Comment by Biswa96** [comment]
Thanks for the link. It seems that mold linker does not support creating PE binary file but the linker itself has Windows platform support. Wondering if it for cross compiling ELF from Windows or something. This upstream commit suggests same thing https://github.com/rui314/mold/commit/996dc7c9a39afa0d65cad2a0e9fbbf696f33248a

For the actual compiler error, I have sent this patch in mingw-w64 https://sourceforge.net/p/mingw-w64/mailman/message/37758401/. Also I have to add the following diff in mold's cmake file. I am not sure about the cause. Without the change, it shows linking error.

```diff
 @@ -204,6 +208,7 @@
   endif()
 
   target_compile_definitions(mold PRIVATE NOGDI NOMINMAX)
+  target_link_libraries(mold PRIVATE c++ bcrypt)
 else()
   include(CheckLibraryExists)
   check_library_exists(m pow "" LIBM_FOUND)
```

**Comment by 3rav** [comment]
Proposed fixes allow compilation, but (for me):
1. instead `c++` -> `stdc++`
2. delete symbolic link:
```
@@ -432,8 +437,7 @@
       get_filename_component(NEW_DIR \${NEW_ABS} DIRECTORY)
       file(RELATIVE_PATH OLD_REL \${NEW_DIR} \${OLD_ABS})
       message(STATUS \"Installing symlink: \$ENV{DESTDIR}\${NEW_ABS} -> \${OLD_REL}\")
-      file(MAKE_DIRECTORY \$ENV{DESTDIR}\${NEW_DIR})
-      file(CREATE_LINK \${OLD_REL} \$ENV{DESTDIR}\${NEW_ABS} SYMBOLIC)")
+      file(MAKE_DIRECTORY \$ENV{DESTDIR}\${NEW_DIR})")
   endfunction()
```

**Comment by Biswa96** [comment]
I think that linker error should be discussed in upstream. The symlink patch, as a modification, can be placed in this repository.

The mingw-w64 patch was added in upstream https://sourceforge.net/p/mingw-w64/mingw-w64/ci/4359b3570a717d20dcb4251f5b5e94459e1a64ac/

**Comment by mati865** [comment]
FYI mold will not support Windows.
Sold that is derived from mold will support Windows but it's proprietary.

**Comment by MehdiChinoune** [comment]
> FYI mold will not support Windows. Sold that is derived from mold will support Windows but it's proprietary.

mold/sold doesn't support Windows yet, It's not known if Windows support will be proprietary like macos or open-source.
