### ISSUE TITLE
mpv can't display custom icon font

### ISSUE THREAD

**Issue by tsl0922** [msys2/MINGW-packages#14962]
### Description / Steps to reproduce the issue

1. `pacman -S mingw-w64-ucrt-x86_64-mpv`
2. install https://github.com/maoiscat/mpv-osc-modern
3. `mpv <some video file>`

### Expected behavior

mpv-osc-modern shouled work

### Actual behavior

the icon font used by mpv-osc-modern does not render correctly

![image](https://user-images.githubusercontent.com/1680515/211154042-8367b980-6962-4543-a861-7425378515f9.png)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Have you checked any other mpv package where mpv-osc-modern works?

**Comment by tsl0922** [comment]
Yes, this one works: https://github.com/shinchiro/mpv-winbuild-cmake

**Comment by Biswa96** [comment]
Can you provide the proper way to use the https://github.com/maoiscat/mpv-osc-modern repository? The install guide in the repository is hard to understand.

**Comment by tsl0922** [comment]
replace `~~/` with `C:\users\USERNAME\AppData\Roaming\mpv`

see also: https://mpv.io/manual/stable/#files-on-windows

**Comment by Biswa96** [comment]
And what options in osc.conf did you use?

**Comment by tsl0922** [comment]
osc.conf is optional, I didn't create it.

**Comment by Biswa96** [comment]
How does mpv get the text? If it is from the media file, is there any sample video file which has that type of text?

**Comment by tsl0922** [comment]
You can use any video. The text comes from mordern.lua, which will be rendered by mpv with libass, as icon.

**Comment by Biswa96** [comment]
I do not see any text like in the screenshot. But mpv GUI interface seems to be changed after adding the osc script. For example, the volume slider, play pause button, play time etc.

**Comment by tsl0922** [comment]
mpv logs from MINGW64 / MSYS2:  icon font broken
```
[auto_profiles] Applying auto profile: Idle
[auto_profiles] Restoring profile: Idle
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
AV: 00:00:01 / 01:12:34 (0%) A-V:  0.000
[osd/libass] fontselect: Using default font family: (mpv-osd-symbols, 400, 0) -> ArialMT, 0, ArialMT
[osd/libass] fontselect: Using default font family: (material-design-iconic-font, 400, 0) -> ArialMT, 0, ArialMT
AV: 00:00:01 / 01:12:34 (0%) A-V:  0.000
```
mpv logs from mpv-winbuild-cmake: icon font ok
```
[auto_profiles] Applying auto profile: Idle
[auto_profiles] Restoring profile: Idle
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
AV: 00:00:06 / 01:12:34 (0%) A-V:  0.000
```

> [osd/libass] fontselect: Using default font family: (mpv-osd-symbols, 400, 0) -> ArialMT, 0, ArialMT
> [osd/libass] fontselect: Using default font family: (material-design-iconic-font, 400, 0) -> ArialMT, 0, ArialMT

maybe this means material-design-iconic-font is not loaded on MINGW64 / MSYS2?

**Comment by Biswa96** [comment]
> mpv logs from MINGW64 / MSYS2: icon font broken

I get the same `Using default font family` message in both cases 😄 I may missed something and shall look into it later. Please wait for others to comment.
