### ISSUE TITLE
mingw-w64-x86_64-git-lfs 3.3.0 cannot handle unix-like paths from MSYS2's git anymore

### ISSUE THREAD

**Issue by msarehn** [msys2/MINGW-packages#15005]
### Issue

We're running MSYS2 in our Windows build environments. When running `git lfs pull` in a repository, this now fails with

```
# GIT_TRACE=1 git lfs pull
10:32:29.440933 git.c:750               trace: exec: git-lfs pull
10:32:29.441742 run-command.c:655       trace: run_command: git-lfs pull
10:32:29.486760 trace git-lfs: exec: git 'version'
10:32:29.560580 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'
10:32:29.621112 trace git-lfs: exec: uname
10:32:29.677833 trace git-lfs: Error running 'git rev-parse': error converting "/builds/5aqPQdE1/0/gitlab/<path to git repo>" to absolute: The system cannot find the path specified.
Error: error converting "/builds/5aqPQdE1/0/gitlab/<path to git repo>"
to absolute: The system cannot find the path specified.
Not in a Git repository.
```

Downgrading to git-lfs 3.2.0 fixes the issue.

Sifting through the ChangeLog of [git-lfs](https://github.com/git-lfs/git-lfs) it appears that [#5106](https://github.com/git-lfs/git-lfs/pull/5106) might be at fault. And indeed, running git-lfs like

```
# MSYSTEM=MSYS git lfs pull

```

No issue anymore! In MSys2, even in an MINGW shell we're using the MSYS git, so dropping the check for `"MINGW"` seems wrong.

I've reported this [issue upstream](https://github.com/git-lfs/git-lfs/issues/5250). Upstream points to MSys2, however. What should we do? Simply revert the mentioned git-lfs commit for MSys2 builds?

### Versions

```
# git --version
git version 2.38.1
# git-lfs --version
git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3)
# pacman -Qi git mingw-w64-x86_64-git-lfs
Name            : git
Version         : 2.38.1-1
Description     : The fast distributed version control system
Architecture    : x86_64
URL             : https://git-scm.com/
Licenses        : GPL2
Groups          : VCS
Provides        : git-core
Depends On      : curl  libpcre2_8  libexpat  libintl  nano  openssh  openssl  perl-Error  perl>=5.14.0
                  perl-Authen-SASL  perl-libwww  perl-MIME-tools  perl-Net-SMTP-SSL  perl-TermReadKey
Optional Deps   : python: various helper scripts
                  subversion: git svn
Required By     : mingw-w64-x86_64-git-lfs
Optional For    : None
Conflicts With  : None
Replaces        : git-core
Installed Size  : 34.92 MiB
Packager        : CI (msys2/msys2-autobuild/9d582e19/3276290976)
Build Date      : Tue, Oct 18, 2022 22:48:09
Install Date    : Mon, Jan 9, 2023 10:39:17
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

Name            : mingw-w64-x86_64-git-lfs
Version         : 3.3.0-1
Description     : An open source Git extension for versioning large files (mingw-w64)
Architecture    : any
URL             : https://git-lfs.github.com/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : git
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 14.40 MiB
Packager        : CI (msys2/msys2-autobuild/59e8e1af/3590037304)
Build Date      : Thu, Dec 1, 2022 07:21:09
Install Date    : Mon, Jan 9, 2023 10:49:22
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

### Expected behavior

git-lfs can handle the unix-like path without issues.

### Actual behavior

git-lfs errors out with

    Error: error converting "/builds/5aqPQdE1/0/gitlab/<path to git repo>" to absolute: The system cannot find the path specified.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
I can't reproduce the cygpath issues mentioned upstream. Here is a revert: https://github.com/msys2/MINGW-packages/pull/15006

**Comment by lazka** [comment]
Please try again now.

**Comment by msarehn** [comment]
This fixed it. Thanks!

**Comment by lazka** [comment]
A better upstream fix would be to detect if git is cygwin vs native. Maybe by checking if lines in `git config --list --show-origin` start with `file:/` vs something different.
