### ISSUE TITLE
Add bzip3

### ISSUE THREAD

**Issue by kspalaiologos** [msys2/MINGW-packages#15017]
### Package name

bzip3

### Brief description of package

A better, faster and stronger spiritual successor to BZip2. Features higher compression ratios and better performance thanks to a order-0 context mixing entropy coder, a fast Burrows-Wheeler transform code making use of suffix arrays and a RLE with Lempel Ziv+Prediction pass based on LZ77-style string matching and PPM-style context modeling.

### URL for package's homepage

https://github.com/kspalaiologos/bzip3

### Provide a basic test case to validate the package's functionality.

```bash
$ bzip3 -vfeb 6 LICENSE LICENSE.bz3
$ bzip3 -vd LICENSE.bz3 LICENSE.orig
```

### MINGW environments where you need the package

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

I don't use Windows frequently enough and my knowledge of msys2 is rather shallow, so I would prefer if someone more experiened took on this problem.

**Comment by Biswa96** [comment]
Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/3886223547

**Comment by kspalaiologos** [comment]
Seems to work! Thanks a lot!
