### ISSUE TITLE
Numba requires at least version 0.39.0 of llvmlite.

### ISSUE THREAD

**Issue by tienviitta** [msys2/MINGW-packages#15022]
### Description / Steps to reproduce the issue

Require installed:

- pacman -S mingw-w64-x86_64-cython
- pacman -S mingw-w64-x86_64-python-numpy
- pacman -S mingw-w64-x86_64-python-numba

Steps:

```
> python
>>> import numba
```

### Expected behavior

Succesful import, e.g., no error message:

```
> python
>>> import numba
>>>
```

### Actual behavior

```
> python
Python 3.10.9 (main, Dec 10 2022, 09:13:58)  [GCC 12.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.10/site-packages/numba/__init__.py", line 205, in <module>
    _ensure_llvm()
  File "C:/msys64/mingw64/lib/python3.10/site-packages/numba/__init__.py", line 117, in _ensure_llvm
    raise ImportError(msg)
ImportError: Numba requires at least version 0.39.0 of llvmlite.
Installed version is 0.38.1.
Please update llvmlite.
>>>
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19044

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by tienviitta** [comment]
Numba dependencies:
        mingw-w64-x86_64-python-llvmlite >=0.37
        mingw-w64-x86_64-python-numpy >=1.17

[https://packages.msys2.org/package/mingw-w64-x86_64-python-numba?repo=mingw64]

**Comment by MehdiChinoune** [comment]
duplicate #14670

**Comment by tienviitta** [comment]
> 

Hmmh, I couldn't find that with Numba as search. So, there is no solution and Numba is unusable for now?

**Comment by MehdiChinoune** [comment]
Unless someone could fix llvmlite to build against LLVM 15 https://github.com/numba/llvmlite/issues/897

**Comment by MehdiChinoune** [comment]
Should be fixed by #15242

**Comment by ognevnydemon** [comment]
```
OSError: Could not find/load shared object file: llvmlite.dll
 Error was: Could not find module 'C:\msys64\ucrt64\lib\python3.10\site-packages\llvmlite\binding\llvmlite.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by MehdiChinoune** [comment]
@ognevnydemon could you try package from #15259

**Comment by ognevnydemon** [comment]
@MehdiChinoune I tried to import njit and I received this
```
from numba import njit
  File "C:\msys64\ucrt64\lib\python3.10\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\msys64\ucrt64\lib\python3.10\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\msys64\ucrt64\lib\python3.10\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
```

**Comment by MehdiChinoune** [comment]
see https://github.com/numba/numba/issues/8464

**Comment by MehdiChinoune** [comment]
@ognevnydemon hopefully #15656 will fix the issue.
```
from numba import njit
```
runs, but I am not a user of numba.

**Comment by ognevnydemon** [comment]
@MehdiChinoune now it works. thanks!
