### ISSUE TITLE
`libc++abi` update to 15.0.5

### ISSUE THREAD

**Issue by str4d** [msys2/MINGW-packages#15032]
### Package name

libc++abi

### New version number

15.0.5

### Other information that may be useful

It looks like `libc++` has been getting 15.0.* updates, but for some reason `libc++abi` doesn't have any matching packages. The `libc++` packages look about the same size, so I don't believe `libc++abi` has been merged into it, but I could be mistaken.

**Comment by str4d** [comment]
I'm specifically looking in https://repo.msys2.org/mingw/x86_64/ - I can see that packages for both `libc++` and `libc++abi` were available up to `14.0.6-1`, but `15.0.0-2` and onwards only have `libc++` packages.

Alternative idea: maybe the package builder is encountering an error for the `libc++abi` packages and is just proceeding to upload whatever it managed to build?

**Comment by lazka** [comment]
libc++abi is provided by libc++ and is at version 15.0.5
