### ISSUE TITLE
mingw64 gcc fails when using UNIX style absolute include paths

### ISSUE THREAD

**Issue by poinu** [msys2/MINGW-packages#15037]
### Description / Steps to reproduce the issue

Trying to build a program using UNIX style absolute include paths:
```
// t1.c
#include "/home/user/header.h"
void foo() {}
```

with `/mingw64/bin/gcc -c t1.c` results in failure:
```
t1.c:1:10: fatal error: /home/user/header.h: No such file or directory
    1 | #include "/home/user/header.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Using `C:/msys64/home/user/header.h` or `/msys64/home/user/header.h` "styles" for the path makes the compilation work.

Steps to reproduce:
1) (`$ /mingw64.exe`)
2) `/mingw64/bin/gcc -c t1.c`

### Expected behavior

Absolute UNIX paths are usable with mingw64 toolchain.

### Actual behavior

Absolute UNIX paths cause compilation failures with mingw64 toolchain.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19044

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [x] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
mingw gcc is a native Windows program and doesn't understand unix/cygwin paths.

**Comment by poinu** [comment]
Hi @lazka, thanks for the quick answer. I was confused by the `/` vs `\` so I thought that would/should work.

Is UCRT64 gcc toolchain native Windows as well?

I get the same result with `clang64/mingw-w64-clang-x86_64-clang` (which makes sense from your explanation). I wanted to try `msys/clang` as well but I can't seem to be able to run it.

**Comment by Biswa96** [comment]
> Is UCRT64 gcc toolchain native Windows as well?

Yes, any package starts with mingw- prefix is native to Windows platform and does not use msys2 compatibility layer. More information can be found here https://www.msys2.org/docs/environments/
