### ISSUE TITLE
[python-msgpack] Uses Python fallback implementation instead of fast C implementation

### ISSUE THREAD

**Issue by RayyanAnsari** [msys2/MINGW-packages#15040]
### Description / Steps to reproduce the issue

1. Install `python-msgpack` package for the specific environment
2. Run this script:
```py
import msgpack
print(msgpack.Packer)
```

### Expected behavior

Expected output (from the official Python on Windows):
```
<class 'msgpack._cmsgpack.Packer'>
```

### Actual behavior

Actual output (from MSYS2 UCRT64 Python):
```
<class 'msgpack.fallback.Packer'>
```

### More info

- The C implementation exists as `/ucrt64/lib/python3.10/site-packages/msgpack/_cmsgpack.cp310-mingw_x86_64_ucrt.pyd`
- However the library probably fails to import that and instead uses the fallback implementation

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Hi @RayyanAnsari, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/3917331820. Please follow these steps:

1. Scroll down and download the correct artifact. It'll be a zip file.
2. Extract the package (.tar.zst) from zip file.
3. Install it with `pacman -U the-package-name.tar.zst` command.

**Comment by Biswa96** [comment]
This issue was interesting. I am not sure what happened behind the scene. Any explanation would be helpful.

* Before removing the sed command:
```
$ file /ucrt64/lib/python3.10/site-packages/msgpack/_cmsgpack.cp310-mingw_x86_64_ucrt.pyd
/ucrt64/lib/python3.10/site-packages/msgpack/_cmsgpack.cp310-mingw_x86_64_ucrt.pyd: MS-DOS executable
```

* After removing the sed command:
```
$ file /ucrt64/lib/python3.10/site-packages/msgpack/_cmsgpack.cp310-mingw_x86_64_ucrt.pyd
/ucrt64/lib/python3.10/site-packages/msgpack/_cmsgpack.cp310-mingw_x86_64_ucrt.pyd: PE32+ executable (DLL) (console) x86-64 (stripped to external PDB), for MS Windows, 11 sections
```

**Comment by RayyanAnsari** [comment]
@Biswa96 thanks for the quick fix!
That does solve the issue and now it is working as expected.
