### ISSUE TITLE
gmp: can no longer link gmp as a static library

### ISSUE THREAD

**Issue by galloty** [msys2/MINGW-packages#15123]
### Description / Steps to reproduce the issue

`g++ test.cpp -static -lgmp`

where test.cpp is
`#include <gmp.h>`
`int main()`
`{`
`	mpz_t t; mpz_init(t);`
`	return 0;`
`}`

### Expected behavior

With the previous versions of MSYS2 - gmp, it builds fine.

### Actual behavior

`undefined reference to '__imp___gmpz_init'`

The diff of gmp.h with the previous version is
`> #define __GMP_LIBGMP_DLL  1`
`< #define __GMP_LIBGMP_DLL  0`
This is the reason of the error: __GMP_LIBGMP_DLL must be set to 0.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

**Comment by lazka** [comment]
likely related -> #14954
