### ISSUE TITLE
gcc-12.2.0-8: why did the package size increased many times?

### ISSUE THREAD

**Issue by mobius217** [msys2/MINGW-packages#15132]
### Description / Steps to reproduce the issue

Why did gcc-12.2.0-8 the packages size increased many times compared with gcc-12.2.0-7?

mingw-w64-x86_64-gcc-12.2.0-8-any.pkg.tar.zst - https://repo.msys2.org/staging/mingw-w64-x86_64-gcc-12.2.0-8-any.pkg.tar.zst
238 278 350 bytes
mingw-w64-x86_64-gcc-12.2.0-7-any.pkg.tar.zst - https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-gcc-12.2.0-7-any.pkg.tar.zst
29 309 386 bytes

mingw-w64-x86_64-gcc-libs-12.2.0-8-any.pkg.tar.zst - https://repo.msys2.org/staging/mingw-w64-x86_64-gcc-libs-12.2.0-8-any.pkg.tar.zst
6 548 877 bytes
mingw-w64-x86_64-gcc-libs-12.2.0-7-any.pkg.tar.zst - https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-gcc-libs-12.2.0-7-any.pkg.tar.zst
897 108 bytes

### Expected behavior

gcc-12.2.0-8 and previous gcc-12.2.0-7 should have a similar size, because minor changes.

### Actual behavior

gcc-12.2.0-8 (from staging repo) is up to 8 times bigger than previous gcc-12.2.0-7

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19044

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by revelator** [comment]
stripping disabled ?

**Comment by lazka** [comment]
yes, looks like it doesn't get stripped for some reason

**Comment by lazka** [comment]
`file` now reports .exe as `application/vnd.microsoft.portable-executable; charset=binary`, previously it did as `application/x-dosexec; charset=binary`

**Comment by Biswa96** [comment]
Does this mean every packages which built after 'file package' update need to be rebuilt?

**Comment by lazka** [comment]
yes

**Comment by lazka** [comment]
@mobius217 thanks again for the report

**Comment by mobius217** [comment]
> @mobius217 thanks again for the report

Thanks for the quick resolution of the issue
