### ISSUE TITLE
 'openssl/applink.c' file not found

### ISSUE THREAD

**Issue by hbenrico** [msys2/MINGW-packages#15142]
### Description / Steps to reproduce the issue

no problems with previous versions 
thank you in advance

### Expected behavior

.

### Actual behavior

gcc.exe -c -O3 -DHB_MEMO_SAFELOCK -DHBMK_HAS_OPENSSL -DOPENSSL_NO_IDEA -Iyes\..\inc32 -W -Wall -pipe -DUNICODE -D_UNICODE -I../../../../../include -Ic:/comp/msys64/clang64/include -std=gnu89 ../../../../../contrib/hbssl/ssl.c
../../../../../contrib/hbssl/ssl.c:105:13: fatal error: 'openssl/applink.c' file not found
   #include "openssl/applink.c"
            ^~~~~~~~~~~~~~~~~~~
1 error generated.
hbmk2[hbssl]: Error: Running C/C++ compiler. 1

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
Does this compile/build on any Linux distribution.
The file was installed manually (not by `make install`), so I removed it to keep the default installation.
`applink.c` is not part of OpenSSL by default.

**Comment by hbenrico** [comment]
ok, thanks
please, where I could find a copy of applink.c file? (needed by harbour
compiler)

thanks in advance

‪Il giorno lun 16 gen 2023 alle ore 22:00 ‫مهدي شينون (Mehdi Chinoune)‬‎ <
***@***.***> ha scritto:‬

**Comment by MehdiChinoune** [comment]
`applink.c` is only installed with MSVC, so the project you are trying to build has a wrong assumption:
https://github.com/vszakats/hb/blob/main/contrib/hbssl/ssl.c#L86
They should only define `HB_OPENSSL_HAS_APPLINK` with MSVC.

You could fix your build by adding `-DHB_OPENSSL_NO_APPLINK` to your compile/preprocess flags.

**Comment by hbenrico** [comment]
thank you so much! :)

‪Il giorno lun 16 gen 2023 alle ore 22:22 ‫مهدي شينون (Mehdi Chinoune)‬‎ <
***@***.***> ha scritto:‬
