### ISSUE TITLE
OpenSSL: default certificate path changed from `ssl` to `etc/ssl`

### ISSUE THREAD

**Issue by larskanis** [msys2/MINGW-packages#15141]
### Description / Steps to reproduce the issue

If libssl is used without `SSL_CERT_FILE` environment variable, it loads a default CA list from a predefined directory. This used to be the `ssl` directory, but changed to `etc/ssl` in the [commit to update to OpenSSL-3.0.7](https://github.com/msys2/MINGW-packages/commit/2f97826e8a8fce0b9a49da7ea2bffbab7ce98eb5#r96397194).

That means, that CA certificates have a different location now. I didn't find any discussion about this change.

We use the ssl directory in RubyInstaller to distribute the CA bundle and our [unit tests fail](https://github.com/oneclick/rubyinstaller2/actions/runs/3928135524/jobs/6715431259#step:29:565) now. If I change the path to `etc/ssl` in RubyInstaller and adjust the tests, they get green again. Unfortunately this breaks backward compatibility with running installations of RubyInstaller.

### Expected behavior

Load the default CA certificate file from `ssl` (the path is relative to the architecture directory of the MSYS2 installation).

### Actual behavior

Load the default CA certificate file from `etc/ssl` since https://github.com/msys2/MINGW-packages/commit/2f97826e8a8fce0b9a49da7ea2bffbab7ce98eb5 .

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

  Microsoft Windows Server 2022   10.0.20348

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by larskanis** [comment]
[Here is a description](https://github.com/oneclick/rubyinstaller2/blob/8e47f078f3448d05fe2d0e9ff1d5ef247a61d758/resources/ssl/README-SSL.md) how OpenSSL CA certificates are handled in RubyInstaller.

**Comment by Biswa96** [comment]
If the [FHS rules][1] are followed the /etc directory should be used to store config files. The move from /ssl to /etc/ssl looks right to me. ArchLinux's [openssl v3][2] package also uses /etc/ssl directory.

IIUC, the proper way to get the directory should be using openssl itself - command line or API. For example, `openssl info -configdir`. But as of now that command returns `D:/a/msys64/ucrt64/etc/ssl` which is the build directory in CI. That should be relocated properly.

[1]: https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard
[2]: https://archlinux.org/packages/core/x86_64/openssl/

**Comment by MehdiChinoune** [comment]
> Unfortunately this breaks backward compatibility with running installations of RubyInstaller.

What kind of "backward compatibility"?
Does something will break for existing users?
If you mean by `incompatibility` anything that's different then I don't think It's an issue to begin with.

**Comment by larskanis** [comment]
The incompatibility arises, when people place their own certificates into the `ssl` directory according to [this desciption](https://github.com/oneclick/rubyinstaller2/blob/8e47f078f3448d05fe2d0e9ff1d5ef247a61d758/resources/ssl/README-SSL.md). This is what we do on all our Windows machines in the company to add our companies internal root certificate. This certificate will no longer be loaded and TLS connections will fail after an update from RubyInstaller-3.2.0 to 3.2.1.

Aside from that RubyInstaller versions up to 3.1.x will keep using OpenSSL-1.1.1, since OpenSSL-3.0 breaks the Ruby API in an partly incompatible way. Therefore I have to change the SSL documentation to kind of: "If you're using Ruby up to 3.1.x then use `ssl/certs` directory and use `etc/ssl/certs` instead on newer versions. Not very nice, but manageable.


> For example, `openssl info -configdir`. But as of now that command returns `D:/a/msys64/ucrt64/etc/ssl` which is the build directory in CI. That should be relocated properly.

We use only the OpenSSL API and don't ship the executable. And the certificate issue already [runs fine](https://github.com/oneclick/rubyinstaller2/actions/runs/3933637833/jobs/6727553899#step:29:96) with the current relocation patch, when using the `etc/ssl` path.

**Comment by MehdiChinoune** [comment]
> The incompatibility arises, when people place their own certificates into the `ssl` directory according to [this desciption](https://github.com/oneclick/rubyinstaller2/blob/8e47f078f3448d05fe2d0e9ff1d5ef247a61d758/resources/ssl/README-SSL.md). This is what we do on all our Windows machines in the company to add our companies internal root certificate. This certificate will no longer be loaded and TLS connections will fail after an update from RubyInstaller-3.2.0 to 3.2.1.

Just tell them - in releas notes- to change where they should copy their certificates in.

**Comment by MSP-Greg** [comment]
Does this affect the 'ca-certificates' packages (mingw-w64-ucrt-x86_64-ca-certificates, mingw-w64-x86_64-ca-certificates, etc)?

**Comment by MSP-Greg** [comment]
If the current location remains etc/ssl, and given that a lot of CI is still run with OpenSSL 1.1.1, it would be very helpful if 'ca-certificates' placed files in both etc/ssl for OpenSSL 3 and ssl for OpenSSL 1.1...

**Comment by MehdiChinoune** [comment]
> given that a lot of CI is still run with OpenSSL 1.1.1

How could be this possible?, If you mean downloading from a direct link or building an old version then they should know the consequences.

**Comment by larskanis** [comment]
OK, thank you for discussing this topic! I changed RubyInstaller to use the new directory `etc/ssl` starting with ruby-3.2.1, updated the documentation and will add it to the release notes: https://github.com/oneclick/rubyinstaller2/commit/3c839c73f4bc1568d1b841a3d0c850be8616d81b

Also thank you for developing and maintaining this great software library! Without it RubyInstaller for Windows wouldn't work!

**Comment by MSP-Greg** [comment]
@MehdiChinoune

> How could this be possible?, If you mean downloading from a direct link

Yes.

OpenSSL 1.1.1 is supported until 2023-Sep-11.  OpenSSL 3.0.0 was released 2021-Sep-07, and MSYS2 has waited (understandably) until now to update to 3.0.  A lot of CI is done with code that cannot be built with OpenSSL 3.0, and a lot of 'packages' test with 1.1.1, and will try to maintain compatibility with it.

In general, I think we all wish that the use of EOL versions was not as prevalent as it is.

Thanks for the update to 3.0.

**Comment by kasper93** [comment]
@MehdiChinoune: Breaking changes like this should be done with little bit more care.

`mingw-w64-x86_64-python` does not work currently, because of this change. `mingw-w64-x86_64-ca-certificate` installs certs into old `ming64/ssl/certs` instead of `mingw64/etc/ssl/certs`. Didn't test other envs, but issue is probably mirrored there too.

@larskanis: Could you reopen this issue, I would like not to create duplicate and it is still very much not resolved.

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune: Breaking changes like this should be done with little bit more care.
> 
> `mingw-w64-x86_64-python` does not work currently, because of this change. `mingw-w64-x86_64-ca-certificate` installs certs into old `ming64/ssl/certs` instead of `mingw64/etc/ssl/certs`. Didn't test other envs, but issue is probably mirrored there too.

When I opened #15041 It was possible for anyone to review the changes. The other contributors were OK with it, so I went ahead and pushed it.
If you care that much about MSYS2 then you are welcome to contribute.

**Comment by kasper93** [comment]
It's fine as soon as it gets resolved. It was just not obvious why CI stopped working and took some time to backtrack the issue to here. Things happens. :)

**Comment by kasper93** [comment]
I can confirm that ca-certificate update fixes python issue, thanks.
