### ISSUE TITLE
qt6-static: qmake cannot find mkspecs due to wrong QT_INSTALL_PREFIX

### ISSUE THREAD

**Issue by eighttails** [msys2/MINGW-packages#15218]
### Description / Steps to reproduce the issue

1. install qt6-static package.
2. run `qmake foo.pro` in any Qt project folder.
3. run `/ucrt64/qt6-static/bin/qmake -query`

for more details see Actual Behavior below.

### Expected behavior

QT_INSTALL_PREFIX is set to C:/msys64/ucrt64/qt6-static (not qt6-st)
and qmake properly works.

### Actual behavior

When I try to create Makefile from .pro I get following error.
```
eight@DESKTOP-75JNRHB UCRT64 ~/extlib/qt6-src-static/qtbase/examples/widgets/mainwindows
$ /ucrt64/qt6-static/bin/qmake mainwindows.pro
Could not find qmake spec 'win32-g++'.
Error processing project file: mainwindows.pro
```

`qmake -query` says QT_INSTALL_PREFIX is truncated and every other path is made wrong.
It should be `qt6-static` but is truncated to 'qt6-st'.
```
eight@DESKTOP-75JNRHB UCRT64 ~/extlib/qt6-src-static/qtbase/examples/widgets/mainwindows
$ /ucrt64/qt6-static/bin/qmake -query
QT_SYSROOT:
QT_INSTALL_PREFIX:C:/msys64/ucrt64/qt6-st
QT_INSTALL_ARCHDATA:C:/msys64/ucrt64/qt6-st/share/qt6
QT_INSTALL_DATA:C:/msys64/ucrt64/qt6-st/share/qt6
QT_INSTALL_DOCS:C:/msys64/ucrt64/qt6-st/share/doc/qt6
QT_INSTALL_HEADERS:C:/msys64/ucrt64/qt6-st/include/qt6
QT_INSTALL_LIBS:C:/msys64/ucrt64/qt6-st/lib
QT_INSTALL_LIBEXECS:C:/msys64/ucrt64/qt6-st/share/qt6/bin
QT_INSTALL_BINS:C:/msys64/ucrt64/qt6-st/bin
QT_INSTALL_TESTS:C:/msys64/ucrt64/qt6-st/share/qt6/tests
QT_INSTALL_PLUGINS:C:/msys64/ucrt64/qt6-st/share/qt6/plugins
QT_INSTALL_QML:C:/msys64/ucrt64/qt6-st/share/qt6/qml
QT_INSTALL_TRANSLATIONS:C:/msys64/ucrt64/qt6-st/share/qt6/translations
QT_INSTALL_CONFIGURATION:
QT_INSTALL_EXAMPLES:C:/msys64/ucrt64/qt6-st/share/doc/qt6/examples
QT_INSTALL_DEMOS:C:/msys64/ucrt64/qt6-st/share/doc/qt6/examples
QT_HOST_PREFIX:C:/msys64/ucrt64/qt6-st
QT_HOST_DATA:C:/msys64/ucrt64/qt6-st/share/qt6
QT_HOST_BINS:C:/msys64/ucrt64/qt6-st/bin
QT_HOST_LIBEXECS:C:/msys64/ucrt64/qt6-st/share/qt6/bin
QT_HOST_LIBS:C:/msys64/ucrt64/qt6-st/lib
QMAKE_SPEC:win32-g++
QMAKE_XSPEC:win32-g++
QMAKE_VERSION:3.1
QT_VERSION:6.4.2
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
I think It's because of my latest update. When I modified https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-qt6-static/014-fix-relocatable-prefix-staticbuild-v2.patch to be compatible with qt6 6.4.2.
Someone has to take a look and figure a better patch.

**Comment by shithappens2016** [comment]
@MehdiChinoune

https://github.com/qt/qtbase/blob/e3e40c44d3f998a433a6a1080297c5f28e9a768f/src/corelib/global/qlibraryinfo.cpp#L302-L316

It says "For Qt tools in a static build, we must chop off the bin directory". So my guess is that 4 characters (`/bin`) were chop off from `C:/msys64/ucrt64/qt6-static` and end up become `C:/msys64/ucrt64/qt6-st` .

**Comment by alvinhochun** [comment]
> But I don't really know what `qt_configure_strs` is

https://github.com/qt/qtbase/blob/v6.4.2/src/corelib/global/qconfig.cpp.in#L15
https://github.com/qt/qtbase/blob/v6.4.2/cmake/QtQmakeHelpers.cmake#L20-L31

**Comment by birdsTalks** [comment]
Ah, this problem can be solved temporarily by the following methods.

cp -r ./qt6-static  ./qt6-st

or create junction using junction.exe tools.

**Comment by Trilec** [comment]
any real fix for this ?
