### ISSUE TITLE
openmp: Unit tests fail in CLANG64 and many more in CLANGARM64

### ISSUE THREAD

**Issue by hmartinez82** [msys2/MINGW-packages#15220]
### Description
I found this while investigating SEGFAULTs in DarkTable, Inkscape and GraphicsMagick after OpenMP was enabled when building them in CLANGARM64.

### Steps to reproduce the issue in CLANG64 and CLANGARM64:
- Install pip with `pacman -S ${MINGW_PACKAGE_PREFIX}-python-pip`
- Install lit with `pip install lit`
- Edit `mingw-w64-openmp/PKGBUILD` and add an extra `OPENMP_LLVM_LIT_EXECUTABLE` to the CMake call. E.g:
```
      -B "build-${MSYSTEM}-${shared_libs}" \
      -DOPENMP_LLVM_LIT_EXECUTABLE:FILEPATH="${MINGW_PREFIX}/bin/lit-script.py"
```
- Build OpenMP package
- cd to `src/build-${MSYSTEM}-shared` and run `ninja check-openmp`

I wanted to compare CLANG64 units tests vs. MINGW64's, but OpenMP does not configure the tests for building if the compiler is not Clang. (See https://github.com/llvm/llvm-project/blob/main/openmp/libompd/test/CMakeLists.txt#L3)

### Expected behavior

All unit tests pass

### Actual behavior

CLANG64 output:
```
********************
Failed Tests (3):
  libomp :: tasking/bug_proxy_task_dep_waiting.c
  libomp :: tasking/hidden_helper_task/gtid.cpp
  libomp :: worksharing/for/kmp_sch_simd_guided.c


Testing Time: 35.36s
  Unsupported: 108
  Passed     : 188
  Failed     :   3
```
CLANGARM64 output:
```
********************
Failed Tests (11):
  libomp :: env/kmp_dispatch_buf_range.c
  libomp :: env/kmp_set_dispatch_buf.c
  libomp :: misc_bugs/many-microtask-args.c
  libomp :: tasking/bug_proxy_task_dep_waiting.c
  libomp :: tasking/hidden_helper_task/gtid.cpp
  libomp :: tasking/kmp_task_reduction_nest.cpp
  libomp :: teams/kmp_num_teams.c
  libomp :: worksharing/for/kmp_sch_simd_guided.c
  libomp :: worksharing/for/kmp_set_dispatch_buf.c
  libomp :: worksharing/for/omp_for_dynamic_large_chunk.c
  libomp :: worksharing/for/omp_for_static_large_chunk.c


Testing Time: 67.61s
  Unsupported: 108
  Passed     : 180
  Failed     :  11
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

Unfortunately OpenMP is completely out of my league 😞

**Comment by mati865** [comment]
> Expected behavior
All unit tests pass

I think we don't have passing unit tests for any LLVM subproject for various reasons. Last time I tried that most of the tests failed because of path conversions.

**Comment by hmartinez82** [comment]
I also created this upstream https://github.com/llvm/llvm-project/issues/60220

**Comment by mstorsjo** [comment]
> > Expected behavior
> > All unit tests pass
> 
> I think we don't have passing unit tests for any LLVM subproject for various reasons. Last time I tried that most of the tests failed because of path conversions.

In current git main, all tests pass for me, on both x86 and arm (32 and 64). For x86, it’s tested in my GitHub actions nightly builds. But reaching that state requires backporting half a dozen patches at least.

**Comment by hmartinez82** [comment]
@lazka after your patches, OpenMP now has unit test parity with CLANG64. Fun fact, 8 other unit tests fail if you don't run the unit tests with Admin elevation. But this is only required in ARM64 🤔
```
********************
Failed Tests (3):
  libomp :: tasking/bug_proxy_task_dep_waiting.c
  libomp :: tasking/hidden_helper_task/gtid.cpp
  libomp :: worksharing/for/kmp_sch_simd_guided.c


Testing Time: 51.09s
  Unsupported: 108
  Passed     : 188
  Failed     :   3
```
