### ISSUE TITLE
lua-lgi: Fails to be found when running under luajit

### ISSUE THREAD

**Issue by hmartinez82** [msys2/MINGW-packages#15245]
### Description 

When installing lua-lgi after luajit, lua-lgi installs without errors (since luajit provides lua51), but it's then not found by luajit.

What are the options here ?
- Either luajit should also look for modules where lua51 modules are expected, or
- Create a luajit flavor of lua-lgi, for instance luajit-lgi 

### Steps to reproduce the issue
- Install `mingw-w64-x86_64-luajit`
- Install `mingw-w64-x86_64-lua51-lgi`
- Run `luajit -e 'print(require("lgi")._VERSION)'`

### Expected behavior

lua-lgi's version is returned. E.g: 
`0.9.2`

### Actual behavior

The lgi module is not found:
```
C:/msys64/mingw64/bin/luajit.exe: (command line):1: module 'lgi' not found:
        no field package.preload['lgi']
        no file '.\lgi.lua'
        no file 'C:\msys64\mingw64\bin\lua\lgi.lua'
        no file 'C:\msys64\mingw64\bin\lua\lgi\init.lua'
        no file '.\lgi.dll'
        no file 'C:\msys64\mingw64\bin\lgi.dll'
        no file 'C:\msys64\mingw64\bin\loadall.dll'
stack traceback:
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x7ff70c7a2100    
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [x] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes. I can create an PR after a solution is picked up as in the Decription

**Comment by hmartinez82** [comment]
@Biswa96 what should I do? :)

**Comment by Biswa96** [comment]
I am not familiar with lua. The lua51 was being replaced with luajit and hence I just asked about that.

**Comment by hmartinez82** [comment]
I prefer luajit too (I'm a `jit all the things` kind of guy), but lua-lgi is not working when luajit is used in lieu of lua51
