### ISSUE TITLE
python: broken launcher executables

### ISSUE THREAD

**Issue by podsvirov** [msys2/MINGW-packages#15249]
### Description / Steps to reproduce the issue

For example, there is broken for me:

```console
$ ipython
```

But module is working:

```console
$ python -m IPython
```

### Expected behavior

I want to launch ipython by simply typing:

```console
$ ipython
```

### Actual behavior

When I type:

```console
$ ipython
```

The `ipython` not launched.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Would you like to test the packages from here https://github.com/msys2/MINGW-packages/actions/runs/4012208852 ?

**Comment by podsvirov** [comment]
I apologize for the long answer. Your fix does what it's supposed to do.

**Comment by Biswa96** [comment]
No problem. Thanks for verifying that.
