### ISSUE TITLE
`mingw-w64-x86_64-nodejs` requires openssl and c-ares

### ISSUE THREAD

**Issue by djdisodo** [msys2/MINGW-packages#15258]
### Description / Steps to reproduce the issue

i installed mingw-w64-x86_64-nodejs

### Expected behavior

npm just works

### Actual behavior

had to install
mingw-w64-x86_64-openssl
and
mingw-w64-x86_64-c-ares

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19044

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
nodejs already depends on openssl and c-ares, How did you install nodejs?

**Comment by djdisodo** [comment]
> nodejs already depends on openssl and c-ares, How did you install nodejs?

simply typeing
`pacman -S mingw-w64-x86_64-nodejs`

seems like my update just bugged

**Comment by fei4xu** [comment]
I had a same issue here.

quich fix: manually install (maybe reinstall)
```
pacman -S mingw-w64-x86_64-openssl
pacman -S mingw-w64-x86_64-c-ares
```

**Comment by Biswa96** [comment]
> I had a same issue here.

@fei4xu As state before, mingw nodejs package already has those dependencies declared. Make sure to update the packages with `pacman -Syyu` command. You can see the package details here https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-nodejs?repo=ucrt64
