### ISSUE TITLE
Dependency bz2 missing

### ISSUE THREAD

**Issue by sunderme** [msys2/MINGW-packages#15317]
### Description / Steps to reproduce the issue

Using quazip-qt6 in a build results in errors "msys64/ucrt64/lib/libbz2.dll.a" needed by ...
See https://github.com/texstudio-org/texstudio/actions/runs/4032250713/jobs/6932011898

The issue is that quazip now can use bzip2 as well and looking into CMakeLists.txt automatically downloads dependencies and builds them (at least it looks like it: `
option(QUAZIP_FETCH_LIBS "Enables fetching third-party libraries if not found" ${WIN32})`)

### Expected behavior

add libbz2 as dependency (or disable build with bz2 support)

### Actual behavior

missing dependency/missing dll

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows Server 2022   10.0.20348 (github)

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

maybe

**Comment by MehdiChinoune** [comment]
looking at https://github.com/msys2/MINGW-packages/pull/15292/checks, cmake found system bzip2 and use it with quazip.
I think we should add it as an optional dependency.

**Comment by MehdiChinoune** [comment]
There is no need to add it as an optional dependency, It's already an indirect dependency.
I think cmake files shoud be fixed.
