### ISSUE TITLE
[cmake] 3.25.2-1 missing libraries

### ISSUE THREAD

**Issue by schroeca** [msys2/MINGW-packages#15369]
### Description / Steps to reproduce the issue

The current version of cmake is referencing an old version of openssl and I can't get it working after updating my msys2 installation  using pacman.

I have also installed "git for windows" - perhaps this is the issue.

it seems that the library libcrypto-1_1-x64.dll is not available on my system.

`mingw64/bin/cmake.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory`

### Expected behavior

At least a hint which library is missing would be nice.

### Actual behavior

I get this error message:

`mingw64/bin/cmake.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory`

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-25284

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> I have also installed "git for windows" - perhaps this is the issue.

If you want to use msys2/mingw packages in git-for-windows environment it would not work. "Git for Windows' OpenSSL is still at v1.1.* while MSYS2's has advanced to v3.*. This version is encoded in the DLL name. So if you still have libcurl from Git for Windows (pacman -Qi shows the packager if you want to check), but libssl from MSYS2, things are broken in the setup."

As pointed by this documentation[^1], Please note that this scenario is not officially supported by Git for Windows.

[^1]: https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper

**Comment by schroeca** [comment]
Thx for the fast response.  If I understood you correctly I should simply use the git provided in the msys2 package list and everything is fine, correct?

**Comment by Biswa96** [comment]
Yes, you can simply use the git-for-windows provided packages as is.
Or, install git-for-windows and msys2 separately if you want latest packages from msys2.
