### ISSUE TITLE
Go can't find its GOROOT directory

### ISSUE THREAD

**Issue by ognevnydemon** [msys2/MINGW-packages#15364]
### Description / Steps to reproduce the issue

I tried to init go module to make programm in Go, but go.exe says that it couldn't find its library
```
go mod init test.com\test
go: cannot find GOROOT directory: D:\a\msys64\ucrt64\lib\go
```
But I don't have drive D:\ on my computer

### Expected behavior

I expected to see .mod file

### Actual behavior

Actually I receieve a message that Go can't find GOROOT directory

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Try to add this as environment variable `GOROOT=${MINGW_PREFIX}/lib/go`

**Comment by ognevnydemon** [comment]
@Biswa96 after that PowerShell still writes me

**Comment by ognevnydemon** [comment]
@Biswa96 after that PowerShell still writes me
```
go mod init example.com/m
go: cannot find GOROOT directory: D:\a\msys64\ucrt64\lib\go
```
But UCRT64 terminal get it right
```
$ go mod init example.com/m
go: creating new go.mod: module example.com/m
go: to add module requirements and sums:
        go mod tidy

```

**Comment by Biswa96** [comment]
How are you using ucrt64 in powershell?

**Comment by ognevnydemon** [comment]
Because PowerShell is default VS Code terminal

**Comment by ognevnydemon** [comment]
I run UCRT64 separately

**Comment by Biswa96** [comment]
I can not help unless you provide how you are using ucrt64 in powershell or in vscode. There are multiple ways that can be done.

**Comment by ognevnydemon** [comment]
I separately run PS in VS code and UCRT64 mintty terminal
![image](https://user-images.githubusercontent.com/119937608/215512353-3721a679-8056-438d-afaf-61cb72116c93.png)

**Comment by Biswa96** [comment]
In that way, the powershell do not get the variables from ucrt64 terminal environment. You have to initialize the ucrt64 environment in that powershell with `msys2_shell.cmd` script. Some command provided here https://www.msys2.org/docs/terminals/ as an example. Or you have to add a ucrt64 terminal profile in vscode as provided here https://code.visualstudio.com/docs/terminal/profiles.

**Comment by Biswa96** [comment]
Wait a minute, did you add ucrt64 in system's PATH environment variable?

**Comment by ognevnydemon** [comment]
yes

**Comment by ognevnydemon** [comment]
> In that way, the powershell do not get the variables from ucrt64 terminal environment. You have to initialize the ucrt64 environment in that powershell with `msys2_shell.cmd` script. Some command provided here https://www.msys2.org/docs/terminals/ as an example. Or you have to add a ucrt64 terminal profile in vscode as provided here https://code.visualstudio.com/docs/terminal/profiles.

I tried both variants, but it didn't help me at all

**Comment by Biswa96** [comment]
> I tried both variants, but it didn't help me at all

Understood. We can try to add the vscode terminal in the msys2 documentation.

But in the meantime, try to run this command in Powershell. This is the Powershell equivalent command of my first comment https://github.com/msys2/MINGW-packages/issues/15364#issuecomment-1408725659

```
$env:GOROOT='C:\msys64\ucrt64\lib\go'
```

Make sure to use your msys2 installation directory in place of `C:\msys64`.
