### ISSUE TITLE
Add wordcloud

### ISSUE THREAD

**Issue by rivanfebrian123** [msys2/MINGW-packages#15454]
### Package name

wordcloud

### URL for package's homepage

https://github.com/amueller/word_cloud

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [x] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
python-wordcloud package is available in pacman repository, see more here https://packages.msys2.org/base/mingw-w64-python-wordcloud.

**Comment by rivanfebrian123** [comment]
Thank you so much!
