### ISSUE TITLE
llvmlite uses old byval syntax not recognized by llvm15

### ISSUE THREAD

**Issue by sbourdeauducq** [msys2/MINGW-packages#15467]
### Description / Steps to reproduce the issue

Use byval attributes with llvmlite.

### Expected behavior

llvmlite generates correct LLVM IR and the byval attribute is taken into account by LLVM.

### Actual behavior

RuntimeError: LLVM IR parsing error

See https://github.com/m-labs/artiq/issues/2050#issuecomment-1416712307 for details

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-17763

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by revelator** [comment]
llvmlite allways seems to be a bit behind the current LLVM releases, had to patch the former version due to no upstream updates to it for a long time, looks like we hit the same snag again.

**Comment by Biswa96** [comment]
@sbourdeauducq [python-llvmlite](https://packages.msys2.org/base/mingw-w64-python-llvmlite) was updated to 0.40.0 version. Would you like to re-check the issue please?

**Comment by thomasfire** [comment]
> @sbourdeauducq [python-llvmlite](https://packages.msys2.org/base/mingw-w64-python-llvmlite) was updated to 0.40.0 version. Would you like to re-check the issue please?

@Biswa96  I'm currently working on it and testing it with LLVM 14, and it fails on byval/sret tests, expecting `(` after such values

```
RuntimeError: LLVM IR parsing error
python3.10-artiq> <string>:67:57: error: expected '('
python3.10-artiq> define private void @"input.get_tuple"({i32, i32}* sret %".1", i8* %"ARG.ENV") uwtable personality i32 (...)* @"__artiq_personality" !dbg !16
```

**Comment by oltolm** [comment]
Can this be closed now?
