### ISSUE TITLE
opencv: failed to compile

### ISSUE THREAD

**Issue by royqh1979** [msys2/MINGW-packages#15477]
### Description / Steps to reproduce the issue

When I try to build the following code, it fails:
`#include <opencv4/opencv2/opencv.hpp>
int main(){
    return 0;
}`

The error message is :
`g++.exe  "R:/testcv.cpp" -o "R:/testcv.exe" -g3 -pipe -Wall`
`In file included from R:/testcv.cpp:1:`
`D:/msys64/mingw64/include/opencv4/opencv2/opencv.hpp:48:10: fatal error: opencv2/opencv_modules.hpp: No such file or directory`
`   48 | #include "opencv2/opencv_modules.hpp"`
`      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~`

It seems that opencv include files should be placed directly in the include folder, instead of the "opencv4" subfolder.

### Expected behavior

The source file should be compiled successfully.

### Actual behavior

It failed to compile.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> It seems that opencv include files should be placed directly in the include folder, instead of the "opencv4" subfolder.

The opencv4 subfolder is selected by the build system of opencv itself. See the following line in this file https://github.com/opencv/opencv/blob/4.x/cmake/OpenCVInstallLayout.cmake

```cmake
  ocv_update(OPENCV_INCLUDE_INSTALL_PATH       "${CMAKE_INSTALL_INCLUDEDIR}/opencv4")
```

Also the include path should looks like this `#include <opencv2/opencv.hpp>`. See these sample projects as reference https://github.com/opencv/opencv/tree/4.x/samples/cpp. The opencv4 subfolder should be fetched using pkgconfig or cmake files.
