### ISSUE TITLE
Add rime-cli

### ISSUE THREAD

**Issue by Freed-Wu** [msys2/MINGW-packages#15481]
### Package name

rime-cli

### Brief description of package

1. A tool for rime IME
2. [coc-rime](https://github.com/tonyfettes/coc-rime) need it
3. A standard Go project

### URL for package's homepage

https://github.com/puddinging/rime-cli

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by Biswa96** [comment]
The last commit of rime-cli was in Sep 8, 2021. Unmaintained repositories should not be added in package list.

**Comment by Freed-Wu** [comment]
I'll ask if it is maintained.

However, nixOS has this package [rime-cli](https://search.nixos.org/packages?channel=unstable&show=rime-cli&from=0&size=50&sort=relevance&type=packages&query=rime-cli).
