### ISSUE TITLE
[package name] update to <version>

### ISSUE THREAD

**Issue by jwkunz** [msys2/MINGW-packages#15541]
### Package name

mingw-w64-x86_64-hicolor-icon-theme-0.17-2-any.pkg.tar.zst

### Other information that may be useful

I'm not sure how to fix this, but I get this error 

error: mingw-w64-x86_64-hicolor-icon-theme: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/mingw-w64-x86_64-hicolor-icon-theme-0.17-2-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).

**Comment by lazka** [comment]
Can you try this https://www.msys2.org/docs/updating/#potential-issues ?

**Comment by jwkunz** [comment]
Thank you for the quick support to a NOOB
It appears my pacman was stale, and pacman -S lftp allowed me to complete my update with pacman -Syu (which is where I was getting the error message and I was confused).  
You can close this issue

**Comment by lazka** [comment]
> It appears my pacman was stale, and pacman -S lftp allowed me to complete my update with pacman -Syu

Do you mean `pacman-key --refresh-keys` and not `pacman -S lftp`?

**Comment by jwkunz** [comment]
Nope, the refresh keys option was also failing.

**Comment by lazka** [comment]
hm, but `pacman -S lftp` doesn't do anything related, it is just an example for things failing.. I'm confused :)

anyway, glad it worked somehow
