### ISSUE TITLE
cmake-gui not working

### ISSUE THREAD

**Issue by DiegoJArg** [msys2/MINGW-packages#15564]
### Description / Steps to reproduce the issue

```
$ cmake-gui
C:/msys64/mingw32/bin/cmake-gui.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

### Expected behavior

To work as the installer supplied by official cmake distributable does.

.

### Actual behavior

I have used the Dependency Walker to compare both distributables and the one inside msys2 seem to link with qt6.
https://github.com/lucasg/Dependencies

cmake was installed by pacman but didn't installed qt6 as dependency, however the windows distributable does not have that dependency.

![image](https://user-images.githubusercontent.com/25246225/217622677-d9dc70a8-451c-4f54-9be1-c2e1db4cf240.png)

![image](https://user-images.githubusercontent.com/25246225/217622412-fb754e58-d18d-424d-a9a1-c8abac2f37e5.png)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Win 10

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
You need to install qt6-base package manually. The qt6-base package is mentioned as optional dependency in cmake, see https://packages.msys2.org/package/mingw-w64-x86_64-cmake?repo=mingw64
