### ISSUE TITLE
"_Unwind_Resume The Procedure Entry Point Could Not Be Located" error in qt6 moc

### ISSUE THREAD

**Issue by IdrisKalp** [msys2/MINGW-packages#15578]
### Description / Steps to reproduce the issue

Install clang64 subsystem
Upgrade packages
Install mingw-w64-clang-x86_64-qt6-base
Run /clang64/share/qt6/bin/moc.exe

### Expected behavior

It runs

### Actual behavior

It doesn't throw any error on mintty shell. However, when try to run it through Windows Explorer, it throws an error dialogue box. Also copying libunwind.dll aside to moc.exe doesn't help.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22623

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> when try to run it through Windows Explorer, it throws an error dialogue box.

Running through Windows Explorer do not set the PATH variable.

> Also copying libunwind.dll aside to moc.exe doesn't help.

The moc.exe depends on other libraries e.g. pcre2, libc++ etc.

**Comment by IdrisKalp** [comment]
Actually I got this error through using qt6-base while building something other. Custom build qbittorrent against qt6,

`CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- The CXX compiler identification is Clang 15.0.7
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/msys64/clang64/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The following features have been enabled:

 * GUI, Build GUI application (default: ON)
 * WEBUI, Enable built-in HTTP server for remote control (default: ON)
 * QT6, Build with Qt 6 instead of Qt 5 (default: OFF)
 * STACKTRACE, Enable stacktrace support (default: ON)

-- The following features have been disabled:

 * TESTING, Build internal testing suite (default: OFF)
 * VERBOSE_CONFIGURE, Show information about PACKAGES_FOUND and PACKAGES_NOT_FOUND in the configure output (only useful for debugging the CMake build scripts) (default: OFF)

-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenSSL: D:/msys64/clang64/lib/libcrypto.dll.a (found version "3.0.8")
-- Found OpenSSL: D:/msys64/clang64/lib/libcrypto.dll.a (found suitable version "3.0.8", minimum required is "1.1.1")
-- Found ZLIB: D:/msys64/clang64/lib/libz.dll.a (found suitable version "1.2.13", minimum required is "1.2.11")
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Performing Test SNS_SUPPORT
-- Performing Test SNS_SUPPORT - Failed
Warning: plug-in Qt::QSvgIconPlugin is not known to the current Qt installation.
Warning: plug-in Qt::QSvgPlugin is not known to the current Qt installation.
-- Found WrapVulkanHeaders: D:/msys64/clang64/include
-- Configuring done
CMake Error: AUTOMOC for target qbt_app: Test run of "moc" executable "D:/msys64/clang64/share/qt6/bin/moc.exe" failed.
D:/msys64/clang64/share/qt6/bin/moc.exe -h

Exit code 0xc0000139

CMake Generate step failed.  Build files cannot be regenerated correctly.`

**Comment by Biswa96** [comment]
I can not reproduce that issue in my system. The configure command `cmake -DQT6=ON -B bin` ran without any issue. You can try to reinstall the qt6-tools or qt6-base packages. Or run `ntldd /clang64/share/qt6/bin/moc.exe` like commands to find any missing dependent DLLs.
