### ISSUE TITLE
UCRT64/CLANG64 mixed up of headers

### ISSUE THREAD

**Issue by iahung** [msys2/MINGW-packages#15587]
As I recall, everything was fine before I installed the MSYS GCC package to test compile some Cygwin programs. After that, everything failed mysteriously: https://github.com/objeck/objeck-lang/issues/137

Until today, I decided to wipe everything and reinstalling MSYS2, the problem suddenly gone away.

Please have a look at the error: https://github.com/objeck/objeck-lang/files/10694783/error.txt

A quick Google search pointed me to:

https://stackoverflow.com/questions/47942015/compiling-a-c-program-which-uses-sfml-with-mingw-to-port-from-linux-to-windows

Everything made sense now. UCRT64/CLANG64 mixed up with headers of MSYS GCC and caused a real mess. This if confirmed is a serious bug.

**Comment by Biswa96** [comment]
Please provide detailed steps to reproduce the issue.

**Comment by iahung** [comment]
> Please provide detailed steps to reproduce the issue.

I discovered this during building other people's code. I have described what I encountered in details. If you want a minimal example code to reproduce the problem, I can't give you.

**Comment by Biswa96** [comment]
Without any reproducible steps, it is hard to suggest any actual solution. Each msystem are separated into their own directory, see the list here https://www.msys2.org/docs/environments/. So, it is not possible to mix any header file in normal usage. Please check if you are using proper mingw terminal and compiler toolchain.

> A quick Google search pointed me to:
> https://stackoverflow.com/questions/47942015/compiling-a-c-program-which-uses-sfml-with-mingw-to-port-from-linux-to-windows

That thread is about cross-compiling from GNU/Linux and out-of-scope of msys2 environment.

**Comment by iahung** [comment]
> That thread is about cross-compiling from GNU/Linux and out-of-scope of msys2 environment.

Still the same idea: mixing of incompatible headers.

**Comment by Biswa96** [comment]
> mixing of incompatible headers is the cause.

That mixing is done by the user unknowingly, not by msys2 or the compiler toolchain.

**Comment by alvinhochun** [comment]
From [output.txt](https://github.com/objeck/objeck-lang/files/10694784/output.txt) in the linked issue:

```
g++ -m64 -I/usr/include -O3 -Wall -Wno-unused-function -std=c++17 -Wno-dangling-pointer -Wno-maybe-uninitialized -Wno-unknown-pragmas -Wno-unused-function -Wno-unused-variable -Wno-int-to-pointer-cast -Wno-unknown-pragmas -c jit_common.cpp
```

The build system or build script is wrongly passing `-I/usr/include` to the mingw-w64 compiler. This is what's causing the mix-up, not an issue caused by MSYS2.
