### ISSUE TITLE
UCRT and __imp__set_output_format error

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#15607]
So far I have compiled the CalculiX by mingw64 version, now I tried it in UCRT64 but I have this error, any ideas?:

```
 -Wl,--no-whole-archive -o static/ccx_static.exe static/ccx_2.20.o static/ccx_2.20_MT.a -lopenblas -lpastix -lpastix_kernels -lspm -lhwloc  -lspoolesMT -lspooles -lopenblas -lmetis -lscotch -lscotcherrexit -lstdc++ -lltdl -lstarpu-1.3 -lws2_32 -lssp
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/l
d.exe: static/ccx_2.20.o:ccx_2.20.c:(.text.startup+0x3a): undefined reference to `__imp__set_o
utput_format'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile_mingw_static:44: static/ccx_static.exe] Error 1
```

**Comment by lazka** [comment]
https://learn.microsoft.com/en-us/cpp/c-runtime-library/set-output-format?view=msvc-170 suggests `_set_output_format` is not available in newer CRTs (?)

**Comment by Biswa96** [comment]
UCRT does not export the _set_output_format API. This is by-design. Also some info provided in this mail https://sourceforge.net/p/mingw-w64/mailman/message/37801566/
