### ISSUE TITLE
Qt6 documentation is not complete

### ISSUE THREAD

**Issue by milen-prg** [msys2/MINGW-packages#15640]
After installing all packages in MSYS2/mingw64bit for Qt6, in qt Assistant many documentation topics missing. For example in QWidgets sections, no C++ class even for QPushButton etc.

**Comment by Biswa96** [comment]
Did you install the qt6-doc package? This one https://packages.msys2.org/base/mingw-w64-qt6-doc

**Comment by milen-prg** [comment]
Yes and these are also installed:
mingw-w64-x86_64-qt6-tools mingw-w64-x86_64-qt-creator-docs mingw-w64-x86_64-qt-creator mingw-w64-x86_64-qt6-doc

There is many of the documentation, but more is missing. The base part is missing. And I install the official Qt, copy its doc folder and replace the
C:\msys64\mingw64\share\qt6\doc
Then uninstall the official Qt, because its not works proper and uses almost whole disk :)
This works, But I think that this will produce errors and problems with msys2 update etc.

**Comment by milen-prg** [comment]
After new update of the mingw-w64-x86_64-qt6-doc package, all is ok.
