### ISSUE TITLE
Possible issue with GCC static libs

### ISSUE THREAD

**Issue by brisingraerowing** [msys2/MINGW-packages#15650]
### Description / Steps to reproduce the issue

I'm building some things manually for something else I'm doing, and when compiling NCurses I got the following error:

```text
/ucrt64/bin/c++  -o demo.exe ../obj_s/demo.o -Wl,--enable-auto-import  -L../lib -lncurses++w -L../lib -lformw -lmenuw -lpanelw -lncursesw   -pipe -L/ucrt64-python/lib  -lsystre -ltre -lintl -liconv -LD:/PythonBuilds/msys64/ucrt64-python/lib -lpcre2-posix  -Wl,--enable-auto-import  -DHAVE_CONFIG_H -DBUILDING_NCURSES_CXX -I../c++ -I. -I../include -D__USE_MINGW_ANSI_STDIO=1 -I/ucrt64-python/include -D__USE_MINGW_ACCESS -ID:/PythonBuilds/msys64/ucrt64-python/include -D_FILE_OFFSET_BITS=64 -DNDEBUG -DWINVER=0x0501 -DWIN32_LEAN_AND_MEAN -DUSE_WIN32CON_DRIVER -march=x86-64 -mtune=generic -O2 -pipe -static-libgcc -static-libstdc++
D:/PythonBuilds/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/PythonBuilds/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/libgcc_eh.a(unwind-seh.o):(.text+0x3b0): multiple definition of `_Unwind_Resume'; ../lib/libncurses++w.dll.a(libncurses__w6_dll_d000015.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:272: demo.exe] Error 1
make[1]: Leaving directory '/home/baerowing/Sources/ncurses-6.4/c++'
make: *** [Makefile:142: all] Error 2
```

I'm not sure what could cause this particular breakage.

### Expected behavior

Compilation succeeds.

### Actual behavior

Compilation error noted above.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> when compiling NCurses I got the following error

ncurses is being updated in a pull request and it did not fail in CI or in my setup.

There are two paths in your error message D:/PythonBuilds/msys64/ucrt64-python/ and D:/PythonBuilds/msys64/ucrt64/. Check if msys2/mingw programs are not conflicting with any other similar compiler toolchain.

**Comment by brisingraerowing** [comment]
This was actually me being an idiot and failing to remove `-static-libgcc` and `-static-libstdc++` from my `.bashrc` when copying it from another setup where I was building things statically. Derp. Time to rebuild.
