### ISSUE TITLE
How to detect GCC MSVCRT and GCC UCRT64 on source code level?

### ISSUE THREAD

**Issue by iahunq** [msys2/MINGW-packages#15661]
I could check for Cygwin with `__CYGWIN__`. But I don't know how to tell GCC MSVCRT and GCC UCRT64 apart on source code level.

**Comment by Biswa96** [comment]
`#ifdef _UCRT`

**Comment by iahunq** [comment]
> `#ifdef _UCRT`

Does `_UCRT` also defined on MSVC?

**Comment by Biswa96** [comment]
Yes, it seems to be defined in vcruntime.h.

**Comment by Biswa96** [comment]
For general questions like these, please ask them in Discord or Gitter or [Discussions](https://github.com/msys2/MINGW-packages/discussions) page. Any type of msys2 related questions are always welcomed 🤗
