### ISSUE TITLE
lupdate.exe from mingw-w64-clang-x86_64-qt6-static cannot start

### ISSUE THREAD

**Issue by missdeer** [msys2/MINGW-packages#15744]
### Description / Steps to reproduce the issue

Steps:
1. install mingw-w64-clang-x86_64-qt6-static
2. try to start /clang64/qt6-static/bin/lupdate.exe
3. an error message appears: `error while loading shared libraries: api-ms-win-crt-filesystem-l1-1-0.dll: cannot open shared object file: No such file or directory`

### Expected behavior

lupdate.exe runs.

### Actual behavior

an error message pops up, lupdate.exe can't start.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19044

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
I can not reproduce the issue in my system. Here is the screenshot of a working state.

![image](https://user-images.githubusercontent.com/31443074/219843760-d97c179b-de38-4aeb-b6dd-a8c771ec276c.png)

The only things we differ in Windows 10 version. I am running 10.0.19045.xxxx. The "api-ms-win-crt-filesystem-l1-1-0.dll" is a Windows internal entity. It is possible to verify if that entity exists or not. Do you have gcc or clang toolchain installed in msys2 setup?

**Comment by Biswa96** [comment]
Also, would you like to check if all the required DLLs are available in your system using the following command?

```
ntldd /clang64/qt6-static/bin/lupdate.exe
```

It needs mingw-w64-clang-x86_64-ntldd package.

**Comment by missdeer** [comment]
```bash
$ env PATH=/clang64/bin ntldd /clang64/qt6-static/bin/lupdate.exe
        KERNEL32.dll => C:\Windows\SYSTEM32\KERNEL32.dll (0x00000205dd190000)
        libclang-cpp.dll => H:\msys64\clang64\bin\libclang-cpp.dll (0x00000205dd190000)
        libLLVM-15.dll => H:\msys64\clang64\bin\libLLVM-15.dll (0x00000205e0fe0000)
        SHELL32.dll => C:\Windows\SYSTEM32\SHELL32.dll (0x00000205e82d0000)
        USER32.dll => C:\Windows\SYSTEM32\USER32.dll (0x00000205e8a20000)
        ADVAPI32.dll => C:\Windows\SYSTEM32\ADVAPI32.dll (0x00000205e8a20000)
        ole32.dll => C:\Windows\SYSTEM32\ole32.dll (0x00000205e8a20000)
        NETAPI32.dll => C:\Windows\SYSTEM32\NETAPI32.dll (0x00000205dcaf0000)
        AUTHZ.dll => C:\Windows\SYSTEM32\AUTHZ.dll (0x00000205e8ef0000)
        USERENV.dll => C:\Windows\SYSTEM32\USERENV.dll (0x00000205dcaf0000)
        VERSION.dll => C:\Windows\SYSTEM32\VERSION.dll (0x00000205dcaf0000)
        WS2_32.dll => C:\Windows\SYSTEM32\WS2_32.dll (0x00000205dcaf0000)
        WINMM.dll => C:\Windows\SYSTEM32\WINMM.dll (0x00000205dcaf0000)
```

**Comment by missdeer** [comment]
I have searched "api-ms-win-crt-filesystem-l1-1-0.dll" on my disk, this file exists in other applications' directory except system directories.

**Comment by Biswa96** [comment]
Aren't you using the clang64 environment? This would not required then `PATH=/clang64/bin`. 

> I have searched "api-ms-win-crt-filesystem-l1-1-0.dll" on my disk

That DLLs are virtual and redirected to ucrtbase.dll. More at https://learn.microsoft.com/en-us/uwp/win32-and-com/win32-extension-apis#apis-from-api-ms-win-crt-filesystem-l1-1-0dll

**Comment by missdeer** [comment]
Usually I use MSYS environment. Ntldd's output is not changed in CLANG64 environment.

**Comment by Biswa96** [comment]
Please use the clang64 environment. Some programs depends on the relocated paths (here, /clang64 instead of /usr).

**Comment by missdeer** [comment]
Always export MSYSTEM=CLANG64, right ?

**Comment by Biswa96** [comment]
> Always export MSYSTEM=CLANG64, right ?

Nope. Use the clang64 launcher from start menu, the red M icon. The launcher does more than setting MSYSTEM environment variables. More details about those environments can be found here https://www.msys2.org/docs/environments/

**Comment by missdeer** [comment]
But how can I use non-MSYS MSYSTEM tools in Windows batch file?

**Comment by Biswa96** [comment]
> how can I use non-MSYS MSYSTEM tools in Windows batch file?

How are you using it now?

**Comment by missdeer** [comment]
A real batch file:

```bat
set PATH=H:\msys64\clang64\bin
H:\msys64\clang64\bin\cmake.exe %*
```
I use this batch file to run cmake configure, and build project. It may run lupdate.exe, then it failed.

**Comment by Biswa96** [comment]
⚠️ warning: Changing PATH variable may break things.

Does this help `PATH=H:\msys64\clang64\bin;H:\msys64\usr\bin;%PATH%`

**Comment by missdeer** [comment]
> ⚠️ warning: Changing PATH variable may break things.
> 
> Does this help `PATH=H:\msys64\clang64\bin;H:\msys64\usr\bin;%PATH%`

Seemly it works, I could use this solution for the time being. Thanks.

**Comment by Biswa96** [comment]
Glad to help. Some reminders.

The two main ways of using a msys2 environment are -
1. with the launcher. e.g. clang64.exe
2. with msys2_shell.cmd script. e.g. `C:/msys64/msys2_shell.cmd -defterm -here -no-start -clang64` command

Adding msys2 directories in PATH environment variable does not set the full context (e.g. see the output of env). Also doding that may conflict msys2 with cygwin or other mingw environments.
