### ISSUE TITLE
Package mingw-w64-x86_64-opencv with gstreamer

### ISSUE THREAD

**Issue by coolcatco888** [msys2/MINGW-packages#15750]
### Package name

mingw-w64-x86_64-opencv

### Other information that may be useful

I am trying to develop a program using opencv, python and gstreamer.

When I install these packages:
mingw-w64-x86_64-opencv
mingw-w64-x86_64-python-opencv
mingw-w64-x86_64-gstreamer

I notice that gstreamer is not enabled. After doing some digging, online sources say it needs to be compiled. Here is the build information of OpenCV:
```
General configuration for OpenCV 4.7.0 =====================================
  Version control:               9cb92df44

  Extra modules:
    Location (extra):            C:/M/mingw-w64-opencv/src/opencv_contrib-4.7.0/modules
    Version control (extra):     9cb92df44

  Platform:
    Timestamp:                   2023-01-26T00:08:12Z
    Host:                        Windows 10.0.20348 AMD64
    CMake:                       3.25.2
    CMake generator:             Ninja
    CMake build tool:            D:/a/msys64/mingw64/bin/ninja.exe
    Configuration:               Release
    
  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES (find_package)
      avcodec:                   YES (58.134.100)
      avformat:                  YES (58.76.100)
      avutil:                    YES (56.70.100)
      swscale:                   YES (5.9.100)
      avresample:                NO
    DirectShow:                  YES
 ```

Note that in the Video I/O GSTREAMER YES is not included. I am asking to please build the package to include GSTREAMER. Thank you very much!

**Comment by Biswa96** [comment]
Wouldn't this create a circular dependency? Like this opencv ← gstreamer ← gst-plugins-base ← gst-plugins-bad ← opencv

gst-plugins-bad also needs opencv.

**Comment by revelator** [comment]
as long as it is not a requirement of the main package i think we would be fine ?

**Comment by Biswa96** [comment]
@coolcatco888 Would you like to test the packages from here https://github.com/msys2/MINGW-packages/actions/runs/4311602117 ?

**Comment by lazka** [comment]
Arch has started to split the libraries and plugins: https://archlinux.org/packages/?q=gst-plugins

We could do the same.

**Comment by Biswa96** [comment]
opencv can not be split based on dependencies. But gst-plugins-base can be separated like gst-plugins-bad. Though I am not sure how to do that properly. Too many dependencies to manage.

**Comment by lazka** [comment]
yeah that's what I mean. and yeah, that doesn't have to be done now, but maybe some improvement for the future.

**Comment by coolcatco888** [comment]
> @coolcatco888 Would you like to test the packages from here https://github.com/msys2/MINGW-packages/actions/runs/4311602117 ?

Sorry for my late reply. I noticed the link gives a 404. How can I test the packages?

Also thanks for working on this!

**Comment by Biswa96** [comment]
opencv packages has been updated with gstreamer support. Just updating packages with `pavman -Syu` command would be enough.
