### ISSUE TITLE
lupdate.exe from mingw-w64-ucrt-x86_64-qt6-static depends on mingw-w64-ucrt-x86_64-clang

### ISSUE THREAD

**Issue by missdeer** [msys2/MINGW-packages#15764]
### Description / Steps to reproduce the issue

Steps:
1. install mingw-w64-ucrt-x86_64-qt6-static but not mingw-w64-ucrt-x86_64-clang
2. run /ucrt64/qt6-static/bin/lupdate.exe
3. failed to start lupdate.exe

### Expected behavior

lupdate.exe could run as expected

### Actual behavior

lupdated.exe failed to start

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19044

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
It is listed as an optional dependency.
