### ISSUE TITLE
Invalid pkg-config --cflags output for Qt6

### ISSUE THREAD

**Issue by loonycyborg** [msys2/MINGW-packages#15801]
### Description / Steps to reproduce the issue

Latest version of Qt6 added .pc files but seems something went wrong when generating them.
`$ pkg-config --cflags Qt6Widgets
-IC:/msys64/mingw64/include/qt6/QtWidgets -IC:/msys64/mingw64/include/qt6 -DQT_WIDGETS_LIB -IC:/msys
64/mingw64/include/qt6/QtCore -IC:/msys64/mingw64/share/qt6/mkspecs/win32-g++ -IC:/msys64/mingw64/in
clude/qt6/QtGui -DQT_GUI_LIB -DQT_CORE_LIB -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -D_WIN
64 -DMINGW_HAS_SECURE_API=1 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -D_UNICODE\>`
This last `-D_UNICODE\>` is most definitely wrong and makes compiler blow up if used in command line.

### Expected behavior

pkg-config generating usable --cflags for Qt6

### Actual behavior

Invalid output from `$ pkg-config --cflags Qt6*`

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by mmuetzel** [comment]
Seems to be caused by a trailing `>` in `/mingw64/lib/pkgconfig/Qt6Platform.pc`:
```
Cflags: -I${mkspecsdir}/win32-g++ -I${includedir} -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -D_WIN64 -DMINGW_HAS_SECURE_API=1 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -D_UNICODE>
```

**Comment by Biswa96** [comment]
This issue was reported in upstream, here https://bugreports.qt.io/browse/QTBUG-103019

**Comment by mmuetzel** [comment]
Should we test `mingw-w64-qt5-base` with the diff that was proposed in the upstream report?
``` diff
--- a/cmake/QtFlagHandlingHelpers.cmake
+++ b/cmake/QtFlagHandlingHelpers.cmake
@@ -269,7 +269,7 @@ function(qt_internal_enable_unicode_defines)
         set(no_unicode_condition
             "$<NOT:$<BOOL:$<TARGET_PROPERTY:QT_NO_UNICODE_DEFINES>>>")
         target_compile_definitions(Platform
-            INTERFACE "$<${no_unicode_condition}:UNICODE;_UNICODE>")
+            INTERFACE "$<${no_unicode_condition}:UNICODE$<SEMICOLON>_UNICODE>")
     endif()
 endfunction()
 ```

**Comment by Biswa96** [comment]
Yeah, sure.

**Comment by Biswa96** [comment]
I have tried that patch but it totally removes `-D_UNICODE` in Qt6Platform.pc file. I have not build the entire qt6-base package though.

**Comment by mmuetzel** [comment]
> I have tried that patch but it totally removes `-D_UNICODE` in Qt6Platform.pc file.

If I understand the comments in the upstream report correctly, that is the intention of that patch. Currently only `UNICODE` is removed by the condition in the generator expression and the remainder (the part after the semicolon `;`) is treated as a separate argument.
The intention seems to be that both `UNICODE` and `_UNICODE` are treated the same and that both are removed on that condition in the generator expression.
