### ISSUE TITLE
Warnings building Emacs master (ac-wrapper, libattr)

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#15819]
### Description / Steps to reproduce the issue

Running `./autogen.sh` prints

```
Checking whether you have the necessary tools...
(Read INSTALL.REPO for more details on building Emacs)
Checking for autoconf (need at least version 2.65) ... ok
Your system has the required tools.
Building aclocal.m4 ...
Running 'autoreconf -fi -I m4' ...
ac-wrapper: autoreconf: warning: auto-detected versions not found ( ); falling back to latest available
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

You can now run './configure'.
```

while running `configure` prints

```
[...]
configure: WARNING: libattr development library was not found or not usable.
configure: WARNING: GNU Emacs will be built without xattr support.
[...]
```

Until a few weeks ago these warnings were not present...

### Expected behavior

.

### Actual behavior

.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

.

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by oscarfv** [comment]
AFAIK `libattr` does not support Windows, so Emacs should not complain about not finding it. You can submit a bug report to Emacs about this. FWIW both warnings look benign to me.

**Comment by angelog0** [comment]
A recent upgrade of `autoconf-wrapper` package could be the origin of the warning emitted by `autogen.sh`. The warning is not present in the build I did on December 6..
