### ISSUE TITLE
wxWidgets3.2 is defining -mthreads in its pkgconfig CLANGARM64 params, but Clang does not support it

### ISSUE THREAD

**Issue by hmartinez82** [msys2/MINGW-packages#15825]
### Description / Steps to reproduce the issue

The C++ flags for wxWidgets returned by `wx-config --cxxflags` contain `-mthreads`, but Clang does not support this command line switch.
This is causing downstream builds that depend on wxWidgets to use `-mthreads` which will fail if `-Werror,-Wunused-command-line-argument` is used: E.g.:

`clang++: error: argument unused during compilation: '-mthreads' [-Werror,-Wunused-command-line-argument]`

### Expected behavior

`wx-config --cxxflags` does not contain `-mthreads` in its  Clang AARCH64 based builds

### Actual behavior

`wx-config --cxxflags` contains `-mthreads` in its  Clang AARCH64 based builds. This is only happening in CLANGARM64. CLANG64 builds don't have `-mthreads` as expected.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment]
Which package did fail to build?

**Comment by hmartinez82** [comment]
@Biswa96 KiCad 😅. My current workaround is to add `-Wno-unused-command-line-argument`  because the project uses `-Werror`
The workaround works for KiCad, but since this a hiccup behavior between CLANG64 and CLANGARM64 I thought it deserved attention.
