### ISSUE TITLE
[python-tifffile] unable to write bigtiff file (hangs at 4GB)

### ISSUE THREAD

**Issue by rlbrott** [msys2/MINGW-packages#15856]
### Unable to write TIFF file larger than 4GB.
After posting on Discord (https://discord.com/channels/792780131906617355/1078393517396729886), I was asked to open an issue on github.

I am trying to write a large TIFF file (bigtiff) using imwrite from tifffile in python.  The file writes up to about 4GB and hangs.  I feel like this might be based on how libtiff was built, maybe?  The type of TIFF I am writing is a numpy array that is about 100000 x 100000 and is and 8 bit grayscale (unit8).

I have tried to do the imwrite on a linux machine and the same code works fine.   And indeed, a colleague with a Windows conda environment also reports success.

I came across this :
https://gist.github.com/jcupitt/ba60e4e1100607d7a5cc9c19e2ec11e8
which seems to indicate some special build flag/config for large files, and wondered if it might be relevant?

Here is example of the imwrite:
```
imwrite("test.tiff", neg, 
        photometric='minisblack', dtype='uint8')
```

TIFF info:
```
$ pacman -Q | grep -i tiff
mingw-w64-x86_64-libtiff 4.5.0-1
mingw-w64-x86_64-python-tifffile 2023.2.3-1
```

### Expected behavior

I expect that the file would write successfully.

### Actual behavior

The write starts successfully, but "hangs" at 4GB.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19042

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No.  I wouldn't now where to start. ;-)

**Comment by Biswa96** [comment]
@kmilos Would you like to look into this issue?

The option in that gist seems to be enabled. See

```
$ grep -i win32 $MINGW_PREFIX/include/tif_config.h
/* define to use win32 IO system */
#define USE_WIN32_FILEIO 1
```

**Comment by cgohlke** [comment]
FWIW, tifffile does not use libtiff.

**Comment by Biswa96** [comment]
Oh, right. I was under the influence of that gist file. So, the issue subject should be with python-tifffile instead of libtiff.

**Comment by kmilos** [comment]
Sorry, no idea where to start on this one...

**Comment by cgohlke** [comment]
Does `with open('test.bin', 'wb') as fh: numpy.zeros((100000, 100000), 'uint8').tofile(fh)` work? That's how tifffile writes the numpy array to the file.

**Comment by rlbrott** [comment]
Further testing indicates that the problem is in numpy itself because numpy.save() also hangs.  I looked at the numpy source and there is a function PyArray_ToFile in `numpy/core/src/multiarray/convert.c` which seems to be the workhorse.  There is a reference to numpy issue 1660 in the code for a workaround to write large files for Win64 at about line 160 or so.  When I build numpy, this check didn't seem to be triggered, so I forced it to compile that section and tofile() worked. I am not sure the right way to fix this, however.

![image](https://user-images.githubusercontent.com/126202783/221967447-4391d6bc-fe1f-4597-855f-8a80b0622cc6.png)

**Comment by cgohlke** [comment]
Does `#if (defined (_MSC_VER) && defined(_WIN64)) || defined (__MINGW64__)` work at https://github.com/numpy/numpy/blob/486878b37fc7439a3b2b87747f50db9b62fea8eb/numpy/core/src/multiarray/convert.c#L159 ?

**Comment by rlbrott** [comment]
Yes, adding the `|| defined (__MINGW64__)` _does_ work.

**Comment by cgohlke** [comment]
@rlbrott: Do you [open a numpy PR](https://github.com/numpy/numpy/pulls)? Looks like I submitted the [original patch for MSVC](https://github.com/numpy/numpy/commit/0baf0ecf378265f69cf8e14e337f26e51d78faa0) in 2011...

**Comment by Biswa96** [comment]
Wouldn't checking `_WIN64` be enough for that? gcc in x86_64 defines both.

```
$ gcc -dM -E - < /dev/null | egrep -i "win64|mingw64"
#define _WIN64 1
#define __WIN64 1
#define WIN64 1
#define __MINGW64__ 1
#define __WIN64__ 1
```

**Comment by cgohlke** [comment]
> Wouldn't checking _WIN64 be enough for that? gcc in x86_64 defines both.

Yes, that should work too.

**Comment by rlbrott** [comment]
> @rlbrott: Do you [open a numpy PR](https://github.com/numpy/numpy/pulls)? Looks like I submitted the [original patch for MSVC](https://github.com/numpy/numpy/commit/0baf0ecf378265f69cf8e14e337f26e51d78faa0) in 2011...

I have not.

**Comment by rlbrott** [comment]
As for opening a numpy PR.  I don't really feel confident doing that.

**Comment by cgohlke** [comment]
No problem. I'll submit a PR.

**Comment by cgohlke** [comment]
I'm not able to reproduce the issue. Installed msys2 and compiled numpy-1.24.2 under the mingw64 console. The test `with open('test.bin', 'wb') as fh: numpy.zeros((100000, 100000), 'uint8').tofile(fh)` succeeds. What am I missing?

**Comment by rlbrott** [comment]
I don't rightly know.  Is it possible that your setup does define the appropriate environment variables somehow?  

If you use the MSYS2 mingw64 pre-built numpy does it still work?

**Comment by cgohlke** [comment]
> If you use the MSYS2 mingw64 pre-built numpy does it still work?

No, it hangs.

**Comment by cbrt64** [comment]
Drive-by hobbyist hacker here, with the resolution I hope you're looking for.

The detective work is already done, i.e. `|| defined (__MINGW64__)` pulls in the "chunking" code as expected. The trick on MSYS2 is to build and install numpy as a package. For future reference, MSYS2's package system is Arch-like, so from a MINGW64 console you can do (see also [the docs](https://www.msys2.org/dev/new-package/)):

```
$ git clone --depth=1 https://github.com/msys2/MINGW-packages.git  # or whatever
$ cd MINGW-packages/mingw-w64-python-numpy/
  ... edit PKGBUILD and patches ...
$ makepkg-mingw -sriL
```

I've built `numpy` locally with and without this patch, and tested with `numpy.zeros().tofile()` as well as the long test from `convert.c`, with the expected results. Would anyone mind if I submitted PRs, here and upstream? I looked and didn't see any.

Notes:

> Wouldn't checking `_WIN64` be enough for that? gcc in x86_64 defines both.

Keep in mind Cygwin's gcc defines `_WIN64`, and they might have a better `fwrite()` to work with, so unilaterally including this on Windows might not be the right thing. Dunno, just thinking out loud.

> When I look in the Task Manager once things stall, python.exe is still using the CPU (2--3% on my system).

What do you have, @rlbrott, like 32 cores?! And I'm stuck here with 4! Lucky! 😄

**Comment by cgohlke** [comment]
> Would anyone mind if I submitted PRs

Go ahead. I have been unable to reproduce this issue in local builds and therefore could not test the patch.

**Comment by Biswa96** [comment]
> Keep in mind Cygwin's gcc defines _WIN64

Then `#if defined(_WIN64) && !defined(__CYGWIN__)` may be better. Just a thought.

**Comment by cbrt64** [comment]
> > Keep in mind Cygwin's gcc defines `_WIN64`
> 
> it does not

Well, that was dumb. For some formerly valid reason I still had `/mingw64/bin` in my main system environment PATH, I have now rectified that with extreme prejudice. Thanks for saying something @lazka.

Although, as surprising as it was to have `_WIN64` (especially with no gcc installed in the first place), I find it just as surprising that Cygwin doesn't "sanitize" its startup environment to get a more consistent OOB *nix experience. Isn't that the point of Cygwin, even more than MSYS2? Whatever, I don't really know what I'm talking about.

**Comment by rlbrott** [comment]
Thanks to everyone for getting this fixed.  This was my first experience doing a bug report or anything github-ish.  All in all, a pleasant experience.
