### ISSUE TITLE
strange behaviour with subprocess.run and os.path.sep in UCRT64 Python

### ISSUE THREAD

**Issue by jdpipe** [msys2/MINGW-packages#15947]
### Description / Steps to reproduce the issue

After being totally confused by the behaviour noted in [issue 1591](https://github.com/msys2/MSYS2-packages/issues/1591), I did some testing. This script, unexpectedly, works as it should both with MSYSTEM set and with MSYSTEM unset (eg in a cmd prompt).

```python
import pathlib
import shutil
import subprocess

p = pathlib.Path("mytest2/")
p.mkdir(parents=True, exist_ok=True)

fp = p / "test.c"
fp2 = p / "test.exe"
with fp.open("w",encoding="utf8") as f:
	f.write("#include<stdio.h>\n")
	f.write('int main(void){fprintf(stderr,"hello from C\\n");return 0;}\n')
print("Compiling...")1591
subprocess.run([shutil.which("gcc"),"-o",fp2,fp],check=True)
print(" found executable?",fp2.exists())
print("Running '%s'...x" %(fp2,))
subprocess.run([fp2])
# subprocess.run([fp2],shell=True)
```

The path separator changes, but somehow subprocess.run figures it out.

***HOWEVER!*** The above script fails if you change the last line to

```python
subprocess.run([fp2],shell=True)
```

and run it within MSYS with `MSYSTEM` defined as normal. It seems that the shell used by MINGW64 Python when MSYS2 is set needs to be modified in some way.

Sometimes, one will want to use `shell=True`, for example to pipe output into a named file. It seems that this behaviour cannot be reliably used because it does not work inside an MSYS prompt.

### Expected behavior

I would expect the script to work even if `shell=True` is added in the second `subprocess.run` call.

### Actual behavior

With UCRT64 Python 3.10.10, and setting `shell=True`, I get:
```
john@WIN-HG6RBDGB9LV UCRT64 ~/testsize
$ python example2.py
Compiling...
 found executable? True
Running 'mytest2/test.exe'...x
'mytest2' is not recognized as an internal or external command,
operable program or batch file.
```

This problem goes away either by running `MSYSTEM= python example2.py` or by running in a `cmd` prompt instead of MSYS.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-20348

### Are you willing to submit a PR?

If I knew where to start...!

**Comment by jdpipe** [comment]
@lazka I suspect this issue is equally applicable with MSYS Python... although I'm not sure about that. How is `subprocess.run(shell=True)` functioning when running `MSYSTEM='MSYS'` Python, as opposed to `MSYSTEM='MINGW64'` Python? Does MSYS Python use `sh` automatically, perhaps?

**Comment by lazka** [comment]
Yeah, I guess that is https://github.com/msys2-contrib/cpython-mingw/commit/46604a992466e0ed8085c7c791a4b5ae605dc689

**Comment by lazka** [comment]
Oh, that's just cmd.exe not allowing slashes in paths for the program to execute if the path is relative. So the behaviour is expected

I'd just try to avoid `shell=True` if I were you :)
