### ISSUE TITLE
ffmpeg 6.0

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#15958]
Let's wait for Arch to figure out how painful this is first: https://archlinux.org/todo/ffmpeg-60/

**Comment by lazka** [comment]
Arch is done more or less, and things look good: https://archlinux.org/todo/ffmpeg-60/

**Comment by Biswa96** [comment]
Should there be ffmpeg5.1 package like ffmpeg4.4?

**Comment by lazka** [comment]
Ideally we wouldn't need it. I'm not sure about external users.

**Comment by lazka** [comment]
Done in #16070

**Comment by lazka** [comment]
In the repo now
