### ISSUE TITLE
mesa: vulkan driver manifest files have wrong library_path

### ISSUE THREAD

**Issue by kasper93** [msys2/MINGW-packages#16065]
### Description / Steps to reproduce the issue

For example `/clang64/share/vulkan/icd.d/lvp_icd.x86_64.json` contains `"library_path": "\\clang64\\bin\\vulkan_lvp.dll"` which fails to load. Manually changing this to absolute path `C:/MSYS/clang64/bin/vulkan_lvp.dll` fixes the problem.

To reproduce you can use vulkaninfo or anything else using vulkan.
```
VK_ICD_FILENAMES="${MINGW_PREFIX}/share/vulkan/icd.d/lvp_icd.x86_64.json" vulkaninfo
```
all files in `icd.d` are affected.

I see there is some patching for `radeon_icd*.json`, but it is outdated and doesn't do anything.

/CC @pal1000

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment]
Is there any other program which can also reproduce the issue? Wondering, should this path relocation issue be fixed in mesa or in vulkaninfo program?

**Comment by kasper93** [comment]
> Is there any other program which can also reproduce the issue? Wondering, should this path relocation issue be fixed in mesa or in vulkaninfo program?

`vulkaninfo` is only an example. Any vulkan application is affected. It is `vulkan-loader` who is loading the driver.

So one approach is to do path relocation in `vulkan-loader`, another produce .json files with absolute paths. I don't really know what is that way MSYS2 handles issues like that in general.

**Comment by driver1998** [comment]
It seems that vulkan-loader can resolve relative path, relate to the location of icd json.
So something like '../../../bin/vulkan_lvp.dll' would make more sense?

I don't think you would want to add cygwin path handling inside mingw vulkan-loader.

**Comment by Biswa96** [comment]
There are two possible ways
1. Use pathtools like function in vulkan-loader, like in curl, openssl etc.
2. Use install script to change the path in that .json file.

**Comment by lb90** [comment]
Does a similar issue exist for OpenCL?

**Comment by pal1000** [comment]
OpenCL ICD loader works with ICD DLL files directly so not really.

**Comment by d235j** [comment]
This is still broken and prevents LLVMPipe and other Vulkan drivers from working.

**Comment by pal1000** [comment]
We probably need to replicate this code from PKGBULD for the other Vulkan drivers:

````
# Fix JSON for RADV
  if compgen -G "${pkgdir}${MINGW_PREFIX}/share/vulkan/icd.d/radeon_icd*.json" > /dev/null; then
    sed -e "s|./vulkan_radeon|${MINGW_PREFIX}/bin/libvulkan_radeon|g" \
      -i $(find ${pkgdir}${MINGW_PREFIX}/share/vulkan/icd.d -name "radeon_icd*.json" -print)
  fi
````

**Comment by lb90** [comment]
Hi! Ideally this should be fixed in Mesa, will take a look

**Comment by lb90** [comment]
Opened https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/27468

**Comment by kasper93** [comment]
Thanks everyone involved for fixing this 👍
