### ISSUE TITLE
Please package python winsdk

### ISSUE THREAD

**Issue by mimi89999** [msys2/MINGW-packages#16088]
Hello
Could you please package https://pypi.org/project/winsdk/ for using the WinRT API in Python? I saw that the `cppwinrt` package was added in https://github.com/msys2/MINGW-packages/pull/14176

**Comment by mimi89999** [comment]
I'm working on packaging it

**Comment by Biswa96** [comment]
Q. Will it install or bundle its own winrt headers? Or can it be configured to use system provided winrt headers? There was a discussion about adding a winrt headers package. So, I am thinking if pywinrt will use that. This way we may prevent any duplicate headers.

**Comment by mimi89999** [comment]
Hello,
The headers in the https://github.com/pywinrt/python-winsdk repo are old and won't build with Clang. However, after updating the headers, I end up with another error that I don't quite know how to fix:
[build_error.txt](https://github.com/msys2/MINGW-packages/files/11019528/build_error.txt)

**Comment by mimi89999** [comment]
Maybe @dlech could help? 🥺

**Comment by dlech** [comment]
Maybe better to wait for the next release? There are a bunch of changes made to the PyWinRT generator tool that haven't been released yet. IIRC, there was something I fixed with regard to a compile error in delegate wrappers.

**Comment by mimi89999** [comment]
Thanks to dlech changes and other changes I made it finally built, but now it fails to link against `onecore` (`lld: error: unable to find library -lonecore`). I'm not quite sure how to solve that.

Also, to have full support, `windows.graphics.capture.interop.h` and `windows.graphics.capture.h` headers would be needed, but I don't see them in mingw.

**Comment by Biswa96** [comment]
How did you compile python-winsdk in mingw? First, I have to change setup.py and CMakeLists.txt for changing compiler and its options. After that, I got many C++ compiler error both with gcc and clang.

**Comment by mimi89999** [comment]
Here are changes I made to the build files: https://github.com/pywinrt/python-winsdk/issues/28#issuecomment-1495736698

You also need to build latest master of https://github.com/pywinrt/pywinrt (can only be built with Windows build tools) and use it to generate the bindings. I just changed the path in `generate.ps1`:
```
diff --git a/generate.ps1 b/generate.ps1
index ce3d6ffe..ea573a83 100644
--- a/generate.ps1
+++ b/generate.ps1
@@ -12,7 +12,7 @@ if (!$skipNugetInstall) {
     nuget install Microsoft.Windows.CppWinRT -Version $cppwinrt_version -ExcludeVersion -OutputDirectory "$nugetPath"
 }

-$pywinrt_exe = "$nugetPath\PyWinRT\bin\pywinrt.exe"
+$pywinrt_exe = "$env:USERPROFILE\git\pywinrt\_build\Windows\x64\Debug\pywinrt.exe"
 $cppwinrt_exe = "$nugetPath\Microsoft.Windows.CppWinRT\bin\cppwinrt.exe"

 $cppwinrt_path = "$projectionPath\cppwinrt"
```

**Comment by mimi89999** [comment]
Since `onecore` is only an umbrella lib, we could work around it by linking against individual libs.

**Comment by dlech** [comment]
> fails to link against `onecore` (`lld: error: unable to find library -lonecore`). I'm not quite sure how to solve that.
> 
> Also, to have full support, `windows.graphics.capture.interop.h` and `windows.graphics.capture.h` headers would be needed, but I don't see them in mingw.

The headers are distributed in https://www.nuget.org/packages/Microsoft.Windows.SDK.CPP and the architecture-specific `onecore.lib` is distributed in https://www.nuget.org/packages/Microsoft.Windows.SDK.CPP.x64 and similar packages.

**Comment by mimi89999** [comment]
Anyway, to quickly get past the header error, you can just delete `pywinrt/winsdk/src/py.Windows.Graphics.Capture.Interop.cpp`.

**Comment by mimi89999** [comment]
I updated the pull request https://github.com/msys2/MINGW-packages/pull/16711 to use the latest release `1.0.0b9`.

**Comment by Biswa96** [comment]
The python-winsdk package is now available in msys2 pacman repository. See this page for further information https://packages.msys2.org/base/mingw-w64-python-winsdk. Thank you all for the contribution ❤️
