### ISSUE TITLE
Would you like a MinGW git?

### ISSUE THREAD

**Issue by Berrysoft** [msys2/MINGW-packages#16091]
### Package name

mingw-w64-git

### Brief description of package

It seems that it is a long history that MSYS2 cannot distribute git-for-windows at last. The git-for-windows project finally decided to pack it themselves, and MSYS2 refused the patches from that project because it was too large and complicated.

Nowadays, git-for-windows project, basically and directly, uses the MSYS2 runtime without (or sometimes with a few) patches. Git also writes a new buildsystem alternative with cmake. It is possible to build a MinGW git again with MSYS2.

I have written a `PKGBUILD` for it, and have use it for more than half a year. The repo is here: https://github.com/Berrysoft/msys-git-for-windows/ . It also contains some other git tools, for example, I also build `git-lfs` myself.

This `PKGBUILD` contains only 4 patches. 3 of them are necessary patches to build for 5 MinGW targets (I cannot test clangarm64). One of them is a patch that wasn't accepted by upstream: https://github.com/git-for-windows/git/pull/3869 , which is about shebang parsing. The upstream maintainers thought that they don't need to parsing *that* correctly because after all they pack all MSYS2 tools themselves, but I need this patch to make it work well with my MSYS2 environment.

I'm now asking that if you, the maintainers of this repo, would like a MinGW git. If so, I'll open a PR based on my `PKGBUILD` and without the customized version string.

I have also found that it is possible to build for CLANGARM64 environment. All additional work is to remove the custom allocator, and use the system `malloc/free`. It could be simply done by removing one code file. I cannot check if it really works as expected, but I know it could be built successfully.

### URL for package's homepage

https://gitforwindows.org/

### Provide a basic test case to validate the package's functionality.

``` bash
$ git --version
```

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

Yes

**Comment by lazka** [comment]
Yes please :)

**Comment by Biswa96** [comment]
> I cannot check if it really works as expected, but I know it could be built successfully.

I have built git in native ARM64 platform (Raspberry Pi 4B). I have not found any issue with. But I do not daily drive it for every task. @hmartinez82 will be interested probably.

**Comment by Berrysoft** [comment]
Thanks to you all. Now I'm going to close this issue because someone doesn't like my solution.
