### ISSUE TITLE
[libvirt] build fails randomly while generating docs

### ISSUE THREAD

**Issue by Biswa96** [msys2/MINGW-packages#16090]
### Description / Steps to reproduce the issue

libvirt fails to build docs randomly. Just enable the docs option or remove `-Ddocs=disabled` option from meson command, if any. This issue was first reported here https://github.com/msys2/MINGW-packages/pull/13426

### Expected behavior

Docs should be build without any issue.

### Actual behavior

The build fails with the errors like following:

```
[503/812] Generating docs/drvnodedev.html with a custom command (wrapped by meson to capture output)
FAILED: docs/drvnodedev.html
"F:/msys64/ucrt64/bin/meson" "--internal" "exe" "--capture" "docs/drvnodedev.html" "--" "F:\msys64\ucrt64\bin/xsltproc.EXE" "--stringparam" "pagesrc" "docs/drvnodedev.rst" "--stringparam" "builddir" "F:/my-MINGW-packages/mingw-w64-libvirt/src/build-UCRT64" "--stringparam" "timestamp" "Tue Mar  7 16:00:29 2023 UTC" "--stringparam" "href_base" "" "--nonet" "../libvirt-9.1.0/docs/site.xsl" "docs/drvnodedev.html.p/drvnodedev.html.in"
[505/812] Generating 'docs/drvqemu.html.p/drvqemu.html.in' (wrapped by meson to capture output).
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
```

Also the build fails with different file in each run. Sometimes, the issue can be workaround by running `meson compile` or `ninja` twice.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
This issue was brought to attention by @1480c1 

@eli-schwartz helped with some meson related issues before. @elmarco also maintains and contributes to virtualization related repositories. They may provide some insights.

**Comment by eli-schwartz** [comment]
The failing command is:
```
"F:/msys64/ucrt64/bin/meson" "--internal" "exe" <more arguments>
```

It fails without emitting any stdout or stderr.

So really, this is just a duplicate of #11864 and related to the fact that python itself sometimes crashes for unknown reasons, non-reproducibly. But it was successfully worked around in CI with 6ff1a1f8a631ab9b243a827e77619dc2f33cb992.

**Comment by Biswa96** [comment]
That workaround doesn't fix this issue with libvirt. I can reproduce this issue in my PC and in CI.

**Comment by Biswa96** [comment]
Understood. Thank you.

Duplicate of https://github.com/msys2/MINGW-packages/issues/11864

**Comment by Biswa96** [comment]
I workaround the issue with `meson compiler || meson compiler -j1` command.

**Comment by Biswa96** [comment]
The workaround was removed in this abe8ecfe72df07fea11c52e3c24889ee53994f2f commit and no longer required after python 3.11 update.
