### ISSUE TITLE
qgis fails to run/start on CLANG64

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#16161]
### Description / Steps to reproduce the issue

launch qgis
```
qgis
```
![image](https://user-images.githubusercontent.com/79349457/224526470-cc897ee9-7bb3-4431-b2f8-06e2fb290e13.png)

I have built it with `options=(!strip debug)`, The only thing I have discovered is that libqgis_core.dll fails to load.

### Expected behavior

run

### Actual behavior

fails to run

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by hmartinez82** [comment]
I found the issue. It's in a static initialization order. 
in qgspluginmanager.h:
```
    static inline QgsSettingsTreeNode *sTreePluginManager = QgsSettingsTree::treeRoot()->createChildNode( QStringLiteral( "plugin-manager" ) );

    static const QgsSettingsEntryBool *settingsAutomaticallyCheckForPluginUpdates;
    static const QgsSettingsEntryBool *settingsAllowExperimental;
    static const QgsSettingsEntryBool *settingsAllowDeprecated;
    static const QgsSettingsEntryVariant *settingsCheckOnStartLastDate;
    static const QgsSettingsEntryStringList *settingsSeenPlugins;

    static inline QgsSettingsTreeNode *sTreeUi = sTreePluginManager->createChildNode( QStringLiteral( "UI" ) );
```
That last line, once replaced with `static inline QgsSettingsTreeNode *sTreeUi = QgsSettingsTree::treeRoot()->createChildNode( QStringLiteral( "UI" ) );` just works :). I think that there's no guarantee that that the initialization of `sTreePluginManager`  occurs before? Or do the C++ rules mandate that static initialization here is in order and CLANG is failing the mandate?
