### ISSUE TITLE
Emacs: Unnecessary call of ./autogen.sh 

### ISSUE THREAD

**Issue by dr-scsi** [msys2/MINGW-packages#16197]
Hi all,

MSYS2 builds and distributes Emacs from released tarballs.  When doing this, there is actually no need to run:

https://github.com/msys2/MINGW-packages/blob/cd1f3da75d26b98aa4ae911091154cd20617e56b/mingw-w64-emacs/PKGBUILD#L58

`./autogen.sh` is needed when one is building Emacs from the repo.  I think the line above can be deleted.

**Comment by lazka** [comment]
Many of our packages require a regen to build with clang.

**Comment by dr-scsi** [comment]
@lazka - Thanks for your response and closing the report.
