### ISSUE TITLE
neovim copy using clip.exe not working on mingw64

### ISSUE THREAD

**Issue by sueyllam** [msys2/MINGW-packages#16267]
To make nvim work with the system clipboard, I followed the example for WSL in the help of neovim by defining g:clipbpard as provider. Paste seems to work fine but copy is not working at all and any yanking or deletion does not change the system clipboard...

**Comment by Biswa96** [comment]
@techie-guy Could you also reproduce this issue? I'm not familiar with the use cases.

**Comment by sueyllam** [comment]
I have put the following in my init.vim file:
`
set clipboard+=unnamedplus
let g:clipboard = {
		\  'name': 'myClipboard',
		\  'copy': {
		\     '+':   'clip.exe',
		\     '*':   'clip.exe',
		\          },
		\ 'paste': {
		\     '+':   'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
		\     '*':   'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
		\          },
		\     'cache-enabled':0,
		\          }
`
then after invoking nvim I issued the command i
and inserted a random line of f's then exited the command i by hitting <ESC> then yanked the inserted line with the command y.
then into another window of say notepad I hit <CTRL-V> then the yanked line did not appear but what appeared is the previous content of the system clipboard.

**Comment by sueyllam** [comment]
Sorry the code in init.vim was mangled: Here it is

`
set clipboard+=unnamedplus

let g:clipboard = {

		\  'name': 'myClipboard',

		\  'copy': {

		\     '+':   'clip.exe',

		\     '*':   'clip.exe',

		\          },

		\ 'paste': {

		\     '+':   'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',

		\     '*':   'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',

		\          },

		\     'cache-enabled':0,

		\          }


`

**Comment by sueyllam** [comment]
And also, when I copy something from say notepad using <CTRL-C> and then switch to nvim and issue the command p, The just copied text is pasted into nvim. So paste works as expected.

**Comment by techie-guy** [comment]
Works fine for me.
I copied the line from neovim to notepad.

**Comment by sueyllam** [comment]
Well, the paste into neovim works fine for me but the yank ('y') or delete ('dd') kind of freeze out and do not get executed until I press <CTRL-C> and nothing is copied into the system clipboard (its old contents remain unaffected).
I believe something is wrong with clip.exe and msys2 maybe it is a windows issue (I am using windows 11 latest patches). or maybe msys2 which is also up to date.

**Comment by techie-guy** [comment]
> I have put the following in my init.vim file: ` set clipboard+=unnamedplus let g:clipboard = { \ 'name': 'myClipboard', \ 'copy': { \ '+': 'clip.exe', \ '*': 'clip.exe', \ }, \ 'paste': { \ '+': 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))', \ '*': 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))', \ }, \ 'cache-enabled':0, \ } ` then after invoking nvim I issued the command i and inserted a random line of f's then exited the command i by hitting then yanked the inserted line with the command y. then into another window of say notepad I hit then the yanked line did not appear but what appeared is the previous content of the system clipboard.

As you mentioned here

I did the following after adding the code snippet to init.vim:
1. Executing command 'i', typing something and pressing ESC Key. The text that I typed was copied to the document. -> This works fine.

2. Then, Executing command 'y', and selecting the line that is to be yanked. The line gets copied to the clipboard.

I found an issue in the second step. If the line that is to be yanked is the first line in the document, it doesn't copy it. But if it is any other line, it gets copied

Have you tried this in the neovim on the Neovim Release Page?
https://github.com/neovim/neovim/releases/tag/stable

If this issue is present in that neovim too, you should open an issue there.

Also, you can see all the contents of the clipboard by using "Win + V''.

**Comment by techie-guy** [comment]
If you press Ctrl-C, it will hang/exit as it sends the signal to exit, iirc.

**Comment by sueyllam** [comment]
Well definitely the problem is with clip.exe. I did download win32yank and put win32yank.exe in the executable path of the mingw64 shell, then commented out all the g:clipboard lines in init.vim and now everything works like charm.
