### ISSUE TITLE
Is it normal that gcc cannot find a DLL it needs?

### ISSUE THREAD

**Issue by tim-lebedkov** [msys2/MINGW-packages#16298]
### Description / Steps to reproduce the issue

try to compile a file from cmd.exe by running c:\msys2\mingw64\bin\gcc. It fails if c:\msys2\mingw64\bin is not in the PATH. Is this normal? Shouldn't GCC set the PATH while running cc1?

### Expected behavior

the file is compiled

### Actual behavior

![grafik](https://user-images.githubusercontent.com/831371/226172306-1ab9ff87-3883-4f32-aeca-560736554a25.png)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22000

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
This is expected.

**Comment by tim-lebedkov** [comment]
What is the reason for this?

**Comment by tim-lebedkov** [comment]
What is the right thing to do? Set the PATH?

**Comment by MehdiChinoune** [comment]
> What is the right thing to do? Set the PATH?

Exactly

**Comment by mmuetzel** [comment]
> What is the reason for this?

Afaict, on Windows, there is no `rpath` analogue or `LD_PRELOAD` (or other similar tricks you might know from other platforms). Instead, shared libraries are looked for in the current directory and in the directories specified in the `PATH` environment variable. If the required shared libraries cannot be found in any of those directories, execution fails with an error similar to the one you reported.

**Comment by tim-lebedkov** [comment]
Thanks for the explanation. For me it is just strange that starting gcc fails. Copying cc1 to mingw64\bin or setting the environment from gcc or adding mingw64\bin from cc1 to PATH could actually solve this.
