### ISSUE TITLE
lua/lua51 ucrt packages are empty

### ISSUE THREAD

**Issue by Febbe** [msys2/MINGW-packages#16341]
### Description / Steps to reproduce the issue

 Calling 
 ```
 pacman -S mingw-w64-ucrt-x86_64-lua51
 pacman -S mingw-w64-ucrt-x86_64-lua
 ```

`cd C:\msys64\ucrt64\lib\lua\5.4`

### Expected behavior

Lua is installed in the lib directory

### Actual behavior

Directory is empty,
The package here also: 
https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-lua?repo=ucrt64

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
What are the files you expect to be in that `/ucrt64/lib/lua/5.4` directory?

**Comment by Febbe** [comment]
> What are the files you expect to be in that `/ucrt64/lib/lua/5.4` directory?

Both the static and dynamic library files. e.g. lua.lib, liblua.lib / lua.lib.a.

But it seems like, they are in `ucrt/lib`.
It seems like, cmake just can't find it correctly, because it's looking in `/ucrt64/lib/lua/5.4`/`/ucrt64/lib/lua` instead of `/ucrt64/lib`.
Also, *all* pc files expect that I fake rooted the MSYS2 directory.

**Comment by Febbe** [comment]
> Could you provide any example?

I called cmake from powershell with the project gh:xournalpp/xournalpp, but the following CMakeLists.txt should also fail:

```
cmake_minimum_required(VERSION 3.15)
project(Luatest C CXX)
find_package(Lua REQUIRED)
```

it fails with: `[cmake] -- Could NOT find Lua (missing: LUA_LIBRARIES) (found version "5.4.4")`

When I copy the lib file from `/ucrt/lib` to `/ucrt/lib/lua/5.4` it works

**Comment by Biswa96** [comment]
Here is my output without any issue.

```
-- Found Lua: F:/msys64/ucrt64/lib/liblua.dll.a (found version "5.4.4")
```

I have installed mingw-w64-ucrt-x86_64-lua

**Comment by Febbe** [comment]
Sorry for the noise, I think this is only an issue, when someone just adds MSYS to the path or makes a mistake with that, 
instead of using one of the MSYS consoles. 
When I use UCRT64, it also is not a problem at all.

**Comment by Biswa96** [comment]
How did you add msys2 to the PATH?

**Comment by Febbe** [comment]
> How did you add msys2 to the PATH?

I've added `C:\msys64\ucrt64`, `C:\msys64\ucrt64\bin` and `C:\msys64\ucrt64\lib\pkgconfig`.   
    
After adding also `C:\msys64\ucrt64\lib` or using the ucrt environment from msys, it worked.
