### ISSUE TITLE
gtkmm-3.0 ucrt is installed into mingw64 directory instead of ucrt64 dir (using the package search msys2 copy/paste pacman command) - is that on purpose?

### ISSUE THREAD

**Issue by turidan** [msys2/MINGW-packages#16441]

**Comment by Biswa96** [comment]
gtkmm3 ucrt package contains files with /ucrt64 prefix. The file list can be found here https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-gtkmm3?repo=ucrt64. Please re-install the package and explain your issue properly.

**Comment by turidan** [comment]
Reinstalling the gtkmm-3.0 fixed the issue, could have been a typo on my side, apologizes and thanks for the quick reply.
