### ISSUE TITLE
supertux fails to find sdl2 related paths with cmake

### ISSUE THREAD

**Issue by hgntn** [msys2/MINGW-packages#16491]
Everything was sorted out, but finally failed by a bug of `mingw-w64-x86_64-cmake`: https://github.com/SuperTux/supertux/issues/2293

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I can reproduce it in my system. The issue seems to be in the CMakeLists.txt of supertux project. It tries to find sdl2 related files in some unusual ways. Upstreaming the required changes would be hard because the logic has to satisfy vcpkg also.

**Comment by hgntn** [comment]
> Thank you for reporting the issue. I can reproduce it in my system. The issue seems to be in the CMakeLists.txt of supertux project. It tries to find sdl2 related files in some unusual ways. Upstreaming the required changes would be hard because the logic has to satisfy vcpkg also.

The SDL2 part is already have workaround. The subproject part (Squirrel) is the issue. It failed to work on your cmake. See: https://github.com/SuperTux/supertux/issues/2293#issuecomment-1241049356

**Comment by Biswa96** [comment]
> The SDL2 part is already have workaround.

That workaround is not working in mingw. Or workaround isn't even required with SDL2 in mingw or in any other platform, IIRC.

>  The subproject part (Squirrel) is the issue.

That's issue in the logic how supertux finds those paths. I can also see the following error.

```
$ ninja -C bin
ninja: error: 'squirrel/ex/lib/squirrel', needed by 'supertux2.exe', missing and no known rule to make it
ninja: Entering directory `bin'
```

The workaround is to disable that check in mingw. The following change worked in my case.

```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -510,7 +510,7 @@
   -DINSTALL_INC_DIR=include
   -DCMAKE_POSITION_INDEPENDENT_CODE=ON)
 
-if(WIN32)
+if(MSVC)
   add_library(squirrel_lib SHARED IMPORTED)
   set_target_properties(squirrel_lib PROPERTIES IMPORTED_LOCATION "${SQUIRREL_PREFIX}/bin/${CMAKE_SHARED_LIBRARY_PREFIX}squirrel${CMAKE_SHARED_LIBRARY_SUFFIX}")
   set_target_properties(squirrel_lib PROPERTIES IMPORTED_IMPLIB "${SQUIRREL_PREFIX}/lib/squirrel${CMAKE_LINK_LIBRARY_SUFFIX}")
```

Though that fix is not required in latest main branch because it now finds system provided squirrel package.

**Comment by hgntn** [comment]
@Biswa96 Failed with another error:

```
[541/542] Linking CXX static library libsupertux2_lib.a
FAILED: libsupertux2_lib.a
cmd.exe /C "cd . && C:\msys64\mingw64\bin\cmake.exe -E rm -f libsupertux2_lib.a && C:\msys64\mingw64\bin\ar.exe qc libsupertux2_lib.a  @CMakeFiles\supertux2_lib.rsp && C:\msys64\mingw64\bin\ranlib.exe libsupertux2_lib.a && cmd.exe /C "cd /D C:\msys64\home\hgntn\supertux\build && C:\msys64\mingw64\bin\cmake.exe -E copy_directory C:/msys64/home/hgntn/supertux/dependencies64/dll C:/msys64/home/hgntn/supertux/build""
Error copying directory from "C:/msys64/home/hgntn/supertux/dependencies64/dll" to "C:/msys64/home/hgntn/supertux/build".
ninja: build stopped: subcommand failed.
```

**Comment by Biswa96** [comment]
That also classifies in same issue. I shall add a supertux package which can provide the required changes. The patches can not be upstreamed because those specific "dependencies64" directories may be used by other build systems or projects.

**Comment by hgntn** [comment]
> That also classifies in same issue. I shall add a supertux package which can provide the required changes. The patches can not be upstreamed because those specific "dependencies64" directories may be used by other build systems or projects.

Thank you. A supertux package would be awesome.

**Comment by Biswa96** [comment]
> Do you know how to fix this? I think I still want to be able to build it locally on my machine.

I have applied the following changes.

```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -935,13 +935,13 @@
   target_link_options(supertux2 PUBLIC -sEXPORTED_FUNCTIONS=['_main','_set_resolution','_save_config','_onDownloadProgress','_onDownloadFinished','_onDownloadError','_onDownloadAborted'] PUBLIC -sEXPORTED_RUNTIME_METHODS=['ccall','cwrap'] PUBLIC -sEXTRA_EXPORTED_RUNTIME_METHODS=['ccall','cwrap'])
 endif(EMSCRIPTEN)
 
-if(WIN32 AND NOT VCPKG_BUILD)
+if(MSVC AND NOT VCPKG_BUILD)
   ## Copy dlls on windows
   add_custom_command(TARGET supertux2_lib POST_BUILD
     COMMAND ${CMAKE_COMMAND} -E copy_directory
     "${DEPENDENCY_FOLDER}/dll"
     $<TARGET_FILE_DIR:supertux2_lib>)
-endif(WIN32 AND NOT VCPKG_BUILD)
+endif(MSVC AND NOT VCPKG_BUILD)
 
 ## Link supertux binary with squirrel and other libraries
 ```

GitHub seems to have some issues with actions. I shall add a the pull request for the new supertux package.

**Comment by Biswa96** [comment]
That's not enough though. At last you'll get linking error due to the wrong order of libraries. And the patch is not small.

**Comment by Biswa96** [comment]
Would you like to test the packages from here https://github.com/msys2/MINGW-packages/actions/runs/4557298890 ?

**Comment by hgntn** [comment]
> Would you like to test the packages from here https://github.com/msys2/MINGW-packages/actions/runs/4557298890 ?

Worked as good as the official release built by MSVC!
