### ISSUE TITLE
Add QOI

### ISSUE THREAD

**Issue by novomesk** [msys2/MINGW-packages#16558]
### Package name

qoi

### Brief description of package

QOI - The “Quite OK Image Format” for fast, lossless image compression

QOI is just another image format we support in GIMP. It is a format used by some game developers because it is very simple, fast and "quite OK" for them.

In GIMP, we need to have **qoi.h** in include directory, so that compiler can find it by simple include directive.

Debian has package which installs the header and info documents.

https://packages.debian.org/bookworm/all/libqoi-dev/filelist

### URL for package's homepage

https://github.com/phoboslab/qoi

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
I have added a pull request to add the qoi package. Though I am not sure if a single header file need to be packaged.
