### ISSUE TITLE
Add KF5-KNotifyConfig

### ISSUE THREAD

**Issue by kassane** [msys2/MINGW-packages#16581]
### Package name

KNotifyConfig

### Brief description of package

Tried build Konsole on msys2/mingw. But need `KNotifyConfig` and `KNotifyConfigWidget`

```bash
Could NOT find KF5 (missing: NotifyConfig)
```

Tried removing the knotify dependency?
```bash
C:/msys64/home/Matheus/konsole/src/MainWindow.cpp:38:10: fatal error: 'KNotifyConfigWidget' file not found
#include <KNotifyConfigWidget>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
```
The konsole base libraries have been built, but not the executable and its plugins.

### URL for package's homepage

https://invent.kde.org/frameworks/knotifyconfig

### Provide a basic test case to validate the package's functionality.

![knotify-msys2](https://user-images.githubusercontent.com/6756180/229295044-f889229b-9904-4f89-8fa3-1feb0ad56f5f.png)

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment]
I planed to add the knotifyconfig package when konsole will be released. Meanwhile, you can test the package from my fork https://github.com/Biswa96/MINGW-packages/actions

**Comment by kassane** [comment]
> I planed to add the knotifyconfig package when konsole will be released. Meanwhile, you can test the package from my fork https://github.com/Biswa96/MINGW-packages/actions

It works!!
![knotify-msys2](https://user-images.githubusercontent.com/6756180/229295871-bfb05262-7bd8-47a0-b2b3-97c32540fbd2.png)

**Comment by kassane** [comment]
@Biswa96 , would it be possible to pass msys2 in konsole instead of powershell?

**Comment by kassane** [comment]
@Biswa96 , would it be possible to pass msys2 in konsole instead of powershell?

**Comment by Biswa96** [comment]
Yeah, sure. First you have to create a new profile in konsole. In that profile, add the command `C:\\msys64\\msys2_shell.cmd -defterm -no-start -ucrt64`. Make sure that the path matches with your current msys2 installation.
