### ISSUE TITLE
Gtk3 : Full path name in CSS not working

### ISSUE THREAD

**Issue by Kerenok** [msys2/MINGW-packages#16599]
### Description / Steps to reproduce the issue

When trying to set the background of a widget using a CSS provider, the "url" function of the style doesn't support full Windows path name starting with a drive letter.

To reproduce, compile and run the gtk3_background.c program.

### Expected behavior

The window should display a centered image of a red apple over a backgroud of tiled apples. It can be done by replacing the macro MY_IMAGE by "/Users/Kerenoc/Pictures/apple-red.png"

### Actual behavior

With the macro MY_IMAGE set to "C:/Users/Kerenoc/Pictures/apple-red.png", the program only displays a centered apple without any background. It means that Gtk3 is interpreting correctly the full path when using the API to load an image but not when parsing the CSS.

Actual result
![Gtk3_background_bad](https://user-images.githubusercontent.com/18365378/229382886-9e8f6a0c-8d2d-427f-9594-67c74e44f5eb.png)
Expected result
![Gtk3_background_good](https://user-images.githubusercontent.com/18365378/229382893-e2699559-f2c4-46d4-8d16-34d8f0266871.png)
Original image
![apple-red](https://user-images.githubusercontent.com/18365378/229382918-32a8a2b6-66e8-4e88-ad79-dcf889f4612b.png)
C program
[gtk3_background.c.txt](https://github.com/msys2/MINGW-packages/files/11133500/gtk3_background.c.txt)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
I haven't tested your example, but a path is not an URL, you probably need something like `file:///C:/Users/Kerenoc/Pictures/apple-red.png`

**Comment by Kerenok** [comment]
Using the full URI gives the expected results. My bad: I had tried it but with only 2 slashes instead of 3!

The "C:/Users..." format was supported in the old Gtk 3.20.6 runtime I was using previously and I had assumed that this would continue with newer versions of GTK.

Thanks for the help and for reminding to always stick to the standards.
