### ISSUE TITLE
[crt] strip debug information plz

### ISSUE THREAD

**Issue by seudonam** [msys2/MINGW-packages#16600]
### Description / Steps to reproduce the issue

everytime I use gdb in vscode it can't exit after the last line of code, if I strip debug info it's ok!

### Expected behavior

strip debug info

### Actual behavior

crt with debug info

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19044

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
>  gdb in vscode it can't exit after the last line of code

Could you provide the steps to reproduce the issue? And how is that related to debug info in crt (if any)?

**Comment by MehdiChinoune** [comment]
Please, provide a minimal reproducer.

Hundreds (if not thousands) of people uses mingw-w64-gdb to debug their programs and no one has ever complained about encountering an issue like yours or that crt not being stripped!
