### ISSUE TITLE
Luajit module search path is still incorrect

### ISSUE THREAD

**Issue by FractalU** [msys2/MINGW-packages#16618]
### Description / Steps to reproduce the issue

In the commit:

https://github.com/msys2/MINGW-packages/commit/d1e69348d07dd0f401df58f1cc39dc6ee189f0c4

The luajit module search path is still incorrect in that it still uses the '/bin/lua' directory for the '.lua' files and the '/bin' directory for the '.dll' files. Furthemore, the '/share/luajit-2.1.0-beta3' directory is missing.

### Expected behavior

Something like

In [/mingw-w64-luajit/003-lua51-modules-paths.patch](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-luajit/003-lua51-modules-paths.patch)

```
diff -bur LuaJIT-2.1.0-beta3-orig/src/luaconf.h LuaJIT-2.1.0-beta3/src/luaconf.h
--- LuaJIT-2.1.0-beta3-orig/src/luaconf.h	2023-01-26 22:15:03.558193500 -0700
+++ LuaJIT-2.1.0-beta3/src/luaconf.h	2023-01-26 22:15:17.283052500 -0700
@@ -18,12 +18,20 @@
 ** In Windows, any exclamation mark ('!') in the path is replaced by the
 ** path of the directory of the executable file of the current process.
 */
-#define LUA_LDIR	"!\\lua\\"
-#define LUA_CDIR	"!\\"
+
+/* Paths for modules expecting non-jit lua5.1  */
+#define LUA_LDIR	"!\\..\\share\\lua\\5.1\\"
+#define LUA_CDIR	"!\\..\\lib\\lua\\5.1\\"
+
+#define LUAJIT_LDIR	"!\\..\\share\\luajit-2.1.0-beta3\\"
 #define LUA_PATH_DEFAULT \
-  ".\\?.lua;" LUA_LDIR"?.lua;" LUA_LDIR"?\\init.lua;"
+  ".\\?.lua;" LUAJIT_LDIR"?.lua;" LUAJIT_LDIR"?\\init.lua;" \
+              LUA_LDIR"?.lua;"  LUA_LDIR"?\\init.lua;" \
+              LUA_CDIR"?.lua;"  LUA_CDIR"?\\init.lua"
 #define LUA_CPATH_DEFAULT \
   ".\\?.dll;" LUA_CDIR"?.dll;" LUA_CDIR"loadall.dll"
 #else
 /*
 ** Note to distribution maintainers: do NOT patch the following lines!
```

### Actual behavior

In [/mingw-w64-luajit/003-lua51-modules-paths.patch](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-luajit/003-lua51-modules-paths.patch)

```
diff -bur LuaJIT-2.1.0-beta3-orig/src/luaconf.h LuaJIT-2.1.0-beta3/src/luaconf.h
--- LuaJIT-2.1.0-beta3-orig/src/luaconf.h	2023-01-26 22:15:03.558193500 -0700
+++ LuaJIT-2.1.0-beta3/src/luaconf.h	2023-01-26 22:15:17.283052500 -0700
@@ -18,12 +18,20 @@
 ** In Windows, any exclamation mark ('!') in the path is replaced by the
 ** path of the directory of the executable file of the current process.
 */
-#define LUA_LDIR	"!\\lua\\"
-#define LUA_CDIR	"!\\"
+
+/* Paths for modules expecting non-jit lua5.1  */
+#define LUA_LDIR	"!\\..\\share\\lua\\5.1\\"
+#define LUA_CDIR	"!\\..\\lib\\lua\\5.1\\"
+
+#define LUAJIT_LDIR	"!\\lua\\"
+#define LUAJIT_CDIR	"!\\"
 #define LUA_PATH_DEFAULT \
-  ".\\?.lua;" LUA_LDIR"?.lua;" LUA_LDIR"?\\init.lua;"
+  ".\\?.lua;" LUAJIT_LDIR"?.lua;" LUAJIT_LDIR"?\\init.lua;" \
+              LUA_LDIR"?.lua;"  LUA_LDIR"?\\init.lua;" \
+              LUA_CDIR"?.lua;"  LUA_CDIR"?\\init.lua"
 #define LUA_CPATH_DEFAULT \
-  ".\\?.dll;" LUA_CDIR"?.dll;" LUA_CDIR"loadall.dll"
+  ".\\?.dll;" LUAJIT_CDIR"?.dll;" LUA_CDIR"?.dll;" LUAJIT_CDIR"loadall.dll"
+
 #else
 /*
 ** Note to distribution maintainers: do NOT patch the following lines!

```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by Biswa96** [comment]
Could you provide any minimal sample code to reproduce the issue?

**Comment by FractalU** [comment]
Well, you can check the 'package.path' and 'package.cpath' variables in luajit by

```
print("package.path: "..package.path)
print("package.cpath: "..package.cpath)
```
Currently, it outputs
```
path: .\?.lua;C:\msys64\ucrt64\bin\lua\?.lua;C:\msys64\ucrt64\bin\lua\?\init.lua;C:\msys64\ucrt64\bin\..\share\lua\5.1\?.lua;C:\msys64\ucrt64\bin\..\share\lua\5.1\?\init.lua;C:\msys64\ucrt64\bin\..\lib\lua\5.1\?.lua;C:\msys64\ucrt64\bin\..\lib\lua\5.1\?\init.lua
cpath: .\?.dll;C:\msys64\ucrt64\bin\?.dll;C:\msys64\ucrt64\bin\..\lib\lua\5.1\?.dll;C:\msys64\ucrt64\bin\loadall.dll
```
But this is not a correct module search path. It should output
```
path: .\?.lua;C:\msys64\ucrt64\bin\..\share\luajit-2.1.0-beta3\?.lua;C:\msys64\ucrt64\bin\..\share\luajit-2.1.0-beta3\?\init.lua;C:\msys64\ucrt64\bin\..\share\lua\5.1\?.lua;C:\msys64\ucrt64\bin\..\share\lua\5.1\?\init.lua;C:\msys64\ucrt64\bin\..\lib\lua\5.1\?.lua;C:\msys64\ucrt64\bin\..\lib\lua\5.1\?\init.lua
cpath: .\?.dll;C:\msys64\ucrt64\bin\..\lib\lua\5.1\?.dll;C:\msys64\ucrt64\bin\..\lib\lua\5.1\loadall.dll
```
It's difficult to give a reproducible code sample. The module search path is simply misconfigured. I already presented a solution in the 'Expected behavior' section. There is a bug associated with the misconfigured module search path. If you type 'luajit -b' in the terminal, the output is
```
C:/msys64/ucrt64/bin/luajit.exe: unknown luaJIT command or jit.* modules not installed
```
The expected output is
```
Save LuaJIT bytecode: luajit -b[options] input output ...
```
This is due to the fact that the 'C:\msys64\ucrt64\bin\..\share\luajit-2.1.0-beta3' path where the 'jit' directory is located isn't found in the module search path. Additionally, the module search path issue only affects MSYS2 (Windows) and not arch based linux distros. I hope I could help you out. If you have further questions, just ask.

**Comment by Biswa96** [comment]
Thanks for the details. I have compared the result of those variables with ArchLinux luajit package.

**Comment by FractalU** [comment]
I think the expected behavior should be similar to the linux distros. It's because luajit detects that the running system is windows and treats the module search path as if its compiled from visual studio. This is where the search paths got messed up. The MSYS community didn't understand it and wrote a wrong patch. This is what I try to mention. Lua has a similar issue in https://github.com/msys2/MINGW-packages/issues/16638. The difference is that the module search path there contains redundant paths.

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? I have also mentioned the file path changes in the commit message. Please make sure those matches with your expected behavior.

**Comment by FractalU** [comment]
I tested the package from github actions artifacts and checked the commit changes from the pull request. Everything works exactly as expected. You can merge the pull request.

**Comment by FractalU** [comment]
Now lua needs a similar fix for the issue https://github.com/msys2/MINGW-packages/issues/16638.

**Comment by FractalU** [comment]
@sewbacca Thank you for mentioning this. Luajit has switched to rolling releases. The version number has changed from `luajit-2.1.0-beta3` to `luajit-2.1`. Apparently, the module search path patch `003-lua51-modules-paths.patch` has not been updated to adopt this change. Luckily, it can easily be done.

In file `003-lua51-modules-paths.patch` at line 15

Change from
```
+#define LUAJIT_LDIR	"!\\..\\share\\luajit-2.1.0-beta3\\"
```
to
```
+#define LUAJIT_LDIR	"!\\..\\share\\luajit-2.1\\"
```
