### ISSUE TITLE
Add typst

### ISSUE THREAD

**Issue by Freed-Wu** [msys2/MINGW-packages#16612]
### Package name

typst

### Brief description of package

Typst is a new markup-based typesetting system that is designed to be as powerful as LaTeX while being much easier to learn and use.

### URL for package's homepage

https://github.com/typst/typst

### Provide a basic test case to validate the package's functionality.

```typst
#set heading(numbering: "I.")
#set text(
  font: "New Computer Modern"
)

= Introduction
With set rules, you can style
your document.
```

`typst a.typ`

![screenshot](https://typst.app/assets/docs/No_FkEnMJtBBgtXmmMtrWQ.png)

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by Biswa96** [comment]
Hi @Freed-Wu, I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/4615262780
