### ISSUE TITLE
Path issues on several packages

### ISSUE THREAD

**Issue by schoenid** [msys2/MINGW-packages#16629]
### Description / Steps to reproduce the issue

After installing several packages, it's not possible to compile anything.
![image](https://user-images.githubusercontent.com/15383666/229646281-2a0795a8-0a18-499f-9e10-aece72d94ae9.png)

Packages (mingw-w64-x86_64):

- gtk-4,0
- glib-2.0
- graphene-1.0
- gstreamer-1.0
- cairo
- and more ...

Installation:
`pacman -S mingw-w64-x86_64-<package-name>`

Reason:
I assume, that the fact, the packages are unpacked by it's package names causes broken include paths.
![image](https://user-images.githubusercontent.com/15383666/229647839-97e2c785-156c-4b04-a0c0-d24d70010bba.png)

Example:  the file `#include <gtk/gtk.h>` is at `gtk-4.0/gtk/gtk.h`.
If I correct the include path to  `#include <gtk-4.0/gtk/gtk.h>`. then the next problem ocurs:
![image](https://user-images.githubusercontent.com/15383666/229647275-11354a95-801a-4910-9220-cb823b46612f.png)

Conclusions:

1. Either all these libraries are installed in a wrong place,
2. or all libraries do contain wrong path informations.
3. (... or there must be some secret configuration settings ...)

After several hours of trying, I find the system is not easy to handle.

### Expected behavior

After doing the simple steps, described at "https://docs.gtk.org/gtk4/getting_started.html", entering the first code and run the program 
![image](https://user-images.githubusercontent.com/15383666/229648215-26a59405-1aff-400b-aa33-4590cbcf9be6.png)
it should compile and open a simple test-application.

Expected Result:
![image](https://user-images.githubusercontent.com/15383666/229648362-d097e6ee-d2fa-4e2f-8223-179f3248d61f.png)

Code:
`
#include <gtk-4.0/gtk/gtk.h>

static void
activate (GtkApplication* app,
          gpointer        user_data)
{
  GtkWidget *window;

  window = gtk_application_window_new (app);
  gtk_window_set_title (GTK_WINDOW (window), "Window");
  gtk_window_set_default_size (GTK_WINDOW (window), 200, 200);
  gtk_widget_show (window);
}

int
main (int    argc,
      char **argv)
{
  GtkApplication *app;
  int status;

  app = gtk_application_new ("org.gtk.example", G_APPLICATION_DEFAULT_FLAGS);
  g_signal_connect (app, "activate", G_CALLBACK (activate), NULL);
  status = g_application_run (G_APPLICATION (app), argc, argv);
  g_object_unref (app);

  return status;
}
`

### Actual behavior

Only errors (see above ...)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

To complicated for me.

**Comment by schoenid** [comment]
Addition:

```
MSYS ~
$ pkg-config --libs gtk4
Package gtk4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk4.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtk4', required by 'virtual:world', not found
```
What does this mean and how to fix it?

**Comment by schoenid** [comment]
After a manual copy of the many required libraries and files to a destination, where the compiler is looking for, it compiles flawless, but the binding does not work.

Terminal Output:
`
PS E:\Code\temp> gcc $( pkg-config --cflags gtk4 ) -o test test.cpp $( pkg-config --libs gtk4 )            
>>
E:/Code/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\danie\AppData\Local\Temp\ccKDs7hu.o:test.cpp:(.text+0x18): undefined reference to `gtk_application_window_new'
E:/Code/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\danie\AppData\Local\Temp\ccKDs7hu.o:test.cpp:(.text+0x21): undefined reference to `gtk_window_get_type'
E:/Code/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\danie\AppData\Local\Temp\ccKDs7hu.o:test.cpp:(.text+0x32): undefined reference to `__imp_g_type_check_instance_cast'
E:/Code/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\danie\AppData\Local\Temp\ccKDs7hu.o:test.cpp:(.text+0x46): undefined reference to `gtk_window_set_title'
E:/Code/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\danie\AppData\Local\Temp\ccKDs7hu.o:test.cpp:(.text+0x4b): undefined reference to `gtk_window_get_type'
E:/Code/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\danie\AppData\Local\Temp\ccKDs7hu.o:test.cpp:(.text+0x5c): undefined reference to `__imp_g_type_check_instance_cast'
E:/Code/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\danie\AppData\Local\Temp\ccKDs7hu.o:test.cpp:(.text+0x71): undefined reference to `gtk_window_set_default_size'
E:/Code/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\danie\AppData\Local\Temp\ccKDs7hu.o:test.cpp:(.text+0x82): undefined reference to `gtk_widget_set_visible'
E:/Code/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\danie\AppData\Local\Temp\ccKDs7hu.o:test.cpp:(.text+0xb1): undefined reference to `gtk_application_new'
E:/Code/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\danie\AppData\Local\Temp\ccKDs7hu.o:test.cpp:(.text+0xe8): undefined reference to `__imp_g_signal_connect_data'
E:/Code/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\danie\AppData\Local\Temp\ccKDs7hu.o:test.cpp:(.text+0xf1): undefined reference to `__imp_g_application_get_type'
E:/Code/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\danie\AppData\Local\Temp\ccKDs7hu.o:test.cpp:(.text+0x104): undefined reference to `__imp_g_type_check_instance_cast'
E:/Code/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\danie\AppData\Local\Temp\ccKDs7hu.o:test.cpp:(.text+0x11c): undefined reference to `__imp_g_application_run'
E:/Code/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\danie\AppData\Local\Temp\ccKDs7hu.o:test.cpp:(.text+0x12f): undefined reference to `__imp_g_object_unref'
collect2.exe: error: ld returned 1 exit status
PS E:\Code\temp> 
`

**Comment by MehdiChinoune** [comment]
You should use UCRT64 shell/environment programs, I see you are using MSYS shell/environment.
https://www.msys2.org/docs/environments/

**Comment by schoenid** [comment]
@MehdiChinoune 
Oh, thank you!
`MINGW64 ~
$ pkg-config --libs gtk4
-lgtk-4 -lpangowin32-1.0 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lgdk_pixbuf-2.0 -lcairo-gobject -l
cairo -lgraphene-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl
`

That's better.

**Comment by schoenid** [comment]
```
MINGW64 /
$ gcc E:/code/temp/test.cpp -o E:/Code/temp/test.exe -mwindows %GTK4-PKG-CONFIG%
E:/code/temp/test.cpp:1:10: fatal error: gtk/gtk.h: No such file or directory
    1 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
```

**Comment by Biswa96** [comment]
The correct command would be `gcc $( pkg-config --cflags gtk4 ) -o example-0 example-0.c $( pkg-config --libs gtk4 )` as provided in gtk docs.

**Comment by MehdiChinoune** [comment]
You need `cflags`: `pkg-config --cflags gtk4`.

**Comment by schoenid** [comment]
@Biswa96 
Thank yo, but:
`E:\Code\temp> gcc $( pkg-config --cflags gtk4 ) .o test test.cpp $( pkg-config --libs gtk4 )    
test.cpp:1:10: fatal error: gtk/gtk.h: No such file or directory
    1 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.`

**Comment by MehdiChinoune** [comment]
> @Biswa96 Thank yo, but:
> 
> ```
> E:\Code\temp> gcc $( pkg-config --cflags gtk4 ) -o test test.cpp $( pkg-config --libs gtk4 )    
> test.cpp:1:10: fatal error: gtk/gtk.h: No such file or directory
>     1 | #include <gtk/gtk.h>
>       |          ^~~~~~~~~~~
> compilation terminated.
> ```

It doesn't work on CMD.

**Comment by schoenid** [comment]
@Biswa96 

Thank you again.

> It doesn't work on CMD.

... either not in VSCODE terminal ... or the MINGW64 terminal.
MINGW throws no error
```
sd@Radieschen MINGW64 /
$ gcc $( pkg-config --cflags gtk4 ) -o E:/code/temp/test E:/code/temp/test.cpp $( pkg-config --libs gtk4 )

sd@Radieschen MINGW64 /
```
But gives also no result. Just nothing ...  :(

However, I filled up the results from `pkg-config --cflags gtk4` and `pkg-config --libs gtk4` into VSCODEs tasks.json:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: gcc.exe build active file",
            "command": "E:/Code/msys/mingw64/bin/gcc.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "-IE:/Code/msys/mingw64/include/gtk-4.0",
                "-IE:/Code/msys/mingw64/include/pango-1.0",
                "-IE:/Code/msys/mingw64/include",
                "-IE:/Code/msys/mingw64/include/glib-2.0",
                "-IE:/Code/msys/mingw64/lib/glib-2.0/include",
                "-IE:/Code/msys/mingw64/include/harfbuzz",
                "-IE:/Code/msys/mingw64/include/freetype2",
                "-IE:/Code/msys/mingw64/include/libpng16",
                "-IE:/Code/msys/mingw64/include/fribidi",
                "-IE:/Code/msys/mingw64/include/cairo",
                "-IE:/Code/msys/mingw64/include/pixman-1",
                "-IE:/Code/msys/mingw64/include/gdk-pixbuf-2.0",
                "-IE:/Code/msys/mingw64/include/webp",
                "-DLIBDEFLATE_DLL",
                "-IE:/Code/msys/mingw64/include/graphene-1.0",
                "-IE:/Code/msys/mingw64/lib/graphene-1.0/include",
                "-mfpmath=sse",
                "-msse",
                "-msse2",
                "${file}",
                "-LE:/Code/msys/mingw64/lib",
                "-lgtk-4",
                "-lpangowin32-1.0",
                "-lpangocairo-1.0",
                "-lpango-1.0",
                "-lharfbuzz",
                "-lgdk_pixbuf-2.0",
                "-lcairo-gobject",
                "-lcairo",
                "-lgraphene-1.0",
                "-lgio-2.0",
                "-lgobject-2.0",
                "-lglib-2.0",
                "-lintl",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ]
}
```

The Output:
![image](https://user-images.githubusercontent.com/15383666/229714871-2cbb50fa-dbd3-44ec-8ab1-b4594d91a65d.png)

This works.
But WHAT an effort. Is there a simpler method?

**Comment by MehdiChinoune** [comment]
A simpler method is to learn and write Makefile.
Or better learn How to use CMake or Meson.

**Comment by schoenid** [comment]
Summary:

This can clearly not be a standard procedure.
For this 5 minute GTK demonstration I was required, to spend over 16 hours on effort.

The procedure should be:
- Reading the document (1 minute)
- Installing all the stuff (2 minutes)
- Copy/Paste of code and settings (1 minute)
- Run with success (20 seconds)
Finish

I fear, for larger projects I would have to spend hundreds of years, if this goes further in this manner.
So there must be something wrong with the installation procedure.
Anyway, even the documentation lacks the main important things, to make this working on VSCODE.

For Newbies, like me, it's an absolute nightmare.
Should I really go further with MINGW and GTK?

**Comment by schoenid** [comment]
Workaround:

I have to copy all contents of all the folders with "non-conform" content, to the destination described in the header files. For this, a batch job can be made, using a CMD. The batch has to be run after every update.

I mean, who has the idea, to place a header file in a destination, which will never work, because the description in this header file points to a different location?

**Comment by MehdiChinoune** [comment]
Those packages couldn't be used without using pkg-config, directly, in Makefile or through a build-system like meson or cmake.

**Comment by schoenid** [comment]
@MehdiChinoune it's installed like in the description or the tutorials and does not work.

Btw: pkg-config is installed.

**Comment by MehdiChinoune** [comment]
No, they do, just learn how to use pkg-config as you did when you used MINGW64 shell (above)

**Comment by schoenid** [comment]
@MehdiChinoune 

> No, they do, just learn how to use pkg-config as you did when you used MINGW64 shell (above)

It's just not working on my system.
How do you set up this in tasks.json ?

**Comment by schoenid** [comment]
There was an update since yesterday, which installed several changes.
Now it's working with system variables:

```
"args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe",
                "-mwindows",
                "%GTK4-PKG-CONFIG%"
            ],
```
I've got the idea from https://stdin.top/posts/gtk4-on-windows/
Much thanks for this tutorial.

**Comment by schoenid** [comment]
Why this is closed?
The problems are not solved truely.
It's just a workaround.

**Comment by schoenid** [comment]
@Biswa96  Please, give an explanation or an example of how to compile, like in the tutorial, which is not working. I can't learn anything, if the stuff to learn is not working.

**Comment by schoenid** [comment]
```
sd@Radieschen MINGW64 ~
$ gcc -g $( pkg-config --cflags gtk4 ) E:/Code/temp/test.cpp $( pkg-config --libs gtk4 ) -o E:/Code/temp/test.exe

sd@Radieschen MINGW64 ~
```

I found, that the compilation in the MINGW64 environment creates an exe file.
Altough it's not working:
![image](https://user-images.githubusercontent.com/15383666/229895993-0c0c11c5-688b-4ce9-b26c-61a1e6f79295.png)
![image](https://user-images.githubusercontent.com/15383666/229896107-8e181d30-4cff-428a-9e1d-7966f3827dbc.png)
![image](https://user-images.githubusercontent.com/15383666/229896272-f82e8328-51c1-4bea-9336-a2adcb13acb0.png)
![image](https://user-images.githubusercontent.com/15383666/229896363-fd21a7f0-dd87-41b7-be3a-4c8bbe5d8987.png)

**Comment by MehdiChinoune** [comment]
launch the program from MINGW64 shell (type full path).

**Comment by schoenid** [comment]
@Biswa96 Thank you.

The only thing I would like, is to be able, to follow the tutorial https://docs.gtk.org/gtk4/getting_started.html step by step, and this is not working.

I'm trying now, to find the way with VSCODE, which seems to work. I'm doing actually more complex examples and try to realise own ideas. If this does the job, I'm fine.
