### ISSUE TITLE
Qt Creator package broken

### ISSUE THREAD

**Issue by Alex20129** [msys2/MINGW-packages#16646]
### Description / Steps to reproduce the issue

install and update all necessary packages:
1) ``pacman -S mingw-w64-x86_64-qt5-static mingw-w64-x86_64-qt5-base mingw-w64-x86_64-qt5-doc mingw-w64-x86_64-qt5-charts``
2) ``pacman -S mingw-w64-x86_64-qt-creator``
3) ``pacman -Syu``

as the result we getting pretty new ``Qt Creator 10.0.0`` package which cannot detect any Qt installation.
![qt4](https://user-images.githubusercontent.com/11476369/229961120-f2964d7b-207c-4969-96c0-a0a6f78bfc55.png)

### Expected behavior

Qt Creator should detect all kits automatically during installation.

### Actual behavior

There are no working kits, all are broken.
![qt1](https://user-images.githubusercontent.com/11476369/229961194-a0766912-9f75-4341-a496-7550f3f7e07f.png)
![qt2](https://user-images.githubusercontent.com/11476369/229961200-67e104cd-b6cb-445f-ac6d-1131ea38f91a.png)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19043

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
It's not broken at all.
There are some warning ⚠️ That you could ignore (Tell you that the compiler could be incompatible with Qt ...)
Those "red polygon" are expected, because you don't have Qt for other environments.

Unless, It doesn't work. You could ignore those warnings and errors.

**Comment by Alex20129** [comment]
In `Qt Creator 10` from this package, I cannot create a new project. I can't delete bad kits and profiles, and the `link with Qt...` button doesn't work: none of the selected folders match. I temporarily solved the problem by installing `Qt Creator 9` manually.
![qt5](https://user-images.githubusercontent.com/11476369/230010814-abe7f3ab-7747-49a4-ae6f-b302cf7d62f9.png)
![qt6](https://user-images.githubusercontent.com/11476369/230010853-780ee8c7-65a0-4d44-b8d8-ce7321e5fee1.png)

**Comment by Alex20129** [comment]
In `Qt Creator 10` from this package, I cannot create a new project. I can't delete bad kits and profiles, and the link with Qt... button doesn't work: none of the selected folders match. I temporarily solved the problem by installing `Qt Creator 9` manually.
![qt5](https://user-images.githubusercontent.com/11476369/230011668-bb914361-bdb5-44ae-b86c-1f3e44d9c875.png)
![qt6](https://user-images.githubusercontent.com/11476369/230011690-d8fe4cda-1a93-4f0a-9650-0e887d01369f.png)

**Comment by Alex20129** [comment]
sorry i tried to select wrong folders
`C:\msys64\mingw64\bin`
`C:\msys64\mingw64\qt5-static`
`C:\msys64\mingw64\qt5-static\bin`
etc.

Anyway, even when I chose the right folder (`C:\msys64\mingw64`) I still can't create a new project. There is no templates available.

**Comment by Alex20129** [comment]
`Qt Creator 10` itself seems a bit buggy. This little button (should create a new window in the sidebar) causes a crash.
![qt7](https://user-images.githubusercontent.com/11476369/230042370-b7456598-12d1-4ba9-8ff3-ef19bbe92f0a.png)
Now I think the package itself is ok, so the title on this issue is probably incorrect.

**Comment by Alex20129** [comment]
Qt Creator 10 itself seems a bit buggy. This little button (should create a new window in the sidebar) causes a crash.
Now I think the package is ok, so the title on this issue is probably incorrect.

![qt7](https://user-images.githubusercontent.com/11476369/230044690-42327868-9d74-47aa-9c0a-28e12b4b2ac1.png)

**Comment by Alexpux** [comment]
Maybe its Qt6 issue with resolving paths

**Comment by Trilec** [comment]
I do notice this in the build setting with the wrong name in the QTPath:
![image](https://user-images.githubusercontent.com/11463704/232321455-a273c476-f7b6-42b0-9484-5066483ae95b.png)

**Comment by SlySven** [comment]
Oh, so hitting the split window to allow a simultaneous view of a different aspect is a known defect :boom: - I thought it was just me! I did try running `qtcreator` via `gdb` but the results were, sadly, uninformative (though I don't think I had the `.debug` files installed at that point)...

**Comment by MehdiChinoune** [comment]
Maybe It needs a rebuild against Qt 6.5.0?
let's try!
