### ISSUE TITLE
[python] update to 3.10.11

### ISSUE THREAD

**Issue by brisingraerowing** [msys2/MINGW-packages#16670]
### Package name

mingw-w64-python

### New version number

3.10.11

### Other information that may be useful

[Changelog](https://docs.python.org/3.10/whatsnew/changelog.html#changelog)

(Does not seem to be fully updated as of this post)

### Are you willing to submit a PR?

no

**Comment by Biswa96** [comment]
Duplicate of https://github.com/msys2/MINGW-packages/issues/14094
