### ISSUE TITLE
Missing <vulkan/vk_sdk_platform.h>

### ISSUE THREAD

**Issue by iahung** [msys2/MINGW-packages#16732]
I'm trying to build FlingEngine: https://github.com/flingengine/FlingEngine

Failed with:

```
C:/msys64/home/Administrator/FlingEngine/FlingEngine/Graphics/inc/FlingVulkan.h:8:10: fatal error: vulkan/vk_sdk_platform.h: No such file or directory
    8 | #include <vulkan/vk_sdk_platform.h>
```

`pacman -F /mingw64/include/vulkan/vk_sdk_platform.h` returned nothing.

**Comment by Biswa96** [comment]
The vk_sdk_platform.h file does not exist in any upstream vulkan repository. The project is probably using older vulkan repository.

**Comment by Biswa96** [comment]
I have found that file in a archived repository, here https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/include/vulkan/vk_sdk_platform.h
