### ISSUE TITLE
Qt6 Multimedia: cannot open file if file path contains non-ascii characters

### ISSUE THREAD

**Issue by BLumia** [msys2/MINGW-packages#16756]
### Step to reproduce:

1. Install Qt6 with Qt6 multimedia installed (currently `mingw64/mingw-w64-x86_64-qt6-multimedia 6.5.0-1 (mingw-w64-x86_64-qt6)`)
2. Save the following sample code to local, modify the path in `main.cpp` to an existing valid audio file on your machine, and ensure the path doesn't contain any non-ascii characters. (e.g. `R"path(D:\Users\Gary\Downloads\Music\sample.wav)path"`)
3. Compile the following sample program.
4. Run the program, the audio file should be able to play.
5. Re-do step 2, and modify the path to an existing file that contain non-ascii characters. (e.g. `R"path(D:\Users\Gary\Downloads\Music\sample - 副本.wav)path"`)
6. Compile the program again and run the program, now the audio file cannot be played.

### Sample Code:

CMakeLists.txt:

```cmake
cmake_minimum_required (VERSION 3.9.5)

project (qt6mm)

set (CMAKE_AUTOMOC ON)
set (CMAKE_AUTORCC ON)

find_package(QT NAMES Qt6 REQUIRED COMPONENTS Core)
set (QT_MINIMUM_VERSION "6.5")

find_package(Qt${QT_VERSION_MAJOR} ${QT_MINIMUM_VERSION} REQUIRED
    COMPONENTS Widgets Multimedia
)

set (EXE_NAME testbug)
add_executable (${EXE_NAME} main.cpp)
target_link_libraries (${EXE_NAME} Qt::Widgets Qt::Multimedia)

```

main.cpp:

```cpp
#include <QApplication>
#include <QAudioOutput>
#include <QMediaPlayer>

int main(int argc, char* argv[])
{
    QApplication app(argc, argv);

    auto path = QUrl::fromLocalFile(R"path(D:\Users\Gary\Downloads\Music\sample - 副本.wav)path"); // change the path here.

    QMediaPlayer * player = new QMediaPlayer;

    QObject::connect(player, &QMediaPlayer::sourceChanged, [&player](){
        qDebug() << player->source();
    });
    QObject::connect(player, &QMediaPlayer::errorOccurred, [&player](){
        qDebug() << player->errorString();
    });

    player->setAudioOutput(new QAudioOutput);
    player->setSource(path);
    player->play();

    return app.exec();
}
```

\* Note: My system locale is Chinese so not sure if there are file-system or system-locale related encoding issues.
\** Note: I don't have an official Qt installation so currentlt I'm not sure if it's an upstream bug or a MSYS2-only issue.

### Expected behavior

Qt should be able to play the files whatever if the path contain non-ascii characters.

### Actual behavior

Qt multimedia cannot play the files if the path contains non-ascii characters.

If trying to use the above steps to reproduce, the following logs can be seen:

```plain
"Could not open file"
QUrl("file:///D:/Users/Gary/Downloads/Music/sample - 副本.wav")
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Maybe? But I have no idea why it happens.

**Comment by BLumia** [comment]
Seems like an upstream issue. I got the official binary installed via the official Qt Online Installer and installed Qt 6.5.0 MinGW version + Multimedia, and use that to compile the sample project, I'm still be able to reproduce this issue.

Bug reported to upstream: https://bugreports.qt.io/browse/QTBUG-112707

**Comment by lazka** [comment]
> "Could not open file"
> QUrl("file:///D:/Users/Gary/Downloads/Music/sample - 副本.wav")

This doesn't look like a valid URL, so maybe ``QUrl::fromLocalFile` is broken?

**Comment by BLumia** [comment]
> > "Could not open file"
> > QUrl("file:///D:/Users/Gary/Downloads/Music/sample - 副本.wav")
> 
> This doesn't look like a valid URL, so maybe `QUrl::fromLocalFile` is broken?

Don't think so, since Qt's file schemed URL always look like this, and for this issue, `QUrl("file:///D:/Users/Gary/Downloads/Music/sample.wav")` works fine.

**Comment by MehdiChinoune** [comment]
Could you remove spaces and try again.

**Comment by BLumia** [comment]
```
true
"Could not open file"
QUrl("file:///D:/Users/Gary/Downloads/Music/sample副本.wav")
```

I also added a line just below the path line to use QFileInfo to check if the file exists:

```cpp
qDebug() << QFileInfo::exists(path.toLocalFile());
```

And file path/name contain space can be played by QMediaPlayer as well.

**Comment by lazka** [comment]
> Don't think so, since Qt's file schemed URL always look like this, and for this issue, `QUrl("file:///D:/Users/Gary/Downloads/Music/sample.wav")` works fine

yes, but it contains unicode, which isn't allowed in URLs

**Comment by BLumia** [comment]
> but it contains unicode, which isn't allowed in URLs since they need to be encoded and escaped.

I didn't dig in too much but it might be a qDebug() pretty print so the URL itself can be more readable. That probably won't be the source of the problem since spaces (which should be URLEncoded to `%20` but qDebug() prints them as-is) won't cause this issue.

**Comment by lazka** [comment]
ah, I see :)

**Comment by BLumia** [comment]
This issue probably gets addressed in this commit: https://code.qt.io/cgit/qt/qtmultimedia.git/commit/?id=d4f99bdfc22c7f4edb26877a5912a9d5dbb55cfb

So we can confirm this is not a MSYS2/MINGW-packages issue. Should I close this issue or do we need to apply this commit as a patch before the release that contains the fix comes out?

**Comment by Biswa96** [comment]
I would suggest to apply that commit as a patch.

**Comment by Biswa96** [comment]
qt6 has been updated to version 6.5.1. Is this issue still valid?

**Comment by BLumia** [comment]
Can confirm it no longer exists in 6.5.1. Closing :)
