### ISSUE TITLE
zstd: stderr messages are buffered

### ISSUE THREAD

**Issue by KSR-Yasuda** [msys2/MINGW-packages#16763]
### Description / Steps to reproduce the issue

`zstd` stderr message are buffered and does not show query messages.

If output file already exists, `zstd` asks to overwrite it or not.
But the message into `stderr` is buffered, it does not show up immediately and looks as if the program is hang up.

```bash
# Prepare `a.zst` file.
% touch a
% /usr/bin/zstd -o a.zst a
a                    :  (     0 B =>     13 B, a.zst)                          

# Overwrite `a.zst` (by `msys/zstd`)
% /usr/bin/zstd -o a.zst a
zstd: a.zst already exists; overwrite (y/n) ? y
a                    :  (     0 B =>     13 B, a.zst)                          

# Overwrite `a.zst` (by `mingw64/mingw-w64-x86_64-zstd`)
% /mingw64/bin/zstd -o a.zst a
                                                                                # Query message to stderr is not shown until the program ends.
                                                                                # <- [ Input Enter ]
zstd: a.zst already exists; overwrite (y/n) ? Not overwritten  
```

```bash
% pacman -F zstd.exe
mingw64/mingw-w64-x86_64-zstd 1.5.4-1 [installed: 1.5.5-1]
    mingw64/bin/zstd.exe
msys/zstd 1.5.4-1 (libraries) [installed: 1.5.5-1]
    usr/bin/zstd.exe
```

----

It will be the problem below, about stdout / stderr in mintty envof

* https://stackoverflow.com/questions/61426558/why-does-printf-with-n-still-not-flush-on-windows

So other package for MinGW may have the same issue.

Do you have any clever idea to help this?

### Expected behavior

`stderr` message is not buffered to appear immediately.

### Actual behavior

`stderr` message is buffered as above.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by oscarfv** [comment]
`/usr/bin/zstd` is a MSYS2 executable, `/mingw64/bin/zstd` is a MinGW64 executable. I can't reproduce the problem with the later under the mintty MinGW64 shell.

Please report MSYS2 bugs on [its bug tracker](https://github.com/msys2/MSYS2-packages).

If this resolves your question (as far as MINGW-packages is concerned) please close this issue. Thanks.

**Comment by KSR-Yasuda** [comment]
Okay, thank you.
