### ISSUE TITLE
TCL pkgconfig is pointing to the wrong locations

### ISSUE THREAD

**Issue by hmartinez82** [msys2/MINGW-packages#16814]
### Description / Steps to reproduce the issue

TCL's pkgconfig is wrong in all environments. 

### Expected behavior

`pkgconfig` , and `tcl::pkgconfig get libdir,runtime` information queries for TCL return the correct paths

### Actual behavior

In MINGW32 and MINGW64
`pkgconf.exe --path tcl` is returning
`/usr/lib/pkgconfig/tcl.pc`
and 
`pkgconf.exe --libs tcl` is returning
`-L/usr/lib -ltcl8.6 -ltclstub8.6`

In the CLANG based environments, TCL's pkgconfig info is missing.

Running `tcl::pkgconfig get libdir,runtime` in tclsh also has wrong information in all environments (surprisingly only CLANGARM64 has the correct path).

| Env | Output |
|-----|---------|
| MINGW32 | `D:/a/msys64/mingw32/lib` |
| MINGW64 | `/usr/lib` |
| CLANG64 | `D:/a/msys64/clang64/lib` |
| CLANGARM64 | `C:/msys64/clangarm64/lib` |
| UCR64 | `D:/a/msys64/ucrt64/lib` |

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes (I can try)

**Comment by mmuetzel** [comment]
Afaict, the mingw tcl packages don't contain any .pc files. IIUC, the pkg-config commands should fail in those environments. They should only work in the MSYS2 environment. And that is what I observe here:
```
Markus@Markus-PC MINGW64 ~
$ pkgconf -libs tcl
Package tcl was not found in the pkg-config search path.
Perhaps you should add the directory containing `tcl.pc'
to the PKG_CONFIG_PATH environment variable
Package 'tcl', required by 'virtual:world', not found
```
```
Markus@Markus-PC MSYS ~
$ pkgconf -libs tcl
-ltcl8.6 -ltclstub8.6
```

**Comment by hmartinez82** [comment]
Correct.
I checked the makefiles. It seems that only *nix   builds are given a pc file. Arch has the pc file in it's package.
If not pkgconf, what's the correct way to query TCL for it's cflags?

**Comment by Biswa96** [comment]
pkgconfig file can be added in mingw tcl package. But I am not sure if any configure script would get confused with the pkgconfig files in msys2 tcl and mingw tcl packages.

**Comment by mmuetzel** [comment]
IIUC, it should be fine if all packages (msys2 and mingw) had pkg-config files. This shouldn't cause any confusion as long as `PKG_CONFIG_PATH` is set correctly.

**Comment by Biswa96** [comment]
I have added a pull request to add the pkgconfig file in mingw tcl package. Would you like to check the yosys package with it?

The msys2 tcl-devel package now has its pkgconfig file and will not be installed by-default. So, it will not get collide with mingw tcl pkgconfig file.

**Comment by mmuetzel** [comment]
> The msys2 tcl-devel package now has its pkgconfig file and will not be installed by-default. So, it will not get collide with mingw tcl pkgconfig file.

Could the .pc files from different environments really collide?
IIUC, "each" `pkg-config` only looks for .pc files that are installed in its respective environment.
E.g., for me in an MSYS2 environment:
```
MSYS ~
$ pkgconf --variable pc_path pkgconf
/usr/lib/pkgconfig:/usr/share/pkgconfig
```
And in a MINGW64 environment:
```
MINGW64 ~
$ pkg-config --variable pc_path pkg-config
../lib/pkgconfig;../share/pkgconfig
```
In the latter case, the paths are relative to the location of the `pkg-config` executable afaict:
```
MINGW64 ~
$ which pkg-config
/mingw64/bin/pkg-config
```
Additionally, it looks in the paths set in the `PKG_CONFIG_PATH` environment variable. For me that is:
```
MSYS ~
$ echo $PKG_CONFIG_PATH
/usr/lib/pkgconfig:/usr/share/pkgconfig:/lib/pkgconfig
```
```
MINGW64 ~
$ echo $PKG_CONFIG_PATH
/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig
```
So, it should be possible to install the .pc file of the MSYS2 TCL and the MINGW64 TCL at the same time without any risk for them to mix. (Unless the user mingles with `PKG_CONFIG_PATH` manually.)

Am I missing something?

**Comment by Biswa96** [comment]
> Could the .pc files from different environments really collide?

I thought -- what if the build system in the project does some weird thing -- not if msys2 will do something wrong. Also tcl has some shell script to find libraries and headers. There are/were some issues where msys2 things are get included in mingw packages.
