### ISSUE TITLE
openxr : missing validation layer

### ISSUE THREAD

**Issue by sdegrande** [msys2/MINGW-packages#16837]
Could it be possible to build and add the validation layer (https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/main/src/api_layers/README_core_validation.md) in the openxr package ?
It's quite mandatory when developing and debugging an OpenXR code...

Thanks for your great work - before msys2/mingw64 my life as a multi-platform dev was so hard ! :-)

**Comment by Biswa96** [comment]
Thank you for reporting this issue.

* It seems that the mingw package is using OpenXR-SDK repository. The validation layers are installed if OpenXR-SDK-Source repository is used. Would like to make sure that OpenXR-SDK-Source repository should be used for packaging? 
* Do you have any test to make sure that the validation layer is installed in correct directory? There was an issue with install path in vulkan validation layer package. After using the OpenXR-SDK-Source repository, the validation layers are installed like the following paths

```diff
 ucrt64/
 ucrt64/bin/
+ucrt64/bin/api_layers/
+ucrt64/bin/api_layers/XrApiLayer_api_dump.json
+ucrt64/bin/api_layers/XrApiLayer_core_validation.json
+ucrt64/bin/api_layers/libXrApiLayer_api_dump.dll
+ucrt64/bin/api_layers/libXrApiLayer_core_validation.dll
+ucrt64/bin/hello_xr.exe
 ucrt64/bin/libopenxr_loader.dll
+ucrt64/bin/list_json.exe
+ucrt64/bin/openxr_runtime_list.exe
 ucrt64/include/
 ucrt64/include/openxr/
 ucrt64/include/openxr/openxr.h
```

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?
