### ISSUE TITLE
Add zellij

### ISSUE THREAD

**Issue by techie-guy** [msys2/MINGW-packages#16851]
### Package name

zellij

### Brief description of package

A terminal workspace with batteries included

### URL for package's homepage

https://zellij.dev

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [X] CLANGARM64

**Comment by techie-guy** [comment]
Since, tmux doesn't work in other terminals. Can this package be added to MSYS2 MingW.

**Comment by Biswa96** [comment]
It seems that the project does not support Windows platform. Here is a snippet from the build log

```
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> zellij-utils\src\ipc.rs:18:9
   |
18 |     os::unix::io::{AsRawFd, FromRawFd},
   |         ^^^^ could not find `unix` in `os`
```

**Comment by techie-guy** [comment]
Aww, Okay then I'll close this Issue.

**Comment by techie-guy** [comment]
Also, when will this tmux patch be available in msys2?

https://cygwin.com/pipermail/cygwin-patches/2022q4/012092.html

https://github.com/msys2/msys2-runtime/commit/d0bad6996d62f4b897269be4407ca463b2ef30ff

**Comment by dscho** [comment]
> msys2/msys2-runtime@d0bad69

That page says that it's in msys2-runtime v3.5.3.

**Comment by mati865** [comment]
FTR they seem to support Windows now: https://github.com/zellij-org/zellij/issues/316

**Comment by ognevny** [comment]
I'll try to add here next days
