### ISSUE TITLE
Vulkan unusable on 32-bit builds

### ISSUE THREAD

**Issue by kasper93** [msys2/MINGW-packages#17029]
### Description / Steps to reproduce the issue

Simple example:
```
#include <stdio.h>
#include <vulkan/vulkan_core.h>

int main(void) {
    printf("%p\n", &vkCreateDisplayPlaneSurfaceKHR);
    return 0;
}
```
`cc c.c -lvulkan-1 && ./a.exe`
It links, but fails to find functions in dll.

64-bit works as expected.

~~It breaks mpv's CI currently~~
~~You can look at the history, it is recent breakage, was working day or two ago.~~

### Expected behavior

Vulkan is functions are resolved during runtime.

### Actual behavior

Vulkan is functions are not resolved during runtime.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW32_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [X] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
It's working in my Windows 10 x86_64 OS.

```
$ cc test.c -lvulkan-1 && ./a.exe
00081558
```

Are you using 32-bit Windows OS? 

> You can look at the history, it is recent breakage, was working day or two ago.

I can not find the reason. The CI log just showed a help message and an exit code.

**Comment by kasper93** [comment]
> It's working in my Windows 10 x86_64 OS (WoW64 mode).

Ok, so the build is not compatible with the rest of the world. Indeed it works when using `clang32/bin/vulkan-1.dll`, but not when using the gpu driver provided loader, which has priority, because it is in system and PATH is way on the end of dll search order.

To summarize:
`cc c.c -lvulkan-1 && ./a.exe`
**OK**: `/clang32/bin/vulkan-1.dll`
**FAIL**: `C:\Windows\SysWOW64\vulkan-1.dll`

`cl c.c /IC:\VulkanSDK\1.3.243.0\Include /link /LIBPATH:C:\VulkanSDK\1.3.243.0\Lib32 vulkan-1.lib`
**OK**: `C:\Windows\SysWOW64\vulkan-1.dll`

So I think import library/build needs to be fixed to be compatible with official SDK.

> I can not find the reason. The CI log just showed a help message and an exit code.

Yes, forget about it for now, I will report different issue about it. I quickly tested locally and hit different issue apparently.

This on CI prints logs and crashes/errors out. But it doesn't looks like the same issue at all. I need to debug, it is just that I tested locally and hit another issue....

**Comment by Biswa96** [comment]
> So I think import library/build needs to be fixed to be compatible with official SDK.

I have compared the DEF file from the DLL in this official runtime libraries https://vulkan.lunarg.com/sdk/home#windows. It is same as libvulkan-32.def file.

**Comment by lb90** [comment]
Ugh...the problem is that hello_vulkan.exe imports `vkCreateDisplayPlaneSurfaceKHR@16`. msys64\clang32\bin\vulkan-1.dll indeed exports `vkCreateDisplayPlaneSurfaceKHR@16`, but C:\Windows\SysWOW64\vulkan-1.dll exports `vkCreateDisplayPlaneSurfaceKHR` 😕

**Comment by lb90** [comment]
Ah wait, we have a local patch exactly for that: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-vulkan-loader/002-proper-def-files-for-32bit.patch
