### ISSUE TITLE
İnstalling failed

### ISSUE THREAD

**Issue by CanGonulacar** [msys2/MINGW-packages#17036]
### Description / Steps to reproduce the issue

canca@DESKTOP-G7K3EJJ UCRT64 ~
$ pacman -S mingw-w64-ucrt-x86_64-qemu
resolving dependencies...
looking for conflicting packages...
warning: dependency cycle detected:
warning: mingw-w64-ucrt-x86_64-harfbuzz will be installed before its mingw-w64-ucrt-x86_64-freetype dependency
warning: dependency cycle detected:
warning: mingw-w64-ucrt-x86_64-libwebp will be installed before its mingw-w64-ucrt-x86_64-libtiff dependency

Packages (130) mingw-w64-ucrt-x86_64-SDL2-2.26.5-1  mingw-w64-ucrt-x86_64-SDL2_image-2.6.3-1
               mingw-w64-ucrt-x86_64-adobe-source-code-pro-fonts-2.042u+1.062i+1.026vf-1
               mingw-w64-ucrt-x86_64-adwaita-icon-theme-44.0-1
               mingw-w64-ucrt-x86_64-angleproject-2.1.r20724.b26b01a2-2
               mingw-w64-ucrt-x86_64-aom-3.6.0-1  mingw-w64-ucrt-x86_64-atk-2.48.0-1
               mingw-w64-ucrt-x86_64-brotli-1.0.9-5  mingw-w64-ucrt-x86_64-bzip2-1.0.8-2
               mingw-w64-ucrt-x86_64-c-ares-1.19.0-1
               mingw-w64-ucrt-x86_64-ca-certificates-20230311-1
               mingw-w64-ucrt-x86_64-cairo-1.17.8-1
               mingw-w64-ucrt-x86_64-cantarell-fonts-0.303.1-2
               mingw-w64-ucrt-x86_64-capstone-4.0.2-3  mingw-w64-ucrt-x86_64-curl-8.0.1-1
               mingw-w64-ucrt-x86_64-cyrus-sasl-2.1.28-3  mingw-w64-ucrt-x86_64-dav1d-1.1.0-1
               mingw-w64-ucrt-x86_64-egl-headers-1.5.r255.9ab6036-1
               mingw-w64-ucrt-x86_64-expat-2.5.0-1  mingw-w64-ucrt-x86_64-flac-1.4.2-1
               mingw-w64-ucrt-x86_64-fontconfig-2.14.2-1  mingw-w64-ucrt-x86_64-freetype-2.13.0-1
               mingw-w64-ucrt-x86_64-fribidi-1.0.12-1  mingw-w64-ucrt-x86_64-gdbm-1.19-2
               mingw-w64-ucrt-x86_64-gdk-pixbuf2-2.42.10-2  mingw-w64-ucrt-x86_64-gettext-0.21.1-1
               mingw-w64-ucrt-x86_64-giflib-5.2.1-3
               mingw-w64-ucrt-x86_64-gles-headers-3.2.r1005.d127c30-1
               mingw-w64-ucrt-x86_64-glib-networking-2.76.0-1  mingw-w64-ucrt-x86_64-glib2-2.76.1-1
               mingw-w64-ucrt-x86_64-gnutls-3.8.0-1  mingw-w64-ucrt-x86_64-graphene-1.10.8-2
               mingw-w64-ucrt-x86_64-graphite2-1.3.14-2
               mingw-w64-ucrt-x86_64-gsettings-desktop-schemas-44.0-1
               mingw-w64-ucrt-x86_64-gsl-2.7.1-1  mingw-w64-ucrt-x86_64-gst-plugins-base-1.22.2-1
               mingw-w64-ucrt-x86_64-gst-plugins-good-1.22.2-1
               mingw-w64-ucrt-x86_64-gstreamer-1.22.2-1
               mingw-w64-ucrt-x86_64-gtk-update-icon-cache-3.24.37.r22.gf1b6556-2
               mingw-w64-ucrt-x86_64-gtk3-3.24.37.r22.gf1b6556-2
               mingw-w64-ucrt-x86_64-harfbuzz-7.1.0-1
               mingw-w64-ucrt-x86_64-hicolor-icon-theme-0.17-2
               mingw-w64-ucrt-x86_64-highway-1.0.4-1  mingw-w64-ucrt-x86_64-imath-3.1.7-2
               mingw-w64-ucrt-x86_64-iso-codes-4.13.0-1  mingw-w64-ucrt-x86_64-jbigkit-2.1-4
               mingw-w64-ucrt-x86_64-json-glib-1.6.6-3  mingw-w64-ucrt-x86_64-jsoncpp-1.9.5-2
               mingw-w64-ucrt-x86_64-lame-3.100-3  mingw-w64-ucrt-x86_64-lcms2-2.15-1
               mingw-w64-ucrt-x86_64-lerc-4.0.0-1  mingw-w64-ucrt-x86_64-libavif-0.11.1-3
               mingw-w64-ucrt-x86_64-libc++-16.0.2-1  mingw-w64-ucrt-x86_64-libcaca-0.99.beta20-3
               mingw-w64-ucrt-x86_64-libdatrie-0.2.13-1  mingw-w64-ucrt-x86_64-libdeflate-1.18-1
               mingw-w64-ucrt-x86_64-libepoxy-1.5.10-5  mingw-w64-ucrt-x86_64-libffi-3.4.4-1
               mingw-w64-ucrt-x86_64-libidn2-2.3.4-1  mingw-w64-ucrt-x86_64-libjpeg-turbo-2.1.5.1-1
               mingw-w64-ucrt-x86_64-libjxl-0.8.1-1  mingw-w64-ucrt-x86_64-libnfs-5.0.2-1
               mingw-w64-ucrt-x86_64-libogg-1.3.5-1  mingw-w64-ucrt-x86_64-libpng-1.6.39-1
               mingw-w64-ucrt-x86_64-libproxy-0.4.18-2  mingw-w64-ucrt-x86_64-libpsl-0.21.2-4
               mingw-w64-ucrt-x86_64-librsvg-2.56.0-1  mingw-w64-ucrt-x86_64-libshout-2.4.6-2
               mingw-w64-ucrt-x86_64-libslirp-4.7.0-1  mingw-w64-ucrt-x86_64-libsndfile-1.2.0-2
               mingw-w64-ucrt-x86_64-libsoup-2.74.3-1  mingw-w64-ucrt-x86_64-libssh-0.10.4-2
               mingw-w64-ucrt-x86_64-libssh2-1.10.0-2  mingw-w64-ucrt-x86_64-libsystre-1.0.1-4
               mingw-w64-ucrt-x86_64-libtasn1-4.19.0-1  mingw-w64-ucrt-x86_64-libthai-0.1.29-1
               mingw-w64-ucrt-x86_64-libtheora-1.1.1-7  mingw-w64-ucrt-x86_64-libtiff-4.5.0-1
               mingw-w64-ucrt-x86_64-libtre-git-r128.6fb7206-2
               mingw-w64-ucrt-x86_64-libunistring-1.1-1  mingw-w64-ucrt-x86_64-libunwind-16.0.2-1
               mingw-w64-ucrt-x86_64-libusb-1.0.26-1  mingw-w64-ucrt-x86_64-libvorbis-1.3.7-1
               mingw-w64-ucrt-x86_64-libvpx-1.13.0-1  mingw-w64-ucrt-x86_64-libwebp-1.3.0-2
               mingw-w64-ucrt-x86_64-libxml2-2.10.4-1
               mingw-w64-ucrt-x86_64-libyuv-1864.r2426.464c51a0-1
               mingw-w64-ucrt-x86_64-lz4-1.9.4-1  mingw-w64-ucrt-x86_64-lzo2-2.10-2
               mingw-w64-ucrt-x86_64-mpdecimal-2.5.1-1  mingw-w64-ucrt-x86_64-mpg123-1.31.3-1
               mingw-w64-ucrt-x86_64-ncurses-6.4.20230211-1  mingw-w64-ucrt-x86_64-nettle-3.8.1-1
               mingw-w64-ucrt-x86_64-nghttp2-1.52.0-1  mingw-w64-ucrt-x86_64-openexr-3.1.7-1
               mingw-w64-ucrt-x86_64-openssl-3.1.0-1  mingw-w64-ucrt-x86_64-opus-1.4-2
               mingw-w64-ucrt-x86_64-orc-0.4.33-1  mingw-w64-ucrt-x86_64-p11-kit-0.24.1-5
               mingw-w64-ucrt-x86_64-pango-1.50.14-1  mingw-w64-ucrt-x86_64-pcre2-10.42-1
               mingw-w64-ucrt-x86_64-pixman-0.42.2-1  mingw-w64-ucrt-x86_64-python-3.10.11-1
               mingw-w64-ucrt-x86_64-qemu-common-8.0.0-1
               mingw-w64-ucrt-x86_64-qemu-guest-agent-8.0.0-1
               mingw-w64-ucrt-x86_64-qemu-image-util-8.0.0-1
               mingw-w64-ucrt-x86_64-rapidjson-1.1.0-5  mingw-w64-ucrt-x86_64-rav1e-0.6.3-1
               mingw-w64-ucrt-x86_64-readline-8.2.001-6
               mingw-w64-ucrt-x86_64-shared-mime-info-2.2-1  mingw-w64-ucrt-x86_64-snappy-1.1.10-1
               mingw-w64-ucrt-x86_64-speex-1.2.1-1  mingw-w64-ucrt-x86_64-speexdsp-1.2.1-1
               mingw-w64-ucrt-x86_64-spice-0.15.1-2  mingw-w64-ucrt-x86_64-spice-protocol-0.14.4-1
               mingw-w64-ucrt-x86_64-sqlite3-3.41.2-1  mingw-w64-ucrt-x86_64-svt-av1-1.4.1-1
               mingw-w64-ucrt-x86_64-taglib-1.13-1  mingw-w64-ucrt-x86_64-tcl-8.6.12-2
               mingw-w64-ucrt-x86_64-termcap-1.3.1-6  mingw-w64-ucrt-x86_64-tk-8.6.12-1
               mingw-w64-ucrt-x86_64-twolame-0.4.0-2  mingw-w64-ucrt-x86_64-tzdata-2023c-1
               mingw-w64-ucrt-x86_64-usbredir-0.13.0-1
               mingw-w64-ucrt-x86_64-vulkan-headers-1.3.248-1
               mingw-w64-ucrt-x86_64-vulkan-loader-1.3.248-1  mingw-w64-ucrt-x86_64-wavpack-5.6.0-1
               mingw-w64-ucrt-x86_64-wineditline-2.205-3  mingw-w64-ucrt-x86_64-xz-5.4.2-1
               mingw-w64-ucrt-x86_64-qemu-8.0.0-1

Total Download Size:    203.56 MiB
Total Installed Size:  1937.79 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 mingw-w64-ucrt-x86_64-gtk3...     9.8 MiB   558 KiB/s 00:18 [###############################] 100%
 mingw-w64-ucrt-x86_64-open...     7.2 MiB   358 KiB/s 00:21 [###############################] 100%
 mingw-w64-ucrt-x86_64-libr...     7.1 MiB   947 KiB/s 00:08 [###############################] 100%
 mingw-w64-ucrt-x86_64-imat...     4.7 MiB   515 KiB/s 00:09 [###############################] 100%
 mingw-w64-ucrt-x86_64-angl...     3.8 MiB   526 KiB/s 00:07 [###############################] 100%
 mingw-w64-ucrt-x86_64-rav1...    16.2 MiB   471 KiB/s 00:35 [###############################] 100%
 mingw-w64-ucrt-x86_64-glib...     3.8 MiB   704 KiB/s 00:06 [###############################] 100%
 mingw-w64-ucrt-x86_64-aom-...     3.4 MiB  1793 KiB/s 00:02 [###############################] 100%
 mingw-w64-ucrt-x86_64-gett...     3.3 MiB   976 KiB/s 00:03 [###############################] 100%
 mingw-w64-ucrt-x86_64-pyth...    18.4 MiB   456 KiB/s 00:41 [###############################] 100%
 mingw-w64-ucrt-x86_64-iso-...     3.3 MiB   569 KiB/s 00:06 [###############################] 100%
 mingw-w64-ucrt-x86_64-spic...     2.5 MiB  2.29 MiB/s 00:01 [###############################] 100%
 mingw-w64-ucrt-x86_64-qemu...     3.5 MiB   277 KiB/s 00:13 [###############################] 100%
 mingw-w64-ucrt-x86_64-gst-...     2.4 MiB   574 KiB/s 00:04 [###############################] 100%
 mingw-w64-ucrt-x86_64-tcl-...     2.7 MiB   457 KiB/s 00:06 [###############################] 100%
 mingw-w64-ucrt-x86_64-libj...     2.0 MiB   180 KiB/s 00:12 [###############################] 100%
 mingw-w64-ucrt-x86_64-gnut...     2.2 MiB   194 KiB/s 00:12 [###############################] 100%
 mingw-w64-ucrt-x86_64-svt-...     2.9 MiB   151 KiB/s 00:19 [###############################] 100%
 mingw-w64-ucrt-x86_64-qemu...    48.4 MiB   658 KiB/s 01:15 [###############################] 100%
 Total ( 19/130)                 203.6 MiB  2.70 MiB/s 01:15 [###############################] 100%
error: failed retrieving file 'mingw-w64-ucrt-x86_64-qemu-common-8.0.0-1-any.pkg.tar.zst.sig' from mirror.selfnet.de : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.

### Expected behavior

.

### Actual behavior

.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
The issue is expected. Some mirrors are slower than other. Please re-run the pacman command to resume the package installation.
