### ISSUE TITLE
Consider bundling GStreamer plugins differently

### ISSUE THREAD

**Issue by realmazharhussain** [msys2/MINGW-packages#17038]
## The problem

Currently, GStreamer plugins of different categories are bundled together. So, if someone needs all the codecs to be installed they have to install all the plugin bundles `gst-plguins-{base,good,bad,ugly}` which contain the codecs support but also other stuff (significantly more than what that person needs) e.g. GTK3, OpenCV, networking plugins, etc.

For example, I am working on a media player based on LibAdwaita/GTK4 and I need h264, x265, opus, srt (and so on) plugins from the `gst-plugins-bad` package. But when I install `gst-plugins-bad` package, it also installs GTK3 and OpenCV, both of which I don't want.

## Suggested Solution
GStreamer has [merge modules which group plugins by function](https://gstreamer.freedesktop.org/documentation/deploying/windows.html#deploy-only-necessary-packages-using-provided-merge-modules), e.g. codecs, network protocols, playback, etc.

MSYS could try a similar approach. We could
- split each plugin bundle into a separate package for each plugin
- group similar plugins with either meta packages or package groups

For backwards compatibility with any CI/CD scripts/recipes which rely on `gst-plugins-{base,good,bad,ugly}`, we could keep `gst-plugins-{base,good,bad,ugly}` as meta packages.

**Comment by Biswa96** [comment]
Awesome idea. ArchLinux also splits the gtk and opencv plugins in different packages https://archlinux.org/packages/?sort=&q=gst-

Please make sure the package name is same as ArchLinux. Also update the dependencies in the related mingw packages.

**Comment by realmazharhussain** [comment]
> ArchLinux also splits the gtk and opencv plugins in different packages

Just doing this is fine with me but I was hoping we could do more than just that.

If we do everything I suggested, package names won't be the same as Arch but we also won't need to update the dependencies in the related mingw packages.

**Comment by Biswa96** [comment]
I have added a pull request to split the gtk and opencv plugins like ArchLinux does. Would you like to check the packages from GitHub Actions artifacts of that pull request?

**Comment by realmazharhussain** [comment]
I have downloaded the relevant artifacts but I can test for my use case and system only. I'm using UCRT64 MSYSTEM and my app does not need OpenCV and GTK3 plugins.

In other words, I'll only be testing the following packages from the build artifacts

```
mingw-w64-ucrt-x86_64-gst-plugins-bad-1.22.2-2-any.pkg.tar.zst
mingw-w64-ucrt-x86_64-gst-plugins-bad-libs-1.22.2-2-any.pkg.tar.zst
mingw-w64-ucrt-x86_64-gst-plugins-good-1.22.2-2-any.pkg.tar.zst
```

**Comment by realmazharhussain** [comment]
I have provided [some feedback](https://github.com/msys2/MINGW-packages/pull/17155#issuecomment-1550670209) in the PR conversation.
