### ISSUE TITLE
luarocks did not see openssl

### ISSUE THREAD

**Issue by milen-prg** [msys2/MINGW-packages#17041]
### Description / Steps to reproduce the issue

I'm on Windows 10 Pro 64 bit, MSYS2/MINGW64,

The lua packages and mingw-w64-x86_64-openssl are installed, but luarock can't install any lua package with openssl requirements, for example:

mlap@DESKTOP-3SBJLHO MINGW64 ~
$ luarocks install --global luaossl CRYPTO_DIR=/mingw64/
Installing https://luarocks.org/luaossl-20220711-0.src.rock

Error: Could not find library file for CRYPTO
  No file libssleay32.dll in C:/msys64/mingw64
  No file libssleay32.dll in C:/msys64/mingw64/lib
  No file libssleay32.dll in C:/msys64/mingw64/bin
  No file libssleay32.dll.a in C:/msys64/mingw64
  No file libssleay32.dll.a in C:/msys64/mingw64/lib
  No file libssleay32.dll.a in C:/msys64/mingw64/bin
  No file ssleay32.dll.a in C:/msys64/mingw64
  No file ssleay32.dll.a in C:/msys64/mingw64/lib
  No file ssleay32.dll.a in C:/msys64/mingw64/bin
  No file libssleay32.a in C:/msys64/mingw64
  No file libssleay32.a in C:/msys64/mingw64/lib
  No file libssleay32.a in C:/msys64/mingw64/bin
  No file ssleay32.dll in C:/msys64/mingw64
  No file ssleay32.dll in C:/msys64/mingw64/lib
  No file ssleay32.dll in C:/msys64/mingw64/bin
  No file ssleay32.lib in C:/msys64/mingw64
  No file ssleay32.lib in C:/msys64/mingw64/lib
  No file ssleay32.lib in C:/msys64/mingw64/bin
  No file matching libssleay32.so.* in C:/msys64/mingw64
  No file matching libssleay32.so.* in C:/msys64/mingw64/lib
  No file matching libssleay32.so.* in C:/msys64/mingw64/bin
You may have to install CRYPTO in your system and/or pass CRYPTO_DIR or CRYPTO_LIBDIR to the luarock
s command.
Example: luarocks install luaossl CRYPTO_DIR=/usr/local

### Expected behavior

Want to install these luarocks:

luaossl 
luacrypto
lapis

### Actual behavior

mlap@DESKTOP-3SBJLHO MINGW64 ~
$ luarocks install --global luaossl CRYPTO_DIR=/mingw64/
Installing https://luarocks.org/luaossl-20220711-0.src.rock

Error: Could not find library file for CRYPTO
  No file libssleay32.dll in C:/msys64/mingw64
  No file libssleay32.dll in C:/msys64/mingw64/lib
  No file libssleay32.dll in C:/msys64/mingw64/bin
  No file libssleay32.dll.a in C:/msys64/mingw64
  No file libssleay32.dll.a in C:/msys64/mingw64/lib
  No file libssleay32.dll.a in C:/msys64/mingw64/bin
  No file ssleay32.dll.a in C:/msys64/mingw64
  No file ssleay32.dll.a in C:/msys64/mingw64/lib
  No file ssleay32.dll.a in C:/msys64/mingw64/bin
  No file libssleay32.a in C:/msys64/mingw64
  No file libssleay32.a in C:/msys64/mingw64/lib
  No file libssleay32.a in C:/msys64/mingw64/bin
  No file ssleay32.dll in C:/msys64/mingw64
  No file ssleay32.dll in C:/msys64/mingw64/lib
  No file ssleay32.dll in C:/msys64/mingw64/bin
  No file ssleay32.lib in C:/msys64/mingw64
  No file ssleay32.lib in C:/msys64/mingw64/lib
  No file ssleay32.lib in C:/msys64/mingw64/bin
  No file matching libssleay32.so.* in C:/msys64/mingw64
  No file matching libssleay32.so.* in C:/msys64/mingw64/lib
  No file matching libssleay32.so.* in C:/msys64/mingw64/bin
You may have to install CRYPTO in your system and/or pass CRYPTO_DIR or CRYPTO_LIBDIR to the luarock
s command.
Example: luarocks install luaossl CRYPTO_DIR=/usr/local

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
The project is trying to link with older openssl libraries. libeay32.dll and ssleay32.dll was replaced with libcrypto*.dll and libssl*.dll. The issue is not related to luarocks or lua project.

**Comment by milen-prg** [comment]
Thank, you for the information! Therefore I will search for decision in luaossl and lapis projects.
