### ISSUE TITLE
[python-setuptools] --plat-name must be one of ('win32', 'win-amd64', 'win-arm32', 'win-arm64')

### ISSUE THREAD

**Issue by radarhere** [msys2/MINGW-packages#17049]
### Description / Steps to reproduce the issue

I've created a branch at https://github.com/radarhere/Pillow/tree/setuptools_mingw_demo that demonstrates the error with GitHub Actions, from a simple Python script and relatively simple C script.

### Expected behavior

At least not the error that I received.

If I've made a mistake in trying to create a simple demonstration, let me know.

### Actual behavior

https://github.com/radarhere/Pillow/actions/runs/4860227968/jobs/8663795736#step:5:28
> error: --plat-name must be one of ('win32', 'win-amd64', 'win-arm32', 'win-arm64')

Googling, I found the error at https://github.com/pypa/pip/issues/11258, where it was suggested that this is a package problem, not a problem with setuptools.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-20348

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
There is some known issues about incompatibility between mingw python and regular python for Windows. MOre info here https://www.msys2.org/docs/python/. Try to use the mingw python packages only.

**Comment by radarhere** [comment]
I believe I am only using the MinGW Python packages, as if I don't install mingw-w64-x86_64-python3-pip, I get an error that pip is missing.

However, looking at that link, I noticed
> [setuptools](https://github.com/pypa/setuptools) >= 60.0 is currently incompatible with MSYS2. You can set export SETUPTOOLS_USE_DISTUTILS=stdlib to work around the issue. We are currently working on restoring compatibility.

And adding that setting solves the problem! Thanks very much.
