### ISSUE TITLE
avrdude update to 7.1

### ISSUE THREAD

**Issue by aetha** [msys2/MINGW-packages#17055]
### Package name

avrdude

### New version number

7.1

### Other information that may be useful

New version package is available in Arch

**Comment by lazka** [comment]
Just had a (very) quick look:

* upstream moved to https://github.com/avrdudes/avrdude (no release tarballs anymore)
* we need to port to cmake

**Comment by Biswa96** [comment]
avrdude was updated to version 7.3 in this d1530bc6f11195bcf70e77eee19c2fa6cb1dadef commit.
