### ISSUE TITLE
write() has wrong signature?

### ISSUE THREAD

**Issue by kmilos** [msys2/MINGW-packages#17063]
### Description / Steps to reproduce the issue

This is a [conversion warning while building libheif](https://github.com/msys2/MINGW-packages/actions/runs/4880728203/jobs/8708743827#step:11:1408):
```
C:/_/B/src/libheif-1.16.1/libheif/heif.cc:483:51: warning: conversion from 'std::__cxx11::basic_string<char>::size_type' {aka 'long long unsigned int'} to 'unsigned int' may change value [-Wconversion]
    483 |   auto written = write(fd, dump.c_str(), dump.size());
        |                                          ~~~~~~~~~^~
```

### Expected behavior

No warnings, as `man write(2)` gives this signature that matches the arguments above:
```
ssize_t write(int fd, const void *buf, size_t count);
```

### Actual behavior

[HAVE_UNISTD_H is defined](https://github.com/strukturag/libheif/blob/v1.16.1/libheif/heif.cc#L483) as unistd.h is present (mingw-w64-ucrt-x86_64-headers-git 10.0.0.r258.g530c58e17-1), but write() still has this signature which produces the warning:
```
int write(int, const void *, unsigned int);
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19044

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by kmilos** [comment]
> what you are seeing is the expected behavior

Well, not really if unistd.h is advertised....

**Comment by mmuetzel** [comment]
Afaict, `HAVE_UNISTD_H` is set by the configure script of libheif if it found a header with the name `unistd.h`.
Is there a guarantee that the functions declared by including `unistd.h` *must* be POSIX compatible?

**Comment by kmilos** [comment]
> Afaict, HAVE_UNISTD_H is set by the configure script of libheif if it found a header with the name unistd.h.

Correct.

> Is there a guarantee that the functions declared by including `unistd.h` _must_ be POSIX compatible?

What's the point of it otherwise?

**Comment by mmuetzel** [comment]
> What's the point of it otherwise?

Afaict, the main goal is to add support for compiling projects that have been written for POSIX targets with minimum modifications.

**Comment by kmilos** [comment]
Yes, I saw all that, thanks.

While I can fix this on the libheif side (just check for _WIN32 and don't bother w/ unistd.h at all), I'm sorry to say I still don't get the point of unistd.h then...

**Comment by mmuetzel** [comment]
Well: the code compiled with just a warning...
And it's not necessary to arraign in the user code for including `io.h` on Windows instead of `unistd.h` on POSIX platforms.

**Comment by oscarfv** [comment]
> > Afaict, HAVE_UNISTD_H is set by the configure script of libheif if it found a header with the name unistd.h.
> 
> Correct.
> 
> > Is there a guarantee that the functions declared by including `unistd.h` _must_ be POSIX compatible?
> 
> What's the point of it otherwise?

The purpose of `unistd.h` certainly is not to replace functions provided by the MS C runtime with others that implement a different semantics. Trying to do so would open a big can of worms with far worse consequences than displaying some warnings at compile time.

The purpose of having `unistd.h` is to make easier to compile programs... that `#include` `unistd.h.` :)  Maybe it also contains some new definitions not found in the MS C runtime, but that's it.

If this issue is clarified by now, please close this bug report.

**Comment by Biswa96** [comment]
The issue seem to be fixed in upstream. Thanks @kmilos ❤️
