### ISSUE TITLE
Add cling

### ISSUE THREAD

**Issue by goyalyashpal** [msys2/MINGW-packages#17083]
### Package name

cling

### Brief description of package

"Cling - The Interactive C++ Interpreter", basically a REPL for C++

duplicate search:
i tried searching for [org:msys2 cling], and #2541 & #3107 are listed, so, seems cling-git was already there?

[org:msys2 cling]: https://github.com/search?q=org%3Amsys2+cling&type=issues

### URL for package's homepage

https://github.com/root-project/cling

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Not anytime soon, maybe after some months

**Comment by revelator** [comment]
i think we had that package at some point but it was dropped, not sure why though.

**Comment by Biswa96** [comment]
Yeah, cling was removed in this commit https://github.com/msys2/MINGW-packages/commit/446b69f6347ca25c8d599f19c2c0d68c338772eb

**Comment by Freed-Wu** [comment]
cling-git in https://github.com/msys2/MINGW-packages-dev is out-of-date 7 years ago. Can latest cling 1.1 be included to this repo?
