### ISSUE TITLE
Emacs fails to build on CLANG64

### ISSUE THREAD

**Issue by svraka** [msys2/MINGW-packages#17117]
### Description / Steps to reproduce the issue

I was checking whether the latest compilers might solve https://github.com/msys2/MINGW-packages/issues/16190. Simply run `makepkg-mingw` to build Emacs for CLANG64 (other environments are unaffected).

### Expected behavior

Emacs can be compiled on CLANG64.

### Actual behavior

The fails with compilation errors:

```
../../emacs-28.2/src/sysdep.c:472:13: error: call to undeclared function 'waitpid'; ISO C99 and later do not support
      implicit function declarations [-Wimplicit-function-declaration]
      pid = waitpid (child, status, options);
            ^
../../emacs-28.2/src/sysdep.c:518:43: error: use of undeclared identifier 'WNOHANG'
  return get_child_status (child, status, WNOHANG | options, 0);
                                          ^
2 errors generated.
make[1]: *** [Makefile:388: sysdep.o] Error 1
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I can reproduce it in my system. I shall try to send the patch to upstream and backport it here.

**Comment by Biswa96** [comment]
I have asked about this issue in upstream https://lists.gnu.org/archive/html/help-gnu-emacs/2023-05/msg00097.html

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?
