### ISSUE TITLE
[gcc] Multiple definition when statically linking

### ISSUE THREAD

**Issue by name12surname34** [msys2/MINGW-packages#17218]
### Description / Steps to reproduce the issue

1. Write this program:
```
#include <boost/asio.hpp>

void listen()
{
    boost::asio::io_context context;

    static boost::asio::ip::tcp::acceptor acceptor {
        context,
        {boost::asio::ip::tcp::v4(), 1000}
    };
}

int main()
{}
```
2. Try to compile it with:

> g++  -static -std=c++23 .\main.cpp -lws2_32

### Expected behavior

It should compile with no problems.

### Actual behavior

I get the multiple definition error:

> D:/Programmi/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Programmi/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libstdc++.a(tinfo.o):(.text$_ZNKSt9type_infoeqERKS_+0x0): multiple definition of `std::type_info::operator==(std::type_info const&) const'; C:\Users\jayok\AppData\Local\Temp\ccP4wonU.o:main.cpp:(.text$_ZNKSt9type_infoeqERKS_[_ZNKSt9type_infoeqERKS_]+0x0): first defined here
> collect2.exe: error: ld returned 1 exit status

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [x] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
Proof that you just check boxes without even verifying anything, You are using GCC 12.2.0 so your MSYS2 installation is not up to date.

**Comment by name12surname34** [comment]
I just installed msys2 and it's mingw package, and I got gcc 12.2.0. The time before, it installed gcc 13.1 instead, and there was the same bug .
