### ISSUE TITLE
Pastix package is broken

### ISSUE THREAD

**Issue by ImperatorS79** [msys2/MINGW-packages#17236]
### Description / Steps to reproduce the issue

I tried to use the pastix package provided by msys2, and while everything compiles the program I tested crashes directly at launch. I built locally the package with `makepkg-mingw`. My investigations led me to the following:

- there are some .dll.a files which do not have a .dll file in the bin directory: libpastix_kernels.dll, libpastix_starpu.dll, libspm.dll are not installed, but they are all built;

- when adding a check function in the PKGBUILD using `ctest`, a lot of test fail for the static build and all of them fail for the shared build (certainly due to the missing dlls);

- tests involving the python wrapper fail because the path sent to python is not correct:
`/c/Users/<path-to-msys2-repo>/mingw-w64-pastix/src/build-x86_64-w64-mingw32-shared/wrappers/python/C:/Users/<path-to-msys2-repo>/mingw-w64-pastix/src/build-x86_64-w64-mingw32-shared/wrappers/python/examples/schur_obj.py`; 

- The following warning is generated at the end:
```
==> Checking for packaging issues...
==> WARNING: Package contains reference to $(cygpath -m /)
```

### Expected behavior

Having all the .dll installed, and having all the tests working.

### Actual behavior

Some dlls are missing,  and I do not manage to make it work for my project involving pastix.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [x] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes, If I understand how to fix this, which currently I don't.

**Comment by 3rav** [comment]
https://gitlab.inria.fr/solverstack/pastix/-/issues/60
