### ISSUE TITLE
unittest-cpp: version checks with pkg-config do not work

### ISSUE THREAD

**Issue by rrthomas** [msys2/MINGW-packages#17297]
### Description / Steps to reproduce the issue

A test like this in `configure.ac` does not work:

```
PKG_CHECK_EXISTS([UnitTest++],
    [PKG_CHECK_MODULES(UNITTESTPP, [UnitTest++ >= 1.6])])
```

### Expected behavior

This should pass, since UnitTest++ 2.0.0 is packaged.

Without the version check, the test passes, and UnitTest++ works fine.

A versioned check of glib works too, so it doesn't seem to be a general problem with `pkg-config`.

### Actual behavior

```
checking for UnitTest++ >= 1.6... no
configure: error: Package requirements (UnitTest++ >= 1.6) were not met:

Requested 'UnitTest++ >= 1.6' but version of UnitTest++ is 
You may find new versions of UnitTest++ at https://github.com/unittest-cpp/unittest-cpp
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Latest GitHub Actions version

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No, sorry.

**Comment by Biswa96** [comment]
Could you provide any minimal sample code to reproduce the issue?

**Comment by rrthomas** [comment]
@Biswa96, thanks for your quick response!

Here is a MWE of `configure.ac`:

```
AC_INIT
PKG_CHECK_MODULES(UNITTESTPP, [UnitTest++])
```

Here it is working:

```
$ ./configure
$ ./configure
configure: loading site script /etc/config.site
checking for pkg-config... /mingw64/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for UnitTest++... yes
```

And here is a minimal failing example:

```
AC_INIT
PKG_CHECK_MODULES(UNITTESTPP, [UnitTest++ >= 1.6])
```

And here it is failing:

```
$ ./configure
configure: loading site script /etc/config.site
checking for pkg-config... /mingw64/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for UnitTest++ >= 1.6... no
configure: error: Package requirements (UnitTest++ >= 1.6) were not met:

Package dependency requirement 'UnitTest++ >= 1.6' could not be satisfied.
Package 'UnitTest++' has version '', required version is '>= 1.6'
```

And indeed, `pkg-config` has no version information for UnitTest++:

```
$ pkg-config --modversion UnitTest++
$ pkg-config --modversion tcl # Just to show it's working otherwise!
8.6.12
```

And indeed the `.pc` file contains no version information:

```
$ cat /mingw64/lib/pkgconfig/UnitTest++.pc
prefix=/mingw64
exec_prefix=/mingw64/bin
libdir=/mingw64/lib
includedir=/mingw64/include/UnitTest++

Name: UnitTest++
Description: UnitTest++ is a simple C++ Unit Test Framework
URL: https://github.com/unittest-cpp/unittest-cpp
Version:
Libs: -L${libdir} -lUnitTest++
Cflags: -I${includedir}/
```

So it seems the problem is as simple as needing to add a `Version:` line to the `.pc` file.

**Comment by Biswa96** [comment]
Hi @rrthomas, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? Here is the diff with new pkgconfig file.

```diff
--- a/UnitTest++.pc
+++ b/UnitTest++.pc
@@ -6,6 +6,6 @@
 Name: UnitTest++
 Description: UnitTest++ is a simple C++ Unit Test Framework
 URL: https://github.com/unittest-cpp/unittest-cpp
-Version: 
+Version: 2.0.0
 Libs: -L${libdir} -lUnitTest++
 Cflags: -I${includedir}/
```

**Comment by rrthomas** [comment]
Thanks very much! I won't be able to test for a while, but it looks great. I see that there are other changes in the recipe, but the fix to the `.pc` file is all I need, and I can't see how it could be incorrect now.
