### ISSUE TITLE
MKVToolNix does not open without ffmpeg installed

### ISSUE THREAD

**Issue by fauxpark** [msys2/MINGW-packages#17330]
### Description / Steps to reproduce the issue

The MKVToolNix GUI stopped opening for me recently. After poking around in Process Monitor I discovered it went on a frantic search for some ffmpeg DLLs. `mkvtoolnix-gui` itself does not reference these DLLs, but it does depend on `qt6-multimedia`, which in turn provides an ffmpeg plugin that is apparently now required.

I see there have been some updates to `qt6-multimedia` in the last month or so, but I'm not sure whether ffmpeg should be promoted from an optional dependency there, or if it should be added to `mkvtoolnix-gui`.

### Expected behavior

MKVToolNix should open.

### Actual behavior

MKVToolNix does not open and exits 127.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by fauxpark** [comment]
I found this note: https://doc.qt.io/qt-6/qtmultimedia-index.html#target-platform-and-backend-notes
> In Qt 6.5, we're setting [FFmpeg framework](http://ffmpeg.org/) as the default backend on Windows, macOS, Android, and Linux except Yocto distribution. Native backends, namely gstreamer on Linux, AVFoundation on macOS, WMF on Windows, and the MediaCodec framework on Android, were the default in 6.4. These are still available but with limited support.

Which sounds to me like ffmpeg can no longer be an optional dependency.

**Comment by Biswa96** [comment]
Is it possible to split the ffmpeg and gstreamer plugins in separate packages like [ArchLinux does](https://gitlab.archlinux.org/archlinux/packaging/packages/qt6-multimedia/-/blob/main/PKGBUILD)?

**Comment by fauxpark** [comment]
It would be WMF, not gstreamer, but yes.

**Comment by Biswa96** [comment]
Is this fixed after that qt6-multimedia backend split?

**Comment by fauxpark** [comment]
Still waiting on upload for v78, but 73.0.0 does seem to work.
