### ISSUE TITLE
lua53 and lua51 still have gcc as the default C compiler

### ISSUE THREAD

**Issue by FractalU** [msys2/MINGW-packages#17337]
### Description / Steps to reproduce the issue

The lua53 and lua51 packages still have gcc as the default C compiler. Lua, luajit and all the other associated lua packages have already changed it to cc. Therefore in lua53 and lua51 the build dependency should be changed from gcc to cc. Also in lua53 PKGBUILD

Change from
```
  make -j1 \
    AR="ar rcu" \
    RANLIB="ranlib" \
    STRIP="strip" \
    CC="${MINGW_CHOST}-gcc" \
    mingw
```
to

```
  make \
    AR="ar rcu" \
    RANLIB="ranlib" \
    STRIP="strip" \
    CC="${CC}" \
    mingw
```

### Expected behavior

lua51 build dependency is mingw-w64-ucrt-x86_64-cc
lua53 build dependency is mingw-w64-ucrt-x86_64-cc

### Actual behavior

lua51 build dependency is mingw-w64-ucrt-x86_64-gcc
lua53 build dependency is mingw-w64-ucrt-x86_64-gcc

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [x] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by Biswa96** [comment]
lua51 already has cc in makedepends, see https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-lua51/PKGBUILD. Only lua53 needs the change, right?

**Comment by FractalU** [comment]
Yes, you're right. I checked it wrong in lua51 somehow, apparently. Sorry for the inconvenience.
