### ISSUE TITLE
[lua-luarocks] luarocks can't make parent folders with mkdir

### ISSUE THREAD

**Issue by SeokguKim** [msys2/MINGW-packages#17344]
### Can't install any single rock

When I executed `$ luarocks install json-lua` I got an error message that it failed making directories.   
After some painstaking approach, I figured out that **luarocks just can't make parent folders with mkdir**.

### Why luarocks can't make parent folders?

I traced back the error and define the cause: **There was a missing filesystem config.**

My system is defined as `msys2_mingw_w64` and when I opend `/luarocks/fs/msys2_mingw_w64.lua`, **there was no options for `mkdir` command to operate like `unix` system.**

In other words, my luarocks was trying to execute `mkdir` commands with `windows` style, which does not need `-p` flag to make parent directories.

I actually fixed this to work temporarily, adding a line to  `/luarocks/fs/msys2_mingw_w64.lua`, just like this:

**Original one**

```lua
--- MSYS2 + Mingw-w64 implementation of filesystem and platform abstractions.
local msys2_mingw_w64 = {}

local unix_tools = require("luarocks.fs.unix.tools")

msys2_mingw_w64.zip = unix_tools.zip
msys2_mingw_w64.unzip = unix_tools.unzip
msys2_mingw_w64.gunzip = unix_tools.gunzip
msys2_mingw_w64.bunzip2 = unix_tools.bunzip2
msys2_mingw_w64.copy_contents = unix_tools.copy_contents

return msys2_mingw_w64
```

**The one I added a line**

```lua
--- MSYS2 + Mingw-w64 implementation of filesystem and platform abstractions.
local msys2_mingw_w64 = {}

local unix_tools = require("luarocks.fs.unix.tools")

msys2_mingw_w64.zip = unix_tools.zip
msys2_mingw_w64.unzip = unix_tools.unzip
msys2_mingw_w64.gunzip = unix_tools.gunzip
msys2_mingw_w64.bunzip2 = unix_tools.bunzip2
msys2_mingw_w64.copy_contents = unix_tools.copy_contents
msys2_mingw_w64.make_dir = unix_tools.make_dir

return msys2_mingw_w64
```

After adding that line, my `MSYS2 MinGW64` shell started to successfully install rocks I want.  
I think there still might be several issue just like this... but this time, it just works for me fine.

### Expected behavior

`luarocks` can make parent directories with `mkdir` just like `unix` on  `msys2_mingw_w64` system.

### Actual behavior

`luarocks` tries to make parent directories with `mkdir` just like `windows` on  `msys2_mingw_w64` system and fails.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by osch** [comment]
This has also been reported in  #15458 and there is a pull request for fixing this in #12002

**Comment by SeokguKim** [comment]
Thanks! Seems like it has been fixed!
