### ISSUE TITLE
[mupdf] include mupdf-gl binary

### ISSUE THREAD

**Issue by ousia** [msys2/MINGW-packages#17385]
### Package name

mupdf

### Other information that may be useful

Could you include the mupdf-gl binary.

This allows adding annotations and signatures (when compiled with the proper library).

Many thanks for your help.

### Are you willing to submit a PR?

Sorry, but I cannot code that.

**Comment by Biswa96** [comment]
Hi @ousia, I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request?
