### ISSUE TITLE
Unable to compile Qt5 from source

### ISSUE THREAD

**Issue by iahunq** [msys2/MINGW-packages#17380]
I think I could get a newer version of Qt5 by compiling from source.

I got the source from KDE:

`git clone --depth 1 --branch kde/5.15 https://invent.kde.org/qt/qt/qtbase --recursive`

This is the command I used:

```
./configure \
-platform win32-g++ \
-prefix $HOME/Qt5.15 \
-opensource \
-no-compile-examples \
-opengl desktop \
-skip qtactiveqt -skip qtcharts -skip qtdoc -skip qtlocation \
-skip qtremoteobjects -skip qtserialbus -skip qtwebchannel \
-skip qtwebview -skip qtandroidextras -skip qtconnectivity \
-skip qtgamepad -skip qtmacextras -skip qtpurchasing -skip qtscript \
-skip qttranslations -skip qtwebengine -skip qtwinextras \
-skip qtdatavis3d -skip qtgraphicaleffects -skip qtmultimedia \
-skip qtquickcontrols -skip qtscxml -skip qtspeech \
-skip qtvirtualkeyboard -skip qtwebglplugin -skip qtx11extras \
-skip qt3d -skip qtcanvas3d -skip qtdeclarative \
-skip qtimageformats -skip qtnetworkauth -skip qtquickcontrols2 \
-skip qtsensors -skip qtwayland -skip qtwebsockets -skip qtxmlpattern
```

The problem is `qmake` will stuck indefinitely creating stash file `qtbase\.qmake.stash`. Please help me. Thank you.

**Comment by Biswa96** [comment]
It is not possible to build qt5 base repository from source as is. You need some patches and proper build commands which can be found here https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-qt5-base.
