### ISSUE TITLE
atk package missing

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#17399]
### Description / Steps to reproduce the issue

seems the atk package was removed though several packages still list it as a dependency.

### Expected behavior

well i guess removing it was a mistake ?.

### Actual behavior

still needed.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW32_NT-10.0-19044

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by revelator** [comment]
aha ok but why was it moved to a new package name ?

**Comment by Biswa96** [comment]
> why was it moved to a new package name ?

atk upstream is now part of at-spi2-core. The package name is same as previous.

**Comment by revelator** [comment]
ok so it was an upstream decision ? that explains it, just a bit hard to keep track of all the changes.
