### ISSUE TITLE
Segmentation fault in gfortran 5.3.0

### ISSUE THREAD

**Issue by mfleduc** [msys2/MINGW-packages#17391]
### Description / Steps to reproduce the issue

I am attempting to use gfortran 5.3 to compile some fortran libraries for use with netcdf-fortran, which I installed using conda. Using gfortran 5.3.0, which is required since it is the version conda used to compile netcdf-fortran, leads to a segmentation fault and the instruction to submit a bug report to https://sourceforge.net/projects/msys2 which has not been updated since 2017. This seemed like the logical next place to submit the report.

I am not sure how I can provide a way to reproduce the issue, but will supply whatever is needed. I have attached a log file generated by calling gfortran using f2py.

I got this version of gfortran from conda using the command conda install -c msys2 m2w64-gcc-fortran

[logfile.txt](https://github.com/msys2/MINGW-packages/files/11619321/logfile.txt)

### Expected behavior

I expect that calling gfortran to compile this code into a python module will not result in a segmentation fault. 

### Actual behavior

gfortran 5.3 is seg faulting.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 11 OS build 22621.1702

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> I am attempting to use gfortran 5.3 to compile some fortran libraries for use with netcdf-fortran

msys2 provides gfortran version 13.1.0. Where did you get that ancient version?

**Comment by mfleduc** [comment]
I found it here: https://anaconda.org/msys2/m2w64-gcc-libgfortran

and installed using conda. Upon closer inspection it seems like if this was at one point an official msys2 conda channel it is no longer being used, since it hasn't been updated in years.

**Comment by Biswa96** [comment]
Please use the msys2 provided packages.
