### ISSUE TITLE
nettle update to 3.9.1

### ISSUE THREAD

**Issue by teythoon** [msys2/MINGW-packages#17410]
### Package name

nettle

### New version number

3.9.1

### Other information that may be useful

3.9 contains a heap corruption bug in the OCB implementation.  3.9.1 is a bugfix release to fix that.  Thanks!

**Comment by teythoon** [comment]
Sweet, thanks!

**Comment by Biswa96** [comment]
The outdated packages are shown here https://packages.msys2.org/outofdate
