### ISSUE TITLE
Add Package: AppStream

### ISSUE THREAD

**Issue by taozuhong** [msys2/MINGW-packages#17448]
### Package name

AppStream

### Brief description of package

Tools and libraries to work with AppStream metadata

### URL for package's homepage

https://github.com/ximion/appstream

### Provide a basic test case to validate the package's functionality.

appstreamcli compose

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

Need help

**Comment by brisingraerowing** [comment]
Appstream requires gio-unix, which doesn't exist for Win32.

**Comment by ZachBacon** [comment]
> The library libadwaita require it, so we should add this package.

We already have libadwaita packaged. So no it doesn't require it.

**Comment by taozuhong** [comment]
![image](https://github.com/msys2/MINGW-packages/assets/13451009/de67001b-d0c9-4636-aa27-a2e8a5d53788)

**Comment by brisingraerowing** [comment]
It seems to be an optional dep.

**Comment by ZachBacon** [comment]
> https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/meson.build
> ![image](https://github.com/msys2/MINGW-packages/assets/13451009/de67001b-d0c9-4636-aa27-a2e8a5d53788)

Again, it's not needed on the windows platform

**Comment by lb90** [comment]
Hi! Looked a bit into this...

The dependency on appstream is new to Libadwaita 1.4 (not released yet), so current 1.3.x releases build without problems. As conceived, it's a required dependency on all platforms.

The appstream library is used only in src/adw-about-window.c:

```
$ git grep appstream
.gitlab-ci/fedora.Dockerfile:    appstream-devel \
demo/data/meson.build:  appstream_file = i18n.merge_file(
demo/data/meson.build:  appstreamcli = find_program('appstreamcli', required: false)
demo/data/meson.build:  if appstreamcli.found()
demo/data/meson.build:    test('Validate appstream file', appstreamcli,
demo/data/meson.build:      args: ['validate', '--no-net', '--explain', appstream_file]
demo/meson.build:demo_config_data.set_quoted('ADW_METAINFO', appstream_file.full_path())
demo/meson.build:   dependencies: appstream_file,
src/adw-about-window.c:#include <appstream.h>
src/adw-about-window.c: * [AppStream descriptions](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description).
src/adw-about-window.c:   * [AppStream descriptions](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description).
src/adw-about-window.c: * [AppStream descriptions](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description).
src/meson.build:appstream_dep = dependency('appstream',
src/meson.build:  fallback : ['appstream', 'appstream_dep']
src/meson.build:  appstream_dep,
subprojects/appstream.wrap:directory = appstream
subprojects/appstream.wrap:url = https://github.com/ximion/appstream.git
```

There are three possible ways forward:

1. Port ximion/appstream to Windows (see https://github.com/ximion/appstream/issues/231)
2. Use appstream-glib, which has a different API but it's already packaged in MSYS2
3. Stub out parts of the adw_about_window_new_from_appdata function and return an empty dialog (not very nice, admittedly...)

See also https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/833

**Comment by taozuhong** [comment]
https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/895

**Comment by alex-tee** [comment]
this merge request on upstream appstream (no pun intended) adds windows support https://github.com/ximion/appstream/pull/510

and since the libadwaita dev believes it should be used on windows too according to the MR above, i believe this should be packaged. i'm currently working on a PKGBUILD

**Comment by alex-tee** [comment]
this worked for me, although i used my fork that skips the `doc` directory because it was causing build issues. feel free to edit it to your liking:

```bash
# Contributor: Alexandros Theodotou <alex at zrythm dot org>
_realname=appstream
pkgbase=mingw-w64-${_realname}
pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
_commit='ee2c3545ec6ed708121a7c9ea28252afbc0da8e1'
pkgver=1.0.0
pkgrel=1
pkgdesc="appstream"
arch=('any')
url="http://www.freedesktop.org/wiki/Distributions/AppStream/"
license=(LGPL2.1)
makedepends=("${MINGW_PACKAGE_PREFIX}-gcc"
             "${MINGW_PACKAGE_PREFIX}-pkg-config"
             "${MINGW_PACKAGE_PREFIX}-meson")
depends=("${MINGW_PACKAGE_PREFIX}-libxslt"
         "${MINGW_PACKAGE_PREFIX}-gperf"
         "${MINGW_PACKAGE_PREFIX}-itstool"
         "${MINGW_PACKAGE_PREFIX}-libxmlb")
source=("https://gitlab.zrythm.org/zrythm/${_realname}/-/archive/${_commit}/${_realname}-${_commit}.tar.gz")
sha256sums=('SKIP')

prepare() {
  rm -rf /tmp/${_realname}-${pkgver}
  mv "${srcdir}/${_realname}-${_commit}" /tmp/${_realname}-$pkgver
}

build() {
  rm -rf /tmp/${_realname}-build-${MINGW_CHOST}
  mkdir -p /tmp/${_realname}-build-${MINGW_CHOST}
  cd /tmp/${_realname}-build-${MINGW_CHOST}

  MSYS2_ARG_CONV_EXCL="--prefix=" \
  LDFLAGS="-lssp" \
  ${MINGW_PREFIX}/bin/meson \
    --prefix=${MINGW_PREFIX} \
    -Ddebug=true \
    -Doptimization=2 \
    -Dsystemd=false \
    -Dstemming=false \
    -Dgir=false \
    -Dsvg-support=false \
    -Dapidocs=false \
    -Dinstall-docs=false \
    -Ddefault_library=shared \
    /tmp/${_realname}-${pkgver}

  meson compile
}

package() {
  cd /tmp/${_realname}-build-${MINGW_CHOST}

  DESTDIR="${pkgdir}" meson install

  install -Dm644 "/tmp/${_realname}-${pkgver}/COPYING" "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}/COPYING"
}
```

**Comment by lazka** [comment]
Thanks everyone, added in #18494

Feel free to improve!
