### ISSUE TITLE
32-bit packages of qt6 were dropped

### ISSUE THREAD

**Issue by orgads** [msys2/MINGW-packages#17447]
### Description / Steps to reproduce the issue

Continuing the discussion from [here](https://github.com/msys2/MINGW-packages/pull/16610#discussion_r1216828748).

When Qt was upgraded to 6.5.0 (#16610), mingw32 and clang32 were dropped.

The reason was not mentioned in the commit message nor in the PR.

After the fact, the maintainer (@MehdiChinoune) claimed that support for Win32 was dropped upstream, which is inaccurate.

The source is [this blog post](https://www.qt.io/blog/qt6-development-hosts-and-targets), which mentions dropping support for Win<10, and has the following statement:

> This means that we will not have 32bit Windows support available.

Oliver Wolff commented on this post:

> The end of 32 bit packages for Windows was perhaps phrased a bit unfortunately. The decision no longer to support 32 bit on Windows was done deliberately from the Windows version support. This decision does not mean that we will actively remove support for 32 bit on Windows though. Having a platform as "supported" means more than "it works by chance".

He follows to say there will be no CI and no "official support" for 32-bit, but as long as it works, they won't actively drop it.

### Expected behavior

Please keep the 32-bit packages, as long as they build without a problem (at least qt6-base).

### Actual behavior

The packages were deleted.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19043

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [X] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

I did.

**Comment by orgads** [comment]
I need it only for qmake.

Using Qt5 is an option, but I prefer to stick with a well-maintained release.

Is there a deliberate decision to drop 32-bit Qt? Drop mingw32 altogether? What are the considerations?

**Comment by revelator** [comment]
well it builds fine on 32 bit here as well if reverting a few things like linked above so id say as long as it works we should continue having it as an option.

**Comment by orgads** [comment]
How do we proceed with this?

**Comment by revelator** [comment]
guess someone would have to push the packages with the 32 bit builds reenabled though i see atleast a few dependees also went headfirst into the assumption that 32 bit builds were being deprecated for qt6. so again 32 bit windows is deprecated 32 bit software is not and most likely wont be deprecated in the foreseeable future as 64 bit windows runs 32 bit software quite fine.

**Comment by orgads** [comment]
I pushed #17444 long ago, but it was not approved (nor closed).

**Comment by revelator** [comment]
i guess they just wanted it gone then sigh... 
well if we want 32 bit support for qt6 we would have to make our own repo with the fixed packages for 32 bit builds, should be doable to add this repo to the pacman configuration but we would be the ones to keep it up to date im afraid.

**Comment by revelator** [comment]
to reduce the workload which i guess is a major factor in this id suggest people who want new packages added to keep those updated. as is we are putting a rather large strain on a few people, we allready have so many packages that many of them are in trouble because old source code links are dead or incompatibility with newer dependencies it all add's up. thoughts ?.

**Comment by hmartinez82** [comment]
Qt 6 is not supported for 32 bits Windows. How is that inaccurate. It was the Qt Company itself that said so.

That's probably why even Kitware itself, is releae CMake 3.28-rc (I just looked) with Qt 5.15.x still :)

**Comment by Biswa96** [comment]
At the moment, we have not received any additional reports from other users regarding the 32-bit Qt6 issue. Please feel free to reopen the issue once other users have reported experiencing the same issue as well.

**Comment by revelator** [comment]
qt 6.5 still worked with 32 bit 6.6 dropped support it seems atleast the page claims it is only compatible with 64 bit, i havent tried building a 32 bit version of version 6.6 so cannot say if that is true.

**Comment by jeremyd2019** [comment]
See #19326 for ongoing discussion of the more general move to drop 32-bit packages.
