### ISSUE TITLE
Bug passing Windows Options Type Argument been normalized to Paths!

### ISSUE THREAD

**Issue by nhatkhai** [msys2/MINGW-packages#17470]
### Description / Steps to reproduce the issue

Under MINGW64_NT-10.0-19045 bash:
1. `echo "@echo May Arugemnts %*" > a.cmd`
2. ` a.cmd /i /xyz -hello -x \/c c:/projects`

### Expected behavior

Argument should never been manipulated, so the console output of step 2 should be
`May Arugemnts /i /xyz -hello -x /c c:/projects`

### Actual behavior

Argument with prefix of `/` had been normalized as if they are file path. so the console output of step 2 was:
`May Arugemnts I:/ "C:/Program Files/Git/xyz" -hello -x C:/ c:/projects`

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

maybe

**Comment by Biswa96** [comment]
There are ways to change that behaviour, see https://www.msys2.org/docs/filesystem-paths/#process-arguments
