### ISSUE TITLE
mingw-w64-nsis update to 3.08

### ISSUE THREAD

**Issue by punytroll** [msys2/MINGW-packages#17482]
### Package name

mingw-w64-nsis

### New version number

3.08

### Are you willing to submit a PR?

Unfortunately, I have no idea how. :(

**Comment by Biswa96** [comment]
Hi @punytroll, I have added a pull request to update the package. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Comment by punytroll** [comment]
Hi @Biswa96, I am blown away by the fast response and solution! Thanks so much!

I have tested, as much as I can. It installs, it runs, it reports the correct version and it builds my installer. I haven't tried the "new "NSIS features yet, but I suspect that should work.
