### ISSUE TITLE
gphoto2 --folder=/ always adds "C:/msys64" to folder name

### ISSUE THREAD

**Issue by orbian** [msys2/MINGW-packages#17538]
### Description / Steps to reproduce the issue

1. Start mintty on Windows
2. Try a gphoto2 command with --folder option such as gphoto2 --folder=/ --debug -n

### Expected behavior

folder should simply be "/" which is the root of the camera's folder.

### Actual behavior

debug log shows:
0.107198 main                        (2): invoked with following arguments:
0.110186 main                        (2):   --folder=C:/msys64/
0.112566 main                        (2):   -n
0.114576 main                        (2):   --debug

It is prepending a Windows folder onto the camera's folder. The --folder option is for the camera's internal folder, not a Windows desktop folder.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by kmilos** [comment]
Start w/ `MSYS2_ARG_CONV_EXCL=--folder= gphoto2 --folder=/ --debug -n`
