### ISSUE TITLE
Add android-tools package (adb, fastboot)

### ISSUE THREAD

**Issue by Biswa96** [msys2/MINGW-packages#17531]
### Package name

mingw-w64-android-tools

### Brief description of package

I would like to add the android-tools as mingw package. But building the Windows
port of that is not straight forward. AdbWinApi.dll and AdbWinUsbApi.dll depend
on some [ATL Module Clases](https://learn.microsoft.com/en-us/cpp/atl/atl-module-classes).
So, I planned to build those with MSVC and the rest with gcc/clang as other mingw
packages. Here is the workflow I thought of. Please let me know to how to improve
and implement it.

1. Create a repository, let say _adbwinapi_. It will clone the https://android.googlesource.com/platform/development.git
repository as a git submodule with a specific tag. Then compile it with cmake
and MSVC in CI.

2. The compiled binaries and the required headers/sources are packed into a tarball.

3. Now in MINGW-packages repository, create mingw-w64-android-tools package with
https://github.com/nmeum/android-tools repository. Also use that tarball from
_adbwinapi_ repository release page.

Please share your thoughts and ideas.

### URL for package's homepage

https://github.com/nmeum/android-tools

### Provide a basic test case to validate the package's functionality.

```
$ adb --version
Android Debug Bridge version 1.0.41
Version 33.0.3p2-android-tools
Installed as C:\msys64\ucrt64\bin\adb.exe

$ fastboot --version
fastboot version 33.0.3p2-android-tools
Installed as C:\msys64\ucrt64\bin\fastboot.exe
```

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

Yes.

**Comment by sskras** [comment]
Yay!

**Comment by Biswa96** [comment]
Android-tools package is now available in pacman repository. See the package details here https://packages.msys2.org/base/mingw-w64-android-tools
