### ISSUE TITLE
[rapidjson] CMake error for imported targets

### ISSUE THREAD

**Issue by aikawayataro** [msys2/MINGW-packages#17530]
### Description / Steps to reproduce the issue

I'm using `find_package(RapidJSON)` to get the `RAPIDJSON_INCLUDE_DIRS` variable and add it as include directories to my target.
But, for example, when exporting a target that includes it:
```cmake
# ...
find_package(RapidJSON REQUIRED)

add_library(lib lib.cpp)
target_include_directories(lib PUBLIC ${RAPIDJSON_INCLUDE_DIRS})
# ...
install(TARGETS lib EXPORT LibTargets)
# ...
```

CMake will emit this code for `LibTargets.cmake` file:

```cmake
# ...
add_library(lib STATIC IMPORTED)

set_target_properties(lib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/mingw64/include;${_IMPORT_PREFIX}/include"
)
# ...
```

And linking such imported library will result an error:

```
Imported target "lib" includes non-existent path

    "/mingw64/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  ...
```

Possibly the same path problem (#13958) ncurses had.

### Expected behavior

The imported library links without any trouble.

### Actual behavior

CMake rejects `/mingw64/include` as valid include path.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by aikawayataro** [comment]
Thanks @Biswa96, I tested it, your pull request fixes the problem.

**Comment by aikawayataro** [comment]
@Biswa96, sorry to bother, but here is one more thing. The imported commit from upstream changes config variables prefix from `RAPIDJSON_` to `RapidJSON_`, but for version `1.1.0` it must be `RAPIDJSON_`.

**Comment by Biswa96** [comment]
Does the case change create any issue? Is rapidjson not found by cmake?

**Comment by aikawayataro** [comment]
> Does the case change create any issue? Is rapidjson not found by cmake?

It does, this is breaking change that affects any cmake configs targeted `1.1.0` rapidjson dependency, because for this version the library export `RAPIDJSON_INCLUDE_DIRS` variable, this is the only way to use rapidjson `1.1.0` with cmake. After the prefix changed to `RapidJSON_` all the code that reference this variable is invalid, but code will compile with msys2 mingw only because `RAPIDJSON_INCLUDE_DIRS` is silently expanded to an empty string and because rapidjson lives in the mingw's system include path. But for software that depends on this variable, things can be broken.

**Comment by Biswa96** [comment]
Thank you for bringing this issue to my attention. I have added the fix in a new pull request.

* I have tested rapidjson with the following CMakeLists.txt file.

```cmake
cmake_minimum_required(VERSION 3.27)
project(test)
find_package(RapidJSON REQUIRED)
message(STATUS "RAPIDJSON_INCLUDE_DIRS : ${RAPIDJSON_INCLUDE_DIRS}")
```

* Here is the diff with previous downloaded patch and current patch (notice the case changes).

```diff
--- 0bc856a747ce6b56107c29c80e5f86eb0fee151e.patch
+++ 0008-cmake-relocate-dirs.patch
@@ -78,6 +78,6 @@
 +# Compute paths
 +get_filename_component(RapidJSON_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
 +
-+set( RapidJSON_INCLUDE_DIR  "@RapidJSON_INCLUDE_DIR@" )
-+set( RapidJSON_INCLUDE_DIRS  "@RapidJSON_INCLUDE_DIR@" )
-+message(STATUS "RapidJSON found. Headers: ${RapidJSON_INCLUDE_DIRS}")
++set( RAPIDJSON_INCLUDE_DIR  "@RapidJSON_INCLUDE_DIR@" )
++set( RAPIDJSON_INCLUDE_DIRS  "@RapidJSON_INCLUDE_DIR@" )
++message(STATUS "RapidJSON found. Headers: ${RAPIDJSON_INCLUDE_DIRS}")
```

**Comment by Biswa96** [comment]
The above patch changes the generated RapidJSONConfig.cmake file as following (notice the case change).


```diff
--- a/RapidJSONConfig.cmake
+++ b/RapidJSONConfig.cmake
@@ -10,6 +10,6 @@
 # Compute paths
 get_filename_component(RapidJSON_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
 
-set( RapidJSON_INCLUDE_DIR  "${RapidJSON_CMAKE_DIR}/../../../include" )
-set( RapidJSON_INCLUDE_DIRS  "${RapidJSON_CMAKE_DIR}/../../../include" )
-message(STATUS "RapidJSON found. Headers: ${RapidJSON_INCLUDE_DIRS}")
+set( RAPIDJSON_INCLUDE_DIR  "${RapidJSON_CMAKE_DIR}/../../../include" )
+set( RAPIDJSON_INCLUDE_DIRS  "${RapidJSON_CMAKE_DIR}/../../../include" )
+message(STATUS "RapidJSON found. Headers: ${RAPIDJSON_INCLUDE_DIRS}")
```
