### ISSUE TITLE
`nodejs` - `npx` is a duplicate of `npm`

### ISSUE THREAD

**Issue by GalGR** [msys2/MINGW-packages#17543]
### Description / Steps to reproduce the issue

The `mingw64/bin/npx` command that's part of the `nodejs` package is an exact duplicate of the `mingw64/bin/npm` command.
You can see from the source code of [npm](https://github.com/npm/cli) how they differ (our current `npm` version is `9.5.1`):
https://github.com/npm/cli/blob/v9.5.1/bin/npm
https://github.com/npm/cli/blob/v9.5.1/bin/npx

Steps to reproduce (using `react-native` as an example):
1. Install `nodejs`: `pacman -Sy mingw-w64-x86_64-nodejs`
1. Run: `npx react-native@latest init AwesomeProject`

Possibly related to this issue:
https://github.com/msys2/MINGW-packages/issues/17497

### Expected behavior

`npm` should download and execute the package `react-native` (with the arguments `init AwesomeProject`), thus creating a new `react-native` project in the current directory.

### Actual behavior

`"$NODE_EXE" "$NPM_CLI_JS" react-native@latest ...` is executed instead of `"$NODE_EXE" "$NPX_CLI_JS" react-native@latest ...`, and so the following error occurs:
```
Unknown command: "react-native@latest"

To see a list of supported npm commands, run:
  npm help
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes

**Comment by revelator** [comment]
i think it might be related to this patch 0012-Use-shell-wrapper-script-for-npm-on-MSYS2-mingw-w64.patch

try_symlink('../lib/node_modules/' + name + '/' + bin_target, link_path) was replaced by an msys2 specific wrapper but it seems it does not take npx nor corepack into account.

```
+      # Use MSYS2 shell script wrapper.
+      if ((os.name == 'nt' and 'GCC' in sys.version) or
+          (os.name == 'posix' and 'NT' in platform.system())):
+        # Copy the wrapper shell script
+        try_copy('deps/npm/bin/npm', link_path)
+        # deps/npm/bin/npm is a shell script so the shebang must run sh, not node
+        s = open(link_path, 'r').read()
+        s = re.sub(r'#!.*\n', '#!' + '/usr/bin/env sh' + '\n', s)
+        open(link_path, 'w').write(s)
+      else:
+        try_symlink('../lib/node_modules/' + name + '/' + bin_target, link_path)
```

experimented a bit with the wrappers but so far no success, this one did not work ->

```
#!/usr/bin/env bash

# This is used by the Node.js installer, which expects the cygwin/mingw
# shell script to already be present in the npm dependency folder.

(set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix

basedir=`dirname "$0"`

case `uname` in
  *CYGWIN*|*MINGW*) basedir=`cygpath -w "$basedir"`;;
esac

NODE_EXE="$basedir/node.exe"
if ! [ -x "$NODE_EXE" ]; then
  NODE_EXE="$basedir/node"
fi
if ! [ -x "$NODE_EXE" ]; then
  NODE_EXE=node
fi

# these paths are passed to node.exe, so they need to match whatever
# kind of paths Node.js thinks it's using, typically win32 paths.
CLI_BASEDIR="$("$NODE_EXE" -p 'require("path").dirname(process.execPath)')"
if [ $? -ne 0 ]; then
  # if this didn't work, then everything else below will fail
  echo "Could not determine Node.js install directory" >&2
  exit 1
fi
NPX_CLI_JS="$CLI_BASEDIR/../lib/node_modules/npm/bin/npx-cli.js"
NPX_PREFIX=`"$NODE_EXE" "$NPX_CLI_JS" prefix -g`
NPM_PREFIX_NPX_CLI_JS="$NPX_PREFIX/../lib/node_modules/npm/bin/npx-cli.js"

# a path that will fail -f test on any posix bash
NPX_WSL_PATH="/.."

# WSL can run Windows binaries, so we have to give it the win32 path
# however, WSL bash tests against posix paths, so we need to construct that
# to know if npm is installed globally.
if [ `uname` = 'Linux' ] && type wslpath &>/dev/null ; then
  NPX_WSL_PATH=`wslpath "$NPM_PREFIX_NPX_CLI_JS"`
fi
if [ -f "$NPM_PREFIX_NPX_CLI_JS" ] || [ -f "$NPX_WSL_PATH" ]; then
  NPX_CLI_JS="$NPM_PREFIX_NPX_CLI_JS"
fi

"$NODE_EXE" "$NPX_CLI_JS" "$@"
```

spews a large error string about it not being able to loacte the path.

**Comment by revelator** [comment]
error enoent ENOENT: no such file or directory, lstat 'C:\Msys64\mingw32\bin\lib' which does exist but it says it cannot find the executable to run which i suspect to be the node executable itself ?.

**Comment by revelator** [comment]
might be a bad url in the  code the version here is somewhat old now so things might have changed ?, strange though that i get an error about not finding the executable and you get a network error :S

**Comment by revelator** [comment]
im not well versed in python but the symlink stuff just seems to make links to the corepack.js npm-cli.js and npx-cli.js scripts in install.py while this is ok with a posix system it blows up in our face when we try the same on Windows. Msys2 can do symlinks though they are not exactly the same as the posix version and have to be enabled beforehand, the wrappers for npm and npx are there but the corepack wrapper is located elsewhere so the script cannot find it if we use the msys2 wrapper as the shims are located in corepack/shims not in npm/bin where it looks for them.
atm im trying to figure something out based on the wsl build.

**Comment by revelator** [comment]
it works !!! npx react-native@latest init AwesomeProject now runs.

**Comment by revelator** [comment]
the shims seem to be for WSL only hence why the installer only tries to install a link to the corepack script, working on getting the rest of them ready for msys2 yarn yarnpkg etc. the wrappers need some special handling if run from the msys2 shell it seems i tried running the WSL versions but those ended up throwing an error so i wrote my own wrappers based on the mechanism in the npm / npx wrappers and that finally allowed corepack to run. the python installer script also needs some special handling but my latest iteration seems to work just fine so i guess i can focus on the rest of the wrappers now.

**Comment by revelator** [comment]
[PKGBUILD.zip](https://github.com/msys2/MINGW-packages/files/11833415/PKGBUILD.zip)

and the PKGBUILD allmost forgot :)

**Comment by revelator** [comment]
corepack enable is not nessesary and will throw an error if run cause the mingw specific shims are allready installed by the package now. if you need the WSL versions you would have to point it to a different directory on path with corepack enable --install-directory $somedir. this is a bit different than it is usually done by nodejs i know.

**Comment by raedrizqie** [comment]
@revelator dont you want to open a PR yourself?

**Comment by revelator** [comment]
atm i cant unfortunatly, im using my phones internet connection and the speed is horrendous xD

**Comment by revelator** [comment]
but try it out and let me know if anything borks :)

**Comment by revelator** [comment]
whoops small oversight with the node-gyp wrappers the path to the script is wrong i updated the patch.
[0013-Revert-to-FHS-installation-paths-on-Windows-tests-no.zip](https://github.com/msys2/MINGW-packages/files/11834979/0013-Revert-to-FHS-installation-paths-on-Windows-tests-no.zip)

**Comment by revelator** [comment]
yes previous patch had the paths wrong should be corrected now, works here but if you get something unforeseen post the error here.

**Comment by revelator** [comment]
path looks a bit screwy i know but it is how it is layed out in the mingw build :/ 

here is the output from mine ->

```
$ node-gyp list
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.16.0 | win32 | ia32
No node development files installed. Use `node-gyp install` to install a version.
gyp info ok

```

**Comment by revelator** [comment]
[mingw-w64-nodejs.zip](https://github.com/msys2/MINGW-packages/files/11835985/mingw-w64-nodejs.zip)
full package.

**Comment by revelator** [comment]
i think it is as good as i can get it... 
if someone can push it ill upload the latest changes here.

**Comment by revelator** [comment]
[mingw-w64-nodejs.zip](https://github.com/msys2/MINGW-packages/files/11840555/mingw-w64-nodejs.zip)

if you need the pnpm pnpx yarn and yarnpkg tools run corepack enable after installation, this also installs the powershell scripts to bin.

**Comment by raedrizqie** [comment]
```
this also installs the powershell scripts to bin.
```
you mean the installation of shell scripts from external modules is also fixed?

**Comment by revelator** [comment]
yup :)

**Comment by raedrizqie** [comment]
share the updated patches if you want me to update the package

**Comment by raedrizqie** [comment]
ah.. ok.. i thought there is an update to those patches

**Comment by revelator** [comment]
simplified them quite a bit in case you where wondering about the sizes, mostly corrective surgery on paths + some work on the python install script (if anyone could fix it so it also installs the batch files that would be great) but other than that things should work.

**Comment by raedrizqie** [comment]
npx now works..
```
npx react-native@latest init AwesomeProject

               ######                ######
             ###     ####        ####     ###
            ##          ###    ###          ##
            ##             ####             ##
            ##             ####             ##
            ##           ##    ##           ##
            ##         ###      ###         ##
             ##  ########################  ##
          ######    ###            ###    ######
      ###     ##    ##              ##    ##     ###
   ###         ## ###      ####      ### ##         ###
  ##           ####      ########      ####           ##
 ##             ###     ##########     ###             ##
  ##           ####      ########      ####           ##
   ###         ## ###      ####      ### ##         ###
      ###     ##    ##              ##    ##     ###
          ######    ###            ###    ######
             ##  ########################  ##
            ##         ###      ###         ##
            ##           ##    ##           ##
            ##             ####             ##
            ##             ####             ##
            ##          ###    ###          ##
             ###     ####        ####     ###
               ######                ######


                  Welcome to React Native!
                 Learn once, write anywhere

√ Downloading template
√ Copying template
√ Processing template
√ Installing dependencies


  Run instructions for Android:
    • Have an Android emulator running (quickest way to get started), or a device connected.
    • cd "C:\MSYS64\home\raed\AwesomeProject" && npx react-native run-android

  Run instructions for Windows:
    • See https://aka.ms/ReactNativeGuideWindows for the latest up-to-date instructions.
```

**Comment by revelator** [comment]
oh you used the older one ? :S ok i it also works it seems though the newer one is a bit less cluttered.
[mingw-w64-nodejs-latest.zip](https://github.com/msys2/MINGW-packages/files/11855983/mingw-w64-nodejs-latest.zip)

in case you change your mind ->
