### ISSUE TITLE
Add GNOME Text Editor

### ISSUE THREAD

**Issue by AvtechScientific** [msys2/MINGW-packages#17551]
### Package name

GNOME Text Editor

### Brief description of package

I saw that `gedit` (an older Gnome editor) is part of MSYS2:

https://packages.msys2.org/base/mingw-w64-gedit

However the new modern default editor, based on libadwaita, namely - GNOME Text Editor (g-t-e)

https://gitlab.gnome.org/GNOME/gnome-text-editor

is not yet part of MSYS2. And it's a pity since g-t-e has an automatic Windows port as part of it's CI:

https://gitlab.gnome.org/GNOME/gnome-text-editor/-/blob/main/.gitlab-ci.yml#L90

so adding it to MSYS2 probably would require minimal effort.

May I ask you to add GNOME Text Editor to MSYS2, please?

Thank you!

### URL for package's homepage

https://gitlab.gnome.org/GNOME/gnome-text-editor

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
It is already available in mingw packages, see https://packages.msys2.org/base/mingw-w64-gnome-text-editor

**Comment by AvtechScientific** [comment]
Great, it's new! Didn't know about that! Thank you!
