### ISSUE TITLE
Please add a package for iODBC

### ISSUE THREAD

**Issue by iahung** [msys2/MINGW-packages#17559]
https://github.com/openlink/iODBC

**Comment by Biswa96** [comment]
Does that project support modern Microsoft Windows OSes? The README lists Windows family (3.x, 95, NT, 200x, etc.). I tried to compile it and got some typedefs errors from sqltypes.h.

**Comment by iahung** [comment]
How could you make a package for unixODBC in the first place? Both unixODBC and iODBC don't support Windows.
