### ISSUE TITLE
[tk] Missing `pkg-config` file `tk.pc`

### ISSUE THREAD

**Issue by naveen521kk** [msys2/MINGW-packages#17600]
### Description / Steps to reproduce the issue

Starting version 3.11 python started to use pkg-config to search various libraries it depends on. One such dependency is `tk` which is required to build the `_tkinter` module.

See https://github.com/msys2-contrib/cpython-mingw/pull/139

Looking at the file list at https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-tk?repo=ucrt64 it is missing `tk.pc` (which is present in [the archlinux package](https://archlinux.org/packages/extra/x86_64/tk/)).

### Expected behavior

There should exist a file `tk.pc` in the package.

### Actual behavior

NA

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?
