### ISSUE TITLE
warning: underquoted definition of AM_PATH_AALIB

### ISSUE THREAD

**Issue by Wormnest** [msys2/MINGW-packages#17645]
### Description / Steps to reproduce the issue

While running autogen.sh for [gimp-help](https://gitlab.gnome.org/GNOME/gimp-help), I get these warnings after recently updating all packages. I use MINGW64.

```
/d/msys64/mingw64/share/aclocal/aalib.m4:12: warning: underquoted definition of AM_PATH_AALIB
/d/msys64/mingw64/share/aclocal/aalib.m4:12:   run info Automake 'Extending aclocal'
/d/msys64/mingw64/share/aclocal/aalib.m4:12:   or see https://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
```

I did not have these warnings before as far as I can remember, though I don't always look at the output.

Changing `/d/msys64/mingw64/share/aclocal/aalib.m4`  line 12 to:
```
AC_DEFUN([AM_PATH_AALIB],
```
fixes the issue.

### Expected behavior

No warnings about underquoted AM_PATH_AALIB.

### Actual behavior

The warnings mentioned above.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Hi @Wormnest, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Comment by Wormnest** [comment]
Hi @Biswa96. Sure, I can try, if I can remember how to manually update a package. Not sure yet, when I will have time for it.

**Comment by Wormnest** [comment]
Updated aalib using pacman and tested on gimp-help and the warning is indeed gone. Thanks :)
