### ISSUE TITLE
Multiple definitions of DllMain when linking statically against Pango

### ISSUE THREAD

**Issue by afalkenhahn** [msys2/MINGW-packages#17643]
### Description / Steps to reproduce the issue

I'm trying to link statically against Pango. Since Pango has quite some dependencies I end up doing something like this:

`gcc -shared -fPIC -Wl,--no-undefined -Wl,--version-script=exports.def -Wl,-soname,test.dll -o test.dll test.o -L/c/msys64/mingw64/lib -Wl,-Bstatic -lfreetype -lpng -lbrotlidec -lbrotlienc -lbrotlicommon -lharfbuzz -lpangocairo-1.0 -lpangoft2-1.0 -lpangowin32-1.0 -lpango-1.0 -lcairo -lpixman-1 -lgraphite2 -lfontconfig -lfreetype -lpcre2-8 -lpcre2-16 -lpcre2-32 -lpcre2-posix -lffi -lexpat -lintl -liconv -lthai -ldatrie -lbz2 -lz -luuid -Wl,-Bdynamic -lfribidi -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lstdc++ -lshlwapi -ldwrite -lWs2_32 -lrpcrt4 -lshell32 -lmsimg32 -lgdi32 -lole32`

### Expected behavior

I'd expect this to statically link Pango and most of its dependencies.

### Actual behavior

For some reason, I'm getting a linker error that `DllMain` is defined twice. Once in cairo and once in libthai. This is the exact error I'm getting:

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib\libthai.a(brk-common.o):(.text+0x30): multiple definition of `DllMain'; C:/m
sys64/mingw64/lib\libcairo.a(win32_cairo-win32-system.c.obj):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
```
This looks like a bug to me. Why would somebody want to define `DllMain` in static link library? IMHO it should only be defined in a shared link library (DLL). So I think the definition of `DllMain` is wrong in both `libthai.a` and in `libcairo.a` because those are both static link libraries which shouldn't have `DllMain` at all. 

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Thank you for reporting the issue. Would you like to provide a minimal sample code and proper steps to reproduce the problem?

**Comment by afalkenhahn** [comment]
I don't think that's necessary. Just take a look at the symbols in `libcairo.a` and `libthai.a`: They both have a `DllMain` symbol but I think that shouldn't be there since both are static link libraries.

**Comment by Biswa96** [comment]
Could you check if using pkgconf also results same error? For example,

```
gcc $(pkgconf -cflags -static pango) test.c $(pkgconf -libs -static pango)
```

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Comment by afalkenhahn** [comment]
Sorry, I'm not too familiar with GitHub. I can test the packages if you tell me how.

**Comment by Biswa96** [comment]
Sure. Please follow these steps.

1. Go to this page https://github.com/msys2/MINGW-packages/actions/runs/5373805856 > scroll down > download the XYZ-packages.zip file. The XYZ should match with the value of `$MSYSTEM` variable (here MINGW64).
2. Extract the .tar.zst file from that ZIP.
3. Install the .tar.zst file with `pacman -U <full path here>` command.

**Comment by afalkenhahn** [comment]
Thanks for the instructions. Using the new version indeed solves the problem. Thanks again!

**Comment by afalkenhahn** [comment]
Still struggling with this issue. When statically linking libgdk_pixbuf-2.0 and libthai, the issue pops up again:

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib\libgdk_pixbuf-2.0.a(gdk-pixbuf-io.c.obj):(.text+0x2050): multiple definition
 of `DllMain'; C:/msys64/mingw64/lib\libthai.a(brk-common.o):(.text+0x30): first defined here
```

**Comment by Biswa96** [comment]
> Still struggling with this issue. When statically linking libgdk_pixbuf-2.0 and libthai, the issue pops up again

gnome packages are not meant to be used with static libraries. Let me look into it.

**Comment by Biswa96** [comment]
I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? The cairo, rsvg fix will be in different pull request.

**Comment by afalkenhahn** [comment]
Sure, just post the link to GitHub Actions and I'll test it.

**Comment by Biswa96** [comment]
You can get the artifacts from the pull request page > Checks tab > main button at left column.
Direct link https://github.com/msys2/MINGW-packages/actions/runs/5501161649

**Comment by Biswa96** [comment]
I am not sure if librsvg static library should be added. The librsvg package is nearly 50 MB in total installation size. Adding static library would double the size of it. I shall wait for other comments.

**Comment by afalkenhahn** [comment]
Why is it so big? Librsvg's repository looks rather compact to me. Only a few sources in there.

**Comment by Biswa96** [comment]
> Why is it so big? 

Rust programming language.

**Comment by afalkenhahn** [comment]
@Biswa96 Unfortunately, I forgot to download the artifacts from https://github.com/msys2/MINGW-packages/actions/runs/5501161649 and https://github.com/msys2/MINGW-packages/actions/runs/5373805856 for the MINGW32 platform back in July. I only downloaded and installed them for MINGW64 but I also need them for MINGW32. Unfortunately, I can't download them any more because GitHub says that the artifacts have expired. What can I do to get them for MINGW32?

**Comment by Biswa96** [comment]
Just update the packages with `pacman -Syyu` command.

**Comment by afalkenhahn** [comment]
Did that but it only updated the packages bash-5.2.015-2  mintty-1~3.6.5-1  msys2-runtime-3.4.9-2  msys2-runtime-devel-3.4.9-2 and pacman-6.0.2-9. Doesn't look like it updated cairo and gdk-pixbuf2, does it?

**Comment by Biswa96** [comment]
> Doesn't look like it updated cairo and gdk-pixbuf2, does it?

Then those were updated previously. You can find the latest version of packages here https://packages.msys2.org/search and compare them with your system.

**Comment by afalkenhahn** [comment]
Oh no, it's all broken again :((( I've updated to the latest pango, gdk-pixbuf2 and cairo and now when linking statically I get tons of undefined references to `__imp_cairo_XXX`. This used to work perfectly and now it's broken again and it's trying to import DLL symbols even though I'm linking statically :(

**Comment by afalkenhahn** [comment]
I've opened #18827 for the new problem.
