### ISSUE TITLE
gettext update to 0.22

### ISSUE THREAD

**Issue by Jehan** [msys2/MINGW-packages#17649]
### Package name

gettext

### New version number

0.22

### Other information that may be useful

Could MSYS2 please update to newly released gettext version?

We want to release latest GIMP development version, but [localization is broken on Windows](https://gitlab.gnome.org/GNOME/gimp/-/issues/9653#note_1777280) (GIMP UI is always in English) because of a bug for which we contributed a patch upstream and is contained in gettext 0.22: https://savannah.gnu.org/bugs/index.php?64311

Thanks!

**Comment by Biswa96** [comment]
I'm currently encountering some compiler errors with gettext version 0.22.

```
../../../gettext-0.22/gettext-runtime/libasprintf/lib-asprintf.c:23:18: error: static declaration of 'libasprintf_asprintf' follows non-static declaration
   23 | #define asprintf libasprintf_asprintf
      |                  ^~~~~~~~~~~~~~~~~~~~
../../../gettext-0.22/gettext-runtime/libasprintf/lib-asprintf.c:23:18: note: previous declaration of 'libasprintf_asprintf' with type 'int(char **, const char *, ...)'
   23 | #define asprintf libasprintf_asprintf
      |                  ^~~~~~~~~~~~~~~~~~~~
../../../gettext-0.22/gettext-runtime/libasprintf/vasprintf.h:44:12: note: in expansion of macro 'asprintf'
   44 | extern int asprintf (char **result, const char *format, ...)
      |            ^~~~~~~~
```

**Comment by lazka** [comment]
should we look into backporting that commit first?

**Comment by Wormnest** [comment]
That would certainly be welcome

**Comment by Jehan** [comment]
This would definitely unblock us to at least backport the fix. Right now, we are delaying releasing this version of GIMP because of this (completely broken localization in Windows, while we have more than 80 translations available, it's quite annoying!).

**Comment by Biswa96** [comment]
Is there any way to verify that backporting the patch fixes aforementioned issue?

**Comment by Jehan** [comment]
> Is there any way to verify that backporting the patch fixes aforementioned issue?

Counter-question: is there a way for you to do a test package and a command to give us for installing said test package? Then we could do a test installer of our release and our Windows contributors will report back. 🙂

**Comment by Jehan** [comment]
@Biswa96 I see we can download zip files from there? Is that it? How do we install these in a CI? Can `pacman` be used to install from one such zip file (replacing a `pacman --noconfirm -S --needed mingw-w64-x86_64-gettext` command which we would usually do, according to our CI scripts)?

> Though, the fix may be uploaded soon

I have been generating many installers in the CI these last days to try to fix another packaging issue and I'm close to finishing it (but I'll likely have a few more tests). So I don't mind throwing in a test for this if you can give me a no-brainer simple command line to write down. It's all in a branch anyway.

**Comment by Biswa96** [comment]
Please follow these steps for testing package in CI artifacts.

1. Go to this page https://github.com/msys2/MINGW-packages/actions/runs/5398238833 > scroll down > download the XYZ-packages.zip file. The XYZ should match with the value of `$MSYSTEM` variable.
2. Extract the .tar.zst file from that ZIP.
3. Install the .tar.zst file with `pacman -U <full path of .tar.zst file>` command.

**Comment by Jehan** [comment]
Hmmm… The links to artifacts are not proper redirects (they don't work with a curl/wget) and the actual generated download URI is temporary (it fails after a very short time), so it's unsuited for a CI build rule which might happen in 20 min. I couldn't find how to construct a permanent URI for these artifacts either while wandering the page.

For CI rules, we need a proper URI which can be used through CLI. CI rules can't "click" links. :-/

This being said, I see that the "Pending Package Updates" is empty. Does it mean installing normally the package through pacman would get us the patched version now?

**Comment by Biswa96** [comment]
> Does it mean installing normally the package through pacman would get us the patched version now?

Yes.

**Comment by Biswa96** [comment]
> I'm currently encountering some compiler errors with gettext version 0.22...

I have sent a mail in upstream asking about that issue https://lists.gnu.org/archive/html/bug-gettext/2023-06/msg00088.html

**Comment by Jehan** [comment]
For info, the fix is confirmed with the backported patch: https://gitlab.gnome.org/GNOME/gimp/-/issues/9653#note_1779925 (this same tester had no Japanese interface with the previous installer using the non-fixed gettext)

**Comment by lazka** [comment]
For the record, gettext 0.22.2 still fails the same way

**Comment by brisingraerowing** [comment]
I just checked using the instructions from the linked mailing list, and found that `__USE_MINGW_ANSI_STDIO` is being reset to 1 by the command line *after* it gets set to 0 by the Gettext build system, resulting in the functions getting imported from `stdio.h`. Removing `__USE_MINGW_STDIO` from the compiler command line for Gettext might be a viable work around.
