### ISSUE TITLE
Static libpango-1.0.a has some shared library references

### ISSUE THREAD

**Issue by afalkenhahn** [msys2/MINGW-packages#17651]
### Description / Steps to reproduce the issue

libpango-1.0.a has some shared library references which makes it impossible to statically link against it without dynamically linking against those shared libraries. Specifically, libpango-1.0.a tries to import the following symbols: `__imp_g_utf8_skip`, `__imp_g_ascii_table`, ` __imp_fribidi_get_bidi_type`, ` __imp_fribidi_get_bracket`, `__imp_fribidi_get_par_embedding_levels_ex`. As you can see from the `__imp_` prefix, those are symbol imports from shared libraries (glib and libfribidi) but I think this is wrong. The static build of libpango should use static references to glib and libfribidi and not dynamic ones.

### Expected behavior

see above

### Actual behavior

see above

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
I was thinking to fix this with `Cflags.private` field in pkgconfig file. @lazka Would there be any issue with that in glib2? There were some previous discussion about static linking with glib2.

**Comment by Biswa96** [comment]
Scratch my last thought. It seems that meson does not get the `Cflags.private` value even when it is added manually in glib2 pkgconfig files. So, those need to be added with CFLAGS.

**Comment by Biswa96** [comment]
It is possible to create static libpango-1.0.a library without the `__imp` symbol. But some glib2 function declarations do not have dllimport/dllexport attribute. So, libpangowin32-1.0.a still exports symbols with `__imp`. Those APIs declaration in glib2 need to be fixed.

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Comment by afalkenhahn** [comment]
Sure, I'd be happy to test it. Where can I find the updated files?

**Comment by Biswa96** [comment]
Please follow these steps for testing package in CI artifacts.

1. Go to this page https://github.com/msys2/MINGW-packages/actions/runs/5434700312 > scroll down > download the XYZ-packages.zip file. The XYZ should match with the value of `$MSYSTEM` variable.
2. Extract the .tar.zst file from that ZIP.
3. Install the .tar.zst file with `pacman -U <full path of .tar.zst file>` command.

**Comment by afalkenhahn** [comment]
Thanks, I can confirm that your PR fixes the issue.

**Comment by afalkenhahn** [comment]
Still struggling with this issue. When statically linking librsvg-2 I get lots of DLL imports like this:

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib\librsvg-2.a(glib-84cacb77ac5946c7.glib.87b84d83-cgu.1.rcgu.o):(.text+0x454f)
: undefined reference to `__imp_g_param_spec_types'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib\librsvg-2.a(glib-84cacb77ac5946c7.glib.87b84d83-cgu.1.rcgu.o):(.text+0x45c3)
: undefined reference to `__imp_g_param_spec_types'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib\librsvg-2.a(glib-84cacb77ac5946c7.glib.87b84d83-cgu.1.rcgu.o):(.text+0x45df)
: undefined reference to `__imp_g_param_spec_types'
```

And also from libcairo-gobject:

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib\libcairo-gobject.a(cairo-gobject-enums.c.obj):(.text+0x2c): undefined refere
nce to `__imp_g_once_init_enter'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib\libcairo-gobject.a(cairo-gobject-enums.c.obj):(.text+0x3d): undefined refere
nce to `__imp_g_intern_static_string'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib\libcairo-gobject.a(cairo-gobject-enums.c.obj):(.text+0x4d): undefined refere
nce to `__imp_g_enum_register_static'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib\libcairo-gobject.a(cairo-gobject-enums.c.obj):(.text+0x59): undefined refere
nce to `__imp_g_once_init_leave'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib\libcairo-gobject.a(cairo-gobject-structs.c.obj):(.text+0x8): undefined refer
ence to `__imp_g_memdup2'
```

And also from libgdk_pixbuf-2.0:

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib\libgdk_pixbuf-2.0.a(gdk-pixbuf-io.c.obj):(.text+0x2d): undefined reference t
o `__imp_g_ascii_table'
```
