### ISSUE TITLE
Add fluidsynth static build

### ISSUE THREAD

**Issue by richardg867** [msys2/MINGW-packages#17664]
### Package name

fluidsynth

### Brief description of package

The fluidsynth library is already provided in `$MINGW_PACKAGE_PREFIX-fluidsynth`, but only as a dynamically linked library since #3071 due to upstream apparently removing static build support at the time. It looks like upstream now supports static builds again, so one should be packaged as well.

### URL for package's homepage

https://github.com/FluidSynth/fluidsynth

### Provide a basic test case to validate the package's functionality.

I've downloaded fluidsynth 2.3.3, successfully compiled it under MINGW32 with `-D BUILD_SHARED_LIBS=OFF`, verified that a `libfluidsynth.a` as well as a `fluidsynth.exe` binary statically linked to it were generated, and successfully played a MIDI file with the binary.

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
glib2 needs the changes. I have thought some steps to fix it - like adding proper dll attribute in glib2 functions and Cflags.private in pkgconfig file. But I have not tried it. There are other similar issue with glib2 static linking. I shall provide further info if things go right way.

**Comment by richardg867** [comment]
I eventually figured glib2 requires fixing, since linking a static FluidSynth into an actual static executable results in missing symbols mostly on glib2 and readline:

```
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/msys64/home/Richard/fluidsynth-2.3.3/build/src/libfluidsynth.a(fluid_settings.c.obj): in function `new_fluid_settings':
C:/msys64/home/Richard/fluidsynth-2.3.3/src/utils/fluid_settings.c:275: undefined reference to `_imp__g_rec_mutex_init'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/msys64/home/Richard/fluidsynth-2.3.3/build/src/libfluidsynth.a(fluid_settings.c.obj): in function `delete_fluid_settings':
C:/msys64/home/Richard/fluidsynth-2.3.3/src/utils/fluid_settings.c:290: undefined reference to `_imp__g_rec_mutex_clear'
[...]
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/msys64/mingw32/qt5-static/lib/libqtmain.a(qtmain_win.o):qtmain_win.cpp:(.text+0x140): undefined reference to `qMain(int, char**)'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/msys64/mingw32/lib/libreadline.a(display.o):(.text+0xdfd): undefined reference to `tputs'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/msys64/mingw32/lib/libreadline.a(display.o):(.text+0xe54): undefined reference to `tputs'
[...]

$ grep _imp__g_mutex_unlock /mingw32/lib/libglib-2.0.a

$ grep _imp__g_mutex_unlock /mingw32/lib/libglib-2.0.dll.a
Binary file /mingw32/lib/libglib-2.0.dll.a matches
```

Looking forward to any potential updates.

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Comment by richardg867** [comment]
I've tested the package (a bit late) and ran into issues with the coexistence of shared and dynamic fluidsynth in the same prefix.

Attempting to compile my statically-linked CMake project against the static fluidsynth, imported both directly through CMake and through pkg-config, resulted in the linker loading the static `libfluidsynth.a` but failing to find *dynamic* symbols such as `_imp__new_fluid_synth`. I noticed fluidsynth's CMake scripts, especially `lib/cmake/fluidsynth/FluidSynthConfig.cmake`, save whether or not the library's build was shared or static and take different paths based on that, leading to a prefix conflict between the two variants.

**Comment by richardg867** [comment]
With the macro set, I've managed to successfully import fluidsynth statically through pkg-config. Importing through CMake produces an executable that still links dynamically to `libfluidsynth-3.dll` due to the aforementioned CMake prefix conflict (`FluidSynthConfig.cmake` corresponds to the dynamic build per `set(FLUIDSYNTH_IS_SHARED ON)` and thus doesn't enable the static linking code paths)

**Comment by Biswa96** [comment]
> Importing through CMake produces an executable that still links dynamically

Yes, that is expected. All packages prefer dynamic linking by-default. You can find that rule in many PKGBUILD files. The shared library is installed last in `package()` function. Suggestions are welcomed to improve it.

**Comment by pedrolcl** [comment]
@Biswa96, you may backport this patch from fluidsynth 2.5:
https://github.com/FluidSynth/fluidsynth/commit/df432e151dcaf463b1ecc7e873803bfa19733fd3.patch
