### ISSUE TITLE
Can't build without libgcc_s_seh-1.dll dependency because some static libraries pull symbols from it

### ISSUE THREAD

**Issue by afalkenhahn** [msys2/MINGW-packages#17690]
### Description / Steps to reproduce the issue

I'm unable to do a build that doesn't depend on libgcc_s_seh-1.dll because static libraries like Cairo or HarfBuzz pull symbols from it as can be seen from the map file:

```
C:/msys64/mingw64/lib/libgcc_s.a(libgcc_s_seh_1_dll_d000121.o)
                              C:/msys64/mingw64/lib\libcairo.a(cairo-wideint.c.obj) (__udivmodti4)
C:/msys64/mingw64/lib/libgcc_s.a(libgcc_s_seh_1_dll_d000106.o)
                              C:/msys64/mingw64/lib\libharfbuzz.a(hb-ot-layout.cc.obj) (__popcountdi2)
...
 .idata$5       0x00000002d7fa2fb8        0x8 C:/msys64/mingw64/lib/libgcc_s.a(libgcc_s_seh_1_dll_d000106.o)
                0x00000002d7fa2fb8                __imp___popcountdi2
 .idata$5       0x00000002d7fa2fc0        0x8 C:/msys64/mingw64/lib/libgcc_s.a(libgcc_s_seh_1_dll_d000121.o)
                0x00000002d7fa2fc0                __imp___udivmodti4
```

How can I statically link libraries like Cairo and HarfBuzz without any libgcc_s_seh-1.dll dependency?

### Expected behavior

see above

### Actual behavior

see above

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Thank you for reporting the issue. Would you like to provide a minimal sample code or proper steps to reproduce the problem?

For example, I have tried to compile a program from this repository https://github.com/preshing/CairoSample statically. It compiled without any msys2/mingw-w64 related dependencies. Here are some output.

```
$ gcc -static $(pkgconf -cflags -static cairo) test-cairo.c $(pkgconf -libs -static cairo) -lstdc++ -liconv

$ echo $?
0

$ ntldd a.exe
        ADVAPI32.dll => C:\Windows\SYSTEM32\ADVAPI32.dll (0x000001d6e9aa0000)
        GDI32.dll => C:\Windows\SYSTEM32\GDI32.dll (0x000001d6e92f0000)
        KERNEL32.dll => C:\Windows\SYSTEM32\KERNEL32.dll (0x000001d6e9b50000)
        MSIMG32.dll => C:\Windows\SYSTEM32\MSIMG32.dll (0x000001d6e92f0000)
        ole32.dll => C:\Windows\SYSTEM32\ole32.dll (0x000001d6e9aa0000)
        RPCRT4.dll => C:\Windows\SYSTEM32\RPCRT4.dll (0x000001d6e9bf0000)
        USER32.dll => C:\Windows\SYSTEM32\USER32.dll (0x000001d6ea440000)
        USP10.dll => C:\Windows\SYSTEM32\USP10.dll (0x000001d6e92a0000)
```

**Comment by revelator** [comment]
try -static -static-libgcc -static-libstdc++ in LDFLAGS linking against -lstdc++ pulls in the libgcc dll unless you use -static-libstdc++ as well.

**Comment by afalkenhahn** [comment]
Oh right, that fixed the issue. I was using `-Wl,-Bstatic -lstdc++ -lgcc_eh -lpthread -lgcc_eh` instead but apparently that's not enough. Adding `-static-libgcc -static-libstdc++` fixes the problem. Sorry for the false alarm.

**Comment by revelator** [comment]
honest mistake tbh. not everyone knows this quirk with gcc :) good that things work again.
