### ISSUE TITLE
Add gjs

### ISSUE THREAD

**Issue by taozuhong** [msys2/MINGW-packages#17733]
### Package name

gjs

### Brief description of package

GNOME Javascript bindings

### URL for package's homepage

https://gitlab.gnome.org/GNOME/gjs

### Provide a basic test case to validate the package's functionality.

libpeas will add gjs support, so gjs package should add to package list.

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by lillolollo** [comment]
This is already requested #5699

**Comment by Biswa96** [comment]
Duplicate of #5699
