### ISSUE TITLE
error: inlining failed in call to 'always_inline'

### ISSUE THREAD

**Issue by AdonNeet** [msys2/MINGW-packages#17741]
### Description / Steps to reproduce the issue

when i build and debug something this error sign came:
![image](https://github.com/msys2/MINGW-packages/assets/95969256/244d8d59-894c-4cd2-926b-d2d1e1665393)

then i check the allocator.h problem
![image](https://github.com/msys2/MINGW-packages/assets/95969256/9c8d64fd-f9db-4477-b2ff-ea73015ebea0)

how to solve it?

### Expected behavior

i expected to run my cpp file

### Actual behavior

the error came from the compiler (?)

### Verification

- [x] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Thank you for reporting the issue. Would you like to provide a minimal sample code or proper steps to reproduce the problem?

**Comment by AdonNeet** [comment]
sure, here is the code

`
/*
 *		Author	: AdonNeet
 *		Date	: 2023-07-07 13:34:32.000-05:00
*/
 
#pragma GCC optimize("Ofast")
#pragma GCC target("sse,sse2,sse3,ssse3,sse4,popcnt,abm,mmx,avx,avx2,fma")
#pragma GCC optimize("unroll-loops")
#include <bits/stdc++.h>  
#include <complex>
#include <queue>
#include <set>
#include <unordered_set>
#include <list>
#include <chrono>
#include <random>
#include <iostream>
#include <algorithm>
#include <cmath>
#include <string>
#include <vector>
#include <map>
#include <unordered_map>
#include <stack>
#include <iomanip>
#include <fstream>

#include <climits>
#include <boost/multiprecision/cpp_int.hpp>	// use boost lib
 
using namespace std;
using namespace boost::multiprecision;	// the namespace for boost lib
 
typedef long long ll;
typedef long long int lli;
typedef long double ld;
typedef pair<int,int> p32;
typedef pair<ll,ll> p64;
typedef pair<double,double> pdd;
typedef vector<ll> v64;
typedef vector<int> v32;
typedef vector<vector<int> > vv32;
typedef vector<vector<ll> > vv64;
typedef vector<vector<p64> > vvp64;
typedef vector<p64> vp64;
typedef vector<p32> vp32;
ll MOD = 998244353;
double eps = 1e-12;
#define forn(i,e) for(ll i = 0; i < e; i++)
#define forsn(i,s,e) for(ll i = s; i < e; i++)
#define rforn(i,s) for(ll i = s; i >= 0; i--)
#define rforsn(i,s,e) for(ll i = s; i >= e; i--)
#define ln "\n"
#define dbg(x) cout<<#x<<" = "<<x<<ln
#define mp make_pair
#define pb push_back
#define fi first
#define se second
#define INF 2e18
#define fast_cin() ios_base::sync_with_stdio(false); cin.tie(NULL); cout.tie(NULL)
#define all(x) (x).begin(), (x).end()
#define sz(x) ((ll)(x).size())
 
cpp_int fakt(cpp_int n)
{
	if(n==0)
	return 1;
	return n*fakt(n-1);
}


int main()
{
    #ifndef ONLINE_JUDGE
	freopen("input.txt", "r", stdin);
	freopen("output.txt", "w", stdout);
	#endif
	
	fast_cin();
    int t,n; cpp_int ans;
	cin>>t;
	while(t--){
		cin>>n;
		cout << fakt(n) << ln;
	}
	
	return 0;
}
`

The code is for factorial in t case and (1<=n<=1000)! (i think)

**Comment by Biswa96** [comment]
First, my condolences go out to the person who wrote that code 🙏 Every bit of it looks weird.

Removing the `pragma GCC target` line fixes the error.

**Comment by Biswa96** [comment]
Removing the `pragma GCC target` line fixes the error.

**Comment by AdonNeet** [comment]
sorry for my bad code if my code looks weird :)
and thanks for the solution, now it works again :D

![image](https://github.com/msys2/MINGW-packages/assets/95969256/ab7e0e7c-2f7c-4a89-9046-0894e60faaec)

**Comment by AdonNeet** [comment]
I think this case is over, time to close the issue
