### ISSUE TITLE
include-what-you-use craches with an assertion

### ISSUE THREAD

**Issue by the-m-master** [msys2/MINGW-packages#17743]
### Description / Steps to reproduce the issue

When using include-what-you-use, it will stop with an assertion failed.
**include-what-you-use-0.20/iwyu.cc:3735: Assertion failed: sema.getCurScope() != nullptr**

### Expected behavior

Normal operation of include-what-you-use (checking the includes what I'm using)

### Actual behavior

It stop right away with an assertion **iwyu.cc:3735: Assertion failed: sema.getCurScope() != nullptr**

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Thank you for reporting the issue. Would you like to provide a minimal sample code or proper steps to reproduce the problem?

**Comment by AlessandroScrem** [comment]
Sample code here:
main.cpp:
`int main() { return 0; }`

C:/msys64/clang64/bin/include-what-you-use.exe main.cpp
C:/M/mingw-w64-include-what-you-use/src/include-what-you-use-0.20/iwyu.cc:3735: Assertion failed: sema.getCurScope() != nullptr

**Comment by Biswa96** [comment]
Hi @the-m-master @AlessandroScrem, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Comment by AlessandroScrem** [comment]
Thank you for fixing the issue.

I would like to test the  updated package.
How can i download the updated package from GitHub?
Thanks

**Comment by Biswa96** [comment]
I have tested it with few examples. The updated package will be provided after some time/days.
