### ISSUE TITLE
Large exe file on mingw for Hello World!

### ISSUE THREAD

**Issue by iostream64** [msys2/MINGW-packages#17753]
### Description / Steps to reproduce the issue

I installed mingw on my system  to compile executable files for windows. The problem is the generated exe file is so large around 2-3mb. **The same program on other compiler is about 100kb.** 

My program is just "Hello World".

```cpp
#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}
```

### Expected behavior

"Hello World" program should be maximum 100-200kb. The same program on other compiler is about 100kb.

### Actual behavior

I use  `g++ main.cpp -static` to compile my program.

And if I disable `-static`, this error shown:

![image](https://github.com/msys2/msys2.github.io/assets/139329555/f0e27edd-fdc3-49c5-b30c-994767f61b53)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19044

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> The problem is the generated exe file is so large around 2-3mb.

This is expected behaviour. 

> And if I disable -static, this error shown

Also expected due to linking with shared libraries.
