### ISSUE TITLE
[qt6-base] windeployqt6.exe creashed with version 6.5.1

### ISSUE THREAD

**Issue by gcjyzdd** [msys2/MINGW-packages#17765]
### Description / Steps to reproduce the issue

`windeployqt6.exe` causes Segmentation fault.

Steps to reproduce: just install Qt6 via

``` sh
pacman -S --noconfirm mingw64/mingw-w64-x86_64-gcc
pacman -S --noconfirm mingw64/mingw-w64-x86_64-gdb
pacman -S --noconfirm mingw64/mingw-w64-x86_64-make
pacman -S --noconfirm mingw64/mingw-w64-x86_64-cmake

pacman -S --noconfirm mingw64/mingw-w64-x86_64-qt6
```

I also tried to `export QTC_USE_QPROCESS=1` before running `windeployqt6.exe` and it gave me the same error.

### Expected behavior

By default, it should show the help menu.

### Actual behavior

It has a Segmentation fault error.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19042

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> By default, it should show the help menu.

windeployqt6.exe does show help menu in my system. Here is a screenshot of that output.

![image](https://github.com/msys2/MINGW-packages/assets/31443074/fba9a34b-7cf8-46f2-ba1a-bac1cbffef0b)

**Comment by gcjyzdd** [comment]
I updated all packages (mainly gcc and other utilities, I didn't see an update of qt in the list) a few minutes ago and windeployqt6 starts working again(with MinGW64).
