### ISSUE TITLE
Capstone package no longer includes static libraries

### ISSUE THREAD

**Issue by solemnwarning** [msys2/MINGW-packages#17779]
### Description / Steps to reproduce the issue

The capstone library packages (mingw-w64-x86_64-capstone, mingw-w64-i686-capstone) no longer include static libraries, anything that tries building against `-lcapstone` fails to link. I've verified this on MinGW32/64, may apply to the other toolchains too.

### Expected behavior

The libcapstone.a library should be present so you can link against it.

### Actual behavior

The libcapstone.a library is not present.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19044

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Opps! my mistake. I did not notice that in this update https://github.com/msys2/MINGW-packages/pull/17775
