### ISSUE TITLE
scrcpy can't find /share/scrcpy-server file

### ISSUE THREAD

**Issue by ognevnydemon** [msys2/MINGW-packages#17778]
### Description / Steps to reproduce the issue

1. ensure that device is connected using `adb devices`
2. execute `scrcpy`

### Expected behavior

program starts properly

### Actual behavior

scrcpy-server exists but program can't detect it
```console
$ scrcpy
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  2C050DLH2000WA                  device  Pixel_7
stat: No such file or directory
ERROR: '/clang64/share/scrcpy/scrcpy-server' does not exist or is not a regular file
ERROR: Server connection failed
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
The path to scrcpy-server is not relocated yet in scrcpy mingw package. `SCRCPY_SERVER_PATH` environment variable is required to be set to that scrcpy-server path.

**Comment by ognevnydemon** [comment]
it works, thanks!

as I understand, this is temporary issue, right?

**Comment by Biswa96** [comment]
> as I understand, this is temporary issue, right?

Nope. This is a real issue. I was using the environment variable workaround myself. But maybe it's time to fix the issue. Reopeing...

**Comment by ognevnydemon** [comment]
> Nope. This is real issue

I meant it should be fixed soon

**Comment by ognevnydemon** [comment]
also I found this thing while starting
```console
ERROR: Could not open icon image: /clang64/share/icons/hicolor/256x256/apps/scrcpy.png
WARN: Could not load icon
```
