### ISSUE TITLE
Issues using archive mail with python2

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#17781]
### Description / Steps to reproduce the issue

I still have MSYS2-python2 installed

```
$ python2 --version
Python 2.7.18
```

and it used to work for years with [archivemail](https://archivemail.sourceforge.net), based on it. Since it has

```
$ head archivemail/archivemail
#! /usr/bin/env python
...
```

I used it as follows (really with a bash function) and the steps to reproduce the issues are the following:

```
$ cd /tmp
$ git clone git://archivemail.git.sourceforge.net/gitroot/archivemail/archivemail

$ /usr/bin/python2 /tmp/archivemail/archivemail -D 2021-12-31 --copy --no-compress imap://username@foobar.it/IN
BOX
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
IMAP password:
```

As you see it ask for password but there are a lot of garbage error messages. The same steps on GNU/Linux Mint 21.1 on which 2.7 is installed, ask only the password, no error message.

Running on MSYS2/MINGW64 fails completely:

```
$ /mingw64/bin/python2 /tmp/archivemail/archivemail -D 2021-12-31 --copy --no-compress imap://username@foobar.it/INBOX
Traceback (most recent call last):
  File "C:/msys64/tmp/archivemail/archivemail", line 54, in <module>
    import fcntl
ImportError: No module named fcntl
```

Same results if I change the python script changing `#! /usr/bin/env python` with `#! /usr/bin/env python2` or `#! /usr/bin/python2` and so on

### Expected behavior

It should work without errors and after asking the password it should download the emails requested in a INBOX_archive. I have emails saved this way since 2016... (maybe older on CD/DVD storage)

### Actual behavior

Fail as above

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
We have removed Python2 a long time ago: https://github.com/msys2/MSYS2-packages/pull/2131

I assume you have an outdated version still installed, and that fails because openssl is no longer there.

As for `fcntl`, that's a unix only thing, so likely archivemail does not support Windows.

**Comment by angelog0** [comment]
> I assume you have an outdated version still installed,

it is 2.7.18 the same I have in MSYS2/MINGW64 and in GNU/Linux Mint 21.1..

> and that fails because openssl is no longer there.

I have 

```
msys/libopenssl 3.1.1-1 (libraries) [installato]
msys/openssl 3.1.1-1 [installato]
```

Instead, `msys/openssl-devel 3.1.1-1 (development)` is NOT installed. I doubt it would fix these issues.. Right?

Maybe I have to migrate on GNU/Linux Mint do save emails until I will find a substitute of `archivemail`. Do you know any?

**Comment by lazka** [comment]
try `/usr/bin/python2 --version`

**Comment by angelog0** [comment]
> try /usr/bin/python2 --version

```
$ /usr/bin/python2 --version
Python 2.7.18
```

**Comment by lazka** [comment]
oh, right, we also shipped the last verion. Either way that package is long gone/unsupported, sorry.

re openssl, I mean openssl-1.1, which no longer is in the repo.

**Comment by lazka** [comment]
google gives me https://groups.google.com/g/linux.debian.user/c/LkGHfdfLbfk

**Comment by angelog0** [comment]
Oh thanks. It seems `chewmail` is the candidate... May be it could be added to MSYS2...

**Comment by angelog0** [comment]
It seems that `chewmail` the `--copy` option, so it only moves mails from an archive to another but often one wants only copy some emails leaving the original archive intact.

**Comment by Biswa96** [comment]
python2 is no more... 💀
