### ISSUE TITLE
Add ansifilter

### ISSUE THREAD

**Issue by Freed-Wu** [msys2/MINGW-packages#17791]
### Package name

ansifilter

### Brief description of package

ANSI sequence filter

Some reference:

- [NixOS](https://search.nixos.org/packages?query=ansifilter)
- [ArchLinux](https://aur.archlinux.org/packages/ansifilter)
- [Homebrew](https://formulae.brew.sh/formula/ansifilter)

### URL for package's homepage

<http://www.andre-simon.de/doku/ansifilter/en/ansifilter.php>

<https://gitlab.com/saalen/ansifilter>

### Provide a basic test case to validate the package's functionality.

```sh
ansifilter -i input.ansi -o output.txt
tail -f server.log | ansifilter
```

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by sskras** [comment]
I imported `PKGBUILD` from Arch Linux in late 2021:
https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=ansifilter&id=2e8d8839eca24245f1b14dfc4e7b9d54999794df

Maybe it's possible to just import the newest version:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ansifilter (use Plain link as the page doesn't render part of the file).

Not sure what to do about copyright.  There seems to be two contributors:
```sh
$ git blame -e PKGBUILD | awk 'BEGIN {FS="[<>]"} {print $2}' | sort -u
adsun701@gmail.com
contact@elelay.fr

$ head -3 PKGBUILD
# Maintainer: Andrew Sun <adsun701 at gmail dot com>
# Contributor: Eric Le Lay <contact at elelay dot fr>

```

But then I created an `MSYS2-packages` style package. No idea about `MINGW-packages`.
