### ISSUE TITLE
helix not launching (installed via msys2)

### ISSUE THREAD

**Issue by goyalyashpal** [msys2/MINGW-packages#17797]
### Description / Steps to reproduce the issue

"Steps" as well as "Actual behaviour"

```console
$ pacboy debug -S helix:x
:: Executing pacman --color auto -S mingw-w64-x86_64-helix...
   ... MORE ...

$ # helix's executable name elsewhere is hx; following from that expectation
$ hx
bash: hx: command not found

$ helix
/mingw64/bin/helix: line 3: /lib/helix/hx.exe: No such file or directory
```

### Expected behavior

`hx` runs fine, and launches the helix editor

### Actual behavior

1. the `hx` command is not found, and 
2. with `helix`, it says: `/mingw64/bin/helix: line 3: /lib/helix/hx.exe: No such file or directory`

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

`uname`
* `-s`: MSYS_NT-10.0-19045
* `-r`: 3.4.7.x86_64

### MINGW environments affected

- [x] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by goyalyashpal** [comment]
* https://github.com/helix-editor/helix/discussions/8017

**Comment by Biswa96** [comment]
It's launching fine in my system. Are you using the MINGW64 or UCRT64 launchers?

**Comment by goyalyashpal** [comment]
> Are you using the MINGW64 or UCRT64 launchers?

nope

**Comment by ognevnydemon** [comment]
> > Are you using the MINGW64 or UCRT64 launchers?
> 
> nope; i used the `konsole` terminal

what's output of `echo $MSYSTEM`?

**Comment by goyalyashpal** [comment]
> Here is a screenshot of helix working in UCRT64 in konsole.

it works.... but why is that so? how to know which packages require this umh, constraint??

**Comment by Biswa96** [comment]
> how to know which packages require this umh, constraint??

No extra packages are required beside helix itself.

**Comment by goyalyashpal** [comment]
> No extra packages are required beside helix itself.

i meant say i download package xyz in future, how do i know, if possible in advance, that it would require this procodure?

**Comment by Biswa96** [comment]
> how do i know, if possible in advance, that it would require this procodure?

Ask the question when it breaks.
