### ISSUE TITLE
glog bails on 32 bit

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#17853]
### Description / Steps to reproduce the issue

on 32 bit mingw glog bails on weak references to libunwind symbols.
using the previous version 0.5.0 works so it seems to be a recent change.

### Expected behavior

glog building for 32 bit arch.

### Actual behavior

bails with undefined symbols pointing to weak references in the libunwind library unw_* etc.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19044

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Please provide the error output and steps to reproduce the issue.

**Comment by revelator** [comment]
```
[16/29] Linking CXX shared library libglog.dll
FAILED: libglog.dll libglog.dll.a
cmd.exe /C "cd . && D:\msys64\mingw32\bin\g++.exe -march=pentium4 -mtune=generic -O2 -pipe -O3 -DNDEBUG  -pipe -Wl,--no-seh -Wl,--large-address-aware -shared -o libglog.dll -W
l,--out-implib,libglog.dll.a -Wl,--major-image-version,0,--minor-image-version,6 CMakeFiles/glogbase.dir/src/demangle.cc
.obj CMakeFiles/glogbase.dir/src/logging.cc.obj CMakeFiles/glogbase.dir/src/raw_logging.cc.obj CMakeFiles/glogbase.dir/s
rc/symbolize.cc.obj CMakeFiles/glogbase.dir/src/utilities.cc.obj CMakeFiles/glogbase.dir/src/vlog_is_on.cc.obj CMakeFile
s/glogbase.dir/src/signalhandler.cc.obj CMakeFiles/glogbase.dir/src/windows/port.cc.obj  -ldbghelp  D:/msys64/mingw32/li
b/libgflags.dll.a  D:/msys32/mingw32/lib/libunwind.dll.a  -lshlwapi  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -l
ole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
D:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: CMakeFiles/glogbase.di
r/src/utilities.cc.obj:utilities.cc:(.text+0x76): undefined reference to `unw_getcontext'
D:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: CMakeFiles/glogbase.di
r/src/utilities.cc.obj:utilities.cc:(.text+0x82): undefined reference to `unw_init_local'
D:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: CMakeFiles/glogbase.di
r/src/utilities.cc.obj:utilities.cc:(.text+0xae): undefined reference to `unw_get_reg'
D:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: CMakeFiles/glogbase.di
r/src/utilities.cc.obj:utilities.cc:(.text+0xc1): undefined reference to `unw_step'
D:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: CMakeFiles/glogbase.di
r/src/utilities.cc.obj:utilities.cc:(.text+0xf6): undefined reference to `unw_step'
collect2.exe: error: ld returned 1 exit status

```

steps are makepkg-mingw -c -i --skippgp --nocheck

**Comment by Biswa96** [comment]
Where does this come from `D:/msys32/` ?

**Comment by revelator** [comment]
strange did not notice that ?? i have both msys32 and msys64 on the same drive but it should not pick up the msys32 dir when working from msys64 huh... but i got a little closer turns out my libunwind library does not even have those exports Oo while a previous version does. not sure what went wrong there.

**Comment by revelator** [comment]
disabled linking to libunwind for now, will try a rebuild of libunwind to see if the exports are still missing.

**Comment by revelator** [comment]
yeah new rebuild also does not have these exports, bug in libunwind or is ld acting up ?

**Comment by Biswa96** [comment]
The issue can not be reproduced. The glog shared library was compiled successfully. Here is the output of ntldd with libglog.dll.

```
$ ntldd pkg/mingw-w64-i686-glog/mingw32/bin/libglog.dll
        libgcc_s_dw2-1.dll => F:\msys64\mingw32\bin\libgcc_s_dw2-1.dll (0x00f60000)
        KERNEL32.dll => C:\Windows\SYSTEM32\KERNEL32.dll (0x00f90000)
        msvcrt.dll => C:\Windows\SYSTEM32\msvcrt.dll (0x00f90000)
        libwinpthread-1.dll => F:\msys64\mingw32\bin\libwinpthread-1.dll (0x003e0000)
        libstdc++-6.dll => F:\msys64\mingw32\bin\libstdc++-6.dll (0x00f60000)
        libgflags.dll => F:\msys64\mingw32\bin\libgflags.dll (0x00f60000)
        libunwind.dll => F:\msys64\mingw32\bin\libunwind.dll (0x00f60000)
```

Please make sure your system does not have other issues.

**Comment by revelator** [comment]
was this with the latest libunwind ? in that case im not sure whats up.

**Comment by Biswa96** [comment]
> was this with the latest libunwind ? in that case im not sure whats up.

It seems so https://packages.msys2.org/package/mingw-w64-i686-libunwind?repo=mingw32 

```
x@y MINGW32 ~
$ pacboy -Qi libunwind:p
Name            : mingw-w64-i686-libunwind
Version         : 16.0.5-1
Description     : A new implementation of a stack unwinder for C++ exceptions (mingw-w64)
```

**Comment by revelator** [comment]
doh i know why... i built clang with sjlj exceptions seems it also translates to libunwind no longer including the symbols for the other exception models bummer. and to make matters worse glog expects libunwind to have dwarf exceptions on 32 bit.
i got around the problem by linking it to the gcc runtimes instead (strangely dwarf is not a hard requirement with the gcc runtimes).
