### ISSUE TITLE
[nlohmann-json]

### ISSUE THREAD

**Issue by Avdieienko** [msys2/MINGW-packages#17851]
Error 1: name followed by '::' must be a class or namespace name
Error 2: namespace "std" has no member "cout"

Downloaded library through MSYS2 (pacman), all files are present in the mingw64/include directory
Tried different "Include path" in the c_cpp_properties.json
When leaving
 `            "includePath": [
                "${default}"
            ],` library nlohmann is not found, but when
 `            "includePath": [
                "${default}",
                "C:/msys64/mingw64/include"
            ],` namespace "std" has no member "cout"

In both occurrences "name followed by '::' must be a class or namespace name" error in nlohmann::json

![image](https://github.com/msys2/MINGW-packages/assets/96653832/7d74d34c-76d6-47bb-8747-e4917bdb9072)
c_cpp_properties.json
![image](https://github.com/msys2/MINGW-packages/assets/96653832/13ce1895-d508-4724-be58-b0e2093d9bff)
tasks.json
![image](https://github.com/msys2/MINGW-packages/assets/96653832/4b4e1b70-8755-4f0b-9937-3ce6932b77c8)

**Comment by Biswa96** [comment]
Please fill up the issue template and explain the issue.

**Comment by mmuetzel** [comment]
You seem to be mixing the compiler from MSVC `cl.exe` with headers from GCC/MinGW - or the other way round.
That won't work.

**Comment by Avdieienko** [comment]
My bad,  @mmuetzel prompt is correct
`{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${default}",
                "C:/msys64/mingw64/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "C:\\msys64\\mingw64\\bin\\gcc.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-gcc-x64"
        }
    ],
    "version": 4
}`

Work correct, no errors, thanks

**Comment by Avdieienko** [comment]
My bad, @mmuetzel prompt is correct, just change compiler path in c_cpp_properties.json to C:\msys64\mingw64\bin\gcc.exe and intelliSenseMode to windows-gcc-x64

Work correct, no errors, thanks
