### ISSUE TITLE
[python] some scripts contain full build path in python 3.11

### ISSUE THREAD

**Issue by MaxGaspa** [msys2/MINGW-packages#17929]
### Description / Steps to reproduce the issue

I recently updated my MSYS2  installation (ucrt64) and the  scripts  in /ucrt64/bin   idle ,  idle3 and  idle3.11 are wrong .They are using      #!D:/a/msys64/ucrt64/bin/python3.11.exe.    Shouldn't it be   #!/ucrt64/bin/python3.11.exe? 

### Expected behavior

idle script working

### Actual behavior

not working, running idle I got 

 -bash: /ucrt64/bin/idle: cannot execute: required file not found

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19044

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
thanks
