### ISSUE TITLE
Add yt-dlp

### ISSUE THREAD

**Issue by cmdrkotori** [msys2/MINGW-packages#17921]
### Package name

yt-dlp

### Brief description of package

yt-dlp is a youtube-dl fork based on the now inactive youtube-dlc. The main focus of this project is adding new features and patches while also keeping up to date with the original project.

The latest release of yt-dlp was 2023-07-06, while the latest release of youtube-dl is 20**21**-12-17. You may want to consider dropping youtube-dl from the repo in favor of yt-dlp. By packaging yt-dlp in favor of youtube-dl, I would be able to easily bundle a working version of the stream downloader from inside a CI server.

### URL for package's homepage

https://github.com/yt-dlp/yt-dlp

### Provide a basic test case to validate the package's functionality.

`yt-dlp <url>`

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No because I only have two or so hours free a day, but there is an Arch PKGBUILD at https://gitlab.archlinux.org/archlinux/packaging/packages/yt-dlp/-/blob/main/PKGBUILD.

**Comment by Biswa96** [comment]
Hi @cmdrkotori, I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request?
