### ISSUE TITLE
pyside2 not able to build with current qt5

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#17934]
### Description / Steps to reproduce the issue

complains about QDragMove not being defined.

### Expected behavior

that it builds.

### Actual behavior

pyside2 is a bit borked with the current qt5 there is a patch here from openmandriva https://github.com/OpenMandrivaAssociation/qt5-qtbase/blob/master/qtbase-5.15.9-work-around-pyside2-brokenness.patch

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

not related

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
We already use that patch.

**Comment by revelator** [comment]
ah recently added i see...
