### ISSUE TITLE
Add VisualizationLibrary

### ISSUE THREAD

**Issue by asmwarrior** [msys2/MINGW-packages#17943]
### Package name

VisualizationLibrary

### Brief description of package

This is a OpenGL based library, and support many GUI framework, such as wxWidgets and QT.
This is the github site: [VisualizationLibrary](https://github.com/MicBosi/VisualizationLibrary), it also has its own official site here: https://www.visualizationlibrary.org/, you can see there are many screen shots here: [Visualization Library: Visualization Library Gallery](https://visualizationlibrary.org/docs/2.1/html/pag_gallery.html)

This library supporting building by CMake, see here: https://visualizationlibrary.org/docs/2.1/html/pag_install.html

### URL for package's homepage

https://www.visualizationlibrary.org/

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment]
Is that project in development? The last commit was a year ago.

**Comment by asmwarrior** [comment]
I first used this library in year 2020. I think this library is quite mature, I see it published a new release in year 2021.
If it has arrived in the msys2's package, it will certainly has more users.

I think using OpenGL in GUI framework, especially in wxWidgets is a very common need. 

This library's code base is much smaller than [Package: mingw-w64-x86_64-magnum - MSYS2 Packages](https://packages.msys2.org/package/mingw-w64-x86_64-magnum) (which is version 2020 in msys2's package), and [Package: mingw-w64-x86_64-ogre3d - MSYS2 Packages](https://packages.msys2.org/package/mingw-w64-x86_64-ogre3d).

**Comment by asmwarrior** [comment]
The build step is simple if you need link to the wxWidgets library under msys2, I have another post mention this steps: [Screen shots when running visualization library under Windows' msys2 · Issue #212 · MicBosi/VisualizationLibrary](https://github.com/MicBosi/VisualizationLibrary/issues/212)

**Comment by Biswa96** [comment]
I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request?

Do you need the package for all MSYSTEMs and 32 bit also?

**Comment by asmwarrior** [comment]
Hi, thanks. I will test it as soon as possible. In fact, I am currently only use mingw64 targets.

By the way, how can I download the build package from you pull request.

Another question is that did you enable some gui support?

**Comment by Biswa96** [comment]
> how can I download the build package from you pull request.

Please follow these steps for testing package in CI artifacts.

1. Go to this page https://github.com/msys2/MINGW-packages/actions/runs/5771231258 > scroll down > download the XYZ-packages.zip file. The XYZ should match with the value of `$MSYSTEM` variable.
2. Extract the .tar.zst file from that ZIP.
3. Install the .tar.zst file with `pacman -U <full path of .tar.zst file>` command.

> Another question is that did you enable some gui support?

I am not sure about that. Please suggest any required changes for that PKGBUILD file.

**Comment by asmwarrior** [comment]
Thanks, I will try your CI artifacts if I got time, I will go traveling next week, not sure I will got test time vary soon. But this project do works on Msys2 ( I can build it with wxWidgets gui support on msys2 mingw64 shell), running the test is vary simple, see here: [Screen shots when running visualization library under Windows' msys2 · Issue #212 · MicBosi/VisualizationLibrary](https://github.com/MicBosi/VisualizationLibrary/issues/212)


> > Another question is that did you enable some gui support?
> 
> I am not sure about that. Please suggest any required changes for that PKGBUILD file.

You can see this post: [when building this library wxWidgets support under msys2, I got build error, here is a patch to fix the error · Issue #210 · MicBosi/VisualizationLibrary](https://github.com/MicBosi/VisualizationLibrary/issues/210)

I have enabled the wxWidgets gui option in the cmake command option, and it works fine. (a small file change is needed, I also have patch in that issue)

I'm not familiar with QT, so I don't have any idea about how to enable QT or whether it works OK when QT gui is enabled.

**Comment by asmwarrior** [comment]
Oh, I just see that you have merged your branch to the master, many thanks!
