### ISSUE TITLE
[binutils] latest versoin of mingw-w64-x86_64-binutils-2.41-1 had compile error when build ffmpeg

### ISSUE THREAD

**Issue by karvn** [msys2/MINGW-packages#17946]
### Description / Steps to reproduce the issue

1 download msys2 and install

2 open mingw64.exe

3 install packages for build ffmpeg
pacman -S mingw-w64-x86_64-toolchain git make automake autoconf perl mingw-w64-x86_64-SDL2 libtool mingw-w64-x86_64-cmake pkg-config yasm diffutils nasm mingw-w64-x86_64-x264 mingw-w64-x86_64-x265 mingw-w64-x86_64-yasm mingw-w64-x86_64-nasm

4 download ffmpeg source code
git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg

5 configure ffmpeg
./configure \
--prefix=/YourFfmpegOutputDir/buildout \
--disable-static \
--enable-shared \
--enable-sdl2 \
--enable-stripping \
--enable-optimizations \
--enable-asm \
--enable-decoder=mjpeg,png \
--enable-demuxer=image2 \
--enable-protocol=file \
--enable-zlib \
--enable-w32threads \
--disable-autodetect

6 compile ffmpeg
make -j12

7 now compile success, because mingw-w64-x86_64-binutils is an old version

8 we update msys2 and all packages to latest
pacman -Syyu
This will upgrade msys2, then reopen mingw64.exe and execute
pacman -Syyu
This will install latest version of mingw-w64-x86_64-binutils

9 after install complete, delete compiled output file
delete "YourFfmpegDir"/libavutil/hdr_dynamic_metadata.o

"YourFfmpegDir" is your ffmpeg source code dir

10 compile ffmpeg
make -j12

11 compile failed, error occur:
CC      libavutil/hdr_dynamic_metadata.o
C:\msys64\tmp\ccvQeWeD.s: Assembler messages:
C:\msys64\tmp\ccvQeWeD.s:251: Error: operand type mismatch for `shr'
C:\msys64\tmp\ccvQeWeD.s:295: Error: operand type mismatch for `shr'
C:\msys64\tmp\ccvQeWeD.s:386: Error: operand type mismatch for `shr'

12 we downgrade mingw-w64-x86_64-binutils-2.41-1 to mingw-w64-x86_64-binutils-2.40-4, and compile again, compile will be success, follow the steps

13 download mingw-w64-x86_64-binutils-2.40-4-any.pkg.tar.zst from https://repo.msys2.org/mingw/mingw64/

14 install downloaded package:
pacman -U mingw-w64-x86_64-binutils-2.40-4-any.pkg.tar.zst

15 compile again
make -j12

16 compile ffmpeg success with mingw-w64-x86_64-binutils-2.40-4

Now, i can confirm that mingw-w64-x86_64-binutils-2.41-1 will cause ffmpeg compile failed, but mingw-w64-x86_64-binutils-2.40-4 is ok. 

### Expected behavior

Expected mingw-w64-x86_64-binutils-2.41-1 build ffmpeg successfully.

### Actual behavior

Actually, mingw-w64-x86_64-binutils-2.41-1 build ffmpeg failed.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22000

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
This maybe https://github.com/FFmpeg/FFmpeg/commit/effadce6c756247ea8bae32dc13bb3e6f464f0eb ?
