### ISSUE TITLE
[python-lief] ImportError: dynamic module does not define module export function (PyInit_lief)

### ISSUE THREAD

**Issue by WillyAguilera1977** [msys2/MINGW-packages#17942]
### Description / Steps to reproduce the issue

By running the following code:

```
import lief

# PE
binary = lief.parse("C:\\Windows\\explorer.exe")
print(binary)

```
It gives this error:
C:\Programming\Python\Learn\LiefTest>python3 main.py
Traceback (most recent call last):
   File "C:\Programming\Python\Learn\LiefTest\main.py", line 1, in <module>
     import lief
ImportError: dynamic module does not define module export function (PyInit_lief)

### Expected behavior

I would have to import the lief module and show information about the executable

### Actual behavior

It shows the error:
ImportError: dynamic module does not define module export function (PyInit_lief)

and finish

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I can reproduce it in my system.

```
$ python
Python 3.11.4 (main, Aug  2 2023, 21:04:34)  [GCC UCRT 13.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import lief
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_lief)
>>>
```

We shall look into it.

**Comment by Biswa96** [comment]
There are many issues in the project. I shall try to send those changes to upstream first.

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Comment by hartwork** [comment]
@Biswa96 thanks for #17947! Not being on Windows myself (but Linux), I lack bandwidth to do the suggested testing myself right now. Maybe from inside CI later, likely doable but not a 5 minute thing. I hope that's okay with you.

**Comment by Biswa96** [comment]
No problem. I have tested it with the example OP provided.

**Comment by hartwork** [comment]
@Biswa96 thanks for the quick fix! Any idea when the binary host will start serving the fixed `0.13.2-2`?

**Comment by Biswa96** [comment]
>  Any idea when the binary host will start serving the fixed 0.13.2-2?

This [queue page](https://packages.msys2.org/queue) should not have python-lief. Then update the packages as usual with `pacman -Syu` command.

**Comment by hartwork** [comment]
@Biswa96 I see, thanks!

**Comment by Biswa96** [comment]
Related question but off-topic. Is there any issue not to enable other executable file format like ELF, MachO etc. ? I  would like to enable those formats. It seems useful for poking into binaries. For example, here is a example with the init binary for WSL1.

```py
>>> import lief
>>> elf = lief.parse("C:\\Windows\\System32\\lxss\\tools\\init")
>>> print(f"Format: {elf.header.file_type}")
Format: E_TYPE.EXECUTABLE
>>> print(f"Entry point: 0x{elf.header.entrypoint:08x}")
Entry point: 0x00226000
>>> print(f"Number of sections: {len(elf.sections)}")
Number of sections: 16
>>> print(f"Number of segments: {len(elf.segments)}")
Number of segments: 8
```
