### ISSUE TITLE
Inkscape fails to run.

### ISSUE THREAD

**Issue by cmdrkotori** [msys2/MINGW-packages#17972]
### Description / Steps to reproduce the issue

Inkscape fails to run. This was found by trying to run `magick convert` on a svg to make an ico file in a build server.
1. `pacman -S mingw-w64-x86_64-inkscape`
2. `inkscape`

### Expected behavior

Inkscape runs.

### Actual behavior

I receive the error message `error while loading shared libraries: libinkscape_base.dll: cannot open shared object file: No such file or directory`

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19044

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

I literally have no idea what the problem would be.

**Comment by Biswa96** [comment]
Thank you for reporting the issue. It seems that the boost package was not added in the dependency list.

```
$ ntldd /mingw64/bin/libinkscape_base.dll | grep -i not
        libboost_filesystem-mt.dll => not found
```

Just installing boost package may work. Run `pacman -S $MINGW_PACKAGE_PREFIX-boost` command to install boost package.
