### ISSUE TITLE
[mpv] please build with javascript support

### ISSUE THREAD

**Issue by AeliusSaionji** [msys2/MINGW-packages#17994]
### Package name

mpv

### Other information that may be useful

Currently, the provided build of mpv only supports lua scripts.

Thanks!

**Comment by Biswa96** [comment]
Would you like to provide any steps to verify that JS is working in mpv? There is a pending pull request to add the feature in mpv.

**Comment by AeliusSaionji** [comment]
Thank you. I will test it soon. I also probably need another change made- for some reason the sponsor block lua/Python script isn't working in this build of mpv, but it does work in other builds

**Comment by AeliusSaionji** [comment]
> Would you like to provide any steps to verify that JS is working in mpv?

The simplest is probably to load this js script https://github.com/ento/mpv-cheatsheet

As per the instructions, drop it in the scripts folder, or `mpv video.mp4 --script=mpv-cheatsheet.js`
Activate the cheatsheet overlay by pressing `?`

It works here 👍 
Sponsorblock also is now working here as well.

Thanks!
