### ISSUE TITLE
[glslang] glslang did not make a copy of itself as glslangValidator

### ISSUE THREAD

**Issue by MeteorEmber** [msys2/MINGW-packages#18163]
### Description / Steps to reproduce the issue

1. Install mingw-w64-[env]-x86_64-glslang
2. /[env]/bin/glslang.exe is there, but glslangValidator.exe is not

### Expected behavior

We should have a copy of glslang.exe renamed as glslangValidator.exe, so that the existing projects that using glslangValidator as excutable name could work. For now I have to manually copy and rename it, which should be done by package manager.

In arch linux, they have /usr/bin/glslang and /usr/bin/glslangValidator, two separated but actually the same excutables.

Also I've noticed the older versions of glslang package in msys2 repos comes with glslangValidator.exe, but the current latest version does not.

### Actual behavior

Only glslang is available, glslangValidator need to be copied and renamed manually.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by MehdiChinoune** [comment]
Please fill this issue to glslang project, We were not the ones who decide to rename glslangValidator to glslang.

**Comment by MehdiChinoune** [comment]
see: https://github.com/KhronosGroup/glslang/issues/3281
I will try to backport https://github.com/KhronosGroup/glslang/pull/3283
