### ISSUE TITLE
Add nerd-fonts

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#18178]
### Package name

nerd-fonts

### Brief description of package

See https://github.com/msys2/MINGW-packages/pull/17833

The Arch variant as split package is here: https://gitlab.archlinux.org/archlinux/packaging/packages/nerd-fonts/-/blob/main/PKGBUILD

### URL for package's homepage

https://github.com/ryanoasis/nerd-fonts

### Provide a basic test case to validate the package's functionality.

not sure

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

not now

**Comment by lazka** [comment]
@ognevnydemon

**Comment by ognevnydemon** [comment]
> @ognevnydemon

oh, I don't have access to the computer now, but you can just take recipe from https://github.com/msys2/MINGW-packages/commit/71d4113956182f8d35a9eecc111c2a2d0989bbde (but I deleted branch 🙁) and make it buildable
