### ISSUE TITLE
setup environment

### ISSUE THREAD

**Issue by sniper-1x** [msys2/MINGW-packages#18186]
### Description / Steps to reproduce the issue

when writing this code
#include <iostream>
using namespace std;

int main()
{
    std::cout << "Hello World!";
    return 0;
}

### Expected behavior

to get the output

### Actual behavior

it get these errors
1/  #include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (D:\main.cpp).
2/   cannot open source file "iostream". Please run the 'Select IntelliSense Configuration...' command to locate your system headers.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

22H2

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
This issue is not related to msys2 or mingw-w64.
