### ISSUE TITLE
[pandas] update to 2.0.3

### ISSUE THREAD

**Issue by sam-s** [msys2/MINGW-packages#18193]
### Package name

pandas

### New version number

2.0.3

### Other information that may be useful

https://pandas.pydata.org/
you provide relatively ancient 1.5.3

**Comment by Kreijstal** [comment]
padas 2.0.0 adds a new dependency: python-versioneer which is not in msys2 yet

**Comment by lazka** [comment]
Fixed in d258664a3db99a3d9a8d6bca8781f57ee4403b8b
