### ISSUE TITLE
[MSYS2 CLANG64] error while loading shared libraries: zlib1.dll

### ISSUE THREAD

**Issue by iahung2** [msys2/MINGW-packages#18235]
### Discussed in https://github.com/msys2/MINGW-packages/discussions/18233

<div type='discussions-op-text'>

<sup>Originally posted by **iahung2** August 22, 2023</sup>
@Biswa96 Try compiling a simple program which links with zlib via `-lz`. The compilation is fine but when you run it, it will fail to run with:

` error while loading shared libraries: zlib1.dll: cannot open shared object file: No such file or directory`

```
$ file /clang64/bin/zlib1.dll
/clang64/bin/zlib1.dll: PE32+ executable (DLL) (GUI) x86-64, for MS Windows, 8 sections
```

```
$ file /ucrt64/bin/zlib1.dll
/ucrt64/bin/zlib1.dll: PE32+ executable (DLL) (console) x86-64 (stripped to external PDB), for MS Windows, 11 sections
```

Something is definitely wrong here.</div>

**Comment by Biswa96** [comment]
Thank you for reporting the issue. Would you like to provide a minimal sample code or proper steps to reproduce the problem?

**Comment by iahung2** [comment]
Sorry everyone, it seems I have some problems with my SSD. It's so embarrassing 😕
