### ISSUE TITLE
[vulkan-validation-layers] library_path in VkLayer_khronos_validation.json is wrong

### ISSUE THREAD

**Issue by MeteorEmber** [msys2/MINGW-packages#18236]
### Description / Steps to reproduce the issue

1. Install vulkan-validation-layers package
2. Add the path of VkLayer_khronos_validation.json to Windows registry as described in #12873 
3. Build the following C++ example program with `g++ -o main main.cpp -lvulkan-1`
```c++
#include <vulkan/vulkan.hpp>
#include <vulkan/vulkan_core.h>

#include <iostream>
#include <vector>

int main() {
  const std::vector<const char *> validation_layers = {
      "VK_LAYER_KHRONOS_validation"};

  VkInstanceCreateInfo create_info{};
  create_info.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
  create_info.enabledLayerCount = 1;
  create_info.ppEnabledLayerNames = validation_layers.data();

  VkInstance vk_instance;
  VkResult vk_result = vkCreateInstance(&create_info, nullptr, &vk_instance);

  std::cout << "vkCreateInstance() returned: " << vk_result << '\n';

  return 0;
}
```
4. Run main.exe with the default vulakn-validation-layers package
5. The output is`vkCreateInstance() returned: -6` which means `VK_ERROR_LAYER_NOT_PRESENT`
6. Modify line 6 of `/ucrt64/bin/VkLayer_khronos_validation.json` from `"library_path": ".\\VkLayer_khronos_validation.dll"` to `"library_path": ".\\libVkLayer_khronos_validation.dll"`
7. Run main.exe, now the ouput is `vkCreateInstance() returned: 0`, which means no errors happened

### Expected behavior

The "library_path" value in VkLayer_khronos_validation.json should be `".\\libVkLayer_khronos_validation.dll"` by default, so that the programs using validation layers would work after adding the json to Windows registry.

### Actual behavior

The "library_path" value is ".\\VkLayer_khronos_validation.dll", which is wrong.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Martysh12** [comment]
This looks like an oversight in [Vulkan-ValidationLayers](https://github.com/KhronosGroup/Vulkan-ValidationLayers)'s build files. I submitted [an issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7213).

**Comment by Martysh12** [comment]
The fix has been merged, now we need wait for a new release.

**Comment by Martysh12** [comment]
Commit https://github.com/msys2/MINGW-packages/commit/dfb01cfca3270f21494557815e67daceed6dbb5b has fixed this issue, it can be closed now.
