### ISSUE TITLE
Add kati

### ISSUE THREAD

**Issue by Freed-Wu** [msys2/MINGW-packages#18249]
### Package name

kati

### Brief description of package

kati is an experimental GNU make clone. It instead converts your Makefile to a ninja file.

### URL for package's homepage

https://github.com/google/kati

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment]
Is there any project that uses this build tool other than AOSP? And how are you supposed to use it?

**Comment by Freed-Wu** [comment]
> Have you used or seen any project that use kati other than Google (internally) or AOSP?

I just try `ckati` in NixOS (they package it in <https://search.nixos.org/packages?query=kati>) and found it can work for makefile project. However, I really don't know any project only use ckati to replace make.
