### ISSUE TITLE
package xmake is corrupted after update

### ISSUE THREAD

**Issue by f-zl** [msys2/MINGW-packages#18305]
### Description / Steps to reproduce the issue

`pacman -Syu` to update system
`pacman -S mingw-w64-x86_64-xmake` to install xmake if it is not installed before

### Expected behavior

xmake works as before

### Actual behavior

xmake.exe is corrupted. It is only 178 bytes in size

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

**Comment by waruqi** [comment]
It's about solving https://github.com/xmake-io/xmake/issues/3628

> Therefore bin/xmake.exe cannot run outside of msys2 shell.

It's only for msys2.
