### ISSUE TITLE
[gtk4] 

### ISSUE THREAD

**Issue by wan942182718** [msys2/MINGW-packages#18324]
### Description / Steps to reproduce the issue

Version: 4.12.1-1 Actual version: 4.10.4

### Expected behavior

upgrade version

### Actual behavior

In project development, the version is too low and many functions do not have it

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

windows 10 x64

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Please update the packages with `pacman -Syyu` command. mingw-w64-gtk4 version is 4.12.1. See this page for more information https://packages.msys2.org/base/mingw-w64-gtk4
