### ISSUE TITLE
Typo in libssh2.pc under ucrt64

### ISSUE THREAD

**Issue by jeroen** [msys2/MINGW-packages#18451]
### Description / Steps to reproduce the issue

The `libssh2.pc ` file seems broken in `ucrt64`. Note we get a (non existing) `-R` flag:

```sh
$ pkg-config --libs --static libssh2
-lssh2 -lws2_32 -L/ucrt64/lib -L/ucrt64/lib -R/ucrt64/lib -lz -lssl -lcrypto -lws2_32 -lgdi32 -lcrypt32
```

Indeed this is in the `libssh2.pc` file

```sh
$ cat /ucrt64/lib/pkgconfig/libssh2.pc
###########################################################################
# libssh2 installation details
###########################################################################

prefix=/ucrt64
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libssh2
URL: https://www.libssh2.org/
Description: Library for SSH-based communication
Version: 1.11.0
Requires.private: libssl libcrypto zlib
Libs: -L${libdir} -lssh2
Libs.private:  -lws2_32 -L/ucrt64/lib -lssl -L/ucrt64/lib -lcrypto -R/ucrt64/lib
Cflags: -I${includedir}

```

### Expected behavior

No -R flag.

### Actual behavior

Returns wrong flag.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 11

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Hi @jeroen, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Comment by jeroen** [comment]
Thank you!
