### ISSUE TITLE
hdf5: pkg-config file incorrect for static linking

### ISSUE THREAD

**Issue by svillemot** [msys2/MINGW-packages#18554]
### Description / Steps to reproduce the issue

Trying to create a static executable linked against HDF5 using the pkg-config system fails (in the MINGW64 environment).

For example, using [h5_write.c](https://raw.githubusercontent.com/HDFGroup/hdf5/develop/examples/h5_write.c):

```
$ gcc -static h5_write.c $(pkg-config --static --libs hdf5) -o h5_write
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/msys64/mingw64/lib/libcurl.dll.a: Invalid argument
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/msys64/mingw64/lib/libssl.dll.a: Invalid argument
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/msys64/mingw64/lib/libcrypto.dll.a: Invalid argument
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/msys64/mingw64/lib/libz.dll.a: Invalid argument
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/msys64/mingw64/lib/libsz.dll.a: Invalid argument
collect2.exe: error: ld returned 1 exit status
```

### Expected behavior

Static linking should work with pkg-config.

### Actual behavior

The problem is that the `hdf5.pc` file contains invalid `-l` flags in the `Libs.private` field:
```
$ pkg-config --static --libs hdf5
-lhdf5 -lshlwapi -lm -lws2_32 -lwsock32 -l/mingw64/lib/libcurl.dll.a -l/mingw64/lib/libssl.dll.a -l/mingw64/lib/libcrypto.dll.a -l/mingw64/lib/libz.dll.a -l/mingw64/lib/libsz.dll.a
```

An easy fix would be to rather use the `Requires.private` field and populate it with `libcurl` and `zlib`. Maybe this solution should be reported upstream.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> An easy fix would be to rather use the `Requires.private` field and populate it with `libcurl` and `zlib`.

libaec, provides libsz.dll.a, does not have pkgconfig file. That "fix" will not work.

**Comment by svillemot** [comment]
Indeed, `libsz` needs to be specified in `Libs.private`.

**Comment by svillemot** [comment]
But otherwise, using `Requires.private` for libraries that ship a `pkg-config` file is the proper solution.

**Comment by svillemot** [comment]
But whatever solution you adopt, I will be happy if static linking works as expected.

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

The last two lines in hdf5.pc now looks like following.

```
Libs.private:  -lhdf5  -lz -lsz -lsz
Requires.private:  libcrypto libssl libcurl
```

I have tried to compile that hdf5 example statically but I have to add `-lbrotlicommon` explicitly. It comes from libcurl.pc. pkgconf may have some issue with the order of libraries. Here is the command.

```
gcc -static h5_write.c $(pkg-config --static --libs hdf5) -lbrotlicommon
```

**Comment by svillemot** [comment]
Thanks for working on this issue.

I don’t understand why you put `libcrypto` and `libssl` in `Requires.private`. They are dependencies of `libcurl`, and `pkg-config` works recursively. In any case, this does not harm at this point.

There is indeed still a problem with `libbrotlicommon`. That’s quite unfortunate, since that means that my problem is not solved (I am building a static library with Meson, which gets dependency information directly from `pkg-config`). At this point I don’t understand why `pkg-config` reorders the libraries that come from `libcurl`.

**Comment by svillemot** [comment]
The problem with `libbrotlicommon` is most likely a bug in `pkgconf`, possibly this one: https://github.com/pkgconf/pkgconf/issues/322

**Comment by Biswa96** [comment]
> I don’t understand why you put `libcrypto` and `libssl` in `Requires.private`.

My mistake. I blindly followed the CMake requirements in hdf5. That would not cause any issue, I think.
