### ISSUE TITLE
[gcc] Missing libmpc.a and libmpfr.a

### ISSUE THREAD

**Issue by trixtan** [msys2/MINGW-packages#18568]
### Description / Steps to reproduce the issue

- Install the complete mingw-w64-ucrt-x86_64-toolchain
- Run the following command:  `x86_64-w64-mingw32-gcc -o conftest.exe -I/ucrt64/include   -static -L/ucrt64/lib conftest.c  -lmpc -lmpfr -lgmp`

Content of conftest.c:
```
/* confdefs.h */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define HAVE_CXX11 1
#define LT_OBJDIR ".libs/"
/* end confdefs.h.  */
#include <mpc.h>
int
main ()
{

    mpfr_t n;
    mpfr_t x;
    mpc_t c;
    int t;
    mpfr_init (n);
    mpfr_init (x);
    mpfr_atan2 (n, n, x, MPFR_RNDN);
    mpfr_erfc (n, x, MPFR_RNDN);
    mpfr_subnormalize (x, t, MPFR_RNDN);
    mpfr_clear(n);
    mpfr_clear(x);
    mpc_init2 (c, 53);
    mpc_set_ui_ui (c, 1, 1, MPC_RNDNN);
    mpc_cosh (c, c, MPC_RNDNN);
    mpc_pow (c, c, c, MPC_RNDNN);
    mpc_acosh (c, c, MPC_RNDNN);
    mpc_clear (c);

  ;
  return 0;
}
```

### Expected behavior

Conftest.exe is correctly created

### Actual behavior

The following error is produced:
`C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmpc: No such file or directory
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmpfr: No such file or directory`

The folder /ucrt64/lib does not contain libmpfr.a and libmpc.a (the previous mingw-w64-ucrt-x86_64-toolchain version did)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
I can't reproduce.

libmpfr.a is part of https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-mpfr which is a dependency of gcc

**Comment by MehdiChinoune** [comment]
You are using an outdated MSYS2.
Please update your MSYS2 before submitting issues.
Why do you check something you haven't verified?

**Comment by lazka** [comment]
Oh, right, gcc 13.1.0. We are at 13.2.0 atm

**Comment by ognevnydemon** [comment]
those static libs were added in recent gmp and mpfr updates. see https://github.com/msys2/MINGW-packages/commit/516fa59444b8cfee001e2f13c44579c1997890c7 and https://github.com/msys2/MINGW-packages/commit/19a497b647dea2939e4fe9cc2ad5818f83b1632f. so, please, update MSYS2

**Comment by trixtan** [comment]
> You are using an outdated MSYS2. Please update your MSYS2 before submitting issues. Why do you check something you haven't verified?

Sorry was assuming a fresh download from the site also implies up-to-date package. My bad didn't read the linked page..
Thanks for explaining,

**Comment by ognevnydemon** [comment]
> > You are using an outdated MSYS2. Please update your MSYS2 before submitting issues. Why do you check something you haven't verified?
> 
> Sorry was assuming a fresh download from the site also implies up-to-date package. My bad didn't read the linked page..
> Thanks for explaining,

I think we should clarify, that update is needed after installing in website guide

**Comment by lazka** [comment]
> I think we should clarify, that update is needed after installing in website guide

We had that before, but it confused users a lot in case there were no updates and they thought something is broken and asked for help.
