### ISSUE TITLE
[arrow] Apache Arrow LLVM v17 build issues

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#18601]
Just so we don't forget: https://github.com/apache/arrow/issues/37834

**Comment by MehdiChinoune** [comment]
A quick workaround is to disable gandiva component (`-DARROW_GANDIVA=OFF`).

**Comment by lazka** [comment]
> A quick workaround is to disable gandiva component (`-DARROW_GANDIVA=OFF`).

This was done now in 89feafbca9ad74c3f241f, so I think we can close this.
