### ISSUE TITLE
The C executable compiled using the MinGW environment, which contains all the BSS segment content, causes the program to become very large

### ISSUE THREAD

**Issue by hiwooiot** [msys2/MINGW-packages#18612]
### Description / Steps to reproduce the issue

My project was originally running on Linux, and now using MinGW to compile on windows has been compiled successfully, and can run normally, but the size of the executable program is abnormal, which contains a lot of 0 are BSS segment content

### Expected behavior

The compiled C program is too big

### Actual behavior

There are now more than 800 MB of compiled executable programs, and the BSS segment content occupies a majority of the minority and is all 0

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW32_NT-10.0-18362

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
Please, show a minimal reproducer. No one can investigate the issue without it.

**Comment by hiwooiot** [comment]
$ objdump.exe -h HIWOOBOX.exe

HIWOOBOX.exe:     file format pei-i386

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 .text         0016f098  00401000  00401000  00000600  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE, DATA
  1 .data         00009d2c  00571000  00571000  0016f800  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  2 .rdata        0004a778  0057b000  0057b000  00179600  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  3 .eh_frame     00027254  005c6000  005c6000  001c3e00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  4 .bss          326d8600  005ee000  005ee000  001eb200  2**2
                  CONTENTS, ALLOC
  5 .edata        00000b19  32cc7000  32cc7000  328c3800  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  6 .idata        00002554  32cc8000  32cc8000  328c4400  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  7 .CRT          00000030  32ccb000  32ccb000  328c6a00  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  8 .tls          00000008  32ccc000  32ccc000  328c6c00  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  9 .rsrc         000004e8  32ccd000  32ccd000  328c6e00  2**2
                  CONTENTS, ALLOC, LOAD, DATA
 10 .reloc        0000d608  32cce000  32cce000  328c7400  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 11 .debug_aranges 00000750  32cdc000  32cdc000  328d4c00  2**0
                  CONTENTS, READONLY, DEBUGGING
 12 .debug_info   0001d4d9  32cdd000  32cdd000  328d5400  2**0
                  CONTENTS, READONLY, DEBUGGING
 13 .debug_abbrev 00005a2a  32cfb000  32cfb000  328f2a00  2**0
                  CONTENTS, READONLY, DEBUGGING
 14 .debug_line   0000ecd1  32d01000  32d01000  328f8600  2**0
                  CONTENTS, READONLY, DEBUGGING
 15 .debug_str    000004be  32d10000  32d10000  32907400  2**0
                  CONTENTS, READONLY, DEBUGGING
 16 .debug_line_str 000036f5  32d11000  32d11000  32907a00  2**0
                  CONTENTS, READONLY, DEBUGGING
 17 .debug_loclists 000110f5  32d15000  32d15000  3290b200  2**0
                  CONTENTS, READONLY, DEBUGGING
 18 .debug_rnglists 00000a57  32d27000  32d27000  3291c400  2**0
                  CONTENTS, READONLY, DEBUGGING

**Comment by MehdiChinoune** [comment]
Show the source code.
