### ISSUE TITLE
Add qt6-webassembly

### ISSUE THREAD

**Issue by mariuszmaximus** [msys2/MINGW-packages#18800]
### Package name

qt6-webassembly

### Brief description of package

Qt for Webassembly lets you to run Qt applications on the web.
WebAssembly (abbreviated Wasm) is a binary instruction format intended to be executed in a virtual machine, for example in a web browser.

With Qt for WebAssembly, you can distribute your application as a web application that runs in a browser sandbox. This approach is suitable for web distributed applications that do not require full access to host device capabilities.

### URL for package's homepage

https://doc.qt.io/qt-6/wasm.html

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
Webassembly is whole different platform. It has its own compiler, runtime, ... etc.
If you want to use qt6-webassembly just download the official one from Qt and build your code with it.
I haven't found any Linux distribution offering it as a package.
