### ISSUE TITLE
Emacs 29.1 touchpad scrolling

### ISSUE THREAD

**Issue by djsylvester** [msys2/MINGW-packages#18816]
### Description / Steps to reproduce the issue

I read bug #65360: emacs 29.1 with MSYS2: vertical scrolling with touchpad when searching for issues/solutions and that ticket indicates "fixed in current git" (26 Aug 2023). It's not working for me.

I have msys2 emacs 29.1 package installed on Win-10 - Dell Inspiron 7000 2-in-1.

When initially using 2-finger touchpad swipe to scroll up or down it only scrolls UP until top of buffer then completely stops working. If I use arrow keys or C-n to move down buffer and try scrolling again it repeats same - up only, top-of-buffer, stop working. I checked mouse settings in customizer (defaults) and don't see a problem.

### Expected behavior

Scrolling to work in both directions with 2-finger swipe on touchpad.

### Actual behavior

1. Only scroll UP regardless of direction of touchpad swipe
2. Stops working once you reach top of buffer.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by dr-scsi** [comment]
> I read bug #65360: emacs 29.1 with MSYS2: vertical scrolling with touchpad when searching for issues/solutions and that ticket indicates "fixed in current git" (26 Aug 2023). It's not working for me.

That report was resolved with [this change](https://git.savannah.gnu.org/cgit/emacs.git/commit/?h=emacs-29&id=781ddd7e7d87de150d74d6d8615c25e68b42275b) and "fixed in current git" means that the change will be available with Emacs 29.2.  Since you're using 29.1, you'll have to wait until 29.2 is released and distributed with Msys2 or you build Emacs from the `emacs-29` branch yourself.

**Comment by djsylvester** [comment]
Ah. Understand. Lesson learned. Thanks.

**Comment by dr-scsi** [comment]
@djsylvester - You're welcome.  Maybe you want to close this report as well.

**Comment by MehdiChinoune** [comment]
Hi @djsylvester I have backported the patch in #18890
Could you test it and see If It fixes the issue for you (Download the corresponding artifacts from https://github.com/msys2/MINGW-packages/actions/runs/6564274448, decompress it and install file by `pacman -U`)

**Comment by dr-scsi** [comment]
@MehdiChinoune - That might be a short-lived backport.  [Pretest for Emacs 29.2](https://lists.gnu.org/archive/html/emacs-devel/2023-10/msg00363.html) has just begun.

**Comment by djsylvester** [comment]
@MehdiChinoune That did the trick. Scrolling is working. Thank you.
