### ISSUE TITLE
files not found

### ISSUE THREAD

**Issue by HIBA-HAMADTO** [msys2/MINGW-packages#18817]
### Description / Steps to reproduce the issue

the wang64 file in c is empty but i downloaded g++ , gdb and gcc . when i check for the versions of them it appears . how can i find them?

### Expected behavior

i need the path of them and files must be in c

### Actual behavior

they are not there

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

10

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
What files are you searching for?
