### ISSUE TITLE
DLL symbols are imported even though I'm linking statically

### ISSUE THREAD

**Issue by afalkenhahn** [msys2/MINGW-packages#18827]
### Description / Steps to reproduce the issue

Take this little test program:

```
#include <ctype.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>

#include <ft2build.h>
#include FT_FREETYPE_H
#include FT_BITMAP_H

#include <pango/pangocairo.h>
#include <pango/pangoft2.h>

int main(int argc, char *argv[])
{
	PangoContext *context;
	PangoLayout *layout;
	PangoFont *font;
	PangoFontDescription *fontdesc;
	PangoFontMap *fontmap;
	PangoRectangle rc;
	cairo_surface_t *surf;
	cairo_t *cr;
	cairo_matrix_t cm;
	
	fontmap = pango_cairo_font_map_new_for_font_type(CAIRO_FONT_TYPE_FT);
	fontdesc = pango_font_description_from_string("Arial 36px");
	
	context = pango_font_map_create_context(fontmap);
	layout = pango_layout_new(context);
		
	pango_layout_set_font_description(layout, fontdesc);
	pango_layout_set_width(layout, 640 * PANGO_SCALE);
		
	font = pango_font_map_load_font(fontmap, context, fontdesc);
				
       pango_layout_set_markup(layout, "Hello World", -1);

	pango_layout_get_pixel_extents(layout, &rc, NULL);

	surf = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, rc.width, rc.height);

	cr = cairo_create(surf);
	
	cairo_set_source_rgba(cr, 0, 0, 0, 1.0);
	
	cairo_matrix_init(&cm, 1, 0, 0, 1, -rc.x, -rc.y);
	cairo_set_matrix(cr, &cm);
	
	pango_cairo_show_layout(cr, layout);
	cairo_surface_flush(surf);
	
	cairo_surface_write_to_png(surf, "test.png");
	
	cairo_destroy(cr);
	cairo_surface_destroy(surf);
	
	g_object_unref(font);
	g_object_unref(layout);
	g_object_unref(context);
	g_object_unref(fontmap);
	pango_font_description_free(fontdesc);
	
	return 0;
}
```

Compile it using static linking like this:

`gcc test.c -static-libgcc -static-libstdc++ -I/c/msys64/mingw64/include/pango-1.0 -I/c/msys64/mingw64/include/cairo -I/c/msys64/mingw64/include/glib-2.0 -I/c/msys64/mingw64/include/harfbuzz -I/c/msys64/mingw64/include/freetype2 -I/c/msys64/mingw64/include -I/c/msys64/mingw64/lib/glib-2.0/include -L/c/msys64/mingw64/lib -Wl,-Bstatic -lfreetype -lpng -lbrotlidec -lbrotlienc -lbrotlicommon -lharfbuzz -lpangocairo-1.0 -lpangoft2-1.0 -lpangowin32-1.0 -lpango-1.0 -lcairo -lpixman-1 -lgraphite2 -lfontconfig -lfreetype -lexpat -lthai -ldatrie -lbz2 -lz -lfribidi -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lpcre2-8 -lpcre2-16 -lpcre2-32 -lpcre2-posix -lffi -luuid -lintl -liconv -lharfbuzz -lgraphite2 -lpng -lbrotlidec -lbrotlienc -lbrotlicommon -lz -lstdc++ -lgcc_eh -lpthread -lgcc_eh -Wl,-Bdynamic -lshlwapi -ldwrite -lWs2_32 -lrpcrt4 -lshell32 -lmsimg32 -lusp10 -lgdi32 -lole32`

This leads to the following linker errors:

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:\msys64\tmp\cc67mREc.o:test.c:(.text+0xd6): undefined reference to `__imp_cairo_image_surface_cr
eate'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:\msys64\tmp\cc67mREc.o:test.c:(.text+0xea): undefined reference to `__imp_cairo_create'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:\msys64\tmp\cc67mREc.o:test.c:(.text+0x118): undefined reference to `__imp_cairo_set_source_rgba
'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:\msys64\tmp\cc67mREc.o:test.c:(.text+0x170): undefined reference to `__imp_cairo_matrix_init'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:\msys64\tmp\cc67mREc.o:test.c:(.text+0x184): undefined reference to `__imp_cairo_set_matrix'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:\msys64\tmp\cc67mREc.o:test.c:(.text+0x1a4): undefined reference to `__imp_cairo_surface_flush'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:\msys64\tmp\cc67mREc.o:test.c:(.text+0x1bb): undefined reference to `__imp_cairo_surface_write_t
o_png'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:\msys64\tmp\cc67mREc.o:test.c:(.text+0x1cb): undefined reference to `__imp_cairo_destroy'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:\msys64\tmp\cc67mREc.o:test.c:(.text+0x1db): undefined reference to `__imp_cairo_surface_destroy
'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:\msys64\tmp\cc67mREc.o:test.c:(.text+0x1eb): undefined reference to `__imp_g_object_unref'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:\msys64\tmp\cc67mREc.o:test.c:(.text+0x1fb): undefined reference to `__imp_g_object_unref'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:\msys64\tmp\cc67mREc.o:test.c:(.text+0x20b): undefined reference to `__imp_g_object_unref'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:\msys64\tmp\cc67mREc.o:test.c:(.text+0x21b): undefined reference to `__imp_g_object_unref'
collect2.exe: error: ld returned 1 exit status
```

As you can see, something is trying to import DLL symbols from cairo and gobject but this shouldn't be done since I'm linking statically.

### Expected behavior

see above

### Actual behavior

see above

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> something is trying to import DLL symbols from cairo and gobject 

That something is the example program :) Some macros have to be defined for static linking with glib2 and cairo. See all the `_static_flags` here https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-pango/PKGBUILD

**Comment by afalkenhahn** [comment]
Alright, adding `-DGLIB_STATIC_COMPILATION -DGOBJECT_STATIC_COMPILATION -DGIO_STATIC_COMPILATION -DCAIRO_WIN32_STATIC_BUILD -DGMODULE_STATIC_COMPILATION` solved the issue. Sorry for the false alert.

**Comment by Biswa96** [comment]
This is somewhat an real issue, just we don't have any proper solution.

Those flags should be provided in corresponding pkgconfig files, like cairo.pc, glib-2.0.pc etc. Both cairo and glib has multiple pkgconfig files. So, it is hard to decide which one should have the correct compiler flag in Cflags.private.

**Comment by afalkenhahn** [comment]
Yes, it's a bit of mess with the symbol imports and exports in MSYS2. Note that a few months ago I also opened #17744 which shows that there is an issue in the way that several static libraries seem to export DLL symbols even though they are linked statically. I think this should also be fixed.
