### ISSUE TITLE
findGLEW doesn't behave properly with the msys2 glew package

### ISSUE THREAD

**Issue by SeleDreams** [msys2/MINGW-packages#18822]
### Description / Steps to reproduce the issue

I am making a cross-platform software that relies on glew. As such, I rely on mingw and msys2 and use the mingw-w64-x86_64 version of glew, cmake and the gcc compiler.
In my project, I import the glew dependency using the find_package feature of cmake which normally should make the target GLEW::GLEW available according to cmake's official documentation.
However instead, an error occurs.
![image](https://github.com/msys2/MINGW-packages/assets/16335601/014c7fd3-8f8e-4ab4-b43e-b083deb29bfd)
checking the variables that have been set, I notice that while some variables were set properly, some, such as GLEW_VERSION weren't
I had at one point in my cmake file these lines in order to check if glew had actually been found. And the result was clearly strange.
```
if (GLEW_FOUND)
message("Found GLEW version ${GLEW_VERSION}")
endif()
```
this resulted in the log showing `[cmake] Found GLEW version`
which means GLEW_VERSION has never been set.

### Expected behavior

find_package(GLEW) should have the expected result from the cmake documentation and should fill all variables as expected and create the proper GLEW::GLEW target.

### Actual behavior

The GLEW::GLEW target doesn't exist and several variables such as GLEW_VERSION are improperly set

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

If I knew how it worked

**Comment by SeleDreams** [comment]
That was an issue with my cmake project's structure in the end

**Comment by Biswa96** [comment]
Would you like to share what happened or what the mistake was?

**Comment by SeleDreams** [comment]
> Would you like to share what happened or what the mistake was?

Basically, after using find_package, the GLEW::GLEW target was created however it was only accessible in the local scope, not in the parent scope in which the dependencies were defined, so when linking it did not find the GLEW::GLEW target because for cmake it did not exist in the parent scope

**Comment by Biswa96** [comment]
Thanks for sharing that. I was not aware of the specific behavior of the set function in cmake.
