### ISSUE TITLE
mkvtoolnix-gui does not open after last MSYS2 update

### ISSUE THREAD

**Issue by dustwanderer** [msys2/MINGW-packages#18870]
### Description / Steps to reproduce the issue

I have MSYS2 and its mingw-w64-ucrt-x86_64-mkvtoolnix-gui package installed in my Windows 11 laptop. Windows 11 (English) is up-to-date.
I updated MSYS2 on 2023-09-23.
I updated MSYS2 again on 2023-10-13 and on 2023-10-14.

### Expected behavior

when I double-click the mkvtoolnix-gui icon, I expect a graphic window to open, as before. I am pretty sure that it was working after the 2023-09-23 update.

### Actual behavior

After the 2023-10-13 update, when I double-click the mkvtoolnix-gui icon, no window opens and no error message appears. If I try to launch mkvtoolnix-gui.exe from cmd.exe or from bash.exe, nothing happens either.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
I get "Cannot mix incompatible Qt library (6.5.3) with this library (6.6.0)"

**Comment by MehdiChinoune** [comment]
qt6-base and qt6-svg are at 6.6.0 while qt6-multimedia still in staging.

**Comment by megatol** [comment]
> I get "Cannot mix incompatible Qt library (6.5.3) with this library (6.6.0)"

I am getting the very same error while trying to execute my app (Webots) after recompilation with Qt 6.6.0:
```
$ webots
Fatal: Cannot mix incompatible Qt library (6.5.3) with this library (6.6.0)
QWaitCondition: Destroyed while threads are still waiting
```

**Comment by Biswa96** [comment]
The queue is stuck with self hosted ARM runner. See the progress here https://packages.msys2.org/queue

**Comment by lazka** [comment]
Should be fixed now. Sorry for the delay.

**Comment by omichel** [comment]
That works! Thank you.
