### ISSUE TITLE
h5py: UserWarning: h5py is running against HDF5 1.14.2 when it was built against 1.14.1

### ISSUE THREAD

**Issue by fsagbuya** [msys2/MINGW-packages#18871]
### Description
Installing mingw-w64-x86_64-python-h5py and then importing it prints this warning:
```shell
# python
Python 3.11.6 (main, Oct  3 2023, 09:12:56)  [GCC 13.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
C:/msys64/mingw64/lib/python3.11/site-packages/h5py/__init__.py:36: UserWarning: h5py is running aga
inst HDF5 1.14.2 when it was built against 1.14.1, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "

```

### Steps to Reproduce
```
pacman -S mingw-w64-x86_64-python-h5py
python
import h5py
```

### Expected behavior

No warning is emitted.

### Actual behavior

Warning above is printed.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-17763

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by mmuetzel** [comment]
Likely, `mingw-w64-python-h5py` just needs a pkgrel bump.

**Comment by fsagbuya** [comment]
New version `3.10.0` also available (https://pypi.org/project/h5py/).

**Comment by fsagbuya** [comment]
> Please, go ahead. Every contributor is appreciated. 👍

Tests:
-  Upgrade python-h5py to `3.10.0-1` - Still emit warning message ❌
-  Bump hdf5 pkgrel to `4` - Still emit warning message ❌
-  Bump python-h5py to `3.9.0-3` - No warning message ✅

**Comment by mmuetzel** [comment]
I wonder why updating to h5py 3.10.0 didn't remove the warning. How could that version have picked up the older HDF5 libraries and headers during compilation?

**Comment by fsagbuya** [comment]
Not sure also. Didn't get to test it thoroughly. I only updated the `pkgver` and `sha256sums`. Might be something to look into when upgrading the package.
