### ISSUE TITLE
VLC (MINGW64) segment faults loading an mp4 file

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#18912]
### Description / Steps to reproduce the issue

1. Star VLC (`/mingw64/bib/vlc.exe`)
2. Click Media/Open File
3. Select an MP4 file

After a few seconds it is loading the file, it quits with a `Segmentation fault`

### Expected behavior

.

### Actual behavior

.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
I can not reproduce the issue with mingw64 vlc. Could you provide any error log and any sample video to try with?

**Comment by lazka** [comment]
I can't reproduce either.

**Comment by Biswa96** [comment]
@angelog0 Does this video fail https://datasheets.raspberrypi.com/video/big-buck-bunny-1080p.mp4 ?

**Comment by angelog0** [comment]
This occurs since there was a VLC upgrade few day ago (3.0.19). With previous version VLC worked with the same mp4 files. I searched the log of segmentation fault but did not find them. 

With the above mp4 file there are the same segmentation fault.

I tried both starting VLC from MINGW64 shell:
```
$ vlc &

## it starts, then Media/Open file/THEABOVE_MP4

[1]+  Segmentation fault      vlc

## Also this fails (almost Instantly fails)
$ vlc.exe big-buck-bunny-1080p.mp4
Segmentation fault
```

and clicking on `vlc.exe` in Explorer.

**Comment by angelog0** [comment]
I did this:

```
cd /tmp
wget https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-vlc-3.0.18-9-any.pkg.tar.zst    ## NB: 3.0.18
aunpack mingw-w64-x86_64-vlc-3.0.18-9-any.pkg.tar.zst
mv mingw-w64-x86_64-vlc-3.0.18-9-any.pkg.tar/mingw64 ./vlc

## then in MINGW64 shell

/tmp/vlc/bin/vlc.exe big-buck-bunny-1080p.mp4

```

and it works, also with the other MP4 files...

**Comment by lazka** [comment]
Note that you can just `pacman -U https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-vlc-3.0.18-9-any.pkg.tar.zst`

**Comment by angelog0** [comment]
Yes, I know. Just to do a quick test..

**Comment by angelog0** [comment]
Just for the record, I installed the UCRT64 version but the results are the same.

**Comment by Biswa96** [comment]
I can not reproduce the issue with mingw VLC package version 3.0.19 or with 3.0.20.

There may be some issue in your system. Also please try with a clean msys2 install (if possible).

**Comment by angelog0** [comment]
I downgraded with

```
pacman -U https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-vlc-3.0.18-9-any.pkg.tar.zst
```

and it works just fine.

Which OS? Here 

```
C:\WINDOWS\system32>ver

Microsoft Windows [Versione 10.0.19045.3570]
```

**Comment by angelog0** [comment]
`3.0.20` seems to work!

**Comment by lazka** [comment]
https://code.videolan.org/videolan/vlc/-/compare/3.0.19...3.0.20?from_project_id=435&straight=false
