### ISSUE TITLE
Add python-mysqldb

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MINGW-packages#18911]
### Package name

python-mysqldb

### Brief description of package

To use with sqlalchemy to call a mariadb or mysql database from python

### URL for package's homepage

https://pypi.org/project/mysqlclient/

### Provide a basic test case to validate the package's functionality.

python -c "import MySQLdb"

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

I have no idea how mingw works.

**Comment by Biswa96** [comment]
May I ask what the package name should be? We generally follow ArchLinux package name. In this case the Arch package name is python-mysqlclient[^1]. Also, the pypi name is mysqlclient[^2].

[^1]: https://archlinux.org/packages/extra/x86_64/python-mysqlclient/
[^2]: https://pypi.org/project/mysqlclient/

**Comment by Kreijstal** [comment]
I think python-mysqlclient should be the name

btw I managed to fix it myself i am so happy
```
#!/bin/bash
#mingw-w64-x86_64-libmariadbclient is a dependency, should be installed

# Download the source code
pip download mysqlclient --no-binary :all:

# Unpack the downloaded tarball
tar -xvf mysqlclient-*.tar.gz

# Move into the directory
cd mysqlclient-*/

# Apply the patch to setup.py starting from line 99
patch setup.py << 'EOF'
--- original_code
+++ modified_code
@@ -99,10,0 +11,10 @@
+        "kernel32",
+        "advapi32",
+        "wsock32",
+        "shlwapi",
+        "crypt32",
+        "bcrypt",
+        client,
+        "ws2_32",
+        "secur32",
+        "z"
@@ -99,17 +27 @@
-    extra_link_args = ["/MANIFEST"]
+    extra_link_args = []
EOF

# Build the extension
MYSQLCLIENT_CONNECTOR=/mingw64/ python setup.py build_ext --verbose

# Build the wheel file
python setup.py bdist_wheel --verbose

# Install the wheel file
pip install dist/mysqlclient-*.whl
```
I don't know how to build pacman packages and I fixed by putting the linker libraries twice, which I don't think it is a "good/pretty" way of solving it. "/MANIFEST" is for MSVC and not mingw

**Comment by Biswa96** [comment]
I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Comment by Kreijstal** [comment]
Hi, I tested it with https://docs.rfam.org/en/latest/database.html It can do queries, thank you
