### ISSUE TITLE
CMake fails when an explicit CMAKE_RC_COMPILER is set for the MSVC toolchain

### ISSUE THREAD

**Issue by tophoo** [msys2/MINGW-packages#18936]
### Description / Steps to reproduce the issue

With the current CMake 3.27.7 release in mingw and msys the following CMake project fails to compile e.g. in the `Developer Command Prompt for Visual Studio 2019` (yes it is not necessary to set CMAKE_RC_COMPILER inside the Developer CMD, it is only for reproducing the error):
CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.25)
project(test)
set(CMAKE_RC_COMPILER "C:/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0/x64/rc.exe")
add_executable(test main.cpp test.rc)
```
main.cpp:
```
int main() { return 0; }
```
test.rc:
```
2 TEXTINCLUDE
BEGIN
    "\0"
END
```
Save files to disk and run:
```
mkdir build
cd build
cmake -GNinja ..
cmake --build .
```
This code works with vanilla CMake 3.27.7, i.e. not from mingw/msys, and it also worked with CMake 3.26.3 from mingw/msys.

### Expected behavior

A successful build.

### Actual behavior

```
C:\Users\XXXXXXXX\git\cmake_rc\build>C:\msys64\mingw64\bin\cmake.exe --build .
[1/3] Building RC object CMakeFiles\test.dir\test.rc.res
FAILED: CMakeFiles/test.dir/test.rc.res
RC C:\Users\XXXXXXXX\git\cmake_rc\test.rc CMakeFiles\test.dir\test.rc.res.d CMakeFiles\test.dir\test.rc.res "Hinweis: Einlesen der Datei: " "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29333/bin/Hostx86/x86/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe   -DWIN32 -D_DEBUG /fo CMakeFiles\test.dir\test.rc.res C:\Users\XXXXXXXX\git\cmake_rc\test.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Copyright (C) Microsoft Corporation.  All rights reserved.

fatal error RC1107: invalid usage; use RC /? for Help
[2/3] Building CXX object CMakeFiles\test.dir\main.cpp.obj
ninja: build stopped: subcommand failed.
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [ ] CLANGARM64

**Comment by tophoo** [comment]
I have found the issue in the CMake project: https://gitlab.kitware.com/cmake/cmake/-/issues/25047

**Comment by Biswa96** [comment]
This is not an msys2 related issue at all. The msys2 packages are used with mingw toolchain which is different from msvc toolchain.

**Comment by tophoo** [comment]
I would like to reopen the issue, as I have found the bug:
https://github.com/msys2/MINGW-packages/commit/a43370c60273b4b6fd1c7a8d97602d93f83de9b0
With this commit the install was refactored and the component `cmcldeps` was forgotten. With cmcldeps.exe installed my bug is fixed.

**Comment by Biswa96** [comment]
@MehdiChinoune would it be possible to re-add cmcldeps.exe in cmake package?

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune would it be possible to re-add cmcldeps.exe in cmake package?

I know about it at the time of refactoring, but I don't need it for MSYS2.
MSYS2 tools are for MSYS2/MinGW packages to use.
Beside that VS has its own CMake, just install it and use it from their VS-CMD or CS-Powershell.

**Comment by tophoo** [comment]
I would really appreciate if we could readd `cmcldeps` to the CMake package. We use mingw as the main driver, i.e. toolchain:
* to cross compile from Windows to Linux
* to compile with MSVC 
* to compile with mingw clang for Windows
* run code analysis
* etc.
So yes, we use MinGW package also outside of their context, but this also makes them such a great tool!

**Comment by MehdiChinoune** [comment]
I will try to re-add it in the next release (major or minor) as a separate package.

**Comment by dg0yt** [comment]
> I will try to re-add it in the next release (major or minor) as a separate package.

TIL. This choice is responsible for a significant inflow of issues in vcpkg. Several times I looked  at the package source and didn't spot a suspicious patch or setting. I didn't expect a missing binary breaking one of the generators `cmake` reports as supported. And the UX is bad, giving no clue about the actual problem. E.g. https://github.com/microsoft/vcpkg/issues/49250:

~~~
Run Build Command(s): E:/vcpkg/downloads/tools/ninja/1.13.2-windows/ninja.exe -v -v -j25 install
[1/9] RC E:\vcpkg\buildtrees\spdlog\x64-windows-dbg\version.rc CMakeFiles\spdlog.dir\version.rc.res.d CMakeFiles\spdlog.dir\version.rc.res "Note: including file: " "C:/Program Files/Microsoft Visual Studio/18/Community/VC/Tools/MSVC/14.50.35717/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100261~1.0\x64\rc.exe -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_FWRITE_UNLOCKED -DSPDLOG_SHARED_LIB -Dspdlog_EXPORTS -I E:\vcpkg\buildtrees\spdlog\src\v1.16.0-e349c3b9b7.clean\include -I E:\vcpkg\installed\x64-windows\include -c65001 /DWIN32 -D_DEBUG /fo CMakeFiles\spdlog.dir\version.rc.res E:\vcpkg\buildtrees\spdlog\x64-windows-dbg\version.rc
FAILED: [code=1] CMakeFiles/spdlog.dir/version.rc.res 
RC E:\vcpkg\buildtrees\spdlog\x64-windows-dbg\version.rc CMakeFiles\spdlog.dir\version.rc.res.d CMakeFiles\spdlog.dir\version.rc.res "Note: including file: " "C:/Program Files/Microsoft Visual Studio/18/Community/VC/Tools/MSVC/14.50.35717/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100261~1.0\x64\rc.exe -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_FWRITE_UNLOCKED -DSPDLOG_SHARED_LIB -Dspdlog_EXPORTS -I E:\vcpkg\buildtrees\spdlog\src\v1.16.0-e349c3b9b7.clean\include -I E:\vcpkg\installed\x64-windows\include -c65001 /DWIN32 -D_DEBUG /fo CMakeFiles\spdlog.dir\version.rc.res E:\vcpkg\buildtrees\spdlog\x64-windows-dbg\version.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384

Copyright (C) Microsoft Corporation.  All rights reserved.


fatal error RC1107: invalid usage; use RC /? for Help
~~~

I would strongly recommend to always include this utility program in the mingw cmake packages.

**Comment by MehdiChinoune** [comment]
> > I will try to re-add it in the next release (major or minor) as a separate package.
> 
> TIL. This choice is responsible for a significant inflow of issues in vcpkg. Several times I looked at the package source and didn't spot a suspicious patch or setting. I didn't expect a missing binary breaking one of the generators `cmake` reports as supported. And the UX is bad, giving no clue about the actual problem. E.g. [microsoft/vcpkg#49250](https://github.com/microsoft/vcpkg/issues/49250):
> 
> ```
> Run Build Command(s): E:/vcpkg/downloads/tools/ninja/1.13.2-windows/ninja.exe -v -v -j25 install
> [1/9] RC E:\vcpkg\buildtrees\spdlog\x64-windows-dbg\version.rc CMakeFiles\spdlog.dir\version.rc.res.d CMakeFiles\spdlog.dir\version.rc.res "Note: including file: " "C:/Program Files/Microsoft Visual Studio/18/Community/VC/Tools/MSVC/14.50.35717/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100261~1.0\x64\rc.exe -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_FWRITE_UNLOCKED -DSPDLOG_SHARED_LIB -Dspdlog_EXPORTS -I E:\vcpkg\buildtrees\spdlog\src\v1.16.0-e349c3b9b7.clean\include -I E:\vcpkg\installed\x64-windows\include -c65001 /DWIN32 -D_DEBUG /fo CMakeFiles\spdlog.dir\version.rc.res E:\vcpkg\buildtrees\spdlog\x64-windows-dbg\version.rc
> FAILED: [code=1] CMakeFiles/spdlog.dir/version.rc.res 
> RC E:\vcpkg\buildtrees\spdlog\x64-windows-dbg\version.rc CMakeFiles\spdlog.dir\version.rc.res.d CMakeFiles\spdlog.dir\version.rc.res "Note: including file: " "C:/Program Files/Microsoft Visual Studio/18/Community/VC/Tools/MSVC/14.50.35717/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100261~1.0\x64\rc.exe -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_FWRITE_UNLOCKED -DSPDLOG_SHARED_LIB -Dspdlog_EXPORTS -I E:\vcpkg\buildtrees\spdlog\src\v1.16.0-e349c3b9b7.clean\include -I E:\vcpkg\installed\x64-windows\include -c65001 /DWIN32 -D_DEBUG /fo CMakeFiles\spdlog.dir\version.rc.res E:\vcpkg\buildtrees\spdlog\x64-windows-dbg\version.rc
> Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
> 
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> 
> fatal error RC1107: invalid usage; use RC /? for Help
> ```
> 
> I would strongly recommend to always include this utility program in the mingw cmake packages.

It's separated in its own package, not removed.

**Comment by dg0yt** [comment]
> It's separated in its own package, not removed.

Please look at the effect, not at the letters. 

(I didn't write "removed" but "missing". And I cited "re-add it in the next release (major or minor) as a separate package".)

**Comment by MehdiChinoune** [comment]
I re-added it as a separate package for those who want to use it with MSVC.
It wasn't available at all.

**Comment by dg0yt** [comment]
> I re-added it as a separate package for those who want to use it with MSVC.

This is what I understood as soon as I arrived here. This is the starting point for my comments, not the answer.

IMO `cmcldeps` is an undocumented implementation detail of `cmake`. Even for fairly experienced users of MSYS2, CMake and MSVC, it is very hard to discover that they need to install a unique "cmake-cmcldeps" binary package when a build fails with that message for a fairly capable `cmake.exe` provided by msys2 via `PATH`.

> It wasn't available at all.

IIUC this problem was introduced with https://github.com/msys2/MINGW-packages/commit/a43370c60273b4b6fd1c7a8d97602d93f83de9b0, as a side effect of adopting the component based install. In that case, it was probably readily available until 3.27.3.

**Comment by MehdiChinoune** [comment]
mingw-w64-cmake is for mingw users, those who want to use MSVC could install cmake from somewhere else.
I splitted the package mainly to reduce install time for development tools for MSYS2 CI and for mingw users in general.
I am not going to introduce extra time/size to cmake because someone wants to mix netween mingw and MSVC.
vcpkg download cmake from official website.
Visual Studio has a bundeled one.
You want to mix toolchains you are on your own. Don't come here and complain.
We said it hindered times, we don't support using packages outside of MSYS2 environments.

**Comment by dg0yt** [comment]
> We said it hindered times, we don't support using packages outside of MSYS2 environments.

Indeed, I answered nearly a hundred reports with "Don't use msys cmake with msvs."

I understand that msys2 supports only mingw. I'm still surprised the harsh reaction from the "build environment for native Windows software".
