### ISSUE TITLE
[qt6-static]  Qt Charts is missing in Qt6.6 static builds

### ISSUE THREAD

**Issue by birdsTalks** [msys2/MINGW-packages#18952]
### Description / Steps to reproduce the issue

- in current version of msys2 qt,  Qt Charts is missing in Qt6.6 static builds. Binary Package does not contain any include files or binary files for Qt Charts.

### Expected behavior

After a update approach using pacman, Qt Charts can not be found with CMake or QMAKE for both Msys2 package [mingw-w64-x86_64-qt6-static](https://packages.msys2.org/package/mingw-w64-x86_64-qt6-static?repo=mingw64) and ucrt version.

### Actual behavior

The file list below [This Page](https://packages.msys2.org/package/mingw-w64-x86_64-qt6-static?repo=mingw64) contains no Charts files.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Some qt6 modules were disabled in this commit https://github.com/msys2/MINGW-packages/commit/32e2c1c7617244c0a0235e539f222ac489e1408c

See the commit message for further information. If it is necessary for you to obtain the full qt6 static library, I would like to suggest building it yourself.

**Comment by birdsTalks** [comment]
> Some qt6 modules were disabled in this commit [32e2c1c](https://github.com/msys2/MINGW-packages/commit/32e2c1c7617244c0a0235e539f222ac489e1408c)
> 
> See the commit message for further information. If it is necessary for you to obtain the full qt6 static library, I would like to suggest building it yourself.

Thanks! The packages in msys2 is really a disk eater !

**Comment by Biswa96** [comment]
@MehdiChinoune I wonder if it is possible to add qtcharts module in qt6 static package.

**Comment by birdsTalks** [comment]
> @MehdiChinoune I wonder if it is possible to add qtcharts module in qt6 static package.

It would be great if QtCharts could be reintroduced into the automatic construction system. QtCharts have a more modern style than Qwt.

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune I wonder if it is possible to add qtcharts module in qt6 static package. 

Yes, It's possible.

**Comment by birdsTalks** [comment]
Greate! Qt Charts is back in static release. However,  a new tiny problem breaks out after the update.

When creating a new empty hello-world QWidget application with qtcreator (CMAKE), CMake reports some error messages with IMPORTED_IMPLIB and harfbuzz::harfbuzz, like this:

```
Running C:\msys64\ucrt64\bin\cmake.exe -S D:/Projects/testQt6Static -B D:/Projects/build-testQt6Static-Desktop_Qt_6_6_0_static_MinGW_w64_UCRT64_MSYS2-Release "-DCMAKE_GENERATOR:STRING=Ninja" "-DCMAKE_BUILD_TYPE:STRING=Release" "-DCMAKE_PROJECT_INCLUDE_BEFORE:FILEPATH=D:\Projects\build-testQt6Static-Desktop_Qt_6_6_0_static_MinGW_w64_UCRT64_MSYS2-Release/.qtc/package-manager/auto-setup.cmake" "-DQT_QMAKE_EXECUTABLE:FILEPATH=C:/msys64/ucrt64/qt6-static/bin/qmake.exe" "-DCMAKE_PREFIX_PATH:PATH=C:/msys64/ucrt64/qt6-static" "-DCMAKE_C_COMPILER:FILEPATH=C:/msys64/ucrt64/bin/gcc.exe" "-DCMAKE_CXX_COMPILER:FILEPATH=C:/msys64/ucrt64/bin/g++.exe" "-DCMAKE_CXX_FLAGS_INIT:STRING=" in D:\Projects\build-testQt6Static-Desktop_Qt_6_6_0_static_MinGW_w64_UCRT64_MSYS2-Release.
-- The CXX compiler identification is GNU 13.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/ucrt64/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found ZLIB: C:/msys64/ucrt64/lib/libz.dll.a (found version "1.3")  
-- Found WrapSystemZLIB: TRUE  
-- Using system ZLIB.
-- Found WrapZLIB: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Checking for module 'libb2'
--   Found libb2, version 0.98.1
-- Found WrapSystemPCRE2: C:/msys64/ucrt64/lib/libpcre2-16.dll.a (found version "10.42") 
-- Using system PCRE2.
-- Found WrapPCRE2: TRUE  
-- Performing Test HAVE_GETTIME
-- Performing Test HAVE_GETTIME - Success
-- Performing Test HAVE_SHM_OPEN_SHM_UNLINK
-- Performing Test HAVE_SHM_OPEN_SHM_UNLINK - Failed
-- Found WrapRt: TRUE  
-- Found WrapSystemPNG: C:/msys64/ucrt64/lib/libpng.dll.a;C:/msys64/ucrt64/lib/libz.dll.a (found version "1.6.40") 
-- Using system PNG.
-- Found WrapPNG: TRUE  
-- Found WrapSystemHarfbuzz: TRUE  
-- Using system Harfbuzz.
-- Found WrapHarfbuzz: TRUE  
-- Found WrapSystemFreetype: C:/msys64/ucrt64/lib/libfreetype.dll.a (found version "2.13.2") 
-- Using system Freetype.
-- Found WrapFreetype: TRUE  
-- Found WrapVulkanHeaders: C:/msys64/ucrt64/include  
-- Found WrapSystemJpeg: C:/msys64/ucrt64/lib/libjpeg.dll.a (found version "80") 
-- Using system Jpeg.
-- Found WrapJpeg: TRUE  
-- Checking for module 'libmng'
--   Found libmng, version 2.0.3
-- Found TIFF: C:/msys64/ucrt64/lib/libtiff.dll.a (found version "4.6.0")  
-- Found OpenSSL: C:/msys64/ucrt64/lib/libcrypto.dll.a (found version "3.1.4")  
-- Found WrapOpenSSLHeaders: C:/msys64/ucrt64/include (found version "3.1.4") 
-- Found WrapOpenSSL: C:/msys64/ucrt64/lib/libcrypto.dll.a (found version "3.1.4") 
-- Checking for module 'libwebp'
--   Found libwebp, version 1.3.2
-- Checking for module 'libwebpdemux'
--   Found libwebpdemux, version 1.3.2
-- Checking for module 'libwebpmux'
--   Found libwebpmux, version 1.3.2
-- Found WrapWebP: C:/msys64/ucrt64/include  
-- Configuring done (6.9s)
CMake Error in CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target "harfbuzz::harfbuzz"
  configuration "Release".


-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
CMake process exited with exit code 1.

Elapsed time: 00:07.

```

May be some lib config for harfbuzz is missing in Qt's CMake config files.

**Comment by birdsTalks** [comment]
Thank You!!
