### ISSUE TITLE
[qt-creator] Failed to load Several Plugins when starting up.

### ISSUE THREAD

**Issue by birdsTalks** [msys2/MINGW-packages#18953]
### Description / Steps to reproduce the issue

After a pacman -Syu update, Qt Creator 11.0.2-2 in ucrt64 encounted an error. 
```
C:\msys64\ucrt64\lib\qtcreator\plugins\libCtfVisualizer.dll: Can not load library.
C:\msys64\ucrt64\lib\qtcreator\plugins\libCtfVisualizer.dll: Can not find specified program。
C:\msys64\ucrt64\lib\qtcreator\plugins\libPerfProfiler.dll: Can not load library.
C:\msys64\ucrt64\lib\qtcreator\plugins\libPerfProfiler.dll：Can not find specified program。
C:\msys64\ucrt64\lib\qtcreator\plugins\libQmlProfiler.dll: Can not load library.
C:\msys64\ucrt64\lib\qtcreator\plugins\libQmlProfiler.dll：Can not find specified program。
```
These plugins failed to be loaded into QtCreator when starting up.

### Expected behavior

These plugins seems to be OK in old versions

### Actual behavior

May be some dll depends mistake caused this problem. ldd can not detect missing dlls.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Does ntldd show any missing DLLs?

It is possible to show an error message if DLL is absent. Set the `MSYS=winjitdebug` environment variable before launching msys2/mingw terminal. Then run msys2 and the program.

**Comment by birdsTalks** [comment]
This issue has been solved!
