### ISSUE TITLE
[mingw-w64-x86_64-glibmm] static library isn't really static

### ISSUE THREAD

**Issue by Sonic-Amiga** [msys2/MINGW-packages#18960]
### Description / Steps to reproduce the issue

Trying to compile Sigrok (sigrok.org) natively on MSYS2, and hit a conflict between dynamic vs static libglib. A reduced test case proves that:
Sample code:
```
#include <glibmm/datetime.h>
#include <stdio.h>

int main(void)
{
    Glib::DateTime obj;
	printf("%d\n", obj.get_day_of_week());
	
	return 0;
}
```
Command line to compile:
```
$ g++ -c glibmm_test.cpp -IC:/msys64/mingw64/include/glibmm-2.4 -IC:/msys64/mingw64/lib/glibmm-2.4/include -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/include/sigc++-2.0 -IC:/msys64/mingw64/lib/sigc++-2.0/include
```
Then it fails to link with -static:
```
Sonic@Sonic MINGW64 /D/Projects/Test
$ g++ glibmm_test.o -o glibmm_test.exe -static -lglibmm-2.4
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../lib\lib
glibmm-2.4.a(.._.._untracked_glib_glibmm_datetime.cc.obj):(.text+0x13): undefined reference to `__imp_g_date_time_get_type'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../lib\lib
glibmm-2.4.a(.._.._untracked_glib_glibmm_datetime.cc.obj):(.text+0x4a): undefined reference to `__imp_g_date_time_ref'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../lib\lib
glibmm-2.4.a(.._.._untracked_glib_glibmm_datetime.cc.obj):(.text+0x9a): undefined reference to `__imp_g_date_time_ref'
... etc
```
 Is it a bug or intentional behavior ? It seems glibmm-2.4.a is static by itself but still linked against dynamic libglib . If this intentional, how do i get a fully static build ?

### Expected behavior

I expect the test code to successfully link with -static option

### Actual behavior

-static yields linkage error, without -static the code compiles fine and even runs. Yes, it throws an assert, i know.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Hi @Sonic-Amiga, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? https://github.com/msys2/MINGW-packages/actions/runs/6635757008

**Comment by Sonic-Amiga** [comment]
Thank you very much for your turbo-reply! ⚡  Will test today's evening.

**Comment by Sonic-Amiga** [comment]
Thank you again, i've checked, at least my test app builds correctly.
