### ISSUE TITLE
some problems where debugging using lldb

### ISSUE THREAD

**Issue by ZiChenZou** [msys2/MINGW-packages#18968]
### Description / Steps to reproduce the issue

1.create a new cpp file and compile it into an executable file in debug mode. 
2.run lldb program by a command like "lldb main.exe"
3.set some breakpoints
4.run "run" command in lldb program

### Expected behavior

It should display something in a short time, no matter what it will show on screen.

### Actual behavior

It show nothing on screen within a long period, unless you enter the "enter" key for several times. Then the lldb program will run as usual. However, it seems that most commands in lldb program need to take a long time to react, or you can try the "enter" key.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

**Comment by ZiChenZou** [comment]
The most simple code:

#include <iostream>

int main()
{
        std::cout << "hello!" << '\n';
        return 0;
}

And I don't think it's a problem with the code, because all of codes I have tried just can't work well in lldb program. I think either it's a problem with lldb itself, or it's a problem with my computer. So, I want to find some help.

**Comment by Biswa96** [comment]
lldb is working fine in my system. Could you provide the output of these two commands?

```
type lldb
lldb --version
```

**Comment by ognevnydemon** [comment]
is this about MSYS lldb or MINGW lldb?

**Comment by Biswa96** [comment]
May I ask if you were able to resolve the issue? Would it also be possible for you to kindly elaborate on the reason behind it?

**Comment by ZiChenZou** [comment]
> May I ask if you were able to resolve the issue? Would it also be possible for you to kindly elaborate on the reason behind it?

OK, I still can't resolve the issue. I don't know how to fix it. Apart from lldb, I am able to use gdb for debugging. I'll be waiting for developers' updates. Maybe I can use it again someday. But before that, I don't want to focus on this issue for too long.

And thanks for all of kind people who tried to help me.
