### ISSUE TITLE
universal-ctags: `--links` option is not working

### ISSUE THREAD

**Issue by KSR-Yasuda** [msys2/MINGW-packages#19000]
### Description / Steps to reproduce the issue

As `man`, `universal-ctags` v6.0.0 has `--links` option to specify to follow or unfollow symbolic links.

```text
% man ctags
                                     (snip)

       --links[=(yes|no)]
              Indicates whether symbolic links (if supported) should be followed.  When disabled, symbolic links are ignored. This option is  on  by  de‐
              fault.
```

However, it looks not working: always follows links even if `--links=no` is set.

Is this option unavailable in MSYS env?
Or just a bug?

### How to repro

```bash
% echo "void f() {}" > a.c
% ln -s a.c b.c
% ls -l
total 1.0K
drwxr-xr-x 1 xxxxxxxx xxxxxxxx  0 Nov  1 12:05 ./
drwxr-xr-x 1 xxxxxxxx xxxxxxxx  0 Nov  1 12:05 ../
-rw-r--r-- 1 xxxxxxxx xxxxxxxx 12 Nov  1 12:05 a.c
lrwxrwxrwx 1 xxxxxxxx xxxxxxxx  3 Nov  1 12:05 b.c -> a.c

% ctags -f .tags --append=no --recurse=yes --links=no

% sed '/^!/ d' .tags
f       a.c     /^void f() {}$/;"       f       typeref:typename:void
f       b.c     /^void f() {}$/;"       f       typeref:typename:void
```

### Version

```bash
% ctags --version
Universal Ctags 6.0.0, Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Mar 12 2023, 06:11:44
  URL: https://ctags.io/
  Output version: 0.0
  Optional compiled features: +win32, +wildcards, +regex, +gnulib_regex, +internal-sort, +unix-path-separator, +iconv, +option-directory, +xpath, +json, +
interactive, +yaml, +case-insensitive-filenames, +packcc, +optscript, +pcre2
yasuda@Kujira3 MINGW64 ~/Downloads/Ctags/test

% type -a ctags
ctags is /mingw64/bin/ctags

% pacman -Ss ctags
mingw64/mingw-w64-x86_64-ctags 5.8-5
    A multilanguage implementation of Ctags (mingw-w64)
mingw64/mingw-w64-x86_64-universal-ctags 6.0.0-1 [installed]
    Generates an index file of language objects found in source files (mingw-w64)
msys/ctags 5.8-2
    Generate tag files for source code
```

### Expected behavior

`ctags --links=no` ignores symbolic links.

### Actual behavior

Even if `--links=no` is set, `ctags` follows symbolic links.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by KSR-Yasuda** [comment]
Could you try with `--recurse=yes` option?
I've missed it was specified in my `${HOME}/.ctags.d/*.ctags`.

**Comment by Biswa96** [comment]
> Could you try with `--recurse=yes` option?

I have tried `ctags -f .tags --append=no --recurse=yes --links=no` command but it does not show any output. I have run the command in a directory which has a.c and b.c files.

**Comment by KSR-Yasuda** [comment]
I usually uses `-f .tags` option to make output tag file hidden.
Don't you see the file even `ls -a`?
Otherwise, if you drop `-f .tags` option, it outputs `tags` file as its default file name.

By `--recurse=yes`, the working dir should be the target of the command.
So, I think it will output something even if no source files are found...

**Comment by Biswa96** [comment]
Yeah, the command creates .tags file. Somehow I assumed that it should show output in terminal 😄 

This seems to be general symbolic link issue. Try to create the b.c file with `MSYS=winsymlinks:sys ln -sf a.c b.c` command. More info about `winsymlinks` can be found here https://www.cygwin.com/cygwin-ug-net/using-cygwinenv.html

**Comment by KSR-Yasuda** [comment]
Okay, so `ctag` can't tell `winsymlinks:nativestrict` links from other normal files, right?

I tried other `winsymlinks` options.
Other than `nativestrict` does work as expected, ignored by `--links=no` correctly.

```bash
% for o in lnk nativestrict sys; do
>     MSYS=winsymlinks:$o ln -s a.c "$o.c"
> done
% ctags -f .tags --append=no --links=no --recurse=yes
% sed -re '/^!/ d' .tags
f       a.c     /^void f() {}$/;"       f       typeref:typename:void
f       nativestrict.c  /^void f() {}$/;"       f       typeref:typename:void
```
