### ISSUE TITLE
Kicad for UCRT64 locks up

### ISSUE THREAD

**Issue by stahta01** [msys2/MINGW-packages#19102]
### Description / Steps to reproduce the issue

Install KiCad for UCRT64
Run kicad

### Expected behavior

The KICad GUI to be displayed

### Actual behavior

After waiting 5 minutes I kill the program because the GUI is not displayed

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes

**Comment by MehdiChinoune** [comment]
Fixed.

**Comment by stahta01** [comment]
FYI: Mu patch never fixed the UCRT locking up when Plugin Content Manager is used!
