### ISSUE TITLE
Sheboken requires a different python version than those installed on current MSYS2 system.

### ISSUE THREAD

**Issue by wsteffe** [msys2/MINGW-packages#19182]
### Description / Steps to reproduce the issue

Try to configure with cmake a package that requires shiboken2 on current platform Msys2-Mingw64. 

### Expected behavior

Cmake configuration free of errors

### Actual behavior

I got the following error when I was trying to build FreeCAD:

> CMake Error at C:/msys64/mingw64/lib/cmake/Shiboken2-5.15.11/shiboken_helpers.cmake:468 (message):
>   The detected Python minor version is not compatible with the Python minor
>   version which was used when Shiboken was built.  Consider building shiboken
>   with FORCE_LIMITED_API set to '1', so that only the Python major version
>   matters.
> 

>     Built with: '3.11' Detected: '3.12'
> Call Stack (most recent call first):
>   C:/msys64/mingw64/lib/cmake/Shiboken2-5.15.11/Shiboken2Config.cp311-mingw_x86_64.cmake:45 (shiboken_check_if_built_and_target_python_are_compatible)
>   C:/msys64/mingw64/lib/cmake/Shiboken2-5.15.11/Shiboken2Config.cmake:5 (include)
>   cMake/FreeCAD_Helpers/SetupShibokenAndPyside.cmake:22 (find_package)
>   CMakeLists.txt:83 (SetupShibokenAndPyside)
> 

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
There is a known issue about CMake choosing Official Python over mingw-w64-python. It's obvious the cmake is selecting Official Python 3.12 as mingw-w64-python is still at 3.11
Try passing `-DPython_EXECUTABLE=${MINGW_PREFIX}/bin/python` to cmake.
