### ISSUE TITLE
Can't download "mingw-w64-i686-qemu" package

### ISSUE THREAD

**Issue by TheBigEye** [msys2/MINGW-packages#19200]
While working on a project, I wanted to install 32-bit QEMU via pacman on **MSYS-MINGW32**, but it seems that the package no longer exists:

https://packages.msys2.org/package/mingw-w64-i686-qemu

![image](https://github.com/msys2/MINGW-packages/assets/63316583/100ffbf3-14e2-4308-8938-b065ea2e3df1)

Which is a bit strange since several months ago it was available and I could do it
download, could you review it or at least update it?, Thanks ...

**Comment by lazka** [comment]
Starting with 8.1.2 it no longer built, so we disabled the 32bit build. #18884

I don't know what the error was though.

**Comment by lazka** [comment]
What's the reason you need it?

**Comment by TheBigEye** [comment]
I'm working on a project where I need to run a 32-bit system, more specifically a basic (bare-bones) i486-based kernel. QEMU is run through my Makefile, since doing it manually would involve too many arguments. I could perfectly use 64-bit QEMU on MSYS-MINGW64, but I do the build process with MSYS-MINGW32 due to the architecture of the libraries, the compiler, and my project within VS Code.

Therefore, due to the nature of MSYS2, I would have to constantly modify my Path variable on Windows, which is not very convenient. Also, having both terminals open at the same time doesn't seem like a good idea either. I've tried using separate scripts that point to the full path of each executable, but I don't see that as portable.

**Comment by stahta01** [comment]
> Starting with 8.1.2 it no longer built, so we disabled the 32bit build. #18884
> 
> I don't know what the error was though.

```
pc-bios/optionrom: Linking multiboot.img
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot open linker script file /h/devel/msys2_projects/repos/MINGW-packages/mingw-w64-qemu/src/qemu-8.1.3/pc-bios/optionrom/flat.lds: No such file or directory
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:50: multiboot.img] Error 1
make: *** [Makefile:190: pc-bios/optionrom/all] Error 2
```
I just tried to build mingw32 and got the above error.

Tim S.

**Comment by heljkon** [comment]
With upcoming 8.2.0, 32bit builds are reenabled. I've found a workaround for the error. See https://github.com/msys2/MINGW-packages/pull/19085

**Comment by MehdiChinoune** [comment]
Actually we started phasing-out 32bit environments, so better to not re-enable them again.

**Comment by 1480c1** [comment]
One thing I can recommend is looking to see if using the commands `. shell
mingw32` and `. shell mingw64` would work in your case to switch between
environments without needing a new terminal

**Comment by OBattler** [comment]
> Actually we started phasing-out 32bit environments, so better to not re-enable them again.

But why? And without an announcement at that so projects don't even have a timeframe in which to adapt.

**Comment by MehdiChinoune** [comment]
> But why? And without an announcement at that so projects don't even have a timeframe in which to adapt.

https://github.com/msys2/msys2.github.io/pull/299/files
https://github.com/msys2/MINGW-packages/discussions/19326
