### ISSUE TITLE
mkvtoolnix-gui is missing libfmt.dll

### ISSUE THREAD

**Issue by dustwanderer** [msys2/MINGW-packages#19226]
### Description / Steps to reproduce the issue

On 2023-10-16 I reported a mkvtoolnix-gui bug introduced by a recent update. Next day Lazka solved the issue [mkvtoolnix-gui does not open after last MSYS2 update](https://github.com/msys2/MINGW-packages/issues/18870). Thank you very much!!

I have updated MSYS2 again, and mkvtoolnix-gui has a new bug.

### Expected behavior

When I double-click the mkvtoolnix-gui icon, I expect a graphic window to open.

### Actual behavior

When I double-click the mkvtoolnix-gui icon, I get an error message stating that libfmt.dll is missing, and suggesting to reinstall the program (translated from Spanish).

I have reinstalled mkvtoolnix-gui, but the problem persists.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
It was a silly mistake. fmt library was not added in dependencies 😞
