### ISSUE TITLE
error: target not found: mingw-w64-cmake

### ISSUE THREAD

**Issue by vault-thirteen** [msys2/MINGW-packages#19282]
### Description / Steps to reproduce the issue

1. Start the `MSYS2 MINGW64` Terminal
2. Try to install the `mingw-w64-cmake` package located here: https://packages.msys2.org/base/mingw-w64-cmake
3. An error occures.

### Expected behaviour

Package installation.

### Actual behaviour

Error.

```
$ pacman -S mingw-w64-cmake
error: target not found: mingw-w64-cmake
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
mingw-w64-cmake is not a real package name. It's just a name. For MINGW64, the actual package name is [mingw-w64-x86_64-cmake](https://packages.msys2.org/package/mingw-w64-x86_64-cmake?repo=mingw64). 

`pacman -S $MINGW_PACKAGE_PREFIX-cmake` command can be used to avoid typing that long package name. Or, use `pacboy -S cmake:p` command. pacboy has to be installed with `pacman -S pactoys` command.

**Comment by vault-thirteen** [comment]
Thank you, my friend. 
`$ pacman -S mingw-w64-x86_64-cmake`
It works.
