### ISSUE TITLE
Add ngspice_con.exe to ngspice package

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MINGW-packages#19283]
ngspice opens a gui window, but there is also ngspice for the terminal, called ngspice_con which should be able to run from the terminal, since ngspice is really just text, and there is no "real gui"

**Comment by Biswa96** [comment]
I have tried to build the console version but it produces the executable with similar ngspice.exe name. Is there any documentation how to provide console version or do you know any software distribution which provides the console version?

**Comment by Kreijstal** [comment]
It works but it still needs the #12535 workaround/fix

**Comment by Biswa96** [comment]
Thanks for the hint. I have added the required changes for that issue. Please test the new builds from here https://github.com/msys2/MINGW-packages/actions/runs/7142160126

**Comment by Kreijstal** [comment]
It works, bugs is fixed, and we have both console and gui version :)
