### ISSUE TITLE
The new version of "librest > 0.8.1" is incompatible with virt-viewer.

### ISSUE THREAD

**Issue by kernelplv** [msys2/MINGW-packages#19292]
### Description / Steps to reproduce the issue

Virt-viewer uses librest 0.7, this library is necessary in order to be able to mount CDs in the ovirt virtual machine. Attempts to build virt-viewer with “librest > 0.8.1” result in disks not being mounted, and a bunch of errors in the console.

A long time ago I built virt-viewer in msys2, and that build still works, but now the msys2 repositories have been significantly updated and it is impossible to build virt-viewer with the necessary packages.

I also think that this leads to the inability to connect USB devices to the ovirt virtual machine.

### Expected behavior

- meson sees the rest0.7 dependency 
- after connecting to spice the CD selection button is active
![image](https://github.com/msys2/MINGW-packages/assets/4732036/b3bc3ba5-400e-4ab9-9051-2c030b6dd784)

### Actual behavior

- meson does NOT see the rest0.7 dependency 
```bash
Run-time dependency glib-2.0 found: YES 2.78.1
Run-time dependency gmodule-2.0 found: YES 2.78.1
Run-time dependency gtk+-3.0 found: YES 3.24.39
Run-time dependency libxml-2.0 found: YES 2.12.1
Run-time dependency libvirt found: YES 9.9.0
Run-time dependency libvirt-glib-1.0 found: YES 5.0.0
Run-time dependency gtk-vnc-2.0 found: YES 1.3.1
Run-time dependency spice-client-glib-2.0 found: YES 0.42.1-77af
Run-time dependency spice-client-gtk-3.0 found: YES 0.42.1-77af
Run-time dependency spice-protocol found: YES 0.14.5
Run-time dependency govirt-1.0 found: YES 0.3.9
Did not find CMake 'cmake'
Found CMake: NO
`Run-time dependency rest-0.7 found: NO (tried pkgconfig and cmake)`
Run-time dependency vte-2.91 found: NO (tried pkgconfig and cmake)
Run-time dependency bash-completion found: NO (tried pkgconfig and cmake)
Configuring config.h using configuration
```
- after connecting to spice the CD selection button is inactive or, if building with “librest > 0.8.1” then the button is active, but changing disks does not lead to their mounting
![image](https://github.com/msys2/MINGW-packages/assets/4732036/7fefc63f-10e4-43e8-9582-f2c3b20e71ab)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
mingw-w64-virt-viewer does not use librest.
It seems that your building wasn't run on MSYS2 because there is no mingw-w64-libgovirt (which depends on librest).
Please give more details.
Are you using mingw-w64-virt-viewer, or this issue is from you own built virt-viewer that uses MSYS2 packages

**Comment by kernelplv** [comment]
> mingw-w64-virt-viewer does not use librest.

Yes, the mingw-w64-virt-viewer package does not use either libgovirt or librest, so it does not have the necessary functionality.

> It seems that your building wasn't run on MSYS2 because there is no mingw-w64-libgovirt (which depends on librest).

Yes, that’s why I had to build libgovirt myself. I would have built librest0.7 myself too, but then there is a dependency conflict.

> Are you using mingw-w64-virt-viewer, or this issue is from you own built virt-viewer that uses MSYS2 packages

I don’t use mingw-w64-virt-viewer, I build it from source inside MSYS2 using mingw-w64-meson.

Thank you.

**Comment by MehdiChinoune** [comment]
but, I see libgovirt requires librest>=0.9 https://gitlab.gnome.org/GNOME/libgovirt/-/blob/v0.3.9/meson.build?ref_type=tags#L44
This is something you should report to virt-viewer not to MSYS2

**Comment by kernelplv** [comment]
I understand that the latest libgovirt requires a fresh rest, but if you compile the freshest libgovirt, then virt-viewer will require code modifications. Unfortunately, the virt-viewer project is more dead than alive, so the option with modification is not possible.

If you take not the freshest libgovirt (https://gitlab.gnome.org/GNOME/libgovirt/-/blob/v0.3.7/meson.build?ref_type=tags#L44), then it just uses rest-0.7 which is also needed for virt-viewer. As far as I understand, these dependencies are used in virt-viewer in parallel. In other words, for the correct operation of virt-viewer, libgovirt-0.3.7 and rest-0.7 are required simultaneously.

I would like to see the rest-0.7 package in the MSYS2 repositories or at least have the opportunity to return to the old repositories (maybe there is some kind of archive).

P.S: I tried to build virt-viewer on fedora, where there is a rest-0.7 package, but there are many other problems there that are not in MSYS2.

**Comment by MehdiChinoune** [comment]
better to wait for a fix from upstream

**Comment by MehdiChinoune** [comment]
@kernelplv Just a last attempt, could you update your MSYS2 installation (run `pacman -Syu` twice) and install virt-viewer from MSYS2 and If it works or not.
