### ISSUE TITLE
CMake 3.28 no longer finds ICU libs

### ISSUE THREAD

**Issue by kmilos** [msys2/MINGW-packages#19310]
### Description / Steps to reproduce the issue

Run `find_package(ICU COMPONENTS i18n data uc)` in a CMake script.

### Expected behavior

w/ older CMake (and older icu 73):
```
-- Found the following ICU libraries:
--   i18n (required): C:/msys64/ucrt64/lib/libicuin.dll.a
--   data (required): C:/msys64/ucrt64/lib/libicudt.dll.a
--   uc (required): C:/msys64/ucrt64/lib/libicuuc.dll.a
```

### Actual behavior

Windows system libs are being detected instead of MSYS ones:
```
-- Found the following ICU libraries:
--   i18n (required): C:/Windows/System32/icuin.dll
--   data (required): C:/msys64/ucrt64/lib/libicudt.dll.a
--   uc (required): C:/Windows/System32/icuuc.dll
```

Possibly related to this CMake 3.28 changes:
```
* The "find_library()", "find_path()", and "find_file()" commands no
longer search in installation prefixes derived from the "PATH"
environment variable.  This behavior was added in CMake 3.3 to
support MSYS and MinGW ("MSYSTEM") development environments on
Windows, but it can search undesired prefixes that happen to be in
the "PATH" for unrelated reasons.  Users who keep some
"<prefix>/bin" directories in the "PATH" just for their tools do not
necessarily want any corresponding "<prefix>/lib" or
"<prefix>/include" directories searched. The behavior was reverted
for non-Windows platforms by CMake 3.6. Now it has been reverted on
Windows platforms too.

One may set the "CMAKE_PREFIX_PATH" environment variable with a
semicolon-separated list of prefixes that are to be searched.

* When using MinGW tools in a "MSYSTEM" environment on Windows, the
"$MSYSTEM_PREFIX/local" and "$MSYSTEM_PREFIX" prefixes are now added
to "CMAKE_SYSTEM_PREFIX_PATH".
```

It gives the impression CMAKE_SYSTEM_PREFIX_PATH should be handled automatically in MSYS, but doesn't seem to be?

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19044

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
If I do:

```
project(test)

foreach(dir ${CMAKE_SYSTEM_PREFIX_PATH})
  message(${dir})
endforeach()
```

I get

```
C:/msys64/ucrt64
C:/Program Files
C:/Program Files (x86)
C:/msys64/ucrt64
C:/Program Files (x86)/test
```

so it seems to be working somewhat

**Comment by MehdiChinoune** [comment]
Are you running mingw-w64-cmake from Windows CMD or PWSH?
I couldn't reproduce the issue on MSYS shells?

**Comment by kmilos** [comment]
Nope, UCRT64 launcher.

The standalone test project indeed works, so I'll have to figure out what's going in w/ my large project CMakeLists.txt...

**Comment by kmilos** [comment]
I'm also seeing other weirdness w/ CMake 3.28. For LibTIFF I'm now getting:
```
-- Could NOT find tiff (missing: tiff_DIR)
-- Found TIFF: C:/msys64/ucrt64/lib/libtiff.dll.a (found version "4.6.0")
-- The following REQUIRED packages have been found:

 * TIFF

-- The following OPTIONAL packages have not been found:

 * tiff
````

With this minimal reproducer:
```
find_package(TIFF REQUIRED)
include(FeatureSummary)
feature_summary(WHAT ALL)
```

**Comment by MehdiChinoune** [comment]
Could you report those issue upstream

**Comment by kmilos** [comment]
Done. I guess I'll close this as it comes down to difference in behaviour in the new version.
