### ISSUE TITLE
openssl first / is replaced to file path

### ISSUE THREAD

**Issue by bitamind** [msys2/MINGW-packages#19312]
### Description / Steps to reproduce the issue

when using openssl req command, first / is replaced to file path in subj option.
add one more / to first /, so / is not replaced.

### Expected behavior

/ is not replaced.

### Actual behavior

```
$ pacman -Ss openssl
ucrt64/mingw-w64-ucrt-x86_64-openssl 3.2.0-1 [installed]
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security (mingw-w64)
$ openssl req -verbose -new -x509 -days 365 -newkey rsa:2048 -sha256 -subj "/C=JP/CN=TEST Root Certification Authority" -out cacert.pem -keyout ./private/cakey.pem
Using configuration from D:/tool/msys64/ucrt64/etc/ssl/openssl.cnf
Generating rsa key with 2048 bits
.......+.+++++++++++++++++++++++++++++++++++++++*........+......+......+........+.......+......+..+.
+...........+......+...+++++++++++++++++++++++++++++++++++++++*...+........................+...+....
..+............+...+.........++++++
...........+...+....+...........+....+......+.....+.+.........+.....+.+.....................+.......
.+....+..+.+..+.+++++++++++++++++++++++++++++++++++++++*.+.......+............+.....+............+++
++++++++++++++++++++++++++++++++++++*.............+......+.......+..+..........+...........+...+....
...+..+.+.....+.+...+.................+.+........++++++
Writing private key to './private/cakey.pem'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
req: subject name is expected to be in the format /type0=value0/type1=value1/type2=... where charact
ers may be escaped by \. This name is not in that format: 'D:/tool/msys64/C=JP/CN=TEST Root Certific
ation Authority'
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by brisingraerowing** [comment]
This is an MSYS2 feature. It replaces Unix paths with their Win32 equivalent.

**Comment by bitamind** [comment]
I know that, but subj option needs to start /.
If MSYS2 has exception handling for path replacement, I would like it to be added there.
now i add "//=" first, like this "//=/C=JP/CN=TEST Root Certification Authority"
or any other solutions?
thank you

**Comment by Kreijstal** [comment]
maybe try
`MSYS2_ARG_CONV_EXCL="*"  openssl req -verbose -new -x509 -days 365 -newkey rsa:2048 -sha256 -subj "/C=JP/CN=TEST Root Certification Authority" -out cacert.pem -keyout ./private/cakey.pem`

**Comment by bitamind** [comment]
It was clearly resolved.
Thanks for the advice.
