### ISSUE TITLE
[helix] Package not found

### ISSUE THREAD

**Issue by Wallchs** [msys2/MINGW-packages#19348]
### Description / Steps to reproduce the issue

With the command: pacman -S mingw-w64-helix isn't work, the message with return 

error: target not found: mingw-w64-helix

### Expected behavior

The installation of the package

### Actual behavior

error: target not found: mingw-w64-helix

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-11 Windows 22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
For MINGW64 environment, the package name is [mingw-w64-x86_64-helix](https://packages.msys2.org/package/mingw-w64-x86_64-helix?repo=mingw64).

You can use `pacboy` command to shorten the package name. First, install pactoys package with `pacman -S pactoys`. Then install helix with `pacboy -S helix:p` (the colon-p is important).
