### ISSUE TITLE
Add libplacebo-demos

### ISSUE THREAD

**Issue by kasper93** [msys2/MINGW-packages#19354]
### Package name

libplacebo-demos

### Brief description of package

libplacebo, but the demo applications only. Main libplacebo package is a dependency of ffmpeg. We cannot build demos directly which depends on ffmpeg, creating dependency cycle as a result.

What I propose is to add libplacebo-demos package with only the demo applications.

Motivation is to give users ability to play around with those applications. Without forcing them to build locally, see https://github.com/haasn/libplacebo/discussions/231

### URL for package's homepage

https://code.videolan.org/videolan/libplacebo

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment]
It may be possible to add the demos. First, the libplacebo source need to be converted to git repository in PKGBUILD. Otherwise, the demos/3rdparty/nuklear does not exist in tarball and I got the linking error undefined reference to parse_args.

**Comment by Biswa96** [comment]
Just realized that removing ffmpeg workarounds the issue as it does not compile plplay.

**Comment by Biswa96** [comment]
I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request?
