### ISSUE TITLE
[binutils] --compress-debug-sections is not supported by ld

### ISSUE THREAD

**Issue by palladium-coder** [msys2/MINGW-packages#19395]
### Description / Steps to reproduce the issue

The linker flag `--compress-debug-sections` is not supported by [mingw-w64-ucrt-x86_64-binutils](https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-binutils?repo=ucrt64)

Details
```
$ /ucrt64/bin/ld --version
GNU ld (GNU Binutils) 2.41
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

```
$ /ucrt64/bin/ld --help | grep compress
```

But 
with the same ld version on my wsl2 environment I can confirm that the above is a valid linker option.

```
$ /usr/bin/ld --version
GNU ld (GNU Binutils for Ubuntu) 2.41
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

```
$ /usr/bin/ld --help | grep compress
--compress-debug-sections=[none|zlib|zlib-gnu|zlib-gabi|zstd]
```

### Expected behavior

--compress-debug-sections is a valid linker flag and show up in the help message

### Actual behavior

--compress-debug-sections is not a valid linker flag and dosent show up in the help message .

If I use it, i get the below error
```
ld: unrecognized option '--compress-debug-sections=zlib'
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by revelator** [comment]
some commands in binutils are not supported on windows despite showing up in the help section, though that one not being supported is indeed strange ?. there are several sections in ld that are only supported in linux, most will just throw a warning about it.

**Comment by MehdiChinoune** [comment]
See https://sourceware.org/binutils/docs/ld/Options.html
```
--compress-debug-sections=none
--compress-debug-sections=zlib
--compress-debug-sections=zlib-gnu
--compress-debug-sections=zlib-gabi
--compress-debug-sections=zstd
On ELF platforms, these options control how DWARF debug sections are compressed using zlib.

```
MinGW-w64 is not an ELF platform.

**Comment by revelator** [comment]
indeed, it would have been a nice option on windows to though :), maybe something to point out the next time we have something to discuss with the binutils developer.

**Comment by palladium-coder** [comment]
Thank you all for the information

**Comment by palladium-coder** [comment]
Hello,

I wanted one more clarification.

why does objcopy support compressed debug sections but not ld. For e.g 

ld details

```
$ /ucrt64/bin/ld --version
GNU ld (GNU Binutils) 2.41
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
$ /ucrt64/bin/ld --help | grep compress
<no_output>
```

objcopy details

```
$ objcopy --version
GNU objcopy (GNU Binutils) 2.41
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
$ objcopy --help | grep compress
     --compress-debug-sections[={none|zlib|zlib-gnu|zlib-gabi|zstd}]
     --decompress-debug-sections   Decompress DWARF debug sections using zlib
```

I am able to use --compress-debug-sections on a hello world binary complied from rust like below
```
$ cargo new hello_world
$ cargo +stable-gnu build
$ ./target/debug/hello_world.exe
Hello, world!
$ objcopy --compress-debug-sections target/debug/hello_world.exe hello_world_compress
$ ./hello_world_compress
Hello, world!
$ ls -lah ./hello_world_compress target/debug/hello_world.exe
-rwxr-xr-x 1 user user 2.4M Dec 24 16:56 ./hello_world_compress
-rwxr-xr-x 2 user user 5.4M Dec 24 16:54 target/debug/hello_world.exe
```

**Comment by MehdiChinoune** [comment]
Ask binutils maintainers, not us.
