### ISSUE TITLE
[libavif] static library missing

### ISSUE THREAD

**Issue by hessenfarmer** [msys2/MINGW-packages#19510]
### Description / Steps to reproduce the issue

in  our CI environment we build static windows builds. Since the last update pf sdl2 image  libavif is required but does not provide a static library.

### Expected behavior

Please add a static library of avif to the package

### Actual behavior

no static library provided

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

uname

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Comment by hessenfarmer** [comment]
I Installed the package from the PR.  
and it found the static library but at link time I still get some of these failures.

C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib/libSDL2_image.a(libSDL2_image_la-IMG_avif.o):(.text+0x120): undefined refere
nce to `__imp_avifImageYUVToRGB'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:/msys64/mingw64/lib/libSDL2_image.a(libSDL2_image_la-IMG_avif.o):(.text+0x127): undefined refere
nce to `__imp_avifResultToString'

**Comment by Biswa96** [comment]
Thank you for conducting the test. It appears that the issue you encountered is related to SDL2_image. I will make the necessary changes and include them in the pull request.

**Comment by kmilos** [comment]
Could this be because the `lib/cmake/libavif-config-release.cmake` file shipped w/ the package always points to the shared library (i.e. that's the last config installed even after enabling the static build):
```
set_target_properties(avif PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/libavif.dll.a"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/libavif-16.dll"
  )
```

**Comment by Biswa96** [comment]
Not sure if the SDL2_image static library issue is related to cmake files. The libSDL2_image.a has libavif symbols with dllimport attribute. See the following command output.

```
$ nm /ucrt64/lib/libSDL2_image.a | grep -i _imp
                 U __imp_avifDecoderCreate
                 U __imp_avifDecoderDestroy
                 U __imp_avifDecoderNextImage
                 U __imp_avifDecoderParse
                 U __imp_avifDecoderSetIO
                 U __imp_avifImageYUVToRGB
                 U __imp_avifPeekCompatibleFileType
                 U __imp_avifResultToString
                 U __imp_longjmp
                 U __imp_longjmp
```

**Comment by kmilos** [comment]
So SDL2_image defined (or didn't undef) `AVIF_DLL` when building the static lib then?

**Comment by Biswa96** [comment]
> Isn't this a job for libavif pkgconf/cmake config files?

Yes, the AVIF_DLL flag came from pkgconfig file of libavif.

@hessenfarmer Would you like to test the latest artifacts from the pull request? The artifact contains two package file and you need to install them both to test.

**Comment by hessenfarmer** [comment]
unfortunately I only tested the 64bit package but not the 32 bit package. 
32 bit is still broken as avif needs svt-av1 which is only available for 64 bit

**Comment by Biswa96** [comment]
> 32 bit is still broken as avif needs svt-av1 which is only available for 64 bit

32 bit libavif package does not have svt-av1 dependency, see the package info here https://packages.msys2.org/package/mingw-w64-i686-libavif?repo=mingw32

Also, there is a similar issue about libavif static linking. I have sent a pull request to upstream libavif repository and waiting for reply.

**Comment by hessenfarmer** [comment]
ok I understand, however I believe having a package that behaves differently between 32bit builds and 64 bit builds, results in different functionalities and potentially makes it hard to provide the same software on different plarforms.  
is there any chance that there might be some 32bit package of svt-av1?
If not would you consider removing it from the 64 bit as well.

**Comment by Biswa96** [comment]
> is there any chance that there might be some 32bit package of svt-av1?

svt-av1 only supports 64 bit operating systems. See this upstream documentation https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/System-Requirements.md

Speaking of 32 bit package, are you or your user running 32 bit Windows OS?

**Comment by hessenfarmer** [comment]
basically we still provide 32 bit crosscompiled packages for WINDOWS of our game. ([widelands](https://github.com/widelands/widelands))

**Comment by Biswa96** [comment]
I was asking for actual or estimated users who are using 32 bit Windows OS on 32 bit hardware.

**Comment by hessenfarmer** [comment]
we can't tell as we do not count all downloads for each package
