### ISSUE TITLE
Missing mingw-w64-i686-opencascade

### ISSUE THREAD

**Issue by stahta01** [msys2/MINGW-packages#19511]
### Description / Steps to reproduce the issue

pacman -S mingw-w64-i686-opencascade

### Expected behavior

Expect the package to be installed

### Actual behavior

error: target not found: mingw-w64-i686-opencascade

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
What do you need it for?

**Comment by stahta01** [comment]
> What do you need it for?

Self built Kicad

**Comment by MehdiChinoune** [comment]
We (I) dropped it as part of #19326

**Comment by stahta01** [comment]
> We (I) dropped it as part of #19326

Okay, I will self build opencascade, also. I just thought it strange to still have CLANG32 but not have MINGW32 package.
