### ISSUE TITLE
UCRT64 LLVM-17 is linked to wrong DLL msvcrt.dll instead of ucrtbase.dll

### ISSUE THREAD

**Issue by hkinke** [msys2/MINGW-packages#19534]
### Description / Steps to reproduce the issue

It is easy to see that LLVM is linked to `msvcrt.dll` instead of `ucrtbase.dll`

```bash
$ ntldd -R /ucrt64/bin/libLLVM-17.dll | grep msvcrt
         msvcrt.dll => C:\Windows\SYSTEM32\msvcrt.dll (0x000002613edc0000)
```

An example code can be found at [https://github.com/hkinke/testllvm](https://github.com/hkinke/testllvm)

First we configure and build

```bash
cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug .
cmake --build build
```
Application does not crash with simple example, but we can analyze a debug information. We will see both `msvcrt` and `ucrt` functions are used at same time.

```bash
gdb ./main
```

We have this interactive debug information

```gdb
(gdb) b 114
Breakpoint 1 at 0x140001e82: file C:/dev/testllvm/testllvm/main.cpp, line 114.
(gdb) run
Starting program: C:\dev\testllvm\build\main.exe
Thread 1 hit Breakpoint 1, main (argc=1, argv=0x101a90) at C:/dev/testllvm/testllvm/main.cpp:114
114         int * p=static_cast<int *>(myalloc(4*sizeof(int)));
(gdb) x/5i myalloc
   0xd20000:    sub    $0x28,%rsp
   0xd20004:    movabs $0x7ffa1e350060,%rax
   0xd2000e:    call   *%rax
   0xd20010:    nop
   0xd20011:    add    $0x28,%rsp
(gdb) x/5i 0x7ffa1e350060
   0x7ffa1e350060 <ucrtbase!malloc>:    jmp    0x7ffa1e350070 <ucrtbase!_malloc_base>
   0x7ffa1e350065 <ucrtbase!malloc+5>:  int3
   0x7ffa1e350066 <ucrtbase!malloc+6>:  int3
   0x7ffa1e350067 <ucrtbase!malloc+7>:  int3
   0x7ffa1e350068 <ucrtbase!malloc+8>:  jno    0x7ffa1e350012 <ucrtbase!_realloc_base+34>
(gdb) x/5i free
   0x7ffa1f19c690 <msvcrt!free>:        test   %rcx,%rcx
   0x7ffa1f19c693 <msvcrt!free+3>:      je     0x7ffa1f19c6cc <msvcrt!free+60>
   0x7ffa1f19c695 <msvcrt!free+5>:      push   %rbx
   0x7ffa1f19c696 <msvcrt!free+6>:      sub    $0x20,%rsp
   0x7ffa1f19c69a <msvcrt!free+10>:     mov    %rcx,%r8
```
As you can see, `malloc` belongs to `ucrt` and `free` belongs to `msvcrt`.

**Maybe, The fault comes LLVM** and it is not a fault of `MSYS2` build script.

### Expected behavior

My application can call `free` on memory allocated by `libLLVM-17.dll`.

### Actual behavior

Application crashes because it uses `free` from `ucrtbase.dll`  for memory allocated with `malloc` of `msvcrt.dll` by `libLLVM-17.dll`.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22000

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
ldd output is not correct, use [ntldd](https://packages.msys2.org/base/mingw-w64-ntldd) to find dependencies.

> Application crashes because it uses `free` from `ucrtbase.dll` for memory allocated with `malloc` of `msvcrt.dll` by `libLLVM-17.dll`.

Please provide sample code and steps to reproduce the issue.

**Comment by MehdiChinoune** [comment]
I couldn't reproduce your results:
```
$ ntldd -R /ucrt64/bin/libLLVM-17.dll | grep ucrtbase
```
shows nothing. While
```
$ ntldd -R /ucrt64/bin/libLLVM-17.dll | grep msvcrt
         msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x000001f6901a0000)
```
Maybe because I am using Windows 10 and you are using Windows 11?

**Comment by MehdiChinoune** [comment]
All libraries in bin folder are linked against msvcrt.dll.
We need someone from mingw-w64 to explain that.

**Comment by Biswa96** [comment]
> All libraries in bin folder are linked against msvcrt.dll.

Could you provide any output from any tool other than ldd?

**Comment by MehdiChinoune** [comment]
> Could you provide any output from any tool other than ldd?

I am using ntldd
```
for _dll in /ucrt64/bin/*.dll; do echo "${_dll}:"; ntldd -R ${_dll} | grep -E "(msvcrt|ucrtbase)"
```

**Comment by Biswa96** [comment]
`ntldd -R ${_dll}` command does not give full picture after grep. For example, here is the output after grep-ing msvcrt with 5 line context.

```
$ ntldd -R /ucrt64/bin/avformat-60.dll | grep -C 5 msvcrt
        libbluray-2.dll => C:\msys64\ucrt64\bin\libbluray-2.dll (0x000001eeee7b0000)
         ADVAPI32.dll => C:\Windows\SYSTEM32\ADVAPI32.dll (0x000001eeeec10000)
          msvcrt.dll => C:\Windows\SYSTEM32\msvcrt.dll (0x000001eeeecc0000)
          ntdll.dll => C:\Windows\SYSTEM32\ntdll.dll (0x000001eeeed60000)
          KERNELBASE.dll => C:\Windows\SYSTEM32\KERNELBASE.dll (0x000001eeeed60000)
           ext-ms-win-advapi32-registry-l1-1-0.dll => not found
           ext-ms-win-advapi32-registry-l1-1-1.dll => not found
           ext-ms-win-kernel32-appcompat-l1-1-0.dll => not found
```

The msvcrt comes from advapi32.dll.

**Comment by Biswa96** [comment]
@hkinke I am not familiar with llvm and have no idea what is going with your sample project. I have asked about this thread in mingw-w64 IRC and here is the reply.

> well, I can only say that x/5i free is probably printing one of the many symbols that is named "free", in this case it happens to pick the one in msvcrt (which gdb probably found in its DLL export table)
> if you actually break at the free(p) call and do si multiple times you'll see that it correctly calls the ucrtbase free, not msvcrt
> which means that example does not help

If you can use programs like https://github.com/lucasg/dependencies it shows free() is linked with ucrtbase.dll.

**Comment by hkinke** [comment]
Thank you. I close the issue for now. In meantime, I will do further investigation. I believe that other dependencies of LLVM load msvcrt.dll. When LLVM JIT look dynamically `malloc`  in symbol tables, it finds `malloc` coming from wrong dynamic library. Which creates discrepancy between `free` and `malloc`. When I compile my primary project on Linux, it works fine.

**Comment by hkinke** [comment]
Actually, `free` calls `__imp_malloc` and `malloc` from `LLVMJIT` call `ucrtbase!malloc`. I am now sure that the problem comes from `Windows` and `LLVM` because `Windows` allows many version of `malloc` at same times. Each `DLL` can comes with own pair of `malloc` and `free`. The transition from `msvcrt.dll` to `ucrtbase.dll` will not be easy without `Windows` itself uses exclusively `ucrtbase.dll`.

```gdb
(gdb) b 123
Breakpoint 1 at 0x140001fc6: file C:/dev/testllvm/testllvm/main.cpp, line 123.
(gdb) run
Starting program: C:\dev\testllvm\build\main.exe
1 1 2 3

Thread 1 hit Breakpoint 1, main (argc=1, argv=0x68d7e0) at C:/dev/testllvm/testllvm/main.cpp:123
123         free(p);
(gdb) x/5i $rip
=> 0x7ff78f6c1fc6 <main(int, char const**)+2600>:       mov    0x2a8(%rbp),%rax
   0x7ff78f6c1fcd <main(int, char const**)+2607>:       mov    %rax,%rcx
   0x7ff78f6c1fd0 <main(int, char const**)+2610>:       call   0x7ff78f6d85b8 <free>
   0x7ff78f6c1fd5 <main(int, char const**)+2615>:       mov    $0x0,%ebx
   0x7ff78f6c1fda <main(int, char const**)+2620>:       lea    -0x20(%rbp),%rax
(gdb) x/5i 0x7ff78f6d85b8
   0x7ff78f6d85b8 <free>:       jmp    *0x1e51d0a(%rip)        # 0x7ff79152a2c8 <__imp_free>
   0x7ff78f6d85be <free+6>:     nop
   0x7ff78f6d85bf <free+7>:     nop
   0x7ff78f6d85c0 <malloc>:     jmp    *0x1e51d0a(%rip)        # 0x7ff79152a2d0 <__imp_malloc>
   0x7ff78f6d85c6 <malloc+6>:   nop
(gdb) x/5i myalloc
   0x620000:    sub    $0x28,%rsp
   0x620004:    movabs $0x7ffa1e350060,%rax
   0x62000e:    call   *%rax
   0x620010:    nop
   0x620011:    add    $0x28,%rsp
(gdb) x/5i 0x7ffa1e350060
   0x7ffa1e350060 <ucrtbase!malloc>:    jmp    0x7ffa1e350070 <ucrtbase!_malloc_base>
   0x7ffa1e350065 <ucrtbase!malloc+5>:  int3
   0x7ffa1e350066 <ucrtbase!malloc+6>:  int3
   0x7ffa1e350067 <ucrtbase!malloc+7>:  int3
   0x7ffa1e350068 <ucrtbase!malloc+8>:  jno    0x7ffa1e350012 <ucrtbase!_realloc_base+34>
(gdb) x/5i 0x7ffa1e350070
   0x7ffa1e350070 <ucrtbase!_malloc_base>:      sub    $0x28,%rsp
   0x7ffa1e350074 <ucrtbase!_malloc_base+4>:    cmp    $0xffffffffffffffe0,%rcx
   0x7ffa1e350078 <ucrtbase!_malloc_base+8>:    ja     0x7ffa1e39b0aa <ucrtbase!exp2f+25018>
   0x7ffa1e35007e <ucrtbase!_malloc_base+14>:   mov    %rbx,0x30(%rsp)
   0x7ffa1e350083 <ucrtbase!_malloc_base+19>:   test   %rcx,%rcx
(gdb)
```

After changing the application logic by forcing `LLVMJIT` to use given pair of `free` and `malloc` (the same with main application). I have this `gdb` output

```gdb
(gdb) b 123
Breakpoint 1 at 0x140001fc6: file C:/dev/testllvm/testllvm/main.cpp, line 123.
(gdb) run
Starting program: C:\dev\testllvm\build\main.exe
[New Thread 233408.0x1417a0]
[New Thread 233408.0x5a044]
[New Thread 233408.0x141774]
1 1 2 3

Thread 1 hit Breakpoint 1, main (argc=1, argv=0x71d310) at C:/dev/testllvm/testllvm/main.cpp:123
123         free(p);
(gdb) x/5i $rip
=> 0x7ff75cc61fc6 <main(int, char const**)+2600>:       mov    0x2a8(%rbp),%rax
   0x7ff75cc61fcd <main(int, char const**)+2607>:       mov    %rax,%rcx
   0x7ff75cc61fd0 <main(int, char const**)+2610>:       call   0x7ff75cc785b8 <free>
   0x7ff75cc61fd5 <main(int, char const**)+2615>:       mov    $0x0,%ebx
   0x7ff75cc61fda <main(int, char const**)+2620>:       lea    -0x20(%rbp),%rax
(gdb) x/5i 0x7ff75cc785b8
   0x7ff75cc785b8 <free>:       jmp    *0x1e56d0a(%rip)        # 0x7ff75eacf2c8 <__imp_free>
   0x7ff75cc785be <free+6>:     nop
   0x7ff75cc785bf <free+7>:     nop
   0x7ff75cc785c0 <malloc>:     jmp    *0x1e56d0a(%rip)        # 0x7ff75eacf2d0 <__imp_malloc>
   0x7ff75cc785c6 <malloc+6>:   nop
(gdb) x/5i myalloc
   0x630000:    sub    $0x28,%rsp
   0x630004:    movabs $0x7ff75cc785c0,%rax
   0x63000e:    call   *%rax
   0x630010:    nop
   0x630011:    add    $0x28,%rsp
(gdb) x/5i 0x7ff75cc785c0
   0x7ff75cc785c0 <malloc>:     jmp    *0x1e56d0a(%rip)        # 0x7ff75eacf2d0 <__imp_malloc>
   0x7ff75cc785c6 <malloc+6>:   nop
   0x7ff75cc785c7 <malloc+7>:   nop
   0x7ff75cc785c8 <realloc>:    jmp    *0x1e56d0a(%rip)        # 0x7ff75eacf2d8 <__imp_realloc>
   0x7ff75cc785ce <realloc+6>:  nop
```
We can see now that both main application and `LLVMJIT` use the same pair of `malloc` and `free`.

**Thank you for your support** even it was in fact an issue with `Windows` and `LLVMJIT`.
