### ISSUE TITLE
GnuCobol: Libcjson.dll was not found when run cobc from 26/12/2023

### ISSUE THREAD

**Issue by hxtho** [msys2/MINGW-packages#19556]
### Description / Steps to reproduce the issue

Run Cobc or Cobenv.cmd and the system produce the issue "libcjson.dll was not found".
Maybe because of new update of cjson package. https://github.com/DaveGamble/cJSON

### Expected behavior

Cobc.exe / Cobenv.cmd works as usual. 

### Actual behavior

Issue / Error "libcjson.dll was not found"

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 10 Pro

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
Where could we find those programs?

**Comment by lazka** [comment]
I think it's because the gnucobol package version is smaller then a previous one and thus never got rebuilt for the libcjson rebuild

**Comment by GitMensch** [comment]
Note: the same issue occurred with libintl-8.dll, likely the rebuild will fix both.

**Comment by MehdiChinoune** [comment]
> Note: the same issue occurred with libintl-8.dll, likely the rebuild will fix both.

Not a rebuild, the update to 3.2 didn't make it because It's less than 3.2_rc2 by semantic versioning.

**Comment by GitMensch** [comment]
As it contains patches to 3.2.1 and there is no official 3.2.1, maybe just name the version that way?
Following RC versions should likely then be named different...

**Comment by MehdiChinoune** [comment]
> As it contains patches to 3.2.1 and there is no official 3.2.1, maybe just name the version that way?
> Following RC versions should likely then be named different...

`-` should be just removed not replaced by `_`. We do that in many packages.

**Comment by GitMensch** [comment]
Then the PR should be adjusted to adjust the version string, just as it did (revert), but without the replace.
