### ISSUE TITLE
[mingw-w64-clang-x86_64-clang-analyzer]: 17.0.6-5. Missing analyzer components (e.g. scan-build)

### ISSUE THREAD

**Issue by bradh352** [msys2/MINGW-packages#19564]
### Description / Steps to reproduce the issue

pacman -S mingw-w64-clang-x86_64-clang-analyzer

I'm not sure what version this broke, but I can see in google results where the expected files existed in this package.

### Expected behavior

package should contain files for /clang64/bin/  like scan-build, scan-build-py, analyze-build

### Actual behavior

The only file contained in the package is /clang64/share/licenses/clang-analyzer/LICENSE

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
Started with 17.0.6
I think I messed something.

**Comment by MehdiChinoune** [comment]
I have pushed a fix. Shuld be available in coming days.

**Comment by bradh352** [comment]
Just saw the package hit, that said, it doesn't appear to actually "work":
```
bhouse@BRADHOUSED956 CLANG64 ~/c-ares/build
$ scan-build -v --use-cc /clang64/bin/x86_64-w64-mingw32-cc --use-c++ /clang64/bin/x86_64-w64-mingw32-c++ cmake ..
scan-build: Using '/clang64/bin/clang' for static analysis
scan-build: Emitting reports for this run to '/tmp/scan-build-2023-12-28-183429-5231-1'.
-- Building for: Ninja
-- The C compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/msys64/clang64/libexec/ccc-analyzer
-- Check for working C compiler: C:/msys64/clang64/libexec/ccc-analyzer - broken
CMake Error at C:/msys64/clang64/share/cmake/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "C:/msys64/clang64/libexec/ccc-analyzer"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: 'C:/msys64/home/bhouse/c-ares/build/CMakeFiles/CMakeScratch/TryCompile-04ftt7'

    Run Build Command(s): C:/msys64/clang64/bin/ninja.exe -v cmTC_94a61

    CreateProcess failed. Command attempted:
    "C:\msys64\clang64\libexec\ccc-analyzer    -o CMakeFiles\cmTC_94a61.dir\testCCompiler.c.obj -c C:\msys64\home\bhouse\c-ares\build\CMakeFiles\CMakeScratch\TryCompile-04ftt7\testCCompiler.c"
    ninja: fatal: CreateProcess: %1 is not a valid Win32 application.






  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:15 (PROJECT)


-- Configuring incomplete, errors occurred!
scan-build: Analysis run complete.
scan-build: Removing directory '/tmp/scan-build-2023-12-28-183429-5231-1' because it contains no reports.
scan-build: No bugs found.
```

In case this is a ninja issue, I also tried `-G "MSYS Makefiles"`, and it doesn't attempt to test for a working compiler then fails the checks to detect functionality so nothing compiles.

Any idea what else might be required on Windows?  I also tried scan-build-py, and not specifying the --use-cc or --use-c++ options.

**Comment by bradh352** [comment]
Interesting, executing autotools with:
```
CCC_CC=/clang64/bin/x86_64-w64-mingw32-cc CCC_CXX=/clang64/bin/x86_64-w64-mingw32-c++ scan-build -v ../configure
```
works.  Must be something with the scan-build and scan-build-py wrapper script and interaction with cmake on Windows.
