### ISSUE TITLE
mpv is broken with yt-dlp

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MINGW-packages#19568]
### Description / Steps to reproduce the issue

Try to play youtube url with both yt-dlp and mpv, like this
` mpv https://www.youtube.com/watch?v=LseOJEYcC4I`

### Expected behavior

It should play

### Actual behavior

we get the following error

<details><summary>Toggle me!</summary>

[error.txt](https://github.com/msys2/MINGW-packages/files/13782020/error.txt)

</details>

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I can reproduce the issue in my system. I followed this article to run mpv with yt-dlp https://www.funkyspacemonkey.com/replace-youtube-dl-with-yt-dlp-how-to-make-mpv-work-with-yt-dlp but it also shows same error.

**Comment by LABPBS** [comment]
try with ``mpv ytdl://https://www.youtube.com/watch?v=LseOJEYcC4I`` or alternatively ``mpv ytdl://LseOJEYcC4I`` for youtube videos

i couldnt reproduce, however my mpv is custom built with a personal patch

**Comment by Kreijstal** [comment]
> try with `mpv ytdl://https://www.youtube.com/watch?v=LseOJEYcC4I` or alternatively `mpv ytdl://LseOJEYcC4I` for youtube videos
> 
> i couldnt reproduce, however my mpv is custom built with a personal patch

```
No protocol handler found to open URL ytdl://https://www.youtube.com/watch?v=hzGmbwS_Drs
The protocol is either unsupported, or was disabled at compile-time.
```

**Comment by Kreijstal** [comment]
fixed https://github.com/mpv-player/mpv/issues/13775
