### ISSUE TITLE
MPFR: mpfr_sub_si may produce wrong result on MINGW64

### ISSUE THREAD

**Issue by pmor13** [msys2/MINGW-packages#19565]
### Description / Steps to reproduce the issue

MRE:
```
#include <mpfr.h>
#include <stdio.h>

int main(void)
{
	mpfr_t x;
	mpfr_t r;

	mpfr_init(x);
	mpfr_init(r);
	mpfr_set_d(x, 0.0, MPFR_RNDN);
	mpfr_sub_si(r, x, (long int)2155000000, MPFR_RNDN);
	mpfr_printf("x %RNa %RNf\n", x, x);
	mpfr_printf("r %RNa %RNf\n", r, r);
}
```
Invocation on `MINGW64`:
```
MINGW64 /d
$ gcc t1.c -std=c11 -pedantic -Wall -lmpfr -lgmp && ./a
x 0x0p+0 0.000000
r 0x7.f8d4f4p+28 2139967296.000000
```
Invocation on `UCRT64`:
```
UCRT64 /d
$ gcc t1.c -std=c11 -pedantic -Wall -lmpfr -lgmp && ./a
x 0x0p+0 0.000000
r -0x8.072b0cp+28 -2155000000.000000
```
It seems, the results on `UCRT64` are correct (because on `UCRT64` my test passed).

### Expected behavior

The same and correct results between MINGW64 and UCRT64.

### Actual behavior

The results on MINGW64 differ from results on UCRT64.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by pmor13** [comment]
This issue seems invalid due to difference `long` size: 4 (MINGW64) vs. 8 (UCRT64).

**Comment by HolyBlackCat** [comment]
@pmor13 I believe it's `4` on both.

**Comment by Biswa96** [comment]
> This issue seems invalid due to different size of `long`: 4 (MINGW64) vs. 8 (UCRT64).

Wrong. Size of `long` is always 4 for all Windows platform and for all MSYSTEMs. Try to run the following command in those shell environments. The output will be same.

```
$ gcc -dM -E - < /dev/null | grep __SIZEOF_LONG__
#define __SIZEOF_LONG__ 4
```

**Comment by Biswa96** [comment]
> The results on MINGW64 differ from results on UCRT64.

I get the same result in MINGW64 and in UCRT64.

**Comment by pmor13** [comment]
@Biswa96 
> Wrong. Size of long is always 4 for all Windows platform and for all MSYSTEMs. 
Wrong. In my case size of long is always 4 on MINGW64 and 8 an UCRT64:
```
MINGW64 /d
$ echo "int main(void){return sizeof(long);}" | gcc -xc - && ./a ; echo $?
4
UCRT64 /d
$ echo "int main(void){return sizeof(long);}" | gcc -xc - && ./a ; echo $?
8
MINGW64 /d
$ gcc -dM -E - < /dev/null | grep __SIZEOF_LONG__
#define __SIZEOF_LONG__ 4
UCRT64 /d
$ gcc -dM -E - < /dev/null | grep __SIZEOF_LONG__
#define __SIZEOF_LONG__ 8
```

**Comment by HolyBlackCat** [comment]
@pmor13 Can you check `which g++` and `which gcc` please? Perhaps you don't have UCRT64 GCC installed, and it uses MSYS GCC?

**Comment by pmor13** [comment]
@HolyBlackCat 
```
MINGW64 /d
$ which gcc
/mingw64/bin/gcc

MINGW64 /d
$ which g++
/mingw64/bin/g++

UCRT64 /d
$ which g++
/usr/bin/g++

UCRT64 /d
$ which gcc
/usr/bin/gcc
```

**Comment by Biswa96** [comment]
Please install gcc in ucrt64 environment and try again.

**Comment by pmor13** [comment]
@Biswa96 How to correctly install gcc in ucrt64 environment? Now there is warning:
```
UCRT64 /d
$ pacman -S gcc
warning: gcc-13.2.0-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) gcc-13.2.0-2

Total Installed Size:  177.43 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                     [#############] 100%
(1/1) checking package integrity                   [#############] 100%
(1/1) loading package files                        [#############] 100%
(1/1) checking for file conflicts                  [#############] 100%
(1/1) checking available disk space                [#############] 100%
:: Processing package changes...
(1/1) reinstalling gcc                             [#############] 100%
:: Running post-transaction hooks...
(1/1) Updating the info directory file...

UCRT64 /d
$ gcc -dM -E - < /dev/null | grep __SIZEOF_LONG__
#define __SIZEOF_LONG__ 8
```

**Comment by Biswa96** [comment]
This command may help `pacman -S mingw-w64-ucrt-x86_64-gcc`

All the steps are documented here https://www.msys2.org/

**Comment by pmor13** [comment]
Thanks! Now gcc is OK:
