### ISSUE TITLE
[mingw-w64-efl] update to 1.27.0

### ISSUE THREAD

**Issue by ghost** [msys2/MINGW-packages#19591]
### Package name

mingw-w64-efl

### New version number

1.27.0

### Other information that may be useful

MSYS2 is still stuck at 1.25.0:

https://packages.msys2.org/base/mingw-w64-efl

1.27.0 has been released recently: https://www.enlightenment.org/news/2023-12-23-efl-1.27.0

### Are you willing to submit a PR?

I don't have the needed skills to do so! I'm sorry!

**Comment by MehdiChinoune** [comment]
fixed by https://github.com/msys2/MINGW-packages/commit/216dbaf8fa284663cd3902a0306147314371b54c
