### ISSUE TITLE
GLFW 3.3.9 : invalid pkgconfig file 

### ISSUE THREAD

**Issue by oxillo** [msys2/MINGW-packages#19599]
### Description / Steps to reproduce the issue

GLFW 3.3.9 has fixed an issue on pkgconfig file generation when generating the shared version of the library.

Now `pkgconf --libs glfw3` returns `-l glfw3dll` instead of `-lglfw3` which breaks existing build scripts.

### Expected behavior

I would expect 2 pkgconfig files :
  - 1 for static version `glfw3.pc` that would return `-lglfw3`
  - 1 for shared version `glfw3-shared.pc` that would return `-lglfw3dll` (or -lglfw3.dll to keep consistency with the exisiting MSYS2 patch)

### Actual behavior

Now `pkgconf --libs glfw3` returns `-l glfw3dll` instead of `-lglfw3` which breaks existing build scripts.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

Yes

**Comment by MehdiChinoune** [comment]
already fixed in https://github.com/msys2/MINGW-packages/commit/62434524fe934f1d72f66d17ca5163bc4c42a818

**Comment by oxillo** [comment]
I do not think this is the same thing. 
With the patch above, you are always forcing the user to always use the static version for linkage.
GLFW 3.3.9 fixed an issue for generating an .pc file for dynamic linking but it is generating the same pkgconf filename for both version.
As the MSYS2 packages() installs the shared version after the static version, the static 'glw3.pc' is overwritten by the shared version!
The problem has been reported to GLFW team glfw/glfw#2459

**Comment by Biswa96** [comment]
> With the patch above, you are always forcing the user to always use the static version for linkage.

It does not force static linking. Here is a glfw3.pc after the aforementioned commit.

```ini
prefix=/ucrt64
exec_prefix=${prefix}
includedir=/ucrt64/include
libdir=/ucrt64/lib

Name: GLFW
Description: A multi-platform library for OpenGL, window and input
Version: 3.3.9
URL: https://www.glfw.org/
Requires.private:
Libs: -L${libdir} -lglfw3
Libs.private:  -lgdi32
Cflags: -I${includedir}
```
