### ISSUE TITLE
MingW32 13.2.0 - Hello World causes fatal crash

### ISSUE THREAD

**Issue by ThunderPerfectWitchcraft** [msys2/MINGW-packages#19593]
### Description / Steps to reproduce the issue

```cpp
#include <iostream>

int WinMain()
{ 
std::cout << "Hello World" << std::endl;
return 0;
}
```

### Expected behavior

A binary that gives out "Hello World!"

### Actual behavior

Program crashes without any output

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Problems exist on Windows and Wine

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
I can not reproduce the issue in my system. Also, a simple program like that should not crash anyway. Please check your system.
