### ISSUE TITLE
[clang64] libaec import libraries are empty

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#19604]
### Description / Steps to reproduce the issue

- Try to link to libsz or libaec (of course by calling one of their fuctions)
- linking fails
- You could test building HDF5 (ninja hdf5-shared)

```
$ nm /clang64/lib/libsz.dll.a

libsz.dll:
00000000 i .idata$2
00000000 ? .idata$4
00000000 ? .idata$5
00000000 i .idata$6
00000000 I __IMPORT_DESCRIPTOR_libsz
         U __NULL_IMPORT_DESCRIPTOR
         U ⌂libsz_NULL_THUNK_DATA

libsz.dll:
00000000 I __NULL_IMPORT_DESCRIPTOR

libsz.dll:
00000000 I ⌂libsz_NULL_THUNK_DATA
$ nm /clang64/lib/libaec.dll.a

libaec.dll:
00000000 i .idata$2
00000000 ? .idata$4
00000000 ? .idata$5
00000000 i .idata$6
00000000 I __IMPORT_DESCRIPTOR_libaec
         U __NULL_IMPORT_DESCRIPTOR
         U ⌂libaec_NULL_THUNK_DATA

libaec.dll:
00000000 I __NULL_IMPORT_DESCRIPTOR

libaec.dll:
00000000 I ⌂libaec_NULL_THUNK_DATA
```

### Expected behavior

To link successfully

### Actual behavior

Fails to link

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Maybe!

**Comment by MehdiChinoune** [comment]
It looks like visibility is broken https://github.com/MathisRosenhauer/libaec/blob/v1.1.2/include/libaec.h.in#L52
@mstorsjo

**Comment by Biswa96** [comment]
visibility should not be used for Windows platform, I guess. dllexport/dllimport would be right attribute for that.

**Comment by MehdiChinoune** [comment]
The visibility wasn't enabled for MINGW https://github.com/MathisRosenhauer/libaec/blob/v1.1.2/src/CMakeLists.txt#L62

**Comment by MehdiChinoune** [comment]
Fixed by https://github.com/msys2/MINGW-packages/commit/c3c322ae5f39860aa124fcfe93b8d9411287bc2e
