### ISSUE TITLE
node.exe from mingw-w64-x86_64-nodejs not work in mingw64 env

### ISSUE THREAD

**Issue by RocketMaDev** [msys2/MINGW-packages#19602]
### Description / Steps to reproduce the issue

1. `pacman -S mingw-w64-x86_64-nodejs`
2. `node -v`

### Expected behavior

display node's version

### Actual behavior

no output
<img width="289" alt="屏幕截图 2024-01-02 223253" src="https://github.com/msys2/MINGW-packages/assets/48864431/1521a301-26e8-4307-8024-165008d44ed1">

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Kreijstal** [comment]
which windows version, which shell?

**Comment by raedrizqie** [comment]
i cannot reproduce this error

**Comment by RocketMaDev** [comment]
but i truly experience this exception
<img width="1280" alt="屏幕截图 2024-01-03 185600" src="https://github.com/msys2/MINGW-packages/assets/48864431/cb2ace8d-9bda-4f0d-a171-afffc5bf5079">
more details is attatched

**Comment by raedrizqie** [comment]
please run `pacman -Syuu` first
then update your nodejs package, `pacman -S mingw-w64-x86_64-nodejs`

**Comment by RocketMaDev** [comment]
i've updated all packages, but don't work

**Comment by RocketMaDev** [comment]
I've tested ucrt64 and the nodejs in ucrt64 works perfectly.
