### ISSUE TITLE
Add intel-oneapi-mkl

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#19618]
### Package name

intel-oneapi-mkl

### Brief description of package

Please add like in archlinux: https://archlinux.org/packages/extra/x86_64/intel-oneapi-mkl/

PKGBUILD file: 
https://gitlab.archlinux.org/archlinux/packaging/packages/intel-oneapi-mkl/-/blob/main/PKGBUILD?ref_type=heads

or like in python: https://pypi.org/project/mkl/2024.0.0/#files

### URL for package's homepage

https://software.intel.com/content/www/us/en/develop/tools/oneapi.html

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Probably not too advanced

**Comment by Biswa96** [comment]
The ArchLinux page shows "Installed Size: 3.2 GB". Is it possible to compile in CI's time limit?

**Comment by MehdiChinoune** [comment]
They repackaged a proprietary software. Something we couldn't do because Intel MKL on Windows is compatible with MSVC not mingw/gcc.

**Comment by 3rav** [comment]
In my case, I need several .dll libraries and header files to compile the CalculiX program and to prepare a package for mingw, the .dll libraries include the PARDISO solver.

It would be nice if these ready-made libraries were available in the msys2.ming repo

Path to .dll library: `mkl/2023.0.0/redist/intel64`

**Comment by MehdiChinoune** [comment]
It's not compatible with MinGW-w64 and It's open-source so we could build it.

**Comment by 3rav** [comment]
I don't understand something, these .dll libraries work locally on my computer and the package is available in the archlinux and python repo

**Comment by ImperatorS79** [comment]
> I don't understand something, these .dll libraries work locally on my computer (msys2/mingw) and the package is available in the archlinux and python repo

I tried to use Intel MKL using mingw's gcc one or two years ago and I had multiple problems with the following symbols missing:

```
__GSHandlerCheck()
__security_check_cookie(unsigned *p)
unsigned *__security_cookie
```

While defining those functions/variables somewhere in a .c made my project compiles, the pardiso solver crashed... So I wonder how you managed to compile CalculiX.

**Comment by 3rav** [comment]
> > I don't understand something, these .dll libraries work locally on my computer (msys2/mingw) and the package is available in the archlinux and python repo
> 
> I tried to use Intel MKL using mingw's gcc one or two years ago and I had multiple problems with the following symbols missing:
> 
> ```
> __GSHandlerCheck()
> __security_check_cookie(unsigned *p)
> unsigned *__security_cookie
> ```
> 
> While defining those functions/variables somewhere in a .c made my project compiles, the pardiso solver crashed... So I wonder how you managed to compile CalculiX.

Send me your Makefile in a private message and I will try to correct it if necessary

**Comment by 3rav** [comment]
@MehdiChinoune
1. Is there any way to install these python packages in msys2/mingw?
2. May I just download such a package (python: https://pypi.org/project/mkl/2024.0.0/#files), unpack it and use its .dll libraries and .h in a new mingw package?

**Comment by MehdiChinoune** [comment]
In general we don't repackage proprietary software with few exceptions when an open-source project requires hardly that software. That was allowed with android-tools because mingw-w64 has no implementation for ATL/MFC.

**Comment by 3rav** [comment]
CalculiX FEA program can use this solvers:
spooles (quite old, unstable and very slow)
PARDISO (Intel or Panua-Pardiso)
PaStiX (currently, not the basic version, but a modified one)

Intel PARDISO (from oneAPI/oneMKL),  it is modern, the most stable, and almost the fastest (https://calculix.discourse.group/t/pastix-vs-pardiso-performance/177/6).

If it technically works, please grant an exception for the use of these .dll files

License freeware under ISSL, from: https://en.wikipedia.org/wiki/Math_Kernel_Library
ISSL: https://software.intel.com/sites/landingpage/pintool/intel-simplified-software-license.txt

**Comment by ImperatorS79** [comment]
> > > I don't understand something, these .dll libraries work locally on my computer (msys2/mingw) and the package is available in the archlinux and python repo
> > 
> > 
> > I tried to use Intel MKL using mingw's gcc one or two years ago and I had multiple problems with the following symbols missing:
> > ```
> > __GSHandlerCheck()
> > __security_check_cookie(unsigned *p)
> > unsigned *__security_cookie
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > While defining those functions/variables somewhere in a .c made my project compiles, the pardiso solver crashed... So I wonder how you managed to compile CalculiX.
> 
> Send me your Makefile in a private message and I will try to correct it if necessary

I don't know how to send a private message via github. I am using the following .cmake to find and link the mkl:
https://github.com/arrayfire/arrayfire/blob/master/CMakeModules/FindAF_MKL.cmake

**Comment by 3rav** [comment]
> In general we don't repackage proprietary software with few exceptions when an open-source project requires hardly that software. That was allowed with android-tools because mingw-w64 has no implementation for ATL/MFC.

I have an almost working package, unfortunately I have a rather strange error when I copy the .exe and .dll files from the pkg folder (from test), when I run the program I get the error 0xc000007b related to the libiomp5md.dll library, however, when I copy this library from the src location, everything works fine.

Any suggestions?

**Comment by 3rav** [comment]
> Intel PARDISO (from oneAPI/oneMKL), it is modern, the most stable, and almost the fastest (https://calculix.discourse.group/t/pastix-vs-pardiso-performance/177/6 or https://mecway.com/forum/discussion/836/mecway-pc-benchmarks).

Recipe: https://github.com/msys2/MINGW-packages/pull/19673#issue-2069046008

**Comment by MehdiChinoune** [comment]
As I said It's not possible because It's ABI incompatible proprietary software.
