### ISSUE TITLE
scalapack-targets.cmake path to libscalapack.a or libscalapack.dll

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#19619]
### Description / Steps to reproduce the issue

I try to build MFEM packages with MUMPS but I have this error:

```
-- MUMPS: looking for required package: ScaLAPACK
CMake Error at C:/msys64/mingw64/lib/cmake/scalapack-2.1.0/scalapack-targets.cmake:84 (message):
  The imported target "scalapack" references the file
     "C:/msys64/mingw64/Testing/libscalapack.dll"
  but this file does not exist.  Possible reasons include:
  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "C:/msys64/mingw64/lib/cmake/scalapack-2.1.0/scalapack-targets.cmake"
  but not all the files it references.
```

This is strange: `C:/msys64/mingw64/Testing/libscalapack.dll`

### Expected behavior

`C:/msys64/mingw64/bin/libscalapack.dll`

![image](https://github.com/msys2/MINGW-packages/assets/24394573/209261c4-1605-4681-8978-c26b98d368a4)

### Actual behavior

`C:/msys64/mingw64/Testing/libscalapack.dll`

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Comment by 3rav** [comment]
> Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

Thank you, yes please

**Comment by Biswa96** [comment]
Did the packages work for your case? Those can be downloaded from CI artifacts.

**Comment by 3rav** [comment]
Now is OK
