### ISSUE TITLE
Kicad does not find ngspice shared library

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MINGW-packages#19629]
### Description / Steps to reproduce the issue

install ngspice and kicad with pacman or pacboy.
Open kicad,
create new project. Put some spice elements in schematic view.
[3-2024-01-05_145924.zip](https://github.com/msys2/MINGW-packages/files/13844019/3-2024-01-05_145924.zip)
Try to use simulation, kicad will not find the ngspice shared library

![image](https://github.com/msys2/MINGW-packages/assets/2415206/3994d01c-487d-4c4b-97b6-21c56ef25964)

### Expected behavior

Simulation should work, or it should find ngspice shared library

### Actual behavior

Simulation library is not found

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-6.3-9600

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

I don't know what the problem is

**Comment by Biswa96** [comment]
> Open kicad,
> create new project. Put some spice elements in schematic view.

Please explain those steps and how the attached file is used after those steps.

**Comment by Kreijstal** [comment]
> > Open kicad,
> > create new project. Put some spice elements in schematic view.
> 
> Please explain those steps and how the attached file is used after those steps.

it is an example file of me creating some components

**Comment by Biswa96** [comment]
Do you mean to open the project/directory in kicad somehow?

**Comment by Kreijstal** [comment]
I think the zip file is a misunderstanding, it is just an example in case tester was too lazy to create anything in schematics interface, it is unrelated to the bug, just click on 
![image](https://github.com/msys2/MINGW-packages/assets/2415206/fd380185-7fa6-4c59-a58e-f495c0cc8795)
 
and you receive an error, when kicad is installed through pacman, 
steps are
- create new project
- open schematic
- click button
error

tried with a recent installation of msys2 on another computer running windows 10, I can reproduce

**Comment by Kreijstal** [comment]
I installed kicad through scoop, to see what is wrong..

![image](https://github.com/msys2/MINGW-packages/assets/2415206/d12ac57f-69d5-48e5-9676-b486263d0819)

scoop's kicad provides ngspice.dll which msys does not seem to provide.

**Comment by Kreijstal** [comment]
okay, so I did something weird, I copy this ngspice.dll into /mingw64/bin directory, and it did not error anymore, but it crashed with a segfault, so... there is something going on. :)

**Comment by Kreijstal** [comment]
There is ngspice [documentation ](https://ngspice.sourceforge.io/shared.html) about  [ngspice.dll](https://sourceforge.net/projects/ngspice/files/ng-spice-rework/42/ngspice-42_dll_64.7z/download)

Okay, I copied libngspice0.dll into ngspice.dll, and it worked!

**Comment by Biswa96** [comment]
Thanks for the info. I can reproduce the issue in my setup. kicad is probably loading ngspice shared library with LoadLibrary and can not find it.

```
eeschema/sim/ngspice.cpp:        m_dll.Load( wxDynamicLibrary::CanonicalizeName( "ngspice" ) );
```

**Comment by Kreijstal** [comment]
I guess I would see what is the most common naming notation, and either make a copy of ngspice.dll for kicad or patch kicad so it looks for either libngspice0.dll or ngspice.dll or upstream?

**Comment by MehdiChinoune** [comment]
https://gitlab.com/kicad/code/kicad/-/blob/7.0.10/cmake/Findngspice.cmake?ref_type=tags#L105
Is valid only when using `MSYS Makefiles`, probably should changed to `if (MINGW)`.
https://gitlab.com/kicad/code/kicad/-/blob/7.0.10/eeschema/CMakeLists.txt#L19

**Comment by Kreijstal** [comment]
I guess it is a problem wit wxWidgets name resolution?

**Comment by Biswa96** [comment]
> I guess it is a problem wit wxWidgets name resolution?

Yeah, something like that. The DLL name is set by the CMake file. MehdiChinoune's suggestion may solve the issue.

**Comment by MehdiChinoune** [comment]
@Kreijstal I have pushed an update for kicad to 7.0.10, It includes a fix for your issue.
Could update it from staging repo https://packages.msys2.org/queue and confirm.

**Comment by Biswa96** [comment]
I have downloaded the kicad 7.0.10 package from staging and verified that 02cf7e7dc77ca15758ec83e6e7ea3fc4672995a8 commit fixes the kicad issue. Thank you.

**Comment by Biswa96** [comment]
The new kicad package has been added in pacman repository. Please update the packages with `pacman -Syu` command.

**Comment by Kreijstal** [comment]
> @Kreijstal I have pushed an update for kicad to 7.0.10, It includes a fix for your issue. Could update it from staging repo https://packages.msys2.org/queue and confirm.

Yeah it fixed it thank you
