### ISSUE TITLE
Cannot load ONNX models using dnn

### ISSUE THREAD

**Issue by joda01** [msys2/MINGW-packages#19677]
### Description / Steps to reproduce the issue

When attempting to load an ONNX model using dnn, the following exception is thrown:

```
"OpenCV(4.9.0) C:/M/B/src/opencv-4.9.0/modules/dnn/src/onnx/onnx_importer.cpp:4097: error: (-2:Unspecified error) DNN/ONNX: Build OpenCV with Protobuf to import ONNX models in function 'readNetFromONNX'\n"
```
It seems that opencv was built without protobuf support.
(see https://github.com/opencv/opencv/blob/9691a2dccf63f527122dc515b0a082d33e088572/modules/dnn/src/onnx/onnx_importer.cpp#L23)

Code snipet to reproduce:

```
try{
   cv::dnn::Net mNet {cv::dnn::readNet(onnxNetPath)}
 } catch(const std::exception &ex) {
   std::string what = ex.what();
   std::cout << what << std::endl;
}
```

### Expected behavior

No excpetion is thrown when loadig model.

### Actual behavior

Exception is thrown when model is loading.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Thank you for reporting the issue. Would you like to provide a full example code and required files to reproduce the issue?

**Comment by joda01** [comment]
@Biswa96 Thank you for your quick response. Of course. Will the following code be enough for you?

```c++
#include <opencv2/core/mat.hpp>
#include <opencv2/dnn.hpp>
#include <opencv2/dnn/all_layers.hpp>
#include <opencv2/opencv.hpp>
#include <string>
#include <iostream>

class ObjectDetector
{
public:
  ObjectDetector(const std::string &onnxNet):
    mNet{cv::dnn::readNet(onnxNet)}{}

private:
  cv::dnn::Net mNet;
};


int main(int argc, char **argv){
  try {
    ObjectDetector detector("nucleus_detection_ex_vivo_v1.onnx");
  } catch(const std::exception &ex) {
   // Throws exception: "OpenCV(4.9.0) C:/M/B/src/opencv-4.9.0/modules/dnn/src/onnx/onnx_importer.cpp:4097: error: (-2:Unspecified error) DNN/ONNX: Build OpenCV with Protobuf to import ONNX models in function 'readNetFromONNX'\n"
   std::string what = ex.what();
   std::cout << what << std::endl;
  }

  return 0;
}

```

ONNX model can be downloaded here:
https://github.com/joda01/imagec/tree/main/models

**Comment by Biswa96** [comment]
It seems that the protobuf module in opencv requires C++ 17 or above, see https://github.com/opencv/opencv/blob/4.9.0/cmake/OpenCVFindProtobuf.cmake#L84

```
CMAKE_CXX_STANDARD=11 is too old to support protobuf(24.3.0) and/or abseil-cpp. Use C++17 or later. Turning HAVE_PROTOBUF off
```

In current opencv PKGBUILD file, protobuf option is enabled but it is turned off in cmake due to above reason. There was a previous discussion about enabling C++17 standard in abseil-cpp. @MehdiChinoune may provide some info about whether C++17 should be enabled in abseil-cpp explicitly.

**Comment by MehdiChinoune** [comment]
It looks like we will forcibly set CXX_STANDARD=17 for abseil-cpp and dependent packages.

**Comment by Biswa96** [comment]
ArchLinux also has C++17 in all abseil-cpp related packages. Please feel free to create a pull request to set the C++ standard.

**Comment by joda01** [comment]
It's my first contribution to this repository. So hopefully I did it right.

https://github.com/msys2/MINGW-packages/pull/19681
