### ISSUE TITLE
Add rufus

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MINGW-packages#19697]
### Package name

rufus

### Brief description of package

Rufus is a utility that helps format and create bootable USB flash drives.

### URL for package's homepage

https://github.com/pbatard/rufus

### Provide a basic test case to validate the package's functionality.

it is a gui application so it just starts

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

I can try, it builds on mingw already

**Comment by Biswa96** [comment]
rufus is in mingw packages repository https://packages.msys2.org/base/mingw-w64-rufus
