### ISSUE TITLE
[mingw-w64-geany] update to 2.0

### ISSUE THREAD

**Issue by iahung3** [msys2/MINGW-packages#19704]
### Package name

mingw-w64-geany

### New version number

2.0

### Other information that may be useful

https://www.geany.org/documentation/releasenotes/2.0/

### Are you willing to submit a PR?

No

**Comment by lazka** [comment]
I actually tried when it came out, but there were various build issues/fixes upstream, so I decided to wait on a bugfix release first.

We can try backporting them instead though.

**Comment by iahung3** [comment]
What surprises me most is that most programs will not build out of the box. For example, I tried to build SMPlayer, SMTube, and GNOME Mahjongg. All of them failed to build on MSYS2.

**Comment by Biswa96** [comment]
> What surprises me most is that most programs will not build out of the box.

If upstream supports native Windows platform there will be no issue. Recently, many gnome projects can not be built for Windows.

**Comment by iahung3** [comment]
> > What surprises me most is that most programs will not build out of the box.
> 
> If upstream supports native Windows platform there will be no issue. Recently, many gnome projects can not be built for Windows.

Qt based programs like SMPlayer/SMTube also fail to build on MSYS2. They support native Windows platform and even have MinGW in their CI.

**Comment by ognevny** [comment]
#20298 is merged

**Comment by hmartinez82** [comment]
@iahung3 Most of the times is that projects use build processed code that assume Linux is the target just because the compiler is GCC (or GCC-like).  Stuff like this: https://github.com/oneapi-src/oneDNN/pull/1804
