### ISSUE TITLE
`evince.exe` always comes with a command prompt window

### ISSUE THREAD

**Issue by ghost** [msys2/MINGW-packages#19723]
### Discussed in https://github.com/msys2/MINGW-packages/discussions/19703

<div type='discussions-op-text'>

<sup>Originally posted by **iahung3** January 11, 2024</sup>
Package `mingw-w64-ucrt-x86_64-evince`. This isn't the case with `mingw-w64-ucrt-x86_64-geany`.</div>

It isn't the case with the old GTK2 Evince I have always used, too.

https://portableapps.com/apps/office/evince_portable

**Comment by iahung3** [comment]
The problem only exists with `evince`. Other GTK applications like `meld3` don't have such problem.

**Comment by iahung3** [comment]
I don't see anything suspicious with https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-evince. That command prompt window is kind of coming from nowhere. Maybe someone forgot `-mwindows`?

**Comment by iahung3** [comment]
> ### Discussed in #19703
> Originally posted by **iahung3** January 11, 2024 Package `mingw-w64-ucrt-x86_64-evince`. This isn't the case with `mingw-w64-ucrt-x86_64-geany`.
> 
> It isn't the case with the old GTK2 Evince I have always used, too.
> 
> https://portableapps.com/apps/office/evince_portable

Update: Geany (`mingw-w64-clang-x86_64-geany`) is now the same, too.

**Comment by iahung3** [comment]
Superseded by https://github.com/msys2/MINGW-packages/issues/20519
