### ISSUE TITLE
[mingw-w64-gcc] __builtin_clz can give wrong results when passed 0

### ISSUE THREAD

**Issue by mcendu** [msys2/MINGW-packages#19724]
### Description

The following test case outputs wrong results when compiled against AMD64, without any compiler flags:

```c
extern int printf(const char *format, ...);
extern long strtol(const char *nptr, char **endptr, int base);

int main(int argc, char **argv)
{
    int a = 0;

    /* argv-dependent section to prevent constant folding */
    if (argc >= 2) {
        char *end;
        int n = strtol(argv[1], &end, 0);
        if (!(*end)) a = n;
    }

    /* this is where the bug emerges */
    printf("%d\n", __builtin_clz(a));
    return 0;
}
```

Commands to compile and run are as follows:

```console
$ gcc clz.c
$ ./a.exe 0
```

[Here is the console output when running `gcc -v clz.c`.](https://github.com/msys2/MINGW-packages/files/13911278/a-clz.log)

Normally I would expect `a.exe` to output the following, as a 32-bit 0 has 32 leading zeros:

```console
32
```

The actual output, however, is a wrong value:

```console
31
```

The problem disappears when the code is compiled with `-mlzcnt`. In addition, the constant expression `(int)__builtin_clz(0)` also gives the correct value of `32`.

### Verification
- [x] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version
MINGW64_NT-10.0-22631

### MINGW environments affected
- [x] MINGW64
- [ ] MINGW32
- [x] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?
Probably not. I have reproduced the issue across multiple platforms, including non-Windows ones, so likely an upstream problem.

**Comment by lhmouse** [comment]
https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html#index-_005f_005fbuiltin_005fclz

> Built-in Function: `int __builtin_clz (unsigned int x)`
> Returns the number of leading 0-bits in _x_, starting at the most significant bit position. If _x_ is 0, **the result is undefined**.
