### ISSUE TITLE
[utf8cpp] There is no i686 packages for mingw-w64-utf8cpp

### ISSUE THREAD

**Issue by e2t** [msys2/MINGW-packages#19746]
### Description / Steps to reproduce the issue

Go to https://packages.msys2.org/base/mingw-w64-utf8cpp

### Expected behavior

[mingw-w64-clang-x86_64-utf8cpp](https://packages.msys2.org/package/mingw-w64-clang-x86_64-utf8cpp?repo=clang64)
[mingw-w64-clang-i686-utf8cpp](https://packages.msys2.org/package/mingw-w64-clang-i686-utf8cpp?repo=clang32)
        [mingw-w64-clang-aarch64-utf8cpp](https://packages.msys2.org/package/mingw-w64-clang-aarch64-utf8cpp?repo=clangarm64)
        [mingw-w64-x86_64-utf8cpp](https://packages.msys2.org/package/mingw-w64-x86_64-utf8cpp?repo=mingw64)
        [mingw-w64-i686-utf8cpp](https://packages.msys2.org/package/mingw-w64-i686-utf8cpp?repo=mingw32)
        [mingw-w64-ucrt-x86_64-utf8cpp](https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-utf8cpp?repo=ucrt64)

### Actual behavior

[mingw-w64-clang-x86_64-utf8cpp](https://packages.msys2.org/package/mingw-w64-clang-x86_64-utf8cpp?repo=clang64)
        [mingw-w64-clang-aarch64-utf8cpp](https://packages.msys2.org/package/mingw-w64-clang-aarch64-utf8cpp?repo=clangarm64)
        [mingw-w64-x86_64-utf8cpp](https://packages.msys2.org/package/mingw-w64-x86_64-utf8cpp?repo=mingw64)
        [mingw-w64-ucrt-x86_64-utf8cpp](https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-utf8cpp?repo=ucrt64)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22000

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by e2t** [comment]
[I got it.](https://github.com/msys2/MINGW-packages/discussions/19326) Now OpenSource C++ does not support 32-bit platform. "Fascinating."

**Comment by Biswa96** [comment]
Could you kindly provide some clarification on your requirement for 32-bit packages? Are you utilizing a 32-bit machine or a Windows operating system?

**Comment by e2t** [comment]
I try to make my applications so that customers don't have to worry about anything extra: neither updating their operating systems nor installing frameworks.
Anyway, I'm not going to argue with your decision.
