### ISSUE TITLE
[libblocksruntime] The current version 0.4.1-2 seems to be missing export symbols

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [msys2/MINGW-packages#19743]
### Description / Steps to reproduce the issue

I'm building my project via github action / workflow, and get linking errors.
No related changes on my side.

The library is definitely getting linked, but symbols are not found.

I downloaded and inspected the dll file from the package, and it doesn't seem to have those symbols exported.

```
clang -o "bin/release/deadbeef.exe" obj/Windows/release/deadbeef/buffered_file_writer.o obj/Windows/release/deadbeef/conf.o obj/Windows/release/deadbeef/ctmap.o obj/Windows/release/deadbeef/cueutil.o obj/Windows/release/deadbeef/decodedblock.o obj/Windows/release/deadbeef/dsp.o obj/Windows/release/deadbeef/dsppreset.o obj/Windows/release/deadbeef/escape.o obj/Windows/release/deadbeef/fft.o obj/Windows/release/deadbeef/handler.o obj/Windows/release/deadbeef/junklib.o obj/Windows/release/deadbeef/logger.o obj/Windows/release/deadbeef/main.o obj/Windows/release/deadbeef/md5.o obj/Windows/release/deadbeef/messagepump.o obj/Windows/release/deadbeef/metacache.o obj/Windows/release/deadbeef/parser.o obj/Windows/release/deadbeef/playlist.o obj/Windows/release/deadbeef/playmodes.o obj/Windows/release/deadbeef/playqueue.o obj/Windows/release/deadbeef/plmeta.o obj/Windows/release/deadbeef/pltmeta.o obj/Windows/release/deadbeef/plugins.o obj/Windows/release/deadbeef/premix.o obj/Windows/release/deadbeef/replaygain.o obj/Windows/release/deadbeef/resizable_buffer.o obj/Windows/release/deadbeef/ringbuf.o obj/Windows/release/deadbeef/sort.o obj/Windows/release/deadbeef/streamer.o obj/Windows/release/deadbeef/streamreader.o obj/Windows/release/deadbeef/tf.o obj/Windows/release/deadbeef/threading_pthread.o obj/Windows/release/deadbeef/utf8.o obj/Windows/release/deadbeef/vfs.o obj/Windows/release/deadbeef/vfs_stdio.o obj/Windows/release/deadbeef/viz.o obj/Windows/release/deadbeef/volume.o obj/Windows/release/deadbeef/wcwidth.o obj/Windows/release/deadbeef/Resources.o obj/Windows/release/deadbeef/deadbeef-icon.o   -Lstatic-deps/lib-x86-64/lib/x86_64-linux-gnu -Lstatic-deps/lib-x86-64/lib -Lxdispatch_ddb/lib -mwindows -Wl,--export-all-symbols libwin.lib -lintl -lws2_32 -lpsapi -lshlwapi -liconv -lm -lpthread -ldl -ldispatch -lBlocksRuntime
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/main.o:main.c:(.text+0x1993): undefined reference to `__imp__NSConcreteGlobalBlock'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/plugins.o:plugins.c:(.text+0x187c): undefined reference to `_Block_copy'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/plugins.o:plugins.c:(.text+0x18fb): undefined reference to `__imp__NSConcreteStackBlock'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/plugins.o:plugins.c:(.text+0x1c23): undefined reference to `_Block_release'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/plugins.o:plugins.c:(.text+0x2786): undefined reference to `__imp__Block_object_dispose'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/plugins.o:plugins.c:(.text+0x2826): undefined reference to `__imp__Block_object_dispose'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/plugins.o:plugins.c:(.text+0x28c6): undefined reference to `__imp__Block_object_dispose'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/plugins.o:plugins.c:(.text+0x2966): undefined reference to `__imp__Block_object_dispose'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/plugins.o:plugins.c:(.text+0x2a06): undefined reference to `__imp__Block_object_dispose'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/plugins.o:plugins.c:(.text+0x2aa6): more undefined references to `__imp__Block_object_dispose' follow
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/viz.o:viz.c:(.text+0xae): undefined reference to `__imp__NSConcreteStackBlock'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/viz.o:viz.c:(.text+0x15e): undefined reference to `__imp__NSConcreteStackBlock'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/viz.o:viz.c:(.text+0x21e): undefined reference to `__imp__NSConcreteStackBlock'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/viz.o:viz.c:(.text+0x2ce): undefined reference to `__imp__NSConcreteStackBlock'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/viz.o:viz.c:(.text+0x3b3): undefined reference to `__imp__NSConcreteGlobalBlock'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/viz.o:viz.c:(.text+0x3d6): undefined reference to `__imp__NSConcreteStackBlock'
D:/a/_temp/msys64/mingw64/bin/ld: obj/Windows/release/deadbeef/viz.o:viz.c:(.text+0x82c): undefined reference to `__imp__NSConcreteStackBlock'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Expected behavior

There should not be any errors

### Actual behavior

I'm getting linker errors

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows Server 2022   10.0.20348

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Oleksiy-Yakovenko** [comment]
The first failing build occurred 3 weeks ago, which coincides with this change:
https://github.com/msys2/MINGW-packages/commit/e87cac480bc31720fac005dab9cc1c00a0d6b0f5

**Comment by ognevny** [comment]
> The first failing build occurred 3 weeks ago, which coincides with this change: [e87cac4](https://github.com/msys2/MINGW-packages/commit/e87cac480bc31720fac005dab9cc1c00a0d6b0f5)

this change did _nothing_ to the package. it's just metadata for website

**Comment by Oleksiy-Yakovenko** [comment]
Yes, sorry, I didn't mean to imply that this change caused it. But there was a new build 3 weeks ago, and maybe some external script in some other package has changed.

I downloaded the previous build (1) and looked in the dll contents.
The latest dll doesn't contain string `_Block_release`, but the previous one does.

0.4.1-2:
```
% strings libBlocksRuntime-0.dll | grep _Block_release
```

0.4.1-1:
```
% strings libBlocksRuntime-0.dll | grep _Block_release
_Block_release
```

**Comment by Oleksiy-Yakovenko** [comment]
FYI: we are unblocked, and can build again, by using another version of BlocksRuntime.dll
So if it's not important for mingw itself -- this issue can be closed.
Yet keep in mind, that the mingw-supplied BlocksRuntime package is not usable.

**Comment by lazka** [comment]
Weird that package-grokker didn't catch this

**Comment by MehdiChinoune** [comment]
> Weird that package-grokker didn't catch this

Package-grokker catches missing symbols for reverse dependencies.

**Comment by lazka** [comment]
ah, right, we have no internal users.

**Comment by lazka** [comment]
Did #19777 improve things?

**Comment by Oleksiy-Yakovenko** [comment]
> Did https://github.com/msys2/MINGW-packages/pull/19777 improve things?

We have already resolved the problem by switching to our own build of this library, and I will not be able to spend the time necessary to switch back.
If the symbol is now exported, the problem should be resolved, and the issue can be closed.

**Comment by qmfrederik** [comment]
> We have already resolved the problem by switching to our own build of this library

Out of curiosity, which repository are you using to get the sources for libblocksruntime?

**Comment by Oleksiy-Yakovenko** [comment]
From here: https://github.com/apple/swift-corelibs-libdispatch/releases
It's part of libdispatch source tree.

**Comment by ognevny** [comment]
we are about to remove old `libblocksruntime` package. can you try new `libdispatch` package, please (you can download it from [artifact](https://github.com/msys2/MINGW-packages/pull/20054/checks))

**Comment by MehdiChinoune** [comment]
It was removed in https://github.com/msys2/MINGW-packages/commit/7aaaa112 and It's now provided by libdispatch package.
