### ISSUE TITLE
mingw-w64-kate vs Kate_Release_win64

### ISSUE THREAD

**Issue by iahung3** [msys2/MINGW-packages#19745]
Why `mingw-w64-kate` is too bare metal and ugly compared to `Kate_Release_win64` which is full featured and included the KDE themes out of the box?

https://binary-factory.kde.org/job/Kate_Release_win64/

**Comment by iahung3** [comment]
Can our `mingw-w64-kate` be as full featured as `Kate_Release_win64`? I don't mind a few more dependencies!

**Comment by Biswa96** [comment]
The only thing that we are missing is full breeze icons and themes. The source tarball has symbolic links and can not be extracted properly in PKGBUILD.
