### ISSUE TITLE
Build angleproject for mingw32 and clang32

### ISSUE THREAD

**Issue by kasper93** [msys2/MINGW-packages#19747]
### Package name

angleproject

### For which environment do you need the package?

CLANG32

### Provide a brief description why you need this package in the selected environment

It has been removed in https://github.com/msys2/MINGW-packages/commit/fff2fa3711e3cf1c9b65b12784ab3d9428a779f1 without explaining why is has been disabled.

I would like to have build coverage for 32-bit builds too for mpv, which unfortunately due this removal was disabled for all the build targets now see https://github.com/mpv-player/mpv/commit/d56ad8f0329e973d4c41e93f8491b4d3ceac9793

**Comment by Biswa96** [comment]
Could you kindly provide some clarification on your requirement for 32-bit packages? Are you utilizing a 32-bit machine or a Windows operating system?

**Comment by Biswa96** [comment]
Please see this #19326 discussion and this news https://www.msys2.org/news/#2023-12-13-starting-to-drop-some-32-bit-packages

**Comment by kasper93** [comment]
Ok, in this case should we disable 32-bit CI in mpv? I don't see a sane path forward if packages can be randomly dropped. I don't need 32-bit build specifically. It increases test coverage of build test, as there were multiple issues in the past that were identified. But if it is no longer supported target by MSYS2, I don't think we should support it either.

**Comment by kasper93** [comment]
I decided to remove 32-bit builds of mpv from our CI. https://github.com/mpv-player/mpv/pull/13277

If it is intended to remove 32-bit packages randomly like that it is not feasible to maintain those builds and fix the each time somethings disappears.
