### ISSUE TITLE
bash: complete -r doesn't work

### ISSUE THREAD

**Issue by eekee** [msys2/MINGW-packages#19755]
### Description / Steps to reproduce the issue

Steps to reproduce:
1. find an undesired completion; in this case, `cdiff`
2. attempt to remove it -- `complete -r cdiff`
3. verify removal -- `complete | grep cdiff`
4. attempt tab completion -- see it doesn't work
5. check removal -- `complete | grep cdiff`

the last step shows the unwanted completion has been restored.

log, with bracketed indication of where completion was attempted:
```
Home@DESKTOP-UOIVVI4 MSYS /c/forth
$ complete | grep cdiff
complete -F _filedir_xspec cdiff

Home@DESKTOP-UOIVVI4 MSYS /c/forth
$ complete -r cdiff

Home@DESKTOP-UOIVVI4 MSYS /c/forth
$ complete | grep cdiff

[$ cdiff fo<tab>]

Home@DESKTOP-UOIVVI4 MSYS /c/forth
$ complete | grep cdiff
complete -F _filedir_xspec cdiff
```

**NB:** The checkmarks below don't match my MSYS install. Specifically, I see this:
```
Home@DESKTOP-UOIVVI4 MSYS /c/forth
$ echo $MSYSTEM
MSYS
```
Given that I have performed almost no customization on my MSYS2 install, only adding some aliases to `.bashrc`, I'm unsure of what to check. Besides, if `bash` isn't the same version in all of them... oh never mind, I can't fix your problems for you.

### Expected behavior

To quote bash(1):
 The  -r  option  removes  a  completion specification  for  each _name_, or, if no _name_s are supplied, all completion specifications.

### Actual behavior

Not sure what to write here when the problem is clear in its reproduction.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by brisingraerowing** [comment]
This should probably be in the [MSYS2-Packages Issue Tracker](https://github.com/msys2/MSYS2-packages/issues)

**Comment by eekee** [comment]
Yes, it probably should. Thanks for the link, it wasn't coming up when I reported it. I'll copy it over when I can.
