### ISSUE TITLE
[openssl] static linking got broken with OpenSSL 3.2

### ISSUE THREAD

**Issue by JelteF** [msys2/MINGW-packages#19772]
### Description / Steps to reproduce the issue

PgBouncer its statically linked Windows build is broken since the release of OpenSSL 3.2.0 on MINGW.

```bash
MINGW_PACKAGE_PREFIX=mingw-w64-x86_64
pacman --noconfirm -S --needed base-devel ${MINGW_PACKAGE_PREFIX}-gcc ${MINGW_PACKAGE_PREFIX}-libevent ${MINGW_PACKAGE_PREFIX}-openssl ${MINGW_PACKAGE_PREFIX}-postgresql autoconf automake libtool ${MINGW_PACKAGE_PREFIX}-python ${MINGW_PACKAGE_PREFIX}-python-pip zip
git clone https://github.com/pgbouncer/pgbouncer.git
cd pgbouncer
git submodule init
git submodule update
./autogen.sh
./configure --prefix=$HOME/install --enable-werror PANDOC=/c/programdata/chocolatey/bin/pandoc LDFLAGS=-static LIBS=-liphlpapi PKG_CONFIG='pkg-config --static'
```

### Expected behavior

Running `./configure` succeeds

### Actual behavior

Fails with: 
```
checking for OpenSSL... configure: error: not found
```

This started happening in CI after the 3.2.0 release: https://cirrus-ci.com/task/6077420436979712

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-17763

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
It seems that the autotools files in the project do not use pkgconfig for openssl libraries. Here is a snippet in config.log file.

```
configure:8863: checking for OpenSSL
configure:8917: gcc -o conftest.exe -g -O2  -D__USE_MINGW_ANSI_STDIO=1  -static -Wl,--as-needed conftest.c -lssl -lcrypto  -lws2_32 >&5
ld.exe: libcrypto.a(libdefault-lib-winstore_store.obj):(.text+0x64): undefined reference to `__imp_CertFreeCertificateContext'
ld.exe: libcrypto.a(libdefault-lib-winstore_store.obj):(.text+0x86): undefined reference to `__imp_CertCloseStore'
ld.exe: libcrypto.a(libdefault-lib-winstore_store.obj):(.text+0x137): undefined reference to `__imp_CertOpenSystemStoreW'
ld.exe: libcrypto.a(libdefault-lib-winstore_store.obj):(.text+0x14f): undefined reference to `__imp_CertFreeCertificateContext'
ld.exe: libcrypto.a(libdefault-lib-winstore_store.obj):(.text+0x372): undefined reference to `__imp_CertFindCertificateInStore'
ld.exe: libcrypto.a(libdefault-lib-winstore_store.obj):(.text+0x5fa): undefined reference to `__imp_CertFreeCertificateContext'
ld.exe: libcrypto.a(libdefault-lib-winstore_store.obj):(.text+0x66f): undefined reference to `__imp_CertFindCertificateInStore'
collect2.exe: error: ld returned 1 exit status
```

But the pkgconfig output for openssl has all the required libraries.

```
$ pkgconf -libs -static openssl
-lssl -lcrypto -lws2_32 -lgdi32 -lcrypt32 -lcrypto -lws2_32 -lgdi32 -lcrypt32
```

**Comment by JelteF** [comment]
Thank you! That solved the compilation issue (after renaming a function that now had a name conflict). The tests still don't pass though... but that is probably not related to mingw packaging.

**Comment by Biswa96** [comment]
Could you provide the solution of the issue? Just out of curiosity.

**Comment by JelteF** [comment]
Adding `$(pkgconf -libs -static openssl)` to the LIBS on the configure line. I might actually change the configure script in the future to do this automatically, but for now this is acceptable.
```
./configure --prefix=$HOME/install --enable-werror PANDOC=/c/programdata/chocolatey/bin/pandoc LDFLAGS=-static "LIBS=-liphlpapi $(pkgconf -libs -static openssl)" PKG_CONFIG='pkg-config --static'
```
