### ISSUE TITLE
Build CMake for Windows 7

### ISSUE THREAD

**Issue by yakamoz423** [msys2/MINGW-packages#19773]
### Package name

mingw-w64-x86_64-cmake

### For which environment do you need the package?

MINGW64

### Provide a brief description why you need this package in the selected environment

I tried mingw-w64-x86_64-cmake=3.28.1 in Windows 7 SP1, but cmake.exe cannot be executed and pops up `GetSystemTimePreciseAsFileTime` function not found in KERNEL32.DLL. 

I know the MSYS supports of elder Windows is end, but I also tried [latest CMake offcial binary distributions for Windows x64](https://cmake.org/download/), and it runs smoothly in Windows 7. So I think it may be an mistake.

**Comment by Biswa96** [comment]
Unfortunately, msys2 project dropped support for Windows 7 and lower since a year ago. Please see this news entry https://www.msys2.org/news/#2023-01-15-dropping-support-for-windows-7-and-80

**Comment by asmwarrior** [comment]
I see some similar error in my Windows 7. When I try to start the "cmake"(, it just exit without any message or messagebox. 
I tried from "mingw-w64-x86_64-cmake-3.25.3-1-any.pkg.tar.zst" to "mingw-w64-x86_64-cmake-3.28.0-1-any.pkg.tar.zst" which I can download from https://repo.msys2.org/mingw/mingw64/.

I think currently the only solution is to use Win10 and above. Not only `cmake`, but there are many other packages which don't work under Win 7.

**Comment by yakamoz423** [comment]
> I see some similar error in my Windows 7. When I try to start the "cmake"(, it just exit without any message or messagebox. I tried from "mingw-w64-x86_64-cmake-3.25.3-1-any.pkg.tar.zst" to "mingw-w64-x86_64-cmake-3.28.0-1-any.pkg.tar.zst" which I can download from https://repo.msys2.org/mingw/mingw64/.
> 
> I think currently the only solution is to use Win10 and above. Not only `cmake`, but there are many other packages which don't work under Win 7.

You can obtain more accurate error report, by double clicking `cmake.exe` directly in the Explorer. And in my case, `cmake.exe` from https://cmake.org/download/ works well in Windows 7, simply put it into `mingw64/bin/` and replace.

**Comment by asmwarrior** [comment]
> You can obtain more accurate error report, by double clicking `cmake.exe` directly in the Explorer. And in my case, `cmake.exe` from https://cmake.org/download/ works well in Windows 7, simply put it into `mingw64/bin/` and replace.

Thanks for the response.

Yes, I use the same way as you mentioned to workaround this issue. The official cmake package I use is a zip: [cmake-3.28.2-windows-x86_64.zip](https://github.com/Kitware/CMake/releases/download/v3.28.2/cmake-3.28.2-windows-x86_64.zip).
