### ISSUE TITLE
x86 qoi disappeared 

### ISSUE THREAD

**Issue by brunolopesdsilv** [msys2/MINGW-packages#19820]
### Description / Steps to reproduce the issue

Open qoi package page: https://packages.msys2.org/base/mingw-w64-qoi

or, see this pipeline: https://gitlab.gnome.org/GNOME/gimp/-/jobs/3477781#L182

The same happens locally: 
![image](https://github.com/msys2/MINGW-packages/assets/156703114/657f81f1-ea0b-4305-ad45-003697371177)

### Expected behavior

qoi is available to x86 (32-bit) though mingw32

### Actual behavior

qoi disappeared

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW32_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
We are actually in the process of dropping 32-bit environments see: https://www.msys2.org/news/#2023-12-13-starting-to-drop-some-32-bit-packages

and https://github.com/msys2/MINGW-packages/discussions/19326

**Comment by brunolopesdsilv** [comment]
> We are actually in the process of dropping 32-bit environments see: https://www.msys2.org/news/#2023-12-13-starting-to-drop-some-32-bit-packages
> 
> and #19326

Thanks for the clarifications.
