### ISSUE TITLE
soci+mariadbclient 3.3.8-1 failed to connect to a mysql database, while it works with 3.1.13(replace the libmariadb.dll with old one works)

### ISSUE THREAD

**Issue by asmwarrior** [msys2/MINGW-packages#19861]
### Description / Steps to reproduce the issue

I have c++ code to connect to mysql through the mariadbclient library , it used to work with the mariadbclient version 3.1.3, but after I upgraded yesterday, I see it can't connect to the mysql now.

I just replace the libmariadb.dll file with the old libmariadb.dll(version 3.1.13), my code works, so I believe the interface may changes?

This is the test code:

~~~~
#include <soci/soci.h>
#include <soci/mysql/soci-mysql.h>

int main()
{
    soci::session sql(soci::mysql, "dbname=testdb user=root password=123456");
    return 0;
}
~~~~

Note I also use the soci library, it looks like the libmariadb library has some interface changes, so soci library just failed to use it.

The above program will report some error like:

~~~~
terminate called after throwing an instance of 'soci::mysql_soci_error'
  what():  Plugin caching_sha2_password could not be loaded: 找不到指定的模块。 Library path is 'caching_sha2_password.dll'
~~~~

The text "找不到指定的模块。" means it can't find the specified module.

### Expected behavior

It should connect to the mysql correctly

### Actual behavior

failed to connect to the mysql database

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Could you provide steps to compile the program?

**Comment by asmwarrior** [comment]
> Could you provide steps to compile the program?

OK, since I'm using Code::Blocks IDE, here is the build log:

~~~~
[ 50.0%] g++.exe -Wall -fexceptions -g -IF:\msys2\mingw64\include\mysql -c D:\project\main.cpp -o obj\Debug\main.o
[100.0%] g++.exe  -o bin\Debug\test.exe obj\Debug\main.o  -lsoci_core_4_0 -lsoci_mysql_4_0  
Output file is bin\Debug\test.exe with size 483.75 KB
~~~~

Thanks.

**Comment by raedrizqie** [comment]
i think this can fix the mysql error:
https://github.com/mariadb-corporation/mariadb-connector-c/pull/234

**Comment by Biswa96** [comment]
In my case, the program shows the following error.

```
terminate called after throwing an instance of 'soci::mysql_soci_error'
  what():  Can't connect to server on 'localhost' (10061)
```

I think there is some info missing about reproducing the error in original post.

**Comment by asmwarrior** [comment]
> In my case, the program shows the following error.
> 
> ```
> terminate called after throwing an instance of 'soci::mysql_soci_error'
>   what():  Can't connect to server on 'localhost' (10061)
> ```
> 
> I think there is some info missing about reproducing the error in original post.

What extra information should I post? I'm running MySQL 8.0.33 in Win10 64bit, and the export TCP port is 3306(default).

**Comment by Biswa96** [comment]
Thanks for the info. I can reproduce the issue and get the same error message in original post. From a quick look, the issue is about path relocation.

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

I got the following error with the fix. I guess this error is expected because I am not running any db, right?

```
terminate called after throwing an instance of 'soci::mysql_soci_error'
  what():  Unknown database 'testdb'
```

**Comment by asmwarrior** [comment]
> I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?
> 
> I got the following error with the fix. I guess this error is expected because I am not running any db, right?
> 
> ```
> terminate called after throwing an instance of 'soci::mysql_soci_error'
>   what():  Unknown database 'testdb'
> ```

OK, I can test it. Can you show me the package file, so that I can install that package locally in my PC.

**Comment by Biswa96** [comment]
Please follow these steps for testing package in CI artifacts.

1. Go to this page https://github.com/msys2/MINGW-packages/actions/runs/7677849506 > scroll down > download the XYZ-packages.zip file. The XYZ should match with the value of `$MSYSTEM` variable.
2. Extract the .tar.zst file from that ZIP.
3. Install the .tar.zst file with `pacman -U <full path of .tar.zst file>` command.

**Comment by asmwarrior** [comment]
> Please follow these steps for testing package in CI artifacts.
> 
>     1. Go to this page https://github.com/msys2/MINGW-packages/actions/runs/7677849506 > scroll down > download the XYZ-packages.zip file. The XYZ should match with the value of `$MSYSTEM` variable.
> 
>     2. Extract the .tar.zst file from that ZIP.
> 
>     3. Install the .tar.zst file with `pacman -U <full path of .tar.zst file>` command.

Thanks, I just tested this new package, and it solves my reported issue. Great!
