### ISSUE TITLE
[cc] -print-multi-os-directory NOT working in CLANG shells

### ISSUE THREAD

**Issue by brunolopesdsilv** [msys2/MINGW-packages#19884]
### Description / Steps to reproduce the issue

I'm implementing multi arch variables to the GIMP build system and they are working well in MINGW 64, Debian and even Fedora, using some gcc facilities. In CLANGARM64, ~~UCRT64~~ and others, however, nothing useful happens when using this command: `gcc -print-multi-os-directory`

### Expected behavior

Output "../lib"

### Actual behavior

Nothing is output, just a dot "."

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

N-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment]
> Output "../lib"

It's working as expected in UCRT64 environment in my setup.

![image](https://github.com/msys2/MINGW-packages/assets/31443074/82f857c9-4587-45bb-9169-1f7133a7a4b5)

**Comment by brunolopesdsilv** [comment]
Bug captured in CLANGARM64:

https://gitlab.gnome.org/GNOME/gimp/-/jobs/3499666#L221

**Comment by brunolopesdsilv** [comment]
> > Output "../lib"
> 
> It's working as expected in UCRT64 environment in my setup.
> 
> ![image](https://private-user-images.githubusercontent.com/31443074/300187493-82f857c9-4587-45bb-9169-1f7133a7a4b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjk5MTMsIm5iZiI6MTcwNjM2OTYxMywicGF0aCI6Ii8zMTQ0MzA3NC8zMDAxODc0OTMtODJmODU3YzktNDU4Ny00NWJiLTkxNjktMWY3MTMzYTdhNGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDE1MzMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjOTQ3ODMwYWNhMjgyYjAwN2UxYTBhNTg2Y2U4ZDZlMmE0MTQyYjM1YWNmOTEwYjdmY2UwYWJlMjUyMWU3ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DocNQ_6fzR_6r32ykupGsDDxxfl6pSPY6CguEMZYngU)

Bug captured in UCRT64

https://github.com/msys2/MINGW-packages/assets/156703114/dd243f31-1edd-4c5a-b13f-f6771e1fa59f

**Comment by Biswa96** [comment]
Could you provide the link of gitlab yaml file related to that CI failure?

**Comment by Biswa96** [comment]
I just saw that video. You are installing gcc package which is a msys2 package i.e. links programs with msys2 runtime. Try to install the mingw toolchain with `pacman -S $MINGW_PACKAGE_PREFIX-cc` command.

**Comment by brunolopesdsilv** [comment]
> I just saw that video. You are installing gcc package which is a msys2 package i.e. links programs with msys2 runtime. Try to install the mingw toolchain with `pacman -S $MINGW_PACKAGE_PREFIX-cc` command.
> 
> The `cc` name will automatically converted to gcc or clang based on [environments](https://www.msys2.org/docs/environments/).

Worked in UCRT64 and MINGW32 👍.

---

But not in any of the CLANG shells. I got the following error:

```
cc: error: unsupported option '-print-multi-os-directory'
cc: error: no input files
```

Don't work calling gcc or clang either.

**Comment by Biswa96** [comment]
It seems that clang does not support that option. Though, I would like to know why that option is required in first place and if there is any alternative solution.

**Comment by brunolopesdsilv** [comment]
> It seems that clang does not support that option. Though, I would like to know why that option is required in first place and if there is any alternative solution.

Sure. In short, we use the same scripts to build GIMP for 3 different archs in Windows. In the script s we use some variables required by meson and they are working fine, but my plane is make this variables work in others OSes too. I used this:

```bash
LIB_DIR=$(cc -print-multi-os-directory | sed 's/\.\.\///g')
cc -print-multiarch | grep . && LIB_SUBDIR=$(echo $(cc -print-multiarch)'/')
export PATH="${GIMP_PREFIX}/bin:$PATH"
export PKG_CONFIG_PATH="${GIMP_PREFIX}/${LIB_DIR}/${LIB_SUBDIR}pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
export LD_LIBRARY_PATH="${GIMP_PREFIX}/${LIB_DIR}/${LIB_SUBDIR}"
export XDG_DATA_DIRS="${GIMP_PREFIX}/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
export GI_TYPELIB_PATH="${GIMP_PREFIX}/${LIB_DIR}/${LIB_SUBDIR}girepository-1.0"
```

I sucessed, as said in the description, with the excepcion of CLANG based builds.

It may seem clueless, but it has a motivation (it's easier to replicate in documentation and other "universal" variable scripts, if that's even possible)

**Comment by brunolopesdsilv** [comment]
Closing since this isn't a msys2 bug.
