### ISSUE TITLE
mingw-w64-i686-sqlite3 file mingw32/bin/showjournal.exe is detected as malware by multiple vendors

### ISSUE THREAD

**Issue by bill-e-ghote** [msys2/MINGW-packages#19912]
### Description / Steps to reproduce the issue

https://www.virustotal.com/gui/file/db218d848641aff7c9d37369f57c55a65da5b7ca5653ebebdd233d74558eb3b1/detection

### Expected behavior

Not being detected as malware would be nice.

### Actual behavior

Detected and quarantined by multiple EDR vendors.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Report the issue to those security vendors. All the packages are compiled from source code in GitHub Actions.

**Comment by bill-e-ghote** [comment]
I'm not sure I agree my issue is invalid, but for now I'm pursuing it with the Sigma team, whose detection rule is leading multiple vendors to detect this sqlite3 package as malicious (it is not). I opened a support case here:
https://github.com/SigmaHQ/sigma/issues/4699

**Comment by Biswa96** [comment]
There are thousands false positive reports with programs compiled using mingw, msys, cygwin environments. Those are really frustrating. See these

* https://cygwin.com/faq/faq.html#faq.using.bloda
* https://github.com/msys2/MINGW-packages/issues?q=is%3Aissue+virus
* https://github.com/msys2/MINGW-packages/issues?q=is%3Aissue+malware
* https://github.com/msys2/msys2-packages/issues?q=is%3Aissue+virus
* https://github.com/msys2/msys2-packages/issues?q=is%3Aissue+malware
