### ISSUE TITLE
appstream-glib fails to build

### ISSUE THREAD

**Issue by woot000** [msys2/MINGW-packages#19946]
### Description / Steps to reproduce the issue

On a Windows 10 VM with a clean msys2 installation, the appstream-glib package fails to build. All dependencies and build dependencies were installed before `makepkg-mingw -sCLf` was run.

`mingw-w64-appstream-glib-0.8.2-1-x86_64-build.log`:
```
The Meson build system
Version: 1.3.1
Source dir: C:/Users/woot000/Desktop/appstream-glib/src/appstream-glib-appstream_glib_0_8_2
Build dir: C:/Users/woot000/Desktop/appstream-glib/src/build-MINGW64
Build type: native build
Project name: appstream-glib
Project version: 0.8.2

../appstream-glib-appstream_glib_0_8_2/meson.build:1:0: ERROR: Unable to detect GNU compiler type:
Compiler stdout:

-----
Compiler stderr:
gcc: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
compilation terminated.

-----


A full log can be found at C:/Users/woot000/Desktop/appstream-glib/src/build-MINGW64/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```

`src/build-MINGW64/meson-logs/meson-log.txt`:
```
Build started at 2024-02-04T07:40:22.123819
Main binary: C:/mabs/msys64/mingw64/bin/python.exe
Build Options: -Dintrospection=true -Dgtk-doc=true -Dman=true -Dfonts=true -Dstemmer=false -Dalpm=false -Drpm=false -Ddep11=false -Dbuilder=false -Dprefix=/mingw64 -Dauto_features=enabled -Dbuildtype=plain -Ddefault_library=both -Dwrap_mode=nodownload
Python system: Windows
The Meson build system
Version: 1.3.1
Source dir: C:/Users/woot000/Desktop/appstream-glib/src/appstream-glib-appstream_glib_0_8_2
Build dir: C:/Users/woot000/Desktop/appstream-glib/src/build-MINGW64
Build type: native build
Project name: appstream-glib
Project version: 0.8.2
-----------
Detecting compiler via: `gcc --version` -> 0
stdout:
gcc (Rev3, Built by MSYS2 project) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-----------
Running command: gcc -E -dM -

../appstream-glib-appstream_glib_0_8_2/meson.build:1:0: ERROR: Unable to detect GNU compiler type:
Compiler stdout:

-----
Compiler stderr:
gcc: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
compilation terminated.

-----
```

I've searched online for issues related to failing to find `cc1` in MSYS2's MINGW environment, and reinstalling `mingw-w64-x86_64-gcc` has not solved my issue. `cc1.exe` is not being flagged by any antivirus programs either, so I'm not sure what the root cause of the problem would be.

### Expected behavior

makepkg-mingw creates a MINGW64-environment package for appstream-glib

### Actual behavior

makepkg-mingw fails at the configure process due to failing to find `cc1`

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19041

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
The issue can not be reproduced with clean install of msys2. It seems that you are using msys2 from media-autobuild-suite project. Please try with a clean install from msys2.org.
