### ISSUE TITLE
[mpdecimal] update to 4.0.0

### ISSUE THREAD

**Issue by brisingraerowing** [msys2/MINGW-packages#19941]
### Package name

mingw-w64-mpdecimal

### New version number

4.0.0

### Other information that may be useful

https://www.bytereef.org/mpdecimal/changelog.html

### Are you willing to submit a PR?

No

**Comment by ognevny** [comment]
https://github.com/msys2/MINGW-packages/pull/19816

**Comment by lazka** [comment]
I'll look into it in the coming days

**Comment by lazka** [comment]
Fixed
