### ISSUE TITLE
[jq] package doesn't work with zsh Shell

### ISSUE THREAD

**Issue by souovan** [msys2/MINGW-packages#19997]
### Description / Steps to reproduce the issue

I installed as it shows on the package page https://packages.msys2.org/package/mingw-w64-x86_64-jq?repo=mingw64 with `pacman -S mingw-w64-x86_64-jq`

### Expected behavior

The `jq` package to be available

![image](https://github.com/msys2/MINGW-packages/assets/42985246/da01f399-a94f-43ff-9f33-9427b3a3f846)

### Actual behavior

when try to use from zsh shell i get:
`zsh: command not found: jq`

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by ognevny** [comment]
do you run MINGW64 shell?

**Comment by Biswa96** [comment]
jq is working fine in mingw64 environment. Please make sure you are using mingw64 environment or mingw64 directory path is in PATH environment variable.

![image](https://github.com/msys2/MINGW-packages/assets/31443074/24591b21-5c37-4804-b253-f1d550dcfd36)

**Comment by souovan** [comment]
Thank you for your replies, but as i mentioned early jq isn't working on msys2 with zsh shell, is there any tip to make it work ?

![image](https://github.com/msys2/MINGW-packages/assets/42985246/418e0664-04bf-4024-a49e-724625b98dc3)

![image](https://github.com/msys2/MINGW-packages/assets/42985246/f05f915c-88b1-44fc-9bdf-ef08fb75e5e6)

I'm running msys2 on Windows 11

![image](https://github.com/msys2/MINGW-packages/assets/42985246/aa8bac32-22a0-44ec-93ba-d0bdecebac1f)

**Comment by Biswa96** [comment]
If mingw-w64-x86_64-jq is installed, you have to use MINGW64 environment. See the blue M icon in the list here https://www.msys2.org/docs/environments/

If you are using any terminal emulator like here https://www.msys2.org/docs/terminals/, the command should be as following.

```
msys2_shell.cmd -defterm -here -no-start -mingw64 -shell zsh
```

**Comment by souovan** [comment]
Thank you @Biswa96 this solved my problem !!
