### ISSUE TITLE
Add [libpst]

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MINGW-packages#20002]
### Package name

libpts

### Brief description of package

Ezwinports already has an implementation https://sourceforge.net/projects/ezwinports/files/libpst-0.6.63-w32-src.zip
essentially it is a library that allows you to read propietary outlook formats
it can be found as pst-utils on other distros.

### URL for package's homepage

https://man.archlinux.org/man/extra/libpst/readpst.1.en

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
In the repo now, feedback welcome.

https://packages.msys2.org/base/mingw-w64-libpst
