### ISSUE TITLE
tmpnam_s different behavior in MINGW64 vs UCRT64

### ISSUE THREAD

**Issue by totszwai** [msys2/MINGW-packages#20001]
### Description / Steps to reproduce the issue

Sample code:
```
#include <stdio.h>

int main(int argc, char **argv)
{
    char rndtmp[32];
    tmpnam_s(rndtmp, sizeof(rndtmp));
    printf("rndtmp: %s\n", rndtmp);
}
```

MINGW64
```
$ g++ -MMD -MP -MF -Wall -fstack-protector-all -fpie -DDSO_WIN32 -DWIN32_LEAN_AND_MEAN -m64 -Wno-unknown-pragmas -DWINVER=0x0601 -D_WIN32_WINNT=0x0601  -O2 -Woverloaded-virtual -fpermissive test.cc -o mingw64.exe

$ which g++
/mingw64/bin/g++

$ cat /proc/version
MINGW64_NT-10.0-22621 version 3.4.10.x86_64 (runneradmin@fv-az1495-832) (gcc version 13.2.0 (GCC) ) 2023-12-22 10:06 UTC
```

> rndtmp: \sq4o.

UCRT64
```
$ g++ -MMD -MP -MF -Wall -fstack-protector-all -fpie -DDSO_WIN32 -DWIN32_LEAN_AND_MEAN -m64 -Wno-unknown-pragmas -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -D_UCRT -lucrt  -O2 -Woverloaded-virtual -fpermissive test.cc -o ucrt64.exe

$ which g++
/ucrt64/bin/g++

$ cat /proc/version
MINGW64_NT-10.0-22621 version 3.4.10.x86_64 (runneradmin@fv-az1495-832) (gcc version 13.2.0 (GCC) ) 2023-12-22 10:06 UTC
```

> rndtmp: C:\msys64\tmp\urh4.2

### Expected behavior

Expect both environment returns the same behavior

### Actual behavior

UCRT64 incorrectly appended msys2 root path? 

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
See https://learn.microsoft.com/en-us/cpp/porting/visual-cpp-change-history-2003-2015?view=msvc-170#stdio_and_conio (and search for `tmpnam_s`)

These functions changed with ucrt.

**Comment by lazka** [comment]
You can `#ifdef _UCRT` to check with the predecessor.

> Can we assume that MINGW64 would remain the old way and everything UCRT64 will be the new way...?

In theory mingw-w64 could add some adjustments to bring msvcrt closer to ucrt, but I doubt anything will change at this point in time.
