### ISSUE TITLE
Add libzvbi

### ISSUE THREAD

**Issue by kasper93** [msys2/MINGW-packages#20023]
### Package name

libzvbi

### Brief description of package

VBI capture and decoding library

arch reference https://archlinux.org/packages/extra/x86_64/zvbi/

### URL for package's homepage

https://zapping.sourceforge.net/ZVBI/index.html

### Provide a basic test case to validate the package's functionality.

teletext decoding in ffmpeg

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by kasper93** [comment]
Yes, it is essential for teletext decoding.

**Comment by Biswa96** [comment]
Does the project support native Windows platform? I got the following compiler error while compiling zvbi from git repository.

```
../../zvbi/src/conv.c:29:10: fatal error: langinfo.h: No such file or directory
   29 | #include <langinfo.h>
      |          ^~~~~~~~~~~~
```

**Comment by kasper93** [comment]
I don't know, I have not tried to build. But both Gyan's and BtbN's ffmpeg Windows build does include this library, so there shouldn't be a problem to build it.

**Comment by kasper93** [comment]
I've taken a quick look at BtbN build, he uses older version with patches https://github.com/BtbN/FFmpeg-Builds/tree/master/patches/zvbi originally copied form VLC https://github.com/videolan/vlc/tree/master/contrib/src/zvbi

But if @1480c1 says that build has been fixed upstream, we can just try to use that first.

**Comment by Biswa96** [comment]
I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Comment by kasper93** [comment]
I've rebuild ffmpeg with the new package, everything seems fine.

**Comment by Biswa96** [comment]
> You could enable it in ffmpeg build in repo, so it gets used.

Does ffmpeg support this dependency? ArchLinux uses zvbi with some forks of ffmpeg.

**Comment by kasper93** [comment]
Yes, https://github.com/FFmpeg/FFmpeg/blob/7bf1b9b35769b37684dd2f18a54f01d852a540c8/configure#L308C5-L308C11
