### ISSUE TITLE
Can you donate Emacs UCRT64 patches to Emacs?

### ISSUE THREAD

**Issue by amno1** [msys2/MINGW-packages#20038]
Hi guys; thank you for all the work and effort!

Could it be possible for the authors to donate Emacs [UCRT64 patches](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-emacs) to Emacs, so we can build it out of the box on ucrt64 runtime?

I guess they are considered non-trivial since there is more than 10-15 lines; so FSF copyright would be needed.

**Comment by MehdiChinoune** [comment]
Our repo is licensed under BSD-3-Clause which is compatible with GPL. Nothing stops anyone from using them.

**Comment by amno1** [comment]
"مهدي شينون (Mehdi Chinoune)" ***@***.***> writes:

> Our repo is licensed under BSD-3-Clause which is compatible with GPL. Nothing stops anyone from using them.

I see :). Thank you for the replay.
