### ISSUE TITLE
MINGW64 toolchain gcc does not compile executable

### ISSUE THREAD

**Issue by Brandon-Hurst** [msys2/MINGW-packages#20039]
### Description / Steps to reproduce the issue

From a clean install of MSYS2 as Administrator on my Dell Latitude 7440, I ran the following steps:
`pacman -S --needed mingw-w64-x86_64-toolchain` 

After a clean install log (attached as msys2-install-mingw64-toolchain-log.txt), I...
- Opened MINGW64
- Verified working paths for gcc, gdb, and g++ with gcc --version, etc. 
- Made a hello.c file, including stdio and printing to output, then returning. 
- Called `gcc hello.c` and observed no output file. 

MINGW64 log is also attached. 
[mingw64.txt](https://github.com/msys2/MINGW-packages/files/14270367/mingw64.txt)
[msys2-install-mingw64-toolchain-log.txt](https://github.com/msys2/MINGW-packages/files/14270368/msys2-install-mingw64-toolchain-log.txt)

EDIT: I actually get a similar issue on UCRT64. Log attached for this as well.
[ucrt64-gcc-install.txt](https://github.com/msys2/MINGW-packages/files/14270534/ucrt64-gcc-install.txt)
[ucrt64-gcc-run.txt](https://github.com/msys2/MINGW-packages/files/14270535/ucrt64-gcc-run.txt)

### Expected behavior

gcc should generate a "a.exe" file on my machine. I should be able to execute this file and observe "Hello World" on the standard output. 

### Actual behavior

No output file is produced, and no errors are reported. 

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Brandon-Hurst** [comment]
Just tried a fresh install without using admin permission, and the same issue occurs for me.

**Comment by Biswa96** [comment]
The issue is not caused by the gcc compiler. Please make sure other software like antivirus or anti-cheat are not interfering with msys2 process. See the 4.43 point here https://cygwin.com/faq/faq.html#faq.using.bloda
