### ISSUE TITLE
[nodejs-neovim] 

### ISSUE THREAD

**Issue by landao314** [msys2/MINGW-packages#20035]
### Description / Steps to reproduce the issue

1.I install mingw-w64-x86_64-{neovim,nodejs,nodejs-neovim} with pacman.
2.:checkhealth in nvim-qt
3.the nodejs provider is not enable by needing install "npm install -g neovim"
4.it is like the path was not right.

### Expected behavior

checkhealth is OK to Node

### Actual behavior

need install neovim with "npm install -g neovim"

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

windows 11

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by podsvirov** [comment]
Hm, but:
```console
user@host MINGW64 ~
$ npm list -g
C:\msys64\mingw64\lib
├── corepack@0.24.0
├── neovim@4.10.1
└── npm@10.2.4
```
Looks like, the problem on the neovim side, not on nodejs.
