### ISSUE TITLE
Segmentation fault after fresh install of fonttools v4.48.1

### ISSUE THREAD

**Issue by NadAlaba** [msys2/MINGW-packages#20052]
### Description / Steps to reproduce the issue

Installing version 4.48.1 with `pacman -S fonttools` and with `pip install fonttools` gives segmentation fault after `fonttools -h`

### Expected behavior

It should not give a segmentation fault

### Actual behavior

It gives segmentation fault

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
"C extensions are not compatible with the official CPython, which means pip can't use binary wheels from PyPI and packages have to be build when installing them" - https://www.msys2.org/docs/python/#known-issues

Either use the pacman one or from pip.

**Comment by NadAlaba** [comment]
> Either use the pacman one or from pip.

Installing from either pacman  (`pacman -S mingw-w64-x86_64-python-fonttools`) or building wheels before installing them (`pip install --no-binary=fonttools fonttools`) produces the same result.

**Comment by Biswa96** [comment]
The msys2/mingw64 environment is already messed up after that experiment. Please try with a clean msys2 install. In my case, python-fonttools is working fine. Though, I have only run `fonttools -h` command.

**Comment by NadAlaba** [comment]
Clean MSYS2 install solved the issue. Thank you!
