### ISSUE TITLE
python/pip not using pre-built wheels

### ISSUE THREAD

**Issue by ReenigneArcher** [msys2/MINGW-packages#20059]
### Description / Steps to reproduce the issue

Pip is building a wheel for `pydantic-core` instead of using a pre-built wheel.

1. Install python
2. Create python venv and activate it
3. run `python -m pip install pydantic-core`

OS: Win 11 and Server 2019
Arch: amd64

I may be missing something, but I cannot determine why it's not using a pre-built wheel.

### Expected behavior

Use a pre-built wheel... as far as I can tell there is one for windows/python 3.11/amd64.

- `pydantic_core-2.16.2-cp311-none-win_amd64.whl`

Here's the full list of pre-built wheels. https://pypi.org/project/pydantic-core/#files

### Actual behavior

Wheel is built locally, which is very time consuming (~7-8 minutes) and requires otherwise unneeded dependencies, such as a rust compiler.

```txt
Collecting pydantic-core==2.16.2 (from pydantic>=2->rstcheck-core>=1.1->rstcheck[sphinx]==6.2.0->-r ./repo/docs/requirements.txt (line 4))
  Downloading pydantic_core-2.16.2.tar.gz (368 kB)
     ------------------------------------- 368.9/368.9 kB 22.4 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows Server 2019 10.0.17763

**Comment by MehdiChinoune** [comment]
Using external software on MSYS2 is not supported.
