### ISSUE TITLE
Please provide static llvm libs

### ISSUE THREAD

**Issue by iahung3** [msys2/MINGW-packages#20063]
### Package name

mingw-w64-[environment]-llvm-libs-static

### Brief description of package

static version of llvm libs (mingw-w64-[environment]-llvm-libs)

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by MehdiChinoune** [comment]
Static llvm libraries are already providey bu mingw-w64-llvm package.
