### ISSUE TITLE
Build libbotan for MINGW32

### ISSUE THREAD

**Issue by solemnwarning** [msys2/MINGW-packages#20084]
### Package name

libbotan

### For which environment do you need the package?

MINGW32

### Provide a brief description why you need this package in the selected environment

I use the MINGW32/MINGW64 toolchains for building [rehex](https://github.com/solemnwarning/rehex), libbotan is no longer available in MINGW32 (as of 67a5d4f37d165133d3d6bc866ff277dc9625db15?) which means I can't built 32-bit versions of rehex (unless I build botan myself, anyway).

As per the news post on 2023-12-13, I'm opening this issue for you to consider re-instating it :)

**Comment by MehdiChinoune** [comment]
Is there a problem with 64-bit that make users want 32-bit one?

**Comment by solemnwarning** [comment]
I build 32-bit and 64-bit just in case of people trying to run it on 32-bit installations, going by the download counts of the past few release approx 18% of downloads are for the 32-bit version.

**Comment by MehdiChinoune** [comment]
> I build 32-bit and 64-bit just in case of people trying to run it on 32-bit installations, going by the download counts of the past few release approx 18% of downloads are for the 32-bit version.

How many of those who download 32-bit version use Windows 10 32-bit?
There are many users who have 64-bit but just download 32-bit, the rest have Windows<10

**Comment by solemnwarning** [comment]
> > I build 32-bit and 64-bit just in case of people trying to run it on 32-bit installations, going by the download counts of the past few release approx 18% of downloads are for the 32-bit version.
> 
> How many of those who download 32-bit version use Windows 10 32-bit? There are many users who have 64-bit but just download 32-bit, the rest have Windows<10

It could be people are downloading the 32-bit version when they in fact have 64-bit Windows... although I'd expect the target audience of a hex editor to know the difference. Is there something significant about Windows 10 vs. other Windows versions?

**Comment by MehdiChinoune** [comment]
> It could be people are downloading the 32-bit version when they in fact have 64-bit Windows... although I'd expect the target audience of a hex editor to know the difference. Is there something significant about Windows 10 vs. other Windows versions?

Windows<10 is not supported.

**Comment by rimrul** [comment]
> > It could be people are downloading the 32-bit version when they in fact have 64-bit Windows... although I'd expect the target audience of a hex editor to know the difference. Is there something significant about Windows 10 vs. other Windows versions?
> 
> Windows<10 is not supported.

According to https://www.msys2.org/docs/windows_support/

Windows 8.1 is still supported.

**Comment by MehdiChinoune** [comment]
> According to https://www.msys2.org/docs/windows_support/
> 
> Windows 8.1 is still supported.

Yes, you are right but almost all Windows 8.1 upgraded to free Windows 10
