### ISSUE TITLE
[pyqt5] i686 Support for Qt5 & PyQt5

### ISSUE THREAD

**Issue by jonoomph** [msys2/MINGW-packages#20090]
### Description / Steps to reproduce the issue

I noticed that the 32-bit i686 packages for Qt5 and PyQt5 are no longer found by pacman on the latest version of MSYS2. OpenShot Video Editor uses these packages for our 32-bit builds, and we still receive hundreds of thousands of downloads and lots of interest from schools and educators for 32-bit support. Just curious if this is on purpose, or are these packages only removed temporarily?

**Old Package Names:**
`mingw-w64-i686-qt5`
`mingw-w64-i686-python3-pyqt5`

### Expected behavior

Expected behavior would be for these 2 packages to be supported by MSYS2 and available to install in the i686 environment.

### Actual behavior

Packages are not found.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-6.1-7601

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
mingw-w64-i686-qt5 packages still exists, you have just to install the components individually. for example qt5-base, qt5-declarative...etc
mingw-w64-i686-pyqt5 was removed as part of dropping 32-bit packages, see #19326

**Comment by jonoomph** [comment]
Thanks for the info! Video editing and other digital media classes are taught to middle and high school students all over the world. For example, in India millions of students are taught these skills using Linux and open-source software.

**Comment by jonoomph** [comment]
Some schools are using Linux now, but I get emails quite often from school districts still using Windows, with no ability to upgrade to more modern versions, due to budget and limited/old hardware. So, while I totally understand the download stats for these 32-bit packages is basically zero on MSYS2, downstream build systems such as OpenShot's are producing binaries which are still being downloaded hundreds of thousands of times.

**Comment by brunolopesdsilv** [comment]
I am surprised that, in times of 720p, 1080p, someone tries to edit a video in 4GB RAM 😲

**Comment by jonoomph** [comment]
Also, I know that in recent years, Chromebooks have been surging, and perhaps this is slowly eroding the need for 32-bit Windows in schools... but it's hard to find good stats on this stuff.

**Comment by lazka** [comment]
@jonoomph do you depend on QtWebKit via pyqt5 too?

**Comment by jonoomph** [comment]
Yes, OpenShot uses QtWebKit for our timeline on Windows.

**Comment by lazka** [comment]
It's back now. Note that there are hardly any users left and since we are a rolling distro there is a good chance things will start to bit-rot eventually.

**Comment by jonoomph** [comment]
Thanks! I will give this a try
