### ISSUE TITLE
[libuv] Segfault in neovim caused by upgrade libuv to version 1.48.0-1

### ISSUE THREAD

**Issue by gotnone** [msys2/MINGW-packages#20119]
### Description / Steps to reproduce the issue

1. upgraded mingw-w64-ucrt-x86_64-libuv (1.46.0-1 -> 1.48.0-1)
2. Have a lua.init that is non-trivial.  E.g. kickstart.nvim
3. start nvim
4. Watch neovim segfault

### Expected behavior

A package upgrade -Syu should probably not cause your text editor to segfault.

### Actual behavior

Neovim segfaults.

I downloaded and installed an older version of libuv with `pacman -U` and that seems to fix the segfault issue.
```
downgraded mingw-w64-ucrt-x86_64-libuv (1.48.0-1 -> 1.47.0-1)
```

starting nvim --clean does not present the segfault issue, but it also makes neovim a lot less useful.

I don't know how to easily debug the location of the segfault.
```
(No debugging symbols found in C:/msys64/ucrt64/bin/nvim.exe)
```

Is it possible that a version mismatch between libuv and libluv is the cause of this problem?  Perhaps one of the public functions that libluv is relying upon in libuv was dropped in the upgrade of libuv from 1.47.0-1 -> 1.48.0-1.  I currently have libluv version 1.47.0-1 installed as that is the latest available to me.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> 2\. Have a lua.init that is non-trivial.  E.g. kickstart.nvim

Please explain this step.

**Comment by lazka** [comment]
I can confirm that rebuilding neovim fixes things

**Comment by Biswa96** [comment]
The latest neovim version is 0.9.5-3. It's in the queue https://packages.msys2.org/queue
