### ISSUE TITLE
Build mingw-w64-karchive-qt5 for mingw32

### ISSUE THREAD

**Issue by lmoureaux** [msys2/MINGW-packages#20118]
### Package name

mingw-w64-karchive-qt5

### For which environment do you need the package?

MINGW32

### Provide a brief description why you need this package in the selected environment

We use your builds in [Freeciv21](https://github.com/longturn/freeciv21) releases. Would be great if you could bring it back :)

Our [download stats](https://somsubhra.github.io/github-release-stats/?username=longturn&repository=freeciv21&page=1&per_page=20) indicate that anywhere between 10 and 25% of downloads are 32 bits.

### Are you willing to submit a PR?

yes

**Comment by Biswa96** [comment]
No.

**Comment by lmoureaux** [comment]
Quoting from there:

> Tell us which packages that were removed you still need, so we can consider reinstating them. Please use the [issue template](https://github.com/msys2/MINGW-packages/issues/new?assignees=&labels=package-request&projects=&template=environment_request.yml&title=Build+%5Bpackage+name%5D+for+%5Benvironment%5D) to file your request.

Thanks for the detailed answer...

**Comment by MehdiChinoune** [comment]
The maintainer of this package decided to drop it.
We are phasing out 32-bit, that's it. Prepare for more 32-bit packages to be dropped.
