### ISSUE TITLE
Cannot find GCC 11.3 package

### ISSUE THREAD

**Issue by TomaszHID** [msys2/MINGW-packages#20135]
### Package name

-	mingw-w64-x86_64-gcc-xxx-11.3.0-2-any.pkg.tar.zstt

### Brief description of package

I need to downgrade the GCC 13.2.0 to 11.3.0. I have found the following link to similar issue…
https://github.com/msys2/MINGW-packages/issues/11730
My problem is, that on the page below…
https://repo.msys2.org/mingw/mingw64/
...I cannot find the following GCC packages with their respective 11.3.0 versions:
-	mingw-w64-x86_64-gcc-11.3.0-2-any.pkg.tar.zst
-	mingw-w64-x86_64-gcc-libs-11.3.0-2-any.pkg.tar.zst
-	mingw-w64-x86_64-gcc-libgfortran-11.3.0-2-any.pkg.tar.zst
-	mingw-w64-x86_64-gcc-ada-11.3.0-2-any.pkg.tar.zst
-	mingw-w64-x86_64-gcc-fortran-11.3.0-2-any.pkg.tar.zst
-	mingw-w64-x86_64-gcc-objc-11.3.0-2-any.pkg.tar.zst
-	mingw-w64-x86_64-libgccjit-11.3.0-2-any.pkg.tar.zst

### URL for package's homepage

https://repo.msys2.org/mingw/mingw64/

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
MSYS2 is a rolling based platorrm It only offers latest versions.
gcc-11.3.0 files were removed because packages are only kept for 1.5 years after they removed from package databases.

**Comment by MartinEesmaa** [comment]
Hi, @TomaszHID. I tried to find GCC 11.3 package that you requested, but it's already deleted after 1.5 years said by @MehdiChinoune. Also, looked up for my SSD, I already deleted that I thought it's going to keep GCC 11.3.0 archive file.

On web.archive.org (https://web.archive.org/web/20230204091512/https://repo.msys2.org/mingw/mingw64/), I get only partially file like 1MB when downloading GCC 11.3.0 base, cause Web Archive may leave some partial files for carrying too much archive files some reasons.

I tried to compile GCC with past commit: https://github.com/msys2/MINGW-packages/blob/fc660082fabe2181cae188cb10a99566d8301768/mingw-w64-gcc/PKGBUILD
but it returned error 2 for unknown reason.

Three maintainers has GCC 11.3 build available for you to download it of three different builds:
https://sourceforge.net/projects/gcc-win64/files/11.3.0/
https://github.com/xpack-dev-tools/mingw-w64-gcc-xpack/releases/tag/v11.3.0-1
https://github.com/brechtsanders/winlibs_mingw/releases/download/11.3.0-14.0.3-10.0.0-ucrt-r3/winlibs-x86_64-posix-seh-gcc-11.3.0-mingw-w64ucrt-10.0.0-r3.7z, you can look https://winlibs.com for more information if you want do.

After downloading any build of one compressed file, you can decompress into C:\msys64\mingw64. Before doing this, it may be good idea to backup whole mingw64 folder for just in case, for example FFmpeg does not load when it's already compiled on GCC 13.2 latest after it's decompressed GCC 11.3.

Any questions or issues, feel free to let me know.

Thank you! :)

- Martin Eesmaa
