### ISSUE TITLE
[Kicad] update to 8.0

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MINGW-packages#20139]
### Package name

Kicad

### New version number

8.0

### Other information that may be useful

Kicad is gonna get a new release pretty soon!

**Comment by Kreijstal** [comment]
at the end of february, in 9 days

**Comment by Kreijstal** [comment]
8.0 has been released, I managed to update the pkgbuild but I have no idea how to fix the clang issue
https://github.com/kreijstal-contributions/MINGW-packages/actions/runs/8116547863/job/22186830838
it builds and runs on ucrt64 and mingw64

**Comment by oltolm** [comment]
You need to apply this https://github.com/lazka/MINGW-packages/blob/master/mingw-w64-fmt/0001-no-private-clang-header.patch patch to the fmt included in Kicad.

**Comment by Kreijstal** [comment]
> You need to apply this https://github.com/lazka/MINGW-packages/blob/master/mingw-w64-fmt/0001-no-private-clang-header.patch patch to the fmt included in Kicad.

Wow thank you!, I wonder is it okay to simply use our version instead of patching it?

**Comment by Kreijstal** [comment]
so oltolm suggestion worked, but then an even more esoteric error popped up

```
FAILED: gerbview/CMakeFiles/gerbview.dir/gerbview_rc.obj C:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-kicad/src/build-CLANG64/gerbview/CMakeFiles/gerbview.dir/gerbview_rc.obj
C:\Windows\system32\cmd.exe /C "cd /D C:\Users\topkek\scoop\persist\msys2\home\topkek\git\MINGW-packages\mingw-w64-kicad\src\build-CLANG64\gerbview && C:\Users\topkek\scoop\apps\msys2\2024-01-13\clang64\bin\windres.exe -IC:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-kicad/src/kicad-8.0.0/gerbview -IC:/Users/topkek/scoop/apps/msys2/2024-01-13/clang64/lib/wx/include/msw-unicode-3.2 -IC:/Users/topkek/scoop/apps/msys2/2024-01-13/clang64/include/wx-3.2 -IC:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-kicad/src/kicad-8.0.0/resources/msw/ -IC:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-kicad/src/build-CLANG64/ -DKICAD_BUILD_ARCH=x64 -iC:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-kicad/src/kicad-8.0.0/resources/msw/gerbview.rc -oC:/Users/topkek/scoop/persist/msys2/home/topkek/git/MINGW-packages/mingw-w64-kicad/src/build-CLANG64/gerbview/CMakeFiles/gerbview.dir/gerbview_rc.obj"
llvm-rc: Error in 24 statement (ID 1):
Is a directory
[1051/1661] Building CXX object pcbnew/CMakeFiles/pcbnew_kiface_objects.dir/microwave/microwave_inductor.cpp.obj
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...

```
as seen here https://github.com/kreijstal-contributions/MINGW-packages/actions/runs/8119374049/job/22195181538
somewhere  somehow cmd.exe is being called when compiling from clang.

**Comment by hmartinez82** [comment]
I'll take a look soon™️

**Comment by oltolm** [comment]
You probably need to fix `006-ki-6.0-rewrite-kiwin32_rc_for_clang.patch` instead of deleting it.

**Comment by Kreijstal** [comment]
> You probably need to fix `006-ki-6.0-rewrite-kiwin32_rc_for_clang.patch` instead of deleting it.

I would but I don't understand the patch or what it does so this is beyond me :)

**Comment by hmartinez82** [comment]
Ok. I'm going to take a look now.

**Comment by hmartinez82** [comment]
@oltolm That was the missing piece. Of course the patch to be very reworked for kicad 8 
@Kreijstal I cherry-picked your commit so you get credits for most of the work at https://github.com/msys2/MINGW-packages/pull/20248 ;-)
