### ISSUE TITLE
Is this a `libicu` bug, or am I using it incorrectly?

### ISSUE THREAD

**Issue by iahung3** [msys2/MINGW-packages#20154]
### Discussed in https://github.com/msys2/MINGW-packages/discussions/20147

<div type='discussions-op-text'>

<sup>Originally posted by **iahung3** February 23, 2024</sup>
```
#include <stdio.h>
#include <stdlib.h>
#include <unicode/ustring.h>

void print_hex_u8(const char *const str) {
	for (size_t i = 0; i < strlen(str); ++i) {
		printf("%02x ", (unsigned char) str[i]);
	}
	printf("\n");
}

void print_hex_u16(const char16_t *const str, size_t str_len) {
	for (size_t i = 0; i < str_len; ++i) {
		printf("%02x ", str[i]);
	}
	printf("\n");
}

int main(void) {
	char[] u8str = "Здравствуйте";
	int u16str_len;
	UErrorCode error;
	u_strFromUTF8(NULL, 0, &u16str_len, u8str, -1, &error); // calculate u16str_len
	UChar* u16str = malloc(sizeof(UChar) * (u16str_len + 1));
	u_strFromUTF8(u16str, u16str_len + 1, &u16str_len, u8str, -1, &error); // actual conversion
	print_hex_u8(u8str);
	print_hex_u16(u16str, u16str_len);
	return 0;
}
```
</div>

**Comment by lazka** [comment]
Here is what I get (after fixing various compiler errors):

```
$ ./a.exe
d0 97 d0 b4 d1 80 d0 b0 d0 b2 d1 81 d1 82 d0 b2 d1 83 d0 b9 d1 82 d0 b5
00 50 52 4f 43 45 53 53 4f 52 5f 41
```

**Comment by iahung3** [comment]
> Here is what I get (after fixing various compiler errors):
> 
> ```
> $ ./a.exe
> d0 97 d0 b4 d1 80 d0 b0 d0 b2 d1 81 d1 82 d0 b2 d1 83 d0 b9 d1 82 d0 b5
> 00 50 52 4f 43 45 53 53 4f 52 5f 41
> ```

You said you fixed various compiler errors, so the code must be modified. Could you give me the code?

Btw, I posted more information in the discussion thread. Could you try to run the program multiple times to see if the results are the same? I am afraid each run will give a different result. Again, please have a look at the discussion thread.

The result of `print_hex_u16)` is not right to me. Try to decode the hex string `00 50 52 4f 43 45 53 53 4f 52 5f 41` in UTF-16 will give nonsense. But in UTF-8, it means something!

https://dencode.com/string/hex decodes the hex string to UTF-8 as `�PROCESSOR_A`, it sounds like an error message to me.

Something must be very wrong with your `libicu`.

p/s: Thank you very much for your help.

**Comment by lazka** [comment]
The first call apparently sets an U_BUFFER_OVERFLOW_ERROR, even if no destination is given and it just writes out the length. What's missing I think is that you have to reset error in that case before the next use:

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unicode/ustring.h>

void print_hex_u8(const char *const str) {
	for (size_t i = 0; i < strlen(str); ++i) {
		printf("%02x ", (unsigned char) str[i]);
	}
	printf("\n");
}

void print_hex_u16(const UChar *const str, size_t str_len) {
	for (size_t i = 0; i < str_len; ++i) {
		printf("%02x ", str[i]);
	}
	printf("\n");
}

int main(void) {
	const char* u8str = "Здравствуйте";
	int32_t u16str_len = 0;
	UErrorCode error = U_ZERO_ERROR;
	u_strFromUTF8(NULL, 0, &u16str_len, u8str, -1, &error); // calculate u16str_len
	error = U_ZERO_ERROR;
	UChar* u16str = malloc(sizeof(UChar) * (u16str_len + 1));
	u_strFromUTF8(u16str, u16str_len + 1, &u16str_len, u8str, -1, &error); // actual conversion
	print_hex_u8(u8str);
	print_hex_u16(u16str, u16str_len);
	return 0;
}
```

**Comment by iahung3** [comment]
In real code I do have error handling, but I use `U_SUCCESS`. Btw, thank you very much. Even though `libicu` is said to be the industrial standard, finding the examples for it in C is very hard. They mostly use C++.
