### ISSUE TITLE
Trellix Endpoint Security detects trojan "rdn/genericu" in package mingw-w64-i686-gettext-tools 0.22.5-2 (msgcat.exe)

### ISSUE THREAD

**Issue by ThaFireDragonOfDeath** [msys2/MINGW-packages#20185]
Installing the MSYS2 package "mingw-w64-i686-gettext-tools-0.22.5-2-any.pkg.tar.zst" causes a virus alert in Trellix Endpoint Security (aka. McAfee). The file "msgcat.exe" is labeled as trojan "rdn/genericu".

It seams that this is a false positive since nearly all other anti virus programs report the same file as clean (see VirusTotal report at https://www.virustotal.com/gui/file/bef548e8a693a8e6f438056c38ff2c831272fb59c824b121f895b9406feb329d).
The package "mingw-w64-x86_64-gettext-tools-0.22.5-2-any.pkg.tar.zst" isn't affected and passes the AV scan without problems (VirusTotal report: https://www.virustotal.com/gui/file/fa56c4d7b918924a2a46917628c8e4e13676e1ac46244b4463333b6ac690199f).

We're trying to get that issue solved with Trellix.
Please let me know if this isn't a false positive.

**Comment by MehdiChinoune** [comment]
We got many reports about many packages being detected as a trojen. MSYS2/MinGW-w64 packages are built from source.

**Comment by ThaFireDragonOfDeath** [comment]
Problem is now fixed. We've reported the file to Trellix as false positive.
Now msgcat.exe isn't detected as malware anymore.
