### ISSUE TITLE
Build rtmidi and libslirp for mingw32

### ISSUE THREAD

**Issue by OBattler** [msys2/MINGW-packages#20191]
### Package name

rtmidi and libslirp

### Brief description of package

We need these packages to build 32-bit builds of 86Box. We rely on RTMIDI for MIDI input and output and on libslirp for networking.

### MINGW environments where you need the package

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
IIRC, you asked for a time for a transition to 64-bit (https://github.com/msys2/MINGW-packages/issues/19200#issuecomment-1849443737). Isn't 3 months enough.

**Comment by OBattler** [comment]
> IIRC, you asked for a time for a transition to 64-bit ([#19200 (comment)](https://github.com/msys2/MINGW-packages/issues/19200#issuecomment-1849443737)). Isn't 3 months enough.

I do most of the work on the project alone and I have a lot of other work to do on it on top of that. I already work on the project so much that I nearly burned out earlier this month and put my health at risk. Also, it's not even been 3 month since then but 2 months and a half. So no, I haven't had the opportunity to do it yet. I'm doing it now (I had to set aside all the other planned work) because you've begun pulling the rug from under our feet.

**Comment by OBattler** [comment]
Also, what I asked for in my post there was a timeframe of when MSYS2 plans to remove 32-bit packages so we knew by when we have to be ready. That was not given.

**Comment by MehdiChinoune** [comment]
We said we are slowly phasing out 32-bit, so expect anu package to be dropped at any time. Except toolchains and some essential packages like qt5-base, declarative, svg,and tools, boost, ffmpeg...etc

**Comment by maron2000** [comment]
Is dropping 32bit libraries **at any time** a official stand point of MSYS2?
I don't think the official news release say so, at least you should start from what is not used.
Also it mentions that some consideration will be made if the library is still used.

DOSBox-X also uses 32bit libslirp library, so I appreciate your generous consideration.

```
2023-12-13 - Starting to drop some 32-bit Packages
Three years ago we dropped 32-bit Windows support for running MSYS2 itself, now we are taking the next step and slowly starting to reduce the number of 32-bit packages, meaning the packages for the MINGW32 and CLANG32 environments. The goal of the phase-out is to reduce maintenance costs and server resources while not affecting most users. The focus will be on packages that aren't likely to see much use anyway, or where 64-bit alternatives are available and viable:

Packages which are likely not used outside of MSYS2 (re-packaged)
End-user applications which are likely not used outside of MSYS2 (GUI apps, ...)
Packages for resource intensive work where most external users are likely already on 64-bit (some scientific packages, ...)
Leaf packages with complex and resource intensive builds that are likely not used
New leaf packages
To find out if a package you have installed is affected you can run pacman -Qm which lists all installed packages which are no longer available in the repo. Ideally not many people should notice these changes, but in case they affect you:

Switch your workflow to use 64-bit packages instead ;)
Tell us which packages that were removed you still need, so we can consider reinstating them. Please use the issue template to file your request.
```

**Comment by MehdiChinoune** [comment]
> DOSBox-X also uses 32bit libslirp library, so I appreciate your generous consideration.

I am just a contributor, other contributors have other points of view.
Probably someone will enable them for you.

**Comment by MehdiChinoune** [comment]
I see all 86box msys2 fail in your repo actions, you could disable that by adding `fail-fast: false`.

I am not going to restore any mingw32 package unless there is a vaid reason for that.
- the app/library couldn't run/be built against 64-bit
- you have a significant userbase with windows>=8.1 32-bit (>5% with a proof).

If you have some performance issues then you should start working it.

**Comment by OBattler** [comment]
> I am not going to restore any mingw32 package unless there is a vaid reason for that.

I thought you said you were just a contributor? Why, then, do you behave as if you own this proejct?

>     * you have a significant userbase with windows>=8.1 32-bit running it on a 32-bit only CPU (which is impossible because Windows 7 requires sse2 instruction that only exists on 64-bit CPUs).

Windows 7, at least SP0, absolutely does not require sse2, or even the original sse. The 32-bit version of SP0 works on 86Box itself, even on a Pentium. And as for 8.x and later - you do realize 32-bit versions of 8.x and 10 exist, right? Now yes, 86Box does require sse2, but sse2 was added by the original Pentium 4 (Willamette) which was, I can assure you, 32-bit only. The Northwood Pentium 4 I had 14 years ago also supported sse2 and was 32-bit only. And then there's the early Core series that also for a while included 32-but only CPU's as well.

> If you have some performance issues then you should start working it.

To completely get rid of them, I would have to write a completely new dynamic recompiler. Which would take at least a year before it's polished to anywhere near the level of the current ones.

**Comment by MehdiChinoune** [comment]
> I thought you said you were just a contributor? Why, then, do you behave as if you own this proejct?

I was talking to the one who ask me to responsible and restore it.
As I said above I am just a contributor I can't decide whether a package should be restored or not, but I am not going to restore any unless those conditions.

**Comment by OBattler** [comment]
> As I said above I am just a contributor I can't decide whether a package should be restored or not, but I am not going to restore any unless those conditions.

You realize that this sentence contradicts itself? You say you're just a contributor and can't decide, but at the same time, you're imposing conditions on when you're going to restore a package.

**Comment by MehdiChinoune** [comment]
There is no contradiction, other contributors could restore them, so I couldn't speak on behalf of them.
I am talking about myself.

**Comment by MehdiChinoune** [comment]
> To completely get rid of them, I would have to write a completely new dynamic recompiler. Which would take at least a year before it's polished to anywhere 

That's your fault, apps and libraries started porting to 64bit since more than 15 years.

**Comment by OBattler** [comment]
> > To completely get rid of them, I would have to write a completely new dynamic recompiler. Which would take at least a year before it's polished to anywhere
> 
> That's your fault, apps and libraries started porting to 64bit since more than 15 years.

It's not my fault. My program is a fork of another program (PCem) and that didn'thave a 64-bit dynamic recompiler (or any kind of dynamic recompiler at all) until 2015. It took me several years to familiarize myself enough with the recompiler's code to even just be able to fix bugs.

Not to mention that I wasn't developing this emulator 15 years ago and it's not my fault that the developer of the project I forked from, always treated 64-bit as secondary to 32-bit.

And again, I did have a new recompiler in the plans already, but it's not like I have no other work to do on the emulator, or a life outside the emulator, you know?

**Comment by OBattler** [comment]
Also, would you be able to bring here someone who is actually in chage of this project? Because given that you are, as you say, just a user, I don't think you're the one I should be discussing this with.

**Comment by maron2000** [comment]
Regardless of the discussions, I am now trying to build 32bit version library on my own.
I followed the direction and managed to build the package.
```
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: git make base-devel mingw-w64-i686-toolchain mingw-w64-i686-libtool mingw-w64-i686-nasm autoconf automake mingw-w64-i686-ncurses mingw-w64-i686-binutils
      - name: Install libslirp
        run: |
          top=`pwd`
          mkdir pkg
          cd pkg
          git clone https://github.com/msys2/MINGW-packages.git
          cd MINGW-packages
          cd mingw-w64-libslirp
          sed -i -e "s/^mingw_arch=\(.*\)/mingw_arch=(\'mingw32\')/" PKGBUILD
          MINGW_ARCH=mingw32 makepkg-mingw -sLf --noconfirm
          pacman --noconfirm -U mingw-w64-*-any.pkg.tar.zst
          pacman -Syu
```
I think(?) the library is properly built.
```
2024-03-02T01:56:06.7942572Z ==> Tidying install...
2024-03-02T01:56:06.8083694Z   -> Removing libtool files...
2024-03-02T01:56:06.8453242Z   -> Purging unwanted files...
2024-03-02T01:56:06.9259096Z   -> Stripping unneeded symbols from binaries and libraries...
2024-03-02T01:56:07.4970858Z   -> Compressing man and info pages...
2024-03-02T01:56:07.5349238Z ==> Checking for packaging issues...
2024-03-02T01:56:07.7665575Z ==> Creating package "mingw-w64-i686-libslirp"...
2024-03-02T01:56:07.7868535Z   -> Generating .PKGINFO file...
2024-03-02T01:56:07.9079843Z   -> Generating .BUILDINFO file...
2024-03-02T01:56:08.8210012Z   -> Generating .MTREE file...
2024-03-02T01:56:08.8829921Z   -> Compressing package...
2024-03-02T01:56:09.2061692Z ==> Finished making: mingw-w64-libslirp 4.7.0-1 (Sat, Mar  2, 2024  1:56:09 AM)
2024-03-02T01:56:09.8665247Z loading packages...
2024-03-02T01:56:09.8665737Z resolving dependencies...
2024-03-02T01:56:09.8770029Z looking for conflicting packages...
2024-03-02T01:56:09.8874671Z 
2024-03-02T01:56:09.8875176Z Packages (1) mingw-w64-i686-libslirp-4.7.0-1
2024-03-02T01:56:09.8875509Z 
2024-03-02T01:56:09.8875645Z Total Installed Size:  0.43 MiB
2024-03-02T01:56:09.8875892Z 
2024-03-02T01:56:09.8876098Z :: Proceed with installation? [Y/n] 
2024-03-02T01:56:09.8876744Z checking keyring...
2024-03-02T01:56:09.8877256Z checking package integrity...
2024-03-02T01:56:09.8877605Z loading package files...
2024-03-02T01:56:09.8877923Z checking for file conflicts...
2024-03-02T01:56:09.8891949Z :: Processing package changes...
2024-03-02T01:56:09.8892620Z installing mingw-w64-i686-libslirp...
```

So I build my software with the libslirp package installed, it builds fine until the ld.exe links libslirp by `-lslirp -lglib-2.0`, I get tons of errors. The following is a part of it.
```
2024-03-02T08:04:19.5549532Z D:/a/_temp/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/a/_temp/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../lib\libslirp.a(src_slirp.c.obj):(.text+0x14f): undefined reference to `_imp__g_getenv'
2024-03-02T08:04:19.5552321Z D:/a/_temp/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/a/_temp/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../lib\libslirp.a(src_slirp.c.obj):(.text+0x1c0): undefined reference to `_imp__g_parse_debug_string'
2024-03-02T08:04:19.5555133Z D:/a/_temp/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/a/_temp/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../lib\libslirp.a(src_slirp.c.obj):(.text+0x45d): undefined reference to `_imp__g_log'
2024-03-02T08:04:19.5557728Z D:/a/_temp/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/a/_temp/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../lib\libslirp.a(src_slirp.c.obj):(.text+0x48a): undefined reference to `_imp__g_log'
```
If I install the existing final 32-bit version package, instead of using the package I built on my own, the software compiles and links fine.
```
pacman --noconfirm -U https://repo.msys2.org/mingw/mingw32/mingw-w64-i686-libslirp-4.7.0-1-any.pkg.tar.zst
```
I think there is a problem in my procedures, can I ask someone for help?
Any advises are welcome. Thanks in advance.

**Comment by MehdiChinoune** [comment]
you could download the package and install it from https://repo.msys2.org/mingw/mingw32

**Comment by maron2000** [comment]
@MehdiChinoune Thanks for your information. Yes I know that, and I mentioned that above.
My question is regarding building the package on my own.

**Comment by maron2000** [comment]
@MehdiChinoune 
Maybe how you confirm building the 64bit package may help. Can you provide some information?

**Comment by MehdiChinoune** [comment]
We could look at it if you reproduce the issue with 64-bit, build your own and link against it.

**Comment by maron2000** [comment]
@MehdiChinoune 
May I ask if there are any difference with your procedures?

**Comment by Biswa96** [comment]
I can reproduce the issue after recompiling libslirp. I shall try to re-add mingw32 ones also. These are two small packages and could be added, IMO.

**Comment by maron2000** [comment]
Unfortunately, I got the same result for mingw64 as well.
I confirmed building with package installed by `pacman -S mingw-w64-x86_64-libslirp` works fine.
 
Here's my procedures.
```
runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool mingw-w64-x86_64-nasm autoconf automake
      - name: Install libslirp
        run: |
          top=`pwd`
          mkdir pkg
          cd pkg
          git clone https://github.com/msys2/MINGW-packages.git
          pwd
          cd MINGW-packages
          cd mingw-w64-libslirp
          MINGW_ARCH=mingw64 makepkg-mingw -sLf --noconfirm
          ls -lg
          pacman --noconfirm -U mingw-w64-*-any.pkg.tar.zst
```

```
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../lib\libslirp.a(src_slirp.c.obj):(.text+0x138): undefined reference to `__imp_g_getenv'
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../lib\libslirp.a(src_slirp.c.obj):(.text+0x1b5): undefined reference to `__imp_g_parse_debug_string'
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../lib\libslirp.a(src_slirp.c.obj):(.text+0x498): undefined reference to `__imp_g_log'
```

I'd like to add that compiler flags are added as below, using pkg-config.
```
    LIBS="$LIBS "`pkg-config slirp --libs`
    CFLAGS="$CFLAGS "`pkg-config slirp --cflags`
    CPPFLAGS="$CPPFLAGS "`pkg-config slirp --cflags`
```

I followed the procedures for building the package from the README of this repository.
As an alternative you can download or clone the package folder with the scripts to your machine and you build it for yourself, in whatever version you like.

```
Assuming you have a properly installed MSYS2 environment and build tools, 
you can build any package using the following command:

   cd ${package-name}
   MINGW_ARCH=mingw64 makepkg-mingw -sLf
```

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Comment by maron2000** [comment]
@Biswa96 Thank you for looking into this.
I manually copied PKGBUILD and build DOSBox-X 32-bit version and it built successfully.
So I personally don't need artifacts to test.

BTW, I understand your situation to reduce workloads by phasing out 32-bit libraries, but I personally feel that the criteria mentioned in the above conversation is too drastic compared to what was mentioned in the news release last December.
I know there are diverse way of thinking, but please consider the process of phasing out in a more moderate way, at least for a start.

**Comment by MehdiChinoune** [comment]
Just to clarify, That was my point of view, It doesn't represent MSYS2 project.
We agreed first to just keep toolchains and some GUI and common libraries and that's What I am trying to do.

**Comment by maron2000** [comment]
@MehdiChinoune I just want to say that if you say your opinion and MSYS officials are ifferent, that itself is okay.
But urging users your opinion will make users confused, such as what occured here.
Please carefully consider that.

**Comment by MehdiChinoune** [comment]
@maron2000 I was clear since the begenning, I told you I am just a contributor but you insisted on me for taking the responsability, so I told you my criteria.
The news says:
```
- Switch your workflow to use 64-bit packages instead ;)
- Tell us which packages that were removed you still need, so we can consider reinstating them.
Please use the [issue template](https://github.com/msys2/MINGW-packages/issues/new?assignees=&labels=package-request&projects=&template=environment_request.yml&title=Build+%5Bpackage+name%5D+for+%5Benvironment%5D) to file your request.
```
Q: Couldn't you switch to 64-bit?
A: yes you could.
So there is no need to ask for restoring 32-bit.
