### ISSUE TITLE
Build mingw-w64-i686-freetds for mingw32

### ISSUE THREAD

**Issue by swistak35** [msys2/MINGW-packages#20195]
### Package name

mingw-w64-i686-freetds

### For which environment do you need the package?

MINGW32

### Provide a brief description why you need this package in the selected environment

I'm building a software which for other reasons (other than the freetds package) still needs to stay 32-bit for a while, and I'm using msys2 in building process (CI/dev/building the package). If I can somehow workaround missing package (for example by installing the package somehow manually on my CI/dev environments), I'd be totally fine with that.

### Are you willing to submit a PR?

Yes

**Comment by MehdiChinoune** [comment]
Please specify those `other reasons`?

**Comment by swistak35** [comment]
Thanks, it's because we have other dependency in the same program which we are not yet certain whether it works correctly with 64-bit architecture. We're gonna test on 64-bit soon and hopefully in few months we wouldn't care about the 32-bit version of this package anymore.
