### ISSUE TITLE
Add GNOME Builder

### ISSUE THREAD

**Issue by iahung2** [msys2/MINGW-packages#20200]
### Package name

mingw-w64-gnome-builder

### Brief description of package

An IDE for GNOME

Builder is an actively developed Integrated Development Environment for GNOME. It combines integrated support for essential GNOME technologies such as GTK+, GLib, and GNOME APIs with features that any developer will appreciate, like syntax highlighting and snippets.

### URL for package's homepage

https://apps.gnome.org/Builder/

### Provide a basic test case to validate the package's functionality.

https://apps.gnome.org/Builder/

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by ZachBacon** [comment]
I don't think it's possible, primarily due to the fact it also tightly integrates flatpak stuff. And that's not really available to windows.

**Comment by iahung2** [comment]
> I don't think it's possible, primarily due to the fact it also tightly integrates flatpak stuff. And that's not really available to windows.

`flatpak` is only a package format. GNOME Builder is available in other package formats, too.

**Comment by ZachBacon** [comment]
> > I don't think it's possible, primarily due to the fact it also tightly integrates flatpak stuff. And that's not really available to windows.
> 
> `flatpak` is only a package format. GNOME Builder is available in other package formats, too.

You failed to grasp what I meant

**Comment by iahung2** [comment]
> > > I don't think it's possible, primarily due to the fact it also tightly integrates flatpak stuff. And that's not really available to windows.
> > 
> > 
> > `flatpak` is only a package format. GNOME Builder is available in other package formats, too.
> 
> You failed to grasp what I meant, functionality within builder makes use of flatpak functions, for building flatpaks.

I'm sorry. I need an IDE for Vala. It seems I need to look for something else.

**Comment by ZachBacon** [comment]
That said, I'm looking at the meson code, it's not showing a dependency for flatpak though.

**Comment by iahung2** [comment]
> That said, I'm looking at the meson code, it's not showing a dependency for flatpak though.

Yes. This must be the case. There are non-flatpak packages offered by Linux distributions.

**Comment by ZachBacon** [comment]
> > That said, I'm looking at the meson code, it's not showing a dependency for flatpak though.
> 
> Yes. This must be the case. There are non-flatpak packages offered by Linux distributions.

Again... Not what I'm talking about. I'm talking about that gnome-builder is used to make flatpak yamls and builds them 😅

**Comment by ZachBacon** [comment]
I'll give it a shot later today.

**Comment by wszqkzqk** [comment]
`flatpak` may not be important for this problem, the main problem is that GNOME Builder relies on `webkitgtk`, which may be very difficult to port.

See also:
https://github.com/msys2/MINGW-packages/issues/19965
https://github.com/msys2/MINGW-packages/pull/5375
https://github.com/msys2/MINGW-packages/discussions/9512#discussioncomment-2906753

**Comment by ZachBacon** [comment]
> `flatpak` may not be important for this problem, the main problem is that GNOME Builder relies on `webkitgtk`, which may be very difficult to port.
> 
> See also: #19965 #5375 [#9512 (comment)](https://github.com/msys2/MINGW-packages/discussions/9512#discussioncomment-2906753)

In the gnome-builder options you can disable WebKit support https://gitlab.gnome.org/GNOME/gnome-builder/-/blob/main/meson_options.txt?ref_type=heads#L18

**Comment by taozuhong** [comment]
> > > > I don't think it's possible, primarily due to the fact it also tightly integrates flatpak stuff. And that's not really available to windows.
> > > 
> > > 
> > > `flatpak` is only a package format. GNOME Builder is available in other package formats, too.
> > 
> > 
> > You failed to grasp what I meant, functionality within builder makes use of flatpak functions, for building flatpaks.
> 
> I'm sorry. I need an IDE for Vala. It seems I need to look for something else.

VSCode + Valac + Vala extenstion + Meson is a good choice for you.
