### ISSUE TITLE
octave 8.4.0 fails to build on clang64

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#20253]
### Description / Steps to reproduce the issue

build octave from its PKGBUILD

### Expected behavior

succeeds to build

### Actual behavior

fails to
```
    CXXLD    libgui/src/libgui-src.la
  clang++: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
  ld.lld: error: undefined symbol: pthread_mutex_lock
  >>> referenced by libgnu.a(libgnu_la-localename.o):(get_lcid)
  
  ld.lld: error: undefined symbol: pthread_mutex_unlock
  >>> referenced by libgnu.a(libgnu_la-localename.o):(get_lcid)
  >>> referenced by libgnu.a(libgnu_la-localename.o):(get_lcid)
  
  ld.lld: error: undefined symbol: pthread_mutexattr_init
  >>> referenced by libgnu.a(libgnu_la-lock.o):(glthread_recursive_lock_init_multithreaded)
  
  ld.lld: error: undefined symbol: pthread_mutexattr_settype
  >>> referenced by libgnu.a(libgnu_la-lock.o):(glthread_recursive_lock_init_multithreaded)
  
  ld.lld: error: undefined symbol: pthread_mutexattr_destroy
  >>> referenced by libgnu.a(libgnu_la-lock.o):(glthread_recursive_lock_init_multithreaded)
  >>> referenced by libgnu.a(libgnu_la-lock.o):(glthread_recursive_lock_init_multithreaded)
  
  ld.lld: error: undefined symbol: pthread_mutex_init
  >>> referenced by libgnu.a(libgnu_la-lock.o):(glthread_recursive_lock_init_multithreaded)
  
  ld.lld: error: undefined symbol: pthread_once
  >>> referenced by libgnu.a(libgnu_la-lock.o):(glthread_once_multithreaded)
  
  ld.lld: error: undefined symbol: pthread_getspecific
  >>> referenced by libgnu.a(libgnu_la-strsignal.o):(strsignal)
  
  ld.lld: error: undefined symbol: pthread_setspecific
  >>> referenced by libgnu.a(libgnu_la-strsignal.o):(strsignal)
  >>> referenced by libgnu.a(libgnu_la-strsignal.o):(free_key_mem)
  
  ld.lld: error: undefined symbol: pthread_key_create
  >>> referenced by libgnu.a(libgnu_la-strsignal.o):(init)
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  make[2]: *** [Makefile:14209: liboctave/liboctave.la] Error 1
  make[2]: Leaving directory '/C/_/B/src/build-CLANG64'
  make[1]: *** [Makefile:27672: all-recursive] Error 1
  make[1]: Leaving directory '/C/_/B/src/build-CLANG64'
  make: *** [Makefile:11062: all] Error 2
  ==> ERROR: A failure occurred in build().
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Maybe!

**Comment by mmuetzel** [comment]
The current head of the Octave repository builds in the CLANG64 environment of MSYS2 in CI tests. A new major version of Octave is going to be released probably pretty soon.
Is this build error blocking some issue for you? If it is, which? Would it be ok to wait for Octave 9?

**Comment by MehdiChinoune** [comment]
I am waiting for https://github.com/mfem/mfem/issues/4169 to be fixed first, so I could update sundials to 7.0.0 and rebuild octave against it.

**Comment by mmuetzel** [comment]
Octave is currently not compatible to SUNDIALS 7.
See: https://savannah.gnu.org/bugs/index.php?65392

I hope that Octave 9 will be able to use it.

**Comment by MehdiChinoune** [comment]
your changes https://hg.savannah.gnu.org/hgweb/octave/raw-rev/2c8ade2c7491 could be applied on 8.4.0

**Comment by mmuetzel** [comment]
Please, wait until this is tested a bit more than by just one single user (i.e., me).

See #20254 for the PKGBUILD that I used for those tests.

**Comment by mmuetzel** [comment]
Additionally: I had to install MSMPI from Microsoft locally (even if Octave doesn't actually use MPI). Without it, the SUNDIALS libraries wouldn't load.

Would it be possible to package a version of SUNDIALS that does not depend on MSMPI?

**Comment by MehdiChinoune** [comment]
I was going to propose that.

**Comment by hmartinez82** [comment]
We already do that in MSYS2, right? https://github.com/msys2/MINGW-packages/blob/4160aba35c03a976f31a9bbc1ac5cb2e8b556930/mingw-w64-sundials/PKGBUILD#L81

**Comment by mmuetzel** [comment]
> We already do that in MSYS2, right? https://github.com/msys2/MINGW-packages/blob/4160aba35c03a976f31a9bbc1ac5cb2e8b556930/mingw-w64-sundials/PKGBUILD#L81

Correct. But that's only for aarch64 afaict.
I don't know if we'd still need a variant with MPI for i686 and x86_64.
For Octave, we wouldn't need MPI for any target. I can't speak for other dependers.

**Comment by MehdiChinoune** [comment]
MPI is only required for those scintific apps that doesn't use OpenMP (or something similar) for multi-core computing.

**Comment by mmuetzel** [comment]
> MPI is only required for those scintific apps that doesn't use OpenMP (or something similar) for multi-core computing.

Does that mean that we could remove MSMPI from the dependencies of SUNDIALS?

**Comment by MehdiChinoune** [comment]
I think so.

**Comment by MehdiChinoune** [comment]
Octave still fails to build on clang64 against flang-18

**Comment by mmuetzel** [comment]
> Octave still fails to build on clang64 against flang-18

Like I mentioned in your PR: I am working on an update for the build rule of Octave.
