### ISSUE TITLE
Problem with package mingw-w64-headers-git 

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MINGW-packages#20284]
### Description / Steps to reproduce the issue

install package mingw-w64-headers-git 
and include `ddk/ntddk.h` on your file.

### Expected behavior

including `ddk/ntddk.h` shouldn't error out considering the file `wdm.h` is part of the package already. so it should be include <ddk/wmd.h> and not <wmd.h>

### Actual behavior

```
# make
gcc -Wall    -c -o drvtest.o drvtest.c
In file included from drvtest.c:11:
C:/ucrt64/include/ddk/ntddk.h:38:10: fatal error: wdm.h: No such file or directory
   38 | #include <wdm.h>
      |          ^~~~~~~
compilation terminated.
make: *** [<builtin>: drvtest.o] Error 1
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Sure

**Comment by Biswa96** [comment]
Include the header directory with `-Iddk`. Also, those headers are for kernel driver development and not tested properly.

**Comment by Kreijstal** [comment]
> Include the header directory with `-Iddk`. Also, those headers are for kernel driver development and not tested properly.

It seems you have to explicitly do -I/ucrt64/include/ddk  -Iddk won't do it.
