### ISSUE TITLE
fix Luajit module search path

### ISSUE THREAD

**Issue by FractalU** [msys2/MINGW-packages#20297]
### Description / Steps to reproduce the issue

Since Luajit has been updated to rolling releases, the luajit directory has been changed from `luajit-2.1.0-beta3` to `luajit-2.1`. Unfortunately, the patch file `003-lua51-modules-paths.patch` hasn't been updated to adopt the change of the directory name. That means, that the non-existent `luajit-2.1.0-beta3` directory is still in the module search path. @sewbacca already reported this in https://github.com/msys2/MINGW-packages/issues/16618#issuecomment-1953908814. He is the one that noticed this issue.

### Expected behavior

In file [/mingw-w64-luajit/003-lua51-modules-paths.patch](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-luajit/003-lua51-modules-paths.patch) at line 15
```
+#define LUAJIT_LDIR	"!\\..\\share\\luajit-2.1\\"
```

### Actual behavior

In file [/mingw-w64-luajit/003-lua51-modules-paths.patch](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-luajit/003-lua51-modules-paths.patch) at line 15
```
+#define LUAJIT_LDIR	"!\\..\\share\\luajit-2.1.0-beta3\\"
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

no

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to review the change please?

**Comment by FractalU** [comment]
@Biswa96 I reviewed the updated package. The bug has been fixed.
