### ISSUE TITLE
msys2 installation protobuf-c has no return value.

### ISSUE THREAD

**Issue by w345731923** [msys2/MINGW-packages#20330]
### Description / Steps to reproduce the issue

mingw64 mingw-w64-x86_64-protobuf 25.3-1 [installed]
mingw64 mingw-w64-x86_64-protobuf-c 1.5.0-3 [installed]

$ ./protoc-c --version
Return empty.

$ ldd ./protoc-c
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7ffa0a5b0000)
        KERNEL32.DLL => /c/Windows/system32/KERNEL32.DLL (0x7ffa098a0000)
        KERNELBASE.dll => /c/Windows/system32/KERNELBASE.dll (0x7ffa07a50000)
        msvcrt.dll => /c/Windows/system32/msvcrt.dll (0x7ffa07d40000)
        libabsl_log_internal_check_op-2401.0.0.dll => /mingw64/bin/libabsl_log_internal_check_op-2401.0.0.dll (0x7ffa03b90000)
        libabsl_log_internal_message-2401.0.0.dll => /mingw64/bin/libabsl_log_internal_message-2401.0.0.dll (0x7ffa03980000)
        libabsl_raw_hash_set-2401.0.0.dll => /mingw64/bin/libabsl_raw_hash_set-2401.0.0.dll (0x7ffa03b80000)
        libabsl_raw_logging_internal-2401.0.0.dll => /mingw64/bin/libabsl_raw_logging_internal-2401.0.0.dll (0x7ffa02db0000)
        libabsl_spinlock_wait-2401.0.0.dll => /mingw64/bin/libabsl_spinlock_wait-2401.0.0.dll (0x7ffa03020000)
        libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x7ffa02c10000)
        libprotobuf.dll => /mingw64/bin/libprotobuf.dll (0x7ff9fc5c0000)
        libprotoc.dll => /mingw64/bin/libprotoc.dll (0x7ff9fc8f0000)
        libstdc++-6.dll => /mingw64/bin/libstdc++-6.dll (0x7ff9f8f50000)
        libabsl_log_internal_nullguard-2401.0.0.dll => /mingw64/bin/libabsl_log_internal_nullguard-2401.0.0.dll (0x7ffa02da0000)
        libabsl_strings-2401.0.0.dll => /mingw64/bin/libabsl_strings-2401.0.0.dll (0x7ffa01850000)
        libabsl_base-2401.0.0.dll => /mingw64/bin/libabsl_base-2401.0.0.dll (0x7ffa01840000)
        libabsl_hash-2401.0.0.dll => /mingw64/bin/libabsl_hash-2401.0.0.dll (0x7ffa01830000)
        ADVAPI32.dll => /c/Windows/system32/ADVAPI32.dll (0x7ffa0a0e0000)
        sechost.dll => /c/Windows/system32/sechost.dll (0x7ffa07e50000)
        libabsl_strerror-2401.0.0.dll => /mingw64/bin/libabsl_strerror-2401.0.0.dll (0x7ffa01810000)
        RPCRT4.dll => /c/Windows/system32/RPCRT4.dll (0x7ffa09fa0000)
        libabsl_examine_stack-2401.0.0.dll => /mingw64/bin/libabsl_examine_stack-2401.0.0.dll (0x7ffa017f0000)
        libabsl_log_globals-2401.0.0.dll => /mingw64/bin/libabsl_log_globals-2401.0.0.dll (0x7ffa017e0000)
        libabsl_log_internal_format-2401.0.0.dll => /mingw64/bin/libabsl_log_internal_format-2401.0.0.dll (0x7ffa017d0000)
        libabsl_log_internal_log_sink_set-2401.0.0.dll => /mingw64/bin/libabsl_log_internal_log_sink_set-2401.0.0.dll (0x7ffa017c0000)
        libabsl_log_internal_globals-2401.0.0.dll => /mingw64/bin/libabsl_log_internal_globals-2401.0.0.dll (0x7ffa017b0000)
        libabsl_log_internal_proto-2401.0.0.dll => /mingw64/bin/libabsl_log_internal_proto-2401.0.0.dll (0x7ffa017a0000)
        libabsl_time-2401.0.0.dll => /mingw64/bin/libabsl_time-2401.0.0.dll (0x7ffa01780000)
        libabsl_cord-2401.0.0.dll => /mingw64/bin/libabsl_cord-2401.0.0.dll (0x7ff9ff8c0000)
        libwinpthread-1.dll => /mingw64/bin/libwinpthread-1.dll (0x7ff9ff8a0000)
        libabsl_cordz_info-2401.0.0.dll => /mingw64/bin/libabsl_cordz_info-2401.0.0.dll (0x7ffa01770000)
        libabsl_die_if_null-2401.0.0.dll => /mingw64/bin/libabsl_die_if_null-2401.0.0.dll (0x7ffa01710000)
        libabsl_log_internal_conditions-2401.0.0.dll => /mingw64/bin/libabsl_log_internal_conditions-2401.0.0.dll (0x7ffa01440000)
        libabsl_status-2401.0.0.dll => /mingw64/bin/libabsl_status-2401.0.0.dll (0x7ff9ff880000)
        libabsl_statusor-2401.0.0.dll => /mingw64/bin/libabsl_statusor-2401.0.0.dll (0x7ff9ff3f0000)
        libabsl_synchronization-2401.0.0.dll => /mingw64/bin/libabsl_synchronization-2401.0.0.dll (0x7ff9fea10000)
        libabsl_str_format_internal-2401.0.0.dll => /mingw64/bin/libabsl_str_format_internal-2401.0.0.dll (0x7ff9fcee0000)
        libabsl_throw_delegate-2401.0.0.dll => /mingw64/bin/libabsl_throw_delegate-2401.0.0.dll (0x7ff9fd760000)
        libabsl_time_zone-2401.0.0.dll => /mingw64/bin/libabsl_time_zone-2401.0.0.dll (0x7ff9fceb0000)
        zlib1.dll => /mingw64/bin/zlib1.dll (0x7ff9fce80000)
        libabsl_strings_internal-2401.0.0.dll => /mingw64/bin/libabsl_strings_internal-2401.0.0.dll (0x7ff9fd230000)
        libabsl_city-2401.0.0.dll => /mingw64/bin/libabsl_city-2401.0.0.dll (0x7ff9fcfb0000)
        libabsl_low_level_hash-2401.0.0.dll => /mingw64/bin/libabsl_low_level_hash-2401.0.0.dll (0x7ff9fcfa0000)
        libabsl_stacktrace-2401.0.0.dll => /mingw64/bin/libabsl_stacktrace-2401.0.0.dll (0x7ff9fce70000)
        libabsl_symbolize-2401.0.0.dll => /mingw64/bin/libabsl_symbolize-2401.0.0.dll (0x7ff9fce60000)
        libabsl_log_sink-2401.0.0.dll => /mingw64/bin/libabsl_log_sink-2401.0.0.dll (0x7ff9fce50000)
        libabsl_int128-2401.0.0.dll => /mingw64/bin/libabsl_int128-2401.0.0.dll (0x7ff9fce40000)
        libabsl_cord_internal-2401.0.0.dll => /mingw64/bin/libabsl_cord_internal-2401.0.0.dll (0x7ff9fce20000)
        libabsl_crc_cord_state-2401.0.0.dll => /mingw64/bin/libabsl_crc_cord_state-2401.0.0.dll (0x7ff9fce10000)
        libabsl_cordz_handle-2401.0.0.dll => /mingw64/bin/libabsl_cordz_handle-2401.0.0.dll (0x7ff9fce00000)
        libabsl_malloc_internal-2401.0.0.dll => /mingw64/bin/libabsl_malloc_internal-2401.0.0.dll (0x7ff9fc5b0000)
        libabsl_kernel_timeout_internal-2401.0.0.dll => /mingw64/bin/libabsl_kernel_timeout_internal-2401.0.0.dll (0x7ff9fc5a0000)
        dbghelp.dll => /c/Windows/SYSTEM32/dbghelp.dll (0x7ffa01130000)
        libabsl_crc32c-2401.0.0.dll => /mingw64/bin/libabsl_crc32c-2401.0.0.dll (0x7ff9fc590000)
        libabsl_crc_internal-2401.0.0.dll => /mingw64/bin/libabsl_crc_internal-2401.0.0.dll (0x7ff9fc580000)
All ldd dependent libraries exist.

### Expected behavior

./protoc-c --version
protobuf-c xxxx.xxx
libprotoc xxx.xxx

### Actual behavior

Return empty.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-10240 DESKTOP-K80CRRU 3.4.10.x86_64 

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

yes

**Comment by MehdiChinoune** [comment]
Where did you execute the command from?
You sould execute it from shell without `./`, just like
```shell
$ protoc-c --version
D:\Programs\msys64_test\clang64\bin\protoc-c: Unknown option: --version
```
protoc output:
```
$ protoc --version
libprotoc 25.3
```

**Comment by MehdiChinoune** [comment]
Where did you execute your command from?
Is it from MINGW64 shell or CMD or powershell?

**Comment by w345731923** [comment]
MINGW64 shell.

sougou@DESKTOP-K80CRRU MINGW64 ~
$ pacman -Sl|grep protobuf
clangarm64 mingw-w64-clang-aarch64-protobuf 25.3-1
clangarm64 mingw-w64-clang-aarch64-protobuf-c 1.5.0-3
clangarm64 mingw-w64-clang-aarch64-python-protobuf 4.25.3-1
mingw32 mingw-w64-i686-protobuf 25.3-1
mingw64 mingw-w64-x86_64-protobuf 25.3-1
mingw64 mingw-w64-x86_64-protobuf-c 1.5.0-3
mingw64 mingw-w64-x86_64-python-protobuf 4.25.3-1
ucrt64 mingw-w64-ucrt-x86_64-protobuf 25.3-1
ucrt64 mingw-w64-ucrt-x86_64-protobuf-c 1.5.0-3
ucrt64 mingw-w64-ucrt-x86_64-python-protobuf 4.25.3-1
clang32 mingw-w64-clang-i686-protobuf 25.3-1
clang32 mingw-w64-clang-i686-python-protobuf 4.25.3-1
clang64 mingw-w64-clang-x86_64-protobuf 25.3-1
clang64 mingw-w64-clang-x86_64-protobuf-c 1.5.0-3
clang64 mingw-w64-clang-x86_64-python-protobuf 4.25.3-1
msys protobuf 21.12-3
msys protobuf-devel 21.12-3

pacman -S mingw-w64-x86_64-protobuf-c

$ protoc-c --version
C:\msys64\mingw64\bin\protoc-c: Unknown option: --version

Expected behavior
protoc-c --version
protobuf-c xxxx.xxx
libprotoc xxx.xxx

**Comment by w345731923** [comment]
`
$ protoc --version
libprotoc 25.3
`

Thank you for your answer, it gave me inspiration.
When compiling postgis with win, protoc should be used.

**Comment by w345731923** [comment]
Solved.
