### ISSUE TITLE
Missing definitions of "IID_IPinConnection" and "IID_IPinFlowControl" in strmif.h

### ISSUE THREAD

**Issue by JaFojtik** [msys2/MINGW-packages#20352]
The declaration is present in srtmif.h, but the definition stub is not present. "IID_IPinConnection" could not be found anywhere else.

It is also interesting that -lstrmiids does not add a requested symbol.

The GUID definition must be added from a code.

```
//https://stackoverflow.com/questions/72207562/where-is-the-library-for-guid-in-win32
#include <Initguid.h>

#include <strmif.h>
#include <control.h>		// `IID_IMediaControl'
//#include <unknwnbase.h>
//#include <unknwn.h>

DEFINE_GUID(GUID_NULL,0x00000000,0x0000,0x0000, 0x0,0x0,0x00,0x0,0x00,0x0,0x0,0x0);

//                                  4a9a62d3   27d4   403d    91    e9    89   f5   40   e5   55   34
DEFINE_GUID(IID_IPinConnection,0x4a9a62d3,0x27d4,0x403d, 0x91, 0xe9, 0x89,0xf5,0x40,0xe5,0x55,0x34);

//				   "c56e9858 - dbf3-4f6b-     81    19    38   4a   f2   06   0d   eb"
DEFINE_GUID(IID_IPinFlowControl,0xc56e9858,0xdbf3,0x4f6b, 0x81, 0x19, 0x38,0x4A,0xF2,0x06,0x0D,0xEB);

#include <uuids.h>
```

**Comment by JaFojtik** [comment]
This seems to be a problem of all branches not only w64, mingw32 mingw64 clang64 clang32

**Comment by Biswa96** [comment]
This is an issue for mingw-w64 project.

mingw32 mingw64 clang64 clang32 - are just environment names in msys2.

**Comment by Biswa96** [comment]
The patches have been sent to upstream.
* https://sourceforge.net/p/mingw-w64/mailman/message/58750085/
* https://sourceforge.net/p/mingw-w64/mailman/message/58750087/
* https://sourceforge.net/p/mingw-w64/mailman/message/58750086/

**Comment by Biswa96** [comment]
Those patches have been added in the following commits.
* https://sourceforge.net/p/mingw-w64/mingw-w64/ci/9004580db4eb416d02f42d71a51d1f167747fe5c/
* https://sourceforge.net/p/mingw-w64/mingw-w64/ci/e54be045708343a55f533e29971fa3bbcc2fb181/
* https://sourceforge.net/p/mingw-w64/mingw-w64/ci/0bac2d3cdb122dadcdee90009f7e24a69d56939f/

Please wait for the headers to be updated.

**Comment by Biswa96** [comment]
mingw-w64 headers and crt has been updated in e7704dffbb3217f4a71e5b2efa3e8dbc38e5452d commit.
