### ISSUE TITLE
[sqlcipher] 

### ISSUE THREAD

**Issue by ls5302** [msys2/MINGW-packages#20350]
### Description / Steps to reproduce the issue

Has the mingw-w64-i686-sqlcipher package been discontinued?

### Expected behavior

`pacman --noconfirm -S mingw-w64-i686-sqlcipher` install the package.

### Actual behavior

`pacman --noconfirm -S mingw-w64-i686-sqlcipher` reports package not found

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 10

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> Has the mingw-w64-i686-sqlcipher package been discontinued?

Yes. 32 bit packages are being removed. See this news https://www.msys2.org/news/#2023-12-13-starting-to-drop-some-32-bit-packages

**Comment by ls5302** [comment]
Thank you for the prompt response.
