### ISSUE TITLE
mingw-w64-x86_64-python-py2exe seems broken - _memimporter.pyd missing

### ISSUE THREAD

**Issue by sdbbs** [msys2/MINGW-packages#20382]
### Description / Steps to reproduce the issue

I just started with trying to use py2exe.

In my first attempt, it ended up hanging at "Analyzing the code", which seems described in [py2exe hangs in dllfinder.py · Issue #1 · py2exe/py2exe](https://github.com/py2exe/py2exe/issues/1), and seems to occur in Anaconda and MSYS2/MINGW64 Pythons.

Then I found https://www.py2exe.org/index.cgi/TroubleshootingImportErrors , tried the scripts there, and found that I cannot `import zipextimporter`

```lang-none
$ python3 -c 'import zipextimporter'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:/msys64/mingw64/lib/python3.11/site-packages/zipextimporter.py", line 51, in <module>
    import _memimporter
ModuleNotFoundError: No module named '_memimporter'
```

Then I tried to figure out how to build `_memimporter.pyd` - eventually that succeeded, and is documented here: https://stackoverflow.com/questions/78182723/does-memimporter-still-exist-in-py2exe

However, that does not solve the issue - trying this script as `test_zipextimporter.py`:

```lang-python
import sys
print("start1")

import zipextimporter
print("start2")
sys.stderr.write("start2e\n")
with open("log.txt", "a") as text_file:
  text_file.write("start2\n")
zipextimporter.install()
print("start3")
with open("log.txt", "a") as text_file:
  text_file.write("start3\n")
````

... just prints out "start1", and there is no log.txt file created:

```lang-none
$ python3 test_zipextimporter.py
start1
```

Unfortunately, there are no errors either. Eventually I managed to get to some errors like this:

```lang-none
$ python3 -m pdb test_zipextimporter.py
> d:/msys64/tmp/test_zipextimporter.py(1)<module>()
-> import sys
(Pdb) b zipextimporter.py:1
Breakpoint 1 at d:/msys64/mingw64/lib/python3.11/site-packages/zipextimporter.py:1
(Pdb) r
start1
> d:/msys64/mingw64/lib/python3.11/site-packages/zipextimporter.py(1)<module>()
-> r"""zipextimporter - an importer which can import extension modules
(Pdb) n
> d:/msys64/mingw64/lib/python3.11/site-packages/zipextimporter.py(44)<module>()
-> import sys
(Pdb)
> d:/msys64/mingw64/lib/python3.11/site-packages/zipextimporter.py(45)<module>()
-> import zipimport
(Pdb)
> d:/msys64/mingw64/lib/python3.11/site-packages/zipextimporter.py(47)<module>()
-> from importlib import machinery
(Pdb)
> d:/msys64/mingw64/lib/python3.11/site-packages/zipextimporter.py(48)<module>()
-> from importlib import util
(Pdb)
> d:/msys64/mingw64/lib/python3.11/site-packages/zipextimporter.py(51)<module>()
-> import _memimporter
(Pdb) s
--Call--
> <frozen importlib._bootstrap>(1165)_find_and_load()
(Pdb) s
> <frozen importlib._bootstrap>(1170)_find_and_load()
...
> <frozen importlib._bootstrap>(188)_get_module_lock()
(Pdb)
KeyError: '_memimporter'
...
> <frozen importlib._bootstrap>(1176)_find_and_load()->None
(Pdb)
KeyError: 2848
> d:/msys64/tmp/test_zipextimporter.py(4)<module>()
-> import zipextimporter
(Pdb)
--Return--
> d:/msys64/tmp/test_zipextimporter.py(4)<module>()->None
-> import zipextimporter
(Pdb)
KeyError: 2848
> <string>(1)<module>()->None
(Pdb)
--Return--
> <string>(1)<module>()->None
(Pdb)
KeyError: 2848
> d:/msys64/mingw64/lib/python3.11/bdb.py(600)run()
-> exec(cmd, globals, locals)
(Pdb) p cmd
<code object <module> at 0x00000215ed5bed30, file "<string>", line 1>
(Pdb) s
> d:/msys64/mingw64/lib/python3.11/bdb.py(601)run()
-> except BdbQuit:
(Pdb)
> d:/msys64/mingw64/lib/python3.11/bdb.py(604)run()
-> self.quitting = True
(Pdb)
Traceback (most recent call last):
  File "D:/msys64/mingw64/lib/python3.11/pdb.py", line 1793, in main
    pdb._run(target)
  File "D:/msys64/mingw64/lib/python3.11/pdb.py", line 1659, in _run
    self.run(target.code)
  File "D:/msys64/mingw64/lib/python3.11/bdb.py", line 600, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "D:/msys64/tmp/test_zipextimporter.py", line 4, in <module>
    import zipextimporter
  File "D:/msys64/mingw64/lib/python3.11/site-packages/zipextimporter.py", line 51, in <module>
    import _memimporter
  File "<frozen importlib._bootstrap>", line 1173, in _find_and_load
  File "<frozen importlib._bootstrap>", line 171, in __enter__
  File "<frozen importlib._bootstrap>", line 123, in acquire
KeyError: 2848
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> <frozen importlib._bootstrap>(123)acquire()->None
(Pdb) q
Post mortem debugger finished. The D:/msys64/tmp/test_zipextimporter.py will be restarted
> d:/msys64/tmp/test_zipextimporter.py(1)<module>()
-> import sys
(Pdb) quit
```

I really cannot interpret `KeyError: 2848` - but, apparently the `_memimporter.pyd` that I build under MINGW64, is somehow not compatible with the installed mingw-w64-x86_64-python-py2exe.

Note that:

```lang-none
$ grep _memimporter /mingw64/lib/python3.11/site-packages/zipextimporter.py
This file and _memimporter.pyd is part of the py2exe package.
It uses the _memimporter extension which uses code from Joachim
# _memimporter is a module built into the py2exe runstubs.
import _memimporter
        verbose = _memimporter.get_verbose_flag()
                    mod = _memimporter.import_module(fullname, path,
                verbose = _memimporter.get_verbose_flag()
                        mod = _memimporter.import_module(fullname, path,
```

I can also note the comment "_memimporter is a module built into the py2exe runstubs"; and in my SO post, I've confirmed that `_memimporter.o` does get built, and gets linked into `py2exe/run-py311-mingw_x86_64.exe`; also I can see:

```lang-none
$ grep -rI _memimporter /mingw64/lib/python3.11/site-packages/py2exe
/mingw64/lib/python3.11/site-packages/py2exe/distutils_buildexe.py:##             self.excludes.append("_memimporter") # builtin in run_*.exe and run_*.dll
/mingw64/lib/python3.11/site-packages/py2exe/hooks.py:# _memimporter can be excluded because it is built into the run-stub.
/mingw64/lib/python3.11/site-packages/py2exe/hooks.py:_memimporter
````

... but apparently, without a standalone `_memimporter.pyd`, `import zipextimporter` will fail, regardless of the "built into the run-stub" aspect.

Btw, I also tried the original py2exe wheel - it doesn't work under MINGW64 Python3:

```lang-none
$ wget https://files.pythonhosted.org/packages/b1/07/f45b201eb8c3fea1af6a9bd9f733479aa9d009139ce2396e06db7aa778c8/py2exe-0.13.0.1-cp311-cp311-win_amd64.whl
...
$ python3 -m pip install py2exe-0.13.0.1-cp311-cp311-win_amd64.whl
ERROR: py2exe-0.13.0.1-cp311-cp311-win_amd64.whl is not a supported wheel on this platform.
```

So, the first problem is, that `mingw-w64-x86_64-python-py2exe` does not contain `_memimporter.pyd`, which "is part of the py2exe package".

The second problem is - even if you build `_memimporter.pyd` yourself under MINGW64, it still fails to work/integrate with `mingw-w64-x86_64-python-py2exe`.

### Expected behavior

At least, `python3 -c 'import zipextimporter'` should succeed, if the `mingw-w64-x86_64-python-py2exe` package is installed.

### Actual behavior

The command fails with:

```lang-none
$ python3 -c 'import zipextimporter'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:/msys64/mingw64/lib/python3.11/site-packages/zipextimporter.py", line 51, in <module>
    import _memimporter
ModuleNotFoundError: No module named '_memimporter'
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/msys2/MINGW-packages/actions/runs/8378517045

**Comment by sdbbs** [comment]
Thanks a lot, @Biswa96 :

> I found another workaround. I renamed setup_zipextimporter.py to setup.py and build zipextimporter wheel file. It has the _memimporter pyd file.

Huh, that is interesting - I would not have expected renaming a setup file would have helped 😄 

> I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/msys2/MINGW-packages/actions/runs/8378517045

Sure - I clicked on [MINGW64-packages](https://github.com/msys2/MINGW-packages/actions/runs/8378517045/artifacts/1347280004) link there, and downloaded a `MINGW64-packages.zip`, in which there was a `mingw-w64-x86_64-python-py2exe-0.13.0.1-2-any.pkg.tar.zst` file; then I used:

```lang-none
$ pacman -Q | grep py2exe
mingw-w64-x86_64-python-py2exe 0.13.0.1-1

$ pacman -U /d/Downloads/mingw-w64-x86_64-python-py2exe-0.13.0.1-2-any.pkg.tar.zst
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-python-py2exe-0.13.0.1-2

Total Installed Size:  1.13 MiB
Net Upgrade Size:      0.02 MiB

:: Proceed with installation? [Y/n] y
...
(1/1) upgrading mingw-w64-x86_64-python-py2exe                     [###################################] 100%
```

After this, I can see `_memimporter.pyd` in the Python 3 site-packages location:

```lang-none
$ ls /mingw64/lib/python3.11/site-packages/_mem*
/mingw64/lib/python3.11/site-packages/_memimporter.cp311-mingw_x86_64.pyd*
```

... and of course, `python3 -c 'import zipextimporter'` now works fine, and does not crash anymore.

Many thanks again!
