### ISSUE TITLE
`mingw-w64-geany-plugins` and `mingw-w64-lua51` dependency

### ISSUE THREAD

**Issue by iahung3** [msys2/MINGW-packages#20489]
### Description / Steps to reproduce the issue

Install `mingw-w64-geany-plugins` and it will also install `mingw-w64-lua51` as dependency. Doing `pacman -Syu` will prompt to replace `mingw-w64-lua51` with `mingw-w64-luajit`.

### Expected behavior

Why don't install `mingw-w64-luajit` as the dependency of `mingw-w64-geany-plugins` in the first place?

### Actual behavior

`mingw-w64-lua51` is installed as the dependency only to be replaced by `mingw-w64-luajit` when doing `pacman -Syu`

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by iahung3** [comment]
@hmartinez82

**Comment by hmartinez82** [comment]
This is by design
It's one OR the other
