### ISSUE TITLE
notepad++ does not start from msys shell if you have a local language

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MINGW-packages#20490]
### Description / Steps to reproduce the issue

go to say mingw64 enviroment, install notepad++
then do 
`LANG="en_GB.UTF-8" notepad++`
simulating you have a non en_US locale.

### Expected behavior

opens

### Actual behavior

![it does not open](https://github.com/msys2/MINGW-packages/assets/2415206/cdedf5e6-9c8b-45af-a363-a27b6457b5e7)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
Looks like this is a known problem: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12417

**Comment by Biswa96** [comment]
Does this happen in mingw64 only?

**Comment by Kreijstal** [comment]
Ucrt as well don't know about clang

**Comment by heljkon** [comment]
@Kreijstal
With https://github.com/msys2/MINGW-packages/pull/20599 a solution was provided. 
Please update your packages and verify.

**Comment by Biswa96** [comment]
Is this issue fixed with newer notepad++ package?

**Comment by Kreijstal** [comment]
bug is solved!
