### ISSUE TITLE
Can't load GCC environment for computer

### ISSUE THREAD

**Issue by Hung027558** [msys2/MINGW-packages#20491]
### Description / Steps to reproduce the issue

When I installed Codeblocks 20.3 MINGW on a Lenovo Ideapad Slim 3i on Windows 11, I cannot open the GCC environment for C and C++.

### Expected behavior

I expected it to run my newly saved C++ script.
Here:
#include <iostream>
using namespace std;

int main() {
  cout << "Hello World!";
  return 0;
}
I clicked Build and then Run.
I expected to have "Hello World!" on the output.

### Actual behavior

Instead, it didn't output anything. 

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 11 NT 22H2

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
You should setup codeblocks to use gcc.
