### ISSUE TITLE
Add [PowerShell]

### ISSUE THREAD

**Issue by LinArcX** [msys2/MINGW-packages#20504]
### Package name

PowerShell

### Brief description of package

PowerShell for every system!

### URL for package's homepage

https://github.com/PowerShell/PowerShell

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [X] CLANGARM64

**Comment by ognevny** [comment]
powershell is included in Windows, pwsh can be easily download woth official .msi installer

**Comment by Biswa96** [comment]
@LinArcX Please stop adding random package request issues.

**Comment by LinArcX** [comment]
@ognevny my current msys2 c runtime is ucrt. i'm not sure the default powershell that comes with windows uses this runtime or not.

if this is the case, then i can close this package request.

@Biswa96  sorry?

**Comment by ognevny** [comment]
> @ognevny my current msys2 c runtime is ucrt. i'm not sure the default powershell that comes with windows uses this runtime or not.
> 
> if this is the case, then i can close this package request.

PowerShell compiled with MSVC for Windows because it's MS product. IMHO there is no need to compile it with mingw

**Comment by LinArcX** [comment]
ok, it makes sense. I'm going to close this request. thanks for the explanation.
