### ISSUE TITLE
`geany.exe` is without an icon

### ISSUE THREAD

**Issue by iahung3** [msys2/MINGW-packages#20520]
### Description / Steps to reproduce the issue

Install package `mingw-w64-clang-x86_64-geany`

### Expected behavior

`geany.exe` should have an icon

### Actual behavior

`geany.exe` doesn't have an icon

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by iahung3** [comment]
@ognevny @hmartinez82

**Comment by ognevny** [comment]
> @ognevny @hmartinez82 

I don't know, I'm not a user of geany. sorry

**Comment by lazka** [comment]
@iahung3 this seems like something that should be reported upstream: https://github.com/geany/geany

**Comment by Biswa96** [comment]
I have the fix and try to make it upstream.

**Comment by hmartinez82** [comment]
Their Windows provided installer does install a geany.exe that has the icon. So it's probably an ifdef or a build-time only behavior that adds the icon to the .exe resources
