### ISSUE TITLE
`gedit.exe` is without an icon

### ISSUE THREAD

**Issue by ghost** [msys2/MINGW-packages#20526]
### Description / Steps to reproduce the issue

Install package `mingw-w64-clang-x86_64-gedit`

### Expected behavior

`gedit.exe` should have an icon

### Actual behavior

`gedit.exe` doesn't have an icon

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by iahung3** [comment]
@Biswa96

**Comment by Biswa96** [comment]
gedit upstream repository does not have the setup to add icon in Windows executable. It needs resource, manifest and icon files. So, this would a feature request for upstream as well.

**Comment by hmartinez82** [comment]
Upstream merge request created https://gitlab.gnome.org/GNOME/gedit/-/merge_requests/168
