### ISSUE TITLE
`evince.exe` is without an icon

### ISSUE THREAD

**Issue by ghost** [msys2/MINGW-packages#20537]
### Description / Steps to reproduce the issue

Install package `mingw-w64-clang-x86_64-evince`

### Expected behavior

`evince.exe` should have an icon

### Actual behavior

`evince.exe` doesn't have an icon

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by iahung3** [comment]
@Biswa96 @pokoli

**Comment by hmartinez82** [comment]
@Biswa96 this can be closed since we added the icon :)
