### ISSUE TITLE
Geany's run feature is broken

### ISSUE THREAD

**Issue by iahung3** [msys2/MINGW-packages#20554]
### Description / Steps to reproduce the issue

Open a simple C/C++ program source file, could be `helloworld`. Press `F9` to build. Press `F5` to run. You could use the toolbar buttons or the menu buttons, it doesn't matter.

### Expected behavior

Geany could be able to find and run the compiled binary. A new command window will popped up to run the program.

### Actual behavior

Nothing happened. If you go to the popup window that is opened with Geany itself (see https://github.com/msys2/MINGW-packages/issues/20518), you will see `The system cannot find the path specified.`. The program is successfully compiled and the binary is there. But Geany can't find and run it.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by iahung3** [comment]
Note: I run `geany.exe` by double click into the binary. I don't launch it from the MSYS2 shell. It's a native Win32 program, so why do I need to launch it via the MSYS2 Shell?

**Comment by iahung3** [comment]
Update: It fails with the same error when I launch `geany` from the MSYS2 Shell.

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Do we have any other issue related to geany?

**Comment by iahung3** [comment]
> I have added a pull request to fix this issue. Do we have any other issue related to geany?

Currently, no. But if you could help, please have a look at https://github.com/msys2/MINGW-packages/discussions/20555

**Comment by Biswa96** [comment]
No idea.
