### ISSUE TITLE
Add PDFium

### ISSUE THREAD

**Issue by taozuhong** [msys2/MINGW-packages#20583]
### Package name

mingw-w64-pdfium

### Brief description of package

[PDFium library](https://github.com/PDFium/PDFium), an open-source library for PDF manipulation and rendering.

Patch and build script found here:
https://github.com/bblanchon/pdfium-binaries

### URL for package's homepage

https://github.com/PDFium/PDFium

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

Need help

**Comment by Biswa96** [comment]
The last commit of https://github.com/PDFium/PDFium project is 10 years old.

**Comment by iahung2** [comment]
> The last commit of https://github.com/PDFium/PDFium project is 10 years old.

I think the correct repository is here: https://pdfium.googlesource.com/pdfium/
