### ISSUE TITLE
Bitdefender scans issues on mingw32

### ISSUE THREAD

**Issue by demosthenesk** [msys2/MINGW-packages#20580]
Hello, i have scanned the msys2 directory with Bitdefender antivirus and it found PUP issues in mingw32 folder.
I don't know how to export text from bitdefender log so i upload a picture.

![msys2-viruses](https://github.com/msys2/MINGW-packages/assets/1350282/31f773fa-4f38-45a1-805f-3adaa2759117)

**Comment by Biswa96** [comment]
Those are false positive. All the binaries are compiled in GitHub Actions CI from source code.
