### ISSUE TITLE
[glib2] Introspection files not generated

### ISSUE THREAD

**Issue by jwharm** [msys2/MINGW-packages#20602]
### Description / Steps to reproduce the issue

GObject-Introspection allows libraries to export their API in an xml repository (`.gir`) file. These files are installed under `/usr/share/gir-1.0/` and are commonly used by language bindings.

In the past (until glib 2.78), the introspection outputs for glib, gobject, gmodule and gio were generated not from the `glib2` package itself, but by building and installing a separate package, `gobject-introspection`. Since glib 2.80, this has been integrated into glib itself.

However, in the MINGW packages, [the 'introspection' build option is still disabled](https://github.com/msys2/MINGW-packages/blob/8eb30672ae0b6d11b96ee8fd0eaeb66b06083345/mingw-w64-glib2/PKGBUILD#L85) for the `glib2` package, so it doesn't generate and install the `.gir` files.

The `mingw-w64-gobject-introspection` package will still install the gir files, but those are the old ones for glib 2.78.

Steps to reproduce:

```
1. pacman -S mingw-w64-x86_64-glib2 --> installs glib 2.80
2. ls /mingw64/share/gir-1.0/GLib-2.0.gir --> does not exist
3. pacman -S mingw-w64-gobject-introspection
4. ls /mingw64/share/gir-1.0/GLib-2.0.gir --> file exists, but is based on glib 2.78
```

### Expected behavior

`GLib-2.0.gir`, `GObject-2.0.gir`, `GModule-2.0.gir` and `Gio-2.0.gir` are generated when building `mingw-w64-x86_64-glib2` and installed into `/mingw64/share/gir-1.0/`.

### Actual behavior

The gir files are not installed with the `glib2` package.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes

**Comment by Biswa96** [comment]
Yes, this is expected. gobject-introspection has not been updated yet.

**Comment by jwharm** [comment]
Thanks @Biswa96
