### ISSUE TITLE
Add [mingw-w64-clang-tools-extra-17]

### ISSUE THREAD

**Issue by auryouth** [msys2/MINGW-packages#20608]
### Package name

mingw-w64-clang-tools-extra-17

### Brief description of package

Extra tools built using Clang's tooling APIs (mingw-w64)

### URL for package's homepage

 https://clang.llvm.org/

#### Note
**clang-tools-extra-18** in current msys2 packages repo works well in **shell environment** when running `clang-tidy main.cpp`, but according to my test in Linux and Windows11, only clangd up to version 17 supports clang-tidy's functionality in vscode now.

#### Test case
- In UCRT64 environment install **clang-tools-extra-17**.
- In vscode install **clangd** extension.
- make a demo main.cpp file:
```cpp
#include <iostream>

auto main() -> int {
  std::cout << "Hello, World!" << std::endl;
  return 0;
}
```
- In the same directory touch a **.clangd** file:
```yaml
Diagnostics:
  ClangTidy:
    Add: [performance-*]
```
- Under `std::endl`, if **clang-tidy** prompt you: `Do not use 'std::endl' with streams; use '\n' instead (fix available)clang-tidy performance-avoid-endl`, it is corrent.

### MINGW environments where you need the package

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Possible if i know how to make a package for msys2 :)

**Comment by MehdiChinoune** [comment]
That's not possible, MSYS2 is a rolling release platform.
You should report the issue to VS code to support clang 18.1
