### ISSUE TITLE
[mosquitto] Static linking broken

### ISSUE THREAD

**Issue by silabs-beta** [msys2/MINGW-packages#20604]
### Description / Steps to reproduce the issue

I try to use the libmosquitto package in my project with static linking. I use `-static` linker flag and I get the linker flags for the package like this:  `pkg-config --libs --static libmosquitto`. The output of the pkg-config is `-lmosquitto`.

### Expected behavior

The flags provided by pkg-config should work as is.

### Actual behavior

The linker fails like this: `cannot find -lmosquitto: No such file or directory`
It happens because the static library is called `libmosquitto.dll.a`, see the file list [here](https://packages.msys2.org/package/mingw-w64-x86_64-mosquitto).
If I link with the `-lmosquitto.dll` flag, the link succeeds.
I think the `libmosquitto.dll.a` should be renamed to `libmosquitto.a`, but I don't know where to look at.
I think `libmosquittopp` is affected too, but I haven't tried it.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by podsvirov** [comment]
@silabs-beta, can you confirm that #20605 fix your problem? (you can rebuild package himself or download prebuild `Artifacts` from [Checks](https://github.com/msys2/MINGW-packages/pull/20605/checks))

**Comment by silabs-beta** [comment]
Unfortunately no, I get various linker errors like these
```
undefined reference to `__imp_mosquitto_lib_init'
undefined reference to `__imp_mosquitto_new'
undefined reference to `__imp_mosquitto_connect_callback_set'
undefined reference to `__imp_mosquitto_disconnect_callback_set'
undefined reference to `__imp_mosquitto_message_callback_set'
undefined reference to `__imp_mosquitto_log_callback_set'
undefined reference to `__imp_mosquitto_connect'
...
```
I didn't expect such a quick response, so I opened a ticket in the mosquitto repo too.
https://github.com/eclipse/mosquitto/issues/3035

**Comment by Biswa96** [comment]
It is not an issue. You forgot to define `LIBMOSQUITTO_STATIC` macro for static linking. We could also add that macro in pkgconfig file.

**Comment by silabs-beta** [comment]
@Biswa96 Shall I replace the `-lmosquitto` linker flag to `-lmosquitto_static`? Is this what you meant?
It doesn't work, either, I get the same undefined reference errors.

**Comment by Biswa96** [comment]
I meant to define `LIBMOSQUITTO_STATIC` macro in compiler flag. For example, `gcc -DLIBMOSQUITTO_STATIC -static test.c <put the rest things here>`

**Comment by silabs-beta** [comment]
I don't understand how could a compiler flag solve a linker issue.
Anyway, I tried it, and the original issue still persists: `cannot find -lmosquitto: No such file or directory`

**Comment by silabs-beta** [comment]
@podsvirov , your fix renames libmosquitto_static.a to libmosquitto.a. But the libmosquitto.dll.a should be renamed to libmosquitto.a instead.

**Comment by Biswa96** [comment]
> But the libmosquitto.dll.a should be renamed to libmosquitto.a instead.

No. The .dll.a are import library and those are correctly named.

**Comment by silabs-beta** [comment]
I agree, it can be correctly named in theory, but the experience shows that the fix doesn't work. If I rename the one with the `.dll.a suffix`, then the build succeeds.

**Comment by Biswa96** [comment]
Could you provide any sample code to reproduce the issue?

**Comment by silabs-beta** [comment]
Sure, you can use e.g. [basic-1.c](https://github.com/eclipse/mosquitto/blob/master/examples/subscribe/basic-1.c)
and compile it like this: `gcc basic-1.c -static -lmosquitto -o subscribe.exe`

**Comment by Biswa96** [comment]
Try this command `gcc -static -DLIBMOSQUITTO_STATIC  basic-1.c $(pkgconf -libs -static libmosquitto libssl)`

The pkgconfig file is not correct yet. I shall try to upstream the changes first.

**Comment by silabs-beta** [comment]
Indeed, I managed to build it (and found the reference to the `LIBMOSQUITTO_STATIC` in the API header).
Thank you for your support!

**Comment by silabs-beta** [comment]
I have just tried the patched mosquitto artifacts from [here](https://github.com/msys2/MINGW-packages/suites/22631154855/artifacts/1402627925).

Probably dumb question, but why do I need to add the libssl package manually when I use static linking? When use dynamic linking, then the following build command works perfectly:
`gcc basic-1.c $(pkgconf -libs -cflags libmosquitto)`
But the same command with the static flag fails because of undefined reference errors.
`gcc -static basic-1.c $(pkgconf -libs -cflags -static libmosquitto)`

Since there is no direct dependency on libssl in [basic-1.c](https://github.com/eclipse/mosquitto/blob/master/examples/subscribe/basic-1.c), I think this dependency should be provided in the libmosquitto.pc file too.
Probably a `Requires.private: libssl` or `Libs.private: -lssl` entry is missing?

**Comment by Biswa96** [comment]
> Probably a `Requires.private: libssl` or `Libs.private: -lssl` entry is missing?

Yes.

**Comment by silabs-beta** [comment]
What should be the way forward? Shall I open a new issue for this one? Or Shall I open a PR myself?
And what is the process of adding the fixes in the original eclipse/mosquitto repo?

**Comment by Biswa96** [comment]
I have added a new pull request to add the libssl in pkgconfig file of libmosquitto. I should have suggested the change in podsvirov's pull request.

**Comment by podsvirov** [comment]
> I have added a new pull request to add the libssl in pkgconfig file of libmosquitto. I should have suggested the change in podsvirov's pull request. Would you like to review the new change please?

Good addition.

**Comment by Biswa96** [comment]
Please feel free to copy or modify or upstream my changes.
