### ISSUE TITLE
kiconthemes: KIconTheme needs to add BreezeIcons as build-time dependency and needs to be patched for init icon resources correctly

### ISSUE THREAD

**Issue by BLumia** [msys2/MINGW-packages#20687]
### Description / Steps to reproduce the issue

There are two issues:

1. It's suggested to build KIconTheme with BreezeIcons since icon theme works in a different way under Windows. when adding BreezeIcons as a build-time dependency, KIconTheme will help init icon resources and ensure app also find icons from Qt's resource system, so programs can use BreezeIcons as they do under Linux.
2. KIconTheme's 6.1.0 release has a typo: https://github.com/KDE/kiconthemes/commit/d8ee0caf5b940a310020dd68ecb6905e67413ed4 which will cause the icon resource not be able to init correctly. KDE applied a patch to fix this issue from their build system (Craft), see https://github.com/KDE/craft-blueprints-kde/blob/9335df8a24b10043295086e8079909736f551627/kde/frameworks/tier3/kiconthemes/kiconthemes-6.1.0-20240415.diff

And another issue I haven't figure it out right now:

- KDE also [apply another patch in their Craft build system](https://github.com/KDE/craft-blueprints-kde/blob/9335df8a24b10043295086e8079909736f551627/kde/frameworks/tier3/kiconthemes/svgiconengine.diff) to [enforce iconengine plugin is there on (mac and) Windows](https://github.com/KDE/craft-blueprints-kde/blob/9335df8a24b10043295086e8079909736f551627/kde/frameworks/tier3/kiconthemes/kiconthemes.py#L11). I'm not quite sure but we likely might also need to apply this patch too.

### Expected behavior

kiconthemes is build with BreezeIcons and patched, so KDE apps like Kate can find breeze icons, as lone as they are depend on kiconthemes.

### Actual behavior

kiconthemes (currently `ucrt64/mingw-w64-ucrt-x86_64-kiconthemes 6.1.0-1`) is not build with BreezeIcons and not patched.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Maybe? But might not have time to submit this as a patch right now. Feel free to work on it directly if you plan to do so, and please leave a comment first before you work on this issue.

**Comment by Biswa96** [comment]
breeze and breeze-icons are incomplete right now because the source tarball contain symlinks. craft uses some wizardry to copy files, see https://invent.kde.org/packaging/craft/-/blob/bfac5fa33be1ae8a4be2e9a9446a9aa05fc103fc/bin/utils.py#L153-153. I need some help to fix those first.

**Comment by BLumia** [comment]
> breeze and breeze-icons are incomplete right now

Is there a related issue so I can check the details?

> I need some help to fix those first.

I'm interested in helping (no promise tho, since my spare time is quite limited recently), but is that issue blocking this issue from fixed? If not, I personally tend to fix this issue first when I got time, then try the symlink one.

**Comment by BLumia** [comment]
> > breeze and breeze-icons are incomplete right now
> 
> Is there a related issue so I can check the details?

Additionally, I actually didn't even notice the missing icon issue. KDE apps on Windows actually use the BreezeIcon assets embedded in the resource file instead of using the one on-disk. Do you have related screenshots to showcase this issue?

**Comment by Biswa96** [comment]
After many commits, dark theme is now working with KDE apps.

![image](https://github.com/msys2/MINGW-packages/assets/31443074/61deb60e-4dc1-4195-91d6-f0058576360a)

**Comment by BLumia** [comment]
Thanks!

Also put a link here so people could find related info: https://cullmann.io/posts/kde-applications-and-icons/
