### ISSUE TITLE
Emacs crashes with "stack smashing detected" when starting tree-sitter

### ISSUE THREAD

**Issue by RKBK** [msys2/MINGW-packages#20705]
### Description / Steps to reproduce the issue

I updated my mys mingw-w64-x86_64 environment today. That included updates for emacs (mingw64/mingw-w64-x86_64-emacs 29.3-1) and tree-sitter. After the update, emacs crashes with a "stack smashing detected" as soon as I open a file that is configured to use tree-sitter. I have set up emacs to use tree-sitter by default for certain major modes (e.g. java).

The error seems to be exactly the same as is described here: https://github.com/tree-sitter/tree-sitter/issues/3296 

I would be grateful for any suggestions for what to do to fix the error.

### Expected behavior

Emacs should not crash when opening a file using a tree-sitter major mode.

### Actual behavior

Emacs crashes with the error "*** stack smashing detected ***: terminated"

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by kisp** [comment]
I experience the same error message and problem on Arch Linux.

**Comment by lazka** [comment]
emacs was rebuilt now. Can you update and test if it helped?

**Comment by chuntaro** [comment]
It works fine with the latest tree-sitter 0.22.5!
Thanks!

**Comment by RKBK** [comment]
The issue has been resolved after an update using pacman -Syu. Much appreciated!
