### ISSUE TITLE
lupdate-qt6.exe depends on llvm-libs and clang-libs in MINGW64 environment with Qt6

### ISSUE THREAD

**Issue by missdeer** [msys2/MINGW-packages#20707]
### Description / Steps to reproduce the issue

Install mingw-w64-x86_64-qt6
Run lupdate-qt6.exe

### Expected behavior

Run without errors.

### Actual behavior

Missing libLLVM-18.dll and libclang-cpp.dll.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
clang-libs are mentioned as optdepnds for lupdate-qt6 and qdoc-qt6 to work.
see https://packages.msys2.org/package/mingw-w64-x86_64-qt6-tools?repo=mingw64
