### ISSUE TITLE
`prefix=/mingw64` missing in `openssl.pc` file

### ISSUE THREAD

**Issue by newhoggy** [msys2/MINGW-packages#20763]
### Description / Steps to reproduce the issue

Reproduction:

```
# pacman -Sw mingw-w64-x86_64-openssl
# tar xvf /var/cache/pacman/pkg/mingw-w64-x86_64-openssl-3.3.0-1-any.pkg.tar.zst
```

The above `pc` file does not use `prefix`.

### Expected behavior

```
# cat mingw64/lib/pkgconfig/openssl.pc
libdir=/mingw64/lib
includedir=/mingw64/include

Name: OpenSSL
Description: Secure Sockets Layer and cryptography libraries and tools
Version: 3.3.0
Requires: libssl libcrypto
```

### Actual behavior

```
# cat mingw64/lib/pkgconfig/openssl.pc
libdir=/mingw64/lib
includedir=/mingw64/include

Name: OpenSSL
Description: Secure Sockets Layer and cryptography libraries and tools
Version: 3.3.0
Requires: libssl libcrypto
```

Example good case for another library

```
# pacman -Sw mingw-w64-x86_64-gmp
# tar xvf /var/cache/pacman/pkg/mingw-w64-x86_64-gmp-6.3.0-2-any.pkg.tar.zst
# cat mingw64/lib/pkgconfig/gmp.pc
prefix=/mingw64
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

Name: GNU MP
Description: GNU Multiple Precision Arithmetic Library
URL: https://gmplib.org
Version: 6.3.0
Cflags: -I${includedir}
Cflags.private: -DGMP_STATICLIB
Libs: -L${libdir} -lgmp
```

Because `prefix=` and `${prefix}` are not used in the `openssl` case, this breaks `openssl` in Github Actions.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-20348 fv-az1111-280 3.4.10.x86_64 2024-04-08 18:11 UTC x86_64 Msys

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [x] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by newhoggy** [comment]
Work around:

```
wget https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-openssl-3.2.1-1-any.pkg.tar.zst
pacman -Uy mingw-w64-x86_64-openssl-3.2.1-1-any.pkg.tar.zst
```

**Comment by lazka** [comment]
Confirmed. Thanks

**Comment by lazka** [comment]
Filed upstream: https://github.com/openssl/openssl/issues/24298
