### ISSUE TITLE
mingw-w64-rclone: no mount command

### ISSUE THREAD

**Issue by ArchGuyWu** [msys2/MINGW-packages#20772]
### Description / Steps to reproduce the issue

rclone mount

### Expected behavior

The mount command should exist.

### Actual behavior

Error: unknown command "mount" for "rclone"
Run 'rclone --help' for usage.
You could use 'rclone selfupdate' to get latest features.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-20348

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by ognevny** [comment]
in arch linux `mount.rclone` is a symlink to `rclone`: https://gitlab.archlinux.org/archlinux/packaging/packages/rclone/-/blob/main/PKGBUILD?ref_type=heads#L56

**Comment by ArchGuyWu** [comment]
> in arch linux `mount.rclone` is a symlink to `rclone`: https://gitlab.archlinux.org/archlinux/packaging/packages/rclone/-/blob/main/PKGBUILD?ref_type=heads#L56

It's not related to mount command.

**Comment by ArchGuyWu** [comment]
rclone mount can still work without /usr/bin/mount.rclone and `/usr/bin/rclonefs`.

**Comment by Kreijstal** [comment]
you cannot make it with msys2 because it has drivers and right now msys2 cannot compile drivers unless you fiddle with reactos headers, even then you will have to either allow unsigned drivers on your computer which you do by unsetting trusted boot, or pay microsoft. So just use `rclone update`, and you will get the dll but it will not be from msys2 but from rclone team itself.

**Comment by ArchGuyWu** [comment]
> you cannot make it with msys2 because it has drivers ([FSP dependency](https://winfsp.dev/)) and right now msys2 cannot compile drivers unless you fiddle with reactos headers, (and it is written in dotnet which we do not have) even then you will have to either allow unsigned drivers on your computer which you do by unsetting trusted boot, or pay microsoft. So just use `rclone update`, and you will get the dll but it will not be from msys2 but from rclone team itself.

It's required at compile time to enable mount option, maybe can include it in PKGBUILD.

**Comment by Kreijstal** [comment]
> > you cannot make it with msys2 because it has drivers ([FSP dependency](https://winfsp.dev/)) and right now msys2 cannot compile drivers unless you fiddle with reactos headers, (and it is written in dotnet which we do not have) even then you will have to either allow unsigned drivers on your computer which you do by unsetting trusted boot, or pay microsoft. So just use `rclone update`, and you will get the dll but it will not be from msys2 but from rclone team itself.
> 
> It's required at compile time to enable mount option, maybe can be included in PKGBUILD.

binaries are not included at compile time, afaik, you can make your own PKGBUILD that does this

**Comment by ArchGuyWu** [comment]
> > > you cannot make it with msys2 because it has drivers ([FSP dependency](https://winfsp.dev/)) and right now msys2 cannot compile drivers unless you fiddle with reactos headers, (and it is written in dotnet which we do not have) even then you will have to either allow unsigned drivers on your computer which you do by unsetting trusted boot, or pay microsoft. So just use `rclone update`, and you will get the dll but it will not be from msys2 but from rclone team itself.
> > 
> > 
> > It's required at compile time to enable mount option, maybe can be included in PKGBUILD.
> 
> binaries are not included at compile time, afaik, you can make your own PKGBUILD that does this

OK, I'll try it.
