### ISSUE TITLE
MSYS2 installer stuck on updating trust database

### ISSUE THREAD

**Issue by NikNikovsky** [msys2/MINGW-packages#20779]
### Description / Steps to reproduce the issue

Just attempt to run the installer

### Expected behavior

It's supposed to install MSYS2

### Actual behavior

Updating trust database is the last thing that shows up

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 11 Pro (OS Build: 22635.3566)

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Sure, I guess

**Comment by Biswa96** [comment]
The issue can not be reproduced. There are many things that can hinder msys2 installation procedure. It is anti-virus software most of the time. See https://cygwin.com/faq/faq.html#faq.using.bloda
