### ISSUE TITLE
`qoi` is failling to install due to existing file

### ISSUE THREAD

**Issue by brunvonlope** [msys2/MINGW-packages#20788]
### Description / Steps to reproduce the issue

When trying to install qoi package, pacman complains about existing file:

```sh
error: failed to commit transaction (conflicting files)
mingw-w64-clang-aarch64-qoi: /clangarm64/include/qoi.h exists in filesystem
```

### Expected behavior

qoi is installed

### Actual behavior

qoi is not installed

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22000

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment]
That file is only provided by qoi package.

```
$ pacman -F /clangarm64/include/qoi.h
clangarm64/include/qoi.h is owned by clangarm64/mingw-w64-clang-aarch64-qoi r335.d4fc9d1-1
```
