### ISSUE TITLE
package mingw-w64-x86_64-srecord will not compile using 'C'

### ISSUE THREAD

**Issue by vero-board** [msys2/MINGW-packages#20799]
### Description / Steps to reproduce the issue

problem using 'C'. The srecord include folder contains
problem one; "string.h" has the same name as used in by libc.
problem two; The file includes <string> which is a C++ file.

There is nothing to say that this is a C++ only package!, therefore I would expect it to build in 'C'

### Expected behavior

string.h needs to be called something else. reference to C++ code needs to be changes to be 'C'.

### Actual behavior

C:\msys64\mingw64\include\srecord/string.h:22:10: fatal error: string: No such file or directory
   22 | #include <string>

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

no

**Comment by MehdiChinoune** [comment]
Please report the issue to the upstream (https://github.com/sierrafoxtrot/srecord/issues), not an MSYS2 issue.
And BTW srecord is a C++ project (written in C++) don't expect its headers to be compatible with C.
