### ISSUE TITLE
FFmpeg update to 7.0

### ISSUE THREAD

**Issue by esator** [msys2/MINGW-packages#20816]
### Package name

ffmpeg

### New version number

7.0

**Comment by lazka** [comment]
Like last time we need to check which dependencies have support for it, and/or patches available: #16070

**Comment by lazka** [comment]
Arch has started the transition: https://archlinux.org/todo/ffmpeg-70-mbedtls-360-x265-36-combo-rebuild/

**Comment by lazka** [comment]
* [ ] mingw-w64-qt6-multimedia
* [ ] mingw-w64-gst-libav
* [ ] mingw-w64-mlt
* [ ] mingw-w64-x264
* [ ] mingw-w64-mpv
* [ ] mingw-w64-ffms2
* [ ] mingw-w64-audaspace
* [ ] mingw-w64-python-xpra
* [ ] mingw-w64-freerdp
* [ ] mingw-w64-wxsvg
* [ ] mingw-w64-scrcpy
* [ ] mingw-w64-vlc
* [ ] mingw-w64-mtn
* [ ] mingw-w64-gegl
* [ ] mingw-w64-aubio
* [ ] mingw-w64-kfilemetadata
* [ ] mingw-w64-libplacebo-demos
* [ ] mingw-w64-gr
* [ ] mingw-w64-openimageio
* [ ] mingw-w64-opencv
* [ ] mingw-w64-ossia-score
* [ ] mingw-w64-vtk
* [ ] mingw-w64-blender

**Comment by lazka** [comment]
initial build test done now, lots of things to do still

**Comment by lazka** [comment]
For the last two we should probably wait a bit for upstream.

**Comment by lazka** [comment]
The VLC MR seems to be stuck on details, so I'm wondering if we should just take it as is and update it later if needed: https://code.videolan.org/videolan/vlc/-/merge_requests/5574

**Comment by lazka** [comment]
done now
