### ISSUE TITLE
RapidJSON: Failed to build in `document.h`

### ISSUE THREAD

**Issue by otegami** [msys2/MINGW-packages#20858]
### Description / Steps to reproduce the issue

Step1: Tried to build Groonga. The build step is [here](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-groonga/PKGBUILD).
Step2: Using RapidJSON([mingw-w64-rapidjson](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-rapidjson/PKGBUILD))'s header file raised the following error.

- Groonga is depended on RapidJSON [here](https://github.com/msys2/MINGW-packages/blob/7df4e394f3100d374875bc00885de7c098956bff/mingw-w64-groonga/PKGBUILD#L28).

```console
  D:/M/msys64/mingw64/include/rapidjson/document.h:319:82: error: assignment of read-only member 'grn_rapidjson::GenericStringRef<CharType>::length'
    319 |     GenericStringRef& operator=(const GenericStringRef& rhs) { s = rhs.s; length = rhs.length; }
        |                                                                           ~~~~~~~^~~~~~~~~~~~
```

ref: Building Groonga failed [here](https://github.com/komainu8/MINGW-packages/actions/runs/9026581500/job/24804111381).

### My personal suggestion

This error has already resolved at upstream. See also [here](https://github.com/xbmc/inputstream.adaptive/issues/1548)
So how about adding the above patch to this repository for the issue we're facing?

The rationale for this sugestion is as follows.

- New RapidJSON version hasn't been released for 8 years like [here](https://github.com/Tencent/rapidjson/tags)
- A lot of people asked for it at upstream but it haven't done yet by this moment. See also [here](https://github.com/Tencent/rapidjson/issues/2238)

### Expected behavior

Successfully build RapidJSON

### Actual behavior

During building step, RapidJSON raised the following error.

```console
  D:/M/msys64/mingw64/include/rapidjson/document.h:319:82: error: assignment of read-only member 'grn_rapidjson::GenericStringRef<CharType>::length'
    319 |     GenericStringRef& operator=(const GenericStringRef& rhs) { s = rhs.s; length = rhs.length; }
        |                                                                           ~~~~~~~^~~~~~~~~~~~
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64: windows-2022 on GitHub Actions, UCRT64: windows-2022 on GitHub Actions

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes if I can, I might need your helps.

**Comment by mmuetzel** [comment]
I'm seeing the same build error when trying to build Octave with GCC 14.
The build artifacts from PR #20859 avoid the build error for me.

Do they also avoid the build error for you?

**Comment by otegami** [comment]
@mmuetzel 
Thank you so much for addressing it and resolving it.
Your patch works for me too [here](https://github.com/otegami/MINGW-packages/actions/runs/9034323838).
