### ISSUE TITLE
Error generating a full debug report using gcc 14.1.0-2

### ISSUE THREAD

**Issue by JaiSoone** [msys2/MINGW-packages#20864]
### Description / Steps to reproduce the issue

1) download wxWidgets 3.2.4
2) make the following changes to wxWidgets for compiling on a Microsoft windows 10 system:
```diff
diff -r 11c2f3533abe -r 71959affad03 build/msw/config.gcc
--- a/build/msw/config.gcc      Sun Feb 11 08:29:01 2024 -0800
+++ b/build/msw/config.gcc      Sun Feb 11 09:32:43 2024 -0800
@@ -23,10 +23,10 @@
 CXX = g++

 # Standard flags for CC
-CFLAGS ?=
+CFLAGS ?= -Wno-unused-local-typedefs -Wno-deprecated-declarations -fno-omit-frame-pointer -march=native -DwxUSE_OWNER_DRAWN -freport-bug

 # Standard flags for C++
-CXXFLAGS ?=
+CXXFLAGS ?= -Wno-unused-local-typedefs -Wno-deprecated-declarations -fno-omit-frame-pointer -march=native -DwxUSE_OWNER_DRAWN -freport-bug

 # Standard preprocessor flags (common for CC and CXX)
 CPPFLAGS ?=
diff -r 11c2f3533abe -r 71959affad03 build/msw/makefile.gcc
--- a/build/msw/makefile.gcc    Sun Feb 11 08:29:01 2024 -0800
+++ b/build/msw/makefile.gcc    Sun Feb 11 09:32:43 2024 -0800
@@ -5217,7 +5217,7 @@
 endif
 ifeq ($(BUILD),debug)
 ifeq ($(DEBUG_INFO),default)
-__DEBUGINFO = -g
+__DEBUGINFO = -ggdb3
 endif
 endif
 ifeq ($(BUILD),release)
@@ -5235,7 +5235,7 @@
 __OPTIMIZEFLAG = -O0
 endif
 ifeq ($(BUILD),release)
-__OPTIMIZEFLAG = -O2
+__OPTIMIZEFLAG = -O3
 endif
 ifeq ($(USE_THREADS),0)
 __THREADSFLAG =
diff -r 11c2f3533abe -r 71959affad03 include/wx/msw/setup.h
--- a/include/wx/msw/setup.h    Sun Feb 11 08:29:01 2024 -0800
+++ b/include/wx/msw/setup.h    Sun Feb 11 09:32:43 2024 -0800
@@ -1648,7 +1648,7 @@
 #if defined(_MSC_VER) && _MSC_VER >= 1600
     #define wxUSE_GRAPHICS_DIRECT2D wxUSE_GRAPHICS_CONTEXT
 #else
-    #define wxUSE_GRAPHICS_DIRECT2D 0
+    #define wxUSE_GRAPHICS_DIRECT2D wxUSE_GRAPHICS_CONTEXT
 #endif

 // wxWebRequest backend based on WinHTTP.
diff -r 11c2f3533abe -r 71959affad03 include/wx/msw/setup_inc.h
--- a/include/wx/msw/setup_inc.h        Sun Feb 11 08:29:01 2024 -0800
+++ b/include/wx/msw/setup_inc.h        Sun Feb 11 09:32:43 2024 -0800
@@ -33,7 +33,7 @@
 #if defined(_MSC_VER) && _MSC_VER >= 1600
     #define wxUSE_GRAPHICS_DIRECT2D wxUSE_GRAPHICS_CONTEXT
 #else
-    #define wxUSE_GRAPHICS_DIRECT2D 0
+    #define wxUSE_GRAPHICS_DIRECT2D wxUSE_GRAPHICS_CONTEXT
 #endif

 // wxWebRequest backend based on WinHTTP.
```
NateJoe@TinkeringAround UCRT64 ~/wxWidgets/clang/dbgTesting324/wxWidgets-3.2.4

3) cd wxWidgets-3.2.4/build/msw
4) mingw32-make -f makefile.gcc SHARED=1 MONOLITHIC=1 USE_OPENGL=0 BUILD=release clean
5) mingw32-make -f makefile.gcc SHARED=1 MONOLITHIC=1 USE_OPENGL=0 BUILD=release

6) This ends up with an error I think is being caused by trying to generate a bug report.
    Something  about not being able to open a temporary directory:
```
gcc -c -o gcc_mswudll\wxjpeg_jfdctint.o  -O3 -mthreads -DNDEBUG -I..\..\lib\gcc_dll\mswu  -Wno-unused-local-typedefs -Wno-deprecated-declarations -fno-omit-frame-pointer -march=native -DwxUSE_OWNER_DRAWN=1 -freport-bug -MTgcc_mswudll\wxjpeg_jfdctint.o -MFgcc_mswudll\wxjpeg_jfdctint.o.d -MD -MP ../../src/jpeg/jfdctint.c
during RTL pass: final
../../src/jpeg/jfdctint.c: In function 'jpeg_fdct_6x6':
../../src/jpeg/jfdctint.c:577:1: internal compiler error: in seh_cfa_offset, at config/i386/winnt.cc:1137
  577 | }
      | ^
Please submit a full bug report, with preprocessed source.
See <https://github.com/msys2/MINGW-packages/issues> for instructions.
gcc: fatal error: cannot execute 'C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/cc1.exe': open temporary output file: No such file or directory
compilation terminated.
mingw32-make: *** [makefile.gcc:6341: gcc_mswudll\wxjpeg_jfdctint.o] Error 1
```
P.S. The only reason I'm specifying the -fno-omit-frame-pointer option is because drmingw, the post-mortem dumper used by Code::Blocks, requires it.

### Expected behavior

Compiles without errors when using gcc-13.2.0

### Actual behavior

gets an error trying to generate  bug report.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by JaiSoone** [comment]
FWIF, native for me is 'haswell'.

**Comment by lazka** [comment]
See #20861

**Comment by lazka** [comment]
I've c-reduced the wxwidget build error as well and added it to the upstream bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115038#c1

**Comment by lazka** [comment]
There is a temporary workaround now by passing `-fno-fold-mem-offsets`

**Comment by JaiSoone** [comment]
If you don't think that it is important to get the gcc -freport-bug option to work, that is OK by me.I'll just treat it as so much boiler plate BS to be ignored should the occasion ever arise in the future.  Joe Searle

    On Sunday, May 12, 2024 at 10:02:03 PM PDT, Christoph Reiter ***@***.***> wrote:   

 


Closed #20864 as completed via #20884.

**Comment by lazka** [comment]
hm, yeah, not sure. It's annoying that `-freport-bug` can only be tested if gcc crashes from what I see.

I've created #20894 so we don't forget at least.

btw. the fixed package is now in the repo

**Comment by JaiSoone** [comment]
Thanks for the info. I've used gcc-14.1.0-3 and it works for me. rebuilt wxWidgets and Code::Blocks, then got that to compile a debug version of itself. I was wondering if some environment variable needed to be set in order for it to find suitable temporary directory.
Thanks again!

    On Monday, May 13, 2024 at 11:57:20 AM PDT, Christoph Reiter ***@***.***> wrote:   

 


hm, yeah, not sure. It's annoying that -freport-bug can only be tested if gcc crashes from what I see.

I've created #20894 so we don't forget at least.

btw. the fixed package is now in the repo

**Comment by FlightControl-User** [comment]
[1/6] Building CXX object CMakeFiles/KickC.dir/src/main/kickc/parse/CParser.ixx.obj
FAILED: CMakeFiles/KickC.dir/src/main/kickc/parse/CParser.ixx.obj CMakeFiles/KickC.dir/CParser.gcm 
C:\msys64\ucrt64\bin\g++.exe -DANTLR4CPP_STATIC -IC:/Users/svenv/CLionProjects/KickC/cmake-build-debug-mingw-msys2/antlr4_runtime/src/antlr4_runtime/runtime/Cpp/runtime/src -IC:/Users/svenv/CLionProjects/KickC -IC:/Users/svenv/CLionProjects/KickC/libs -IC:/Users/svenv/CLionProjects/KickC/src/main/include -IC:/Users/svenv/CLionProjects/KickC/src/main/kickc -IC:/Users/svenv/CLionProjects/KickC/src/main/modules -IC:/Users/svenv/CLionProjects/KickC/cmake-build-debug-mingw-msys2/antlr4cpp_generated_src/KickCLexer -IC:/Users/svenv/CLionProjects/KickC/cmake-build-debug-mingw-msys2/antlr4cpp_generated_src/KickCParser -Mmodules -freport-bug -g -std=gnu++23 -fdiagnostics-color=always -MD -MT CMakeFiles/KickC.dir/src/main/kickc/parse/CParser.ixx.obj -MF CMakeFiles\KickC.dir\src\main\kickc\parse\CParser.ixx.obj.d -fmodules-ts -fmodule-mapper=CMakeFiles\KickC.dir\src\main\kickc\parse\CParser.ixx.obj.modmap -MD -fdeps-format=p1689r5 -x c++ -o CMakeFiles/KickC.dir/src/main/kickc/parse/CParser.ixx.obj -c C:/Users/svenv/CLionProjects/KickC/src/main/kickc/parse/CParser.ixx
In module imported at C:/Users/svenv/CLionProjects/KickC/src/main/kickc/cpu/Cpu65xx.ixx:14:1,
of module Cpu65xx, imported at C:/Users/svenv/CLionProjects/KickC/src/main/kickc/cpu/CpuHuc6280.h:10,
        included from C:/Users/svenv/CLionProjects/KickC/src/main/kickc/model/TargetCpu.h:21,
                 from C:/Users/svenv/CLionProjects/KickC/src/main/kickc/model/TargetPlatform.h:13,
                 from C:/Users/svenv/CLionProjects/KickC/src/main/kickc/model/Program.h:12,
                 from C:/Users/svenv/CLionProjects/KickC/src/main/kickc/parse/CParser.ixx:13:
CpuAddressingMode: note: unable to represent further imported source locations
C:/Users/svenv/CLionProjects/KickC/src/main/kickc/parse/CParser.ixx:21:9: internal compiler error: in write_location, at cp/module.cc:16271
   21 | export  module CParser;
      |         ^
Please submit a full bug report, with preprocessed source.
See <https://github.com/msys2/MINGW-packages/issues> for instructions.
g++.exe: fatal error: cannot execute 'C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/cc1plus.exe': open temporary output file: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.
