### ISSUE TITLE
ICE in gcc 14.1.0 trying to compile emacs from source

### ISSUE THREAD

**Issue by cyrilarnould** [msys2/MINGW-packages#20879]
### Description / Steps to reproduce the issue

Trying to compile emacs from source, I get an internal compilation error. I do need to patch `src/syswait.c` to forcibly include `<sys/wait.h>`, as I get an implicit function declaration error otherwise (I've reported this upstream). The (hacky) patch: 

[syswait.patch](https://github.com/msys2/MINGW-packages/files/15285428/syswait.patch)

The steps to reproduce:

```
git clone https://git.savannah.gnu.org/git/emacs.git
cd emacs
git checkout emacs-29.3
git apply syswait.patch
./autogen.sh
./configure
make
```

Contrary to #20861 (which seems similar), I'm _not_ compiling with `-fno-omit-frame-pointer`, just the default CFLAGS `-g3 -O2 -gdwarf-2`. OTOH, the issue _does_ seem to go away when compiling with `-O1`.

### Expected behavior

No ICE

### Actual behavior

```
  CC       thread.o
during RTL pass: dwarf2
thread.c: In function 'Fthread_yield':
thread.c:725:1: internal compiler error: in dwarf2out_frame_debug_expr, at dwarf2cfi.cc:2112
  725 | }
      | ^
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://github.com/msys2/MINGW-packages/issues> for instructions.
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Sure

**Comment by lazka** [comment]
Thanks. This this work before (with GCC 13.2.0)?

**Comment by lazka** [comment]
Your example also fails with "-fno-omit-frame-pointer" like the other issues, so it might be related at least.

**Comment by cyrilarnould** [comment]
> Thanks. Did this work before (with GCC 13.2.0)?

Haven't personally tested it, but I guess the current `mingw-w64-emacs` release (also 29.3) is probably still built with GCC 13.2.

> I'm going to reduce both cases and file them upstream.

Thanks!

**Comment by cyrilarnould** [comment]
I saw that `-fno-fold-mem-offsets` is suggested in your ticket as a workaround for the other issues, and it seems to solve the emacs compilation as well. I want to take another look at the `-D_FORTIFY_SOURCE` and `-fno-optimize-sibling-calls' that were added to `mingw-w64-emacs` in the past before creating a PR though.

Also, the `sys/wait.h` issue can be fixed using `-Wno-error=implicit-function-declaration`.

**Comment by lazka** [comment]
Reduced to this in the meantime:

```
void a() {
    __builtin_unwind_init();
}
```

**Comment by cyrilarnould** [comment]
Ah, I guess there's no need to add the `-fno-fold-mem-offsets` flag if the upstream patch works, so we'd only need to add `-Wno-error=implicit-function-declaration`.

In the meantime, I've confirmed that #17550 and #17343 still are a problem, so the `-D_FORTIFY_SOURCE` and `-fno-optimize-sibling-calls` modifications are still necessary.
