### ISSUE TITLE
`mingw-w64-clang-x86_64-gcc-compat` is no longer included in `mingw-w64-clang-x86_64-toolchain`?

### ISSUE THREAD

**Issue by iahung3** [msys2/MINGW-packages#20881]
Today I do a new installation of MSYS2 and as usual I install `mingw-w64-clang-x86_64-toolchain` on CLANG64. But when I started to compile projects, I found absurd errors about POSIX functions being used. I checked the code and don't see any problems. I do `which gcc` and it tells me `/usr/bin/gcc`! Then I check with `pacman -S mingw-w64-clang-x86_64-gcc-compat` and I confirm that it's not installed.

**Comment by ognevny** [comment]
> I do `which gcc` and it tells me `/usr/bin/gcc`!

why did you install `gcc` from msys environment?

the gcc-compat was removed because it's not required for general use. please, run `pacman -R gcc` and incoke clang directly

**Comment by iahung3** [comment]
> > I do `which gcc` and it tells me `/usr/bin/gcc`!
> 
> why did you install `gcc` from msys environment?
> 
> the gcc-compat was removed because it's not required for general use. please, run `pacman -R gcc` and incoke clang directly

I would rather install the `mingw-w64-clang-x86_64-gcc-compat` package. I do use the MSYS GCC so I installed it.

**Comment by iahung3** [comment]
> > > > I do `which gcc` and it tells me `/usr/bin/gcc`!
> > > 
> > > 
> > > why did you install `gcc` from msys environment?
> > > the gcc-compat was removed because it's not required for general use. please, run `pacman -R gcc` and incoke clang directly
> > 
> > 
> > I would rather install the `mingw-w64-clang-x86_64-gcc-compat` package. I do use the MSYS GCC so I installed it.
> 
> use UCRT64 environment for gcc toolchain

I use MSYS GCC in MSYS Shell. I sometimes need to develop for POSIX but I don't have Linux!

**Comment by MehdiChinoune** [comment]
We did it in purpose, so people don't get confused and think that gcc is the real gnu `gcc`.

**Comment by iahung3** [comment]
> We did it in purpose, so people don't get confused and think that gcc is the real gnu `gcc`.

I don't think people will get confused. `gcc -v` still shows Clang.
