### ISSUE TITLE
GCC for Clang-based environments?

### ISSUE THREAD

**Issue by iahung3** [msys2/MINGW-packages#20880]
CLANG64 already has GCC ports like https://packages.msys2.org/groups/mingw-w64-clang-x86_64-arm-none-eabi-toolchain. What about adding `mingw-w64-clang-x86_64-toolchain-gcc`? People will no longer have to switch between environments to have both Clang and GCC. On MinGW-based environments, there are packages for Clang. Why don't Clang-based environment have packages for GCC?

**Comment by ognevny** [comment]
> Why don't Clang-based environment have packages for GCC?

because they will be a clone of UCRT environment

**Comment by iahung3** [comment]
What about reuse the package name `mingw-w64-clang-x86_64-gcc`? We already have `mingw-w64-clang-x86_64-gcc-compat`.

**Comment by iahung3** [comment]
> > Why don't Clang-based environment have packages for GCC?
> 
> because they will become a clone of UCRT environment

Why do MinGW-based environments include packages for Clang? Isn't it will make them a clone of the CLANG64 environment? Yes, I know this Clang is using the GCC's standard C++ library `libstdc++` instead of `libc++` on Clang-based environment. But the point of adding GCC packages for Clang-based environment is you can use both GCC and Clang in the same environment.

**Comment by ognevny** [comment]
> Why do MinGW-based environments include packages for Clang? Isn't it will make them a clone of the CLANG64 environment? Yes, I know this Clang is using the GCC's standard C++ library `libstdc++` instead of `libc++` on Clang-based environment. But the point of adding GCC packages for Clang-based environment is you can use both GCC and Clang in the same environment.

in rare cases software can't be compiled with gcc, but can with clang. if you want to use gcc and clang in the same environment, use UCRT64 environment

**Comment by iahung3** [comment]
I understand. There are Clang packages for MinGW-based environments because this Clang will use the same `libstdc++` as GCC. Perhaps when GCC supports using of `libc++` like Clang supports using of `libstdc++`, the idea to add GCC packages for Clang-based environments will be viable.
