### ISSUE TITLE
[lua] cannot seek to the end of large file

### ISSUE THREAD

**Issue by sewbacca** [msys2/MINGW-packages#20892]
### Description / Steps to reproduce the issue

This bug prevents calculating the size of large files. It works as expected on the same system using WSL.
Reproduce with any file:
```lua
f = assert(io.open("somefile.txt"))
f:seek("set", 0x200000000)
```

Reproduce with a large file:
```lua
f = assert(io.open("largefile.txt"))
print(f:seek("end"))
```

### Expected behavior

`seek("set", 0x200000000)` should succeed (even if the actual file is smaller).
and `seek("end")` should return the correct file size.

### Actual behavior

`seek("set", 0x200000000)` fails with `bad argument #2 to 'seek' (not an integer in proper range)`
and `seek("end")` returns `-1` as file size.

It probably has something to with how [l_seeknum](https://github.com/lua/lua/blob/master/liolib.c#L116-L143) is defined at compile time.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

no

**Comment by luau-project** [comment]
Hello @sewbacca . Based on your input, I tried to fix your issue on [https://github.com/msys2/MINGW-packages/pull/21266](https://github.com/msys2/MINGW-packages/pull/21266). Please, download the artifacts generated by the build and tell me whether it works or not.
