### ISSUE TITLE
Build some qt5-*-debug packages for MINGW32

### ISSUE THREAD

**Issue by SlySven** [msys2/MINGW-packages#20902]
### Package name

qt5-base-debug, qt5-imageformats-debug, qt5-multimedia-debug, qt5-speech-debug, qt5-svg-debug, qt5-virtualkeyboard-debug, qt5-winextras-debug

### For which environment do you need the package?

MINGW32

### Provide a brief description why you need this package in the selected environment

I am in the process of port the project I code for, [Mudlet](https://github.com/Mudlet/Mudlet), from a CI system that has become very fragile (and now frequently borking) MSYS+(original) Mingw to use MSYS2+Mingw-w64 completely.

As one might guess from our usage of the original project we current only ship a 32-Bit Windows application and we do not want to just drop that without finding out how many of our users are on 32-bit first.

Our plans are to migrate to providing both 32 and 64 bit versions in the short term. At the same time as doing this I have been able to build private "debug" versions which has proved useful when hunting down problems.

However I have just found out that my previous attempts over the last couple of years are no longer buildable on MINGW32 because the listed debug versions of these Qt packages are no longer available in that environment though they are for the MINGW64 one. As such this makes it harder to hunt down issues that have occurred during the move from 32-Bits to 64-Bit - independent of changes that need to be mitigated in a change for the latter (only) from Qt5 to Qt6, before we drop support for 32-Bit *Windows* builds of our application (to be fair we have already done so for Linux and MacOS, but it ought to be possible for third parties to build 32-Bit versions for those OSes themselves - though it is up to them should they not get the mileage they hoped for 😀).

### Are you willing to submit a PR?

I'm not sure I know enough about your package build system to do so.

**Comment by Biswa96** [comment]
qt5 debug packages for 32 bit were removed in 54daf65c76c83bc88af2ec7cd7fa2fa30c6ae417 commit.

**Comment by SlySven** [comment]
So by studying that I might be able to get them back again?

**Comment by MehdiChinoune** [comment]
> So by studying that I might be able to get them back again?

I don't think so. You could build them yourself. like any other package (majority 99% of MSYS2 packages).
I dropped them because of their huge size.

**Comment by SlySven** [comment]
> > So by studying that I might be able to get them back again?
> 
> I don't think so. You could build them yourself. like any other package (majority 99% of MSYS2 packages). I dropped them because of their huge size.

I don't think that is likely to be possible - the CI/CB system we use has a 60 minute time limit per job and I suspect it won't be possible to build a whole Qt platform (processor architecture) in that time frame...

... ah well I guess we'll just have to confine our Qt5 i686 builds to ship with the debug information for our own code.
