### ISSUE TITLE
Add DuckDB

### ISSUE THREAD

**Issue by joda01** [msys2/MINGW-packages#20918]
### Package name

DuckDB

### Brief description of package

DuckDB is a modern alternative to SQLite designed to be fast in-process analytical database.

There is still a gitflow for building duckdb under Windows
https://github.com/duckdb/duckdb/blob/v0.10.2/.github/workflows/Windows.yml#L234

### URL for package's homepage

https://duckdb.org/

### MINGW environments where you need the package

- [X] MINGW64

### Are you willing to submit a PR?

YES

**Comment by Biswa96** [comment]
I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/msys2/MINGW-packages/actions/runs/9340791502

**Comment by joda01** [comment]
Thank's @Biswa96! In `/mingw64/lib/cmake/DuckDB/DuckDBExports.cmake` at line `50` the installation prefix is hard coded with `/mingw64`. 
```
# The installation prefix configured by this project.
set(_IMPORT_PREFIX "/mingw64")
```

This leads to a cmake error when trying to look for the libs:

```
CMake Error at C:/msys64/mingw64/lib/cmake/DuckDB/DuckDBExports.cmake:124 (message):
  The imported target "duckdb" references the file

     "/mingw64/lib/libduckdb.dll.a"

  but this file does not exist.  Possible reasons include:
```

**Comment by joda01** [comment]
`/msys64/mingw64/include/duckdb/common/shared_ptr.hpp` includes following headers which are not present

```
#include "duckdb/common/shared_ptr.ipp"
#include "duckdb/common/weak_ptr.ipp"
#include "duckdb/common/enable_shared_from_this.ipp"
```
[Uploading duckdb-install.zip…]()

However, when I tested locally my executing cmake install my header files looks different.
I uploaded the files of my manual installation (which works) with following copy pseudeo code:


````
Copy-Item -Path ".\lib\libduckdb-windows-amd64\libduckdb.dll" -Destination "$mingwBasePathWin\bin" -Force
Copy-Item -Path ".\lib\libduckdb-windows-amd64\libduckdb.dll.a" -Destination "$mingwBasePathWin\lib" -Force
Copy-Item -Path ".\lib\libduckdb-windows-amd64\libduckdb_static.a" -Destination "$mingwBasePathWin\lib" -Force
Copy-Item -Path ".\lib\libduckdb-windows-amd64\duckdb.hpp" -Destination "$mingwBasePathWin\include" -Force
Copy-Item -Path ".\lib\libduckdb-windows-amd64\duckdb.h" -Destination "$mingwBasePathWin\include" -Force
Copy-Item -Path ".\lib\libduckdb-windows-amd64\libparquet.dll.a" -Destination "$mingwBasePathWin\lib" -Force
Copy-Item -Path ".\lib\libduckdb-windows-amd64\libparquet_extension.a" -Destination "$mingwBasePathWin\lib" -Force
Copy-Item -Recurse -Path ".\lib\libduckdb-windows-amd64\duckdb" -Destination "$mingwBasePathWin\include" -Force
Copy-Item -Recurse -Path ".\lib\libduckdb-windows-amd64\cmake_local\*.cmake" -Destination "$mingwBasePathWin\lib\cmake\duckdb" -Force
Copy-Item -Recurse -Path ".\lib\libduckdb-windows-amd64\third_party\*.a" -Destination "$mingwBasePathWin\lib" -Force
````

**Comment by Biswa96** [comment]
Would you like to test the new duckdb 1.0.0 packages from GitHub Actions artifacts of that pull request? Link https://github.com/msys2/MINGW-packages/actions/runs/9361978265

**Comment by joda01** [comment]
Tested on my local Windows machine, works fine now.

- [x] Install okay
- [x] Find package in cmake okay
- [x] Compile the application okay
- [x] Execute the application okay   
- [x] Uninstall the package okay 

Reference project used for testing: https://github.com/joda01/imagec
