### ISSUE TITLE
fix for building codeblocks on 32 bit targets

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#20922]
### Description / Steps to reproduce the issue

there is a bug in the way windres is invoked when building the codeblocks executable, this seems to have been an oversight in the autotools based version we build since WX_CXXFLAGS returns -mthreads along with the wx definitions and windres cannot handle that. fixed by replacing WX_CXXFLAGS with WX_CPPFLAGS in makefile.am. both flags return the same with the exception that WX_CPPFLAGS omits the -mthreads flag.

### Expected behavior

well for it to build like it does if using the batch build scripts.

### Actual behavior

windres chokes on the -mthreads -flag.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-26100

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [X] CLANG32
- [ ] CLANGARM64

**Comment by revelator** [comment]
[002-fix-32bit-build.zip](https://github.com/msys2/MINGW-packages/files/15328251/002-fix-32bit-build.zip)

patch for the aforementioned problem.

i cant do pull requests atm since im moving and im using my phone as a wifi hotspot (slow as mollases but atleast i can post).

feel free to add it the 32 bit version works just fine with this patch.

**Comment by ognevny** [comment]
msys2 doesn't provide codeblocks for i686
