### ISSUE TITLE
Add Skylark Editor

### ISSUE THREAD

**Issue by iahung3** [msys2/MINGW-packages#20931]
### Package name

mingw-w64-skylark

### Brief description of package

Skylark Editor is written in C, a high performance text/hex editor. Embedded Database-client/Redis-client/Lua-engine. You can run Lua scripts and SQL files directly.

### URL for package's homepage

https://github.com/adonais/skylark

### Provide a basic test case to validate the package's functionality.

https://github.com/adonais/skylark

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment]
The project is not quite active. We've many well known text editors or IDE packages - vim, nano, neovim, gedit, geany, kate, gnome-text-editor etc.
