### ISSUE TITLE
Documentation issue (instructions on how to install gcc)

### ISSUE THREAD

**Issue by dfkettle** [msys2/MINGW-packages#20949]
There seems to be a mistake in the instructions for installing MSYS2 and gcc on the "Getting Started" page (https://www.msys2.org/). I was able to install MSYS2 and bring up a terminal without any problem. Then I tried to install gcc with the following command:

`pacman -S mingw-w64-ucrt-x86_64-gcc`

The installation seemed to complete successfully, but when I tried to run the command 'gcc --version', I got this response:

`bash: gcc: command not found`

After a lot of searching, I found another web site (https://sajidifti.medium.com/how-to-install-gcc-and-gdb-on-windows-using-msys2-tutorial-0fceb7e66454) with instructions on how to install MSYS2 and gcc, which outlined the same steps, except that the command for installing gcc looked like this:

`pacman -S mingw-w64-x86_64-gcc`

Lo and behold, this worked and the gcc command was found. I assume that the instructions on your site are a bit out-of-date, or there's something odd about my Windows installation, I'm not sure. I don't know what the difference is between the two packages (both installed without error), but one worked and the other didn't. I'm running under Windows 10 Home Edition (64-bit).

**Comment by Biswa96** [comment]
The mingw-w64-ucrt-x86_64-gcc package installs gcc in UCRT64 environment. The installation procedure suggests to open UCRT64 environment also. See https://www.msys2.org/

**Comment by dfkettle** [comment]
I just ran the command in the window that opened by default after installing MSYS2. Your instructions might be a little clearer, considering the name of the page "Getting Started". Only one icon was created, which I guess opens the other kind of window (not a UCRT64 window).

**Comment by Biswa96** [comment]
The following screenshot shows the window that opened by default after installing msys2. And that is the ucrt64 environment. 

![image](https://github.com/msys2/MINGW-packages/assets/31443074/bcbe4409-368d-4dfc-9edd-841e484b2457)
