### ISSUE TITLE
ZSTD PKGBUILD uses incorrect parameter

### ISSUE THREAD

**Issue by brisingraerowing** [msys2/MINGW-packages#20947]
### Description / Steps to reproduce the issue

[This line](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-zstd/PKGBUILD#L49) is wrong. ZSTD's CMake files uses `ZSTD_BUILD_SHARED` to control shared library compilation.

### Expected behavior

Correct parameter is used

### Actual behavior

Wrong parameter is used

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
`ZSTD_BUILD_SHARED` is ON by default, so not a big deal.
Will fix it next update.
