### ISSUE TITLE
Gettext build error on UCRT

### ISSUE THREAD

**Issue by brisingraerowing** [msys2/MINGW-packages#20948]
### Description / Steps to reproduce the issue

1. Build Gettext on UCRT
2. Error when building GNULIB localtime.c

```
localtime.c: In function 'rpl_localtime':
localtime.c:66:24: error: initialization of 'char *' from incompatible pointer type 'char **' [-Wincompatible-pointer-types]
   66 |         for (char *s = env; *s != NULL; s++)
      |                        ^~~
localtime.c:66:32: warning: comparison between pointer and integer
   66 |         for (char *s = env; *s != NULL; s++)
      |                                ^~
localtime.c:70:28: error: initialization of 'wchar_t *' {aka 'short unsigned int *'} from incompatible pointer type 'wchar_t **' {aka 'short unsigned int **'} [-Wincompatible-pointer-types]
   70 |         for (wchar_t *ws = wenv; *ws != NULL; ws++)
      |                            ^~~~
localtime.c:70:38: warning: comparison between pointer and integer
   70 |         for (wchar_t *ws = wenv; *ws != NULL; ws++)
      |     
```

GNULIB git has fixed code.

### Expected behavior

No build error

### Actual behavior

Build error

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
This is expected to happen with gcc-14, just add `-Wno-incompatible-pointer-types` to CFLAGS.
