### ISSUE TITLE
mosquitto have no 32bit version

### ISSUE THREAD

**Issue by lygstate** [msys2/MINGW-packages#20962]
### Description / Steps to reproduce the issue

install pacman -S mingw-w64-i686-mosquitto 

### Expected behavior

mingw-w64-i686-mosquitto exist

### Actual behavior

mingw-w64-i686-mosquitto not published

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

maybe,

**Comment by MehdiChinoune** [comment]
We removed as part of phasing out 32-bit see: https://www.msys2.org/news/#2023-12-13-starting-to-drop-some-32-bit-packages
