### ISSUE TITLE
cairo: pkgconfig files reference `-ldl` in Libs.private on clangarm64

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#20974]
I believe this is the cause of the build error of inkscape currently being seen.  I don't know why that is though.  This is not present in the version in clang64.

**Comment by jeremyd2019** [comment]
I rebuilt sqlite3 locally (on "CI" version of runner) and it did not include `-ldl` anymore.  I am attempting to rebuild cairo now to see if/why it has `-ldl`.

**Comment by jeremyd2019** [comment]
That doesn't show `-ldl` either.  I will try a PR ci run rebuilding those two packages.  I wonder what else may have this issue though.

**Comment by jeremyd2019** [comment]
bdw-gc.pc seems to still have it too...

**Comment by jeremyd2019** [comment]
Unfortunately it appears that cairo does not successfully rebuild on MINGW64/UCRT64.

**Comment by Biswa96** [comment]
`-Wno-error=incompatible-pointer-types`

**Comment by lazka** [comment]
The BUILDINFO files of the latest vs the previous cairo shows that some unrelated packages where installed in the latest one. Maybe some leftovers of a stuck pacman recovery?

**Comment by lazka** [comment]
Should we add some reset script to the autobuild CI?

```console
TO_REMOVE=$(comm -23 <(pacman -Qq | sort) <(pactree -ul base | sed 's/[<>=].*//' | sort -u))
if [[ -n "$TO_REMOVE" ]]; then
    pacman -Rdd $TO_REMOVE
fi
```

**Comment by jeremyd2019** [comment]
I made a script to look at clangarm64 packages.  It seems looking for packages built having mingw-w64-clang-aarch64-dlfcn installed finds a *ton* of them, from 2021 to the present.  Looking specifically for `/clangarm64/{lib,share}/pkgconfig/*.pc` files containing `-ldl` I find only ffmpeg (which does makedepend on dlfcn so this is probably expected) and openvr (which does not - maybe a rebuild of that is also in order)

**Comment by jeremyd2019** [comment]
Nope, rebuilding openvr didn't change its .pc file, and in fact clang64's has `-ldl` in it as well.  Also, I found a bug in my script that meant that the build dates for packages that had dlfcn installed were garbage.

**Comment by jeremyd2019** [comment]
OK, think I got my script squared away.  seeing 428 packages that had dlfcn installed but I'm not seeing a reason for it.  Between January 25 and March 17, 2024, except for mingw-w64-mediainfo on May 4.  I'm not seeing why mediainfo would have had dlfcn installed.
[dlfcn-installed.txt](https://github.com/msys2/MINGW-packages/files/15428111/dlfcn-installed.txt)

**Comment by jeremyd2019** [comment]
I tried a differect tack, and hacked something together with package-grokker to check all clangarm64 packages for references to `libdl.dll`.

mingw-w64-clang-aarch64-aspell-0.60.8.1-2-any.pkg.tar.zst
mingw-w64-clang-aarch64-mlt-7.22.0-1-any.pkg.tar.zst
mingw-w64-clang-aarch64-tslib-1.23-1-any.pkg.tar.zst

mlt depends on dlfcn, so that's probably expected, but the other two may not be
