### ISSUE TITLE
Re-enable multi-threading for mingw-w64-ucrt-x86_64-imagemagick and variants

### ISSUE THREAD

**Issue by saschacurzon** [msys2/MINGW-packages#20983]
### Description / Steps to reproduce the issue

Hello,

This commit - [mingw-w64-ucrt-x86_64-imagemagick](https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-imagemagick?repo=ucrt64) added the "--without-threads" line to the ImageMagick configure section of PKGBUILD. This means that the packages (I have tested the normal one, ucrt64 and clang64) are only single threaded. I removed the line and rebuilt all three packages locally and multi-threaded support is restored. I do not need all three packages as the ucrt one is the most suitable. The commit mentions that adding this line also fixed a clang compiler error but I tested building using clang64 with and without the line and I could not see any difference but I must admit I am no expert.

If this line does need to be there, then any guidance as to how to enable native Windows threads for mingw-w64-ucrt-x86_64-imagemagick would be most welcome. I have spent a few days trying to make it work but without any success.

Many thanks for any pointers or advice!

### Expected behavior

That the package would use all CPUs to process images.

### Actual behavior

The package only uses a single CPU to process images.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by Biswa96** [comment]
Does `--without-thread` option really disable multi-threading support in ImageMagick? With threading option, the code depends on pthread which is not present in Windows platform. The pthread was disable so that ImageMagick can use native Windows threading APIs. See the conditions when MAGICKCORE_THREAD_SUPPORT is not defined but MAGICKCORE_WINDOWS_SUPPORT is defined.

https://github.com/ImageMagick/ImageMagick/blob/main/MagickCore/thread.c
https://github.com/ImageMagick/ImageMagick/blob/main/MagickCore/thread-private.h

**Comment by Biswa96** [comment]
Is `magick -list resource` lying about the threads count with `--without-threads` option? Should that option be removed?

**Comment by saschacurzon** [comment]
I can confirm that when OpenMP is listed and the threads = 19 then multiple CPUs are being used whereas if OpenMP is not listed and threads = 1 then only a single CPU is being used.

**Comment by Biswa96** [comment]
I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/msys2/MINGW-packages/actions/runs/9331510950

**Comment by saschacurzon** [comment]
Many thanks! I have just tested the ucrt64 version as that is the one I want to use and I can confirm that multi-threading is back and performance is restored! Do you know when this will be released? I see that the latest package is 7.1.1.33-1 whereas this fix is available in 7.1.1.33-2?

**Comment by Biswa96** [comment]
> Do you know when this will be released?

The new package is in queue list now https://packages.msys2.org/queue

**Comment by saschacurzon** [comment]
So many thanks all. The new publicly available package is great - I just tested it! :-)
