### ISSUE TITLE
Strip compiler build information

### ISSUE THREAD

**Issue by void2012** [msys2/MINGW-packages#20993]
When compiling using code::blocks, my binary executable has many copies of the compiler build string
"GCC: (Rev3, Built by MSYS2 project) 13.2.0". They won't go even if I pass the -s option and even If I build in the optimized release build.

I wonder if there is any way to strip that information out? Thanks

**Comment by Biswa96** [comment]
Is there any issue with having that string in binary files?

**Comment by MehdiChinoune** [comment]
I don't think this is even possible on other platforms.
Please consider reporting the bug upstrea.
We could reopen the issue if it is specific to MSYS2/MinGW-w64
