### ISSUE TITLE
-DNGHTTP3_STATICLIB CFLAGS option has to be specified when building static curl to link against libnghttp3.a

### ISSUE THREAD

**Issue by sammycage** [msys2/MINGW-packages#21006]
### Description / Steps to reproduce the issue

I tried compiling my library using `msys2/setup-msys2@v2` in GitHub Actions with `CURL_STATICLIB` enabled. This issue is similar to  #5440

### Expected behavior

It was supposed to compile successfully, like the previous `mingw-w64-x86_64-curl` build.

### Actual behavior

undefined reference to `__imp_nghttp3_*'

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-20348

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by ReenigneArcher** [comment]
I wonder if this is the same problem? https://github.com/LizardByte/Sunshine/actions/runs/9278791852/job/25530652407#step:7:501

Although our build worked a few hours ago, so I'm not sure it's the same. We are using ucrt64.

**Comment by MehdiChinoune** [comment]
@ReenigneArcher Would you test artifact from #21008 and see it fixes the issue.

**Comment by ReenigneArcher** [comment]
@MehdiChinoune sorry, I just saw this. Just had another build fail, but I don't know if there is a delay between merging here and being able to access the updated package.

**Comment by Biswa96** [comment]
Check if the curl package version is 8.8.0-2 (as of writing this comment) in CI build log.

**Comment by ReenigneArcher** [comment]
It's 8.8.0-1. I cleared the cache for the msys2 action, but it's still the same. I guess there's a delay.
