### ISSUE TITLE
pango help2man

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#21018]
### Description / Steps to reproduce the issue

seems to be a problem building pango when help2man is installed (also noted by the pango devs)

### Expected behavior

would build the man file for pango-view when help2man is installed

### Actual behavior

fails due to some bug with how meson handles help2man (seems path related) so i made a package for a python port of help2man for mingw64 and a patch for using the mingw-w64-python-help2man.

[mingw-w64-pango.zip](https://github.com/msys2/MINGW-packages/files/15487667/mingw-w64-pango.zip)
[mingw-w64-python-help2man.zip](https://github.com/msys2/MINGW-packages/files/15487669/mingw-w64-python-help2man.zip)

this fixes the man build problem.
i forgot to update the build number but it should be an easy fix.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-26100

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment]
Please provide the error output. I can not reproduce the issue in my system.

**Comment by revelator** [comment]
should probably mark it as invalid though it does fix a user case problem if mingw perl is installed.
