### ISSUE TITLE
Unable to link to static glib2 (again)

### ISSUE THREAD

**Issue by flinco** [msys2/MINGW-packages#21012]
### Description / Steps to reproduce the issue

1. Create a test.c with the following content:

```
#include <glib-object.h>
int main(int argc, char *argv[]) {
  GValue *lgv = g_new0(GValue, 1);
  g_value_init(lgv, G_TYPE_INT);
  g_value_set_int(lgv, 0);
  return 0;
}
```

2. Compile with:

`cc -DGLIB_STATIC_COMPILATION -DG_DISABLE_DEPRECATED $(pkg-config.exe --cflags gobject-2.0) -c -o test.o test.c`

3. Link with:

`cc -static -static-libgcc test.o -o test.exe $(pkg-config.exe --libs --static gobject-2.0) -liconv`

### Expected behavior

The executable `test.exe` is created successfully.

### Actual behavior

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: test.o:test.c:(.text+0x36): undefined reference to `__imp_g_value_init'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: test.o:test.c:(.text+0x4b): undefined reference to `__imp_g_value_set_int'
collect2.exe: error: ld returned 1 exit status
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by flinco** [comment]
I wrote 'again' in the title since I'm facing the issue compiling the same applications for which I has a [similar issue](https://github.com/msys2/MINGW-packages/issues/10211) in the 2021.

**Comment by MehdiChinoune** [comment]
Try adding `-DGOBJECT_STATIC_COMPILATION`

**Comment by flinco** [comment]
It worked. Many thanks.
