### ISSUE TITLE
libslirp static link error

### ISSUE THREAD

**Issue by maron2000** [msys2/MINGW-packages#21035]
### Description / Steps to reproduce the issue

After libslirp is updated to 4.8.0, I get static link error using libslirp.

Edit: Fixed according to @MehdiChinoune 's information.

### Expected behavior

Link successfully as it did before.

### Actual behavior

```
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: misc/libmisc.a(ethernet_slirp.o):ethernet_slirp:(.text+0x97): undefined reference to `__imp_slirp_input'
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: misc/libmisc.a(ethernet_slirp.o):ethernet_slirp:(.text+0x69f): undefined reference to `__imp_slirp_cleanup'
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: misc/libmisc.a(ethernet_slirp.o):ethernet_slirp:(.text+0x975): undefined reference to `__imp_slirp_remove_hostfwd'
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: misc/libmisc.a(ethernet_slirp.o):ethernet_slirp:(.text+0x10a6): undefined reference to `__imp_slirp_pollfds_fill'
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: misc/libmisc.a(ethernet_slirp.o):ethernet_slirp:(.text+0x1109): undefined reference to `__imp_slirp_pollfds_poll'
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: misc/libmisc.a(ethernet_slirp.o):ethernet_slirp:(.text+0x1a6e): undefined reference to `__imp_slirp_add_hostfwd'
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: misc/libmisc.a(ethernet_slirp.o):ethernet_slirp:(.text+0x1c63): undefined reference to `__imp_slirp_version_string'
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: misc/libmisc.a(ethernet_slirp.o):ethernet_slirp:(.text+0x213f): undefined reference to `__imp_slirp_new'
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

github runner `windows-latest`

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
This has nothing to do with gcc-14.
libslirp was updated to 4.8.0 which start exporting/importing functions whether it's shared or static.
https://gitlab.freedesktop.org/slirp/libslirp/-/commit/e6a7465cca7044da75cba97193c4bb570f608aa3

Someone has to fix the issue and make it export/import only with shared library.

**Comment by maron2000** [comment]
@MehdiChinoune Thanks for looking into this. 
Well understood, and I will temporarily disable libslirp until it is fixed.

**Comment by Biswa96** [comment]
For static linking, that could be fixed by adding a workaround as of now.

```c
#ifdef SLIRP_EXPORT
  #undef SLIRP_EXPORT
  #define SLIRP_EXPORT
#endif
```

I shall try to propose a change in upstream, e.g. adding `SLIRP_STATIC` symbol for static linking.

**Comment by Biswa96** [comment]
> I shall try to propose a change in upstream, e.g. adding `SLIRP_STATIC` symbol for static linking.

I have opened a merge request in upstream project with that feature https://gitlab.freedesktop.org/slirp/libslirp/-/merge_requests/134

**Comment by Biswa96** [comment]
The feature was added in upstream commit https://gitlab.freedesktop.org/slirp/libslirp/-/commit/84361923047f867561efc0184a4af9c66c8ba852. I have added a pull request to add that and also added that macro in Cflags.private in pkgconfig file.

So, for static linking, you have to define `LIBSLIRP_STATIC` macro or let pkgconf handle it

```
$ pkgconf -cflags -static slirp
-IC:/msys64/ucrt64/include/slirp -IC:/msys64/ucrt64/include/glib-2.0 -IC:/msys64/ucrt64/lib/glib-2.0/include -DLIBSLIRP_STATIC
```

**Comment by maron2000** [comment]
@Biswa96 Thank you very much for fixing this upstream.
The code I'm dealing with has currently disabled libslirp,
but I shall try adding the macro when the release is updated.

**Comment by maron2000** [comment]
I updated libslirp and added LIBSLIRP_STATIC macro, and the project built successfully on both MinGW32 and 64.
With many thanks.
