### ISSUE TITLE
[ccache] update to 4.10

### ISSUE THREAD

**Issue by silverqx** [msys2/MINGW-packages#21032]
### Package name

ccache

### New version number

4.10

**Comment by silverqx** [comment]
I would like to ask how long it will take to be available in pacman repo? I have no idea.

**Comment by Biswa96** [comment]
> I would like to ask how long it will take to be available in pacman repo? I have no idea.

ccache is in queue now https://packages.msys2.org/queue

**Comment by silverqx** [comment]
I see this packages.msys2.org page first time, thx

```
[staging]
Server = https://repo.msys2.org/staging/
SigLevel = Never
```

Is my temp. solution until will be released. 😎

**Comment by silverqx** [comment]
I know, I will wait until be released.
