### ISSUE TITLE
gobject-introspection: Gio Typelib error on method call: 'gi.repository.Gio' object has no attribute 'content_type_get_icon'

### ISSUE THREAD

**Issue by cal0pteryx** [msys2/MINGW-packages#21044]
### Description / Steps to reproduce the issue

Hi there! We're using [gobject-introspection via MSYS2](https://packages.msys2.org/package/mingw-w64-x86_64-gobject-introspection) for a Python project.
After upgrading from gobject-introspection `1.78.1` to `1.80.1`, calling `Gio.content_type_get_icon("your_mime_type_here")` fails with the following error:

**Steps to reproduce**

```python
from gi.repository import Gio

Gio.content_type_get_icon("audio/mp4")
```

Calling this python code yields the following traceback:

```
Traceback (most recent call last):
  File "C:/msys64/home/X/test/test5.py", line 3, in <module>
    Gio.content_type_get_icon("audio/mp4")
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/mingw64/lib/python3.11/site-packages/gi/overrides/__init__.py", line 31, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/mingw64/lib/python3.11/site-packages/gi/module.py", line 130, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gio' object has no attribute 'content_type_get_icon'. Did you mean: 'content_type_equals'?
```

</details>

<details>
  <summary>Alternative traceback</summary>

```
'gi.repository.Gio' object has no attribute 'content_type_get_icon'

C:/msys64/home/appveyor/gajim/win/_build_root/mingw64/lib/python3.11/site-packages/gi/module.py in __getattr__ at line 130
name "content_type_get_icon"
self <IntrospectionModule 'Gio' from 'C:\\Program Files\\Gajim\\lib\\girepository-1.0\\Gio-2.0.typelib'>
C:/msys64/home/appveyor/gajim/win/_build_root/mingw64/lib/python3.11/site-packages/gi/overrides/__init__.py in __getattr__ at line 31

name "content_type_get_icon"
self <GioProxyModule <IntrospectionModule 'Gio' from 'C:\\Program Files\\Gajim\\lib\\girepository-1.0\\Gio-2.0.typelib'>>
```

</details>

Checking `Gio-2.0.typelib` manually shows indeed that `content_type_get_icon` is missing, while for example `content_type_get_mime_type` and others exist.

Cross posting: https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/509

### Expected behavior

Method call should work as before upgrading the gobject-introspection package.

### Actual behavior

Error 'gi.repository.Gio' object has no attribute 'content_type_get_icon' is raised.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Where does 'C:\\Program Files\\Gajim\\lib\\girepository-1.0\\Gio-2.0.typelib' file come from? Do you think that file will conflict with files in mingw gobject-introspection package?

**Comment by Biswa96** [comment]
Please provide the steps to reproduce the issue.

**Comment by cal0pteryx** [comment]
> Please provide the steps to reproduce the issue.

I added a simple Python code example which triggers the error.

**Comment by cal0pteryx** [comment]
> Where does 'C:\Program Files\Gajim\lib\girepository-1.0\Gio-2.0.typelib' file come from? Do you think that file will conflict with files in mingw gobject-introspection package?

I'm not quite sure. The folder %programfiles%\Gajim does not exist on my machine. It may be an artifact from building the application though.

**Comment by Biswa96** [comment]
Copying the comment of g_content_type_get_icon function from gcontenttype.c to gcontenttype-win32.c fixes the issue. I shall try to create pull request in upstream with that change.

**Comment by Biswa96** [comment]
I have created a merge request in upstream to fix this issue https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4106

**Comment by cal0pteryx** [comment]
Great, thanks a lot!
