### ISSUE TITLE
[python-xlsxwriter] mingw-w64-x86_64-python-xlsxwriter-3.2.0-1-any.pkg.tar.zst file is corrupted

### ISSUE THREAD

**Issue by 777shuang** [msys2/MINGW-packages#21045]
### Description / Steps to reproduce the issue

`pacman -S mingw-w64-x86_64-python-xlsxwriter`

### Expected behavior

Installs successfully

### Actual behavior

![image](https://github.com/msys2/MINGW-packages/assets/100687590/66472e0b-d8aa-4a97-ba5b-5f6cd4225d4f)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
I can reproduce the issue in my system. Some server storage hardware issue was reported previously.

**Comment by lazka** [comment]
thanks, I'll have a look

**Comment by lazka** [comment]
The signature and the checksums all match. The fact that it affects the same package in multiple envs indicates that something went wrong with the (somewhat) recent MD5 checksum removal.

**Comment by lazka** [comment]
Ah, no, something different, the trailing "=" in the PKGBUILD confuses pacman, it's missing in the DB but gets compared to the PKGINFO file in the package which has it.

**Comment by lazka** [comment]
pacman got stricter with https://gitlab.archlinux.org/pacman/pacman/-/merge_requests/96 in the last release, which exposed this issue.

**Comment by lazka** [comment]
Filed upstream with pacman: https://gitlab.archlinux.org/pacman/pacman/-/issues/152

**Comment by lazka** [comment]
fixed now
