### ISSUE TITLE
[kdenlive] segmenation fault on start

### ISSUE THREAD

**Issue by thesword53** [msys2/MINGW-packages#21069]
### Description / Steps to reproduce the issue

When I launch Kdenlive it crashes on loading window

### Expected behavior

Kdenlive starts successfully

### Actual behavior

```
$ kdenlive
mlt_repository_init: failed to dlopen C:\msys64\ucrt64\lib\mlt/libmltplus.dll
  ("C:\msys64\ucrt64\lib\mlt\libmltplus.dll": Le module spécifié est introuvable.)
mlt_repository_init: failed to dlopen C:\msys64\ucrt64\lib\mlt/libmltrtaudio.dll
  ("C:\msys64\ucrt64\lib\mlt\libmltrtaudio.dll": Le module spécifié est introuvable.)
mlt_repository_init: failed to dlopen C:\msys64\ucrt64\lib\mlt/libmltsdl.dll
  ("C:\msys64\ucrt64\lib\mlt\libmltsdl.dll": Le module spécifié est introuvable.)
mlt_repository_init: failed to dlopen C:\msys64\ucrt64\lib\mlt/libmltsox.dll
  ("C:\msys64\ucrt64\lib\mlt\libmltsox.dll": Le module spécifié est introuvable.)
Segmentation fault
```

I noticed some DLLs from `mingw-w64-x86_64-mlt` and listed in logs above have missing dependencies:
```
ldd /ucrt64/lib/mlt/libmltsdl.dll
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffe75330000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ffe73e50000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ffe72e60000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7ffe73cb0000)
        libmltsdl.dll => /ucrt64/lib/mlt/libmltsdl.dll (0x7ffe6c790000)
        ucrtbase.dll => /c/Windows/System32/ucrtbase.dll (0x7ffe73260000)
        libwinpthread-1.dll => /mingw64/bin/libwinpthread-1.dll (0x7ffe59f80000)
        libmlt-7.dll => /mingw64/bin/libmlt-7.dll (0x7ffe44f60000)
        api-ms-win-crt-convert-l1-1-0.dll => not found
        api-ms-win-crt-environment-l1-1-0.dll => not found
        api-ms-win-crt-filesystem-l1-1-0.dll => not found
        api-ms-win-crt-heap-l1-1-0.dll => not found
        api-ms-win-crt-locale-l1-1-0.dll => not found
        api-ms-win-crt-private-l1-1-0.dll => not found
        api-ms-win-crt-runtime-l1-1-0.dll => not found
        api-ms-win-crt-stdio-l1-1-0.dll => not found
        api-ms-win-crt-string-l1-1-0.dll => not found
        api-ms-win-crt-time-l1-1-0.dll => not found
        api-ms-win-crt-utility-l1-1-0.dll => not found
        SDL.dll => not found
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
I can reproduce the issue in UCRT64 environment. @hmartinez82

**Comment by hmartinez82** [comment]
I'll take a look sometime soon.  Just for completion, the translation is `The specified module could not be found`

**Comment by hmartinez82** [comment]
@Biswa96 This line in qmlmanager.cpp 
```
        m_view->setSource(
            QUrl(id == Kdenlive::ClipMonitor ? QStringLiteral("qrc:/qml/kdenliveclipmonitor.qml") : QStringLiteral("qrc:/qml/kdenlivemonitor.qml")));
        root = m_view->rootObject();
```
Is the culprit. That root object is null, because the QML in the line before fails to load with:
`qrc:/qml/kdenliveclipmonitor.qml: module "org.kde.desktop" is not installed` 😑

**Comment by hmartinez82** [comment]
Seems to be related, and just as new https://bugs.gentoo.org/931924

**Comment by Biswa96** [comment]
If it fixes the issue please feel free to add that. Try to use kf6 kcoreaddons PKGBUILD as a template.

**Comment by hmartinez82** [comment]
Well that was part of the solution. It is loading that new QML style:
![image](https://github.com/msys2/MINGW-packages/assets/1100440/67ff3af7-73ae-4957-a356-a28ab23ce2d6)
But now the problem is still loading `kdenliveclipmonitor.qml`: 😑 and of course much worse to debug
![image](https://github.com/msys2/MINGW-packages/assets/1100440/60036c2e-d67d-4928-909a-f2e305b6f356)
This happens when executing the `m_view->setSource(` line

**Comment by hmartinez82** [comment]
@Biswa96 I'm going to add a workaround patch to Kdenlive. If `export QT_QUICK_CONTROLS_STYLE=Fusion` is done before starting Kdenlive, then it just works without SEGFAULTing. 

After that I'll look into why trying to use org.kde.desktop still leads to crashes even after adding that new package.
