### ISSUE TITLE
mingw-w64: syntax error in `time.h` in MinGW-w64 affecting Groonga build

### ISSUE THREAD

**Issue by otegami** [msys2/MINGW-packages#21077]
### Description / Steps to reproduce the issue

Step1: Attempted to build Groonga using the build steps provided  [here](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-groonga/PKGBUILD).
Step2: During the building process, the following error was raised in `time.h` from `mingw-w64`

```
  In file included from D:/M/msys64/mingw64/include/_mingw.h:10,
                   from D:/M/msys64/mingw64/include/corecrt.h:10,
                   from D:/M/msys64/mingw64/include/stdlib.h:9,
                   from C:/_/B/src/groonga-14.0.4/lib/grn.h:50,
                   from C:/_/B/src/groonga-14.0.4/lib/grn_cache.h:21,
                   from C:/_/B/src/groonga-14.0.4/lib/cache.c:19:
  D:/M/msys64/mingw64/include/time.h:217:84: error: expected ',' or ';' before '__asm__'
    217 |   wchar_t *__cdecl _wctime(const time_t *_Time) __MINGW_ATTRIB_DEPRECATED_SEC_WARN __MINGW_ASM_CALL(_wctime64);
        |                                                                                    ^~~~~~~~~~~~~~~~
  ninja: build stopped: subcommand failed.
  ==> ERROR: A failure occurred in build().
```

ref: Building Groonga failed [here](https://github.com/msys2/MINGW-packages/actions/runs/9378910604/job/25822911936).

### What I investigated

This error might be related to this commit: https://github.com/mingw-w64/mingw-w64/commit/e5ac8c5509cd729b97065733cf4b0df0ec732797 in `mingw-w64`. I suspect this commit may have introduced the syntax error? in `time.h`.
If I should make a issue in [mingw-w64](https://github.com/mingw-w64/mingw-w64), could you tell me?

### Expected behavior

Successfully build Groonga on CI MINGW64 environment.

### Actual behavior

During building step, mingw-w64 raised the following error.

```
  In file included from D:/M/msys64/mingw64/include/_mingw.h:10,
                   from D:/M/msys64/mingw64/include/corecrt.h:10,
                   from D:/M/msys64/mingw64/include/stdlib.h:9,
                   from C:/_/B/src/groonga-14.0.4/lib/grn.h:50,
                   from C:/_/B/src/groonga-14.0.4/lib/grn_cache.h:21,
                   from C:/_/B/src/groonga-14.0.4/lib/cache.c:19:
  D:/M/msys64/mingw64/include/time.h:217:84: error: expected ',' or ';' before '__asm__'
    217 |   wchar_t *__cdecl _wctime(const time_t *_Time) __MINGW_ATTRIB_DEPRECATED_SEC_WARN __MINGW_ASM_CALL(_wctime64);
        |                                                                                    ^~~~~~~~~~~~~~~~
  ninja: build stopped: subcommand failed.
  ==> ERROR: A failure occurred in build().
```

ref: Building Groonga failed [here](https://github.com/msys2/MINGW-packages/actions/runs/9378910604/job/25822911936).

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64: windows-2022 on GitHub Actions, UCRT64: windows-2022 on GitHub Actions

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Hi @otegami Thank you for reporting the issue. The fix is pending in upstream here https://sourceforge.net/p/mingw-w64/mailman/message/58780198/. It will be added soon.

**Comment by otegami** [comment]
Thank you so much for giving me this information. I will wait for it :pray:

**Comment by lazka** [comment]
please try now

**Comment by otegami** [comment]
Thank you so much for supporting it.
The CI about the following PR has passed 👍🏾 
- https://github.com/msys2/MINGW-packages/pull/21076
