### ISSUE TITLE
Add python-pyarrow

### ISSUE THREAD

**Issue by thesword53** [msys2/MINGW-packages#21070]
### Package name

python-pyarrow

### Brief description of package

Columnar in-memory analytics layer for big data — Python module.

### URL for package's homepage

https://arrow.apache.org/

### Provide a basic test case to validate the package's functionality.

This package is an optional dependency of `mingw-w64-x86_64-python-pandas`: https://pandas.pydata.org/docs/user_guide/pyarrow.html
Pandas >= 3.0.0 will probably require it: https://github.com/pandas-dev/pandas/issues/54466

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by lazka** [comment]
What about https://packages.msys2.org/base/mingw-w64-python-arrow ?

**Comment by Biswa96** [comment]
> What about https://packages.msys2.org/base/mingw-w64-python-arrow ?

https://archlinux.org/packages/extra/any/python-arrow/ != https://archlinux.org/packages/extra/x86_64/python-pyarrow/

**Comment by lazka** [comment]
ah, right, thanks!
