### ISSUE TITLE
Sonic 1&2 Decomp - Could NOT find Vorbis (missing: Vorbis_DIR)

### ISSUE THREAD

**Issue by shoober420** [msys2/MINGW-packages#21095]
### Description / Steps to reproduce the issue

1. launch mingw64.exe
2. git clone --recursive https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation
3. cmake -B build

### Expected behavior

Build completion

I have all the following libvorbis packages installed.

mingw-w64-x86_64-libvorbis
mingw-w64-i686-libvorbis
mingw-w64-ucrt-x86_64-libvorbis
mingw-w64-clang-x86_64-libvorbis
mingw-w64-clang-i686-libvorbis

### Actual behavior

Build failure

-- Building for: Ninja
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
found libogg
-- Could NOT find Vorbis (missing: Vorbis_DIR)
libvorbis not found, attempting to build from source
found GLEW
-- Configuring done (0.4s)
CMake Error at CMakeLists.txt:127 (add_library):
Cannot find source file:

dependencies/windows/libvorbis/lib/analysis.c

Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
.ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
.f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:127 (add_library):
No SOURCES given to target: libvorbis

CMake Generate step failed. Build files cannot be regenerated correctly.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-26227

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes

**Comment by Biswa96** [comment]
> 2\. clone repo

What repo?

**Comment by shoober420** [comment]
My apologies, its https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation

**Comment by Biswa96** [comment]
The issue is in the project cmake file. It wants to compile the dependencies from source. Follow the steps from dependencies/windows/dependencies.txt or modify cmake file to link with system dependencies.

**Comment by shoober420** [comment]
In those instructions, its asking to build an .sln file, which is a visual c++ file. I was trying to avoid installing Visual Studio, so i think ill have to find another way.
