### ISSUE TITLE
PR process fails with "database file for 'staging' does not exist"

### ISSUE THREAD

**Issue by heljkon** [msys2/MINGW-packages#21143]
### Description / Steps to reproduce the issue

Create a PR to process checks. See latest PRs:
* https://github.com/msys2/MINGW-packages/pull/21142
* https://github.com/msys2/MINGW-packages/pull/21141

### Expected behavior

CI processes PR

### Actual behavior

CI fails to bootstrap with
```
warning: database file for 'staging' does not exist (use '-Sy' to download)
error: failed to prepare transaction (could not find database)
Error: Process completed with exit code 1.
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

This is no client issue!

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Out of scope

**Comment by Biswa96** [comment]
msys2.org is down. Please wait.
