### ISSUE TITLE
[python-pre-commit] 

### ISSUE THREAD

**Issue by RobinMaub** [msys2/MINGW-packages#21161]
### Description / Steps to reproduce the issue

Hello support team,

I am a pre-commit user on Linux and I'd like to use it on Windows with msys2/mingw64. I installed it using `pacman -S mingw-w64-x86_64-python-pre-commit`, which goes fine. But at run, it is not working:
```
$ pre-commit run
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from C:/Users/XYZ/.cache/pre-commit/repogzwwsprl/py_env-python3.11/Scripts/python.exe>>
- expected version: 3.11.9.final.0

Check the log at C:/Users/XYZ/.cache/pre-commit/pre-commit.log
```

A guy answered that there is an issue in the package itself. The whole discussions is [here](https://stackoverflow.com/questions/78615923/pre-commit-version-did-not-match-created-version-on-msys2)

Any idea on the root cause / issue ?

### Expected behavior

It works directly after installation

### Actual behavior

the log shows:
**version information**
```
pre-commit version: 3.7.0
git --version: git version 2.45.1
sys.version:
    3.11.9 (main, Apr 12 2024, 09:55:31)  [GCC 13.2.0 64 bit (AMD64)]
sys.executable: C:/msys64/mingw64/bin/python.exe
os.name: nt
sys.platform: win32
```

**error information**
```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from C:/Users/robin.maubert.ch2/.cache/pre-commit/repogzwwsprl/py_env-python3.11/Scripts/python.exe>>
- expected version: 3.11.9.final.0
```

```
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/repository.py", line 99, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from C:/Users/XYZ/.cache/pre-commit/repogzwwsprl/py_env-python3.11/Scripts/python.exe>>
- expected version: 3.11.9.final.0
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
hm, not even the default config works, since that installs C libs that no longer build due to outdated Cython sources.

Can you share your pre-commit config?

**Comment by sdegrande** [comment]
I had the same issue, fixed with this patch (virtualenv on msys2 uses the same directories structure than on Linux)
[info: msys2/mingw64 updated on 29th of July, using the clang64 environment, pre-commit installed with pip]

```diff
 diff --git a/pre_commit/languages/python.py b/pre_commit/languages/python.py
index 0c4bb62..cb09f61 100644
--- a/pre_commit/languages/python.py
+++ b/pre_commit/languages/python.py
@@ -4,6 +4,7 @@ import contextlib
 import functools
 import os
 import sys
+import sysconfig
 from collections.abc import Generator
 from collections.abc import Sequence
 
@@ -48,7 +49,7 @@ def _read_pyvenv_cfg(filename: str) -> dict[str, str]:
 
 def bin_dir(venv: str) -> str:
     """On windows there's a different directory for the virtualenv"""
-    bin_part = 'Scripts' if sys.platform == 'win32' else 'bin'
+    bin_part = 'Scripts' if sys.platform == 'win32' and not "mingw" in sysconfig.get_platform() else 'bin'
     return os.path.join(venv, bin_part)

```

**Comment by RobinMaub** [comment]
@sdegrande do you have the pull request link ?

**Comment by sdegrande** [comment]
Mhhh... do you mean a PR on the github pre-commit repository ? Then there is not such PR because the pre-commit dev is not willing to integrate a mingw specific patch (see https://github.com/pre-commit/pre-commit/issues/3234)

So the patch is to be added in PKGBUILD (as far as I understand it...). I'm not used to pacman (I'm a Fedora user), but I could try to craft something...

Note that there's somehow the same kind of issue with langagues/conda.py and languages/node.py

**Comment by RobinMaub** [comment]
Arf sad. me neither but I am happy to help you...
@Biswa96 or @lazka could you help us on that to get back a working package ?

**Comment by sdegrande** [comment]
I'll get inspiration from some other packages, and propose a PR. That would give me a bit of knowledge about the pacman stuff, which is not worthless :-)

**Comment by RobinMaub** [comment]
so cool, many thanks ! Can we release the 3.7.1-3 to be able to get it ?
