### ISSUE TITLE
[lua-lgi] Add support to Lua 5.2 and 5.3

### ISSUE THREAD

**Issue by brunvonlope** [msys2/MINGW-packages#21171]
### Description / Steps to reproduce the issue

[lua-lgi](https://github.com/lgi-devs/lgi) supports newer versions of Lua:

> LGI is tested and compatible with standard Lua 5.1, Lua 5.2, Lua 5.3 and LuaJIT2

But MSYS2 don't package it with support to newer versions:
1. Install lua-lgi
2. Observes that it only links to lua5.1

### Expected behavior

Lua 5.2 and 5.3 support

### Actual behavior

Stuck at prehistoric Lua 5.1

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment]
I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/msys2/MINGW-packages/actions/runs/9528738412

**Comment by brunvonlope** [comment]
Hi @Biswa96. I wasn't able to test yet. I plan to do it today and give you a feedback.

**Comment by brunvonlope** [comment]
@Biswa96 Tested. Thanks for the package. lgi is working nice with Lua 5.3 🫂
