### ISSUE TITLE
mingw64 missing C11 threads.h header

### ISSUE THREAD

**Issue by ermarch** [msys2/MINGW-packages#21195]
### Description / Steps to reproduce the issue

After installing msys2-x86_64-20240507 I get a threads.h file in the MSYS2 environment but not when using mingw64

### Expected behavior

I would have assumed that if MSYS2 supports C11 threads then mingw64 would also

### Actual behavior

I get a fatal error: thread.h: No such file or directory message

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT_10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Peter0x44** [comment]
This is not a bug, I think mingw-w64 upstream simply isn't supporting this currently.

The closest you can currently get is mcfgthread and its c11.h, for now.

**Comment by MehdiChinoune** [comment]
Please file the bug to mingw-w64 project.

**Comment by striezel** [comment]
> Please file the bug to mingw-w64 project.

I just did that: https://github.com/mingw-w64/mingw-w64/issues/143
