### ISSUE TITLE
mingw-w64-mpv-git

### ISSUE THREAD

**Issue by shoober420** [msys2/MINGW-packages#21215]
### Package name

mingw-w64-mpv-git

### Brief description of package

Video player based on MPlayer/mplayer2 (mingw-w64)

### URL for package's homepage

https://mpv.io/

### Provide a basic test case to validate the package's functionality.

I've actually created a PKGBUILD for mingw-w64-mpv-git package.

https://github.com/shoober420/windows-configs/blob/main/C:/msys2/home/shoober420/mingw-w64-mpv-git/PKGBUILD

Please consider adding to the mingw package repo.

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes

**Comment by MehdiChinoune** [comment]
mingw-w64-mpv is already available.
