### ISSUE TITLE
Add nativefiledialog-extended

### ISSUE THREAD

**Issue by ikspress** [msys2/MINGW-packages#21245]
### Package name

nativefiledialog-extended

### Brief description of package

Cross platform native file dialog for C/C++/ObjC

### URL for package's homepage

https://github.com/btzy/nativefiledialog-extended

### Provide a basic test case to validate the package's functionality.

![屏幕截图 2024-06-25 142451](https://github.com/msys2/MINGW-packages/assets/91833768/7558d8a5-c78b-4646-a559-621deefba70e)

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

YES!!!

**Comment by ikspress** [comment]
I don't know `nativefiledialog-extended` is appropriate, it's too long. Maybe `nfd-extended` is better?

**Comment by Biswa96** [comment]
That's just a small C library and not widely used.
