### ISSUE TITLE
[texlive-bin] rebuild

### ISSUE THREAD

**Issue by podsvirov** [msys2/MINGW-packages#21263]
### Package name

texlive-bin

### New version number

same

### Other information that may be useful

For example:

```
$ ldd $(which xelatex) | grep 'not found' | grep -v api-ms-win-crt
        libicuuc74.dll => not found
```

but we have `icu 75.1` currently.

```
$ pacman -Qo $(which xelatex).exe
/ucrt64/bin/xelatex.exe is owned by mingw-w64-ucrt-x86_64-texlive-bin 2023.20230523-6
```

### Are you willing to submit a PR?

no

**Comment by MehdiChinoune** [comment]
It couldn't be rebuilt because of #19981
