### ISSUE TITLE
undefined reference to `WinMain'

### ISSUE THREAD

**Issue by phamconghao** [msys2/MINGW-packages#21261]
### Description / Steps to reproduce the issue

I run 'make' command then the error show "mingw-w64/mingw-w64-crt/crt/crtexewin.c:67:(.text.startup+0xbd): undefined reference to `WinMain'"
Could you help me how to fix this error?
Thanks!!!

### Expected behavior

![image](https://github.com/msys2/MINGW-packages/assets/38640029/b714eaf1-8328-47c6-abf9-c1b942d1047e)

### Actual behavior

After linking 100%, this issue appeared

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 10

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Use `-mwindows` compiler option.
