### ISSUE TITLE
Add libspelling

### ISSUE THREAD

**Issue by g-willems** [msys2/MINGW-packages#21294]
### Package name

libspelling

### Brief description of package

A GNOME library for spellchecking

This is the official gtk4 successor of `gtkspell` (gtk+2) and `gspell` (gtk+3).

### URL for package's homepage

https://gitlab.gnome.org/GNOME/libspelling

### Provide a basic test case to validate the package's functionality.

Simple Python script, please additionally install "hunspell-en".

```python
#!/usr/bin/env python3

import sys
import gi
gi.require_version('Gtk', '4.0')
gi.require_version('GtkSource', '5')
gi.require_version('Spelling', '1')
from gi.repository import GLib, Gtk, GtkSource, Spelling

TXT = "\nThis text contains somme speling errorz!\n"

class MyApp(Gtk.Application):
    def __init__(self):
        Gtk.Application.__init__(self)
        self.connect('activate', self.on_activate)
    def on_activate(self, app):
        self.add_window(MyAppWindow())

class MyAppWindow(Gtk.ApplicationWindow):
    def __init__(self):
        Gtk.ApplicationWindow.__init__(self, default_width=800, default_height=600)
        view = GtkSource.View()
        buffer = view.get_buffer()
        buffer.set_text(TXT)
        checker = Spelling.Checker.get_default()
        checker.set_language("en_US")
        adapter = Spelling.TextBufferAdapter.new(buffer, checker)
        menu = adapter.get_menu_model()
        view.get_extra_menu().append_section(None, menu)
        view.insert_action_group('spelling', adapter)
        adapter.set_enabled(True)
        self.set_child(view)
        self.present()

if __name__ == '__main__':
    GtkSource.init()
    Spelling.init()
    sys.exit(MyApp().run(sys.argv))
```

### MINGW environments where you need the package

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No, but I'll attach a PKGBUILD

**Comment by g-willems** [comment]
[PKGBUILD.txt](https://github.com/user-attachments/files/16070942/PKGBUILD.txt)

This PKGBUILD works fine on my side (ucrt64, Windows10)

**Comment by Biswa96** [comment]
> This PKGBUILD works fine on my side (ucrt64, Windows10)

Could you create a pull request with that PKGBUILD file? It looks fine to me (just remove the 32 bit ones in mingw_arch).
