### ISSUE TITLE
clang++ linking errors

### ISSUE THREAD

**Issue by fspeech** [msys2/MINGW-packages#213]
When using the clang compiler I get the "multiple definition" errors like the following:

```
C:\alt\msys32\mingw32\bin/../lib\libclangFrontend.a(FrontendAction.o):(.text$_ZN5clang14FrontendAction15BeginInvocationERNS_16CompilerInstanceE[__ZN5clang14FrontendAction15BeginInvocationERNS_16CompilerInstanceE]+0x0): multiple definition of `clang::FrontendAction::BeginInvocation(clang::CompilerInstance&)'
CMakeFiles/codebrowser_generator.dir/objects.a(main.cpp.obj):C:/alt/msys32/mingw32/include\clang/Frontend/FrontendAction.h:73: first defined here
```

**Comment by rpavlik** [comment]
FWIW, this still appears to be the case - clang can't link apps built against jsoncpp or the static library versions of Boost, in both cases the MinGW-w64 packages as included with MSYS-2. I would have expected the ABI compatibility issues re: C++11 to go away post GCC 5.0.

**Comment by rpavlik** [comment]
I do have a fairly compact test case here - grabbed the nearest, smallest app that used jsoncpp (pulled  out the small boost dependency and left it functional), wrote a tiny shell script to naively compile and link it with either clang or gcc, and stuck it in a gist along with logs, in case it's something that someone with more experience looking at toolchain configs could make use of. https://gist.github.com/rpavlik/41f94169ee869dec2eac4ff753dcbd94
