### ISSUE TITLE
maelstrom build fail

### ISSUE THREAD

**Issue by shoober420** [msys2/MINGW-packages#21306]
### Description / Steps to reproduce the issue

1. maelstrom-git PKGBUILD (https://github.com/shoober420/windows-configs/blob/main/C%3A/msys2/home/shoober420/maelstrom-git/PKGBUILD)
2. makepkg inside PKGBUILD directory

### Expected behavior

Build Completion

### Actual behavior

Build error:

-march=native -msahf -O3 -pipe -fno-plt -fno-common -fipa-pta -falign-functions=32 -fdevirtualize-at-ltrans -fuse-linker-plugin -floop-nest-optimize -fgraphite-identity -fexcess-precision=fast -flto=auto -march=native -msahf -O3 -pipe -fno-plt -fno-common -fipa-pta -falign-functions=32 -fdevirtualize-at-ltrans -fuse-linker-plugin -floop-nest-optimize -fgraphite-identity -fexcess-precision=fast -flto=auto -IC:/msys64/mingw64/include/SDL2 -Dmain=SDL_main -I.. -I../netlogic -I../screenlib -I../maclib -DLIBDIR="." -o snd2wav.exe snd2wav.o libSDLmac.a -lmingw32 -mwindows -lSDL2main -lSDL2 -lSDL2_net
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../lib/libSDL2main.a(SDL_windows_main.c.obj):(.text+0x17a): undefined reference to `SDL_main'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:385: snd2wav.exe] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/RavenWolf_-/maelstrom-git/src/Maelstrom/maclib'
make: *** [Makefile:561: all-recursive] Error 1
==> ERROR: A failure occurred in build().
Aborting...

Full Build Log:
[log.txt](https://github.com/user-attachments/files/16078885/log.txt)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-26244

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes

**Comment by oltolm** [comment]
This is not our bug. The project needs to be ported to mingw-w64.
