### ISSUE TITLE
Add eza

### ISSUE THREAD

**Issue by hour-keeper** [msys2/MINGW-packages#21302]
### Package name

eza

### Brief description of package

A modern, maintained replacement for ls

### URL for package's homepage

https://eza.rocks/

### Provide a basic test case to validate the package's functionality.

eza -alF --icons

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [ ] CLANGARM64

**Comment by ognevny** [comment]
I've opened https://github.com/msys2/MINGW-packages/pull/21305 with this package. please, can you download it from artifacts and test it?

**Comment by ognevny** [comment]
Q. do you need it for 32-bit envs? we're currently slowly removing them

**Comment by hour-keeper** [comment]
> Q. do you need it for 32-bit envs? we're currently slowly removing them (you've marked MINGW32 and CLANG32)问：32 位环境需要它吗？我们目前正在慢慢删除它们（您已标记 MINGW32 和 CLANG32）

Think you, i marked 32-bit envs as a habitual operator, I only use ucrt64 myself.


> I've opened #21305 with this package. please, can you download it from artifacts and test it?我已经用这个包打开了 #21305 。请问您可以从artifacts下载并测试吗？

Of course.

**Comment by hour-keeper** [comment]
> I've opened #21305 with this package. please, can you download it from artifacts and test it?

It's running very well.
