### ISSUE TITLE
volk: volk_modtool.py has build machine shebang that prevents it from running

### ISSUE THREAD

**Issue by chrisjohgorman** [msys2/MINGW-packages#21331]
### Description / Steps to reproduce the issue

edit ${MINGW_PREFIX}/bin/volk_modtool.py and look at it's shebang line

On mine I get the build machine shibang followed by #!/usr/bin/env/python3
```
#!D:\a\msys64\mingw64\bin\python
#!/usr/bin/env python3
```
This prevents the file from being run until the build machine shebang is removed.

### Expected behavior

I expected the program to run.

### Actual behavior

```
$ volk_modtool.py
-bash: /mingw64/bin/volk_modtool.py: cannot execute: required file not found
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes, but I need to fix my gnuradio bugs first :)

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/msys2/MINGW-packages/actions/runs/9829373649

**Comment by chrisjohgorman** [comment]
Hi Biswapriyo,

Sorry to say, I can't seem to get this to run properly and I'm not 100% certain on how to use it.  I don't think this is a very regularly used script.  With your changes, when I run it, I get an error due to a circular dependency.
```
$ volk_modtool.py -i
Traceback (most recent call last):
  File "C:/msys64/mingw64/bin/volk_modtool.py", line 12, in <module>
    from volk_modtool import volk_modtool, volk_modtool_config
  File "C:/msys64/mingw64/bin/volk_modtool.py", line 12, in <module>
    from volk_modtool import volk_modtool, volk_modtool_config
ImportError: cannot import name 'volk_modtool' from partially initialized module 'volk_modtool' (most likely due to a circular import) (C:/msys64/mingw64/bin/volk_modtool.py)
```
This is more than I got before with the incorrect build directory.  Under linux, when I run `volk_modtool -i` the script runs and a dialog is started. 
```
$ volk_modtool -i
/usr/bin/volk_modtool:53: SyntaxWarning: invalid escape sequence '\/'
  print("   /------\/     ")
/usr/bin/volk_modtool:55: SyntaxWarning: invalid escape sequence '\-'
  print(" *  /\---/\      ")
Initializing config file...
name: test
destination: new
base: volk
Traceback (most recent call last):
  File "/usr/bin/volk_modtool", line 65, in <module>
    my_modtool.make_module_skeleton();
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/volk_modtool/volk_modtool_generate.py", line 96, in make_module_skeleton
    instring = open(infile, 'r').read()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```
So I think your change is an improvement, but it doesn't run still.  Sorry for the make work project.

**Comment by Biswa96** [comment]
Could you please try with this latest one https://github.com/msys2/MINGW-packages/actions/runs/9833272722 ? I ran the command `volk_modtool -i` and got `ValueError: Verification function returns False... key:destination`. If you get similar error it has to be reported to upstream.

**Comment by chrisjohgorman** [comment]
I just ran a test and it works.  (As well as it does in linux.)  I will still make a bug report for volk upstream on this.

Running under windows I get ...
```
$ volk_modtool -i
Initializing config file...
name: test
destination: new
base: volk
Traceback (most recent call last):
  File "C:/msys64/mingw64/bin/volk_modtool", line 64, in <module>
    my_modtool.make_module_skeleton();
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/mingw64/lib/python3.11/site-packages/volk_modtool/volk_modtool_generate.py", line 96, in make_module_skeleton
    instring = open(infile, 'r').read()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/mingw64/lib/python3.11/encodings/cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 38: character maps to <undefined>
```
and under linux I get ...
```

$ volk_modtool -i
/usr/bin/volk_modtool:53: SyntaxWarning: invalid escape sequence '\/'
  print("   /------\/     ")
/usr/bin/volk_modtool:55: SyntaxWarning: invalid escape sequence '\-'
  print(" *  /\---/\      ")
Initializing config file...
name: test
destination: new
base: volk
Traceback (most recent call last):
  File "/usr/bin/volk_modtool", line 65, in <module>
    my_modtool.make_module_skeleton();
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/volk_modtool/volk_modtool_generate.py", line 96, in make_module_skeleton
    instring = open(infile, 'r').read()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```
The modtool does generate some files and directories for me, so I **guess** it's working.  Thanks for the fix.

**Comment by Biswa96** [comment]
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

That can be fixed by adding `encoding="UTF-8"` in `open()` function as shown in log.
