### ISSUE TITLE
Using -flto=auto build flag causes Basilisk II ./configure to fail

### ISSUE THREAD

**Issue by shoober420** [msys2/MINGW-packages#21366]
Following the instructions on https://www.emaculation.com/doku.php/compiling_sheepshaver_basilisk, when running ./configure --with-bincue for Basilisk II on MSYS2 using Windows 11, I get this error.

checking floating point format... configure: error: Unknown floating point format

I found the cause to be using the -flto=auto build flag.

Full build log:
[buildlog.txt](https://github.com/user-attachments/files/16142783/buildlog.txt)

SheepShaver compiles fine using -flto=auto. This error does not occur on vanilla Arch Linux machine.

https://github.com/kanjitalk755/macemu/issues/200

**Comment by MehdiChinoune** [comment]
Fixed upstream by https://github.com/kanjitalk755/macemu/commit/b63490da
