### ISSUE TITLE
installing Lua package can't be found using CMake (3.30) find_package(Lua)

### ISSUE THREAD

**Issue by Raffaello** [msys2/MINGW-packages#21391]
### Description / Steps to reproduce the issue

install GCC through Pacman and CMake through winget (i supposed it would be the same installing it through pacman)

create a simple CMake project 

```Cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.28)
Project(lua_test)
find_package(Lua 5.4 REQUIRED)
```

then run from CLI: `cmake .`

the output will be:
```
CMake Error at C:[..]/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR) (Required is at
  least version "5.4")
Call Stack (most recent call first):
  C:[..]/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
  C:[...]/cmake-3.30/Modules/FindLua.cmake:237 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:3 (find_package)
```

when the same kind of thing works ok on Linux

### Expected behavior

It should find Lua

### Actual behavior

CMake crash while running `find_pacakge` macro

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

windows 11

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

well i could, need some mentoring though...

**Comment by ognevny** [comment]
> (i supposed it would be the same installing it through pacman)

what about a cmake from pacman?

**Comment by Raffaello** [comment]
> > (i supposed it would be the same installing it through pacman)
> 
> what about a cmake from pacman? that looks like an issue with winget's cmake

Well just install cmake through pacman, i have issues with GCC as CMake can't find GCC (ucrt64), i guess it might work if i will configure through msys.

----

Besides i have solved this issue passing `LUA_DIR` to cmake:
```
cmake -D LUA_DIR="C:/msys64/ucrt64" .
```

the error message was a little bit misleading.

**Comment by Raffaello** [comment]
i am closing the the issue as eventually is cmake related.
