### ISSUE TITLE
fs-uae-launcher fails to compile

### ISSUE THREAD

**Issue by shoober420** [msys2/MINGW-packages#21417]
### Description / Steps to reproduce the issue

- git clone --recursive https://github.com/FrodeSolheim/fs-uae-launcher.git
- cd fs-uae-launcher
- ./bootstrap
- make

### Expected behavior

Successful compilation

### Actual behavior

# make
make -C src
make[1]: Entering directory '/home/RavenWolf_-/fs-uae-launcher/src'
make -C icons
make[2]: Entering directory '/home/RavenWolf_-/fs-uae-launcher/src/icons'
mkdir -p ../../data/Icons
./normal.sh ../../data/Icons/AmigaForever.png tango/64/drive-harddisk-4.svg tango/64/../../amigaforever/volumeoverlays/AmigaForever.png
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:/msys64/home/RavenWolf_-/fs-uae-launcher/launcher/extra/glowicon.py", line 9, in <module>
    from fsui.qt.qt import QImage, QPainter, QSvgRenderer
  File "C:/msys64/home/RavenWolf_-/fs-uae-launcher/fsui/__init__.py", line 3, in <module>
    from fsui.common.group import Group
  File "C:/msys64/home/RavenWolf_-/fs-uae-launcher/fsui/common/group.py", line 6, in <module>
    from fsui.qt import QObject
  File "C:/msys64/home/RavenWolf_-/fs-uae-launcher/fsui/qt/__init__.py", line 6, in <module>
    from fsui.qt.qt import *
  File "C:/msys64/home/RavenWolf_-/fs-uae-launcher/fsui/qt/qt.py", line 14, in <module>
    from fsui.qt.pyqt5 import *
  File "C:/msys64/home/RavenWolf_-/fs-uae-launcher/fsui/qt/pyqt5.py", line 39, in <module>
    from PyQt5.QtSvg import QSvgRenderer
ImportError: DLL load failed while importing QtSvg: The specified module could not be found.
make[2]: *** [Makefile:5: ../../data/Icons/AmigaForever.png] Error 1
make[2]: Leaving directory '/home/RavenWolf_-/fs-uae-launcher/src/icons'
make[1]: *** [Makefile:2: all] Error 2
make[1]: Leaving directory '/home/RavenWolf_-/fs-uae-launcher/src'
make: *** [Makefile:4: build] Error 2

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-26252

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes

**Comment by MehdiChinoune** [comment]
Shouldn't you report it to the upstream project?
You should Install pyqt5 package `mingw-w64-x86_64-pyqt5`.

**Comment by shoober420** [comment]
I do have the `mingw-w64-x86_64-python-pyqt5 mingw-w64-x86_64-python-pyqt6` packages installed, and also did make a post about it on the fs-uae GitHub issue page.

https://github.com/FrodeSolheim/fs-uae-launcher/issues/158

**Comment by shoober420** [comment]
I got a bit farther during compile by installing the `python-typing_extensions mingw-w64-x86_64-python-typing_extensions mingw-w64-i686-python-typing_extensions` packges. I'll report back with more info when I foudn out whats going on.

I also installed python-rx for Windows just in case in Windows Powershell.
`pip3 install rx`
