### ISSUE TITLE
[tinyxml] cmake can not find tinyxml

### ISSUE THREAD

**Issue by yanzixiang** [msys2/MINGW-packages#21425]
### Description / Steps to reproduce the issue

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find TinyXML (missing: TinyXML_LIBRARY TinyXML_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindTinyXML.cmake:65 (find_package_handle_standard_args)
  CMakeLists.txt:9 (find_package)

### Expected behavior

cmake can find and use it.

### Actual behavior

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find TinyXML (missing: TinyXML_LIBRARY TinyXML_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindTinyXML.cmake:65 (find_package_handle_standard_args)
  CMakeLists.txt:9 (find_package)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

NO

**Comment by MehdiChinoune** [comment]
That's an external module `FindTinyXML.cmake`, so nothing to do with CMake package.
