### ISSUE TITLE
qt5-static package is broken since 5.15.14-1

### ISSUE THREAD

**Issue by OBattler** [msys2/MINGW-packages#21447]
### Description / Steps to reproduce the issue

Try to build any cmake-using project which uses it.

### Expected behavior

cmake finds qt5-static and all its dependencies successfully.

### Actual behavior

It crashes when looking for libz with this:
```
CMake Error at C:/msys64/mingw32/qt5-static/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:91 (message):
  Library not found: :libz
Call Stack (most recent call first):
  C:/msys64/mingw32/qt5-static/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:272 (_qt5_Core_process_prl_file)
  C:/msys64/mingw32/qt5-static/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  src/qt/CMakeLists.txt:44 (find_package)


-- Configuring incomplete, errors occurred!
[!] CMake failed with status [1]
[Pipeline] writeFile
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // dir
[Pipeline] catchError
[Pipeline] {
[Pipeline] }
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 27f24933-88ed-4e28-951d-97c00e10e173
java.lang.ArithmeticException: Division by zero
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes.

**Comment by lazka** [comment]
@raedrizqie got any ideas?

**Comment by raedrizqie** [comment]
ah.. faulty sed command.. will look into it later

**Comment by raedrizqie** [comment]
GHA seems to be down atm.. maybe you can try this quick fix:
```
sed -e 's|-l\:libz|-l\:libz.a|g'  -e 's|-l\:libzstd|-l\:libzstd.a|g' -i ${MINGW_PREFIX}/qt5-static/lib/Qt5*.prl
```

**Comment by lemondrops** [comment]
Doesn't work for me:
```
CMake Error at C:/msys64/mingw64/qt5-static/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:91 (message):
  Library not found: :libz.a
Call Stack (most recent call first):
  C:/msys64/mingw64/qt5-static/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:272 (_qt5_Core_process_prl_file)
  C:/msys64/mingw64/qt5-static/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  src/frontend/qt_sdl/CMakeLists.txt:73 (find_package)


-- Configuring incomplete, errors occurred!
```

Only replacing with `-lz` and `-lzstd` works.

**Comment by raedrizqie** [comment]
@lemondrops please see the updated post

**Comment by lemondrops** [comment]
Nope, still the same error. I suspect CMake doesn't like the colon after the `-l`, because if I modify the first command to be like this:
```
sed -e 's|-l\:libz\;|-llibz.a\;|g'  -e 's|-l\:libzstd\;|-llibzstd.a\;|g' -i ${MINGW_PREFIX}/qt5-static/lib/*.prl`
```
it succeeds.
