### ISSUE TITLE
Conflict when installing Zed through "pacman" ; unable to install in Windows 10

### ISSUE THREAD

**Issue by DarwinsCorn** [msys2/MINGW-packages#21458]
### Description / Steps to reproduce the issue

Updated "pacman" manager to version 6.1.0, then in the UCRT64 shell I typed: 

`pacman -S mingw-w64-ucrt-x86_64-zed`

### Expected behavior

It was excpected to install Zed through MSYS2 since it couldn't compile through Rust due to some trait not being implemented in sdtin.

### Actual behavior

I got the following error:

```
$ pacman -S mingw-w64-ucrt-x86_64-zed
resolving dependencies...
looking for conflicting packages...
:: mingw-w64-ucrt-x86_64-gettext-runtime-0.22.5-2 and mingw-w64-ucrt-x86_64-gettext-0.21.1-1 are in conflict. Remove mingw-w64-ucrt-x86_64-gettext? [Y/n] y
error: failed to prepare transaction (could not satisfy dependencies)
:: removing mingw-w64-ucrt-x86_64-gettext breaks dependency 'mingw-w64-ucrt-x86_64-gettext' required by mingw-w64-ucrt-x86_64-libtre-git
:: removing mingw-w64-ucrt-x86_64-gettext breaks dependency 'mingw-w64-ucrt-x86_64-gettext' required by mingw-w64-ucrt-x86_64-make
:: removing mingw-w64-ucrt-x86_64-gettext breaks dependency 'mingw-w64-ucrt-x86_64-gettext' required by mingw-w64-ucrt-x86_64-xz

```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by ognevny** [comment]
there was a split for gettext packages. IIRC you should run `pacman -Suy` until there is no updates
