### ISSUE TITLE
Question: Convention or procedure for obtaining package sources

### ISSUE THREAD

**Issue by jcaselman-keysight** [msys2/MINGW-packages#21450]
Are source packages available for mingw packages, containing the source that was used to build the binaries?  Redistributing many of the binaries would require to include or make available the source for them so I'm wondering what sort of existing infrastructure or processes may be in place to support doing so.

**Comment by MehdiChinoune** [comment]
Yes, They are available.
Just enable `mingw-src` from `/etc/pacman.conf`

**Comment by jcaselman-keysight** [comment]
Sorry @MehdiChinoune I'm not following 😬 Could you provide more detail?

My `/etc/pacman.conf` looks like this:

```#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
HoldPkg     = pacman
#XferCommand = /usr/bin/curl -L -C - -f -o %o %u
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
Architecture = auto

# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options
#UseSyslog
Color
#NoProgressBar
CheckSpace
#VerbosePkgLists
ParallelDownloads = 5

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
#SigLevel = Never
SigLevel    = Required
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

#
# REPOSITORIES
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#
# Repository entries are of the format:
#       [repo-name]
#       Server = ServerName
#       Include = IncludePath
#
# The header [repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#

# The testing repositories are disabled by default. To enable, uncomment the
# repo name header and Include lines. You can add preferred servers immediately
# after the header, and they will be used before the default mirrors.

# Staging packages: enable at your own risk
# [staging]
# Server = https://repo.msys2.org/staging/
# SigLevel = Never

[clangarm64]
Include = /etc/pacman.d/mirrorlist.mingw

[mingw32]
Include = /etc/pacman.d/mirrorlist.mingw

[mingw64]
Include = /etc/pacman.d/mirrorlist.mingw

[ucrt64]
Include = /etc/pacman.d/mirrorlist.mingw

[clang32]
Include = /etc/pacman.d/mirrorlist.mingw

[clang64]
Include = /etc/pacman.d/mirrorlist.mingw

[msys]
Include = /etc/pacman.d/mirrorlist.msys

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs
```

I tried separately adding
```
[sources] # just a guess based on https://repo.msys2.org/mingw/sources/
Include = /etc/pacman.d/mirrorlist.mingw
```
and
```
[mingw-src]
Include = /etc/pacman.d/mirrorlist.mingw
```
both result in 404 errors `X failed to download` when I subsequently run `pacman -Sy`

**Comment by MehdiChinoune** [comment]
Looks like an issue.
@lazka I think source packages should have their own repo. I mean add necessary DBs

**Comment by lazka** [comment]
I'm not aware of pacman supporting some kind of source packages.

**Comment by jcaselman-keysight** [comment]
Thanks @lazka, in that case it shouldn't be too much trouble to script something to download them.

Is it correct to assume that packages without the `mingw` prefix come from the `msys` sources and those with the `mingw` prefix come from the `mingw` sources?

```
vagrant@DESKTOP-N1PH04A MINGW64 ~/code
# pacman -Q
...
libunistring 1.2-1
libutil-linux 2.35.2-4
libxcrypt 4.4.36-1
libyaml 0.2.5-2
libzstd 1.5.6-1
m4 1.4.19-2
make 4.4.1-2
mingw-w64-ucrt-x86_64-SDL2 2.30.3-1
mingw-w64-ucrt-x86_64-abseil-cpp 20240116.1-1
mingw-w64-ucrt-x86_64-aom 3.9.0-2
mingw-w64-ucrt-x86_64-asciidoc 10.2.0-3
mingw-w64-ucrt-x86_64-binutils 2.42-2
...
```

**Comment by MehdiChinoune** [comment]
I think the question is answered.

**Comment by MehdiChinoune** [comment]
Even without offering source-packages PKGBUILD already contain the scripts used to build package including the source-url. So if someone wants to obtain the source code he should just download the source from the url in PKGBUILD.

**Comment by mmuetzel** [comment]
> if someone wants to obtain the source code he should just download the source from the url in PKGBUILD.

That is an option for users interested in the source code. But afaiu, it wouldn't be enough to comply with some licenses (e.g., the GPL). Especially, for packages for which we apply patches.
The source repositories should be covering the licensing aspects probably.
(I'm not lawyer though.)

**Comment by MehdiChinoune** [comment]
> That is an option for users interested in the source code. But afaiu, it wouldn't be enough to comply with some licenses (e.g., the GPL). Especially, for packages for which we apply patches.

I meant all files in 'sources()' which includes the patches.

**Comment by rimrul** [comment]
> I was playing with this a bit and noticed that in some cases the source package needed has a different name than the package owning a given library, for example
> 
> ```
> /mingw64/bin/libwinpthread-1.dll is owned by mingw-w64-x86_64-libwinpthread-git 11.0.0.r731.g8fdf7c9b5-1
> ```
> 
> but is published from the [winpthreads-git PKGBUILD](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-winpthreads-git/PKGBUILD#L7) and so uses the winpthreads-git source package
> 
> I there an automated way to determine when a source package for a given package is available under a different package like this or will it be trial and error to sort out?

The [packages page for a package](https://packages.msys2.org/package/mingw-w64-x86_64-libwinpthread-git) will list the "base package".

**Comment by lazka** [comment]
There is now a link to the tarball on packages.msys2.org: https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-libwinpthread-git (under "Source-Only Tarball" which is what makepkg calls it)
