### ISSUE TITLE
Include [bash-completion] for [bat] packages

### ISSUE THREAD

**Issue by Mark-Joy** [msys2/MINGW-packages#21462]
### Package name

mingw-w64-x86_64-bat

### New version number

0.24.0

### Other information that may be useful

`bash-completion` is available for `bat` since [0.18.2](https://github.com/sharkdp/bat/releases/tag/v0.18.2) but is not included in `mingw-w64-x86_64-bat`. I'm not sure about other `bat` packages from MSYS2 such as `mingw-w64-ucrt-x86_64-bat` `mingw-w64-clang-x86_64-bat`. Better check it out.
Please include `bash-completion` for `bat` packages

**Comment by ognevny** [comment]
I've opened #21463 which adds bash completions for bat. can you download an artifact from GHA and test it, please?

**Comment by Mark-Joy** [comment]
> can you download an artifact from GHA and test it, please?

I'm not sure what to do, since I don't familiar with GHA (suppose it means Github action). Can you give me a bit more info?

**Comment by ognevny** [comment]
yes, GHA is GitHub Actions. to get artifact, you need to go to "Checks" tab in PR, then found an "artifacts" list. here is a direct link to an artifact for MINGW64: https://github.com/msys2/MINGW-packages/suites/26261364242/artifacts/1724501624

**Comment by Mark-Joy** [comment]
> yes, GHA is GitHub Actions. to get artifact, you need to go to "Checks" tab in PR, then found an "artifacts" list. here is a direct link to an artifact for MINGW64: https://github.com/msys2/MINGW-packages/suites/26261364242/artifacts/1724501624

Yes, Thank you very much!
I can confirm that `bash-completion` is now work for `bat`
