### ISSUE TITLE
[qt5-base] deploying 32bit Qt applications is broken with 2-any update

### ISSUE THREAD

**Issue by vadi2** [msys2/MINGW-packages#21477]
### Description / Steps to reproduce the issue

Build a 32bit Qt application ([examples](https://doc.qt.io/qt-6/qtexamplesandtutorials.html)) and deploy it with [windeployqt](https://doc.qt.io/qt-6/windows-deployment.html). 

Between the mingw-w64-i686-qt5-base-5.15.14+kde+r141-1-any and the mingw-w64-i686-qt5-base-5.15.14+kde+r141-**2**-any package versions, the following files will be missing in deployment:

```
audio\qtaudio_windows.dll
bearer\qgenericbearer.dll
iconengines\qsvgicon.dll
imageformats\qgif.dll
imageformats\qicns.dll
imageformats\qico.dll
imageformats\qjp2.dll
imageformats\qjpeg.dll
imageformats\qsvg.dll
imageformats\qtga.dll
imageformats\qtiff.dll
imageformats\qwbmp.dll
imageformats\qwebp.dll
mediaservice\dsengine.dll
mediaservice\qtmedia_audioengine.dll
mediaservice\wmfengine.dll
platforms\qwindows.dll
playlistformats\qtmultimedia_m3u.dll
styles\qwindowsvistastyle.dll
texttospeech\qtexttospeech_sapi.dll
```

Notably, `platforms\qwindows.dll` missing is crucial and breaks application deployment on Windows.

### Expected behavior

The files in the 2-any update are present just as they were available in the 1-any update.

### Actual behavior

The essential libraries are missing.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 10 Pro 2009      22631        6.3

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by vadi2** [comment]
If it is interesting, here are the build logs using [1-any](https://github.com/Mudlet/Mudlet/actions/runs/9984544507/job/27593937192) and [2-any](https://github.com/Mudlet/Mudlet/actions/runs/10001600092/job/27645504748) building the exact same application code.

**Comment by MehdiChinoune** [comment]
Should be fixed by https://github.com/msys2/MINGW-packages/commit/40900bd87

**Comment by vadi2** [comment]
Thanks, confirmed fixed.
