### ISSUE TITLE
[nodejs] Windows version check fails

### ISSUE THREAD

**Issue by TerrorJack** [msys2/MINGW-packages#21481]
### Description / Steps to reproduce the issue

```
$ which node
/clang64/bin/node
$ node --version
Node.js is only supported on Windows 8.1, Windows Server 2012 R2, or higher.
Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this
check, but Node.js might not execute correctly. Any issues encountered on
unsupported platforms will not be fixed.
```

The above occurs on a Windows 11 23H2 (22631.3880) x86_64 machine.

### Expected behavior

`node` should work out of the box.

### Actual behavior

`node` fails version check.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by lazka** [comment]
confirmed.

@raedrizqie looks like we dropped https://github.com/msys2/MINGW-packages/pull/17411 maybe?

**Comment by Biswa96** [comment]
It feels like one of those missing manifest file issues where gcc links those implicitly.

**Comment by raedrizqie** [comment]
@TerrorJack which version are you using? the current nodejs already have embedded manifest file in the exe..

**Comment by ognevny** [comment]
I got that issue in latest Windows 11 (not from windows insider)

**Comment by raedrizqie** [comment]
this error should also affect upstream binaries.. but i cannot find any similar issue reported

**Comment by lazka** [comment]
I can confirm that the manifest is missing

**Comment by raedrizqie** [comment]
ok, i will look into it soonish
