### ISSUE TITLE
Bitdefender Trojan flag on ahost.exe

### ISSUE THREAD

**Issue by holyman2k** [msys2/MINGW-packages#21498]
### Description / Steps to reproduce the issue

Hi this morning Bitdefender flag a virus: Trojan.Agent.GLTG on my windows 11 laptop in /Program File/git/mingw64/ahost.exe.  I created a Fresh Virtual Machine and installed Git the same file got flagged again.

Is this a false positve, has anyone notice the same issue?

### Expected behavior

ahost.exe not trigger virus detection

### Actual behavior

/Program File/git/mingw64/ahost.exe flaged for Trojan.Agent.GLTG

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.22631.3880]

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

don't know how

**Comment by Biswa96** [comment]
Please report the issue to BitDefender.
