### ISSUE TITLE
[libtool] update to 2.5.1

### ISSUE THREAD

**Issue by ikspress** [msys2/MINGW-packages#21508]
### Package name

mingw-w64-libtool

### New version number

2.5.1

### Other information that may be useful

It is already avaliable in Arch Linux [core-testing](https://archlinux.org/packages/core-testing/x86_64/libtool/) repository. Furthermore, the [core](https://archlinux.org/packages/core/x86_64/libtool/) repository is also newer than MSYS2. I am attempting to build GCC mltilib toolchain for myself. The changes for multilib support are necessary for me.

### Are you willing to submit a PR?

Yes, if I could.

**Comment by MehdiChinoune** [comment]
Is there a new feature or a fixed bug you want from that release?

**Comment by ikspress** [comment]
> Is there a new feature or a fixed bug you want from that release?

Yes, I need the changes which already included in 2.5.1.
autotools-mirror/libtool@ab89ebbcc2ff0ecff5157982ef03627cfd615f7e changes the `libdir` when configured with `--enable-multilib`.

**Comment by ikspress** [comment]
> Is there a new feature or a fixed bug you want from that release?

Yes, I need the changes which already included in 2.5.1.
autotools-mirror/libtool@ab89ebbcc2ff0ecff5157982ef03627cfd615f7e changes the `libdir` when configured with `--enable-multilib`.

**Comment by MehdiChinoune** [comment]
https://www.gnu.org/software/libtool/ shows that the latest stable version is 2.4.7.
I don't know if It's OK to package an unstable version!

**Comment by ikspress** [comment]
> https://www.gnu.org/software/libtool/ shows that the latest stable version is 2.4.7. I don't know if It's OK to package an unstable version!

Yes, it is a unstable version. Arch Linux also uses an [unstable git version](https://archlinux.org/packages/core/x86_64/libtool/) in core repository. libtool 2.5.1 is testing in their repository, so I think it is useful to use 2.5.1.

**Comment by lazka** [comment]
gnu developers complained that arch packaged the alpha version, but this is a beta and there hasn't been a release in a long time, so maybe...

**Comment by ikspress** [comment]
I'm attempting to compile libtool manually, but some error occured.
`bootstrap` script was failed to clone `gnulib-bootstrap` repository.
```
$ ./bootstrap
bootstrap: running: git clone 'https://git.savannah.gnu.org/git/gnulib' 'gnulib'
Cloning into 'gnulib'...
remote: Counting objects: 305659, done.
remote: Compressing objects: 100% (39271/39271), done.
remote: Total 305659 (delta 270859), reused 300945 (delta 266277)
Receiving objects: 100% (305659/305659), 85.87 MiB | 17.02 MiB/s, done.
Resolving deltas: 100% (270859/270859), done.
Updating files: 100% (11727/11727), done.
bootstrap: running: git submodule init -- gnulib
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
bootstrap: running: git submodule update -- gnulib
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
bootstrap: running: git submodule init -- gl-mod/bootstrap
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
bootstrap: running: git submodule update -- gl-mod/bootstrap
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
bootstrap: running: gnulib/gnulib-tool --no-changelog --avoid=dummy --libtool --macro-prefix=GL --with-tests --tests-base=gnulib-tests --aux-dir=build-aux --m4-base=m4 --local-dir=gl --local-dir=gl-mod/bootstrap --symlink --import announce-gen bootstrap...
gnulib-tool: warning: python3 not found or too old, using the slow shell-based implementation
gnulib-tool: warning: module bootstrap doesn't exist
gnulib-tool: warning: module extract-trace doesn't exist
gnulib-tool: warning: module inline-source doesn't exist
gnulib-tool: warning: module options-parser doesn't exist
Module list with included dependencies (indented):
```
According to PKGBUILD script in Arch Linux, they changed these submodules to a local directory to solve the problem.
```
  git submodule init
  git config --local submodule.gnulib.url "${srcdir}"/gnulib
  git config --local submodule.gl-mod/bootstrap.url "${srcdir}"/gnulib-bootstrap
  git -c protocol.file.allow=always submodule update
```
I prefer to use the snapshot tarball file while these commands will fail. Should I following them to just clone the specific commit (or tag will better)?
