### ISSUE TITLE
msys2 installation fails with strange error regarding 7z CRC mismatch

### ISSUE THREAD

**Issue by Bytefyre** [msys2/MINGW-packages#21517]
### Description / Steps to reproduce the issue

I am running 64-bit Windows 11 and am getting the following error when trying to install msys2:

![image](https://github.com/user-attachments/assets/7a2d4166-f847-408d-83f1-562d878c1691)

It seems that this can occur on any component attempting to be installed, and I'm at a total loss to understand why this is happening.

### Expected behavior

A successful installation.

### Actual behavior

An unsuccessful installation.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 11 23H2 (22631.3880)

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Only antivirus or antimalware like programs may interface with the installation procedure.

**Comment by lazka** [comment]
Or a 13/14 gen intel CPU?

**Comment by Bytefyre** [comment]
> Or a 13/14 gen intel CPU? (https://old.reddit.com/r/hardware/comments/1edh7z1/raptor_lake_degradation_issue_rpldie_faq_10/)

From System Information:  Intel(R) Core(TM) i9-14900HX, 2200 Mhz, 24 Core(s), 32 Logical Processor(s)

I've had this laptop for less than six months, so I doubt the processor could've degraded so quickly in such a short amount of time.

**Comment by lazka** [comment]
It fits perfectly though :/

If you have 7-zip installed, you could try to see if the 7-zip benchmark runs OK

![image](https://github.com/user-attachments/assets/76dfee5f-48ab-451c-bcb5-114ba9026805)

**Comment by Bytefyre** [comment]
> It fits perfectly though :/
> 
> If you have 7-zip installed, you could try to see if the 7-zip benchmark runs OK
> 
> ![image](https://private-user-images.githubusercontent.com/991986/353310079-76dfee5f-48ab-451c-bcb5-114ba9026805.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDI3NDYsIm5iZiI6MTcyMjM0MjQ0NiwicGF0aCI6Ii85OTE5ODYvMzUzMzEwMDc5LTc2ZGZlZTVmLTQ4YWItNDUxYy1iY2I1LTExNGJhOTAyNjgwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxMjI3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjEzODhhNzM4ODQzOWUzNjY4Yzg0ZDhlMjhjOTU4MjEyOTQwYzJjNTFjM2MxYmNjNDZmNGNiYWI3MjI5NWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bM3x1iHG7-Cbo4LCaf6747qt1YMs_pltpmVaSHI6H0Q)

![image](https://github.com/user-attachments/assets/4bd955f6-93d3-4a4d-88e6-8f54b5e3dd9c)

There doesn't appear to be any issue here, no apparent failure.  Do the ratings indicate anything amiss?

**Comment by Biswa96** [comment]
The issue can not be reproduce in other systems and nothing can be done in msys2 installer to solve the issue.
