### ISSUE TITLE
[rust] update to 1.80.0

### ISSUE THREAD

**Issue by ognevny** [msys2/MINGW-packages#21528]
### Package name

rust

### New version number

1.80.0

### Other information that may be useful

it's required for a future version of Zed and new version of uv

**Comment by ognevny** [comment]
@filnet

**Comment by ArchGuyWu** [comment]
uv is broken for python from msys2.

**Comment by ognevny** [comment]
> uv is broken for python from msys2.

I know, I'm talking about build issue. it can't be updated either

**Comment by ArchGuyWu** [comment]
> > uv is broken for python from msys2.
> 
> I know, I'm talking about build issue. it can't be updated either

Ok, and I hope that real target *-pc-windows-gnullvm can be used for clang*.

**Comment by ognevny** [comment]
> > > uv is broken for python from msys2.
> > 
> > I know, I'm talking about build issue. it can't be updated either
> 
> Ok, and I hope that real target *-pc-windows-gnullvm can be used for clang*.

that would be @mati865 decision

**Comment by mati865** [comment]
> > > > uv is broken for python from msys2.
> > > 
> > > 
> > > I know, I'm talking about build issue. it can't be updated either
> > 
> > 
> > Ok, and I hope that real target _-pc-windows-gnullvm can be used for clang_.
> 
> that would be @mati865 decision

I think I've said it before. We should be ready to do the switch since few releases.
