### ISSUE TITLE
Add [mingw libmd]

### ISSUE THREAD

**Issue by hessenfarmer** [msys2/MINGW-packages#21545]
### Package name

llibmd

### Brief description of package

Message Digest functions from BSD systems

### URL for package's homepage

https://www.hadrons.org/software/libmd/

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/msys2/MINGW-packages/actions/runs/10431468661

**Comment by hessenfarmer** [comment]
thanks for the pull request. However it seems that the 32bit packages are not built anymore. if this is the official policy the issue template should be updted accordingly.

**Comment by Biswa96** [comment]
32 bit packages are being removed since last year. See the news here https://www.msys2.org/news/
