### ISSUE TITLE
[Zed] BÉPO keyboard - some dead keys are not functional.

### ISSUE THREAD

**Issue by raylemon** [msys2/MINGW-packages#21599]
### Description / Steps to reproduce the issue

I want to type some symbols, like _ or }.
With my BÉPO (french) keyboard, I must type ctrl+alt+space to write underscore (_) and ctrl+alt+y for }.
But nothing appears.

### Expected behavior

Typing ctrl-alt-space must be write _

### Actual behavior

Nothing appear

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by ognevny** [comment]
is this an actual issue for MINGW package?

**Comment by raylemon** [comment]
I have the same problem for MinGw and native compilation.

**Comment by ognevny** [comment]
do you face this issue in a program compiled for MINGW, or it's system-wide?

**Comment by raylemon** [comment]
Both. First I have installed zed with MSYS. While it’s functional, I can’t use some shortcuts starting by ctrl-alt, even when deactivate them in keymap.json.

Today I have compiled zed in native, with the same problem.

**Comment by ognevny** [comment]
> Both. First I have installed zed with MSYS. While it’s functional, I can’t use some shortcuts starting by ctrl-alt, even when deactivate them in keymap.json.
> 
> Today I have compiled zed in native, with the same problem.

Zed support only English keyboard layout. this is _intended_ behaviour. there is a lot issues about that: https://github.com/zed-industries/zed/issues?q=is%3Aissue+is%3Aopen+keyboard+layout
