### ISSUE TITLE
Latest pkgconf 2.3.0 package reporting under Microsoft systems as a virus

### ISSUE THREAD

**Issue by VK3SIR** [msys2/MINGW-packages#21603]
### Description / Steps to reproduce the issue

Navigate to https://packages.msys2.org/package/mingw-w64-x86_64-pkgconf

Download https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar.zst 

### Expected behavior

Download without issue.

### Actual behavior

MS Windows 11 Defender AV cutting in and quarantining mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar.zst 

detected: Trojan:Win32/Wacatac.B!ml

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

N.A. as downloading package file from Website

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes

**Comment by Biswa96** [comment]
Please report it as false positive. All the packages are compiled in GitHub Actions.
