### ISSUE TITLE
[qt5-static] broken library linking with qmake

### ISSUE THREAD

**Issue by edo9300** [msys2/MINGW-packages#21612]
### Description / Steps to reproduce the issue

Try to build a qmake project with the latest qt5-static package (e.g. `/mingw32/qt5-static/bin/qmake.exe -o Makefile project.pro`).
The project I'm building this way is https://github.com/ProjectIgnis/Datacorn

### Expected behavior

The generated makefile builds the application correctly (and it does with the package `qt5-static 5.15.13`).

### Actual behavior

After updating to the qt 5.15.14-2 package, generating a project with qmake will produce a makefile with the wrong libraries/paths to be linked.
The main issue is that it will add anything that is not a plugin as `-lQtModule` (for example `-lQt5Widgets`, while with the previous version the linked library was the proper one `C:/msys64/mingw32/qt5-static/lib/libQt5Widgets.a`).
Also among the libraries, `-llibzstd.a` and `-llibz.a` are attempted to be linked, instead of `-lz` and `-lzstd` (this might be related to https://github.com/msys2/MINGW-packages/issues/21447)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW32_NT-10.0-17763

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by raedrizqie** [comment]
could you try download from this artifacts, and test it..
https://github.com/raedrizqie/MINGW-packages/actions/runs/10056650588

it supposed to fix libz and libzstd linkage. if it works, i will try fixing the other bug you mentioned..

**Comment by edo9300** [comment]
> could you try download from this artifacts, and test it.. https://github.com/raedrizqie/MINGW-packages/actions/runs/10056650588
> 
> it supposed to fix libz and libzstd linkage. if it works, i will try fixing the other bug you mentioned..

With that package, the generated makefile will now attempt to link to `-lz.a` and `-lzstd.a`, so still wrong (in this case the erroneous thing is the `.a` in the library name)

**Comment by raedrizqie** [comment]
ok thanks for the feedback

**Comment by raedrizqie** [comment]
@edo9300 please test from this artifact
https://github.com/raedrizqie/MINGW-packages/actions/runs/10339534181

**Comment by Biswa96** [comment]
Static libraries can be checked with `nm` to find link with shared libraries. For example,

```
ls ucrt64/lib/libz*.a | grep -v dll | xargs -l nm | grep -i _imp | sort | uniq
```

Then find any APIs which is not Windows API and provided by a mingw package.

**Comment by edo9300** [comment]
> @edo9300 please test from this artifact https://github.com/raedrizqie/MINGW-packages/actions/runs/10339534181

working flawlessly
