### ISSUE TITLE
Bad signature from Emacs on Windows 11

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#21639]
### Description / Steps to reproduce the issue

I decided to uninstall the Emacs 29 MSYS2/UCRT64 package and to install my build of Emacs master on a Win11 Home machine. The build has been done on a Win10 Pro machine.

On both machines (Win10 and Win11) there are the same MSYS2/UCRT64 packages installed and also the `.emacs.d` directory is the same, with the same `init.el` etc.

### Expected behavior

Now using `M-x list-packages`, one would expect `*Packages*` buffer to appear showing the packages installed from MELPA/ELPA to be updated. This works on the Win 10 machine but not on the Win11 machine.

The packages installed are: 

a. `sr-speedbar, markdown-mode` from MELPA
b. `auctex` from ELPA

and the `init.el` file contains

```
(require 'package)

;; Adds the MELPA archive to the list of available repositories
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)

;; Initializes the package infrastructure
(package-initialize)

;; If there are no archived package contents, refresh them
(when (not package-archive-contents)
  (package-refresh-contents))
```

### Actual behavior

On the Win11 machine an `Error` buffer appears with this message:

```
Failed to verify signature archive-contents.sig:
Bad signature from 645357D2883A0966 GNU ELPA Signing Agent (2023) <elpasign@elpa.gnu.org>
Command output:
gpg: Firma effettuata 12/08/2024 23:05:01 ora legale Europa occidentale
gpg:                utilizzando la chiave EDDSA 0327BE68D64D9A1A66859F15645357D2883A0966
gpg: Firma BAD da "GNU ELPA Signing Agent (2023) <elpasign@elpa.gnu.org>" [sconosciuto]
```

and `*Messages*` shows:

```
...
Importing package-keyring.gpg...done
error in process filter: package--check-signature-content: Failed to verify signature: "archive-contents.sig"
error in process filter: Failed to verify signature: "archive-contents.sig"
error in process filter: package--check-signature-content: Failed to verify signature: "archive-contents.sig"
error in process filter: Failed to verify signature: "archive-contents.sig"
Package refresh done
...
```

I tried with an empty `.emacs.d` folder but the **Emacs shows those errors when starts!**

On Win10 machine all works..

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

on Win10: MSYS_NT-10.0-19045; on Win11 MSYS_NT-10.0-22000

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
Please report issue to emacs.
