### ISSUE TITLE
[nodejs] Running 'npm update -g' changes global root

### ISSUE THREAD

**Issue by aandrejevas** [msys2/MINGW-packages#21641]
### Description / Steps to reproduce the issue

1. pacman -S mingw-w64-ucrt-x86_64-nodejs
2. npm root -g
3. npm update -g
4. npm root -g
Output from steps 2 and 4 is different.

### Expected behavior

Output from steps 2 and 4 should not change.

### Actual behavior

![image](https://github.com/user-attachments/assets/1d2a3e8c-e0ca-4bb7-96dc-e5937d1dc935)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by raedrizqie** [comment]
you shouldnt run `npm update -g` in the first place.. it will update ALL the packages in node_modules, resulting to broken node package.

**Comment by raedrizqie** [comment]
you must remember that the mingw platform is not supported upstream. here, we patch npm and corepack to work correctly on mingw environment.. so, if you do `npm upgrade -g`, those packages will be replaced by vanilla npm and corepack..
