### ISSUE TITLE
headers-git package build failures

### ISSUE THREAD

**Issue by ReenigneArcher** [msys2/MINGW-packages#21645]
### Description / Steps to reproduce the issue

Since https://github.com/msys2/MINGW-packages/commit/2c842104e80cb8046cf676b86b94bcd1bb5f803f was merged, getting build failures. i.e. undeclared variables.

Same issue with the following commits, which I believe were an attempt to fix this:

- https://github.com/msys2/MINGW-packages/commit/4092caa8b74efedcdc3122c66b46a2228dc3b70a
- https://github.com/msys2/MINGW-packages/commit/794f052253cde0b6c942660ed7ad26eab8705075

References:
- https://github.com/LizardByte/Sunshine/pull/3002#issuecomment-2285433838

### Expected behavior

Everything is properly defined.

### Actual behavior

```txt
In file included from D:/a/_temp/msys64/ucrt64/include/windows.ui.composition.h:1380,
                 from D:/a/_temp/msys64/ucrt64/include/windows.graphics.capture.interop.h:41,
                 from D:/a/Sunshine/Sunshine/src/platform/windows/display_wgc.cpp:12:
D:/a/_temp/msys64/ucrt64/include/windows.ui.core.h:1605: error: field 'AdjustedPoint' has incomplete type 'ABI::Windows::UI::Core::Point'
 1605 |                     struct Point AdjustedPoint;
D:/a/_temp/msys64/ucrt64/include/windows.ui.core.h:1605: note: forward declaration of 'struct ABI::Windows::UI::Core::Point'
D:/a/_temp/msys64/ucrt64/include/windows.ui.core.h:2762: error: use of enum 'VirtualKey' without previous declaration
 2762 |                         enum VirtualKey key,
D:/a/_temp/msys64/ucrt64/include/windows.ui.core.h:2766: error: use of enum 'VirtualKey' without previous declaration
 2766 |                         enum VirtualKey key,
D:/a/_temp/msys64/ucrt64/include/windows.ui.core.h:4608: error: use of enum 'VirtualKey' without previous declaration
 4608 |                         enum VirtualKey *value) = 0;
D:/a/_temp/msys64/ucrt64/include/windows.ui.core.h:4879: error: use of enum 'VirtualKeyModifiers' without previous declaration
 4879 |                         enum VirtualKeyModifiers *value) = 0;
In file included from D:/a/_temp/msys64/ucrt64/include/windows.graphics.capture.interop.h:42:
D:/a/_temp/msys64/ucrt64/include/windows.graphics.capture.h:905: error: use of enum 'DirectXPixelFormat' without previous declaration
  905 |                         enum DirectXPixelFormat pixel_format,
D:/a/_temp/msys64/ucrt64/include/windows.graphics.capture.h:1103: error: use of enum 'DirectXPixelFormat' without previous declaration
 1103 |                         enum DirectXPixelFormat pixel_format,
D:/a/_temp/msys64/ucrt64/include/windows.graphics.capture.h:1239: error: use of enum 'DirectXPixelFormat' without previous declaration
 1239 |                         enum DirectXPixelFormat pixel_format,
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows Server 2022 GitHub runner

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
The actual issue is in widl program which generates header file from IDLs. See this upstream report https://bugs.winehq.org/show_bug.cgi?id=55347. We can workaround the issue with couple of sed commands.

**Comment by ReenigneArcher** [comment]
@Biswa96 thank you for that info. Let me know if you need me to test any artifacts or anything.

**Comment by Biswa96** [comment]
I can not compile Sunshine from that PR.

```
In file included from Sunshine/src/platform/windows/display_base.cpp:15:
Sunshine/src/platform/windows/display.h:15:10: fatal error: 'winrt/Windows.Graphics.Capture.h' file not found
   15 | #include <winrt/Windows.Graphics.Capture.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by Biswa96** [comment]
> Also note, it's not just that PR that's broken but all builds, so you can just use our master branch.

Please let us know if there is any further issue with msys2 ASAP.

BTW, it would be helpful if there is an cmake option in Sunshine to toggle building the web ui. npm is hard requirement but it is not required in this case.

**Comment by ReenigneArcher** [comment]
Just tried but I think it's still downloading an old version. `mingw-w64-ucrt-x86_64-headers-git-12.0.0.r235.g7a6c241e4-1-any downloading...`

I will try again in a little while.

> BTW, it would be helpful if there is an cmake option in Sunshine to toggle building the web ui. npm is hard requirement but it is not required in this case.

That probably never comes up because the web ui is required to run Sunshine. Only in dev does it get mentioned, but people just build specific targets, not disable it entirely. I can make make an option to disable it though.

**Comment by Biswa96** [comment]
> Just tried but I think it's still downloading an old version.

It's in the queue https://packages.msys2.org/queue

**Comment by ReenigneArcher** [comment]
@Biswa96 the build is improved, but still getting a couple of errors with the `-2` package.

```
FAILED: CMakeFiles/sunshine.dir/src/platform/windows/display_wgc.cpp.obj 
D:\a\_temp\msys64\ucrt64\bin\c++.exe -DBOOST_ATOMIC_NO_LIB -DBOOST_CHRONO_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_LOCALE_NO_LIB -DBOOST_LOG_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -DCURL_STATICLIB -DMINIUPNP_STATICLIB -DNDEBUG -DSUNSHINE_ASSETS_DIR=\"assets\" -DSUNSHINE_PLATFORM=\"windows\" -DSUNSHINE_TRAY=1 -DUSE_BOOST_REGEX -ID:/a/Sunshine/Sunshine/build -ID:/a/Sunshine/Sunshine -isystem D:/a/Sunshine/Sunshine/third-party/nvapi-open-source-sdk -isystem D:/a/Sunshine/Sunshine/third-party/ViGEmClient/include -isystem D:/a/Sunshine/Sunshine/third-party/nv-codec-headers/include -isystem D:/a/Sunshine/Sunshine/third-party -isystem D:/a/Sunshine/Sunshine/third-party/moonlight-common-c/enet/include -isystem D:/a/Sunshine/Sunshine/third-party/nanors -isystem D:/a/Sunshine/Sunshine/third-party/nanors/deps/obl -isystem D:/a/Sunshine/Sunshine/third-party/build-deps/ffmpeg/Windows-AMD64/include -O2 -g -DNDEBUG -std=gnu++20 -Wall -Wno-sign-compare -Wno-maybe-uninitialized -Werr
In file included from D:/a/_temp/msys64/ucrt64/include/windows.graphics.capture.interop.h:41,
                 from D:/a/Sunshine/Sunshine/src/platform/windows/display_wgc.cpp:12:
D:/a/_temp/msys64/ucrt64/include/windows.ui.composition.h:4922: error: use of enum 'DirectXPixelFormat' without previous declaration
 4922 |                         enum DirectXPixelFormat *value) = 0;
D:/a/_temp/msys64/ucrt64/include/windows.ui.composition.h:5707: error: use of enum 'DirectXPixelFormat' without previous declaration
 5707 |                         enum DirectXPixelFormat format,
```

**Comment by Biswa96** [comment]
d8d00b264c620f1781687b423eb38f0fb5796740 should fix it.

**Comment by ReenigneArcher** [comment]
Confirming this is resolved. Thank you!

**Comment by Biswa96** [comment]
The issue has been fixed in upstream wine project https://gitlab.winehq.org/wine/wine/-/merge_requests/6496. It'll take some time to reach this project via mingw-w64.
