### ISSUE TITLE
CodeBlocks package does not have wxSmith Plugin

### ISSUE THREAD

**Issue by stahta01** [msys2/MINGW-packages#21650]
The CodeBlocks package does not have wxSmith Plugin; reason it fails to build.
I am going to try to fix that by a round about method because the Makefile.am build system is too complex for me to fix it that way.
So, I plan to create or edit an MSys2 MinGW package to provide the cbp2make command.
Then, I will use cbp2make in an second package codeblocks-wxsmith that uses cbp2make to create a makefile to build wxsmithlib.dll and the wxsmith plugin. Likely be weeks to months before I am done.

Edit: The options for cbp2make are very complex looking

Tim S.

- [x] cbp2make package
- [x] wxsmith cbp file created
- [ ] makefile created using wxsmith cbp file and cbp2make
- [ ] wxsmith package created

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

**Comment by stahta01** [comment]
I really do not use wxSmith very much myself; but, it is a key plugin used by other projects; I will see if it builds and verify it can recreate files which is all I normally do. I do think the PR needs re-written so it is more likely the CodeBlocks dev team will accept the changes.

Tim S.
