### ISSUE TITLE
libssh package: ssh_userauth_agent missing in dynamic library but present in static library

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MINGW-packages#21664]
### Description / Steps to reproduce the issue

The `libssh` package in MinGW-w64 has an inconsistency between its static and dynamic libraries. The `ssh_userauth_agent` function is present in the static library (`libssh.a`) but missing from the dynamic library (`libssh.dll`).

Steps to reproduce:
1. Install the `libssh` package in MinGW-w64 (UCRT64 environment).
2. Run the following commands:
   ```bash
   objdump -x /ucrt64/lib/libssh.a | grep 'ssh_userauth_agent'
   objdump -x /ucrt64/bin/libssh.dll | grep 'ssh_userauth_agent'
   ```

### Expected behavior

Both the static and dynamic libraries should contain the same functions, including `ssh_userauth_agent`.

### Actual behavior

- The static library (`libssh.a`) contains the `ssh_userauth_agent` function:
  ```
  [  2](sec  1)(fl 0x00)(ty   20)(scl   3) (nx 0) 0x0000000000000020 ssh_userauth_agent_publickey
  [ 21](sec  1)(fl 0x00)(ty   20)(scl   2) (nx 0) 0x00000000000012e0 ssh_userauth_agent
  [ 29](sec  1)(fl 0x00)(ty   20)(scl   2) (nx 0) 0x0000000000001e80 ssh_userauth_agent_pubkey
  ```
- The dynamic library (`libssh.dll`) does not contain any `ssh_userauth_agent` functions.

### Verification

- [x] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [x] MINGW64
- [ ] MINGW32
- [x] UCRT64
- [x] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No, but I'm willing to provide any additional information or testing if needed.

Additional Notes:
Why this affects me, is trying to `git clone https://github.com/wez/libssh-rs` and `cargo test` breaks on msys2/ucrt64

**Comment by Kreijstal** [comment]
seems on archlinux
```
$ objdump -T /usr/lib/libssh.so.4.10.0 | grep 'ssh_userauth_agent'
0000000000015470 g    DF .text  000000000000007c  LIBSSH_4_5_0 ssh_userauth_agent_pubkey
0000000000013b50 g    DF .text  0000000000000dfd  LIBSSH_4_5_0 ssh_userauth_agent
```
the libraries seem there

**Comment by Biswa96** [comment]
I have updated libssh to version 0.11.0. Now the shared library contains the ssh_userauth_agent function.
