### ISSUE TITLE
Breeze dark theme icons do not work with KDE Qt5 apps on mingw32

### ISSUE THREAD

**Issue by jack6th** [msys2/MINGW-packages#21663]
### Description / Steps to reproduce the issue

Reproduce:
1. run okular or kate on mingw32
2. Menu -> Settings -> Color Scheme -> Breeze Dark

Tried with latest i686 binary. It does not work.
mingw-w64-i686-okular-23.08.4-1
mingw-w64-i686-kate-23.08.4-1
mingw-w64-i686-breeze-qt5-5.27.5-1
mingw-w64-i686-breeze-icons-qt5-5.114.0-1
mingw-w64-i686-kiconthemes-qt5-5.114.0-1

Build from latest mingw source (qt5) and all the dependencies.  It does not work either.
mingw-w64-i686-okular-23.08.5-1
mingw-w64-i686-kate-23.08.5-1
mingw-w64-i686-breeze-qt5-5.27.10-1
mingw-w64-i686-breeze-icons-qt5-5.115.0-1
mingw-w64-i686-kiconthemes-qt5-5.116.0-1

### Expected behavior

The icons in dark theme display icons with light foreground color and dark background color.

### Actual behavior

The icons in dark theme display icons same as light theme.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW32_NT-6.1-7601-WOW64

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
There is no mingw32 versions of those being maintained. For example, see kate https://packages.msys2.org/base/mingw-w64-kate. Please switch to ucrt64 environment.

**Comment by jack6th** [comment]
I solved it with the patch https://github.com/KDE/craft-blueprints-kde/blob/9335df8a24b10043295086e8079909736f551627/kde/frameworks/tier3/kiconthemes/svgiconengine.diff

see #20687
