### ISSUE TITLE
Looking for outdates msys mirror with .tar.xz packages

### ISSUE THREAD

**Issue by NS-Clone** [msys2/MINGW-packages#21680]
Is there any active msys packages mirror with old .tar.xz files?
without new all tar.zst ones

and old folder structure
```
distrib\i686\
distrib\x86_64\
mingw\i686\
mingw\sources\
mingw\x86_64\
msys\i686\
msys\sources\
msys\x86_64\
```

**Comment by Biswa96** [comment]
> Is there any active msys packages mirror with old .tar.xz files?

AFAIK, there is no such mirror. May I ask the reason for asking that?

**Comment by NS-Clone** [comment]
> > Is there any active msys packages mirror with old .tar.xz files?
> 
> AFAIK, there is no such mirror. May I ask the reason for asking that?

because i'm loading\backuping packages in old mirror format (several years : )
but now mirror that i'm using die\updated to new folder structure and to tar.zst format
and i can't continue download many files etc...

**Comment by Biswa96** [comment]
There is a guide to setup mirror https://www.msys2.org/dev/mirrors/

**Comment by NS-Clone** [comment]
> There is a guide to setup mirror https://www.msys2.org/dev/mirrors/

i can't reload it from zero...

what new equivalents of old files?

mingw\i686 -> mingw\mingw32 ????
or it still mingw\i686\

**Comment by 1480c1** [comment]
i686 seems to just be a symlink to mingw32 and x86_64 is a symlink to mingw64.
