### ISSUE TITLE
node.js npm doesn't install manpages when installing modules globally

### ISSUE THREAD

**Issue by elieux** [msys2/MINGW-packages#217]
When installing a module globally, manpages should be copied to `share/man/` as described here: https://www.npmjs.org/doc/files/package.json.html#man

What's weird is that Arch's npm doesn't copy manpages either, so maybe it's an upstream bug. Could be that the modules have wrong/obsolete metadata.

I tested with modules jslint v0.6.4 and luamin v0.2.8. Arch node v0.10.32-2 with bundled npm v2.0.1. MSYS2 node v0.10.32-4 with bundled npm v1.4.28.

Split from #216, see [this comment](https://github.com/Alexpux/MINGW-packages/issues/216#issuecomment-56295095).

**Comment by MehdiChinoune** [comment]
nodejs is no longer available.
