### ISSUE TITLE
zed: not able to use MSYS2's clangd

### ISSUE THREAD

**Issue by BLumia** [msys2/MINGW-packages#21712]
### Description / Steps to reproduce the issue

I'm reporting this issue here because...

> Please, report any issue in [msys2/MINGW-packages/issues](https://github.com/msys2/MINGW-packages/issues?q=is%3Aissue+is%3Aopen+zed) first.  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--[windows.md](https://github.com/zed-industries/zed/blob/main/docs/src/development/windows.md#installing-from-msys2)

Currently it seems Zed won't recognize MSYS2's clangd, don't support setting the location of clangd manually, and also won't be able to download its own clangd successfully.

Reproduce steps:

1. Create a simple CMake-based C++ project
2. run `cmake -Bbuild . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug` to ensure `compile_commands.json` is generated
3. run `zed .` to start the zed editor, which is installed by running `pacman -S mingw-w64-ucrt-x86_64-zed`
4. See result.

Feel free to let me know if you need any additional information.

### Expected behavior

The clangd-based C++ intellisense features should be available (able to Ctrl+Click to jump to definition, etc.)

### Actual behavior

The clangd-based C++ intellisense features is not working at all, we can also "Downloading clangd..." on the status bar, and it also won't finish download. Beside that, it also seems we can not set the location of clangd manually.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No (since it might be a Zed issue instead of MSYS2 packaging issue)

**Comment by Biswa96** [comment]
Could you get some hint in Process Monitor (filter: process name zed.exe)?

**Comment by BLumia** [comment]
The filtered results are seven figured and I'm not sure where to look at. Could you explain in detail? btw, does it mean it works as intended on your device?

**Comment by Biswa96** [comment]
It does not work in my device and fails with some vulkan related error probably due to absense of dGPU.

**Comment by ognevny** [comment]
> Reproduce steps:
> 
>     1. Create a simple CMake-based C++ project
> 
>     2. run `cmake -Bbuild . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug` to ensure `compile_commands.json` is generated
> 
>     3. run `zed .` to start the zed editor, which is installed by running `pacman -S mingw-w64-ucrt-x86_64-zed`
> 
>     4. See result.

**Comment by ognevny** [comment]
> Create a simple CMake-based C++ project

sorry for very late answer. can you provide example of such project, please?

**Comment by ognevny** [comment]
nevermind, I found one. it's not reproducible for me. make sure that (in case you use UCRT64)
1. you have [clang-tools-extra](https://packages.msys2.org/packages/mingw-w64-ucrt-x86_64-clang-tools-extra) package installed
2. you have clangd.exe in $PATH while executing Zed (this can be achieved by running `zed` in UCRT64 shell or put absolute path to `/ucrt64/bin` to global $PATH)

**Comment by BLumia** [comment]
Can confirm still exists in `zed 0.154.3-1` but now fixed after upgrade `zed` (`mingw-w64-ucrt-x86_64-zed`) to `0.160.7-1`. Should be a bug fixed from zed side.

Anyway thanks for the update :)

**Comment by ognevny** [comment]
> Should be a bug fixed from zed side

they add support for system LSPs from time to time
