### ISSUE TITLE
[qemu] root=/dev/sda2 kernel command line changed to root=F:/msys2/dev/sda2

### ISSUE THREAD

**Issue by yuanjianpeng** [msys2/MINGW-packages#21728]
### Description / Steps to reproduce the issue

I'm try to use qemu-system-aarch64 to run a debian 12 os. after I install the debian to a local disk file and try to run it.
that failed to mount the rootfs.
$ qemu-system-aarch64 -machine type=virt -m 1024 -cpu max -kernel ./vmlinuz-6.1.0-22-arm64 -append 'root=/dev/sda2 console=ttyAMA0 rootfstype=ext4' -initrd ./initrd.img-6.1.0-22-arm64 -drive file=./debian-aarch64.qcow2,id=hd,if=none,media=disk -device virtio-scsi-device -device scsi-hd,drive=hd -nographic

the boot console log show kernel command line changed:
[    0.000000] Kernel command line: root=F:/msys2/dev/sda2 console=ttyAMA0 rootfstype=ext4

[   33.931370] F:/msys2/dev/sda2: Can't open blockdev
mount: mounting F:/msys2/dev/sda2 on /root failed: No such file or directory
Failed to mount F:/msys2/dev/sda2 as root file system.

### Expected behavior

kernel command line should same as the -append arguments

### Actual behavior

kernel command line changed from /dev/sda2 to F:sys2/dev/sda2

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045 DESKTOP-6ORM3SI 3.5.3.x86_64 2024-05-06 06:45 UTC x86_64 Msys

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by heljkon** [comment]
try
```
export MSYS2_ARG_CONV_EXCL='*'
qemu-system-aarch64 -machine type=virt -m 1024 -cpu max \
  -kernel ./vmlinuz-6.1.0-22-arm64 \
  -append 'root=/dev/sda2 console=ttyAMA0 rootfstype=ext4' \
  -initrd ./initrd.img-6.1.0-22-arm64 \
  -drive file=./debian-aarch64.qcow2,id=hd,if=none,media=disk \
  -device virtio-scsi-device -device scsi-hd,drive=hd -nographic
unset MSYS2_ARG_CONV_EXCL
```

**Comment by yuanjianpeng** [comment]
> try
> 
> ```
> MSYS2_ARG_CONV_EXCL='*' qemu-system-aarch64 -machine type=virt -m 1024 -cpu max \
>   -kernel ./vmlinuz-6.1.0-22-arm64 \
>   -append 'root=/dev/sda2 console=ttyAMA0 rootfstype=ext4' \
>   -initrd ./initrd.img-6.1.0-22-arm64 \
>   -drive file=./debian-aarch64.qcow2,id=hd,if=none,media=disk \
>   -device virtio-scsi-device -device scsi-hd,drive=hd -nographic
> ```
> 
> see https://www.msys2.org/docs/filesystem-paths/#automatic-unix-windows-path-conversion
> 
> please close if solved

works, kernel command line is now right  
[    0.000000] Kernel command line: `root=/dev/sda2` console=ttyAMA0 rootfstype=ext4
