### ISSUE TITLE
[ffmpeg] 'drawtext' filter not available since 6.1

### ISSUE THREAD

**Issue by k-ashiya** [msys2/MINGW-packages#21734]
### Description / Steps to reproduce the issue

'drawtext' filter is not available since 6.1 because it requires libharfbuzz as stated in [ffmpeg documentation](https://ffmpeg.org/ffmpeg-all.html#drawtext-1).

similar Arch issue: https://gitlab.archlinux.org/archlinux/packaging/packages/ffmpeg/-/issues/1

### Expected behavior

```
$ ffmpeg -hide_banner -filters | grep drawtext
 T.C drawtext          V->V       Draw text on top of video frames using libfreetype library.
```

### Actual behavior

```
$ ffmpeg -hide_banner -filters | grep drawtext
(no result)
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I have added a pull request to fix this issue and it works now.

```
$ /ucrt64/bin/ffmpeg -hide_banner -filters | grep drawtext
 T.C drawtext          V->V       Draw text on top of video frames using libfreetype library.
```
