### ISSUE TITLE
Artifact download fails

### ISSUE THREAD

**Issue by heljkon** [msys2/MINGW-packages#21794]
### Description / Steps to reproduce the issue

With https://github.com/msys2/MINGW-packages/pull/21540 I prepare QEMU 9.1.0. I usually download with FirefoxESR@Linux. This fails. Trying to download with Edge@Win10 the download starts but it does not finish. It's a failure, too.

Last time I was able to download the built package zip was 2 weeks ago after commit https://github.com/msys2/MINGW-packages/pull/21540/commits/ba269f38f10f6dce70c51e67c568af54fe67b700.

Last week I did not work after commit https://github.com/msys2/MINGW-packages/pull/21540/commits/5cbb1baecd93b8d7a852e8d443832aeef3775493.

Now with commit https://github.com/msys2/MINGW-packages/pull/21540/commits/9e8246c595518d760e7b98892692e00a040cd049 it keeps failing. 

I've read about issues with octokit v4 in https://github.com/actions/upload-artifact/issues/593

### Expected behavior

I would like to successfully download artifacts.

### Actual behavior

Downloading artifacts fails.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
This has nothing to do with msys2 or mingw-packages. I can download the artifacts without any issue.

**Comment by heljkon** [comment]
thanx for checking
