### ISSUE TITLE
A conflict cannot be resolved

### ISSUE THREAD

**Issue by NTUWhitefox** [msys2/MINGW-packages#21790]
### Package name

mingw-w64-x86_64-cmake

### For which environment do you need the package?

UCRT64

### Provide a brief description why you need this package in the selected environment

How to resolve this conflict?
![圖片_2024-08-30_063656679](https://github.com/user-attachments/assets/b1189e6d-d857-4b86-913f-3585d3936048)

**Comment by ognevny** [comment]
run `pacman -Suy` multiple times until there are no updates

**Comment by NTUWhitefox** [comment]
It works! Thanks. 
I use -syyu to upgrade instead of -syu. I didn't notice the difference. I'm idiot.
