### ISSUE TITLE
Does UCRT64/ps2pdf work with other UCRT64 apps?

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#21809]
I tried to use `ps2pdf` from `mingw-w64-ucrt-x86_64-ghostscript` in my UCRT64 Emacs init file to print a buffer in a PDF file. Something like this

```
[...]
(setq cmd (concat "C:/msys64/ucrt64/bin/ps2pdf -sPAPERSIZE=a4 tmp.ps " (buffer-name) ".pdf"))
[...]
```

but it does not work because `ps2pdf` is a (bash) script not a binary file (`ps2pdf.exe`).

Indeed if I use `ps2pdf` from my monolithic TeXLive installation, it works

```
[...]
(setq cmd (concat "C:/texlive/bin/windows/ps2pdf -sPAPERSIZE=a4 tmp.ps " (buffer-name) ".pdf"))
[...]
```

In this case `ps2pdf` is an `exe`:

```
ls  C:/texlive/bin/windows/ps2pdf*
texlive/bin/windows/ps2pdf.exe    texlive/bin/windows/ps2pdf13.exe
texlive/bin/windows/ps2pdf12.exe  texlive/bin/windows/ps2pdf14.exe
```

Given the MSYS2 mission, should the `ps2pdf` and friends, from UCRT64, be _binary_ files not script?

Yes, invoked from command line they work but they should work also if invoked from another Windows (UCRT64) app.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> Given the MSYS2 mission, should the `ps2pdf` and friends, from UCRT64, be _binary_ files not script?

There is no "MSYS2 mission" to convert scripts to PE files.

Could you reproduce the issue without emacs?

**Comment by angelog0** [comment]
Is MSYS2 a tool to build Windows _native_ applications using a `POSIX` infrastructure? Are UCRT64 apps Windows _native_ apps?

With TeXLive in the path I can convert a Postscript file to PDF from CMD. If I remove TeXLive and add `C:\msys64\ucrt64\bin` to Windows PATH, `ps2pdf` is not recognized.

**Comment by Biswa96** [comment]
I think this is not actionable by msys2 project. ps2pdf is a shell script and we can not change that.
