### ISSUE TITLE
Add asm-lsp

### ISSUE THREAD

**Issue by Freed-Wu** [msys2/MINGW-packages#21845]
### Package name

asm-lsp

### Brief description of package

Language server for NASM/GAS/GO Assembly

### URL for package's homepage

https://github.com/bergercookie/asm-lsp

### Provide a basic test case to validate the package's functionality.

asm-lsp --version

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by Biswa96** [comment]
I have added a pull request to add the package. Would you like to test the packages from GitHub Actions artifacts of that pull request? Link https://github.com/msys2/MINGW-packages/actions/runs/10732087534

Could you provide any steps to add the asm-lsp in any IDE except vscode or its forks?
