### ISSUE TITLE
In ucrt64 bash, running g++ compilation does not prompt errors and also does not generate object files.

### ISSUE THREAD

**Issue by TwoBrushes** [msys2/MINGW-packages#21843]
### Description / Steps to reproduce the issue

1、install msys2, then install gcc toolchain
2、in ucrt64 bash,type g++ test.cpp -o test, , No matter whether test.cpp exists or not, there is no prompt.
3、in Windows cmd,type g++ test.cpp -o test,  it prompts an error that cc1plus entry point cannot be found. (g++.exe path is already add to system path)
4、Copy the dll files under the same directory as g++.exe to lib\gcc\x86_64-w64-mingw32\14.2.0,  g++ can run normally in both ucrt64 bash and Windows cmd.
![image](https://github.com/user-attachments/assets/4c842222-7022-4e01-9615-373f6e73481f)
![image](https://github.com/user-attachments/assets/58b2f6d7-860b-46de-9fe9-53ddda8047ae)

 

### Expected behavior

After installing the gcc toolchain, you can compile and generate object files normally.

### Actual behavior

In ucrt64 bash, no errors are displayed and no target files are generated.
In Windows cmd, it prompts an error that cc1plus entry point cannot be found.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by TwoBrushes** [comment]
I found a zlib1.dll file with the same name under c:\windows\system32 as in ucrt64\bin, and it is possible that cc1plus.exe called by g++ first referenced c:\windows\system32\zlib1.dll, which may be the cause of the error. After renaming c:\windows\system32\zlib1.dll, everything worked fine.

**Comment by Biswa96** [comment]
> I found a zlib1.dll file with the same name under c:\windows\system32

That is not done by msys2.

> After renaming c:\windows\system32\zlib1.dll, everything worked fine.

The issue is solved then.
