### ISSUE TITLE
[llvm] missing lib/LLVMgold.dll

### ISSUE THREAD

**Issue by enetheru** [msys2/MINGW-packages#21869]
### Description / Steps to reproduce the issue

Enable link time optimisation(-lto) when building programs with clang and lld in ucrt64 environment
compile
it appears other distributions have run into the same trouble in the past:
https://github.com/microsoft/azurelinux/issues/6999

### Expected behavior

program compiles successfully.

### Actual behavior

... /lib/LLVMgold.dll : error loading plugin: clang++: error: linker command failed with exit code 1 (use -v to see invocation)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

https://github.com/microsoft/azurelinux/pull/8582

**Comment by enetheru** [comment]
> `-fuse-ld=lld`

"Enable link time optimisation(-lto)"

**Comment by enetheru** [comment]
Thanks, I had a problem in the build system that went unnoticed. I appreciate your time.

**Comment by TheAenema** [comment]
> Thanks, I had a problem in the build system that went unnoticed. I appreciate your time.

Can you please share what was wrong, I have same issue.

**Comment by CycloneRing** [comment]
> Thanks, I had a problem in the build system that went unnoticed. I appreciate your time.

@enetheru Can you please share what was wrong, I have same issue.

**Comment by enetheru** [comment]
OK, so my memory is not great, last week was a year ago to me. But I remember vaguely that my toolchain was not setup properly, I was tracing commands from verbose output and found that it wasnt even doing what I told it to. I'm sorry I cant be more helpful. I've completely re-built my environments since then and dont remember the exact issue.

**Comment by hwalinga** [comment]
@CycloneRing  I have the same issuee. How did you manage to fix it?

**Comment by enetheru** [comment]
@CycloneRing @hwalinga In my case I didnt fix it. After reading a bunch more, and testing out other build chains, I just stopped trying to use llvm clang in msys2/ucrt64. I change to msys2/clang64 when I want to compile using the llvm tools.
