### ISSUE TITLE
[filezilla] source link does not download tarball instead redirects to html file

### ISSUE THREAD

**Issue by stahta01** [msys2/MINGW-packages#21889]
### Package name

filezilla

### Other information that may be useful

ERROR: One or more files did not pass the validity check!

I tried to build the package and got this error and can not get it to build after ignoring the error.

Tim S. 

### Are you willing to submit a PR?

No

**Comment by Biswa96** [comment]
I can reproduce the issue and it has been reported to ArchLinux also https://gitlab.archlinux.org/archlinux/packaging/packages/libfilezilla/-/issues/1

**Comment by Biswa96** [comment]
In the meantime, you could use source-only tarball from here https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-filezilla?repo=ucrt64 if you need source code immediately.

**Comment by MehdiChinoune** [comment]
Fixed by ddc213fa6867111321a68d4c4c41a03d8a9f3798

**Comment by Biswa96** [comment]
> Fixed by [ddc213f](https://github.com/msys2/MINGW-packages/commit/ddc213fa6867111321a68d4c4c41a03d8a9f3798)

That download link did not work. The commit was reverted in 849c8246ae7433d16c2e9b2c89161b38abcb99b7

**Comment by Biswa96** [comment]
Would it be possible to download the source tarball from upstream and save it in release page of this repository? ArchLinux did something like that in https://gitlab.archlinux.org/archlinux/packaging/packages/filezilla/-/commit/2d0299d932474aac5e63091ae2deb456a8ad3920 commit.
