### ISSUE TITLE
archive for Windows 7

### ISSUE THREAD

**Issue by veso266** [msys2/MINGW-packages#21917]
Hi there, today I had to reinstall msys2 on one of my windows 7 maschine and was met with a cold shower

I was not able to replicate the enviroment anymore, that used to work fine, when windows 7 was still supported

I used the last supported installer: https://github.com/msys2/msys2-installer/releases/tag/2022-10-28

and then used this commands to try to replicate my enviroment
```
#Run in Msys2 shell
pacman -Sy
pacman --noconfirm -S msys2-runtime-3.4 msys2-runtime-3.4-devel

#Run in Mingw64 shell
pacman -Suy -- if I run this, then it gets updated to some wierd shell with broken font
pacman -S --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain perl git
pacman -S mingw-w64-x86_64-cmake curl, wget
pacman -S libcurl-devel -- errors out: error: failed to prepare transaction (could not satisfy dependencies)
:: installing libdb (6.2.32-5) breaks dependency 'libdb=5.3.28' required by db

pacman -S mingw-w64-x86_64-mtools
```

To make python run, you need to copy this dll (x64 folder) from [api-ms-win-core-path-blender-0.3.1.zip](https://github.com/nalexandru/api-ms-win-core-path-HACK) to C:/msys64/mingw64/bin/

but cmake, curl, wget all all stil broken (this are just the ones I know are broken, who knows, what else doesn't work)

I understand that msys2 cannot support unsupported oses anymore with new updated packages, but to not be able to replicate the enviroment to the state that in one point in time worked?

is there any archive which has packages supported for older osese I can point my pacman to

I know cygwin has an archive of packages, which means you can just point it to and it will download everything from the archive, meaning what worked will continue to do so

or maybe pacman can be updated to only install supported version of a package?

Thanks for Anwsering and Best Regards
PS: if anyone knows, how can I get my cmake, curl and wget working, please tell me :smile:

**Comment by Biswa96** [comment]
Windows 7 is not supported.

**Comment by veso266** [comment]
I know its not supported, but why I can't even replicate the enviroment that used to work fine when windows 7 was supported

Why no archive to be able to configure msys2 the way it was?
