### ISSUE TITLE
mingw-w64-ucrt-x86_64-gtk4 4.16.1-1

### ISSUE THREAD

**Issue by hbiblia** [msys2/MINGW-packages#21959]
### Description / Steps to reproduce the issue

I updated to GTK 4.16.1-1 on Windows 11 on 09/17/2024, and everything is flickering.

### Expected behavior

Que funcione...

### Actual behavior

...

https://github.com/user-attachments/assets/514483f7-6ce0-44bb-8f61-d25264aacac1

https://github.com/user-attachments/assets/4256fba9-27d6-4605-8f0a-83c2c84a9ea0

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by hbiblia** [comment]
The stable version of GTK4 is 4.14.6. How is it possible for an unstable version to be released...? 😡🤬

**Comment by lazka** [comment]
4.16.1 is the latest stable release.

**Comment by sheaf** [comment]
I have the same issue since updating to GTK 4.16 (on Windows). For example, the GTK Inspector now flickers; after changing tab I get flickers which display the tab I was on previously.

I am currently on `mingw64/mingw-w64-x86_64-gtk4 4.16.0-1`. I am upgrading to `4.16.1-1` and will report back if it fixes the issue. I'm not hopeful, I don't see anything in the changelog between 4.16.0 and 4.16.1 about this though.

Changing the renderer from the new OpenGL renderer back to the old OpenGL renderer with `GSK_RENDERER=gl` does **not** fix the issue, although it seems it makes it a bit less severe.

**Comment by sheaf** [comment]
I believe this is a GTK bug so I've [filed a ticket](https://gitlab.gnome.org/GNOME/gtk/-/issues/7019) on the dedicated bug-tracker.

**Comment by lazka** [comment]
> I believe this is a GTK bug so I've [filed a ticket](https://gitlab.gnome.org/GNOME/gtk/-/issues/7019) on the dedicated bug-tracker.

thanks, perfect!

For the record, I'm on AMD, so maybe an Nvidia specific issue.

**Comment by lb90** [comment]
> For the record, I'm on AMD, so maybe an Nvidia specific issue.

You beat me to it :) @hbiblia do you happen to have an NVidia GPU?

**Comment by hbiblia** [comment]
> > For the record, I'm on AMD, so maybe an Nvidia specific issue.
> 
> You beat me to it :) @hbiblia do you happen to have an NVidia GPU?

Nvidia GeForce GTX 1660 Ti Mobile

**Comment by hbiblia** [comment]
I have the same problem with version 4.16.1-2, but I was able to get it working with **GSK_RENDERER=cairo**. The other renderers have the same issue, and some are much worse.

**Comment by lazka** [comment]
I guess someone with nvidia hardware needs to bisect it.

I wonder if vulkan would work nowadays? Might be a workaround.

**Comment by hbiblia** [comment]
Tested on **mingw-w64-ucrt-x86_64-gtk4 4.16.2-1**
I tested it with Vulkan, but the issue remains the same, so I stuck with GSK_RENDERER=cairo.

**Comment by lazka** [comment]
Please try again now.

**Comment by hbiblia** [comment]
**mingw-w64-ucrt-x86_64-gtk4 4.16.3-2**
This version works correctly, thank you for the work done. ❤️

**Comment by hbiblia** [comment]
> Please try again now.

This version works correctly, thank you for the work done. ❤️

**mingw-w64-ucrt-x86_64-gtk4 4.16.3-2**
Windows 11 Home 23H2
MINGW64_NT-10.0-22631

**Comment by lazka** [comment]
thanks for testing

**Comment by sheaf** [comment]
Same here, 4.16.3-2 works a charm. The recently enabled Vulkan backend seems to work well too. Thanks!
