### ISSUE TITLE
[qt6-base] Missing UIC and MOC

### ISSUE THREAD

**Issue by bkmgit** [msys2/MINGW-packages#21966]
### Description / Steps to reproduce the issue

Qt6-base is missing the moc and uic executables.  These are available in Qt5-base but have been moved to libexecdir in Qt6 as explained at https://github.com/msys2/MINGW-packages/blob/e858872a3b4d7ee9bfdc40f41aaead2bfc519186/mingw-w64-gpgme/0001-fix-find-moc-qt6.patch#L6  This creates compilation errors when trying to build programs that depend on moc or uic, see https://github.com/wedesoft/anymeal/pull/67

### Expected behavior

The binaries uic and moc should be available.

### Actual behavior

Binaries cannot be found

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-17763

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes

**Comment by Biswa96** [comment]
/mingw64/share/qt6/bin/uic.exe
/mingw64/share/qt6/bin/moc.exe

**Comment by bkmgit** [comment]
Thanks.

**Comment by Biswa96** [comment]
I am not sure what is going in that pull request but you do not need to add the paths explicitly. CMake should find the path automatically. We do not add paths like that for qt6 based projects.

**Comment by bkmgit** [comment]
That build currently uses autotools, not CMake.

**Comment by mmuetzel** [comment]
You could use `qtpaths-qt6 --query QT_HOST_LIBEXECS` to query the path to the tools.
