### ISSUE TITLE
[qt6-tools] lupdate requires Qt6QML library from Qt6-declarative

### ISSUE THREAD

**Issue by bkmgit** [msys2/MINGW-packages#21976]
### Description / Steps to reproduce the issue

When running lupdate-qt6 from qt6-base without qt6-declarative, one gets an error because the library qt6qml is not available. Can be observed in https://github.com/wedesoft/anymeal/pull/67 in particular CI on commit https://github.com/wedesoft/anymeal/pull/67/commits/46cc09a76a2f3f21e356a00587d2c1b4037bcd56

### Expected behavior

lupdate-qt6 should run as normal.

### Actual behavior

Exits with an error

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-17763

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Can make Qt6-base require Qt6-declarative

**Comment by lazka** [comment]
lupdate is part of qt6-tools not base.

https://github.com/msys2/MINGW-packages/blob/2e116955d3a5c302ae78278a963184049f11f848/mingw-w64-qt6-tools/PKGBUILD#L71C44-L71C55 marks it as an optional dependency, same as Arch Linux. I don't know if this is something that should be changed.

**Comment by MehdiChinoune** [comment]
It's already marked as an optional dependency for lupdate-qt6.
