### ISSUE TITLE
broken nsis

### ISSUE THREAD

**Issue by ciros88** [msys2/MINGW-packages#21999]
### Description / Steps to reproduce the issue

1. install `mingw-w64-i686-nsis` or `mingw-w64-x86_64-nsis`
2. execute `makensis /version` or `makensis /license`

### Expected behavior

display nsis version or license

### Actual behavior

`$ makensis /version`\
`Processing config: C:\msys64\mingw32\etc\nsisconf.nsh`\
`Can't open script "C:/msys64/version"`

`$ makensis /license`\
`Processing config: C:\msys64\mingw32\etc\nsisconf.nsh`\
`Can't open script "C:/msys64/license"`

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW32_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by raedrizqie** [comment]
you can use:
```
$ nss-config --version
3.104.0
```

**Comment by ciros88** [comment]
> you can use:
> 
> $ nss-config --version
> 3.104.0
> 
@raedrizqie ure not getting the point: makensis is broken, it is not about printing the version itself

**Comment by raedrizqie** [comment]
i think you need to run it under `cmd` or `powershell` ?

**Comment by ciros88** [comment]
i run it in mingw32 shell (as it should be)

**Comment by ciros88** [comment]
this is not the point, the issue is that makensis doesn't work in msys2 shell (where is supposed to, and also where i personally need it)

**Comment by ArchGuyWu** [comment]
> this is not the point, the issue is that makensis doesn't work in msys2 shell (where is supposed to, and also where i personally need it)

You can see this: https://www.msys2.org/docs/filesystem-paths/

**Comment by ArchGuyWu** [comment]
Automatic Unix ⟶ Windows Path Conversion is enabled by default.

**Comment by ciros88** [comment]
@ArchGuyWu can you give me a proper context? exactly what is your suggested solution? have you tried it? thanks

**Comment by ArchGuyWu** [comment]
> 2\. makensis

Don't use "/" for arguments in unix shell.

**Comment by ArchGuyWu** [comment]
> @ArchGuyWu can you give me a proper context? exactly what is your suggested solution? have you tried it? thanks
Don't use "/" for arguments in unix shell.

**Comment by ArchGuyWu** [comment]
"/" is used for path in unix system.
