### ISSUE TITLE
[boost] 1.86.0-4 missing system library

### ISSUE THREAD

**Issue by ThexXTURBOXx** [msys2/MINGW-packages#22081]
### Description / Steps to reproduce the issue

1. Run `pacman -S mingw-w64-ucrt-x86_64-boost` or `pacman -Syuu` (if boost was already installed)

### Expected behavior

There should be the system library of boost in `/ucrt64/lib/libboost_system-mt.a` or `/ucrt64/lib/libboost_system-mt.dll.a`

### Actual behavior

In 1.86.0-1, both these files existed, but they got removed when I updated to `1.86.0-4` yesterday.
A quick look into the zst shows that the system library indeed is not shipped anymore with the distribution.
The same is true for many other libraries of boost as well, as WinMerge shows:
![grafik](https://github.com/user-attachments/assets/141a535f-c6e0-4953-9c6d-0defa82a653d)

I am quite unsure whether this was done purposely or by accident.
Also, I don't know which environments are affected. UCRT64 is for sure affected by this.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
Those libraries were just dummy libraries they don't contain any relevant symbol. Those libraries are just header libraries i.e. you should just look for headers if you want to use them (like eigen3 library).
If you use CMake It won't be an issue.

**Comment by MehdiChinoune** [comment]
see: https://github.com/boostorg/system/issues/123
