### ISSUE TITLE
Add vala-lint

### ISSUE THREAD

**Issue by chatchoi** [msys2/MINGW-packages#22135]
### Package name

vala-lint

### Brief description of package

Check code-style of Vala code files

### URL for package's homepage

https://github.com/vala-lang/vala-lint

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANGARM64

**Comment by Biswa96** [comment]
The project depends on posix functions. I can not compile it in mingw environment.

```
src/io.elementary.vala-lint.exe.p/Application.c:32:10: fatal error: fnmatch.h: No such file or directory
   32 | #include <fnmatch.h>
      |          ^~~~~~~~~~~
compilation terminated.
```

**Comment by chatchoi** [comment]
Nope. They don't care about Windows. I have no replies from them.
