### ISSUE TITLE
header `wasm.h` exists in both `libwasmtime` and `wasmer`

### ISSUE THREAD

**Issue by podsvirov** [msys2/MINGW-packages#22147]
### Description / Steps to reproduce the issue

```
$ pacboy -S libwasmtime:u wasmer:u --noconfirm
resolving dependencies...
looking for conflicting packages...

Packages (2) mingw-w64-ucrt-x86_64-libwasmtime-25.0.1-3  mingw-w64-ucrt-x86_64-wasmer-4.4.0-1

Total Installed Size:  192.20 MiB

:: Proceed with installation? [Y/n]
(2/2) checking keys in keyring                               [###############################] 100%
(2/2) checking package integrity                             [###############################] 100%
(2/2) loading package files                                  [###############################] 100%
(2/2) checking for file conflicts                            [###############################] 100%
error: failed to commit transaction (conflicting files)
/ucrt64/include/wasm.h exists in both 'mingw-w64-ucrt-x86_64-libwasmtime' and 'mingw-w64-ucrt-x86_64-wasmer'
Errors occurred, no packages were upgraded.
```

### Expected behavior

install and use both `libwasmtime` and `wasmer` packages

### Actual behavior

error: failed to commit transaction (conflicting files)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANGARM64

**Comment by podsvirov** [comment]
Cc: @ognevny

**Comment by ognevny** [comment]
> Cc: @ognevny 

maybe split wasmer into `wasmer` and `libwasmer` then mark `libwasmtime` as conflict with `libwasmer`
