### ISSUE TITLE
`data` folder in `ucrt64/bin` after Okular installation

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#22185]
Is it to be expected a `data` directory in `/ucrt64/bin` after installing Okular?

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

**Comment by ognevny** [comment]
yes, it's expected

**Comment by angelog0** [comment]
Ok, I close this then..

**Comment by Biswa96** [comment]
> Is it to be expected a `data` directory in `/ucrt64/bin` after installing Okular?

The list of files in okular package can be found here https://packages.msys2.org/packages/mingw-w64-ucrt-x86_64-okular

**Comment by raedrizqie** [comment]
can't we set the datadir to `share` instead?

**Comment by Biswa96** [comment]
> can't we set the datadir to `share` instead?

Nope, it's default paths for Qt in Windows https://doc.qt.io/qt-6/qstandardpaths.html

**Comment by raedrizqie** [comment]
i see..
