### ISSUE TITLE
[wineditline] Wrong lib when linking statically

### ISSUE THREAD

**Issue by lorcap** [msys2/MINGW-packages#22198]
### Description / Steps to reproduce the issue

Static linking fails because `pkgconf --libs --static`  returns `-ledit` (i.e., `libedit.a`) which does not exist.

### Expected behavior

`pkgconf --libs --static` shall return `-ledit_static`.

### Actual behavior

`pkgconf --libs --static`  returns `-ledit`.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32 (not tested)
- [X] UCRT64
- [X] CLANG64 (not tested)
- [X] CLANGARM64 (not tested)

### Are you willing to submit a PR?

As far as I know, it is not possible to provide both linking flags with a single `.pc` file. Therefore, a second `wineditline-static.pc` shall be provided:

```
prefix=${prefix}
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: wineditline-static
Description: EditLine API implementation for the native Windows Console - static linking
Version: 2.206
Cflags: -I${includedir}/editline
Libs: -L${libdir} -ledit_static
```

**Comment by mmuetzel** [comment]
Alternatively and maybe easier to manage: The static library could be renamed to `libedit.a`. Or does that break existing use-cases?

**Comment by lorcap** [comment]
> Alternatively and maybe easier to manage: The static library could be renamed to `libedit.a`. Or does that break existing use-cases?

Upstream `src/CMakeLists.txt` installs `libedit_static.a` and no pkg-config file, unfortunately. Thus, renaming is not a good idea, IMHO.

**Comment by mmuetzel** [comment]
> Thus, renaming is not a good idea, IMHO.

I already suspected as much. 
Maybe, installing two copies of the static library (named `libedit_static.a` and `libedit.a`) could work?

**Comment by lorcap** [comment]
> Maybe, installing two copies of the static library (named `libedit_static.a` and `libedit.a`) could work?

That would do. A symlink would be better, I think.

The only concern I still have: why choosing such a pattern? `.a` already means *static*... I don't know.
