### ISSUE TITLE
[mingw-w64-tcl] is missing tcl.h

### ISSUE THREAD

**Issue by Febbe** [msys2/MINGW-packages#22197]
### Description / Steps to reproduce the issue

Try to compile to libtcl8.6.

### Expected behavior

No error, that tcl.h is missing.

### Actual behavior

Compilation is missing tcl.h.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-26120

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANGARM64

**Comment by ognevny** [comment]
it has tcl.h. try to reinstall package
```
pacman -Scc
pacman -Sy $MINGW_PACKAGE_PREFIX-tcl
```
see https://packages.msys2.org/packages/mingw-w64-ucrt-x86_64-tcl for details about installed files
