### ISSUE TITLE
python-jupyter_console not starting 

### ISSUE THREAD

**Issue by voertler** [msys2/MINGW-packages#22214]
### Description / Steps to reproduce the issue

- Install the package `pacman -S mingw-w64-x86_64-python-jupyter_console` or  `pacman -S mingw-w64-ucrt-x86_64-python-jupyter_console`

- start jupyter console

### Expected behavior

The jupyter console should open

### Actual behavior

Error message `Fatal error in launcher: Unable to find an appended archive.`

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Thank you for reporting the issue. The fix will be added in version 6.6.3-4 and later.
