### ISSUE TITLE
poppler's pdftocairo version 24.09.0 runs out of memory

### ISSUE THREAD

**Issue by dustwanderer** [msys2/MINGW-packages#22220]
### Description / Steps to reproduce the issue

`pdftocairo.exe -pdf "original.pdf" "corrected.pdf"`

### Expected behavior

`pdftocairo.exe` corrects a defective "original.pdf" archive into a new "corrected.pdf" archive without errors.

### Actual behavior

"cairo error: out of memory"
A new "corrected.pdf" is created, but "Acrobat 3D 8" can not open it, Acrobat claims that the archive is damaged and can't be repaired. 

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
I think you should report the issue to the upstream, I mean poppler developers. MSYS2 just packages it.

**Comment by Biswa96** [comment]
I can not reproduce the issue with a test pdf file. The new pdf file can be opened in okular without any error.

**Comment by MehdiChinoune** [comment]
The issue was reported to poppler from a Linux user https://gitlab.freedesktop.org/poppler/poppler/-/issues/1521

**Comment by Biswa96** [comment]
I can not reproduce the issue in ArchLinux either. I have commented that in the poppler issue.
