### ISSUE TITLE
[osgearth] The newest mingw-w64-clang-x86_64-osgearth is broken due to the updated version of sdplog package

### ISSUE THREAD

**Issue by ninepillars** [msys2/MINGW-packages#22229]
### Description / Steps to reproduce the issue

The updated package of spdlog (version 1.14.1-1)，has different export symbols other than old version, osgearth depends on the old symbols, and cannot run anymore...

### Expected behavior

run osgearth_version got version message
run osgearth_view got an earth scene.

### Actual behavior

run osgearth_version got nothing
run osgearth_view got got nothing

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
I don't thin the breakage was due spdlog update because package-grokker shows no symbols was removed.
https://github.com/msys2/MINGW-packages/actions/runs/10889783843/job/30217376398?pr=21941

**Comment by MehdiChinoune** [comment]
osgearth was updated to 3.7 and the issue was fixed. both osgearth_version and osgearth_viewer work.
