### ISSUE TITLE
C:\msys64\ucrt64\bin\mkvtoolnix-gui.exe fails to open

### ISSUE THREAD

**Issue by dustwanderer** [msys2/MINGW-packages#22307]
### Description / Steps to reproduce the issue

`mkvtoolnix-gui.exe` does not generate a graphic window. If launched from Windows, it generates an error message. If launched from bash, I do not see any error message, but the expected graphic window does not appear, either

### Expected behavior

A graphic window opening

### Actual behavior

A pop-up error message in Spanish. Translated to:
Can't find entry point of procedure _Z12qt_blurImageP8QPainterR6QImagedbbi in the dynamic link library C:\msys64\ucrt64\bin\mkvtoolnix-gui.exe.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
The package is being rebuilt. Please wait.

**Comment by MehdiChinoune** [comment]
Should be fixed now.
