### ISSUE TITLE
Qt Creator need to be rebuilt after Qt 6's every major upgrade

### ISSUE THREAD

**Issue by wszqkzqk** [msys2/MINGW-packages#22301]
### Description / Steps to reproduce the issue

Qt Creator uses the private API of Qt 6, so it needs to be rebuilt after each Qt 6 upgrade.

Otherwise, if you run `qtcreator` it will fail because it unable to locate program entry point on dlls.

Also, our upstream, Arch Linux, is maintaining **[a list of packages](https://gitlab.archlinux.org/archlinux/kde-build/-/blob/master/package-list/qt6/rebuild.list)** that need to be rebuilt after Qt 6 upgrade. Some of them are also in MSYS2's repo, so we may reuse some part of this list.

At least, there are following packages need to be rebuilt:

* [mingw-w64-gammaray](https://packages.msys2.org/base/mingw-w64-gammaray)
* [mingw-w64-pyqt6](https://packages.msys2.org/base/mingw-w64-pyqt6)
* [mingw-w64-qt-creator](https://packages.msys2.org/base/mingw-w64-qt-creator)

### Expected behavior

Rebuild, and Qt Creator works again.

### Actual behavior

Unable to locate program entry point on dlls.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-26100

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANGARM64

**Comment by Biswa96** [comment]
CI shows which packages need to be rebuilt https://github.com/msys2/MINGW-packages/actions/runs/11492344868/job/31996151285?pr=22280#step:3:444

pyside6 update is in queue. The other 3 are in a pull request now.

**Comment by wszqkzqk** [comment]
> CI shows which packages need to be rebuilt https://github.com/msys2/MINGW-packages/actions/runs/11492344868/job/31996151285?pr=22280#step:3:444
> 
> pyside6 update is in queue. The other 3 are in a pull request now.

Sorry, I just noticed.

Is it possible for us to automate this rebuild? Arch Linux has [tools](https://gitlab.archlinux.org/archlinux/kde-build/) specifically for this situation.

**Comment by Biswa96** [comment]
Which part need to be automated? CI is already showing which packages need to be rebuild. In the end, human touch is required to fix the build or runtime issue.

**Comment by wszqkzqk** [comment]
> Which part need to be automated? CI is already showing which packages need to be rebuild. In the end, human touch is required to fix the build or runtime issue.

I mean to automatically issue a rebuild of these packages (additional manually maintained packages that need to be built) when Qt 6 is upgraded. The reason these packages need to be rebuilt is not soname changes (more like "runtime issue") so it seems that CI can't figure them out directly. This may help prevent maintainers from forgetting.

**Comment by Biswa96** [comment]
> The reason these packages need to be rebuilt is not soname changes (more like "runtime issue")

Both file name changes and API changes are checked in CI, see https://github.com/jeremyd2019/package-grokker
