### ISSUE TITLE
Build meson-python for mingw32

### ISSUE THREAD

**Issue by ankith26** [msys2/MINGW-packages#22327]
### Package name

meson-python

### For which environment do you need the package?

MINGW32

### Provide a brief description why you need this package in the selected environment

I was using this package in one of my CI builds, which started failing recently.

I understand that this is a result of the commit https://github.com/msys2/MINGW-packages/commit/100f9bad8f3e7f4a5f3dfed12d949a75e14c5e48 and I was wondering if the bit that is removing mingw32 support can be reverted, or if there is a reason for the removal that I am not aware of (in which case I would have to rewrite my CI config)

### Are you willing to submit a PR?

Yes

**Comment by MehdiChinoune** [comment]
The reason is that mingw32 are being gradually dropped.
You seem only using mingw32 only for testing.
