### ISSUE TITLE
[poppler] update to 24.10.

### ISSUE THREAD

**Issue by sunderme** [msys2/MINGW-packages#22328]
### Package name

poppler

### New version number

24.10.0

### Other information that may be useful

I have updated and run PKGBUILD in my fork.
The problem is that inkscape does not build anymore as poppler uses now smartpointers for some functions.
What is the policy here ?

### Are you willing to submit a PR?

yes

**Comment by sunderme** [comment]
and the corresponding inkscape bug: https://gitlab.com/inkscape/inkscape/-/merge_requests/6782

**Comment by lazka** [comment]
> What is the policy here ?

Wait a bit, andd/or backport build fixes.

Feel free to open a PR, so we can see which other packages are affected (poppler usually bumps their DLL versions for changes)
