### ISSUE TITLE
Python mingw64 stdin error with subprocess pipe

### ISSUE THREAD

**Issue by gedare** [msys2/MINGW-packages#22354]
### Description / Steps to reproduce the issue

1. Create a subprocess with `subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE)` in the usual way.
2. Repeatedly write to the pipe's stdin and read from its stdout.
3. At some point the pipe's stdin is unable to be written for no apparent reason. This seems to be a bug.

Reduced test case: [test.txt](https://github.com/user-attachments/files/17578453/test.txt)

Compare the behavior with the msys2 python:
```
$ /usr/bin/python -V
Python 3.12.7
$ /usr/bin/python test.py
```
see Expected behavior

vs. failure on readline with mingw Python:
```
$ /mingw64/bin/python.exe -V
Python 3.11.10
$ /mingw64/bin/python.exe test.py
```
see Actual behavior

### Expected behavior

0
b'test\n'
1
2
b'test\n'
...
17
b'test\n'
18
b'test\n'
19
b'test\n'
20
b'test\n'

### Actual behavior

0
1
b'test\r\n'
Traceback (most recent call last):
  File "<string>", line 9, in <module>
OSError: [Errno 22] Invalid argument
b''
Traceback (most recent call last):
  File "C:/msys64/home/gedare/test.py", line 34, in <module>
    proc.stdin.flush()
OSError: [Errno 22] Invalid argument

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-26100

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

**Comment by raedrizqie** [comment]
I cannot reproduce this error on the latest python 3.12

**Comment by gedare** [comment]
> I cannot reproduce this error on the latest python 3.12

Updating to Python 3.12 fixes the issue.
