### ISSUE TITLE
zed: `zed-download-pc-windows-gnu-assets.patch` breaks tools donwload

### ISSUE THREAD

**Issue by mati865** [msys2/MINGW-packages#22511]
### Description / Steps to reproduce the issue

Neither rust-analyzer nor deno provide windows-gnu artifacts, so [the patch](https://github.com/msys2/MINGW-packages/blob/a2d39f8399595c7e33642f52d6020851ca39b236/mingw-w64-zed/zed-download-pc-windows-gnu-assets.patch) is conceptually wrong.

### Expected behavior

No errors.

### Actual behavior

An error when opening a Rust project:
```
Language server error: rust-analyzer

no asset found matching `"rust-analyzer-x86_64-pc-windows-gnu.gz"`
-- stderr--
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [x] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANGARM64

**Comment by ognevny** [comment]
oops, I wanted to remove this patch actually, thanks for catch

**Comment by ognevny** [comment]
you can download rust-analyzer from msys2. it should be available from $PATH to work on Zed

**Comment by mati865** [comment]
I know, just noticed the patch is wrong.

**Comment by ognevny** [comment]
also in zed 0.162.x rust-analyzer will be downloaded in a bit another way: https://github.com/zed-industries/zed/commit/181c3724aa99e67ebc5f8147dce8d6ee2f77276d
