### ISSUE TITLE
[paraview] does not start

### ISSUE THREAD

**Issue by podsvirov** [msys2/MINGW-packages#22536]
### Description / Steps to reproduce the issue

Try to start

### Expected behavior

Start

### Actual behavior

Not started

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANGARM64

**Comment by MehdiChinoune** [comment]
tracking the source if the error:
https://gitlab.kitware.com/paraview/paraview/-/blob/5bf1112f/Remoting/Application/vtkInitializationHelper.cxx#L200
https://github.com/protocolbuffers/protobuf/blob/a422268d/src/google/protobuf/stubs/common.h#L72
https://github.com/protocolbuffers/protobuf/blob/a422268d/src/google/protobuf/stubs/common.cc#L44

Should we patch protobuf or paraview?

**Comment by podsvirov** [comment]
@MehdiChinoune thanks for fix this for `CLANG64`!
But looks like for `UCRT64` we have `ABI` problem with `libgdal-35.dll`. I was try to rebuild, but get errors for [CLANG64](https://github.com/podsvirov/MINGW-packages/actions/runs/11840425563/job/32994219923)...

**Comment by MehdiChinoune** [comment]
That's another issue, most probably caused by recent update to LLVM-19.
We already rebuilt paraview against gdal-3.9 in https://github.com/msys2/MINGW-packages/commit/afac7514.
and It was rebuilt many times after that https://github.com/msys2/MINGW-packages/commits/master/mingw-w64-paraview. I don't understand how did deduce that ABI breakage?

**Comment by MehdiChinoune** [comment]
You should backport https://gitlab.kitware.com/vtk/vtk-m/-/commit/674d370b3d021d6352045f09ce69f84c41e863cd if you want to rebuild paraview.

**Comment by podsvirov** [comment]
![paraview-fail](https://github.com/user-attachments/assets/6bbcf64b-2227-465f-80ee-9f04820f6514)

**Comment by MehdiChinoune** [comment]
I think It's gdal that should be rebuilt not paraview!
