### ISSUE TITLE
[imagemagick] /msys64 is for some reason automatically added to absolute output paths

### ISSUE THREAD

**Issue by lockie** [msys2/MINGW-packages#22544]
### Description / Steps to reproduce the issue

Call imagemagick e.g. like this:
```sh
magick icon.png /tmp/icon.ico
```

or even like this:
```sh
magick icon.png /icon.ico
```

### Expected behavior

The file is being output at the specified path.

### Actual behavior

Imagemagick prepends `/msys64` to the output path and of course fails to open it:

```
magick.exe: unable to open image '/msys64/tmp/icon.ico': No such file or directory @ error/blob.c/OpenBlob/3596.
```

```
magick.exe: unable to open image '/msys64/icon.ico': No such file or directory @ error/blob.c/OpenBlob/3596.
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19043

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

### Are you willing to submit a PR?

Possibly

**Comment by lazka** [comment]
I can't reproduce.

The most likely thing is that MSYS2 converts the path to a Windows path, so in reality you call `magick icon.png C:/msys64/tmp/icon.ico`. Why it errors out for you, or why it strips of the `C:`, at least in the error message, I don't know.

**Comment by lockie** [comment]
Here are steps to reproduce:

```sh
$ docker run -it ghcr.io/msys2/msys2-docker-experimental

## in docker container:

# pacman -Sy --noconfirm mingw-w64-ucrt-x86_64-imagemagick
# wget https://getsamplefiles.com/download/png/sample-1.png
# magick magick sample-1.png /tmp/test.ico
```

> Both your examples above are the same command, did you miss something there?

Ah, sorry, editorial mistake, fixed it.

**Comment by lockie** [comment]
I was told this kind of path conversion is [supreessible](https://stackoverflow.com/a/34386471/1336774), and indeed running

```sh
MSYS2_ARG_CONV_EXCL='*' magick sample-1.png /tmp/test.ico
```

solves the issue. Sorry for the fuss 😅

**Comment by lockie** [comment]
Oh, I was too quick to judge: it does not fail, but it does not produce the output file either 😞

**Comment by lockie** [comment]
I found that the file is written into `/z/tmp` in this case, which is kind of logical, but still inconvenient.
