### ISSUE TITLE
Does libscotch.dll from scotch-int64 and mingw-scotch-int64 packages really provide int64 interface?

### ISSUE THREAD

**Issue by ChessMastery** [msys2/MINGW-packages#22540]
### Description / Steps to reproduce the issue

I downloaded [mingw-w64-x86_64-mumps](https://packages.msys2.org/packages/mingw-w64-x86_64-mumps) package, and used it correctly with libscotch.dll from [mingw-w64-x86_64-scotch](https://packages.msys2.org/packages/mingw-w64-x86_64-scotch) package. Then I downloaded [mingw-w64-x86_64-scotch-int64](https://packages.msys2.org/packages/mingw-w64-x86_64-scotch-int64) and [mingw-w64-ucrt-x86_64-scotch-int64](https://packages.msys2.org/packages/mingw-w64-ucrt-x86_64-scotch-int64), and these packages also provide libscotch.dll, but when I replace old libscotch.dll with the one provided by these packages, mumps still works correctly. From the other hand, when I try to link "int64" libscotch.dll to 64-bit integer mumps, it return error -52 that means it thinks 32-bit scotch was provided. How should I check which functions does libscotch.dll export and are they 32-bit-int or 64-bit-int? 

### Expected behavior

Expected behaviour: I guess mumps-int32 should not work fine with scotch-int64.

### Actual behavior

Actual behaviour: mumps-int32 works fine with libscotch.dll obtained from scotch-in64 and ucrt-scotch-int64 packages.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 10 Pro 22H2

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
@3rav could you look into this issue please?

**Comment by mmuetzel** [comment]
Thank you for raising this probably long-standing issue. I wonder how it went unnoticed for so long.

Could you please check with the build artifacts from #22548 if this is fixed with that change?

**Comment by okhlybov** [comment]
It would also be nice to change package naming to scotch64 to be in line with other related packages.

**Comment by ChessMastery** [comment]
@mmuetzel , now [mingw-w64-x86_64-mumps](https://packages.msys2.org/packages/mingw-w64-x86_64-mumps) crushes and int64 mumps still returns -52 (I just copied obtained libscotch.dll to executable directory, will try other things a bit later).
P.S. first I could not execute BUILDPKG script so I run pacman -S patch and pacman -S make, then I could not compile so I run pacman -S bison and pacman -S flex.
![Screenshot_1](https://github.com/user-attachments/assets/40843b74-7b1a-461d-965c-12fd3a9ed75d)

**Comment by mmuetzel** [comment]
@ChessMastery: Thank you for testing.
You don't need to rebuild the package yourself. Instead, you can download the build artifacts from the PR by selecting it from the "Artifacts" dropdown on the "Checks" tab:
https://github.com/msys2/MINGW-packages/pull/22548/checks

After you downloaded the package, you can install it with `pacman -U mingw-w64-x86_64-scotch-7.0.5-1-any.pkg.tar.zst` (or `pacman -U mingw-w64-x86_64-scotch-int64-7.0.5-1-any.pkg.tar.zst` for the other one).

You might need to update your local installation first to have a compatible set of installed packages. For that, run `pacman -Syu` (repeatedly until you receive no more updates).

**Comment by mmuetzel** [comment]
Just to clarify: A program crash wouldn't surprise me if you try to use Scotch libraries with 64-bit indexing together with Mumps libraries with 32-bit indexing. (Or vice versa)
Afaict, MSYS2 doesn't distribute Mumps libraries with 64-bit indexing. Where did you get them from?

**Comment by okhlybov** [comment]
There is my WiP for mumps64 which seems to work by itself yet presumably triggers this bug.
https://github.com/okhlybov/MINGW-packages/tree/mumps64

**Comment by mmuetzel** [comment]
@okhlybov: Wouldn't you need to set `i64=1` (and/or `r64=1`? I don't know which of them actually correspond to the Fortran integer type used for indexing) somewhere in the make flags? I can't find that anywhere in your packaging rules. Without it, wouldn't the C-parts of Mumps still use 32-bit integers for indexing?

**Comment by mmuetzel** [comment]
Did you rebuild the 64-bit indexing Mumps after you updated to the new 64-bit indexing Scotch? Some headers were wrong in the 64-bit indexing Scotch package before #22548.

**Comment by ChessMastery** [comment]
Seems like it works fine now, thanks for fixing it so fast.
