### ISSUE TITLE
Doxygen issue when building

### ISSUE THREAD

**Issue by MimoKar** [msys2/MINGW-packages#22570]
### Description / Steps to reproduce the issue

Try to build with command:

`makepkg-mingw -sCLf`

### Expected behavior

Build will be finished properly.

### Actual behavior

Doxygen is throwing this error:

`error: Could not create output directory /home/xxxx/gitrepos/MINGW-packages/mingw-w64-libheif/src/build-MINGW64/C:/msys64/home/xxxx/gitrepos/MINGW-packages/mingw-w64-libheif/src/build-MINGW64/apidoc//html`

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-27749

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

**Comment by lazka** [comment]
I guess this is about building libheif? I can't reproduce here.

It complains about missing graphviz though.

**Comment by MimoKar** [comment]
> I can reproduce the issue with msys doxygen but **not** with mingw doxygen. Please use the mingw doxygen if you want.

How to switch ? I am a newbie in mingw environment...

**Comment by Biswa96** [comment]
Just use `pacman -S $MINGW_PACKAGE_PREFIX-doxygen` command to install mingw doxygen package.

**Comment by MimoKar** [comment]
Thanks.
Now working.

**Comment by MimoKar** [comment]
Thanks.
Now working.
