### ISSUE TITLE
Some win32 packages are not included in the mingw32.db

### ISSUE THREAD

**Issue by jack6th** [msys2/MINGW-packages#22577]
### Description / Steps to reproduce the issue

pacman -Syu
pacman -Ss i686-zeromq

The mingw32 zeromq package exists but it is not included in the mingw32.db.
https://repo.msys2.org/mingw/mingw32/mingw-w64-i686-zeromq-4.3.5-3-any.pkg.tar.zst
https://repo.msys2.org/mingw/mingw32/mingw32.db.tar.zst

### Expected behavior

output mingw32/mingw-w64-i686-zeromq 4.3.5-3

### Actual behavior

output nothing.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-6.1-7601

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> MSYS_NT-6.1-7601

Windows 7 is not supported https://www.msys2.org/news/#2023-01-15-dropping-support-for-windows-7-and-80
