### ISSUE TITLE
mingw64 is missing for qt6-graphs package

### ISSUE THREAD

**Issue by f-zl** [msys2/MINGW-packages#22667]
In the qt6-graphs package, `mingw_arch=('ucrt64' 'clang64' 'clangarm64')`, mingw64 is missing. Is there a reason for this, or is it a mistake? Thanks very much.

**Comment by Biswa96** [comment]
qt6-graphs for mingw64 was not present since it was added in 130416b0e26b0e65ffa7f72357cce2bb685871d1 commit. Could you switch to ucrt64 or clang64 environment?

**Comment by MehdiChinoune** [comment]
Use UCRT64 environment.
