### ISSUE TITLE
[mingw-w64-premake4] update to 4.4-beta5

### ISSUE THREAD

**Issue by chadchoi** [msys2/MINGW-packages#22673]
### Package name

mingw-w64-premake4

### New version number

4.4-beta5

### Other information that may be useful

https://github.com/premake/premake-4.x/issues/18

**Comment by lazka** [comment]
We normally don't update to non-stable releases without a reason. But I see that this is ancient and never got a release, so I see why we might want it.

What motivated you to create the issue?

**Comment by chadchoi** [comment]
I think the latest is always better.

**Comment by chadchoi** [comment]
Well, Debian is still packaging premake 4.3-1, so it seems they think premake 4.4-beta5 is not worth it.

https://packages.debian.org/bookworm/premake4
