### ISSUE TITLE
Add mingw-w64-premake4-stable

### ISSUE THREAD

**Issue by chadchoi** [msys2/MINGW-packages#22674]
### Package name

mingw-w64-premake4-stable

### Brief description of package

Friendly Premake4 fork

### URL for package's homepage

https://github.com/assarbad/premake-4.x-stable

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANGARM64

**Comment by MehdiChinoune** [comment]
MSYS2 doesn't package forks unless the main project is abandoned.
