### ISSUE TITLE
there is not symbol exported in jaylink

### ISSUE THREAD

**Issue by wre40** [msys2/MINGW-packages#22710]
### Description / Steps to reproduce the issue

when i use openocd, it failed to start.  After i use gendef to export jaylink 's symbol, i found nothing.

### Expected behavior

export jaylink 's symbol

### Actual behavior

openocd failed to start

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [ ] CLANGARM64

**Comment by raedrizqie** [comment]
I tried rebuilding openocd, but clang64 failed to build.. ucrt64 and mingw64 compiles successfully though

**Comment by wre40** [comment]
problem happened on libjaylink. After I changed a defination in libjaylink.h which controls function visability , problem solved. But according to raedrizqie, I think that it is caused by clang. Maybe clang handle visability of function by mistake

**Comment by raedrizqie** [comment]
ah.. clang sets `visibility=hidden` is it?

**Comment by wre40** [comment]
I think that can explain why after i add __attribute__ ((visibility ("default"))) ahead of functions in libjaylink.h, i could compile libjaylink with symbols exported.  And because you sucessfully compile openocd in ucrt64 and mingw64,so i think maybe clang sets visibility=hidden by mistake
