### ISSUE TITLE
Add Gnirehtet

### ISSUE THREAD

**Issue by doronbehar** [msys2/MINGW-packages#22718]
### Package name

gnirehtet

### Brief description of package

This project provides reverse tethering over adb for Android: it allows devices to use the internet connection of the computer they are plugged on. It does not require any root access (neither on the device nor on the computer). It works on GNU/Linux, Windows and Mac OS.

### URL for package's homepage

https://github.com/Genymobile/gnirehtet

### Provide a basic test case to validate the package's functionality.

Simply run the binary.

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

### Are you willing to submit a PR?

If I were using Windows enough, then yes, perhaps.

**Comment by Biswa96** [comment]
The project is not being maintained anymore. https://github.com/Genymobile/gnirehtet/blob/1eb2e58bc91e268dba62561d11e3bebd9b100883/README.md?plain=1#L16-L17
