### ISSUE TITLE
hdf5: pkg-config file incorrect for static linking

### ISSUE THREAD

**Issue by svillemot** [msys2/MINGW-packages#22712]
### Description / Steps to reproduce the issue

Trying to create a static executable linked against HDF5 using the pkg-config system fails (in the MINGW64 environment).

For example, using [h5_write.c](https://raw.githubusercontent.com/HDFGroup/hdf5/develop/examples/h5_write.c):

```
$ gcc -static h5_write.c $(pkg-config --static --libs hdf5) -o h5_write
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lzlib-static: No such file or directory
collect2.exe: error: ld returned 1 exit status
```

### Expected behavior

Static linking should work with `pkg-config`.

### Actual behavior

The problem is that the `hdf5.pc` file contains invalid `-lzlib-static` flags in the `Libs.private` field:
```
$ pkg-config --static --libs hdf5
-lhdf5 -lzlib-static -lcurl -lws2_32 -lbcrypt -lcrypto -lz -lwldap32 -ladvapi32 -lcrypt32 -lssl -lbrotlidec -lbrotlicommon -lzstd -lnghttp2 -lnghttp3 -lpsl -lunistring -lws2_32 -liconv -lidn2 -L/mingw64/lib -liconv -L/mingw64/lib -lunistring -lssh2 -lws2_32 -L/mingw64/lib -lssl -L/mingw64/lib -L/mingw64/lib -lcrypto -lws2_32 -lgdi32 -lcrypt32 -lz
```

An easy fix would be to clear the `Libs.private` field and rather add `zlib` to the `Requires.private` field.

Note that this is a recent regression. Static linking used to work after #18554 was fixed.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
The issue was fixed upstream by https://github.com/HDFGroup/hdf5/commit/e64e1ea8
I will try to backport it.
