### ISSUE TITLE
Add [libgig]

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MINGW-packages#22740]
### Package name

libgig

### Brief description of package

libgig is a C++ library for loading, modifying existing and creating new GigaStudio/Gigasampler (.gig) files and DLS (Downloadable Sounds) Level 1/2 files, KORG sample based instruments (.KSF and .KMP files), SoundFont v2 (.sf2) files and AKAI sampler data

### URL for package's homepage

http://www.linuxsampler.org/libgig/

### Provide a basic test case to validate the package's functionality.

rifftree

This is a standard autotools package ./configure &make&make install

### MINGW environments where you need the package

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> libgig is a C++ library for loading, modifying existing and creating new GigaStudio/Gigasampler (.gig) files

What are those files?

**Comment by Kreijstal** [comment]
> > libgig is a C++ library for loading, modifying existing and creating new GigaStudio/Gigasampler (.gig) files
> 
> What are those files?

The .gig files are sample-based instrument files used by GigaSampler and GigaStudio, digital sampling applications initially developed by Tascam (formerly Nemesys Music Technology). These files contain audio samples and associated metadata used to emulate instruments in music production. The .gig format was among the first to provide extensive support for realistic and detailed sample-based instrument playback.
https://www.soundlib.com/gplayer/
http://doc.linuxsampler.org/Gigedit/
