### ISSUE TITLE
Add mingw-w64-ucrt-clang-x86_64-toolchain or mingw-w64-ucrt-x86_64-clang-toolchain

### ISSUE THREAD

**Issue by ssrkaze** [msys2/MINGW-packages#22805]
### Package name

mingw-w64-ucrt-clang-x86_64-toolchain

### Brief description of package

I can find a group named `mingw-w64-clang-i686-toolchain`, `mingw-w64-ucrt-x86_64-arm-none-eabi-toolchain`  or `mingw-w64-ucrt-x86_64-toolchain`, but i can not find a group named `mingw-w64-ucrt-clang-x86_64-toolchain` or `mingw-w64-ucrt-x86_64-clang-toolchain`. Would you like to add this group? Or why there is no such group? Thank you.

### MINGW environments where you need the package

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
> but i can not find a group named `mingw-w64-ucrt-clang-x86_64-toolchain` or `mingw-w64-ucrt-x86_64-clang-toolchain`

No such package group is required. Just install clang.
