### ISSUE TITLE
[raylib] raylib defaults with opengl-3.0

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MINGW-packages#22857]
### Description / Steps to reproduce the issue

This is not bad but some people have drivers that are not there yet, can't we use fallback on aangle instead?
If it runtime determines the opengl version can't we make it so that it fallbacks on aangle?

simply try to build https://github.com/raysan5/raylib-game-template.git

### Expected behavior

raylib programs should run 

### Actual behavior

while trying a raylib build
$ ./build2/raylib-game-template/raylib-game-template.exe
INFO: Initializing raylib 5.5
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Trying to enable MSAA x4
WARNING: GLFW: Error: 65542 Description: WGL: The driver does not appear to support OpenGL
Segmentation fault

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANGARM64

**Comment by MehdiChinoune** [comment]
you should report the issue to raylib developers.
