### ISSUE TITLE
mingw-w64-x265 is not 4.1 as the package implies

### ISSUE THREAD

**Issue by jamrial** [msys2/MINGW-packages#22931]
### Package name

mingw-w64-x265

### New version number

4.1+1-1d117be

### Other information that may be useful

The tarball located in https://bitbucket.org/multicoreware/x265_git/get/4.1.tar.gz fetched by the PKGBUILD is in fact a snapshot of 4.0 (changeset 6318f22), probably by mistake.

An actual snapshot of 4.1 (changeset 1d117be) is in https://bitbucket.org/multicoreware/x265_git/downloads/x265_4.1.tar.gz, but it may be better to instead fetch directly from the git tag, rather than a tarball.

**Comment by lazka** [comment]
Thanks, I remember not finding any release tarballs back then for 3.4 (they still are not available), so moved to downloading tag then, but looks that starting with 3.5 they came back.

I wonder why downloading the tag got a different version.

**Comment by lazka** [comment]
Ah, I see now. The correct version was built, upstream just forgot to update the version information: https://bitbucket.org/multicoreware/x265_git/src/4.1/x265Version.txt and did it one commit later: https://bitbucket.org/multicoreware/x265_git/commits/branch/Release_4.1
