### ISSUE TITLE
pacman trust error

### ISSUE THREAD

**Issue by fspeech** [msys2/MINGW-packages#240]
Suddenly pacman no longer trusts:

```
(1/1) checking keys in keyring                     [######################] 100%
downloading required keys...
:: Import PGP key 2048D/A47D45A1, "Alexey Pavlov (Alexpux) <alexpux@gmail.com>", created: 2013-11-10? [Y/n] y
(1/1) checking package integrity                   [######################] 100%
error: mingw-w64-x86_64-libpng: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/mingw-w64-x86_64-libpng-1.6.12-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] n
```

It was working fine yesterday. I removed old /etc/pacman.d/gnupg and did pacman-key --refresh-keys. I am still getting the same `unknown trust` message. Do I need to disable the trust check? This was working fine before today.

**Comment by ogamespec** [comment]
ошибка: mingw32: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
ошибка: mingw64: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
ошибка: msys: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
ошибка: база данных 'mingw32' недействительна или повреждена (неверная или поврежденная база данных(PGP-подпись))
ошибка: база данных 'mingw64' недействительна или повреждена (неверная или поврежденная база данных(PGP-подпись))
ошибка: база данных 'msys' недействительна или повреждена (неверная или поврежденная база данных(PGP-подпись))

Без ебли хоть один линуксовый пакет устанавливается нормально? :)

**Comment by Biswa96** [comment]
Run those commands provided in 2nd comment.

**Comment by ogamespec** [comment]
>> Run those commands provided in 2nd comment.

Complains about gpg-agent.

This helps:

https://www.linux.org.ru/forum/general/7904623

/etc/pacman.conf => SigLevel = Never.

**Comment by StarWolf3000** [comment]
@ogamespec It's not a pacman issue, it's an issue with your system configuration. Add gpg-agent or MSYS2 installation to exclusion list/white list in your anti-virus software.
