### ISSUE TITLE
Error compiling libVirt with Hyper-V support using MSYS2/MingW

### ISSUE THREAD

**Issue by ivan-alfonso** [msys2/MINGW-packages#2437]
We got an error when we try to compile and install a most-recent version of libvirt with support for hyperv in windows using MSYS2/MingW. 

We are trying to compile/install `libvirt-3.1.0` using the patch at https://github.com/Alexpux/MINGW-packages.git. 

  - Compiling without any special configuration is ok (We got drivers for Test and Remote)
  - Compiling with the `--with-hyperv` we got an error caused by a missing `openwsman` 
  - Then, we have tried to compile `openwsman` but we got other compiling errors.

We know that Matthias Bolte had scripts for compiling libvirt and a fork repository for OpenWsMan. However, we cannot compile the code with these patches.

  - Can you suggest some solution to solve this problem?.

**Comment by mingwandroid** [comment]
> but we got other compiling errors

What are these errors?

> Can you suggest some solution to solve this problem?.

You need to provide complete logs, we can't and shouldn't try to hack into your computer to find them!

**Comment by ivan-alfonso** [comment]
We are trying to compile the libvirt with hyper-v support:

## librvirt

After we installed MSYS2/MingW, we compiled the libvirt using the patches provided in MINGW-packages

```
$ pacman -S base-devel mingw-w64-x86_64-toolchain git
$ git clone https://github.com/Alexpux/MINGW-packages.git
$ cd MINGW-packages/mingw-w64-libvirt
$ MINGW_INSTALLS=mingw64 makepkg-mingw -s
```

At this point, the resulting libvirt works with the default “Test” driver. We ran again the `configure` process to add the support for hyper-v but here we got an error caused by the non-installed openwsman library.

```
$ cd /src/libvirt-3.1.0
$ ./configure --with-hyperv
  :
checking for OPENWSMAN... no
 :
configure: error: openwsman is required for the Hyper-V driver
```

## openwsman fork

We tried to compile the openwsman using [the fork created by Mathias Bolte](https://github.com/photron/openwsman).

```
$ cd openwsman
$ mkdir build
$ cd build
$ cmake -D USE_PAM=NO -DBUILD_BINDINGS=NO -DBUILD_LIBCIM=NO -DBUILD_RUBY=NO -DBUILD_JAVA=NO -DBUILD_PYTHON=NO -DBUILD_CSHARP=NO -DBUILD_PERL=NO -DENABLE_IPV6=NO ..
$ make
```

However, the compiler produces errors related to the (we assume) generated header files.

```
Scanning dependencies of target wsman_curl_client_transport
[  1%] Building C object src/lib/CMakeFiles/wsman_curl_client_transport.dir/wsman-client-transport.obj
In file included from C:/msys64/home/ja.chavarriaga908/openwsman/src/lib/wsman-client-transport.c:37:0:
C:/msys64/home/ja.chavarriaga908/openwsman/build/wsman_config.h:33:5: error: #if with no expression
#if
    ^
In file included from C:/msys64/home/ja.chavarriaga908/openwsman/include/u/os.h:10:0,
                from C:/msys64/home/ja.chavarriaga908/openwsman/include/u/log.h:13,
                from C:/msys64/home/ja.chavarriaga908/openwsman/include/u/carpal.h:18,
                from C:/msys64/home/ja.chavarriaga908/openwsman/include/u/libu.h:12,
                from C:/msys64/home/ja.chavarriaga908/openwsman/src/lib/wsman-client-transport.c:48:
C:/msys64/home/ja.chavarriaga908/openwsman/include/u/gettimeofday.h:18:8: error: redefinition of 'struct timezone'
struct timezone
       ^~~~~~~~
 :
```

The complete log 
[error log -- openwsman fork.txt](https://github.com/Alexpux/MINGW-packages/files/979697/error.log.--.openwsman.fork.txt)


## openwsman

We also tried to use the [official version of OpenWSMan]()

```
$ cd openwsman
$ mkdir build
$ cd build
$ cmake -D USE_PAM=NO -DBUILD_BINDINGS=NO -DBUILD_LIBCIM=NO -DBUILD_RUBY=NO -DBUILD_JAVA=NO -DBUILD_PYTHON=NO -DBUILD_CSHARP=NO -DBUILD_PERL=NO -DENABLE_IPV6=NO ..
$ make
```

But we get similar errors:

```
Scanning dependencies of target wsman_curl_client_transport
[  1%] Building C object src/lib/CMakeFiles/wsman_curl_client_transport.dir/wsman-client-transport.obj
In file included from C:/msys64/home/user/openwsman/src/lib/wsman-client-transport.c:37:0:
C:/msys64/home/user/openwsman/build/wsman_config.h:33:5: error: #if with no expression
#if
    ^
In file included from C:/msys64/home/user/openwsman/include/u/os.h:10:0,
                from C:/msys64/home/user/openwsman/include/u/log.h:13,
                from C:/msys64/home/user/openwsman/include/u/carpal.h:18,
                from C:/msys64/home/user/openwsman/include/u/libu.h:12,
                from C:/msys64/home/user/openwsman/src/lib/wsman-client-transport.c:48:
C:/msys64/home/user/openwsman/include/u/gettimeofday.h:18:8: error: redefinition of 'struct timezone'
struct timezone
       ^~~~~~~~
 :
```

The complete log 
[error log -- openwsman.txt](https://github.com/Alexpux/MINGW-packages/files/979702/error.log.--.openwsman.txt)

**Comment by bgermann** [comment]
openwsman should be buildable with version 2.7.1

**Comment by Biswa96** [comment]
@bgermann Thank you for fixing the issues in upstream https://github.com/Openwsman/openwsman/pull/151 ❤️
