### ISSUE TITLE
About osgearth for Qt

### ISSUE THREAD

**Issue by zebrainncu** [msys2/MINGW-packages#2518]
Hi Alexpux
I want to do something on Qt.
Here is the problem.
After I run pacman -S mingw-w64-x86_64-osgearth in msys2, I try to run 
cmd in Msys2
osgviewer /usr/share/osgearth/maps/openstreetmap.earth

result as below:
D:\msys64\mingw64\bin\osgviewer.exe: No data loaded
Error reading file D:/msys64/usr/share/osgearth/maps/openstreetmap.earth: read error (Could not find plugin to read objects from file "D:/msys64/usr/share/osgearth/maps/openstreetmap.earth".)

And I found the osgearth directory is Empty under /usr/share.

**Comment by Alexpux** [comment]
Mingw-w64 programs not install any files in /usr. You need look other folders

**Comment by zebrainncu** [comment]
Thanks a lot.

But I still have a problem.
$ osgviewer /mingw64/share/osgearth/maps/openstreetmap.earth
D:\msys64\mingw64\bin\osgviewer.exe: No data loaded
Error reading file D:/msys64/mingw64/share/osgearth/maps/openstreetmap.earth: read error (Could not find plugin to read objects from file "D:/msys64/mingw64/share/osgearth/maps/openstreetmap.earth".)

==>Could not find plugin to read objects 
How to do it?

Thanks

**Comment by zebrainncu** [comment]
I think about osgearth
the command "pacman -S mingw-w64-x86_64-osgearth" can't  build osgearth data.
Due to  the osgearth directory is nothing on /mingw64/share.

**Comment by MehdiChinoune** [comment]
Closing due the inactivity and not describing the issue.
