### ISSUE TITLE
Bizarre error with latest GCC-Libs

### ISSUE THREAD

**Issue by BrisingrAerowing** [msys2/MINGW-packages#2579]
I am trying to do a build of LuaSec, and for some reason the shared libgcc does not export the symbol ___chkstk_ms, while the static libgcc does. This causes the build to fail, as LuaSec's internal luasocket requires that symbol.

GCC 6.3.0-3 x86_64

**Comment by lazka** [comment]
Is this still an issue?

**Comment by BrisingrAerowing** [comment]
No clue. I haven’t tried building it lately. I’ll go ahead and close this for now.

**Comment by lazka** [comment]
ok, thanks!
