### ISSUE TITLE
MinGW32 packages are linked with LIBGCC_S_DW2-1.DLL

### ISSUE THREAD

**Issue by HenrikHolst** [msys2/MINGW-packages#2600]
The MingW32 packages are linked with LIBGCC_S_DW2-1.DLL while the MingW64 are not. I.e I installed "mingw32/mingw-w64-i686-zlib" and "mingw64/mingw-w64-x86_64-zlib" on a 64-bit MSYS2 installation and if I drag "C:\msys64\mingw32\bin\zlib1.dll" to Dependency Walker then it shows that  LIBGCC_S_DW2-1.DLL is linked with it while "C:\msys64\mingw64\bin\zlib1.dll" does not.

The same issue was noticed for other libraries such i.e OpenSSL so I assume that the entire MingW32 distribution have been linked with this library by accident.

**Comment by nak5124** [comment]
not by accident but by design

**Comment by Alexpux** [comment]
@HenrikHolst look at https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gcc/0015-Force-linking-to-libgcc_s_dw2-1.dll-deprecated.patch

**Comment by HenrikHolst** [comment]
I'm having a hard time understanding that patch but why is this done deliberatly with the binary packages supplied by pacman for the 32-bit build but not the 64-bit builds? Sounds really strange to require this particular GCC library to be bundled when distributing 32-bit builds but not 64-bit builds?!

**Comment by Alexpux** [comment]
@HenrikHolst, 64-bit build have different GCC library - libgcc_seh. Patch created to solve 32 bit programs crashes. DWARF exceptions have some troubles.

**Comment by HenrikHolst** [comment]
Ok, and libgcc_seh is then statically linked since it does not show up in the dependy walker (or ldd) on the 64-bit binaries and libraries?

Is this something that happened with newer versions of GCC? Because I previously used the TDM-GCC (http://tdm-gcc.tdragon.net/) and it would create 32-bit binaries and libraries that didn't link with this library. I'm currently moving our Windows builds over from TDM-GCC to MSYS2.

However, DWARF Exceptions, should they not only affect C++ code? All the binaries that I've looked at and compiled have been pure C.

**Comment by Alexpux** [comment]
@HenrikHolst libgcc_seh not linked statically, you misunderstanding patch for GCC

**Comment by HenrikHolst** [comment]
So the patch you linked where for GCC? But even then, C does not have exceptions so why are pure C (32-bit) packages linked with DW2? Excuse my confusion here :)

**Comment by MehdiChinoune** [comment]
This is expected. mingw32 default to dw2 exception handling while mingw64 default to seh.
