### ISSUE TITLE
Enchant: libenchant_zemberek.dll installed in $prefix/lib/bin/

### ISSUE THREAD

**Issue by eht16** [msys2/MINGW-packages#2632]
For some reason, `libenchant_zemberek.dll` is installed in $prefix/lib/bin/ which is a weird place for a library:
```
$ ll /mingw32/lib/bin/
total 24K
-rwxr-xr-x 1 enrico None 22K Apr  7 06:03 libenchant_zemberek.dll
```

Even more confusing because Zemberek is disabled in https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-enchant/PKGBUILD#L59 ?

**Comment by revelator** [comment]
ghc also leaves a few files there, as long as runtime paths point to that location it should not be a problem but yeah its a bit messy :). Strange that it installs the library if disabled though.

**Comment by lazka** [comment]
That's no longer the case: https://packages.msys2.org/package/mingw-w64-i686-enchant?repo=mingw32

-> closing
