### ISSUE TITLE
cegui problems

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#2662]
Finally got around building it, sadly its not quite working since there are a few pitfalls. Ogre render does not work it relies on an older version which code has been changed rather extensively so i had to disable that, also the SDL2 framework produces link errors with the current SDL2 package so that one had to go as well.
Now it builds but i had to modify the build script cause it was using windows paths for the CMAKE_INSTALL_PREFIX which caused problems with pacman because the path to the pkg directory ended up being a mile long windows path :( so i changed it to use posix paths, but the samples do not work because it looks for the datadir in the source folder ?!? and again uses windows paths even if explicitly told not to. So i removed building samples as well since there is no easy workaround, and fixing it would probably require hacking the build system to use the linux setup ad some hackery with locating the datadir folder correctly.  it also seems to be a rather old version of cegui since the latest upstream version allready has support for the current ogre version.

**Comment by revelator** [comment]
Disabled ogre and Irrlicht renderers none of them work without patching.
Disabled SDL2 framework (needs library reordering).
Fixed path handling to follow same procedure as the linux version.
Ugly hack used to coerce the package build script to put the resulting builds in the correct folder for installation (windows paths and pacman = disaster).

`diff -urN cegui-0.8.7.old/samples/common/include/CEGUISamplesConfig.h.in cegui-0.8.7/samples/common/include/CEGUISamplesConfig.h.in
--- cegui-0.8.7.old/samples/common/include/CEGUISamplesConfig.h.in	2016-04-23 20:19:40.000000000 +0200
+++ cegui-0.8.7/samples/common/include/CEGUISamplesConfig.h.in	2017-07-21 03:45:12.088659500 +0200
@@ -45,11 +45,7 @@
 #ifndef CEGUI_SAMPLE_DATAPATH
 
 // Define the default place where samples will look for datafiles
-#if defined(_WIN32) || defined(__WIN32__)
-#   define CEGUI_SAMPLE_DATAPATH "${PROJECT_SOURCE_DIR}/datafiles"
-#else
-#   define CEGUI_SAMPLE_DATAPATH "${CMAKE_INSTALL_PREFIX}/${CEGUI_DATA_INSTALL_DIR}"
-#endif
+#define CEGUI_SAMPLE_DATAPATH "${CMAKE_INSTALL_PREFIX}/${CEGUI_DATA_INSTALL_DIR}"
 
 #endif
 `
`# Maintainer: Alexey Pavlov <alexpux@gmail.com>

_realname=cegui
pkgbase=mingw-w64-${_realname}
pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
pkgver=0.8.7
pkgrel=1
pkgdesc="A free library providing windowing and widgets for graphics APIs/engines (mingw-w64)"
arch=('any')
url="http://cegui.org.uk"
license=("MIT")
#makedepends=('doxygen' 'gtk2' 'graphviz' 'irrlicht' 'glm' 'tolua++')
makedepends=("${MINGW_PACKAGE_PREFIX}-gcc"
             "${MINGW_PACKAGE_PREFIX}-pkg-config"
             "${MINGW_PACKAGE_PREFIX}-cmake"
             "${MINGW_PACKAGE_PREFIX}-doxygen"
             "${MINGW_PACKAGE_PREFIX}-python2"
             "mercurial")
depends=("${MINGW_PACKAGE_PREFIX}-tinyxml"
         "${MINGW_PACKAGE_PREFIX}-boost"
         "${MINGW_PACKAGE_PREFIX}-devil"
         "${MINGW_PACKAGE_PREFIX}-expat"
         "${MINGW_PACKAGE_PREFIX}-FreeImage"
         "${MINGW_PACKAGE_PREFIX}-freetype"
         "${MINGW_PACKAGE_PREFIX}-fribidi"
         "${MINGW_PACKAGE_PREFIX}-glew"
         "${MINGW_PACKAGE_PREFIX}-glfw"
         "${MINGW_PACKAGE_PREFIX}-glm"
         "${MINGW_PACKAGE_PREFIX}-irrlicht"
         "${MINGW_PACKAGE_PREFIX}-libxml2"
         "${MINGW_PACKAGE_PREFIX}-libiconv"
         "${MINGW_PACKAGE_PREFIX}-lua51"
         "${MINGW_PACKAGE_PREFIX}-ogre3d"
         "${MINGW_PACKAGE_PREFIX}-ois"
         "${MINGW_PACKAGE_PREFIX}-pcre"
         "${MINGW_PACKAGE_PREFIX}-SDL2"
         "${MINGW_PACKAGE_PREFIX}-tinyxml"
         #"${MINGW_PACKAGE_PREFIX}-tolua"
         "${MINGW_PACKAGE_PREFIX}-xerces-c"
         "${MINGW_PACKAGE_PREFIX}-zlib")
options=('staticlibs' 'strip')
source=("https://downloads.sourceforge.net/crayzedsgui/cegui-${pkgver}.tar.bz2"
        freetype.patch
        mingw-w64-fix.patch
        fix-finding-glew.patch
        fix-finding-directx.patch
        fix-finding-glfw3.patch
        fix-dxerr-libname.patch
		fix-mingw-samples.patch)
sha256sums=('b351e8957716d9c170612c13559e49530ef911ae4bac2feeb2dacd70b430e518'
            '83e84d862a195c61901b0dd53a1c47434b812fff15fb977f390a45f19dcc4a64'
            '31e666ea015b30b9ee939b69994255eacb2e75fa9dec86538715e4b9a026863a'
            '3aa712304267353afe103cd8efa5f6f7b87fa98423d77610716d15a425194f2e'
            '1ae821516efaeecce5b27579d5236b11b3eb8075d3e173d1b3b973e81c1ee22e'
            '181385b172f952265a0be6a96eccd0ab9d4cb8846f7e07cd5d5e5095a0a591a0'
            '4c22f176f0fa430eeaf2ac6b21d587c7e1f3c04d8d3c03e957a35a95f077531b'
            'ee29f5160b5af42c1b7a8c7c1ea29da52bccea27ec0991281581b98d4eb731a7')

prepare() {
  cd "${srcdir}/${_realname}-${pkgver}"
  #patch -p1 -i ${srcdir}/freetype.patch
  #patch -p1 -i ${srcdir}/mingw-w64-fix.patch
  patch -p1 -i ${srcdir}/fix-finding-glew.patch
  patch -p1 -i ${srcdir}/fix-finding-directx.patch
  #patch -p1 -i ${srcdir}/fix-finding-glfw3.patch
  patch -p1 -i ${srcdir}/fix-dxerr-libname.patch
  patch -p1 -i ${srcdir}/fix-mingw-samples.patch
}

build() {
  [[ -d "${srcdir}"/build-${CARCH} ]] && rm -rf ${srcdir}/build-${CARCH}
  mkdir "${srcdir}"/build-${CARCH}  && cd "${srcdir}"/build-${CARCH}

  export DXSDK_DIR=${MINGW_PREFIX}/${MINGW_CHOST}
  export CFLAGS="-I${MINGW_PREFIX}/include"
  export CXXFLAGS="-I${MINGW_PREFIX}/include"
  MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
  ${MINGW_PREFIX}/bin/cmake.exe \
    ../${_realname}-${pkgver} \
    -G"MSYS Makefiles" \
    -DCMAKE_INSTALL_PREFIX=$(cygpath -am ${MINGW_PREFIX}) \
    -DCEGUI_LIB_INSTALL_DIR=lib \
	-DCEGUI_BUILD_RENDERER_OGRE=FALSE \
	-DCEGUI_BUILD_RENDERER_IRRLICHT=FALSE \
    -DCEGUI_BUILD_PYTHON_MODULES=OFF \
	-DCEGUI_INSTALL_WITH_RPATH=TRUE \
	-DCEGUI_BUILD_APPLICATION_TEMPLATE_SDL2=FALSE
	make
}

package() {
  cd ${srcdir}/build-${CARCH}
  make DESTDIR=${pkgdir} install
  cp -rf ${pkgdir}/Msys64${MINGW_PREFIX} ${pkgdir}${MINGW_PREFIX}/
  rm -rf ${pkgdir}/Msys64
}`

Changes posted above since i cannot push it to this repository.

**Comment by peterbud** [comment]
Could you open a PR? It would be easier to review.

**Comment by revelator** [comment]
A public repository ? sure ill set one up.


Den 23-07-2017 kl. 10:49 skrev Peter Budai:

**Comment by revelator** [comment]
PR opened here https://github.com/revelator/MINGW-packages.

**Comment by peterbud** [comment]
@revelator : Please read how to make PRs on github. There are extensive documentations, for example you can start [here](https://gist.github.com/Chaser324/ce0505fbed06b947d962)
And please make sure you are creating a separate feature branch in your repo for the newly developed stuff, don't work on the `master` branch.

**Comment by lazka** [comment]
Is this still a problem?

**Comment by revelator** [comment]
it will build with ogre and irrlicht now but it still crashes if using those to render the gui.
All render paths excepth ogre and irrlicht work fine.

**Comment by revelator** [comment]
CEGUI::FileIOException in function 'virtual CEGUI::Texture* CEGUI::IrrlichtImageCodec::load(const CEGUI::RawDataContainer&, CEGUI::Texture*)' (C:/mingw-w64-cegui/src/cegui-0.8.7/cegui/src/RendererModules/Irrlicht/ImageCodec.cpp:58) : Irrlicht failed to create irr::video::IImage from file data.

ogre just outright crashes :/ before even loading anything, so it seems a session with the debugger is in order.

**Comment by revelator** [comment]
Ok i scoured the net for info on the irrlicht error, and it seems irrlicht does not handle jpeg data correctly, hence the error. Trunk has patch applied to fix this error, so ill see if i can backport it.

No news on ogre yet.

**Comment by lazka** [comment]
cegui is gone: 0cbc5ff1254d7fd0f8eb67691b
