### ISSUE TITLE
Inappropriate vulkan library name

### ISSUE THREAD

**Issue by wirx6** [msys2/MINGW-packages#2673]
I noticed that libraries using dynamic loading of vulkan runtime are referring to `vulkan-1.dll` instead of `libvulkan-1.dll`.
https://github.com/glfw/glfw/blob/master/src/vulkan.c#L53
https://github.com/bkaradzic/bgfx/blob/master/src/renderer_vk.cpp#L740
https://github.com/renelindsay/Vulkan-WSIWindow/blob/master/WSIWindow/VulkanWrapper/vulkan_wrapper.cpp#L29
We have two ways of fixing this and I don't know what is right.
- strip `lib` prefix from vulkan dlls
- patch names in all libraries

**Comment by Biswa96** [comment]
Would it be a possible workaround if libvulkan-1.dll just copied to vulkan-1.dll? Both DLLs will be present and program will use what it wants.

**Comment by lygstate** [comment]
> Would it be a possible workaround if libvulkan-1.dll just copied to vulkan-1.dll? Both DLLs will be present and program will use what it wants.

short-turn it's OK, longturn, remove libvulkan-1.dll

**Comment by Biswa96** [comment]
> remove libvulkan-1.dll

Then we have to check if any programs expects that exact DLL file. That is somewhat tedious but possible to do.

**Comment by MehdiChinoune** [comment]
> Then we have to check if any programs expects that exact DLL file. That is somewhat tedious but possible to do.
Use package-grokker

**Comment by MehdiChinoune** [comment]
Package-grokker list these packages:
```
mingw-w64-gst-plugins-bad
mingw-w64-magnum
mingw-w64-mesa
mingw-w64-libplacebo
mingw-w64-ffmpeg
mingw-w64-mpv
```

**Comment by Biswa96** [comment]
@lygstate I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2951500265

**Comment by lygstate** [comment]
> @lygstate I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/2951500265

I think it's may still lack something, suppose we will remove `libvulkan-1.dll` in future,
what's the `libvulkan.dll.a` should be?
And what's the `vulkan.pc`?

**Comment by Biswa96** [comment]
Is there any issue at compile or link time? I am thinking to keep the change minimum for now.

**Comment by Biswa96** [comment]
> Is there any issue at compile or link time?

Answering my own question. I found an issue with cmake FindVulkan module. cmake searches for `libvulkan-1.dll.a` import library. But it can be workaround with `-DVulkan_LIBRARY` option with cmake. There is a pending pull request + issue in upstream vulkan-loader repository. It may solve all these things. If it get accepted in upstream I shall try to fix it here also.

**Comment by Biswa96** [comment]
Patches are in upstream now https://github.com/KhronosGroup/Vulkan-Loader/commit/b57feee2859e2dd2076b4c36977bf75ac7ac03e3. Let see how well the dependent packages feel about it.

**Comment by Biswa96** [comment]
@lygstate I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/3009951311
