### ISSUE TITLE
pip vs pacman when installing Python modules / packages

### ISSUE THREAD

**Issue by Ede123** [msys2/MINGW-packages#2745]
Many packages containing binary components are available as MINGW-packages (`mingw-w64-python-...`).

If **pacman** is used to install them the files are copied to Python's "site-packages" directory. They work and can be used. So far so good...

If I know accidentally use **pip** to upgrade such a package I'm unsure what will happen, but at the very least it will result in modified files on disk pacman knows nothing about and potential update conflicts in future.

My questions therefore are:
* Is there a possibility to "distinguish" Python modules installed by pip and pacman, so I do not accidentally use pip to update a package that should be managed by pacman?
* Is there a possibility to "fix" this at the start by changing how python modules from MINGW-packages install themselves?

**Comment by lazka** [comment]
You can use "pip install --user" to install them to you user directory but then you get conflicts for i686 vs x86_64

Or use virtualenv

**Comment by mikofski** [comment]
@lazka actually I am having issues with virtualenv (installed via either pip2 or pip3), I'll post the full traceback shortly (sorry) but it raises and `ImportError` exception, "no module called pkgutils" which _does_ exist in both python2 and python3, it's part of setuptools (you can not install it separately, it's a dummy package). From what I can tell, it creates the folder structure for the new virtualenv, and starts to install pip, setuptools, and wheel, but then raises the error in a subprocess call, where it executes a script that contains the import. Execute the script in the base environments of either python2 or 3 and the imports work fine, so something in setting up the folder structure of the virtualenv is failing, limited by a configuration limitation or other issue in my msys2 environments. I will investigate and post back more when I have time.

If anyone thinks this is a legitimate issue, and should be posted separately, I'm happy to do so, this is the only issue containing "virtualenv" that I could find.

thanks!

**Comment by lazka** [comment]
@mikofski I guess I've never used virtualenv under msys2, yeah, seems something is broken there.

I agree that switching to "--user" by default would improve the situation. Here is the current debian patch: https://anonscm.debian.org/cgit/python-modules/packages/python-pip.git/tree/debian/patches/set_user_default.patch

(looking into distutils I see we could even have different user directories per platform, but that would break existing user installs and not sure all packages can deal with it, seems uncommon)

**Comment by KarimReefat** [comment]
> @lazka actually I am having issues with virtualenv (installed via either pip2 or pip3), it raises and `ImportError` exception, "no module called pkgutils" which _does_ exist in both python2 and python3 .
> 
i can confirm this error , this will happen with mingw32 and mingw64 but not with MSYS2 which install old version of pip ( 10.0 ) and  i add that using --user with pip will not fix it (for me at least).

**Comment by sawan** [comment]
I can confirm this exact error -- trying to create a virtual environment using the utility installed via:

```pip3.7 install virtualenv```

**Comment by lazka** [comment]
Thanks to @danyeaw `python3 -m venv myvenv` works now.

Would this work for everyone?
