### ISSUE TITLE
Parallel Build for Boost

### ISSUE THREAD

**Issue by GyrosGeier** [msys2/MINGW-packages#2784]
Boost uses its own build system, which doesn't respect MAKEFLAGS, so it is difficult to pass a -j`nproc` to it, while here it would make a lot of sense.

It would be nice to have a way for parallel builds to work, e.g. by isolating a -j option from MAKEFLAGS and passing it on to b2.

**Comment by mingwandroid** [comment]
This sounds like something you should be able to do with bash to me?

**Comment by holgern** [comment]
I implemted it here: #2866

**Comment by MehdiChinoune** [comment]
Fixed by #2866

**Comment by GyrosGeier** [comment]
Definitely an improvement, but now you can't turn it off. :/
