### ISSUE TITLE
Severe Vulnerablities in RubyGems bundled version

### ISSUE THREAD

**Issue by BrisingrAerowing** [msys2/MINGW-packages#2848]
[More information](https://www.ruby-lang.org/en/news/2017/08/29/multiple-vulnerabilities-in-rubygems/)

Not sure if you were aware of this, and didn't see any indication of any fixes, so...

**Comment by Alexpux** [comment]
Feel free to submit pull request

**Comment by lazka** [comment]
ruby has been updated in the meantime, so closing.
