### ISSUE TITLE
How to install plplot?

### ISSUE THREAD

**Issue by ChinouneMehdi** [msys2/MINGW-packages#2880]
I tried:
`pacman -Ss plplot`
but i got nothing!

**Comment by Alexpux** [comment]
it not yet builded and uploaded to repo

**Comment by stahta01** [comment]
I did a pull request #2877 just yesterday; but, it failed to build the 64 bit version of the package.

I will try to fix that this week; no idea how long it will take it for the package to be built and uploaded to repo, after I fix the 64 bit build.

Tim S.

**Comment by stahta01** [comment]
I have updated my Windows 7 64 bit laptop, and the 64 bit version of plplot built without error.
So, I am going to have to remove MSys2 and try building without all the packages I got installed and see if that will cause it to error out. If it does error out, should be an easy but likely long time to figure out what package needs added as a depends.  If it does not error out could be weeks before I find the intermittent cause of it not building the 64 bit package. Tim S.

**Comment by stahta01** [comment]
#2925 Calling it quits for the day. I hope the Travis build works for 64 bit. Tim S.

**Comment by stahta01** [comment]
#2931 Trying once last time before giving it up for a week or so. Tim S.

**Comment by stahta01** [comment]
I will try fixing the gdlib/libgd issue after the binary for PR #2950 is created.

Tim S.

**Comment by ChinouneMehdi** [comment]
It doesn't work at all. I built the examples /mingw/share/plplot-5.13.0/examples but they do not run at all.

**Comment by stahta01** [comment]
I just tried to run example 00 and 02 using C++ and they appeared to just lock up and display nothing.
Note: I never heard of plplot till this month; so, I might be doing a simple user error.

Tim S.

**Comment by ChinouneMehdi** [comment]
I built it myself and it runs as expected. maybe there is something wrong with your build.

**Comment by stahta01** [comment]
I had installed the uploaded binary instead of self building.
PR #2990 should fix the libGD or GDlib issue. And, once it build the uploaded binary should work.

Tim S.

**Comment by ChinouneMehdi** [comment]
Still not working.

**Comment by stahta01** [comment]
What is still not working? Since, last time you changed you mind about it working or not working!

**Comment by stahta01** [comment]
What version are you using ? Are you self building?

**Comment by ChinouneMehdi** [comment]
i thought you uploaded new build because i removed it and reinstall it after days.

**Comment by ChinouneMehdi** [comment]
another bug :  I can't build program unless i remove `-lqhull` from pkg-config

**Comment by stahta01** [comment]
I do NOT have the rights to upload a new binary; I think only Alexpux can upload a binary.

I suggest trying to report enough information to fix any bug you find; because what you posted is useless.

Tim S.

**Comment by ChinouneMehdi** [comment]
I tried to build the examples in `/mingw64/share/plplot5.13.0/examples/c`
> make x00c.exe

It gives me this error:
>C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lqhull
>collect2.exe: error: ld returned 1 exit status
>make: *** [Makefile:99: x00c.exe] Error 1

So i edited the file `/mingw64/lib/pkgconfig/plplot.pc`  and i removed `-lqhull`.
After it builds but when i run it. it just lock and does not return anything
> ./x00c.exe -dev pdf

**Comment by Alexpux** [comment]
Latest build in repo for few days. If it not working then package seems still broken in some way

**Comment by stahta01** [comment]
Duplicated the cannot find -lqhull and I think I also got the just lockup problem.

Tim S.

**Comment by stahta01** [comment]
I just found out that MSys related directions and testing sh files where added to plplot git repo.
I will work on getting the changes suggested/hinted by it. The first major change is it suggests python3 instead of python2. Tim S.

**Comment by Dalan94** [comment]
I have a fix for the link of qhull.

I also try to to fix a problem with the DATA_DIR which is hardcoded as `/mingw64/share/plplot5.13.0`. Is there a way to convert it to the Windows path? I looked at the `mingw-w64-pathtools` tool but I couldn't find a way to do it. I couldn't even find an environment variable to the MSYS2 install path.
