### ISSUE TITLE
SOCI package without MySQL and ODBC backends

### ISSUE THREAD

**Issue by DirkMausF** [msys2/MINGW-packages#2935]
It's nice to have prebuild sqlite3, postgres and firebird backends with SOCI, but a good database layer should include mysql and odbc also.

I recompiled the package and changed in mingw-w64-soci\src\soci-3.2.3\src\cmake\modules the files
FindMySQL.cmake and FindODBC.cmake to include the (canonical) search paths of MariaDB and ODBC headers like this:

find_path(ODBC_INCLUDE_DIR sql.h
  /usr/include
  /usr/include/odbc
  /usr/local/include
  /usr/local/include/odbc
  /usr/local/odbc/include
  c:/msys64/mingw64/x86_64-w64-mingw32/include

and 

if(WIN32)
   find_path(MYSQL_INCLUDE_DIR mysql.h
      PATHS
      $ENV{MYSQL_INCLUDE_DIR}
      $ENV{MYSQL_DIR}/include
      $ENV{ProgramFiles}/MySQL/*/include
      $ENV{SystemDrive}/MySQL/*/include
      c:/msys64/mingw64/include/mariadb

Then i recompiled it with makepkg-mingw -f -e, to don't extract the sources and override my changes.
I didn't find out, how to make it a relative path, but building of these both backends works now.
Is there a way to integrate this into the cmake files via patch without canonical paths to share it with all msys2 users?

Greetings, Dirk

**Comment by MehdiChinoune** [comment]
It supports them, now.
