### ISSUE TITLE
ASLR is disabled for exe linked by GCC

### ISSUE THREAD

**Issue by quilloss** [msys2/MINGW-packages#3035]
ASLR always seems to be disabled even when `--dynamicbase` is specified.

Example code
```c
// test.c
#include <stdio.h>

int main()
{
	printf("Wait...\n");
	getc(stdin);
	return 0;
}
```

`gcc test.c -static -Wl,--dynamicbase -o test.exe`
Process Explorer reports: `Address Space Load Randomization: Enabled (permanent)Disabled`

`clang-cl test.c`
Process Explorer reports: `Address Space Load Randomization: High-Entropy, Bottom-Up`

**Comment by asvc** [comment]
Any progress on this one?..

**Comment by salowenh** [comment]
Same here

**Comment by Biswa96** [comment]
Did you try latest mingw-w64-gcc? ASLR is enabled when specified `-Wl,--dynamicbase` option with gcc 10.1.0.

**Comment by salowenh** [comment]
@Biswa96 I'm using a pre-built lib (libgsf) - does that mean there is need to recompile the library and all its dependencies with `-Wl,--dynamicbase`
Thanks!

**Comment by Biswa96** [comment]
As far as I know, yes, everything needs to be recompiled to enable ASLR for all msys2 components. But @Alexpux once told me that there are some problems to enable ASLR by default.

**Comment by salowenh** [comment]
@Alexpux can you please elaborate?

**Comment by salowenh** [comment]
@Biswa96 can you please explain shortly how I can add these flags?
I'm building via MSYS2 using the following command: `MINGW_INSTALLS=mingw64 makepkg-mingw -sLf`
I believe I should alter the relevant [PKGBUILD](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-zlib/PKGBUILD) file but I'm not sure as I don't see the actual compilation command in there

**Comment by Biswa96** [comment]
`LDFLAGS+=" -Wl,--dynamicbase"` can be added in PKGBUILD file. But it may vary with packages and build systems.

**Comment by salowenh** [comment]
@Biswa96 thanks, I've tried adding it before the `make -j1 all` but I don't see it was added to the compilation line, for example: (w/ the flag):
```
x86_64-w64-mingw32-gcc -march=x86-64 -mtune=generic -O2 -pipe -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/inffast.o inffast.c
```

**Comment by Biswa96** [comment]
If you are using `makepkg` command then append those flags in `LDFLAGS` in `/etc/makepkg_mingw64` file _in this case_.

**Comment by Biswa96** [comment]
If you are using `makepkg` command then append those flags in `LDFLAGS` in `/etc/makepkg_mingw64.conf` file _in this case_.

**Comment by salowenh** [comment]
@Biswa96 I did that, there was even a pre-written line with the necessary flags, I uncommented it but I still don't see the relevant flags in the complication command (I closed and reopened the MSYS2 window as well)
```
LDFLAGS="-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat"
```

**Comment by mati865** [comment]
Binutils 2.34 has finally fixed missing relocation sections when using ASLR (AFAIK they were missing since the beginning) but introduced another issues which should be already solved by patches backported to our `mingw-w64-binutils` package.

I think it's worth trying again with update to Binutils 2.35.

**Comment by salowenh** [comment]
@mati865 can you please elaborate a bit, should we re-install mingw on its latest version and recompile with the same flags above?
Does that mean baseAddress for x64 will now be over the 4GB limit without the need to use LLD?

**Comment by mati865** [comment]
@salowenh mingw version is already fine, what needs update is binutils package. Then recompile with above flags.

> Does that mean baseAddress for x64 will now be over the 4GB limit without the need to use LLD?

No, it's still broken in ld.bfd.

**Comment by lazka** [comment]
This is fixed since https://www.msys2.org/news/#2021-01-31-aslr-enabled-by-default
