### ISSUE TITLE
cmake doesn't respect compiler setting, uses system MSVC instead of MSYS2/mingw64

### ISSUE THREAD

**Issue by mappu** [msys2/MINGW-packages#306]
I am trying to build a cmake project. However cmake fails to find gcc and insists on using my system MSVC install instead. Even when the compiler is explicitly set in arguments.

```
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=C:/msys32/mingw32/bin/gcc.exe -DCMAKE_C_FLAGS=-O1 -DCMAKE_CXX_COMPILER=C:/msys32/mingw32/bin/g++.exe -DCMAKE_CXX_FLAGS=-O1 -DCMAKE_EXE_LINKER_FLAGS='' -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_MODULE_LINKER_FLAGS='' -DCMAKE_SHARED_LINKER_FLAGS='' -- C:/redacted/openage/openage

-- The C compiler identification is MSVC 18.0.30501.0
-- The CXX compiler identification is MSVC 18.0.30501.0
-- Check for working C compiler using: Visual Studio 12 2013
-- Check for working C compiler using: Visual Studio 12 2013 -- works
...[snipped]
```

Setting the `_COMPILER` flags to just `gcc`/`g++` has the same issue.

Weirdly, if the `CMakeLists.txt` file contains e.g. `message(" ${CMAKE_CXX_COMPILER_ID} ")` then g++ is displayed.

Package version:

```
$ pacman -Qs cmake
local/mingw-w64-i686-cmake 3.0.2-1
$ which cmake
/mingw32/bin/cmake
$ cmake --version
cmake version 3.0.2
```

I'm a little unexperienced with cmake so it might be my problem. But surely, setting `CMAKE_C_COMPILER` should work properly.

**Comment by bagong** [comment]
I would love to see cmake use "MSYS Makefiles" by default in msys2. On Windows cmake uses the VS toolchain and solution files by default, on Linux Makefiles, on OSX Xcode, so setting MSYS as default for msys2 would be very cmake conform and save typing. Not academic but practical ;)
