### ISSUE TITLE
cling-git: llvm compile error

### ISSUE THREAD

**Issue by wurui1994** [msys2/MINGW-packages#3107]
D:/Software/GitHub/mingw/mingw-w64-cling-git/src/llvm-cern/include/llvm/ADT/IntrusiveRefCntPtr.h:158:9: error: '{anonymous}::ChainedIncludesSource* llvm::IntrusiveRefCntPtr<{anonymous}::ChainedIncludesSource>::Obj' is private within this context
       S.Obj = 0;
       ~~^~~
D:/Software/GitHub/mingw/mingw-w64-cling-git/src/llvm-cern/include/llvm/ADT/IntrusiveRefCntPtr.h:137:8: note: declared private here
     T* Obj;
        ^~~

**Comment by mati865** [comment]
That PKGBUILD wasn't updated for quite long time.
You will have to refresh it.

**Comment by goyalyashpal** [comment]
hi @wurui1994 does this error still exists?
