### ISSUE TITLE
AddressSanitizer does not appear to be available for mingw-w64-x86_64-gcc

### ISSUE THREAD

**Issue by ghost** [msys2/MINGW-packages#3163]
OS: Windows 10 x64, version 1703 (build 15063.726)

Steps to reproduce:
1. Install MSYS2, default values
2. Update MSYS2, `pacman -Syyu`, use ctrl+C to close pacman then close window
3. Update MSYS2 again, `pacman -Syyu`
4. Install GCC and nano, `pacman -Sy mingw-w64-x86_64-gcc nano`
5. Open a MinGW 64bit session from the Start menu
6. Open nano to create a new .cpp file, `nano test.cpp`
7. Paste following code into nano,
```
int main(int argc, char **argv) {
  int *array = new int[100];
  array[0] = 0;
  int res = array[argc + 100];  // BOOM
  delete [] array;
  return res;
}
```
8. Try to compile, `g++ -fsanitize=address -O1 test.cpp -o test`

Output:
```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lasan
collect2.exe: error: ld returned 1 exit status
```

So, is AddressSanitizer available within the MinGW-w64 project?

**Comment by mati865** [comment]
I think there are no working sanitizers for mingw.

**Comment by ukhf-jm** [comment]
Output for `clang++: error: unsupported option '-fsanitize=address' for target 'x86_64-pc-msys'`:
```
clang++: error: unsupported option '-fsanitize=address' for target 'x86_64-pc-msys'
```

> I think there are no working sanitizers for mingw.
Well, that's really disappointing. Also tried the distribution of MinGW from https://nuwen.net/mingw.html but got the same result :(

**Comment by ZijunH** [comment]
Would like to know if you got ASAN working

**Comment by mati865** [comment]
Sanitizers should work now if you build LLVM from git.

**Comment by ZijunH** [comment]
I have installed LLVM 8.0.0 from a prebuilt binary and attempted adding -fsanitize=address to the compiler flags. Linker throws and error saying cannot find the files:

- libclang_rt.asan_dynamic-x86_64.dll.a
- libclang_rt.asan_dynamic_runtime_thunk-x86_64.a

Checking the folder itself reveals .lib files with the following names (and many more .lib files) exist:

- clang_rt.asan_dynamic-x86_64.dll
- clang_rt.asan_dynamic_runtime_thunk-x86_64.lib

 Any hints on how to fix this?

**Comment by mati865** [comment]
`LLVM 8.0.0 from a prebuilt binary` you mean from llvm.org?
Those binaries are built with MSVC and you need one build with MinGW.

**Comment by amithks25** [comment]
I m also facing the same issue.I didn't got any solution for that. I m also trying to build clang from Mingw on windows , It is giving error that I cant find any solution.Please let me know If you guys find any solution

**Comment by SeanTolstoyevski** [comment]
hey follks

I don't want to use CL. I dont know.
I'm compiling everything with GCC (mingw-w64).

What are the tools I can use in Windows to detect memory leaks?

**Comment by debashish-ghosh** [comment]
I tried building mingw-w64 (using gcc toolchain) with `--enable-libsanitizer` (in the configure step), but the build failed with the following error:
```
../../../../src/libsanitizer/sanitizer_common/sanitizer_win_defs.h:69:11: error: expected constructor, destructor, or type conversion before ‘(’ token
   69 |   __pragma(comment(linker, "/alternatename:" WIN_SYM_PREFIX STRINGIFY(Name) "="\
      |           ^
```
Looks like they are expecting it to be built by MSVC (`__pragma` is MSVC specific) 😞

**Comment by ThosRTanner** [comment]
is there any advance on this? I can use sanitisers if I use the clang64 packages (though the program I'm trying hangs very oddly without any messages), but building under mingw64 with gcc gives me the original message, and using clang under mingw64 compiles but won't link, giving:

C:/Apps/msys64/mingw64/bin/ld: cannot find C:/Apps/msys64/mingw64/lib/clang/13.0.1/lib/windows/libclang_rt.asan_dynamic-x86_64.dll.a: No such file or directory
C:/Apps/msys64/mingw64/bin/ld: cannot find C:/Apps/msys64/mingw64/lib/clang/13.0.1/lib/windows/libclang_rt.asan_dynamic_runtime_thunk-x86_64.a: No such file or directory
C:/Apps/msys64/mingw64/bin/ld: cannot find C:/Apps/msys64/mingw64/lib/clang/13.0.1/lib/windows/libclang_rt.asan_dynamic_runtime_thunk-x86_64.a: No such file or directory

**Comment by mati865** [comment]
> the program I'm trying hangs very oddly without any messages

Does is hang without sanitizers?

> building under mingw64 with gcc gives me the original message

GNU sanitizers don't support Windows, there is nothing we can do about it.

> using clang under mingw64 compiles but won't link

LLVM sanitizers don't build when using GCC or ld.bfd which are the main tools for mingw and ucrt subsystems.

**Comment by ThosRTanner** [comment]
> Does is hang without sanitizers?
It certainly goes very slowly. This is why I'm trying to use sanitisers to see if the code is doing something it shouldn't

**Comment by mati865** [comment]
> It certainly goes very slowly. This is why I'm trying to use sanitizers to see if the code is doing something it shouldn't

So this is expected, sanitizers because of their nature introduce slowdown (how much depends on sanitizer type).

> Wouldn't it make sense to build them with clang in that case?

We'd probably accept if somebody opens PR that achieves that without complicating PKGBUILDS too much.

**Comment by ThosRTanner** [comment]
> So this is expected, sanitizers because of their nature introduce slowdown (how much depends on sanitizer type).

It's going very slowly WITHOUT the sanitizers. Which is why I was trying to use them

**Comment by mati865** [comment]
> It's going very slowly WITHOUT the sanitizers. Which is why I was trying to use them

This is the exact reason to use profilers. Sanitizers won't help here and only make it even slower.

**Comment by ThosRTanner** [comment]
Given I'm getting different results with different compilers, I'd be inclined to look for undefined behaviour first. Also, I can't help feeling my chances of profilers working in mingw64 are lower than that of sanitisers.

**Comment by mati865** [comment]
I think it's LLVM bug (missed optimization perhaps?) since it works with GCC (`mingw64` and `ucrt64` use the same compiler but different C runtime library). Also why do you think running sanitizers with clang from `mingw64` environment would be any faster than `clang64`?

Anyway I suggest opening new issue for missing Clang sanitizers in GNU based environments since this issue has been created for missing sanitizers in GCC (which is unlikely to be ever fixed).

**Comment by ThosRTanner** [comment]
I really don't understand why you feel I think running with sanitisers would be faster. I am observing behaviour that I believe sanitisers might throw some light on. However, I will open a new issue for missing sanitisers as suggested

**Comment by mati865** [comment]
Let me clarify it: what benefit do you expect from using Clang+sanitizers in `mingw64` environment compared to Clang+sanitizers in `clang64` environment?

**Comment by ThosRTanner** [comment]
not having to have multiple environments?

**Comment by MehdiChinoune** [comment]
Sanitizers are not supported by GCC on Windows.

**Comment by Karlson2k** [comment]
As I see a number of references to this issue, it is worth clarifying: 
* Msys2 does nothing with sanitizers. It is up to compiler, linker and sanitizer library to support the platform.
* While GCC-based toolchains for MinGW do not support sanitizers, the clang/llvm-based toolchains supported sanitizers for a long time. See [here](https://www.msys2.org/docs/environments/#gcc-vs-llvmclang) and [here](https://github.com/msys2/MSYS2-packages/discussions/3020#discussioncomment-2840741).
