### ISSUE TITLE
Build qttools as a separate package

### ISSUE THREAD

**Issue by annulen** [msys2/MINGW-packages#3239]
After QtWebKit was moved into separate package, QtDesigner and QtAssistant cannot use it anymore (the former doesn't provide respective widget, the latter cannot use full-featured HTML renderer and falls back to QTextDocument). Solution is to build them after QtWebKit is installed.

**Comment by Biswa96** [comment]
qttools is a separate package now. Thanks to Mehdi Chinoune for the great work.

* qt5-tools: https://packages.msys2.org/base/mingw-w64-qt5-tools
* qt6-tools: https://packages.msys2.org/base/mingw-w64-qt6-tools
