### ISSUE TITLE
qt5 patch needed for building with gcc-7.2.0

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#3255]
64 bit version builds ok but the 32 bit version croaks on cpu randomization code.
discussed here and there is a patch https://github.com/mxe/mxe/issues/2011
tested and works fine.

**Comment by kmatheussen** [comment]
Same problem in gcc 5.4 BTW. Seems to be a mingw + qt5.10 issue.

**Comment by revelator** [comment]
A gcc bug was mentioned, it might go back some releases as far as i can see. Gcc-5.2.0 seems to work but i have no idea which of the numerous changes caused this bug in later versions of gcc.

**Comment by revelator** [comment]
updating to gcc-7.3.0 now breaks building qtwebkit with cc1plus out of memory error :/, this only happens on the 32 bit compiler.
