### ISSUE TITLE
Cannot run doxywizard/Issue with Qt5 install

### ISSUE THREAD

**Issue by ghost** [msys2/MINGW-packages#3263]
I've installed doxygen and was trying to use the included GUI tool doxywizard. Got the following error:  
```
$ doxywizard
C:/msys64/mingw64/bin/doxywizard.exe: error while loading shared libraries: Qt5Xml.dll: cannot open shared object file: No such file or directory
```  
No problem, seems that the doxygen package missed the Qt5 dependency. So I run `$ pacman -S mingw-w64-x86_64-qt5` and that installs fine.  

I then try to run doxywizard again and this time get a popup with this error:  
```
---------------------------
doxywizard
---------------------------
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.
---------------------------
OK   
---------------------------
```  

I'm not sure if this is a problem with the doxygen package or the Qt5 package or if I've done something wrong here.

**Comment by Alexpux** [comment]
@ukhf-jm seems qtbinpatcher not patch some files. Reinstall qt5 package

**Comment by ukhf-jm** [comment]
Tried reinstalling Qt5 but still having the same issue.
