### ISSUE TITLE
mingw-w64-boost: version 1.66.0 no longer requires boost-1.61.0-fix-undefined-referense-to-codecvt.patch

### ISSUE THREAD

**Issue by hanetzer** [msys2/MINGW-packages#3266]
The latest update fixed this, I'm not sure where or what commit it was but
boost.serialization now builds on mingw-w64 without that patch.

**Comment by MehdiChinoune** [comment]
boost is now at 1.79.0
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-boost/PKGBUILD#L9
