### ISSUE TITLE
Cross-compilers to Mac OSX and Linux?

### ISSUE THREAD

**Issue by AlexKotik** [msys2/MINGW-packages#3336]
Sorry, this might be a stupid question, but still. Is it possible for you to build and add to MSYS2 distribution cross-compilers that will allow compiling C/C++ code on Windows targeting Mac OSX and some generic Linux distribution?

**Comment by Alexpux** [comment]
Feel free to do this work and create pull request

**Comment by lazka** [comment]
Since nothing happened here since then -> closing
