### ISSUE TITLE
Cannot find a type to use in place of socklen_t

### ISSUE THREAD

**Issue by manhnt9** [msys2/MINGW-packages#3342]
I meet error: Cannot find a type to use in place of socklen_t
when configuring (./configure) distcc
Maybe mingw doesn't have socket.h, how can I install sys/socket.h for it?

**Comment by mati865** [comment]
https://stackoverflow.com/questions/4638604/where-does-one-get-the-sys-socket-h-header-source-file
Mingw-w64 isn't an exception here,

**Comment by MehdiChinoune** [comment]
see comment above.
