### ISSUE TITLE
gcc-7.3.0 breaks qtwebkit with out of memory error in cc1plus

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#3401]
This is a rather strange bug, qtwebkit builds fine with gcc-7.2.0 and the only major difference i can see is that you now build the experimental stdc++17 library, so i tried to rebuild gcc without that one and it works again, so something seems to seep through in the buildchain causing this error.

maybe better to hold off on including this library as of yet ?.

**Comment by mingwandroid** [comment]
Is this 32 bit? If so then it's likely plain run out of memory since there's only 4GB address space.

**Comment by revelator** [comment]
Then why does it work with gcc-7.2.0 ?. 
But yeah QT allways had a taste for memory hungry builds,
even so libstdc++ts should not be used when not using c++17 but it seems atleast some part of it is as apparent by g++ being able to build it again when i turn it off.

**Comment by lazka** [comment]
> Is this 32 bit? If so then it's likely plain run out of memory since there's only 4GB address space.

It's limited to 2GB by default, but afaik you can increase the virtual address space size of a binary with "editbin.exe /LARGEADDRESSAWARE", maybe that should be done by default here.

**Comment by revelator** [comment]
Yep tried that does not work unfortunatly, neither does building with -wa,-mbig or any other workaround than disabling the experimental libstdc++ts, trust me i tried every trick in the book and nothing works besides that. But the problem should be forwarded to both the gcc and qtwebkit devs so that it can be fixed properly.  

Also noticed something that might be unrelated with gcc-7, but it fails to determine static vs shared libraries and tries to link to both at the same time causing some rather weird situations at times. gcc-6 also exhibited this behaviour to some degree. Actually a lot of the packages that do not build atm according to your statements in the source fail to build because of this. I managed to build 99% of the mingw-packages but i had to physically rip out the shared libraries which a lot of those packages tried to link to instead of the static ones that they where told to. This might not even be a gcc bug but rather a bug in binutils. In essence it seems as though the tools do not know the difference between lib.a and lib.dll.a and treat both as static libraries, even libtool bitches about it telling me lib.dll.a is a static library :/

**Comment by smihaila** [comment]
I might be experiencing the same issue, but with the x86_64 flavor of the mingw64 toolchain (and using the same gcc / g++ 7.3.0), namely some mix-up between the truly static system libs (libadvapi32.a, libws_32.a etc) and the import equivalent (.dll.a) - both present in the toolchain' standard system path/prefix.

Following upon Alex' advice, I'll redo my build by making sure to temporarily rename all those .a.dll implibs.
