### ISSUE TITLE
mingw-w64-imagemagick: configure.xml file not located in the correct place

### ISSUE THREAD

**Issue by paulalanthompson** [msys2/MINGW-packages#3444]
After installing mingw-w64-imagemagick with no errors, a run-time error was encountered:

convert.exe: unable to find configure file 'configure.xml' etc etc

The file was found in 
/mingw64/lib/ImageMagick-7.0.6/config-Q16HDRI

After copying the file to 
/mingw64/etc/ImageMagick-7
the error went away, and specific scripts which use IM now run correctly. 

This is an misconfiguration issue in the install utility.

**Comment by jho101** [comment]
see also here: https://github.com/Alexpux/MINGW-packages/issues/2995

**Comment by jeroen** [comment]
Configure with `--enable-zero-configuration --without-modules` to prevent runtime dependencies on external xml or dll files.
