### ISSUE TITLE
gphoto2 still needs libtool after build

### ISSUE THREAD

**Issue by knokmki612** [msys2/MINGW-packages#3457]
## Step to reproduce

1. install msys2 with [Current installer](http://www.msys2.org)
2. do commands as follows

```
$ pacman -Syuu
$ pacboy -S gphoto:x
$ gphoto2
C:/msys64/mingw64/bin/gphoto2.exe: error while loading shared libraries: libreadline7.dll: cannot open shared object file: No such file or directory
```

## What happens

I get the error the above and I cannot use gphoto2

## Temporary solution

I do `pacboy -S libtool:x` then I could use gphoto2 without the error

I looked into this issue, and I noticed that `libtool` was specified by [PKGBUILD](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gphoto2/PKGBUILD#L15) in "makedepends"

I think `libtool` should requires only while build step, but now It is not

## Environment

* Windows 10 64bit
* Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz

**Comment by peterbud** [comment]
Thanks,  I'll look into that.

**Comment by thegoldenmule** [comment]
@knokmki612 did you find a workaround for this? I'm hitting the same thing.

**Comment by lazka** [comment]
So, looks like gphoto2 is still missing a readline dep, right?

**Comment by peterbud** [comment]
I don't think so. Look at the _direct_ dependencies:
```
$ ntldd /mingw64/bin/libgphoto2-6.dll
        libgphoto2_port-12.dll => C:\msys64\mingw64\bin\libgphoto2_port-12.dll (0x0000000000b30000)
        KERNEL32.dll => C:\windows\SYSTEM32\KERNEL32.dll (0x0000000000d70000)
        msvcrt.dll => C:\windows\SYSTEM32\msvcrt.dll (0x0000000000d70000)
        SHELL32.dll => C:\windows\SYSTEM32\SHELL32.dll (0x0000000001050000)
        libexif-12.dll => C:\msys64\mingw64\bin\libexif-12.dll (0x0000000000b30000)
        libintl-8.dll => C:\msys64\mingw64\bin\libintl-8.dll (0x0000000000b50000)
        libltdl-7.dll => C:\msys64\mingw64\bin\libltdl-7.dll (0x0000000000b50000)

$ ntldd libgphoto2_port-12.dll
        libintl-8.dll => C:\msys64\mingw64\bin\libintl-8.dll (0x0000000000b10000)
        libltdl-7.dll => C:\msys64\mingw64\bin\libltdl-7.dll (0x0000000000b10000)
        libsystre-0.dll => C:\msys64\mingw64\bin\libsystre-0.dll (0x0000000000020000)
        KERNEL32.dll => C:\windows\SYSTEM32\KERNEL32.dll (0x0000000000d40000)
        msvcrt.dll => C:\windows\SYSTEM32\msvcrt.dll (0x0000000000d40000)

```

So I don't see that it _directly_ depends on readline. 
Also the Arch libgphoto2 is NOT dependent on readline either directly:
https://www.archlinux.org/packages/extra/x86_64/libgphoto2/

Maybe some of the above libraries are dependent on readline? My first suspect is libxml2, according to Arch it does depends on readline:
https://www.archlinux.org/packages/core/x86_64/readline/

However in libxml2 in MSYS2 does not depend on readline.

Thoughts?

**Comment by lazka** [comment]
I meant gphoto2 not libgphoto2

**Comment by peterbud** [comment]
Indeed! PR opened.
