### ISSUE TITLE
Installing Djview 'eats' a lot of space

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#3474]
Really to install mingw-w64-x86_64-djview do we need to install about 6 GiB of  packages?

```
$ pacman -S mingw-w64-x86_64-djview
risoluzione delle dipendenze in corso...
ricerca dei pacchetti in conflitto in corso...

Pacchetti (7) mingw-w64-x86_64-assimp-4.0.1-1  mingw-w64-x86_64-icu-debug-libs-58.2-3
              mingw-w64-x86_64-pcre2-10.30-1  mingw-w64-x86_64-qt5-5.10.1-1
              mingw-w64-x86_64-qtbinpatcher-2.2.0-2  mingw-w64-x86_64-zziplib-0.13.62-5
              mingw-w64-x86_64-djview-4.10.6-1

Dimensione totale dei pacchetti da scaricare:   1066,89 MiB
Dimensione totale dei pacchetti da installare:  6212,35 MiB

:: Vuoi procedere con l'installazione? [S/n] n

```

The [setup](https://sourceforge.net/projects/djvu/files/DjVuLibre_Windows/3.5.27%2B4.10/) from SourceForge is only 9 MiB...

Angelo

**Comment by metab0t** [comment]
`mingw-w64-x86_64-qt5` is the main space hog, which occupies about 6GiB space.

**Comment by filnet** [comment]
and msys2 is a development environment, so you get the full qt5 package and not just what djview needs.

**Comment by filnet** [comment]
what's strange is that djview pulls icu-debug and not plain icu.

**Comment by angelog0** [comment]
@filnet wrote:

> and msys2 is a development environment, so you get the full qt5 package and not just what djview needs

Maybe that package has to be splitted?

How is this handled in Arch Linux (MSYS2 has the same package manager)?

Angelo

**Comment by filnet** [comment]
I don't know djview but won't it create an installer when you build it ?
If yes, then the installer will install only what djview needs.

Again, msys2 is a development environment. It is not meant to use apps but to build them.
For a development environment having smaller packages is nice to have but not a must.
So I doubt anyone will start breaking up qt into smaller parts unless there is a really compelling reason.
Disk space is not a compelling reason as it is cheap.

**Comment by mingwandroid** [comment]
Well MSYS2 is a software distro really. Yes we hope to attract developers (because they help to make the distro better) but we are also happy to attract users.

Qt5 is not split mostly because no one has bothered to do it and because it will cost Alexey a lot of time rebuilding stuff if not done very carefully.

Also our qt recipes are very heavily patched and therefore large and complicated so splitting them would be pretty difficult. The same recipe is more or less used for both qt5 and qt5-static which makes things even trickier.

**Comment by filnet** [comment]
Correct, MSYS2 is a software distro and building platform for Windows.
