### ISSUE TITLE
Split up the packages into categories / directories

### ISSUE THREAD

**Issue by askondro** [msys2/MINGW-packages#3479]
Hello,

I would like to propose that we sort all the packages into a more concise structure.
This would avoid the 1000 items limit on github and would also help with the navigation.

Proposed categories / directories:

- Development
- Games
- Editors
- Core // crt and stuff
- Database
- Sound / Music
- Graphics
...

What do you think?

**Comment by elieux** [comment]
Categories are a PITA.  They would enforce a tree structure where a tree structure does not work.  I'm sad about the GitHub listing as well, but bending the repo just to fix that doesn't sound good to me.

-- 
David Macek

**Comment by KrullBorg** [comment]
we can split the repository into directories as debian do

http://ftp.debian.org/debian/pool/main/
