### ISSUE TITLE
Update webkitgtk-3.0 to webkit2gtk-4.0

### ISSUE THREAD

**Issue by adrianptr** [msys2/MINGW-packages#3484]
Hello, the last package webkitgtk for msys2 is at version 2.4, but the last version of webkitgtk is 2.18. Most apis are deprecated. Please update this.

**Comment by Alexpux** [comment]
2.4 is the last version that can be build with mingw. So there are will no updates anymore.
You can try to build last version yourself and patch it. If you success you can create pull request

**Comment by lazka** [comment]
If someone wants to play around here is a basic PKGBUILD for webgit2gtk. It compiles at least some files before failing :)

**Comment by lazka** [comment]
https://bugs.webkit.org/show_bug.cgi?id=183776#c2

**Comment by revelator** [comment]
Have also been trying to get the new version building, so far with little success im afraid.
Build system also changed in later versions from autotools to cmake based and it needs a ton of patches to even get some parts of it building on windows (atleast with the current gcc version). It might get further with an older gcc version because some build erors seem to be related to recent api changes.

**Comment by allforabit** [comment]
Perhaps this could be of some help? https://gist.github.com/baylej/d32be86616104569b29b

**Comment by lazka** [comment]
It's unlikely that we'll manage to get this building and maintained without upstream officially supporting Windows.

If something changes feel free to post here or create a new issue.

**Comment by darkguy2008** [comment]
Do we have any news this year of having WebKitGTK on Windows?

**Comment by Alexpux** [comment]
@darkguy2008 as I know there are no volunteers to do this work

**Comment by DShelgren** [comment]
It's doable, but NOT redistributable as far as I know. I absolutely hard needed it. Yep having to use some semi commercial options in the now, but there'a still hope.

**Comment by BehroozAmoozad** [comment]
@DShelgren Are you able to use it right now? what did you end up doing?

**Comment by Kreijstal** [comment]
> It's doable, but NOT redistributable as far as I know. I absolutely hard needed it. Yep having to use some semi commercial options in the now, but there's still hope.

how did you do it?

**Comment by BehroozAmoozad** [comment]
I ended up running a custom web server and did my renders using webkit on Linux, converted the results to png and pdf and to cups from there.  Took us like 500 developer hours for the entire thing including a very advanced print backend.

**Comment by lazka** [comment]
If you have control over the html and just need it rendered, maybe https://weasyprint.org would work for you.

**Comment by taozuhong** [comment]
https://github.com/roojs/webview2-gtk/blob/master/packaging/msys2/PKGBUILD
