### ISSUE TITLE
update mingw-w64-go to go 1.10

### ISSUE THREAD

**Issue by oksbsb** [msys2/MINGW-packages#3501]
go 1.10 released, so please update.
Thanks a lot!

**Comment by lazka** [comment]
@taketori

**Comment by taketori** [comment]
I want to do. but no time to do these days.
so plz, ANYONE!
(If no one does, I shall do in April.)

**Comment by umarcor** [comment]
The current version is 1.14.4: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-go/PKGBUILD#L7. Hence, I think this issue can be closed.
