### ISSUE TITLE
update mingw-w64-nodejs to latest LTS

### ISSUE THREAD

**Issue by eshimischi** [msys2/MINGW-packages#3502]
Node.js v8.10.0 LTS or v9.8.0
Thanks a lot!

**Comment by eshimischi** [comment]
Or v9.9.0 that has some security fixes, released 2018-03-21

**Comment by lazka** [comment]
https://github.com/msys2/msys2/wiki/Creating-Packages

**Comment by MehdiChinoune** [comment]
nodejs is no longer available.
