### ISSUE TITLE
pdcurses: is it reasonable to ship the executable demos as part of the package?

### ISSUE THREAD

**Issue by GitMensch** [msys2/MINGW-packages#3549]
Is it useful for the user to have the complete demos (the *.exe) installed? If not we should adjust the PKGBUILD.

Additional Question:
The two samples rain.c and worms.c are actually under NCurses MIT-like license - should the license header (previously "custom" with 8c31f32 as "public domain") be adjusted?

**Comment by MehdiChinoune** [comment]
pdcurses no longer installs demos/tests.
Fixed by #10347
