### ISSUE TITLE
Missing netdb.h

### ISSUE THREAD

**Issue by HorizonShadow** [msys2/MINGW-packages#3586]
I'm trying to install the `do_postgres` gem, using --platform ruby.

The error on install is: 

```
checking for -lpq... yes
checking for libpq-fe.h... yes
checking for libpq/libpq-fs.h... yes
checking for postgres.h... no
```

And in mkmf.log

```
C:/ruby24/msys32/mingw32/include/POSTGR~1/server/port.h:17:10: fatal error: netdb.h: No such file or directory
 #include <netdb.h>
          ^~~~~~~~~
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: #include <postgres.h>
/* end */
```

I can't seem to find out where to get that header file, exactly.

**Comment by elieux** [comment]
Looks like `netdb.h` is not available in mingw-w64, see <https://www.gnu.org/software/gnulib/manual/html_node/netdb_002eh.html>.

Searching around the Internet, it seems that it might help to replace it with `winsock2.h` and/or `ws2tcpip.h`.

-- 
David Macek
