### ISSUE TITLE
go build github.com/bieber/barcode，zbar and libiconv is error

### ISSUE THREAD

**Issue by mj520** [msys2/MINGW-packages#3604]
windows x64
msys2 zbar+libiconvinstall

D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libzbar.a(zbar_libzbar_la-qrdectxt.o):(.text+0xdf): undefined reference to `libiconv_open'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libzbar.a(zbar_libzbar_la-qrdectxt.o):(.text+0xfa): undefined reference to `libiconv_open'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libzbar.a(zbar_libzbar_la-qrdectxt.o):(.text+0x10e): undefined reference to `libiconv_open'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libzbar.a(zbar_libzbar_la-qrdectxt.o):(.text+0x31f): undefined reference to `libiconv_close'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libzbar.a(zbar_libzbar_la-qrdectxt.o):(.text+0x37b): undefined reference to `libiconv_close'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libzbar.a(zbar_libzbar_la-qrdectxt.o):(.text+0x38e): undefined reference to `libiconv_close'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libzbar.a(zbar_libzbar_la-qrdectxt.o):(.text+0x3a4): undefined reference to `libiconv_close'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libzbar.a(zbar_libzbar_la-qrdectxt.o):(.text+0x693): undefined reference to `libiconv'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libzbar.a(zbar_libzbar_la-qrdectxt.o):(.text+0x714): undefined reference to `libiconv_open'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libzbar.a(zbar_libzbar_la-qrdectxt.o):(.text+0x7bb): undefined reference to `libiconv_close'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libzbar.a(zbar_libzbar_la-qrdectxt.o):(.text+0x938): undefined reference to `libiconv_close'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libzbar.a(zbar_libzbar_la-qrdectxt.o):(.text+0xa4d): undefined reference to `libiconv_close'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libzbar.a(zbar_libzbar_la-qrdectxt.o):(.text+0xc46): undefined reference to `libiconv'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../lib/libzbar.a(zbar_libzbar_la-qrdectxt.o):(.text+0xef0): undefined reference to `libiconv'
collect2.exe: error: ld returned 1 exit status

please help build windows for golang    、centos build ok

**Comment by mj520** [comment]
D:/msys64/mingw64/bin/zbarimg.exe: error while loading shared libraries: libMagickWand-7.Q16HDRI-0.dll: cannot open shared object file: No such file or directory

libMagick++-7.Q16HDRI-3.dll
libMagickCore-7.Q16HDRI-3.dll
libMagickWand-7.Q16HDRI-3.dll

**Comment by Alexpux** [comment]
@mj520 see what library is missing to load, for example using Dependency Walker

**Comment by mj520** [comment]
libMagick++-7.Q16HDRI-3.dll 
libMagickCore-7.Q16HDRI-3.dll
libMagickWand-7.Q16HDRI-3.dll
rename 
libMagick++-7.Q16HDRI-0.dll 
libMagickCore-7.Q16HDRI-0.dll
libMagickWand-7.Q16HDRI-0.dll

zbarimg.exe is run ok，Please make sure it is not a file naming error

but 
go build github.com/bieber/barcode is error
Compile errors to help solve the top problems

**Comment by Alexpux** [comment]
zbar will be rebuild
