### ISSUE TITLE
Build libcurl with http/2 over winssl

### ISSUE THREAD

**Issue by jeroen** [msys2/MINGW-packages#3617]
The current [mingw-w64-curl](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-curl/PKGBUILD) has a variant to build with nghttp2+openssl that supports HTTP/2, and a variant to build with winssl that does not support HTTP/2

However I would like to build libcurl to use HTTP/2 (nghttp2) over winssl rather than openssl. According to [this post](https://curl.haxx.se/mail/lib-2018-04/0077.html) on the mailing list this can be done:

> You need to build curl with a new enough SDK ("version 8.1 of the Windows SDK"), run on a new enough Windows ("Windows 8.1 / Server 2012 R2 and above") and of course nghttp2.

How would I do this with msys2?

**Comment by Alexpux** [comment]
@jeroen you need specify CFLAGS to target Windows 8.1 and try to rebuild.

**Comment by jeroen** [comment]
Which CFLAGS would I need to set?

**Comment by MehdiChinoune** [comment]
Fixed by #8469
