### ISSUE TITLE
[NOT AN ISSUE] icu for winxp

### ISSUE THREAD

**Issue by KrullBorg** [msys2/MINGW-packages#3627]
if someone needed i patched latest icu to work (build/run) under winxp

http://saetta.ns0.it/gitweb?p=msys2;a=tree;f=packages/mingw-w64-icu;h=fb58b8ce95d1b907f0c0b4bae06c1231717707da;hb=HEAD

**Comment by lazka** [comment]
I guess it doesn't matter now if this is open or closed, so closing :)
