### ISSUE TITLE
 ERROR: options array contains unknown option '!emptydirs !strip'

### ISSUE THREAD

**Issue by jeroen** [msys2/MINGW-packages#365]
When building `mingw-w64-v8` I keep getting this error:

``` bash
Jeroen@Jeroen-Windows ~/MINGW-packages/mingw-w64-v8
$ makepkg-mingw
==> ERROR: options array contains unknown option '!emptydirs !strip'
```

**Comment by mingwandroid** [comment]
@jeroenooms any update on this?

**Comment by jeroenooms** [comment]
I guess we can close this. I ended up rebuilding V8 with msys and a version from mingw builds that was compiled with `sj0` instead of `seh` exceptions.

I would still be very interested to see if we can support alternative mingw compilers in msys2.

**Comment by mingwandroid** [comment]
Ok thanks.

You can make your own repositories of packages with software compiled however you want, but we'll not do that.

We've picked what we consider to be the best compiler configurations for MSYS2 so packages that are part of the "MSYS2 distribution" will always be compiled with these. Mixing and matching them is not possible and providing alternatives is confusing and not a worthwhile way for us to spend our time.

SJLJ is slower than dw2 and SEH. IMHO you should work on convincing the R project to switch to MSYS2 and our toolchains.

**Comment by mingwandroid** [comment]
Also, you should have no problem with using the MSYS2 shell for your libv8 project. It's just a POSIX environment; you're free to install whatever compilers you want into that environment and ignore MSYS2 distribution's toolchain packages.

**Comment by jeroenooms** [comment]
I had a very hard time configuring msys2 to use external compilers and linkers. I guess the easiest way would be to create an actual `mingw-w64-i686-sjlj-toolchain` package.

I raised the suggestion of switching compilers in the R community, but the told that they would only consider if they would be able to build the entire package (including the shell, installers, etc). They don't want to be dependent on anyone in case you guys abandon the project. Are there instructions somewhere?
