### ISSUE TITLE
why is Go not updated even if this repository's have been updated?

### ISSUE THREAD

**Issue by taketori** [msys2/MINGW-packages#3692]
I have tried `pacman -Syy` again and again, but `pacman -Ss go` always showes `mingw64/mingw-w64-x86_64-go 1.9.1-1`.
 How do you obtain go 1.10.1 on mingw64? does your pacman work well or do you usually `git clone & makepkg`?
 Any ideas / hints are welcome.

cf. my mirrorlist.mingw64 is like below.
```
##
## 64-bit Mingw-w64 repository mirrorlist
##

## Primary
## msys2.org
Server = http://repo.msys2.org/mingw/x86_64
Server = https://downloads.sourceforge.net/project/msys2/REPOS/MINGW/x86_64
Server = http://www2.futureware.at/~nickoe/msys2-mirror/mingw/x86_64
```
With this, pacman showes the newest version of another packages.  (e.g. mingw64/mingw-w64-x86_64-nodejs 8.11.1-1 )

**Comment by Alexpux** [comment]
@taketori because it not builded and uploaded
If you cant find new version in repository then probably it have issues with building or not builded for other reasons

**Comment by umarcor** [comment]
I think this issue can be closed. The go package was updated since then.
