### ISSUE TITLE
wassert.c not found -- mingw-w64-crt-git package

### ISSUE THREAD

**Issue by battaglia01** [msys2/MINGW-packages#3715]
I'm running Windows 10, and trying to get MSYS2 MinGW-w64 to work with Eclipse 4.7.3a CDT. My main issue is that I'd like to set a breakpoint on `assert()`. Doing so gives the following message in Eclipse:

> Can't find a source file at "C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/misc/wassert.c"

Note the path is `C:/repo/...`, which must be cruft from some maintainer's local repo directory.

The file `wassert.c` is located online at the `mingw-w64-crt` repository, which can be found here: https://github.com/Alexpux/mingw-w64/tree/master/mingw-w64-crt

The repository appears as `mingw-w64-crt-git` here on the MinGW list: https://github.com/Alexpux/MINGW-packages

However, this package is not in pacman for the MSYS2 or MinGW shells:
```
$ pacman -Ql mingw-w64-crt-git
error: package 'mingw-w64-crt-git' was not found
```

There does, however, exist the package `mingw64/mingw-w64-x86_64-crt-git`, but this package does not contain the file `wassert.c`.

Where is this file located? How do I install the relevant package?

**Comment by Alexpux** [comment]
@battaglia01  binary packages don't contain source files that ````*.c```` files is.

**Comment by battaglia01** [comment]
Thanks. Having the source is helpful for debugging, as mentioned. What is the proper directory for the source to go in?

**Comment by Alexpux** [comment]
See source URL in PKGBUILD.
When you build package with makepkg sources downloading and extracting in arc subdirectory

**Comment by MehdiChinoune** [comment]
[Not a bug](https://github.com/msys2/MINGW-packages/issues/3715#issuecomment-389441564)
