### ISSUE TITLE
Running npm from PKGBUILD stops makepkg

### ISSUE THREAD

**Issue by peterbud** [msys2/MINGW-packages#3813]
I'm not sure whether it's a problem of `npm`(I guess) or `makepkg `(less likely).

**Symptom:**
If you have in your PKGBUILD an `npm`call (like `npm install`), `makepkg `executes it properly, but then stops without any error message.

Here is a minimal example: https://github.com/peterbud/npm-test

When running this, you see the following:
```
$ MINGW_INSTALLS=mingw64 makepkg-mingw -sCLf
==> Making package: mingw-w64-test 1.0-1 (Wed, May 23, 2018  6:44:30 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found package.json
==> Validating source files with sha256sums...
    package.json ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
==> Starting prepare()...
==> Starting build()...
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN

```
Even though `npm `exits with 0, makepkg stops. What I have also noticed, that when running this, the logpipe file is left open. 

Any idea how this can be fixed (most likely on `npm `side)?

**Comment by peterbud** [comment]
@dscho , @Alexpux  - any idea?

**Comment by dscho** [comment]
Can you trace this? Like, `MINGW_INSTALLS=mingw64 bash -x "$(which makepkg-mingw)" -sCLf`? I somehow doubt that it is `npm` that is stopping you.

**Comment by stahta01** [comment]
A guess is that npm does not like the terminal or thinks it is not being ran in a terminal with logging is being done. This is a wild guess on my part. Tim S.

**Comment by MehdiChinoune** [comment]
nodejs is no longer available.
