### ISSUE TITLE
GDB ImportError: No module named libstdcxx.v6.printers

### ISSUE THREAD

**Issue by apo126** [msys2/MINGW-packages#383]
GNU gdb (GDB) 7.6.2
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
(gdb) Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named libstdcxx.v6.printers
d:\msys\mingw64\bin../etc/gdbinit:6: Error in sourced command file:
Error while executing Python code.

**Comment by ignativs-reilly** [comment]
I have the same problem. gdbinit says gcc version 4.9.2. I use msys2.

**Comment by Alexpux** [comment]
Why you post here and in mingw-builds at the same time?

**Comment by ignativs-reilly** [comment]
Sorry, after some hours trying to solve that I beging to ask every time I saw someone with the same issue, It´s wrong to post in both places? I'm new in this.

**Comment by Alexpux** [comment]
What toolchain you use? From mingw-builds or from msys2?

**Comment by ignativs-reilly** [comment]
msys2. I try with gdbinit to correct the path but nothing.

**Comment by ignativs-reilly** [comment]
I install gdb from mingw-builds and now works fine.

**Comment by sonictk** [comment]
I am also experiencing this issue, and the gdbinit file already has the version set correctly:

```
python
import sys
sys.path.insert(0, sys.path[0] + '/../../gcc-4.9.2/python')
from libstdcxx.v6.printers import register_libstdcxx_printers
register_libstdcxx_printers (None)
end
```
