### ISSUE TITLE
QT creator 32 bit kits use gdb 64 bit that causes error when debugging 32 bit code.

### ISSUE THREAD

**Issue by vasili111** [msys2/MINGW-packages#3883]
Both static and nonstatic versions of MinGW-w64 32bit kits for QT Creator use gdb 64 bit. That causes an error when debugging 32 bit code in QT Creator 32 bit. More about that issue here:  https://stackoverflow.com/questions/50593191/how-to-change-debugger-in-qt-creator/50619772
If I clone32 bit kits and change debugger to gdb 32 bit then debugging works fine. Please change in 32 bit kits default debugger from 64 bit gdb to 32 bit gdb.

**Comment by Alexpux** [comment]
@vasili111 I dont know what is wrong and how to change it. For me all looks ok:
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-qt-creator/qt-creator-x86_64.install#L145

**Comment by vasili111** [comment]
1. You linked 64 bit QT Creator version. Problem is in 32 bit QT Creator version.
2. In QT creator Tools > Options > Build and Run > Kits which version of gdb do you see in 32 bit kits? Here is a screenshot from my system: https://i.stack.imgur.com/lxcLz.png
3. Also, I use static versions of qt. Maybe it is a reason?

**Comment by Alexpux** [comment]
@vasili111 well for 32-bit QtCreator script looks ok too: https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-qt-creator/qt-creator-i686.install#L145

**Comment by MehdiChinoune** [comment]
there is no qt-creator for 32bit anymore.
