### ISSUE TITLE
gcc 8.1.0: .seh_savexmm offset is negative

### ISSUE THREAD

**Issue by jeroen** [msys2/MINGW-packages#3893]
I tried building libpng using gcc-8.1.0 and get the error below on x64 (i686 is fine). It was fine with gcc 7.3.0. Is this likely a bug in libpng or in gcc-8.1.0?

```
libtool: link: ranlib .libs/libpng16.a
libtool: link: ( cd ".libs" && rm -f "libpng16.la" && cp -pR "../libpng16.la" "libpng16.la" )
/bin/sh ./libtool  --tag=CC   --mode=link x86_64-w64-mingw32-gcc  -march=x86-64 -mtune=generic -O2 -pipe  -pipe -o pngfix.exe contrib/tools/pngfix.o libpng16.la -lz 
/bin/sh ./libtool  --tag=CC   --mode=link x86_64-w64-mingw32-gcc  -march=x86-64 -mtune=generic -O2 -pipe  -pipe -o pngtest.exe pngtest.o libpng16.la -lz 
{standard input}: Assembler messages:
{standard input}:23367: Error: .seh_savexmm offset is negative
{standard input}:23368: Error: .seh_savexmm offset is negative
{standard input}:23373: Error: .seh_savexmm offset is negative
make[1]: *** [Makefile:1159: contrib/libtests/pngvalid.o] Error 1
```
See [full log](https://ci.appveyor.com/project/jeroen/rtools-packages/build/1.0.118/job/5tbtnv4hyodko3mx).

**Comment by Alexpux** [comment]
@jeroen someone already ask on libpng
https://sourceforge.net/p/libpng/bugs/280/

**Comment by jeroen** [comment]
Ah good find. Still don't know if this is a bug in libpng, or in the assembler.

**Comment by Alexpux** [comment]
try first rebuild mingw-w64 headers/crt with gcc 8

**Comment by jeroen** [comment]
OK I am going to be rebuilding headers with gcc 8.

In general, what order of rebuilding do you use for a major upgrade of gcc? First `mingw-w64-gcc` and then `mingw-w64-headers-git` and `mingw-w64-headers-crt` and `mingw-w64-headers-tools` and `mingw-w64-headers-libmangle`?

Do I also need to rebuild `mingw-w64-winpthreads-git` and `mingw-w64-windows-default-manifest`?

**Comment by jeroen** [comment]
Hmm I tried rebuilding crt and headers and a bunch of other things, but still the error remains.

**Comment by jeroen** [comment]
I found that the error does not appear if I compile without optimization, or with `-flto`. What could be the problem here:

<img width="581" alt="screen shot 2018-06-04 at 4 50 20 pm" src="https://user-images.githubusercontent.com/216319/40924466-96406226-6817-11e8-9536-9edd61bec831.png">

**Comment by Alexpux** [comment]
@jeroen that is probably LTO issue then

**Comment by jeroen** [comment]
> @lhmouse: With LTO enabled, assembly is generated during link time instead of compile time.

Is this probably just a bug in the libpng configuration then?

**Comment by lhmouse** [comment]
I know little about SEH. :<

**Comment by jeroen** [comment]
I have rebuilt a few dozen libs and libpng is the only library with this issue. So fortunately this may just be a bug in libpng and not a general regression in gcc.

**Comment by daniel-starke** [comment]
The issue was fixed in the [GCC PR86048](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86048).

**Comment by jeroen** [comment]
Thanks! I don't fully understand the bug. Do you think this will cause 8.1.0 to be unreliable for other libraries using seh? So far it has only appeared to us for libpng.

**Comment by daniel-starke** [comment]
I do not think that this is directly related to SEH. Take a look at the [created test case](https://gcc.gnu.org/viewcvs/gcc/trunk/gcc/testsuite/gcc.target/i386/pr86048.c?view=markup&pathrev=261544).

**Comment by lazka** [comment]
Let's close this then
