### ISSUE TITLE
intel-tbb: warnings "has different size"

### ISSUE THREAD

**Issue by jeroen** [msys2/MINGW-packages#3904]
When linking to TBB I always see this warning:

```
task.o: duplicate section `.rdata$_ZTIN3tbb4taskE[__ZTIN3tbb4taskE]' has different size
arena.o: duplicate section `.rdata$_ZTIN3tbb4taskE[__ZTIN3tbb4taskE]' has different size
scheduler.o: duplicate section `.rdata$_ZTIN3tbb4taskE[__ZTIN3tbb4taskE]' has different size
```

You can also see this warning in the [appveyor build log for mingw-w64-intel-tbb](https://ci.appveyor.com/project/Alexpux/mingw-packages/build/1.0.5789).

Searching online suggests that this may be due to different pieces being compiled with different `arch` or optimizations, but I have not been able to find the problem.

**Comment by jeroen** [comment]
@daniel-starke you seem to know gcc a bit. Any guess where this could come from?

**Comment by daniel-starke** [comment]
Such errors usually happen in combination with some C++ template instantiation. E.g. if you have a templated function in your header file and multiple compilation units include this header but producing slightly different resulting version of the function with the same signature.
Of course, as you said, this can also happen if you build the same function with different compile flags or compiler versions. E.g. you have a function in your header file which may get compiled in each compile unit including this function. Now you compile your library which also includes this header file. Later you build your program with a different compiler/compile flags and also include this header file. You get the function from the header file in two version and the linker will complain about it.

**Comment by jeroen** [comment]
Right, but in this case all units seem to be compiled with the same flags. So I don't understand where the discrepancies arise.

**Comment by daniel-starke** [comment]
Well, you could have a look and compare assembly of those symbols. But it only seems to affect the typeinfo for tbb::task as far as I can see.

**Comment by jeroen** [comment]
Still seeing these warnings with the latest build: https://ci.appveyor.com/project/Alexpux/mingw-packages/builds/19935179/job/hjpc3bewcoviuef8

It also appears for anything linking against tbb.

**Comment by Biswa96** [comment]
Is this issue still valid now?
