### ISSUE TITLE
Updated mingw-w64-angleproject package doesn't work

### ISSUE THREAD

**Issue by matanui159** [msys2/MINGW-packages#3918]
Yesterday I updated from 2.1.r6846-1 to 2.1.r8455-1 and now I get the error:

```
Assertion failed!

Program: <my program I'm working on>
File: ../src/libANGLE/Context.h, Line 1601

Expression: mSavedArgsType->hasDynamicType(T::TypeInfo)
```

**Comment by Alexpux** [comment]
@matanui159 I think you need to speak with developers of  angleproject. I'm just build it

**Comment by matanui159** [comment]
https://bugs.chromium.org/p/angleproject/issues/detail?id=2530&q=mSavedArgsType&colspec=ID%20Type%20Status%20Priority%20Feature%20Owner%20Summary

It seems to have already been reported (twice by the sounds of the original message). As a work around it seems you can either enable `NDEBUG` or patch out that specific `ASSERT`.

**Comment by revelator** [comment]
latest git version changed build system, so broken again :/
seems it now uses googles own build tool.

**Comment by MehdiChinoune** [comment]
angleproject no longer available
