### ISSUE TITLE
GCC-git 8.1 build is broken

### ISSUE THREAD

**Issue by Alex-Gamper** [msys2/MINGW-packages#3949]
Hi Alexpux

As you are aware, the gcc-8-branch build of gcc fails due to a error relating to using LTO when
linking gnat.exe (aka ADA) .Do you have any ideas what's causing the problem ? I am happy to assist/test
if you are short on time

Thanks

Alex

**Comment by Alexpux** [comment]
@Alex-Gamper we have the same issue with 8.1.0 release. Problem that xg++ cant find liblto_plugin-0.dll as it look for it in wronf folders.
I dont know what cause this and dont have time to fix it

**Comment by Alex-Gamper** [comment]
Hi Alexpux

I agree with your assessment, I'll try and look thru the gcc/gnat changelogs to see if I can find the cause!

Alex

**Comment by Alex-Gamper** [comment]
Hi Alexpux
The build works if you disable bootstrap!  I know did may not help, but at least I can get a build.
Is building with bootstrap disabled 3 times with intervening installs the same as doing a full
bootstrap?
