### ISSUE TITLE
debugger error_start support

### ISSUE THREAD

**Issue by frederich** [msys2/MINGW-packages#4]
Please bring `error_start` back to live.

I've a program which generate a SIGSEGV. I want to create automatically a core dump. On Linux I set `ulimit -c unlimited`. What's the right way on MSYS2. I've tried:
```
set MSYS=error_start:%WD%dumper.exe -d -c %1 %2
```
but nothing happens.

**Comment by mingwandroid** [comment]
This issue should be in MSYS2-packages since the feature is/was implemented in msys2-runtime. Please create it there and close this one.

**Comment by frederich** [comment]
moved to [msys2-package](https://github.com/msys2/MSYS2-packages/issues/1)
