### ISSUE TITLE
GTK+ 2.24: svg support fix

### ISSUE THREAD

**Issue by jernejs** [msys2/MINGW-packages#4046]
Some systems seem to have broken (or missing) .svg mime type, which results in GTK+ not handling .svg icons properly. Would it be possible to include this patch: <https://gitlab.gnome.org/GNOME/gimp/commit/3ebeef9fedb7f32e6bdee2ba440acd567f1ccb5e> from GIMP to work around the problem?

**Comment by Alexpux** [comment]
@jernejs as I see it is about Windows XP, isn't it? We dont support Windows XP anymore

**Comment by jernejs** [comment]
The comments are misleading, it's about Windows 7. It's actually easy to reproduce the problem with GIMP - install 2.10, go to Registry, rename HKEY_CLASSES_ROOT\.svg to something else and start GIMP - all icons will appear as 2x2 pixel blocks. And while it's clear that this is a problem with end-user systems, it'd still be nice if this workaround was in place.

Here's the actual GIMP bug report: https://gitlab.gnome.org/GNOME/gimp/issues/1563

**Comment by Alexpux** [comment]
@jernejs you can create pull request in this repo with patch that you want to merge

**Comment by lazka** [comment]
@jernejs another possibility is if you try upstreaming the patch to gtk 2.24. It's still maintained to some degree.

This way we can have more confidence in backporting the patch etc.

**Comment by lillolollo** [comment]
@cbrt64 Please can you submit your patch here?

**Comment by cbrt64** [comment]
I hope this can simplify your building the GIMP installer, @jernejs. :)

**Comment by lillolollo** [comment]
@cbrt64 Thanks maybe you can open a merge request on upstream too though GTK 2 seem almost dead

**Comment by lazka** [comment]
Closing, because of #5654
