### ISSUE TITLE
Npm does not call nodejs via winpty

### ISSUE THREAD

**Issue by HsingYun** [msys2/MINGW-packages#4086]
ctrl-c will be not handled properly if uses node without winpty

$vim /mingw64/bin/npm
...
NODE_EXE="$basedir/node.exe"
...

There is no winpty added in npm script

**Comment by lazka** [comment]
The same is true for all programs sadly. You can do "winpty bash" to get a shell where winpty is active all the time.

**Comment by peterbud** [comment]
Could also #3813 a related problem?

**Comment by zhkailing** [comment]
But winpty was taken into account by node‘s executable file.

it's wrapper script.

`#!/usr/bin/env bash

NODE_EXE="$( dirname ${BASH_SOURCE[0]} )/node.exe"

if [ -t 0 -a -t 1 ]; then
  /usr/bin/winpty $NODE_EXE "$@"
else
  exec $NODE_EXE "$@"
fi
`

**Comment by MehdiChinoune** [comment]
nodejs is no longer available
