### ISSUE TITLE
[Request] knewstuff + ktexteditor

### ISSUE THREAD

**Issue by NebuHiiEjamu** [msys2/MINGW-packages#4091]
I've been wanting to build the Kate text editor with MinGW-w64, and according to dependencies, this repo seems to be missing knewstuff and ktexteditor. I'm not sure if they've been overlooked or if mingw-w64 can't build them. There is a built binary for Windows available, but it's almost a year old as opposed to the latest source release that's available. As of this post, that version would be 18.04.1

**Comment by MehdiChinoune** [comment]
knewstuff and ktexteditor are both available.
