### ISSUE TITLE
libxml2 (sys/select.h: No such file or directory)

### ISSUE THREAD

**Issue by Necrosss** [msys2/MINGW-packages#4094]
Hello.

make[4]: enter directory «/c/Users/Necrosss/Desktop/minGW/libxml2/mybuild/python»
  CC       libxml.lo
In file included from C:/msys32/usr/include/python2.7/Python.h:58,
                 from ../../python/libxml.c:14:
C:/msys32/usr/include/python2.7/pyport.h:351:10: fatal error: sys/select.h: No such file or directory
 #include <sys/select.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [Makefile:624: libxml.lo] Error 1

===
What am I doing wrong ?

**Comment by Alexpux** [comment]
You build with MSYS compiler instead MINGW

**Comment by Necrosss** [comment]
What "compiler" ? GCC ?

**Comment by Alexpux** [comment]
Yes

**Comment by Necrosss** [comment]
This is strange. My GCC already belongs to MINGW.
C:\mingw-w64\i686-8.1.0-win32-dwarf-rt_v6-rev0\mingw32\bin\gcc.exe
I do not have a gcc in MSYS.

Or maybe problem with my python ?
I install python for MSYS (With this command: "pacman -S python")

**Comment by lazka** [comment]
you probably want to use "mingw-w64-i686-python2"
