### ISSUE TITLE
gcc -pie and -fpie options produced bogus binaries

### ISSUE THREAD

**Issue by d3vv** [msys2/MINGW-packages#4100]
simple code:

```
#include <iostream>
#include <iomanip>
#include <cstddef>
#include <cstdlib>

static void lf()
{
    // Do nothing
}

static int zsv;
static int isv = 1;

int main()
{
    int lv;
    void* mem = malloc(1);
    free(mem);
    std::cout << std::hex;
    std::cout << "Local Variable             " << (void*)&lv    << std::endl;
    std::cout << "Heap Memory                " << mem           << std::endl;
    std::cout << "Static Variable (Zeroed)   " << (void*)&zsv   << std::endl;
    std::cout << "Static Variable (Inited)   " << (void*)&isv   << std::endl;
    std::cout << "Local Function             " << (void*)&lf    << std::endl;
    std::cout << "Library Function           " << (void*)&_Exit << std::endl;
}
```

just compile it with "g++ -pie -fpie filename.cpp", run "./a.exe" and we have long run with nothing into output...

**Comment by nephatrine** [comment]
Set the entry point as well with -Wl,-e,mainCRTStartup (64-bit) or -Wl,-e,_mainCRTStartup (32-bit). The -pie/-Wl,--pic-executable flag shouldn't be neede/usedd on Windows, but unfortunately to really get ASLR to work you need it to work around a binutils issue where relocation tables are stripped.

**Comment by d3vv** [comment]
Yes, for sure - it is all about ASLR
And it is strange that most of variables has constant values into MINGW builds
Moreover it is VERY STRANGE that ALL vars are constant into Pure MSYS2

**Comment by MehdiChinoune** [comment]
Couldn't reproduce with GCC 12.2.0
