### ISSUE TITLE
mpv doesn't work

### ISSUE THREAD

**Issue by yearharvest** [msys2/MINGW-packages#4101]
Version: mingw-w64-x86_64-mpv 0.28.2-3
Symptom: mpv doesn't work at all. console log are:

    Assertion failed!
    
    Program: C:\msys64\mingw64\bin\mpv.exe
    File: ../src/libANGLE/Context.h, Line 1601
    
    Expression: mSavedArgsType->hasDynamicType(T::TypeInfo)

**Comment by Venoox** [comment]
Same problem here

**Comment by Alexpux** [comment]
@yearharvest  @Venoox I\m upload new angleproject package. Try it

**Comment by yearharvest** [comment]
anothor error
<pre>Assertion failed!

Program: C:\msys64\mingw64\bin\mpv.exe
File: ../src/libANGLE/Context.h, Line 1670

Expression: mSavedArgsType->hasDynamicType(T::TypeInfo)<pre>

**Comment by Biswa96** [comment]
mpv is working fine now.
