### ISSUE TITLE
binutils-2.31.1 gold linker broken with plugins enabled.

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#4104]
Seems gold has plugin support as well, but none that work with windows.
Unfortuantly golds plugin support also gets enabled when we specify plugin support so the build fails.

**Comment by revelator** [comment]
The problem is dlfcn-win32, SYSTEMTIME and FILETIME comes from minwinbase.h which is included by winbase.h and finally by windows.h, dlfcn.h includes neither and the gold plugin seems to assume that it does so these end up undefined if dlfcn-win32 is installed with the current patchset.
moving the dlfcn.h header out of the place fixes things but it would probably be better with a more permanent fix.

**Comment by Alexpux** [comment]
@revelator I dont install dlfch-win32 at all in system because in this case most packages will build with it.

**Comment by revelator** [comment]
So should we remove it from packages ?

**Comment by Alexpux** [comment]
@revelator I will leave it in packages but I dont recomment to install it if you realyy dont need it. I will not build packages that depends on this library

**Comment by revelator** [comment]
Seems resonable, it was mostly intended as a tool for porting some stubborn packages anyway.

**Comment by revelator** [comment]
Hmm small whoops, previous binutils linked with dlfcn-win32 worked fine with liblto_plugin.dll copied to /mingw<arch>/lib/bfd-plugins, using the builtin version in the new 2.31.1 build yields unable to load dll :s
so it seems to be broken or ?.

**Comment by Alexpux** [comment]
@revelator As I know plugins not working without dlfcn-win32

**Comment by revelator** [comment]
Ah damn, i wonder what changed from previous versions since this no longer works.
Maybe i should ready a patch fixing up binutils dlfcn replacement functions based on dlfcn-win32, would this be considered apropriate  ?. LTO builds work much better when this plugin works so id really like to have it back.

**Comment by Alexpux** [comment]
@revelator create pull request and i will look

**Comment by revelator** [comment]
Ok got it working, one small snag though, it requires linking in the psapi library and binutils dont link this in by default, so where would be the best place to add this in the autotools chain ?.

**Comment by Alexpux** [comment]
@revelator possibly need to add additional library in configure script

**Comment by revelator** [comment]
Not having much luck finding a good place to getting this library in yet.
I have a hunch that i might need to do some additions to configure.ac and then rebuild the autotool toolchain, the only places i found where i could plug it in are to specific to some code, and atm i need this library linked in with bfd ld ranlib and gold. Besides that it works extremely well now if i just link psapi in globally.

**Comment by revelator** [comment]
Uh oh... anyone remember the bug in binutils-2.26 with to many files open ? guess what its back.
To make sure it had nothing to do with my fixing the dlfcn replacements for plugin support i tried downloading an unmodified version from here and it also has this. 

Try building clang, the error comes allmost at the end of the build. 
Had to downgrade to 2.25 to be able to build clang.

**Comment by revelator** [comment]
[0030-fix-plugin-support.zip](https://github.com/Alexpux/MINGW-packages/files/2636104/0030-fix-plugin-support.zip)

finally got it done, it became a bit messy but now binutils support loading plugin dll's like the lto_plugin.dll if it is placed in /mingw*/lib/bfd-plugins. 

The dlfcn code was taken from dlfcn-win32 because the inbuilt minimal version does not support loading plugins from external folders.

**Comment by mati865** [comment]
Gold linker doesn't use BFD and supports only ELF format, porting it would need a lot of effort. I doubt it'd be worth the time.

**Comment by revelator** [comment]
true i could probably remove the plugin support from the gold linker to simplify the patch a bit. 
Strangely even though bfd has plugin support it seems ld also needs the same code which is kinda overkill.
Ill see if i can come up with a way to simplify things a bit, but in the meantime feel free to use my patch if you like.

**Comment by MehdiChinoune** [comment]
gold linker is no longer supported/shipped on Windows.
