### ISSUE TITLE
Ruby - gcc 8.2.0 failure, 7.3.0 ok

### ISSUE THREAD

**Issue by MSP-Greg** [msys2/MINGW-packages#4136]
I've opened an issue with ruby core, but building ruby trunk/head/master using gcc 8.2.0 is generating a test failure.  Using gcc 7.3.0, all tests pass.

Currently, ruby trunk/head/master is built and tested using Travis, mswin (vc12) and MinGW.  The full ruby test system has four test suites, and the failure is occurring in one that I don't ever recall seeing a failure in.

When I determine the cause, I'll be back...  Thanks, Greg

Off topic - Ruby builds with gdbm, and all ok with 1.17.  Thanks for your work on 1.16 (adding `--enable-libgdbm-compat`)...

**Comment by MehdiChinoune** [comment]
Is it fised with gcc 12.2.0 or not?

**Comment by MSP-Greg** [comment]
This may have been a Ruby issue, as a major jump in gcc can certainly cause issues.

Regardless, this is very old, and as I recall, Ruby has built fine with several of the more recent gcc versions.

Hence, closing...
