### ISSUE TITLE
Numerous shebangs incorrect/misleading - mostly python -

### ISSUE THREAD

**Issue by aabatpurdue** [msys2/MINGW-packages#4147]
This bug report covers/duplicates a number of other bug reports reporting problems with shebangs (I used filter=shebang to find them).  Below is a script that I call 'showshebang' that can be used to extract ALL shebangs.  I used it to examine the  msys2, mingw32 and mingw64 "bin" and "lib" directory trees as:
 `showshebang /mingw32/bin /mingw32/lib /mingw64/bin /mingw64/lib /bin /usr/lib`
Some of the interesting results include:
```
#!C:\building\msys64\mingw32/bin/python3.7.exe   /mingw32/bin/2to3-3
#!C:\building\msys64\mingw32/bin/python3.7.exe   /mingw32/bin/pyvenv
#! /usr/local/bin/python                      /mingw64/lib/python3.7/cgi.py
#!C:/msys64/mingw64/bin/python3.exe           /mingw64/bin/pip3-script.py
#!/usr/bin/env python                         /mingw64/lib/python3.7/site-packages/pip/_internal/__init__.py
```
I am not sure about the backslashes (\\) but there is no 'building' on my box.  The second from last example probably works. Actually, the last example is both correct and incorrect.  It uses '#!/usr/bin/env ...' which is correct and is what I consider to be "the correct way" to use the shebang mechanism.  It also uses 'python' which is incorrect since there is no 'python' in the "bin"s.

There are a number of shebangs used that will not work.  It is my opinion that the entire shebang menagerie should be examined, cleaned, corrected and made consistent.

-- Thanks,
--   aabatpurdue
```
#!/usr/bin/env bash
typeset    files
typeset    dirs=/dev/null
(( $# )) || exit 1
while (( $# )); do
  if [[ -f ${1} ]]; then
    files="${files} ${1}"
  elif [[ -d ${1} ]]; then
    dirs="${dirs} ${1}"
  fi
  shift
done
{ for x in ${files}; do
    echo ${x};
  done;
  find ${dirs} -type f;
} |
  sed -e 's,^,",' -e 's,$,",' |
    xargs -n 100 gawk -e '
 { if ($0 ~ /^#\!/ )
     printf ("%-45s %s\n", $0, ARGV[ARGIND]);
     nextfile;
 }
'
```

**Comment by aabatpurdue** [comment]
Just out of curiosity, why can't the github "selecting them" mechanism accept files with '.sh' suffixes?  The script above would look a lot nicer if almost all of the blank characters had not been removed.

**Comment by lazka** [comment]
Yeah, a bit of a mess.

These are possible afaik:
```
#!/mingw64/bin/python3
#!/mingw64/bin/python3.exe
#!/usr/bin/env python3
#!/usr/bin/env python3.exe
#<install-path>/python3.exe -> results in "C:/msys64/mingw64/bin/python3.exe" for example
```
Since we patch many of those it would be good to decide on one of them.

There are two uses cases I can think of to consider:
* Executing a mingw script in a msys shell (env wont work)
* Executing a script with the official cpython launcher (/mingw64 wont work)

**Comment by aabatpurdue** [comment]
@lazka - you said
   "Executing a mingw script in a msys shell (env wont work)"
but that is entirely dependent on the PATH.  Unfortunately, I guess you cannot guarantee that.

**Comment by lazka** [comment]
> "Executing a mingw script in a msys shell (env wont work)"
> but that is entirely dependent on the PATH. Unfortunately, I guess you cannot guarantee that.

yeah, that assumes you call /mingw64/bin/foo.py without PATH set. I'm not saying that that's something we should support, it's just something I remember coming up last time this was discussed.

**Comment by Alexpux** [comment]
I think all shebangs must be fixed with full Windows path in post install scripts

**Comment by lazka** [comment]
> I think all shebangs must be fixed with full Windows path in post install scripts

Just curious, why do you prefer this over the other shebangs?

**Comment by Alexpux** [comment]
With full Windows path you can call python script under shell and it run with proper python, in other case you must care about right interpreter to call

**Comment by Alexpux** [comment]
Also some packages have wrapper around python scripts and if script doesn’t have proper path you can’t run this wrapper under windows

**Comment by Biswa96** [comment]
Most of the incorrect shebang were fixed. Packages are now moved from python-setuptools and the `*-script.py` are removed also.
