### ISSUE TITLE
Using these on Linux?

### ISSUE THREAD

**Issue by Janrupf** [msys2/MINGW-packages#4159]
I know that this was made for Windows and MinGW, but since this is a format for a linux packagemanager (pacman) and MinGW seems to function the same on Linux, could it be possible to somehow download these packages and install them in Linux?

**Comment by Alexpux** [comment]
@Janrupf why you need it on Linux?

**Comment by Janrupf** [comment]
Because I use Linux... and there is no good way to cross compile gtkmm3 programs.

**Comment by mati865** [comment]
@Janrupf to put it simply: those packages are build for Windows host and Windows target, what you are asking for is Linux host and Windows target. Wine won't help here because it doesn't work with Cygwin anymore.

**Comment by Janrupf** [comment]
Aren't these packages downloaded and then compiled? If so it should work.

**Comment by lazka** [comment]
There is a gtkmm3 package by @Adsun701  in the AUR: https://aur.archlinux.org/packages/mingw-w64-gtkmm3

**Comment by Janrupf** [comment]
I'm using Ubuntu, thats why I ask. I think I'm going to experiment a bit and report back what my results are.

**Comment by jhasse** [comment]
You can use Arch via Docker on Ubuntu.

Fedora also has a MinGW gtkmm package btw: https://apps.fedoraproject.org/packages/mingw-gtkmm30
