### ISSUE TITLE
MSYS2: ldd returns no names for missing libraries

### ISSUE THREAD

**Issue by luckyluc67** [msys2/MINGW-packages#4164]
Hello,

I'm trying to create a 64bit DLL library using M§YS2. After 'configure' with --enable-64bit,, 'make' creates the objects without any problem, and :

g++ -shared -Wall -o tclcluspack01.dll 2means.o GAPkmeans.o TclDataIn.o TclDataOut.o alignment.o apprentissage.o apprentissageKernels.o bionj.o densityEstimation.o dissimilarities_clustering.o divide.o dpc.o ecrfi.o eigenMixtureModels.o emGaussian.o emKernels.o emSimplex.o emSphericalGaussian.o filtering.o kNearestNeighbours.o kernelKmeans.o kernelMixtureModels.o kernels.o kmeans.o lecfi.o mainClusPackTcl.o mainKernelBayesClassifier.o matrice.o mds.o mixtureModels.o normalized_2cut.o prediction.o predictionKernels.o pretraitements.o secatorbionj.o space.o spectralClustering.o svd0.o symeig.o tools.o treebionj.o treecut.o treedpc.o treeward.o wardbionj.o weighting.o -L./lib -lRmath-julia  "C:/TclTk64-8.6.7/lib/libtclstub86.a" -static-libgcc

(The 'Rmath-julia.dll' library builds perfectly, and 'ldd' shows no error.)

The above command returns no errors. But the library can't be loaded in my main program (Tcl) and 'ldd' gives :

$ ldd tclcluspack01.dll
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffcc97f0000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ffcc78b0000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ffcc5e50000)
        ??? => ??? (0x6a4c0000)
        ??? => ??? (0x7ffcc6fb0000)

As you can see, the 'Rmath-julia' does not appear in the list, and the "????" doesn't tell me which libraries are missing.

I've checked that libtclstubs86.a, Rmath-julia and the resulting tclcluspack01.dll are all 64bits. I verified my MSYS2 distribution is up-to-date pacman -Syu).

1) Why 'ldd' is not returning the names of missing libraries ?
2) what may be wrong in my linking ?
3) Is there packages I am missing in MSYS2 ?

Many thanks in advance !!
Luc

**Comment by lazka** [comment]
There is `pacman -S mingw-w64-x86_64-ntldd` which provides ntldd.exe

**Comment by MehdiChinoune** [comment]
Use ntldd instead.
