### ISSUE TITLE
WebKitGTK linked to old version of ICU

### ISSUE THREAD

**Issue by awhatson** [msys2/MINGW-packages#4318]
The update to `mingw-w64-{i686,x86_64}-icu-62.1-1` has broken `mingw-w64-{i686,x86_64}-webkitgtk{2,3}` because those packages are linked to `libicu*61.dll` instead of `libicu*62.dll`.  Probably the webkit packages just need to be rebuilt against the new ICU.

This is basically the same problem as #4290

**Comment by Alexpux** [comment]
@awhatson it not possible to rebuild webkitgtk now. I'm thinking about removing this package as I dont have time to support it

**Comment by adrpo** [comment]
@awhatson: you can just get the older icu dlls from:
https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/mingw-w64-x86_64-icu-61.1-1-any.pkg.tar.xz
https://sourceforge.net/projects/msys2/files/REPOS/MINGW/i686/mingw-w64-i686-icu-61.1-1-any.pkg.tar.xz
and the exe will work. You will have a freakish system for a while until Alexpux can fix the issues (if is possible).

**Comment by spl1inter** [comment]
Second Alex comments, no to mixing merging unsupported DLLs.

**Comment by revelator** [comment]
I can still build it but not easily.
Problems: 
Crashes a lot, unless i use specific build flags, then it works.
Likes to use clang if detected, have to force gcc.
Package is old as sin and not secure anymore for online work, 
later versions cannot be built with MinGW64 though.

Only use i have for it as of now is gimps help system where my special build works fine, but midori will crash to no end if built with it.

**Comment by EionRobb** [comment]
is libicu*62 compatible with libicu*61?  If so, could you use https://stackoverflow.com/a/3420626/895744 to point the dependencies at the newer dll without having the hassle of rebuilding everything?

**Comment by Alexpux** [comment]
If you need it you can try change dependencies for dll locally, I will not do it. As I tell I will drop webkitgtk package as there are no maintainers for it

**Comment by lazka** [comment]
https://github.com/msys2/MINGW-packages/issues/5207#issuecomment-483400667
