### ISSUE TITLE
OpenSSL 1.1.x brokens

### ISSUE THREAD

**Issue by Alexpux** [msys2/MINGW-packages#4458]
At least next mingw packages have issues building with new openssl:
````
gdcm 
libmowgli
libwebsockets
````

**Comment by tschoonj** [comment]
I assume the following error is related:

```
checking for file conflicts...
error: failed to commit transaction (conflicting files)
mingw-w64-i686-openssl: /mingw32/share/man/man3/BN_print.3ssl.gz exists in filesystem
mingw-w64-i686-openssl: /mingw32/share/man/man3/HMAC.3ssl.gz exists in filesystem
mingw-w64-i686-openssl: /mingw32/share/man/man3/LHASH.3ssl.gz exists in filesystem
mingw-w64-i686-openssl: /mingw32/share/man/man3/MD5.3ssl.gz exists in filesystem
mingw-w64-i686-openssl: /mingw32/share/man/man3/MDC2.3ssl.gz exists in filesystem
mingw-w64-i686-openssl: /mingw32/share/man/man3/RC4.3ssl.gz exists in filesystem
mingw-w64-i686-openssl: /mingw32/share/man/man3/UI.3ssl.gz exists in filesystem
mingw-w64-x86_64-openssl: /mingw64/share/man/man3/BN_print.3ssl.gz exists in filesystem
mingw-w64-x86_64-openssl: /mingw64/share/man/man3/HMAC.3ssl.gz exists in filesystem
mingw-w64-x86_64-openssl: /mingw64/share/man/man3/LHASH.3ssl.gz exists in filesystem
mingw-w64-x86_64-openssl: /mingw64/share/man/man3/MD5.3ssl.gz exists in filesystem
mingw-w64-x86_64-openssl: /mingw64/share/man/man3/MDC2.3ssl.gz exists in filesystem
mingw-w64-x86_64-openssl: /mingw64/share/man/man3/RC4.3ssl.gz exists in filesystem
mingw-w64-x86_64-openssl: /mingw64/share/man/man3/UI.3ssl.gz exists in filesystem
Errors occurred, no packages were upgraded.
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

```

**Comment by Alexpux** [comment]
@tschoonj no it is not related

**Comment by lazka** [comment]
* opusfile -> #4460
* libsrtp -> builds fine here

**Comment by Alexpux** [comment]
Libsrtp build but without OpenSSL

**Comment by lazka** [comment]
python is also broken

**Comment by MSP-Greg** [comment]
If anyone wants to try the package I've used with Ruby:

https://ci.appveyor.com/api/buildjobs/293ujnaycuk7nv0p/artifacts/mingw-w64-x86_64-openssl-1.1.1-1-any.pkg.tar.xz

SHA256 & SHA512 are on the 'messages' tab, see:
 https://ci.appveyor.com/project/MSP-Greg/ruby-makepkg-mingw/build/messages

**Comment by peterbud** [comment]
@Alexpux : what was the problem with `wget`? For me it compiled OK

**Comment by lazka** [comment]
@iDunk5400 what's the affected package? So one can try to reproduce the issue.

**Comment by iDunk5400** [comment]
@lazka Sorry for the lack of context. Your #4462 helped shed light on what's going on. I've now modified some cmake checks in the project that was failing to build for me (unrelated to MSYS2), and now it builds fine.

**Comment by lazka** [comment]
@iDunk5400 you can probably revert that. It was an issue with the msys2 package.

I've opened #4475 and #4476

**Comment by iDunk5400** [comment]
@lazka Thank you for the info.

**Comment by Alexpux** [comment]
I'm edit fail list

**Comment by Ede123** [comment]
Another issue I'm seeing in Inkscape (linked against libpoppler which is linked against libcurl whihc is linked against libssl) when executed on the AppVeyor CI server:
![error_ci](https://user-images.githubusercontent.com/904570/46222875-f8e00b80-c351-11e8-938b-213d414cce5e.png)

Not sure what exactly is causing it yet...

**Comment by Ede123** [comment]
The issue above is not directly related to the OpenSSL update (it only made it apparent by adding a new function not available previously) but is the result of AppVeyor build images containing an older version of the OpenSSL DLLs (libssl-1_1-x64.dll / libcrypto-1_1-x64.dll) in C:\Windows\system32, see https://github.com/appveyor/ci/issues/2571

Applications will load these before even looking at the PATH variable (unless the DLL is located in the same directory as the application executable).

**Comment by MSP-Greg** [comment]
@Ede123

Sorry for not mentioning that.  I think they're the Shining Light OpenSSL-Win64 1.1.0 dll's.  Most of my CI uses binaries that link to dll's via a manifest, so only one repo's CI had the issue....

**Comment by lazka** [comment]
appveyor has been updated now: https://www.appveyor.com/updates

**Comment by lazka** [comment]
Is there anything left to do there?

**Comment by lazka** [comment]
Please open a new issue if there is.
