### ISSUE TITLE
Missing minizip.dll for libKML

### ISSUE THREAD

**Issue by habersaa** [msys2/MINGW-packages#4464]
Hi ! I just updated all my packages to the latest versions.

Now my executable does not run anymore due to a missing libminizip-1.dll.

I tried to install the minizip package, but it did not work (could not find entry point in lib, i.e. different version required). 
After investigation, it turns out that the minizip package is v2.5.2, but the required DLL is version 1.x, and it is required by libKML. So I rebuilt libKML, and during the build it automatically downloaded the sources for its minizip (v1) dependence. But once the package is built, the minizip.dll used for the build is *not* included in the package, which causes this issue. 
I used the work-around to manually copy the minizip.dll (built while building libKML) in the mingw64/bin directory to make it work.

**Comment by Alexpux** [comment]
@habersaa need to fix libkml for minizip v2

**Comment by stahta01** [comment]
An easier solution might be to use a static minizip v1

Tim S.

**Comment by illwieckz** [comment]
The issue is that the minizip package provided by mingw is not minizip, it's a brand new project historically based on minizip that is not source-compatible anymore. The issue was introduced in e1e045dfc9933780ae258a2465d907ebc73c331e. See https://github.com/nmoinvaz/minizip/issues/333.

**Comment by illwieckz** [comment]
thanks! :+1:
