### ISSUE TITLE
Problems building  mingw-w64-pyside2-qt5

### ISSUE THREAD

**Issue by thor8** [msys2/MINGW-packages#4507]
Building mingw-w64-pyside2-qt5 stops while checking dependencies with:
Fehler: Ziel nicht gefunden: mingw-w64-x86_64-python2-shiboken2-qt5=5.11.0

Trying to build mingw-w64-shiboken2-qt5 fails with:

> [ 23%] Built target libsample
> Scanning dependencies of target libother
> [ 23%] Building CXX object ApiExtractor/CMakeFiles/apiextractor.dir/docparser.cpp.obj
> [ 23%] Building CXX object tests/libother/CMakeFiles/libother.dir/number.cpp.obj
> [ 23%] Building CXX object ApiExtractor/CMakeFiles/apiextractor.dir/doxygenparser.cpp.obj
> [ 24%] Building CXX object ApiExtractor/CMakeFiles/apiextractor.dir/qtdocparser.cpp.obj
> [ 24%] Building CXX object tests/libother/CMakeFiles/libother.dir/otherderived.cpp.obj
> [ 25%] Building CXX object tests/libother/CMakeFiles/libother.dir/otherobjecttype.cpp.obj
> [ 25%] Building CXX object ApiExtractor/CMakeFiles/apiextractor.dir/apiextractor_autogen/mocs_compilation.cpp.obj
> [ 25%] Building CXX object tests/libother/CMakeFiles/libother.dir/othermultiplederived.cpp.obj
> In file included from D:/MINGW-packages/mingw-w64-shiboken2-qt5/src/pyside-setup-everywhere-src-5.11.0/sources/shiboken2/tests/libother/otherderived.cpp:29:
> D:/MINGW-packages/mingw-w64-shiboken2-qt5/src/pyside-setup-everywhere-src-5.11.0/sources/shiboken2/tests/libother/otherderived.h:58:10: warning: 'hideFunction' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
>     void hideFunction(HideType*) {}
>          ^
> D:/MINGW-packages/mingw-w64-shiboken2-qt5/src/pyside-setup-everywhere-src-5.11.0/sources/shiboken2/tests/libsample/abstract.h:96:18: note: overridden virtual function is here
>     virtual void hideFunction(HideType* arg) = 0;
>                  ^
> 1 warning generated.
> [ 25%] Linking CXX shared library libother.dll
> CMakeFiles/libother.dir/objects.a(othermultiplederived.cpp.obj):(.rdata[_ZTI14SonOfMDerived1]+0x10): Warnung: undefinierter Verweis auf ▒typeinfo for MDerived1▒
> CMakeFiles/libother.dir/objects.a(othermultiplederived.cpp.obj):(.rdata[_ZTI20OtherMultipleDerived]+0x10): Warnung: undefinierter Verweis auf ▒typeinfo for MDerived1▒
> clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [tests/libother/CMakeFiles/libother.dir/build.make:131: tests/libother/libother.dll] Fehler 1
> make[1]: *** [CMakeFiles/Makefile2:3223: tests/libother/CMakeFiles/libother.dir/all] Fehler 2
> make[1]: *** Es wird auf noch nicht beendete Prozesse gewartet....
> [ 25%] Linking CXX static library ../tests/libapiextractor.a
> [ 25%] Built target apiextractor
> make: *** [Makefile:141: all] Fehler 2
> ==> FEHLER: Ein Fehler geschah in build().
>     Breche ab...

**Comment by Alexpux** [comment]
Pyside2 not buildable (I'm add it to repo as WIP) - need someone who can fix. Also Clang building is not supported at all

**Comment by revelator** [comment]
Aye had the same problem though i managed to get shiboken2 to build, but it took a lot of hacking about.
Had to force it to use gcc instead of clang which it was none to happy about.

**Comment by raccoonmonk** [comment]
Please somebody review my pull request #6747 regarding this issue
