### ISSUE TITLE
libxmlsec1 static linking error

### ISSUE THREAD

**Issue by bartland** [msys2/MINGW-packages#4528]
I have a couple of programs which link statically to  libxml2. The first works fine. The second also uses libxmlsec1 but fails to link because it seems that libxmlsec1.a and libxmlsec1-openssl.a have been linked dynamically against libxml2.

Is this is a similar issue to:  https://github.com/Alexpux/MINGW-packages/issues/3538#issuecomment-408016158? (where I temporarily fixed that by rebuilding using --without-nghttp2). 

```
...
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1-openssl.a(libxmlsec1_openssl_la-x509.o):(.text+0x21f2): undefined reference to `_imp__xmlFree'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1-openssl.a(libxmlsec1_openssl_la-x509.o):(.text+0x2259): undefined reference to `_imp__xmlFree'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1-openssl.a(libxmlsec1_openssl_la-x509.o):(.text+0x2308): undefined reference to `_imp__xmlFree'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1-openssl.a(libxmlsec1_openssl_la-x509.o):(.text+0x2398): undefined reference to `_imp__xmlFree'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1-openssl.a(libxmlsec1_openssl_la-x509.o):(.text+0x2466): undefined reference to `_imp__xmlFree'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1-openssl.a(libxmlsec1_openssl_la-x509.o):(.text+0x250f): more undefined references to `_imp__xmlFree' follow
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1.a(base64.o):(.text+0x4f5): undefined reference to `_imp__xmlMalloc'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1.a(base64.o):(.text+0x17dd): undefined reference to `_imp__xmlMalloc'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1.a(base64.o):(.text+0x1885): undefined reference to `_imp__xmlFree'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1.a(base64.o):(.text+0x195d): undefined reference to `_imp__xmlFree'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1.a(buffer.o):(.text+0x1ae): undefined reference to `_imp__xmlFree'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1.a(buffer.o):(.text+0x235): undefined reference to `_imp__xmlFree'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1.a(buffer.o):(.text+0x3fa): undefined reference to `_imp__xmlRealloc'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1.a(buffer.o):(.text+0x441): undefined reference to `_imp__xmlMalloc'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1.a(buffer.o):(.text+0x565): undefined reference to `_imp__xmlMalloc'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../lib\libxmlsec1.a(buffer.o):(.text+0x10ec): undefined reference to `_imp__xmlFree'
...
```

**Comment by peterbud** [comment]
@bartland : how do you link statically to xmlsec?
Have you followed the instructions here? 
https://www.aleksey.com/xmlsec/faq.html

> When people link statically to XMLSec, then they must #define XMLSEC_STATIC in their source files before including any XMLSec header. Almost none is doing that :) This macro has no effect on Unix, but it is vital on Windows.
This applies to LibXML and LibXSLT as well, no matter if these are used directly or not. If just XMLSec is used, but everything is linked statically, then there must be a
>    #define LIBXML_STATIC
    #define LIBXSLT_STATIC
    #define XMLSEC_STATIC
before any xmlsec header is included. Even if the client code doesn't call into libxml at all, still this must be defined. XMLSec headers will include LibXML headers and they must have these definitions. Without them, every variable XMLSec includes from LibXML headers will have __declspec(dllimport) prepended and that will give headaches if static LibXML is used for linking.

**Comment by bartland** [comment]
@peterbud Thanks. Yes, I define all relevant statics (below). I did build this successfully a while back before xmlsec1 was included in the packages. I've just come back to this recently to rebuild, and got the error. 

Compile flags are:
```
-DCURL_STATICLIB
-DLIBXML_STATIC
-DLIBXSLT_STATIC
-DMINGW
-DNGHTTP2_STATICLIB
-DWIN32
-DXMLSEC_CRYPTO_OPENSSL
-DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING
-DXMLSEC_NO_XSLT
-DXMLSEC_STATIC
-D_MINGW
-D_WIN32
-I/C/msys64/mingw32/include
-I/C/msys64/mingw32/include/xmlsec1
-I/C/msys64/mingw32/include/libxml2
-O2
-ansi
-std=c99
-pedantic-errors
-Werror
-Wmissing-prototypes
-Wstrict-prototypes
-Wall
-Wextra
-Wshadow
-Wcast-qual
-Wwrite-strings
-Wformat=2
-Wstrict-overflow=5
-Waggregate-return
-Wbad-function-cast
-Wcast-align
-Wmissing-declarations
-Wnested-externs
-Wredundant-decls
-Winline
-Wno-error=long-long
-Wno-format-nonliteral
-Wno-pedantic-ms-format
```

**Comment by peterbud** [comment]
@bartland : glad that you were able to solve it. If I'm reading it right, that means you have also disabled dynamic loading of crypto libs, which might be OK to you, but in this project the preferred way is shared libraries, so I'm not really comfortable to add such changes to the PKGBUILD.

Anyhow if you feel sorted out, please close the issue.

**Comment by bartland** [comment]
@peterbud I agree that disabling the dynamic loading is not the right way. I was just being lazy as I wanted to get my particular use case going quickly. Similarly with excluding xslt, as I didn't bother rebuilding it. 

The main issue is that xmlsec/xslt are linking to the dynamic version instead of the static version of libxml2. What do you think about changing it to link to static libxml2? It seems analogous to curl linking against the dynamic version of nghttp2 which Alexpux indicated was wrong. I'm not sure if the way I did it (export CPPFLAGS="-DLIBXML_STATIC") is appropriate or not as I'm not that familiar with PKGBUILD.

Happy to close the issue if you think otherwise. I'll then keep applying my private patch.

Cheers

**Comment by bartland** [comment]
This seems to have been resolved in the latest MSYS2 upgrade.

**Comment by bartland** [comment]
I'll leave this closed, but note this has come back in the latest. My workaround is still:

Download and modify MINGW-packages/mingw-w64-xmlsec/PKGBUILD

Change

```
    ../${_realname}-${_realname}-${pkgver//./_}/configure \
        --prefix="${MINGW_PREFIX}"      \
        --build=${MINGW_CHOST}          \
        --host=${MINGW_CHOST}

```
to

```
    export CPPFLAGS="-DLIBXML_STATIC"
    ../${_realname}-${_realname}-${pkgver//./_}/configure \
        --prefix="${MINGW_PREFIX}"      \
        --build=${MINGW_CHOST}          \
        --host=${MINGW_CHOST}  \
        --without-libxslt \
        --disable-crypto-dl  \
        --disable-apps-crypto-dl
```

Build and install (see logs for progress). Check takes too long, so disable it.

```
cd MINGW-packages/mingw-w64-xmlsec
makepkg-mingw -sCLf --skippgpcheck --nocheck
pacman -U mingw-w64-*-xmlsec-*-any.pkg.tar.*
```

**Comment by bartland** [comment]
Getting tiresome. Now libxmlsec1-openssl.a is linked dynamically against libxml2

Not sure what flags have affect but this worked - for now:
```
  export CPPFLAGS="-DLIBXML_STATIC -DXMLSEC_STATIC -DLIBXSLT_STATIC"
  ../${_realname}1-${pkgver}/configure \
    --prefix="${MINGW_PREFIX}" \
    --build=${MINGW_CHOST} \
    --host=${MINGW_CHOST} \
    --without-libxslt \
    --disable-shared \
    --enable-static \
    --enable-static-linking \
    --disable-crypto-dl \
    --disable-apps-crypto-dl
```

**Comment by Biswa96** [comment]
Hi @bartland, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/3596278695

**Comment by bartland** [comment]
Hi @Biswa96. Thanks for looking at this and apologies for the snark.

I have tested your 64bit build. "nm ... | grep _imp_" no longer shows dynamic links to libxml2 which is good - where ... is libxmlsec1.a  or libxmlsec1-openssl.a.

Problem 1:
I get the following when linking against your libxmlsec1.a  (plus xslt errors - see Problem 2)
* undefined reference to: lt_dlclose, lt_dlopenext, lt_dlsym, lt_dlinit, lt_dlexit.

Problem 2:
libxmlsec1.a statically links to libxslt.a. The same problem applies to  libxslt.a which currently dynamically links to libxml2. 

Thanks again

**Comment by bartland** [comment]
Great. libxslt.a is now correct. However 

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\
libxmlsec1.a(dl.o):(.text+0x43): undefined reference to `lt_dlclose'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\
libxmlsec1.a(dl.o):(.text+0x23f): undefined reference to `lt_dlopenext'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\
libxmlsec1.a(dl.o):(.text+0x258): undefined reference to `lt_dlsym'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\
libxmlsec1.a(dl.o):(.text+0x99c): undefined reference to `lt_dlinit'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\
libxmlsec1.a(dl.o):(.text+0xa61): undefined reference to `lt_dlexit'
collect2.exe: error: ld returned 1 exit status
```

**Comment by bartland** [comment]
Good news @Biswa96 . I rebuilt using your PKGBUILD with one amendment and everything worked  :-).

I just added the flag --enable-static-linking.

```
  mkdir -p "${srcdir}/build-${MSYSTEM}-static" && cd "${srcdir}/build-${MSYSTEM}-static"

  CPPFLAGS+=" -DLIBXML_STATIC -DLIBXSLT_STATIC -DXMLSEC_STATIC" \
  ../${_realname}1-${pkgver}/configure \
    --prefix="${MINGW_PREFIX}" \
    --build=${MINGW_CHOST} \
    --host=${MINGW_CHOST} \
    --disable-shared \
    --enable-static \
    --enable-static-linking \
    --enable-mscrypto \
    --enable-mscng
```

**Comment by Biswa96** [comment]
Thanks for the hint. For testing, the new packages can be found here https://github.com/msys2/MINGW-packages/actions/runs/3645325714

**Comment by bartland** [comment]
Perfect. All working.

Looking forward to the official releases.

Thanks
