### ISSUE TITLE
Boost 1.68.0-2 Installation fails

### ISSUE THREAD

**Issue by fgstrati** [msys2/MINGW-packages#4530]
Recent Boost package fails to install:

------------------------------------------------------------------------------------
$ pacman -S --disable-download-timeout mingw-w64-x86_64-boost
risoluzione delle dipendenze in corso...
ricerca dei pacchetti in conflitto in corso...

Pacchetti (1) mingw-w64-x86_64-boost-1.68.0-2

Dimensione totale dei pacchetti da scaricare:    19,22 MiB
Dimensione totale dei pacchetti da installare:  298,34 MiB

:: Vuoi procedere con l'installazione? [S/n] S
:: Download dei pacchetti in corso...
errore: impossibile scaricare il pacchetto 'mingw-w64-x86_64-boost-1.68.0-2-any.pkg.tar.xz' da repo.msys2.org : transfer closed with 20141388 bytes remaining to read---------------------------------------------------------------------------------------------------]   0%
errore: impossibile scaricare il file 'mingw-w64-x86_64-boost-1.68.0-2-any.pkg.tar.xz' da sourceforge.net: la dimensione di download supera quella attesaM/s 00:00 [###############################################################################################-----]  95%

`Interrupt signal received`
------------------------------------------------------------------------------------

I tried to update manually by downloading from:
http://repo.msys2.org/mingw/x86_64/
the package
mingw-w64-x86_64-boost-1.68.0-2-any.pkg.tar.xz     08-Oct-2018 07:41            20149876

But when I try to install it:
 pacman -U mingw-w64-x86_64-boost-1.68.0-2-any.pkg.tar.xz
caricamento dei pacchetti in corso...
errore: impossibile aprire il file mingw-w64-x86_64-boost-1.68.0-2-any.pkg.tar.xz: Lzma library error: Corrupted input data
errore: 'mingw-w64-x86_64-boost-1.68.0-2-any.pkg.tar.xz': impossibile aprire il pacchetto

I then verified with 7zip that the file mingw-w64-x86_64-boost-1.68.0-2-any.pkg.tar.xz is really corrupted.

**Comment by StarWolf3000** [comment]
Have downloaded the file myself, and its complete. Do you have any security software running (firewall, anti-virus, anti-malware, etc.) or are you using a proxy?

**Comment by lazka** [comment]
Is this still a problem?
