### ISSUE TITLE
Errors catching exceptions with mingw-w64-i686-gcc-7.3.0-3 (32-bit only)

### ISSUE THREAD

**Issue by jberkenbilt** [msys2/MINGW-packages#4543]
I build [qpdf](https://github.com/qpdf/qpdf) using Azure Pipelines. [This build](https://dev.azure.com/qberkenbilt/qpdf/_build/results?buildId=108&view=logs) from 2018-10-14, passes all its tests on Windows except one fragile test I'm still trying to figure out. I don't know how to link to it directly, but if you click on "Windows mingw32" on the left and then "Build, test generate binary distributions" on the right, you can see the build log and observe the following on line 26491: `2018-10-14T02:03:52.1105814Z Packages (43) mingw-w64-i686-bzip2-1.0.6-6  mingw-w64-i686-ca-certificates-20170211-2  mingw-w64-i686-expat-2.2.6-1  mingw-w64-i686-gettext-0.19.8.1-6  mingw-w64-i686-gmp-6.1.2-1  mingw-w64-i686-isl-0.19-1  mingw-w64-i686-libffi-3.2.1-4  mingw-w64-i686-libiconv-1.15-3  mingw-w64-i686-libsystre-1.0.1-4  mingw-w64-i686-libtasn1-4.13-1  mingw-w64-i686-libtre-git-r128.6fb7206-2  mingw-w64-i686-mpc-1.1.0-1  mingw-w64-i686-mpdecimal-2.4.2-1  mingw-w64-i686-mpfr-4.0.1-2  mingw-w64-i686-ncurses-6.1.20180908-1  mingw-w64-i686-openssl-1.1.1-4  mingw-w64-i686-p11-kit-0.23.14-1  mingw-w64-i686-python3-3.7.0-15  mingw-w64-i686-readline-7.0.005-1  mingw-w64-i686-sqlite3-3.25.2-1  mingw-w64-i686-tcl-8.6.8-1  mingw-w64-i686-termcap-1.3.1-3  mingw-w64-i686-tk-8.6.8-1  mingw-w64-i686-windows-default-manifest-6.4-3  mingw-w64-i686-xz-5.2.4-1  mingw-w64-i686-zlib-1.2.11-4  mingw-w64-i686-binutils-2.30-5  mingw-w64-i686-crt-git-7.0.0.5245.edf66197-1  mingw-w64-i686-gcc-7.3.0-2  mingw-w64-i686-gcc-ada-7.3.0-2  mingw-w64-i686-gcc-fortran-7.3.0-2  mingw-w64-i686-gcc-libgfortran-7.3.0-2  mingw-w64-i686-gcc-libs-7.3.0-2  mingw-w64-i686-gcc-objc-7.3.0-2  mingw-w64-i686-gdb-8.2-1  mingw-w64-i686-headers-git-7.0.0.5245.edf66197-1  mingw-w64-i686-libmangle-git-7.0.0.5230.69c8fad6-1  mingw-w64-i686-libwinpthread-git-7.0.0.5231.7da6518b-1  mingw-w64-i686-make-4.2.1-2  mingw-w64-i686-pkg-config-0.29.2-1  mingw-w64-i686-tools-git-7.0.0.5242.1b29d1bc-1  mingw-w64-i686-winpthreads-git-7.0.0.5231.7da6518b-1  mingw-w64-i686-winstorecompat-git-7.0.0.5230.69c8fad6-1`

On the other hand, [this build](https://dev.azure.com/qberkenbilt/qpdf/_build/results?buildId=113&view=results) from 2018-10-15, has 199 failing test cases, all of which are in the mingw-win32 build. From the [logs](https://dev.azure.com/qberkenbilt/qpdf/_build/results?buildId=113&view=logs), again click in Windows mingw32, then Build, test, generate binary distributions. On line 26490, observe the line: `2018-10-15T18:58:02.9676026Z Packages (43) mingw-w64-i686-bzip2-1.0.6-6  mingw-w64-i686-ca-certificates-20170211-2  mingw-w64-i686-expat-2.2.6-1  mingw-w64-i686-gettext-0.19.8.1-6  mingw-w64-i686-gmp-6.1.2-1  mingw-w64-i686-isl-0.19-1  mingw-w64-i686-libffi-3.2.1-4  mingw-w64-i686-libiconv-1.15-3  mingw-w64-i686-libsystre-1.0.1-4  mingw-w64-i686-libtasn1-4.13-1  mingw-w64-i686-libtre-git-r128.6fb7206-2  mingw-w64-i686-mpc-1.1.0-1  mingw-w64-i686-mpdecimal-2.4.2-1  mingw-w64-i686-mpfr-4.0.1-2  mingw-w64-i686-ncurses-6.1.20180908-1  mingw-w64-i686-openssl-1.1.1-4  mingw-w64-i686-p11-kit-0.23.14-1  mingw-w64-i686-python3-3.7.0-15  mingw-w64-i686-readline-7.0.005-1  mingw-w64-i686-sqlite3-3.25.2-1  mingw-w64-i686-tcl-8.6.8-1  mingw-w64-i686-termcap-1.3.1-3  mingw-w64-i686-tk-8.6.8-1  mingw-w64-i686-windows-default-manifest-6.4-3  mingw-w64-i686-xz-5.2.4-1  mingw-w64-i686-zlib-1.2.11-4  mingw-w64-i686-binutils-2.30-5  mingw-w64-i686-crt-git-7.0.0.5245.edf66197-1  mingw-w64-i686-gcc-7.3.0-3  mingw-w64-i686-gcc-ada-7.3.0-3  mingw-w64-i686-gcc-fortran-7.3.0-3  mingw-w64-i686-gcc-libgfortran-7.3.0-3  mingw-w64-i686-gcc-libs-7.3.0-3  mingw-w64-i686-gcc-objc-7.3.0-3  mingw-w64-i686-gdb-8.2-1  mingw-w64-i686-headers-git-7.0.0.5245.edf66197-1  mingw-w64-i686-libmangle-git-7.0.0.5230.69c8fad6-1  mingw-w64-i686-libwinpthread-git-7.0.0.5231.7da6518b-1  mingw-w64-i686-make-4.2.1-2  mingw-w64-i686-pkg-config-0.29.2-1  mingw-w64-i686-tools-git-7.0.0.5242.1b29d1bc-1  mingw-w64-i686-winpthreads-git-7.0.0.5231.7da6518b-1  mingw-w64-i686-winstorecompat-git-7.0.0.5230.69c8fad6-1`

Diffing these, you can see that the following packages moved from 7.3.0-2 to 7.3.0-3:

```
mingw-w64-i686-gcc-7.3.0-3
mingw-w64-i686-gcc-ada-7.3.0-3
mingw-w64-i686-gcc-fortran-7.3.0-3
mingw-w64-i686-gcc-libgfortran-7.3.0-3
mingw-w64-i686-gcc-libs-7.3.0-3
mingw-w64-i686-gcc-objc-7.3.0-3
```

Looking at the test runs, there are numerous errors such as this:

```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'std::length_error'
terminate called recursively
```

Here's another:

```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'QPDFSystemError'
terminate called recursively
```

Basically there are several failures of this type where terminate is called recursively after throwing an exception. There is a good chance that these errors are in programs that catch `std::exception` from main, but I haven't verified all the failures.

Here are a few things to note:

* The tests are clean with mingw64 which also switched to 7.3.0-3
* The tests are clean for both 32-bit and 64-bit Windows with Visual C++
* The tests are clean for mac with clang and Linux with gcc. They also run clean with gcc with address sanitizer. There are no uncaught exceptions anywhere in the extensive test suite.
* I have built and tested qpdf on Windows using many versions of mingw 32 and 64 over several years and have never before experienced instability.

My build pipeline includes the following:
```
choco install msys2
pacman -Sy --noconfirm make base-devel tar zip unzip
pacman -Sy --noconfirm mingw-w64-i686-toolchain
```

The choco command is run from a Windows BAT file. The pacman commands are run from a bash script invoked as

```
C:\tools\msys64\usr\bin\env.exe MSYSTEM=MINGW64 /bin/bash -l %CD%/azure-pipelines/build-windows %1 %2
```
The bash script invokes the two pacman commands. The output of `g++ -v` is

```
2018-10-15T18:59:43.5034402Z Using built-in specs.
2018-10-15T18:59:43.5035500Z COLLECT_GCC=C:\tools\msys64\mingw32\bin\g++.exe
2018-10-15T18:59:43.5035893Z COLLECT_LTO_WRAPPER=C:/tools/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/lto-wrapper.exe
2018-10-15T18:59:43.5036098Z Target: i686-w64-mingw32
2018-10-15T18:59:43.5036799Z Configured with: ../gcc-7.3.0/configure --prefix=/mingw32 --with-local-prefix=/mingw32/local --build=i686-w64-mingw32 --host=i686-w64-mingw32 --target=i686-w64-mingw32 --with-native-system-header-dir=/mingw32/i686-w64-mingw32/include --libexecdir=/mingw32/lib --enable-bootstrap --with-arch=i686 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --enable-libstdcxx-filesystem-ts=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw32 --with-mpfr=/mingw32 --with-mpc=/mingw32 --with-isl=/mingw32 --with-pkgversion='Rev3, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld --disable-sjlj-exceptions --with-dwarf2
2018-10-15T18:59:43.5037605Z Thread model: posix
2018-10-15T18:59:43.5037886Z gcc version 7.3.0 (Rev3, Built by MSYS2 project) 
```

I'm going to attempt to reproduce this with a small file.

**Comment by jberkenbilt** [comment]
This program appears to do the trick:

```c++
#include <exception>
#include <iostream>

int main()
{
    try
    {
        throw std::runtime_error("potato");
    }
    catch (std::exception& e)
    {
        std::cerr << "caught " << e.what() << std::endl;
    }
    return 0;
}
```

**Comment by jberkenbilt** [comment]
Here's a pipeline [build](https://dev.azure.com/qberkenbilt/qtest/_build/results?buildId=118&view=logs) that shows g++ 64-bit working and 32-bit failing on the above example. To see the whole thing, you can look at https://github.com/jberkenbilt/qtest-azure-pipelines/tree/547535ddafdd4f73b22b7152e2a035072992575e. This is just a commit in my sandbox repo that I use to do quick tests against azure pipelines.

**Comment by Alexpux** [comment]
@jberkenbilt this is possible because of switching mingw-w64 runtime to build for Win7 by default and something is goes wrong

**Comment by Alexpux** [comment]
Here is debug version of GCC if someone want to try bisecting issue:
https://yadi.sk/d/uh63NQPAsETwBw

**Comment by Alexpux** [comment]
Currently I'm downgrade GCC in repo to working.

**Comment by oscarfv** [comment]
The same procedure described above produces a working C++ compiler for gcc 8.2. Ada still fails as described in #4125.

**Comment by mati865** [comment]
Wasn't it fixed along with https://github.com/msys2/MINGW-packages/issues/4728?

**Comment by oscarfv** [comment]
@mati865 : yes, as far as I remember. This issue should be closed.

**Comment by oscarfv** [comment]
@jberkenbilt : is this issue fixed for you? If yes, please close it. Thanks.

**Comment by jberkenbilt** [comment]
Yes, thanks.
