### ISSUE TITLE
Latest crt and headers break multiple packages.

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#4601]
Some recent updates in the mingw-w64 repo has done away with the need for some mingw specific hacks used in multiple sources, unfortunatly as long as they are not updated to reflect that we can no longer build them. 
git for instance no longer builds with errors about pollfd (now part of winsock2.h).

I started patching the affected packages, so i guess i will no longer be able to avoid having to fork this repo to do commits :P

**Comment by Alexpux** [comment]
@revelator I think this is because I switch mingw-w64 runtime minimum version to Win7

**Comment by revelator** [comment]
workaround for the time being is to set CPPFLAGS+=" -D_WIN32_WINNT=0x0501" on the packages that croak.

**Comment by mati865** [comment]
If you are seeing these errors on Windows 7 or newer then you should report it on mingw-w64 mailing list.

**Comment by lazka** [comment]
@revelator is there anything left to fix/improve here?

**Comment by lazka** [comment]
I guess not. Feel free to open another issue or post here.
