### ISSUE TITLE
Weird problem: strip crashing

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#4602]
Yesterday i started building VTK and i ran into a rather bizarre problem.
the 64 bit package is 10 times the size of the 32 bit version Oo, same happens with ITK.
Are the 64 bit packages not stripped ?.

**Comment by Alexpux** [comment]
@revelator it must be stripped. Look at package log. If it not stripped then need to find why

**Comment by revelator** [comment]
Huh its strip crashing, signal 11.

**Comment by revelator** [comment]
seems something odd is happening, i tried rebuilding binutils no dice, then i tried an older version, still crashes. Then i checked permissions on the folder where i built it and they where totally screwed up sigh :S not sure whats causing this but every folder created by 64 bit gcc sets permissions that do not allow anything to run. I suspect windows defender is doing something rather sneaky behind my back because i get no popups about potentially harmfull material like i used to.
Also i whitelisted the folders Msys2 uses, so its a bit of a mystery.

**Comment by lazka** [comment]
Is there anything left to do here?

**Comment by revelator** [comment]
Not sure what caused this, but after reinstalling windows everything works again.
Might have been a bad win10 patch...

**Comment by lazka** [comment]
@revelator thanks for checking again and reporting back! Let's close this for now.
