### ISSUE TITLE
issue with python .exe invocation

### ISSUE THREAD

**Issue by JPeterMugaas** [msys2/MINGW-packages#4622]
I noticed an issue with the prebuild binary python packages.  For some reason, the build process hard-coded something like \mingw64 or \mingw32 instead of /mingw64 or /mingw32 like the build and install scripts for the package expects.
 
This does not happen when I build the packages locally and I can't reproduce what's causing the issue.  Here's an example of the error I was getting.
```
/mingw64/bin/sphinx-apidoc --help
failed to create process (\mingw64\bin\python3.exe "D:\msys64\mingw64\bin\sphinx-apidoc-script.py" "--help").
```

**Comment by lazka** [comment]
Your example works fine here.

**Comment by peterbud** [comment]
It's also working for me, and I have not built them from source, but all these packages are coming from the repo.

**Comment by lazka** [comment]
Still working fine here. Feel free to provide more info.

**Comment by gits68** [comment]
Running system : Windows 10 20H2
uname -a : MINGW64_NT-10.0-19042 pcseven 3.1.7-340.x86_64 2020-10-22 12:43 UTC x86_64 Msys
pacman is up to date

when I try to run pip3, I'm getting the following error :

$ pip3
failed to create process (\mingw64\bin\python.exe "C:\msys64\mingw64\bin\pip3-script.py").

this works well :

$ python "C:\msys64\mingw64\bin\pip3-script.py"
$ python -m pip

any idea ?
