### ISSUE TITLE
Gnuplot: How to install?

### ISSUE THREAD

**Issue by alekhe** [msys2/MINGW-packages#4649]
I’m trying to use gnuplot in msys2 environment, but I didn’t succeed up to now.

What I did:
1. Fresh install of msys2-64bit on Windows 10 machine + updates.
2. mingw-w64-x86_64-toolchain (without ada and objc).
3. mingw-w64-x86_64-gnuplot

What I have when I start gnuplot:
C:/msys64/mingw64/bin/gnuplot.exe: error while loading shared libraries: Qt5Network.dll: cannot open shared object file: No such file or directory

Does that mean I have to install Qt5? Can I use gnuplot without it?

**Comment by Alexpux** [comment]
Yes you need install Qt5, other way is to build gnuplot without Qt5 yourself

**Comment by alekhe** [comment]
OK, thanks. I think I will go back to the stand-alone version for Windows.
