### ISSUE TITLE
Qt 5.11.2-3 not built with (or capable of) SSL support

### ISSUE THREAD

**Issue by droidmonkey** [msys2/MINGW-packages#4668]
I cannot get SSL to work with Qt 5.11.2-2 or 5.11.2.-3. This used to work about a year ago, but recently no dice. Also, the openssl package does not come with libeay.dll or ssleay.dll (not sure if it should?). Furthermore, the Qt 5.11.2-3 libraries are looking for openssl 1.0.2p and MSYS2 is shipping openssl 1.1.x.

In my opinion, SSL support should be baked into the Qt libs in MSYS2 to make it easy for everyone. Please see http://doc.qt.io/qt-5/ssl.html#enabling-and-disabling-ssl-support

**Comment by droidmonkey** [comment]
Side note, installing [this version of OpenSSL](https://slproweb.com/download/Win64OpenSSL_Light-1_0_2p.exe) into the windows system directory makes everything work correctly. However, this is not very good for the end user or packaging self-contained (portable) apps.

**Comment by MehdiChinoune** [comment]
closing since the package has been updated and we didn't get any similar bug reports since then
