### ISSUE TITLE
Macro problem on openssl X509 building

### ISSUE THREAD

**Issue by saverio-mori** [msys2/MINGW-packages#4685]
Dear All,
i have tried to build net-snmp in windows using the latest msys2 and mingw64 environment, unfortunately make broke on openssl X509 headers, with tons of errors apparently related to macros. I have given further details on https://github.com/openssl/openssl/issues/7686

**Comment by lazka** [comment]
Best to ask net-snmp if they support Windows. Might be that it's not including windows.h before including openssl headers.

**Comment by saverio-mori** [comment]
Teoretically they should. Windows is supported and documented, while latest release 5.8 is of July, 2018. It is true that on their download page they declare an issue with windows binaries and openssl > 0.9, but it is unclear if this issue affect also 5.8 sources. Anyway this morning i have open a ticket on  net-snmp bug tracker.

**Comment by saverio-mori** [comment]
https://sourceforge.net/p/net-snmp/bugs/2904/

**Comment by lazka** [comment]
Is there anything left to do here?
