### ISSUE TITLE
GCC 8 regression

### ISSUE THREAD

**Issue by omichel** [msys2/MINGW-packages#4744]
It seems that gcc 8 introduced a regression comparing to gcc 7.
With gcc 7, it was and is still possible to install msys64 in a folder that contains spaces and still be able to compile a `hello_world.c` file, which was working nicely, but it seems it is broken with gcc 8 (note the space between `msys` and `64`):

```bash
$ pwd
/D/msys 64/home/Olivier

$ ls -l
total 9
-rw-r--r-- 1 Olivier None     96 Dec  4 18:01 hello_world.c


$ gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 8.2.1 20181123
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc hello_world.c
D:/msys 64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w6 4-mingw32/bin/ld.exe: cannot find D:/msys: No such file or directory
D:/msys 64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w6 4-mingw32/bin/ld.exe: cannot find 64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8 .2.1/../../../../x86_64-w64-mingw32/lib/../lib/default-manifest.o: No such file  or directory
collect2.exe: error: ld returned 1 exit status

$ PATH=/usr/bin gcc --version
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ PATH=/usr/bin gcc hello_world.c

$ ls -l
total 153
-rwxr-xr-x 1 Olivier None 144279 Dec  4 18:01 a.exe
-rw-r--r-- 1 Olivier None     96 Dec  4 18:01 hello_world.c
```

It seems the problem is a wrong path to `default-manifest.o`, probably missing double quotes, which should be fairly easy to fix.

*Note*: I am aware that it is not recommended to install MSYS2 in a path containing spaces, but it used to work nicely until gcc 8 came 😒...

**Comment by omichel** [comment]
Is there any progress on this issue? I checked and the problem is still there in the current MSYS2...

**Comment by Alexpux** [comment]
@omichel no one work on this issue currently.

**Comment by omichel** [comment]
Thank you for the reply. Meanwhile, I investigated the issue and found out that removing `windows-default-manifest` which is a dependency of `gcc` does fix the problem. I could recompile my huge app without this `window-default-manifest` and everything seems to run smoothly. Therefore I am wondering whether this default manifest is useful or not. In my case it is harming more than helping... Do you know what is the purpose of the `default-manifest.o` file?

**Comment by Alexpux** [comment]
@omichel probably the problem not with manifest but with windres from binutils

**Comment by omichel** [comment]
I see, it probably relates with #1035.

**Comment by omichel** [comment]
I tried to apply this patch https://sourceware.org/bugzilla/show_bug.cgi?id=4933 to binutils, but it doesn't fix the problem...

**Comment by omichel** [comment]
I finally found and fixed the problem. That was a bug in gcc which I reported here along with a patch: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90692
I will prepare a PR with my patch to fix gcc in MSYS2.
