### ISSUE TITLE
gcc, SOURCE_DATE_EPOCH

### ISSUE THREAD

**Issue by MSP-Greg** [msys2/MINGW-packages#4749]
I've been looking into a 'reproducible build', and SOURCE_DATE_EPOCH is suggested for use as timestamp, often set to a date/time particular to the build.  I'm building on a repo's master branch, so I'm using the timestamp from the last commit.

I can't seem to get it to work with gcc.

Has anyone used it successfully?

**Comment by stahta01** [comment]
I have verified that  makepkg version 5.1.0 has support for SOURCE_DATE_EPOCH and GCC 8.2 has support.

But, I have no idea on how to use it, correctly.

But, you need set SOURCE_DATE_EPOCH to a valid system variable value.

Tim S.

**Comment by GitMensch** [comment]
I guess this old issue can be closed?

In any case the correct thing to do is: no code change at all, but before running the complete toolset `export/set SOURCE_DATE_EPOCH` - it is an environmental setting, see https://gcc.gnu.org/onlinedocs/cpp/Environment-Variables.html

**Comment by stahta01** [comment]
pacman and GCC supports SOURCE_DATE_EPOCH; but, the mingw-64 tool genlib does not seem to support it.

Tim S.

**Comment by GitMensch** [comment]
> pacman and GCC supports SOURCE_DATE_EPOCH; but, the mingw-64 tool genlib does not seem to support it.

So then this issue should either be closed or its topic and title adjusted to be about genlib instead (I think the former is more clear). The genlib tool is the one from mingw-w64 8discussed in its mailing list](https://sourceforge.net/p/mingw-w64/mailman/message/34577521/) and initially found [at github](https://github.com/martell/genlib/blob/master/src/genlib.c)?
According to the [MSYS2 recipe](https://github.com/msys2/MINGW-packages/blob/f7b8ebdf9f2749b3f2b68039755f875d03884475/mingw-w64-tools-git/PKGBUILD) the code directly comes from [mingw-w64's repo](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-tools/genlib/src/) so the easiest thing would to ask for all mingw-w64 tools to take `SOURCE_DATE_EPOCH` into account. This is definitely an "upstream" issue so we may don't need one here at all, do we?
Of course it would also be possible to create and use a patch in the MSYS2 package for at least genlib to use `SOURCE_DATE_EPOCH` and then sending the patch upstream.

> I am building 9 packages that are an old GCC 5 toolchain and the C Runtime (CRT) has major problems

Why are those using an old GCC 5 toolchain at all? Wouldn't it be reasonable to update this to use current gcc [or via the wrapping in the clang environments clang]?

**Comment by stahta01** [comment]
I am trying to build an even older GCC version of 3.4.5 and GCC 5 is just a step on the way.
I first programmed on an color computer 2 using an 8 bit CPU; version 4.6 was the last version of GCC that someone ported to targeting that CPU. And, I want to see if I can add Ada support to it. And, 3.4.x is the last version of GCC where you did not need an Ada compiler to build Ada support.

Yes, closing this thread makes sense to me; I will see if it is easy to add support to  genlib but, it will likely be weeks in the future.

Tim S.

**Comment by GitMensch** [comment]
@stahta01 I suggest to just create a feature request at mingw-w64 to support `SOURCE_DATE_EPOCH` in its tools in this case, maybe linking here.

Just out of interest: Did I understand your project correctly that you want to cross-compile a GCC 3.4.5 with Ada for an 8bit cpu which you then want to use there (so you also have the hardware to transfer the program and test it there)?

**Comment by stahta01** [comment]
I have the old hardware. The cross compiler will be running under windows generating code to be  transfer to an simulator program. And, finally to real hardware if I can figure it out.
It is possible that I might have to burn it to ROM or figure out how to write it to an old 3.5 inch disk. Both methods are possible. And I could try RS232 file transfer or audio tape tranfer.

I have to decide in the next year or two what do do with the old hardware. I figure I must have at least 3 old color computes. I hope one of them works. I plan to down size and hope to save at most two color computers and maybe some parts.

Tim S.

**Comment by jeremyd2019** [comment]
https://github.com/mingw-w64/mingw-w64/blob/578aafddc4447b976b454477c025345a3787e235/mingw-w64-tools/genlib/src/genlib.c#L179

I bet they'd accept a patch.

**Comment by stahta01** [comment]
I have found a possible issue with using "SOURCE_DATE_EPOCH" the packages I am building appears to lockup between prepare and build staging. The problem has been traced to a find command in "makepkg".

`		if (( REPRODUCIBLE )); then
			# We have activated reproducible builds, so unify source times before
			# building
			find "$srcdir" -exec touch -h -d @$SOURCE_DATE_EPOCH {} +
		fi
`
Is there any know reason that touch would run much faster under Linux?

Tim S.

**Comment by GitMensch** [comment]
Is there any reason to have that in makepkg at all?

[`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/) is for the build tools, not for changing the source file's date, which should come out of a tarball and therefore already has the correct timestamps, no?

**Comment by stahta01** [comment]
> Is there any reason to have that in makepkg at all?
> 
> [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/) is for the build tools, not for changing the source file's date, which should come out of a tarball and therefore already has the correct timestamps, no?

I am not sure if it is correct or not; I do know that the other use of SOURCE_DATE_EPOCH to set the build date seems correct.

Tim S.

**Comment by MSP-Greg** [comment]
This is rather old, and I think it came about due to a commercial application getting complaints about dlls not showing licensing info, build dates, etc.  Not even involved with that commercial application anymore.

Hence, closing.
