### ISSUE TITLE
mingw-w64-angleproject-git

### ISSUE THREAD

**Issue by mumin16** [msys2/MINGW-packages#4795]
I don't know what happened but there is problem in mingw-w64-angleproject-git. my project correctly run with my own compiled angle. But mingw-w64-angleproject-git's build is problem.

**Comment by mumin16** [comment]
there is no mingw-w64-angleproject-git build's  hash number!

**Comment by revelator** [comment]
build system changed, in later git versions. 
Previous versions used gyp new version uses gn from depot-tools so a new set of patches are needed before it builds again.

**Comment by Alexpux** [comment]
I'm deprecate angleproject package and remove it from database because google switch to its own build system
