### ISSUE TITLE
gedit: searching is broken

### ISSUE THREAD

**Issue by fabiangreffrath** [msys2/MINGW-packages#4838]
Hi,

currently, searching is broken in gedit. 

Try to open a file, hit CTRL+F and type a string: it won't appear in the search box. Now, hit ESC to close the search box, hit CTRL+F again and start to type. Now, it will work as expected.

**Comment by lazka** [comment]
Has this worked for you before?

**Comment by fabiangreffrath** [comment]
Indeed. I am not sure which upgrade killed it, but I guess it was one since around ~Dec 20.

**Comment by fabiangreffrath** [comment]
Maybe the glib update? I don't know...

**Comment by lazka** [comment]
likely the last gtk3 update

**Comment by fabiangreffrath** [comment]
The following warning is emitted:
```
(gedit.exe:484): GtkSourceView-WARNING **: 09:35:26.369: gtk_source_search_context_set_settings() is deprecated, the GtkSourceSearchContext:settings property will become a construct-only property in a future version.
```

**Comment by fabiangreffrath** [comment]
Unfortunately neither the gtk3 3.24.3 nor the 3.24.4 upgrade solved this issue. Is there a way to revert back to previously released package versions without rebuilding them from the sources?

**Comment by fabiangreffrath** [comment]
Never mind, I found it out myself.

I can confirm that the feature broke between 3.24.1-1 (which works) and 3.24.2-1 (which does not)!

**Comment by fabiangreffrath** [comment]
I have taken this issue upstream: https://gitlab.gnome.org/GNOME/gtk/issues/1758

**Comment by fabiangreffrath** [comment]
The search box is back to working with the update to gtk3-3.24.8-1, thanks!
