### ISSUE TITLE
postgresql refuses to build

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#4842]
getting this error in the later versions when trying to build it.

cyrillic_and_mic.o:cyrillic_and_mic.c:(.text+0x505): undefined reference to "local2local"
5 of them to be exact.

Is this a known bug ?.

**Comment by Alexpux** [comment]
Don’t see it before

**Comment by revelator** [comment]
strange then... -_- i even tried on another machine and i get the exact same error.
so i tried by directly typecasting the local2local function in cyrillic_and_mic.c but it refuses to aknowledge it as a valid function. then i tried changing the function name and now it builds. 
Seems gcc-7 atleast does not like this function name.

**Comment by revelator** [comment]
looks like its my old versions libraries that get picked up, they do not have this export so it seems likely that this might be the problem. ill try removing the libraries temporarily to see what happens.

**Comment by revelator** [comment]
yep old version was interfering, but i get another one further in the build.
seems NUMERIC_ABBREV_BITS has trouble finding out if 32 or 64 bit so im going to force it in the PKGBUILD next.

**Comment by revelator** [comment]
ok forcing it worked, but im not sure its the right thing to do.
Atleast i got it building :) and it works like a charm.
I do have a bash script handy for creating the databases based on the linux version which might be interresting to people who want to toy with postgres databases. I borrowed a part of the python3 bash script to set $prefix so that it works even if relocated. Only downside is that it only works in the msys shell. 

`#!/bin/sh

# PostgreSQL server start script

# Returns the actual prefix where this script was installed to.
installed_prefix ()
{
	local RESULT=$(dirname $(cd $(dirname "$1") && pwd -P))
	if [ $(which readlink) ] ; then
		RESULT=$(readlink -f "$RESULT")
	fi
	# Since we don't know where the output from this script will end up
	# we keep all paths in Windows-land since MSYS2 can handle that
	# while native tools can't handle paths in MSYS2-land.
	if [ "$OSTYPE" = "msys" ]; then
		RESULT=$(cd "$RESULT" && pwd -W)
	fi
	echo $RESULT
}

# the subdirectory this script is run from.
prefix_real=$(installed_prefix "$0")

# directory containing postgres executable:
PGBINDIR="${prefix_real}/bin"

# data directory:
PGDATA="${prefix_real}/var/lib/psql"

# file to receive postmaster's initial log messages:
PGLOGFILE="${PGDATA}/pgstart.log"

# What to use to shut down the postmaster
PGCTL="${PGBINDIR}/pg_ctl"

# (it's recommendable to enable the Postgres logging_collector feature
# so that PGLOGFILE doesn't grow without bound)

# init the database with default values if it does not exist yet.
if [ ! -f "$PGDATA"/PG_VERSION ] && [ ! -d "$PGDATA"/base ]; then
	echo -n $"Initializing database: "
	if [ ! -d "$PGDATA" ]; then
		mkdir -p "$PGDATA"
	fi
	${PGBINDIR}/initdb -D "$PGDATA" -U postgres -A trust
fi

# Parse command line parameters.
case $1 in
start)
echo -n "Starting PostgreSQL: "
$PGCTL start -D "$PGDATA" -l "$PGLOGFILE" -w -s
echo "ok"
;;
stop)
echo -n "Stopping PostgreSQL: "
$PGCTL stop -D "$PGDATA" -m fast -s
echo "ok"
;;
restart)
echo -n "Restarting PostgreSQL: "
$PGCTL restart -D "$PGDATA" -m fast -w -s
echo "ok"
;;
reload)
echo -n "Reload PostgreSQL: "
$PGCTL reload -D "$PGDATA" -s
echo "ok"
;;
status)
$PGCTL status -D "$PGDATA"
;;
*)
# Print help
echo "Usage: $0 {start|stop|restart|reload|status}" 1>&2
;;
esac

exit 0
`

**Comment by revelator** [comment]
[postgresql.zip](https://github.com/Alexpux/MINGW-packages/files/2737069/postgresql.zip)

shell script here.
