### ISSUE TITLE
qt5-static build fails

### ISSUE THREAD

**Issue by tim-lebedkov** [msys2/MINGW-packages#4862]
Here is the output. I only changed "_with_icu=no" in "PKGBUILD"

makepkg-mingw -fsiL

...
gcc -c -fno-keep-inline-dllexport -march=nocona -mtune=core2 -Wa,-mbig-obj -O2 -std=gnu11 -fno-exceptions -Wall -W -Wextra -Wno-unused-parameter -Wno-main -ffunction-sections -fdata-sections -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_STATICPLUGIN -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DDBUS_STATIC_BUILD -DJAS_DLL=0 -I. -I../../../3rdparty/libjpeg -I../../../3rdparty/libjpeg/src -I../../../../include/QtGui/5.12.0 -I../../../../include/QtGui/5.12.0/QtGui -I../../../../include -I../../../../include/QtGui -I../../../../include/QtCore/5.12.0 -I../../../../include/QtCore/5.12.0/QtCore -I../../../../include/QtCore -I.moc/release -I\include -isystem C:/msys64/mingw64/include/dbus-1.0 -IC:/msys64/mingw64/lib/dbus-1.0/include -isystem C:/msys64/mingw64/include/mariadb -I../../../../mkspecs/win32-g++  -o .obj/release/jmemnobs.o ../../../3rdparty/libjpeg/src/jmemnobs.c
g++ -fno-keep-inline-dllexport -O2 -std=c++1z -fno-exceptions -Wall -W -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -ffunction-sections -fdata-sections -dM -E -o .moc/release/moc_predefs.h ../../../../mkspecs/features/data/dummy.cpp
/C/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/bin/moc.exe -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_STATICPLUGIN -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DDBUS_STATIC_BUILD -DJAS_DLL=0 --include C:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/imageformats/jpeg/.moc/release/moc_predefs.h -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/mkspecs/win32-g++ -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/imageformats/jpeg -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/3rdparty/libjpeg -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/3rdparty/libjpeg/src -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/include/QtGui/5.12.0 -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/include/QtGui/5.12.0/QtGui -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/include -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/include/QtGui -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/include/QtCore/5.12.0 -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/include/QtCore/5.12.0/QtCore -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/include/QtCore -IC:/msys64/mingw64/include/c++/8.2.1 -IC:/msys64/mingw64/include/c++/8.2.1/x86_64-w64-mingw32 -IC:/msys64/mingw64/include/c++/8.2.1/backward -IC:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/8.2.1/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/8.2.1/include-fixed -IC:/msys64/mingw64/x86_64-w64-mingw32/include main.h -o .moc/release/moc_main.cpp
g++ -c -fno-keep-inline-dllexport -O2 -std=c++1z -fno-exceptions -Wall -W -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -ffunction-sections -fdata-sections -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_STATICPLUGIN -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DDBUS_STATIC_BUILD -DJAS_DLL=0 -I. -I../../../3rdparty/libjpeg -I../../../3rdparty/libjpeg/src -I../../../../include/QtGui/5.12.0 -I../../../../include/QtGui/5.12.0/QtGui -I../../../../include -I../../../../include/QtGui -I../../../../include/QtCore/5.12.0 -I../../../../include/QtCore/5.12.0/QtCore -I../../../../include/QtCore -I.moc/release -I\include -isystem C:/msys64/mingw64/include/dbus-1.0 -IC:/msys64/mingw64/lib/dbus-1.0/include -isystem C:/msys64/mingw64/include/mariadb -I../../../../mkspecs/win32-g++  -o .obj/release/moc_main.o .moc/release/moc_main.cpp
rm -f ../../../../plugins/imageformats/libqjpeg.a 2>/dev/null
ar -M < object_script.libqjpeg.Release
make[6]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/imageformats/jpeg'
make[5]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/imageformats/jpeg'
make[4]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/imageformats'
make[3]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins'
make[2]: *** [Makefile:825: sub-plugins-make_first] Error 2
make[2]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src'
make[1]: *** [Makefile:45: sub-src-make_first] Error 2
make[1]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase'
make: *** [Makefile:75: module-qtbase-make_first] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

tim_lebedkov@dev MINGW64 /c/msys64/repos/MINGW-packages/mingw-w64-qt5-static

[object_script.libqjpeg.Release.zip](https://github.com/Alexpux/MINGW-packages/files/2753220/object_script.libqjpeg.Release.zip)

**Comment by Alexpux** [comment]
@tim-lebedkov you dont show exact error. Look at your build log and find  real error message

**Comment by tim-lebedkov** [comment]
I thought that the directory name length could be a problem and renamed it. Now I get this error. Any ideas?

...
s-linked DBUS_LIBS=-ldbus-1 -lws2_32 -liphlpapi -openssl-linked -no-fontconfig -qt-freetype -qt-harfbuzz -qt-libjpeg -qt-libpng -qt-zlib -qt-pcre -icu -nomake examples
Creating qmake...
mkdir: cannot create directory ‘C:/msys64/r’: No such file or directory
==> ERROR: A failure occurred in build().
    Aborting...

tim_lebedkov@dev MINGW64 /c/msys64/r/p/mingw-w64-qt5-static
$

**Comment by tim-lebedkov** [comment]
back to  /c/msys64/repos/MINGW-packages/mingw-w64-qt5-static and now I get this error. Note that this time it is about libqgif, libqjpeg. There is no "real" error message in the log.

g++ -c -fno-keep-inline-dllexport -O2 -std=c++1z -fno-exceptions -Wall -W -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -ffunction-sections -fdata-sections -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_STATICPLUGIN -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DDBUS_STATIC_BUILD -DJAS_DLL=0 -I. -I../../../3rdparty/libjpeg -I../../../3rdparty/libjpeg/src -I../../../../include/QtGui/5.12.0 -I../../../../include/QtGui/5.12.0/QtGui -I../../../../include -I../../../../include/QtGui -I../../../../include/QtCore/5.12.0 -I../../../../include/QtCore/5.12.0/QtCore -I../../../../include/QtCore -I.moc/release -I\include -isystem C:/msys64/mingw64/include/dbus-1.0 -IC:/msys64/mingw64/lib/dbus-1.0/include -isystem C:/msys64/mingw64/include/mariadb -I../../../../mkspecs/win32-g++  -o .obj/release/moc_main.o .moc/release/moc_main.cpp
g++ -c -fno-keep-inline-dllexport -O2 -std=c++1z -fno-exceptions -Wall -W -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -ffunction-sections -fdata-sections -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_STATICPLUGIN -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DDBUS_STATIC_BUILD -DJAS_DLL=0 -I. -I../../../../include -I../../../../include/QtGui -I../../../../include/QtCore -I.moc/release -I\include -isystem C:/msys64/mingw64/include/dbus-1.0 -IC:/msys64/mingw64/lib/dbus-1.0/include -isystem C:/msys64/mingw64/include/mariadb -I../../../../mkspecs/win32-g++  -o .obj/release/moc_main.o .moc/release/moc_main.cpp
rm -f ../../../../plugins/imageformats/libqjpeg.a 2>/dev/null
ar -M < object_script.libqjpeg.Release
make[6]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/imageformats/jpeg'
make[5]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/imageformats/jpeg'
rm -f ../../../../plugins/imageformats/libqgif.a 2>/dev/null
ar -rc ../../../../plugins/imageformats/libqgif.a .obj/release/main.o .obj/release/qgifhandler.o .obj/release/moc_main.o
make[6]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/imageformats/gif'
make[5]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/imageformats/gif'
make[4]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/imageformats'
make[3]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins'
make[2]: *** [Makefile:825: sub-plugins-make_first] Error 2
make[2]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src'
make[1]: *** [Makefile:45: sub-src-make_first] Error 2
make[1]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase'
make: *** [Makefile:75: module-qtbase-make_first] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

tim_lebedkov@dev MINGW64 /c/msys64/repos/MINGW-packages/mingw-w64-qt5-static
$

**Comment by tim-lebedkov** [comment]
OK. Looking at the mingw-w64-qt5-static-5.12.0-2-x86_64-build.log the first error seems to be this one. I didn't knew that an error message could be that far away!

make[6]: Entering directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/sqldrivers/sqlite'
g++ -c -fno-keep-inline-dllexport -g -Og -std=c++1z -fno-exceptions -Wall -W -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -ffunction-sections -fdata-sections -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_COMPLETE -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_RTREE -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_EXCEPTIONS -DQT_STATICPLUGIN -DQT_PLUGIN -DQT_SQL_LIB -DQT_CORE_LIB -DDBUS_STATIC_BUILD -DJAS_DLL=0 -I. -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/3rdparty/sqlite -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/include/QtSql/5.12.0 -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/include/QtSql/5.12.0/QtSql -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/include/QtCore/5.12.0 -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/include/QtCore/5.12.0/QtCore -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/include -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/include/QtSql -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/include/QtCore -I.moc/debug -isystem C:/msys64/mingw64/include/dbus-1.0 -IC:/msys64/mingw64/lib/dbus-1.0/include -isystem C:/msys64/mingw64/include/mariadb -IC:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/mkspecs/win32-g++  -o .obj/debug/qsql_sqlite.o qsql_sqlite.cpp
make[6]: Entering directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/platforms/minimal'
g++ -fno-keep-inline-dllexport -g -Og -std=c++1z -fno-exceptions -Wall -W -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -ffunction-sections -fdata-sections -dM -E -o .moc/debug/moc_predefs.h ../../../../mkspecs/features/data/dummy.cpp
g++ -c -fno-keep-inline-dllexport -g -Og -std=c++1z -fno-exceptions -Wall -W -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -ffunction-sections -fdata-sections -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DQT_NO_FOREACH -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -DQT_STATICPLUGIN -DQT_PLUGIN -DQT_EVENTDISPATCHER_SUPPORT_LIB -DQT_FONTDATABASE_SUPPORT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DDBUS_STATIC_BUILD -DJAS_DLL=0 -I. -I../../../../include -I../../../../include/QtEventDispatcherSupport -I../../../../include/QtEventDispatcherSupport/5.12.0 -I../../../../include/QtEventDispatcherSupport/5.12.0/QtEventDispatcherSupport -I../../../../include/QtFontDatabaseSupport -I../../../../include/QtFontDatabaseSupport/5.12.0 -I../../../../include/QtFontDatabaseSupport/5.12.0/QtFontDatabaseSupport -I../../../../include/QtGui/5.12.0 -I../../../../include/QtGui/5.12.0/QtGui -I../../../../include/QtGui -I../../../../include/QtCore/5.12.0 -I../../../../include/QtCore/5.12.0/QtCore -I../../../../include/QtCore -I.moc/debug -I\include -I../../../3rdparty/freetype/include -isystem C:/msys64/mingw64/include/dbus-1.0 -IC:/msys64/mingw64/lib/dbus-1.0/include -isystem C:/msys64/mingw64/include/mariadb -I../../../../mkspecs/win32-g++  -o .obj/debug/qminimalintegration.o qminimalintegration.cpp
In file included from qminimalintegration.cpp:47:
../../../../include/QtFontDatabaseSupport/5.12.0/QtFontDatabaseSupport/private/qfreetypefontdatabase_p.h:1:10: fatal error: ../../../../../src/platformsupport/fontdatabases/freetype/qfreetypefontdatabase_p.h: No such file or directory
 #include "../../../../../src/platformsupport/fontdatabases/freetype/qfreetypefontdatabase_p.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[6]: *** [Makefile.Debug:984: .obj/debug/qminimalintegration.o] Error 1
make[6]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/platforms/minimal'
make[5]: *** [Makefile:40: debug-all] Error 2
make[5]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/platforms/minimal'
make[4]: *** [Makefile:44: sub-minimal-make_first] Error 2
make[4]: Leaving directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/platforms'
make[3]: *** [Makefile:99: sub-platforms-make_first] Error 2
make[3]: *** Waiting for unfinished jobs....
make -f Makefile.Release all
make[6]: Entering directory '/c/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/src/plugins/bearer/generic'
g++ -c -fno-keep-inline-dllexport -O2 -std=c++1z -fno-exceptions -Wall -W -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -ffunction-sections -fdata-sections -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_STATICPLUGIN -DQT_PLUGIN -DQT_NETWORK_LIB -DQT_CORE_LIB -DDBUS_STATIC_BUILD -DJAS_DLL=0 -I. -I../../../../include/QtNetwork/5.12.0 -I../../../../include/QtNetwork/5.12.0/QtNetwork -I../../../../include/QtCore/5.12.0 -I../../../../include/QtCore/5.12.0/QtCore -I../../../../include -I../../../../include/QtNetwork -I../../../../include/QtCore -I.moc/release -isystem C:/msys64/mingw64/include/dbus-1.0 -IC:/msys64/mingw64/lib/dbus-1.0/include -isystem C:/msys64/mingw64/include/mariadb -I../../../../mkspecs/win32-g++  -o .obj/release/qgenericengine.o qgenericengine.cpp
g++ -fno-keep-inline-dllexport -g -Og -std=c++1z -fno-exceptions -Wall -W -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -ffunction-sections -fdata-sections -dM -E -o .moc/debug/moc_predefs.h C:/msys64/repos/MINGW-packages/mingw-w64-qt5-static/src/x86_64/qtbase/mkspecs/features/data/dummy.cpp
g++ -fno-keep-inline-dllexport -O2 -std=c++1z -fno-exceptions -Wall -W -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -ffunction-sections -fdata-sections -dM -E -o .moc/release/moc_predefs.h ../../../../mkspecs/features/data/dummy.cpp

**Comment by tim-lebedkov** [comment]
Please ignore all my previous comments. The errors were caused by Qt not being able to compile with 2 parallel jobs. I was able to compile with the following settings:

```
_build_mode=-release

# Tune the following to decide how and what to build
if [ "${_variant}" = "-static" ]; then
  _namesuff="-static"
  _with_icu=no
  _with_fontconfig=no
  _with_openssl=no
  _with_dbus=no
  _system_freetype=no
  _system_zlib=no
  _system_pcre=no
  _system_libpng=no
  _system_libjpeg=no
  _system_harfbuzz=no
  _build_examples=no # examples result in > 100 GiB
  _build_tools=no
  _build_tests=no
  _make_docs=no # docs in shared qt5 are sufficient
#  _ltcg="yes"
  _ltcg="no"

```
If I set _build_tools to yes, I get this error:

```
make[3]: Entering directory '/c/msys64/repos/m/mingw-w64-qt5-static/src/x86_64/qttools/src/qdoc'
make -f Makefile.Release
make[4]: Entering directory '/c/msys64/repos/m/mingw-w64-qt5-static/src/x86_64/qttools/src/qdoc'
g++ -Wl,-s -static -Wl,-subsystem,console -Wl,--gc-sections -o ../../bin/qdoc.exe @object_script.qdoc.Release  -LC:/msys64/mingw64/lib -Wl,--start-group -lclangAnalysis -lclangApplyReplacements -lclangARCMigrate -lclangAST -lclangASTMatchers -lclangBasic -lclangChangeNamespace -lclangCodeGen -lclangCrossTU -lclangDaemon -lclangDriver -lclangDynamicASTMatchers Commit.cpp.obj EditedSource.cpp.obj RewriteObjCFoundationAPI.cpp.obj -lclangFormat -lclangFrontend -lclangFrontendTool -lclangHandleCXX -lclangIncludeFixer -lclangIncludeFixerPlugin -lclangIndex -lclangLex -lclangMove -lclangParse -lclangQuery -lclangReorderFields -lclangRewrite -lclangRewriteFrontend -lclangSema -lclangSerialization -lclang_static -lclangStaticAnalyzerCheckers -lclangStaticAnalyzerCore -lclangStaticAnalyzerFrontend -lclangTidy -lclangTidyAbseilModule -lclangTidyAndroidModule -lclangTidyBoostModule -lclangTidyBugproneModule -lclangTidyCERTModule -lclangTidyCppCoreGuidelinesModule -lclangTidyFuchsiaModule -lclangTidyGoogleModule -lclangTidyHICPPModule -lclangTidyLLVMModule -lclangTidyMiscModule -lclangTidyModernizeModule -lclangTidyMPIModule -lclangTidyObjCModule -lclangTidyPerformanceModule -lclangTidyPlugin -lclangTidyPortabilityModule -lclangTidyReadabilityModule -lclangTidyUtils -lclangTidyZirconModule -lclangTooling -lclangToolingASTDiff -lclangToolingCore -lclangToolingInclusions -lclangToolingRefactor -lfindAllSymbols -lLLVMLTO -lLLVMPasses -lLLVMObjCARCOpts -lLLVMSymbolize -lLLVMDebugInfoPDB -lLLVMDebugInfoDWARF -lLLVMMIRParser -lLLVMFuzzMutate -lLLVMCoverage -lLLVMTableGen -lLLVMDlltoolDriver -lLLVMOrcJIT -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMLanaiDisassembler -lLLVMLanaiCodeGen -lLLVMLanaiAsmParser -lLLVMLanaiDesc -lLLVMLanaiAsmPrinter -lLLVMLanaiInfo -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonAsmParser -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMBPFDisassembler -lLLVMBPFCodeGen -lLLVMBPFAsmParser -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMBPFAsmPrinter -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMARMUtils -lLLVMAMDGPUDisassembler -lLLVMAMDGPUCodeGen -lLLVMAMDGPUAsmParser -lLLVMAMDGPUDesc -lLLVMAMDGPUInfo -lLLVMAMDGPUAsmPrinter -lLLVMAMDGPUUtils -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils -lLLVMObjectYAML -lLLVMLibDriver -lLLVMOption -lLLVMWindowsManifest -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMLineEditor -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMCoroutines -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMScalarOpts -lLLVMLinker -lLLVMIRReader -lLLVMAsmParser -lLLVMInstCombine -lLLVMBitWriter -lLLVMAggressiveInstCombine -lLLVMTransformUtils -lLLVMAnalysis -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMBitReader -lLLVMCore -lLLVMBinaryFormat -lLLVMSupport -lLLVMDemangle -Wl,--end-group -lz -lz3 -lgomp -lpsapi -lshell32 -lole32 -luuid -ladvapi32 -lversion -LC:/msys64/repos/m/mingw-w64-qt5-static/src/x86_64/qtdeclarative/lib C:/msys64/mingw64/lib/libQt5QmlDevTools.a -LC:/msys64/repos/m/mingw-w64-qt5-static/pkg/mingw-w64-x86_64-qt5-static/mingw64/qt5-static/lib C:/msys64/repos/m/mingw-w64-qt5-static/pkg/mingw-w64-x86_64-qt5-static/mingw64/qt5-static/lib/libQt5Core.dll.a -LC:/msys64/repos/m/mingw-w64-qt5-static/src/x86_64/qtbase/lib C:/msys64/mingw64/lib/libQt5Core.dll.a
g++.exe: error: C:/msys64/repos/m/mingw-w64-qt5-static/pkg/mingw-w64-x86_64-qt5-static/mingw64/qt5-static/lib/libQt5Core.dll.a: No such file or directory
make[4]: *** [Makefile.Release:195: ../../bin/qdoc.exe] Error 1
make[4]: Leaving directory '/c/msys64/repos/m/mingw-w64-qt5-static/src/x86_64/qttools/src/qdoc'
make[3]: *** [Makefile:36: release] Error 2
make[3]: Leaving directory '/c/msys64/repos/m/mingw-w64-qt5-static/src/x86_64/qttools/src/qdoc'
make[2]: *** [Makefile:226: sub-qdoc-make_first] Error 2
make[2]: Leaving directory '/c/msys64/repos/m/mingw-w64-qt5-static/src/x86_64/qttools/src'
make[1]: *** [Makefile:43: sub-src-make_first] Error 2
make[1]: Leaving directory '/c/msys64/repos/m/mingw-w64-qt5-static/src/x86_64/qttools'
make: *** [Makefile:862: module-qttools-make_first] Error 2

```

**Comment by tim-lebedkov** [comment]
the problem is with qdoc only. If I modify the Makefile.Release by adding the missing libraries, it works. I don't know yet how to change the QMake files.
