### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by user706** [msys2/MINGW-packages#4866]
Hi, 

is someone working on packaging the newest cmake for https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-cmake ?
3.12.4 is "relatively old"...

since the 3.13.0 was already released on Nov 21, 2018.
And just a few hours ago **3.13.3** was released.

Would be a good point to package it.
I tried building 3.13.2 yesterday and that builds fine without patches (perhaps the same is true with the brand-new 3.13.3).
PS: Where do the patches for 3.12.4 come from: is it just to get it to compile, or is there more to it?

Thanks.

**Comment by Alexpux** [comment]
@user706 need someone to volunteer to fix qt5 patch for cmake. In other case we will stay on current package version

**Comment by user706** [comment]
Hi @Alexpux 

Could you please name project, suitable for testing this AUTOSTATICPLUGINS with cmake?
(Preferable a small project)

**Comment by lazka** [comment]
Our cmake is at 3.15.2 now.  Thanks @user706 for the PR.
