### ISSUE TITLE
nuitka fails to find Python headers

### ISSUE THREAD

**Issue by ghost** [msys2/MINGW-packages#4868]
I'm trying to use nuitka with mingw-w64-i686-python3 under msys2 but it throws up errors asking for .h files, is there a python3-dev package anywhere I can use? I have it working on a normal python setup so my compiler is setup correctly (visual studio and mingw-64.)

**Comment by Azza-NZ** [comment]
Just to confirm it is getting as far as the compiler before showing the error needing .h files.

**Comment by Azza-NZ** [comment]
I'm not sure how but I somehow installed the needed dev files, but I simply asked for more source file "crypt.h" , this page says it's known it's missing from mingw.

https://www.gnu.org/software/gnulib/manual/html_node/crypt_002eh.html

I was doing this because I wanted to use Python 3.7.2 with PyGobject and Nuitka, was anyone succesfully done that?

**Comment by EchterAgo** [comment]
I likely had this problem too. A package I tried to compile picked up the MSYS `Python.h` instead of the MinGW one. For me it was enough to remove the `python` package. You need to install `mingw-w64-x86_64-python3` (depending on whether you need 32/64 bits and Python 2 or 3)

**Comment by lazka** [comment]
I only get this, so likely nuitka is broken..

```
$ CC=gcc nuitka3 a.py

scons: warning: MSVC_USE_SCRIPT set to False, assuming environment set correctly.
File "C:/msys64/mingw32/lib/python3.7/site-packages/nuitka/build/inline_copy/lib/scons-3.0.4\SCons\Script\Main.py", line 609, in _scons_internal_warning
Error, no 'Python.h' development headers can be found at 'C:/msys64/mingw32/include', dependency not satisfied
```

**Comment by jayvdb** [comment]
Yes, Nuitka has a few problems with this setup.  I've got it working, under wine, and will post updates/patches referencing https://github.com/Nuitka/Nuitka/issues/43

**Comment by jayvdb** [comment]
Python 3.8 is in RC1 now.

Will it be replacing Python 3.7 when it is stable and all mingw Python packages build & pass smoke tests on it?

Or will it be a separate package which can be a bit experimental?

This is regarding Nuitka support of static standalone, which I would ideally like to solve at the same time https://github.com/Nuitka/Nuitka/issues/95

It might be easier to solve in Python 3.8 - still investigating that.

**Comment by lazka** [comment]
It'll replace 3.7, but it might take some time after the release to rebase our changes. 3.8 changed they way Python loads binary extensions on Windows, so that could result in additional work.

**Comment by andrewgohlk** [comment]
Still no solution to this?

**Comment by lazka** [comment]
I still get 

```
CC=gcc nuitka3 g.py
Error, no 'Python.h' development headers can be found at 'C:/msys64/mingw64/include', dependency not satisfied!
```

so likely nothing has changed.

**Comment by kuznetsov-m** [comment]
OS Ubuntu 18.40
Python 3.8.0
nuitka 0.6.9.4

Also:
```
Scons: Compiler used /usr/bin/gcc
Error, no 'Python.h' development headers can be found at 'C:/msys64/mingw64/include', dependency not satisfied!
```

**Comment by kayhayen** [comment]
Not sure what you guys are doing, checkout Nuitka/Nuitka#872 where I found it to be working out of the box with the correct packages installed, these being `python-devel python gcc`. Just don't use MinGW if you are not on Win32.

**Comment by MehdiChinoune** [comment]
@podsvirov Was it fixed?

**Comment by podsvirov** [comment]
As an alternative, I suggest trying the [pyinstaller](https://packages.msys2.org/base/mingw-w64-pyinstaller) package with similar functionality that we recently added.

**Comment by podsvirov** [comment]
> I still get
> 
> ```
> CC=gcc nuitka3 g.py
> Error, no 'Python.h' development headers can be found at 'C:/msys64/mingw64/include', dependency not satisfied!
> ```
> 
> so likely nothing has changed.

I think we can consider this problem solved, because it is not relevant right now.
For example, I'm doing well at the moment:
```
$ nuitka g.py
Nuitka-Options: Used command line options: g.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check
Nuitka-Options:WARNING: options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.4.10' on Python '3.11' commercial grade 'not
Nuitka: installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Non downloaded winlibs-gcc 'C:/msys64/ucrt64/bin/gcc.exe' is being ignored, Nuitka is
Nuitka-Scons: very dependent on the precise one.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this
Nuitka-Scons: stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 6
Nuitka: Keeping build directory 'g.build'.
Nuitka: Successfully created 'g.exe'.
Nuitka: Execute it by launching 'g.cmd', the batch file needs to set environment.
```

**Comment by jayvdb** [comment]
@lazka , I think this issue can be closed.
