### ISSUE TITLE
Python 3 as default python

### ISSUE THREAD

**Issue by FlyingWombat** [msys2/MINGW-packages#4950]
I suggest that Python 3 be made the default python target in Msys2.  
Python 2 [End of Life](https://pythonclock.org) is about 10 months from now.  

Arch Linux can be used as a reference for this, as they have had python3 as default for quite some time now.

Edit:
To clarify, I think `/mingw64/bin/python --version` should return `python 3.7.2` (or whatever latest version).  
Instead, `/mingw64/bin/python --version` returns `python 2.7.15`  
I understand this was done to preserve compatibility with legacy python programs. IMO it is a backwards way of doing things. I think this not just for python, but for any program: `foo` should execute the latest installed version, and older versions should be installed as `fooX.Y`.

One way this change could be made is to add a statement in the `prepare()` of every python2 PKGBUILD, to patch the shebang to target python2 explicitly.

**Comment by lazka** [comment]
I assume you mean the binary name? There is a new discussion upstream https://mail.python.org/pipermail/python-dev/2019-February/156272.html for changing PEP 394

**Comment by FlyingWombat** [comment]
Yes  
OP edited for clarification

**Comment by spl1inter** [comment]
cd bin; cp python3.exe python.exe ?

**Comment by FlyingWombat** [comment]
> OS file associations and internal scripts should always target the unversioned pointer image 

That's my point.  
For MSYS2-MINGW64, the unversioned python binary is an outdated version that is nearing end-of-life.  
I think that the unversioned python binary should be the *latest* version of python.

**Comment by lazka** [comment]
Once we get rid of python2 (#4993) we can switch python.exe over to python3, imo.

**Comment by lazka** [comment]
https://github.com/python/peps/pull/989 -> python can now point to python3

**Comment by lazka** [comment]
#5640 moves pip.exe

**Comment by lazka** [comment]
python.exe is Python3 since 228cc0cf1611d

The remaining scripts are moved in #5723
