### ISSUE TITLE
gexiv2 pkgbuild missing python typelib

### ISSUE THREAD

**Issue by prculley** [msys2/MINGW-packages#4956]
https://github.com/Alexpux/MINGW-packages/commit/0382541223a7f9bc071c120166975613b22a473b#diff-e4dbdea33c86089e6d39f05dbbc43dd6
Seems to be the source of the problem, the patch was deleted.

**Comment by Alexpux** [comment]
@prculley patch was deleted because build was migrated to meson from autoconf and patch was not relevant anymore. Feel free to fix it

**Comment by prculley** [comment]
I had figured out that my issue (missing Python bindings and code) was not directly related to the patch itself, but a different PKGBUILD setting.  I kind of hacked it up in the process of debugging so I'm not certain I should submit it...
I think the setting was disable-introspection=true I changed it to false to get my Python access back.

**Comment by revelator** [comment]
for anyone having problems with introspection, make sure to build with BUILDDIR=/C or the root of any other drive. Introspection has problems handling long path names, doing this allowed me to build any package that relied on introspection.

**Comment by lazka** [comment]
I've created #5303 for this.
