### ISSUE TITLE
Firebird is completely unstable - The main devs dropped support for GCC

### ISSUE THREAD

**Issue by tomay3000** [msys2/MINGW-packages#4992]
**fbclient.dll** shipped with **Msys2** is not stable at all, it make my application crashes all the time. Besides that, what is the point of it when it depends on **libwinpthread-1.dll** and **libgcc_s_dw2-1.dll** for static builds. So I decided to try generating **libfbclient.dll.a** from **fbclient.dll** shipped with **Firebird server v2.5** using the following commands:

`cd "/C/Program Files/Firebird/Firebird_2_5/bin"`
`gendef.exe fbclient.dll`
`dlltool.exe -l libfbclient.dll.a -D fbclient.dll -d fbclient.def -k`

I then tried it, this time it passed all the previous crashings but it still crashes on some situations.
I have switched to **SJLJ** Exceptions model and **Win32** Threads model, this time all went smoothly.

**Conclusion:** Even though I generated **libfbclient.dll.a** it is not enough to use **Dwarf**.

**Comment by spl1inter** [comment]
Thanks for that, I am collecting notes on how various thread and exception models impact 64-bit migration on many of my legacy packages and will make similar studies on my side.

**Comment by revelator** [comment]
My own build environment uses sjlj exclusively for that exact reason. Sadly im not even able to build firebird2 with any gcc newer than gcc-6.* . Would be preferable with seh but so far its 64 bit gcc only.
So im using an old build of firebird3 created with gcc-5.3 which does not crash, but has trouble with finding its config files (reloaction patches do not work correctly it seems, it looks for the in the root of the mingw dir, and not in /mingw*/etc).

**Comment by MehdiChinoune** [comment]
Firebird was updated to 5.0
