### ISSUE TITLE
[MinGW64/gcc 8.3.0] strndup missing in <string.h>

### ISSUE THREAD

**Issue by jannick0** [msys2/MINGW-packages#4999]
`MinGW64/gcc 8.3.0`: It appears that that `char* strndup(const char*s, size_t size)` is missing in the header `string.h`.

Not sure if this is the right place for this report, please advice otherwise.

**Comment by oscarfv** [comment]
Your report seems to imply that the function was present on previous versions.

AFAIK, those functions are not provided by GCC, but by the Mingw-w64 C runtime:

http://mingw-w64.org

**Comment by lazka** [comment]
strndup() is a POSIX function and not supported on Windows.

**Comment by jannick0** [comment]
> strndup() is [...] not supported on Windows.

Agree - as I can see. So on Windows `strndup` needs a quick default implementation to make things protable to Windows.

Thanks.

**Comment by StarWolf3000** [comment]
Freetype GL handles it like this, maybe a similar approach can be implemented for MINGW:
https://github.com/rougier/freetype-gl/blob/master/platform.c

**Comment by jannick0** [comment]
Thanks - This might be OK as long as the addition does not break the compilation of existing code which presumably offers a home-made version of `strndup` for `WIN32` compilation.  Something as you suggested could be thinkable when guarded by a mingw specific cpp macro, but - and I guess this is more compelling here - this thingy is simple enough to be quickly implemented when needed for `WIN32`.  So am now rather staying away from thinking it should be part of this package.

**Comment by ravipodila** [comment]
From which version onwards MinGW started supporting the Strings.h and string.h

**Comment by StarWolf3000** [comment]
> From which version onwards MinGW started supporting the Strings.h and string.h

string.h is an ANSI C standard header and has always been part of MINGW, while strings.h is just a wrapper for string.h in MINGW (it originally is a header which has legacy names of functions and non-ANSI functions, so you could also compile code that has used those legacy function calls). Outside of this, it is not used in any way in MINGW and you should always use string.h.

**Comment by Daniel-Abrecht** [comment]
strndup may be added to the c standard library starting with the c23 standard: https://en.cppreference.com/w/c/23#New_library_features
Therefore, it is no longer just a posix function, but a standard c function.

**Comment by Daniel-Abrecht** [comment]
The implementation linked above (https://github.com/rougier/freetype-gl/blob/master/platform.c) has multiple flaws:
* It copies n bytes even if s is smaller than n
* It allocates n bytes even if the memory needed to hold s is much smaller
* There is no check if n+1 overflows
* There is no check if malloc failed

**Comment by gnif** [comment]
Not sure why this was closed, but here is an implementation that does what is required:
```c
char * strndup(const char * src, size_t size)
{
  size_t len = strlen(src);
  len = len < size : len : size;
  char * dst = malloc(len + 1);
  if (!dst)
    return NULL;
  memcpy(dst, src, len);
  dst[len] = '\0';
  return result;
}
```

**Comment by Biswa96** [comment]
> Perhaps it's time to re-open this, as @Daniel-Abrecht correctly points out, it's part of the C standard now.

`strndup` is not exported from msvcrt.dll or ucrtbase.dll. Also it is neither defined in Windows SDK.

**Comment by jay** [comment]
> ```c
> char * strndup(const char * src, size_t size) {
>   size_t len = strlen(src);
> ```

Is it allowed to read past size? I suggest `memchr(src, '\0', size);` and if found then adjust len

**Comment by gnif** [comment]
> > ```c
> > char * strndup(const char * src, size_t size) {
> >   size_t len = strlen(src);
> > ```
> 
> Is it allowed to read past size? I suggest `memchr(src, '\0', size);` and if found then adjust len

Good point, I just updated my suggestion to use `strnlen`

**Comment by MehdiChinoune** [comment]
strndup is now part of mingw-w64, you could use with `-std=c23`
