### ISSUE TITLE
CodeLite doesn't use MSYS paths or toolchain

### ISSUE THREAD

**Issue by SamuraiCrow** [msys2/MINGW-packages#5002]
When I tried to build a new project with the MSYS2 version of CodeLite 12.0.9 it looked at the default Windows paths for all of its tools including the mingw32-make.exe instead of /usr/bin/make.exe so it won't build anything.  Likewise it used my broken install of "D:\Program Files\LLVM\clang.exe" instead of /mingw64/bin/clang.exe so is there some sort of toolchain configuration that can override the default paths using the MSYS2 install?  It should look closer to the Linux toolchain than the Windows one.

I forgot to mention that I'm trying to compile in C/C++ if you haven't figured that out by now.

**Comment by Alexpux** [comment]
@SamuraiCrow you need add msys2 and mingw paths to your environment to be able codelite use them

**Comment by SamuraiCrow** [comment]
Adding /mingw64/bin to the path helped.  Thanks.
