### ISSUE TITLE
SDL2-config tries to link -lmingw32 on 64-bit build

### ISSUE THREAD

**Issue by SamuraiCrow** [msys2/MINGW-packages#5003]
The default way to link on a BASH build of SDL2 is to do something like this:

> gcc list.o of.o objects.o -o executable.exe \`sdl2-config --libs\`

but the MinGW runtime is linked directly as if it weren't an MSYS package.  Is there a better way to do this?  Also, I tried copying and pasting the text from sdl2-config --libs and changing the -lmingw32 into an -lmingw64 and it still wouldn't link.  Leaving out the -mingw* term altogether also didn't link complaining about a missng WinMain symbol.

**Comment by Alexpux** [comment]
@SamuraiCrow there are no libmingw64 library. Both 32 and 64 bit library named mingw32

**Comment by SamuraiCrow** [comment]
Thanks.  It appears to have been a path error.
