### ISSUE TITLE
which Packages to install

### ISSUE THREAD

**Issue by schnedann** [msys2/MINGW-packages#5014]
Hi, simple Question,
for example the emacs packages: there are three of them
 MSYS ~
$ pacman -Ss emacs
mingw32/mingw-w64-i686-emacs 26.1-1
    The extensible, customizable, self-documenting, real-time display editor (mingw-w64)
mingw64/mingw-w64-x86_64-emacs 26.1-1 [Installiert]
    The extensible, customizable, self-documenting, real-time display editor (mingw-w64)
msys/emacs 26.1-1 (editors)
    The extensible, customizable, self-documenting, real-time display editor (msys2)

on my computer at work i have installed the mingw64 one, at home the msys version.
And, they seem to differ! for example the file .../runemacs.exe was missing in the msys version, but it exists in the mingw version

and I cant find a word of explaination in the wiki...

help welcome!

**Comment by oscarfv** [comment]
Which wiki? MSYS2 or Emacs'?

That is how Emacs works. `runemacs.exe` is exclusive of Emacs on Windows. As MSYS2 is a POSIX emulation layer, `runemacs.exe` is not included on the MSYS2 package. And that's only the tip of the iceberg.

Unless you want to run Emacs on POSIX, install the "native" mingw-w64 packages, either the 32 bits (i686) or the 64 bits (x86_64) variant depending on your operative system and preferences.

If this answers your question, please close this issue.

**Comment by schnedann** [comment]
MSYS2 wiki, but OK your explanation makes some sense, so my answer is answered in preferring  mingw-w64 packages over msys  if both exist
