### ISSUE TITLE
mingw-w64-x86_64-plplot issue with gtk-fortran

### ISSUE THREAD

**Issue by vmagnin** [msys2/MINGW-packages#5047]
Hi,
I am working on the gtk-fortran project (https://github.com/vmagnin/gtk-fortran) which is a GTK / Fortran binding. My gtk3devel branch builds and runs great in MSYS2-MINGW-W64 (Windows 7), except the examples which are using PLplot (5.13).

In fact, there is no error or warning messages building them with CMake, even in Debug mode. But when I try to launch them, I obtain the following kind of error about a libgfortran-5.dll:

```
$ ./hl_plplot17e.exe
  gtk-fortran/build/plplot/hl_plplot17e.exe: error while loading shared libraries: libgfortran-5.dll: cannot open shared object file: No such file or directory
```
PLplot was installed via the MSYS shell:

    $ pacman -S mingw-w64-x86_64-plplot mingw-w64-x86_64-qhull mingw-w64-x86_64-gd

And the gfortran version installed in MSYS2 is:

```
$ gfortran --version
GNU Fortran (Rev1, Built by MSYS2 project) 8.2.1 20181214
```
So I guess that some PLplot package has perhaps been built with a previous gfortran version ?

**Comment by Alexpux** [comment]
@vmagnin new plplot-5.14.0 uploaded. Test it

**Comment by vmagnin** [comment]
@Alexpux

I have done the PLplot 5.14 upgrade via:
$ pacman -S mingw-w64-x86_64-plplot

Now our project gtk-fortran is 100% building and running in MSYS2 / Windows 7 ! Thanks very much.

It was a long time I had not tested things like MSYS or Cygwin. And I am astonished to see how easy it is now to install and use, and that whole projects developed under Linux can be built and run under Windows without any modification !
