### ISSUE TITLE
python3 debug build syntax errors

### ISSUE THREAD

**Issue by lovetox** [msys2/MINGW-packages#5048]
Hi i build the python3 mingw package with the debug option in the PKGBUILD file

this results in a python3 installation that has a syntax error in

`python3.7\lib-dynload\_sysconfigdata_dm_win32_.py`

around the string

`INCLDIRSTOMAKE`

which breaks for example meson

is this a python bug or a problem with how msys builds that?

**Comment by Alexpux** [comment]
@lovetox well it can be issue with patching this file. Feel free to find the problem)

**Comment by lazka** [comment]
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.7\sysconfig.py", line 620, in get_config_var
    return get_config_vars().get(name)
  File "C:/msys64/mingw64/lib/python3.7\sysconfig.py", line 569, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "C:/msys64/mingw64/lib/python3.7\sysconfig.py", line 440, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
  File "C:/msys64/mingw64/lib/python3.7/lib-dynload\_sysconfigdata_dm_win32_.py", line 518
    sys.prefix + '/include/python3.7dm',
      ^
SyntaxError: invalid syntax
>>>
```

**Comment by lovetox** [comment]
@lazka i also have a patch for this that gets rid of the sed replacing, i will upload it today, maybe you could review it

right now we have to places where we replace paths

1. the 0000-patch that is applied
2. PKGBUILD sed operations

this approach is in my opinion hard to review and extend in the future and prone to breakage

**Comment by lazka** [comment]
Yeah, I tried to keep it simple for starters.

My thinking was we could write the values out in the place 0000-patch patches one by one
in python syntax and replace things there. What's your plan?

**Comment by lovetox** [comment]
```python
    replacement = """
        keys_to_replace = [
            'BINDIR', 'BINLIBDEST', 'CONFINCLUDEDIR',
            'CONFINCLUDEPY', 'DESTDIRS', 'DESTLIB', 'DESTSHARED',
            'INCLDIRSTOMAKE', 'INCLUDEDIR', 'INCLUDEPY',
            'LIBDEST', 'LIBDIR', 'LIBPC', 'LIBPL', 'MACHDESTLIB',
            'MANDIR', 'SCRIPTDIR', 'datarootdir', 'exec_prefix',
        ]

        prefix = build_time_vars["BINDIR"][:-4]

        for key in keys_to_replace:
            value = build_time_vars.get[key]
            build_time_vars[key] = value.replace(prefix, sys.prefix)"""

    with open(destfile, 'w', encoding='utf8') as f:
        f.write('import sys\n')
        f.write('# system configuration generated and used by'
                ' the sysconfig module\n')
        f.write('build_time_vars = ')
        pprint.pprint(vars, stream=f)
        f.write('\n%s' % textwrap.dedent(replacement))
```

This is what i had planned, so we dont touch the code of the original dict, instead add code to _sysconfigdata.py which alters the dict at module load time in python syntax

**Comment by lovetox** [comment]
I also would add a test where we load something that loads this module, just to see if `build_time_vars.get[key]` throws a KeyError because python removed some keys from this dict that we alter

**Comment by lovetox** [comment]
https://github.com/lovetox/MINGW-packages/commit/7d40bcf641659d8fec743602e25e5ec944fcd791

**Comment by lazka** [comment]
Nice!

* Can't we just do this for all str values so this wont break on upstream changes?
* Aren't there paths in there starting with `/lib` or `/include`?

**Comment by lovetox** [comment]
I installed the normal python build opened `_sysdataconfig.py` extracted all keys that had `sys.prefix` in them and these you can see now in the list.

So if we do more than that we venture into new territory and i am not knowledgeable enough to know what all these paths do and how this would break something

The original prefix we replace is `/mingw`

there is no other key that has a path in it that starts with this prefix, but there are keys in there that have full paths like in my case ` 'LIBFFI_INCLUDEDIR': 'C:/msys64_debug/mingw64/lib/libffi-3.2.1/include',`

if we replace in this str `/mingw` with `sys.prefix` it will break ans sys.prefix is a absolute path.

Also i dont know for what use case this is needed at all, when do we modify sys.prefix at runtime?

the python installation is already very portable, at least i never saw problems with it.

**Comment by lovetox** [comment]
In case you care for the other keys that contain `mingw64`

CONFIGURE_CPPFLAGS
CONFIG_ARGS
CPPFLAGS
LIBFFI_INCLUDEDIR
OPENSSL_INCLUDES
OPENSSL_LDFLAGS
PY_BUILTIN_MODULE_CFLAGS
PY_CORE_CFLAGS
PY_CPPFLAGS
PY_STDMODULE_CFLAGS

**Comment by lazka** [comment]
> So if we do more than that we venture into new territory and i am not knowledgeable enough to know what all these paths do and how this would break something

ok, fair enough.

> Also i dont know for what use case this is needed at all, when do we modify sys.prefix at runtime?

I don't think it was used to because it can be modified, just to remove all paths from the source so one can grep for them to see potential problems with non-relocatable stuff.

----

anyway, if the result is not worse than before, please open a PR :)

**Comment by lovetox** [comment]
@lazka offtopic question:

when i use the debug version of python, the gi packages dont work anymore, for example cairo, or python3-gobject.

they seem to have a python3.7m.dll installed, so is my assumption correct that they are build against the normal python version, and hence dont work with the debug version?

how can i make these packages work

**Comment by lazka** [comment]
Afair you need to rebuild everything with the debug build because they are not ABI compatible and have different filenames for DLLs. There could still be msys2 specific bugs in addition to that of course, because I doubt that gets much testing.

**Comment by lovetox** [comment]
my GLib resolving code crashes inside python, i have a traceback but without symbols, so to get these i tried to use python debug build, but its very hard to get all the deps running on it

**Comment by lazka** [comment]
oh, you probably want something like this then (untested), so you get a normal Python with debug info:

```
--- a.txt	2019-03-16 18:07:38.058159666 +0100
+++ b.txt	2019-03-16 18:08:19.526327028 +0100
@@ -37,7 +37,7 @@
          "${MINGW_PACKAGE_PREFIX}-sqlite3"
         )
 makedepends=("${MINGW_PACKAGE_PREFIX}-gcc" "${MINGW_PACKAGE_PREFIX}-pkg-config")
-options=('makeflags') # 'debug' '!strip' )
+options=('makeflags' 'debug' '!strip' )
 source=("https://www.python.org/ftp/python/${pkgver%rc?}/Python-${pkgver}.tar.xz"
         0000-make-_sysconfigdata.py-relocatable.patch
         0001-fix-_nt_quote_args-using-subprocess-list2cmdline.patch
@@ -336,7 +336,6 @@
     #    CXXFLAGS+=" -DDEBUG -DPy_DEBUG -D_DEBUG "
     CFLAGS+=" -O0 -ggdb"
     CXXFLAGS+=" -O0 -ggdb"
-    _extra_config+=("--with-pydebug")
   fi
 
   # Workaround for conftest error on 64-bit builds
@@ -371,7 +370,7 @@
   if check_option "debug" "n"; then
     VERABI=${_pybasever}m
   else
-    VERABI=${_pybasever}dm
+    VERABI=${_pybasever}m
   fi
 
   # gdb pretty printers for debugging Python itself; to use:
```

**Comment by lovetox** [comment]
Ah nice, thanks i will test this

**Comment by lovetox** [comment]
This works great thanks !
