### ISSUE TITLE
Wrong dependency libreadline7.dll

### ISSUE THREAD

**Issue by TinoM** [msys2/MINGW-packages#5049]
Our automatic builds fail since March 7th, the day libreadline was updated to version8.

Current build log: https://ci.appveyor.com/project/widelands-dev/widelands/builds/23023011/job/eagv6s8fe5e212ga

Last successful build: https://ci.appveyor.com/project/widelands-dev/widelands/builds/22831079/job/8xqh11ri4m6rsurw

I've connected to the build image and started our binary manually => "Could not be started because libreadline7.dll is missing"

The logfs should show every package we are installing. The build script contains a pacman -Syuu, so everything is up to date.

Analyzing the resulting .exe with dependenywalker shows that libfluidsynth-2.dll depends on libreadline7.dll

**Comment by Alexpux** [comment]
@TinoM rebuilded fluidsynth uploaded
