### ISSUE TITLE
Random failure of build toolchains in specific Windows versions

### ISSUE THREAD

**Issue by FrankHB** [msys2/MINGW-packages#5067]
Not sure it is related some segfaults already reported here like [this](#4266), but it should be concerned: some segfaults may be [caused by the Windows kernel bug](https://randomascii.wordpress.com/2018/02/25/compiler-bug-linker-bug-windows-kernel-bug/).

Both the compiler and linker randomly fail after the update to Windows 10 1809 in my configuration. It also fails in WSL Arch Linux's GCC 8.2.1. Moreover, even Firefox with some legacy addons crashed randomly previously in last year after a manual update to 1809 to avoid [the annoying bug of KB4467682](https://www.zdnet.com/article/windows-10-bsod-pricey-surface-book-2s-bricked-by-latest-1803-update/), and downgrading to 1803 seemed to fix all problems, until the recent auto-update of 1809 again. (Now I am using [Basilisk](http://www.basilisk-browser.org/) built by myself and it does not crash yet.) So, it is apparently not MSYS2-specific and not GCC-specific.

I suspect the kernel bug as the reason because all ill-behaved programs are (very likely) using memory mapped I/O. The strange thing is that the blog post states that the kernel bug has likely been already fixed in 1809, and it is still a heisenbug not always reproducible even in the same machine, so I am not sure it is the exact reason. (Or is it just a Windows kernel regression in 1809?)

As such kind of bugs may be also related to the output binary (e.g. #4959) and there can be some possibilities to work around in the toolchain, I first report the issue here and request to investigate the build environment used.

Perhaps it should be further reported in upstreams (i.e. gcc and binutils) to do workaround like [MSVC](https://developercommunity.visualstudio.com/content/problem/191590/linker-needs-workaround-for-windows-kernel-bug.html) if this is confirmed.

**Comment by spl1inter** [comment]
>
Both the compiler and linker randomly fail after the update to Windows 10 1809 in my configuration
>

What crash? Specific backtrace or debug info?

**Comment by FrankHB** [comment]
The error message during compiling would usually be "internal compiler error". The linker error might be "
collect2.exe: error: ld returned 5 exit status". Sometimes they'd fail silently.

I found [this question at SO](https://stackoverflow.com/questions/45077846/collect2-exe-error-ld-returned-5-exit-status) then, but it could fail without '-Wl,--no-gc-sections' so this should not be the reason.

Since I have rolled back the system to 1803, everything is OK again. So, it still looks like a Windows bug.

**Comment by FrankHB** [comment]
Today another Windows 10 machine has upgraded and failed similarly. So, it still looks like a Windows 10 1809 bug.

While building PCH files, there are error messages like [this](http://community.axoloti.com/t/error-when-going-live-with-the-patching/583). More other errors follow (failure on opening headers, etc).

**Comment by FrankHB** [comment]
Windows 10 1903 (18362.175) seems to has the bug fixed. Not sure what is the exact but, though.
