### ISSUE TITLE
msys64  gfortran  not found for gcc

### ISSUE THREAD

**Issue by JamesBWhite** [msys2/MINGW-packages#5098]
I installed the 64 bit and did pacman to install gcc vim and cmake ;
and **gcc -v** shows: 
mickey@Mickeys64 MINGW64 /c/msys64
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-msys/7.4.0/lto-wrapper.exe
Target: x86_64-pc-msys
Configured with: /msys_scripts/gcc/src/gcc-7.4.0/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible
Thread model: posix
gcc version 7.4.0 (GCC)

mickey@Mickeys64 MINGW64 /c/msys64
----------------------
But as you can see Fortran is not there???? 
mickey@Mickeys64 MINGW64 /c/msys64
$ **gfortran -v**
bash: gfortran: command not found

mickey@Mickeys64 MINGW64 /c/msys64
$ fortran -v
bash: fortran: command not found

mickey@Mickeys64 MINGW64 /c/msys64
$

How can this be fixed ?

Tanks,
Mickey

**Comment by JamesBWhite** [comment]
Here is a list of the executables in the \usr\bin  (gfortran is not there) 
[msys64.exe.list.txt](https://github.com/msys2/MINGW-packages/files/2990627/msys64.exe.list.txt)
[msys64.exe.list.txt](https://github.com/msys2/MINGW-packages/files/2990628/msys64.exe.list.txt)

**Comment by VishnuEriyat** [comment]
Hi, Im having a similar problem, finally for you how it got resolved

**Comment by JamesBWhite** [comment]
I am not sure, I think I did this: 
`sudo apt-get install gcc gfortran g++  `
It was a long time ago ! 
Also I use Cobol,  GnuCOBOL and they have an install that builds this too. I think msys64 is outdated, you should try to install MSYS2  for windows.  It is newer. Arnold Tremby has an install that may work for you. 
https://sourceforge.net/p/gnucobol/discussion/help/thread/964872d6a2/

**Comment by VishnuEriyat** [comment]
Thanks
