### ISSUE TITLE
why closed no fortran

### ISSUE THREAD

**Issue by JamesBWhite** [msys2/MINGW-packages#5101]
I installed the 64 bit and did pacman to install gcc vim and cmake ;
and gcc -v shows:
mickey@Mickeys64 MINGW64 /c/msys64
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-msys/7.4.0/lto-wrapper.exe
Target: x86_64-pc-msys
Configured with: /msys_scripts/gcc/src/gcc-7.4.0/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible
Thread model: posix
gcc version 7.4.0 (GCC)

mickey@Mickeys64 MINGW64 /c/msys64
But as you can see Fortran is not there????
mickey@Mickeys64 MINGW64 /c/msys64
$ gfortran -v
bash: gfortran: command not found

mickey@Mickeys64 MINGW64 /c/msys64
$ fortran -v
bash: fortran: command not found

mickey@Mickeys64 MINGW64 /c/msys64
$

How can this be fixed ?

Tanks,
Mickey

**Comment by Alexpux** [comment]
@JamesBWhite ````pacman -S gcc-fortran````

**Comment by JamesBWhite** [comment]
Alexpux, ok I just saw that install, I will try it tonight when I get home.  Thanks!

**Comment by JamesBWhite** [comment]
It did work. 
THANKS !
