### ISSUE TITLE
does mingw64-gdb could not debug pe32?

### ISSUE THREAD

**Issue by Byzero512** [msys2/MINGW-packages#5104]
![image](https://user-images.githubusercontent.com/36794026/54830237-17b4ce80-4cf3-11e9-9001-081ec75d3c50.png)
![image](https://user-images.githubusercontent.com/36794026/54830258-226f6380-4cf3-11e9-9d4f-c489c04ae3c4.png)

**Comment by Alexpux** [comment]
For 32 bit binaries you need use 32 bit GDB

**Comment by revelator** [comment]
alex is right, this is because the compilers are not multilib so they dont support programs with bitness besides there own. 
mingw32 -> 32 bit debugging only.
mingw64 -> 64 bit debugging only.

**Comment by ssbssa** [comment]
Since gdb 10 it's possible to [debug 32 bit executables with a 64 bit gdb](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gdb/NEWS;hb=e5213e2c851c295c5e4c3e9b52606c1012029b67#l848).

**Comment by Byzero512** [comment]
got that.
