### ISSUE TITLE
avr-gcc issue

### ISSUE THREAD

**Issue by exoizzy** [msys2/MINGW-packages#5105]
im new to msys2 and qmk so bear with me here. Im following these instructions here: [https://docs.qmk.fm/#/newbs_getting_started](https://docs.qmk.fm/#/newbs_getting_started) and got tried to make a file and got this error:

> $ make keebio/nyquist/rev2:default
> QMK Firmware 0.6.320
> Making keebio/nyquist/rev2 with keymap default

> /bin/sh: avr-gcc: command not found
> sh: avr-gcc: command not found
> sh: avr-gcc: command not found
> make[1]: *** [tmk_core/rules.mk:369: .build/obj_keebio_nyquist_rev2_default/comp                                                      > iler.txt] Error 127
> Make finished with errors
> make: *** [Makefile:551: keebio/nyquist/rev2:default] Error 1

i dont really know what this means, is it an error with the fie for the nyquist or am i missing some sort of supporting library? thanks in advance for any help or advice

**Comment by Alexpux** [comment]
@exoizzy we don’t provide avr-gcc

**Comment by StarWolf3000** [comment]
MSYS2/MINGW is only used for Git and the build tools used by that project. But you forgot to run `util/msys2_install.sh` to let it download the AVR build environment for Windows.

Please only post here issues, if you encounter problems with the MINGW part of MSYS2.

**Comment by stahta01** [comment]
@exoizzy Please close this thread if it is no longer needed.
