### ISSUE TITLE
Can't find gtk4 

### ISSUE THREAD

**Issue by trayres** [msys2/MINGW-packages#5120]
I see there was a commit for gtk4 preview, but even if I update (-Syuu) and clean cache (-Scc) I can't seem to find it with pacman -Ss gtk4.

**Comment by oscarfv** [comment]
The fact that a PKGBUILD exists on this repo does not imply that there exists a corresponding binary package. Either the binary package is on the process of being published or, more likely, the package is considered experimental/work-in-progress/unstable.

**Comment by lazka** [comment]
Yeah, gtk4 hasn't been released yet. The PKGBUILD in git is the last (and quite old now) experimental release.

**Comment by trayres** [comment]
Thanks for the clarification
