### ISSUE TITLE
Applications linked with winpthread can not be run on Windows XP

### ISSUE THREAD

**Issue by vovams** [msys2/MINGW-packages#5139]
An application linked with winpthread fails to start on Windows XP due to missing `GetTickCount64()` function in `kernel32.dll`. This function in available only starting from Vista. The dependency seems to come from [this commit][1] in winpthread. The use of `GetTickCount64()` is surrounded by `#if _WIN32_WINNT >= _WIN32_WINNT_VISTA`, but apparently the library was built with a high enough value of `_WIN32_WINNT`.

Do you still support building software for Windows XP? I did not found anything about supported target platforms on the website and wiki.

[1]: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/52f2ce12c6182bd239e4f1bbffcd420997b64b08/

**Comment by mati865** [comment]
Targeted Windows version is set here: https://github.com/msys2/MINGW-packages/blob/4a7eb3e90bc008e80274b7d2968269a5ea38156c/mingw-w64-headers-git/PKGBUILD#L58

**Comment by vovams** [comment]
That line comes from 6665c4fe22989f157c31db3a6fbc5a7d19c5674e. So, does that mean that building for Windows XP is no longer supported? Can i rebuild winpthread locally, or will i need to rebuild other libs too?

**Comment by mati865** [comment]
Hard to tell, theoretically anything linked to libs build for Win7 may not work on XP.

**Comment by vovams** [comment]
I downgraded mingw-w64-i686-libwinpthread-git and mingw-w64-i686-winpthreads-git to 7.0.0.5273.3e5acf5d-1 according to instructions in wiki and it seems to work. At least for now.

**Comment by oscarfv** [comment]
@vovams : developers of winpthread and other runtime libraries bumped the minimum supported OS version to Windows 7 time ago because they want to take advantage of new APIs. This is not going to change. And MSYS2/Cygwin do not support Windows XP any more.

If this answer your question please close this issue. Thanks.

**Comment by vovams** [comment]
Yeah, thanks. You might want to consider writing a list of supported Windows versions somewhere. Because i was unable to find that information.

**Comment by mingwandroid** [comment]
You Micky want to consider touching up your googling skills. http://www.msys2.org/ clearly states this.

Supporting insecure OSes does no one a favor.

**Comment by vovams** [comment]
If you are talking about this phrase:

> Current MSYS2 can't be installed on Windows XP anymore.

Then i have seen this. Being able to build *on* XP and being able to build *for* XP are different things. I would not call it "clearly".

**Comment by trufanov-nok** [comment]
> I downgraded mingw-w64-i686-libwinpthread-git and mingw-w64-i686-winpthreads-git to 7.0.0.5273.3e5acf5d-1 according to instructions in wiki and it seems to work. At least for now.

Just leaving here a few commands for that in case someone will search:

```
wget http://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz
wget http://repo.msys2.org/mingw/i686/mingw-w64-i686-winpthreads-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz

pacman -U --noconfirm mingw-w64-i686-libwinpthread-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz mingw-w64-i686-winpthreads-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz

rm mingw-w64-i686-libwinpthread-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz
rm mingw-w64-i686-winpthreads-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz
```

**Comment by tomay3000** [comment]
What about **InitializeConditionVariable** for **zstd** !?
How to solve this!?

**Comment by pileon** [comment]
> Supporting insecure OSes does no one a favor.

Except when one have to maintain legacy systems still running on such an OS.

**Comment by jbruchon** [comment]
> Supporting insecure OSes does no one a favor.

Security isn't the only thing that matters. I have a netbook that will never have Windows Vista or up but that plays classic Windows games perfectly fine. Supporting it does me a favor.

**Comment by sskras** [comment]
Also it lets software to run on ReactOS, which implement NT5.1/5.2 APIs and is very much in development.

**Comment by sskras** [comment]
Also the support would enable software on ReactOS, which implements NT5.1/5.2 APIs and is very much in development.

**Comment by Biswa96** [comment]
This project does not target ReactOS or any Windows platform older that Windows 7. Feel free to compile your own version.

**Comment by nambona890** [comment]
> > I downgraded mingw-w64-i686-libwinpthread-git and mingw-w64-i686-winpthreads-git to 7.0.0.5273.3e5acf5d-1 according to instructions in wiki and it seems to work. At least for now.
> 
> Just leaving here a few commands for that in case someone will search:
> 
> ```
> wget http://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz
> wget http://repo.msys2.org/mingw/i686/mingw-w64-i686-winpthreads-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz
> 
> pacman -U --noconfirm mingw-w64-i686-libwinpthread-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz mingw-w64-i686-winpthreads-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz
> 
> rm mingw-w64-i686-libwinpthread-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz
> rm mingw-w64-i686-winpthreads-git-7.0.0.5273.3e5acf5d-1-any.pkg.tar.xz
> ```

Small problem: They purged those versions of winpthread. There's no archive of them I can find.

**Comment by Midar** [comment]
This should fix it: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/cb7f42e05b94cbb1d94edcebdbfb47b652a45484/
