### ISSUE TITLE
readline-7 history fails when writing to an existing history file

### ISSUE THREAD

**Issue by lostbard** [msys2/MINGW-packages#5143]
When compiling code example:

    #include <stdio.h>
    #include <readline/history.h>

    int main (int argc, char **argv)
    {
      using_history ();

      add_history ("test1");
      if(write_history ("history_file") !=0)
        perror("1st");
      if(write_history ("history_file") !=0)
        perror("2nd");

      return 0;
    }

using mingw-w64-x86_64-readline 7.0.003-1

the readline write_history will fail if the history file already exists.

This is due to a change in readline 7 where they started to use the rename function to copy the new file over the old history file - however in windows rename fails if the file already exists.

I sent a possible solution to readline mailing list for readline 8 (patch attached), The msg thread is at
http://lists.gnu.org/archive/html/bug-readline/2019-04/msg00000.html

[0001-Add-private-history_rename-function-and-in-WIN32-use.zip](https://github.com/msys2/MINGW-packages/files/3044197/0001-Add-private-history_rename-function-and-in-WIN32-use.zip)

**Comment by Alexpux** [comment]
@lostbard currenly we are on readline 8 already

**Comment by lostbard** [comment]
It is the same issue with readline 8

**Comment by revelator** [comment]
readline has allways been tricky on windows, the 1.6 version works however.

**Comment by Alexpux** [comment]
@lostbard done in https://github.com/msys2/MINGW-packages/commit/c20809f03137a9a2469b7f4fa8a564375c1ca9cf
