### ISSUE TITLE
Sed producing wrong results

### ISSUE THREAD

**Issue by AntonioCS** [msys2/MINGW-packages#5145]
Hello,

I have the following code in a Makefile:
```
export IMAGE_TAG=$(shell git symbolic-ref --short HEAD | sed 's/[^a-zA-Z0-9_.-]/_/g')
```
So if the result from the command is this: feature/branch
It is suppose to be replaced with: feature_branch

The issue is that the `sed` command is doing the reverse, it's replacing every alphanumeric with _ and leaving behind the rest so from `feature/branch` I get `_______/_______`

This works on Mac and Linux (debian) but fails in Msys2
Here is `sed` info:

```
$ sed --version
sed (GNU sed) 4.7
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jay Fenlason, Tom Lord, Ken Pizzini,
Paolo Bonzini, Jim Meyering, and Assaf Gordon.
GNU sed home page: <https://www.gnu.org/software/sed/>.
General help using GNU software: <https://www.gnu.org/gethelp/>.
E-mail bug reports to: <bug-sed@gnu.org>.
```

**Comment by oscarfv** [comment]
`sed` is an MSYS2 package here, isn't it? Then the correct place to report bugs is

https://github.com/msys2/MSYS2-packages

If you agree please close this issue. Thanks.

**Comment by AntonioCS** [comment]
Right... sorry
