### ISSUE TITLE
python3 must not update $PATH

### ISSUE THREAD

**Issue by mattn** [msys2/MINGW-packages#5146]
python3 command update $PATH.

https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-python3/0565-mingw-add-ModuleFileName-dir-to-PATH.patch#L28

Vim can use python interface called if_python using libpython3.7m.dll. When using Vim with if_python, Py_Initialize update $PATH environment variable. So when using another python environment like miniconda and open python file in Vim, `:!python` command use mingw's python.exe instead of conda's one.

**Comment by Alexpux** [comment]
@mattn we add python to PATH to solve problems with loading modules

**Comment by mattn** [comment]
Yes, prepending path into $PATH often make new problem. How about appending to last instead of prepending?

**Comment by lazka** [comment]
Oh, that explains all the meson PATH issues I'm having :(

@Alexpux do you remember what this fixes by any chance?

**Comment by Alexpux** [comment]
@lazka I dont remember what it was but maybe @mingwandroid remember

**Comment by Alexpux** [comment]
@lazka this was added by @mingwandroid 
https://github.com/msys2/MINGW-packages/commit/8fa89a9a18c63d4bf861a172f1b94ce52636e9cf#diff-83fbd35688f51e49829b450b0dd82a09

**Comment by lazka** [comment]
Thanks, I guess the comment means this:

* some/path/to/python3 -c "import tkinter" 
* loads lib\python3.7\lib-dynload\_tkinter-cpython-37m.dll
* which tries to find tcl86.dll and tk86.dll
* fails because the python3 dir isn't in PATH

**Comment by lazka** [comment]
Maybe we should backport https://github.com/python/cpython/commit/2438cdf0e932a341c7613bf4323d06b91ae9f1f1 which will be in 3.8 anyway. I'll give that a try.

**Comment by lazka** [comment]
> Yes, prepending path into $PATH often make new problem. How about appending to last instead of prepending?

I went with this in #5223
