### ISSUE TITLE
mingw-w64-i686-webkitgtk3 depends on libicu61

### ISSUE THREAD

**Issue by paukonen** [msys2/MINGW-packages#5147]
And libicu61 is not available. Current version is 62.
Renaming is not helping - version number is hardcoded in some function names.

**Comment by revelator** [comment]
webkitgtk was deprecated, its a very old and unstable package. Unfortunatly later versions no longer work with windows (tons of patches needed), so don't expect this to be updated. If you can fix the build problems on windows, patches are welcome.

**Comment by lazka** [comment]
Also see https://github.com/msys2/MINGW-packages/issues/5207#issuecomment-483400667
