### ISSUE TITLE
mingw-w64-qt5: qdoc linking fails due to libclang

### ISSUE THREAD

**Issue by zgyarmati** [msys2/MINGW-packages#5160]
Unfortunately t seems the clang related linking errors are not totally sorted out yet, my (dynamic) build fails with:

`g++ -Wl,-s -Wl,-subsystem,console -o ../../bin/qdoc.exe
@object_script.qdoc.Release  -LD:/msys64_devel/mingw64/lib
-Wl,--start-group -lclangAnalysis -lclangApplyReplacements
-lclangARCMigrate -lclangAST -lclangASTMatchers -lclangBasic
-lclangChangeNamespace -lclangCodeGen -lclangCrossTU -lclangDaemon
-lclangDriver -lclangDynamicASTMatchers Commit.cpp.obj
EditedSource.cpp.obj RewriteObjCFoundationAPI.cpp.obj -lclangFormat
-lclangFrontend -lclangFrontendTool -lclangHandleCXX -lclangIncludeFixer
-lclangIncludeFixerPlugin -lclangIndex -lclangLex -lclangMove
-lclangParse -lclangQuery -lclangReorderFields -lclangRewrite
-lclangRewriteFrontend -lclangSema -lclangSerialization -lclang_static
-lclangStaticAnalyzerCheckers -lclangStaticAnalyzerCore
-lclangStaticAnalyzerFrontend -lclangTidy -lclangTidyAbseilModule
-lclangTidyAndroidModule -lclangTidyBoostModule
-lclangTidyBugproneModule -lclangTidyCERTModule
-lclangTidyCppCoreGuidelinesModule -lclangTidyFuchsiaModule
-lclangTidyGoogleModule -lclangTidyHICPPModule -lclangTidyLLVMModule
-lclangTidyMiscModule -lclangTidyModernizeModule -lclangTidyMPIModule
-lclangTidyObjCModule -lclangTidyPerformanceModule -lclangTidyPlugin
-lclangTidyPortabilityModule -lclangTidyReadabilityModule
-lclangTidyUtils -lclangTidyZirconModule -lclangTooling
-lclangToolingASTDiff -lclangToolingCore -lclangToolingInclusions
-lclangToolingRefactor -lfindAllSymbols -lLLVMLTO -lLLVMPasses
-lLLVMObjCARCOpts -lLLVMMIRParser -lLLVMSymbolize -lLLVMDebugInfoPDB
-lLLVMDebugInfoDWARF -lLLVMCoverage -lLLVMMCA -lLLVMTableGen
-lLLVMDlltoolDriver -lLLVMXRay -lLLVMOrcJIT -lLLVMXCoreDisassembler
-lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter
-lLLVMWebAssemblyDisassembler -lLLVMWebAssemblyCodeGen
-lLLVMWebAssemblyDesc -lLLVMWebAssemblyAsmPrinter
-lLLVMWebAssemblyAsmParser -lLLVMWebAssemblyInfo
-lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser
-lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter
-lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser
-lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter
-lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser
-lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter
-lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter
-lLLVMMSP430Disassembler -lLLVMMSP430CodeGen -lLLVMMSP430AsmParser
-lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter
-lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser
-lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter
-lLLVMLanaiDisassembler -lLLVMLanaiCodeGen -lLLVMLanaiAsmParser
-lLLVMLanaiDesc -lLLVMLanaiAsmPrinter -lLLVMLanaiInfo
-lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonAsmParser
-lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMBPFDisassembler
-lLLVMBPFCodeGen -lLLVMBPFAsmParser -lLLVMBPFDesc -lLLVMBPFInfo
-lLLVMBPFAsmPrinter -lLLVMARMDisassembler -lLLVMARMCodeGen
-lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter
-lLLVMARMUtils -lLLVMAMDGPUDisassembler -lLLVMAMDGPUCodeGen
-lLLVMAMDGPUAsmParser -lLLVMAMDGPUDesc -lLLVMAMDGPUInfo
-lLLVMAMDGPUAsmPrinter -lLLVMAMDGPUUtils -lLLVMAArch64Disassembler
-lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc
-lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils
-lLLVMObjectYAML -lLLVMLibDriver -lLLVMOption -lLLVMOptRemarks
-lLLVMWindowsManifest -lLLVMTextAPI -lLLVMFuzzMutate
-lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen
-lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc
-lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils
-lLLVMMCJIT -lLLVMLineEditor -lLLVMInterpreter -lLLVMExecutionEngine
-lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMCoroutines -lLLVMipo
-lLLVMInstrumentation -lLLVMVectorize -lLLVMScalarOpts -lLLVMLinker
-lLLVMIRReader -lLLVMAsmParser -lLLVMInstCombine -lLLVMBitWriter
-lLLVMAggressiveInstCombine -lLLVMTransformUtils -lLLVMAnalysis
-lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMMC
-lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMBitReader -lLLVMCore
-lLLVMBinaryFormat -lLLVMSupport -lLLVMDemangle -Wl,--end-group -lz -lz3
-lgomp -lpsapi -lshell32 -lole32 -luuid -ladvapi32 -lversion
-LD:/src/MINGW-packages/mingw-w64-qt5/src/x86_64/qtdeclarative/lib
D:/src/MINGW-packages/mingw-w64-qt5/src/x86_64/qtdeclarative/lib/libQt5QmlDevTools.a
-LD:/src/MINGW-packages/mingw-w64-qt5/src/x86_64/qtbase/lib
D:/src/MINGW-packages/mingw-w64-qt5/src/x86_64/qtbase/lib/libQt5Core.dll.a
make[4]: Leaving directory
'/d/src/MINGW-packages/mingw-w64-qt5/src/x86_64/qtconnectivity/examples/bluetooth/btfiletransfer'

g++.exe: error: Commit.cpp.obj: No such file or directory

g++.exe: error: EditedSource.cpp.obj: No such file or directory

g++.exe: error: RewriteObjCFoundationAPI.cpp.obj: No such file or directory

make[4]: *** [Makefile.Release:197: ../../bin/qdoc.exe] Error 1`

**Comment by oscarfv** [comment]
Do the mentioned obj files exist in the directory where the command is executed? Why the obj files are listed after some libraries? And why the obj files are listed inside `--start-group/--end-group` directives?

I'm not familiar with Qt, but I see nothing that points to `libclang` as the problem here.

**Comment by Alexpux** [comment]
@zgyarmati @oscarfv this is due to this changes:
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-qt5/0052-qt-5.11-mingw-fix-link-qdoc-with-clang.patch#L176
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-qt5/0052-qt-5.11-mingw-fix-link-qdoc-with-clang.patch#L186

But this workaround not working during build

**Comment by revelator** [comment]
Is this after the recent upgrade to clang 8?.
Maybe the bug we had with linking qdoc to libclang from the version 7 clang package has had some changes thst fixed the linker bug we experienced back then. Though most of the problem stemmed from a binutils bug that made ld unable to link huge libraries, so that would be rather weird.

**Comment by Alexpux** [comment]
@revelator this is long standing bug

**Comment by MeerMusik** [comment]
Hello. Any update on this? Just changed all my Build Scripts from using MinGW-w64 to MinGW-w64 on MSYS2 - and I am now obviously have the same Problem. Is there any solution in sight? A work around? Anything? Another Issue with not having QDoc.exe compiled is, that the Translations do not get build either. Thanks!

**Comment by MehdiChinoune** [comment]
likely fixed, We build qt5-tools 5.15.5 with no issue.
