### ISSUE TITLE
Cannot get a2p Awk to Perl installed n my msys2/mingw64

### ISSUE THREAD

**Issue by abdulbadii** [msys2/MINGW-packages#5175]
Many on my msys2/ming64 are not available such as a2p Awk to Perl not installed and if I type

$ perldoc -f perlfunc
No documentation for perl function 'perlfunc' found

How to solve and get all these ? please help!

**Comment by StarWolf3000** [comment]
The same reason as here: https://github.com/msys2/MSYS2-packages/issues/1614#issuecomment-482451927
