### ISSUE TITLE
wutime linking error

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#5183]
glib build has started to fail under x86:

```
FAILED: subprojects/glib/glib/libglib-2.0-0.dll 
ccache cc @subprojects/glib/glib/libglib-2.0-0.dll.rsp
subprojects/glib/glib/9812f34@@glib-2.0@sha/gstdio.c.obj: In function `wutime':
C:/msys64/mingw32/i686-w64-mingw32/include/sys/utime.h:106: undefined reference to `_imp___wutime32'
collect2.exe: error: ld returned 1 exit status
```

Does anyone have any ides?

@lhmouse you seem to have touched wutime recently

**Comment by lhmouse** [comment]
Yes it was <https://github.com/mingw-w64/mingw-w64/commit/fde585a1ef36580c3a8d3675fae6d3191c4c3ac2>. I am looking for a fix now.

**Comment by lhmouse** [comment]
Apologize for the trouble. Please try [this patch](https://github.com/msys2/MINGW-packages/files/3076512/0001-crt-msvcrt.def.in-Export-_utime32-and-_wutime32-on-x.patch.txt).

**Comment by lazka** [comment]
I'll try tomorrow, thanks for the quick response!

**Comment by lazka** [comment]
I can confirm that glib builds fine with the patch applied. thanks!

**Comment by lhmouse** [comment]
Thanks for testing. I pushed it.
