### ISSUE TITLE
python3: inet_ntop() not available

### ISSUE THREAD

**Issue by lovetox** [msys2/MINGW-packages#5184]
Hi,

on the current python3 package `socket.inet_ntop()` is not available, although the python docs say its available for Windows.

I checked on my windows python3 installation and its available there.

**Comment by lazka** [comment]
My guess would be that the HAVE_INET_PTON check in configure.ac doesn't work on Windows.

**Comment by lovetox** [comment]
thanks @lazka for the quick fix

**Comment by lovetox** [comment]
How long until this is available via pacman?

**Comment by Alexpux** [comment]
If you need quick - you can build yourself, don’t see problems

**Comment by lovetox** [comment]
@Alexpux yes i know that, i just wanted to know how often the build job on the server runs, once a week, once a day, do you do it yourself?

**Comment by Alexpux** [comment]
I don’t use any build server. All packages are builded by me in right order

**Comment by lazka** [comment]
@lovetox the new version is in. (btw you can follow updates -> https://msys2.duckdns.org/updates)

**Comment by lovetox** [comment]
nice, thanks for the notice
