### ISSUE TITLE
Dll Error- The specified module could not be found

### ISSUE THREAD

**Issue by arvindpro** [msys2/MINGW-packages#5203]
Hi

When trying to install vala I get the above message with this specific error-

Warning: Could not load "C:\msys32\mingw32\bin\libgvplugin_neato_layout-6.dll" 

I checked at the location specified and the file is there.

I even changed the execution of the msys2 shell to "Run as Administrator" even then the same error occurs.

I am using Windows 10 64 bit. Please let me know how to resolve this error.

Yours sincerely,
Arvind.

**Comment by oscarfv** [comment]
Please copy & paste the exact commands you executed and produce the warning. Also mention the shell type you use (MSYS2, MSYS2-Mingw32, MSYS2-Mingw64, etc).

**Comment by arvindpro** [comment]
Hi

This is the command I ran in the MSYS2 Shell-
 pacman -S  mingw-w64-i686-vala
Total 27 packages including the vala package above have to be installed.
The error messages occurs during/after installation of the 26th package-
Given below is the message-
(26/27) installing mingw-w64-i686-graphviz         [#####################] 100%
Warning: Could not load "C:\msys32\mingw32\bin\libgvplugin_neato_layout-6.dll" - The specified module could not be found.
Warning: Could not load "C:\msys32\mingw32\bin\libgvplugin_neato_layout-6.dll" - The specified module could not be found.
(27/27) installing mingw-w64-i686-vala             [#####################] 100%

I checked in WIndows Explorer and the DLL file is there at the specified location.

Yours sincerely,
Arvind.

**Comment by oscarfv** [comment]
First of all, those are not error messages, they are warnings. The installation completes. Also, it seems that the problem occurs while installing graphviz, not vala.

I'll say that some script is trying to execute or test something and fails. Loading a dll can fail for various reasons. It is possible that whatever outputs the warnings is misreporting the cause of the failure as "could not be found".

Does vala work?

P.D.: just after installing the graphviz package, an script executes `mingw32/bin/dot -c`, which produces the warnings. You can execute that command on the shell and see the same warnings. Examining the dll with Dependency Walker shows that it depends on a missing dll: `libgts-0-7-5.dll`. Googling a bit indicates that the library might belong to GTS. Indeed, installing `mingw-w64-i686-gts` makes the warning go away. So the problem consists on a missing dependency on Graphviz's PKGBUILD.

To @arvindpro : just `pacman -S mingw-w64-i686-gts` and you should be fine.
