### ISSUE TITLE
Newly created app- how to get all dependency DLL files for a working and correctly compiled application

### ISSUE THREAD

**Issue by arvindpro** [msys2/MINGW-packages#5204]
Hi,

I have compiled and run an app I am workig on successfully, using the msys2 shell.

Now I want to package the app as a windows executable with its dependency DLL files.

How do I get the names and locations of these DLL files without which my Windows (32 bit) app will not work?

Sorry if this question sounds silly I am a newbie to MSYS2.

Yours sincerely,
Arvind.

**Comment by StarWolf3000** [comment]
If you create applications, that are not supposed to be used within MSYS2, use the MINGW environment instead. The MSYS2 environment does not support the creation of "portable" applications, you would need a lot of MSYS2-only libraries to package with it. MSYS2 applications always require msys-2.0.dll and their dependencies to be distributed (and no, you also cannot static link, this is not supported in MSYS2).

The MSYS2 build environment is made for packages to be used in MSYS2.

Recommended way to publish your applications:
Build them again within MINGW32 or MINGW64 environment and then not only can you make them more portable (they get linked to msvcrt.dll instead, which is available on any Windows), but also statically linked.

**Comment by oscarfv** [comment]
You can use `ntldd` https://github.com/LRN/ntldd (also available as a Mingw* package:

`pacman -Ss ntldd`

Please close this issue if your question is answered.

**Comment by ewheelerinc** [comment]
Copy your .EXE to a directory like build64/ and then run this a few times:

```
ntldd.exe build64/*|grep -iv system32|grep -v :$  | cut -f2 -d\> | cut -f1 -d\( | tr \\ / |while read a; do ! [ -e "build64/`basename $a`" ] && cp -v "$a" build64/; done
```

**Comment by Biswa96** [comment]
This question has already been answered.
