### ISSUE TITLE
Failed to load shared library 'libwebkitgtk-3.0-0.dll' despite dll file existing in mingw64 lib and bin folders

### ISSUE THREAD

**Issue by ThiccLikeBlart** [msys2/MINGW-packages#5207]
I am running Mingw64 via MSYS2 on Windows 10 and trying to run Python code that originally worked on Linux. I downloaded mingw-w64-x86_64-webkitgtk3 because the code references this package, but when I run the code I get the following message:

Failed to load shared library 'libwebkitgtk-3.0-0.dll' referenced by the typelib: 'libwebkitgtk-3.0-0.dll': The specified module could not be found.

I have tried renaming the dll file in the Mingw64 folder, since its default name is libwebkitgtk-3.0.dll.a, but no variations have made any difference. I also downloaded every webkitgtk-related package in Mingw64 but that did not help either (and the dll file the program wants is where it seemingly should be in Mingw64's lib folder anyways, so I don't know how this could have helped). I have also tried uninstalling and reinstalling MSYS2, and this did not help.

The code that references Webkit is the following, in case this is helpful:

`
#!/usr/bin/env python3
import gi
from PIL import Image
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk as gtk
from gi.repository import Gdk as gdk
gi.require_version('WebKit', '3.0')
from gi.repository import WebKit as webkit
from threading import Timer

idle = False
firstload = True
tidle = ""

#WOW
class Opac():

    def __init__(self):
        # Create window
        self.much_window = gtk.Window()
        self.much_window.set_icon_from_file('doge.jpg')
        self.much_window.connect('destroy', lambda w: gtk.main_quit())
        self.much_window.set_default_size(1000, 800)
        self.much_window.set_decorated(False)
        self.much_window.fullscreen()

        # Create navigation bar

        self.so_navigation = gtk.HBox()
        self.so_navigation.override_background_color(gtk.StateType.NORMAL, gdk.RGBA(13107, 13107, 13107))
        self.many_back = gtk.ToolButton(gtk.STOCK_GO_BACK)
        self.such_forward = gtk.ToolButton(gtk.STOCK_GO_FORWARD)
        imgBack = gtk.Image()
        imgBack.set_from_file('./back.png')
        self.many_back.set_icon_widget(imgBack)
        imgHome = gtk.Image()
        imgHome.set_from_file('./home.png')
        self.such_forward.set_icon_widget(imgHome)
        self.wow_address_bar = gtk.Entry()

        self.many_back.connect('clicked', self.go_back)
        self.such_forward.connect('clicked', self.go_forward)

        self.wow_address_bar.connect('activate', self.load_page)

        self.so_navigation.pack_start(self.many_back, False, True, 0)
        self.so_navigation.pack_start(self.such_forward, False, True, 0)
        self.so_navigation.pack_start(self.wow_address_bar, True, True, 0)

        # Create view for webpage
        self.very_view = gtk.ScrolledWindow()
        self.such_webview = webkit.WebView()
        self.such_webview.open('http://mcpl.monroe.lib.in.us/Search/default.aspx')
        self.such_webview.connect('title-changed', self.change_title)
        self.such_webview.connect('load-committed', self.change_url)
        self.very_view.add(self.such_webview)

        # Add everything and initialize
        self.wow_container = gtk.VBox()
        self.wow_container.pack_start(self.so_navigation, False, True, 0)
        self.wow_container.pack_start(self.very_view, True, True, 0)

        self.much_window.add(self.wow_container)
        self.much_window.show_all()
        self.wow_address_bar.hide()
        tidlestart = Timer(20,self.reset)
        tidlestart.start()
        gtk.main()

    def load_page(self, widget):
        so_add = self.wow_address_bar.get_text()
        if 'monroe' in so_add:            
            if so_add.startswith('http://') or so_add.startswith('https://'):
                self.such_webview.open(so_add)
            else:
                so_add = 'http://' + so_add
                self.wow_address_bar.set_text(so_add)
                self.such_webview.open(so_add)
        elif 'mcpl' in so_add:            
            if so_add.startswith('http://') or so_add.startswith('https://'):
                self.such_webview.open(so_add)
            else:
                so_add = 'http://' + so_add
                self.wow_address_bar.set_text(so_add)
                self.such_webview.open(so_add)
        else:
            self.such_webview.open('file://' + '/home/exec/Desktop/monroe.html')

    def change_title(self, widget, frame, title):
        self.much_window.set_title(title)

    def reset(self):
        global idle
        if idle:
            self.go_home()
        else:
            tidle = Timer(20,self.reset2)
            tidle.start()
            idle = True

    def reset2(self):
        global idle
        if idle:
            self.go_home()
        else:
            tidle = Timer(20,self.reset)
            tidle.start()
            idle = True

    def change_url(self, widget, frame):
        global idle
        global firstload
        idle = False
        uri = frame.get_uri()
        if 'monroe' in uri:  
            self.wow_address_bar.set_text(uri)
        elif 'mcpl.info' in uri:  
            self.wow_address_bar.set_text(uri)
        else:
            self.such_webview.open('file://' + '/home/exec/Desktop/monroe.html')

    def go_back(self, widget):
        self.such_webview.go_back()

    def go_forward(self, widget):
        self.such_webview.open('http://mcpl.monroe.lib.in.us/Search/default.aspx')

    def go_home(self):
        self.such_webview.open('http://mcpl.monroe.lib.in.us/Search/default.aspx')

wow = Opac()
`

As far as I know, the inability to use WebkitGTK is the only thing that is keeping the code from creating the desired webpage successfully. I used pacman -S to download the webkitgtk3 package, and I use the command python3 (name of file) to run it. echo $MSYSTEM returns MINGW64.

**Comment by oscarfv** [comment]
`libwebkitgtk-3.0.dll.a` is not a dll, but an import library. On Windows, import libraries are used by the linker to know which symbols a dll exports. Import libraries live in `/mingw??/lib`, proper dlls are usually in `/mingw??/bin`. So, in your case, `libwebkitgtk-3.0.dll` (without the trailing `.a`) should be on `/mingw64/bin`. Some packages put some dlls elsewhere. Some Tcl-related packages, for instance.

If `libwebkitgtk-3.0.dll` is not in `/mingw64/bin`, check which package installed `libwebkitgtk-3.0.dll.a`:

```
pacman -Qo /mingw64/lib/libwebkitgtk-3.0.dll.a
```

Now go to `/var/cache/pacman/pkg` and list the contents of that package to see if the dll is there.

**Comment by Alexpux** [comment]
Webkitgtk package is not maintaining anymore. I will remove it from database tomorrow. Don’t use it as it completely broken now.

**Comment by ThiccLikeBlart** [comment]
Thank you both for your quick responses. Does this mean no form of Webkitgtk will be supported in MSYS2 in the near future? And would you be able to recommend any possible packages I could use instead?

**Comment by Alexpux** [comment]
@ThiccLikeBlart yeah we dont have plans to support webkitgtk packages. If you can you can voluteer this work for updating webkitgtk
