### ISSUE TITLE
Clang produces bad binary with -gsplit-dwarf

### ISSUE THREAD

**Issue by ghost** [msys2/MINGW-packages#5215]
Binaries compiled with -gsplit-dwarf produce this error at startup:
-bash: ./out: cannot execute binary file: Exec format error

Compile any program like this:
clang -g -gsplit-dwarf main.c -o out
-gsplit-dwarf worked fine on clang-7.0.1-1, and broke in clang-8.0.0-1.
-g is also needed because -gsplit-dwarf does not automatically enable -g on windows.

Sample program:
int main() { return 0; }

**Comment by Alexpux** [comment]
@Giloh report upstream, we not maintainers of clang
