### ISSUE TITLE
boost 1.70.0 broken

### ISSUE THREAD

**Issue by josch** [msys2/MINGW-packages#5233]
It seems the new upload of boost 1.70.0 is broken. We now get loads of undefined references when building. We regularly build our project 3DTK on appveyor. Here the last successful builds with boost 1.69.0:

https://ci.appveyor.com/project/josch/3dtk/builds/23917748/job/4x69y28b43eisdkw

And here the first failing one that was triggered by a daily cron job and thus is building the exact same source as the last successful build 12 hours before:

https://ci.appveyor.com/project/josch/3dtk/builds/23934292/job/imn4tv91bg6oqhmg

**Comment by Alexpux** [comment]
@dsisnero for me it looks like your program not linking with libboost_program_options-mt.dll.a

**Comment by josch** [comment]
The project is using CMake and as I pointed out, the code did not change between it working and now breaking. Indeed we are linking against boost program options, specifically `${Boost_PROGRAM_OPTIONS_LIBRARY}`:

https://github.com/3DTK/3DTK/blob/master/src/show/CMakeLists.txt#L6

Maybe this is a bug in CMake which is unable to accommodate for a change in boost?

**Comment by iDunk5400** [comment]
I also have problems building with boost 1.70.0 in MSYS2 when using cmake, at least with the supplied cmake 3.13.4.

```
-- Found Boost 1.70.0 at C:/msys64/mingw64/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS system;filesystem;thread;date_time;chrono;regex;serialization;program_options;locale
-- Found boost_headers 1.70.0 at C:/msys64/mingw64/lib/cmake/boost_headers-1.70.0
-- Found boost_system 1.70.0 at C:/msys64/mingw64/lib/cmake/boost_system-1.70.0
-- No suitable boost_system variant has been identified!
--   libboost_system-mt.dll.a (shared, Boost_USE_STATIC_LIBS=ON)
--   libboost_system-mt.a (shared runtime, Boost_USE_STATIC_RUNTIME=ON)
CMake Error at C:/msys64/mingw64/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Found package configuration file:

    C:/msys64/mingw64/lib/cmake/boost_system-1.70.0/boost_system-config.cmake

  but it set boost_system_FOUND to FALSE so package "boost_system" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

Call Stack (most recent call first):
  C:/msys64/mingw64/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  C:/msys64/mingw64/share/cmake-3.13/Modules/FindBoost.cmake:264 (find_package)
  CMakeLists.txt:887 (find_package)


-- Configuring incomplete, errors occurred!
```

[https://gitlab.kitware.com/cmake/cmake/issues/18865](https://gitlab.kitware.com/cmake/cmake/issues/18865)

The suggested workaround of setting `Boost_NO_BOOST_CMAKE` worked for me.

**Comment by algo99** [comment]
It's not bug, it's like a new way of using Boost with CMake using the Boost own BoostConfig.cmake instead of the one from CMake distribution. Unfortunately it's not documented or at least I could not find the documentation, so it took me a pair of hours today to figure it out.

Old way:
```cmake
set(Boost_NO_BOOST_CMAKE ON)

find_package(Boost REQUIRED COMPONENTS thread timer)

include_directories(${Boost_INCLUDE_DIRS}
    ...)

link_directories(${Boost_LIBRARY_DIRS}
    ...)

target_link_libraries(...
    ${Boost_LIBRARIES
    ...}
```

New way:
```cmake
set(Boost_NO_BOOST_CMAKE OFF)

find_package(Boost REQUIRED COMPONENTS thread timer)

target_link_libraries(
    ...
    Boost::thread
    Boost::timer
    ...)

```

**Comment by josch** [comment]
Changing my `CMakeLists.txt` to `Boost::foo` instead of `${Boost_foo}` did not solve my problem.

So what you are seeing is probably another problem? Anyways it seems clear that there is some kind of issue in the relationship between cmake and boost 0.70.0.

**Comment by algo99** [comment]
Forgot to mention, that for this to work for me I have to make the next settings as well
```cmake
set(Boost_USE_STATIC_LIBS OFF)
set(BUILD_SHARED_LIBS ON)
```
Btw. do you mean Boost 1.70 all the way, not 0.70 ?

**Comment by josch** [comment]
Apologies, I repeatedly mistyped 0.70 instead of 1.70.

**Comment by josch** [comment]
Okay, I found a workaround for my problem.

I don't have these linker flags anymore when I add

    set(Boost_NO_BOOST_CMAKE ON)

To my CMakeLists.txt. As far as I understand how `Boost_NO_BOOST_CMAKE` works, this hints to the problem being in boost's `BoostConfig.cmake` because it seems to work fine with cmake's FindBoost.

**Comment by nickoe** [comment]
A difference I see in the boost 1.69 and 1.70 packages are that the 1.70 package includes  `*.cmake` files while 1.69 does not. I guess that is part of the reason that `Boost_NO_BOOST_CMAKE=ON` is not needed for 1.69. I wonder if the cmake files are installed by intention. The boost release notes (for 1.70.0) does not seem to mention anything about cmake.

**Comment by Adsun701** [comment]
@nickoe I see from boostorg/boost#229 that between version 1.69 and 1.70 they added cmake config support, as well as a new option `--no-cmake-config`, which prevents installation of `*.cmake` files. I will try to look further into this tomorrow.

**Comment by nickoe** [comment]
Maybe it will be fixed in the next release of cmake
https://gitlab.kitware.com/cmake/cmake/merge_requests/2747
Found via https://gitlab.kitware.com/cmake/cmake/issues/18865

I have not tested cmake-git, but I guess we really should, and if that works I think this is a non issue with the next release of cmake.

**Comment by Adsun701** [comment]
@nickoe the merge request you mentioned is already in cmake version 3.14.2, which is the current mingw-w64 version here. I just made pull request #5326 to fix this issue.

**Comment by MehdiChinoune** [comment]
closing since the package has been updated
