### ISSUE TITLE
Seems like ICU 64 build is broken.

### ISSUE THREAD

**Issue by elohim-meth** [msys2/MINGW-packages#5238]
Library libicudt62.dll had size over 26 Mb.
Size of libicudt64.dll is 18 Kb. All data files has gone.
ICU functions (usprep_open for example) that want access to that data return U_FILE_ACCESS_ERROR.

**Comment by Alexpux** [comment]
@elohim-meth I think all is ok. Data stored in .dat file as described by option  ````--with-data-packaging=archive````, if you need data in dll you need pass value ````dll````

**Comment by elohim-meth** [comment]
According to ICU documentation storing data in dll is the default and preferred method. What was the reason to change this? After upgrading ICU to version 64 C driver for mongodb (mongoc) compiles fine, but fails at runtime with mentioned error. This was very hard to debug and determine why it was failing. And I'm still not sure why it can't find this data. Obviously this error was introduced by upgrading.

**Comment by Alexpux** [comment]
@elohim-meth it was done here : https://github.com/msys2/MINGW-packages/commit/efc055741534fcf26c561123c8becac1261bd139#diff-f1b923a95a79218b3e95c8de8ddc69ed

Need ask @wirx6 I think

**Comment by elohim-meth** [comment]
I resolved it by setting environment variable ICU_DATA to <MSYS>\mingw64\share\icu\64.1
It was really hard to track the issue down to that ICU building change.

**Comment by Alexpux** [comment]
@elohim-meth probably need revert this change

**Comment by oscarfv** [comment]
As hinted in the commit message pointed by Alexpux the intention was to reduce size, which seems it did comparing the size of the previous and current binary packages. But apparently the author forgot to test if icu is able to find the data archive without external help.

**Comment by elohim-meth** [comment]
After latest upgrade files are in invalid places. libicudt64.a is in bin folder and libicudt64.dll is in lib folder.
And bin and lib folders contain dll and a files respectively, but of invalid size.

**Comment by oscarfv** [comment]
Yeah, looks like a full revert of efc055741534fcf26c561123c8becac1261bd139 is necessary.

Or fix the `--with-data-packaging=archive` functionality teaching icu how to locate the data when installed on an arbitrary directory.

**Comment by elohim-meth** [comment]
Now everything is working. Thanks!
