### ISSUE TITLE
FFMPEG libvpx Fail - ABI Mismatch

### ISSUE THREAD

**Issue by Beinsezii** [msys2/MINGW-packages#5239]
When encoding video using the libvpx, it fails with
> Failed to initialize encoder. ABI version mismatch.

tested with
> ffmpeg -i in.mp4 -c:v vp9 -an out.webm

Everything's up to date via pacman -Syu
It says ffmpeg is using 1.8.0 which is the version in the log and that's the version that's installed, so I'm not sure what's up. Same video converts successfully with the same command on Linux. All other encoders I've tried also work fine in MSYS2.

**Comment by Adsun701** [comment]
@Beinsezii #5242 fixes this issue and has already been merged.
