### ISSUE TITLE
Cannot build GDAL using mingw32-make

### ISSUE THREAD

**Issue by Gpinchon** [msys2/MINGW-packages#5245]
I am trying to build a minimal GDAL version using MINGW64.
When trying to use mingw32-make, the compilation fails because g++ can't find any local headers. It is working fine when using MSYS2 make (But I get other issues later so it's not a solution)...

The issue seems to be happening more or less randomly. The exact same compilation line will fail in mingw32-make and succeed when launched from the shell.

The ticked I opened on GDAL's github (even though I am not sure they can do anything about it...) : https://github.com/OSGeo/gdal/issues/1429

**Comment by mingwandroid** [comment]
mingw32-make is not something I'd recommend anyone to use.

If you are going to use it then you need to take care to ensure Makefiles never contain posix paths. They must contain windows mixed paths only (C:/msys64/mingw64 for example).

**Comment by Gpinchon** [comment]
Oh ! I was not aware mingw32-make only took windows-kindof paths, that's a strange breed indeed...
It explains a lot thanks.
