### ISSUE TITLE
qtcreator segfaults on startup

### ISSUE THREAD

**Issue by Optiligence** [msys2/MINGW-packages#5252]

**Comment by GallifreyZhang** [comment]
I also have this problem. When I start qtcreator , it's Segmentation fault.
Then I find it's  CppTools plugin cause this.
But I can't solve it.

**Comment by GallifreyZhang** [comment]
I'm sorry, it's ProjectExplorer plugin.
But When I run `qtcreator -noload all -load Core ProjectExplorer` , qtcreator can start without error.
