### ISSUE TITLE
minizip version is different from zlib minizip

### ISSUE THREAD

**Issue by OmegaDoom** [msys2/MINGW-packages#5255]
Hello.
I have tried to build assimp-git and compilation failed because it assumes that zlib has it's own minizip that is different from minizip that is installing with current zlib PKGBLD.

minizip 1.2 is installing but should be 1.1.

**Comment by oscarfv** [comment]
What I see in zlib's PKGBUILD is that zlib version is 1.2.11 and the accompanying minizip is 1.2.

Are your packages up to date? (Execute `pacman -Suy`).

**Comment by OmegaDoom** [comment]
Yes, packages are up to date.
It's exactly what i'm talking about.
zlib version is 1.2.11 and it has minizip in it's 'contrib' folder.
But that minizip is different from minizip that is used in zlib PKGBUILD.
It's 1.2 but should be 1.1.

**Comment by oscarfv** [comment]
Why minizip's version should be 1.1? Is it documented somewhere?

**Comment by OmegaDoom** [comment]
I don't know if it should be 1.1 or 1.2. I'm just saying that zlib has minizip 1.1. That's why assimp-git is not compiling. Do you know any reason to use minizip 1.2 instead of 1.1?

**Comment by oscarfv** [comment]
> I don't know if it should be 1.1 or 1.2. I'm just saying that zlib has minizip 1.1. That's why assimp-git is not compiling. Do you know any reason to use minizip 1.2 instead of 1.1?

minizip is packaged with the zlib source distribution just as an optional convenience for the user. `zlib/Contrib/README.contrib` says:

```
All files under this contrib directory are UNSUPPORTED. There were
provided by users of zlib and were not tested by the authors of zlib.
Use at your own risk. Please contact the authors of the contributions
for help about these, not the zlib authors. Thanks.
```

MSYS2 is trying to provide a minizip version that is both up-to-date and compatible with zlib. Should we downgrade minizip just because a project is assuming too much about its environment?

On addition, it would be useful to know why zlib's PKBUILD switched from building contrib/minizip to fetch it externally. Maybe it was for fixing some problem elsewhere. Sadly, this type of information is scarce in our commit logs.

**Comment by OmegaDoom** [comment]
Exactly, it's interesting to know why this changed. These libraries are old and i'm surprised of such change.
It's not a problem to switch to a new version but why?

**Comment by spillerrec** [comment]
minizip 1.2 provided is a fork by another developer which has changed the API and is not compatible with the minizip. They claim 1.2 is a drop-in replacement, but they changed one of the structs used for the writing API so it is not source compatible if you need to write zip files.

So gosh damnit, now we have three incompatible versions. The 1.1 version bundled with zlib, the 1.2 version from a random fork, and the completely different 2.0 version born from the 1.2 fork. Arch Linux is using the 1.1 version for the minizip 1.2.11 package, so I'm starting to think the only sane approach is to stop using minizip.

**Comment by Neustradamus** [comment]
There are different packages:
- minizip and zlib
- minizip-ng and zlib-ng

Thanks to @neheb for this PR about the rename.

Linked to:
- https://github.com/zlib-ng/minizip-ng/issues/358
- https://github.com/msys2/MINGW-packages/pull/10371

**Comment by Neustradamus** [comment]
@jeremyd2019: It is possible to rename https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-minizip-git to https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-minizip and use the official zlib release?
- https://zlib.net/
- https://github.com/madler/zlib
- https://github.com/madler/zlib/tree/develop

**Comment by Neustradamus** [comment]
@MehdiChinoune has done a part of the change here about the renaming of minizip2 to minizip-ng:
- https://github.com/msys2/MINGW-packages/pull/14031

But it is not perfect yet, now it is needed to see for official minizip from zlib (specified in the previous comment) and zlib-ng too.

The goal is to have:
- zlib (ok): https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-zlib
- zlib-ng: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-zlib-ng
- minizip: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-minizip (not here: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-minizip-git)
- minizip-ng (ok): https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-minizip-ng

cc: @gvollant, @madler, @zlib-ng, @nmoinvaz.

**Comment by MehdiChinoune** [comment]
minizip is available as a split package from zlib base package.

**Comment by MehdiChinoune** [comment]
Please, open separate issue about zlib-ng, this issue is solved.

**Comment by MehdiChinoune** [comment]
OMG, there is a split package ${MINGW_PACKAGE_PREFIX}-minizip from the base package zlib.
It doesn't show when you search in "base packages", change it to "packages" https://packages.msys2.org/search?t=binpkg&q=minizip
