### ISSUE TITLE
Gimp plugins can't find libjasper-1.dll  

### ISSUE THREAD

**Issue by GallifreyZhang** [msys2/MINGW-packages#5275]
pacman -S mingw-w64-x86_64-gimp mingw-w64-x86_64-gimp-ufraw

when start gimp, it shows can't find libjasper-1.dll 

cmd shows: D:\msys64\mingw64\bin\gimp.exe: LibGimpBase-▒▒▒▒: gimp.exe: gimp_wire_read(): error

**Comment by lazka** [comment]
Does it work now?
