### ISSUE TITLE
Source for giflib out of date

### ISSUE THREAD

**Issue by phillord** [msys2/MINGW-packages#5277]
The source for the giflib package seems to be out-of-date -- the source package is:

mingw-w64-giflib-5.1.6-1.src.tar.gz

while the binary distributed is at:

mingw-w64-x86_64-giflib-5.1.8-1-any.pkg.tar.xz

**Comment by lazka** [comment]
Confirmed

**Comment by MehdiChinoune** [comment]
no longer an issue
