### ISSUE TITLE
error: target not found: mingw-w64-x86_64-webkitgtk3

### ISSUE THREAD

**Issue by rbvictor** [msys2/MINGW-packages#5299]
I suppose this package entry was not included in the latest mingw64.db file from the repo http://repo.msys2.org/mingw/x86_64/

**Comment by lazka** [comment]
webkitgtk3 no longer works and has been dropped.

**Comment by maximveksler** [comment]
> webkitgtk3 no longer works and has been dropped.

What would be the replacement? 

Trying to get Leksah to run proves diffculet as it requries webkit3 https://github.com/leksah/leksah/blob/master/leksah.bat#L4

**Comment by lazka** [comment]
There is none that I know of.
