### ISSUE TITLE
inkscape broken, wrong poppler library

### ISSUE THREAD

**Issue by MaartenBent** [msys2/MINGW-packages#5300]
`inkscape.exe: error while loading shared libraries: libpoppler-85.dll: cannot open shared object file: No such file or directory`

The dll is now named `libpoppler-86.dll`, I suppose due to a newer poppler version. Please rebuild the package.
Thanks.

**Comment by aaronps** [comment]
Still broken, but now poppler is `libpoppler-87.dll`

**Comment by MaartenBent** [comment]
https://github.com/msys2/MINGW-packages/commit/001a63f1efa45ae331bedac7036d83a423cd213e
fixed, thanks.
