### ISSUE TITLE
Firebird 2 is missing libicuuc61.dll and libicudt61.dll from the package

### ISSUE THREAD

**Issue by tomay3000** [msys2/MINGW-packages#5308]
Files: **libicuuc61.dll** and **libicudt61.dll** are missing from Firebird 2 pre-compiled libraries package.

**Comment by Alexpux** [comment]
Firebird2 rebuilded with current ICU

**Comment by tomay3000** [comment]
OK, I will try it out.

**Comment by tomay3000** [comment]
I have tried it, but fbclient.dll still crashing when Firebird server is stopped.

**Comment by Alexpux** [comment]
@tomay3000 this is another issue. Feel free to dig why it crashing. Firebird dont officially supoport mingw, so maybe need more work to get it working

**Comment by tomay3000** [comment]
@Alexpux Indeed, it is another issue. I have to compare the patched and the original sources using like "**Beyond Compare**" tool and see what I can do.
