### ISSUE TITLE
Static library does not link properly

### ISSUE THREAD

**Issue by Youda008** [msys2/MINGW-packages#5315]
I was trying to build static version of Qt-5.12.3 from official sources and i got this error:

```
g++ -Wl,-s -Wl,-subsystem,console -static -Wl,--gc-sections -o ../../bin/dumpdoc.exe
.obj/release/main.o .obj/release/dumpdoc_plugin_import.o
-LE:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/plugins/styles
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/plugins/styles/libqwindowsvistastyle.a
-LE:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/lib
-LE:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/plugins/platforms
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/plugins/platforms/libqwindows.a -lwinspool -lopengl32 -lshlwapi -lwtsapi32
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/lib/libQt5EventDispatcherSupport.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/lib/libQt5FontDatabaseSupport.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/lib/libqtfreetype.a
C:/msys64/mingw64/x86_64-w64-mingw32/lib/libdwrite.a
C:/msys64/mingw64/x86_64-w64-mingw32/lib/libd2d1.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/lib/libQt5ThemeSupport.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/lib/libQt5AccessibilitySupport.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/lib/libQt5WindowsUIAutomationSupport.a
-LE:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtimageformats/plugins/imageformats
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtimageformats/plugins/imageformats/libqicns.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtimageformats/plugins/imageformats/libqjp2.a -ljasper
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtimageformats/plugins/imageformats/libqtga.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtimageformats/plugins/imageformats/libqtiff.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtimageformats/plugins/imageformats/libqwbmp.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtimageformats/plugins/imageformats/libqwebp.a
-LE:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/plugins/imageformats
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/plugins/imageformats/libqgif.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/plugins/imageformats/libqico.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/plugins/imageformats/libqjpeg.a
C:/msys64/mingw64/lib/libjpeg.dll.a
-LE:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtactiveqt/lib
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtactiveqt/lib/libQt5AxContainer.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtactiveqt/lib/libQt5AxBase.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/lib/libQt5Widgets.a -luxtheme -ldwmapi
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/lib/libQt5Gui.a
C:/msys64/mingw64/lib/libpng16.dll.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/lib/libqtharfbuzz.a -lgdi32 -lcomdlg32 -loleaut32 -limm32
C:/msys64/mingw64/x86_64-w64-mingw32/lib/libglu32.a
C:/msys64/mingw64/x86_64-w64-mingw32/lib/libopengl32.a
C:/msys64/mingw64/x86_64-w64-mingw32/lib/libgdi32.a
C:/msys64/mingw64/x86_64-w64-mingw32/lib/libuser32.a
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtbase/lib/libQt5Core.a -lmpr -lnetapi32 -luserenv -lversion -lws2_32 -lkernel32 -luser32 -lshell32 -luuid -lole32 -ladvapi32 -lwinmm
C:/msys64/mingw64/lib/libz.dll.a
C:/msys64/mingw64/lib/libpcre2-16.dll.a .obj/release/dumpdoc_resource_res.o
C:/msys64/mingw64/x86_64-w64-mingw32/lib/libglu32.a
C:/msys64/mingw64/x86_64-w64-mingw32/lib/libopengl32.a
C:/msys64/mingw64/x86_64-w64-mingw32/lib/libgdi32.a
C:/msys64/mingw64/x86_64-w64-mingw32/lib/libuser32.a
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe:
E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtimageformats/plugins/imageformats/libqjp2.a(qjp2handler.o):qjp2handler.cpp
(.text$_ZN20Jpeg2000JasperReaderC2EP9QIODevice9SubFormat+0x2f): undefined reference to '__imp_jas_init'
... lots of simmilar undefined reference errors ...
```

These are functions from libjasper. I checked my msys64 directory and jasper is correctly installed. There is
`C:\msys64\mingw64\include\jasper`
`C:\msys64\mingw64\lib\libjasper.a`
`C:\msys64\mingw64\lib\libjasper.dll.a`
`C:\msys64\mingw64\bin\libjasper-4.dll`
I even checked them with nm and DependancyWalker and the functions from undefined errors are all present.

The `__imp_` prefix in the missing function name would indicate that it tried to link `libjasper.dll.a`, but it was supposed to link `libjasper.a`. If you look closer at the command, there is `-static` and later `E:/Youda/Projects/Qt/Qt-5.12.3-release-static/qtimageformats/plugins/imageformats/libqjp2.a -ljasper`, which is correct, `libqjp2.a` contains object file that uses jasper and the command clearly says to link static library, but it linked the import lib for the dynamic one. This seems to me like a bug of MSYS/MinGW.

Steps to replicate:

1. download sources of 5.12.3 https://www.qt.io/offline-installers
2. configure with these parameters `-opensource -release -static -static-runtime -no-pch -optimize-size -prefix "E:\Youda\Libraries\Qt" -opengl desktop -nomake tools -nomake tests -nomake examples -skip androidextras -skip connectivity -skip gamepad -skip sensors -skip serialbus -skip serialport -skip speech -skip webengine`
3. mingw32-make

**Comment by oscarfv** [comment]
The problem is that `-ljasper` comes after `libqjp2.a` on the command line. The linker resolves symbols referenced on object/library N searching for them on N-1, N-2... not on the objects/libraries that are listed on position N+1 etc.

**Comment by Youda008** [comment]
Hm, not true.

```
youda@Youda-Latitude:~/experiments$ g++ -o test -lpthread test_pthread.cpp
/tmp/ccH0URFt.o: In function `std::thread::thread<void (&)()>(void (&)())':
test_pthread.cpp:(.text._ZNSt6threadC2IRFvvEJEEEOT_DpOT0_[_ZNSt6threadC5IRFvvEJEEEOT_DpOT0_]+0x2f): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
youda@Youda-Latitude:~/experiments$ g++ -o test test_pthread.cpp -lpthread
youda@Youda-Latitude:~/experiments$
```

**Comment by oscarfv** [comment]
Oh well, I mixed the order on my explanation: the linker searches for symbols on libraries that comes further on the command line. The problem is so common that I reacted without paying proper attention.

Back to the issue:

The fact that the missing symbols have the `__imp_` prefix does not mean that `-static` is not working. It can mean that the header files that declared those functions marked them as imports (with `__declspec(dllimport)`). Some libraries require that you define some symbol on the compile command depending on your intention of linking statically or dynamically. I took a quick look at jasper's and it seems that the flag is `JAS_DLL` and it defaults to 1, so try building with `-DJAS_DLL=0` and see if the problem goes away.

**Comment by Youda008** [comment]
LMAO. So after reconfiguring with QMAKE_CXXFLAGS+=DJAS_DLL=0 and rebuilding everything, i got this instead:
```
internal compiler error: in tsubst_default_argument, at cp/pt.c:12714
             return Feature { std::move(geom) };
                                              ^
libbacktrace could not find executable to open
```
I guess i must be the unluckiest person in the world. Everytime i try to build something on my own, i get the most rare errors no one else gets and i discover the deepest bugs in compiler itself.

**Comment by Youda008** [comment]
However, the original problem with jasper library disappeared, so consider this resolved.

**Comment by lucaszanella** [comment]
Hi @Youda008, how did you get libz.dll.a?

I'm getting

```
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lC:/msys64/mingw64/lib/libz.dll.a
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lC:/msys64/mingw64/lib/libssl.dll.a
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lC:/msys64/mingw64/lib/libcrypto.dll.a
/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lC:/msys64/mingw64/lib/libzstd.dll.a
```

and I don't know how to solve, and I already installed `zlib` and `zlib-dev`

**Comment by oscarfv** [comment]
@lucaszanella : you are using MSYS2 linker, and searching for libraries on the mingw-w64 directories. This is wrong. Most likely, you want to use mingw-64 compiler and linker.

When you execute `pacman -S gcc` you are installing an MSYS2 package, which depends on the POSIX emulation layer. If you execute `pacman -S mingw-w64-x86_64-gcc` you install a package that depends on the mingw-w64 runtime, which does not depend on the POSIX emulation layer, it is "native". Make sure that you start the "MinGW-w64 64 bits" shell for using the native package.

**Comment by taynpg** [comment]
> 

I have the same problem. How do you solve it.
 internal compiler error: in tsubst_default_argument, at cp/pt.c:12692

**Comment by taynpg** [comment]
@Youda008 
I have the same problem. How do you solve it.
internal compiler error: in tsubst_default_argument, at cp/pt.c:12692
