### ISSUE TITLE
librsvg broken

### ISSUE THREAD

**Issue by RishYang** [msys2/MINGW-packages#5317]
When I tried to compile Octave in MSYS2, an error about invalid png file occured.
The invalid png file generated by rsvg-convert is not able to be opened by GIMP 2.
I reinstalled librsvg and then manaully converted svg files to png files.
The png files I manually converted is still invalid.
Does the promble come from rsvg-convert(librsvg)?
`rsvg-convert -w 512 -f png octave-logo.svg > tmp.png`
rsvg-convert version 2.40.20
[Ocatve-logo.svg](https://drive.google.com/file/d/1vsFJpOxJZDHpPNmFLSeG9TBwn2JVm6RD/view?usp=sharing)
[All pakages in my MSYS2 environment](https://drive.google.com/file/d/1sSyigmZ-Oc3f4WcAyqG5LkPc9mC7GZMu/view?usp=sharing)

**Comment by lazka** [comment]
Use `rsvg-convert -w 512 -f png octave-logo.svg -o tmp.png` instead.

**Comment by RishYang** [comment]
> 
> 
> Use `rsvg-convert -w 512 -f png octave-logo.svg -o tmp.png` instead. Maybe you can report this to Octave so this can be fixed there.
Thanks @lazka 
It works.
BTW, I gave up compiling native Ocatve in MSYS2. It seems impossible for me.
