### ISSUE TITLE
for god sake, to the maintainter of firebird 2, please explain the process of building it, because the compilation never competes without errors.

### ISSUE THREAD

**Issue by tomay3000** [msys2/MINGW-packages#5318]
I thought, issuing just this works for Firebird PKGBUILD, and would build it:

`git clone https://github.com/msys2/MINGW-packages.git`
`cd mingw-w64-firebird2-git`
`MINGW_INSTALLS=mingw32 makepkg-mingw -sLf`

but, actually it is not.
All the necessary tools are installed though.

Please explain how you did it.

Thank you for your understanding.

**Comment by oscarfv** [comment]
Given that it is a -git package, what you attempted to build is not necessarily the same as what the maintainer built a week ago.

A better start is to describe how the build fails for you.

Please be careful with the language you use here, specially on the subject of issues. It is not about conveying your emotions, but providing technical information that helps to solve the problem.

**Comment by lazka** [comment]
You can also pass `--holdver` to makepkg so it builds the upstream revision that the maintainer used last. Or not build it at all and use the version in the repo: `pacman -S mingw-w64-x86_64-firebird2-git`

If you hit any more problems please open a new issue and explain what you are trying to do and how it fails exactly.

**Comment by tomay3000** [comment]
@lazka Thank you.
