### ISSUE TITLE
libc++ does not contain (required) __libcpp_vasprintf

### ISSUE THREAD

**Issue by saurik** [msys2/MINGW-packages#5320]
If you try to compile using using the libc++ from msys2's mingw package set, at least if you try to statically compile it (which I am), you get this error:

```
lld-link: error: undefined symbol: _Z18__libcpp_vasprintfPPcPKcS_
>>> referenced by libc++.a(locale_win32.cpp.obj):(_Z11vasprintf_lPPc8locale_tPKcS_)
```

The issue is caused by an obsolete patch to clang named "0401-mingw-w64-hack-and-slash-fixes-for-libc.patch" that needs to be deleted. The reason this patch used to be needed was because of a conflict on the vasprintf symbol (you can see the name of the symbol in question in the @ line, despite the comments that pad around it).

However, early last year, libc++ upstream fixed that problem by renaming vasprintf to __libcpp_vasprintf; and because of the leading context of comments, this change did not cause a patch conflict with msys2, and so went unnoticed. I do not see any reason why the patch that is in msys2 would still be needed (and it is actively harmful).

https://reviews.llvm.org/D42405?id=130998

**Comment by lazka** [comment]
The patch in question was added in #1833 -> @mati865

**Comment by mati865** [comment]
Yeah, it was upstreamed in different form nad and should be deleted.

**Comment by lazka** [comment]
@saurik feel free to open a PR (remove the patch + bump pkgrel)

**Comment by saurik** [comment]
> feel free to open a PR (remove the patch + bump pkgrel)

@lazka I have done this as part of the patchset in #5500.
