### ISSUE TITLE
clang -flto-visibility-public-std override is obsolete as of clang 6

### ISSUE THREAD

**Issue by saurik** [msys2/MINGW-packages#5321]
The patch to clang named "0106-MinGW-use-flto-visibility-public-std-CC1-arg-to-get-.patch" was to work around an issue that was (supposedly) fixed in upstream clang as of clang 6, and so should probably be removed from msys2.

Per this conversation:

https://www.bountysource.com/issues/47984908-cannot-compile-with-static-when-using-exceptions

Written by mati865:

> It is clang bug with possible fix here https://github.com/mati865/MINGW-packages/blob/954fa97c5349029b75b63c58ae81c62a39fa9658/mingw-w64-clang/0106-MinGW-use-flto-visibility-public-std-CC1-arg-to-get-.patch

> If there will be no regressions I'll try to push it for next feature LLVM/clang release.

Later, also mati865:

> Fixed in clang trunk and 6.0 (coming next year) https://github.com/llvm-mirror/clang/commit/be95e325b8e301e87b32edba022796726dfe90f7

The patch in msys2 turns this flag on by force, as without it bad behavior resulted; instead, the fix in clang makes it so in the situations where the flag is being turned on, the bad behavior that happens when the flag was off does not happen.

**Comment by lazka** [comment]
@mati865

**Comment by mati865** [comment]
Martell's patch: https://reviews.llvm.org/D33620 is even better than my patch (we have discussed it), therefore it's obsolete now.

**Comment by saurik** [comment]
I have included removal of this patch in my patchset #5500.
