### ISSUE TITLE
[qt5] zero patch goal - please keep open

### ISSUE THREAD

**Issue by mcallegari** [msys2/MINGW-packages#5322]
The number of patches on the Qt5 package is becoming ridiculous.
It is difficult to maintain them and each Qt5 version requires more and more patches.

I am opening this in the hope to gather some interest and collaborative work to have MSYS2 supported by Qt upstream, therefore requiring **zero patches** to work.
This is a huge task, I know, but if we join efforts, there is some hope we can make it.
There will be also a lot of resistance by the Qt guys, I warn you. They have their own MinGW environment and don't give a damn about MSYS2. It's "just" a matter to convince them that Qt cannot be built on any environment.

I already started myself and did my part. I will continue this crusade in my spare time.
Here's a table to track which patches can be removed and since which Qt version.

Patch | QTBUG | Gerrit | Qt version
------------ | ------------- | ------------- | -------------
[0003-qt-5.8.0-autodetect-fontconfig.patch](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-qt5/0003-qt-5.8.0-autodetect-fontconfig.patch) | [QTBUG-57436](https://bugreports.qt.io/browse/QTBUG-57436) | [link](https://codereview.qt-project.org/#/c/247670/) | 5.12.4

**Comment by athmsSYN** [comment]
There are Qt contributors that would be interested.

**Comment by mcallegari** [comment]
Hi, it seems patch [0016-qt-5.8.0-win32-g++-use-qpa-genericunixfontdatabase](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-qt5/0016-qt-5.8.0-win32-g%2B%2B-use-qpa-genericunixfontdatabase.patch) might be no longer needed after [this patch](https://codereview.qt-project.org/c/qt/qtbase/+/280820)
Can someone please check?
@Alexpux have you already attempted to build the 5.14 branch? I think it's going to be painful...again... :(

**Comment by MehdiChinoune** [comment]
Qt5 is no longer open for development.
