### ISSUE TITLE
mingw-w64-x86_64-editorconfig-core-c: Missing shared library libpcre2-8-0.dll 

### ISSUE THREAD

**Issue by rookiejet** [msys2/MINGW-packages#5327]
![2019-05-08 16_37_20-editorconfig exe - System Error](https://user-images.githubusercontent.com/6133327/57406987-1c084e80-71b0-11e9-84da-a2b25a16e0ef.png)

editorconfig.exe is missing libpcre2-8-0.dll dependency when installed. PKGBUILD depends on pcre but not pcre2.

**Comment by lazka** [comment]
Thanks, fixed in f2acc1ecc032fa1f9
