### ISSUE TITLE
Binutils 2.30 can't compile AVX code with GCC 8.3

### ISSUE THREAD

**Issue by rubenvb** [msys2/MINGW-packages#5328]
Binutils 2.30 cannot process all files generated by GCC 8.3.

See for example: https://ci.appveyor.com/project/RubenVanBoxem/skui/build/job/jlkmhpoa15kwvkbq#L1208

These errors are solved by using binutils 2.32:

C:\Users\appveyor\AppData\Local\Temp\1\cckdHx00.s: Assembler messages:
C:\Users\appveyor\AppData\Local\Temp\1\cckdHx00.s:49915: Error: invalid register for .seh_savexmm
C:\Users\appveyor\AppData\Local\Temp\1\cckdHx00.s:52067: Error: invalid register for .seh_savexmm
C:\Users\appveyor\AppData\Local\Temp\1\cckdHx00.s:52069: Error: invalid register for .seh_savexmm

**Comment by StarWolf3000** [comment]
Probably the compiler switch `-fno-asynchronous-unwind-tables` is needed:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65782

**Comment by mati865** [comment]
As per https://github.com/msys2/MINGW-packages/issues/4317#issuecomment-476523826 2.31 and 2.32 are broken in different way.

**Comment by rubenvb** [comment]
The compiler switch is a workaround, not a solution, so it can't be "needed" (and it's not with Binutils 2.32).

As for the Clang build issue: if the ld bug is not fixed on binutils master, it should be reopened.
Is there a way to get e.g. binutils-git as a built package in MSYS2? That would avoid my issue without adding hacks to my code.

**Comment by mati865** [comment]
Binutils 2.32 with the fix for #4317 have been uploaded.

**Comment by lazka** [comment]
Is this fixed now?
