### ISSUE TITLE
Building clang package generates corrupt package files

### ISSUE THREAD

**Issue by oscarfv** [msys2/MINGW-packages#5334]
After building clang the resulting package files are corrupt, as reported by `bsdtar -xjf <package>`

Indeed, many files are missing after installing the package. For instance `/mingw64/bin/clang.exe`.

**Comment by Alexpux** [comment]
@oscarfv I see tha same issues when packaging Qt5 as it generate very big archives, but this issue is happen time to time. Dont know where to see

**Comment by oscarfv** [comment]
Thanks for confirming the issue. It is quite disturbing. Is there some method for changing the archiver `makepkg-mingw` uses? Then I could experiment with different varieties and versions of bsdtar/tar. I looked into `/etc/makepkg-mingw??.conf` but found nothing.

**Comment by Alexpux** [comment]
@oscarfv yo need change directly in makepkg script. Lines 102, 725, 775, 783, 874

**Comment by MehdiChinoune** [comment]
likely no longer an issue
