### ISSUE TITLE
yarn package does not add global bin directory to PATH

### ISSUE THREAD

**Issue by sarangjo** [msys2/MINGW-packages#5343]
When installing yarn (`mingw-w64-yarn`), is there any way to add yarn's global bin directory to the PATH?

**Comment by peterbud** [comment]
Why would it be necessary could you elaborate? I don't see the arch package changing the PATH either:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/yarn

**Comment by sarangjo** [comment]
Oh, that's a good point. Interesting, this might be more of a recommendation there, then.

Basically, any js packages that are added globally that provide executables are symlinked in the yarn global binary directory. These binaries are intended to be callable from anywhere on the system.

However, I think you're right that this shouldn't be handled by the installation of the package. As the [documentation indicates](https://yarnpkg.com/en/docs/cli/global#adding-the-install-location-to-your-path), this seems to be a required manual step for users wanting to use global packages. Will close the issue, apologies for unnecessary churn.
