### ISSUE TITLE
[gdb] Lastest version (8.3-1) is still showing as 8.2.1-1 and crash on startup

### ISSUE THREAD

**Issue by mveronneau-primero** [msys2/MINGW-packages#5357]
I was having problem starting gdb in all msys2 shells, so I deleted msys2 from my system and did a fresh install.

After that, I was having the following problems.

MSYS2 shell
```
$ gdb
osabi.c:661: internal-error: _initialize_gdb_osabi: gdb_osabi_names[] is inconsistent
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) Segmentation fault (core dumped)
```

MINGW32 shell : 
```
$ gdb
C:/msys64/mingw32/bin/gdb.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

MINGW64 shell : 
```
$ gdb
C:/msys64/mingw64/bin/gdb.exe: error while loading shared libraries: libsource-highlight-4.dll: cannot open shared object file: No such file or directory
```

Calling `pacman -Q --info gdb` reports the following in a MINGW64 shell : 
```
Name                     : gdb
Version                  : 8.2.1-1
Description              : GNU Debugger (MSYS2 version)
Architecture             : x86_64
```

[This URL](https://msys2.duckdns.org/package/mingw-w64-x86_64-gdb?repo=mingw64) reports that the latest version should be 8.3-1.

If I open gdb.exe with an hexadecimal editor, I can see a lot of reference to "gdb-8.3" (mostly in assertion strings).

To be sure, one of my colleague, which didn't update for a few days and is still able to debug, did this : 
```
$ sha256sum `which gdb`
099588743af8a4847c2d4c51b85bb67a139194db74eec654aa94e9720b4e1a84 */mingw64/bin/gdb
```

On my computer, it yield this result : 
```
$ sha256sum `which gdb`
91c8f9f131a3a2c5cea7ecb9f442bb2d97367bb7213d629ca5abdce1f2169d68 */mingw64/bin/gdb
```
This SHA matches the SHA of gdb 8.3-1.

I cannot reinstall 8.2.1-1, as the meta-data for the package are wrong, but gdb 8.3-1 doesn't start.

What should I do?

**Comment by bit2shift** [comment]
The mingw64 version is also broken, even after installing `mingw-w64-x86_64-source-highlight`.
See if you can rollback to the previous version by installing the appropriate package from `/var/cache/pacman/pkg`, namely `/var/cache/pacman/pkg/mingw-w64-x86_64-gdb-8.2-1-any.pkg.tar.xz`.

**Comment by lazka** [comment]
@Adsun701

**Comment by Alexpux** [comment]
@lazka  @mveronneau-primero  I will rebuild source-highlight with new boost and fix GDB deps

**Comment by mveronneau-primero** [comment]
Thanks! Good idea! I'll do that next time.

In the mean time, the 8.3 package was updated, and it's working now.

Please note that the package infos are still 8.2.1-1 :  
```
$ gdb --version
GNU gdb (GDB) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


$ pacman -Q --info gdb
Name                     : gdb
Version                  : 8.2.1-1
Description              : GNU Debugger (MSYS2 version)
Architecture             : x86_64
```

**Comment by lazka** [comment]
@mveronneau-primero the mingw package is called `mingw-w64-x86_64-gdb`, so `pacman -Q --info mingw-w64-x86_64-gdb`

**Comment by mveronneau-primero** [comment]
Indeed : 
```
$ pacman -Q --info mingw-w64-x86_64-gdb
Name                     : mingw-w64-x86_64-gdb
Version                  : 8.3-2
```

I'm not that knowledgable about the inner workings of pacman. When I installed GDB, I did it with this command :
```
pacman -S gdb
```

I was under the impression that I could just query back "gdb". Can you explain to me why it's not the same (or point me to an online resource about that)?

**Comment by lazka** [comment]
You can also use the web interface to browse: https://msys2.duckdns.org/search?t=pkg&q=gdb

**Comment by cclark2a** [comment]
I've worked around this with
```
pacman -S mingw-w64-x86_64-gdb 
```
and that works fine; gdb works. But running it directly from the mingw64 shell prompt appears to think it is invoked by a shell script. The up arrow key moves the cursor up the terminal window rather than activating gdb history, and interactive questions like "Make breakpoint pending on future shared library load?" annotate "[answered N; input not from terminal]". Is there a way around this?

**Comment by oscarfv** [comment]
@cclark2a : don't use mintty for non-MSYS2 gdb (nor for non-MSYS2 console interactive applications in general) or

```
$ pacman -S winpty
$ winpty gdb ...args...
```

See #5353.

**Comment by cclark2a** [comment]
@oscarfv : thank you for that. Unfortunately, while it fixes the interactive problem, it appears to mess up breakpoints. When I use `winpty gdb ...` , set a breakpoint, and the breakpoint is hit, gdb exits. When I use `gdb ...` and set the same breakpoint, gdb works normally.

**Comment by oscarfv** [comment]
There is a `gdb` package for MSYS2 (`pacman -S gdb`, then invoke it as `/usr/bin/gdb ... `) but I'll rather use a different console. Try [conemu](https://conemu.github.io/) for instance.

**Comment by cclark2a** [comment]
@oscarfv : Because `/usr/bin/gdb` is an older version, it currently crashes on startup as described above. Note the version numbers here:
```
$ pacman -Qs gdb
local/gdb 8.2.1-1 (base-devel)
    GNU Debugger (MSYS2 version)
...
local/mingw-w64-x86_64-gdb 8.3-2 (mingw-w64-x86_64-toolchain)
    GNU Debugger (mingw-w64)
```
Maybe this is not the right place to report this bug, but it would be great if pacman pulled the 8.3-2 version of the MSYS2 gdb. Sorry for the confusion.

**Comment by Alexpux** [comment]
@cclark2a feel free to try build GDB for MSYS yourself first and see if it working

**Comment by cclark2a** [comment]
> @cclark2a feel free to try build GDB for MSYS yourself first and see if it working

@Alexpux : I did try to build GDB for MSYS (64 bit).  I ran into problems compiling files in the bfd directory, associated with incompatibilities around printf, scanf, and 64 bit values. 

If there are instructions for how to build GDB for MSYS, I will gladly try it.

**Comment by MehdiChinoune** [comment]
likely no longer an issue
