### ISSUE TITLE
Need libjpeg-turbo-dev

### ISSUE THREAD

**Issue by luckrill** [msys2/MINGW-packages#5359]
I install python Pillow with "pip install Pillow"
search msys2 package:
 pacman -Ss jpeg

found libjpeg-turbo, but I also need dev version.
not found libjpeg-trubo-devel 
how to install libjpeg-trubo-devel

**Comment by lazka** [comment]
The libjpeg-turbo package also includes the headers (the same is true for all other packages)

**Comment by luckrill** [comment]
I install mingw-w64-x86_64-libjpeg-turbo
path is /ming64/lib /ming64/include 
But pip install Pillow cann't found /ming64 path.
I copy all mingw-w64-x86_64-libjpeg-turbo files to /usr/lib and /usr/include, 
Then install Pillow succeed.

**Comment by oscarfv** [comment]
`/usr` is the wrong place for non-MSYS2 files. Copying Mingw-w64 files to that directory is a sure way of creating problems in the future.

Either your `pip` command is searching for files in the wrong place or you are not executing it from a MINGW64 shell. You must use a MINGW64 shell for executing or building 64bit Mingw-w64 binaries. The setup code of that shell sets some required environment variables (critically, PATH).

**Comment by lazka** [comment]
There also is a prebuilt https://msys2.duckdns.org/base/mingw-w64-python-pillow you can install

**Comment by Oifan** [comment]
I have tried today to do these 2 steps -- 1st was OK, but the 2nd has one failed (during installation of image module):
`pacman -S --needed mingw-w64-x86_64-python2-pillow mingw-w64-x86_64-python3-pillow`
`pip2 install image`
The error message was:
`Installing collected packages: pytz, asgiref, sqlparse, django, pillow, image`
`    Running setup.py install for pillow ... error`
`    ...`
`    The headers or library files could not be found for zlib,`
`    a required dependency when compiling Pillow from source.`

**Comment by Biswa96** [comment]
Please create a new issue with steps to reproduce it.
