### ISSUE TITLE
OpenCV - DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by gpraceman** [msys2/MINGW-packages#5361]
I'm having problems with OpenCV 4.0.1 with MSYS2 on Windows 10 and Python 3.7.3 x86. I can get OpenCV to install, but when I do a simple "import cv2", it throws an exception.  Here's the exception with debug turned on.

```
>>> import cv2
OpenCV loader: os.name="nt"  platform.system()="Windows"
OpenCV loader: loading config: C:/msys64/mingw32/lib/cv2/config.py
OpenCV loader: loading config: C:/msys64/mingw32/lib/cv2/config-3.7.py
OpenCV loader: PYTHON_EXTENSIONS_PATHS=['C:/msys64/mingw32/lib/cv2/python-3.7']
OpenCV loader: BINARIES_PATHS=['C:/msys64/mingw32/lib/cv2/../../bin']
OpenCV loader: PATH=C:/msys64/mingw32/lib/cv2/../../bin;C:\msys64\mingw32\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\usr\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\msys64\usr\bin\site_perl;C:\msys64\usr\bin\vendor_perl;C:\msys64\usr\bin\core_perl;C:\msys64\mingw32\bin\
OpenCV loader: replacing cv2 module
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw32/lib\cv2\__init__.py", line 90, in <module>
    bootstrap()
  File "C:/msys64/mingw32/lib\cv2\__init__.py", line 80, in bootstrap
    import cv2
ImportError: DLL load failed: The specified module could not be found.
```
Here's how I installed OpenCV:

`pacman -S mingw-w64-i686-opencv`

I did add C:\msys64\mingw32\lib to my PYTHONPATH, which is the location of the cv2 folder.

I also tried setting up a Python 3.7.3 x64 environment, but got the same error.

**Comment by Alexpux** [comment]
@gpraceman I think it fixed in 4.1.0 package version

**Comment by gpraceman** [comment]
Tried it, but unfortunately, the python files are now missing.  The only thing in the cv2 folder is the __pychache__ folder.

**Comment by Alexpux** [comment]
@gpraceman python module installed directly to site-packages directory

**Comment by gpraceman** [comment]
I see a DLL in site-packages, but doing a "import cv2" yields an error:

ImportError: DLL load failed: The specified module could not be found.

**Comment by Alexpux** [comment]
Try from CMD, not MSYS2

**Comment by gpraceman** [comment]
I appreciate your patience and sorry if I am being dense, but no joy with CMD.

```
C:\Users\gpraceman>python3
Python 3.7.3 (default, Apr 23 2019, 08:31:01)  [GCC 7.4.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
>>>
```
Here's how I have my paths setup.
PATH: C:\msys64\mingw32\bin
PYTHON_PATH: C:\msys64\mingw32\lib; C:\msys64\mingw32\lib\python3.7\site-packages

**Comment by Alexpux** [comment]
@gpraceman I dont see issue on my computer:
````
c:\building\msys64\mingw64\bin>python2
Python 2.7.16 (default, Apr 23 2019, 07:57:28)  [GCC 8.3.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> exit()

c:\building\msys64\mingw64\bin>python3
Python 3.7.3 (default, Apr 23 2019, 08:20:20)  [GCC 8.3.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> exit()
````

So probably some package is missing. Try to find it

**Comment by cbrt64** [comment]
Hey @gpraceman, Windows' generic "The specified module could not be found" is not very helpful, is it? Luckily I was able to pin this down using [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon). To `import cv2` in python, you'll need to have all of opencv's optional dependencies (except ffmpeg) installed, as well as ceres-solver, which will be added as a dependency.

Run `pacman -S --needed mingw-w64-i686-{ceres-solver,hdf5,python2-numpy,python3-numpy,ogre3d,tesseract-ocr}` (or mingw-w64-x86_64- as desired) and you should be all set.

**Comment by gpraceman** [comment]
@cbrt64 Thanks so much!  That got it working.  So much for "optional dependencies".
