### ISSUE TITLE
blender.exe: error while loading shared libraries: libHalf-2_2.dll

### ISSUE THREAD

**Issue by lixuzhang** [msys2/MINGW-packages#5366]
mingw-w64-x86_64-blender 2.79.b-6

Z:/msys64/mingw64/bin/blender.exe: error while loading shared libraries: libHalf-2_2.dll: cannot open shared object file: No such file or directory

**Comment by Alexpux** [comment]
@lixuzhang blender need lot of work, so feel free to do some work to get it working or wait while someone do it

**Comment by Alexpux** [comment]
@lixuzhang first thing to do is to fix building openshadinglanguage package

**Comment by revelator** [comment]
for openshadinglanguage change to look like this ->
'  # $PWD/src/liboslcomp PATH addition needed for running oslc.exe during the build (for liboslcomp.dll)
  # ${MINGW_PREFIX}/bin PATH addition needed for finding libboost_system-mt.dll when running oslc.exe.
  PATH=${MINGW_PREFIX}/bin:"${PATH}" make'

unfortunatly while it now finds the needed dll's make will bug out with a 127 error so sheesh :S

**Comment by Alexpux** [comment]
@revelator i think openshadinglanguage is good now. But now we need wait blender 2.82 as it will be moved to python 3.8. Our blender is builded with python 3.7

**Comment by revelator** [comment]
sadly while it gets farther, it will still crash with a 127 error when building some of the shaders.
tried all kinds of tricks even tried building it in a windows commandline shell instead of bash and it will still crash with error 127 so im a bit stumped.

**Comment by revelator** [comment]
Still not working tried all tricks in the book :S error 127 on all shaders, rebuilding dependencies does not fix it neither does putting dependencies on path. Kinda irritating that it spews a numerical error which basically means that the compiler cannot find something in path instead of telling me what :( makes it rather hard to get any hint on what goes wrong.

**Comment by MehdiChinoune** [comment]
should be fixed now
