### ISSUE TITLE
qemu-system-x86_64.exe: error while loading shared libraries: zlib1.dll

### ISSUE THREAD

**Issue by lixuzhang** [msys2/MINGW-packages#5367]
mingw-w64-x86_64-qemu 4.0.0-1

Z:/msys64/mingw64/bin/qemu-system-x86_64.exe: error while loading shared libraries: zlib1.dll: cannot open shared object file: No such file or directory

**Comment by Alexpux** [comment]
install mingw-w64-x86_64-zlib

**Comment by lixuzhang** [comment]
I have installed mingw-w64-x86_64-zlib 1.2.11-5.
==========
$ which qemu-system-x86_64.exe
/mingw64/bin/qemu-system-x86_64.exe

$ ls /mingw64/bin/qemu-system-x86_64.exe /mingw64/bin/zlib1.dll
/mingw64/bin/qemu-system-x86_64.exe*  /mingw64/bin/zlib1.dll*

$ qemu-system-x86_64.exe
Z:/msys64/mingw64/bin/qemu-system-x86_64.exe: error while loading shared libraries: zlib1.dll: cannot open shared object file: No such file or directory

$ LANG=C pacman -Sl | grep zlib
mingw32 mingw-w64-i686-zlib 1.2.11-5
mingw64 mingw-w64-x86_64-zlib 1.2.11-5 [installed]
msys mingw-w64-cross-zlib 1.2.11-1
msys zlib 1.2.11-1 [installed]
msys zlib-devel 1.2.11-1

**Comment by Alexpux** [comment]
@lixuzhang open qemu-system-x86_64 in dependency walker and see what really is missing

**Comment by lazka** [comment]
SDL2_image is missing

**Comment by lazka** [comment]
This was already fixed by #5356

@lixuzhang `pacman -S mingw-w64-x86_64-SDL2_image` should help
