### ISSUE TITLE
Qt Installer Framework is outdated

### ISSUE THREAD

**Issue by suratovvlad** [msys2/MINGW-packages#5369]
New version has been released https://blog.qt.io/blog/2019/05/17/qt-installer-framework-3-1-1-released/
Also, i would be great, if package mingw-w64-x86_64-qt-installer-framework-git would be able to build from sources, to not download binaries

**Comment by Alexpux** [comment]
@suratovvlad it is building from git sources not download binaries

**Comment by suratovvlad** [comment]
It offers me to install (about) 290 mb file, it doesn't try to rebuilt... Is there some saved data?
On arch Linux I use yaourt or yay along with pacman to install AUR packages, they rebuild every time

**Comment by oscarfv** [comment]
@suratovvlad : `pacman` installs binary packages. If you want to build them, you need to grab the corresponding `PKGBUILD` (plus patches, if they exist) and use `makepkg-mingw` to build your own binary package.

**Comment by Alexpux** [comment]
Fixed by https://github.com/msys2/MINGW-packages/commit/ff4d60cb8c23bde6b0db2e3dec6204627a80d5d4
