### ISSUE TITLE
can not resolve devhelp dependency package 'mingw-w64-x86_64-webkitgtk3'

### ISSUE THREAD

**Issue by tiensanchiang** [msys2/MINGW-packages#5372]
when i try to install devhelp in my msys2 , the console tell me some dependency can not be found.

warning: cannot resolve "mingw-w64-x86_64-webkitgtk3", a dependency of "mingw-w64-x86_64-devhelp"
:: The following package cannot be upgraded due to unresolvable dependencies:
      mingw-w64-x86_64-devhelp

**Comment by Alexpux** [comment]
@tiensanchiang webkitgtk not maintained anymore so devhelp will be removed from repository too

**Comment by lazka** [comment]
I'll look into removing the broken dependencies

**Comment by lazka** [comment]
See #5375

**Comment by lazka** [comment]
All gone now
