### ISSUE TITLE
CMake assertion failing for no obvious reason

### ISSUE THREAD

**Issue by TheDcoder** [msys2/MINGW-packages#5388]
Hi, I am trying to build my project but an assertion in CMake is failing preventing it from generating the build files :disappointed:

My project is pretty simple and does not have heavy dependencies, I installed the i686 MinGW version of `cmake` (`pacboy -S cmake:i`) to use it in the MINGW32 shell. When I invoke `cmake` I always get this assertion error:
```
$ cmake -G "Unix Makefiles" ..
-- The C compiler identification is GNU 7.4.0
-- Check for working C compiler: C:/msys64/mingw32/bin/cc.exe
-- Check for working C compiler: C:/msys64/mingw32/bin/cc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
Assertion failed: local_path.empty() || local_path.back() != '/', file E:/mingwbuild/mingw-w64-cmake/src/cmake-3.14.4/Source/cmSystemTools.cxx, line 1459
```

I am not sure if this is a bug in the build or if it is a bug within CMake itself.

For those who may want to try to reproduce this issue themselves, they can clone my [project](https://github.com/DcodingTheWeb/ProxAllium/tree/next-gen) and update [liballium](https://github.com/DcodingTheWeb/liballium/tree/master) to the latest version of the code since the old version included as a submodule doesn't support CMake ... to attempt to compile it (or atleast generate the build files) on your system.

I am attaching my [`CMakeLists.txt`](https://github.com/msys2/MINGW-packages/files/3198190/CMakeLists.txt) script which is not part of the upstream yet because I haven't commited it due to failing to build on Windows.

Thank you for the help in advance!

**Comment by oscarfv** [comment]
What happens if you use other generator than "Unix Makefiles"? I'm not sure if that generator is supposed to work in Windows/MSYS2 at all, since there is "MSYS Makefiles".

**Comment by TheDcoder** [comment]
The same error occurs, I have tried the "Ninja" and "Nmake" (default) generators as well. I will try the MSYS generator today to see if it makes any difference

**Comment by TheDcoder** [comment]
@oscarfv I have tried different generators:
```
John Doe@DESKTOP-CAT1JVP MINGW32 /x/build
$ cmake -G "MSYS Makefiles" ..
-- The C compiler identification is GNU 7.4.0
-- Check for working C compiler: C:/msys64/mingw32/bin/gcc.exe
-- Check for working C compiler: C:/msys64/mingw32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
Assertion failed: local_path.empty() || local_path.back() != '/', file E:/mingwbuild/mingw-w64-cmake/src/cmake-3.14.4/Source/cmSystemTools.cxx, line 1459

John Doe@DESKTOP-CAT1JVP MINGW32 /x/build
$ cmake -G "Ninja" ..
-- The C compiler identification is GNU 7.4.0
-- Check for working C compiler: C:/msys64/mingw32/bin/cc.exe
-- Check for working C compiler: C:/msys64/mingw32/bin/cc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
Assertion failed: local_path.empty() || local_path.back() != '/', file E:/mingwbuild/mingw-w64-cmake/src/cmake-3.14.4/Source/cmSystemTools.cxx, line 1459

John Doe@DESKTOP-CAT1JVP MINGW32 /x/build
$ cmake -G "NMake Makefiles" ..
-- The C compiler identification is unknown
Assertion failed: local_path.empty() || local_path.back() != '/', file E:/mingwbuild/mingw-w64-cmake/src/cmake-3.14.4/Source/cmSystemTools.cxx, line 1459

John Doe@DESKTOP-CAT1JVP MINGW32 /x/build
$ cmake -G "Unix Makefiles" ..
-- The C compiler identification is GNU 7.4.0
-- Check for working C compiler: C:/msys64/mingw32/bin/cc.exe
-- Check for working C compiler: C:/msys64/mingw32/bin/cc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
Assertion failed: local_path.empty() || local_path.back() != '/', file E:/mingwbuild/mingw-w64-cmake/src/cmake-3.14.4/Source/cmSystemTools.cxx, line 1459
```
All of them give the same assertion error :confused:

**Comment by MehdiChinoune** [comment]
closing since the package has been updated and we didn't get any similar bug reports since then
