### ISSUE TITLE
ostringstream::str() crash with -std=c++17

### ISSUE THREAD

**Issue by whfuyn** [msys2/MINGW-packages#5392]
```c++
#include <sstream>

int main(void){
    std::ostringstream s;
    // s << " ";
    s.str();
}
```
This simple code crash when compiled with `g++ test.cpp -o test.exe -g -std=c++17`, but it works fine if I uncomment`s << " ";` or use `-std=c++14`.

Other information:
```
# g++ --version
g++ (GCC) 7.3.0
Copyright © 2017 Free Software Foundation, Inc.
```
MSYS2 is installed by `msys2-x86_64-20180531.exe`

test.exe.stackdump
```
Stack trace:
Frame        Function    Args
000FFFFC210  0018005D16C (00000000000, 0000000FA80, 0000000007F, 000FFFFDE50)
000FFFFC2B0  0018005E77B (00000000000, 00000000000, 000000000C4, 00000000000)
000FFFFC500  00180123ACD (0018015A7DC, 00000000001, 00000000040, 0000027EE7C)
00180010000  001801202AE (00000000000, 43002D00000000, 00000000000, 00000000043)
000FFFFC990  00180120762 (005268EE073, 00526900E20, 0018011BEDB, 00000000006)
000FFFFC990  001801209AA (000FFFFCA88, 00000000000, 00000000000, 00000000000)
000FFFFC990  00180120C6F (00526911320, 00526901B50, 0052690F920, 00526901B50)
000FFFFC990  0018015A0C6 (000FFFFCBA8, 000FFFFCAD8, 00000000010, 0052690EB78)
000FFFFC990  001800BA8E3 (005268ED084, 000FFFFCBA8, 005268EEF26, 000FFFFC9D0)
000FFFFC990  0018011BEDB (005268ED084, 000FFFFCBA8, 005268EEF26, 000FFFFC9D0)
000FFFFC990  00100401840 (00526902560, 00000000019, 000FFFFFFFF, 000FFFFCA88)
000FFFFC9D0  00100401927 (000FFFFCA3F, 000FFFFCA80, 000FFFFCA80, 000FFFFCA90)
000FFFFCA00  00100401997 (000FFFFCA3F, 001801C9710, 000FFFFCBA0, 000FFFFCC50)
000FFFFCA90  001004019FD (001800B20F5, 00180142BC1, 0018014478F, 00526918878)
000FFFFCAE0  00100401161 (00000000020, 30001010000FF00, 00180047986, 00000340000)
000FFFFCCB0  001800479F7 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace (more stack frames may be present)
```

**Comment by whfuyn** [comment]
![QYC4ZFU7{(787{P`IS_)L(6](https://user-images.githubusercontent.com/39162745/58070397-79969500-7bcb-11e9-96d4-b848e2f5f1d7.png)

![}~@VAEK{5 @XXEW`%JG8FZG](https://user-images.githubusercontent.com/39162745/58070410-81eed000-7bcb-11e9-8a37-9f09ac866928.png)

![LJX1L M)_$@ZS 91UVS8N](https://user-images.githubusercontent.com/39162745/58070415-86b38400-7bcb-11e9-850f-d3678513820d.png)

**Comment by whfuyn** [comment]
After I ensure every ostringstream has been filled with some chars, my project won't crash when optimization is off. But not with -O3.
-O3 works fine on Cygwin64 and Unbuntu.

**Comment by oscarfv** [comment]
Cannot reproduce with an up to date mingw-w64-i686-gcc package:

```
$ g++ --version
g++.exe (Rev1, Built by MSYS2 project) 7.4.0
```

 Any reason for not upgrading your packages?

**Comment by whfuyn** [comment]
> 
> 
> Cannot reproduce with an up to date mingw-w64-i686-gcc package:
> 
> ```
> $ g++ --version
> g++.exe (Rev1, Built by MSYS2 project) 7.4.0
> ```
> 
> Any reason for not upgrading your packages?

No, I just need a platform that can provide a POSIX enviroment. I thought it crashed for some smart pointer and vtable issues, and spent a lot of time debugging it. It makes me feel better if I can figure out the reason :p

**Comment by oscarfv** [comment]
So you are using MSYS2 gcc, not MinGW-w64 gcc.

First of all, this project (MINGW-packages) is for MinGW-based packages ("native", not dependent on any POSIX emulation layer). You need to direct your bug report to https://github.com/msys2/MSYS2-packages

Second, MSYS2 (the POSIX emulation layer and dependent packages) is about providing a convenient tooling for building MinGW-w64 packages. If you want a POSIX environment for building and using POSIX-dependent software, maybe Cygwin is more adequate.

**Comment by whfuyn** [comment]
> 
> 
> So you are using MSYS2 gcc, not MinGW-w64 gcc.
> 
> First of all, this project (MINGW-packages) is for MinGW-based packages ("native", not dependent on any POSIX emulation layer). You need to direct your bug report to https://github.com/msys2/MSYS2-packages
> 
> Second, MSYS2 (the POSIX emulation layer and dependent packages) is about providing a convenient tooling for building MinGW-w64 packages. If you want a POSIX environment for building and using POSIX-dependent software, maybe Cygwin is more adequate.

Sorry for the late reply.
I'm not familiar with MSYS and pick the first repository as mentioned in the homepage for issue and bug report...
I will close this issue and open a new one there. Thanks for your help!
