### ISSUE TITLE
avrdude under msys2 doesn't work, but WinAVR version does

### ISSUE THREAD

**Issue by clinton-r** [msys2/MINGW-packages#5396]
Hi, I originally posted this in the wrong place (msys2/MSYS2-packages), so now I'm copying it here.  I'm also adding a second file, similar to the first but with the -v's omitted from the commands.  Thanks.
------------------
Hello, I've been trying to use avrdude under msys2, but I haven't been able to make it work. I finally installed WinAVR instead and the (old) avrdude it provides does work. I'm running Windows 10 64-bit, but I tried both packages mingw-w64-x86_64-avrdude and mingw-w64-i686-avrdude. The programmer I'm using is the Pocket AVR Programmer from SparkFun. I'm attaching a file showing the output I get from each of the avrdude versions. The first 3 commands just try to contact the AVR, the next 3 are trying to program it.
avrdude_problems.txt
Can anyone please tell me what could be wrong? Thanks.

[avrdude_problems.txt](https://github.com/msys2/MINGW-packages/files/3204879/avrdude_problems.txt)
[avrdude_problems_silent.txt](https://github.com/msys2/MINGW-packages/files/3204880/avrdude_problems_silent.txt)

**Comment by clinton-r** [comment]
An additional note: I did come across this posting: https://github.com/msys2/MINGW-packages/issues/947
I have verified that the following packages are installed already:
mingw-w64-i686-libusb-compat-git
mingw-w64-x86_64-libusb-compat-git

**Comment by stahta01** [comment]
There is likely very few people with hardware to test this program.
Does it have a problem that can be duplicated without the programming hardware?

Tim S.

**Comment by stahta01** [comment]
Are you running the command from the proper Msys2 mingw command window?

Tim S.

**Comment by stahta01** [comment]
Is this programmer hooked up to the parallel printer port?

Tim S.

**Comment by clinton-r** [comment]
Hi Tim,
1. I don't know of any commands other than --help which don't need to connect to a programmer first, so I don't think there is any problem that can be duplicated without the programmer, sorry.
2. I usually run the commands from the Windows command prompt, and the files I attached were done that way.  I have tried in all 3 of the MSYS2 command windows installed with MSYS2, and the problems are the same.  The installed windows show up in my start menu as MSYS2 MinGW 32-bit, MSYS2 MinGW 64-bit, and MSYS2 MSYS.
3. The programmer is connected by USB.  Interesting that the WinAVR version indicates lpt1 as the port.  I've recently also found this version of avrdude: http://blog.zakkemble.net/avrdudess-a-gui-for-avrdude/
I'm using just the command line tools from it.  It does show the port as "Using Port : usb"
Thanks very much for your help.
Clint

**Comment by clinton-r** [comment]
I thought I would try get the source and build the package myself, so that I can try to troubleshoot it myself.  Unfortunately the build fails for me.  I hope this is the right place to ask for help with building...  Here is what I did, all in the "MSYS2 MSYS" shell:

> $ git clone "https://github.com/Alexpux/MINGW-packages"

(that seemed to work fine)

> $ cd MINGW-packages/mingw-w64-avrdude

(also fine)

> $ makepkg-mingw -sCLf
> ==> Making package: mingw-w64-avrdude 6.3-2 (10 Jun 2019 20:50:39)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Downloading avrdude-6.3.tar.gz...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  888k  100  888k    0     0  96935      0  0:00:09  0:00:09 --:--:--  116k
>   -> Downloading avrdude-6.3.tar.gz.sig...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    72  100    72    0     0     20      0  0:00:03  0:00:03 --:--:--    20
>   -> Found 01-libtool.patch
>   -> Found 02-ddk-headers.patch
>   -> Found 03-handle-printing.patch
>   -> Found 04-no-giveio.patch
> ==> Validating source files with sha256sums...
>     avrdude-6.3.tar.gz ... Passed
>     avrdude-6.3.tar.gz.sig ... Skipped
>     01-libtool.patch ... Passed
>     02-ddk-headers.patch ... Passed
>     03-handle-printing.patch ... Passed
>     04-no-giveio.patch ... Passed
> ==> Verifying source file signatures with gpg...
>     avrdude-6.3.tar.gz ... FAILED (unknown public key F48CA81B69A85873)
> ==> ERROR: One or more PGP signatures could not be verified!
> 
> 

Should this just work, or have I missed something(s)?

I'm following the example under "Re-building a package" on [this page](https://github.com/msys2/msys2/wiki/Creating-Packages).
I will keep digging to try to understand why this error is occurring, but I'm just a beginner here and will appreciate any help.

Thanks,
Clint

**Comment by stahta01** [comment]
Try adding skippgpcheck
makepkg-mingw -sCLf --skippgpcheck

**Comment by clinton-r** [comment]
I did some experimenting with the code, and discovered the function call chain that is leading to the error.  This chain leads from avrdude through libusb-compat to libusb, so I guess the problem is with libusb-compat or how it is being used by avrdude.  I have no familiarity with or understanding of any of this code, so I will leave it for now.  If anyone is interested to look further, I'll attach a file describing the call chain to the error.  Thanks.
[callchain.txt](https://github.com/msys2/MINGW-packages/files/3705485/callchain.txt)

**Comment by Amavect** [comment]
I have a USBtinyISP. It works with the old avrdude downloaded from WinAVR, but not when compiled from source.
I've done a great deal of digging through libusb source by now (which was quite painful).

The differences in device enumeration between libusb-win32 and libusb calls to SetupDiGetClassDevsA() cause the incompatibility. In libusb, the handle returned is valid (in fact, all of the arguments and flags are correct), but the handle points to no devices. This fails on the subsequent call to SetupDiEnumDeviceInfo(). winusbx_claim_interface() calls SetupDiGetClassDevsA(), which eventually bubbles up to winusbx_submit_control_transfer(), which was the extent of callchain.txt.

The issue is ultimately the device driver's fault (and Window's cruddy device api).
adafruit/Adafruit_Windows_Drivers#22

Thanks,
Amavect
