### ISSUE TITLE
mingw-w64-i686-zlib (1.2.11-7) breaks dependency 'mingw-w64-i686-minizip' required by mingw-w64-i686-assimp

### ISSUE THREAD

**Issue by BenKey** [msys2/MINGW-packages#5400]
I am getting the following odd error when I run 'pacman -Syuu.'

> :: Starting full system upgrade...
> resolving dependencies...
> looking for conflicting packages...
> error: failed to prepare transaction (could not satisfy dependencies)
> :: installing mingw-w64-i686-zlib (1.2.11-7) breaks dependency 'mingw-w64-i686-minizip' required by mingw-w64-i686-assimp
> :: installing mingw-w64-x86_64-zlib (1.2.11-7) breaks dependency 'mingw-w64-x86_64-minizip' required by mingw-w64-x86_64-assimp
>

**Comment by oscarfv** [comment]
There was a change today affecting zlib and minizip. Apparently some dependencies need to be updated.

If you are in a hurry, you can try

```
$ pacman -S mingw-w64-i686-minizip-git
$ pacman -S mingw-w64-x86_64-minizip-git
```

accept the questions about replacing minizip with minizip-git and then `pacman -Suuy`.

**Comment by Alexpux** [comment]
To workaround problem run:
````
pacman -Sdd mingw-w64-{i686,x86_64}-zlib
pacman -S mingw-w64-minizip
````

**Comment by lazka** [comment]
So zlib lost the provides for minizip and upgrading it breaks the dependency for assimp. I wonder what would be the correct fix here. Would bumping the pkgrel of assimp work?

**Comment by Alexpux** [comment]
Assimp was rebuilded to properly handle minizip package

**Comment by BenKey** [comment]
Thanks.
