### ISSUE TITLE
libgda doesn't contain providers(jdbc/mysql/postgres)

### ISSUE THREAD

**Issue by taozuhong** [msys2/MINGW-packages#5407]
libgda( mingw-w64-x86_64-libgda) doesn't contain providers(jdbc/mysql/postgres):
libgda-jdbc
libgda-mysql
libgda-postgres
libgda-sqlserver

but the PKGBUILD seems that contain them all:
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libgda/PKGBUILD

due to lack of providers, this package doesn't work with mysql / postgres / jdbc on windows.

**Comment by Alexpux** [comment]
See /mingw64/lib/libgda-5.0 providers folder, all is there

**Comment by taozuhong** [comment]
Hi Alexpux, thanks for your response.

I have checked the directory:/mingw64/lib/libgda-5.0/providers, found mysql and postgres provider, but can't list in gda providers:
` Installed providers list
Provider | Description
---------+------------------------------------
MSAccess | Provider for Microsoft Access files
SQLite   | Provider for SQLite databases
Web      | Provider for web server proxies
(3 rows)
`

ldd analyze the dll show the information as follow:
`
# ldd libgda-mysql.dll
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x77670000)
        kernel32.dll => /c/Windows/system32/kernel32.dll (0x77450000)
        KERNELBASE.dll => /c/Windows/system32/KERNELBASE.dll (0x7fefd170000)
        ??? => ??? (0x70000000)
        ??? => ??? (0x63b40000)
        ??? => ??? (0x7fefe690000)
        ??? => ??? (0x77570000)
        ??? => ??? (0x7feff7f0000)
        ??? => ??? (0x7fefdb70000)
        ??? => ??? (0x7feff870000)
        ??? => ??? (0x613c0000)
        ??? => ??? (0x61cc0000)
        ??? => ??? (0x7fefe090000)
        ??? => ??? (0x7fefd620000)
        ??? => ??? (0x7fefdd60000)
        ??? => ??? (0x66000000)
        ??? => ??? (0x7fefc700000)
        ??? => ??? (0x7fefe850000)
        ??? => ??? (0x7feff860000)
        ??? => ??? (0x7fefa7b0000)
        ??? => ??? (0x7fefa7a0000)
        ??? => ??? (0x7fefea30000)
        ??? => ??? (0x7fefe730000)
        ??? => ??? (0x62e80000)
        ??? => ??? (0x649c0000)
        ??? => ??? (0x7fefd640000)
        ??? => ??? (0x64940000)
        ??? => ??? (0x69140000)
        ??? => ??? (0x66c40000)
        ??? => ??? (0x67f00000)
        ??? => ??? (0x6b740000)
        ??? => ??? (0x70f40000)
        ??? => ??? (0x3d0000)
`

**Comment by taozuhong** [comment]
```bash
# ls
libgda-firebird-client.dll    libgda-mdb.dll         libgda-sqlcipher.dll
libgda-firebird-client.dll.a  libgda-mdb.dll.a       libgda-sqlcipher.dll.a
libgda-firebird-embed.dll     libgda-mysql.dll       libgda-sqlite.dll
libgda-firebird-embed.dll.a   libgda-mysql.dll.a     libgda-sqlite.dll.a
libgda-ldap.dll               libgda-postgres.dll    libgda-web.dll
libgda-ldap.dll.a             libgda-postgres.dll.a  libgda-web.dll.a
```
