### ISSUE TITLE
Missing sources for gcc-7.4.0-1

### ISSUE THREAD

**Issue by dg0yt** [msys2/MINGW-packages#5428]
http://repo.msys2.org/mingw/sources/ does not contain sources for gcc-7.4.0-1, which is the newest binary for i686 (http://repo.msys2.org/mingw/i686/mingw-w64-i686-gcc-7.4.0-1-any.pkg.tar.xz).

**Comment by lazka** [comment]
I can't help you with the missing sources, but the newest version has matching sources there again.

**Comment by dg0yt** [comment]
I see, I will need to test gcc 9.1.0 then.

If the corresponding sources, patches and build scripts cannot be supplied, the binaries may need to be removed as well.

**Comment by Alexpux** [comment]
@dg0yt all patches and build scripts for all packages are in this repository or you dont have eyes?
https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-gcc7

**Comment by dg0yt** [comment]
> ... or you dont have eyes?

@alexpux I think there are better ways to express that you think that I should guess what the source was.

**Comment by Alexpux** [comment]
Time to time I'm removing packages and sources from repos because of disk quota exceeded.

**Comment by Alexpux** [comment]
Sources uploaded
