### ISSUE TITLE
Broken dependency in today update (GCC-9.1)

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#5434]
Just now:

```
$ pacman -Syu
:: Sincronizzazione dei database in corso...
 mingw32                                   545,0 KiB   792K/s 00:01 [####################################] 100%
 mingw32.sig                               119,0   B  0,00B/s 00:00 [####################################] 100%
 mingw64                                   546,1 KiB   943K/s 00:01 [####################################] 100%
 mingw64.sig                               119,0   B  0,00B/s 00:00 [####################################] 100%
 msys è aggiornato
:: Starting core system upgrade...
 non ci sono aggiornamenti disponibili
:: Aggiornamento del sistema in corso...
risoluzione delle dipendenze in corso...
ricerca dei pacchetti in conflitto in corso...
errore: impossibile eseguire l'operazione richiesta (impossibile soddisfare le dipendenze)
:: installing mingw-w64-i686-gcc (9.1.0-1) breaks dependency 'mingw-w64-i686-gcc=7.4.0-1' required by mingw-w64-i686-gcc-ada
:: installing mingw-w64-i686-gcc (9.1.0-1) breaks dependency 'mingw-w64-i686-gcc=7.4.0-1' required by mingw-w64-i686-gcc-objc
:: installing mingw-w64-x86_64-gcc (9.1.0-1) breaks dependency 'mingw-w64-x86_64-gcc=8.3.0-2' required by mingw-w64-x86_64-gcc-ada
:: installing mingw-w64-x86_64-gcc (9.1.0-1) breaks dependency 'mingw-w64-x86_64-gcc=8.3.0-2' required by mingw-w64-x86_64-gcc-objc
```

How to fix?

**Comment by Alexpux** [comment]
Remove Ada and ObjC packages. They are dropped now.

**Comment by Ede123** [comment]
Is there a good option to do this in CI environments which are broken because of this?  
Or is "manually" uninstalling the only way?

**Comment by Alexpux** [comment]
I think only manually can do

**Comment by Biswa96** [comment]
I have this error in pacman:

    resolving dependencies...
    looking for conflicting packages...
    error: failed to prepare transaction (could not satisfy dependencies)
    :: installing mingw-w64-x86_64-gcc (9.1.0-1) breaks dependency 'mingw-w64-x86_64-gcc=8.3.0-2' required by mingw-w64-x86_64-gcc-ada
    :: installing mingw-w64-x86_64-gcc (9.1.0-1) breaks dependency 'mingw-w64-x86_64-gcc=8.3.0-2' required by mingw-w64-x86_64-gcc-objc

**Comment by Optiligence** [comment]
https://github.com/msys2/MINGW-packages/issues/5434

Am Mi., 29. Mai 2019 um 06:21 Uhr schrieb Biswapriyo Nath <
notifications@github.com>:

**Comment by lazka** [comment]
> Is there a good option to do this in CI environments which are broken because of this?

```
# Workaround gcc9 update issues
pacman -R --noconfirm mingw-w64-i686-gcc-ada mingw-w64-i686-gcc-objc || true;
pacman -R --noconfirm mingw-w64-x86_64-gcc-ada mingw-w64-x86_64-gcc-objc || true;
```

**Comment by Ede123** [comment]
Yes, that's what I referred to as "manually" and [implemented accordingly](https://gitlab.com/inkscape/inkscape/commit/9d97563e2fab586ea511f7291ef6b2fe6c28c2b2).

The obvious problem is that this requires manual intervention and does not prevent the CI from failing if this type of conflict occurs for a different package in future.

**Comment by Optiligence** [comment]
To alleviate this problem the gcc PKGBUILD could make use of [`replaces`](https://wiki.archlinux.org/index.php/PKGBUILD#replaces)

One could say that the usage would be _incorrect_, but I would argue that the benefits outweigh that argument here.

**Comment by lazka** [comment]
> The obvious problem is that this requires manual intervention and does not prevent the CI from failing if this type of conflict occurs for a different package in future.

Yeah, agreed, this came up @ https://gitter.im/msys2/msys2?at=5cee3b899b50f639354862e5

**Comment by angelog0** [comment]
@Alexpux wrote:
> Remove Ada and ObjC packages. They are dropped now.

What a pity!

Ok, fixed now... and closing the issue...

**Comment by Ede123** [comment]
> 
> 
> > The obvious problem is that this requires manual intervention and does not prevent the CI from failing if this type of conflict occurs for a different package in future.
> 
> Yeah, agreed, this came up @ https://gitter.im/msys2/msys2?at=5cee3b899b50f639354862e5

I see, so it's not obvious if this even is solvable without causing more trouble... (Oh, and thanks for pointing towards gitter, I always thought IRC was the most official communication channel for MSYS2).
