### ISSUE TITLE
-DNGHTTP2_STATICLIB CFLAGS option has to be specified when building static curl to link against libnghttp2.a

### ISSUE THREAD

**Issue by tomay3000** [msys2/MINGW-packages#5440]
**-DNGHTTP2_STATICLIB** CFLAGS option has to be specified when building **static** libcurl to link against **libnghttp2.a**, otherwise linker errors will be raised complaining about the **dynamic** **library** **libnghttp2.dll.a**

**Comment by Alexpux** [comment]
@tomay3000 i think we already do it. See https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-curl/0002-nghttp2-static.patch

**Comment by tomay3000** [comment]
@Alexpux it did not work unfortunately. I think **CURL_CFLAG_EXTRAS** should be used instead of **CURL_CPPFLAGS_EXTRA** because the main libcurl authors did like this:
`CURL_CFLAG_EXTRAS=-DCURL_STATICLIB -fno-ident -DCURL_DISABLE_SSL_AUTO_LOAD_CONFIG -fno-asynchronous-unwind-tables -DNGHTTP2_STATICLIB`. You can see the build log here: [https://ci.appveyor.com/project/curlorg/curl-for-win/build/1.0.1344/job/ou04hvmqdmaysp3f](https://ci.appveyor.com/project/curlorg/curl-for-win/build/1.0.1344/job/ou04hvmqdmaysp3f).
Their libcurl version is working without problems.

**Comment by Alexpux** [comment]
@tomay3000 check latest curl package

**Comment by tomay3000** [comment]
@Alexpux Same issue, I forgot to mention that I have to specify these three libraries to be dynamically linked to be able to compile like this: `-lnghttp2.dll -lpsl.dll -lidn2.dll` instead of the static ones.
So the problem remains.

**Comment by muv1** [comment]
https://github.com/msys2/MINGW-packages/issues/3538

**Comment by MehdiChinoune** [comment]
Fixed by #8804
