### ISSUE TITLE
More  breaks dependency errors.

### ISSUE THREAD

**Issue by BenKey** [msys2/MINGW-packages#5447]
I am getting the following errors when I run 'pacman -Syuu'.

> looking for conflicting packages...
> error: failed to prepare transaction (could not satisfy dependencies)
> :: installing mingw-w64-i686-gcc (9.1.0-1) breaks dependency 'mingw-w64-i686-gcc=7.4.0-1' required by mingw-w64-i686-gcc-ada
> :: installing mingw-w64-i686-gcc (9.1.0-1) breaks dependency 'mingw-w64-i686-gcc=7.4.0-1' required by mingw-w64-i686-gcc-objc
> :: installing mingw-w64-x86_64-gcc (9.1.0-1) breaks dependency 'mingw-w64-x86_64-gcc=8.3.0-2' required by mingw-w64-x86_64-gcc-ada
> :: installing mingw-w64-x86_64-gcc (9.1.0-1) breaks dependency 'mingw-w64-x86_64-gcc=8.3.0-2' required by mingw-w64-x86_64-gcc-objc
>

**Comment by Alexpux** [comment]
https://github.com/msys2/MINGW-packages/issues/5434

**Comment by BenKey** [comment]
Thanks.
