### ISSUE TITLE
appstream-glib

### ISSUE THREAD

**Issue by lillolollo** [msys2/MINGW-packages#5451]
Gimp master build need this package please can you add it? https://github.com/hughsie/appstream-glib
@lazka can you help please?

**Comment by Alexpux** [comment]
https://github.com/msys2/MINGW-packages/commit/fc42c9fd5619de4dd6aeb7a563c11995123dd9ba

**Comment by lillolollo** [comment]
@Alexpux Thanks :-) why pacman -S mingw-w64-i686-appstream-glib don't find the package?

**Comment by Adsun701** [comment]
Packages may not necessarily be uploaded to the repository immediately.

**Comment by lillolollo** [comment]
@Adsun701 Thanks

**Comment by lillolollo** [comment]
@Alexpux So I'm trying to install the package with MINGW_INSTALLS=mingw32 makepkg-mingw -sLf but I recive this error

 libappstream-glib/meson.build:238:2: ERROR: Program(s) ['g-ir-scanner'] not found or not executable

**Comment by Alexpux** [comment]
Install gobject-introspection package

**Comment by Alexpux** [comment]
@lillolollo fix is https://github.com/msys2/MINGW-packages/commit/3e97c415e37cb7c0c09ecca2e37da45f0f613b13

**Comment by lillolollo** [comment]
@Alexpux Thanks now it work
