### ISSUE TITLE
dependency gtk-update-icon-cache

### ISSUE THREAD

**Issue by lillolollo** [msys2/MINGW-packages#5455]
Seems gtk3 don't have this library @Adsun701 must be a different package?

**Comment by Adsun701** [comment]
@lillolollo `gtk-update-icon-cache` is owned by the `gtk2` package. We have `gtk-update-icon-cache-3.0` for `gtk3`.

**Comment by lillolollo** [comment]
@Adsun701 I'm trying to build Gimp master gtk3 is needed but I have errors for gtk-update-icon-cache and appstream-glib

**Comment by lillolollo** [comment]
@Adsun701 

# pacman -S mingw-w64-i686-gtk-update-icon-cache-3.0
error: target not found: mingw-w64-i686-gtk-update-icon-cache-3.0

**Comment by Adsun701** [comment]
@lillolollo the gtk3 package already contains gtk-update-icon-cache-3.0.exe; it does not split it into a separate package. Also if you need appstream-glib feel free to contribute a PKGBUILD rather than simply requesting.

**Comment by lillolollo** [comment]
@Adsun701 if I could do it I would have done it already :-)

**Comment by lillolollo** [comment]
@Adsun701 I have ask because on linux gtk-update-icon-cache have separate pakages

**Comment by Adsun701** [comment]
@lillolollo We don't have to follow the exact same conventions as Arch Linux when it regards to packages.

**Comment by lillolollo** [comment]
So I think we can close this issue
