### ISSUE TITLE
pkg-config and Unicode paths: a failed marriage

### ISSUE THREAD

**Issue by bit2shift** [msys2/MINGW-packages#5457]
`pkg-config` seems _unhappy_ when it has to deal with paths containing Unicode characters.
Its _MSYS_ sibling, on the other hand, has no problem dealing with those, as seen below.
![image](https://user-images.githubusercontent.com/6282023/58756190-21289700-84eb-11e9-94b7-7270d99ad586.png)

I'd say this "bug" is all too common with most (if not all) MINGW packages since the default CRT (`msvcrt.dll`) never supported UTF-8 in the first place. It being an _operating system DLL_ further compounds the problem since it cannot receive feature updates without breaking other system components or archaic programs that rely on it.

---
<details>
<summary>Contents of <code>sömë-päth-wïth-ünïcödë-chäräctërs/blah.pc</code></summary>
<pre>
Name: blah
Description: dummy package
Version: 0.0
Libs: -L.
Libs.private: -lm
Cflags: -I.
</pre>
</details>
Test invocation, from the <i>MINGW(32|64)</i> shell:
<pre>PKG_CONFIG_DEBUG_SPEW=1 PKG_CONFIG_PATH='sömë-päth-wïth-ünïcödë-chäräctërs' pkg-config --cflags blah</pre>

**Comment by oscarfv** [comment]
Mingw-w64 can use recent MSVCRTXX.DLL and has some extensions of its own. But UTF-8 on Windows is, so far, a non-starter. Microsoft introduced experimental support on last year's Windows 10 update, IIRC, that you can explicitly enable. In my experience it causes more problems than it solves.

OTOH, I would expect problems with UTF-16 (the "native" unicode encoding of Windows) and programs ported from GNU/Linux.

In any case, doing this type of experiments with MSYS2 mintty is not wise, try them with the Windows console.

BTW, please don't post screen captures of console output. It is difficult to read and it is not possible to copy and paste content to reproduce your observations.

**Comment by bit2shift** [comment]
@oscarfv the Linux programs built using the MSYS runtime don't have this problem since the CRT (`MSYS-2.0.DLL`) handles the necessary UTF-8 <> UTF-16 conversions automatically.

I tried it on `cmd.exe` with the same results: that the `msvcrt.dll` converts everything between UTF-16 and the current ACP when using the non-wide functions, eg. `main()` instead of `_wmain()`.

PS: you can click on images to open them on a new tab.

**Comment by stahta01** [comment]
Copy and Pasting is better!

**Comment by mingwandroid** [comment]
@bit2shift lots of mingw-w64 works fine with Unicode. Your bug applies only to pkg-build. Pardner welcome. It's not hard to fix.

**Comment by bit2shift** [comment]
@mingwandroid I would appreciate some advice in that direction, in regards to the format of patches and their relationship with the `PKGBUILD` file.
@oscarfv, @stahta01 I've updated the first post with a minimal (non-)working example.

**Comment by mingwandroid** [comment]
Will there is so much misinformation in your initial complaint presented as fact and I found it a little sharp, that personally I won't help you out. Sorry if I've misconstrued your intention but bashing our hard work seemed to be your main objective.

**Comment by bit2shift** [comment]
@mingwandroid that part after the image is a rant born out of frustration, targeted primarily at Microsoft for not having the initiative to fix `cp65001` (UTF-8 code page) so it could be used like a regular _ACP_ (ANSI Code Page), which would fix >90% of the problems arising from the use of the narrow-char APIs.
A residual amount is targeted at the MinGW project for not having provided a proper C99/C11 runtime from its inception.
None of it was aimed at what this repo has accomplished to improve the _MinGW experience_.

I'll figure it out on my own since I've faced similar Unicode problems with `mingw-w64-jq`, having already come up with a fix for it (stedolan/jq/pull/1907).

**Comment by mingwandroid** [comment]
Ah OK, no worries and thanks for helping out.
