### ISSUE TITLE
glbindings missing KHR includes

### ISSUE THREAD

**Issue by TinoM** [msys2/MINGW-packages#5458]

**Comment by TinoM** [comment]
The build scripts for glbindings-3.1.0 explicitely removes the KHR includes, but they are needed when using glbindings.

**Comment by Adsun701** [comment]
@TinoM They are already provided by the `angleproject-git` package.

**Comment by TinoM** [comment]
Ok, but then this package should be a dependency. If I want to use openglbindings, how should i know that a completely unrelated package provides necessary header files?

**Comment by Alexpux** [comment]
@TinoM @Adsun701 right now angleproject is not buildable anymore as google switch build to its own build system that i dont really want to see, so I will deprecate angleproject-git package and remove it probably

**Comment by TinoM** [comment]
Thanks to both of you @Adsun701 and @Alexpux. Was able to mitigate the issue by using the angleproject package for now.

**Comment by Alexpux** [comment]
@TinoM  @Adsun701 I remove angleproject package from database as not supported anymore because google switch build system to its own. Will restore KHR headers soon

**Comment by Alexpux** [comment]
KHR headers restored
