### ISSUE TITLE
mingw-w64-i686-imagemagick-7.0.8.47-1 broken

### ISSUE THREAD

**Issue by shithappens2016** [msys2/MINGW-packages#5466]

**Comment by t246246** [comment]
I wrote the same thing at https://github.com/msys2/MSYS2-packages/issues/1666, I now noticed it was the  wrong place.  So I continue this topic here.

If your environment is Windows 7, it is the same issue.

After disabling  MAGICKCORE_LOCALE_SUPPORT at the link and build it from source, it works.

But I have to set some environment variables.

$ export MAGICK_CONFIGURE_PATH=/mingw64
$ export MAGICK_CONFIGURE_PATH=/mingw64/etc/ImageMagick-7
$ export MAGICK_CODER_MODULE_PATH=/mingw64/lib/ImageMagick-7.0.8/modules-Q16HDRI/coders

**Comment by Alexpux** [comment]
Fixed by https://github.com/msys2/MINGW-packages/commit/1209ad5fa50088e23cb0c70a2c670c7da62a0440

**Comment by t246246** [comment]
This patch works.  However, as it disabled locale support, magick command cannot read non-ascii file.
