### ISSUE TITLE
mingw-w64-gdb (libiberty): ERROR: undeclared (first use in this function): _O_RDONLY  _O_BINARY  _O_TEXT

### ISSUE THREAD

**Issue by eactor** [msys2/MINGW-packages#5491]
Rebuilding the package with all standard msys - mingw64 shell with **makepgk** dies after config:

config.status: executing default commands
make[1]: Leaving directory '/d/workspaces/own_gdb/MINGW-packages/mingw-w64-gdb/src/build-x86_64-w64-mingw32'
make: *** [Makefile:857: all] Error 2
**==> ERROR: A failure occurred in build().
    Aborting...**

Restarting 'make' manually in '/d/workspaces/own_gdb/MINGW-packages/mingw-w64-gdb/src/build-x86_64-w64-mingw32' results in

../../gdb-8.3/libiberty/pex-win32.c:121:10: warning: implicit declaration of function ‘_open’; did you mean ‘open’? [-Wimplicit-function-declaration]
   return _open (name, _O_RDONLY | (binary ? _O_BINARY : _O_TEXT));
          ^~~~~
          open
../../gdb-8.3/libiberty/pex-win32.c:121:23: **error: ‘_O_RDONLY’ undeclared** (first use in this function); did you mean ‘O_RDONLY’?
   return _open (name, _O_RDONLY | (binary ? _O_BINARY : _O_TEXT));
                       ^~~~~~~~~
                       O_RDONLY
../../gdb-8.3/libiberty/pex-win32.c:121:23: note: each undeclared identifier is reported only once for each function it appears in
../../gdb-8.3/libiberty/pex-win32.c:121:45: **error: ‘_O_BINARY’ undeclared** (first use in this function); did you mean ‘O_BINARY’?
   return _open (name, _O_RDONLY | (binary ? _O_BINARY : _O_TEXT));
                                             ^~~~~~~~~
                                             O_BINARY
../../gdb-8.3/libiberty/pex-win32.c:121:57: **error: ‘_O_TEXT’ undeclared** (first use in this function); did you mean ‘__TEXT’?
   return _open (name, _O_RDONLY | (binary ? _O_BINARY : _O_TEXT));
                                                         ^~~~~~~

I also tried to rebuild the gdb with my own compiler within same mingw shell, but get stuck at different point : 

configure:9746: checking for libexpat
configure:9765: gcc -o conftest.exe -I/mingw64/include/pdcurses -I/mingw64/include -D__USE_MINGW_ACCESS -I/mingw64/include/pdcurses -I/mingw64/include -Wl,--stack,12582912 conftest.c -lcurses -lm /mingw64/lib/libexpat.a >&5
D:/COSIDE_VERSION_SPACE/coside-2.6RC2_mingw-**w64_2019_06_06/tools/msys64/mingw64/lib/libexpat.a(xmlparse.o):(.text+0x860a): undefined reference to `__imp___acrt_iob_func'**

**Comment by Alexpux** [comment]
Are you using makepkg-mingw not makepkg?

**Comment by eactor** [comment]
Sorry my fault
