### ISSUE TITLE
Package Inkscape 1.0 alpha?

### ISSUE THREAD

**Issue by kozross** [msys2/MINGW-packages#5506]
Given [this issue here][1], it appears no fixes will get backported any time soon, and I'd like to test Inkscape's alpha's functionality in the MSYS2 shell. Would it be possible to package the 1.0 alpha for Inkscape?

[1]: https://gitlab.com/inkscape/inbox/issues/564

**Comment by Alexpux** [comment]
well I prefer to wait a release. In any case I don’t have time right now to do it myself

**Comment by Ede123** [comment]
Absolute misinterpretation of what I said...

Inkscape 0.92.x is our "long-term support" branch and will receive bug-fixes for the foreseeable future.

Inkscape 1.0alpha is currently (as the name says) in alpha-phase and we're only slowly getting to beta-phase from where there's still some way to go to the 1.0 stable release.

For productive work 0.92.4 is by far the best choice right now (and might even be for some time after the 1.0 release as I'm sure some regressions will have slipped in and they might not all be caught in time for the release).

**Comment by kozross** [comment]
@Ede123 I apologise for misunderstanding what you said - I definitely should have phrased my request better. Thanks for clearing that up.

**Comment by oscarfv** [comment]
@kozross : if you changed your mind about your request, please close this issue. Thanks.
