### ISSUE TITLE
gobjc missing

### ISSUE THREAD

**Issue by Midar** [msys2/MINGW-packages#5538]
Hi!

It seems that gobjc was dropped a few days ago. This broke every application using ObjFW, as well as ObjFW itself: https://ci.appveyor.com/project/Midar/objfw-wbanh#L66

While there is no application in msys2 that uses ObjFW, msys2 is currently the recommended way to build ObjFW and applications depending on it, and all ObjFW applications for Windows are built using it: https://github.com/objfw/objfw#windows

This affects some popular software for Windows as well, for example XVid4PSP.

Can this be restored, please? Clang is still buggy on Windows.

CC: @winnydows @GunGraveKoga

**Comment by Alexpux** [comment]
@Midar you can build your own GCC packages using scripts from our repo. Right now I dont plan to return back Ada and ObjC

**Comment by Midar** [comment]
Telling my users to rebuild GCC is against the entire point - I should not ask them to spend an hour recompiling the only thing they use from MSys2, just because you decided to strip a component that is part of a standard GCC installation and takes around 10 seconds to build. At that point, I have to discourage use of MSys2. You save 10 seconds, but every user has to rebuild for an hour. I strongly urge you to reconsider this, as the ObjC frontend in GCC is super-low (pretty much zero) maintenance: It's just there, it doesn't require more than C++ (if you have threads, global ctors and exceptions -- all strong requirements for C++ -- you have everything you need), it takes 10 seconds to build it and it increases binary size by so little you don't even notice. And most importantly, it is considered a *default language* by GCC (unlike Ada). There's really no reason to ship GCC with less functionality than it's default configuration other than to spite users who expect a full GCC, but then only get a subset of GCC that's less than the default configuration. You also wouldn't ship a GCC with C++ disabled, would you?

**Comment by Alexpux** [comment]
@Midar read my carefully answers in https://github.com/msys2/MINGW-packages/issues/5508
I'm explain there what I think and why it happen. Issue about  dropping Ada and ObjC was started a year ago and no one go there and have discuss with us.
I owed you nothing and promised nothing.

**Comment by mingwandroid** [comment]
> There's really no reason to ship GCC with less functionality than it's default configuration other than to spite users who expect a full GCC, but then only get a subset of GCC that's less than the default configuration.

Are you serious? Spite our users? You should be ashamed of yourself.


> You also wouldn't ship a GCC with C++ disabled, would you?

Yes. I would. If a c programmer (politely) asked me to and I had time. Get involved if you care, otherwise don't complain.

**Comment by Midar** [comment]
@Alexpun I was not aware of the discussion a year ago. Also, there is reasons for dropping Ada in #5508, but not even a mention of ObjC. What are the reasons for dropping ObjC? There is no maintenance burden involved, there is increase in compile time (it disappears in the noise of how expensive it is to build GCC), there is no increase in binary size (it disappears in the noise of the sheer size of GCC), it was not broken. So, what reasons are there? None were listed.

@mingwandroid Well, if there is no reason to drop it (see above), then why drop it other than saying "No, we don't like our users to have the software in the default configuration - they should get through great length of effort if they want to have the full software"?

**Comment by mingwandroid** [comment]
Welcome to open source. Yes

**Comment by Midar** [comment]
@mingwandroid Thanks for your derogatory comment. I've been in open source for almost two decades, so I think I know how it works. Either you run a project that is supposed to be for users, then you provide a rationale for breaking users, or you run a project only for yourself and don't care about users. It would be sad if MSys2 falls into the latter.

**Comment by Alexpux** [comment]
@Midar as I tell earlier, there is no any feedback from users/communities who use MSYS2. You come here only after the fact that we decide something and remove something. Topic about removing Ada and ObjC was open year ago and no one leave feedback about ObjC, so don’t blame me. 
You can create your own custom repo and provide packages that missing in MSYS2 to your users. As I tell MSYS2 is free time project, so if you don’t want to spend your time to do something that you needed, then why need spend MY time for your needs?

**Comment by Alexpux** [comment]
Fixed via https://github.com/msys2/MINGW-packages/commit/7e59389dd7fe748b38356f0fc78f5edeb933aa96

**Comment by Midar** [comment]
@Alexpux Thanks for fixing!

Unfortunately, there was no deprecation notice or anything that would have brought the bug to my attention, and the bug also provided no hints on to why ObjC would be removed (as it seems it wasn't broken). Is there a way to show such a bug to users the next time a package gets removed? I don't think all users are following all bugs :). Just an idea. I'm happy for now that it's back, thanks! I was just about the submit a patch setting that =no back to =yes since you said if I want it I should do it ;).
