### ISSUE TITLE
Issue at gphoto2 package

### ISSUE THREAD

**Issue by laheller** [msys2/MINGW-packages#5542]
Hi @dsisnero @nacho @bbolli @taketori @bygreencn 

I have an issue in latest MSYS2 and gphoto2/libgphoto2 v2.5.23-1 packages.
The command _gphoto2 -a_ recognizes my **Canon EOS 1300D** camera.
But when I try to take a photo using command _gphoto2 --show-preview --debug_, it returns with an error:
_1.587091 gp_libusb1_open [libusb1.c:430](0): 'libusb_claim_interface (port->pl->dh, port->settings.usb.interface)' failed: **Access denied (insufficient permissions)** (-3)
1.588091 gp_port_set_error [gphoto2-port.c:1190](0): Could not claim interface 0 (No such file or directory). Make sure no other program (unknown libgphoto2 using program) or kernel module (such as sdc2xx, stv680, spca50x) is using the device and you have read/write access to the device._

I am sure that no other program is using the camera! I am running MSYS2/mingw64 as an Administrator and the command prompt also has the hashtag format, which says at least to me that I have permissions.

Any idea? Was anybody able to successfully take photo using gphoto2 on msys2/mingw64 ?

BR

Ladislav

**Comment by laheller** [comment]
Update!

I disabled the **Canon EOS 1300D** item in _Device Manager / Computer / Portable Devices_.
Now the error message after command _gphoto2 --show-preview --debug_ is following:
_1.524087 gp_libusb1_open [libusb1.c:398](0): 'libusb_open (port->pl->d, &port->pl->dh)' failed: Operation not supported or unimplemented on this platform (-12)_

Pls help! How to make gphoto2/libgphoto2/libusb work on msys2/mingw64?

**Comment by laheller** [comment]
Update #2!

After googling a while I've found a tool called [Zadig](https://zadig.akeo.ie/) which is able to replace **WinUSB driver** to **libusb driver** for a selected USB device. Now the _gphoto2_ command works perfectly!

**Comment by peterbud** [comment]
I'm glad that you have found this, actually this is the way how you can enable tethering with libgphoto2 on Windows, as described here: https://www.darktable.org/about/faq/#faq-tethering

If everything works, then pls close the issue.
