### ISSUE TITLE
[opencv] opencv (4.1.0) dnn module fails to load libprotobuf.dll (3.8.0)

### ISSUE THREAD

**Issue by isra60** [msys2/MINGW-packages#5547]
Packages are

mingw-w64-x86_64-opencv 4.1.0-2 
mingw-w64-x86_64-protobuf 3.8.0-1 

The program says ...

The procedure entry point 

_ZN6google8protobuf8internal17AssignDescriptorsEPNS1_22AssignDescriptorsTableE
_ZN6google8protobuf8internal14AddDescriptorsEPNS1_15DescriptorTableEPKPFvvEi

could not be located in the dynamic library libopencv_dnn410.dll

Based on dependency walker these are the only functions are broken...

**Comment by Alexpux** [comment]
@isra60 probably need rebuild opencv

**Comment by isra60** [comment]
Yeah I think so. But the package should be fixed right? 
I tried with the 4.0.1 package and the same libprotobuf.dll and works

**Comment by Alexpux** [comment]
@isra60  fixed
