### ISSUE TITLE
Trojan detected on qt5

### ISSUE THREAD

**Issue by enginmanap** [msys2/MINGW-packages#5551]
Hi,

while installing package: mingw-w64-x86_64-qt

Kaspersky antivirus detects a trojan on file: 

%MSYS2 DIR%\mingw64\share\qt5\examples\widgets\itemviews\frozencolumn\frozencolumn.exe

The trojan name means it is detected by Heuristics, so it is possibly a false positive. Full name: HEUR:Trojan.Win32.Generic

**Comment by lazka** [comment]
https://www.virustotal.com/gui/file/42875d898f196f8fb03970287f28363a88e2bc64805f797f20085ea1f1dea5ce/detection

**Comment by Alexpux** [comment]
@enginmanap there are nothing that i can do here. Use as is or build yourself.
