### ISSUE TITLE
Upgrade qt to 5.12.4-1,qmake don't work.

### ISSUE THREAD

**Issue by CCTV-1** [msys2/MINGW-packages#5554]
upgrade to `5.12.4-1`:
`qmake -project`
error message:
`D:/MSYS2/mingw64/share/qt5/mkspecs/common/windows-vulkan.conf:1: Cannot find feature windows_vulkan_sdk`

downgrade to `5.12.3-1`:
`pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-qt5-5.12.3-1-any.pkg.tar.xz`
`qmake -project`
the work.

**Comment by Alexpux** [comment]
@CCTV-1 this is just an warning. This is regression upstream

**Comment by CCTV-1** [comment]
ah,yes.
i habitually think this is error message.
