### ISSUE TITLE
Python: when installing librarys via pip deletes python/python3.exe

### ISSUE THREAD

**Issue by genusistimelord** [msys2/MINGW-packages#5560]
updated to the latest msys2 and latest python versions. 
Using python 3.7
1. `python3 -m venv venv` Also tried it with just python.
2. `source venv/bin/activate`
3. `pip install -r requirements.txt`

After installing the appropriate Msys2 programs and library's i ran the above 3 lines. What occurs is it will download all of the files just fine then begin installing them.

Running setup.py install for cffi ... done
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for SQLAlchemy ... done
  Running setup.py install for Mako ... done
(venv)

once it gets this far it then deletes the python3.exe or python.exe <which ever one i was attempting to use at the time and not finish the installation.  I thought this might of just been a environment issues so i also attempted to install them without the environment which also deleted python.exe or python3.exe. 

the requirement file i am using is below:

[requirements.txt](https://github.com/msys2/MINGW-packages/files/3311671/requirements.txt)

**Comment by lazka** [comment]
I can't reproduce. It installs fine here and is usable after that.

btw, I'd look into using WSL instead of MSYS2 for this, it'll probably be faster.

**Comment by genusistimelord** [comment]
Hello and thank you for the quick reply. First off I do not really want 100 huge programs on my PC i rather have a select few. It is why i use msys2. I also use msys2 for C development which is a god send compared to getting libraries and compiling them all manually. (thank you Alexey for your hard work).

I did manage to figure out the cause. Apparently Comodo updated itself and now thinks Python is a crypto virus it even says "probably" within the quarantine. So i suspect other antivirus might start to do the same so leaving this here as a helper for others who's files get silently removed.

**Comment by lazka** [comment]
ok, thanks for the update :+1:
