### ISSUE TITLE
GCC 9: c++ standard experimental networking is broken

### ISSUE THREAD

**Issue by kassane** [msys2/MINGW-packages#5570]
I've been testing a simple example in using io_context and several errors occur during the compile attempt. However in linux it works normally.

```cpp
#include <experimental/net>
namespace net = std::experimental::net;

int main()
{
    net::io_context io;
}
```
mingw params: ``-std=c++2a -mwindows -lpthread -lws2_32``

**Comment by Alexpux** [comment]
@kassane, I’m not GCC developer, fill bug report to GCC bugzilla
