### ISSUE TITLE
Ask a question about executing the g++ command

### ISSUE THREAD

**Issue by zhouhangzooo** [msys2/MINGW-packages#5582]
If the a.pp file fails to compile when executing the g++ a.pp command, a prompt appears, where is the prompt file in winGW?
在执行g++ a.cpp命令进行编译时，如果a.cpp文件编译不通过，出现提示，请问这个提示文件在winGW中哪个位置？

**Comment by zhouhangzooo** [comment]
![image](https://user-images.githubusercontent.com/37395573/60577916-de403480-9db2-11e9-944b-89c23e9b231e.png)
I want to know where this error message is stored, and I want to find the location of this error message

**Comment by Alexpux** [comment]
I think all is described clearly in error message. You must add missing include to your sources

**Comment by zhouhangzooo** [comment]
I think the error message is not clear enough. Could you tell me which file the information is stored in?

**Comment by Alexpux** [comment]
I don’t understand what you mean.

**Comment by StarWolf3000** [comment]
@Alexpux I think they want to know, where in the GCC's source code the error and warning messages are stored in?

**Comment by zhouhangzooo** [comment]
@StarWolf3000 right!

**Comment by Alexpux** [comment]
@zhouhangzooo you need ask on GCC mailing list - this is not GCC developers resource

**Comment by MehdiChinoune** [comment]
You need to include `#include <iostream>` in your source file.
