### ISSUE TITLE
upgrade to latest hdf5 version

### ISSUE THREAD

**Issue by musm** [msys2/MINGW-packages#5585]

**Comment by musm** [comment]
The only patch that is required is https://github.com/musm/hdf5-builds/blob/master/utf8-windows-filenames.patch

**Comment by Alexpux** [comment]
@musm we build HDF5 with cmake, so you need update your patch to be able build with cmake

**Comment by musm** [comment]
The build is fine with cmake. Just apply the patch then autoreconf

**Comment by Alexpux** [comment]
@musm cmake doesnt need autoreconf

**Comment by musm** [comment]
What's wrong with autoreconf, i.e. why do you want cmake

**Comment by Alexpux** [comment]
@musm once we build it with cmake I dont want to switch back to autotools. If you not argee I dont mind. If you will be able to fix cmake build then do it - if no wait while someone do it.

**Comment by musm** [comment]
Yeah I'm  not sure how to convert the patch for cmake.

**Comment by musm** [comment]
OK nvm. I think all that needs to be done is to update the hdf5 patch list. Remove the ones in this repo and update with the linked one. Cmake should work just fine. I'll test later.

**Comment by Alexpux** [comment]
@musm implemented by https://github.com/msys2/MINGW-packages/commit/b80713152cedea8f421b4428c973b9f584734f63
