### ISSUE TITLE
gdb: command line is broken

### ISSUE THREAD

**Issue by MCP1** [msys2/MINGW-packages#5587]
In recent gdb versions (mingw-w64-x86_64-gdb-8.3-X and 8.2.1-X) the command line is not usable (arrow keys and backspace don't work). Tested in winpty, cmd, powerShell, all with the same results. 
Steps to reproduce: install msys2-x86_64-20190524.exe and update twice, run "pacman -S mingw-w64-x86_64-gdb winpty", run "winpty gdb" and try to edit the command line with backspace. Tested in Windows 10 1903.
MSYS2 version of gdb (gdb-8.2.1-2) works flawlessly.

**Comment by jwt27** [comment]
I noticed this too and I believe it happened after ncurses/termcap were removed. It's not just an issue with the mingw build, I built a cross-gdb under mingw64 and it has the same bug.

**Comment by Alexpux** [comment]
@MCP1 @jwt27 Im back packages to ncurses

**Comment by MCP1** [comment]
Working fine now, tks!
