### ISSUE TITLE
gimp package windows 7 32 bit error

### ISSUE THREAD

**Issue by lillolollo** [msys2/MINGW-packages#5591]
Starting gimp I have this error

`# gimp-2.10
GEGL-Message: 08:10:42.390: Module 'C:\msys32\mingw32\lib\gegl-0.4\ff-load.dll' load error: 'C:\msys32\mingw32\lib\gegl-0.4\ff-load.dll': The specified module could not be found.
GEGL-Message: 08:10:42.390: Module 'C:\msys32\mingw32\lib\gegl-0.4\ff-save.dll' load error: 'C:\msys32\mingw32\lib\gegl-0.4\ff-save.dll': The specified module could not be found.
C:\msys32\mingw32\bin\gimp-2.10.exe: Gimp-Widgets-WARNING: parse_iso_codes: error parsing 'C:\msys32\mingw32\share\xml\iso-codes\iso_639.xml': No such file or directory

C:\msys32\mingw32\bin\gimp-2.10.exe: LibGimpBase-WARNING: gimp-2.10.exe: gimp_wire_read(): error
`

and drmingw seems to not work

for the iso-codes error seems the folder it is not created

**Comment by Alexpux** [comment]
Run gimp from cmd or explorer and see what dll is missing

**Comment by lillolollo** [comment]
one problem seems to be file-heif

**Comment by lillolollo** [comment]
but the iso-codes folder is missed too

**Comment by Alexpux** [comment]
libheif in dependencies - https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gimp/PKGBUILD#L24

ISO-codes in make dependencies

**Comment by lillolollo** [comment]
I don't know what happen but on windows 7 32 bit gimp mingw pakage show those error

**Comment by Alexpux** [comment]
As I tell run from cmd and see real missing library or some entry points inside libraries

**Comment by lillolollo** [comment]
Alex the error log come from the mingw32 cmd I started gimp with
# gimp-2.10

**Comment by Alexpux** [comment]
I don’t have Win7 32bit so I can’t do anything here. Try to find issue

**Comment by lillolollo** [comment]
I use a VM

**Comment by Alexpux** [comment]
Sorry but I don’t have time to find it myself, maybe some later

**Comment by lillolollo** [comment]
Thanks anyway for the effort

**Comment by Alexpux** [comment]
Problem seems that libheif need to be rebuilded with new x265 library

**Comment by lillolollo** [comment]
the main issue is the  iso-codes folder I don't know if they are related

**Comment by Alexpux** [comment]
Отправлено с iPhone

**Comment by Alexpux** [comment]
Install iso-codes package

**Comment by lillolollo** [comment]
Thnks yes it fix the iso-codes issue so this package must be added to gimp/PKGBUILD now remain gegl and file-heif

**Comment by Alexpux** [comment]
@lillolollo try update packages and see if issue present

**Comment by lillolollo** [comment]
file-heif is fixed too remain the gegl error on console, and drmingw seems don't work on crash thanks

**Comment by Alexpux** [comment]
@lillolollo what error with gegl?

**Comment by lillolollo** [comment]
@Alexpux 

GEGL-Message: 08:10:42.390: Module 'C:\msys32\mingw32\lib\gegl-0.4\ff-load.dll' load error: 'C:\msys32\mingw32\lib\gegl-0.4\ff-load.dll': The specified module could not be found.
GEGL-Message: 08:10:42.390: Module 'C:\msys32\mingw32\lib\gegl-0.4\ff-save.dll' load error: 'C:\msys32\mingw32\lib\gegl-0.4\ff-save.dll': The specified module could not be found.

**Comment by Alexpux** [comment]
@lillolollo as I told earlier you must run gimp from cmd and you will see window that tell what library is missing, in other case I cannot help you anymore

**Comment by lillolollo** [comment]
Excuse me for the delay thanks for your help the issue seem vanished now so we can close it
