### ISSUE TITLE
Aspell 0.60.7 RC2 is out.

### ISSUE THREAD

**Issue by kevina** [msys2/MINGW-packages#5603]
Aspell 0.60.7 RC2 is available at ftp://alpha.gnu.org/gnu/aspell/aspell-0.60.7-rc2.tar.gz

This should fix the crash and avoid the need for `0008-cache-Attempt-to-prevent-premature-destruction-of-gl.patch`.

Could you confirm that this is indeed the case.

**Comment by Alexpux** [comment]
Updated by https://github.com/msys2/MINGW-packages/commit/3e947b756dc5b39783d366bfaa098872ffe725cc
