### ISSUE TITLE
pgp problem curl

### ISSUE THREAD

**Issue by pmjherman** [msys2/MINGW-packages#5614]
I try to compile curl on a fresh MSYS2 install on Windows10, after updating with pacman -Suuy and using the package build instructions freshly downloaded from the mingw-64 package repository
command: 
      makepkg-mingw -sCLf
I get a pgp error: 
     curl-7.65.1.tar.bz2 ... MISLUKT (onbekende publieke sleutel 5CC908FDB71E12C2)
(translation:  curl-7.65.1.tar.bz2 ... FAILED (unknown public key 5CC908FDB71E12C2))

Compilation was successful with command  
     makepkg-mingw --skippgpcheck -sCLf
but this is unsecure.
Any tips how to solve this?

**Comment by lazka** [comment]
`gpg --recv 5CC908FDB71E12C2`

**Comment by pmjherman** [comment]
Thanks! not an issue, but my ignorance. It works perfectly now!
