### ISSUE TITLE
GCC-9.1.0 segmentation fault when building QtWebKit

### ISSUE THREAD

**Issue by Alexpux** [msys2/MINGW-packages#5620]
Here is build log - [https://gist.github.com/Alexpux/1ea5ddf64a412287c07bc6a03689a1ea](https://gist.github.com/Alexpux/1ea5ddf64a412287c07bc6a03689a1ea)

**Comment by Alexpux** [comment]
https://github.com/msys2/MINGW-packages/issues/5664#issue-474966043

**Comment by MehdiChinoune** [comment]
closing since the package has been updated
