### ISSUE TITLE
mingw64-gnuplot  wxmsw30u_core_gcc_custom.dll cannot open.

### ISSUE THREAD

**Issue by challengeX** [msys2/MINGW-packages#5631]
C:/msys64/mingw64/bin/gnuplot.exe: error while loading shared libraries: wxmsw30u_core_gcc_custom.dll: cannot open shared object file: No such file or directory

**Comment by Alexpux** [comment]
@challengeX run gnuplot from CMD to see real missing library

**Comment by challengeX** [comment]
oh,Qt5Network.dll is missing

**Comment by challengeX** [comment]
> @challengeX run gnuplot from CMD to see real missing library

oh,Qt5Network.dll is missing

**Comment by challengeX** [comment]
> @challengeX run gnuplot from CMD to see real missing library
so,do i need to install qt5?

**Comment by darkuranium** [comment]
Had the same exact problem. Installing qt5 manually fixed it.

Looks like the gnuplot package has a missing dependency?

**Comment by Alexpux** [comment]
@darkuranium Qt5 is in optdepends for gnuplot because Qt5 is very big package

**Comment by darkuranium** [comment]
@Alexpux Alright ... but it doesn't work without it, so...?

**Comment by Alexpux** [comment]
@darkuranium well then I add Qt5 to depends.

**Comment by nickoe** [comment]
Does gnuplot support dynamic toolkits? Maybe the problem with the wxwidgets dll goes away because it find the qt dll first? I mean, qt can't be the solution here for the missing wxwidgets dll.

**Comment by Alexpux** [comment]
It linked with both wxwidgets and qt

**Comment by Alexpux** [comment]
@darkuranium @nickoe probably better to disable qt at all for gnuplot?

**Comment by darkuranium** [comment]
I've no idea how it's internally structured, so I'll leave it up to you to determine how to best get this working.

**Comment by Alexpux** [comment]
@darkuranium fixed by https://github.com/msys2/MINGW-packages/commit/ec6f33dc0cf8376d84a6aca1c65430cc91d2eb2d
