### ISSUE TITLE
meson: ImportError: DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by AntumDeluge** [msys2/MINGW-packages#5635]
I sent the following report to the [Meson Build project](https://github.com/mesonbuild/meson/issues/5699), but thought it would be good to share it here as well:

> I can't decrypt the following error. I believe the issue is happening because I am using 32-bit Python but it is trying to load a 64-bit DLL library on my system path. The error occurs when trying to load the `pyexpat` library, but there is no other information, so I don't know how to find the DLL that is causing the problem:
>
> ```
> Traceback (most recent call last):
>   File "C:\Development\MSYS2\mingw32\bin\meson-script.py", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "C:/Development/MSYS2/mingw32/lib/python3.7/site-packages\pkg_resources\__init__.py", line 35, in <module>
>     import plistlib
>   File "C:/Development/MSYS2/mingw32/lib/python3.7\plistlib.py", line 65, in <module>
>     from xml.parsers.expat import ParserCreate
>   File "C:/Development/MSYS2/mingw32/lib/python3.7\xml\parsers\expat.py", line 4, in <module>
>     from pyexpat import *
> ImportError: DLL load failed: %1 is not a valid Win32 application.
> ```
>
> I am trying to build the [Pixman library](http://www.pixman.org/) on Windows under the [MSYS2/MinGW-w64](https://www.msys2.org/) environment. I have no problems building a 64-bit library. So it leads me to believe the issue has something to do with a 64-bit DLL interfering with the 32-bit meson build environment. Please let me know if there is any other information that I might be able to provide.
>
> **Edit:** I can circumvent the error by explicitly calling the meson executable from the 64-bit environment (*/mingw64/bin/meson*), but would be nice if I didn't have to do so, so that I didn't have to manually edit the MSYS2/MinGW-w64 build configuration files.

**Comment by Alexpux** [comment]
Try to place pyexpat pyd or dll file to bin folder and open it in dependency walker to see what is wrong

**Comment by AntumDeluge** [comment]
Found the following files:

```sh
$ find /mingw32/lib -type f -name "*pyexpat*"
/mingw32/lib/python2.7/lib-dynload/pyexpat.pyd
/mingw32/lib/python2.7/test/test_pyexpat.py
/mingw32/lib/python2.7/test/test_pyexpat.pyc
/mingw32/lib/python2.7/test/test_pyexpat.pyo
/mingw32/lib/python3.7/lib-dynload/pyexpat-cpython-37m.dll
/mingw32/lib/python3.7/test/test_pyexpat.py
/mingw32/lib/python3.7/test/__pycache__/test_pyexpat.cpython-37.opt-1.pyc
/mingw32/lib/python3.7/test/__pycache__/test_pyexpat.cpython-37.opt-2.pyc
/mingw32/lib/python3.7/test/__pycache__/test_pyexpat.cpython-37.pyc
```

Since the error shows it's using Pythone 3 (`C:/Development/MSYS2/mingw32/lib/python3.7`), I think I can ignore the Python 2 files.

Running the file `/mingw32/lib/python3.7/lib-dynload/pyexpat-cpython-37m.dll` through Dependency Walker, it appears that it is linked to `libexpat-1.dll`. Since I have rebuilt the expat library as static only, it is using the DLL from another location: `c:\program files\inkscape\LIBEXPAT-1.DLL`. So, I'm thinking that perhaps I need to manually rebuild Python against my static expat library? Ugh!

**Comment by Alexpux** [comment]
Yes, you need rebuild python yourself with your static library. Don’t mix DLLs provided by msys2 with others as it always will lead to problems

**Comment by AntumDeluge** [comment]
Using `/usr/bin/meson` & `/usr/bin/ninja` fixes the issue. However, then I get an undefined reference to `posix_memalign`:

```
[33/110] Compiling C object 'test/9f86d08@@testutils@sta/utils.c.o'.
../pixman-0.38.4/test/utils.c: In function 'aligned_malloc':
../pixman-0.38.4/test/utils.c:1007:9: warning: implicit declaration of function 'posix_memalign' [-Wimplicit-function-declaration]
 1007 |     if (posix_memalign (&result, align, size) != 0)
      |         ^~~~~~~~~~~~~~
[46/110] Linking target test/infinite-loop.
FAILED: test/infinite-loop
cc @test/infinite-loop.rsp
test/libtestutils.a(utils.c.o):utils.c:(.text+0x186b): undefined reference to `posix_memalign'
collect2.exe: error: ld returned 1 exit status
[49/110] Linking target test/a1-trap-test.
FAILED: test/a1-trap-test
cc @test/a1-trap-test.rsp
test/libtestutils.a(utils.c.o):utils.c:(.text+0x186b): undefined reference to `posix_memalign'
collect2.exe: error: ld returned 1 exit status
[51/110] Linking target test/fetch-test.
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
```

Using my system Python/meson/ninja does work however. So, I am just going to set it as default rather than rebuild MinGW Python.
