### ISSUE TITLE
mingw-w64-x86_64-qt5-5.12.4-2-any fails to install

### ISSUE THREAD

**Issue by stev-0** [msys2/MINGW-packages#5645]
I am using MSYS2 64bit 20190524.

My issue is that the package above will not install. It gets stuck at 80%. There are no error messages, or errors in the logs.

Steps to reproduce:

1. Open shell `C:\msys64\msys2_shell.cmd -msys`.
2. Run `pacman -Suy`
3. Close shell
4. Reopen same shell
5. Run `pacman -Suy` again
6. Run `pacman -S mingw-w64-x86_64-qt5`

Result:

`(62/62) installing mingw-w64-x86_64-qt5                                                                                                                            [################################################################################--------------------]  80%`

P.S. I have tried this a number of times, so unless it is an exceptionally long operation disproportionate to the rest of the install, I don't think I am being impatient.

**Comment by StarWolf3000** [comment]
Did you check for storage activity, like blinking LED for your system drive? Have you checked for activity in Task Manager? Qt is a huge library, so even on fast computers and drives it takes a while to install.

**Comment by mati865** [comment]
Check CPU usage of Windows Defender or any other installed AV software, quite often it's the bottleneck because it uses single thread per file and pacman "installs" files sequentially.

**Comment by stahta01** [comment]
It is over 1 gig installation file; I think it installs 3 to 5 gigs of files. Tim S.

**Comment by christianpopescu** [comment]
I have the same problem on mingw-w64-i686-qt5-5.13.2-1.

Packman has been blocked by Norton Antivirus :suspect activity **SONAR.AM.C!g6**

![Blocked at 80 percent](https://user-images.githubusercontent.com/5845588/71327004-1e32d980-2503-11ea-9d46-4de19c810c89.png)


![Security Risk detected](https://user-images.githubusercontent.com/5845588/71327003-1e32d980-2503-11ea-81a9-8665a18c4fe9.png)

**Comment by StarWolf3000** [comment]
> I have the same problem on mingw-w64-i686-qt5-5.13.2-1.
> 
> Packman has been blocked by Norton Antivirus :suspect activity **SONAR.AM.C!g6**
> 
> ![Blocked at 80 percent](https://user-images.githubusercontent.com/5845588/71327004-1e32d980-2503-11ea-9d46-4de19c810c89.png)
> 
> ![Security Risk detected](https://user-images.githubusercontent.com/5845588/71327003-1e32d980-2503-11ea-81a9-8665a18c4fe9.png)

That is a heuristic detection, not an actual virus or trojan. You have to authorize pacman to continue, since the binaries aren't signed (that'd cost lots of money).

**Comment by MehdiChinoune** [comment]
likely no longer an issue
