### ISSUE TITLE
Does mingw-gdb  not parse  pdb file?

### ISSUE THREAD

**Issue by Byzero512** [msys2/MINGW-packages#5646]
when I use the follow commands to load pdb file
symbol-file: it return can't read symbols: File format not recognized
add-symbol-file: The address where xxx.pdb has been loaded is missing

**Comment by Alexpux** [comment]
GDB doesn’t support MSVC pdb files

**Comment by oscarfv** [comment]
@Byzero512 : as Alexpux (and gdb itself) says, gdb does not support the PDB format.

If you have no further questions about this topic, please close this issue. Thanks.
