### ISSUE TITLE
Request: pkg-config library path style return

### ISSUE THREAD

**Issue by HerveAncher** [msys2/MINGW-packages#5650]
Hi all,

When I call pkg-config directly (or accross CMake) the standard library path returned are in Windows style.
Exemple :

```
# pkg-config --libs libcurl
-LC:/msys64/mingw64/lib -lcurl

# pkg-config --libs libxml-2.0
-LC:/msys64/mingw64/lib -lxml2
```

And when GCC try to compile with these path, obviously it failed (because of comma interpretation as separator).
Under my proper CMake script I have developed macro to convert Windows style path to Linux with cygpath tool (`C:/msys64/ => /c/msys64/`) but for other community projects, i is not so simple to modify them to introduce MinGW Windows path tricks.

For my proper library, some returned path in Wndows style, some in Linux:

```
# pkg-config --libs uda-cpp
-L/c/Dev/IMAS/uda-2.2.6/lib -luda_cpp
```

Is it possible to introduce a flag to specify at pkg-config to directly convert path to fit Linux style?
When a said "a flag", I mean an environment variable like `PKG_CONFIG_PATH_STYLE=Windows/Linux`

I use the last MSYS2/MinGW 64 bits installation with GCC 9.1.0 and pkg-config 0.29.2

Thanks ;°)

**Comment by lazka** [comment]
Looks like you are mixing mingw pkg-config and msys2 gcc. Make sure you have `mingw-w64-x86_64-gcc` installed.

**Comment by HerveAncher** [comment]
Yes, this package is installed:

```
# pacman -Ss mingw-w64-x86_64-gcc
mingw64/mingw-w64-x86_64-gcc 9.1.0-3 (mingw-w64-x86_64-toolchain) [installé]
    GNU Compiler Collection (C,C++,OpenMP) for MinGW-w64
mingw64/mingw-w64-x86_64-gcc-ada 9.1.0-3 (mingw-w64-x86_64-toolchain) [installé]
    GNU Compiler Collection (Ada) for MinGW-w64
mingw64/mingw-w64-x86_64-gcc-fortran 9.1.0-3 (mingw-w64-x86_64-toolchain) [installé]
    GNU Compiler Collection (Fortran) for MinGW-w64
mingw64/mingw-w64-x86_64-gcc-libgfortran 9.1.0-3 (mingw-w64-x86_64-toolchain) [installé]
    GNU Compiler Collection (libgfortran) for MinGW-w64
mingw64/mingw-w64-x86_64-gcc-libs 9.1.0-3 (mingw-w64-x86_64-toolchain) [installé]
    GNU Compiler Collection (libraries) for MinGW-w64
mingw64/mingw-w64-x86_64-gcc-objc 9.1.0-3 (mingw-w64-x86_64-toolchain) [installé]
    GNU Compiler Collection (ObjC,Obj-C++) for MinGW-w64
```

And this is the right version:

```
# which pkg-config
/mingw64/bin/pkg-config

```

**Comment by Alexpux** [comment]
@HerveAncher, native MINGW GCC works ok with Windows paths and dont work with UNIX style paths, so from my point of view you use MINGW pkg-config with MSYS gcc

**Comment by HerveAncher** [comment]
When I called this command:

```
# /usr/bin/pkg-config --libs libxml-2.0
-L/mingw64/lib -lxml2 -lz -llzma -liconv -lws2_32
```

The path returned is correct.

so I remove the mingw-w64 package with this command:

`pacman -R mingw-w64-x86_64-pkg-config`

And now, the paths are correct in all situation! Thanks ;°)
