### ISSUE TITLE
Use windmc in distutils for Python 3

### ISSUE THREAD

**Issue by joankaradimov** [msys2/MINGW-packages#5659]
While trying to build the [pywin32 package](https://github.com/msys2/MINGW-packages/pull/5615) on Python 3, I get this error:

```
error: unknown file type '.mc' (from 'win32/src/PerfMon/PyPerfMsgs.mc')
```

It appears that the Python 2 package [patches distutils](https://github.com/msys2/MINGW-packages/blob/228cc0cf1611d0fdc77915fffdcd481f17d8805d/mingw-w64-python2/2000-distutils-add-windmc-to-cygwinccompiler.patch) and handles `.mc` files via `windmc` from binutils. Python 3, however, does not.

**Comment by lazka** [comment]
Sounds like a good idea.

**Comment by Alexpux** [comment]
done by @https://github.com/msys2/MINGW-packages/commit/240d92366618714d270d7236f35ebff450bd763d

**Comment by lazka** [comment]
@Alexpux  what about this part of the py2 patch 

```diff
             ext_normcase = os.path.normcase(ext)
             if ext_normcase in ['.rc','.res']:
                 ext = ext_normcase
-            if ext not in (self.src_extensions + ['.rc','.res']):
+            if ext not in (self.src_extensions + ['.rc', '.res', '.mc']):
                 raise UnknownFileError, \
                       "unknown file type '%s' (from '%s')" % \
                       (ext, src_name)
```

Is it not needed?

**Comment by Alexpux** [comment]
oh forgot about it. Will fix

**Comment by Alexpux** [comment]
Done in https://github.com/msys2/MINGW-packages/commit/1912c5bffe55b2ac8be1f59769bbf5b7d1620059
