### ISSUE TITLE
GCC 9.1.0 segfault often

### ISSUE THREAD

**Issue by Alexpux** [msys2/MINGW-packages#5664]
Current GCC 9.1.0 have lots of segfaults during build packages. 
Broken packages:

- Qt 5.13.0
- QtWebkit
- opencolada

**Comment by vadz** [comment]
FWIW it also gave an internal compiler error while building wxWidgets unit tests (using CATCH), see [this build log](https://ci.appveyor.com/project/wxWidgets/wxwidgets/builds/26445788/job/ovajab6v4ltp5h70), for example.

We've worked around it by just adding extra parentheses in [this commit](https://github.com/wxWidgets/wxWidgets/commit/054cb35b395a88486d23df4db44ed153bfc0847f)

**Comment by JL2210** [comment]
You're kidding. I had the exact same issue on a Gentoo installation and I thought it was bad memory.

**Comment by MehdiChinoune** [comment]
We no longer see these segfaults.
