### ISSUE TITLE
gitg 3.32.1

### ISSUE THREAD

**Issue by albfan** [msys2/MINGW-packages#5686]
I'm sure this is something easy to fix, but can remember it.

I need to copy libs from:

`/mingw64/lib` to `/mingw64/bin` to be able to run `gitg.exe`

right now they were: libdazzle-1.0-0.dll, libgitg-1.0-0.dll and libgitg-ext-1.0-0.dll

@lazka, @Alexpux: Any of you remember what is needed on meson to make gitg look for libraries on `/mingw64/lib`?. I guess it is `${prefix}/lib` in general

**Comment by Alexpux** [comment]
@albfan all dlls must be installed in bin folder, only plugins can be in lib but they must be loaded by relative paths or so

**Comment by Alexpux** [comment]
So from my point of view this is bug in build system

**Comment by Alexpux** [comment]
@albfan gitg already install dlls in bin, but not libdazzle

**Comment by albfan** [comment]
ok, that makes sense, let me fix that on libdazzle and we are ready to go.

What a journey! @Alexpux you rock!

**Comment by albfan** [comment]
#5687 should fix that
