### ISSUE TITLE
prebuild zeromq package still ships with old c++ header

### ISSUE THREAD

**Issue by kanonet** [msys2/MINGW-packages#5689]
Hi,
a few days ago I updated mingw-w64-zeromq to include new version of zmq.hpp. Packaging works on my machine and correctly includes the new header file. The PR got accepted but when I install the new prebuild package it still ships the old header file.
So what went wrong? Did I miss something, since this was my first PR to msys2?

**Comment by Alexpux** [comment]
Fixed. Need to remove old downloaded header before build
