### ISSUE TITLE
(binutils) windres.exe: Can't detect architecture.

### ISSUE THREAD

**Issue by LigH-de** [msys2/MINGW-packages#5692]
_Bold guess:_

Possibly since you "fixed" [handling filenames with spaces by quoting](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-binutils/0100-Put-filenames-from-command-line-in-quotes-to-handle-spaces-correctly.patch), windres.exe fails in projects like x265 or mpv.

https://github.com/jb-alvarado/media-autobuild_suite/issues/1335

**Comment by lazka** [comment]
@Alexpux ^

**Comment by hhromic** [comment]
It's also failing for me too since the recent update :(
In my case, windres is just failing silently with a retval of `127` when there are `-I` arguments passed.

**Comment by stahta01** [comment]
Finally an answer to the problem I have building my own wxWidgets-git project

**Comment by Alexpux** [comment]
https://github.com/msys2/MINGW-packages/commit/fec9a48d35ea79d7188d9506ca6c61fd4611c9dc
