### ISSUE TITLE
_syslist.h should also define _O_RDONLY, etc

### ISSUE THREAD

**Issue by cbiesinger** [msys2/MINGW-packages#5695]
I'm not sure if I'm using this right, but I am trying to compile gdb, which has calls like this:

```c
 int fd = _open (executable, _O_RDONLY);
```

It seems that mingw defines `_open` in /usr/include/_syslist.h, but not `_O_RDONLY` and the like. Should it?

**Comment by Alexpux** [comment]
@cbiesinger MINGW never use headers from /usr, only from /mingw{32,64}. If you see that mingw GCC try to use headers from /usr then check include paths

**Comment by lazka** [comment]
_open is defined in io.h, _O_RDONLY in fcntl.h. See the Microsoft docs for details.

**Comment by cbiesinger** [comment]
@Alexpux that doesn't seem correct:
```
$ echo | gcc -E -Wp,-v -
ignoring nonexistent directory "/usr/local/include"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/include"
ignoring duplicate directory "/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/lib/../lib/../../include/w32api"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-pc-msys/9.1.0/include
 /usr/lib/gcc/x86_64-pc-msys/9.1.0/include-fixed
 /usr/include
 /usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../lib/../include/w32api
End of search list.
```

@lazka I know that's what MSDN says but it is not what MSYS2/MINGW64 are shipping:
```
cbiesinger@cbiesinger0-w MINGW64 /usr/include
$ grep -r _O_RDONLY *

cbiesinger@cbiesinger0-w MINGW64 /usr/include
$
```

**Comment by cbiesinger** [comment]
(it's not in /usr/lib/gcc/x86_64-pc-msys/9.1.0 either)

**Comment by Alexpux** [comment]
@cbiesinger wrong here is you. You tell about mingw but GCC that you use is MSYS, this is not the same. MSYS(Cygwin) GCC is mostly Unix-like GCC and don’t use Win32 API directly

**Comment by StarWolf3000** [comment]
@cbiesinger Your first snippet is from MSYS2 shell (which you never should use for MINGW), your second from MINGW64 shell, but you're in the wrong path.

It should look like this:
```
$ echo | gcc -E -Wp,-v -
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "<stdin>"
ignoring duplicate directory "C:/msys64/mingw64/lib/gcc/../../lib/gcc/x86_64-w64-mingw32/9.2.0/include"
ignoring nonexistent directory "C:/building/msys64/mingw64/include"
ignoring nonexistent directory "/mingw64/include"
ignoring duplicate directory "C:/msys64/mingw64/lib/gcc/../../lib/gcc/x86_64-w64-mingw32/9.2.0/include-fixed"
ignoring duplicate directory "C:/msys64/mingw64/lib/gcc/../../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/include"
ignoring nonexistent directory "C:/building/msys64/mingw64/x86_64-w64-mingw32/include"
#include "..." search starts here:
#include <...> search starts here:
 C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/include
 C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../include
 C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/include-fixed
 C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/include
End of search list.
```

Searching for _O_RDONLY:
```
MINGW64 /mingw64
$ grep -nR _O_RDONLY .
./include/uv/win.h:673:#define UV_FS_O_RDONLY       _O_RDONLY
./x86_64-w64-mingw32/include/fcntl.h:13:#define _O_RDONLY 0x0000
./x86_64-w64-mingw32/include/fcntl.h:25:#define _O_ACCMODE (_O_RDONLY|_O_WRONLY|_O_RDWR)
./x86_64-w64-mingw32/include/fcntl.h:36:#define O_RDONLY _O_RDONLY
```

**Comment by cbiesinger** [comment]
OK, I must have installed this incorrectly (?)

cbiesinger@cbiesinger0-w MINGW64 /mingw64
$ echo | x86_64-pc-msys-gcc -E -Wp,-v -
ignoring nonexistent directory "/usr/local/include"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/include"
ignoring duplicate directory "/usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../x86_64-pc-msys/lib/../lib/../../include/w32api"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-pc-msys/9.1.0/include
 /usr/lib/gcc/x86_64-pc-msys/9.1.0/include-fixed
 /usr/include
 /usr/lib/gcc/x86_64-pc-msys/9.1.0/../../../../lib/../include/w32api
End of search list.
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "<stdin>"

cbiesinger@cbiesinger0-w MINGW64 /mingw64
$ ls /mingw64
bin  etc  include  lib  share


I guess I'll try reinstalling....?

**Comment by cbiesinger** [comment]
Sorry @Alexpux ; you were right, and I installed the msys gcc instead of the mingw64. My apologies for wasting y'all's time.
