### ISSUE TITLE
Is there any particular reason Python2 doesn't have SQLite as a dependency?

### ISSUE THREAD

**Issue by BrisingrAerowing** [msys2/MINGW-packages#5704]
As per title. Python2 doesn't have SQLite listed as a dependency. Is that intended or a mistake?

**Comment by lazka** [comment]
Probably a mistake.

**Comment by Alexpux** [comment]
Fixed by https://github.com/msys2/MINGW-packages/commit/694eed7a898af39423edadd0635a667d9282ab0f
