### ISSUE TITLE
gettext: Positional arguments

### ISSUE THREAD

**Issue by MangaD** [msys2/MINGW-packages#5706]
Gettext with positional arguments in printf doesn't appear to work.
```cpp
printf(gettext("String A: %2$s\nString B: %1$s\n", sb, sa));
```

**Comment by lazka** [comment]
What doesn't work?

**Comment by MangaD** [comment]
@lazka Suppose I have the following:
```cpp
printf(gettext("Replacing '%s' with file '%s'...\n"), nameA, nameB);
```
And in my PO file I translate that string as follows:
```po
msgid "Replacing '%s' with file '%s'...\n"
msgstr "A substituir '%2$s' com o ficheiro '%1$s'...\n"
```
The result I see when I run the program on Windows is this:
`A substituir '%2$s' com o ficheiro '%1$s'...`

So, positional arguments don't appear to work.

**Comment by MangaD** [comment]
Sorry, I have just realized that this is not a problem of `gettext` but windows `printf`.
https://docs.microsoft.com/en-us/cpp/c-runtime-library/printf-p-positional-parameters?view=vs-2019

I'll close this now.

**Comment by lazka** [comment]
OK, thanks for the update.
