### ISSUE TITLE
ASLR is now enabled for GCC binaries and it breaks PCH

### ISSUE THREAD

**Issue by bustercopley** [msys2/MINGW-packages#5719]
The binaries in the new gcc-9.2.0-1 packages have ASLR enabled in their PE headers. This breaks using precompiled headers, as they can no longer be mapped at a predictable address. The previous package had 'good' binaries, with ASLR disabled. (This isn't a change in the package itself. I rebuilt the 9.1.0-3 package, and the resulting binaries were 'bad'.)
I raised this on the GCC bug tracker[1].

For the GCC 9.1.0-3 packages (assuming they're still in your cache):

    pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-{gcc-9.1.0-3,gcc-libs-9.1.0-3}-any.pkg.tar.xz --noconfirm
    objdump -p /mingw64/lib/gcc/x86_64-w64-mingw32/9.1.0/cc1.exe | grep DllCharacteristics

Output:

    DllCharacteristics	00000000

For the GCC 9.2.0-1 packages:

    pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-{gcc-9.2.0-1,gcc-libs-9.2.0-1}-any.pkg.tar.xz --noconfirm
    objdump -p /mingw64/lib/gcc/x86_64-w64-mingw32/9.2.0/cc1.exe | grep DllCharacteristics

Output:

    DllCharacteristics	00000160

Hex 160 means[2]:
  0x040 (IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE) (i.e., ASLR enabled)
| 0x100 (IMAGE_DLLCHARACTERISTICS_NX_COMPAT) (i.e., DEP enabled)
| 0x020 (??)

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91440
[2] https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-image_optional_header32

**Comment by Alexpux** [comment]
@bustercopley fixed by https://github.com/msys2/MINGW-packages/commit/2602139640f15fb6c58c11c83903f2f3f48b7f13

**Comment by bustercopley** [comment]
Until a new release of the package comes out, workarounds are to remove the ASLR flag from cc1.exe and cc1plus.exe (e.g., using [setdllcharacteristics](https://blog.didierstevens.com/2010/10/17/setdllcharacteristics/), which you might prefer to compile for yourself) or rebuild gcc from the existing PKGBUILD script (having updated your binutils).

**Comment by Lord-Nightmare** [comment]
With the updated gcc-9.2.0-2 packages released on 20190829, this is now fixed, at least for my workload.
