### ISSUE TITLE
qtwebkit5 build error

### ISSUE THREAD

**Issue by spl1inter** [msys2/MINGW-packages#5734]
Hi Guys,

With recent copy of distro loaded the qtwebkit5 chokes on libJavaScriptCore.a

walk-through at Source\JavaScriptCore\CMakeFiles\JavaScriptCore.dir\link.txt
ar.exe rT  ../../lib/libJavaScriptCore.a (obj list)

At some point the resulting library gets truncated, resulting in next:
ranlib libJavaScriptCore.a: invalid archive

Simple manual work-around:
find *.obj from Source\JavaScriptCore
copy all to some temp folder
ar cr  libJavaScriptCore.a *.obj
ranlib libJavaScriptCore.a
place resulting libJavaScriptCore.a in build-x86_64-w64-mingw32-release\lib
** build continues .. **

Obviously not a real fix, just a heads up.

Building under Windows 10 cmd.exe, gcc 8.2.1, binutils 2.31.1-2

**Comment by spl1inter** [comment]
I have narrowed the problem to binutils bug in specific case updating "thin" archives (ar rT).


For mingw-w64-qtwebkit -> JavaScriptCore.dir/link.txt
ar rT ar.exe rT ../../lib/libJavaScriptCore.a (objects)  --> result truncated, library invalid
change in link.txt to:
ar r ../../lib/libJavaScriptCore.a (objects)  --> results ok, project builds

The other components archive without issue as thin archives: ANGLESupport.dir, WebCore.dir etc build without modification. Bug is isolated to JavaScriptCore.dir only.

Can anyone confirm?

**Comment by Alexpux** [comment]
Currently we use GCC-9.2.0 and binutils 2.32, but in any case it fail to build

**Comment by spl1inter** [comment]
No, it won't build under pacman. But it will build and install under cmake alone.

The central problem as I see it is is at libJavaScriptCore.a. Not only due to the problem above but due to the possibility that this may actually be significantly linked to [issue5733 ](https://github.com/msys2/MINGW-packages/issues/5734) and the two problem may actually be one or at least linked.

The error at InjectedScriptManager::InjectedScriptManager loops us back to this component. Similar issues have been reported before that's where I might start but can't promise when I will have more free time to look at it more: [ticket on webkit, led to patch in cmake build for windows](https://bugs.webkit.org/show_bug.cgi?id=150810)

**Comment by spl1inter** [comment]
As it turns out the two issues are unrelated.

To avoid the chance of this error, disable thin archives by adding CMAKE parameters to RELEASE and DEBUG sections of the PKGBUILD file: -DUSE_THIN_ARCHIVES=OFF

I am closing this issue.
