### ISSUE TITLE
Compiled Gettext Binaries are Corrupted

### ISSUE THREAD

**Issue by AntumDeluge** [msys2/MINGW-packages#5737]
I sent a [message to GNU/Gettext mailing list](https://lists.gnu.org/archive/html/bug-gettext/2019-08/msg00019.html) about my compiled Gettext binaries being corrupted. I can't seem to get past it. Compiling v0.20.1 completes, but all executables segfault. When trying to compile v0.19.8.1, it fails with a segfault when trying to execute ***help2man*** for ***gettext-runtime/src/envsubst.exe***. The error output & config.log are included in the mailing list message.

If anyone can help me figure out why my system is producing the corrupted executables/binaries, I would much appreciate it.

**Note:** I'm building 64-bit binaries/libs.

**Comment by oscarfv** [comment]
You have several directories on PATH listed before `/mingw64/bin`. Try removing those before building and *testing* gettext.

OTOH, [we have a PKGBUILD for gettext](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-gettext), although for version 0.19.8.1. It is heavily patched. Look there for ideas about how to build gettext under MSYS2.

**Comment by AntumDeluge** [comment]
The problem appears to be in building with static libs. If I build it with shared libintl, the executables work.

**Comment by MehdiChinoune** [comment]
closing since the package has been updated and we didn't get any similar bug reports since then
