### ISSUE TITLE
[grpc] mingw-w64-x86_64-grpc does not work with mingw-w64-x86_64-protobuf 3.9.0

### ISSUE THREAD

**Issue by xuchuan** [msys2/MINGW-packages#5740]
After upgrading protobuf to the latest version 3.9.0, this command failed:
protoc -I. --grpc_out=. --plugin=protoc-gen-grpc=grpc_cpp_plugin.exe myservice.proto
The reason is that grpc_cpp_plugin.exe relies on a symbol _ZN6google8protobuf19FileDescriptorProto18kSyntaxFieldNumberE exported by libprotobuf.dll, which does not exist in protobuf 3.9.0.
Downgrading protobuf to 3.8.0 resolves this issue.

**Comment by MehdiChinoune** [comment]
closing since the packages were updated and we didn't get any similar bug reports since then
