### ISSUE TITLE
gstreamer's libgstopencv.dll depends on OpenCV 4.1.0 and not 4.1.1

### ISSUE THREAD

**Issue by samerdokas** [msys2/MINGW-packages#5741]
Currently, OpenCV has already been updated to 4.1.1, while libgstopencv still contains links to DLLs with the suffix 410 rather than 411.
Effectively, this makes gstreamer and its plugins unusable with the default pacman's OpenCV installation.

**Comment by lazka** [comment]
we are now at 430 and things seem to have been rebuilt in the meantime. If this happens again just open a PR for the gstreamer package which increases the "pkgrel" field, so it gets rebuild.
