### ISSUE TITLE
linker/dll dependency issues with VTK-ITK

### ISSUE THREAD

**Issue by harshn05** [msys2/MINGW-packages#5752]
With the fully updated MSYS2-MINGW-W64 packages (as on 9:50 am Wednesday, 28 August 2019 GMT), a cmake based (c++ qt-vtk-itk) project of mine fails to compile with following error:
```
.../x86_64-w64-mingw32/bin/ld.exe: cannot find -lvtkalglib
collect2.exe: error: ld returned 1 exit status
```
It appears that the linker is trying to link the executable to vtkalglib. However, in the latest version of VTK (8.2), vtkalglib is [removed](https://fossies.org/diffs/VTK/8.1.2_vs_8.2.0/).

So I manually removed all occurrences of  "-lvtkalglib" from build.make file generated by cmake. Now the project compiles successfully but fails to execute and complains about some missing "libITK***-4.13.dll" and "libVTK***-8.1*.dll". Looks like a muddled case of "dll dependencies". Possibly ITK needs to be updated (4.13->5.0.1), rebuilt, properly linked against the latest VTK-8.2 and updated in the msys2 repository.

**Comment by harshn05** [comment]
Issue can be fixed by rebuilding the latest ITK-5.0.1 against the latest VTK-8.2 available in the repository. I have tested this on my local PC. Just two following changes in the [PKGBUILD](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-itk/PKGBUILD)  are needed. 
```
pkgver=5.0.1
sha256sums=('c6b3c33ecc73104c906e0e1a1bfaa41a09af24bf53a4ec5e5c265d7e82bdf69f')
```
Here is the [ITK-5.0.1 package](https://www.dropbox.com/s/dqkw0tb8ti2qvt7/mingw-w64-x86_64-itk-5.0.1-1-any.pkg.tar.xz?dl=1) which I built on my local PC and can be installed by `pacman -U mingw-w64-x86_64-itk-5.0.1-1-any.pkg.tar.xz`. It may be useful until ITK is updated to the latest version in the repo.

**Comment by MehdiChinoune** [comment]
likely fixed, ITK was updates

**Comment by DISAPPEARED13** [comment]
but what's the name of  the dependency for `vtkalglib` is replaced in newer version of VTK? like 8.2

**Comment by MehdiChinoune** [comment]
> but what's the name of the dependency for `vtkalglib` is replaced in newer version of VTK? like 8.2

I don't understand your question?
Did ITK stop working for you after latest update to 9.3.0

**Comment by DISAPPEARED13** [comment]
> > but what's the name of the dependency for `vtkalglib` is replaced in newer version of VTK? like 8.2
> 
> I don't understand your question? Did ITK stop working for you after latest update to 9.3.0

Hi there. 
I didn't use the latest version of VTK, for our software just need to upgrade from 8.0 to 8.2. With upgrading vtk by replacing the lib and bin in settings I found that `vtkalgli `, `vtkexollc`, `vtknetcdf_c++` and `vtkproj4` is not avaliable in the cmaked VTK8.2.

**Comment by MehdiChinoune** [comment]
Sorry, We have only 9.3.0
