### ISSUE TITLE
Support repo-remove in ci-library.sh

### ISSUE THREAD

**Issue by jeroen** [msys2/MINGW-packages#5756]
I'm running a small fork of msys2 with some customize packages and have a small feature request for the CI code for @renatosilva or @fracting.

Currently [ci-library.sh](https://github.com/msys2/MINGW-packages/blob/master/ci-library.sh) automatically adds new packages to the repository (via `repo-add`):

https://github.com/msys2/MINGW-packages/blob/70c38d948750d769e28c64090e6add99cfe2baca/ci-library.sh#L160-L165

However when a `PKGBUILD` is removed from the git repo, it does not get removed from the pacman repository. Would it be possible to run [`repo-remove`](https://www.archlinux.org/pacman/repo-add.8.html) when a package is removed on Github?

**Comment by lazka** [comment]
I think the problem here is that we need to run the PKGBUILD through makepkg to figure out which packages it produces. And at this point we don't have the PKGBUILD anymore. Or am I missing something?

**Comment by jeroen** [comment]
I think you can look at the PKGBUILD before the commit that removed it (if you fetch at least with depth 2).
