### ISSUE TITLE
nlopt python 3 module

### ISSUE THREAD

**Issue by victorliu** [msys2/MINGW-packages#5764]
The nlopt package includes a python 2 module, which has been very helpful. However, I'm interested in switching over to python 3, and I'm wondering if it's possible to also include a python 3 module as part of the package.

**Comment by lazka** [comment]
Do you need both, or is replacing the Python 2 version with a Python 3 version ok?

**Comment by victorliu** [comment]
Personally, I'm fine with replacing it, but I know there are people using the python 2 module currently. Ideally, the python version could be auto-detected and appropriate versions for each python environment would be installed.

**Comment by lazka** [comment]
We've dropped support for Python 2 and nlopt now contains a Python 3 module.
