### ISSUE TITLE
gdb in mingw64/mingw-w64-x86_64-gdb does not print string or stl types in a pretty way

### ISSUE THREAD

**Issue by bayramboyraz** [msys2/MINGW-packages#5765]
gdb in mingw64/mingw-w64-x86_64-gdb does not print string or stl types in a pretty way, although it requires python3 to be installed. Whereas gdb in msys/x86_64/gdb prints these types in a pretty way.

(gdb) b main
Breakpoint 1 at 0x40157a: file listfiles.cpp, line 7.
(gdb) r
Starting program: C:\msys64\home\User\Dev\a.exe

Breakpoint 1, main (argc=1, argv=0x6d2230) at listfiles.cpp:7
7               **std::string text("hello world");**
(gdb) n
9               std::cout << text << '\n';
(gdb) p text
**$1 = {static npos = 18446744073709551615,
  _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x22fe20 "hello world"},
  _M_string_length = 11, {_M_local_buf = "hello world\000\000\000\000",
    _M_allocated_capacity = 8031924123371070824}}**
(gdb)

**Comment by bayramboyraz** [comment]
I could resolve the issue. 

gdbinit file in mingw64 is erroneous. path: C:\msys64\mingw64\etc\gdbinit (I have installed msys2 under C:\msys64)

I could see that gdb under msys has pretty printing support but not the one under mingw, so after some research I learned that some settings should be done in gdbinit files. So I have searched for "gdbinit" files under msys64 installation. I could find 2, one belongs to msys the other belongs to mingw. When I compared both of the files I noticed that one line is missing in the mingw one. I am not sure if it is done intentionally or not.

Here is how the content should be:
the line with bold font was the missing line:

python
import sys
sys.path.insert(0, sys.path[0] + '/../../gcc-9.2.0/python')
from libstdcxx.v6.printers import register_libstdcxx_printers
**register_libstdcxx_printers (None)**
end

**Comment by eacheveryhour** [comment]
> 
> 
> I could resolve the issue.
> 
> gdbinit file in mingw64 is erroneous. path: C:\msys64\mingw64\etc\gdbinit (I have installed msys2 under C:\msys64)
> 
> I could see that gdb under msys has pretty printing support but not the one under mingw, so after some research I learned that some settings should be done in gdbinit files. So I have searched for "gdbinit" files under msys64 installation. I could find 2, one belongs to msys the other belongs to mingw. When I compared both of the files I noticed that one line is missing in the mingw one. I am not sure if it is done intentionally or not.
> 
> Here is how the content should be:
> the line with bold font was the missing line:
> 
> python
> import sys
> sys.path.insert(0, sys.path[0] + '/../../gcc-9.2.0/python')
> from libstdcxx.v6.printers import register_libstdcxx_printers
> **register_libstdcxx_printers (None)**
> end

Lifesaver. Thanks.

**Comment by chadkennedyonline** [comment]
Fix proposed in PR #6351
