### ISSUE TITLE
mingw-w64-x86_64-gcc not installing current version

### ISSUE THREAD

**Issue by HBI-TV-Dev** [msys2/MINGW-packages#5780]
After a fresh install of MSYS2, running pacman -Syu until no more updates are installed, when I install mingw-w64-x86_64-gcc ( pacman -S mingw-w64-x86_64-gcc ), pacman shows that mingw-w64-x86_64-gcc-8.3.0-2 is going to be installed instead of mingw-w64-x86_64-gcc-9.2.0-2.

I can't seem to get pacman to install the current version (9.2.0), it always wants to install 8.3.

Any ideas what is causing this?

**Comment by StarWolf3000** [comment]
Do a `$ pacman -Syyuu` and then try again.

**Comment by HBI-TV-Dev** [comment]
Thanks for the info! That seemed to do the trick and it is now showing it will install v9.2 instead of v8.3.
