### ISSUE TITLE
mingw-w64-opencv missing dependencies

### ISSUE THREAD

**Issue by kanonet** [msys2/MINGW-packages#5788]
Hi,

mingw-w64-opencv is build including opencv-contrib, which in turn includes several other dependencies. Those are listed in PKGBUILD as makedepends but not as (runtime) depends. I am talking about:
mingw-w64-x86_64-tesseract-ocr
mingw-w64-x86_64-glog
mingw-w64-x86_64-hdf5
mingw-w64-x86_64-ogre3d
mingw-w64-x86_64-ceres-solver
mingw-w64-x86_64-gflags
Because of those missing dependencies it is impossible to use opencv with python, unless you install them manually.

There are several possible ways to fix this:
1. Simply add those depends to the package. Its easy but ugly since it requires the user to install over 500mb of packages that are probably never used.
2. Leave the package as it is, but static link all required external libs
3. Split the package in two: opencv (C api with contrib) and opencv-python (without contrib).
4. Split the package in two: opencv (C+Python without contrib) and opencv-contrib (C+python)
5. Combine points 3 + 4 to split the package in 4: opencv, opencv-contrib, opencv-python, opencv-python-contrib

@Alexpux please make a decision which approach you would like. Maybe I can help to implement it, if you dont have time to do it.

Also a suggestion: I think OpenCV should be build with "BUILD_EXAMPLES=OFF" since we do not need those examples in the package.

**Comment by kanonet** [comment]
Please give me an answer, if you think this should be fixed (I think so) and which kind of fix you like the most.

Also note on latest OpenCV release (4.1.2-1): CMake does not properly find OpenCV anymore. This needs a fix too.

**Comment by Alexpux** [comment]
@kanonet need move then packages to depends. I'm prefer to not split MINGW packages because it more easy to maintain them for me. So only available option is first. Static linking is also out of our interests

**Comment by Alexpux** [comment]
Fixed by https://github.com/msys2/MINGW-packages/commit/c68bb2dab187474498e86f3e4e44f946013e24db

**Comment by oscarfv** [comment]
@kanonet : after you check that the poblem is fixed, please close this issue. Thanks.

**Comment by kanonet** [comment]
Fixed (even thou I would have preferred package splitting). Thank you!
