### ISSUE TITLE
Add vera++ package

### ISSUE THREAD

**Issue by ofry** [msys2/MINGW-packages#5804]
Project URL: https://bitbucket.org/verateam/vera/src/master/

Could it be done with minimal source code patching? Or some dependencies didn't ported at all yet?

**Comment by oscarfv** [comment]
You can submit a PKGBUILD as a pull request. Use some other CMake-based PKGBUILD or adapt [the existing Arch PKBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vera%2B%2B).

Vera++ only depends on CMake, boost and Tcl (plus Pandoc to build). No problem there.

**Comment by ofry** [comment]
@oscarfv Latest master doesn't build in MSYS2/MinGW without patches. See https://bitbucket.org/verateam/vera/issues/105/add-msys2-mingw-support-for-windows

**Comment by oscarfv** [comment]
Then include the patches on your pull request.

**Comment by ofry** [comment]
@oscarfv Could you review it? #5853

**Comment by oscarfv** [comment]
Looks good. I requested a trivial change.

There is no need for a new pull request, just amend the commit locally and used git push -force.

Thanks.

**Comment by oscarfv** [comment]
Also, don't use the commit message for saying things like "please review". The commit message must describe what the change is about. On this case I suggest:

```
vera++: new package
```

**Comment by ofry** [comment]
PR #5853 merged now. When this package will come to pacman MinGW repository?

**Comment by Alexpux** [comment]
@ofry never ask about this because this is free time project

**Comment by ofry** [comment]
@Alexpux Sorry, I thought it manages by buildbot.

Thank you for add this package to repository.
