### ISSUE TITLE
mingw-w64-x86_64-devhelp not found

### ISSUE THREAD

**Issue by liberforce** [msys2/MINGW-packages#5805]
It seems the package is no more available. Does anyone (@lazka ?) know the reason behind it? Is that fixable?

**Comment by lazka** [comment]
See #5372

**Comment by liberforce** [comment]
Thanks. Why is webkit-gtk dropped in the first place? Is that a problem with upstream, or the lack of human resources on the MSYS2 side to maintain the package?

**Comment by lazka** [comment]
upstream doesn't support Windows anymore and maintaining a browser engine isn't easy

**Comment by liberforce** [comment]
Indeed. Thanks for your responsiveness.
