### ISSUE TITLE
How to build Notepad++ on here

### ISSUE THREAD

**Issue by abdulbadii** [msys2/MINGW-packages#5809]
How to build Notepad++ on mingw64 ? What I know/could do only that I should have and now having:

- Boost package https://www.boost.org/users/history/version_1_70_0.html
- Notepad++ source https://github.com/notepad-plus-plus/notepad-plus-plus.git
- nmake

how to transform / transpile the build automation into mingw64 with its cmake instead?

**Comment by oscarfv** [comment]
There is a `PowerEditor/gcc` directory on Notepad++ sources with a makefile that hints that MinGW is/was supported. Try it. If you have difficulties, ask on the Notepad++ forums. If you don't know how to use a makefile, search the web for tutorials and/or ask for guidance on some forum for beginners on the C language.

Please close this bug report. Thanks.
