### ISSUE TITLE
gst-plugins-bad camerabin 'start-capture' signal freezes program

### ISSUE THREAD

**Issue by tjwilli58** [msys2/MINGW-packages#5816]
I'm trying to use gstreamer in a python program I have. I have eveything running fine using python3.4 and pygbject/gstreamer installed using [PyGObject for Windows](https://sourceforge.net/projects/pygobjectwin32/). The problem with this is I'd like to update to a newer python (from 3.4) and gstreamer (from 1.12)

I installed msys2 (x86_64) along with all the packages I needed  for gstreamer. My program works just fine, in that I can connect to a camera and set the state to PLAYING. The problem comes when I try to capture the video using camerabin. As soon as I emit the 'start-capture' signal from my pipeline, my program locks up. I have to kill the python process.

Is there a way for me to install "mingw-w64-x86_64-gstreamer 1.14", etc to see if this helps?
I don't know if this is a gstreamer version issue or something else.

Thanks.

**Comment by tjwilli58** [comment]
I just found [http://repo.msys2.org/mingw/x86_64/](http://repo.msys2.org/mingw/x86_64/).
I'll try and install the 1.14 packages and see what happens.

**Comment by tjwilli58** [comment]
Same result.

**Comment by tjwilli58** [comment]
Works with 1.12. I had to change `elem.get_description() `to `elem.get_metadata('description')` in my python code, but I could still grab some frames.

**Comment by lazka** [comment]
Please file a bug with gstreamer: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues

**Comment by tjwilli58** [comment]
Will do. Thanks

**Comment by tjwilli58** [comment]
Filed bug with gstreamer
