### ISSUE TITLE
Update lcov to 1.14-2 or later

### ISSUE THREAD

**Issue by droidmonkey** [msys2/MINGW-packages#5819]
lcov 1.14-1 and below is incompatible with gcc 9.x. Please update the lcov package to the -2 version. See here for more details: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=924573

**Comment by lazka** [comment]
There is no lcov release newer than 1.14

**Comment by droidmonkey** [comment]
Notice the -2. MSys2 currently has the -1 variant which does not include this fix. Lcov has terrible version numbering

**Comment by lazka** [comment]
Can you give a link to the release, I only see 1.14 at https://github.com/linux-test-project/lcov/releases

**Comment by droidmonkey** [comment]
As discussed in the debian bug report, this is based on a commit that added the functionality. I have no idea when they are going to push out 1.15. Here is the commit that adds the feature: https://github.com/linux-test-project/lcov/commit/75fbae1cfc5027f818a0bb865bf6f96fab3202da

**Comment by lazka** [comment]
We can consider updating once a new release is out.

**Comment by droidmonkey** [comment]
Right now you might as well remove lcov because it is totally incompatible with the gcc version you are shipping. Just my 2 cents.
