### ISSUE TITLE
Bullet physics has significantly worse performance than when built from source

### ISSUE THREAD

**Issue by 20k** [msys2/MINGW-packages#5821]
Hi there! I've noticed that the bullet physics version in the package manager has significantly worse performance than one built from source. I'm not familiar with how packages work on here otherwise I'd have a look myself, though if I had to guess I'd guess it were this https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-bullet/workaround-mingw-gcc6-bug.patch because it seems to mess with optimisation settings

Bullet on my end was built with 

cmake -G "Unix Makefiles" -DBUILD_PYBULLET=OFF -DBUILD_PYBULLET_NUMPY=OFF -DUSE_DOUBLE_PRECISION=OFF -DBULLET2_MULTITHREADING=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_BULLET2_DEMOS=OFF -DBUILD_CPU_DEMOS=OFF -DBUILD_OPENGL3_DEMOS=OFF -DBUILD_ENET=OFF -DUSE_GRAPHICAL_BENCHMARK=OFF -DBUILD_UNIT_TESTS=OFF ../

With ~1000 rigidbodies, bullet from pacman rapidly hits 180ms/frame of execution time. With bullet built from source, bullet takes < 8ms/frame of execution time (which is gpu execution time in my test app), which is a massive difference. These are identical starting conditions, the only difference is where bullet came from

This has been a problem for at least a year so it would be great to see it fixed!

Windows 10, i5 3570k, r9 390, everything up to date, using mingw64 with no modifications

If you need any more information or you need a test application for this, let me know

**Comment by oscarfv** [comment]
The condition and the comment look contradictory on that patch.

Try building the package after removing that patch. See this page for instructions about modifying PKGBUILD and building packages:

https://github.com/msys2/msys2/wiki/Creating-Packages

**Comment by 20k** [comment]
Ok, I navigated the pkgbuild process and can confirm that that gcc6 patch is the one that introduces the performance issue

Just to check I didn't do anything insane: I checked out this repo, built the package once with default settings and tested the produced headers + libs + dlls locally (slow), then changed line 40 of PKGBUILD to read   #patch -p1 -i ${srcdir}/workaround-mingw-gcc6-bug.patch, rebuilt, rebuilt the project with the headers/etc, and then tested again (fast). I definitely used the release build for both, under ./pkg/mingw-w64-x86_64-bullet

Removing that patch also shrinks binary size by quite a bit (50% for some dlls), so it would seem that its not being built with any optimisations at all

**Comment by oscarfv** [comment]
Thanks. Now you can submit a pull request that removes the patch or wait until the maintainer notices this Issue and fixes the package himself.

**Comment by 20k** [comment]
Thanks for all the help with this issue by the way

I'm happy to submit a PR to help move things along (this bug does affect me so it'd definitely be nice for it to get fixed), but I'm unsure what exact form this should take

So: 

1. What's the support for older compilers? Is it appropriate to simply delete this patch, or should it be modified to only target gcc 6.1 to work around whatever bug was presumably affecting bullet?

2. Are there any tests for what this patch is meant to fix to check that whatever it fixes isn't still an issue on later compilers? As far as I can tell, the closest match to what might be the issue is https://sourceforge.net/p/mingw-w64/discussion/723797/thread/2580ff9b/ this bug report which matches all the constraints (gcc 6.1, stops compilation, -O0 is the fix, so given that it compiles without the patch *this* bug is fixed) - but as far as I can tell there is no documentation on why this specific patch is here or if they're really the same issue

**Comment by oscarfv** [comment]
1. Old compilers are irrelevant here.

2. Sadly, it is common on this project adding patches without a mention of their purpose.

So just go ahead and remove the patch.

**Comment by 20k** [comment]
The pull request went through so I'm going to close this issue as fixed. Thanks everyone!
