### ISSUE TITLE
libogg links to wrong dll name (ogg.dll)

### ISSUE THREAD

**Issue by sluicebox** [msys2/MINGW-packages#5825]
The current libogg package links executables to the wrong dll name, preventing them from running.

This was introduced one month ago when the libogg package was upgraded from 1.3.3 to 1.3.4: 581fd214f2ccc036e5eaafea202b92bc2b711864

The correct libogg dll is "libogg-0.dll" but the new package links executables to "ogg.dll", which does not exist. libogg.dll.a contained the correct name in 1.3.3 but not in 1.3.4.

This occurs in i686 and x86_64 packages.

**Comment by Alexpux** [comment]
@sluicebox fixed by https://github.com/msys2/MINGW-packages/commit/5396fc432cc4ab594a715d956e64f105fbd5745b
