### ISSUE TITLE
LLVM/Clang 9 is out

### ISSUE THREAD

**Issue by oscarfv** [msys2/MINGW-packages#5843]
Any reason why it is not pacakeg yet? Is there a problem with the new version?

**Comment by Alexpux** [comment]
I don’t have time

**Comment by Alexpux** [comment]
@oscarfv also I dont see relese archives on github: https://github.com/llvm/llvm-project/releases

Building from git tag is not what i want to do with clang

**Comment by mati865** [comment]
Official releases are here: https://releases.llvm.org/download.html#9.0.0

**Comment by oscarfv** [comment]
Ok, thanks @Alexpux .

I see that we have plenty of backported patches that now are candidates for removal. I'll take a look later if nobody beats me to it.

**Comment by oscarfv** [comment]
WIP https://github.com/oscarfv/MINGW-packages (clang8 branch).

The build does not complete yet. I need to learn some tricks for not having to launch a build from scratch (~50 minutes to the point where currently fails) for every little change. Any pointers to documentation appreciated.

**Comment by mati865** [comment]
@oscarfv if you run makepkg with `-e` or `--noextract` it will not extract sources or run prepare.

You can also reuse build tree by replacing this:
https://github.com/msys2/MINGW-packages/blob/44e66c3a332dc457f00b9a12d3efbb7be5dba66e/mingw-w64-clang/PKGBUILD#L272-L273
with:
```
mkdir -p build-${CARCH} && cd build-${CARCH} 
```
But it can cause issues when you mess up build system.

**Comment by oscarfv** [comment]
Thanks @mati865 , that was a big time-saver.

The beast builds now. I want to study the changes required by a few patches but otherwise looks like it will be ready this week.

The packages were defective, seems that #5334 is still a thing here. This makes testing quite inconvenient.

**Comment by oscarfv** [comment]
Submitted PR #5854. So far I was unable to test the binaries because, as mentioned on the previous message, the packages are defective due to #5334.

i686 build is underway locally.

**Comment by Alexpux** [comment]
@oscarfv I get error during configure:
````
CMake Error at tools/lldb/docs/CMakeLists.txt:32 (get_target_property):
  get_target_property() called with non-existent target "swig_wrapper".

````

**Comment by oscarfv** [comment]
Apparently you have epydoc installed. There is a bug on LLDB's CMake scripts: the target `swig_wrapper` is defined only when the project is configured with `-DLLDB_DISABLE_PYTHON=OFF` and we set it to `ON`. Then on `tools/lldb/docs/CMakeLists.txt` the target is referenced depending on the presence of epydoc alone, ignoring the value of `LLDB_DISABLE_PYTHON`.

I'll submit a PR later.

**Comment by oscarfv** [comment]
The PR was merged. Closing.
