### ISSUE TITLE
nodejs cannot be installed any more

### ISSUE THREAD

**Issue by omichel** [msys2/MINGW-packages#5848]
I cannot install nodejs any more:
```
$ pacman -Syuu mingw-w64-x86_64-nodejs
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
error: target not found: mingw-w64-x86_64-nodejs
```
What is the problem?

**Comment by omichel** [comment]
I still have it installed on my system, so it appears as a foreign package (typically manually downloaded and installed or packages removed from the repositories), whereas I installed it the day before yesterday with `pacman -Syuu mingw-w64-x86_64-nodejs` and it worked. Today, I get this:

```
$ pacman -Qm
mingw-w64-x86_64-nodejs 8.11.1-7
```

**Comment by Alexpux** [comment]
nodejs is very outdated and don’t have maintained, so I decide to remove nodejs and packages that depends on it from repo.

**Comment by omichel** [comment]
OK, thank you for the quick reply. We will have to find a workaround then.

**Comment by sbeckstead** [comment]
Node.js may be outdated but it is still required in packages that I don't want to have to re-engineer just to use.  Thanks for the errors.

**Comment by raxetul** [comment]
> 
> 
> nodejs is very outdated and don’t have maintained, so I decide to remove nodejs and packages that depends on it from repo.

Sorry, but there is a huge difference between "I decide to" and "We decided to". MSYS2 is a home for developers and decisions are better to be done in a discussed and common way.

**Comment by tolstenko** [comment]
Hey, just to bump. The decision on not supporting nodejs is final?

**Comment by Biswa96** [comment]
It is not buildable with mingw toolchain for many years. If anyone can build nodejs package it will be always welcomed. Checkout this previous work https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-nodejs

**Comment by tolstenko** [comment]
Thanks for the explanation! @Biswa96

**Comment by henrik-jensen** [comment]
@Biswa96 wrote:
> It is not buildable with mingw toolchain for many years. If anyone can build nodejs package it will be always welcomed. Checkout this previous work https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-nodejs

The link you are referring to is dead.

Wonder if it's possible for you to restore/find the original/intended link?
 
4 latest commits I found concerning nodejs was these:
By @lazka - 4 Feb 2022 [Remove nodejs/npm/yarn](https://github.com/msys2/MINGW-packages/commit/1fbf09be91365992e935252e72d31b456ec1c614)
By @Alexpux - 30 Jun 2019 [nodejs: Update patch to use separate response file for every target](https://github.com/msys2/MINGW-packages/commit/f77267c45e4ab5aaa340f4b591ed84739466345a)
By @Alexpux - 30 Jun 2019 [nodejs: Try to use response files for linking](https://github.com/msys2/MINGW-packages/commit/550b960af3b3995a82ca8b07e83a2e7651e25540)
By @Alexpux - 29 Jun 2019 [nodejs: Verbose build](https://github.com/msys2/MINGW-packages/commit/753f1581e047895d09acf10b47597746f9f981e3)

**Comment by francogrex** [comment]
> nodejs is very outdated and don’t have maintained, so I decide to remove nodejs and packages that depends on it from repo.

Did you take notice of how many thumbs down you statement has generated?

**Comment by Biswa96** [comment]
> Did you take notice of how many thumbs down you statement has generated?

Did you take notice that nodejs was re-added in the MINGW package repository? See this link https://packages.msys2.org/base/mingw-w64-nodejs
