### ISSUE TITLE
[opencv] opencv (4.1.1) dnn module fails to load libprotobuf.dll (3.10.0) 

### ISSUE THREAD

**Issue by isra60** [msys2/MINGW-packages#5849]
Packages are

mingw-w64-x86_64-opencv 4.1.1-1
mingw-w64-x86_64-protobuf 3.10.0-1 

The program says ...

The procedure entry point

_ZN6google8protobuf11MessageLite16ParseFromIstreamEPNSi 

could not be located in the dynamic library libopencv_dnn411.dll

Based on dependency walker these are the only functions are broken...

**Comment by Alexpux** [comment]
Fixed by https://github.com/msys2/MINGW-packages/commit/69af003db227937566066149e29d427bdfc78575
