### ISSUE TITLE
Readline update error(?)

### ISSUE THREAD

**Issue by BrisingrAerowing** [msys2/MINGW-packages#5856]
Should [these lines](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-readline/PKGBUILD#L38-L41) be uncommented as you now have a patch to apply with them? This seems like an oversight to me.

**Comment by Alexpux** [comment]
Fixed by https://github.com/msys2/MINGW-packages/commit/91ffbcef8e2123508d5aabda1ffd0349fde3b1e2
