### ISSUE TITLE
Missing VAPI in mingw-w64-x86_64-jsonrpc-glib package

### ISSUE THREAD

**Issue by philippejer** [msys2/MINGW-packages#5860]
I think there is a small issue with this package: it is missing the artefact `jsonrpc-glib-1.0.vapi` (see for reference: https://www.archlinux.org/packages/extra/x86_64/jsonrpc-glib/files/)

I'm not familiar enough with the build system to fix this for sure myself...
It might be the flag: `-Dwith_introspection=false`

The impact is that Vala applications cannot be built against this library currently under MSYS2:
```
Compilation failed: 1 error(s), 0 warning(s)
error: Package `jsonrpc-glib-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
```

**Comment by lazka** [comment]
Fixed in master: eea549253de2d9d

**Comment by lazka** [comment]
And now in the repo

**Comment by philippejer** [comment]
Works perfectly, thanks!
