### ISSUE TITLE
Package request: ANGLE

### ISSUE THREAD

**Issue by DonKichot** [msys2/MINGW-packages#5870]
Project URL:<https://chromium.googlesource.com/angle/angle>
Is it possible to easily convert it from their GN (<https://gn.googlesource.com/gn>) to CMake?

**Comment by mati865** [comment]
It was removed in https://github.com/msys2/MINGW-packages/commit/55de803278c97ac0d19253c2edefdf397cc18342 probably because there are no releases available.

**Comment by DonKichot** [comment]
@mati865:
What do you mean by "no releases available"? You can also look at: [https://github.com/google/angle](url) and there clearly are new commits.

**Comment by Alexpux** [comment]
@DonKichot it was removed because I dont want to learn GN build system

**Comment by DonKichot** [comment]
@Alexpux:
That is understandable. From my perspective GN seems to favor llvm over gcc.
Did you mange to compile it with gcc toolchain on Linux?

**Comment by Alexpux** [comment]
@DonKichot I dont build packages on Linux at all

**Comment by DonKichot** [comment]
@Alexpux:
I understand that. I just wanted to convert the project to CMake and gcc so it would be easier to compile it via MSYS2 - i think. However, I just could not compile it on Linux successfully.

**Comment by oscarfv** [comment]
@DonKichot : you can require clang as a build requisite for a package. As long as the resulting binary works, it doesn't matter which compiler was used.

Converting the project to CMake is something that should be implemented within the upstream project. You should talk to them about it.

BTW, for MSYS2 the build tool is also indifferent. As long as you provide a working PKGBUILD and take care of maintenance, I don't think that Alexpux would object.

**Comment by DonKichot** [comment]
I maned to compile the library with the provided clang++: [https://gist.github.com/DonKichot/68e7ec761fa349d9e159cc06de1f2d69](url)
However, I could not achieve positive results with g++ 5.4 on Ubuntu 16.04: [https://gist.github.com/DonKichot/e70089cf3b9f2caaf11fe1338d5b801d](url)
Any ideas why is that happening?

**Comment by oscarfv** [comment]
@DonKichot : I don't think this is the correct place for discussing build issues on an environment that is not MSYS2/Mingw-w64.

**Comment by ZachBacon** [comment]
So I found a set of cmake files that work, but against mingw-w64 it'll compile to a certain point using latest angle, that's mainly because angle now requires d3d12, something that's not yet in mingw-w64. So for to include angle, you'd need an old copy, or wait for mingw-w64 to generate new d3d headers for d3d12

**Comment by Biswa96** [comment]
@ZachBacon Do you have a custom pkgbuild file to compile this package?

**Comment by ZachBacon** [comment]
> @ZachBacon Do you have a custom pkgbuild file to compile this package?

I do not, at the time I was just testing a dry run of the compile, and then I kinda gave up a bit and then built a new PC etc. That stuff I don't have anymore.

**Comment by Biswa96** [comment]
I found a repository to cross compile angleproject in ArchLinux here https://github.com/Martchus/PKGBUILDs/tree/master/angleproject/mingw-w64. I can not make the package in ArchLinux due to permission issue. Maybe the pkgbuild is not correct. Also the dependencies (google-cloud-sdk) are too big to be ported in msys2/mingw packages.

**Comment by ZachBacon** [comment]
even more recent arch cross compile angle https://github.com/gk7huki/mingw-w64-angleproject still makes use of gyp and what not, I'm investigating a bit, but seems msys2's gyp might have some issues with tabulation and spaces that python seems to be complaining about regarding generators.

**Comment by ImperatorS79** [comment]
I have managed to create a PKGBUILD that build ANGLE, using https://github.com/gk7huki/mingw-w64-angleproject. The builded branch is 2 years old though. 

I looked into newer ANGLE and you have to use Google's depot_tools which, on windows, will clone a lot of third-party repositories and build them before even building angle (for example: libpng, libjpeg-turbo, vulkan-headers/loaders, spirv-tools/cross, etc). Maybe it is possible to analyse the generated ninja files to create a CMakeList.txt from them such that one does not have to build all those deps.

Should I still upload my PKGBUILD ?

**Comment by brechtsanders** [comment]
MinGW-w64 8.0.0 comes with `d3d12.h`.
I have a personal build of GCC 10.2.0 against MinGW-w64 8.0.0 available at http://winlibs.com/
I'm also looking for a way to get angle to compile, but I just can't seem to get it configure properly with `gn`. Any pointers on how it should be done?
I have `gn` and `ninja` as well as the http://winlibs.com/ MinGW-w64 build available from my MSYS2 shell, as well as all the prerequisites which I built from source using the same environment (including vulkan-loader).

**Comment by lb90** [comment]
I can give it a try, but cannot make any promise. I think the best way forward is to simply use their build system, GN. Will have to look how to make it use dependencies from the system rather than in-tree checkouts.

**Comment by lb90** [comment]
GN is "unstable", meaning that it can make breaking changes at any time (though the official docs says that it's pretty stable in practice, breaking changes should happen very rarely). As such I'm not sure if it's worth having a standalone package for gn. Or well, at least it's better to use a precise version to build angle. Anyone has a preference in that regard?

See https://gn.googlesource.com/gn/

**Comment by Biswa96** [comment]
It can be possible to make GN as a git package like this https://archlinux.org/packages/extra/x86_64/gn/. Separate package will always be better, IMO.

**Comment by naveen521kk** [comment]
> GN is "unstable", i.e. it can make breaking changes at any time (though they say that's a rarity in practice), so I'm not sure if it's worth having a standalone package for GN. Anyone has a preference in that regard?

It was previously discussed https://github.com/msys2/MINGW-packages/pull/6792. Also, recently when playing with skia I just build gn in the PKGBUILD of skia itself, since it requires a specific version of gn so that it can be built. See https://github.com/msys2/MINGW-packages/pull/10195

**Comment by naveen521kk** [comment]
@lb90 (since you were gonna give it a try), I have made some recipes a few days back for this https://github.com/naveen521kk/MINGW-packages/tree/angle-new-package/mingw-w64-angleproject. Many of the patches there are for gn and chromium build (which is from the v8 package), but not exactly for angle itself. I mainly did the because @ZachBacon was discussing it Discord, and seemed I can help. I hope that helps you!

**Comment by lb90** [comment]
That's great. Thank you very much!

**Comment by J1Man** [comment]
Hi guys.  Thanks for trying to create a MSYS2 package for Angle.  Is there any progress?

Angle package in MSYS2 will be extremely useful for other projects.  For example, we can enable OpenGL support in MSYS2 windows build of QEMU with angle.  Angle requirement was mentioned in the QEMU OpenGL support request issue that I linked below. 
https://github.com/msys2/MINGW-packages/issues/8506

**Comment by brechtsanders** [comment]
Is there any proper instruction on how to use `gn` under MSYS2 with GCC?

**Comment by naveen521kk** [comment]
> Is there any proper instruction on how to use gn under MSYS2 with GCC?

Dunno if there's any, but you can look at the build scripts for [skia](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-skia/PKGBUILD) and [v8](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-v8/PKGBUILD).

**Comment by lb90** [comment]
@Biswa96 Regarding the Wine D3D headers / IDLs, there's this interesting project by Microsoft: https://github.com/microsoft/DirectX-Headers. Would it make sense to update the IDLs in Wine with those?

**Comment by Biswa96** [comment]
[mingw-w64-angleproject][1] package is available now. It was added in this [commit][2]. The package can be installed with `pacman -S $MINGW_PACKAGE_PREFIX-angleproject` command. Huge thanks to raedrizqie.

[1]: https://packages.msys2.org/base/mingw-w64-angleproject
[2]: https://github.com/msys2/MINGW-packages/commit/b8d0f27c9f85cefad37cdf25e98b94058a01f7ae
