### ISSUE TITLE
`mingw-w64-x86_64-ca-certificates-20180409-3` update broke curl

### ISSUE THREAD

**Issue by mati865** [msys2/MINGW-packages#5887]
cc @Alexpux
The error:
```
$ curl https://rust-lang-ci-mirrors.s3-us-west-1.amazonaws.com/rustc/2017-03-15-ninja-win.zip -o t.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by lazka** [comment]
hm :/ I've used meld to check that it didn't change anything, weird..

**Comment by lazka** [comment]
I get the same output for both locally, but the one in the repo has a different content for some reason

**Comment by Alexpux** [comment]
I see this error about 2-3 months with Msys CURL, so I think something with internet provider chain or need update certificates itself

**Comment by Alexpux** [comment]
Error is passing on 2-3 try mostly.

**Comment by lazka** [comment]
I've pushed a potential fix to master

**Comment by mati865** [comment]
> I see this error about 2-3 months with Msys CURL, so I think something with internet provider chain or need update certificates itself

It worked fine with `mingw-w64-x86_64-ca-certificates-20180409-1` and started with revision 3.

**Comment by lazka** [comment]
sadly still the same with rev4, I've created a revert PR: #5890

**Comment by mati865** [comment]
@lazka comparison of rev 4 and rev a packages: https://www.diffchecker.com/XPDSUSpy
Encoding actually has been fixed when compared to python2 build: `FĹ‘tanĂşsĂ­tvĂˇny` -> `Főtanúsítvány` but 3 public keys disappeared.

**Comment by lazka** [comment]
ok, found the likely problem. certdata2pem calls openssl without checking for errors and openssl can't handle unicode filenames.

**Comment by lazka** [comment]
I've pushed something to master

**Comment by dscho** [comment]
> I've pushed something to master

@lazka thank you for your hard work!

**Comment by zufuliu** [comment]
mingw-w64-x86_64-ca-certificates-20180409-4 not fix the bug. 
fortunately `http.sslbackend=schannel` can be used for git.

**Comment by lazka** [comment]
"-5" looks good to me now, can anyone confirm?

**Comment by mati865** [comment]
Indeed it's fixed.
Thank you everyone working on this.

**Comment by lazka** [comment]
Thanks for testing, and sorry for the troubles.
