### ISSUE TITLE
mingw-w64-x86_64-python3-h5py and mingw-w64-python3-scipy are built for Python 3.7 instead of 3.8

### ISSUE THREAD

**Issue by pablob127** [msys2/MINGW-packages#5897]
I have a Python script I want to run under MSYS2 with MINGW, and I have ran into problems since it uses (among other modules) h5py and scipy. All the other modules are compiled for Python 3.8, except for those two that are compiled (and installed for) Python 3.7.

Steps to reproduce:

```
$ pacman -S mingw-w64-x86_64-python3-h5py mingw-w64-python3-scipy
$ python -c "import h5py" 
$ python -c "import scipy"
```
Result:

```
Traceback (most recent call last):
  File "<string>", line 1m in <module>
ModuleNotFoundError: No module named 'h5py'
```
Expected result:
The module should be imported.

I'm guessing a recompilation with the new Python 3.8 should help, but this is the first time I have ever installed MSYS2 and I have no idea how to install a package (I do not have experience with Arch Linux' build system).

Thanks!

**Comment by lazka** [comment]
We are currently rebuilding for Python 3.8, it might take a few days until all packages are complete.

**Comment by pablob127** [comment]
Thanks for the update!

I'm sorry about my ignorance, but I just found MSYS2 yesterday and I'm still learning how it works.
You can go ahead and close this one once the Python 3.8 compilation is done.

**Comment by lazka** [comment]
Ideally we would have a separate repo for such transitions, but... we don't, sorry for the temporary "outage".

**Comment by pablob127** [comment]
No worries! I can wait a couple of days. I'm just hoping that what I am trying to do will work. I'll just close this and reopen if I don't find the packages in a few days to see what happened.
Thanks again!

**Comment by pablob127** [comment]
They're there, thanks a lot!
Can I also ask for a quick bump in the re-building for mingw-w64-x86_64-python3-pyserial?
I'm also missing that one.

**Comment by pablob127** [comment]
I have just found a new pyserial version, thank you very much!!!!
