### ISSUE TITLE
Emacs does not build any more

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#5918]
Today tried to build Emacs from master but it fails. for details you can see this [thread](https://lists.gnu.org/archive/html/emacs-devel/2019-11/msg00003.html).

In short, the same source which built on October 16, now does not build any more. i discovered this trying to build the most recent master.

**Comment by Alexpux** [comment]
@angelog0 this is related to https://github.com/msys2/MINGW-packages/issues/5868

**Comment by angelog0** [comment]
@Alexpux, thanks for clarification. I removed `-D_FORTIFY_SOURCE=2` and now it builds...

I will close this in few days if nobody has to comment.
