### ISSUE TITLE
new releases of FAAC (1.30) and FAAD2 (2.9.0)

### ISSUE THREAD

**Issue by fabiangreffrath** [msys2/MINGW-packages#5929]
https://github.com/knik0/faac/releases
https://github.com/knik0/faad2/releases

**Comment by Alexpux** [comment]
Instead posting this info it better to create pull request. New releases I will see myself without your posts.

**Comment by fabiangreffrath** [comment]
Sorry, not in this case. The PKGINFO files here are still pointing to the abandoned sourceforge sites. Anyway, I'll post a PR for this.

**Comment by Alexpux** [comment]
I’m not look at sites that in PKGBUILD url because there are thousands of packages and I don’t have to me to look at every site

**Comment by fabiangreffrath** [comment]
Yep, and that's why I informed you via bug report. Anyway, seen the two PRs that I filed?

**Comment by Alexpux** [comment]
I will look when have tome

**Comment by totaam** [comment]
For the record, here are the pull requests:
faad2: https://github.com/msys2/MINGW-packages/pull/5930
faac: https://github.com/msys2/MINGW-packages/pull/5931
