### ISSUE TITLE
Can't do process substitution

### ISSUE THREAD

**Issue by cool-RR** [msys2/MINGW-packages#5937]
If I've opened this bug on the wrong repo, please redirect me to the right one. 

I'm on Windows 7 and I use the bash that I got when I installed Git for Windows.

This fails:

```
Administrator@Turing MSYS ~/Desktop          
$ cat <(ls)                                  
cat: /dev/fd/63: No such file or directory   
```

On a normal Bash shell, it should give the same output as `ls`. Why is this failing and how can I make it work?

My final goal is to make something like this possible: https://unix.stackexchange.com/questions/550523/pipe-output-to-a-command-while-still-writing-to-stdout

**Comment by abdulbadii** [comment]
`tee `you mean?
tee --help
Usage: tee [OPTION]... [FILE]...
Copy standard input to each FILE, and also to standard output.

  -a, --append              append to the given FILEs, do not overwrite
  -i, --ignore-interrupts   ignore interrupt signals
  -p                        diagnose errors writing to non pipes
      --output-error[=MODE]   set behavior on write error.  See MODE below
      --help     display this help and exit
      --version  output version information and exit

MODE determines behavior with write errors on the outputs:
  'warn'         diagnose errors writing to any output
  'warn-nopipe'  diagnose errors writing to any output not a pipe
  'exit'         exit on error writing to any output
  'exit-nopipe'  exit on error writing to any output not a pipe

I'm sorry but it's unclear... good to improve the post..

**Comment by cool-RR** [comment]
You can witness the same bug with `tee`. This is on Linux:

```
root@Gottlob ~/Desktop # echo foo | tee >(cat)
foo                                           
root@Gottlob ~/Desktop # foo                  
```

This is on Msys:
```
Administrator@Turing MSYS ~/Desktop   
$ echo foo | tee >(cat)               
tee: /dev/fd/63: Read-only file system
foo                                   
```

**Comment by oscarfv** [comment]
If you are using the shell provided by Git for Windows, you should direct your inquiries to that project, which is independent from MSYS2. If you are using the MSYS2 bash obtained from this project, the right place is https://github.com/msys2/MSYS2-packages This repository (MINGW-packages) is for packages that depend on the mingw-w64 runtime, not on the MSYS2 runtime that provides the POSIX emulation layer that bash (and any other executable placed on `/usr/bin`) requires.
