### ISSUE TITLE
Why the read -p bash shell command cannot delete back correctly

### ISSUE THREAD

**Issue by abdulbadii** [msys2/MINGW-packages#5941]
Tried to type in ` read -p` prompting but always get messy as the editing often need deletion correction,
how to solve this or is there better way?

**Comment by oscarfv** [comment]
Issues related to `bash` should be reported to https://github.com/msys2/MSYS2-packages This repo is for packages based on the mingw-w64 runtime, which are independent from the MSYS2 POSIX emulation layer.
