### ISSUE TITLE
node broken after an update

### ISSUE THREAD

**Issue by pfusik** [msys2/MINGW-packages#5946]
C:\>pacman -Syu
    :: Synchronizing package databases...
     mingw32                    551.2 KiB  1044 KiB/s 00:01 [#############################] 100%
     mingw32.sig                119.0   B  0.00   B/s 00:00 [#############################] 100%
     mingw64                    553.3 KiB  3.14 MiB/s 00:00 [#############################] 100%
     mingw64.sig                119.0   B  0.00   B/s 00:00 [#############################] 100%
     msys is up to date
    :: Starting core system upgrade...
     there is nothing to do
    :: Starting full system upgrade...
    warning: grep: local (3.1-1) is newer than msys (3.0-2)
     there is nothing to do
    C:\>which node
    /mingw64/bin/node

    C:\>node

Displays message boxes about libicuin64.dll and libicuuc64.dll not found.

**Comment by Alexpux** [comment]
@pfusik I’m drop node packages some months ago from repository because it very outdated and there are no maintainer for this packages. So you just use package that not present in MSYS2 anymore.

**Comment by pfusik** [comment]
I see. I'll switch to the official Node.js then.
Thanks for information! Closing.
