### ISSUE TITLE
Create a separate qt5-devel package

### ISSUE THREAD

**Issue by joankaradimov** [msys2/MINGW-packages#5948]
Currently the qt5 package is around 6-7 GB. Most of that is debugging versions of the DLLs. A lot of the remaining is headers. Moving all of that to a development package should leave the qt5 package at around 100MB. And it shouldn't harm its dependents when it comes to runtime dependencies. However, qt5-devel would need to be added to their compile-time dependencies.

Note: This is **not** a duplicate of #4056. The two are orthogonal.

**Comment by Alexpux** [comment]
@joankaradimov feel free to provide pull request for review how to do it

**Comment by Optiligence** [comment]
there is now a `qt5-debug` package that takes out at least the debug infos

**Comment by joankaradimov** [comment]
When updating I get:
```
Total Download Size:     364.99 MiB
Total Installed Size:   1959.27 MiB
Net Upgrade Size:      -5864.45 MiB
```

That's almost 6GB less. This definitely looks fixed. I'm closing the issue.
