### ISSUE TITLE
mingw-w64-python-jsonschema dependencies

### ISSUE THREAD

**Issue by phrrk** [msys2/MINGW-packages#5949]
Following a recent update of my msys2 setup I found that jsonschema had stopped working.  This was reported as due to a dependency on importlib-metadata that had not been satisfied during the update.  Installation of importlib-metalib led also to the installation of the dependencies: python3-cont..., python3-scandir, python3-pathlib2, python3-zipp .  Still jsonschema failed to work as there was one further dependency: more-itertools.  After installing this everything was fine.

Maybe it is my setup, but it looks like the jsonschema's dependencies have not been fully identified in its installation package.

**Comment by lazka** [comment]
Thanks. Please also post the error you are seeing in future reports.

In this case it is python3-zipp missing a dependency on more-itertools
