### ISSUE TITLE
debug build of python3 available via pacman?

### ISSUE THREAD

**Issue by tjwilli58** [msys2/MINGW-packages#5954]
Is there a debug build of python available that I can install via pacman? I'm looking for something like python3-dbg in Ubuntu.

I'm trying to get a backtrace of where my python gstreamer application fails. I've done it with Ubuntu using the instructions [DebuggingWithGdb](https://wiki.python.org/moin/DebuggingWithGdb) but I'd like to do it also under  mingw-w64-x86_64-python3.

I'm trying to track down issue [#1088](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/1088) on gst-plugins-bad.

Thanks for any help.

**Comment by Alexpux** [comment]
@tjwilli58 we not provide debug builds, you must do it yourself

**Comment by tjwilli58** [comment]
@Alexpux  thanks for the reply. I think this is beyond my skillset (at least without a steep learning curve).
I'll stick with debugging this under Ubuntu.
