### ISSUE TITLE
GCC internal compiler error on x86_64 with -O1, -O2 or -O3

### ISSUE THREAD

**Issue by WSSDude420** [msys2/MINGW-packages#5955]
When compiling my code with `-O1`, `-O2` or `-O3`, I get internal compiler error during linking stage (error will be at the end, as it breaks formatting for some reason and I don't know how to go around that...)

I obviously believed this was caused by some flag that these options imply. I defined my own variables, following [info here](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) and checking with `gcc -O<n> -Q --help=optimizers` if all those options are indeed being applied.

In `-O1`, option `-fdelayed-branch` should be enabled (following the link), but is disabled in list from gcc. Trying to put in this option myself hit me with a warning that this option is not available on my platform, so I left it. 

Trying to compile manually with all options (without said one), everything compiled! 
I then double-checked if I'm not dreaming... Rebuild all after complete cleanup... It still worked...

Trying compiling with -O1 again after this (again with complete cleanup), compiler failed again.

I then did the same with -O2 options, leaving out `-ffinite-loops` as that option apparently doesn't exist in this precompiled version at all (compiler just yelling at me that it doesn't know what that option is...)

Same story as with -O1 before (that is everything worked when manually specifying -O2 flags)
I didn't bother with -O3, as I kinda saw the pattern..

It seems there is some weird issue with my specific combination of sources and these -O flags.
I had no issues at all with -O0. Other -O flags, I didn't tried.

This is kinda huge, as now, I am forced to explicitly state each compiler option if I actually want to build release (which is really not optimal!)
I should note that this happened after addition of [sleef](https://github.com/WSSDude/sleef/tree/fslib) to dependencies of one of my sub-projects of my main project. Without changing the options in main project (only those in sub-project like specified above) helped to compile it, so it must somehow correlate. Building this sub-project on its own works even with those flags.

This is [my project](https://gitlab.com/feldarian/quack/tree/develop-broken) in question. Faulty module is `FSLib`, which can be found under `dep` subfolder. Error can be triggered by changing line 46 in `CMakeLists.txt` in root of `FSLib` such that `${fsl_o2}` is replaced by `-O1` or `-O2`.

Anything that could be done? I don't have minimal example (as I don't know at all what is wrong after two days of trying different things...)

```[ 84%] Linking C shared library ..\..\..\..\..\bin\q_shared.dll
during RTL pass: pro_and_epilogue
C:/git/quack/dep/fslib/inc/fslib/math/vector64.inl: In function 'FSL_Vec4D_SlerpUnit':
C:/git/quack/dep/fslib/inc/fslib/math/vector64.inl:734:1: internal compiler error: in choose_baseaddr, at config/i386/i386.c:11835
  734 | }
      | ^
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://sourceforge.net/projects/msys2> for instructions.
lto-wrapper.exe: fatal error: C:\msys64\mingw64\bin\gcc.exe returned 1 exit status
compilation terminated.
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[2]: *** [src\quack\shared\CMakeFiles\q_shared.dir\build.make:172: ../../bin/q_shared.dll] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:1796: src/quack/shared/CMakeFiles/q_shared.dir/all] Error 2
mingw32-make.exe: *** [Makefile:129: all] Error 2```

**Comment by Alexpux** [comment]
@WSSDude better to post bugreport to GCC.

**Comment by mingwandroid** [comment]
@WSSDude, please use `creduce` to make a minimal test case. It works well.

**Comment by MehdiChinoune** [comment]
Closing due to (No minimal reproducer + inactivity)
