### ISSUE TITLE
Can't download package with "pacman -Sw"

### ISSUE THREAD

**Issue by KerimMatlab** [msys2/MINGW-packages#5956]
I'm trying to download a package with command:
`pacman -Sw mingw-w64-x86_64-hdf5`
But I get the following (I have Russian version I simply traslate it):
`Package (1) mingw-w64-x86_64-hdf5-1.10.5-1
Will be downloaded 0 MiB`
And if I type "Y" then nothing in my folder I can see...

But output from the command:
`pacman -S mingw-w64-x86_64-hdf5`
is:
`Package (1) mingw-w64-x86_64-hdf5-1.10.5-1
Will be installed 78,90 MiB`
What is the problem?

And how to configure the the package before installing? Usually we do ./configure --prefix=... etc... How to do that with MSYS2?

Best regards

**Comment by oscarfv** [comment]
pacman puts the downloaded packages in the directory `/var/cache/pacman/pkg`. If you wish to download the package to another directory, use the `--cachedir` parameter.

As for your second question, `./configure ...` is used for configuring the build of source code. pacman downloads and installs binary packages, which means that they are the products of building the source code.

If your questions are resolved, please close this issue. Thanks.

**Comment by KerimMatlab** [comment]
Thank you!
I close the issue
