### ISSUE TITLE
[OpenSCAD] does not support CGAL 5.x

### ISSUE THREAD

**Issue by podsvirov** [msys2/MINGW-packages#5972]
The [CGAL](https://packages.msys2.org/package/mingw-w64-x86_64-cgal?repo=mingw64) package only required by OpenSCAD now, but OpenSCAD do not support header-only CGAL (in `master` [too](https://github.com/openscad/openscad/pull/3083)).
What about to downgrade CGAL package to previous 4.14 version like in Arch?

**Comment by lazka** [comment]
Sounds reasonable to me.

**Comment by t-paul** [comment]
OpenSCAD master is now at C++14 and supports CGAL5 / header only (https://github.com/openscad/openscad/pull/3163).

**Comment by podsvirov** [comment]
@t-paul, thanks for the good news!  We look forward to the next release of OpenSCAD with these changes.

**Comment by lazka** [comment]
Should we backport any patches, like the above mentioned PR?

**Comment by t-paul** [comment]
Debian uses: https://sources.debian.org/src/openscad/2019.05-3/debian/patches/Switch-to-std-c-14-for-CGAL5-compatibility.patch/

**Comment by podsvirov** [comment]
Closed via #7906.
