### ISSUE TITLE
Python 3.8 os.path.expanduser breaking change

### ISSUE THREAD

**Issue by victorliu** [msys2/MINGW-packages#5978]
The following change put in place for Python 3.8 related to ignoring $HOME when evaluating `os.path.expanduser` has broken a number of packages for me, including possibly awscli/botocore:

https://bugs.python.org/issue36264

My $HOME is set "correctly" to `/home/<username>`, while `expanduser` returns `C:\Users\<username>`. My current workaround is to copy all my hidden configuration files into the windows home directory. I would suggest that this patch be undone for the mingw python3 package, or else provide guidance on the best way to handle this behavior change.

**Comment by lazka** [comment]
I agree that this is an annoying change, but using USERPROFILE and not HOME is the right thing to do for native software, and we should try to avoid diverging from upstream Python. I'd advice to move the files to the new location.

While looking into this I found that not all functions in Python were changed to ignore HOME so I've filed https://bugs.python.org/issue38883

**Comment by lazka** [comment]
I've created a PR for the other issue: https://github.com/python/cpython/pull/17961
