### ISSUE TITLE
psycopg2 should depend on PostgreSQL

### ISSUE THREAD

**Issue by samhocevar** [msys2/MINGW-packages#5979]
Installing `mingw64/mingw-w64-x86_64-python3-psycopg2` leaves the package unusable as is, because `/mingw64/usr/lib/libpq.dll` is missing. That library is provided by `mingw64/mingw-w64-x86_64-postgresql`.

I suppose the `python2` and `mingw32` versions suffer from the same problem.

**Comment by lazka** [comment]
@JPeterMugaas is there a reason it is only a make dependency?

**Comment by JPeterMugaas** [comment]
I don't see any problem with that change.  I made a PR for this at: https://github.com/msys2/MINGW-packages/pull/5998

**Comment by lazka** [comment]
Thanks!
