### ISSUE TITLE
mingw-w64-x86_64-python3-colour unusable - has only a COPYING file?

### ISSUE THREAD

**Issue by sdbbs** [msys2/MINGW-packages#5982]
I thought, I'd check if I could find https://pypi.org/project/colour-science in MSYS2/MINGW64.

So, I just ran this on my MSYS2, Windows 10 system:

```
$ pacman -Ss colour
mingw32/mingw-w64-i686-python2-colour 0.3.11-1
    Python library for a multitude of colour science applications (mingw-w64)
mingw32/mingw-w64-i686-python3-colour 0.3.11-1
    Python library for a multitude of colour science applications (mingw-w64)
mingw64/mingw-w64-x86_64-python2-colour 0.3.11-1
    Python library for a multitude of colour science applications (mingw-w64)
mingw64/mingw-w64-x86_64-python3-colour 0.3.11-1
    Python library for a multitude of colour science applications (mingw-w64)
```

I thought - nice, I'll install it from here:

```
$ pacman -S mingw-w64-x86_64-python3-colour
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-python3-colour-0.3.11-1

Total Download Size:   0.02 MiB
Total Installed Size:  0.00 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 mingw-w64-x86_64-python3-colour-0.3.11-1-any    21.1 KiB   810 KiB/s 00:00 [##########################################] 100% (1/1) checking keys in keyring                                              [##########################################] 100% (1/1) checking package integrity                                            [##########################################] 100% (1/1) loading package files                                                 [##########################################] 100% (1/1) checking for file conflicts                                           [##########################################] 100% (1/1) checking available disk space                                         [##########################################] 100% :: Processing package changes...
(1/1) installing mingw-w64-x86_64-python3-colour                            [##########################################] 100%
```

Cool, let's check it now, in MINGW64 python:

```
$ python3
Python 3.8.0 (default, Oct 25 2019, 06:23:40)  [GCC 9.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import colour
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'colour'
```

Ups, not working? Let's see what files are installed:

```
$ pacman -Ql mingw-w64-x86_64-python3-colour
mingw-w64-x86_64-python3-colour /d/msys64/mingw64/
mingw-w64-x86_64-python3-colour /d/msys64/mingw64/share/
mingw-w64-x86_64-python3-colour /d/msys64/mingw64/share/licenses/
mingw-w64-x86_64-python3-colour /d/msys64/mingw64/share/licenses/python3-colour/
mingw-w64-x86_64-python3-colour /d/msys64/mingw64/share/licenses/python3-colour/COPYING
```

What, there is only a single file, `COPYING`, in this package? Indeed, this page: https://packages.msys2.org/package/mingw-w64-x86_64-python3-colour?repo=mingw64 - seems to confirm that!

I guess, I could try installing this package via pypi - but, I was wondering: what is the purpose of having this package, and then having only a single `COPYING` file in it? Do I maybe need to install something else in addition, as well?

**Comment by lazka** [comment]
@briend ^

**Comment by lazka** [comment]
The package build script needs lots of work and we are even missing dependencies. @sdbbs do you need this package? Otherwise I'd say we just remove it.

**Comment by briend** [comment]
I agree, sorry about that.

**Comment by lazka** [comment]
No problem :)

**Comment by sdbbs** [comment]
Hi all,

Sorry for the late response.

> The package build script needs lots of work and we are even missing dependencies. @sdbbs do you need this package? Otherwise I'd say we just remove it.

Thanks - well, I need this package; however, I managed to install it via Anaconda. On the other hand, I *really* prefer working in MSYS2/MINGW64, in my preferred Unix/Linux working environment - which is why I'd like to have the package here as well.

However, I'm aware how difficult it can be to maintain complex packages like this one, so if there are not too many users of this package, I will understand if it is removed - certainly better not to confuse potential users.

Btw, I ran a small test, and first removed the package with `pacman -Rs mingw-w64-x86_64-python3-colour` - and then, tried via pip3:

```
user@DESKTOP MINGW64 /c
$ pip3 install colour-science
Collecting colour-science
  Downloading https://files.pythonhosted.org/packages/0f/5e/d6fb7e115ce3176be3901c62cb01c4189e59058fb0f1b259b54a520ec67c/colour_science-0.3.14-py2.py3-none-any.whl (1.6MB)
     |████████████████████████████████| 1.6MB 9.5MB/s
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/a7/5c/495190b8c7cc71977c3d3fafe788d99d43eeb4740ac56856095df6a23fbd/scipy-1.3.3.tar.gz (23.8MB)
     |████████████████████████████████| 23.8MB 311kB/s
  Installing build dependencies ... / (** wait here, takes a while; 13:24 **)
...
ERROR: Command errored out with exit status 1: /usr/bin/python3.exe /usr/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-143zm95x/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools 'Cython>=0.29.13' 'numpy==1.13.3; python_version=='"'"'3.5'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.5'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' Check the logs for full command output.
```

This is just a snippet of the output - the actual output has like 5000+ lines, and I've pasted it here: 

https://gist.github.com/sdbbs/047b71d0b5acf8e11a5a8ddafc9479f8#file-pip3_install_colour-science_mingw64-log

I've also tried building under MSYS2 shell, too - that fails as well (though with fewer lines in the log):

https://gist.github.com/sdbbs/047b71d0b5acf8e11a5a8ddafc9479f8#file-pip3_install_colour-science_msys2-log

So, just to put it out there, the route of installing `colour-science` via `pip3` under MINGW64 (or MSYS2) does not work, as it requires compilation, and there are currently "undeclared" and "undefined reference" and "No such file or directory" errors. 

So yeah - I guess it should be removed for now; though it would be great if at a certain point, this package also enters MINGW64 packages.

**Comment by lazka** [comment]
> Thanks - well, I need this package

ok, we'll try to fix it then.

**Comment by JPeterMugaas** [comment]
Alright, I do have a proposed fix for this.  https://github.com/msys2/MINGW-packages/pull/6007 .  One problem I saw was that pip probably was NOT doing what was expected.  pip might work for prebuilt things but the package had downloaded source-code.  See if what I did helps.
