### ISSUE TITLE
pre-update packages in installer instead of `pacman -Syu`

### ISSUE THREAD

**Issue by long-nguyenxuan** [msys2/MINGW-packages#5993]
Everytime I re-install msys2 on new system, I must `pacman -Syu` to update packages, it works well, but the problem is it **take time** to update/upgrade. 
Why can't we pre-update packages in installer (msys2-x86_64-YYYYMMDD.exe) so we could just install and work? 

![image](https://user-images.githubusercontent.com/46129500/69602225-66b4bf80-1049-11ea-8bc0-2df10ab94f0b.png)

**Comment by lazka** [comment]
> Why can't we pre-update packages in installer (msys2-x86_64-YYYYMMDD.exe) so we could just install and work?

Because these updates happened between YYYYMMDD and now :)

But, yes, we should try to build the installer in CI regularly.

**Comment by lazka** [comment]
> But, yes, we should try to build the installer in CI regularly.

I've started something here: https://github.com/msys2/msys2-installer/releases/tag/nightly

**Comment by lazka** [comment]
https://github.com/msys2/msys2-installer now has a link to the latest installer.
