### ISSUE TITLE
mingw-w64-i686-gnutls missing dependencies: libhogweed and libnettle

### ISSUE THREAD

**Issue by stephe-ada-guru** [msys2/MINGW-packages#5997]
According to https://github.com/lucasg/Dependencies, libgnutls-30.dll imports libhogweed-5.dll and libnettle-7.dll, but those are not installed by the gnutls package.

**Comment by JPeterMugaas** [comment]
/mingw32/bin/libnettle-7.dll and /mingw32/bin/libhogweed-5.dll  are installed by mingw-w64-i686-nettle.  Those are listed as a dependency in gnutls.
