### ISSUE TITLE
options array contains unknown option

### ISSUE THREAD

**Issue by TwentyOneSolutions** [msys2/MINGW-packages#6]
Hi,

I'm trying to run makepkg-mingw on https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-v8/PKGBUILD and I get an error:

    User@User-PC MINGW64 /C/Builds/MINGW-packages/mingw-w64-v8
    $ makepkg-mingw
    ==> ERROR: options array contains unknown option '!emptydirs !strip'

**Comment by Alexpux** [comment]
Need to place every option in braces: '!emptydirs' '!strip'

**Comment by TwentyOneSolutions** [comment]
I see, 'single quotes', got it, thanks!
