### ISSUE TITLE
ncurses: source tarball gone, package doesn't build

### ISSUE THREAD

**Issue by expnkx** [msys2/MINGW-packages#6000]
not existing package
failed patch

**Comment by lazka** [comment]
?

**Comment by expnkx** [comment]
> ?

I try to makepkg-mingw the latest ncurse and it fails.

**Comment by lazka** [comment]
yeah, looks like upstream has deleted the source tarball.

**Comment by lazka** [comment]
Fixed in 41a099308bc1fe29
