### ISSUE TITLE
LLVM: cmake exports error

### ISSUE THREAD

**Issue by zhouzhenghui** [msys2/MINGW-packages#6003]
Building project using LLVM library with the scripts generated by cmake outside the shell, gives the error "No rule to make target '/mingw64/lib/libz3.dll.a'"

Problem may exist in the LLVMExport.cmake of LLVM mingw package, the line is:

INTERFACE_LINK_LIBRARIES "z;psapi;shell32;ole32;uuid;advapi32;pthread;/mingw64/lib/libz3.dll.a;LLVMDemangle"

An absolute path of libz3.dll.a is used, but it may not match the actually path of windows system.

**Comment by zhouzhenghui** [comment]
The problem is found in LLVM9, the line described above doesn't exist in LLVM8, but a similar problem still occurs, and may caused by a line in ClangTargets.cmake:

INTERFACE_LINK_LIBRARIES "clangAST;clangASTMatchers;clangAnalysis;clangBasic;clangCrossTU;clangLex;clangRewrite;C:/building/msys64/mingw64/lib/libz3.dll.a;LLVMSupport"

**Comment by oscarfv** [comment]
Please decribe a recipe for reproducing the problem. There is no `LLVMExport.cmake` file on my install.

**Comment by zhouzhenghui** [comment]
Sorry I missed.

Those errors are related to specified environment where the package of LLVM/clang are installed. The files mentioned can be found in the corresponding sub-dirctories in /msys64/ming64/lib/cmake if the mingw-w64-x86_64-llvm or others packages are installed.

Those cmake exports files of the packages are generated automatically by cmake when them were created as I know. So the path may be append automatically too  according to the environment those packages were built.

The following steps and example may be used for reproducing the problem：

pacman -S mingw-w64-x86_64-llvm
pacman -S mingw-w64-x86_64-polly
pacman -S mingw-w64-x86_64-compiler-rt
pacman -S mingw-w64-x86_64-clang
pacman -S mingw-w64-x86_64-clang-tools-extra

And a CMakeLists.txt:

find_package(Clang REQUIRED CONFIG)
message(STATUS "Found LLVM ${LLVM_PACKAGE_VERSION}")
message(STATUS "Using LLVMConfig.cmake in: ${LLVM_DIR}")
message(STATUS "Using ClangConfig.cmake in: ${CLANG_CMAKE_DIR}")

I tried under the MINGW64 terminal of msys2.

**Comment by oscarfv** [comment]
The CMakeLists.txt file you listed works fine here and no LLVMExport.cmake file is generated:

```
oscar@w10x64-vm-sky MINGW64 /d/dev/yyy/cmake
$ cmake .
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found LLVM 9.0.0
-- Using LLVMConfig.cmake in: C:/apps/msys64/mingw64/lib/cmake/llvm
-- Using ClangConfig.cmake in: C:/apps/msys64/mingw64/lib/cmake/clang
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.15)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: D:/dev/yyy/cmake

oscar@w10x64-vm-sky MINGW64 /d/dev/yyy/cmake
$ find . | grep -i export

oscar@w10x64-vm-sky MINGW64 /d/dev/yyy/cmake
$ 
```

**Comment by zhouzhenghui** [comment]
Thanks for your quick response.

The CMakeLists.txt is a example to show where the export files of LLVM packages are installed. As the results in your environments, those are installed in:

-- Using LLVMConfig.cmake in: C:/apps/msys64/mingw64/lib/cmake/llvm
-- Using ClangConfig.cmake in: C:/apps/msys64/mingw64/lib/cmake/clang

You can find the files I mentioned in the listed directories.

The export files are generated along with the LLVM/Clang packages, not the current building project.

And error should exists when you needs some objects in the LLVM/Clang export file, if some of the LLVM/Clang objects are needed to be linked in the current project, for example, some lines of the CMakeLists.txt taken from the [LLVM users guide](https://llvm.org/docs/CMake.html):

add_executable(simple-tool tool.cpp)

# Find the libraries that correspond to the LLVM components
# that we wish to use
llvm_map_components_to_libnames(llvm_libs support core irreader)

# Link against LLVM libraries
target_link_libraries(simple-tool ${llvm_libs})

**Comment by oscarfv** [comment]
Sorry, you are right.

The problem probably comes from `Z3_LIBRARIES` CMake variable being assigned the absolute path to the import library by `FindZ3.cmake`, which uses `find_library`. IIRC that command assigns the resulting variable (`Z3_LIBRARIES`) with the full path to the found library.

However, it is strange that the path in `INTERFACE_LINK_LIBRARIES` is `/mingw64/bin/...` instead of what `Z3_LIBRARIES` contains (`c:/msys64/mingw64/bin/...`,) but that's a different topic.

@zhouzhenghui : you have several options. The first one is to simply edit `LLVMExport.cmake` replacing `/mingw64/...z3.dll.a` with `z3`. The second is to create a patch that fixes  `FindZ3.cmake`. The third one is to report the bug to LLVM. Obviously, you can combine all those options :)

**Comment by zhouzhenghui** [comment]
Yes, I have modified the files ad will tries the other options later.
Thanks for your tips and sorry for my late reply.
