### ISSUE TITLE
VLC plugins not working

### ISSUE THREAD

**Issue by Bleiddo** [msys2/MINGW-packages#6005]
It seems that plugins depend or earlier version of libraries than the ones that come with VLC installation. It would be nice if someone would update the package.

**Comment by Bleiddo** [comment]
I'm not  trying to be rude, but what are the chances that someone rebuilds and updates VLC package soon? I've tried to rebuild it myself without success, and i really need libvlc in my project.

**Comment by Alexpux** [comment]
@Bleiddo rebuilded and uploaded
