### ISSUE TITLE
Syntax error in header from wineditline

### ISSUE THREAD

**Issue by olafmandel** [msys2/MINGW-packages#6008]
The file `/mingw32/include/editline/readline.h` belonging to `mingw-w64-i686-wineditline` is defective under C++: contains a closing `}` but no opening `extern "C" {`.

In light of upstream not having released in nearly two years, please consider either building directly from the upstream SVN or at least backporting revision 34 from the SVN repository:

```
Index: src/editline/readline.h
===================================================================
--- src/editline/readline.h     (revision 33)
+++ src/editline/readline.h     (revision 34)
@@ -46,6 +46,10 @@
 */
 #define DEFAULT_HISTORY_SIZE    200  /* default number of history entries */
 
+#ifdef __cplusplus
+extern "C" {
+#endif
+
 typedef char **rl_completion_func_t(const char *, int, int);
 typedef char *rl_compentry_func_t(const char *, int);
 typedef void rl_compentryfree_func_t(void *);
```

Thank you.

**Comment by revelator** [comment]
Thats one hell of a defect... 
Good catch :)
