### ISSUE TITLE
pango breaking pygtk and other packages

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#6014]
So after finally updating to gcc-9.2.0 i decided to rebuild most packages, but theres a snag...
seems recent pango removed bitmap support and private headers causing applications such as pygtk to fail building.  This in turn breaks gimp as it relies on pygtk and inkscape as well.
Most distros have reverted to pango-1.42 because of this, since it also causes T1 font problems.
pygobject was intended to replace pygtk at some point but there has been little to any development 
in that regard, so waiting for them to fix it might take longer than you might want to wait.

So i suggest downgrading pango to 1.42 and possibly cairo to in the meantime.

**Comment by revelator** [comment]
atk also seems to have problems, glib2 and gobject2 are now private objects in the pkgconfig scripts causing more grief with pygtk. Atleast i can fix atk to work by hand modifying atk.pc but that might not fly well with everybody.

```
Requires.private: glib-2.0 >=  2.38.0, gobject-2.0 >=  2.38.0
Libs: -L${libdir} -latk-1.0
```

should be 

```
Requires: glib-2.0 >=  2.38.0, gobject-2.0 >=  2.38.0
Libs: -L${libdir} -latk-1.0 -lglib-2.0 -lgobject-2.0
```

**Comment by lazka** [comment]
yeah, there is a fix upstream. I'll have a look.

**Comment by lazka** [comment]
See #6021. Regarding pango, we don't ship pango 1.44, so I don't think we are affected by all of this.

**Comment by revelator** [comment]
well then it must be the atk package ? cause i could not build pygtk unless i modified the package config files like above.

pango seems to be vesion 1.43 and cairo 1.16 so yeah that seems to be ok.

**Comment by revelator** [comment]
Ah you allready fixed it :) no problems then.

**Comment by lazka** [comment]
We are also stuck with pango < 1.44 but not because of font loading but because of broken font rendering.

**Comment by revelator** [comment]
hmm only problem im noticing so far is that gtk3's viewport seems to be off by a bit, 
the gtk2 viewport looks fine. 

oh wait i see now pango crashes when trying to render fonts ouch :S

**Comment by revelator** [comment]
```
(gtk3-demo.exe:13724): Pango-CRITICAL **: 07:25:43.433: pango_fc_font_lock_face: assertion 'PANGO_IS_FC_FONT (font)' failed
Exception code=0xc0000005 flags=0x0 at 0x6184C1CA. Access violation - attempting to read data at address 0x00000068
Segmentation fault
```

yikes
