### ISSUE TITLE
geos library name for shapely compatibility

### ISSUE THREAD

**Issue by victorliu** [msys2/MINGW-packages#6017]
Currently, when attempt to install the Python package `shapely` via `pip install shapely`, the install fails due to not being able to find `geos_c.dll`. The current geos installation names the DLL `libgeos_c.dll`. I have had to modify the shapely installer to make it find the DLL as referenced here: https://github.com/Toblerity/Shapely/issues/633
It would be potentially cleaner if the geos package simply made a symlink for the alternate DLL name.

**Comment by Alexpux** [comment]
@victorliu we wil not create library copies. Fix python package instead.
