### ISSUE TITLE
miniupnpc: static linking broken

### ISSUE THREAD

**Issue by prissi** [msys2/MINGW-packages#6019]
When linking a program with libminiupnpc.a (i.e. static) also the main function of miniupnpc (the client) is linked and overlays the main program. Hence any executable will be only a miniupnpc client.

I suspect the patch from WIN32 to MSVC is not what was intended. But I am somehow at loss to what base the patch was applied.

**Comment by oscarfv** [comment]
The patch you mention is fine. It just ensures that the static library name gets the correct prefix (MinGW automatically prepends "lib" to library names).

Please provide a detailed, complete and self-contained recipe for reproducing the problem.

**Comment by prissi** [comment]
Tested with 32 bit under windows: Link any program with libminiupnpc
ld ... -static ... -lminiupnpc ...
This program is now an miniupnpc client, it is a commandline program that accept all commands of miniupnpc. Without static linking only the library is taken as intended.
If one looks at the linminiupnpc.a with an editor, one immediately sees that it contains the function _main that overlays the actual main function. Building libminiunpnc from the sources does not do this. So I am at loss to which are the sources used. I downloaded them from https://codeload.github.com/miniupnp/miniupnp/zip/master

**Comment by oscarfv** [comment]
You don't provide the information I requested. You don't even bother to fully show the link command (why do you use `ld` instead of `gcc`?) Thus is very difficult to help you.

**Comment by prissi** [comment]
Main a file test,c which contains "int main(){}"
gcc -static -lminiupnpc test.c
First error message:
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccYdiPak.o:test.c:(.text+0x0): multiple definition of `main'; C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../lib\libminiupnpc.a(listdevices.c.obj):(.text.startup+0x0): first defined here
...

**Comment by oscarfv** [comment]
Try `gcc test.c -static -lminiupnpc`. In general, your compilation units should be listed before any library and if a library A references symbols defined in a library B, A must appear before B on the command line. Order matters.

**Comment by oscarfv** [comment]
If this solves your problem please close this issue. Thanks.

**Comment by prissi** [comment]
Imho a library should never overoad the main function. And the original Sources does not do that either. Of course, revresing order will have the other main function overlaid the library one. Anyway, if you see this as ok, I will close it.

**Comment by oscarfv** [comment]
`main` is defined in [`miniupnpc/listdevices.c`](https://github.com/miniupnp/miniupnp/blob/0ab1d6725b800f007f9bb9919150546476616f1b/miniupnpc/listdevices.c#L86), so that has nothing to do with `MSYS2/MINGW-packages` proper. If you think that's wrong, you should ask `miniupnpc` developers about why they put a `main` function on their library.

**Comment by prissi** [comment]
Bit it is never include in the makefile for the library. See
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/Makefile.mingw or the normal Makelfile LIBSOBJ.
listdevices is an Independent program and should not be linked for the lib.

**Comment by oscarfv** [comment]
It is included on [`CMakeLists.txt`](https://github.com/miniupnp/miniupnp/blob/0ab1d6725b800f007f9bb9919150546476616f1b/miniupnpc/CMakeLists.txt#L70), which is what `MINGW-packages` uses for building the library. That looks like a bug worth reporting to `miniupnp`.

**Comment by prissi** [comment]
Ok, I do not know much about CMake. so I just compiled with "make -f Makefile.mingw" which gave a working libminiupcp.lic. Anyway, thats for the effort to find the cause.
