### ISSUE TITLE
mingw-w64-qtwebkit need to be recompiled every qt5 upgrade

### ISSUE THREAD

**Issue by gmrandazzo** [msys2/MINGW-packages#6020]
Dear All,

every time that there is an upgrade of qt5, the following package mingw-w64-qtwebkit is broken and need to be recompiled manually.  So I was wondering if you can fix this to be automatically recompiled every time that there will be a qt5 upgrade. 

Best regards

CMake Error at C:/msys64/mingw64/share/cmake-3.15/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Could not find a configuration file for package "Qt5Core" that exactly
  matches requested version "5.13.1".

  The following configuration files were considered but not accepted:

    C:/msys64/mingw64/lib/cmake/Qt5Core/Qt5CoreConfig.cmake, version: 5.13.2

Call Stack (most recent call first):
  C:/msys64/mingw64/lib/cmake/Qt5WebKitWidgets/Qt5WebKitWidgetsConfig.cmake:71 (find_dependency)

-- Configuring incomplete, errors occurred!

**Comment by Alexpux** [comment]
@gmrandazzo qtwebkit is not buildable for me now

**Comment by MehdiChinoune** [comment]
likely no longer an issue
