### ISSUE TITLE
fix for rapidjson gcc-9.2.0

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#6023]
upstream patch here.
[0006-gcc-9.2.0.zip](https://github.com/msys2/MINGW-packages/files/3921268/0006-gcc-9.2.0.zip)

**Comment by lazka** [comment]
PRs welcome and please add a link to the upstream issue/commit if there is one.

**Comment by revelator** [comment]
[](https://github.com/pah/rapidjson-upstream/commit/fa5963a2f5b231ee2babff771f169ccca22870ed)

more or less just some casting problems.

**Comment by lazka** [comment]
Thanks, this is the relevant upstream PR: https://github.com/Tencent/rapidjson/pull/1323

re PR, I meant you need to create a PR for msys2.

**Comment by revelator** [comment]
Ah ok. 

Ill look into it.

**Comment by revelator** [comment]
Hmm i dont have a fork of this repository so making a pull request seems to be out of the question atm.
