### ISSUE TITLE
Error with packet mingw-w64-i686-librsvg-2.46.4-1-any

### ISSUE THREAD

**Issue by Citrodata** [msys2/MINGW-packages#6036]
When i compile the XMPP Messenger Gajim the SVG Icons from Adwaita aren't loading.
I installed an old packet Version mingw-w64-i686-librsvg-2.44.14-1-any and the SVG files all loaded correctly like bevor.
Is the any way that i can load the SVG files without patching every time back to and old version of this packet?

**Comment by lazka** [comment]
We'd have to figure out why it doesn't work first.

**Comment by Citrodata** [comment]
When PyGTK try's to load a Icon from Adwaita it woll only show a missing Icon Symbol if the Adwaita iconset has only a SVG Version of the Picture.

**Comment by Citrodata** [comment]
I know that when you compile Gajim its using older GTK3 packets. Version gtk3-3.24.1-1.
Can it be that librsvg and the old GTK3 packet don't work quite well together?

**Comment by lazka** [comment]
Maybe, it's probably untested. Note that gtk doesn't use librsvg directly, it uses gdk-pixbuf.

**Comment by Citrodata** [comment]
And is using gdk-pixbuf? I fixed the Problemm with using an old librsvg-2-2.dll from Version 2.44.14-1.
Not quite sure why this fix the error but not upgrading the gdk-pixbuf and gtk3 packet.

**Comment by Citrodata** [comment]
When the Version change happened the svg icons broke.

**Comment by lazka** [comment]
> And is gdk-pixbuf using librsvg?

yes. If you execute `gdk-pixbuf-query-loaders.exe` you should see `libpixbufloader-svg.dll` in the output which links against librsvg-2-2.dll.
