### ISSUE TITLE
proposal remove coq and ocaml packages

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#6040]
the coq package depends on camlp4 which is no longer maintained nor provided by msys2 anymore,
so i propose removing the ocaml packages alltogether since only a few packages use them and these can no longer be built.

**Comment by MehdiChinoune** [comment]
coq and many ocaml packages were removed.

**Comment by Biswa96** [comment]
We can add those if anyone needs it. Also those packages need to be buildable and usable in mingw environment 😺

**Comment by ericoporto** [comment]
Hey, I really need coq for MSYS2 as a Windows user.

If you are a random person from Google and found this, this is what you should do

- download the windows installer release from coq platform: https://github.com/coq/platform/releases/tag/2022.09.1
- don't install, uses 7-zip to extract the exe into a directory
- copy the bin, lib, etc, share, man dirs to your `/usr/local/`
- copy the findlib.conf file from the `/usr/local/lib` dir to `/usr/local/etc`
- in your bash rc, add a line `export OCAMLFIND_CONF=/usr/local/etc/findlib.conf
- restart your MSYS2 shell and running coqide should work!
-
