### ISSUE TITLE
mingw-w64-x86_64-python3-setuptools missing conflicts

### ISSUE THREAD

**Issue by Optiligence** [msys2/MINGW-packages#6054]
> mingw-w64-x86_64-python3-setuptools: /mingw64/bin/easy_install-script.py exists in filesystem (owned by mingw-w64-x86_64-python2-setuptools)
> mingw-w64-x86_64-python3-setuptools: /mingw64/bin/easy_install.exe exists in filesystem (owned by mingw-w64-x86_64-python2-setuptools)

**Comment by Alexpux** [comment]
@Optiligence we drop nearly all python2 packages from repository, so you need manually uninstall python2 packages from your system

**Comment by Optiligence** [comment]
but you could also add a conflicts, which would let pacman offer to remove it automatically…

**Comment by Alexpux** [comment]
@Optiligence well probably, but mostly packages was propped without rebuilds. Will see later after new year weekends

**Comment by Optiligence** [comment]
it also only affects changed packages that now install their files where there previously were python2 files, like `python3-setuptools`

just dropping packages creates no conflicts…

**Comment by lazka** [comment]
I've added a conflict in #6070

**Comment by lazka** [comment]
I hope it works better now.
