### ISSUE TITLE
I trying to develop an dll file using MinGW for an JNI .In order to develop with pylon camera

### ISSUE THREAD

**Issue by vijay180396** [msys2/MINGW-packages#6060]
x86_64-w64-mingw32-gcc -I"%JAVA_HOME%\include" -I"%JAVA_HOME%\include\win32" -I"C:\Program Files\Basler\pylon5\Development\include" -shared -o basler.dll BaslerGrab.cpp
this an command i tried to develop an dll

**Comment by vijay180396** [comment]
but i get's an issue like
n file included from C:\Program Files\Basler\pylon5\Development\include/pylon/PylonIncludes.h:18:0,
                 from BaslerGrab.cpp:2:
C:\Program Files\Basler\pylon5\Development\include/pylon/Platform.h:127:5: error: #error Unsupported platform
 #   error Unsupported platform 
[And this error through from an header file of pylon ]
please,tell me an solution for further development to solve this issue

#--------------------------------------------------------------------------------------------------
and i using platform of Windows 10
and java version 11.0.4

**Comment by StarWolf3000** [comment]
Without any further info on what the file `include/pylon/Platform.h` looks like (and what build platform it expects), no one can help you, especially when using MINGW with package-foreign software.

**Comment by vijay180396** [comment]
thanks for your comment, But i cannot understand what do you saying

**Comment by vijay180396** [comment]
@StarWolf3000 , i just try to develop an .dll file by using MinGW for JNI concept (Java Native Interface)

**Comment by StarWolf3000** [comment]
I have already understood that, but I don't know what Pylon wants as a platform, if it nags about an "Unsupported platform". Because MINGW doesn't have Pylon, it's a foreign system/whatever, and so we don't know what `include/pylon/Platform.h` looks like.

**Comment by Biswa96** [comment]
It checks this `#if defined (_MSC_VER) && defined (_WIN32)` and then `_WIN64` for 64bit and `_WIN32` for 32bit.

**Comment by StarWolf3000** [comment]
So that means, it is designed for Visual Studio, and not GCC-based compilers.

As there are usual more incompatibilities between GCC and Microsoft's compilers, a lot of rework and patches would be necessary. Not forgetting the libraries for the linker.

**Comment by Biswa96** [comment]
It checks this `#if defined (_MSC_VER) && defined (_WIN32)` and then `_WIN64` for 64bit and `_WIN32` for 32bit. Also then `#elif (defined(__GNUC__) && defined(__linux__)) || defined(__APPLE__)`. Else falied.

**Comment by vijay180396** [comment]
@StarWolf3000 i have developed an dll file in visual studio.it works fine

**Comment by vijay180396** [comment]
but i just trying to create in MinGW,and more thing i have developed .so file in linux for pylon(x64 bit platform)using g++ -fPIC compiler

**Comment by spl1inter** [comment]
Wow. Uh guys. This wont work.

FIRST, you cannot create JNI applications from MinGW using Sun's JDK binary release. As the error says, your platform is not supported. You have two ugly options: resurrect GJC for MinGW or port the Sun JDKto MinGW.

Why is this? Complex runtimes become very compiler specific. Furthermore, as covered at least a millions times on the web, the symbol tables bewteen MSVC C++ and G++ are completely incompatible. You might be able to import a reasonably simple C-only DLL between the two, but that is it.

**Comment by spl1inter** [comment]
Recommend close as invalid.

**Comment by vijay180396** [comment]
@spl1inter ,thanks for your information and i understand clearly now.
