### ISSUE TITLE
mingw-w64-meson: cannot find valid include folder path under ${MINGW_PREFIX} when parsing meson.build wrap file

### ISSUE THREAD

**Issue by pal1000** [msys2/MINGW-packages#6068]
I discovered this when I attempted to simplify [/mingw-w64-mesa/llvmwrapgen.sh](https://github.com/pal1000/MINGW-packages/blob/meson-wrap-include-bug/mingw-w64-mesa/llvmwrapgen.sh)
That simplification should work and mingw-w64-mesa should build successfully. However it unexpectedly fails during setup phase complaining it can't find `/mingw64/include` or `/mingw32/include` include directory when loading llvm subproject.

**Comment by lazka** [comment]
Maybe you want to use `$(cygpath -m "$MINGW_PREFIX")`  instead?

**Comment by pal1000** [comment]
That simplification worked.  Sent #6069. I consider closing this as a won't fix thing unless someone wants to fix it with a PR.
