### ISSUE TITLE
Reduce mingw-w64-clang package size via dynamic linking?

### ISSUE THREAD

**Issue by adrpo** [msys2/MINGW-packages#6072]
Currently installing clang takes 5GB (2.7 for each mingw64/mingw32) which is rather huge.

I see in the cmake conf:
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-clang/PKGBUILD#L299
that we have `LLVM_LINK_LLVM_DYLIB=ON` but then we have `LLVM_LINK_LLVM_DYLIB=OFF`.
This means that clang.exe, clang++.exe, clang-cl.exe all have really big sizes, 90+ MB each.

Would it be possible to enable `LLVM_LINK_LLVM_DYLIB=ON`?

From what I can read here:
https://llvm.org/docs/CMake.html
it says: `This option is not available on Windows` but then below it it somehow hints that is only a problem from Microsoft toolchain.
```
LLVM_LINK_LLVM_DYLIB:BOOL
If enabled, tools will be linked with the libLLVM shared library. Defaults to OFF. Setting LLVM_LINK_LLVM_DYLIB to ON also sets LLVM_BUILD_LLVM_DYLIB to ON. This option is not available on Windows.
BUILD_SHARED_LIBS:BOOL
Flag indicating if each LLVM component (e.g. Support) is built as a shared library (ON) or as a static library (OFF). Its default value is OFF. On Windows, shared libraries may be used when building with MinGW, including mingw-w64, but not when building with the Microsoft toolchain.
```

I will give a try to compile it with LLVM_LINK_LLVM_DYLIB=ON but before I do I was just wondering if anybody has already tried this.

**Comment by mati865** [comment]
It was disabled by https://github.com/msys2/MINGW-packages/commit/85a6ffa028d473c741b3a41be13904f1eb12a8de. Probably there were issues when linking LLDB.

**Comment by adrpo** [comment]
> It was disabled by [85a6ffa](https://github.com/msys2/MINGW-packages/commit/85a6ffa028d473c741b3a41be13904f1eb12a8de). Probably there were issues when linking LLDB.

Thanks for the pointer! I will give it a try anyway, maybe the situation has improved in the meantime. I'll let you know how it goes.

**Comment by adrpo** [comment]
Fixed. Closing.
