### ISSUE TITLE
Dependency gstreamer-1.0 found: NO (tried pkgconfig and cmake)

### ISSUE THREAD

**Issue by pk-a** [msys2/MINGW-packages#6076]
Hi,

I have installed on msys2 and gstreamer using pacman. I've tested videotestsrc plugin and it ran successfully.

I am trying to build the gst-plugin-good from msys2. I have installed python3, python3-setuptools, ninja, meson and cmake.

When I run command meson build, I see below error. Any help would be really appreciable

Message: Disabling deprecated GLib API
Has header "dlfcn.h" : NO
Has header "fcntl.h" : YES
Has header "inttypes.h" : YES
Has header "memory.h" : YES
Has header "process.h" : YES
Has header "stdint.h" : YES
Has header "stdlib.h" : YES
Has header "strings.h" : YES
Has header "string.h" : YES
Has header "sys/ioctl.h" : NO
Has header "sys/param.h" : YES
Has header "sys/socket.h" : NO
Has header "sys/stat.h" : YES
Has header "sys/time.h" : YES
Has header "sys/types.h" : YES
Has header "unistd.h" : YES
Library m found: YES
Checking for function "asinh" with dependency -lm: YES
Checking for function "clock_gettime" with dependency -lm: YES
Checking for function "cosh" with dependency -lm: YES
Checking for function "dcgettext" with dependency -lm: YES
Checking for function "getpagesize" with dependency -lm: NO
Checking for function "isinf" with dependency -lm: YES
Checking for function "mmap" with dependency -lm: NO
Checking for function "mmap64" with dependency -lm: NO
Checking for function "sinh" with dependency -lm: YES
Checking for function "gmtime_r" with dependency -lm: NO
Checking for size of "char" : 1
Checking for size of "int" : 4
Checking for size of "long" : 4
Checking for size of "short" : 2
Checking for size of "void*" : 8
Checking for size of "off_t" : 4
Compiler for C supports arguments -Wmissing-declarations: YES
Compiler for C++ supports arguments -Wmissing-declarations: YES
Compiler for C supports arguments -Wredundant-decls: YES
Compiler for C++ supports arguments -Wredundant-decls: YES
Compiler for C supports arguments -Wwrite-strings: YES
Compiler for C++ supports arguments -Wwrite-strings: YES
Compiler for C supports arguments -Winit-self: YES
Compiler for C++ supports arguments -Winit-self: YES
Compiler for C supports arguments -Wmissing-include-dirs: YES
Compiler for C++ supports arguments -Wmissing-include-dirs: YES
Compiler for C supports arguments -Wno-multichar -Wmultichar: YES
Compiler for C++ supports arguments -Wno-multichar -Wmultichar: YES
Compiler for C supports arguments -Wvla: YES
Compiler for C++ supports arguments -Wvla: YES
Compiler for C supports arguments -Wpointer-arith: YES
Compiler for C++ supports arguments -Wpointer-arith: YES
Compiler for C supports arguments -Wmissing-prototypes: YES
Compiler for C supports arguments -Wdeclaration-after-statement: YES
Compiler for C supports arguments -Wold-style-definition: YES
Compiler for C supports arguments -Waggregate-return: YES
Found pkg-config: C:\msys64\usr\bin/pkg-config.EXE (0.29.2)
Found CMake: C:\msys64\mingw64\bin/cmake.EXE (3.14.4)
**Dependency gstreamer-1.0 found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency gstreamer-1.0

meson.build:237:0: ERROR: Subproject directory not found and gstreamer.wrap file not found**

**Comment by pk-a** [comment]
@lazka 

Thank you for your response!
I had gst-plugin-base installed already.

I have now found the problem. 
Gstreamer plugins installed on msys2 via pacman has version 1.16
However gst-plugins-good sources are moved to 1.17. Now I went back to gst-plugins-good sources of version 1.16.
With above change the meson build is successful. I have tested and verified the built binaries.

**Comment by lazka** [comment]
yeah, looks like the always depend on the dev versions automatically: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/blob/b928517f1ebbe89cce903daa0011bb1307e6aabd/meson.build#L24
