### ISSUE TITLE
Please package cmake 3.16 - required for boost 1.72

### ISSUE THREAD

**Issue by gusnan** [msys2/MINGW-packages#6077]
cmake pre 3.16 doesn't find boost 1.72 (already packaged) properly - see this cmake upstream issue:

https://gitlab.kitware.com/cmake/cmake/issues/20100

Please package cmake 3.16.2.

**Comment by umarcor** [comment]
The current cmake version is 3.19.1: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-cmake/PKGBUILD#L7. Can this issue be closed?

**Comment by gusnan** [comment]
Sure.

**Comment by gusnan** [comment]
Closing.
