### ISSUE TITLE
[dwrite.h] bug - missing closing bracket when compiling as MINGW32/64 c-code

### ISSUE THREAD

**Issue by jannick0** [msys2/MINGW-packages#6081]
Scrambled brackets in `dwrite.h` when compiling as `c` code, both `MINGW32` and `MINGW64`. Compilation as `c++` code is OK. 
~~~
...@... MINGW64 ~
$ echo '#include <dwrite.h>' | gcc -c -xc -
In file included from <stdin>:1:
C:/msys64/mingw64/x86_64-w64-mingw32/include/dwrite.h:2315: error: unterminated argument list invoking macro "STDMETHOD"
 2315 | #endif /* __INC_DWRITE__ */
      |
In file included from <stdin>:1:
C:/msys64/mingw64/x86_64-w64-mingw32/include/dwrite.h:1433:5: error: expected specifier-qualifier-list before 'STDMETHOD'
 1433 |     STDMETHOD(CreateStreamFromKey(THIS_ const void *fontFileReferenceKey,UINT32 fontFileReferenceKeySize,IDWriteFontFileStream **fileStream) PURE;
      |     ^~~~~~~~~
~~~

**Comment by Biswa96** [comment]
Try to include windows.h first.

**Comment by jannick0** [comment]
> Try to include windows.h first.

Umm, but this would not remedy the **syntax error** in `dwrite.h`.

**Comment by Biswa96** [comment]
You can send a patch to [mingw-w64 mailing list](https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/).

**Comment by Biswa96** [comment]
Hmm... There is a closing parenthesis missing. You can send a patch to [mingw-w64 mailing list](https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/).

**Comment by jannick0** [comment]
> Hmm... There is a closing parenthesis missing. 

Yes, that is what the item title says. ;)

> You can send a patch to [mingw-w64 mailing list](https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/).

Thanks - xref  [upstream bug report](https://sourceforge.net/p/mingw-w64/bugs/822/).
