### ISSUE TITLE
msys-gstvideotestsrc.dll generated by Autogen build on msys2 is not detected by gst-inspect

### ISSUE THREAD

**Issue by pk-a** [msys2/MINGW-packages#6083]
Hi,

I have installed gstreamer and packages like base, good. Also installed these - python3, python3-setuptools, ninja, meson and cmake,  on my windows machine. I have tested videotestsrc plugin and it works successfully

Now, I am trying to build gst-plugins-base (version 1.16) on msys2 using Autogen. All the steps (autogen.sh, configure and make) are successful and the binaries are generated. 

I replaced original videotestsrc  with generated one msys-gstvideotestsrc.dll. But it is not found by gst-inspect command. Also, tried by renaming msys-gstvideotestsrc.dll to libgstvideotestsrc.dll, but no success.

Below is the error.
$ gst-inspect-1.0.exe msys-gstvideotestsrc
(gst-inspect-1.0:31088): GStreamer-WARNING **: 12:59:00.968: Failed to load plugin 'C:\msys64\mingw64\lib\gstreamer-1.0\msys-gstvideotestsrc.dll': 'C:\msys64\mingw64\lib\gstreamer-1.0\msys-gstvideotestsrc.dll': The specified module could not be found.
No such element or plugin 'msys-gstvideotestsrc'

1. Any idea what could be the reason? 
2. Is this an issue due to library name "msys-*"? If this is true is it possible to change the names automatically at build time?

Any pointers would be really helpful. Thank you in advance !

**Comment by lazka** [comment]
The "msys-" part means you didn't use the mingw toolchain, but the msys/cygwin one. Make sure you have `mingw-w64-x86_64-toolchain` installed and start the mingw64 environment.

(also, meson is faster...)

**Comment by pk-a** [comment]
Hi @lazka 

Thank you for your response !
- I am actually using the mingw64 toolchain. Below is list that I have installed on my setup.

mingw-w64-x86_64-binutils 2.30-5 (mingw-w64-x86_64-toolchain)
mingw-w64-x86_64-crt-git 7.0.0.5449.a0647123-1 (mingw-w64-x86_64-toolchain)
mingw-w64-x86_64-gcc 8.3.0-2 (mingw-w64-x86_64-toolchain)
mingw-w64-x86_64-gcc-libgfortran 8.3.0-2 (mingw-w64-x86_64-toolchain)
mingw-w64-x86_64-gcc-libs 8.3.0-2 (mingw-w64-x86_64-toolchain)
mingw-w64-x86_64-headers-git 7.0.0.5449.a0647123-1 (mingw-w64-x86_64-toolchain)
mingw-w64-x86_64-libwinpthread-git 7.0.0.5447.a2d94c81-1 (mingw-w64-x86_64-toolchain)
mingw-w64-x86_64-pkg-config 0.29.2-1 (mingw-w64-x86_64-toolchain)
mingw-w64-x86_64-tools-git 7.0.0.5394.0dfb3d3f-1 (mingw-w64-x86_64-toolchain)
mingw-w64-x86_64-winpthreads-git 7.0.0.5447.a2d94c81-1 (mingw-w64-x86_64-toolchain)

- Though, Meson build is successful on my setup and works perfectly. But, I would like to get autogen build working for some reason.
- My initial guess was the prefix "msys-" that is added by autogen toolchain is a problem.
- Please note: msys-gstvideotestsrc.dll (from Autogen build) and  libgstvideotestsrc.dll (from Meson build) are of approx same size. This makes me believe that the binary generation is not a problem.

So could that be just the name of generated dll? Am I missing any other steps?

**Comment by lazka** [comment]
No idea. Here is the PKGBUILD we used for building gst-plugins-base with autotools before we switched to meson: https://github.com/msys2/MINGW-packages/blob/efd1bcf9e22a6fb1f2e8359bec70bcebd3023437/mingw-w64-gst-plugins-base/PKGBUILD

**Comment by pk-a** [comment]
Ok. I will check it. Thank you !
