### ISSUE TITLE
python-pillow Image import broken

### ISSUE THREAD

**Issue by lovetox** [msys2/MINGW-packages#6085]
```
$ python
Python 3.8.1 (default, Dec 24 2019, 11:55:37)  [GCC 9.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.8/site-packages/PIL/Image.py", line 90, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: Das angegebene Modul wurde nicht gefunden.
>>>
```

This is after fully updating the whole enviroment, i think this is probably fallout from the python3 -> python migration

**Comment by Alexpux** [comment]
I can’t reproduce it on my computer

**Comment by lovetox** [comment]
hm yeah weird, any idea why this could happen?

I have this problem on a appveyor vm also

**Comment by Alexpux** [comment]
Maybe some missing dependencies. Try to monitor what happen with procmon

**Comment by lovetox** [comment]
Yeah the dll is there, i think _imaging-cpython-38.dll was probably compiled against other libs that got an update?

**Comment by lazka** [comment]
Does `pacman -S mingw-w64-x86_64-libimagequant` help?

**Comment by lovetox** [comment]
Yes that solves it, thanks @lazka

**Comment by lazka** [comment]
Thanks for testing. We'll need to add it as a dependency.
