### ISSUE TITLE
[fftw] fftwf_make_planner_thread_safe missing

### ISSUE THREAD

**Issue by alex-tee** [msys2/MINGW-packages#6103]
`fftw_make_planner_thread_safe ()` works but the single precision version (`fftwf_make_planner_thread_safe ()`) doesn't work. it fails at link time.

This is the error I get:
```
undefined reference to `fftwf_make_planner_thread_safe'
```

Is the package missing this?

**Comment by lazka** [comment]
No idea but maybe this helps: https://github.com/FFTW/fftw3/issues/16#issuecomment-138600776

**Comment by alex-tee** [comment]
nevermind, I just realized there's separate pkg-config entries for fftw3 and fftw3f in msys2. adding a dependency to the fftw3f one fixed this.

sorry for the noise, it's pretty confusing since every distro decides to do it differently, but it's not msys2's problem. closing

**Comment by lazka** [comment]
Ah, ok, thanks for the update :)

(you can see the files included in a package here btw: https://packages.msys2.org/package/mingw-w64-x86_64-fftw)

**Comment by Kreijstal** [comment]
How did you solve this problem exactly? I got this bug too

**Comment by Biswa96** [comment]
Link with `fftw3_threads` library.

**Comment by Kreijstal** [comment]
> Link with `fftw3_threads` library.

thank you so much..
Is there a reason why can't msys2 patch pkgconfig so it does this automatically.. just asking

**Comment by Thomas-Sparber** [comment]
Hi, I had the same issue, after doing some research I found out that this function is only defined in fftw version 3.3.5.

I had version 3.3.10 installed which did not work. After manually downgrading to 3.3.5 I was able to link successfully. [(Discussion in Ardour forum)](https://debian-bugs-dist.debian.narkive.com/DlCz97qJ/bug-849589-ardour-undefined-symbol-fftwf-make-planner-thread-safe)

**Comment by Kreijstal** [comment]
> Hi, I had the same issue, after doing some research I found out that this function is only defined in fftw version 3.3.5.
> 
> I had version 3.3.10 installed which did not work. After manually downgrading to 3.3.5 I was able to link successfully. [(Discussion in Ardour forum)](https://debian-bugs-dist.debian.narkive.com/DlCz97qJ/bug-849589-ardour-undefined-symbol-fftwf-make-planner-thread-safe)
there is a recipe for ardour https://github.com/msys2/MINGW-packages/pull/20189 you can use it
