### ISSUE TITLE
Qt download is so inefficient...

### ISSUE THREAD

**Issue by abdulbadii** [msys2/MINGW-packages#6110]
Why is some such Qt, the download is very inefficient
```

Packages (1) mingw-w64-x86_64-qt5-static-5.13.1-1
            
Total Download Size:   1778.62 MiB
Total Installed Size:  7844.05 MiB
Net Upgrade Size:        60.73 MiB
```

only get net upgrade 61 MiB with the so expensive cost 1.7 GB ?

How to solve this ? Thanks

**Comment by oscarfv** [comment]
An update contains the whole package. Those 60 MB just indicate that the uncompressed size of the new version is 60 MB larger than the prior version, but surely the differences between the respective packages amount to a much larger extent.

Anyway, `pacman` does not support diff-based package upgrades.

If this answers your question, please close this issue. Thanks.
