### ISSUE TITLE
[wxWidgets] Update python dependency

### ISSUE THREAD

**Issue by MaartenBent** [msys2/MINGW-packages#6131]
When looking at https://packages.msys2.org/python2 I noticed `wxWidgets` has python2 as build dependency.
There is one script that might run during make (`src/stc/gen_iface.py`) and it supports python3 since wxWidgets 3.0.0: https://github.com/wxWidgets/wxWidgets/commit/016a3d4cee0ccf91904f01a89c417cdafea097d8

**Comment by lazka** [comment]
Thanks, changed in #6135
