### ISSUE TITLE
What should I downgrade to target Windows XP?

### ISSUE THREAD

**Issue by tomay3000** [msys2/MINGW-packages#6137]
Hello,
according to this issue #5139,
I have bypassed the `GetTickCount64` error by downgrading `libwinpthread` and `winpthreads`. and then I faced the problem of `InitializeConditionVariable`, this time I should downgrade another library but which one?

TIA.

**Comment by tomay3000** [comment]
I have traced back the issue until I found it cause which is `libtiff-5.dll` which in turns starting from version `4.0.10` will link and depend on `libzstd.dll` which in turns calls `InitializeConditionVariable()` which is only available starting from `Windows Vista`.
So I had to downgrade `libtiff` to version `4.0.9` to be able to launch my application under `Windows XP`

**Comment by lazka** [comment]
It's a bit unclear, most upstreams also have dropped XP for some time now.

Note that there have been 6 CVEs fixed between libtiff 4.0.10 and the latest 4.1.0 release.

**Comment by tomay3000** [comment]
if you have clients who are still using `Windows XP` and insist for supporting it, I believe you will have no choice but to downgrade these three libraries: `libtiff`, `winpthread` and `libwinpthread` to keep the lead of your software in the market.

**Comment by oscarfv** [comment]
You can use Dependency Walker to pinpoint dlls that reference undefined symbols. Of course, you must run it on Windows XP.

Probably there are lots of packages on the repo that are incompatible with XP and the number will grow on the future. If you want to keep supporting XP, the best thing you can do is to freeze your packages, which means stop updating.

There are no interest on keeping XP compatibility, for good reasons. I also have some users with XP: they know that new versions of my software are incompatible with their OS. If they insist on using an unmaintained, unsafe and obsolete OS, surely they can also keep using an old version of my software.

If this answers your question please close the issue. Thanks.

**Comment by nomennescio** [comment]
Google brought me here. Just for completeness sake; many embedded systems still run XP and are typically hardened or not connected to the internet, therefore safe. So there is still a (niche) use case for that.
