### ISSUE TITLE
[python-cx_Freeze] Error with tkinter path

### ISSUE THREAD

**Issue by mrichez** [msys2/MINGW-packages#6139]
Hi,
Got a problem with version  mingw-w64-x86_64-python-cx_Freeze-6.0-1
Can't find path to tkinter (error: [Errno 2] No such file or directory: 'C:/msys64/mingw64/tcl/tcl8.6')
I try to add path in setup-freeze.py:
...
include_files = [
    r"C:\msys64\mingw64\bin\tcl86.dll",
    r"C:\msys64\mingw64\bin\tk86.dll",]

os.environ['TCL_LIBRARY'] = r'C:\msys64\mingw64\lib\tcl8.6'
os.environ['TK_LIBRARY'] = r'C:\msys64\mingw64\lib\tk8.6'
....
Got this error: error: [Errno 2] No such file or directory: 'C:/msys64/mingw64/Dlls/tcl86t.dll'
tcl86t.dll doesn't exist, my file is tcl86.dll

Thanks for help!

**Comment by StarWolf3000** [comment]
The way it looks for the file indicates that it's trying to use the path of a standalone installation on Windows. There's no Dlls directory in the Python packages for MINGW.

**Comment by mrichez** [comment]
Package mingw-w64-x86_64-tk-8.6.10-1 is installed, and  mingw-w64-x86_64-python-cx_Freeze-6.0-1 also.
So problem is tk or cx_freeze? Don't know where path with ../Dlls/... come from...

**Comment by mrichez** [comment]
I try the sample  ('python setup.py build'): 
C:\msys64\mingw64\lib\python3.8\site-packages\cx_Freeze\samples\Tkinter

Got:
...
copying C:/msys64/mingw64/tcl/tcl8.6 -> build/exe.mingw-3.8/tcl
error: [Errno 2] No such file or directory: 'C:/msys64/mingw64/tcl/tcl8.6'

**Comment by mrichez-saluc** [comment]
Can bypass error doing this:

- Create С:\msys64\mingw64\tcl directory and copy into it these directories:
    C:\msys64\mingw64\lib\tcl8.6
    C:\msys64\mingw64\lib\tk8.6
- Create С:\msys64\mingw64\Dlls directory and copy into it these files:
    C:\msys64\mingw64\bin\tcl86.dll
    C:\msys64\mingw64\bin\tk86.dll
- Rename these files in С:\msys64\mingw64\Dlls directory:
    tcl86.dll -> tcl86t.dll
    tk86.dll -> tk86t.dll

**Comment by mrichez** [comment]
Could be linked to this issue: https://github.com/anthony-tuininga/cx_Freeze/pull/559
Could you update package to latest version of cx_freeze ? Thanks!

**Comment by marcelotduarte** [comment]
cx_Freeze 6.2 has just been released.
PR https://github.com/marcelotduarte/cx_Freeze/pull/642 correct copy files of tkinter
The issue can be closed.

**Comment by marcelotduarte** [comment]
@lazka You can close this issue.

**Comment by lazka** [comment]
thanks
