### ISSUE TITLE
gtk4 32 bit crashes

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#6144]
Running the 32 bit demo application crashes with a pointer to the graphene dll.

Also there is a bug in the meson build script in this section ->

```
if graphene_has_sse2 or graphene_has_gcc
  message('Need aligned memory due to the use of SSE2 or GCC vector instructions')

  if os_win32 and cc.get_id() == 'gcc'
    add_global_arguments(['-mstackrealign'], language: 'c')
  endif
endif
```

should probably be ->

```
if graphene_has_sse2 or graphene_has_gcc
  message('Need aligned memory due to the use of SSE2 or GCC vector instructions')

  if os_win32 and cc.get_id() == 'gcc'
    add_project_arguments(['-mstackrealign'], language: 'c')
  endif
endif
```

**Comment by revelator** [comment]
> Starting program: C:\msys64\mingw32\bin\gtk4-demo.exe
[New Thread 4176.0x226c]
[New Thread 4176.0x2260]
[New Thread 4176.0x1700]
[New Thread 4176.0x22d8]
[New Thread 4176.0x2310]
[New Thread 4176.0x1abc]
[New Thread 4176.0x2308]
[New Thread 4176.0x1a3c]
[New Thread 4176.0x1a74]
[New Thread 4176.0x1da4]
[New Thread 4176.0xb30]
[New Thread 4176.0xc5c]
[New Thread 4176.0x17e4]

Program received signal SIGSEGV, Segmentation fault.
0x6f0d0cfc in graphene_vec4_init_from_vec4 ()
   from C:\msys64\mingw32\bin\libgraphene-1.0-0.dll
(gdb)

**Comment by lazka** [comment]
> Also there is a bug in the meson build script in this section ->

This has been fixed some time ago: https://gitlab.gnome.org/GNOME/gtk/commit/23e4d05383805a679ba8fb440612849d5d0de5c1

It's probably best if you work with gtk4 master or wait for the next snapshot release.

**Comment by lazka** [comment]
.. and once you do report things upstream, they have a msys2 CI.

**Comment by revelator** [comment]
Hmm not sure what went wrong there, 
this mingw-packages pull was from yesterday and the meson build script bug was found there.
Git having hiccups maybe ?

**Comment by lazka** [comment]
Our PKGBUILD builds the last released development snapshot of gtk4 which was released 8 months ago.

**Comment by catconstructor** [comment]
Hello! How can i fix it? (i'm noob in it)
