### ISSUE TITLE
broken ffmpeg or libx264 or ... ?

### ISSUE THREAD

**Issue by arosella** [msys2/MINGW-packages#6145]
USER@MACHINE MINGW64 ~
$ pacman -Ss ffmpeg
mingw32/mingw-w64-i686-ffmpeg 4.2.2-1
    Complete and free Internet live audio and video broadcasting solution (mingw-w64)
mingw32/mingw-w64-i686-ffms2 2.23.1-1
    A cross-platform wrapper library around libav/FFmpeg (mingw-w64)
mingw64/mingw-w64-x86_64-ffmpeg 4.2.2-1 [installed]
    Complete and free Internet live audio and video broadcasting solution (mingw-w64)
mingw64/mingw-w64-x86_64-ffms2 2.23.1-1 [installed]
    A cross-platform wrapper library around libav/FFmpeg (mingw-w64)

USER@MACHINE MINGW64 ~
$ ffmpeg
C:/msys64/mingw64/bin/ffmpeg.exe: error while loading shared libraries: swscale-5.dll: cannot open shared object file: No such file or directory

USER@MACHINE MINGW64 ~
$ strace ffmpeg
create_child: ffmpeg
--- Process 11736 created
--- Process 11736 loaded C:\Windows\System32\ntdll.dll at 00007ffc36610000
--- Process 11736 loaded C:\Windows\System32\kernel32.dll at 00007ffc35aa0000
--- Process 11736 loaded C:\Windows\System32\KernelBase.dll at 00007ffc32da0000
--- Process 11736 loaded C:\Windows\System32\msvcrt.dll at 00007ffc35900000
--- Process 11736 thread 15952 created
--- Process 11736 loaded C:\Windows\System32\shell32.dll at 00007ffc338a0000
--- Process 11736 loaded C:\Windows\System32\cfgmgr32.dll at 00007ffc32b50000
--- Process 11736 loaded C:\Windows\System32\ucrtbase.dll at 00007ffc32a50000
--- Process 11736 thread 15856 created
--- Process 11736 loaded C:\Windows\System32\SHCore.dll at 00007ffc363e0000
--- Process 11736 loaded C:\Windows\System32\rpcrt4.dll at 00007ffc35760000
--- Process 11736 loaded C:\Windows\System32\combase.dll at 00007ffc353b0000
--- Process 11736 loaded C:\Windows\System32\bcryptprimitives.dll at 00007ffc32ba0000
--- Process 11736 thread 12468 created
--- Process 11736 loaded C:\Windows\System32\windows.storage.dll at 00007ffc33080000
--- Process 11736 loaded C:\Windows\System32\msvcp_win.dll at 00007ffc32d00000
--- Process 11736 loaded C:\Windows\System32\sechost.dll at 00007ffc36490000
--- Process 11736 loaded C:\Windows\System32\advapi32.dll at 00007ffc36330000
--- Process 11736 loaded C:\Windows\System32\profapi.dll at 00007ffc32660000
--- Process 11736 loaded C:\Windows\System32\powrprof.dll at 00007ffc32600000
--- Process 11736 loaded C:\Windows\System32\shlwapi.dll at 00007ffc35a40000
--- Process 11736 loaded C:\Windows\System32\gdi32.dll at 00007ffc35ce0000
--- Process 11736 loaded C:\Windows\System32\gdi32full.dll at 00007ffc326d0000
--- Process 11736 loaded C:\Windows\System32\user32.dll at 00007ffc36190000
--- Process 11736 loaded C:\Windows\System32\win32u.dll at 00007ffc33060000
--- Process 11736 loaded C:\Windows\System32\kernel.appcore.dll at 00007ffc326b0000
--- Process 11736 loaded C:\Windows\System32\cryptsp.dll at 00007ffc33040000
--- Process 11736 loaded C:\msys64\mingw64\bin\avdevice-58.dll at 00007ffc0cf70000
--- Process 11736 loaded C:\msys64\mingw64\bin\avfilter-7.dll at 00007ffbe0f40000
--- Process 11736 loaded C:\msys64\mingw64\bin\avformat-58.dll at 00007ffbe0d00000
--- Process 11736 loaded C:\msys64\mingw64\bin\avcodec-58.dll at 00007ffbbfa80000
--- Process 11736 loaded C:\Windows\System32\ole32.dll at 00007ffc350e0000
--- Process 11736 loaded C:\Windows\System32\ws2_32.dll at 00007ffc359a0000
--- Process 11736 loaded C:\Windows\System32\ole32.dll at 0000023bdf680000
--- Process 11736 unloaded DLL at 0000023bdf680000
--- Process 11736 loaded C:\Windows\System32\oleaut32.dll at 00007ffc35b70000
--- Process 11736 loaded C:\msys64\mingw64\bin\avutil-56.dll at 00007ffbf4b10000
--- Process 11736 loaded C:\Windows\System32\bcrypt.dll at 00007ffc32c20000
--- Process 11736 loaded C:\msys64\mingw64\bin\swresample-3.dll at 00007ffc07980000
--- Process 11736 loaded C:\msys64\mingw64\bin\swscale-5.dll at 00007ffbf6690000
--- Process 11736 loaded C:\msys64\mingw64\bin\libass-9.dll at 000000006f7c0000
--- Process 11736 loaded C:\msys64\mingw64\bin\postproc-55.dll at 00007ffc07340000
--- Process 11736 loaded C:\msys64\mingw64\bin\libfontconfig-1.dll at 0000000064f80000
--- Process 11736 loaded C:\msys64\mingw64\bin\libfreetype-6.dll at 000000006aa40000
--- Process 11736 loaded C:\msys64\mingw64\bin\libmfx-1.dll at 000000006d8c0000
--- Process 11736 loaded C:\msys64\mingw64\bin\libbluray-2.dll at 000000006f9c0000
--- Process 11736 loaded C:\msys64\mingw64\bin\libbz2-1.dll at 00000000626c0000
--- Process 11736 loaded C:\msys64\mingw64\bin\libgnutls-30.dll at 0000000064840000
--- Process 11736 loaded C:\msys64\mingw64\bin\libiconv-2.dll at 0000000066000000
--- Process 11736 loaded C:\Windows\System32\crypt32.dll at 00007ffc32870000
--- Process 11736 loaded C:\msys64\mingw64\bin\libwinpthread-1.dll at 0000000000350000
--- Process 11736 unloaded DLL at 0000000000350000
--- Process 11736 loaded C:\Windows\System32\msasn1.dll at 00007ffc32690000
--- Process 11736 loaded C:\msys64\mingw64\bin\libmodplug-1.dll at 000000006cb80000
--- Process 11736 loaded C:\msys64\mingw64\bin\libcelt0-2.dll at 0000000064ac0000
--- Process 11736 loaded C:\msys64\mingw64\bin\librtmp-1.dll at 000000006da40000
--- Process 11736 loaded C:\msys64\mingw64\bin\libgsm.dll at 0000000070800000
--- Process 11736 loaded C:\msys64\mingw64\bin\libsrt.dll at 0000000069d00000
--- Process 11736 loaded C:\msys64\mingw64\bin\zlib1.dll at 0000000062e80000
--- Process 11736 loaded C:\msys64\mingw64\bin\liblzma-5.dll at 0000000063cc0000
--- Process 11736 loaded C:\msys64\mingw64\bin\libmp3lame-0.dll at 000000006eb80000
--- Process 11736 loaded C:\msys64\mingw64\bin\libopencore-amrnb-0.dll at 000000006f540000
--- Process 11736 loaded C:\msys64\mingw64\bin\libopenjp2-7.dll at 0000000000350000
--- Process 11736 loaded C:\msys64\mingw64\bin\libopencore-amrwb-0.dll at 0000000066bc0000
--- Process 11736 loaded C:\msys64\mingw64\bin\libopus-0.dll at 0000000062500000
--- Process 11736 unloaded DLL at 0000000000350000
--- Process 11736 loaded C:\msys64\mingw64\bin\libspeex-1.dll at 0000000069580000
--- Process 11736 loaded C:\msys64\mingw64\bin\libtheoraenc-1.dll at 0000000063100000
--- Process 11736 loaded C:\msys64\mingw64\bin\libtheoradec-1.dll at 0000000065b40000
--- Process 11736 loaded C:\msys64\mingw64\bin\libvorbis-0.dll at 000000006d540000
--- Process 11736 loaded C:\msys64\mingw64\bin\libvorbisenc-2.dll at 000000006b680000
--- Process 11736 loaded C:\msys64\mingw64\bin\libwavpack-1.dll at 0000000069180000
--- Process 11736 loaded C:\msys64\mingw64\bin\libwebp-7.dll at 0000000061940000
--- Process 11736 loaded C:\msys64\mingw64\bin\libvpx-1.dll at 0000000066280000
--- Process 11736 loaded C:\msys64\mingw64\bin\xvidcore.dll at 0000000001660000
--- Process 11736 loaded C:\msys64\mingw64\bin\libx265.dll at 0000000000350000
--- Process 11736 unloaded DLL at 0000000001660000
--- Process 11736 unloaded DLL at 0000000000350000
--- Process 11736 loaded C:\msys64\mingw64\bin\libwebpmux-3.dll at 00000000705c0000
--- Process 11736 loaded C:\msys64\mingw64\bin\libopenal-1.dll at 0000000000350000
--- Process 11736 loaded C:\msys64\mingw64\bin\libcaca-0.dll at 0000000069f40000
--- Process 11736 unloaded DLL at 0000000000350000
--- Process 11736 loaded C:\Windows\System32\avicap32.dll at 00007ffc173b0000
--- Process 11736 loaded C:\msys64\mingw64\bin\SDL2.dll at 000000006c6f0000
--- Process 11736 loaded C:\msys64\mingw64\bin\libharfbuzz-0.dll at 0000000061600000
--- Process 11736 loaded C:\Windows\System32\imm32.dll at 00007ffc35a10000
--- Process 11736 loaded C:\Windows\System32\setupapi.dll at 00007ffc35d10000
--- Process 11736 loaded C:\msys64\mingw64\bin\libgcc_s_seh-1.dll at 0000000061440000
--- Process 11736 loaded C:\msys64\mingw64\bin\libintl-8.dll at 0000000061cc0000
--- Process 11736 loaded C:\msys64\mingw64\bin\libexpat-1.dll at 0000000068f40000
--- Process 11736 loaded C:\msys64\mingw64\bin\libpng16-16.dll at 0000000068b40000
--- Process 11736 loaded C:\msys64\mingw64\bin\libstdc++-6.dll at 000000006fc40000
--- Process 11736 loaded C:\msys64\mingw64\bin\libxml2-2.dll at 0000000070f40000
--- Process 11736 loaded C:\msys64\mingw64\bin\libfribidi-0.dll at 0000000066600000
--- Process 11736 loaded C:\msys64\mingw64\bin\libhogweed-5.dll at 000000006c240000
--- Process 11736 loaded C:\msys64\mingw64\bin\libidn2-0.dll at 0000000063d00000
--- Process 11736 loaded C:\msys64\mingw64\bin\libgmp-10.dll at 000000006acc0000
--- Process 11736 loaded C:\msys64\mingw64\bin\libtasn1-6.dll at 0000000065f00000
--- Process 11736 loaded C:\msys64\mingw64\bin\libnettle-7.dll at 00000000669c0000
--- Process 11736 loaded C:\msys64\mingw64\bin\libunistring-2.dll at 0000000000350000
--- Process 11736 unloaded DLL at 0000000000350000
--- Process 11736 loaded C:\msys64\mingw64\bin\libp11-kit-0.dll at 0000000000350000
--- Process 11736 unloaded DLL at 0000000000350000
--- Process 11736 loaded C:\Windows\System32\winmm.dll at 00007ffc27fe0000
--- Process 11736 loaded C:\msys64\mingw64\bin\libcrypto-1_1-x64.dll at 0000000067e00000
--- Process 11736 loaded C:\msys64\mingw64\bin\libogg-0.dll at 0000000070880000
--- Process 11736 loaded C:\msys64\mingw64\bin\libogg-0.dll at 0000000000350000
--- Process 11736 unloaded DLL at 0000000000350000
--- Process 11736 loaded C:\Windows\System32\msvfw32.dll at 00007ffc06e50000
--- Process 11736 loaded C:\Windows\System32\wsock32.dll at 00007ffc2dcf0000
--- Process 11736 loaded C:\msys64\mingw64\bin\libglib-2.0-0.dll at 0000000000350000
--- Process 11736 unloaded DLL at 0000000000350000
--- Process 11736 loaded C:\msys64\mingw64\bin\libgraphite2.dll at 0000000070540000
--- Process 11736 loaded C:\Windows\System32\usp10.dll at 00007ffc2bd90000
--- Process 11736 loaded C:\Windows\System32\version.dll at 00007ffc29d00000
--- Process 11736 loaded C:\Windows\System32\winmmbase.dll at 00007ffc27f50000
--- Process 11736 loaded C:\Windows\System32\winmmbase.dll at 0000023bdf490000
--- Process 11736 unloaded DLL at 0000023bdf490000
--- Process 11736 loaded C:\Windows\System32\winmmbase.dll at 0000023bdf490000
--- Process 11736 unloaded DLL at 0000023bdf490000
--- Process 11736 loaded C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.17763.973_none_10e61004642cbda8\comctl32.dll at 00007ffc240d0000
--- Process 11736 thread 12468 exited with status 0x0
--- Process 11736 thread 15952 exited with status 0x0
--- Process 11736 thread 1180 exited with status 0xc0000135
--- Process 11736 exited with status 0xc0000135
C:/msys64/usr/bin/strace.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

In the popup was reported "can't find libx264-157.dll"

USER@MACHINE MINGW64 ~
$ ls /mingw64/bin/libx*
/mingw64/bin/libx264-159.dll  /mingw64/bin/libx265.dll  /mingw64/bin/libxapian-30.dll  /mingw64/bin/libxml2-2.dll  /mingw64/bin/libxslt-1.dll

USER@MACHINE MINGW64 ~
$ pacman -Ss x264
mingw32/mingw-w64-i686-x264-git r2991.1771b556-1
    Library for encoding H264/AVC video streams (mingw-w64)
mingw64/mingw-w64-x86_64-x264-git r2991.1771b556-1 [installed]
    Library for encoding H264/AVC video streams (mingw-w64)

**Comment by StarWolf3000** [comment]
I can confirm. `ffmpeg` package needs to be rebuilt. Current `x264-git` is linked against and ships with `libx264-159.dll`.
