### ISSUE TITLE
patchset for mingw-w64-headers and crt-git needs updating

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#6157]
Patches no longer apply since the directory structure changed in latest git pull, 
for instance the directx headers are no longer in direct-x/include but in include.

**Comment by Biswa96** [comment]
There may be no patch file required in future for mingw-w64-headers and crt package. Just [working on to import dxva2api.idl][1].

[1]: https://sourceforge.net/p/mingw-w64/mailman/message/36909372/

**Comment by revelator** [comment]
bessel patch also still applies it seems or is this one not nessesary anymore ?.

**Comment by Alexpux** [comment]
@Biswa96 tell when you finish to import dxva2api.idl and I will update mingw-w64 runtime then

**Comment by Biswa96** [comment]
Maybe today or tomorrow. I was sick last two days.

**Comment by Biswa96** [comment]
Patch was sent but no response from mingw-w64 maintainers.

**Comment by Alexpux** [comment]
@Biswa96 ping mingw-w64 thread

**Comment by Alexpux** [comment]
@Biswa96 I see answer of Jacek, seems importing from wine have regressions?

**Comment by Biswa96** [comment]
I sent a patch to wine 1week ago to fix it but it is not added in recent wine version 5.2. So, you can remain the dxva2api patch or wait for 2-3 days for the patch to be included in wine.

**Comment by Biswa96** [comment]
There is a new blender release. Could you compile it (and vlc) to check if we need any modification for mingw-w64 headers/libs? My PC would take days.

**Comment by Alexpux** [comment]
@Biswa96 ok i will update mingw-w64 to current state and try to build them

**Comment by Biswa96** [comment]
Patch is accepted in wine, waiting for mingw-w64 reply...

**Comment by Biswa96** [comment]
Patch is accepted in wine, waiting for mingw-w64 reply...

**Comment by Biswa96** [comment]
dxva2api.h atch imported in mingw-w64.

**Comment by revelator** [comment]
Cool :) allthough biggest problem atm building blender seems to be openshadinglanguage, i simply cannot build it (not even if i set paths to the dll dependency) the oslc parser still complains that it cannot execute it. i Suspect it has something to do with windows paths getting mangled in the msys shell but then nothing should work so ?!?.

**Comment by Biswa96** [comment]
Can `msys2-w32api-headers` be updated also?

**Comment by Alexpux** [comment]
@Biswa96 will do it later.

**Comment by revelator** [comment]
Works fine now :)
