### ISSUE TITLE
ogre3d 64 bit build crash

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#6164]
Program received signal SIGTRAP, Trace/breakpoint trap.
0x000000007765f230 in ntdll!RtlUnhandledExceptionFilter () from C:\Windows\system32\ntdll.dll

Looks like some code is freed without being initialized, strange thing though the 32 bit build works.

**Comment by revelator** [comment]
crash seems to originate from zziplib, rebuilding dependencies does not fix the crash actually it now also crashes the 32 bit build.

**Comment by revelator** [comment]
yep seems to be zziplib, it complains it cannot open SdkTrays.zip but both the file and path exists also the zip has no errors so im not sure whats going on. Uncommenting this file in the cfg leads to zzip complaining it cannot open the next file either. I have a nagging suspision that some change in either ogre or zziplib causes problems with relative paths.

**Comment by Neonit** [comment]
Maybe related: https://github.com/msys2/MINGW-packages/issues/7244

**Comment by revelator** [comment]
Seems to be ;)

**Comment by MehdiChinoune** [comment]
closing since the package has been updated
