### ISSUE TITLE
XMake - Build System

### ISSUE THREAD

**Issue by kassane** [msys2/MINGW-packages#6169]
Would it be possible to join this build system in the package?
[XMAKE_PKBUILD-ARCH](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xmake)

**Comment by Biswa96** [comment]
Is there any guideline about how to build xmake in Windows?

**Comment by kassane** [comment]
> 
> 
> Is there any guideline about how to build xmake in Windows?

https://github.com/xmake-io/xmake/blob/master/.appveyor.yml

**Comment by waruqi** [comment]
https://xmake.io/#/guide/installation?id=installation

I'm not sure I support using mingw/make to build xmake on windows.  Maybe we need modify some makefile and code files to support it.

Now we can only use xmake to build xmake or use nsis installation package to install it.directly

**Comment by Biswa96** [comment]
The core/makefile may need to be changed, here are some outputs:

```
make: Entering directory '/c/MyFiles/xmake/src'
compiling xmake-core ...
cp: cannot stat '/c/MyFiles/xmake/src/core/plat/mingw/config.h': No such file or directory
```

**Comment by Biswa96** [comment]
The core/makefile may need to be changed, here are some outputs:

```
make: Entering directory '/c/MyFiles/xmake/src'
compiling xmake-core ...
cp: cannot stat '/c/MyFiles/xmake/src/core/plat/mingw/config.h': No such file or directory
```

Also the architecture detection may be wrong. I am using MinGW-w64 X86_64 environment and here is the output:

```
compile:
    plat:               mingw
    arch:               x86
    host:               msys
    demo:               y
```

**Comment by waruqi** [comment]
I will add core/plat/mingw in these days.

**Comment by Biswa96** [comment]
Here is a sample PKGBUILD file to test https://github.com/Biswa96/MINGW-packages/blob/add-xmake/mingw-w64-xmake/PKGBUILD.

**Comment by waruqi** [comment]
I have improved xmake to compile it on mingw/msys. It has been compiled successfully on msys/mingw for xmake/dev branch.

compile and install xmake:

```console
make build
make install prefix=/usr
```

You can try it again. however, there are still some problems during operation, such as process execution. e.g. 

```console
$ xmake l os.exec "echo hello"
      1 [main] xmake 1887 dofork: child -1 - forked process 4512 died unexpectedly, retry 0, exit code 0xC0000135, errno 11
error: exec(echo hello) failed(-1)!
```

I attempt to run `cmd /c "c:\msys64\usr\bin\dash.exe /usr/bin/rebaseall -v"` command, seems to have no effect.

**Comment by StarWolf3000** [comment]
@waruqi Hold your horses. What is your build environment? From your last message it seems you're building under MSYS2, but in your opening comment you asked as package under MINGW. Do not mix them up.

The `prefix` for `make install` should be `/mingw32|64`, not `/usr`.

**Comment by waruqi** [comment]
> @waruqi Hold your horses. What is your build environment? From your last message it seems you're building under MSYS2, but in your opening comment you asked as package under MINGW. Do not mix them up.
> 
> The `prefix` for `make install` should be `/mingw32|64`, not `/usr`.

I have tested both the msys and mingw environments.

```console
ruki@DESKTOP-A6MFTOV MINGW64 ~
$ uname
MINGW64_NT-10.0-14393

ruki@DESKTOP-A6MFTOV MINGW64 ~
$ which xmake
/usr/bin/xmake

ruki@DESKTOP-A6MFTOV MINGW64 ~
$ xmake l os.exec "echo hello"
      1 [main] xmake 1000 dofork: child -1 - forked process 4844 died unexpectedly, retry 0, exit code 0xC0000135, errno 11
error: exec(echo hello) failed(-1)!
```

```console
ruki@DESKTOP-A6MFTOV MSYS ~
$ uname
MSYS_NT-10.0-14393

ruki@DESKTOP-A6MFTOV MSYS ~
$ which xmake
/usr/bin/xmake

ruki@DESKTOP-A6MFTOV MSYS ~
$ xmake l os.exec "echo hello"
      0 [main] xmake 1308 dofork: child -1 - forked process 1580 died unexpectedly, retry 0, exit code 0xC0000135, errno 11
error: exec(echo hello) failed(-1)!
```

**Comment by waruqi** [comment]
@Biswa96 


https://github.com/xmake-io/xmake/blob/dev/scripts/PKGBUILD

**Comment by StarWolf3000** [comment]
@waruqi Like I said, do not mixup MSYS2 and MINGW.

This line is wrong:
`$ make install prefix=/usr`

Should be:
`$ make install prefix=/mingw64` and `$ make install prefix=/mingw32`

MINGW binaries should NEVER go into `/usr/bin` and MSYS2 binaries should NEVER go into `/mingw32|64/bin`.

**Comment by waruqi** [comment]
> @waruqi Like I said, do not mixup MSYS2 and MINGW.
> 
> This line is wrong:
> `$ make install prefix=/usr`
> 
> Should be:
> `$ make install prefix=/mingw64` and `$ make install prefix=/mingw32`
> 
> MINGW binaries should NEVER go into `/usr/bin` and MSYS2 binaries should NEVER go into `/mingw32|64/bin`.

Got it, thanks! 

```console
$ pacman -S mingw-w64-x86_64-gcc
$ which gcc
/mingw64/bin/gcc
$ cd xmake
$ make build
$ make install prefix=/mingw64
```

**Comment by Biswa96** [comment]
The linked PKGBUILD does not work in mingw-w64-x86_64 but the dev branch complied successfully.

**Comment by waruqi** [comment]
> The linked PKGBUILD does not work in mingw-w64-x86_64 but the dev branch complied successfully.

I haven’t published a new release version, the 2.2.9 version in PKGBUILD cannot be compiled. I only update PKGBUILD to use `make install` instead of `package() {}` scripts.

**Comment by waruqi** [comment]
@Biswa96 I have published the release version (v2.3.1) and support mingw.

**Comment by Biswa96** [comment]
I have created a test PKGBUILD file. But it shows some error in `package` step. Here is the output:

```
==> Starting package()...
installing to /c/MyFiles/xmake/pkg/mingw-w64-x86_64-xmake ...
plat: msys
arch: x86_64
cp: cannot create regular file '/c/MyFiles/xmake/pkg/mingw-w64-x86_64-xmake/bin/xmake.exe': No such file or directory
make: *** [makefile:109: install] Error 1
```

**Comment by Biswa96** [comment]
Here is the link https://github.com/Biswa96/MINGW-packages/blob/add_xmake/mingw-w64-xmake/PKGBUILD

**Comment by StarWolf3000** [comment]
@Biswa96 Did you use `makepkg` or `mingw-makepkg` to run?

**Comment by Biswa96** [comment]
Both shows the error.

**Comment by waruqi** [comment]
> Here is the link https://github.com/Biswa96/MINGW-packages/blob/add_xmake/mingw-w64-xmake/PKGBUILD

I will look at it later.

**Comment by waruqi** [comment]
> I have created a test PKGBUILD file. But it shows some error in `package` step. Here is the output:
> 
> ```
> ==> Starting package()...
> installing to /c/MyFiles/xmake/pkg/mingw-w64-x86_64-xmake ...
> plat: msys
> arch: x86_64
> cp: cannot create regular file '/c/MyFiles/xmake/pkg/mingw-w64-x86_64-xmake/bin/xmake.exe': No such file or directory
> make: *** [makefile:109: install] Error 1
> ```

@Biswa96 It was because the pkg/bin directory was not created during running `make install`.

 I have fixed this problem in the dev branch. But in the current version, you can temporarily modify PKGBUILD to solve this problem.

```
package() {
    cd "$srcdir"
    mkdir "${pkgdir}/bin" .  <--  ensure to create bin directory
    make install prefix="${pkgdir}"
}
```

**Comment by Biswa96** [comment]
Some issues:

* The `/bin/xmake` file contains absolute path including the folder in which the package is built.
* Where is the executable after running `make install`?
* Why does `make build` automatically delete compiled object files? Shouldn't those be deleted with `make clean` command?

**Comment by waruqi** [comment]
> The /bin/xmake file contains absolute path including the folder in which the package is built.

This is indeed a problem, I need to improve `make install`.

> Where is the executable after running make install?

/mingw64/bin/xmake.exe

> Why does make build automatically delete compiled object files? Shouldn't those be deleted with make clean command?

It is just a legacy problem. `xmake/core/makefile` currently does not support uses depfile to incrementally compile, so `make clean` will be executed before `make build`.

core/makefile

```
build:
	@echo compiling xmake-core ...
	@if [ -f core/.config.mak ]; then rm core/.config.mak; fi
	@$(MAKE) -C core --no-print-directory f DEBUG=$(debug)
	@$(MAKE) -C core --no-print-directory c             <--------------- clean first
	@$(MAKE) -C core --no-print-directory
```

**Comment by waruqi** [comment]
@Biswa96 I have updated xmake-v2.3.1.tar.gz and imrpove `make install` script.

You can update PKGBUILD and try it again.

```
# Maintainer: <waruqi@gmail.com>

_realname=xmake
pkgbase=mingw-w64-${_realname}
pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
pkgver=2.3.1
pkgrel=1
pkgdesc="A make-like build utility based on Lua"
arch=('i686' 'x86_64')
url="https://github.com/xmake-io/xmake"
license=('Apache')
depends=("${MINGW_PACKAGE_PREFIX}-ncurses"
         "${MINGW_PACKAGE_PREFIX}-readline")
makedepends=("${MINGW_PACKAGE_PREFIX}-gcc")
source=("${_realname}-${pkgver}.tar.gz"::"https://github.com/xmake-io/${_realname}/releases/download/v${pkgver}/${_realname}-v${pkgver}.tar.gz")
sha256sums=('94ba21b4ca9586509b78d1bb1e788be966f19c5b9cb6f6ea8fcab26c69f9bda2')

build() {
    cd "$srcdir"
    make build
}

package() {
    cd "$srcdir"
    make install DESTDIR="${pkgdir}" PREFIX="/usr"
}
```

**Comment by Biswa96** [comment]
* `make install DESTDIR="${pkgdir}"` generates `export XMAKE_PROGRAM_DIR=/usr/local/share/xmake`.
* At least, `make install DESTDIR="${pkgdir}" prefix="${MINGW_PREFIX}"` creates correct path i.e. `/mingw64/bin/xmake.exe` but it does not exist. I think the `demo.b` is not copied.

**Comment by waruqi** [comment]
> * `make install DESTDIR="${pkgdir}"` generates `export XMAKE_PROGRAM_DIR=/usr/local/share/xmake`.
> * At least, `make install DESTDIR="${pkgdir}" prefix="${MINGW_PREFIX}"` creates correct path i.e. `/mingw64/bin/xmake.exe` but it does not exist. I think the `demo.b` is not copied.

I have fixed it, please update sha256 and redownload tar.gz to makepkg.

sha256sums=('7aea3ccd4cdd80efad6825761fd75b2de5813a72e08e7fc4b7c4eb0671d6ff28')

When run `mv /tmp/xmake /usr/bin/xmake`, it removed `/usr/bin/xmake.exe` on msys automatically. : (

**Comment by Biswa96** [comment]
Ohh... forgot to check the 32bit build. The 32bit build failed. See the linked PR CI build.

**Comment by waruqi** [comment]
> Ohh... forgot to check the 32bit build. The 32bit build failed. See the linked PR CI build.

You can try `make build ARCH=i386` first.

If it still fails, I'll take a look tomorrow.

**Comment by waruqi** [comment]
> Ohh... forgot to check the 32bit build. The 32bit build failed. See the linked PR CI build.

I have fixed it on mingw32, you can update sha256 and try it again.

b2e46d9b4dd48fb70d32a314ca4ba12d42b0b294f5e2179c5c09c56f9c52933b

**Comment by waruqi** [comment]
xmake have been merged. https://github.com/msys2/MINGW-packages/pull/6224

**Comment by StarWolf3000** [comment]
@waruqi Please close this.

**Comment by waruqi** [comment]
> @waruqi Please close this.

@StarWolf3000 I cannot close it.
@kassane Can you close this issues?

**Comment by waruqi** [comment]
Why has xmake been merged and I executed pacman to update the database and still can't find it?

```console
$ pacman -Syu
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
$ pacman -S mingw-w64-x86_64-xmake
error: target not found: mingw-w64-x86_64-xmake
```

**Comment by StarWolf3000** [comment]
@waruqi What you do here and what is done in the repositories is not synchronized. @Alexpux uploads the packages and updates the databases, when he has free time.

**Comment by waruqi** [comment]
@StarWolf3000 Got it, thanks!

**Comment by kassane** [comment]
I tested it using the following parameter and this error was reported. But it works at the command prompt.

> xmake f -p mingw --mingw=/mingw64

**output:**
``checking for the architecture ... x86_64``
``checking for the mingw directory ... C:/msys64/mingw64``

> xmake

**output:**
``[  0%]: ccache compiling.release src\main.cpp``
``error: ccache: error: Could not find compiler "C:\msys64\mingw64\bin\gcc" in PATH``

**Comment by waruqi** [comment]
> @waruqi
> I tested it using in msys-terminal the following parameter and this error was reported. But it works at the command prompt.
> 
> > xmake f -p mingw --mingw=/mingw64
> 
> **output:**
> `checking for the architecture ... x86_64`
> `checking for the mingw directory ... C:/msys64/mingw64`
> 
> > xmake
> 
> **output:**
> `[ 0%]: ccache compiling.release src\main.cpp`
> `error: ccache: error: Could not find compiler "C:\msys64\mingw64\bin\gcc" in PATH`

please open new issues in xmake/issues.

you can only uses the default platform on msys/mingw64

xmake f -c
xmake
