### ISSUE TITLE
Repository isn't updated since 2020-01-29

### ISSUE THREAD

**Issue by kou** [msys2/MINGW-packages#6182]
It seems that http://repo.msys2.org/mingw/ isn't updated since 2020-01-29.

https://github.com/msys2/MINGW-packages/commit/e93a7532e5c39048d2938e02421a0885b78073ce is applied but
https://github.com/msys2/MINGW-packages/commit/269ae225be28fecbc78e15bf8da472e87b2960e2 or later aren't applied.

**Comment by Alexpux** [comment]
@kou I dont have much time to build packages this time. So new packages will be in repository when i get time

**Comment by kou** [comment]
Thanks for your reply.
I thought that repository update is done automatically. So I thought that there is a system problem. Sorry.
You don't need to hurry.
