### ISSUE TITLE
Boost.locale for 1.72.0-1 package is built without ICU support

### ISSUE THREAD

**Issue by indrekis** [msys2/MINGW-packages#6183]
As a proof, libboost_locale-mt.dll form the mingw-w64-x86_64-boost-1.72.0-1 package does not depend on icu dlls.

It breaks applications dependent on boundary analysis -- non-ICU backends [does not support it](https://www.boost.org/doc/libs/1_48_0/libs/locale/doc/html/using_localization_backends.html). 

Workaround: downgrade to mingw-w64-x86_64-boost-1.71.0-3.

**Comment by lazka** [comment]
Likely fallout from 99ffbce6bffe1eed9, @Alexpux
