### ISSUE TITLE
Does not support inet_pton on MinGW?

### ISSUE THREAD

**Issue by zxgm** [msys2/MINGW-packages#6191]
Does not support inet_pton on MinGW?

**Comment by lazka** [comment]
it should be supported: https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-inet_pton

**Comment by Biswa96** [comment]
It's not in mingw-w64 repo, working...

**Comment by lazka** [comment]
https://github.com/mirror/mingw-w64/blob/1b5ae4b567ee1699f69cd918ae2bc693898edbb2/mingw-w64-headers/include/ws2tcpip.h#L455

**Comment by Biswa96** [comment]
But the actual function declaration isn't present.

**Comment by Biswa96** [comment]
@zxgm Can you provide any compiler error message or any minimal code to reproduce this issue?

**Comment by zxgm** [comment]
Thank you very much.I have found the reason,the macro _WIN32_WINNT value is 0x502 that was defined  in _mingw.h,so inet_pton is disabled in ws2tcpip.h.I redefine the macro _WIN32_WINNT value 0x0600,that is work.

**Comment by zxgm** [comment]
Now,I hit the other problems.The code is follow:

> setOption(IPPROTO_TCP, TCP_KEEPIDLE, &idle, sizeof(idle))
but compile the code use mingw,that error:

> error: 'TCP_KEEPIDLE' was not declared in this scope
On windows, the macro TCP_KEEPIDLE defined in ws2ipdef.h,but the same header file in MinGW,that have not TCP_KEEPIDLE,where was the macro TCP_KEEPIDLE  defined in MinGW?

**Comment by lazka** [comment]
Doesn't look like mingw-w64 has it. https://docs.microsoft.com/en-us/windows/win32/winsock/ipproto-tcp-socket-options states that it is only supported since Windows 10, which could explain it.

**Comment by zxgm** [comment]
Thanks a lot.I think mingw-w64 not support the macro 'TCP_KEEPIDLE' so far.

**Comment by Biswa96** [comment]
I may add that in a PR...
