### ISSUE TITLE
 gdb-9 crashing

### ISSUE THREAD

**Issue by SagarPohekar** [msys2/MINGW-packages#6196]
gdb-9.1-1 : 
gdb.exe: error while loading shared libraries: libgcc_s_seh-1.dll: cannot open shared object file: No such file or directory

**Comment by ChinouneMehdi** [comment]
I got a different error message:
```
$ gdb
D:/Programs/msys64/mingw64/bin/gdb.exe: error while loading shared libraries: libxxhash.dll: cannot open shared object file: No such file or directory
```

**Comment by SagarPohekar** [comment]
> 
> 
> I got a different error message:
> 
> ```
> $ gdb
> D:/Programs/msys64/mingw64/bin/gdb.exe: error while loading shared libraries: libxxhash.dll: cannot open shared object file: No such file or directory
> ```

I also observed this error if i directly open the gdb from normal windows command prompt
