### ISSUE TITLE
Qt5 5.14.1 hardcoded paths

### ISSUE THREAD

**Issue by Gator96100** [msys2/MINGW-packages#6198]
When trying to compile with Qt5 5.14.1 I get the error: `/bin/sh: D:/mingwbuild/mingw-w64-qt5/pkg/mingw-w64-x86_64-qt5/mingw64/bin/uic: No such file or directory`. I don’t even have a D:/ Drive, the path seems to be hardcoded into the qt5 exes.

**Comment by Alexpux** [comment]
Fixed by https://github.com/msys2/MINGW-packages/commit/bdf47e0135556310e64b53e4432f9d7517a0395f

**Comment by Gator96100** [comment]
That didn't fix it.

**Comment by Alexpux** [comment]
@Gator96100 well need more info what not work. I have couple of computers installed and all is working

**Comment by Gator96100** [comment]
I am using [ProxSpace](https://github.com/Gator96100/ProxSpace), a msys2 installation with various tools installed to compile the [proxmark3 firmware]( https://github.com/Proxmark/proxmark3)
It uses mingw as toolchain.
The error that I get is: 

> /bin/sh: D:/mingwbuild/mingw-w64-qt5/pkg/mingw-w64-x86_64-qt5/mingw64/bin/uic: No such file or directory
> make[1]: *** [Makefile:317: ui/ui_overlays.h] Error 127
> make: *** [Makefile:98: client/all] Error 2

**Comment by Alexpux** [comment]
@Gator96100 sorry but it doesnt tell me anything.
Do you update packages to latest with pacman? 
Current Qt5 is 5.14.1-2.

**Comment by Gator96100** [comment]
I will test a few things after work. It might have to do with the portable msys2 installation that ProxSpace is.

**Comment by Gator96100** [comment]
After setting the prefix variable in the msys2\mingw64\lib\pkgconfig\*.pc files correct it did compile successfully. Is 

> prefix=D:/mingwbuild/mingw-w64-qt5/pkg/mingw-w64-x86_64-qt5/mingw64

  correct? Should this variable not update to the current installation path?

**Comment by Alexpux** [comment]
@Gator96100 hope this https://github.com/msys2/MINGW-packages/commit/a4b7d8897febe10b174a2559a89004619ac1e0fb solve issue. Will rebuild qt5 when get time
