### ISSUE TITLE
How to compile gtk3 application? libgtk-3.dll.a seems not to be compiled with G_OS_WIN32

### ISSUE THREAD

**Issue by hakonhagland** [msys2/MINGW-packages#6209]
I am trying to compile a GTK3 application using MSYS2 on Windows 10: Here is what I did:

- Installed MSYS2 from https://www.msys2.org/
- pacman -S git cmake
- pacman -S mingw64/mingw-w64-x86_64-gtk3
- pacman -S gcc
- pacman -S make

Then I created this simple test C program:
```
#include <gtk/gtk.h>

int main() {
    gtk_init(NULL, NULL);	
    return 0;
}
````

To compile this test program, I used:

```
gcc -pthread -mms-bitfields \
-I/mingw64/include/gtk-3.0 \
-I/mingw64/include/cairo -I/mingw64/include -I/mingw64/include/pango-1.0 \
-I/mingw64/include/fribidi -I/mingw64/include -I/mingw64/include/atk-1.0 \
-I/mingw64/include/cairo -I/mingw64/include/pixman-1 -I/mingw64/include \
-I/mingw64/include/freetype2 -I/mingw64/include -I/mingw64/include/harfbuzz \
-I/mingw64/include -I/mingw64/include/libpng16 -I/mingw64/include/gdk-pixbuf-2.0 \
-I/mingw64/include/libpng16 -I/mingw64/include \
-I/mingw64/include/glib-2.0 \
-I/mingw64/lib/glib-2.0/include \
-I/mingw64/include \
-L/mingw64/lib/libgtk-3.dll.a test.c
```
which produces a linker error:
```
/tmp/ccmBtxwp.o:test.c:(.text+0x2d): undefined reference to `gtk_init_abi_check'
/tmp/ccmBtxwp.o:test.c:(.text+0x2d): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `gtk_init_abi_check'
collect2: error: ld returned 1 exit status
```
I think the problem is that the shared library `libgtk-3.dll.a` is not compiled with the symbol `G_OS_WIN32` symbol defined, see line [#1143 in `gtkmain.c`](https://code.woboq.org/gtk/gtk/gtk/gtkmain.c.html#1143).

Note that in the include file [`gtkmain.h` on line #137](https://code.woboq.org/gtk/gtk/gtk/gtkmain.h.html#137), we have

```
#define gtk_init(argc, argv) gtk_init_abi_check (argc, argv, 2, sizeof (GtkWindow), sizeof (GtkBox))
```
so `gtk_init()` is defined in terms of `gtk_init_abi_check()` if the symbol `G_OS_WIN32` is defined. But the problem seems to be that `libgtk-3.dll.a` does not contain the symbol `gtk_init_abi_check`.

**Comment by Alexpux** [comment]
@hakonhagland you need install mingw-w64 GCC.
pacman -S mingw-w64-x86_64-toolchain
and remove MSYS2 gcc
pacman -R gcc

**Comment by lazka** [comment]
@hakonhagland also don't pass the compiler flags manually, use pkg-config instead

**Comment by sauravgo** [comment]
WTF gtk+ under Windows !!!!
