### ISSUE TITLE
msmpi mpic++ 

### ISSUE THREAD

**Issue by dschwen** [msys2/MINGW-packages#6216]
```
$ mpic++ -v
...
COLLECT_GCC_OPTIONS='-I' 'C:\msys64\mingw64\include' '-v' '-LC:\msys64\mingw64\lib' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
...
```

The `COLLECT_GCC_OPTIONS` output by the msmpi wrapper `mpic++` use backslashes. This causes problems with for example the nonlinear solver package PETSc, which drops the backslashes alltogether during its configure process - as does the shell

```
$ ls -la C:\msys64\mingw64\lib
ls: cannot access 'C:msys64mingw64lib': No such file or directory
```

**Comment by Biswa96** [comment]
msys2 (also cygwin) uses paths forward slashes. For example, here it will be `/c/msys64/mingw64/lib`.

**Comment by dschwen** [comment]
Yeah, Forward slashes would be great. What I'm saying is that `mpic++ -v` returns some arguments with backward slashes in the paths they contain.

**Comment by lazka** [comment]
> The `COLLECT_GCC_OPTIONS` output by the msmpi wrapper `mpic++` use backslashes. This causes problems with for example the nonlinear solver package PETSc, which drops the backslashes alltogether during its configure process - 

Ideally those packages would just support Windows paths. 

> as does the shell

This is not the same, you are missing quotes: `ls -la 'C:\msys64\mingw64\lib'`

**Comment by MehdiChinoune** [comment]
PETSc is now available as a package.
