### ISSUE TITLE
KToolbar does not allow the application to close

### ISSUE THREAD

**Issue by khorram-dev** [msys2/MINGW-packages#6217]
I am trying to compile a KF5 application using MSYS2 on Windows 10,7
but in project when using appui.rc
If add ktoolbar in app.rc file, simple:

`<!DOCTYPE kpartgui SYSTEM "kpartgui.dtd">`
`<kpartgui name="kpartmenu" version="1">`
`<MenuBar>`
`	<Menu name="file"><text>File</text>`
`	<Action name="new_profile" />`
`	<Action name="open_profile" />`
`	<Separator/>`
`  </Menu>`
`</MenuBar>`
`<ToolBar name="MyToolBar" noMerge="1"><text>MyApp</text>`
`	<Action name="new_profile" />`
`	<Action name="open_profile" />`
`</ToolBar>`
`</kpartgui>`

when the program closed, Stays in the process system

**Comment by revelator** [comment]
dbus has a habit of staying active after executing stuff dependent on it on windows with a few packages, im also experiencing this.

**Comment by Biswa96** [comment]
This issue has been fixed with https://github.com/msys2/MINGW-packages/commit/f6eacbcdd74cc836294e8e7337c5d3cf772a3117 commit. The fix is available in qt5-base version 5.15.7+kde+r274-2 and above. Feel free to reopen this thread if the issue returns.
