### ISSUE TITLE
after clang 9.0.1 update, i get c++17 filesystem error :

### ISSUE THREAD

**Issue by mumin16** [msys2/MINGW-packages#6238]
[build] C:\msys64\mingw64\include\c++\9.2.0\bits/fs_path.h:636:31: error: invalid use of incomplete type 'std::filesystem::__cxx11::filesystem_error'
[build]       _GLIBCXX_THROW_OR_ABORT(filesystem_error(
[build]                               ^~~~~~~~~~~~~~~~~
[build] C:\msys64\mingw64\include\c++\9.2.0\x86_64-w64-mingw32\bits/c++config.h:177:49: note: expanded from macro '_GLIBCXX_THROW_OR_ABORT'
[build] #  define _GLIBCXX_THROW_OR_ABORT(_EXC) (throw (_EXC))
[build]                                                 ^~~~
[build] C:\msys64\mingw64\include\c++\9.2.0\bits/fs_fwd.h:61:9: note: forward declaration of 'std::filesystem::__cxx11::filesystem_error'
[build]   class filesystem_error;
[build]         ^

**Comment by HolyBlackCat** [comment]
I think previous Clang versions couldn't compile that file too. See [this link](https://stackoverflow.com/questions/57963460/clang-refuses-to-compile-libstdcs-filesystem-header) for a workaround.

The next GCC version should fix this (it's a [libstdc++ bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91786)).

**Comment by revelator** [comment]
on a sidenote this fix allmost allows bootstrapping clang with itself on mingw64, still a few errors to squash in building the clang compiler itself but llvm bootstraps fine now.

**Comment by revelator** [comment]
gcc-9.3.0 has fixed this in libstdc++.
