### ISSUE TITLE
Visual Studio Code

### ISSUE THREAD

**Issue by meiuwa** [msys2/MINGW-packages#6246]
Request for Visual Studio Code package.

I've made a package build file for the [Visual Studio Code][1] official binary release. This is an attempt to stay _as close as possible_ to the [`visual-studio-code-bin`][2] AUR. The source includes both Windows 32 and 64 bit archive release. Is there a chance of having this package official?

**PKGBUILD**
```
_realname='visual-studio-code'
pkgname=("${_realname}-bin")
pkgver=1.42.1
pkgrel=1
pkgdesc='A code editor for building and debugging modern web and cloud applications (official binary release)'
arch=('x86_64'
      'i686')
url='https://code.visualstudio.com/'
license=('custom: commercial')
provides=('code')
conflicts=('code')
options=('!strip')
install="code.install"
source_x86_64=("code-x86_64-${pkgver}.zip::https://update.code.visualstudio.com/${pkgver}/win32-x64-archive/stable")
source_i686=("code-i686-${pkgver}.zip::https://update.code.visualstudio.com/${pkgver}/win32-archive/stable")
sha256sums_x86_64=('b559feec06d7073f74314f0e4778fe30455f0cc25dfeca4d9d3664f4db64abc3')
sha256sums_i686=('7aa14b85dd459296656c16d293b5f3d0ac22673ab42bb1c89ebc8fbbee59b304')
noextract=("code-x86_64-${pkgver}.zip"
           "code-i686-${pkgver}.zip")

prepare() {
    mkdir "${srcdir}/code-${CARCH}-${pkgver}"
    bsdtar -xf "code-${CARCH}-${pkgver}.zip" -C "${srcdir}/code-${CARCH}-${pkgver}"
}

package() {
    # enable portable mode (https://code.visualstudio.com/docs/editor/portable)
    install -d "${pkgdir}/opt/${_realname}/data/tmp"
    cp -Rr "code-${CARCH}-${pkgver}/"* "${pkgdir}/opt/${_realname}"
    install -Dm 644 "code-${CARCH}-${pkgver}/resources/app/LICENSE.rtf" "${pkgdir}/share/licenses/${_realname}/LICENSE.rtf"
}
```

**code.install**
```
post_install() {
    cat << __EOF__
==> Start Visual Studio Code by running:
==> $ /opt/visual-studio-code/bin/code [ARGUMENTS]...
__EOF__
}
```

[1]: https://code.visualstudio.com/
[2]: https://aur.archlinux.org/packages/visual-studio-code-bin/

**Comment by Biswa96** [comment]
Why?

**Comment by meiuwa** [comment]
@Biswa96 Hmm, so... only packages built from source are added to official repo? Sorry, I'm newbie in MSYS2...

**Comment by Biswa96** [comment]
Visual Studio has Windows builds and it can be executed from MSYS2/mintty terminal emulator.

**Comment by meiuwa** [comment]
Hmm, I'm not sure I get that, but It's the Visual Studio Code Editor (https://code.visualstudio.com/) for Windows, not the Visual Studio IDE...

**Comment by meiuwa** [comment]
I think prebuilt binaries are not supported anyway (makes sense as msys is a building platform). So I guess I'll just close this for now...
