### ISSUE TITLE
vsnprintf() behavior is wrong (or outdated)

### ISSUE THREAD

**Issue by holvo** [msys2/MINGW-packages#6254]
pacman -S --needed mingw-w64-x86_64-toolchain
gcc.exe (Rev2, Built by MSYS2 project) 9.2.0
installed as of today to C:\msys64\mingw64

https://en.cppreference.com/w/c/io/vfprintf states the following return behavior
(according to the C99 standards):
The number of characters written if successful or negative value if an error 
occurred. If the resulting string gets truncated due to buf_size limit, function 
returns the total number of characters (not including the terminating null-byte) 
which would have been written, if the limit was not imposed.

However this happens:
The number of characters written if successful or negative value if an error 
occurred. So in case of the resulting string gets truncated, -1 is returned
(instead of the total number of characters which would have been written).

Microsoft has switched to the C99 standard with Visual Studio 2015 and Windows 10.
The legacy function now is _vsnprintf() (no longer the same as vsnprintf() ).

**Comment by lazka** [comment]
The Windows lib mingw links against isn't C99 compatible, you can try compiling with `-D__USE_MINGW_ANSI_STDIO` which replaces things with a mingw implementation which should be C99 compatible. If not that's a bug.

**Comment by holvo** [comment]
Thanks for the tip. Looks good.
