### ISSUE TITLE
Website is down (repo.msys2.org)

### ISSUE THREAD

**Issue by johnratius** [msys2/MINGW-packages#6256]
Is there anyway for me to update msys2? I tried re downloading it or updating it with pacman but the website it tries to connect to is down..

**Comment by lazsma** [comment]
Same issue with me, when trying to build a conan msys2 package.
The problem occurred first yesterday.

**Comment by Biswa96** [comment]
This error seems to be similar as mentioned in this https://github.com/msys2/MSYS2-packages/issues/1098 thread. Subscribe to that issue for future info.

**Comment by Biswa96** [comment]
This error seems to be similar as mentioned in this https://github.com/msys2/MSYS2-packages/issues/1098 and https://github.com/msys2/MSYS2-packages/issues/1884. Subscribe to that issue for future info.

**Comment by magneticflux-** [comment]
It appears to have been noticed here https://github.com/msys2/msys2-web/commit/d7a519a4980606962467ac8983c7ea7bc1be01b3 and here https://github.com/msys2/msys2-web/commit/a76f2380e4f3f36447f5a6cfc5eb13cd0e1a191a.

**Comment by johnratius** [comment]
I commented out the default ones and it works great now. Thanks!

**Comment by lazka** [comment]
should work again
