### ISSUE TITLE
Ghostscript: bbox device is missing

### ISSUE THREAD

**Issue by mgieseki** [msys2/MINGW-packages#6268]
The current build of Ghostcript 9.50 doesn't support the basic output device `bbox`, i.e. it's missing in the list of available devices. Here's the relevant output of `gs --help` (mingw64):
```
Available devices:
   ap3250 atx23 atx24 atx38 bit bitcmyk bitrgb bitrgbtags bj10e bj200 bjc600
   bjc800 bmp16 bmp16m bmp256 bmp32b bmpgray bmpmono bmpsep1 bmpsep8 ccr
   ...
```
Therefore, trying to use the device fails too, of course:
```sh
$ gs -q -sDEVICE=bbox -c "showpage"
Unknown device: bbox
```

When I build the GS sources within the mingw64 environment, device `bbox` is present in the statically linked binary:
```
Available devices:
ap3250 atx23 atx24 atx38 bbox bit bitcmyk bitrgb bitrgbtags bj10e bj200 bjc600
   bjc800 bmp16 bmp16m bmp256 bmp32b bmpgray bmpmono bmpsep1 bmpsep8 ccr
   ...
```
In the executables linked to libgs-9.dll the `bbox` device is also missing.
Unfortunately, I haven't been able to track down the issue in the build system yet and I'm not sure if it's a feature or a bug. On Linux, the device is present regardless of whether the GS executable was linked statically or dynamically.

**Comment by yiyus** [comment]
The bbox device is needed by ps2epsi, which is used by doxygen to generate formulas (as a workaround, the problem can be fixed using ps2eps instead of ps2epsi).

**Comment by gharveymn** [comment]
@Alexpux 
Potential fix:
```diff
--- PKGBUILD.orig       2021-07-09 13:10:49.104387700 -0500
+++ PKGBUILD    2021-07-12 18:34:38.670692500 -0500
@@ -85,7 +85,7 @@
     --without-x \
     --with-drivers=ALL

-  make so
+  make DEVICE_DEVS_EXTRA="soobj/bbox.dev" so
   #make gs.a
 }
```
I haven't tested it with actual inputs, but it makes the device show up in the device list.

**Comment by mmuetzel** [comment]
I came across the same issue and opened PR #9557 with your proposed change. It fixes the issue for me.

**Comment by Biswa96** [comment]
ghoscript now has bbox device. Here is a section of `gs --help` output.

```
$ gs.exe --help | grep -A 5 "Available devices"
Available devices:
   ap3250 atx23 atx24 atx38 bbox bit bitcmyk bitrgb bitrgbtags bj10e bj200
   bjc600 bjc800 bmp16 bmp16m bmp256 bmp32b bmpgray bmpmono bmpsep1 bmpsep8
   ccr cdeskjet cdj500 cdj550 cdjcolor cdjmono cfax cif cljet5 cljet5c
   cljet5pr coslw2p coslwxl declj250 deskjet devicen dfaxhigh dfaxlow
   display dj505j djet500 djet500c dnj650c docxwrite eps2write eps9high
   ...
```

Now the `gs -q -sDEVICE=bbox -c "showpage"` command does not show any "unkown Device" error.

```
$ gs.exe -q -sDEVICE=bbox -c "showpage"
%%BoundingBox: 0 0 0 0
%%HiResBoundingBox: 0.000000 0.000000 0.000000 0.000000
>>showpage, press <return> to continue<<

GS>quit
```
