### ISSUE TITLE
qt5 static depends on zlib1.dll, libzstd.dll

### ISSUE THREAD

**Issue by tim-lebedkov** [msys2/MINGW-packages#6270]
see title

**Comment by tim-lebedkov** [comment]
just adding z and zstd to the list of libraries solved this

**Comment by ppigazzini** [comment]
to link statically those libraries with `cmake` see https://stackoverflow.com/questions/1011197/qt-static-linking-and-deployment
> Currently, to also get all dependencies of Qt statically linked, with CMake, you need to add:
list(PREPEND CMAKE_FIND_LIBRARY_SUFFIXES .a .lib)
before calling find_package(Qt5…
