### ISSUE TITLE
LibLUV

### ISSUE THREAD

**Issue by kassane** [msys2/MINGW-packages#6275]
[Bare libuv bindings for lua - LUV](https://github.com/luvit/luv)
Required by the neovim package. #6269

**Comment by Biswa96** [comment]
libluv package was added here https://github.com/msys2/MINGW-packages/pull/10376. Would you like to test the package?

**Comment by kassane** [comment]
> libluv package was added here https://github.com/msys2/MINGW-packages/pull/10376. Would you like to test the package?

Ok! Thanks.
