### ISSUE TITLE
How to use these packages on ubuntu ?

### ISSUE THREAD

**Issue by eix128** [msys2/MINGW-packages#6277]
Hi , i want to use some packages.
I am making cross compile on linux for windows x64
with:
x86_64-w64-mingw32-c++

but i need packages like mingw-w64-gtk3
apt-get install cant find these libs.
Is there any ppa ? 
Or how can i use these all packages on ubuntu

**Comment by Alexpux** [comment]
@eix128 this packages for MSYS2 only, you can’t use them on Linux

**Comment by Biswa96** [comment]
May be with wine? But it may create [inception](https://en.wikipedia.org/wiki/Inception) like situation, Ubuntu -> wine -> msys2.
