### ISSUE TITLE
D3DOVERLAYCAPS not defined

### ISSUE THREAD

**Issue by Kurvivor19** [msys2/MINGW-packages#6285]
[Patch for mingw64-headers](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-crt-git/0002-DirectX-9-fixes-for-VLC.patch) introduces function that takes D3DOVERLAYCAPS as an argument, however in mingw headers that type is not defined.

Here is output during compilation:

> In file included from libsrc/dxguid.c:20:0:
> /mingw64/x86_64-w64-mingw32/include/d3d9.h:2220:106: error: unknown type name ‘D3DOVERLAYCAPS’; did you mean ‘D3DQUERYTYPE’?
>              D3DFORMAT OverlayFormat, D3DDISPLAYMODEEX* pDisplayMode, D3DDISPLAYROTATION DisplayRotation, D3DOVERLAYCAPS* pOverlayCaps) PURE;
>                                                                                                           ^~~~~~~~~~~~~~
>                                                                                                           D3DQUERYTYPE
> In file included from libsrc/dxguid.c:20:0:

That type, according to [MSDN](https://docs.microsoft.com/ru-ru/windows/win32/api/d3d9caps/ns-d3d9caps-d3doverlaycaps) should be defined in d3d9caps.h, but it just is not there.

**Comment by Biswa96** [comment]
Working on it.

**Comment by Biswa96** [comment]
But it is present in mingw-w64 repository, see here https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/include/d3d9caps.h.

**Comment by Biswa96** [comment]
But D3DOVERLAYCAPS exists in mingw-w64 headers. See this https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/include/d3d9caps.h.

**Comment by Kurvivor19** [comment]
Thanks! that means that i was using obsolete version.
