### ISSUE TITLE
Qt Creator throws error that Clang Format plugin cannot be loaded

### ISSUE THREAD

**Issue by jho101** [msys2/MINGW-packages#6288]
While loading QtCreator, the Clang Format plugin cannot be loading and is disabled. Following error message appears:

Plugin initialization failed: Disabling ClangFormat plugin as it has not been built against a modified Clang's libFormat.For more information see the Qt Creator README at https://code.qt.io/cgit/qt-creator/qt-creator.git/tree/README.md

Installed packages(state from today):
pacman -S base-devel git mercurial cvs wget p7zip perl ruby python2 mingw-w64-x86_64-toolchain mingw-w64-x86_64-clang mingw-w64-x86_64-qt-creator mingw64/mingw-w64-x86_64-opencv  mingw64/mingw-w64-x86_64-imagemagick

**Comment by mingwandroid** [comment]
Simply install mingw-w64 clang
It is listed as an optional dependency of qt creator

**Comment by jho101** [comment]
I have that package installed already and I just installed every clang related package. The same issue. 

But then I have deleted the QtProject folder from the %APPDATA% and the error message disappeared and Plugin is loaded.
