### ISSUE TITLE
qt3d broken

### ISSUE THREAD

**Issue by eringerli** [msys2/MINGW-packages#6298]
Exactly the same error as here: https://bugs.archlinux.org/task/65449

This happens on a 64bit-Windows-installation, with MSYS2, and both MinGW64 and MinGW32 packages.

A compiled application crashes on start. The Arch guys have fixed this with a new version of gcc (which I can affirm, as this bug has stopped me from using the stock QT until it was fixed).

I'm willing to provide more information and test new packages, but i don't have the resources to compile them myself.

**Comment by Alexpux** [comment]
is current Qt still segfault?

**Comment by eringerli** [comment]
No, now it works. I tested it yesterday, I hadn't had the time to report back.

Thanks a lot!
