### ISSUE TITLE
[PACKAGE REQUEST] srecord 

### ISSUE THREAD

**Issue by Spinus1** [msys2/MINGW-packages#6303]
Hello,
it would be very nice to have Srecord tool in msys2: it is a must have to to manipulate file in srecord format (especially useful for embedded devices development)

Upstream project is: http://srecord.sourceforge.net/
There is also an Ubuntu ppa: see http://srecord.sourceforge.net/download.html

I really like to help packaging this tool since it is used in my company, but I don't know where to start :)

BR,
Alessio

**Comment by Biswa96** [comment]
Did anyone try the package? Any issue?
