### ISSUE TITLE
AppVeyor is setting a 60 minutes limit for the build process!

### ISSUE THREAD

**Issue by tomay3000** [msys2/MINGW-packages#6309]
Hello,
I want to build `GCC v9.3.0` to use `SJLJ` exception handling instead of `DWARF`.
So I forked `MINGW-packages` to edit `mingw-w64-gcc` `PKGBUILD` to do so.
When I came back I found that `AppVeyor` canceled the job due to a time limit.
I am still confused about how you do it?

**Comment by lazka** [comment]
That's the default job time limit for free accounts. What did you expect?

**Comment by tomay3000** [comment]
> What do we do? :)

Build `GCC` in that limit conditions.

**Comment by Alexpux** [comment]
@tomay3000 all binary packages in the repo is builded by myself, not in CI

**Comment by tomay3000** [comment]
> @tomay3000 all binary packages in the repo is builded by myself, not in CI

Wait, what! That explains everything then, and you should have a powerful PC.
That is never gonna happen for me with my only 3rd generation i7 because it will take like forever to build.
Also the library dependency order to follow during the build has never been explained in the wiki.

**Comment by lazka** [comment]
For completeness, I think we have a 1.5 hours appveyor limit because we asked nicely. And azure pipelines has a 6 hours limit, but there the disk space is the limit for our large packages (msys2 env + package source + build artifacts + final package don't fit into ~10GB)

**Comment by tomay3000** [comment]
They extended it for me for 100 minutes, but it didn't help neither.
[https://ci.appveyor.com/project/tomay3000/mingw-packages/builds/31746167/job/0xoyk0v6ukr2q985](https://ci.appveyor.com/project/tomay3000/mingw-packages/builds/31746167/job/0xoyk0v6ukr2q985)

I guess I am gonna sacrifice a my PC for a day or two to just build.

**Comment by lazka** [comment]
Looking at our last build on azure it took ~2h50m
