### ISSUE TITLE
Inkscape linked against old librarys

### ISSUE THREAD

**Issue by HazardyKnusperkeks** [msys2/MINGW-packages#6313]
Inkscape wants libgsl-23 and libpoppler-89, currently I have libgsl-25 respectively libpoppler-97.

**Comment by Alexpux** [comment]
@HazardyKnusperkeks need patches to build agains current popper

**Comment by revelator** [comment]
Also needs flags for stack smashing protector with current mingw-w64-api or else you will get undefined references to libssp.

**Comment by Alexpux** [comment]
inkscape 0.92.5 uploaded

**Comment by HazardyKnusperkeks** [comment]
Thanks and sorry for the late answer, I was rather busy.

I'm new to msys2 and have only Linux experience with Debian and mainly server. Wouldn't it be possible to install multiple versions of the libraries, and then updating the dependencies, so that every package uses the version it needs?
