### ISSUE TITLE
[evince] Missing dependency on appstream-glib

### ISSUE THREAD

**Issue by aquilarubra** [msys2/MINGW-packages#6321]
Hi, you need to add mingw-w64-appstream-glib as dependency.

Then, the build seems broken:

make[2]: Leaving directory 'E:/msys64/usr/src/evince/src/build-x86_64-w64-mingw32/properties'
Making all in shell
make[2]: Entering directory 'E:/msys64/usr/src/evince/src/build-x86_64-w64-mingw32/shell'
Failed to open file “./evince.gresource.xml”: No such file or directory
make[2]: *** No rule to make target '/sh.exe', needed by 'ev-resources.c'.  Stop.
make[2]: Leaving directory 'E:/msys64/usr/src/evince/src/build-x86_64-w64-mingw32/shell'
make[1]: *** [Makefile:752: all-recursive] Error 1
make[1]: Leaving directory 'E:/msys64/usr/src/evince/src/build-x86_64-w64-mingw32'
make: *** [Makefile:617: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by lazka** [comment]
thanks

**Comment by aquilarubra** [comment]
Sorry, I mixed 2 issues. The second one subsists. Compilation is broken.

make[2]: Leaving directory 'E:/msys64/usr/src/evince/src/build-x86_64-w64-mingw32/properties'
Making all in shell
make[2]: Entering directory 'E:/msys64/usr/src/evince/src/build-x86_64-w64-mingw32/shell'
Failed to open file “./evince.gresource.xml”: No such file or directory
make[2]: *** No rule to make target '/sh.exe', needed by 'ev-resources.c'. Stop.
make[2]: Leaving directory 'E:/msys64/usr/src/evince/src/build-x86_64-w64-mingw32/shell'
make[1]: *** [Makefile:752: all-recursive] Error 1
make[1]: Leaving directory 'E:/msys64/usr/src/evince/src/build-x86_64-w64-mingw32'
make: *** [Makefile:617: all] Error 2
==> ERROR: A failure occurred in build().
Aborting...

**Comment by lazka** [comment]
The CI run succeeded though -> https://dev.azure.com/msys2/mingw/_build/results?buildId=4776&view=results

**Comment by aquilarubra** [comment]
Maybe there are some other missing dependencies. I have tried many times and it halts there.
