### ISSUE TITLE
configure fails with 32 bit MINGW

### ISSUE THREAD

**Issue by holvo** [msys2/MINGW-packages#6322]
Running autotools configure for ngspice in MINGW32 (updated today)
mingw-w64-i686-toolchain 
gcc.exe (Rev1, Built by MSYS2 project) 9.3.0
with
gcc -o conftest.exe -m32 -O2  -m32 -s conftest.c -lshlwapi
fails with message
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.3.0/../../../../i686-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccI8cBrr.o:conftest.c:(.text.startup+0xc): undefined reference to `PathIsRelativeA'
collect2.exe: error: ld returned 1 exit status

conftest.c generated by ./configure with command 
AC_SEARCH_LIBS([PathIsRelativeA],[shlwapi],[],[])
in configure.ac is 

```
/* Override any GCC internal prototype to avoid an error.
   Use char because int might match the return type of a GCC
   builtin and then its argument prototype would still apply.  */
#ifdef __cplusplus
extern "C"
#endif
char PathIsRelativeA ();
int
main ()
{
return PathIsRelativeA ();
  ;
  return 0;
}

```
Adding -c as in
gcc -o conftest.exe -m32 -O2  -m32 -s -c conftest.c -lShlwapi
then linking is o.k.

Same happens with checking for other libraries (e.g. GetProcessMemoryInfo in -lpsapi).

In MINGW64 with
mingw-w64-x86_64-toolchain
gcc.exe (Rev1, Built by MSYS2 project) 9.3.0
both
gcc -o conftest.exe -m64 -O2  -m64 -s conftest.c -lShlwapi
and
gcc -o conftest.exe -m64 -O2  -m64 -s -c conftest.c -lShlwapi
are o.k.

**Comment by lazka** [comment]
> Adding -c as in
> gcc -o conftest.exe -m32 -O2 -m32 -s -c conftest.c -lShlwapi
> then linking is o.k.

"-c" disables linking.

Are you using our PKGBUILD to build ngspice?

**Comment by holvo** [comment]
No.

Please give a hint and/or link where to find, how to use.

Currently as a workaround we use a direct insertion into two makefile.am to add the library to the appropriate LIBS variable. Then linking is o.k..

**Comment by lazka** [comment]
Here is what we use to build ngspice: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-ngspice/PKGBUILD

Here  is how to build a package: https://www.msys2.org/wiki/Creating-Packages/#build-package

**Comment by holvo** [comment]
Thanks for the info. In fact I do not want to create another package. As a ngspice maintainer I am offering the ngspice-32.tar.gz, which will become the basis of the cited PKGBUILD. Our ngspice distribution package is made with the autotools, and I am testing it by compiling with various compilers and OSs. MINGW32 failed with the above cited error in the conftest. We have a workaround for MINGW32, but I would be happy about a clarification why we have this bug.

**Comment by holvo** [comment]
nm libshlwapi.a
in  /mingw64/x86_64-w64-mingw32/lib
yields
```
0000000000000000 b .bss
0000000000000000 d .data
0000000000000000 i .idata$4
0000000000000000 i .idata$5
0000000000000000 i .idata$6
0000000000000000 i .idata$7
0000000000000000 t .text
0000000000000000 I __imp_PathIsRelativeA
                 U _head_lib64_libshlwapi_a
0000000000000000 T PathIsRelative
```
nm libshlwapi.a
in /mingw32/i686-w64-mingw32/lib
yields
```
00000000 b .bss
00000000 d .data
00000000 i .idata$4
00000000 i .idata$5
00000000 i .idata$6
00000000 i .idata$7
00000000 t .text
         U __head_lib32_libshlwapi_a
00000000 I __imp__PathIsRelativeA@4
00000000 T _PathIsRelativeA@4
```
Is that correct?

**Comment by holvo** [comment]
Yes it is. Seems to be standard Windows 32 bit name mangling. I have to check how the autotools may cope with this feature. It is not a MINGW issue.
