### ISSUE TITLE
evince compilation broken

### ISSUE THREAD

**Issue by aquilarubra** [msys2/MINGW-packages#6323]
make[2]: Leaving directory 'E:/msys64/usr/src/evince/src/build-x86_64-w64-mingw32/properties'
Making all in shell
make[2]: Entering directory 'E:/msys64/usr/src/evince/src/build-x86_64-w64-mingw32/shell'
Failed to open file “./evince.gresource.xml”: No such file or directory
make[2]: *** No rule to make target '/sh.exe', needed by 'ev-resources.c'. Stop.
make[2]: Leaving directory 'E:/msys64/usr/src/evince/src/build-x86_64-w64-mingw32/shell'
make[1]: *** [Makefile:752: all-recursive] Error 1
make[1]: Leaving directory 'E:/msys64/usr/src/evince/src/build-x86_64-w64-mingw32'
make: *** [Makefile:617: all] Error 2
==> ERROR: A failure occurred in build().
Aborting...

**Comment by stahta01** [comment]
Are you trying to build the MSys2 mingw package?
Using the directions found here [README.md](https://github.com/msys2/MINGW-packages/blob/master/README.md)

Tim S.

**Comment by aquilarubra** [comment]
Yes, I have an MSYS2/mingw environment. I downloaded the PKGBUILD and annexed files and run makepkg to build it, instead of installing the prebuilt with the single command, pacman etc.

**Comment by stahta01** [comment]
It worked using the normal MSys2 64 bit MinGW build command which is NOT "makepkg".

`MINGW_INSTALLS=mingw64 makepkg-mingw -sLf`

Tim S.

**Comment by aquilarubra** [comment]
I got the same error. So, I started again from scratch, with a new msys2 environment, and it worked.

Thanks!
