### ISSUE TITLE
WinRT

### ISSUE THREAD

**Issue by tim-lebedkov** [msys2/MINGW-packages#6330]
I'd like to access WinRT from C++ code like here: https://docs.microsoft.com/de-de/windows/uwp/cpp-and-winrt-apis/get-started

The headers are missing. Are maybe some configure-options missing for GCC?

**Comment by Biswa96** [comment]
Working on it. Do you have a simple program to be tested/built (**except UWP**)?

**Comment by tim-lebedkov** [comment]
No, isn't the example at https://docs.microsoft.com/de-de/windows/uwp/cpp-and-winrt-apis/get-started enough?

**Comment by StarWolf3000** [comment]
Shouldn't that be done over at mingw-w64?

**Comment by Biswa96** [comment]
Yup! I'm talking about mingw-w64.

**Comment by tim-lebedkov** [comment]
Is there a branch on mingw-w64 or a ticket or a discussion that we can follow?

**Comment by Biswa96** [comment]
I don't know about an specific issue or thread. The WinRT headers depend on other base headers which have to updated first. Also there is a copyright restriction in Windows SDK headers.

**Comment by tim-lebedkov** [comment]
So there is nothing publicly visible. How much work is it and when will it be ready?

**Comment by Biswa96** [comment]
There is no deadline. If you want to speed up the process you can contribute headers to mingw-w64 repository. Also the WinRT headers have many MSVC specific keywords, so they have to be converted to proper keywords and coding standard for GCC.

**Comment by tim-lebedkov** [comment]
I created this issue: https://sourceforge.net/p/mingw-w64/feature-requests/98/

**Comment by Biswa96** [comment]
One eternity later, there are some progress with winrt headers. The widl tool gained some feature. New winrt headers will be added for SDL2 project.

@maz-1 the winter headers for winhello feature in keepassxc are not present as of writing. But it can be added quicker than before.
