### ISSUE TITLE
qt5 5.14.2-1 CMake builds broken

### ISSUE THREAD

**Issue by Optiligence** [msys2/MINGW-packages#6333]
```
CMake Error at D:/msys64/mingw64/qt5-static/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:15 (message):
  The imported target "Qt5::Core" references the file

     "D:/msys64/mingw64/qt5-static/lib/libQt5Core.dll.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "D:/msys64/mingw64/qt5-static/lib/cmake/Qt5Core/Qt5CoreConfig.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  D:/msys64/mingw64/qt5-static/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:119 (_qt5_Core_check_file_exists)
  D:/msys64/mingw64/qt5-static/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:320 (_populate_Core_target_properties)
  D:/msys64/mingw64/qt5-static/lib/cmake/Qt5Concurrent/Qt5ConcurrentConfig.cmake:223 (find_package)
  D:/msys64/mingw64/qt5-static/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  CMakeLists.txt:73 (find_package)
```

**Comment by Alexpux** [comment]
@Optiligence I don’t have time to fix cmake files for Qt. Let’s wait while it will be fixed upstream. They broke everything every release

**Comment by Optiligence** [comment]
this is an issue with the build tho, because it found a shared Qt during build
my local build of 5.14.2 doesn’t have this issue, although i had shared Qt installed during the build as well

**Comment by Alexpux** [comment]
@Optiligence I will look but I’m build Qt where no qt packages installed

**Comment by Alexpux** [comment]
@Optiligence this is issue with qt configure system, not build

**Comment by Optiligence** [comment]
@Alexpux yes, i just noticed the shared qt is affected too
gonna diff this to my build now

**Comment by Optiligence** [comment]
i actually think my 0008 patch is wrong, but the end result is that it doesn’t actually touch any relevant code and that works at least for the static build

**Comment by fundies** [comment]
libqtmain.dll.a appears to be missing now. I think this package should be reverted to the one that worked

**Comment by Optiligence** [comment]
@fundies just fyi, i think there never was a `qtmain.dll` and therefore also no `libqtmain.dll.a`, it’s always a static library. 
That said, the package was broken and should be fixed now. 

ps reverts don’t happen here, sadly

**Comment by fundies** [comment]
@Optiligence have you confirmed this has been fixed for dynamic qt on your pr? ie should it be fixed when alex updates the package?

**Comment by Optiligence** [comment]
@fundies the packages/repo are already updated
yes, it works for me
