### ISSUE TITLE
qt5 is missing file

### ISSUE THREAD

**Issue by fundies** [msys2/MINGW-packages#6337]
Since your qt updates I'm getting
*** No rule to make target 'D:/msys64/mingw32/lib/libqtmain.dll.a', needed by 'RadialGM.exe'.  Stop.

Please revert that update. It hasn't even been one day since grpc was fixed and now qt is broken on my project.

There should really be a "testing" repo like arch so we can catch some of these things before they hit the main repo

**Comment by Alexpux** [comment]
@fundies you ask to revert something too often. Stop do it, I will not revert anything. If you have problems then try to find solution or downgrade broken package manually on your system

**Comment by Alexpux** [comment]
@fundies I don’t have time and resources to support “testing” repo. All packages are building myself before uploading to repo.

**Comment by fundies** [comment]
You submit broken packages too often with little recourse. I shouldn't need to fix a package for you every 2 days.

**Comment by Alexpux** [comment]
@fundies MSYS2 is rolling  release system. As I told you wait while package will be fixed or downgrade package on your system

**Comment by JoshDreamland** [comment]
Alex, these changes leave the repository in a state where our own continuous integration system is unable to install packages from a clean start. This leads to CI failures in our own repository. Are you suggesting there is a more stable source we could install these packages from to avoid weekly breakages?

**Comment by Alexpux** [comment]
@JoshDreamland I understand but MSYS2 is free time hobby project so I’m not guarantee everything working every time. If you need stable repo then create it yourself and update you repo when you need it

**Comment by fundies** [comment]
Why are you building packages yourself? You already have infrastructure to test that pull requests build. Why can't you just shit master's builds over to the binary repo

**Comment by Alexpux** [comment]
@fundies first, need to build packages in right order, second need to know what packages to rebuild after some package update, third CI can’t build huge packages because of time limit

**Comment by fundies** [comment]
@Alexpux for one, you can increase the time limit on azure but there's also probably ways to build things in the correct order. I doubt the arch linux maintainers manually build every package

**Comment by Alexpux** [comment]
@fundies linux builds are much faster then on windows.

**Comment by Alexpux** [comment]
Also you need to understand that to build in right order you need upload builded package to repo and only after it start next package build with getting new previous package

**Comment by fundies** [comment]
@Alexpux I'm aware but you can set a time limit of up to 6 hours on an azure job and even building something as big as qt + boost + several other things (in vcpkg) only takes ~ 3 hrs on our project. I'm not sure what would take more than 6 hrs other than potentially rebuilding gcc

**Comment by fundies** [comment]
> Also you need to understand that to build in right order you need upload builded package to repo and only after it start next package build with getting new previous package

azure also has conditions that can check previous builds

**Comment by JoshDreamland** [comment]
Thanks, Alex. To clarify, I would not ask you to invest your own time in making sure our repository will build, but I would greatly appreciate if there was a mechanism for a "stable" vs "testing" version, so that the community (us included) could help you ensure that the default repository (http://repo.msys2.org/mingw/x86_64/) always builds.

As fundies is suggesting, Azure can handle builds for specific workflows. We already have one set up to install Qt, etc, for our own uses, and we would love to contribute that if it would mean that our users could reliably install packages. For you, I believe the only difference it would make in your day-to-day contributions to this project is that they would be to a different branch. Or, really, we could update the system to publish a "stable" branch to repo.msys2.org, instead.

I think you'll find a lot of community members are happy to deal with the CI bits for you—particularly because we already have them running as part of our own CI. If all goes well, the release from testing to master or from master to stable would just happen automatically when everyone's CI passes.

Are you willing to enable such a system?

**Comment by fundies** [comment]
I did a little digging on how arch works and they use a program called "sogrep" which maintains a database to all packages that depend on a certain library. (https://git.archlinux.org/infrastructure.git/tree/roles/sogrep/files/createlinks) They use this to auto generate build queues. They do however build manually after that so maintainers can "sign" their packages. However, since you are basically the sole maintainer I don't see real harm in you having the build server sign packages. Azure's time can be upped to 6 hours and you can force order your jobs using  deployment and conditional jobs. You can probably automate the whole thing and spend less time building packages and more time fixing them.

**Comment by Alexpux** [comment]
@fundies I don’t see how this can avoid issues like discussed there. Qt5 package builded and it works for qmake projects well, while it not work for cmake projects. So how this situation will be handled by CI?

**Comment by fundies** [comment]
@Alexpux my intent is for it to make it easier for you to maintain either a testing ot lts repo because it wouldn't be on you to build every package. Then people could tests against the "testing" repo and report issues before they hit the main repo.

**Comment by Alexpux** [comment]
@fundies you think that much peoples will use testing repo? There are few peoples only who regularly do some work on MSYS2 packages, others only come here once to ask for new package or to fill issue with something broken. So I think testing repo is not what can helps here. There are no big community that can help testing packages

**Comment by fundies** [comment]
@Alexpux well I know I would use it to add a separate ci job to my project to catch this kind of thing early. The alternative is to allow people to add dummy programs here or to a partner git repo to test new packages  against.

**Comment by lazka** [comment]
(larger builds usually fail because azure has not enough disk space and not the time limit)

**Comment by revelator** [comment]
A stable repository would be nice, unfortunatly i suck at git else i would have provided a fork of packages that are known to work together  a long time ago :S. 

So if anyone has the time to maintain a stable repo im willing to throw in my time to find the packages that work and provide patches for things i can fix.

**Comment by MehdiChinoune** [comment]
likely no longer an issue
