### ISSUE TITLE
gcc -rdynamic error

### ISSUE THREAD

**Issue by linuxteralb** [msys2/MINGW-packages#6341]
`$ gcc -rdynamic
gcc.exe: error: unrecognized command line option '-rdynamic' `
in `man gcc` page
` Linker Options
           object-file-name  -fuse-ld=linker  -llibrary -nostartfiles
           -nodefaultlibs  -nolibc  -nostdlib -e entry  --entry=entry -pie
           -pthread  -r  ///////////-rdynamic\\\\\\\\\\\\\\ -s  -static  -static-pie  -static-libgcc
           -static-libstdc++ -static-libasan  -static-libtsan
           -static-liblsan  -static-libubsan -shared  -shared-libgcc
           -symbolic -T script  -Wl,option  -Xlinker option -u symbol  -z
           keyword`

**Comment by stahta01** [comment]
Linker options require a prefix when passed to GCC.

**Comment by linuxteralb** [comment]
`$ gcc -Wl,rdynamic` result:
`C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find rdynamic: No such file or directory
collect2.exe: error: ld returned 1 exit status`
`$ gcc -Wl,-rdynamic` result:
`C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: unrecognised option: -rdynamic
collect2.exe: error: ld returned 1 exit status`

**Comment by Alexpux** [comment]
@linuxteralb -Wl,-rdynamic

**Comment by Alexpux** [comment]
@linuxteralb rdynamic not related to windows targets, so you can’t use it.
`-rdynamic

Pass the flag -export-dynamic to the ELF linker, on targets that support it. This instructs the linker to add all symbols, not only used ones, to the dynamic symbol table. This option is needed for some uses of dlopen or to allow obtaining backtraces from within a program. `

**Comment by linuxteralb** [comment]
Ok thanks that work
