### ISSUE TITLE
Building GCC 9.3 meet some error

### ISSUE THREAD

**Issue by Efreets** [msys2/MINGW-packages#6346]
Hi,
  Do you have some time to help me to solve the problem with building gcc 9.3 on windows?
  Thanks.

  Here was my information during Build gcc, how it makes, I'm my best to solve the error, but it's no work

  My configure is

```
../gcc-9.3.0/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/P/Efreets/gcc930/ --with-sysroot=/P/Efreets/gcc930/ --enable-languages=c,lto,c++,fortran --enable-lto --enable-static --disable-symvers --disable-shared --enable-threads=posix --enable-sjlj-exceptions --with-system-zlib --with-gmp=/P/Efreets/gmp620 --with-mpfr=/P/Efreets/mpfr402 --with-mpc=/P/Efreets/mpc110 --with-isl=/P/Efreets/isl221 --with-zstd=/P/Efreets/zstd144
```

  It's meet this error

```
[ -f stage_final ] || echo stage3 > stage_final
make[1]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
make[2]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
make[3]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
rm -f stage_current
make[3]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make[2]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make[2]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
/usr/bin/sh: -c:行6: unexpected EOF while looking for matching `''
/usr/bin/sh: -c:行7: syntax error: unexpected end of file
make[2]: *** [Makefile:11206: all-stage1-libiberty] Error 1
make[2]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make[1]: *** [Makefile:21113: stage1-bubble] Error 2
make[1]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make: *** [Makefile:1003: all] Error 2
```

  And this is the error line in MakeFile, see attaching file.

![76f4fa84a85768a6c2482d160c8b1d07](https://user-images.githubusercontent.com/11472828/78422893-3df6a380-7695-11ea-9322-9ec2cb3e0536.png)

![eff889e3d134e9e2d88fbbae7fb15c79](https://user-images.githubusercontent.com/11472828/78422901-4949cf00-7695-11ea-9463-8d2f92fd69ee.png)

I think error line in right, but I can't solve the problem, could you help me ?

  I can't thank you so much, I need you help, Waiting message.

yours sincerely

**Comment by ret394** [comment]
not a solution. 

in configure
> --enable-languages=c,lto,c++,fortran

is lto allowed in there?

**Comment by MehdiChinoune** [comment]
GCC is available as a package from MSYS2.
