### ISSUE TITLE
mingw64: can't compile a lib such that a Qt signal can connect successfully to a binary slot

### ISSUE THREAD

**Issue by lopippo** [msys2/MINGW-packages#6359]
Greetings,

I do not know if this is the place to ask. 

I am using MinGW-64 to build two artifacts using c:/msys2/mingw64/bin/cmake.exe:
- a library with classes that emit Qt signals (pappso lib below);
- an executable binary that connects slots to these library-emitted signals.

Unfortunately, I receive a number of 

Warning: QObject::connect: signal not found in pappso::PrecisionWidget (:0, )
Warning: QObject::connect: signal not found in pappso::BasePlotWidget (:0, )
Warning: QObject::connect: signal not found in pappso::BasePlotWidget (:0, )
Warning: QObject::connect: signal not found in pappso::BasePlotWidget (:0, )
Warning: QObject::connect: signal not found in pappso::BasePlotWidget (:0, )

First question: what is the (:0, ) string element above ?

Second question: is the dllexport art required when using the MinGW64 build environment and using CMake to build shared libs and executable binaries ?

Indeed, I tried building the library by specifying the following, according to the CMake docs:

-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE

 but although the md5 checksums of the libs are different, the size of the libs (with or without this dllexport art) is identical. So, I gather that the defines above are not essential ?

Third question: When building the library, I get systematically two dll artifacts: the libname.dll and the libname.dll.a. What are the differences between the two? I tried linking my executable against one or the other, but that does not solve my problem.

What other information should I provide to help you help me fix the problem ?

FYI, I am using -G "Unix Makefiles" and have confirmed that WIN32 is indeed defined during the configuration of the build. What about using -G "MinGW Makefiles". I tried, but the build seems to go the exact same way as the other "Unix way". What is the difference between the two, in a msys64/mingw64 context ?

Thank you for your patience and hoping for help,
Sincerely, Filippo

**Comment by oscarfv** [comment]
You are asking basic questions about how to use Qt and the MinGW-w64 toolchain. If I remember correctly Qt has a forum or mailing list for this type of questions (using Qt with Mingw-w64/Mingw). You can try asking there as it is much more probable that you get answers.

**Comment by lopippo** [comment]
Great! Thank you very much, oscarfv.
Sincerely, Filippo

Closing issue.
