### ISSUE TITLE
wxWidgets 3.1.3 has been released

### ISSUE THREAD

**Issue by RalphLynch** [msys2/MINGW-packages#6362]
A new version of wxWidgets was released on the 28th of October last year. Could the version in MINGW-packages please be updated to this version.

**Comment by oscarfv** [comment]
Would you consider updating the PKGBUILD, building, testing and submitting a PR?

**Comment by ZachBacon** [comment]
wxwidgets 3.1 series is a developmental series, I think the wxWidgets package is sticking to stable releases.

**Comment by stahta01** [comment]
wxWidgets3.1 package already exists; if you wish to have it added to the build list then ask for that.
If you just wish to build it yourself please do so.

The wxWidgets 3.1 is a development versions. In about 6 to 12 months they plan to release wxWidgets 3.2.0 which will be production release.

Tim S.
