### ISSUE TITLE
mpv needs rebuild

### ISSUE THREAD

**Issue by Optiligence** [msys2/MINGW-packages#6375]
```
---------------------------
mpv.exe - System Error
---------------------------
The code execution cannot proceed because libdvdread-7.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
```

**Comment by Alexpux** [comment]
done in repo

**Comment by Optiligence** [comment]
@Alexpux 0.32.0-2 still has the same error

**Comment by mati865** [comment]
It's because `mingw-w64-libdvdnav` needs rebuild, not `mingw-w64-mpv`.

**Comment by Alexpux** [comment]
Will be today in repo

**Comment by ilya-lazarev** [comment]
As well as libdvdread:
 ntldd /mingw64/lib/gstreamer-1.0/libgstdvdread.dll
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x0000000000620000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x0000000000620000)
        **libdvdread-7.dll => not found**
        libglib-2.0-0.dll => C:\msys64\mingw64\bin\libglib-2.0-0.dll (0x0000000000f60000)
        libgmodule-2.0-0.dll => C:\msys64\mingw64\bin\libgmodule-2.0-0.dll (0x0000000000020000)
        libgobject-2.0-0.dll => C:\msys64\mingw64\bin\libgobject-2.0-0.dll (0x0000000000620000)
        libgstbase-1.0-0.dll => C:\msys64\mingw64\bin\libgstbase-1.0-0.dll (0x0000000000620000)
        libgstreamer-1.0-0.dll => C:\msys64\mingw64\bin\libgstreamer-1.0-0.dll (0x0000000000f60000)
        libintl-8.dll => C:\msys64\mingw64\bin\libintl-8.dll (0x0000000000620000)
