### ISSUE TITLE
Undefined reference to 'WinMain' when linking against SDL2

### ISSUE THREAD

**Issue by AliceLR** [msys2/MINGW-packages#6379]
When linking against SDL2 using the default output from `sdl2-config --libs` after the most recent update, the following error occurs:
```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): in function `main':
D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status
```

This did not occur prior to the most recent update. The problem appears to be that the new sdl2-config files for both MINGW64 and MINGW32 contain the following handler for `--libs`:
```
    --libs)
      echo -L${exec_prefix}/lib  -mwindows -lSDL2main -lmingw32 -lSDL2
```

Changing it to this line from the sdl2-config bundled with the official SDL2 mingw development package fixes the problem:
```
    --libs)
      echo -L${exec_prefix}/lib  -lmingw32 -lSDL2main -lSDL2 -mwindows
```

Since it looks like SDL generates sdl2-config, could this be related to a082f602?

**Comment by Alexpux** [comment]
Fixed by https://github.com/msys2/MINGW-packages/commit/9a8cde2cd912157616077e3c2ef714ead836cd62
