### ISSUE TITLE
[BUG] Missing package dependency for OGRE

### ISSUE THREAD

**Issue by equilibr** [msys2/MINGW-packages#6390]
The "mingw-w64-x86_64-ogre3d" package should also depend on "mingw-w64-x86_64-pugixml"
OGRE fails to load the "Plugin_DotScene" module.
Looking at "Plugin_DotScene.dll" in the dependency walker shows is also depends on "libpugixml.dll

**Comment by Alexpux** [comment]
@equilibr fixed in https://github.com/msys2/MINGW-packages/commit/2975b19a56b56f5e6252e74d718b40f7c3a05015
