### ISSUE TITLE
aria2.exe can‘t running。

### ISSUE THREAD

**Issue by killghost** [msys2/MINGW-packages#6393]
aria2.exe can‘t running。(0xc000007b) Application ERROR

**Comment by Alexpux** [comment]
@killghost we dont provide aria2.exe. Our packages contain aria2c.exe and it works for me

**Comment by killghost** [comment]
https://packages.msys2.org/package/mingw-w64-i686-aria2?repo=mingw32

after I add some other file, include libcares-4.dll,libsqlite3-0.dll,libssh2-1.dll,.......

I download the Package from Here.

**Comment by killghost** [comment]
I Run Aria2c.exe,Just Like this: 

Aria2c.exe http://repo.msys2.org/mingw/i686/mingw-w64-i686-aria2-1.35.0-2-any.pkg.tar.xz

**Comment by Alexpux** [comment]
@killghost if you manually download and unpack packages then you must use some tools to see if all dependencies are also unpacked. We not support this method.

**Comment by killghost** [comment]
Yes,I Add ALL Depends File.it can't run。Can You Share these files to me？
Thanks U

**Comment by killghost** [comment]
How to Download All the Files by Not manually?

**Comment by Alexpux** [comment]
@killghost install MSYS2 and install aria2 package using package manager
