### ISSUE TITLE
GTK+ 2 patch

### ISSUE THREAD

**Issue by lillolollo** [msys2/MINGW-packages#6395]
@Alexpux Please is it possible to add those patch to GTK+2 ?

 https://gitlab.gnome.org/GNOME/gimp/-/tree/gimp-2-10/build%2Fpatches

 and
 
https://gitlab.gnome.org/GNOME/gimp/-/tree/gimp-2-10/build%2Fwindows%2Fpatches

**Comment by Alexpux** [comment]
@lillolollo create pull request

**Comment by lazka** [comment]
Nothing happened, so closing. Feel free to create a PR still.
