### ISSUE TITLE
inkscape after change to use cmake build system no longer able to use openmp

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#6401]
The previous version using autotools worked but the current version complains about undefined references to the openmp library :S tried adding -fopenmp to flags but that is not enough it seems.
disabling openmp and it builds just fine.

**Comment by Alexpux** [comment]
@revelator probably need ask @Ede123

**Comment by revelator** [comment]
Oki thanks alex :)

**Comment by revelator** [comment]
Mailed him about the issue, lets hope he has some answers to what the problem is.

**Comment by revelator** [comment]
Btw i changed the inkscape-0.92.0-win32-relocatable.patch a bit to use python 3 instead of python 2 and made a correction to 
gchar *pythondll = g_build_filename(prefixpath, "lib", "python3.8", "lib-dynload", "DLLs",  NULL); to 
gchar *pythondll = g_build_filename(prefixpath, "lib", "python3.8", "lib-dynload", NULL); 

this fixed an inkscape warning about this folder as the DLLs folder does not exist in the mingw-w64-pythons.

I suspect this patch was originally intended for compatibility with both the official windows python where the DLLs folder exists and the mingw-w64-python ?.

No other warnings detected with the python scripts after this change,

**Comment by Alexpux** [comment]
@revelator if you have useful changes why you not provide them to our repo?

**Comment by Ede123** [comment]
@revelator I'm not seeing any issues in my local builds. OpenMP is found and used as far as I can tell:
```
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
```

Compiling, linking and running works fine.

Unless there's an issue in or with the PKGBUILD (I did not try that) it seems to work as expected.

---

P.S. The code you found in outdated and is for backwards-compatibility with the official CPython we used to bundle in the past. It's not needed for mingw-w64-python2/3.

**Comment by revelator** [comment]
Patch is still applied so you mean we can skip it entirely then ?.

I suspect the openmp problem im experiencing is caused by changes to current cmake if you use the same then im at a loss as to why the older autotools based version finds it and the cmake one does not.

I dont have a working fork of your repo to make pull requsts from unfortunatly. 
I suck at git badly :/

**Comment by revelator** [comment]
cairo-templates.h:79:78: error: there are no arguments to 'omp_get_num_procs' that depend on a template parameter, so a declaration of 'omp_get_num_procs' must be available [-fpermissive]

This and a few other related errors is what i get with openmp on, 
it seems cmake finds the openmp library though.

**Comment by revelator** [comment]
well this is odd i changed build to use ninja instead and it works.

**Comment by revelator** [comment]
Yep ninja build works fine allthough i have to move the executables from the root dir to bin.
Not sure why cmake croaks on openmp when using standard MSYS Makefiles, its as if it fails to get the correct include dir for omp.h. Maybe the compiler gets confused because i also have msvc installed but i dont see any includes being pulled from it so weird one.

**Comment by revelator** [comment]
More investigation turned out that the inkscape-0.92.0-win32-relocatable.patch cannot be removed as it causes the binaries to install to ${MINGW_PREFIX} and not ${MINGW_PREFIX}/bin.
Could remove the code specific for CPython from it that should still work.

Ninja builds also installs the com wrappers allthough im not sure if those are needed ?.
Ill update the patch above removing the CPython specific parts but i do not have a repo for a pull request so i would have to upload the revised patch here.

**Comment by Ede123** [comment]
Hm, interesting... I'm building with ninja exclusively these days and our CI is ninja-based as well, so I can't rule out something regressed with make in the meantime.

The updated pkgbuild uses "MSYS Makefiles" as well, though, so it seems to have worked in this case.

---

I wasn't implying that the whole patch could be removed (especially as the MSYS2 package differs from the official packages), only that the specific change to PATH is not required to make Python work.

---

.com wrappers are not needed when running Inkscape through an MSYS2 shell. If you want console output when running from cmd.exe you'll have to use them however.

**Comment by revelator** [comment]
ninja build works like a charm so might be well using that instead ?.

Updated the patch also it now uses the site dir for python3.8 instead of python2.7 and everything works. 

Imagemagick would need an update if we want to link to this also, the current version in trunk is way to old.

here are the changed files using ninja for building if you want to incorporate them.

[mingw-w64-inkscape.zip](https://github.com/msys2/MINGW-packages/files/4518439/mingw-w64-inkscape.zip)

**Comment by coffeeandspaceships** [comment]
See also #6400 - this could be the underlying cause?

**Comment by revelator** [comment]
Yep that was it. Allthough strange that this does not affect ninja builds since im also using cmake to generate those.

**Comment by revelator** [comment]
Seems some packages croak on clangs libraries i had one confirmed instance where a package refused to build untill i removed libunwind and now libomp also seems to get in the way. Not sure how to go about fixing this ? allthough one way would be to simply skip building those parts of clang as long as we use it as we currently do.

**Comment by revelator** [comment]
No that was not it either... it seems to be some bug between gcc version 9 and later and cmake causing this. Example here https://github.com/lammps/lammps/pull/1483

We could get away with using cmake / ninja as proposed as that seems to work, but it causes problems with detecting libopenblas in ceres-solver which also suffers from this bug instead sigh :/.

**Comment by MehdiChinoune** [comment]
likely no longer an issue. Inkscape doesn't require any patch to link to OpenMP
