### ISSUE TITLE
Support for opengl 4.6

### ISSUE THREAD

**Issue by sueyllam** [msys2/MINGW-packages#6404]
When I tried to run the opengl red book 9th edition examples that use opengl 4.5, the programs crashed, when I turned down the version to 4.3 everything was fine. I tried the gl3wIsSupported(4,5) and it returned False. My NVidia graphics card support opengl 4.6, so when will the opengl library in mingw64 or mingw32 will be supporting version 4.5 or better yet 4.6...

**Comment by lazka** [comment]
I don't know much about opengl, but from what I know it is provided by Windows and not mingw.

**Comment by sueyllam** [comment]
Thanks, that makes sense since I checked Visual Studio Community 2017 and it can't handle opengl versions above 4.3 also...

**Comment by sueyllam** [comment]
Well, just so that anybody interested in opengl, I upgraded to Visual Studio 2019 Community with the latest SDK and it seems now that mingw under msys2 supports up to opengl 4.4 (like windows) instead of 4.3...

**Comment by ImperatorS79** [comment]
Why did you reopen this @sueyllam ? ^^

**Comment by ImperatorS79** [comment]
Indeed from gl3w github ->

> Its main part is a simple gl3w_gen.py Python script that downloads the Khronos supported glcorearb.h header and generates gl3w.h and gl3w.c from it. Those files can then be added and linked (statically or dynamically) into your project.

Maybe your gl3w.c and .h are not up to date with latest glcorearb.h ^^

**Comment by sueyllam** [comment]
My gl3w.c and glcorearb.h are up to date and they support opengl 4.6.1 but the problem seems to be either glfw3 or opengl32 library, the glfw when asked to set opengl version to 4.5 or 4.6 does not seem to go higher than 4.4 after updating to the latest windows 10 sdk.

**Comment by ImperatorS79** [comment]
The opengl dll on your system are provided by your driver  -> so this does not implies msys2 at all. Are your drivers up to date, and which tool did you use to get the maximum opengl version on your GPU ?

You can also show your code but it will be a little bit out of the scope of this issue ^^.

**Comment by sueyllam** [comment]
A simple and quick way I use, is to have a simple opengl app. that draws a single triangle and use the following fragment shader:

#version 450 core

out vec4 fColor;

void main()
{
    fColor = vec4(0.5, 0.4, 0.8, 1.0);
}

As you see the color is supposed to be some shade of blue but it turns out white(default value of 1's in the color vector) with the 450 version,. Changing the version to 440, the triangle is displayed with the right color.

**Comment by sueyllam** [comment]
Well I guess you're right it is a driver problem. My NVidia GeForce graphics card supports opengl 4.6 but my intel graphics driver supports only 4.4. There are no updates for this intel driver which dates back to 2017. I guess I need a new laptop then...

**Comment by sueyllam** [comment]
Just not to mislead anybody; you get to choose which graphics driver to use, intel was the default, once I changed it to nvidia (using nvidia control panel) the 4.6 is now supported on my laptop...
