### ISSUE TITLE
Assimp 5 package fails to find files using cmake

### ISSUE THREAD

**Issue by enginmanap** [msys2/MINGW-packages#6408]
Hi, 

I am a msys2 user, mainly using it to do C++ development with cmake. I am getting the following error messages after the assimp upgrade to 5.0

I am using win10 x64 fully upgraded, and msys is fully upgraded as far as I know.
$ pacman -Syuu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do

**the error messages are below:**

CMake Error at C:/msys64/mingw64/lib/cmake/assimp-5.0/assimpTargets.cmake:85 (message):
  The imported target "assimp::assimp" references the file

     "C:/msys64/mingw64/lib/libassimp.dll.5"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/msys64/mingw64/lib/cmake/assimp-5.0/assimpTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  C:/msys64/mingw64/lib/cmake/assimp-5.0/assimp-config.cmake:1 (include)
  CMakeLists.txt:87 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by Alexpux** [comment]
@enginmanap hope it fixed by https://github.com/msys2/MINGW-packages/commit/e7d83b5986c88865dcf1b9f3514a10230a54cf66

**Comment by enginmanap** [comment]
It did, thank you very much.
