### ISSUE TITLE
[aria2] How to get a static build

### ISSUE THREAD

**Issue by killghost** [msys2/MINGW-packages#6412]
How to Build libaria2.dll With "-static-libgcc -static-libstdc++"

**Comment by killghost** [comment]
And How To Build Aria2，Make it not depends any other files

**Comment by Alexpux** [comment]
@killghost read our wiki about building packages - https://www.msys2.org/wiki/Home/
To build aria2 with static dependencies probably you must first build all dependencies static and then build aria with them. But this is not topic for our repo.

**Comment by killghost** [comment]
How To Build libaria2.dll ，without depends libgcc_s_dw2-1.dll and libstdc++-6.dll,Thanks

**Comment by ienapliss** [comment]
You mean 'How to compile any program without dependency on libgcc_s_dw2-1.dll and libstdc++-6.dll'.

You simply can't AFAIK with current gcc on windows.

**Comment by Alexpux** [comment]
@ienapliss you are wrong. There are flags for link GCC libs statically

**Comment by killghost** [comment]
> @ienapliss you are wrong. There are flags for link GCC libs statically

how to add flgs in pkgbuild。

https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-aria2/PKGBUILD

**Comment by ienapliss** [comment]
> 
> 
> @ienapliss you are wrong. There are flags for link GCC libs statically

What flags? "-static-libgcc -static-libstdc++" ? They don't work.
I checked and rechecked everytime.

**Comment by Alexpux** [comment]
> > @ienapliss you are wrong. There are flags for link GCC libs statically
> 
> What flags? "-static-libgcc -static-libstdc++" ? They don't work.
> I checked and rechecked.

Then you probably don’t have build all dependencies statically

**Comment by killghost** [comment]
# Maintainer: David Macek <david.macek.0@gmail.com>

_realname=aria2
pkgbase=mingw-w64-${_realname}
pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
pkgver=1.35.0
pkgrel=2
pkgdesc="A multi-protocol & multi-source, cross platform download utility (mingw-w64)"
arch=('any')
url="https://aria2.sourceforge.io/"
license=('GPL2')
makedepends=("${MINGW_PACKAGE_PREFIX}-gcc"
             "${MINGW_PACKAGE_PREFIX}-pkg-config")
depends=("${MINGW_PACKAGE_PREFIX}-gcc-libs"
         "${MINGW_PACKAGE_PREFIX}-gettext"
         "${MINGW_PACKAGE_PREFIX}-c-ares"
         "${MINGW_PACKAGE_PREFIX}-cppunit"
         "${MINGW_PACKAGE_PREFIX}-libiconv"
         "${MINGW_PACKAGE_PREFIX}-libssh2"
         "${MINGW_PACKAGE_PREFIX}-libuv"
         "${MINGW_PACKAGE_PREFIX}-libxml2"
         "${MINGW_PACKAGE_PREFIX}-openssl"
         "${MINGW_PACKAGE_PREFIX}-sqlite3"
         "${MINGW_PACKAGE_PREFIX}-zlib"
         )
optdepends=("${MINGW_PACKAGE_PREFIX}-ruby: aria2rpc and aria2mon")
source=(${_realname}-${pkgver}.tar.gz::https://github.com/tatsuhiro-t/aria2/archive/release-${pkgver}.tar.gz)
sha256sums=('c4072deaf6b443be15f9710657aa6c53527f642bc7a3252bb81d2853161080ed')

prepare() {
  cd "${_realname}-release-${pkgver}"
  autoreconf -ifv || autoreconf -ifv
}

build() {
  [[ -d build-${MINGW_CHOST} ]] && rm -rf build-${MINGW_CHOST}
  mkdir -p build-${MINGW_CHOST}
  cd build-${MINGW_CHOST}

  export LDFLAGS="$LDFLAGS -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic"

  # disabling gnutls and wintls so we will fall back to openssl
  ../${_realname}-release-${pkgver}/configure \
    --prefix=${MINGW_PREFIX} \
    --with-bashcompletiondir=${MINGW_PREFIX}/share/bash-completion/completions \
    --build=${MINGW_CHOST} \
    --host=${MINGW_CHOST} \
    --enable-static \
    --enable-shared \
    --without-gnutls \
    --without-openssl \
    --with-wintls \
    --enable-libaria2 \
    --disable-bittorrent \
    --disable-metalink \
    --without-cppunit \
    --without-libares \
    --without-libcares \
    --enable-threads=win32 \
    --without-libgcrypt \
    --without-libnettle \
    --without-included-gettext \
    --disable-nls \
    --without-sqlite3 \
    --without-libxml2 \
    --without-libexpat 
    #LDFLAGS="-static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic" 


  make clean && make 
  #LDFLAGS='-Wc,-static-libgcc'
}

package() {
  cd "build-${MINGW_CHOST}"
  make DESTDIR="${pkgdir}" install

  cd "../${_realname}-release-${pkgver}"

  install -Dm0755 doc/xmlrpc/aria2rpc "${pkgdir}"${MINGW_PREFIX}/bin/aria2rpc
  install -Dm0755 doc/xmlrpc/aria2mon "${pkgdir}"${MINGW_PREFIX}/bin/aria2mon
  echo '@ruby -- "%~dp0aria2rpc" %*' > "${pkgdir}"${MINGW_PREFIX}/bin/aria2rpc.cmd
  echo '@ruby -- "%~dp0aria2mon" %*' > "${pkgdir}"${MINGW_PREFIX}/bin/aria2mon.cmd
  rm ${pkgdir}${MINGW_PREFIX}/share/doc/${_realname}/xmlrpc/aria2{rpc,mon}
}

**Comment by Alexpux** [comment]
@ienapliss if as you told our gcc can do full static builds then how we do, for example, qt5-static package?

**Comment by killghost** [comment]
In build function,I Add the next Line:

  export LDFLAGS="$LDFLAGS -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic"

**Comment by Alexpux** [comment]
@killghost why you post PKGBUILD here?

**Comment by Alexpux** [comment]
@killghost as I told you before you need to have properly builded all packages in depends in static mode

**Comment by Alexpux** [comment]
we not provide static versions for all packages and it is not our goal. We prefer shared linking. So for building fully static aria2 you **MUST** verify and maybe rebuild all dependend packages statically yourself

**Comment by killghost** [comment]
thanks
