### ISSUE TITLE
cx_Freeze build failing due to missing libffi-6.dll

### ISSUE THREAD

**Issue by kaiw** [msys2/MINGW-packages#6414]
I'm very uncertain about this, but I think that the recent update to use `libffi-7.dll` has broken building with cx_Freeze.

Looking at history, https://github.com/msys2/MINGW-packages/pull/6225 changed the hard-coded cx_Freeze usage of `libffi-7.dll` to instead hard-code `libffi-6.dll`. It's possible that reverting this change will just fix the issue.

**Comment by Alexpux** [comment]
fixed by https://github.com/msys2/MINGW-packages/commit/034b76141e52a551fcb10e895c57155b9c07f178
