### ISSUE TITLE
GCC 9.3 maybe a issue

### ISSUE THREAD

**Issue by ret394** [msys2/MINGW-packages#6415]
```c
#include <stdio.h>

struct string {
    char* name;
};

int main()
{
struct string * value;

value->name = "Fat as a cat that ate a 1,000 rats";
printf((const char *) value->name);
}

/* 
how to get this kind of code:
just keep removing warning messages when compiling with -Wall -Wpedantic, disregard C syntax then see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94675

weird output for
>gcc -O2 .\helloWorld.c -o .\helloWorldC.exe
>.\helloWorldinC.exe
>
so -02 MESSSES IT UP! not -Warray-bounds
> gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
//gcc packaged via scoop.
```

thanks for msys2 packages. if it is a issue, please ask someone to forward it to buzzkill bugzilla.

thanks. have a nice day. keep up the good work.

[ret394](https://github.com/ret394)

**Comment by jtanx** [comment]
It's a problem with your code, not gcc. You haven't allocated `value` so you're dereferencing garbage. Either use `struct string value` or allocate an instance with malloc.

**Comment by ret394** [comment]
The code demonstrates, if you think about it for a while how gcc suggestions can lead to more subtle errors, in some cases.
-  to illustrate that view, `(const char *) value->name` is not intended to de-reference but to typecast, though syntax is confusing.  before this change gcc would give `error: invalid type argument of '->'` and so on the chain continues.

@jtanx Thanks for the tip and the curt reply!

Didn't get the time to mention it in a hurry last time and other stuff came up. after editing the original code to be shorter, posted it here, to at least document it and not forget about it.

But if it is annoying, please let me know. Snipped some other stuff to save time.

thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394)
