### ISSUE TITLE
No module named 'plist' or 'libplist' in python3

### ISSUE THREAD

**Issue by MobilEKG** [msys2/MINGW-packages#6416]
Install libplist successfully by using following command from https://msys2.duckdns.org/package/mingw-w64-x86_64-libplist:
```
pacman -S mingw-w64-x86_64-libplist
```
in Python3, `import plist` failed:
**_ModuleNotFoundError: No module named 'plist'_**

Try `import libplist`, also failed:
**_ModuleNotFoundError: No module named 'libplist'_**

Any hint?

**Comment by lazka** [comment]
> Install libplist successfully by using following command from https://msys2.duckdns.org/package/mingw-w64-x86_64-libplist:

This is not a Python package.

Maybe you want https://docs.python.org/3.8/library/plistlib.html ?

**Comment by MobilEKG** [comment]
According to the webpage(https://msys2.duckdns.org/package/mingw-w64-x86_64-libplist), I suppose `mingw-w64-x86_64-libplist` has Cython configuration attached, after installing, Python should recognize it?
![image](https://user-images.githubusercontent.com/4857500/80278768-8866bf80-872b-11ea-9a20-803e8b315e5e.png)

Of course, I can try the Python package you mentioned.

**Comment by lazka** [comment]
ah, true, I missed that, sorry. I'll have a look when I'm at a windows machine.
