### ISSUE TITLE
No module named 'imobiledevice' or 'libimobiledevice' in python3

### ISSUE THREAD

**Issue by MobilEKG** [msys2/MINGW-packages#6423]
I guess this issue is similar to [msys2#6416](https://github.com/msys2/MINGW-packages/issues/6416)?

libimobiledevice has Cython configuration, but Python3 can't find it.

**Comment by Alexpux** [comment]
@MobilEKG fixed by https://github.com/msys2/MINGW-packages/commit/496f5c3f0cd14b54aafdd4ad977aa7300ca12479
