### ISSUE TITLE
idea for enhancement of gcc 9.3.0 diagnostic

### ISSUE THREAD

**Issue by ret394** [msys2/MINGW-packages#6426]
```
gcc.exe (Rev1, Built by MSYS2 project) 9.3.0
```

compile a c program.
`gcc filename.c` with a unbalanced flcose.
no warnings or errors emitted.

`gcc -Wall filename.c` with a unbalanced flcose.
`warning: unused variable 'number_of_bytes_read' [-Wunused-variable]`

at minimum, what should happen is a error should be issued in both cases. Especially the first
case.

unclosed file handles are not usually the programmer's purpose. and it can be disabled using a flag/switch.

it is a issue, please ask someone to forward it to buzzkill bugzilla.

Thank you for being here, and apologies for the delayed response.
thanks. have a nice day. keep up the good work. 👍

[ret394](https://github.com/ret394)

**Comment by lazka** [comment]
> it is a issue, please ask someone to forward it to buzzkill bugzilla.

Please forward to gcc bugzilla, thanks

**Comment by ret394** [comment]
Thanks for confirmation. I'm sorry, I can't forward it myself or would have. I haven't found a good alternative yet.

thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394)
