### ISSUE TITLE
build gdcm with applications and without manpages

### ISSUE THREAD

**Issue by hubutui** [msys2/MINGW-packages#6433]
gdcm is built with `GDCM_BUILD_APPLICATIONS=OFF` but with `GDCM_BUILD_DOCBOOK_MANPAGES=ON`. That means we build the manpages without the gdcm applications (gdcmconv, gdcminfo, etc.).
Would you like to rebuild gdcm with:
```
GDCM_BUILD_APPLICATIONS=ON
GDCM_BUILD_DOCBOOK_MANPAGES=OFF
```
Maybe we should build with `GDCM_BUILD_TESTING=OFF` too, since we don't run the test in `check()`.
We need to apply this https://github.com/malaterre/GDCM/commit/be7d49cf3d13eafffdba801ba30e1c98202843a8 to build gdcm applications with `poppler 0.87`.

**Comment by lazka** [comment]
> GDCM_BUILD_APPLICATIONS=ON

why not, check that those don't need extra dependencies

> GDCM_BUILD_DOCBOOK_MANPAGES=OFF

Why not manpages if the apps are built?

> GDCM_BUILD_TESTING=OFF

I'd say as long as building them doesn't make any problems leave it on. Maybe someone will want to fix check() in the future..

**Comment by hubutui** [comment]
> Why no manpages if the apps are built?
There is no `man` command in msys2. Maybe one could read manpages with other applications?

**Comment by lazka** [comment]
We have man.exe, but I'm not sure if/how lookup for mingw packages works

**Comment by hubutui** [comment]
Oh, I did not install `man-db`. Another question, what environment is used to build these pkgs? According to [bug 480](https://sourceforge.net/p/gdcm/bugs/480/), make with parallel build and http access to sourceforge.net do not work well together. Is there something like [this](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot) in ArchLinux to build in a clean environment?

**Comment by lazka** [comment]
We have https://packages.msys2.org/base/mingw-w64-docbook-xsl so maybe try that.

The easiest way to get a clean environment is to open a PR and let azure-pipelines build it

You could also clone https://github.com/msys2/msys2-ci-base somewhere and "git reset HEAD --hard; git clean -xfdf" if you want it clean again, but that's slow.
