### ISSUE TITLE
Qt5 QMYSQL plugin doesn't work

### ISSUE THREAD

**Issue by zgyarmati** [msys2/MINGW-packages#6434]
With the current version of  mingw-w64-qt5 and mingw-w64-libmariadbclient packages in the package repo the MySQL plugin loading is failing in the Qt applications:

>  
> QSqlDatabase: QMYSQL driver not loaded
> QSqlDatabase: available drivers: QIBASE QSQLITE QMYSQL QMYSQL3 QODBC QODBC3 QPSQL QPSQL7
> 

It seems to be that after the recent upgrade of the mingw-w64-libmariadbclient  package (85de536d827e5ad90ed36ac0bcf9ba4d4344b6f4) the mingw-w64-qt5 package need a rebuild.
To test this, i rebuilt the mingw-w64-qt5 locally, and with the newly built /mingw64/share/qt5/plugins/sqldrivers/qsqlmysql.dll lib (I only swapped that one, not the whole package) my application can properly load and use the QMYSQL plugin. So therefore i think a mingw-w64-qt5 rebuild would solve the issue.

**Comment by Alexpux** [comment]
@zgyarmati I know this by I will wait Qt 5.15 release

**Comment by zgyarmati** [comment]
This has been solved by the rebuild, thx
