### ISSUE TITLE
vtk needs a rebuild

### ISSUE THREAD

**Issue by hubutui** [msys2/MINGW-packages#6447]
`cmake` with `CMAKE_BUILD_TYPE=Debug` complains `no rule to make target C:/msys64/mingw64/lib/libtbb_debug.dll.a`. I've rebuild vtk on my computer and test it.

**Comment by hubutui** [comment]
Maybe we could just build the latest 9.0.0 version, it's released recently, see [here](https://vtk.org/download/).

**Comment by Biswa96** [comment]
Pull request is welcomed.

**Comment by lazka** [comment]
It has been rebuilt in the meantime.
