### ISSUE TITLE
Qt Creator is broken due to ICU 66

### ISSUE THREAD

**Issue by yaoye** [msys2/MINGW-packages#6459]
Qt Creator cannot be started after the latest update, and I got this:

> "error while loading shared libraries: Qt5Widgets.dll: cannot open shared object file: No such file or directory"

It seems that ICU 66.1 is incompatible with Qt Creator.

**Comment by Alexpux** [comment]
@yaoye be patient I can’t rebuild everything in one time. Qt5 is huge package and it take a day to rebuild it.

**Comment by yaoye** [comment]
Hi, @Alexpux Thanks for your work.
