### ISSUE TITLE
gcc 10.1 update..

### ISSUE THREAD

**Issue by oscarbg** [msys2/MINGW-packages#6460]
thanks..

**Comment by Biswa96** [comment]
Compiler is monumental in any package distribution system. So need time and vigorus testing.

**Comment by lazka** [comment]
current status: https://gitter.im/msys2/msys2?at=5eb57bbcb6dd230697b4440a

**Comment by lazka** [comment]
more here -> #6463

**Comment by lazka** [comment]
it's in the repo now

**Comment by oscarbg** [comment]
thanks..

**Comment by Biswa96** [comment]
Try not to upgrade GCC now. Wait for some times. There are some fixes waiting.

**Comment by oscarbg** [comment]
ok.. thanks for suggestion..
