### ISSUE TITLE
Lot of Qt based apps are broken

### ISSUE THREAD

**Issue by anlambert** [msys2/MINGW-packages#6461]
Since recent package updates, a lot of Qt based apps can not run anymore on MSYS2 platform, see below:

```
$ uic
C:/msys64/mingw64/bin/uic.exe: error while loading shared libraries: libstdc++-6.dll: cannot open shared object file: No such file or directory
```

```
$ qtcreator
C:/msys64/mingw64/bin/qtcreator.exe: error while loading shared libraries: Qt5Widgets.dll: cannot open shared object file: No such file or directory
```

```
$ cmake-gui.exe .
C:/msys64/mingw64/bin/cmake-gui.exe: error while loading shared libraries: zlib1.dll: cannot open shared object file: No such file or directory
```

I think it is related to recent ICU upgrade.

**Comment by Alexpux** [comment]
@anlambert be patient, Qt5 is rebuilding now against new ICU library.

**Comment by anlambert** [comment]
Cool :-) Is there a way to avoid breaking Qt based dependencies on each ICU upgrade ? Thanks a lot for the great work and sorry for the noise.

**Comment by Biswa96** [comment]
If you want you can ignore the package to be updated and downgrade to the older version.

**Comment by rockydut** [comment]
After I update the packages by typing pacman -Syu, the qtcreator, cmake-gui and many other packages can not be loading in mingw64. The mesage shows "error while loading shared libraries: ?: cannot open shared object file: No such file or directory.
When I click the qtcreator.exe directly, it shows cannot find libicuin65.dll and libicuuc65.dll

**Comment by elieux** [comment]
@rockydut, yes, we already know and working on a new release.
