### ISSUE TITLE
sdktool error.

### ISSUE THREAD

**Issue by rockydut** [msys2/MINGW-packages#6464]
After I update the packages min MSYS2 by typing pacman -Syu, the qtcreator, cmake-gui and many other packages can not be loading in mingw64. The mesage shows "error while loading shared libraries: ?: cannot open shared object file: No such file or directory.
When I click the qtcreator.exe directly, it shows cannot find libicuin65.dll and libicuuc65.dll.
When I click sdktool.exe directly, , it also shows cannot find libicuin65.dll and libicuuc65.dll.

**Comment by StarWolf3000** [comment]
#6461

**Comment by rockydut** [comment]
I found the reason for this error.
When update the msys2 packages with -Syu, it update the icu package. the new version of mingw-w64-x86_64-icu-66.1-1 seems error.
By setup the lower version of this package can get good running of both qtcreator and cmake.

**Comment by rockydut** [comment]
I found the reason for this error.
When update the msys2 packages with -Syu, it update the icu package. the new version of mingw-w64-x86_64-icu-66.1-1 seems error.
By setup the lower version of this package can get good running of both qtcreator and cmake.
