### ISSUE TITLE
Creating a top window in glade auto adds a custom titlebar. 

### ISSUE THREAD

**Issue by BFamzz** [msys2/MINGW-packages#6468]
When a top window is added in glade, it automatically adds a custom titlebar. Even when the custom titlebar is deleted manually from the .glade file, upon reloading the file, the custom titlebar reappears. 

@lazka 
Kindly fix this. Thanks.

**Comment by lazka** [comment]
This doesn't seem MSYS2 or Windows specific, so please file with glade: https://gitlab.gnome.org/GNOME/glade

thanks
