### ISSUE TITLE
gcc 10: invalid paths in generated .ninja_deps

### ISSUE THREAD

**Issue by Optiligence** [msys2/MINGW-packages#6469]
```
cmake_minimum_required(VERSION 3.0)
project(simple)
add_executable(${PROJECT_NAME} main.cpp)
```
```
#include <iostream>

int main() {}
```
`mkdir build; cd build; cmake -G Ninja ..; ninja; ninja`
>ninja: error: FindFirstFileExA(g/:/msys64/mingw64/include/c++/10.1.0): The filename, directory name, or volume label syntax is incorrect.

notice the `/` after the drive letter

**Comment by mati865** [comment]
See discussion in https://github.com/msys2/MINGW-packages/pull/6463

**Comment by lazka** [comment]
gobject-introspection build is also broken by this.

I've created #6470 and confirmed that it fixes the issue.. not sure if this is the right fix though..

**Comment by Optiligence** [comment]
patched through https://github.com/msys2/MINGW-packages/pull/6463#issuecomment-626828551
