### ISSUE TITLE
gcc 10: doesn’t work with UTF-8 source (+anymore)

### ISSUE THREAD

**Issue by Optiligence** [msys2/MINGW-packages#6471]
GCC 10 supposedly added UTF-8 support for identifiers
https://gcc.gnu.org/gcc-10/changes.html
>Extended characters in identifiers may now be specified directly in the input encoding (UTF-8, by default)

but
`echo ’ > enc.cpp; g++ -E enc.cpp`

```
enc.cpp:1:1: error: extended character ’ is not valid in an identifier
    1 | ▒▒▒
      | ^
# 1 "enc.cpp"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "enc.cpp"
\U00002019
```

which actually »just worked™« with GCC 9.3.0, before

**Comment by lazka** [comment]
The example from the GCC change log works:

```c
#include <stdio.h>

static const int π = 3;

int get_naïve_pi() {
    return π;
}

int main(void) {
    printf("%d\n", get_naïve_pi());
    return 0;
}
```

**Comment by Optiligence** [comment]
interesting. Apparently it has something against `’`, which could be a somewhat understandable choice for actual identifiers, although it should work for macro substitution, but doesn’t.

**Comment by lazka** [comment]
It seems like it compares the characters in the identifiers against the ranges in this table: https://github.com/gcc-mirror/gcc/blob/releases/gcc-10/libcpp/ucnid.h but not sure what this all means.

**Comment by Optiligence** [comment]
>This clause lists the complete set of hexadecimal code values that are valid in universal-character-names in C++ identifiers (2.10).

macros are identifiers too

The preprocessing use case in question actually wasn’t for valid C++ code anyway, so i guess it’s fine that it’s behaving more »strict« now.
