### ISSUE TITLE
Is it possible to provide MUMPS package by pacman?

### ISSUE THREAD

**Issue by rockydut** [msys2/MINGW-packages#6480]
During I compile the MUMPS package, there are many errors. The compile process is very difficult.
Is it possible to provide MUMPS package by pacman?

**Comment by StarWolf3000** [comment]
If there is any way to obtain the source, without having to fill out a download request form and getting vial email, then probably yes.

**Comment by rockydut** [comment]
Yes, the source code can be obtained from github, (https://github.com/scivision/mumps).
I followed the steps as provied by mumps but failed to compile this package.
Can any one build it as a library and put it into the Msys2 repository?

**Comment by Biswa96** [comment]
I am not familiar with that mumps project. I found the [mingw-w64-mumps][1] package in AUR. If you are familiar with the project and if the package will be used by many users, you can create a pull request here with the modified PKGBUILD.

[1]: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mingw-w64-mumps

**Comment by okhlybov** [comment]
@rockydut take a look at my [mumps](https://github.com/okhlybov/MINGW-packages/tree/whpc/mingw-w64-mumps) build I'm about to push upstream. This will take a while, though, as it requires some dependent packages to be pushed as well.

**Comment by MehdiChinoune** [comment]
mumps is now available as a MINGW package https://packages.msys2.org/base/mingw-w64-mumps
