### ISSUE TITLE
libgit2 static

### ISSUE THREAD

**Issue by muv1** [msys2/MINGW-packages#6482]
For some reason only the DLL is available currently. I checked, and it seems all the dependencies offer static library, so it seems it should be possible

**Comment by muv1** [comment]
I was able to do this:

~~~sh
cmake -G'MSYS Makefiles' -DBUILD_SHARED_LIBS=OFF -DBUILD_CLAR=OFF \
-DCMAKE_LIBRARY_PATH=/mingw64/x86_64-w64-mingw32/lib .
make -j 5
~~~

**Comment by lazka** [comment]
PR welcome

**Comment by muv1** [comment]
I dont want to do yet, as I cant get it to work with `git2go`. It probably works with C programs though, I am just getting linking errors.

**Comment by muv1** [comment]
@lazka do you have a test program for LibGit2? Even trying a C program, I can getting segfaults.

**Comment by muv1** [comment]
ok I got it working, need to call init else it segfaults. I will keep working on it:

~~~c
#include <git2.h>
void main() {
   git_repository* repo_ptr = NULL;
   char* repo_url = "git://github.com/muv1/gulf";
   char* repo_path = "gulf";
   git_clone_options clone_opts = GIT_CLONE_OPTIONS_INIT;
   git_libgit2_init();
   git_clone(&repo_ptr, repo_url, repo_path, &clone_opts);
}
~~~

**Comment by muv1** [comment]
I dont need this anymore, as I am just building static Git proper. But both are possible is anyone is interested. Thanks
