### ISSUE TITLE
[libgda] can not load shared library in msys2 windows 10 mingw64

### ISSUE THREAD

**Issue by sulitro** [msys2/MINGW-packages#6483]
installed it on windows 10 msys2 mingw64. when i try to run gda-sql.exe it says failed to load libxml2-2.dll , but it exists in /mingw64/bin the same directory where gda-sql is.

i run ntldd gda-sql no problem, it detected all libraries and their locations. i restart my windows 10 and re-run the app. still the same problem. is libgda broken for msys2 or did i do anything wrong ?

**Comment by bialasjaroslaw** [comment]
I have 32bit and 64bit environment but 99% time I am working on 32 bit one so 64 bit is relatively clean. I tested how it behaves (I ran pacman -Syu just to be sure that there is no pending update)

# gda-sql
C:/msys2/mingw64/bin/gda-sql.exe: error while loading shared libraries: libsoup-2.4-1.dll: cannot open shared object file: No such file or directory

# ls /mingw64/bin/ | grep libsoup
libsoup-2.4-1.dll
libsoup-gnome-2.4-1.dll

# ntldd.exe /mingw64/bin/libsoup-2.4-1.dll | grep found
        libglib-2.0-0.dll => not found
        libgobject-2.0-0.dll => not found
        libintl-8.dll => not found
        zlib1.dll => not found

# ls /mingw64/bin/ | grep libglib-2.0-0.dll
libglib-2.0-0.dll

# ntldd /mingw64/bin/libglib-2.0-0.dll | grep found
        libintl-8.dll => not found
        libwinpthread-1.dll => not found
        libpcre-1.dll => not found

libintl-8.dll is missing libiconv-2.dll but this one is perfectly fine, so I really don't know what is causing all of that.

On 32 bits there is a problem with missing dependency of libgda-5.0-4.dll which is libsecret-1-0.dll (at least in my installation). After installing it everything works fine.

**Comment by oxillo** [comment]
I've seen similar problem with openEXR 2.5.1 - downgrading to 2.4.1 solved the problem.
I've upgraded my system today and I've the problem again (openexr still at 2.4.1). So a new lib is the problem.
looks similar to #6386 and #6502

**Comment by MehdiChinoune** [comment]
We fixed all the runtime dependencies of packages some time ago.
It should be fixed now.
