### ISSUE TITLE
How to link libpardiso600-WIN-X86-64-MINGW.dll in mingw?

### ISSUE THREAD

**Issue by rockydut** [msys2/MINGW-packages#6487]
The sparse solver "pardiso" provide a version for mingw. Only dll file are provided.
The file "libpardiso600-WIN-X86-64-MINGW.dll" can be download on https://www.pardiso-project.org/
The official instruction only says the method to link in LINUX, MACOS and Windows by Microsoft cl compiles.
How knows how to link it in mingw/MSYS2.

**Comment by Biswa96** [comment]
This may help https://stackoverflow.com/a/60127525/8928481

**Comment by MehdiChinoune** [comment]
no a package of MSYS2
Maybe ask paradiso support instead.
