### ISSUE TITLE
gdb-py3-fixes.patch is no longer necessary

### ISSUE THREAD

**Issue by ChaosinaCan** [msys2/MINGW-packages#6490]
As of https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=272044897e178835f596c96740c5a1800ec6f9fb, GDB now properly supports Python 3 on MinGW. https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gdb/gdb-py3-fixes.patch still cleanly applies, but if you compile GDB linked against a version of Python you didn't also compile with MinGW, the patch bypasses the fix and GDB will crash when you try to source a Python file.

**Comment by lazka** [comment]
thanks
