### ISSUE TITLE
libunwind does not have libunwind.h

### ISSUE THREAD

**Issue by matanui159** [msys2/MINGW-packages#6500]
The [package for libunwind](https://packages.msys2.org/package/mingw-w64-x86_64-libunwind) does not contain `libunwind.h`. Is this intentional?

**Comment by mati865** [comment]
That is how upstream has configured it.
I haven't investigated but compilers seem to have their own `unwind.h`:
```
D:\msys64\mingw64\lib\clang\10.0.0\include\unwind.h
D:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\10.1.0\include\unwind.h
```

**Comment by matanui159** [comment]
I believe `unwind.h` is different (part of the system API), `libunwind.h` is the high level API for this library.

**Comment by mati865** [comment]
I have inspected llvm-libunwind CMake files and there is no code that installs headers. You should ask the upstream why they haven't included headers in install step.

**Comment by Biswa96** [comment]
But ArchLinux's [libunwind][1] has those header files. See the package contents.

[1]: https://www.archlinux.org/packages/extra/x86_64/libunwind/

**Comment by mati865** [comment]
@Biswa96 it's totally different project hosted on nongnu.org. Our package is a part of LLVM project and is often referred as llvm-unwind.

**Comment by jeremyd2019** [comment]
So apparently it was an intentional choice by upstream to *not* install libunwind headers, and that patch to install them was abandoned 4.5 years ago?

**Comment by MehdiChinoune** [comment]
libunwind now includes it.
