### ISSUE TITLE
[Question] Normal vs MinGW tool packages

### ISSUE THREAD

**Issue by Philosoph228** [msys2/MINGW-packages#6501]
What the difference between `foo` and `mingw-w64-x86_64-foo` packages, if `foo` is not a library, but an executable tool? For example, I can't make decision between `cmake` and  `mingw-w64-x86_64-cmake`. They both have same version, but different dependencies and size. I don't know which package better of both I should install and use. Please explain.

**Comment by Alexpux** [comment]
Read https://www.msys2.org/wiki/MSYS2-introduction/
