### ISSUE TITLE
vigra package broken, suspect due to hdf5 and openEXR updates

### ISSUE THREAD

**Issue by kfjahnke** [msys2/MINGW-packages#6502]
For a few weeks now, I have not been able to execute any .exe files linked with mingw-w64-vigra, even though linking produces no errors (I use clang++, the application is in C++11). The vigra package has not changed recently, and the errors I got were obscure, failing to load DLLs which were plainly there. I bundle my windows releases with all DLLs they use to create a portable application, and when I put the new .exe into an older 'bundle' of DLLs, the problem was gone. Taking it from there, I looked at vigra's dependencies and found that the HDF5 and openEXR packages were recently updated, roughly at the time the problems started. I experimentally downgraded them to the previous versions, which made the problem go away. So I suspect the upgrades to openEXR and HDF5 are incompatible with vigra as it is - maybe it's just a matter of relinking it. The offending versions of these packages are

mingw-w64-x86_64-hdf5-1.12.0-1
mingw-w64-x86_64-openexr-2.5.0-1

I downgraded to

mingw-w64-x86_64-hdf5-1.10.5-1-any.pkg.tar.xz
mingw-w64-x86_64-openexr-2.4.1-1-any.pkg.tar.xz 

with regards
Kay F. Jahnke

**Comment by Alexpux** [comment]
@kfjahnke vigra as field3d don’t have fix for build with HDF5 1.12. So it will be rebuilded when someone provide a fix

**Comment by Alexpux** [comment]
@kfjahnke fixed by https://github.com/msys2/MINGW-packages/commit/1d09c4b0ea948036be1bdf68df2ca4253c03da69
