### ISSUE TITLE
pthread not found when porting some source from linux

### ISSUE THREAD

**Issue by 19504643** [msys2/MINGW-packages#6510]
I'm building some small pieces porting from linux, which using pthread
but cmake returns error:

> CMake Error at CMakeLists.txt:108 (MESSAGE):
>   pthread not found

but when I try to list the pthread package
$ pacman -Sl | grep pthread

> mingw32 mingw-w64-i686-libwinpthread-git 8.0.0.5814.9dbf4cc1-1
> mingw32 mingw-w64-i686-winpthreads-git 8.0.0.5814.9dbf4cc1-1
> mingw64 mingw-w64-x86_64-libwinpthread-git 8.0.0.5814.9dbf4cc1-1 [installed]
> mingw64 mingw-w64-x86_64-winpthreads-git 8.0.0.5814.9dbf4cc1-1 [installed]
> msys mingw-w64-cross-winpthreads-git 8.0.0.5688.6ac47dbf-1

it says **installed**, I'm confused:
1. is this **mingw-w64-x86_64-libwinpthread-git 8.0.0.5814.9dbf4cc1-1** not the real pthread library?
2. do I have to use the the pthreads-w32
3. pthreads-w32 is building for native windows, do I have to use mingw-w64-x86_64-gcc to build pthreads from source

**Comment by mati865** [comment]
Probably CMake script issue, you will have to inspect or paste it here.

**Comment by 19504643** [comment]
@mati865 
Thanks, CMakeLists with pthread parts are as follows:
find_library(LIBPTHREAD_PATH pthread)
```
IF(NOT LIBPTHREAD_PATH)
    MESSAGE(FATAL_ERROR "pthread not found")
ENDIF(NOT LIBPTHREAD_PATH)
MESSAGE(STATUS ${LIBPTHREAD_PATH} " found")
```

**Comment by mati865** [comment]
@19504643 that looks correct.
What about output of these commands
```
which gcc
which cmake
```

**Comment by 19504643** [comment]
$ `which gcc`

> /mingw64/bin/gcc

$ `gcc -v`

> Using built-in specs.
> COLLECT_GCC=D:\msys64\mingw64\bin\gcc.exe
> COLLECT_LTO_WRAPPER=D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.1.0/lto-wrapper.exe
> Target: x86_64-w64-mingw32
> Configured with: ../gcc-10.1.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++ --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --disable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev2, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
> Thread model: posix
> Supported LTO compression algorithms: zlib zstd
> gcc version 10.1.0 (Rev2, Built by MSYS2 project)

$ `which cmake`

> /mingw64/bin/cmake

$ `cmake --version`

> cmake version 3.17.2
> 
> CMake suite maintained and supported by Kitware (kitware.com/cmake)
>

**Comment by mati865** [comment]
I have no idea what is wrong.

**Comment by ulatekh** [comment]
This is a CMake issue.
`find_library(pthread)` is not valid.
See [here](https://stackoverflow.com/questions/54189656) for the proper way to support threads.
i.e. `find_package(Threads)`

**Comment by Biswa96** [comment]
Thanks for the answer. This seem to be an old issue. Feel free to reopen if the issue persists.
