### ISSUE TITLE
Should the package mpfr depend on gmp?

### ISSUE THREAD

**Issue by stahta01** [msys2/MINGW-packages#6512]
Should the package mpfr depend on gmp?

It has this in it.
`depends=("${MINGW_PACKAGE_PREFIX}-gmp")
makedepends=("${MINGW_PACKAGE_PREFIX}-gmp")`

I understand the makedepends; but, not the depends.
mpfr is a static library and I would guess it should link to an static gmp.
Therefore, it should not need the depends on gmp, is this correct?

Tim S.

**Comment by MehdiChinoune** [comment]
mpfr is built now as a shared library.
