### ISSUE TITLE
Merge lilv,lv2,sratom,serd,sord (packages ready)

### ISSUE THREAD

**Issue by alex-tee** [msys2/MINGW-packages#6524]
Hi,

Can we please merge these here? Feel free to edit them as you see fit - I don't know what your requirements are. I have tested them with the Zrythm packages that I make and they work.

https://git.zrythm.org/zrythm/zrythm-installer/src/branch/master/windows-msys/PKGBUILD-lilv-mingw
https://git.zrythm.org/zrythm/zrythm-installer/src/branch/master/windows-msys/PKGBUILD-lv2-mingw
https://git.zrythm.org/zrythm/zrythm-installer/src/branch/master/windows-msys/PKGBUILD-serd-mingw
https://git.zrythm.org/zrythm/zrythm-installer/src/branch/master/windows-msys/PKGBUILD-sord-mingw
https://git.zrythm.org/zrythm/zrythm-installer/src/branch/master/windows-msys/PKGBUILD-sratom-mingw

Thanks,
Alex

EDIT: updated URLs

**Comment by lazka** [comment]
> Can we please merge these here?

Why do you need them? These seem like internal dependencies on a first look. Explaining why they would be useful to the community would make this more clear. Thanks!

**Comment by alex-tee** [comment]
these are not internal dependencies!

this is the [LV2 audio plugin standard](https://lv2plug.in/) and [its implementation library lilv](https://drobilla.net/category/lilv). The rest are just lilv's dependencies and include an RDF turtle parser/serializer, which I guess can be useful for other things too.

Lilv is used by a lot of audio applications to add LV2 support, such as Ardour, Audacity, LMMS (just added), Qtractor, Carla (even though Carla ships it in its sources), etc.

**Comment by lazka** [comment]
OK, thanks for the info!

**Comment by StarWolf3000** [comment]
But LV2 is a Linux-only plugin technology, on Windows you have VST.

**Comment by alex-tee** [comment]
@StarWolf3000 LV2 is NOT a Linux-only plugin technology. it is platform-agnostic.

from https://lv2plug.in/
```
The LV2 specification itself as well as the accompanying libraries are permissively licensed free software, with support for all major platforms.
```

also, VST is proprietary (VST2 at least) so we should not recommend anyone to use VST

**Comment by Biswa96** [comment]
After two while years...

I have added serd and sord for lv2 package. Please take a look at those packages. If you to add/modify any other packages I can try to help.
