### ISSUE TITLE
Aspell 0.60.8 is out.

### ISSUE THREAD

**Issue by Eason0210** [msys2/MINGW-packages#6538]
[Aspell ](http://aspell.net/)0.60.8 is already released，https://ftp.gnu.org/gnu/aspell/aspell-0.60.8.tar.gz
Do you have plan to update to the latest version. This version support camel case word check.

**Comment by mardukbp** [comment]
This version also adds support for Markdown files. Please update :)

**Comment by Eason0210** [comment]
Is there any news about updating Aspell to 0.60.8 on Mingw64?

**Comment by ZachBacon** [comment]
Feel free to submit a pull request.

**Comment by Biswa96** [comment]
Would anyone like to test the updated package from the GitHub Actions artifacts in the linked pull request?
