### ISSUE TITLE
[BUG] pacman does not pull all (tertiary) dependencies

### ISSUE THREAD

**Issue by JayEff87** [msys2/MINGW-packages#6553]
## Describe the bug

pacman appears to miss (some?) tertiary dependencies, specifically the following:
ffmpeg depends on libass which depends on harfbuzz which depends on cairo. Cairo is not pulled via pacman when pulling ffmpeg.

## Steps to Reproduce the Problem

1. Run mingw64 shell
2. run `pacman -S $MINGW_PACKAGE_PREFIX-{ffmpeg,libjpeg-turbo,lua51}`
3. run `pkg-config --print-errors --atleast-version 0.12.1 libass`

Expected behavior: the last command prints no errors.

Actual behavior: the last command outputs
```
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
Package 'cairo', required by 'harfbuzz', not found
```
a manual `pacman -S $MINGW_PACKAGE_PREFIX-cairo` fixes the problem.

## Additional Context: 

- OS: Windows 10 Pro version 1909 64bit
- I was trying to build mpv-player according to [these instructions](https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md), configuration failed with the error indicating libass was not found.

**Comment by Biswa96** [comment]
`${MINGW_PACKAGE_PREFIX}-cairo` is added as a make dependency. If you have clone this mingw-pacakges repository or have the PKGBUILD file for ffmpeg or harfbuzz try to use `makepkg -seoc` in that file path. The command will download the make dependencies but not build the package.

**Comment by avih** [comment]
> If you have clone this....

Does this confirm the issue? or does your comment imply something else should be done by the user when installing ffmpeg? (normally, without building ffmpeg locally)

**Comment by Biswa96** [comment]
As per the [harfbuzz PKGBUILD file][1], it is needed when user want to build the project/package **not** when installing/using the package.

[1]: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-harfbuzz/PKGBUILD

**Comment by Biswa96** [comment]
As per the [harfbuzz PKGBUILD file][1], it is needed when user want to build the project/package **not** when installing/using the package. See the details about [`makedepends()`][2] for further information.

[1]: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-harfbuzz/PKGBUILD
[2]: https://wiki.archlinux.org/index.php/PKGBUILD#makedepends

**Comment by lazka** [comment]
So this is some fallout from the harfbuzz meson port I guess.

**Comment by lazka** [comment]
I've asked upstream: https://github.com/harfbuzz/harfbuzz/issues/2441

**Comment by Biswa96** [comment]
@avih Forgot all the buzzwords I said. tl;dr it's just a dependency issue, no source code needed to be changed. Manual installation of cairo package will be a temporary workaround.

**Comment by Biswa96** [comment]
It seems to be fixed now, try it.

**Comment by lazka** [comment]
The cairo dep was added in 0089135c987f8824 and I also fixed this upstream

**Comment by avih** [comment]
Thanks.
