### ISSUE TITLE
glade3: Request to remove

### ISSUE THREAD

**Issue by HowardZorn** [msys2/MINGW-packages#6557]
At present, the `glade` package already exists and it is updated frequently. `glade` is the subsequent version of `glade3`, ~~with compatibility support~~. `glade3` has been deprecated in 2018, and its name is misleading. 
~~Please remove the outdated glade3 package.~~
Please modify the description of `glade3` and mark it as legacy.
Thank you.

**Comment by andreygursky** [comment]
> glade is the subsequent version of glade3, with compatibility support.

Glade3 3.8.x is the latest Glade supporting GTK 2.24.x. Can you target UI designed with Glade for GTK 2.24 and use GTK2 widgets?

**Comment by HowardZorn** [comment]
> > glade is the subsequent version of glade3, with compatibility support.
> 
> Glade3 3.8.x is the latest Glade supporting GTK 2.24.x. Can you target UI designed with Glade for GTK 2.24 and use GTK2 widgets?

Sorry, I found that impossible. But could we add "(legacy)" to the description of `glade3`? They are so similar.

**Comment by lazka** [comment]
I wouldn't mind dropping glade3. Or we could rename it to glade-gtk2

**Comment by lazka** [comment]
I've created #6601
