### ISSUE TITLE
php-config and g++ not found

### ISSUE THREAD

**Issue by TadavomnisT** [msys2/MINGW-packages#6560]
Hi, and thanks for creating this incredible package for windows.
I am trying to install a git package on windows (https://github.com/yaroslavche/phptdlib to be exact) and in the process of installation and compiling while I try to run `make` I get following errors:

```
$ make
mkdir -p shared/common
mkdir -p shared/zend
g++ -Wall -c -std=c++11 -fvisibility=hidden -DBUILDING_PHPCPP -Wno-write-strings -MD -g `php-config --includes` -fpic -o shared/common/modifiers.o common/modifiers.cpp
/bin/sh: php-config: command not found
/bin/sh: g++: command not found
make: *** [Makefile:213: shared/common/modifiers.o] Error 127
```

as you can see, there are no packages naming `php-config` and `g++` .
I went through every documentation and tutorial that I could, but it seems like the above mentioned packages are not provided in pacman.

I even tried a different way of installation using `cmake` like so, but here is the result:

```
$ cmake -G 'Unix Makefiles' -D USE_SHARED_TD:BOOL=ON -D USE_SHARED_JSON:BOOL=ON -D USE_SHARED_PHPCPP:BOOL=ON ..
CMake Error at CMakeLists.txt:63 (message):
  Failed to find php-config
-- Configuring incomplete, errors occurred!
See also "C:/Users/HoMe/Desktop/telegram_php/phptdlib/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/HoMe/Desktop/telegram_php/phptdlib/build/CMakeFiles/CMakeError.log".
```
as you can see, like the other installation, `php-config` is missing, and I guess `g++` will throw an error in future.

I was wondering if there was a solution for these two missing packages, that I can use, I'd appreciate it.

and again thanks for you time and support.

**Comment by Alexpux** [comment]
@TadavomnisT MSYS2 don’t have php packages, so you need to build it yourself

**Comment by TadavomnisT** [comment]
> 
> 
> @TadavomnisT MSYS2 don’t have php packages, so you need to build it yourself

@Alexpux oh huh, I see, Thanks for the answer, and what about `g++` ? 
I supposed installing `mingw-w64-x86_64-gcc` should have fixed that but, it didn't.

**Comment by lazka** [comment]
```
$ pacman -F g++.exe
mingw32/mingw-w64-i686-gcc 10.1.0-2 (mingw-w64-i686-toolchain) [installed: 10.1.0-3]
    mingw32/bin/g++.exe
mingw64/mingw-w64-x86_64-gcc 10.1.0-2 (mingw-w64-x86_64-toolchain) [installed: 10.1.0-3]
    mingw64/bin/g++.exe
msys/gcc 9.3.0-1 (msys2-devel) [installed]
    usr/bin/g++.exe
```

**Comment by TadavomnisT** [comment]
Thanks @lazka

**Comment by beanbuscus** [comment]
> ```
> $ pacman -F g++.exe
> mingw32/mingw-w64-i686-gcc 10.1.0-2 (mingw-w64-i686-toolchain) [installed: 10.1.0-3]
>     mingw32/bin/g++.exe
> mingw64/mingw-w64-x86_64-gcc 10.1.0-2 (mingw-w64-x86_64-toolchain) [installed: 10.1.0-3]
>     mingw64/bin/g++.exe
> msys/gcc 9.3.0-1 (msys2-devel) [installed]
>     usr/bin/g++.exe
> ```

i did this and it just sits there and doesnt install anything.
![thing](https://user-images.githubusercontent.com/96400012/150854177-d699585e-a603-4acf-b036-da7a4431b46a.PNG)

**Comment by 1480c1** [comment]
That just shows which packages provide `g++.exe`, you need to choose which one and run `pacman -S packagename`
