### ISSUE TITLE
GCC silently fails and does not output a .exe

### ISSUE THREAD

**Issue by john01dav** [msys2/MINGW-packages#6562]
I installed GCC via pacman, but, when I run it, it won't output a file and it won't print any errors:
![image](https://user-images.githubusercontent.com/3982497/83955462-d1c12900-a818-11ea-82d6-71b8165d4144.png)

**Comment by jtanx** [comment]
If you want to use the mingw compiler use the mingw prompt and not the msys prompt

**Comment by john01dav** [comment]
Thanks, that fixed it.
