### ISSUE TITLE
Get LLVM OpenMP patches upstream?

### ISSUE THREAD

**Issue by longnguyen2004** [msys2/MINGW-packages#6563]
Getting those patches upstream would allow for easier builds in the future for those expecting it to build without any patches (e.g. https://github.com/mstorsjo/llvm-mingw)

**Comment by mati865** [comment]
I think upstream would accept [`0901-openmp-kpm-lock.patch`](https://github.com/msys2/MINGW-packages/blob/7f01a5d1614d10c50938e43cae49ea7d267ccb38/mingw-w64-clang/0901-openmp-kpm-lock.patch) with possibly slight changes, you'd have to ask the author.
[`0902-libomp-weak-mingw.patch`](https://github.com/msys2/MINGW-packages/blob/7f01a5d1614d10c50938e43cae49ea7d267ccb38/mingw-w64-clang/0902-libomp-weak-mingw.patch) is a quite decent hack but doesn't meet upstream standards.
I'm going to upstream [`0903-Fix-implib-for-MinGW.patch`](https://github.com/msys2/MINGW-packages/blob/7f01a5d1614d10c50938e43cae49ea7d267ccb38/mingw-w64-clang/0903-Fix-implib-for-MinGW.patch) at some point but haven't yet got enough time to rethink if that's proper solution.

**Comment by longnguyen2004** [comment]
I've tried compiling OpenMP without 0902 and it seems to still compile, not sure what it does tho
@adrpo can you upstream 0901?

**Comment by mati865** [comment]
@longnguyen2004 0902 is necessary for binutils since their support for weak symbols on Windows is very buggy.
LLVM and LLD handle it much better (although IIRC Clang converts weak functions into normal).

**Comment by longnguyen2004** [comment]
hmm I see, I built it with the llvm-mingw toolchain so that explains it

**Comment by longnguyen2004** [comment]
@adrpo can you submit https://github.com/msys2/MINGW-packages/blob/7f01a5d1614d10c50938e43cae49ea7d267ccb38/mingw-w64-clang/0901-openmp-kpm-lock.patch

**Comment by adrpo** [comment]
@longnguyen2004 sorry, i missed the discussion, submit it where? To LLVM?

**Comment by longnguyen2004** [comment]
Yeah upstream the patch, I wanna get it included in [llvm-mingw](https://github.com/mstorsjo/llvm-mingw), which requires it to build without any patching

**Comment by adrpo** [comment]
Let me get this straight, do you want a PR on the [llvm-mingw](https://github.com/mstorsjo/llvm-mingw) repository or a patch submitted to Clang via the steps here: https://llvm.org/docs/Contributing.html?

**Comment by longnguyen2004** [comment]
I'd like it to be submitted to LLVM

**Comment by adrpo** [comment]
Ok. I'll try.

**Comment by longnguyen2004** [comment]
How is it going so far? Is there any progress yet?

**Comment by adrpo** [comment]
I read the procedure and I will give it a try later today.

**Comment by adrpo** [comment]
Let's see :)
https://reviews.llvm.org/D81776

**Comment by longnguyen2004** [comment]
Subscribed :) If this passes then mstorsjo/llvm-mingw#115 and mstorsjo/llvm-mingw#16 will be solved

**Comment by longnguyen2004** [comment]
And merged, thanks for your help! This can be closed now
