### ISSUE TITLE
adding simdjson to the package list

### ISSUE THREAD

**Issue by shavesha** [msys2/MINGW-packages#6575]
please consider adding simdjson as a package. Or is this something that anymore can do? am not entirely clear on the  procedure

**Comment by lazka** [comment]
https://aur.archlinux.org/packages/simdjson/

**Comment by shavesha** [comment]
does this imply that it is now usable?

**Comment by lazka** [comment]
I just linked the AUR package, nothing more.

**Comment by Biswa96** [comment]
Done.

**Comment by lazka** [comment]
#6649
