### ISSUE TITLE
Problem with 'Updating icon theme caches' post-transaction hook when run in pacman --root

### ISSUE THREAD

**Issue by swilmet** [msys2/MINGW-packages#6577]
See https://github.com/msys2/MSYS2-packages/issues/1998

There is one more problem:
```
:: Running post-transaction hooks...
(1/2) Compiling GSettings XML schema files...
(2/2) Updating icon theme caches...
call to execv (/usr/share/libalpm/scripts/mingw-w64-x86_64-gtk-update-icon-cache.script /usr/share/libalpm/scripts/mingw-w64-x86_64-gtk-update-icon-cache.script ) failed (No such file or directory)
error: command (/usr/share/libalpm/scripts/mingw-w64-x86_64-gtk-update-icon-cache.script /usr/share/libalpm/scripts/mingw-w64-x86_64-gtk-update-icon-cache.script ) failed to execute correctly
```

For the GTK 3 gtk-update-icon-cache hook.

It can be reproduced when installing for example gedit in the `pacman --root`.

**Comment by lazka** [comment]
thanks, likely the same problem again with the shebang using /bin/bash

**Comment by lazka** [comment]
btw it should be possible to work around this issue by `mount -o bind /<pacmna-root>/usr/bin /<pacmna-root>/bin` before installing more things, though I haven't tested it.

**Comment by lazka** [comment]
Just installed gedit this way and all went through without errors.

**Comment by swilmet** [comment]
Thanks! Yes, normally it was the last problem that I had with `pacman --root`.
