### ISSUE TITLE
OpenImageIO is still linked with OpenEXR 2.4 but the repo has updated to 2.5

### ISSUE THREAD

**Issue by itsmattkc** [msys2/MINGW-packages#6579]
The version of OpenEXR in the repository is 2.5 but the OpenImageIO package is still linked with 2.4, leading to errors that it can't find files like `libHalf-2_4.dll` when only `libHalf-2_5.dll` exists. A simple recompile/makepkg against the new OpenEXR libs fixes this issue.

**Comment by Alexpux** [comment]
@itsmattkc fixed by https://github.com/msys2/MINGW-packages/commit/5e6ec6c8896de6f881907506189fcea3d5516ffc
