### ISSUE TITLE
std::filesystem::file_size > 2 GiB

### ISSUE THREAD

**Issue by davidwed** [msys2/MINGW-packages#6585]
filesystem::filesize returns an incorrect value if the size of the file is more than 2.3 gigabyte.

As an example:

```
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdint.h>
#include <stdio.h>

int main(int argc, char** argv)
{

    uint64_t std_filesystem_file_size;
    uint64_t std_fstream_file_size;
    std::filesystem::path sourceFile = std::filesystem::current_path() / "example_3GiB.bin";

    std::ofstream ofs(sourceFile);
    ofs << "this is some text in the new file\n";
    ofs.close();
    
    std::filesystem::resize_file(sourceFile,3221225472);
    std_filesystem_file_size = std::filesystem::file_size(sourceFile);

    std::ifstream in(sourceFile.string(), std::ifstream::ate | std::ifstream::binary);
    std_fstream_file_size = in.tellg();

    std::cout << "3 GiB file:" << std::endl;
    std::cout << "std_filesystem_file_size: " << std_filesystem_file_size << std::endl;
    std::cout << "std_fstream_file_size: " << std_fstream_file_size << std::endl;
    return 0;
}
```

Output:

> 3 GiB file:
> 
> std_filesystem_file_size: 18446744072635809792
> std_fstream_file_size: 3221225472

gcc -v:

> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/lto-wrapper.exe
> Target: x86_64-w64-mingw32
> Configured with: ../gcc-10.1.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++ --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --disable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev3, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.1.0 (Rev3, Built by MSYS2 project)

**Comment by lazka** [comment]
@lhmouse ^ any idea. some google points me to https://github.com/gcc-mirror/gcc/blob/41d6b10e96a1de98e90a7c0378437c3255814b16/libstdc%2B%2B-v3/src/filesystem/ops-common.h#L66 as the potential problem

**Comment by lhmouse** [comment]
Probably `_wstati64()` should be used in place of `_wstat()`. <https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/stat-functions?view=vs-2019> suggests `struct _stat` uses a 32-bit size. Please file a bug report to GCC bugzilla.

**Comment by lazka** [comment]
Done: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95749

(I suggested _wstat64 instead of _wstati64 though, if there is a reason you used the variable version please add a comment there)

**Comment by lhmouse** [comment]
> Done: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95749
> 
> (I suggested _wstat64 instead of _wstati64 though, if there is a reason you used the variable version please add a comment there)

That asks for 64-bit time explicitly, rather than depending on `_USE_32BIT_TIME_T`. I don't have a preference of one to the other, as 64-bit time is the default now.

**Comment by lazka** [comment]
_USE_32BIT_TIME_T seems like a backwards compat hack to me, so no need make use of it in new code, but I don't know much about this..

**Comment by lazka** [comment]
This has been fixed in gcc now and will be in 10.3

**Comment by davidwed** [comment]
Yes, in version 10.3.0 the correct size is now returned.

**Comment by lazka** [comment]
thanks for testing
