### ISSUE TITLE
OpenCV Dnn Superres DLL Broken

### ISSUE THREAD

**Issue by yaoye** [msys2/MINGW-packages#6589]
Hi Guys,

With the latest upgrade, I found the link of OpenCV DNN SuperReslution (libopencv_dnn430.dll) to LibProtobuf (libprotobuf.dll) is broken.

All attempts to create an instance of the DnnSuperResImpl class will result in a protobuf dynamic link library error (internal::InternalMetadataWithArena).

Any suggestions are welcome, thanks.
Yao

**Comment by lazka** [comment]
This should be fixed now according to https://github.com/msys2/MINGW-packages/issues/6587#issuecomment-676783119

**Comment by MehdiChinoune** [comment]
likely fixed
