### ISSUE TITLE
SQLite load_extension is disabled

### ISSUE THREAD

**Issue by jokoon** [msys2/MINGW-packages#6592]
I installed libspatialite, but it requires extensions in sqlite to be enabled.

Could sqlite be changed to have extensions enabled?

I'm using spatialite with a python extension, installed with

    pip install spatialite

Which github is: https://github.com/malexer/spatialite

Alternatively, instead of this python extension, under windows I was using:

    db = spatialite.connect('db.sqlite', check_same_thread = False)
    db.enable_load_extension(True)
    db.execute('SELECT load_extension("mod_spatialite.dll")')

Under MSYS2, this errors:

    db.enable_load_extension(True)
    AttributeError: 'sqlite3.Connection' object has no attribute 'enable_load_extension'

**Comment by lazka** [comment]
Thanks for the detailed report. Looks like we first need to try building Python with `–enable-loadable-sqlite-extensions` as noted here: https://docs.python.org/3.9/library/sqlite3.html#f1

**Comment by jokoon** [comment]
doesn't that cascade into other problems?

any chance I could do something on my installation, for now?

**Comment by lazka** [comment]
> doesn't that cascade into other problems?

The official Python Windows build has this enabled, so I don't think so.

> any chance I could do something on my installation, for now?

No idea, sorry.
