### ISSUE TITLE
binutils: Missing aliases for executables

### ISSUE THREAD

**Issue by ceggers-arri** [msys2/MINGW-packages#6608]
The mingw-w64-*-binutils packages contain...

- **bin/ar.exe**
- **i686-w64-mingw32/bin/ar.exe** or **x86_64-w64-mingw/bin/ar.exe**

When I build with cmake and set **CMAKE_C_COMPILER=i686-w64-mingw32-gcc**,
cmake looks for **i686-w64-mingw32-ar**, which is not part of the package.

I set "i686-w64-mingw32-gcc" by intention, as I have both mingw32 and ming64 directories simultaneous in my %PATH% variable. While **i686-w64-mingw32-gcc** exists, **i686-w64-mingw32-ar** (and **others**) don't exist.

I found **i686-w64-mingw32-ar** in the package **mingw-w64-cross-binutils**, but this seems to be a msys package which I cannot use in my setup.

Asking Google for "x86_64-w64-mingw32-ar not found" shows that also others may be affected by this.

**Proposed solution:** Add **/bin/i686-w64-mingw32-ar.exe** (and others) to the binutils packages.

**Comment by Alexpux** [comment]
@ceggers-arri prefixed binaries only for Ross-compilers, native toolchain don’t have and will not have.

**Comment by ceggers-arri** [comment]
@Alexpux I think you're right, although the mingw-w64-*-gcc packages contains such aliases... But maybe I would like to "cross compile" for x86_64 from the mingw32 environment.

Anyway I think that the situation having multiple "native" toolchains differentiates MSYS2 from other platforms. Being able to distinguish them not only by setting the %PATH% variable but by having unique aliases would simplify my build setup. My IDE requires to have the compiler inside %PATH% at startup time. Switching between 32 and 64 bit requires restarting the IDE every time.

**Comment by Alexpux** [comment]
@ceggers-arri on your local computer or your own repo you can do how you want. 
Toolchains under /mingw32 and /mingw64 are native toolchains so they will not have prefixes.

If you need cross toolchains then you can install them from MSYS packages, they will be installed under /opt

**Comment by Biswa96** [comment]
@ceggers-arri There is a dangerous hack you can try. But **remember what you have done** so that you can revert the changes. Here is a sample shell commands:

```
cd $MINGW_PREFIX/bin

ln -sf ar.exe $MINGW_CHOST-ar.exe
ln -sf strip.exe $MINGW_CHOST-strip.exe
ln -sf windres.exe $MINGW_CHOST-windres.exe
```

**Comment by Biswa96** [comment]
@ceggers-arri There is a dangerous hack you can try. But **remember what you have done** so that you can revert the changes. Here is a sample shell commands:

```sh
cd $MINGW_PREFIX/bin

ln -sf ar.exe $MINGW_CHOST-ar.exe
ln -sf strip.exe $MINGW_CHOST-strip.exe
ln -sf windres.exe $MINGW_CHOST-windres.exe
```
