### ISSUE TITLE
libgstx265: Failed to load plugin error

### ISSUE THREAD

**Issue by BFamzz** [msys2/MINGW-packages#6615]
Hi, 

I tried to run the tutorials on the gstreamer website but I am getting an error message: 

`Failed to load plugin 'C:\msys64\mingw64\lib\gstreamer-1.0\libgstx265.dll': 'C:\msys64\mingw64\lib\gstreamer-1.0\libgstx265.dll': The specified procedure could not be found.`

How can I fix it please? Thanks.

**Comment by lazka** [comment]
Have you updated everything using `pacman -Suy`? This should be fixed already.

**Comment by BFamzz** [comment]
![image](https://user-images.githubusercontent.com/38426051/85264563-c997f900-b468-11ea-800e-d37eed3d0ace.png)

Hi @Lazka, I have everything updated. See screenshot above. Thanks.

**Comment by lazka** [comment]
ah, right, I see it too

**Comment by lazka** [comment]
Fixed in 6887115, needs a rebuild

**Comment by BFamzz** [comment]
Thanks @lazka for your help.

I will watch out for the new build on MSYS2 packages repo website. Then I'll update on my local machine. 

Thanks once again.

**Comment by BFamzz** [comment]
I have updated the package, it no longer throws the error. Thanks @lazka.
