### ISSUE TITLE
pyqt5: shell script utilities (pylupdate5, pyrcc5, pyuic5) are installed as standard Windows batch files that cannot be run from MSYS2

### ISSUE THREAD

**Issue by andlabs** [msys2/MINGW-packages#6617]
Affected packages:
* `mingw32/mingw-w64-i686-python-pyqt5` (my current version: 5.15.0-1)
* `mingw64/mingw-w64-x86_64-python-pyqt5` (my current version: 5.15.0-1)

PyQt5 comes with three utility programs, `pylupdate5`, `pyrcc5`, and `pyuic5`, which are intended to be used by developers, and which are really just shell scripts that invoke `python -m` with the appropriate Python module installed alongside them.

However, the MSYS2 packages distribute these as proper Windows batch files (`pylupdate5.bat`, `pyrcc5.bat`, `pyuic5.bat`) instead of MSYS2 compatible shell scripts. These files cannot be run (trying to run them simply prints `The device is not ready.`) and do not match `which`.

I caught this trying to build [Carla](https://github.com/falkTX/Carla), an audio plugin host, which uses `which` to determine whether PyQt5 is installed (and even if it had succeeded, it would have still failed to run the commands). I'm currently working around this with conversions of the batch files to shell scripts with the proper hashbang line to make them launchable from MSYS2.

My current `msys2-runtime` is 3.1.5-3. Thanks!

**Comment by lazka** [comment]
@andlabs should be fixed now
