### ISSUE TITLE
libsndfile: needs update to 1.0.29pre2 for pkg-config fixes

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#6618]
Upstream issue: https://github.com/erikd/libsndfile/pull/515

Upstream is trying to get a release out for a year now so waiting might be futile.

CC @andlabs

**Comment by dofuuz** [comment]
There is pre-release of next version.
http://www.mega-nerd.com/libsndfile/files/1.0.29pre2/

I think we should release this instead of waiting another year for stable.

**Comment by lazka** [comment]
Sounds good

**Comment by evpobr** [comment]
> Upstream is trying to get a release out for a year now so waiting might be futile.

https://github.com/erikd/libsndfile/releases/tag/v1.0.29

**Comment by lazka** [comment]
thanks

**Comment by evpobr** [comment]
Also you can use CMake for your builds, just forgot to remove experimental note from `README.md`. 

Right now the only question for me is `-mstackrealign` flag as in Autotools build. Should i add to CMake project too? Never had problems without it.

I will be happy to see results and fix bugs if any.
