### ISSUE TITLE
Failed compiling gcc 10 using makepkg-mingw on msys2

### ISSUE THREAD

**Issue by labba** [msys2/MINGW-packages#6621]
hi,
i have tried to build gcc-git from this on windows 10 x64 and failed during compilation. 
since this is very importand for me to share with others how to build this, i have created the report in the attached PDF to show every step of my ways from clean enviroment until the failure i see

i hope you can help resolve this so other may benefit from it 

please see here the entire issue report
[Step by step failure of compiling mingw with gcc.pdf](https://github.com/msys2/MINGW-packages/files/4823328/Step.by.step.failure.of.compiling.mingw.with.gcc.pdf)

**Comment by sfhacker** [comment]
Any updated on this open issue?

**Comment by MehdiChinoune** [comment]
closing since the package has been updated
