### ISSUE TITLE
Qt 5.15 produce a useless executable

### ISSUE THREAD

**Issue by crziter** [msys2/MINGW-packages#6629]
# Step to reproduce:

- Update system:
```sh
pacman -Syu
```

- Install `mingw-w64-x86_64-qt5`, `mingw-w64-x86_64-qt-creator` and its dependencies (`base-devel`, `mingw-w64-x86_64-toolchain`,  `mingw-w64-x86_64-cmake`)

- Create a simple QML2 project

- Build and run

# Expect:
- Hello word application should work fine

# Reality:
- The application crash
- Debug window on QtCreator show: `The program has unexpectedly finished`

# Additional information:
- Qt Widgets application doesn't crash
- The QML2 application crash with both `cmake` or `qmake` build system

**Comment by MehdiChinoune** [comment]
likely fixed
