### ISSUE TITLE
mingw-w64-x86_64-vapoursynth 49-1 is broken

### ISSUE THREAD

**Issue by norstbox** [msys2/MINGW-packages#6630]
```
$  vspipe.exe -v
Failed to initialize VapourSynth environment
```

```
$ python -c 'import vapoursynth'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'vapoursynth'
```

Renaming `/mingw64/lib/python3.8/site-packages/vapoursynth.dll` to `vapoursynth-cpython-38.dll` fix Python import, but vspipe still give same error. `mpv` player is also affected.

**Comment by Biswa96** [comment]
Hi @norstbox, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/1683122616
