### ISSUE TITLE
libavif package-request

### ISSUE THREAD

**Issue by novomesk** [msys2/MINGW-packages#6639]
Hello,
[libavif](https://github.com/AOMediaCodec/libavif) is a package to support new image format called [AVIF](https://aomediacodec.github.io/av1-avif/). AVIF is partially supported by Mozilla Firefox, Google is working on support for Chrome. AVIF is supported by Microsoft too, it can be used on Windows10 when "AV1 Video Extension" is installed.
I use libavif in my program:
https://github.com/novomesk/qt-avif-image-plugin
https://github.com/novomesk/gimp-avif-plugin
darktable is known to use the library too.
libavif is not only library, it contains command line tools called _avifenc_ and _avifdec_ to convert AVIF from/to other image formats.
libavif builds quickly and easily via cmake (uses dependencies mingw-w64-dav1d and mingw-w64-aom) but to have a package in MSYS2 is especially important for projects like GIMP (GIMP for Windows is built on MSYS2).

In case you agree for libavif to be added in future, I would prepare PKGBUILD for your review when next libavif version is released.
Current libavif version is v0.7.3 but there are some breaking changes going to be released in the future version.

Regards,
Daniel

**Comment by Biswa96** [comment]
I have already a built one. I can help to add the PKGBUILD.

**Comment by lazka** [comment]
Arch package: https://aur.archlinux.org/packages/avif/

**Comment by Biswa96** [comment]
Done.

**Comment by lazka** [comment]
#6640 

thanks @Biswa96 !
