### ISSUE TITLE
[Question] 'crtexe.c: No such file or directory' when stepping over last line of main

### ISSUE THREAD

**Issue by AEGA98** [msys2/MINGW-packages#6653]
I'm new to this so this may sound a bit dumb. I want to know if this behavior is normal or not.

When I debug a file compiled using 'gcc (Rev3, Built by MSYS2 project) 10.1.0' with gdb, and I get to the last line of the main function I get these lines in the debugger: 

(gdb) n
7       }
(gdb) n
__tmainCRTStartup () at D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:337
337     D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c: No such file or directory.
(gdb) n
338     in D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c

I want to know if that's normal because it translates to VS Code as an error message. I just close it and everything is fine but it still annoys me. I ask this because when I was using the MinGW-w64 from here https://sourceforge.net/projects/mingw-w64/, the debug lines were these (no matter what version of gdb):

(gdb) n
7       }
(gdb) n
0x00000000004013c7 in __tmainCRTStartup ()
(gdb) n
Single stepping until exit from function __tmainCRTStartup,
which has no line number information.

which didn't translate in any error on VS code.
I don't want it to step into __tmainCRTStartup(), I'm just using the 'next' command or the 'Step over' in VS Code.

**Comment by AEGA98** [comment]
Oh, I just needed to strip the debug symbols from crt2.o and that solved the "issue". No more debug warnings on VS Code (for now hehe). I did keep a copy of the original file just in case. Thank you, I'm closing the issue now.

**Comment by legion1th** [comment]
what?
