### ISSUE TITLE
Seen this before somewhere... QT5 debug binaries have .debug extension

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#6655]
I remember an old issue where this happened though i do not remember how to fix it since it screws with pacman
causing duplicate package errors unless i install QT5 with --overwrite='*'.

**Comment by Biswa96** [comment]
Please explain your issue. It is unclear what you've done and what you are going to do.

**Comment by revelator** [comment]
rebuilt qt5 and noticed that the debug executables have the extension .debug which for some reason causes pacman to croak about duplicate packages, hard to explain it as i dont remember what caused this behaviour.
But i seen it before in one of the older qt5 packages, the packages that did not throw this error had no .debug extension just added a d to the executable name.

example: Qt5Core.dll.debug Was previously named Qt5Cored.dll.

I can still install the packages but i have to use the option --overwrite='*' or it will bail out with the above error.

**Comment by revelator** [comment]
Hmm seems it also has problems locating openssl, though i get no build error QsslSocket throws a warning about it being undeclared and webkit and some KDE libraries fail to build because of it.

**Comment by revelator** [comment]
Ok got around the openssl problem by adding the openssl include dir to PKGBUILD, webkit builds now still compiling KDE.
Quassel no longer builds with this version of qt5 and webkit, seems it uses some deprecated functions.
maybe add to FAIL_LIST.md ?

**Comment by revelator** [comment]
Aye have to wait for the next version of quassel, also current version of ktexteditor needs some patching to build i managed to fix building it by using the old method -> static_cast<void(QComboBox::*)(int)>(&QComboBox::currentIndexChanged) in kateconfigpage.cpp line 72 and katedialogs.cpp at line 889 . Also need to add #include <QPainterPath> after #include <QPainter> in katecategorydrawer.cpp.

kcwsh-qt5 does not currently build, it tries to build the dll version but fails with a ton of undefined references pointing to the static libkcw.a library in qt5-static. I tried getting around that by building the shared version but it still fails though with less undefined references.

**Comment by SlySven** [comment]
IIRC the `.debug` extension is the debug information for the corresponding executable when qmake is told to "Generate separate debug info" in the Qt Creator IDE - and it causes the addition of `CONFIG+=debug CONFIG+=force_debug_info` to the `qmake` arguments. As far as I remember, `gdb` will look for that extra file if asked to debug the executable...

**Comment by revelator** [comment]
I dont mind the .debug extension but why on earth does it prevent pacman from installing the package unless i use such ugly workarounds as --overwrite='*' ?, does pacman think the debug package is the same as the release package.

**Comment by revelator** [comment]
This fixes quassel building untill next version is availiable.
[0003-qt5-5.15-compat.zip](https://github.com/msys2/MINGW-packages/files/4885010/0003-qt5-5.15-compat.zip)

**Comment by revelator** [comment]
and here is one for vtk -> missing QpainterPath include.
[009-fix-QPainterPath.zip](https://github.com/msys2/MINGW-packages/files/4885021/009-fix-QPainterPath.zip)
