### ISSUE TITLE
wxPython broken: ABI mismatch

### ISSUE THREAD

**Issue by pvgoran** [msys2/MINGW-packages#6656]
I updated my msys2 after a long time, and found that wxPython is broken: executing `import wx` in python2 shell produces the error message:

```
---------------------------
Fatal Error
---------------------------
Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1014,wx containers,compatible with 2.8),
and wxPython used 3.0 (wchar_t,compiler with C++ ABI 1013,wx containers,compatible with 2.8).
```

P. S. I hope this is the right repository to report problems like this.

**Comment by pvgoran** [comment]
Ok, after rebuilding the package from PKGBUILD and installing, the problem disappeared. So I suppose the package just needs to be refreshed in the binaries repository.

wxPython still complains about " wxPython/wxWidgets release number mismatch", but it's another matter.

**Comment by antoniovazquezblanco** [comment]
Also affected by this

**Comment by Alexpux** [comment]
It was rebuilded and uploaded some days ago

**Comment by antoniovazquezblanco** [comment]
The issue still happened to me today. I've rebuilded wxPython from source and worked succesfully. I don't know if this was due to the built package not being in the repos yet.

**Comment by Alexpux** [comment]
@antoniovazquezblanco @pvgoran current wxPython is 3.0.2-10 and it rebuilded with GCC 10, so check that you have latest version

**Comment by pvgoran** [comment]
@Alexpux @antoniovazquezblanco I updated the system with double `pacman -Syuu`. It installed the new versions of mingw-w64-i686-wxPython and mingw-w64-x86_64-wxPython (amongother things), and I can now successfully do `import wx` in python2.

**Comment by antoniovazquezblanco** [comment]
Works for me after a `pacman -Syuu`.

Thank you
