### ISSUE TITLE
License issues for OpenSSL packages?

### ISSUE THREAD

**Issue by SlySven** [msys2/MINGW-packages#6658]
All the packages are based on version **1.1.1.g** of the OpenSSL product.

The license is declared to be **"BSD"** for these:
https://packages.msys2.org/package/mingw-w64-i686-openssl?repo=mingw32
https://packages.msys2.org/package/mingw-w64-x86_64-openssl?repo=mingw64

both of which declare a requirement on the first of the following which are all declared to be **"custom:BSD"**:
https://packages.msys2.org/package/libopenssl?repo=msys
https://packages.msys2.org/package/openssl-devel?repo=msys
https://packages.msys2.org/package/openssl-docs?repo=msys

*Edit - added in later:
https://packages.msys2.org/package/openssl?repo=msys*

The licence for all of these is https://www.openssl.org/source/license-openssl-ssleay.txt which contains at least this paragraph:
> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

But this license text is not included in the files that are distributed as binary packages as far as I can tell.

I am sorry if I am being seen to be being picky but I was hoping to use files from the MSYS2 project as an SDK to build the project I code for the Windows version. However it is GPL licensed and I am trying to work my way through the license minefield that there is around *distributing* a product that includes a pre-version 3.0 OpenSSL library linked to an executable that is currently GPL2.0 or later licensed - the best explanation I have found so far is: https://people.gnome.org/~markmc/openssl-and-the-gpl.html .

**Comment by SlySven** [comment]
:mag_right: Forgive me please - I did manage to eventually track down `/usr/share/licenses/openssl/LICENSE` which belongs - according to `pacman` to the `openssl` package which I hadn't included by accident in the above set of packages. I do not know if the MSYS2 package management system allows for more than one owner for a single file but it strikes me that this file needs to be present if *any* of the openssl packages are installed in a system not just a specific one!

**Comment by lazka** [comment]
> I do not know if the MSYS2 package management system allows for more than one owner for a single file but it strikes me that this file needs to be present if _any_ of the openssl packages are installed in a system not just a specific one!

It doesn't, but we can move it into the libopenssl package

**Comment by lazka** [comment]
Re gpl+openssl, yes, tricky. 3.0 will make things better but like with every major update it will also take some time until all users are ported.

**Comment by lazka** [comment]
> > The license is declared to be **"BSD"** for these:
> > https://packages.msys2.org/package/mingw-w64-i686-openssl?repo=mingw32
> > https://packages.msys2.org/package/mingw-w64-x86_64-openssl?repo=mingw64
> 
> yeah, that's wrong
> 
> > I do not know if the MSYS2 package management system allows for more than one owner for a single file but it strikes me that this file needs to be present if _any_ of the openssl packages are installed in a system not just a specific one!
> 
> It doesn't, but we can move it into the libopenssl package

These are both changed now and will be in the next update.
