### ISSUE TITLE
scalapack patching script

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#6660]
Was ->
`prepare() {
  cd "${srcdir}/${_realname}-${pkgver}"
  for p in ${srcdir}/../*.patch; do
    patch -p1 < $p
  done
}`

which would resolve to patch -p1 -i ${srcdir}/../somepatch.patch

should probably be ->

`prepare() {
  cd "${srcdir}/${_realname}-${pkgver}"
  for p in ${srcdir}/*.patch; do
    patch -p1 < $p
  done
}`

so that it follows the normal way patching is done eg. patch -p1 -i ${srcdir}/somepatch.patch

**Comment by Biswa96** [comment]
There is a `cd "${srcdir}/${_realname}-${pkgver}"` before patch command and the patch command does not have the `-i` option. So, do the rest ;)

**Comment by revelator** [comment]
well there is in the pull from master i did so oversight maybe ?.

**Comment by revelator** [comment]
Ah np no there is no -i in the script but it still resolves to -p1 ${srcdir}/../somepatch.patch and srcdir is static it is allways the root of the PKGBUILD so if i build it in D: it will look for the patch in D:/mingw-w64-scalapack and not in D:/mingw-w64-scalapack/src. the reason i think it might work for you is that you build it without BUILDDIR set so the patches are present in the lower level dir. Eg. you have the mingw-packages repo on C:/mingw-packages so you also have C:/mingw-packages/mingw-w64/scalapack/somepatch.patch but if you build in D: you have D:/mingw-w64-scalapack/ but no patches in it since pacman only copies those to the srcdir so they are located in D:/mingw-w64-scalapack/src.

**Comment by MehdiChinoune** [comment]
PKGBUILD was updated
