### ISSUE TITLE
[fontconfig] gimp could not find any fonts

### ISSUE THREAD

**Issue by kerwinxu** [msys2/MINGW-packages#6661]
mingw-w64-x86_64-fontconfig-2.13.92-1 has problem . gimp could not find any fonts .

**Comment by Jehan** [comment]
Hi!

This was fixed upstream at Fontconfig which had a regression on `FcConfigParseAndLoad*()`:
https://gitlab.freedesktop.org/fontconfig/fontconfig/-/commit/fcada522913e5e07efa6367eff87ace9f06d24c8

So either Msys2 should downgrade (also apparently the stable release is `2.13.1`; why does Msys2 release an unstable version?), or should cherry-pick this fix.
Thanks for all the hard work! 🙂

**Comment by Biswa96** [comment]
> why does Msys2 release an unstable version?

Msys2 is inherited from ArchLinux, so being unstable is in it's gene 😎 Also fontconfig has 2.13.92 tag.

There are two options:

1. Import the patch file here and rebuild the package. It builds without any compiler error (at least).
2. Use the fontconfig git repository with a specific commit. But need someone familiar with the project.

Which one is better option here?

**Comment by Jehan** [comment]
> Msys2 is inherited from ArchLinux, so being unstable is in it's gene sunglasses Also fontconfig has 2.13.92 tag.

Ok.

> Which one is better option here?

Personally I would just go the patch way, because just adding more experimental commits in may bring you more work-in-progress bugs. I mean, unless you get lucky or you've got time on your hand, this is most likely not recommended.

But in the end, the choice is yours, not mine. 🙂

**Comment by lazka** [comment]
@Jehan thanks for the hint re the regression/patch!

Not sure why fontconfig was updated...

**Comment by lazka** [comment]
new package including the fix is out

**Comment by lazka** [comment]
Inkscape noted in #7230 that things are still broken. Does anyone know more?
