### ISSUE TITLE
gobject-introspection: mssing file extenion in .pc file breaks meson 0.55.0

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#6677]
See https://github.com/harfbuzz/harfbuzz/issues/2561#issuecomment-657261692

This is because we convert the g-ir-scanner script to an .exe, but the g-i build system doesn't know about this.

This blocks the meson update to 0.55.0

**Comment by ebraminio** [comment]
@lazka thank you so much :)

**Comment by lazka** [comment]
It will take some time until this hits the repo... we are currently in a maintainer "transition".
