### ISSUE TITLE
gcc:  64-bit image are built with a preferred base address below the 4GB boundary

### ISSUE THREAD

**Issue by salowenh** [msys2/MINGW-packages#6682]
We are building with the following makepkg64 config:
```
CPPFLAGS="-D__USE_MINGW_ANSI_STDIO=1"
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe"
CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe"
LDFLAGS="-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat"
MAKEFLAGS="-j$(($(nproc)+1))"
DEBUG_CFLAGS="-ggdb -Og"
DEBUG_CXXFLAGS="-ggdb -Og"
```
BinSkim flags 64 bit dll's saying their preferred base address is below the 4GB boundry.
Here is the exact message:
```
error BA2001: 'libffi-6.dll' is a 64-bit image with a preferred base address below the 4GB boundary. Having a preferred base address below this boundary triggers a compatibility mode in Address Space Layout Randomization (ASLR) on recent versions of Windows that reduces the number of locations to which ASLR may relocate the binary. This reduces the effectiveness of ASLR at mitigating memory corruption vulnerabilities. To resolve this issue, either use the default preferred base address by removing any uses of /baseaddress from compiler command lines, or /BASE from linker command lines (recommended), or configure your program to start at a base address above 4GB when compiled for 64 bit platforms (by changing the constant passed to /baseaddress or /BASE). Note that if you choose to continue using a custom preferred base address, you will need to make this modification only for 64-bit builds, as base addresses above 4GB are not valid for 32-bit binaries
```
I've looked for a `/baseaddress` or `/BASE` flag but I'm not sure it's there. Any reason why the preferred base address for 64bit images will be below 4GB and how can it be altered?

**Comment by mati865** [comment]
`/base` and `/baseaddress` are MSVC linker arguments, could you try if linking with LLD (`-fuse-ld=lld`) gives the same error?

**Comment by salowenh** [comment]
@mati865 thanks for the quick reply.
I get a compilation error when adding the LLD:

LDFLAGS="-pipe **-fuse-ld=lld** -Wl,--dynamicbase,--high-entropy-va,--nxcompat"

Am I setting it wrongly?

**Comment by mati865** [comment]
> I get a compilation error when adding the LLD:

Which error?

LDFLAGS look good.

**Comment by salowenh** [comment]
```
configure: loading site script /etc/config.site
checking for x86_64-w64-mingw32-gcc... x86_64-w64-mingw32-gcc
checking whether the C compiler works... no
configure: error: in `/c/dev/MINGW-packages/mingw-w64-bzip2/src/build-x86_64':
configure: error: C compiler cannot create executables
See `config.log' for more details
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by mati865** [comment]
You would have to find configure log somewhere in `src/build-x86_64` but it's possible that this package doesn't build with LLD out of the box.

In case you don't want to dig deeper with LLD you can report this issue to binutils bugtracker since it's LD bug.

**Comment by salowenh** [comment]
It fails for glib as well:
```
Sanity check compiler command line: cc C:/dev/MINGW-packages/mingw-w64-glib2/src/build-x86_64-static/meson-private/sanitycheckc.c -o C:/dev/MINGW-packages/mingw-w64-glib2/src/build-x86_64-static/meson-private/sanitycheckc.exe -march=x86-64 -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -pipe -fuse-ld=lld -Wl,--dynamicbase,--high-entropy-va,--nxcompat
Sanity check compile stdout:

-----
Sanity check compile stderr:
collect2.exe: fatal error: cannot find 'ld'
compilation terminated.

-----

../glib-2.64.3/meson.build:1:0: ERROR: Compiler cc can not compile programs.
```

**Comment by salowenh** [comment]
@mati865 any idea if that can be resolved?

**Comment by mati865** [comment]
@salowenh to fix it when using LD you'd have to report it to binutils bug tracker.

For error with LLD you need `mingw-w64-x86_64-ldd` package installed.

**Comment by mati865** [comment]
Found upstream issue: https://sourceware.org/bugzilla/show_bug.cgi?id=19011
FFmpeg has this workaround: https://github.com/TheRyuu/FFmpeg/commit/f2b805d02ee12af5593130ef06f0924422e8622e

LLD already does the right thing: https://github.com/llvm/llvm-project/blob/49193e1fe7e143555d3b740610d6d1d20a553b2f/lld/COFF/Driver.cpp#L604-L608

**Comment by jeremyd2019** [comment]
I think this is fixed now

**Comment by jeremyd2019** [comment]
oh, btw, the option for setting the base is `-Wl,--image-base=0x...`

**Comment by salowenh** [comment]
thank you @jeremyd2019. Marking as fixed
#6880
