### ISSUE TITLE
How to rebuild non-existing dependencies

### ISSUE THREAD

**Issue by salowenh** [msys2/MINGW-packages#6690]
We are using `libgsf` which has quite a few dependencies.
I was able to recompile some of them with different flags as the original flags are flagged as security risk.
For example, here are the dependencies I wasn't able to find:
```
libintl-8.dll
libgcc_s_dw2-1.dll
libffi-6.dll - (only libffi-7?)
```
Is there any way to get these dependencies dll's recompiled with my flags other than the default's?

**Comment by mati865** [comment]
```
$ LANG=C pacman -Qo /mingw64/bin/libintl-8.dll /mingw32/bin/libgcc_s_dw2-1.dll /mingw64/bin/libffi-7.dll
/mingw64/bin/libintl-8.dll is owned by mingw-w64-x86_64-gettext 0.19.8.1-9
/mingw32/bin/libgcc_s_dw2-1.dll is owned by mingw-w64-i686-gcc-libs 10.1.0-3
/mingw64/bin/libffi-7.dll is owned by mingw-w64-x86_64-libffi 3.3-1
```
Nothing should depend on `libffi-6` as it's an old version.

**Comment by salowenh** [comment]
thanks @mati865, given that `libgsf` does use `libffi-6`, any way out here? I assume building `libffi-7` under the hood will end badly :)

**Comment by mati865** [comment]
@salowenh `libffi-6.dll` is not available in the repository so you should be getting error about missing dependency unless you have very old libffi installed or provided `libffi-6.dll` by yourself.
Rebuilding libgsf with latest libffi installed will make it depend on `libffi-7.dll`.

**Comment by lazka** [comment]
I don't see any of libgsf libs depending on libffi.

@salowenh please show why you think it does.

**Comment by MehdiChinoune** [comment]
no info!
