### ISSUE TITLE
Problems caused by hard-coded paths in LibwebsocketsTargets-release.cmake

### ISSUE THREAD

**Issue by tobiichiamane** [msys2/MINGW-packages#6692]
### Problem

When compiling a cmake project that depends on libwebsockets outside of msys2 environment, compiler will fail with `No rule to make target '/mingw64/lib/libssl.dll.a'`.

### Fix

Edit file `/mingw64/lib/cmake/libwebsockets/LibwebsocketsTargets-release.cmake`, change all hard-coded `/mingw64/lib/*` to `${_IMPORT_PREFIX}/lib/*`

**Comment by Biswa96** [comment]
There is a new package of libwebsocket version 4.0.20. Would you like to check if the issue is fixed?

**Comment by tobiichiamane** [comment]
I can confirm that this issue has been fixed in package `mingw-w64-x86_64-libwebsockets-4.0.20-1`, but I didn't check the i686 version of this package.

**Comment by tobiichiamane** [comment]
And I can confirm that this issue has been fixed in package `mingw-w64-i686-libwebsockets-4.0.20-1`. Closing issue.
