### ISSUE TITLE
What for OpenGL?

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#6693]
Building an app fails with:

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lGL[...]
```

Is there in MSYS2 a package to install that can fix this error?

I looked at `glew` and `mesa` but did not find anything related to `libGL*`. BTW, `freeglut` is already installed...

**Comment by Biswa96** [comment]
Can you provide the link of the project and how you have tried to built it?

**Comment by angelog0** [comment]
The project is [this](https://github.com/interkosmos/fortran-sdl2) and tu build the openGL example just run:

```
cd fortran-sdl2
make opengl
```

Notice, all other examples build and I use that also for my fortran-sdle apps since 2018.

**Comment by Biswa96** [comment]
There is no opengl example in that fortran-sdl2 repository.

**Comment by angelog0** [comment]
Hi, @Biswa96, now there are 2 examples of OpenGL which fail. See `gl` and `gl3d` folder under https://github.com/interkosmos/fortran-sdl2/tree/master/examples

**Comment by Biswa96** [comment]
Try with the pull request https://github.com/interkosmos/fortran-sdl2/pull/18. gl3d does not work but gl does.

**Comment by angelog0** [comment]
@Biswa96, you do not answer the basic question: is in MSYS2/MINGW a package with those libraries, containing `libGL*` files?What you propose could be just a workaround which work on Windows but what about the other platforms?

BTW, on Windows where do the needed opengl files live so I can symlink them?

**Comment by Biswa96** [comment]
GL.so and GLU.so are *nix libraries. The Windows counterpart are opengl32.dll and glu32.dll and those are in System32 folder. You don't have to install anything.

**Comment by angelog0** [comment]
I just discovered this:

```
# find /c/ -name "*opengl*"
[...]
/c/msys64/opt/x86_64-w64-mingw32/lib/libopengl32.a
/c/msys64/usr/lib/w32api/libopengl32.a
[...]
```

So, _MSYS2_ already has packages which install 

```
/opt/x86_64-w64-mingw32/lib/libopengl32.a
/opt/x86_64-w64-mingw32/lib/libglul32.a

/usr/lib/w32api/libopengl32.a
/usr/lib/w32api/libglu32.a
```

and this works:

```
make gl
[...]
gfortran -Wall -std=f2008 -fmax-errors=1 `sdl2-config --cflags` -o examples/gl/gl examples/gl/gl.f90 sdl2.a `sdl2-config --libs` /usr/lib/w32api/libopengl32.a

./examples/gl/gl.exe

make gl3d
[...]
gfortran -Wall -std=f2008 -fmax-errors=1 `sdl2-config --cflags` -o examples/gl3d/gl3d examples/gl3d/gl3d.f90 sdl2.a glu.a `sdl2-config --libs` /usr/lib/w32api/libopengl32.a /usr/lib/w32api/libglu32.a

cd examples/gl3d
./gl3d.exe

```

The same with the other set of opengl,glu libraries. 

So, maybe, is _MSYS2_ which should symlink those libraries.

I am sure you already have a patch...

**Comment by mati865** [comment]
You are supposed to use `*32` OpenGL libraries on Windows, blame Microsoft.

**Comment by angelog0** [comment]
@mati865 , I do not think, I run those example in MSYS2/MINGW64 which uses

```
gfortran -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gfortran.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-10.1.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++ --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --disable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev3, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.1.0 (Rev3, Built by MSYS2 project)
```

I do not remember it can mix 64 and 32 bit code.

**Comment by angelog0** [comment]
BTW, another set of OpenGL libraries in MSYS2

```
pacman -Qo /mingw64/x86_64-w64-mingw32/lib/libopengl32.a
/mingw64/x86_64-w64-mingw32/lib/libopengl32.a è contenuto in mingw-w64-x86_64-crt-git 8.0.0.5941.736c7a24-1
```

and

```
gfortran -Wall -std=f2008 -fmax-errors=1 `sdl2-config --cflags` -o examples/gl/gl examples/gl/gl.f90 sdl2.a `sdl2-config --libs` -lopengl32
```

uses that. 

So the OpenGL libraries in mingw-w64-x86_64-crt-git should be symlinked.

**Comment by angelog0** [comment]
@mati865 , I forgot to say that

```
find /c/ -name "*opengl*"
[...]
/c/Windows/System32/opengl32.dll
/c/Windows/SysWOW64/opengl32.dll
```

so, despite of the `...32...` also Windows provides the 64 bit version:

```
ls -lrt /c/Windows/System32/opengl32.dll /c/Windows/SysWOW64/opengl32.dll
-rwxr-xr-x 2 angelo NESSUNO 1284096  7 dic  2019 /c/Windows/System32/opengl32.dll
-rwxr-xr-x 2 angelo NESSUNO  906752  7 dic  2019 /c/Windows/SysWOW64/opengl32.dll
```

**Comment by angelog0** [comment]
Definitively:

```
cd /mingw64/x86_64-w64-mingw32/lib
ln -sf libopengl32.a libGL.a
ln -sf libglu32.a libGLU.a


make gl
[...]
gfortran -Wall -std=f2008 -fmax-errors=1 `sdl2-config --cflags` -o examples/gl/gl examples/gl/gl.f90 sdl2.a `sdl2-config --libs` -lGL

make gl3d
gfortran -Wall -std=f2008 -fmax-errors=1 `sdl2-config --cflags` -fPIC -c src/glu.f90
ar rcs glu.a glu.o
gfortran -Wall -std=f2008 -fmax-errors=1 `sdl2-config --cflags` -o examples/gl3d/gl3d examples/gl3d/gl3d.f90 sdl2.a glu.a `sdl2-config --libs` -lGL -lGLU


echo $MSYS
winsymlinks:nativestrict

$ echo $MSYSTEM
MINGW64

```

**Comment by Alexpux** [comment]
@angelog0 no one will do symlinks, Windows have its own OpenGL libraries name. If you need it do it yourself locally

**Comment by angelog0** [comment]
@Alexpux , there is not need to symlink Windows libraries.  There are at least 3 packages in MSYS2 which contain `libopengl32.a` and `libglu32.a` and if you have read at least [this](https://github.com/msys2/MINGW-packages/issues/6693#issuecomment-660545887), the symlinks would fix the build of GNU/Linux apps based on OpenGL.

After all, is MSYS2 a means to build GNU/Linux apps so that they become Windows native?

Anyway if you don't want...

**Comment by Biswa96** [comment]
It looks like you blame MSYS2 instead of Windows itself. OpenGL is a specification. OpenGL does not care about how and where the OS implements it. Microsoft chose the library name "opengl32". So, programs have to link with that library.

**Comment by angelog0** [comment]
I do not blame anyone. I flag arguments that could make software better.

**Comment by Alexpux** [comment]
@angelog0 better is fill bugreport upstream to project to fix linking using Windows SDK.

**Comment by Biswa96** [comment]
I have already sent a patch to makefile to that fortran-sdl2 project. Link in my previous comment.

**Comment by angelog0** [comment]
Sincerely I do not understand your logic. 

Anyway the patch proposed by @Biswa96 does not work if package `mingw-w64-x86_64-crt-git` is not installed.

I renamed 

```
mv libopengl32.a libopengl32.a-save
```

in `/mingw64/x86_64-w64-mingw32/lib/` and the build fails. 

After all the patch says:

```
ifeq ($(OS), Windows_NT)
    LIBGL  = -lopengl32
    LIBGLU = -lglu32
```

which assumes the files are `libopengl32.a` and `libglu32.a` while the Windows libraries sound as

```
/c/Windows/System32/opengl32.dll 
/c/Windows/SysWOW64/opengl32.dll
```

**Comment by mati865** [comment]
> Anyway the patch proposed by @Biswa96 does not work if package mingw-w64-x86_64-crt-git is not installed.

That's definitely expected, to use mingw-w64 you need it's imports libraries from crt package...

**Comment by oscarfv** [comment]
> > Anyway the patch proposed by @Biswa96 does not work if package mingw-w64-x86_64-crt-git is not installed.
> 
> That's definitely expected, to use mingw-w64 you need it's imports libraries from crt package...

I think that the OP does not realize that those "libraries" are just import libraries, which means that do not contain code at all and just provide the necessary information to link to DLLs in `Windows/System32`.

**Comment by angelog0** [comment]
@oscarfv, I realized that as well as a MSYS2+MINGGW package is needed, so why not to add just 2 symlinks which would work also with other similar apps ported from GNU/Linux. After all, isn't MSYS2 a system to port GNU/Linux apps to Windows native?

Anyway, if MSYS2 developers don't wont for what ever reason, it is ok for us and maybe we can close this.

**Comment by oscarfv** [comment]
> @oscarfv, I realized that as well as a MSYS2+MINGGW package is needed, so why not to add just 2 symlinks which would work also with other similar apps ported from GNU/Linux. After all, isn't MSYS2 a system to port GNU/Linux apps to Windows native?
> 
> Anyway, if MSYS2 developers don't wont for what ever reason, it is ok for us and maybe we can close this.

The suggested change is for MinGW-w64, not MSYS2. MinGW-w64 is *not* about mimicking GNU/Linux. Creating symlinks requires Administrator privileges.

**Comment by lazka** [comment]
I guess everything is said and done here. Thanks @Biswa96 for fixing this upstream (or trying to at least)
