### ISSUE TITLE
libavif 0.8.0 update-request

### ISSUE THREAD

**Issue by novomesk** [msys2/MINGW-packages#6694]
Thanks for adding the previous libavif 0.7.3 version in https://github.com/msys2/MINGW-packages/issues/6639

There is a new [libavif](https://github.com/AOMediaCodec/libavif/releases/tag/v0.8.0) version with significant important changes available.

Among the new features there is also a possibility to build a gdk-pixbuf loader. cmake `-DAVIF_BUILD_GDK_PIXBUF=ON` parameter is needed to activate the component and `gdk-pixbuf2` is a new dependency.

**Comment by Biswa96** [comment]
Tried it. But the `gdk_pixbuf_moduledir` variable seems to be evaluated incorrectly. After packaging x86_64 one, `libpixbufloader-avif.dll` installs in `msys64/mingw64` folder instead of `/mingw64`.

**Comment by novomesk** [comment]
Hmm,
For me it installed to the same folder as other pixbufloader plugins.
However I started to experience crashes in this new component (I will investigate later) so I think to leave this new feature disabled.
Will you update libavif to 0.8.0 without gdk-pixbuf or do you think it is wiser to wait for the next version?

**Comment by Biswa96** [comment]
I would like to investigate it more.

**Comment by novomesk** [comment]
I regret I suggested you to add `-DAVIF_BUILD_GDK_PIXBUF=ON` parameter. 
There is a [crash](https://github.com/AOMediaCodec/libavif/issues/237) and the small fix in https://github.com/AOMediaCodec/libavif/commit/9759bc7346802faa8ec96bb38456d8b8170580aa

**Comment by 1480c1** [comment]
Perhaps we can request @joedrago to tag a patch version after making sure there's no other immediate fix that is needed?

Alternatively, we could just pull `https://github.com/AOMediaCodec/libavif/commit/9759bc7346802faa8ec96bb38456d8b8170580aa.patch` and apply that in `prepare()` for now

**Comment by joedrago** [comment]
I think the patch strategy scales better with future minor tweaks from the contrib directory. It makes for a better pattern that puts control in the hands of the package maintainers. I'm not vetoing the idea completely, however.

**Comment by lazka** [comment]
I've added the patch in master

**Comment by novomesk** [comment]
Unfortunately, the first patch is not enough to solve all crashes of the new gdk-pixbuf loader.
What to do? Extend the patch or to remove the component and to wait for next libavif version?

**Comment by Biswa96** [comment]
Report the issues to upstream. Either wait for next release or revert back to previous libavif version. The old version can be downloaded from here http://repo.msys2.org/mingw/x86_64/.

**Comment by novomesk** [comment]
I created PR with fix to gdk-pixbuf component in libavif.
It was accepted recently.
Latest versions of my software don't work with old libavif (lot of breaking changes). The core libavif 0.8.0 is good and needed. The new gdk-pixbuf feature is broken in 0.8.0
