### ISSUE TITLE
link to OpenSceneGraph failed

### ISSUE THREAD

**Issue by starling13** [msys2/MINGW-packages#6698]
A simple openscenegraph test application with osg::Viewer creation failed to build:
**`$ /mingw64/bin/g++ 'pkg-config --cflags openscenegraph' 'pkg-config --libs openscenegraph' ./main.cpp`**
`
D:/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\msys\tmp\ccmURWym.o:main.cpp:(.text+0x20): undefined reference to `__imp__ZN9osgViewer6ViewerC1Ev'
D:/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\msys\tmp\ccmURWym.o:main.cpp:(.text+0x57): undefined reference to `__imp__ZN9osgViewer4View17setUpViewInWindowEiiiij'
D:/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\msys\tmp\ccmURWym.o:main.cpp:(.text+0x67): undefined reference to `__imp__ZN9osgViewer6Viewer3runEv'
D:/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\msys\tmp\ccmURWym.o:main.cpp:(.text+0x7c): undefined reference to `__imp__ZN9osgViewer6ViewerD1Ev'
D:/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\msys\tmp\ccmURWym.o:main.cpp:(.text+0x93): undefined reference to `__imp__ZN9osgViewer6ViewerD1Ev'

`

**Comment by Biswa96** [comment]
Could you provide a [simple, minimal example][1] to reproduce the issue?

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by starling13** [comment]
main.cpp:
`#include <osgViewer/Viewer>

int main()
{
    osgViewer::Viewer v;
    v.setUpViewInWindow(100,100, 800,600);
    v.run();

    return EXIT_SUCCESS;
}
`

$ /mingw64/bin/g++ 'pkg-config --cflags openscenegraph' 'pkg-config --libs openscenegraph' ./main.cpp

**Comment by Biswa96** [comment]
This may work `g++ test.cpp -losgViewer`.

**Comment by starling13** [comment]
> This may work g++ test.cpp -losgViewer.

Thank you. It's working! After years of linux programming it's hard to do something on windows...
