### ISSUE TITLE
[opencv] DLL load fail when importing to python

### ISSUE THREAD

**Issue by ChemistKieran** [msys2/MINGW-packages#6704]
Hi, 

After installing mingw-w64-x86_64-opencv
When trying import cv2 in python I get the following error:

>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing cv2: The specified procedure could not be found.

I've tried from a fresh install and also previous versions of opencv . 

-Thanks

**Comment by lazka** [comment]
This should be fixed now according to https://github.com/msys2/MINGW-packages/issues/6587#issuecomment-676783119
