### ISSUE TITLE
gcc 10 -> 9

### ISSUE THREAD

**Issue by mipac** [msys2/MINGW-packages#6705]
Is it possible to downgrade mingw-w64-gcc from 10 to 9 serie
10 is to experimental and induce compile errors...

perharps leaving the choice between a stable et testing release

regards

**Comment by 1480c1** [comment]
Since pacman just doesn't work that way :tm:, unless a metapackage like `mingw-w64-x86_64-gcc-9` is introduced, you will need to manually download the packages you need from http://repo.msys2.org/mingw/x86_64/ and keep them locally.

you can use `pacman -U gcc.pkg.tar.zst` to install the package you want

**Comment by Biswa96** [comment]
@mipac If mingw-w64-gcc 10 produces compiler error you can share it here. Maybe we can help to solve it.

**Comment by mipac** [comment]
for example when compiling flatbuffers library:

```
[ 86%] Building CXX object CMakeFiles/flattests.dir/tests/test.cpp.obj
In file included from C:/michel/DEV/targets/windows10/amd64/src/flatbuffers/include/flatbuffers/flatbuffers.h:20,
                 from C:\michel\DEV\targets\windows10\amd64\src\flatbuffers\tests\test.cpp:17:
C:/michel/DEV/targets/windows10/amd64/src/flatbuffers/include/flatbuffers/base.h: In function 'void MutateFlatBuffersTest(uint8_t*, std::size_t)':
C:/michel/DEV/targets/windows10/amd64/src/flatbuffers/include/flatbuffers/base.h:363:29: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  363 |   *reinterpret_cast<T *>(p) = EndianScalar(t);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
In file included from C:\michel\DEV\targets\windows10\amd64\src\flatbuffers\tests\test.cpp:17:
C:/michel/DEV/targets/windows10/amd64/src/flatbuffers/include/flatbuffers/flatbuffers.h:2357:11: note: at offset 0 to object 'flatbuffers::Table::data_' with size 1 declared here
 2357 |   uint8_t data_[1];
      |           ^~~~~

```
after some google, it seems coming from 
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91707

but can't investigate... to deep for me ;)

thx for your replies

**Comment by Biswa96** [comment]
The project seems to use `-Werror` option in cmake. You can remove that option from CMakeLists.txt file so that the warnings are not treated as errors.

**Comment by umarcor** [comment]
As commented in gtkwave/gtkwave#20 I found that building gtk2 produces random compiler crashes:

```
internal compiler error: Segmentation fault
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://sourceforge.net/projects/msys2> for instructions.
```

There is a GitHub Actions workflow (https://github.com/gtkwave/gtkwave/actions?query=workflow%3Abuild) to build gtk2 and gtk3 on MINGW32 and MINGW6t4. The jobs for gtk3 are successful. The ones for gtk2 fail randomly:

- MINGW32 ok, MINGW64 fail: https://github.com/gtkwave/gtkwave/actions/runs/177799675
- Both fail: https://github.com/gtkwave/gtkwave/actions/runs/176410626
- MINGW32 fail, MINGW64 ok: https://github.com/umarcor/gtkwave/actions/runs/155865824
- Both ok: https://github.com/umarcor/gtkwave/actions/runs/175608842

**Comment by mipac** [comment]
it works when forcing -Wno-error...
thanks for replies

but It should be safe to have gcc-X packages
working with gcc 10, or more can be very problematic

it's so bad that a so wonderful project is hard to use cause of git and gcc problems... 2 days wiped out for me...

**Comment by bernd5** [comment]
It is a gcc bug (false positive). Now you can download gcc 10.2 which has a lot of fixes...
(this too)

**Comment by mipac** [comment]
thx very much
