### ISSUE TITLE
Availability of GCC/G++ 11 or 10.2

### ISSUE THREAD

**Issue by bernd5** [msys2/MINGW-packages#6713]
Hello,

I'd like to use the newest gcc/g++ versions (because of bugs, missing features...).
Is there any schedule when such packages are released.
Is there a simple manual how to build gcc manually for MSYS2 (I would prefer pacman because to compile gcc it needs some time...)?

I have seen that there is a package called gcc-git? What is it used for, how to download it / install it?

Kind regards,

Bernd

**Comment by lazka** [comment]
10.2.0 is in the repo now

**Comment by bernd5** [comment]
Thank you very much
