### ISSUE TITLE
[ldns] Build broken

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#6714]
```
32 -lldns -o examples/ldns-version
C:/building/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: examples/.libs/ldns-rrsig.o:ldns-rrsig.c:(.text.startup+0x2b7): undefined reference to `asctime_r'
C:/building/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: examples/.libs/ldns-rrsig.o:ldns-rrsig.c:(.text.startup+0x34f): undefined reference to `asctime_r'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:183: examples/ldns-rrsig] Error 1
```

**Comment by 1480c1** [comment]
perhaps
```c
#ifdef _WIN32
#define asctime_r(tm, char) asctime(tm)
#endif 
```

but, based on looking at the [source code](https://github.com/NLnetLabs/ldns/blob/82192e3f017c427cc5db460d32b38e30370fd27d/examples/ldns-rrsig.c#L189), it seems it may need a patch to do something like
```c
				    && (incep_buf = asctime_r(&incep, incep_buf))) {
```
instead to make it work, but even that is not perfect since in the case it's using the _r version and the return is `NULL`, it will overwrite the pointer

**Comment by Biswa96** [comment]
This looks like our previous discussion at https://github.com/msys2/MSYS2-packages/issues/2048. `asctime_r` is provided in `mingw-w64-headers/crt/time/h` file. Defining `_POSIX_C_SOURCE` in `examples/ldns-rrsig.c` file may help. I am not sure about standards.

**Comment by mati865** [comment]
Using `gnu++` instead of `c++` should also help.

**Comment by lazka** [comment]
> This looks like our previous discussion at [msys2/MSYS2-packages#2048](https://github.com/msys2/MSYS2-packages/issues/2048). `asctime_r` is provided in `mingw-w64-headers/crt/time/h` file. Defining `_POSIX_C_SOURCE` in `examples/ldns-rrsig.c` file may help. I am not sure about standards.

thanks
