### ISSUE TITLE
[mlpack] Build is broken

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#6715]
```
 In file included from D:/a/_temp/msys/msys64/mingw64/include/armadillo:54,
                 from D:/a/MINGW-packages/MINGW-packages/mingw-w64-mlpack/src/mlpack-mlpack-3.1.1/src/mlpack/core/arma_extend/arma_extend.hpp:49,
                 from D:\a\MINGW-packages\MINGW-packages\mingw-w64-mlpack\src\mlpack-mlpack-3.1.1\src\mlpack\prereqs.hpp:108,
                 from D:\a\MINGW-packages\MINGW-packages\mingw-w64-mlpack\src\build-x86_64\src\mlpack\cotire\mlpack_CXX_prefix.cxx:4,
                 from D:/a/MINGW-packages/MINGW-packages/mingw-w64-mlpack/src/build-x86_64/src/mlpack/cotire/mlpack_CXX_prefix.hxx:4:
D:/a/_temp/msys/msys64/mingw64/include/armadillo_bits/compiler_setup.hpp:79:30: fatal error: D:/a/_temp/msys/msys64/mingw64/include/hdf5.h: No such file or directory
   79 | #define ARMA_INCFILE_WRAP(x) <x>
      |                              ^
compilation terminated.
CMake Error at D:/a/MINGW-packages/MINGW-packages/mingw-w64-mlpack/src/mlpack-mlpack-3.1.1/CMake/cotire.cmake:1885 (message):
  cotire: error 1 precompiling
  D:/a/MINGW-packages/MINGW-packages/mingw-w64-mlpack/src/build-x86_64/src/mlpack/cotire/mlpack_CXX_prefix.hxx.
Call Stack (most recent call first):
  D:/a/MINGW-packages/MINGW-packages/mingw-w64-mlpack/src/mlpack-mlpack-3.1.1/CMake/cotire.cmake:3558 (cotire_precompile_prefix_header)
```

Maybe just a missing dep?

**Comment by 1480c1** [comment]
seems the header file is from `mingw64/mingw-w64-x86_64-hdf5`

**Comment by Biswa96** [comment]
mlpack needs version update.

**Comment by Biswa96** [comment]
^ also mlpack needs version update.

**Comment by lazka** [comment]
16cbb66e401531 was the problem. Now if fails with hundreds of linker errors..

**Comment by revelator** [comment]
No problems here besides cmake not liking the MSYS Makefiles generator (problems with clangs omp interfering) so i use Ninja instead (why this works is beyond me though).

**Comment by revelator** [comment]
No wait i see now it also complains about c++11.
Hmm from what i can remember i had to remove any old version of mlpack before recompiling also making sure all libraries are abi compatible (eg. they all have to be built with the same compiler version), if not it will bail when trying to link the test programs.

Tried getting around it by adding -D_GLIBCXX_USE_CXX11_ABI=0 to cmake flags but then it will fail to link to boost so there is really no way around it.

**Comment by revelator** [comment]
ok got it building, add this to cmake -DCMAKE_SHARED_LINKER_FLAGS=" -Wl,--export-all-symbols"
i noticed if i built it as a static library it would succede so i checked the import library for the shared build and noticed that it was allmost empty in comparison. 

Also you will probably have to use a shorter path, use BUILDDIR and set it to something really short.
the trick above could probably be added to the cmake script with a patch.

Damn this package is picky ...

**Comment by revelator** [comment]
Tbh i think it might be a problem with current binutils since ld now defaults to linking with -Wl,--as-needed, unfortunatly flagging it with a -Wl,--no-as-needed is not enough it seems. Atleast it consistenly builds with the above cmake flag, but the import library will contain symbols from armadillo boost and hdf5 which might cause problems further down the line.
I updated the package to version 3.2.2 which now adds go and julia bindings if they are installed and so far no problems have been detected, but as far as i can see no other packages use mlpack atm.

**Comment by revelator** [comment]
sigh mlpack uses the cmake property WINDOWS_EXPORT_ALL_SYMBOLS but that one does not work for mingw-w64.
i patched cmakelist.txt in /src/mlpack to use the gcc version of the above and it builds fine now.
You will also need a new package for gonum (if you want go bindings) and one for stbimage, mlpack does download stbimage but due to some internal differences with other gnu compiler chains it puts it in the wrong place. 
Gonum builds fine with our version of go so should be easy peasy creating a package for that one.

If you want i can upload the patch + modified PKGBUILD script.

**Comment by lazka** [comment]
Any PR welcome. Unless you need all those extra features I think it's fine to skip them for now.

**Comment by revelator** [comment]
stbimage is needed by mlpack now so cannot be skipped but i can probably coerce the PKGBUILD to preinstall it (its a headers only package anyway).

i dont currently have a working fork of your repo so it will have to be zipped up and posted here.

**Comment by mati865** [comment]
> sigh mlpack uses the cmake property WINDOWS_EXPORT_ALL_SYMBOLS but that one does not work for mingw-w64.

CMake does support `WINDOWS_EXPORT_ALL_SYMBOLS` for MinGW and even enables it by default. Check this minimal example: https://gist.github.com/mati865/0429ff6cf4cae2a0027829b33ecb1415

**Comment by revelator** [comment]
Well it does not work with mlpack atleast, i cant say if the maintainer has made an error in how it is setup.

**Comment by revelator** [comment]
this is how it is currently used in mlpack set_target_properties(mlpack PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
and then it uses some magick to generate an export header like this ->
include(GenerateExportHeader)
generate_export_header(mlpack EXPORT_FILE_NAME mlpack_export.hpp)

i changed it to ->
`+if(CMAKE_COMPILER_IS_GNUCC AND WIN32)
+  set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--export-all-symbols")
+else()
+  set_target_properties(mlpack PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
+endif()`

which works but it might not be the most sane way to do things.

**Comment by revelator** [comment]
[mingw-w64-mlpack.zip](https://github.com/msys2/MINGW-packages/files/4978989/mingw-w64-mlpack.zip)

here are my changes, i disabled go and julia bindings and the PKGBUILD script has been modified to predownload the latest stbimage and use it from srcdir.

**Comment by revelator** [comment]
https://cmake.org/cmake/help/v3.17/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html 
This property is implemented only for MS-compatible tools on Windows. Eh?!?

**Comment by mati865** [comment]
Apparently `WINDOWS_EXPORT_ALL_SYMBOLS` is ignored with MinGW. Now I'm confused why my CMake project example has properly exported symbols.

Opened #6726

**Comment by revelator** [comment]
might be because of this line ? gcc -shared -o manual.dll -Wl,--out-implib,libmanual.dll.a.
mlpack tries to use cmake's ability to create an import definition file but failing as far as i can see.

**Comment by mati865** [comment]
Mlpack doesn't use dllimport/dllexport in the code so it has to depend on the linker to export everything. If it used dllimport/dllexport there would be no problem.

**Comment by revelator** [comment]
actually it does, cmake creates an import header with definitions for dll import/export. 

At first i also thought this to be the case of it failing so i had to observe it closely while building to see what was going on.

`
#ifndef MLPACK_EXPORT_H
#define MLPACK_EXPORT_H

#ifdef MLPACK_STATIC_DEFINE
#  define MLPACK_EXPORT
#  define MLPACK_NO_EXPORT
#else
#  ifndef MLPACK_EXPORT
#    ifdef mlpack_EXPORTS
        /* We are building this library */
#      define MLPACK_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MLPACK_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MLPACK_NO_EXPORT
#    define MLPACK_NO_EXPORT 
#  endif
#endif

#ifndef MLPACK_DEPRECATED
#  define MLPACK_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef MLPACK_DEPRECATED_EXPORT
#  define MLPACK_DEPRECATED_EXPORT MLPACK_EXPORT MLPACK_DEPRECATED
#endif

#ifndef MLPACK_DEPRECATED_NO_EXPORT
#  define MLPACK_DEPRECATED_NO_EXPORT MLPACK_NO_EXPORT MLPACK_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef MLPACK_NO_DEPRECATED
#    define MLPACK_NO_DEPRECATED
#  endif
#endif

#endif /* MLPACK_EXPORT_H */
`
this is the cmake created mlpack_export.hpp but it is only used in 3 files namely random.cpp random.hpp and log.hpp which dont have a lot of exports, in fact it is more or less the only exports i was seing in the import library before i modified the cmake script.

**Comment by revelator** [comment]
P.s __declspec(dllimport) is also known to cause problems with mingw gcc compilers so when not exporting the definition is usually left empty.

This would have been more correct ->

`#  ifndef MLPACK_EXPORT
#    ifdef mlpack_EXPORTS
        /* We are building this library */
#      define MLPACK_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MLPACK_EXPORT /* leave empty */
#    endif
#  endif`

**Comment by mati865** [comment]
> P.s __declspec(dllimport) is also known to cause problems with mingw gcc compilers so when not exporting the definition is usually left empty.

It's the other way around, when you try to import constant without dllimport you will get address of the relocation instead of constant so the value will look like trash. For functions linkers will work without dllimport though.

**Comment by revelator** [comment]
Aye edited my reply but you managed to read it before i see heh.

Interrested to see if your cmake patch makes a difference with projects such as this.

**Comment by mati865** [comment]
CMake upstream is a bit unresponsive: https://gitlab.kitware.com/cmake/cmake/-/issues/21026
We should use `-Wl,--export-all-symbols` for now.

**Comment by revelator** [comment]
Aye allthough still looking forward to this being fixed as other packages using this functionality has also started popping up.
