### ISSUE TITLE
[cargo-c] 32bit cargo-cinstall.exe requires admin rights

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#6718]
For some reason the i686 cargo-cinstall.exe triggers a UAC dialog and can't be executed from bash. Does anyone know why this could be? The 64bit version works fine.

https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-cargo-c/PKGBUILD

**Comment by lazka** [comment]
We need to use the new capi command provided by cargo-c to work around that (apparently Windows doesn't like that the exe contains the word "install")

**Comment by Alexpux** [comment]
@lazka or provide manifest file for 32 bit

**Comment by lazka** [comment]
thanks, good to know. I found this https://github.com/rust-lang/rfcs/issues/721 so likely not possible yet

the capi thing works though, so it's fine :)

**Comment by Biswa96** [comment]
Maybe some kind of black magic can be done. For example, create a rc file, add the manifest to it, compile the rc file with windmc and link it with exe.

**Comment by Alexpux** [comment]
@lazka no need to embedding manifest, you can place it near files. Look at /mingw32/bin folder for manifest files

**Comment by mati865** [comment]
There is https://github.com/nabijaczleweli/rust-embed-resource
You can also embed manifest using windres+ar tools.

**Comment by lazka** [comment]
The same is happening for 64bit exes since some recent Windows updates: https://learn.microsoft.com/en-us/answers/questions/5893967/uac-popup-appears-for-some-self-developed-applicat

**Comment by dscho** [comment]
Hmm. I just installed  mingw-w64-ucrt-x86_64-cargo-c-0.10.23-1 in one of my setups (which _just_ did a forced reboot after the most recent Patch Tuesday Winduws Update), and do _not_ get an UAC when running:

```console
$ cargo-cinstall.exe
Helper program to build and install c-like libraries

Usage: cargo-c [COMMAND]

Commands:
  cinstall  Install the crate C-API
  help      Print this message or the help of the given subcommand(s)

Options:
  -h, --help     Print help
  -V, --version  Print version
```

**Comment by nirbheek** [comment]
> The same is happening for 64bit exes since some recent Windows updates: https://learn.microsoft.com/en-us/answers/questions/5893967/uac-popup-appears-for-some-self-developed-applicat

Same for me!

**Comment by dscho** [comment]
@nirbheek Unfortunately, this does not reproduce for me. But I noticed that the manifest in that `cargo-cinstall.exe` file has this section:

```xml
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker"/>
      </requestedPrivileges>
    </security>
```

However, typically MSYS2-built executables have this:

```xml
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel
          level="asInvoker"
          uiAccess="false"/>
      </requestedPrivileges>
    </security>
```

i.e. they include `uiAccess="false"`. Could you edit the manifest (via any resource editor) to add that attribute, and see whether that "fixes" things?
