### ISSUE TITLE
[BUG] "import imobiledevice" fails after update

### ISSUE THREAD

**Issue by mobilEKG** [msys2/MINGW-packages#6724]
## Describe the bug

After update msys2 by using
```
pacman -Sydd pacman
pacman -Syuu 
```

Python code `import imobiledevice` fails: 
_**ImportError: DLL load failed while importing imobiledevice: The specified module could not be found.**_

## Additional Context: Operating System, Screenshots

Related package:
https://packages.msys2.org/package/mingw-w64-x86_64-libimobiledevice

**Comment by Biswa96** [comment]
The issue is related to import library of `libimobiledevice.dll`. It is linked with `libplist.dll` but the actual file name is `libplist-2.0.dll`. See this following output:

```
$ ntldd /mingw64/bin/libimobiledevice.dll
        KERNEL32.dll => C:\Windows\SYSTEM32\KERNEL32.dll (0x0000000000cc0000)
        msvcrt.dll => C:\Windows\SYSTEM32\msvcrt.dll (0x00000000013e0000)
        ole32.dll => C:\Windows\SYSTEM32\ole32.dll (0x0000000000cc0000)
        SHELL32.dll => C:\Windows\SYSTEM32\SHELL32.dll (0x00000000013d0000)
        WS2_32.dll => C:\Windows\SYSTEM32\WS2_32.dll (0x0000000000ea0000)
        libcrypto-1_1-x64.dll => F:\msys64\mingw64\bin\libcrypto-1_1-x64.dll (0x0000000000cc0000)
        libplist.dll => not found
        libssl-1_1-x64.dll => F:\msys64\mingw64\bin\libssl-1_1-x64.dll (0x0000000000cc0000)
        libusbmuxd.dll => F:\msys64\mingw64\bin\libusbmuxd.dll (0x0000000000b40000)
```

I can not rebuild the package because the autoconf can't find the dependencies (libusbmuxd and libplist). I am not sure how it was built as first place.

**Comment by MehdiChinoune** [comment]
likely fixed.
