### ISSUE TITLE
Wrong gcc --print-search-dirs?

### ISSUE THREAD

**Issue by tprk77** [msys2/MINGW-packages#6734]
When I do `gcc --print-search-dirs`, I get a result like this:

```
$ gcc --print-search-dirs
install: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/
programs: =C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/;C:/msys64/mingw64/bin/../lib/gcc/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/x86_64-w64-mingw32/10.2.0/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/
libraries: =C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/;C:/msys64/mingw64/bin/../lib/gcc/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/lib/x86_64-w64-mingw32/10.2.0/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/lib/../lib/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../x86_64-w64-mingw32/10.2.0/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib/;D:/msys64/mingw64/x86_64-w64-mingw32/lib/x86_64-w64-mingw32/10.2.0/;D:/msys64/mingw64/x86_64-w64-mingw32/lib/../lib/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/lib/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../;D:/msys64/mingw64/x86_64-w64-mingw32/lib/
```

This seems wrong because it's printing Windows style paths. And also because it's printing paths that don't exist. (I do have a `D:` drive on my machine, but it's a Blu-Ray drive.)

I'm reporting this because it's causing an issue with a Meson build. Reading the Meson source code, Meson seems to be invoking this command and parsing the output, but then failing to handle the Windows paths. If this is not a packaging bug and intentional, please let me know and I will do a bug report with Meson.

**Comment by 1480c1** [comment]
I do know in the case you are using a mingw-w64 gcc compiler (aka not msys2's msys2 environment-specific /usr/bin/gcc), it should use windows mixed paths (Using C:/ and using `/` as pathseps), and also the other ghost paths are there from when building

**Comment by lazka** [comment]
> I'm reporting this because it's causing an issue with a Meson build. Reading the Meson source code, Meson seems to be invoking this command and parsing the output, but then failing to handle the Windows paths

This was fixed more than a year ago: https://github.com/mesonbuild/meson/pull/5396

The `D:` is weird (I have it too), but meson filters out non-existing paths.

**Comment by tprk77** [comment]
@1480c1 I am using `mingw64/mingw-w64-x86_64-gcc`, maybe out of ignorance... I thought that's what I should use to make a native 64 bit Windows executable. I can say that this exact same build used to work about 3 months ago, but with a fresh MSYS2 install, I'm getting this issue.

@lazka That's weird, maybe it's a regression? I'm using Meson 0.55.0. Do you think I should report there?

**Comment by tprk77** [comment]
As an update, I also tried Clang and ran into the same issue. So I started investigating the Meson code, adding some quick and dirty hacks to print things for sanity checks, and I ran into this:

```
libname: zip
env: <mesonbuild.environment.Environment object at 0x000000000394c8e0>
extra_dirs: ['C:/msys64/mingw64/lib']
code: int main(void) { return 0; }

pobj: c:/msys64/mingw64/lib/clang/10.0.0
unresolved: c:/msys64/mingw64/lib/clang/10.0.0
pobj: c:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0
unresolved: c:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0
pobj: c:/msys64/mingw64/x86_64-w64-mingw32/lib
unresolved: c:/msys64/mingw64/x86_64-w64-mingw32/lib
pobj: c:/msys64/mingw64/lib
unresolved: c:/msys64/mingw64/lib
pobj: c:/msys64/mingw64/x86_64-w64-mingw32/sys-root/mingw/lib
unresolved: c:/msys64/mingw64/x86_64-w64-mingw32/sys-root/mingw/lib
[WindowsPath('C:/msys64/mingw64/lib/libzip.a')]
p1: C:/msys64/mingw64/lib/libzip.a
libname: D:/msys64/mingw64/lib/libz.dll.a
env: <mesonbuild.environment.Environment object at 0x000000000394c8e0>
extra_dirs: ['C:/msys64/mingw64/lib']
code: int main(void) { return 0; }

[WindowsPath('C:/msys64/mingw64/lib/libD:/msys64/mingw64/lib/libz.dll.a.a')]
p1: C:/msys64/mingw64/lib/libD:/msys64/mingw64/lib/libz.dll.a.a
```

As you can see, `'C:/msys64/mingw64/lib/libD:/msys64/mingw64/lib/libz.dll.a.a'` doesn't seem right. I was thinking this was a Meson bug until I saw this:

```
$ pkg-config --libs --static libzip
-LC:/msys64/mingw64/lib -lzip -lD:/msys64/mingw64/lib/libz.dll.a -lD:/msys64/mingw64/lib/libbz2.dll.a -lD:/msys64/mingw64/lib/liblzma.dll.a -lbcrypt -ladvapi32
```

To me, that looks like problem with the package config file of `libzip`. As I mentioned before, I don't even have `D:` drive, so that should definitely be a `C:` at least. It also seem weird to have a `-l` in front of a static library, but maybe that's a Windows thing?
