### ISSUE TITLE
Weird static libraries in libzip pkgconfig

### ISSUE THREAD

**Issue by tprk77** [msys2/MINGW-packages#6736]
On my machine, the file contents are:

```
prefix=/mingw64
exec_prefix=${prefix}
bindir=${exec_prefix}/bin
libdir=${exec_prefix}/lib
includedir=${prefix}/include

zipcmp=${exec_prefix}/bin/zipcmp

Name: libzip
Description: library for handling zip archives
Version: 1.6.1
Libs:  -L${libdir} -lzip
Libs.private:  -lD:/msys64/mingw64/lib/libz.dll.a -lD:/msys64/mingw64/lib/libbz2.dll.a -lD:/msys64/mingw64/lib/liblzma.dll.a -lbcrypt -ladvapi32
Cflags: -I${includedir}
```

Note `-lD:/msys64/mingw64/lib/libz.dll.a`. I don't have a `D:` drive, so that path doesn't actually exist. Also, there's a `-l` in front of a static library. Anyway, it was breaking my build.

I was able to get my build working again by manually editing the pkgconfig file to have the following:

```
prefix=/mingw64
exec_prefix=${prefix}
bindir=${exec_prefix}/bin
libdir=${exec_prefix}/lib
includedir=${prefix}/include

zipcmp=${exec_prefix}/bin/zipcmp

Name: libzip
Description: library for handling zip archives
Version: 1.6.1
Libs:  -L${libdir} -lzip
Libs.private:  C:/msys64/mingw64/lib/libz.dll.a C:/msys64/mingw64/lib/libbz2.dll.a C:/msys64/mingw64/lib/liblzma.dll.a -lbcrypt -ladvapi32
Cflags: -I${includedir}
```

See also #6734.

**Comment by lazka** [comment]
My guess would be because the static build gets installed over the shared one here (the order needs to be reversed): https://github.com/msys2/MINGW-packages/blob/52c6513cf726d9b39c29008fe2d54c32b374e01a/mingw-w64-libzip/PKGBUILD#L62

Sadly libzip doesn't build here:

```
[100%] Built target fopen_unchanged
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/ziptool.dir/objects.a(ziptool.c.obj):ziptool.c:(.text.startup+0x41b): undefined reference to `__imp__snprintf.constprop.0'
[100%] Built target in-memory
collect2.exe: error: ld returned 1 exit status
```

**Comment by mati865** [comment]
Pkgconfig file should be similar to one in Arch Linux so it works with both static and shared:
```
Libs.private:  -lz -lbz2 -llzma -lgnutls -lnettle
```

> Sadly libzip doesn't build here atm (undefined reference to '__imp__snprintf.constprop.0'):

It's GCC 10 regression (no idea if reported upstream). Libzip builds fine with Clang.

**Comment by lazka** [comment]
Looks like the new build has a proper .pc file. If not feel free to respond or open a new issue.

**Comment by brechtsanders** [comment]
About the `undefined reference to __imp__snprintf.constprop.0` error: removing the line `#define snprintf _snprintf` from `lib/compat.h` seems to fix that.

**Comment by stopgaming** [comment]
de-facto `-DZIP_STATIC` is required additionally in cflags after executing the `pkg-config --static --cflags libzip` command. I don't know why this definition is missing in `.pc`.

**Comment by Biswa96** [comment]
> de-facto `-DZIP_STATIC` is required additionally in cflags after executing the `pkg-config --static --cflags libzip` command. I don't know why this definition is missing in `.pc`.

Thanks for the reminder. I have created a pull request to fix it in upstream https://github.com/nih-at/libzip/pull/434
