### ISSUE TITLE
Finding ld from Python distutils

### ISSUE THREAD

**Issue by radarhere** [msys2/MINGW-packages#6744]
Hi. For mingw-w64-python, there is a [patch file for Python distutils](https://github.com/msys2/MINGW-packages/blob/b1cf7cc13d656e9d06212911b0c195015c6140fa/mingw-w64-python/0630-mingw-_winapi_as_builtin_for_Popen_in_cygwinccompiler.patch#L25-L36) so that it doesn't look for 'ld', it asks gcc where ld is.

However, I find that, at least in the AppVeyor MinGW, this [fails](https://ci.appveyor.com/project/Python-pillow/pillow/builds/26416349/job/74tvtjhe0snk25a0). Python Pillow added a [fallback](https://github.com/python-pillow/Pillow/pull/4019/files) to just use 'ld' if the gcc search fails. For a more recent example, see [this passing build](https://ci.appveyor.com/project/radarhere/pillow/builds/34426479), and [this failing build](https://ci.appveyor.com/project/radarhere/pillow/builds/34426497) if the [workaround is removed](https://github.com/radarhere/Pillow/commit/cea79d0a5458326605c1335538061df1850808de)

I'm wondering if this could be integrated into the patch itself - so that if gcc doesn't correctly find ld, then 'ld' is just used?

**Comment by radarhere** [comment]
I've created #6757 as a suggestion for this.

**Comment by lazka** [comment]
Try setting `$env:MSYSTEM=MINGW32` before starting bash, otherwise your PATH will be wrong

**Comment by radarhere** [comment]
Thanks - [one of the Python Pillow contributors came to the same conclusion.](https://github.com/python-pillow/Pillow/issues/4796#issuecomment-683370940), and so was able to fix it.

**Comment by lazka** [comment]
Cool, thanks for the update
