### ISSUE TITLE
Renaming gprbuild-gpl package

### ISSUE THREAD

**Issue by Fabien-Chouteau** [msys2/MINGW-packages#6754]
Hi @juergenpf and @reznikmm,

I think we should rename package (`gprbuild-gpr`)[https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-gprbuild-gpl] in to `gprbuild`.
The `-gpl` suffix comes from the time when this was built from the sources of the "GNAT GPL" release.
But this release doesn't exists anymore and the package is now build from the GitHub sources.

The `PKGBUILD` documentation mentions a field to make sure there is not disruption on the user side:
```shell
replaces=("${MINGW_PACKAGE_PREFIX}-gprbuild-gpl")
```

What do you think?

**Comment by reznikmm** [comment]
I vote for removing `-gpl` from the package name.

**Comment by juergenpf** [comment]
I’m fine with that. Haven’t tracked the GNAT stuff for a while now…

Jürgen

Von: Fabien Chouteau <notifications@github.com>
Gesendet: Montag, 3. August 2020 16:45
An: msys2/MINGW-packages <MINGW-packages@noreply.github.com>
Cc: Jürgen Pfeifer <juergen@familiepfeifer.de>; Mention <mention@noreply.github.com>
Betreff: [msys2/MINGW-packages] Renaming gprbuild-gpl package (#6754)


Hi @juergenpf<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjuergenpf&data=02%7C01%7C%7Ced55b2ac03bf4a87e8a608d837bbc8f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637320626949006557&sdata=pqeqjWlKYzRGe3XVZ7s3cqGLuYx8kBnLdJFlFg%2B0c%2BM%3D&reserved=0> and @reznikmm<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Freznikmm&data=02%7C01%7C%7Ced55b2ac03bf4a87e8a608d837bbc8f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637320626949016527&sdata=HQvPkuqN3l3gdgJG1ej8n2%2B1dZEYu7JRiHiY4b4X46I%3D&reserved=0>,

I think we should rename package (gprbuild-gpr)[https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-gprbuild-gpl] in to gprbuild.
The -gpl suffix comes from the time when this was built from the sources of the "GNAT GPL" release.
But this release doesn't exists anymore and the package is now build from the GitHub sources.

The PKGBUILD documentation mentions a field to make sure there is not disruption on the user side:

replaces=("${MINGW_PACKAGE_PREFIX}-gprbuild-gpl")

What do you think?

**Comment by lazka** [comment]
#6760 was merged, so closing. (packages will be available on the next upload)
