### ISSUE TITLE
arrow: how to process packages in incoming queue?

### ISSUE THREAD

**Issue by kou** [msys2/MINGW-packages#6755]
It seems that packages queued at between 2020-07-25 07:32:24 and 2020-07-27 10:31:21 in incoming queue https://packages.msys2.org/queue aren't processed.
The Repo Updates page https://packages.msys2.org/updates lists packages before 2020-07-24 20:15:22 and after 2020-07-27 21:26:38.

I want mingw-w64-arrow 1.0.0-1 https://packages.msys2.org/base/mingw-w64-arrow that is still in incoming queue.

What should we do to process these packages in incoming queue? Should we bump `pkgrel` to re-queue to incoming queue like the following?

```diff
diff --git a/mingw-w64-arrow/PKGBUILD b/mingw-w64-arrow/PKGBUILD
index cbaa24dff..1f31fcd7e 100644
--- a/mingw-w64-arrow/PKGBUILD
+++ b/mingw-w64-arrow/PKGBUILD
@@ -4,7 +4,7 @@ _realname=arrow
 pkgbase=mingw-w64-${_realname}
 pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
 pkgver=1.0.0
-pkgrel=1
+pkgrel=2
 pkgdesc="Apache Arrow is a cross-language development platform for in-memory data (mingw-w64)"
 arch=("any")
 url="https://arrow.apache.org/"

```

**Comment by lazka** [comment]
The automated building is currently WIP.

> What should we do to process these packages in incoming queue? Should we bump `pkgrel` to re-queue to incoming queue like the following?

No need. I'll have a look.

**Comment by kou** [comment]
I see. Thanks!

**Comment by lazka** [comment]
See https://github.com/msys2/msys2-devtools#build-process for details

**Comment by lazka** [comment]
The arrow build just went through, so should be in the next upload.

**Comment by kou** [comment]
Thanks!
BTW, the build system is very interesting.
