### ISSUE TITLE
sem_open() returns SEM_FAILED with errno 40:  Function not implemented

### ISSUE THREAD

**Issue by xiaowen64** [msys2/MINGW-packages#6782]
is POSIX semaphore implemented under msys2?

**Comment by 1480c1** [comment]
https://github.com/Alexpux/mingw-w64/blob/master/mingw-w64-libraries/winpthreads/include/semaphore.h#L68

seems it's not implemented

https://stackoverflow.com/questions/58792384/what-tool-with-gcc-under-windows-can-make-a-console-program-with-working-named-s

**Comment by lazka** [comment]
here is the implementation: https://github.com/mirror/mingw-w64/blob/0f6395bdd282789b0ffbc84aa9e8fab9e3b5b4fc/mingw-w64-libraries/winpthreads/src/sem.c#L313

**Comment by xiaowen64** [comment]
seems the "named" semaphore is not implemented. in addition, the boost named_semaphore doesn't seem to work either.

**Comment by lazka** [comment]
Things you can do:

* report this to mingw-w64 and ask for it to be implemented.
* Use the Windows semaphore API
