### ISSUE TITLE
[jq] Missing libonig-5.dll dependency

### ISSUE THREAD

**Issue by AndreSteenveld** [msys2/MINGW-packages#6784]
Using MINGW64 I've installed `jq` using pacman with the following command: `pacman -S mingw-w64-x86_64-jq`

Looking at `/mingw64/bin` it does seem to be installed with all its dependencies: 
![image](https://user-images.githubusercontent.com/6936/90003125-e942e500-dc93-11ea-91a1-ec645f1b5ecf.png)

But running it throws the following error: 
![image](https://user-images.githubusercontent.com/6936/90003253-1c857400-dc94-11ea-8037-f356d358dc26.png)

I made sure that I'm invoking the correct binary and using `ldd` it does seem to point to the correct dll: 
![image](https://user-images.githubusercontent.com/6936/90003412-5a829800-dc94-11ea-93d0-cc30f83c558b.png)

The suggestions in #1503 don't seem to help, just starting `jq.exe` in a cmd prompt does seem to work though:
![image](https://user-images.githubusercontent.com/6936/90004027-40958500-dc95-11ea-8e0a-73019b34f28a.png)

Using `ldd` to check if the dependencies could be found was suggested here #4588, and for completnes this this is my path:
![image](https://user-images.githubusercontent.com/6936/90004652-463f9a80-dc96-11ea-879a-7572c4c8097d.png)

**Comment by AndreSteenveld** [comment]
My workaround for this has been downloading a stand alone version of `jq` and placing it in my path.

```bash 
$  curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe > /usr/local/bin/jq
```

![image](https://user-images.githubusercontent.com/6936/90006119-9c154200-dc98-11ea-92cb-76027e003a1f.png)

**Comment by mati865** [comment]
It has missing dependency on `mingw-w64-x86_64-libwinpthread`, works for me with that installed.

`jq.exe --version` in cmd probably pulled winpthreads library from the PATH.

**Comment by AndreSteenveld** [comment]
You're right, I would have never guessed that from error. Installing `mingw-w64-x86_64-libwinpthread-git` does solve the issue, I initially disregarded that fix as double-clicking it in explorer flashed my a cmd prompt and not an error as described in #1503, there for I assumed it worked.

![image](https://user-images.githubusercontent.com/6936/90009970-5740d980-dc9f-11ea-8f07-8832dec1bb0b.png)

If not for the error dialog how would one figure this out? The `ldd` output of `ldd /mingw64/bin/libjq-1.dll` doesn't provide anything usefull (I'm assuming one of the "???" is libwinpthread).

![image](https://user-images.githubusercontent.com/6936/90010506-3b8a0300-dca0-11ea-96db-2b794293a489.png)

**Comment by AndreSteenveld** [comment]
Hmmm, doing some more experimentation. In #4588 someone mentioned `ldd` wasn't working properly just giving it a go seemed to yield "results". Installing `ntldd` using `pacman -S mingw-w64-x86_64-ntldd-git` and running that against `jq.exe` shows `libwinpthread-1.dll` as a dependency while doing the same with `ldd` doesn't. It seems that `ldd` doesn't show missing dependencies. /TIL

![image](https://user-images.githubusercontent.com/6936/90011519-054d8300-dca2-11ea-892f-d80f8efb831d.png)

**Comment by mati865** [comment]
Yes, this is known limitation. `ldd` doesn't show missing libraries on Windows.
