### ISSUE TITLE
About omitted packages on GitHub

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#6789]
[This](https://github.com/msys2/MINGW-packages) page says:

  **Sorry, we had to truncate this directory to 1,000 files. 492 entries were omitted from the list.**

Why you do not group them in 2 or 3 folders?

```
pkg_folder1  # with about 500 pkgs
pkg_folder2  # with about 500 pkgs
pkg_folder3  # with about 500 pkgs
```

or whatever you want to call them....

**Comment by Biswa96** [comment]
Then what do you call this one https://github.com/archlinux/svntogit-community? ArchLinux has 7x folders than MSYS2.

**Comment by Biswa96** [comment]
Then what do you call this one https://github.com/archlinux/svntogit-community? ArchLinux has 7x folders than MSYS2. It's huge 🤯 When I first came to know about I also thought like your idea. Debian family stores all the deb packages in separate folders alphabetically. But if maintainers create more folder and subfolders then every contributors have to memorize that hierarchy.

Though one trick I use for this repository. Assume I want to open mingw-w64-xmake, which is far beyond. So, I open one of the top most folder like this https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-4th and with some keyboard magic I replace `4th` with `xmake`. Done!

**Comment by lazka** [comment]
* Go to https://github.com/msys2/MINGW-packages
* Type `t`
* Start typing the name you want

**Comment by angelog0** [comment]
Thanks for suggestions. Usually, browse the package list readink the PKGBUILD...

**Comment by lazka** [comment]
Another alternative is to search in our package browser and then click "Source Files" in the top left: https://packages.msys2.org/package/mingw-w64-i686-emacs?repo=mingw32
