### ISSUE TITLE
libzip static installation tramples config files for shared installation

### ISSUE THREAD

**Issue by endrift** [msys2/MINGW-packages#6805]
The libzip static and shared installations have conflicting installed files. Examples include /include/zipconf.h and /lib/cmake/libzip/libzip-targets.cmake, which only reflect the static build. Both should not be installed at the same time, it seems. Caused by #3572 most likely.

**Comment by NagyGa1** [comment]
libzip static also exports shared dependencies.

**Comment by Biswa96** [comment]
Could you please explain the issue and provide steps to reproduce it?

**Comment by endrift** [comment]
This issue is 3 years old. I don't know if it's still relevant. No one bothered replying to it until now.

I'm not sure if this is a file conflict or if the header/pkgconfig/etc files dropped reflect a configuration that only works with one type, regardless of which one gets installed. It has been 3 years after all.

It would be easy enough for anyone reading this bug to check by installing the packages and looking at the files I mentioned initially. I won't have time until tomorrow.
