### ISSUE TITLE
 -ffunction-sections -fdata-sections

### ISSUE THREAD

**Issue by stackTom** [msys2/MINGW-packages#6808]
In order to statically link only those functions our executable uses, we use  `-ffunction-sections` and `-fdata-sections` in the compiler as well as `--gc-sections` in the linker on Unix systems. If I need the same functionality on a library I compiled for windows using mingw64 gcc, do I need to compile with `-ffunction-sections` and `-fdata-sections`? The equivalent for visual studio is to compile with `/Gy` and link with `/OPT:REF`. Without these flags, my final executable is a couple kilobytes larger so the flags are doing something even though my library wasn't compiled with `-ffunction-sections` and `-fdata-sections`. However, I wonder if the difference in size is due to stripping libucrt.lib (which I link against) and not the library I compiled with mingw64 gcc.  So, is `-ffunction-sections` and `-fdata-sections` needed if we use `/Gy` and `/OPT:REF` with MSVC compiler and linker, or is `/Gy` and `/OPT:REF` all that is needed?

**Comment by stackTom** [comment]
It appears using `-ffunction-sections` and `-fdata-sections` causes the microsoft linker to view the generated library files as corrupt, so it is not supported in visual studio.

**Comment by mati865** [comment]
Mingw and msvc have different ABIs so you cannot expect full compatibility. That flag should work fine within MinGW.
