### ISSUE TITLE
CppUTest package

### ISSUE THREAD

**Issue by giuspen** [msys2/MINGW-packages#6822]
Don't know if it is the right place to ask, anyway it would be very useful to add the package for CppUTest http://cpputest.github.io/ as a very good unit tests framework

**Comment by Biswa96** [comment]
Would you like to test the package from the GitHub Actions artifacts in the linked pull request?

**Comment by giuspen** [comment]
Sure but is it already in the msys2 repo?

**Comment by giuspen** [comment]
I tried to install it but couldn't find it in the repo, was it added already?

**Comment by 1480c1** [comment]
https://packages.msys2.org/new seems not

**Comment by giuspen** [comment]
Thanks I'll monitor that link before try again
