### ISSUE TITLE
mingw-w64-arm-none-eabi-gcc availability

### ISSUE THREAD

**Issue by Trance-Paradox** [msys2/MINGW-packages#6844]
I was getting started in arm cross platform development. Is there a problem with this package i can't get it to install from MSYS2 cmd.

**Comment by Biswa96** [comment]
For what target do you want to compile for? 1. ARM PE for Windows 10 ARM or 2. ARM ELF for GNU/Linux ARM systems.

**Comment by Trance-Paradox** [comment]
> For what target do you want to compile for? 1. ARM PE for Windows 10 ARM or 2. ARM ELF for GNU/Linux ARM systems.

For windows 10

**Comment by Biswa96** [comment]
To compile Windows 10 ARM PE, use [llvm-mingw][1] toolchain which uses clang and mingw-w64.

[1]: https://github.com/mstorsjo/llvm-mingw

**Comment by DavidEGrayson** [comment]
The "none" in `arm-none-eabi-gcc` means "no operating system", so it wouldn't be appropriate.

**Comment by mati865** [comment]
If you want ARM/Aarch64 Windows GCC toolchain you will have to report it to GCC/Binutils upstreams since they are missing required code.
Clang can support it but it would probably need separate subsystems, otherwise you could build only software without any dependencies.

**Comment by Trance-Paradox** [comment]
OK i get it.
But it is quite easy if we could maintain all packages all in one place. It will be very useful when available.
