### ISSUE TITLE
mingw-w64-glade

### ISSUE THREAD

**Issue by davidwed** [msys2/MINGW-packages#6870]
in the Glade package the libhandy catalog is missing. Even if I install the package "mingw-w64-x86_64-libhandy", the "Hdy*" widgets are not displayed. Under Ubuntu all widgets are displayed when the libhandy package is installed.

**Ubuntu:**
![Glade_ubuntu](https://user-images.githubusercontent.com/12169308/91273459-941bce80-e77d-11ea-87c4-d1adb13aa172.PNG)

**Msys2:**
![Glade_msys2](https://user-images.githubusercontent.com/12169308/91273457-93833800-e77d-11ea-949b-236e8e4db865.PNG)

**Comment by Biswa96** [comment]
Can you provide the package name in Ubuntu? Does glade depends on libhandy there?

**Comment by davidwed** [comment]
I had to install the package "libhandy" separately to display the widgets.

So without the packages "libhandy-0.0-0" and "libhandy-0.0-dev" the widgets are missing and with the packages I can select them on the Ubuntu 20.04 system.

**Glade:**
![grafik](https://user-images.githubusercontent.com/12169308/91311270-2f7b6680-e7b3-11ea-9098-eeef67e51f95.png)

**Comment by Biswa96** [comment]
I think the issue is in libhandy package. The libhandy package was built with `-Dglade_catalog=disabled` option. @taozuhong Would it be right possible to enable that option?

**Comment by Biswa96** [comment]
I think the issue is in libhandy package. The libhandy package was built with `-Dglade_catalog=disabled` option. @taozuhong Is it possible to enable that option? The build went fine.

**Comment by davidwed** [comment]
You are right, when I create the libhandy package with the flag "-Dglade_catalog=enabled" the widgets are displayed.

![grafik](https://user-images.githubusercontent.com/12169308/91414757-4b334b00-e84d-11ea-8bc1-b2b392595e2a.png)

**Comment by Biswa96** [comment]
This issue can be closed now. The change is added in the respository.

**Comment by Biswa96** [comment]
This issue can be closed now. The change is added in the repository.

**Comment by taozuhong** [comment]
Hi, I'll update the package while the next version is released. maybe soon.
