### ISSUE TITLE
opencascade packages

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#6889]
Open CASCADE Technology, 3D modeling & numerical simulation

https://github.com/archlinux/svntogit-community/tree/packages/opencascade/trunk

**Comment by lazka** [comment]
Note that just requesting a package is unlikely to change anything in most cases.

**Comment by 3rav** [comment]
Earlier I tried to add PKGBUILD files myself but it didn't work out:
https://github.com/msys2/MINGW-packages/pull/3814
 or EXODUS:
[PKGBUILD.zip](https://github.com/msys2/MINGW-packages/files/5141268/PKGBUILD.zip)

Regarding Opencascade for build 7.4.0 you just need:
cmake -G "MSYS Makefiles" -DBUILD_LIBRARY_TYPE=STATIC

Required libraries:
freetype
tcl
tk

**Comment by 3rav** [comment]
https://github.com/msys2/MINGW-packages/pull/7148
