### ISSUE TITLE
Typelib file for namespace 'HarfBuzz', version '0.0' not found

### ISSUE THREAD

**Issue by danyeaw** [msys2/MINGW-packages#6898]
## Describe the bug

This may be related to https://github.com/msys2/MINGW-packages/pull/6894. Packaging Gtk apps with pyinstaller now gives an error that the Typelib for HarfBuzz version '0.0' is not found.

## Steps to Reproduce the Problem

1. Update msys2 and install pygobject:
```
$ pacman -Suy
$ pacman -S git mingw-w64-x86_64-gcc mingw-w64-x86_64-gtk3 \
mingw-w64-x86_64-pkg-config mingw-w64-x86_64-cairo \
mingw-w64-x86_64-gobject-introspection mingw-w64-x86_64-python \
mingw-w64-x86_64-python-gobject mingw-w64-x86_64-python-cairo \
mingw-w64-x86_64-python-pip
```
2. `python -m venv .venv`
3. `source .venv/bin/activate`
4. `pip install pygobject pyinstaller==3.6.0`
5. `pyinstaller --exclude-module tk --exclude-module tcl --exclude-module _tkinter helloworld.py`
3. `./dist/helloworld/helloworld.exe`
```
$ ./dist/helloworld/helloworld.exe
Traceback (most recent call last):
  File "gi/importer.py", line 138, in load_module
  File "gi/module.py", line 265, in get_introspection_module
  File "gi/module.py", line 117, in __init__
gi.RepositoryError: Typelib file for namespace 'HarfBuzz', version '0.0' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "helloworld.py", line 3, in <module>
    from gi.repository import Gtk
  File "gi/importer.py", line 140, in load_module
ImportError: Typelib file for namespace 'HarfBuzz', version '0.0' not found
[10892] Failed to execute script helloworld
```

Expected behavior:
Hello world PyGObject example runs fine when packaged with pyinstaller 3.6:
```
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

window = Gtk.Window(title="Hello World")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()
```

## Additional Context: Operating System, Screenshots

- OS: Windows 10 Enterprise version 1909 64bit

**Comment by lazka** [comment]
What does `g-ir-inspect.exe HarfBuzz --print-shlibs --print-typelibs` do?

**Comment by lazka** [comment]
> This may be related to #6894.

This isn't in the repo yet.

**Comment by danyeaw** [comment]
@lazka 
```
$ g-ir-inspect.exe HarfBuzz --print-shlibs --print-typelibs
shlib: libharfbuzz-gobject-0.dll
typelib: GObject-2.0
typelib: GLib-2.0
```

**Comment by lazka** [comment]
thanks. so something in pyinstaller is maybe not picking up the harbuzz files? No idea atm

**Comment by lazka** [comment]
My guess is that this is due to the last pango update, which now exposes harfbuzz in its API. So this is the first time harfbuzz introspection is part of the gtk dependency chain.

**Comment by danyeaw** [comment]
@lazka PyInstaller has a hook that it uses to get the typelibs. It sounds like I need to create a new hook for HarfBuzz. Thanks for pointing me in the right direction.

**Comment by lazka** [comment]
-> https://github.com/pyinstaller/pyinstaller/issues/5129
