### ISSUE TITLE
Adding UCRT to the build matrix

### ISSUE THREAD

**Issue by jeroen** [msys2/MINGW-packages#6901]
Hello! This is an (ambitious) discussion topic.

The [R project](https://cran.r-project.org/bin/windows/base/) uses msys2 to build the official binaries and 16000+ add-on packages. These addon packages depend on about 200 different mingw-w64 libs. We are [very interested](https://developer.r-project.org/Blog/public/2020/05/02/utf-8-support-on-windows/index.html) in providing a UCRT build of R (and all packages), because native UTF-8 support should resolve a lot of problems we are having on non-latin Windows.

UCRT binaries can generally not be linked against binaries compiled against MSVCRT. The [safest approach](https://stackoverflow.com/questions/57528555/how-do-i-build-against-the-ucrt-with-mingw-w64#comment110354007_58857816) is to rebuild the whole toolchain from scratch with `--with-default-msvcrt=ucrt` passed to `mingw-w64-headers` and `mingw-w64-crt`. So it is effectively an entirely different compile target.

I think in theory UCRT should work on both 32-bit and 64-bit, but in practice I don't think is needed to support legacy 32-bit systems, and we can probably limit ourselves to 64-bit ucrt.

What would be needed for msys2 to add support for UCRT binaries? The first part is obvious:

 1. You need a new binary repository in http://repo.msys2.org/mingw/ for example called `x86_64_ucrt` (or just `ucrt` if we only provide 64-bit builds of ucrt).
 2. In this repo we have binaries for `mingw-w64-headers` and `mingw-w64-crt` with  `--with-default-msvcrt=ucrt` and everything else based on that, for example `mingw-w64-x86_64_ucrt-gcc`, etc. 
 3. Once this exists, add this flavor to the GitHub Actions build matrix, alongside regular `mingw32` and `mingw64`.

A more difficult choice is how to organize the installation. I see two different routes:

 - option A: The easiest route: Provide an entirely separate `msys2 ucrt edition` installer, in which everything under `/mingw64` (and possibly `/mingw32`) is taken from the ucrt repos at `http://repo.msys2.org/mingw/x86_64_ucrt`.
 - option B: Alternatively: introduce a new `CARCH`, `MINGW_CHOST`, `MINGW_PREFIX` and `MINGW_INSTALLS` etc for `x86_64_ucrt` and `/mingw64_ucrt` and so on, so that these can be installed alongside mingw32 and mingw64.

**Comment by lazka** [comment]
>     1. You need a new binary repository in http://repo.msys2.org/mingw/ for example called `x86_64_ucrt` (or just `ucrt` if we only provide 64-bit builds of ucrt).

With arm on the horizon that explicit seems better.



> option B: Alternatively: introduce a new `CARCH`, `MINGW_CHOST`, `MINGW_PREFIX` and `MINGW_INSTALLS` etc for `x86_64_ucrt` and `/mingw64_ucrt` and so on, so that these can be installed alongside mingw32 and mingw64.

It think this would be easier.

Two questions:

* When can we switch to ucrt altogether? In other words when do enough users have it installed and we can assume it?
* If we are going to do a rebuild is there anything else we should change while at it?

**Comment by lazka** [comment]
Here is the last time this was discussed: https://gitter.im/msys2/msys2?at=5eaaba04a9de3d01b1dcacdf

**Comment by mati865** [comment]
> With arm on the horizon explicit seems better.

We can't get use GCC for ARM and Clang/LLVM is not yet widely tested with all our packages.

I was already experimenting with creating clang64 subsystem using LLVM everywhere instead of GCC/Binutils and defaulting to UCRT with rather nice success rate for all the deps of LLVM (CMake, Z3, Python, ...). Most of the issues were related to missing LLD options (fixed by dozen backports), the fact LLD will print ELF backend help by default (there are multiple trivial ways to fix it) and buggy build systems.
I wanted to restart it with LLVM 11, probably as my own repo until everything works good but I'm open to making it part of MSYS2.

> When can we switch to ucrt altogether? In other words when do enough users have it installed and we can assume it?

MSVC already defaults to UCRT since version 2015. It's preinstalled on Windows 10 and installable as optional Windows Update package and standalone installer for Windows Vista SP2, Windows 7 SP1, Windows 8 and Windows 8.1.

**Comment by jeroen** [comment]
> MSVC already defaults to UCRT since version 2015. It's preinstalled on Windows 10 and installable as optional Window .Update package and standalone installer for Windows Vista SP2, Windows 7 SP1, Windows 8 and Windows 8.1.

Right, I think we will need to support both msvcrt and ucrt for a while, because it is not installed by default before Windows 10, and many users may not have it (or not have admin permission to install).

I would personally be fine with completely switching over, and making UCRT a hard dependency of msys2, but not everyone may like that :-)

> I was already experimenting with creating clang64 subsystem using LLVM everywhere instead of GCC/Binutils and defaulting to UCRT with rather nice success rate for all the deps of LLVM (CMake, Z3, Python, ...). 

The main problem for the R project is Fortran support, which llvm does not have, so we still need `gfortran`. We heavily rely on lapack and friends, so fortran support is a must.

**Comment by lazka** [comment]
What's the story of clang/gcc compat? Can we mix them both on a package by package basis?

**Comment by jeroen** [comment]
> What's the story of clang/gcc compat? Can we mix them both on a package by package basis? (what about static libs?)

That seems to work well for C/fortran libs, but for C++ libs it only works if you have built clang using GNU libstdc++ (as done in most linux distributions), instead of llvm libcxx.

**Comment by mati865** [comment]
> That works for C/fortran libs, but for C++ libs it only works if you have built clang++ using GNU libstdc++ (as done by most linux distributions for exactly this reason) instead of llvm libcxx.

Some of the problems with libstdc++ are relying on winpthreads (resulting in hangs) and missing Windows ARM support. BTW we will have to build even static LLVM 11 with Clang + libc++ because the hangs got worse.
Libcxx doesn't have Windows `std::filesystem` yet and wide char support is somewhat buggy so it's not perfect either.

> What's the story of clang/gcc compat? Can we mix them both on a package by package basis? (what about static libs?)

With https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-clang/0008-enable-emutls-for-mingw.patch it seems to work good unless weak symbols are used but I'm against applying this patch for Clang focused subsystem since it's step backwards from native TLS to emutls.
There is no easy way to make GCC use Compiler-RT+libunwind or libc++, LLD is supported since GCC 9 IIRC.

**Comment by lazka** [comment]
Hm, so I guess we better have separate roots for everything and see how things go?

**Comment by mati865** [comment]
> Hm, so I guess we better have separate roots for everything and see how things go?

Probably that's the only way. Even if staying within GCC/Binutils toolchain one **cannot** mix libs linked to MSVCRT with those linked to UCRT because that will fail with linker errors. So all the packages would have to be rebuilt right away if `MINGW32` and `MINGW64` subsystems moved to UCRT.

**Comment by Biswa96** [comment]
* If there will be a separate root created for ucrt only, then how it would be migrated to regular msvcrt ones?
* Will this same treatment be applied for msys2 packages?
* Will the msys2-mingw-cross toolchain be recompiled?

**Comment by mati865** [comment]
> If there will be a separate root created for ucrt only, then how it would be migrated to regular msvcrt ones?

The only non-breaking way I can think of is to change `mingw-w64-crt` to default to UCRT and then recompile everything. This is unlikely to succeed without prior testing (it in new root or whatever).

> Will this same treatment be applied for msys2 packages?

MSYS2 packages use newlib instead of MSVCRT.

> Will the msys2-mingw-cross toolchain be recompiled?

`mingw-w64-cross-crt-git` must be configured to use UCRT by default.

**Comment by Biswa96** [comment]
@jeroen I've compile some packages with ucrt. Do you have a package from your R repo that you want to test? A simple, having less dependencies paackage would be better.

**Comment by jeroen** [comment]
Eventually I need to build R: https://github.com/r-windows/r-base...

**Comment by jeroen** [comment]
Hi all, I would like to pick this up again. 

The R project has started testing all packages with ucrt. Currently they use [an experimental custom build of gcc10 with MXE](https://svn.r-project.org/R-dev-web/trunk/WindowsBuilds/winutf8/ucrt3/howto.html) but I would very much like use msys2 to building mingw-packages against ucrt.

I think we really need to rebuild all our libraries; when we try to link regular static libraries with the ucrt toolchain, we get linking errors [like this](https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64-gcc10-UCRT/arrow-00install.html) because of CRT ABI changes.

The easiest and most obvious solution is as proposed above, to add a 3rd `makepkg-mingw` toolchain under `/ucrt64/` where everything is built with `--with-default-msvcrt=ucrt`.

A start would be to create a new repo `http://repo.msys2.org/mingw/ucrt64` so we can maybe get a build of gcc/mingw-w64 and then see if we can start building packages?

**Comment by mingwandroid** [comment]
Hey @jeroen, our systems are now at a state where this is very reasonable (and highly desirable) goal.

I'll do what I can to help out with testing and recipe development etc, especially if we can agree to produce both static and shared libraries.

Let me know if you set a project up. The usual MSYS2 communication channels of gitter, discord and a github discussion here all work for me, if you want me/other MSYS2 contributors to try to lend a hand!

**Comment by Biswa96** [comment]
Shh... This is a secret among us https://repo.msys2.org/mingw/ucrt64/ 🤫

**Comment by jeroen** [comment]
@Biswa96 cool :) What is the next step? Should we add a `makepkg_ucrt64.conf` file?

I think the configuration is mostly the same as `makepkg_mingw64.conf` except for that we should build mingw64 with `--with-default-msvcrt=ucrt`.

**Comment by Biswa96** [comment]
It has already done by lazka. The next step is to compile the cross compiler GCC toolchain (msys2 -> mingw64/ucrt64). Then compile the actual GCC toolchain for ucrt64.

**Comment by jeroen** [comment]
Cool! Excited to start testing the ucrt gcc toolchain once it is there :)

**Comment by lazka** [comment]
well, I only did the easy things until now.. actually building the thing is a bit of an unknown atm as I have no experience in that regard.. we'll see...

**Comment by jeroen** [comment]
> I'm wondering if I can just copy mingw64 and bootstrap from there instead..

Yes the build process is identical to mingw64. I think we would start with updating the `mingw-w64-crt-git` and `mingw-w64-headers` recipes to use the proper `_default_msvcrt` and then build `mingw-w64-gcc` and it's dependencies?

**Comment by lazka** [comment]
there is no clear bootstrap path for mingw64 currently afaics, but I'm doing as you suggested. cross compiling random things now until I have what I need to rebuild everything cleanly.

**Comment by jeremyd2019** [comment]
good luck.  I think I documented what I found doing the same for clang/arm64... The first thing I think you'll hit is that things look at `uname` and expect to get `MINGW`.  https://github.com/msys2/MSYS2-packages/discussions/2289#discussioncomment-257934

**Comment by lazka** [comment]
ah, thanks for the reminder. we should fix that first then.

**Comment by lazka** [comment]
https://github.com/msys2/msys2-runtime/pull/33

**Comment by jeremyd2019** [comment]
Was just re-installing my `clang32` packages and it reminded me of another issue you'll run into for a new prefix for an existing arch: https://github.com/msys2/MSYS2-packages/discussions/2289#discussioncomment-304157

**Comment by lazka** [comment]
yeah, no good fix/idea there atm

**Comment by lazka** [comment]
There are now 108 packages in the ucrt64 repo

**Comment by jeremyd2019** [comment]
I see that `ncurses` is there, guess that answers whether the issue I ran into with it was clang or ucrt related.  I am curious if you ran into the issue I did with python missing time.mktime: CLANG-packages#21

**Comment by lazka** [comment]
ncurses was broken, I mad it use cygwin tic.exe to complete the build. some install scripts are broken obviously., python I didn't check yet

**Comment by jeremyd2019** [comment]
☹️ I guess it is UCRT related after all.

**Comment by lazka** [comment]
One more ucrt issue in graphviz: https://sourceforge.net/p/mingw-w64/bugs/891/

**Comment by lazka** [comment]
I've created an ucrt label for the remaining issues: https://github.com/msys2/MINGW-packages/issues?q=is%3Aissue+is%3Aopen+label%3Aucrt

I'm going to close this. If there are any more problems please create a new specific issue so we can more easily track things.

**Comment by jeroen** [comment]
Thanks for your work on moving this forward!

**Comment by davidwed** [comment]
Exactly.

**Comment by jeroen** [comment]
What would be the point of that?

**Comment by jeremyd2019** [comment]
> Besides there is the clang32 with UCRT support, why not the mingw32 ?

There is clang32 pretty much because I wanted it enough to make it happen.  Not many others seem to really care about 32-bit.  Personally, I am kind of over gcc for mingw - there are several pretty serious bugs that seem to be languishing, while clang/llvm is very responsive about fixing issues I've come across.

I can't guarantee it (because it would add to burden on CI and mirrors), but if somebody were to come forward to create and 'adopt' ucrt32, it would probably be accepted.  But I doubt you'd find anyone around here who'd think it was worth their time to do it themselves.
