### ISSUE TITLE
Not a bug plugin support for binutils-2.35

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#6912]
Patch add's dlfcn-win32 dlopen support to binutils plugin support code.
Handles things a bit better than the builtin dlopen wrappers.

The unicode portions of the code (unused atm) could probably be removed.
[0030-fix-plugin-support.zip](https://github.com/msys2/MINGW-packages/files/5160212/0030-fix-plugin-support.zip)

**Comment by lazka** [comment]
This is quite a large patch, so there needs to be a very good reason to carry this downstream.

**Comment by revelator** [comment]
could probably strip it some by removing said unicode support and only leave the needed functions.
works a lot better than the built in dlopen wrappers so there is that ;), it was a quick and dirty job so there is room for improvement.

**Comment by revelator** [comment]
[0030-fix-plugin-support-v2.zip](https://github.com/msys2/MINGW-packages/files/5162362/0030-fix-plugin-support-v2.zip)

Removed UNICODE support, sadly it did not do much to reduce the size :/ 
reducing it even more would require a shared header and exporting the dlopen symbols to bfd and i doubt that would be accepted upstream. As it is it is standalone for each tool relying on plugin support and it works quite well.

**Comment by jeremyd2019** [comment]
> works a lot better than the built in dlopen wrappers so there is that ;), it was a quick and dirty job so there is room for improvement.

Works for what?  Is there some plugin out there that didn't work before that does with this patch?

**Comment by revelator** [comment]
Atleast in previous binutils versions i had trouble loading the lto plugin with the standard wrapper code, the wrapper code did not seem to have changed so i assumed this might still be the case.

**Comment by lazka** [comment]
I'd suggest you open a bug report upstream and propose your changes there.

**Comment by revelator** [comment]
Will do, maybe the dev also has some suggestions about linking to psapi as my code changes 
are hardly the most portable, though it should not interfere with a posix build (tested that by trying out the patch on the msys2 binutils and it does not seem to interfere with real dlopen support).
