### ISSUE TITLE
need to be rebuilt for libraw-20

### ISSUE THREAD

**Issue by sdegrande** [msys2/MINGW-packages#6922]
Libraw has been updated to version 0.20 on 2020-08-01

Freeimage tries to load libraw-19, and obviously fails.

Could you please rebuild freeimage ?

Thanks for all your great work !

**Comment by lazka** [comment]
I tried in #6924, but freeimage doesn't build successfully right now.

**Comment by Biswa96** [comment]
Try to add the patch file in ArchLinux for freeimage due to libraw update. See here https://github.com/archlinux/svntogit-community/blob/packages/freeimage/trunk/freeimage-libraw-0.20.patch

**Comment by lazka** [comment]
should be in the next upload

**Comment by sdegrande** [comment]
Great ! Thanks a lot.

**Comment by sdegrande** [comment]
I just updated my env.
It works well. Thanks !
