### ISSUE TITLE
unknown type name 'USN'

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#6923]
Hi,

When I try to compile double precision CalculiX I have this error (standard version is OK):

```
C:/msys64/mingw64/x86_64-w64-mingw32/include/winioctl.h:1454:3: error: unknown type name 'USN'
 1454 |   USN Usn;
```

**Comment by Biswa96** [comment]
Where is the source code of that program?

**Comment by 3rav** [comment]
Hi,

http://www.dhondt.de/ccx_2.17.src.tar.bz2

**Comment by Biswa96** [comment]
And how can I compile it? The source code seems to be for *nix systems. To answer your actual question, USN type is defined in `winnt.h` header file as `typedef LONGLONG USN` and it's a Win32 thing.

**Comment by Biswa96** [comment]
And how can I compile it? The source code seems to be for *nix systems. To answer your actual question, USN type is defined in `winnt.h` header file as `typedef LONGLONG USN` and it's a Win32 thing.

**Comment by 3rav** [comment]
Hi,
For mingw I used patched version, I am sending you the most limited version (standard version requires: arpack and spooles - solver).

Instruction for Ubuntu: https://www.libremechanics.com/?q=node/9

[CalculiX.zip](https://github.com/msys2/MINGW-packages/files/5173055/CalculiX.zip)

**Comment by sfhacker** [comment]
We are unable to reproduce the issue reported here!
We downloaded [ccx 2.17](http://www.dhondt.de/ccx_2.17.src.tar.bz2) and built from source.

![image](https://user-images.githubusercontent.com/25817529/92332518-cb657600-f0c1-11ea-9227-d624bc4eafd4.png)

Let us know if we can be of further assistance!

**Comment by 3rav** [comment]
I will try on another computer (different msys2).
May I ask to send me the (used) Makefile, maybe some compilation flag has an effect (name of .exe indicates that no standard Makefile was used).

**Comment by 3rav** [comment]
I compiled on a different computer and I have the same error.
May I  ask you to attach your Makefile and/or the modified source code (if there were any modifications).

**Comment by 3rav** [comment]
> We are unable to reproduce the issue reported here!
> We downloaded [ccx 2.17](http://www.dhondt.de/ccx_2.17.src.tar.bz2) and built from source.
> 
> ![image](https://user-images.githubusercontent.com/25817529/92332518-cb657600-f0c1-11ea-9227-d624bc4eafd4.png)
> 
> Let us know if we can be of further assistance!

May I ask to send me the (used) Makefile, maybe some compilation flag has an effect (name of .exe indicates that no standard Makefile was used).

**Comment by sfhacker** [comment]
Are you still having issues CalculiX?
We used the one provided by you (https://github.com/msys2/MINGW-packages/files/5173055/CalculiX.zip)

**Comment by 3rav** [comment]
Yes, I still have this error

**Comment by sfhacker** [comment]
This issue is several months old!
@3rav You have been unable to troubleshoot and fix this issue after several months?
As we posted here last year, we couldn't reproduce your issue.
Most probably your environment is broken somehow. Try reinstalling it.

**Comment by 3rav** [comment]
I had to do something else, so I had to put this error aside for later, and I am coming back to it (I was hoping some update would help here).

I just reinstall msys2/mingw64 with the required packages and I have the same error again (mingw64 console).
I can add that in the msys2 console I do not have this error, other errors appear at the end of linking libraries (ld).

**Comment by 3rav** [comment]
My test on msys2 "Actions": 
https://github.com/3rav/MINGW-packages/runs/1946328436?check_suite_focus=true

![image](https://user-images.githubusercontent.com/24394573/108629135-d25d2680-745e-11eb-9f19-eacf951fae39.png)

**Comment by 3rav** [comment]
@lazka may I ask you for help with this issue

**Comment by 3rav** [comment]
I can count on help in this topic?

**Comment by 3rav** [comment]
I have the same error for such a simple example (example.c):

```
#include <stdio.h>
#include <windows.h>
int main() {
   // printf() displays the string inside quotation
   printf("Hello, World!");
   return 0;
}
```

**Comment by sfhacker** [comment]
Oh my GOD! This open issue is one year old!!!!!!

No issues here!

![image](https://user-images.githubusercontent.com/25817529/134506883-03ea42f7-57d6-4ca8-8cc8-476478316b86.png)

**Comment by 3rav** [comment]
> Oh my GOD! This open issue is one year old!!!!!!
> 
> No issues here!
> 
> ![image](https://user-images.githubusercontent.com/25817529/134506883-03ea42f7-57d6-4ca8-8cc8-476478316b86.png)

Try with  **-DLONGLONG**

**Comment by sfhacker** [comment]
This is becoming embarrassing!

![image](https://user-images.githubusercontent.com/25817529/135512983-867755b0-6c91-418f-9363-65855c0f4a42.png)

**Comment by 3rav** [comment]
> This is becoming embarrassing!
> 
> ![image](https://user-images.githubusercontent.com/25817529/135512983-867755b0-6c91-418f-9363-65855c0f4a42.png)

I understand that you like to laugh at others, but explain to me why on a completely new mingw64 installation (from the website https://www.mingw-w64.org) I also have this error!: 
![error](https://user-images.githubusercontent.com/24394573/135523047-041d8a99-ca9d-4cd2-8201-5afcd2311f9d.jpg)

PS. Do you have an updated environment at your place?

**Comment by jeremyd2019** [comment]
Yeah, if you define `LONGLONG`, then it breaks the Windows headers.  For similar errors, try passing `-Dint`.

**Comment by 3rav** [comment]
I was able to work around this problem temporarily for CalculiX (but it still persists).

**Comment by sfhacker** [comment]
Any news about this long long long standing issue?
Can you post here your 'workaround'?
Cheers.

**Comment by 3rav** [comment]
> Any news about this long long long standing issue? Can you post here your 'workaround'? Cheers.

https://calculix.discourse.group/t/calculix-i8-and-mingw/134/4?u=rafal.brzegowy
