### ISSUE TITLE
request new package GTK VTE

### ISSUE THREAD

**Issue by lygstate** [msys2/MINGW-packages#6929]
https://gitlab.gnome.org/GNOME/vte/

**Comment by lazka** [comment]
Does vte support Windows?

**Comment by lygstate** [comment]
not yet， plan to get it works

**Comment by lazka** [comment]
upstream looks highly unix specific though

**Comment by AvtechScientific** [comment]
Is there anything new on this? This thing is needed for cross-compilation of Gnome Builder...

**Comment by AvtechScientific** [comment]
This might be related:  https://cygwin.com/packages/summary/vte-src.html

**Comment by Biswa96** [comment]
The vte program can not be compiled for native Windows platform. If I try to compile it with mingw toolchain this error is shown

```
Header "sys/ioctl.h" has symbol "TIOCGWINSZ" : NO
meson.build:264:2: ERROR: Assert failed: TIOCGWINSZ not found
```

From https://www.msys2.org/

> Despite some of these central parts being based on Cygwin, the main focus of MSYS2 is to provide a build environment for native Windows software and the Cygwin-using parts are kept at a minimum.
