### ISSUE TITLE
Current libgd packages are useless

### ISSUE THREAD

**Issue by flamewing** [msys2/MINGW-packages#6937]
This happens with both versions:
- mingw-w64-i686-libgd
- mingw-w64-x86_64-libgd

Install either package. Then try one of the many tools to convert images:
```sh
$ pngtogd --help
Usage: pngtogd filename.png filename.gd
$ pngtogd test.png test.gd
GD Warning: GD image support has been disabled
$ pngtogd test.png test.luaimg
GD Warning: GD image support has been disabled
$ pngtogds --help
Usage: pngtogd2 filename.png filename.gd2 cs fmt
       where cs is the chunk size
       fmt is 1 for raw, 2 for compressed
$ pngtogd test.png test.gd2 0 1
GD Warning: GD2 image support has been disabled
```

Based on configure.ac and the library code, it seems that either zlib is not being detected by ./configure, or that it is being called with --disable-gd-formats.

**Comment by lazka** [comment]
Did it work at some point?

**Comment by Biswa96** [comment]
The current PKGBUILD in libgd uses cmake. I have tried with adding `-DENABLE_GD_FORMATS=ON` but same result as OP.

**Comment by sfhacker** [comment]
Any news/update about this issue?

![image](https://user-images.githubusercontent.com/25817529/92316253-ad9dff80-f034-11ea-8787-3316aba136ef.png)

**Comment by elvadong** [comment]
install libgd with ./configure --enable-gd-formats

**Comment by sfhacker** [comment]
This issue is over a year old!
