### ISSUE TITLE
gdb does no work with aslr executables. Specifically, seems to assume exe loaded at its preferred base

### ISSUE THREAD

**Issue by lygstate** [msys2/MINGW-packages#6941]
Hi, when I compiling qemu with newest mingw-w64-binutils 2.35-4, I can running the program, but can not debug it, what's the possible issue?
And once I downgrading to mingw-w64-x86_64-binutils-2.33.1-1-any.pkg.tar.xz, it's can debugging

**Comment by Biswa96** [comment]
Are you compiling using PKGBUILD file or from qemu git repository? Did you add `-O0 -g` in `$CFLAGS` and/or `$CXXFLAGS`?

**Comment by lygstate** [comment]
No, I am compiling from master qemu source

**Comment by lygstate** [comment]
> Are you compiling using PKGBUILD file or from qemu git repository? Did you add `-O0 -g` in `$CFLAGS` and/or `$CXXFLAGS`?

I can be sure the compiling flags are valid, because same config, once I downgrading binutils to mingw-w64-x86_64-binutils-2.33.1-1-any.pkg.tar.xz, it's can debugging properly
,

**Comment by mati865** [comment]
> I can running the program, but can not debug it, what's the possible issue?

What do you mean by that?

**Comment by jeremyd2019** [comment]
I just found that an executable with dynamicbase didn't hit a breakpoint I set, and the backtrace was not symbolicated.  I'm guessing gdb didn't notice that the image was loaded at a different address.  clearing dynamicbase fixed it

**Comment by lygstate** [comment]
> I just found that an executable with dynamicbase didn't hit a breakpoint I set, and the backtrace was not symbolicated. I'm guessing gdb didn't notice that the image was loaded at a different address. clearing dynamicbase fixed it

does this means thats a gdb bug？

**Comment by jeremyd2019** [comment]
I expect so.  You could try lldb and see if that works

**Comment by lygstate** [comment]
> I expect so. You could try lldb and see if that works

tried.but still failed, do you means disable the dynamic base, then the debugger would works?

**Comment by mati865** [comment]
I have noticed it when devugging some of the segfaults. GDB could not give back trace or disassembly but with LLDB back trace worked, I'll try with breakpoints when I get more time.

**Comment by jeremyd2019** [comment]
The gdb issue is really annoying - I just spent more effort than I should have on https://github.com/msys2/MINGW-packages/pull/6935#issuecomment-687943411, using windbg against the ASLR enabled exe, but it doesn't show any source information with gcc's symbols.  Then gdb with ASLR disabled to look at the relative offsets into the exe to see what those offsets were doing.  I looked at installing lldb, but it wanted to install stuff that would take a TON of disk space, and I didn't give that much space to my virtual machine.

**Comment by lygstate** [comment]
@jeremyd2019  I am using lldb to debug it and works fine, so would think that's a gdb problem.

**Comment by jeremyd2019** [comment]
Someone with access want to rename this issue to something about gdb not working with aslr executables?  (specifically, it seems to assume that the exe loaded at its preferred base)

**Comment by jeremyd2019** [comment]
Looks like there's an upstream bug for this:
https://sourceware.org/bugzilla/show_bug.cgi?id=26037

**Comment by mingwandroid** [comment]
Changed the title.

**Comment by jeremyd2019** [comment]
Upstream bug says it's fixed, in commit https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=584cf46d0ab5960cca76bfaf414cee5641166868

**Comment by jeremyd2019** [comment]
Didn't get lucky enough that the patch applied cleanly to 9.2.  Going to try cherry-picking onto 9.2, once my machine catches up with the giant git repo.
