### ISSUE TITLE
undefined reference to `__imp_cabs'

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#6952]
When I try to complile Pastix https://github.com/Kabbone/PaStiX4CalculiX/tree/cudaless, I have this error:
```
[ 82%] Linking CXX static library libpastix.a
[ 82%] Built target pastix
[ 84%] Built target spm_test
[ 84%] Linking C executable spm_matvec_tests.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/usr/lib/libm.a(t-d000248.o):fake:(.text+0x2): undefined reference to `__imp_cabs'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/usr/lib/libm.a(t-d000249.o):fake:(.text+0x2): undefined reference to `__imp_cabsf'
collect2.exe: error: ld returned 1 exit status
```

**Comment by Biswa96** [comment]
It looks like you are using MSYS2 environment with mingw gcc. Use the mingw64 or mingw32 environment.

**Comment by 3rav** [comment]
I always use the mingw64 console:

`EXD-002@EXD-002-THINK MINGW64 /usr/local/PaStiX4CalculiX-cudaless
`

**Comment by Biswa96** [comment]
I am not sure how you compiled it. I have cloned that repository with that specific branch. Then I installed hwloc, lapack, scotch and ran `mkdir bin; cd bin; /mingw64/bin/cmake -G Ninja ..`. This error is shown:

```
CMake Error at CMakeLists.txt:435 (message):
  PASTIX_INT64 is enabled and provided Scotch is not compiled with int64 support.
```

mingw-w64-scotch may need some change. 🤔

**Comment by 3rav** [comment]
I add -DPASTIX_INT64=OFF

**Comment by Biswa96** [comment]
Now `make` and `ninja` both shows some lexical error. For example,

```
refinement/CMakeFiles/refinement_headers_tgt.dir/build.make:83: *** missing separator.  Stop.
CMakeFiles/bcsc_headers_tgt.dir/build.make:83: *** missing separator.  Stop.
```

**Comment by 3rav** [comment]
Finally I was able to build pastix4calculix (2 job Status: Success, without any error: https://github.com/3rav/MINGW-packages/actions/runs/560359319). 
Then I deleted the branch containing that package (to reduce the history of its creation).
I downloaded PKGBUILD and the patch file (action, summary from deleted branch) from an archive called "source", where everything went 100% correct. The current branch based on this downloaded PKGBUILD file has the same error as in the title (undefined reference to `__imp_cabs'; only for x64, the x32 is OK), what could it be caused by?

**Comment by mati865** [comment]
2nd build (one with `D:/a/_temp/msys/msys64/usr/lib/libm.a;D:/a/_temp/msys/msys64/usr/lib/librt.a`) is probably using wrong compiler because `/usr/lib` should *not* be there. Maybe it's using `/usr/bin/gcc`?

**Comment by 3rav** [comment]
2nd build:

```
  -- The C compiler identification is GNU 10.2.0
  -- The CXX compiler identification is GNU 10.2.0
  -- The Fortran compiler identification is GNU 10.2.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: D:/a/_temp/msys/msys64/mingw64/bin/gcc.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: D:/a/_temp/msys/msys64/mingw64/bin/g++.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
```

How is it possible that the generator only 30 minutes later does not generate the file correctly ('MSYS Makefiles' ora 'Ninja')?

**Comment by 3rav** [comment]
I add this flag to PKGBUILD: `-DCMAKE_SYSTEM_IGNORE_PATH=/usr/lib \` and it helped
