### ISSUE TITLE
libwinpthread-1.dll under mingw-w64-winpthreads-git is missing /dynamicbase after built with --dynamicbase

### ISSUE THREAD

**Issue by salowenh** [msys2/MINGW-packages#6953]
Using the latest msys (20200903)
Built `mingw-w64-winpthreads-git` for both x86 & x64, verified `--dynamicbase` appears in LDFLAGS.
`/dynamicbase` is missing from `libwinpthread-1.dll` (x64 & x86)

`makepkg_mingw64.conf`:
```LDFLAGS="-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat"```

**Comment by mati865** [comment]
Confirmed, seems like it ignores system LDFLAGS.

**Comment by lhmouse** [comment]
Try `LDFLAGS='-Wl,--dynamicbase'`?

**Comment by mati865** [comment]
@lhmouse I've used `makepkg-mingw` with those flags:
```
$ grep LDFLAGS /etc/makepkg_mingw64.conf
LDFLAGS="-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat"
#LDFLAGS="-pipe"
```

**Comment by lhmouse** [comment]
I didn't use `makepkg-mingw`, but ran `make LDFLAGS='-Wl,--dynamicbase'` directly in **BASH**. The flag was passed to **libtool**, which passes it to **GCC** after `-L./fakelib  -g -O2 -no-pthread`. It wasn't ignored.

**Comment by Biswa96** [comment]
Both PKGBUILD of mingw-w64-crt and mingw-w64-winpthreads packages has `!buildflags` option. Is it related to this issue?

**Comment by Biswa96** [comment]
PKGBUILD of mingw-w64-crt, mingw-w64-winpthreads, mingw-w64-winstorecompat packages has `!buildflags` option. Is it related to this issue?

**Comment by salowenh** [comment]
> PKGBUILD of mingw-w64-crt, mingw-w64-winpthreads, mingw-w64-winstorecompat packages has `!buildflags` option. Is it related to this issue?

Confirming changing to `buildflags` fixes the issue, should this become a PR?

**Comment by Biswa96** [comment]
I am wondering why `buildflags` option was disabled at first place @Alexpux

**Comment by Biswa96** [comment]
Should `buildflags` be enabled for other mingw-w64 packages? I am wondering why `buildflags` option was disabled at first place @Alexpux

**Comment by lhmouse** [comment]
In principle the CRT is built prior to other packages, so host flags generally shouldn't be involved.

`_FORTIFY_SOURCE` is a good example, because it depends on the **GCC** library `libssp-?.dll`, which in turn depends on the CRT. If you built the CRT with `_FORTIFY_SOURCE` you would end up in circular dependencies. Maybe that's the reason.
