### ISSUE TITLE
graphite2.pc doesn't use full filepaths

### ISSUE THREAD

**Issue by sheaf** [msys2/MINGW-packages#6958]
The package `graphite2` seems to present the same issue that `fontconfig` used to (#872, fixed in #1062). On my end this causes problems installing the Haskell `gi-cairo-render` library, which depends on `cairo` which in turn depends on `graphite2`:

```
> pkg-config --cflags graphite2
-I/msys64/mingw64/include
```

When the `ghc-pkg` utility gets passed `/msys64/mingw64/include`, it assumes this is a relative path instead of a Unix-style path and throws an error.    

On my end, changing `graphite2.pc` from

```
Libs: -L/msys64/mingw64/lib -lgraphite2
Cflags: -I/msys64/mingw64/include
```

to

```
Libs: -L${libdir} -lgraphite2
Cflags: -I${includedir}
```

fixes the issue, but I'm not sure what that change corresponds to in terms of the `PKGBUILD` source file.

**Comment by lazka** [comment]
you probably need the mingw pkg-config:  `pacman -S mingw-w64-x86_64-pkg-config`

**Comment by sheaf** [comment]
@lazka Yes, that seems to have fixed it too:

```
> pkg-config --cflags graphite2
-IC:/msys64/mingw64/include
```

Not sure what version of `pkg-config` I had beforehand... thanks. Feel free to close.

**Comment by sheaf** [comment]
(Sorry I spoke too soon in an earlier post.)

I made sure to use `mingw-w64-x86_64-pkg-config`, but without the modification to `graphite2.pc` I still get

```
> pkg-config --cflags graphite2
-I/msys64/mingw64/include
```

which still causes confuses `ghc-pkg`

```
gi-cairo-render-0.0.1: include-dirs: /msys64/mingw64/include is a relative path which makes no sense
```

**Comment by lazka** [comment]
ah, right, yeah, that needs fixing

**Comment by Biswa96** [comment]
@sheaf What is the expected output of `pkg-config --cflags graphite2` command?

**Comment by sheaf** [comment]
@Biswa96 In my case, that would be

```
-IC:/msys64/mingw64/include
```

Same issue as in #872.

**Comment by Biswa96** [comment]
This issue is fixed in mingw-w64-*-graphite2 package version 1.3.14-2. Update the package with `pacman -S` and test.

**Comment by sheaf** [comment]
Yep, the new version works nicely for me, thanks for the fix.
