### ISSUE TITLE
package request: shaderc

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#6961]
https://github.com/msys2/MINGW-packages/pull/6960#issuecomment-689103004

Required for vulkan support in gstreamer

**Comment by Biswa96** [comment]
shaderc has some sort of weird dependency with glslang and spirv-tools. shaderc releases are in between releases of glslang. If I compile a specific version of shaderc either I got compiler error or linking error. shaderc has a DEPS file which mentions the git commit of glslang and spirv-tools but those commits are not the stable ones.

**Comment by lazka** [comment]
ok, thanks for looking into it
