### ISSUE TITLE
sudo apt install mingw-w64 did not install everything

### ISSUE THREAD

**Issue by PQCraft** [msys2/MINGW-packages#6968]
I cannot cross-compile due to `/usr/i686-w64-mingw32/bin/i686-w64-mingw32-gcc` missing

**Comment by Biswa96** [comment]
MSYS2 don't use apt. It uses pacman as a package manager. One line issue can not provide the full context. Please explain your issue.

**Comment by PQCraft** [comment]
I used sudo apt install mingw-w64. When I naviigated to /usr/i686-w64-mingw32/bin, I expected to see i686-w64-mingw32-gcc, i686-w64-mingw32-g++, i686-w64-mingw32-g++, and i686-w64-mingw32-ld. They are all missing. I am using Linux Mint 20 if this helps.

**Comment by Biswa96** [comment]
MSYS2 is not related to Linux Mint.

**Comment by PQCraft** [comment]
idk what you meant by that

**Comment by 1480c1** [comment]
MSYS2 is for windows, windows != Linux Mint

**Comment by PQCraft** [comment]
i should just go install codeblocks and sdl2 on windows and compile it there. I was trying to avoid that due to Windows taking eternities to boot and shut down (mostly due to data rot and bad sectors)

**Comment by PQCraft** [comment]
it also erased my linux partition once and rewrote grub. i am not in the best of relations with windows.

**Comment by Biswa96** [comment]
You (We) are **free to use** any operating system you (we) want. But this issue is not related to this repository. I don't know about Debian family. I use ArchLinux and it has `mingw-w64-gcc` package for mingw-w64 cross compilation.
