### ISSUE TITLE
[binutils] linker non-functional from cmake

### ISSUE THREAD

**Issue by CendioOssman** [msys2/MINGW-packages#6974]
Something happened recently that started breaking our automated Travis builds:

https://travis-ci.community/t/collect2-exe-error-ld-returned-5-exit-status-using-the-latest-mingw/9840

We didn't change anything in our end, so we're guessing something changed from MSYS.

I've done a debug build here:

https://travis-ci.org/github/TigerVNC/tigervnc/builds/725223373

The output is unfortunately oddly cropped so I'm not sure what the issue is. Help?

(I did see the comment on #6943 about some cmake patch. Is cmake currently known broken with MSYS?)

**Comment by lazka** [comment]
Fixed in #6971, will be in the next update
