### ISSUE TITLE
Internal Compiler Error while building nettle library

### ISSUE THREAD

**Issue by josuegomes** [msys2/MINGW-packages#6987]
OS: Windows 10 Pro 64-bit

Steps to reproduce:

1. Dowload https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20200903.exe
2. Install msys2-x86_64-20200903.exe
3. Launch MSYS2 MinGW 64-bit
4. Run:
    $ pacman -Syu
5. Run:
    $ pacman -S autoconf automake libtool make mingw-w64-x86_64-toolchain
    $ mkdir /c/prefix
    $ export PKG_CONFIG_PATH=/c/prefix/lib/pkgconfig
6. Download, build and install libgmp
    $ curl -O https://gmplib.org/download/gmp/gmp-6.2.0.tar.xz
    $ tar xf gmp-6.2.0.tar.xz
    $ cd gmp-6.2.0
    $ ./configure --build=x86_64-w64-mingw32 --prefix=/c/prefix --enable-shared --disable-static --enable-fat
    $ make && make install
7. Download and build libnettle
    $ curl -O https://ftp.gnu.org/gnu/nettle/nettle-3.5.1.tar.gz
    $ tar xf nettle-3.5.1.tar.gz
    $ cd nettle-3.5.1
    $ ./configure --build=x86_64-w64-mingw32 --prefix=/c/prefix --enable-shared --disable-static --enable-fat
    $ make

Build fails

gcc -O -g `test -f eccdata.c || echo './'`eccdata.c \
-o eccdata.exe
In file included from eccdata.c:41:
mini-gmp.c: In function 'mpz_set_d':
mini-gmp.c:1654:3: internal compiler error: Segmentation fault
 1654 |   if (x != x || x == x * 0.5)
      |   ^~
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/msys2/MINGW-packages/issues> for instructions.
make[2]: *** [Makefile:313: eccdata.exe] Error 1

Similar errors occur with nettle-3.4, nettle-3.4.1, nettle-3.6

**Comment by jeremyd2019** [comment]
I bet the gmp dll from your prefix is on the path before the /mingw64 one.  #6983

**Comment by josuegomes** [comment]
With nettle-3.4 and nettle-3.4.1 the error can be reproduced just by compiling shadata.c (which has no other dependencies except standard library);

$ curl -O https://ftp.gnu.org/gnu/nettle/nettle-3.4.tar.gz
$ tar xf nettle-3.4.tar.gz
$ cd nettle-3.4
$ gcc -c shadata.c

shadata.c: In function 'main':
shadata.c:18:3: internal compiler error: Segmentation fault
   18 |   static const double third = 1.0/3;
      |   ^~~~~~
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/msys2/MINGW-packages/issues> for instructions.

**Comment by jeremyd2019** [comment]
The error can be reproduced by just having a floating point constant in C:
```c
int main() { double d = 1.0; return 0; }
```
It's due to improper linkage between gcc and libgmp

**Comment by josuegomes** [comment]
Indeed.
