### ISSUE TITLE
mingw-w64-guile can not build for mingw64

### ISSUE THREAD

**Issue by lixuzhang** [msys2/MINGW-packages#699]
SNARF  print.x
  SNARF  procprop.x
G:/msys64/home/lixuzhang/MINGW-packages/mingw-w64-guile/src/guile-2.0.11/libguile/numbers.c:282:2: error: #error creation of mpz not implemented for this inum size
 #error creation of mpz not implemented for this inum size
  ^
  SNARF  procs.x
  SNARF  promises.x
Makefile:3716: recipe for target 'numbers.x' failed
make[2]: **\* [numbers.x] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[2]: Leaving directory '/home/lixuzhang/MINGW-packages/mingw-w64-guile/src/build-x86_64-w64-mingw32/libguile'
Makefile:1821: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/lixuzhang/MINGW-packages/mingw-w64-guile/src/build-x86_64-w64-mingw32'
Makefile:1706: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by Alexpux** [comment]
This is known issue and we not have guile packages for ming builded. You need contact guile devs to fix it. I will not do it.

**Comment by lazka** [comment]
Closing in favor of #3298
