### ISSUE TITLE
[BUG] GDB MI is broken after latest update

### ISSUE THREAD

**Issue by ice0** [msys2/MINGW-packages#7004]
## Describe the bug

I got error "You can't do that when your target is `exec'" when trying to debug program using gdb with MI interpreter.

## Steps to Reproduce the Problem

1. Run `gdb --interpreter=mi`
2. Enter command '-file-exec-and-symbols "./path-to-your/program.exe"'
3. You will get "You can't do that when your target is `exec'" message.

Expected behavior: You should get `^done` answer.

## Additional Context: Operating System, Screenshots

- OS: [Windows 10 64bit]

**Comment by ice0** [comment]
Just checked - works fine without `gdb-windows-aslr.patch`.

ping @jeremyd2019

**Comment by lygstate** [comment]
failed again! gdb.

**Comment by lygstate** [comment]
not the problem of aslr, The broken thing comes from 2020-09-18. The gdb comes before 2020-09-18 are works fine

**Comment by lygstate** [comment]
Yeap, https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gdb-9.2-1-any.pkg.tar.zst works fine now with newest binutils

**Comment by jeremyd2019** [comment]
Looks like there was an additional fix to the code from the commit I cherry-picked.
https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=b7d64b29094ef58448c9b41bcde299fad2976237
