### ISSUE TITLE
[source-highlight] v. 3.1.9-1 - Installs but just quits without any output, when run.

### ISSUE THREAD

**Issue by henrik-jensen** [msys2/MINGW-packages#7010]
source-highlight version 3.1.9-1

`$ pacman -S mingw-w64-x86_64-source-highlight` installs `source-highlight` with boost dependencies but the binary does not seem to work.  Just returns immediately to the prompt, even `$ source-highlight --help`, without printing anything ( though, no surprise, `$ man source-highlight` does work ).

FYI: Installed on my system (output `$ pacman -Q`):
[pacman-Q_2020-09-21_00.29.02,314.txt](https://github.com/msys2/MINGW-packages/files/5252805/pacman-Q_2020-09-21_00.29.02.314.txt)

Host OS : Windows 10 Home 2004 64 bit [Build 10.0.19041.508]

**Comment by jannick0** [comment]
@henrik-jensen Locally the updated package works as expected.  It would be helpful if you could check once the updated package is released and close the issue if solved.  Thanks.

**Comment by Biswa96** [comment]
^ Also if you don't like to wait (like me) you can download the package from the GitHub Actions artifacts in linked pull request.

**Comment by Biswa96** [comment]
^ Also if you don't like to wait (like me) you can download the package from the GitHub Actions artifacts in linked pull request.

**Comment by henrik-jensen** [comment]
@jannick0 
> @henrik-jensen Locally the updated package works as expected. It would be helpful if you could check once the updated package is released and close the issue if solved. Thanks.

I'll do that, thanks.

**Comment by lazka** [comment]
I guess this is fixed?

**Comment by jannick0** [comment]
Yes, issue could be closed.

**Comment by henrik-jensen** [comment]
@lazka - Thanks for closing it.
@jannick0 - Sorry, I've not been able to close it myself, as I've promised, for physical life reasons.
And yes, I can confirm that it's solved. Thanks.
