### ISSUE TITLE
winres.h in mingw-w64-x86_64-headers-git-8.0.0.6001.98dad1fe-1 is incompatible with Windows SDK

### ISSUE THREAD

**Issue by zufuliu** [msys2/MINGW-packages#7037]
@lhmouse the winres.h in mingw-w64-x86_64-headers-git-8.0.0.6001.98dad1fe-1 doesn't define `IDC_STATIC` (as -1), thus incompatible with the one in Visual Studio Windows SDK.

there is working one in ReactOS, see https://github.com/reactos/reactos/blob/master/sdk/include/psdk/winres.h 
https://sourceforge.net/p/mingw-w64/feature-requests/91/

**Comment by Biswa96** [comment]
You could send patch file in mingw-w64 mailing list. Contributions are welcomed 🤗

**Comment by Biswa96** [comment]
I have added that file. You could blame me. Can you provide what is the compiler error that you have got with that file? I have compiled vulkan projects with it without any issue. Also you could send patch file in mingw-w64 mailing list. Contributions are always welcomed 🤗

**Comment by zufuliu** [comment]
Consider these files
https://github.com/zufuliu/notepad2/blob/master/metapath/src/metapath.rc
https://github.com/zufuliu/notepad2/blob/master/src/Notepad2.rc

change code for MinGW to `#include <winres.h>`
```cpp
#if defined(__MINGW64__) || defined(__MINGW32__)
#include <afxres.h>
#include <winresrc.h>
#else
#include <winres.h>
#endif
```

run windres (mingw-w64-x86_64-binutils-2.35-6)
```
windres metapath.rc
windres: metapath.rc:227: syntax error
metapath.rc:728: fatal error: when writing output to : Invalid argument
  728 | /////////////////////////////////////////////////////////////////////////////
      |
compilation terminated.
windres: preprocessing failed.
```

with 
```
#define IDC_STATIC (-1)
#include <winres.h>
```
windres runs without any problem.

**Comment by zufuliu** [comment]
a simple test.rc, which coimpiles when IDC_STATIC is defined.
```cpp
#include <winres.h>
#define IDR_MAINWND 100
IDR_MAINWND MENU
BEGIN
    POPUP "&File"
    BEGIN
        MENUITEM "&New\tCtrl+N", IDC_STATIC 
    END
END
```

```
windres test.rc
windres: test.rc:7: syntax error
```

**Comment by Biswa96** [comment]
Patch sent https://sourceforge.net/p/mingw-w64/mailman/message/37116526/.

**Comment by Biswa96** [comment]
I think the #ifdef isn't required anymore. If you need anything to add in mingw-w64 I would be happy to help.

**Comment by Biswa96** [comment]
Added in mingw-w64 master.

**Comment by zufuliu** [comment]
Thanks👍, closed this as fixed.

**Comment by Biswa96** [comment]
O, forgot to ask. Can whole notepad2 and/or Notepad++  (including scintilla) be compiled with mingw-64 based toolchain? I am thinking of doing the arm thingy.

**Comment by Biswa96** [comment]
The wiki does not mention how to build with gcc or clang. Am I missing something?

**Comment by zufuliu** [comment]
It's in next section, https://github.com/zufuliu/notepad2/wiki/Build-Notepad2#codelite
