### ISSUE TITLE
i686 libstdc++-6.dll built after latest mingw crt/winpthreads/etc update breaks things

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#7043]
After installing a freshly built gcc, things are silently failing. cmake was the first thing I saw, but then when I tried to find out what was happening I saw gdb was also silently failing.
the most likely thing that changed between when it worked and now would be the mingw crt/etc packages were updated

dependency walker is showing libstdc++ has undefined imports `__emutls_v._ZSt11_once_call` and `__emutls_v.Zst15_once_callable`. Those symbols are present in the existing/working libstdc++-6.dll.

libstdc++-6.dll from CI rebuild of gcc has the issue. Local build of gcc after downgrading mingw packages(`pacman -U /var/cache/pacman/pkg/mingw-w64-i686-*-8.0.0.5*`) ongoing, but there is already a stage3 libstdc++-6.dll, which defines those symbols.

**Comment by jeremyd2019** [comment]
Exact packages downgraded:
```
/var/cache/pacman/pkg/mingw-w64-i686-crt-git-8.0.0.5966.f5da805f-1-any.pkg.tar.zst
/var/cache/pacman/pkg/mingw-w64-i686-headers-git-8.0.0.5966.f5da805f-1-any.pkg.tar.zst
/var/cache/pacman/pkg/mingw-w64-i686-libmangle-git-8.0.0.5573.a4de8df4-1-any.pkg.tar.xz
/var/cache/pacman/pkg/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
/var/cache/pacman/pkg/mingw-w64-i686-tools-git-8.0.0.5903.3310d459-1-any.pkg.tar.zst
/var/cache/pacman/pkg/mingw-w64-i686-winpthreads-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
/var/cache/pacman/pkg/mingw-w64-i686-winstorecompat-git-8.0.0.5903.3310d459-1-any.pkg.tar.zst
```

**Comment by mati865** [comment]
You'd have to inspect build logs but my guess is the linking order is not correct for new build of winpthreads.
After https://github.com/msys2/MINGW-packages/pull/6955 it gained dependencies on some of mingw-w64 libraries: https://github.com/rust-lang/rust/pull/77208

It should be trivial to confirm it by using `ntldd` on broken `libstdc++-6.dll`, if it doesn't print `libwinpthread-1.dll` then libstdc++ was built without threading support.

**Comment by jeremyd2019** [comment]
```
$ ntldd libstdc++-6.dll
        libgcc_s_dw2-1.dll (0x00160000)
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x00ea0000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x00ea0000)
        libwinpthread-1.dll => D:\msys32\mingw32\bin\libwinpthread-1.dll (0x00180000)
```

**Comment by Biswa96** [comment]
D:\msys32?

**Comment by jeremyd2019** [comment]
> D:\msys32?

my tablet - stuck with 32-bit windows.  I'd fire up a 64-bit VM if necessary, but for this quick check the tablet was fine

I did the build on github though - the logs and artifacts should be available https://github.com/jeremyd2019/MINGW-packages/actions/runs/274408323

**Comment by jeremyd2019** [comment]
```
$ nm /mingw32/bin/libstdc++-6.dll | grep -E 'thread|tls' | cut -d' ' -f 3 > old
$ nm libstdc++-6.dll | grep -E 'thread|tls' | cut -d' ' -f 3 > new
$ diff old new
2d1
< __imp____emutls_get_address
```

**Comment by jeremyd2019** [comment]
I just came across https://github.com/msys2/MINGW-packages/pull/6539#issuecomment-636429842.  I guess I've got to try the build again locally with newer mingw packages (probably winpthread) and look for a config.log.

**Comment by mati865** [comment]
@jeremyd2019 it's not going to help. Winpthreads package in the repo already contains that fix.

@lhmouse any idea why [that fix](https://github.com/mirror/mingw-w64/commit/e82b4f5681c1e4a81f2ac22e3b1789fb1a844b95) does not work after applying https://github.com/msys2/MINGW-packages/pull/6955 (it adds [CPPFLAGS="-D__USE_MINGW_ANSI_STDIO=1"](`https://github.com/msys2/MSYS2-packages/blob/c5e3193396f2bbe2e986c10d8e0613bcdaf008bb/pacman/makepkg_mingw64.conf#L59`) among the other changes).

**Comment by jeremyd2019** [comment]
I'm not saying that change is going to fix it.  I'm saying I want to do another build to confirm exactly why the TLS test fails, if it is the same undefined symbol or some new one

**Comment by jeremyd2019** [comment]
Same symbol:
```
configure:28821: /home/adminuser/MINGW-packages/mingw-w64-gcc/src/build-i686-w64-mingw32/./gcc/xgcc -B/home/adminuser/MINGW-packages/mingw-w64-gcc/src/build-i686-w64-mingw32/./gcc/ -L/mingw32/i686-w64-mingw32/lib -L/mingw32/lib -isystem /mingw32/i686-w64-mingw32/include -isystem /mingw32/include -B/mingw32/i686-w64-mingw32/bin/ -B/mingw32/i686-w64-mingw32/lib/ -isystem /mingw32/i686-w64-mingw32/include -isystem /mingw32/i686-w64-mingw32/sys-include   -fno-checking -o conftest.exe -g -march=i686 -mtune=generic -O2 -pipe  -static -pipe -Wl,--dynamicbase,--nxcompat,--no-seh -Wl,--large-address-aware conftest.c  >&5
C:\msys64\mingw32\i686-w64-mingw32\bin\ld.exe: C:/msys64/mingw32/i686-w64-mingw32/lib\libmingwex.a(lib32_libmingwex_a-mingw_pformat.o): in function `_pformat_int':
C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/stdio/mingw_pformat.c:797: undefined reference to `__umoddi3'
collect2.exe: error: ld returned 1 exit status
configure:28821: $? = 1
```

**Comment by lhmouse** [comment]
@mati865 winpthreads should be built with `-D__USE_MINGW_ANSI_STDIO=0` (_zero_ instead of _one_). Please try reverting the commit in https://github.com/msys2/MINGW-packages/issues/6953 and rebuilding.

**Comment by jeremyd2019** [comment]
Or maybe just filter the `-D__USE_MINGW_ANSI_STDIO=1` out of the CPPFLAGS in that PKGBUILD so it continues to get the benefit of the LDFLAGS

**Comment by Biswa96** [comment]
Any explanation, why zero not one? Also as the issue is in i686, shouldn't it be done with that arch only?

**Comment by jeremyd2019** [comment]
> Any explanation, why zero not one? Also as the issue is in i686, shouldn't it be done with that arch only?

https://github.com/msys2/MINGW-packages/pull/6539#issuecomment-636618954
and the following couple of comments

**Comment by lhmouse** [comment]
Otherwise the static winpthreads library suddenly requires libgcc and fails during bootstrapping, where it isn't available.

In a canonical cross-compiling (it's probably stage2 of bootstrapping) procedure, the host C library (including the thread library) is linked to produce the host libgcc so it must end up with no undefined reference. GCC's configure apparently tests static linking, so the static winpthreads library cannot reference libgcc symbols (64-bit integer division under this circumstance).
