### ISSUE TITLE
[med] build broken

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#7075]
https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-med

![image](https://user-images.githubusercontent.com/24394573/94803287-60217200-03e9-11eb-9177-0cce9844d3c3.png)

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=med

**Comment by lazka** [comment]
It never built successfully. Feel free to look into it (I don't know what fails)
