### ISSUE TITLE
https://repo.msys2.org is not working!

### ISSUE THREAD

**Issue by DileSoft** [msys2/MINGW-packages#7084]
![image](https://user-images.githubusercontent.com/964238/94951870-b4157f00-04ed-11eb-98b9-e129d4afe8ac.png)

**Comment by lazka** [comment]
We are working on it.

**Comment by nu8** [comment]
As a workaround, you can use a mirror from here:

https://github.com/msys2/MSYS2-packages/tree/master/pacman-mirrors

Example:

https://mirror.selfnet.de/msys2

kind of surprised previous person didnt mention that.

**Comment by r4sas** [comment]
Hello.
Im' trying disable unavailable repository inside appveyor-ci by sed'ing primary address, but pacman continues use it. What I'm doing wrong?

Disabling command:
```
- c:\msys64\usr\bin\bash -lc "sed -i 's/^Server\ =\ http:\/\/repo\.msys2\.org/#Server\ =\ http:\/\/repo\.msys2\.org/g' /etc/pacman.d/mirrorlist.*"
```
Next execution:
```
c:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
:: Synchronizing package databases...
error: failed retrieving file 'mingw32.db' from repo.msys2.org : Connection timed out after 10008 milliseconds
error: failed retrieving file 'mingw64.db' from repo.msys2.org : Connection timed out after 10011 milliseconds
error: failed retrieving file 'msys.db' from repo.msys2.org : Connection timed out after 10011 milliseconds
...
```

**Comment by ice0** [comment]
@r4sas as a temporary solution, I just rewrote it completely:
```
- c:\msys64\usr\bin\bash -lc "echo 'Server = https://mirror.yandex.ru/mirrors/msys2/mingw/x86_64/' > /etc/pacman.d/mirrorlist.mingw64"
- c:\msys64\usr\bin\bash -lc "echo 'Server = https://mirror.yandex.ru/mirrors/msys2/mingw/i686/' > /etc/pacman.d/mirrorlist.mingw32"
- c:\msys64\usr\bin\bash -lc "echo 'Server = https://mirror.yandex.ru/mirrors/msys2/msys/$arch/' > /etc/pacman.d/mirrorlist.msys"
```

**Comment by r4sas** [comment]
> @r4sas as a temporary solution, I just rewrote it completely:
> 
> ```
> - c:\msys64\usr\bin\bash -lc "echo 'Server = https://mirror.yandex.ru/mirrors/msys2/mingw/x86_64/' > /etc/pacman.d/mirrorlist.mingw64"
> - c:\msys64\usr\bin\bash -lc "echo 'Server = https://mirror.yandex.ru/mirrors/msys2/mingw/i686/' > /etc/pacman.d/mirrorlist.mingw32"
> - c:\msys64\usr\bin\bash -lc "echo 'Server = https://mirror.yandex.ru/mirrors/msys2/msys/$arch/' > /etc/pacman.d/mirrorlist.msys"
> ```

Thank you for idea, I think that's better becuase something block sed'ing as I see:
```
c:\msys64\usr\bin\bash -lc "sed -e '/repo\.msys2\.org/ s/^#*/#/' -i /etc/pacman.d/mirrorlist.*"
c:\msys64\usr\bin\bash -lc "cat /etc/pacman.d/mirrorlist.*"
##
## 32-bit Mingw-w64 repository mirrorlist
##
## Primary
## msys2.org
Server = http://repo.msys2.org/mingw/i686/
Server = https://sourceforge.net/projects/msys2/files/REPOS/MINGW/i686/
Server = http://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/
Server = https://mirror.yandex.ru/mirrors/msys2/mingw/i686/
##
## 64-bit Mingw-w64 repository mirrorlist
##
## Primary
## msys2.org
Server = http://repo.msys2.org/mingw/x86_64/
Server = https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/
Server = http://www2.futureware.at/~nickoe/msys2-mirror/mingw/x86_64/
Server = https://mirror.yandex.ru/mirrors/msys2/mingw/x86_64/
##
## MSYS2 repository mirrorlist
##
## Primary
## msys2.org
Server = http://repo.msys2.org/msys/$arch/
Server = https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/$arch/
Server = http://www2.futureware.at/~nickoe/msys2-mirror/msys/$arch/
Server = https://mirror.yandex.ru/mirrors/msys2/msys/$arch/
```

**Comment by DileSoft** [comment]
https://github.com/stalkerg/setup-msys2/
https://github.com/stalkerg/setup-msys2/releases/tag/v2

setup-msys based on mirrow

**Comment by randyfan** [comment]
How do we run the following lines without repo.msys2.org?


  - C:\msys64\usr\bin\bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - C:\msys64\usr\bin\bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - C:\msys64\usr\bin\bash -lc "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - C:\msys64\usr\bin\bash -lc "pacman -U --noconfirm msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"

**Comment by nu8** [comment]
@randyfan as said before, you need to use a mirror. For example:

https://mirror.selfnet.de/msys2/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz

other mirrors here:

https://github.com/msys2/MSYS2-packages/tree/master/pacman-mirrors

**Comment by 1480c1** [comment]
http://mirror.yandex.ru/mirrors/msys2/

```bash
C:\msys64\usr\bin\bash -lc "curl -O http://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
C:\msys64\usr\bin\bash -lc "curl -O http://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
C:\msys64\usr\bin\bash -lc "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
C:\msys64\usr\bin\bash -lc "pacman -U --noconfirm msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
```
just replace it with a mirror

**Comment by lazka** [comment]
It's back up now. Sorry everyone.

(If anyone is willing to sponsor a better server please get in contact with us)

**Comment by jakubgs** [comment]
Some files still appear to be missing:
```
The remote server returned an error: (404) Not Found.
URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libtasn1-4.9-1-any.pkg.tar.xz is not valid
```

**Comment by lazka** [comment]
We've had to remove all files older than 1 year that are not in the pacman repo to save space for the new server.

I still have the old files locally, so I could provide them if needed.
