### ISSUE TITLE
[gflags] cmake auto link to shlwapi.lib

### ISSUE THREAD

**Issue by chenyv** [msys2/MINGW-packages#7086]
I use cmake to import gflags package, the generated makefile auto link to shlwapi.lib. But msys2 only has shlwapi.h , ld not found shlwapi.lib, so ld is failed.

CMakeLists.txt:

```cmake
set(gflags_DIR /mingw64/lib/cmake/gflags)

find_package(gflags COMPONENTS static)
include_directories(${GFLAGS_INCLUDE_DIRS})
target_link_libraries(${GFLAGS_LIBRARIES})
```

Compile Log:

```
/usr/bin/c++.exe   -Wl,--enable-auto-import CMakeFiles/demo.dir/demo.cpp.o  -o demo.exe -Wl,--out-implib,libdemo.dll.a -Wl,--major-image-version,0,--minor-image-version,0  /mingw64/lib/libgflags_static.a -lpthread **-lshlwapi.lib**
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: 找不到 -lshlwapi.lib
collect2: 错误：ld 返回 1
```

**Comment by Biswa96** [comment]
The correct linking option should be `-lshlwapi`. The `.lib` extension is for MSVC.

**Comment by Biswa96** [comment]
Hi @chenyv I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/1673058972
