### ISSUE TITLE
Contribution guidelines for maintainability

### ISSUE THREAD

**Issue by oscarfv** [msys2/MINGW-packages#7087]
Over the course of the years the lack of clear commit messages and code comments on PKBUILDs and other files has been problematic.

Not knowing the rationale of a change, why a patch was introduced or having changes randomly committed on apparently unrelated commits is a maintainability nightmare.

I suggest we adopt some rules for improving this situation.

For instance: commits must adapt to certain format: name of package (sans the `mingw-w64-` prefix) followed by a short description ("update to version X.XX", "introduce fix for upstream bug#XXX", etc). If the above is not clear enough, blank line followed by more details.

The commits of each PR should be sanitized (no personal scratch branches carelessly dumped as a PR, each commit must be conceptually atomic, etc).

Unless it is super-clear from the name of the patch or the patch itself what it does and why it is required, comments should appear on the PKGBUILD explaining that, along with references to relevant bug numbers, discussions, upstream pull requests, etc. Comments on the patches themselves are encouraged. Keeping up to date info about upstream bug# and discussions is encouraged (although on those cases it is not required to bump the pkgrel).

In general, the contributor should take some minutes to follow those simple rules and save hours of future work to others.

The contributions to this project always had too much "fire and forget" PRs, but it is my impression that things are turning for the worse lately. Sometimes it is hard to make heads or tails of the git history. This style welcomes sub-par contributions while turning away long-term contributors.

If the maintainers are okay with this, I can submit a patch against the documentation. But please note that this only make sense if enforced.

**Comment by jeremyd2019** [comment]
This is pretty much also what I try to do in general, except:
> Keeping up to date info about upstream bug# and discussions is encouraged (although on those cases it is not required to bump the pkgrel).

I don't agree with keeping this info in the PKGBUILD, if that's what you are suggesting.  I would put a link to a 'local' MSYS2-packages/MINGW-packages bug in the PKGBUILD and then keep that up to date with such things, rather than thrashing the PKGBUILD for that.  An interested party could follow the link for the full details.

**Comment by oscarfv** [comment]
> This is pretty much also what I try to do in general, except:
> 
> > Keeping up to date info about upstream bug# and discussions is encouraged (although on those cases it is not required to bump the pkgrel).
> 
> I don't agree with keeping this info in the PKGBUILD, if that's what you are suggesting. I would put a link to a 'local' MSYS2-packages/MINGW-packages bug in the PKGBUILD and then keep that up to date with such things, rather than thrashing the PKGBUILD for that. An interested party could follow the link for the full details.

What you suggest would require probably hundreds of bug of active reports on our repo. I agree that thrashing PKGBUILDs is not a good idea, though. If at the moment the patch is introduced there exists an upstream bug#, mention it. If not, edit the PKGBUILD when it appears, no need to add anything about how the upstream bug# or discussion goes. (But, ideally, a bug should be submitted upstream when we create a patch; I know that it is not always adequate, though).
