### ISSUE TITLE
Can MSYS2 be used with Clion?

### ISSUE THREAD

**Issue by WuZhengqiang666** [msys2/MINGW-packages#7094]
亲亲，MSYS2可以和Clion一起使用吗？
如果可以，如何设置呢？谢谢！
![图片](https://user-images.githubusercontent.com/49598775/95463419-4ebd0480-09ab-11eb-8b87-d21e56717314.jpg)

**Comment by lazka** [comment]
> 亲亲，MSYS2可以和Clion一起使用吗？
> 如果可以，如何设置呢？谢谢！

>Pro-tip, can MSYS2 be used with Clion?
>If so, how do you set it up? Thank you!

**Comment by Biswa96** [comment]
https://stackoverflow.com/questions/36375081/

**Comment by WuZhengqiang666** [comment]
感谢你们，完美的解决了我的问题。
再次向你们表示真挚的感谢！

This is Google Translate
Thank you, it solved my problem perfectly.
Thanks again to you!
