### ISSUE TITLE
GCC 7.4.0 removed

### ISSUE THREAD

**Issue by mcallegari** [msys2/MINGW-packages#7099]
Hi, since a couple of days, the GCC 7.4.0 package is no longer available.
http://repo.msys2.org/mingw/i686/mingw-w64-i686-gcc-libs-7.4.0-1-any.pkg.tar.xz
Unfortunately I rely on it to build a Qt software on top of Qt 5.6 which is the latest LTS version supporting Windows XP.

Can you please restore the GCC 7.4.0 packages?
Thanks

**Comment by Biswa96** [comment]
What's the problem with GCC 10? Windows XP in 2020?

**Comment by mcallegari** [comment]
Older Qt versions fail miserably to build with modern GCC versions.
As I said, I need Qt 5.6 for some more time.

Windows XP in 2020? Yes, for many people with old hardware it's still an option.

**Comment by adrpo** [comment]
Seems to be a gcc-7.2 on this msys2 mirror:
http://mirror.yandex.ru/mirrors/msys2/mingw/x86_64/
maybe you can use that?
