### ISSUE TITLE
lensfun 0.3.95 is broken

### ISSUE THREAD

**Issue by phrrk** [msys2/MINGW-packages#7108]
Version 0.3.95 of lensfun was only an alpha release and was soon shown to be seriously broken.  The relevant changes have been made in the git master for lensfun, but there have been no new releases.  As can be seen in
https://repology.org/project/lensfun/packages very few distributions offer this version and instead offer the earlier stable version 0.3.2.  This package is extensively used in raw photo development applications like darktable and they have got around this problem by reverting to 0.3.2, which used to be available from http://repo.msys2.org/mingw/x86_64/  This old package has now been removed and so there is a problem for anyone starting with a clean MSYS2 installation.  Is it possible to have the old 0.3.2 package reinstated into the repository?  Although a better solution might be to replace the current 0.3.95 package with this older one as the current current package is of no use to anyone.

**Comment by sfhacker** [comment]
We are not familiar with lensfun project!
We have just built versions 0.3.2 & 0.3.95 from source on Windows 10 x64 with no issues at all.

![image](https://user-images.githubusercontent.com/25817529/95690623-d2554a80-0c64-11eb-90eb-caafd56f7fc3.png)

Let us know if you require further assistance.

**Comment by lazka** [comment]
@phrrk Would updating to current git master also be an option?

**Comment by phrrk** [comment]
@lazka as far as I can see there is little lensfun development going on at the moment and I have no idea what the current status is.   Existing applications that use lensfun, e.g. darktable and RawTherapee all use version 0.3.2 which is the version offered by major linux distributions and macOS.    Significant changes were made to the way lensfun works since the 0.3.2 so it is not clear the the git master version is compatible with the applications that use it. Therefore making the 0.3.2 package available again is really essential.

**Comment by phrrk** [comment]
@sfhacker #6525 describes the issue.  It is lensfun 0.3.95 itself that is broken (it was only an alpha release) not specifically the mingw package.  This is why linux distributions offer 0.3.2 as the latest version.

**Comment by Alexpux** [comment]
@lazka @elieux lets revert lensfun to 0.3.2

**Comment by lazka** [comment]
Sounds good to me. Here are the lensfun-0.3.2-4 packages from my backup:

[lensfun-0.3.2-4.zip](https://github.com/msys2/MINGW-packages/files/5365977/lensfun-0.3.2-4.zip)

**Comment by kmilos** [comment]
Latest lensfun-0.3.2-5 doesn't seem to ship the necessary python modules...

**Comment by lazka** [comment]
Some quick test show that DESTDIR here is empty, but shouldn't be: https://github.com/msys2/MINGW-packages/blob/bdd6c4f40622e1ab8d4a77919b88881fe8154df5/mingw-w64-lensfun/cmake-mingw.patch#L52

**Comment by phrrk** [comment]
Ok I have tried to build the package locally (my first attempt at building an MSYS2 package so I cannot provide much insight).  I can confirm that the package I built also has none of the python modules included.  However the log file seems to suggest that they are there as shown in the snippet from the end of it below:

running install
running build
running build_py
creating build
creating build/lib
creating build/lib/lensfun
copying C:/msys64/home/jim/mingw-w64-lensfun/src/build-x86_64-w64-mingw32/apps/lensfun/__init__.py -> build/lib/lensfun
running install_lib
creating mingw64
creating mingw64/lib
creating mingw64/lib/python3.8
creating mingw64/lib/python3.8/site-packages
creating mingw64/lib/python3.8/site-packages/lensfun
copying build/lib/lensfun/__init__.py -> mingw64/lib/python3.8/site-packages/lensfun
byte-compiling mingw64/lib/python3.8/site-packages/lensfun/__init__.py to __init__.cpython-38.pyc
running install_egg_info
Writing mingw64/lib/python3.8/site-packages/lensfun-0.3.2-py3.8.egg-info 

However looking  in ......./pkg/mingw-w64-x86_64-lensfun/mingw64/lib, which I believe is where the python3.8 directory should be, it is not to be found.  Instead I found it  below the .../src directory

jim@Jim-PC MINGW64 ~/mingw-w64-lensfun/src/build-x86_64-w64-mingw32/mingw64/lib/python3.8/site-packages
$ ls
lensfun  lensfun-0.3.2-py3.8.egg-info

As I said this is my first attempt at a package build so I could be totally off track, but it looks to me like the python files are written to the wrong place and hence do not get included in the package when it is created.  Checking on the old copy of  lensfun-0.3.2-4 the files are dated  04/09/2017.  One change since then is that python has gone from 3.6 to 3.8 and maybe there have been other relevant changes.

**Comment by phrrk** [comment]
Further to my comments above I have made some progress.  Changing the last but one line of cmake-mingw.patch to

`+    INSTALL(CODE "execute_process(COMMAND ${PYTHON} ${SETUP_PY} install --prefix=\$ENV{DESTDIR}${SETUP_PY_INSTALL_PREFIX})")`

solves the problem of getting the python files installed in the correct place and included in the package file.  The only possible issue is that there are 2 packaging warnings

```
==> Checking for packaging issues...
==> WARNING: Package contains reference to $srcdir
mingw64/bin/liblensfun.dll
==> WARNING: Package contains reference to $pkgdir
mingw64/lib/python3.8/site-packages/lensfun/__pycache__/__init__.cpython-38.pyc
==> Creating package "mingw-w64-x86_64-lensfun"...

```
I don't know whether these warnings are significant, but the first of them was there anyway before my edit and the second would not have been because the python stuff was not in the package anyway.

**Comment by lazka** [comment]
Does `INSTALL(CODE "execute_process(COMMAND ${PYTHON} ${SETUP_PY} install --prefix=${SETUP_PY_INSTALL_PREFIX} --root=\$ENV{DESTDIR})")` also work maybe?

**Comment by phrrk** [comment]
Yes that seems to work too and now I only get the one warning message
```
==> Checking for packaging issues...
==> WARNING: Package contains reference to $srcdir
mingw64/bin/liblensfun.dll
```

**Comment by kmilos** [comment]
FWIW, I'm seeing the same warning on another package, the path of the source directory indeed ends up somehow in binary objects (both shared and static) as plain text...

**Comment by Biswa96** [comment]
That sometimes happen if `__FILE__` is used in a specific (maybe wrong) way in source code. Try to grep recursively the `pkg` folder after creating the package. If the source directory path is not used in actual functions then the warning may be safely ignored.

**Comment by phrrk** [comment]
Having found the reference to $srcdir in the offending dll it just appears amongst some other text which looks like error messages.  I doubt very much that functionality is affected.

**Comment by kmilos** [comment]
Same here, they all seem to be `XMP_Enforce failed` errors in my case...

**Comment by lazka** [comment]
Thanks, see #7128

**Comment by lazka** [comment]
This should be fixed now. Can anyone confirm?

**Comment by kmilos** [comment]
Python module is indeed now there and I could execute `lensfun-update-data`, but I'll leave it to the OP to close the issue.

**Comment by phrrk** [comment]
Yes works for me thanks. Sorry forgot to close.
