### ISSUE TITLE
Python REPL does not behave correctly

### ISSUE THREAD

**Issue by fauxpark** [msys2/MINGW-packages#7111]
When running the Python REPL, using the arrow keys causes the cursor to move around the entire terminal, rather than being constrained to the current line. This also prevents you from accessing the history, for example:

1. Run `python3`
2. Type `print("Hello world!")`
3. Hit the up arrow key

the previously entered line of code (`print("Hello world")`) should have appeared in the prompt, but instead the cursor simply moves up:
![image](https://user-images.githubusercontent.com/4781841/95728344-242ebc80-0cc7-11eb-9eea-a15dc3fc7c99.png)

Oddly, it works perfectly fine within a Windows Terminal session, and the MSYS Python also has no problems. So I'm not sure if the issue lies in Python or mintty.

**Comment by noroadsleft** [comment]
Context: @fauxpark is a friend and colleague who's been helping me investigate this issue.

I note that I only have this issue in MinGW x64 – MSYS and MinGW x32 terminals are unaffected:

![image](https://user-images.githubusercontent.com/18669334/95731211-111edc80-0c34-11eb-9eb2-46c6ddcb9e8d.png)

Also, MinGW x64 is the only terminal with Python 3.8.6. If I run Python 3.8.5 in MinGW x64, I don't have this issue.

**Comment by Alexpux** [comment]
@noroadsleft on your screens you use MSYS python under Mingw 32-bit shell, not Mingw Python

**Comment by noroadsleft** [comment]
@Alexpux I just realized that, and was editing my previous post when you replied.

I do experience the issue in MinGW x32, even if the Python version is 3.8.5:

![image](https://user-images.githubusercontent.com/18669334/95733258-b5098780-0c36-11eb-9db6-3909fbee6a07.png)

**Comment by mati865** [comment]
MinGW Python expects Windows terminal. It works fine when you run `winpty python`.

**Comment by noroadsleft** [comment]
Ah, that's a problem – I'm on Windows 8.1, and Windows Terminal isn't available.

**Comment by mati865** [comment]
@noroadsleft CMD and PowerShell are available.

**Comment by fauxpark** [comment]
I'm still kind of unclear whether this is an actual bug (and if so, where), or whether winpty is the intended "workaround" for this behaviour.

**Comment by ed-tsoy** [comment]
I have the same issue in MinGW-64:
![изображение](https://user-images.githubusercontent.com/65108387/107738700-0a5ebe00-6d29-11eb-83ad-312eef794aa9.png)

In MinGW-32 and MSYS, the python shell behaves correctly. I have Windows 8.1, I installed a recent (yesterday) version of MSYS2.

**Comment by 0dminnimda** [comment]
Got this problem, what should the fix look like?

**Comment by 0dminnimda** [comment]
Found a semi-fix for this: install and use Python3.13 it got new improved REPL and it works in msys consoles. For older versions just use Git for Windows shell.
(And how cool is it, that it uses precompiled python bytecode!)

**Comment by 0dminnimda** [comment]
I see, I was using the official build from python.org
