### ISSUE TITLE
Setting G_SLICE env variable to any non-empty value freezes GLib programs

### ISSUE THREAD

**Issue by khaledhosny** [msys2/MINGW-packages#7118]
While debugging https://github.com/harfbuzz/harfbuzz/issues/2697, I found that any non-empty value of this env variable freezes GLib applications. E.g.

```
#include <glib.h>
int main(int argc, char** argv) {
  g_print("Test\n");
}
```

Building with `gcc test.c -o test $(pkg-config --cflags --libs glib-2.0)`. Runnig without the env variable set is fine, setting it to even just `G_SLICE=' '` will cause the program to just freeze (nothing is printed and not returning either).

**Comment by lazka** [comment]
Thanks! I was seeing the same thing with pygobject but didn't investigate yet.

**Comment by lazka** [comment]
I can confirm that downgrading glib to 2.64.5 fixes things.

**Comment by lazka** [comment]
Bisected and filed an issue in glib: https://gitlab.gnome.org/GNOME/glib/-/issues/2225

**Comment by khaledhosny** [comment]
Thanks, I did suspect it is this commit but didn’t mange to build glib and verify.

**Comment by lazka** [comment]
the fix is in the repo now

**Comment by khaledhosny** [comment]
I confirm that HarfBuzz CI builds are fixed now. Thanks again for the quick fix.

**Comment by lazka** [comment]
Thanks for figuring out the cause!
