### ISSUE TITLE
[arm-none-eabi-gcc] execution fails without "mingw-w64-x86_64-libwinpthread-git"

### ISSUE THREAD

**Issue by fetiu** [msys2/MINGW-packages#7122]
![image](https://user-images.githubusercontent.com/19373731/96107474-6b12f100-0f17-11eb-85a7-f961c14e1d97.png)

Hi, I am trying to use `arm-none-eabi-gcc` on MSYS2, but installing only `mingw-w64-x86_64-arm-none-eabi-gcc` always make the execution fail. Only way to resolve this is seem to be installing `mingw-w64-x86_64-libwinpthread-git` additionally.

Can we add this package as a dependency?

**Comment by MehdiChinoune** [comment]
libwinpthread-git is now a dependency of arm-none-eabi-gcc package
