### ISSUE TITLE
[mpfr][gmp][gcc] gcc no longer works

### ISSUE THREAD

**Issue by DanFulger** [msys2/MINGW-packages#7124]
It's generating 32-bit relative calls for libgmp.dll, and if it's more than 4 GB away in virtual space the program crashes.

**Comment by DanFulger** [comment]
I tested the latest version.

**Comment by DanFulger** [comment]
It's not that, gmp.h is broken, it does not define ___GMP_LIBGMP_DLL. I just updated gmp, and now gcc is broken.

**Comment by DanFulger** [comment]
Sorry, I just updated and it works.

**Comment by jeremyd2019** [comment]
#6983.  Glad it's not broken again/still 😬
