### ISSUE TITLE
i686 Glib2 package trying to install files under /usr

### ISSUE THREAD

**Issue by BrisingrAerowing** [msys2/MINGW-packages#7132]
```text
error: failed to commit transaction (conflicting files)
mingw-w64-i686-glib2: /usr/share/libalpm/hooks/mingw-w64-i686-gio-querymodules.hook exists in filesystem
mingw-w64-i686-glib2: /usr/share/libalpm/hooks/mingw-w64-i686-glib-compile-schemas.hook exists in filesystem
Errors occurred, no packages were upgraded.
```

That pops up when installing the mingw-w64-i686-glib2 package. I would presume those are supposed to be under /mingw32.

**Comment by lazka** [comment]
those are pacman hooks so thats one purpose. no idea why the files are there in your case, hm..

**Comment by BrisingrAerowing** [comment]
Ah. I had to delete the previous installs I had manually due to something corrupting them, so I ended up missing those files.

**Comment by Biswa96** [comment]
Alternatively, if you do not want to remove a installed package you could use `--overwrite` option with `pacman -S` command. Read more in [pacman wiki][1].

[1]: https://wiki.archlinux.org/index.php/pacman#%22Failed_to_commit_transaction_(conflicting_files)%22_error

**Comment by lazka** [comment]
ok. as for the reason why: we could have also added hook directories for mingw32/64 and add the to the pacman config, but I wanted to keep things simple and now hooks are prefixed with "mingw-w64-i686-" etc.
