### ISSUE TITLE
pango update-request

### ISSUE THREAD

**Issue by txe** [msys2/MINGW-packages#7172]
Hello, 
Can pango package be updated up to 1.47.0 version?

The reason for the request is a recent [fix in pango](https://gitlab.gnome.org/GNOME/pango/-/merge_requests/217) to support fallback fonts on Win32. This feature is waited by users of [cherrytree  app](https://github.com/giuspen/cherrytree) and allows to avoid situations when fancy fonts cannot properly show some unicode symbols. I think other apps also can find this useful.

**Comment by lazka** [comment]
I guess you mean pango, no cairo? pango 1.47 isn't a stable release, so we wont update, but we can look into backporting this patch.

**Comment by txe** [comment]
Oh, you are right, thanks. 
Then what about 1.46.2? I just check its sources, it contains the fix. Or you can backport, the fix is really simple.

**Comment by txe** [comment]
OMG, it's already in msys2. I need to sleep more, sorry for bothering)

**Comment by lazka** [comment]
hehe, no problem
