### ISSUE TITLE
cmake -G 'NMake Makefiles' no longer works

### ISSUE THREAD

**Issue by bradbell** [msys2/MINGW-packages#7175]
If you specify `-G 'NMake Makefiles' on the cmake command line, you get  a message listing the possible generators and 'NMake Makefiles' is not in the list, but it should be; see
https://cmake.org/cmake/help/v3.0/generator/NMake%20Makefiles.html

This used to work on msys2, but I forget which version I was using then.
The version of cmake  that is not working and was installed by pacman is 3.17.3.

**Comment by lazka** [comment]
You are likely using the wrong cmake, install the native one: `pacman -S mingw-w64-x86_64-cmake`

**Comment by bradbell** [comment]
I tried uninstalling the old camke and then ``pacman -S mingw-w64-x86_64-cmake``. After the install ``which cmake`` cannot find the executable ?

**Comment by Alexpux** [comment]
@bradbell you need run /mingw64/bin/cmake

**Comment by bradbell** [comment]
That works. Thanks.
