### ISSUE TITLE
Reduce Clang package size? 

### ISSUE THREAD

**Issue by adrpo** [msys2/MINGW-packages#7190]
Any reason we don't configure Clang package with dynamic linking to reduce its size?
I remember we had issues with lld but that one is now linked with Clang stdlib so it should not matter anymore.

Any feedback before I start looking into this again?

**Comment by lazka** [comment]
we had to revert that again afaik: #7185

**Comment by mati865** [comment]
We cannot use libc++ https://github.com/msys2/MINGW-packages/issues/7170

**Comment by mati865** [comment]
One thing we could do is splitting PKGBUILD into separate packages and use `{make,ninja} install-distribution` as recommended by the upstream. This will not install binaries that are used only for building LLVM.

**Comment by adrpo** [comment]
Ok. Thanks for the heads up!
I'll see what I can do about the size. Splitting it up might be good as we could compile just lld statically to resolve the error and all the other stuff with dynamic linking.

**Comment by mati865** [comment]
> Splitting it up might be good as we could compile just lld statically to resolve the error and all the other stuff with dynamic linking.

LLD is not the issue here, it just makes the issue more visible.

**Comment by adrpo** [comment]
Seems we get ~3GB shaved off with the new clang.
```
pacman -Su 
Total Download Size:     413.04 MiB
Total Installed Size:   2489.19 MiB
Net Upgrade Size:      -3344.40 MiB
```
