### ISSUE TITLE
Inkscape not finding wanted version of libpoppler

### ISSUE THREAD

**Issue by SlySven** [msys2/MINGW-packages#7191]
The current version of the 64 bit version of this package `0.92.5-3` (I expect the 32 bit one is the same but I haven't checked) seems to want to load `libpoppler-99.dll` from the `poppler` package - which is currently at `20.10.0-1` however the latter actually provides `libpoppler-103.dll` and that doesn't seem to match what `inkscape` wants so it aborts with a:
```shh
$ inkscape
C:/msys64/mingw64/bin/inkscape.exe: error while loading shared libraries: libinkscape_base.dll: cannot open shared object file: No such file or directory
```
I tried the \*nix trick of:
```ssh
$ ln -s -i /mingw64/bin/libpoppler-103.dll /mingw64/bin/libpoppler-99.dll
```
and (by making a copy of the new library as the older one's name) that seems to allow `inkscape` to work again but I guess that something somewhere needs a revision to fix this properly..,

**Comment by Biswa96** [comment]
Inkscape was not updated since months.

**Comment by lazka** [comment]
I just rebuilt it for unrelated reasons, so will be fixed shortly.

**Comment by Biswa96** [comment]
If you add any patch please upstream those changes.

**Comment by lazka** [comment]
I'm just working on moving packages to use pacman install hooks instead of scripts.

**Comment by Alexpux** [comment]
@SlySven inkscape updated to 1.0.1, will be in repo in next update

**Comment by llongi** [comment]
@Alexpux are you sure? Still not seeing it, and according to:
https://github.com/msys2/MINGW-packages/runs/1321285159
there seems to be some CI failure with the latest inkscape that's preventing build+upload?
Thanks for any status update, as this is blocking our Windows CI pipeline.

**Comment by Alexpux** [comment]
@llongi this issue will be solved soon, it builds ok on my local machine

**Comment by kerwinxu** [comment]
i had a same problem .  it said no _ZN5boost10filesystem4pathVERKS1 in mingw64\bin\libinkscape_base.dll . 
i load libinkscape_base.dll in stud_PE.exe and _ZN5boost10filesystem4pathVERKS1  not in export function .
