### ISSUE TITLE
thank you if you answered my question

### ISSUE THREAD

**Issue by abcdef123ghi** [msys2/MINGW-packages#7193]
I'm pretty new to the MinGW and Cygwin as well and I have installed mingw-w64-x86_64-xlnt-1.5.0-1 with pacman which was command 'pacman -S mingw-w64-x86_64-xlnt' and there're include folder which is  '\mingw64\include\xlnt' and static library as well which is libxlnt.a on folder '\mingw64\lib' 
my question is can I use this static library which is libxlnt.a on VC++?is it different format with standard Windows static library file which is the lib file?thank you so much

**Comment by mati865** [comment]
> my question is can I use this static library which is libxlnt.a on VC++?is it different format with standard Windows static library file which is the lib file?thank you so much

MinGW static libraries differ from MSVC static libraries a lot. I think the only way to combine them is through DLL that doesn't have any C++ code inside.

**Comment by abcdef123ghi** [comment]
Ok cool,ty

**Comment by oscarfv** [comment]
Please close this issue if your question is answered.

**Comment by abcdef123ghi** [comment]
> Please close this issue if your question is answered.

sorry for I was late for closing this post,cuz I was using github apps on my phone which has no functionality for close issue,sorry for inconvenient
