### ISSUE TITLE
cannot build binutils/gdb - readline issues

### ISSUE THREAD

**Issue by askondro** [msys2/MINGW-packages#7194]
make  all-am
make[3]: Entering directory '/home/askon/binutils-gdb/build/gdbsupport'
make[3]: Leaving directory '/home/askon/binutils-gdb/build/gdbsupport'
make[2]: Leaving directory '/home/askon/binutils-gdb/build/gdbsupport'
make[2]: Entering directory '/home/askon/binutils-gdb/build/sim'
make[2]: Leaving directory '/home/askon/binutils-gdb/build/sim'
make[2]: Entering directory '/home/askon/binutils-gdb/build/gdbserver'
make[2]: Leaving directory '/home/askon/binutils-gdb/build/gdbserver'
make[2]: Entering directory '/home/askon/binutils-gdb/build/gdb'
  CXXLD  gdb.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib/libncursesw.a(lib_termcap.o):(.bss+0x8): multiple definition of `UP'; ../readline/readline/libreadline.a(terminal.o):C:/msys64/mingw64/include/termcap.h:35: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib/libncursesw.a(lib_termcap.o):(.bss+0x0): multiple definition of `BC'; ../readline/readline/libreadline.a(terminal.o):C:/msys64/mingw64/include/termcap.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib/libncursesw.a(lib_tputs.o):(.bss+0x6): multiple definition of `PC'; ../readline/readline/libreadline.a(terminal.o):C:/msys64/mingw64/include/termcap.h:29: first defined here
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:1871: gdb.exe] Error 1
make[2]: Leaving directory '/home/askon/binutils-gdb/build/gdb'
make[1]: *** [Makefile:11706: all-gdb] Error 2
make[1]: Leaving directory '/home/askon/binutils-gdb/build'
make: *** [Makefile:866: all] Error 2

**Comment by lazka** [comment]
Try with `CFLAGS+=" -fcommon"`

**Comment by askondro** [comment]
Thanks. Works now!
