### ISSUE TITLE
package 'libvirt' needs package 'yajl', but pacman doesnot install it by auto.

### ISSUE THREAD

**Issue by huiminghao** [msys2/MINGW-packages#7197]
package 'libvirt' needs package 'yajl', but pacman doesnot install it by auto.

```
Pacman v5.2.2 - libalpm v12.0.2
SyncDate 2020/10/29
Env: MinGW64(msys2)
```

**Comment by sateffen** [comment]
This issue was fixes by [this commit](https://github.com/msys2/MINGW-packages/commit/83520bb98036d42b1a332f8113499800dca916c5), see [here](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libvirt/PKGBUILD#L24).

I guess this issue can get closed?
