### ISSUE TITLE
[gdal] Not able to run any gdal library dependent application

### ISSUE THREAD

**Issue by bialasjaroslaw** [msys2/MINGW-packages#7200]
In current version running any executable from package results in error
`gdb --args gdalinfo.exe --help`
results in
`During startup program exited with code 0xc0000139.`

I tried with fresh install but result is exactly the same (there are also missing runtime dependencies mingw-w64-i686-ilmbase mingw-w64-i686-openexr)

I decided to build it in this fresh environment exactly as it is adviced with one exception - that is, I needed 32bit version of a library
`MINGW_INSTALLS=mingw32 makepkg-mingw -sLf`

After coupleish minutes I found out that there is an issue with building current version of GDAL as there were a compilation error:
https://github.com/OSGeo/gdal/issues/3012

After applying a patch I ended up with undefined reference problem which I am not able to easily fix on my own

> C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: frmts\\o\\.libs\\jpeg2000dataset.o:jpeg2000dataset.cpp:(.text+0x9ea): undefined reference to `jp2_box_destroy'
> C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: frmts\\o\\.libs\\jpeg2000dataset.o:jpeg2000dataset.cpp:(.text+0x9f8): undefined reference to `jp2_box_get'

Only way I found out is to add `--with-jasper=no` to configuration.

I will gladly prepare PR with permanent fix, but I don't know if linking stage is fixable or if it will be better to disable problematic library.

**Comment by Alexpux** [comment]
@bialasjaroslaw fixed by https://github.com/msys2/MINGW-packages/commit/cf038bfa07ed73f0fe8afe72c04a20d17c00f054

**Comment by Alexpux** [comment]
@bialasjaroslaw but now there are issue with building with new qhull

**Comment by bialasjaroslaw** [comment]
@Alexpux I just build gdal (version 3.1.3) with this applied to buildtree:
https://github.com/OSGeo/gdal/commit/9ef8e16e27c5fc4c491debe50bf2b7f3e94ed334

I have mingw-w64-i686-qhull-git r166.f1f8b42-1

**Comment by Alexpux** [comment]
@bialasjaroslaw to build with new qhull you need replace in configure ````qhull```` library to ````qhull_r```` in other case it not find qhull and use internal

**Comment by Alexpux** [comment]
@bialasjaroslaw see https://github.com/msys2/MINGW-packages/commit/1c9c7b4efc0f29150bd2dc4202733d225a691cb5

**Comment by bialasjaroslaw** [comment]
It might be related to the fact that in `delaunay.c` there are still includes to the old version of qhull but we are linking to new one. After changing to new headers it seems that rest of the gdal code will break apart, so the only way of solving that is either stick with old version and wait until gdal developers will migrate their code or prepare path to migrate old code.

**Comment by Alexpux** [comment]
@bialasjaroslaw ok lets build with internal qhull
https://github.com/msys2/MINGW-packages/commit/7e30736723fe6c0d89765382d5d093c277442cff
