### ISSUE TITLE
Can't compile sed4.8 on msys2/mingw64 Windows

### ISSUE THREAD

**Issue by stockchess** [msys2/MINGW-packages#7211]
Trying to compile sed4.8 from https://git.savannah.gnu.org/cgit/sed.git/ doesn't work and gives errors like 
```
undefined reference to `__chk_fail
undefined reference to `__strcpy_chk
undefined reference to `__memcpy_chk
undefined reference to `__memmove_chk
```

Commands used:
```
./configure --disable-nls --host=x86_64-w64-mingw32
make
```

Any way to fix this thx.

**Comment by lazka** [comment]
`LDFLAGS+=" -fstack-protector"`

**Comment by stockchess** [comment]
@lazka It doesnt work for me and gives same errors. What series of commands did you use to get it to compile thx.

**Comment by sfhacker** [comment]
It builds fine on my old laptop!

![image](https://user-images.githubusercontent.com/25817529/97802036-e48b3d00-1c94-11eb-85ac-a565fb39a523.png)

Perhaps your environment is broken somehow!

**Comment by stockchess** [comment]
@sfhacker This is strange. Did you use my two commands or something else, thx.

**Comment by sfhacker** [comment]
./configure --disable-rpath --disable-nls
make
make install

It is odd it does not work on your environment. It must be 'polluted' or broken or both!

**Comment by stockchess** [comment]
@sfhacker Still get same error. Looks like I have a broken system. Will reinstall and try again. Thx four your help.

**Comment by stockchess** [comment]
@sfhacker Did a reinstall and still get same error. I'm stumped.

**Comment by sfhacker** [comment]
@stockchess How much experience do you have building projects from source on Windows?
GNU sed is a small project and quite straight forward to build. It took me a couple of mins to build it from source on an old laptop!
Do not know what to suggest? Can you seek advice from your fellow students or colleagues?
How good are you at troubleshooting? Can you search for those 'esoteric' undefined references in the codebase?

**Comment by stockchess** [comment]
@sfhacker I'm not experienced but managed to build some software on msys2. sed is the only one that doesn't compile. I will leave it for now and thx for your advice.

**Comment by sfhacker** [comment]
@stockchess Can you post here a screenshot(s) showing your environment version and configuration?

**Comment by stockchess** [comment]
@sfhacker What commands do you want me to run.

**Comment by stockchess** [comment]
Manually editing the makefile and changing the line  `LDFLAGS = ` to `LDFLAGS = -fstack-protector -static` makes it work. Thx @sfhacker and @lazka for helping me.
