### ISSUE TITLE
Name conflict mtest; parmetis and tfel

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#7220]
They both have a mtest.exe file to install:

`/mingw64/bin/mtest.exe`

If i add to tfel PKGBUILD: 
`-DTFEL_APPEND_VERSION=ON \`

then from:
```
/mingw64/bin/mfm-test-generator.exe
/mingw64/bin/mfm.exe
/mingw64/bin/mfront-doc.exe
/mingw64/bin/mfront-query.exe
/mingw64/bin/mfront.exe
/mingw64/bin/mtest.exe
/mingw64/bin/tfel-config.exe
```

to:
```
/mingw64/bin/mfm-test-generator-3.3.0.exe
/mingw64/bin/mfm-3.3.0.exe
/mingw64/bin/mfront-doc-3.3.0.exe
/mingw64/bin/mfront-query-3.3.0.exe
/mingw64/bin/mfront-3.3.0.exe
/mingw64/bin/mtest-3.3.0.exe
/mingw64/bin/tfel-config-3.3.0.exe
```

I don't know if it's a good solution.

**Comment by lazka** [comment]
What does mtest do? Is it the same in all cases?

**Comment by 3rav** [comment]
"MTest is a tool created to perform unit-testings on the mechanical behaviours generated by
MFront."

**Comment by mati865** [comment]
> "MTest is a tool created to perform unit-testings on the mechanical behaviours generated by MFront."

Sounds like it shouldn't have been included at all?

**Comment by 3rav** [comment]
I haven't used this tool myself yet, but it is rather needed. It allows you to quickly test the created material (it is not a one-time test). For verification, it also allows you to create a graph showing the behavior of the material.

**Comment by revelator** [comment]
Btw this also is a problem after we got gprbuild as it contains a dll with the same name as the dll from the google rpc package. libgpr.dll :S

**Comment by lazka** [comment]
Since parmetis doesn't work here (it complains about a non-existing DLL) I just expanded its .exe namespacing here: #7412
