### ISSUE TITLE
Python produces broken venv

### ISSUE THREAD

**Issue by jtanx** [msys2/MINGW-packages#7227]
This does not work:

```
python3.8 -m venv ve
Error: [WinError 2] The system cannot find the file specified
```

It creates a partially setup venv that is missing setuptools and pip.

This works:

```
python -m venv ve
```

The former used to work, but a recent update to the python package broke this. (as to why python3.8 is executed and not python/python3, this is to do with version detection/cmake)

This package works:
mingw-w64-i686-python-3.8.6-3

This is broken (or maybe the pip package is broken?):
mingw-w64-i686-python-3.8.6-5

**Comment by lazka** [comment]
uh, thanks.
