### ISSUE TITLE
PaRSEC na number the releases (bitbucket)

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#7228]
Hi,

I want to add PaRSEC form: https://bitbucket.org/icldistcomp/parsec/src/master/
There are no released versions, only master versions, zip file are name icldistcomp-parsec-e3360fad5ecf.

I already have a working PKGBUILD file, but how to number the releases?

**Comment by Biswa96** [comment]
1. See mingw-w64-headers/crt/winpthreads as example.
2. Some repository has a script/command to get a version string which may be added in `pkgver()` function in PKGBUILD file.
3. Do not add `-git` in package name/base.
