### ISSUE TITLE
Openscad.exe: error while loading shared libraries: libzip.dll

### ISSUE THREAD

**Issue by helloliver** [msys2/MINGW-packages#7231]
What happened and how to fix it?
```
$ openscad.exe
C:/msys64/mingw64/bin/openscad.exe: error while loading shared libraries: libzip.dll: cannot open shared object file: No such file or directory
$ cd /mingw64/bin/
$ ls | grep libzip
libzip.dll
```

**Comment by Biswa96** [comment]
There is a pending pull request for opencascade package. /cc @3rav

**Comment by 3rav** [comment]
My pull request is for opencascade not openscad

**Comment by Biswa96** [comment]
😛

**Comment by lazka** [comment]
it needs to be rebuild because of cgal changes at least (cgal no longer provides a shared lib)

**Comment by umarcor** [comment]
OpenSCAD 2021.01 is working ok (#7906). I think this issue can be closed.
