### ISSUE TITLE
Gdiplus error while compiling

### ISSUE THREAD

**Issue by raedrizqie** [msys2/MINGW-packages#7234]
Hi,

I got this error while compiling using g++. I'm using GCC 10.2.0 Rev5.

In file included from c:/mingw64/1020-w64-msys2/x86_64-w64-mingw32/include/gdiplus/gdiplus.h:63,
                 from c:/mingw64/1020-w64-msys2/x86_64-w64-mingw32/include/gdiplus.h:1,
                 from ../include/atlimage.h:30,
                 from ../include/afxtoolbarimages.h:20,
                 from ../include/afxsmartdockingguide.h:13,
                 from ../include/afxsmartdockingmanager.h:13,
                 from ../include/afxdockingmanager.h:15,
                 from ../include/afxframeimpl.h:23,
                 from ../include/afxmdichildwndex.h:14,
                 from mfc/winmdi.cpp:12:
c:/mingw64/1020-w64-msys2/x86_64-w64-mingw32/include/gdiplus/gdiplusflat.h:103: internal compiler error: in linemap_compare_locations, at libcpp/line-map.c:1359
  103 | GpStatus WINGDIPAPI GdipSetEffectParameters(CGpEffect*,GDIPCONST VOID*,UINT);
      |
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/msys2/MINGW-packages/issues> for instructions.

**Comment by Biswa96** [comment]
What project are you compiling? If that project is private a simple, minimal code can be provided here which reproduces this issue exactly.

**Comment by raedrizqie** [comment]
I'm compiling atlmfc v100 (yeah, I know) :)

**Comment by Biswa96** [comment]
Link of the project please? AFAIK, ATL and MFC is MSVC thing.

**Comment by raedrizqie** [comment]
Yes.. I was just trying to port it to MinGW.. the last version that I know, that don't have this error is GCC 5.4+. Since GCC 6 and above (IIRC), all got this error when I tried to compile MFC dll.

If I change GDIPCONST VOID* to GDIPCONST **P**VOID*, g++ can continue without error.

**Comment by Biswa96** [comment]
But according to [MS Docs][1], it's `VOID*` type. The `internal compiler error` message seems suspicious to me. I shall ask [mingw-w64][2] devs.

[1]: https://docs.microsoft.com/en-us/windows/win32/gdiplus/-gdiplus-bitmap-flat
[2]: https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/
