### ISSUE TITLE
GCC Illegal Instruction at min() _GLIBCXX_USE_NOEXCEPT { return FLT_MIN; }

### ISSUE THREAD

**Issue by ocroquette** [msys2/MINGW-packages#7236]
## Describe the issue

When building any C++ program, the following internal error is thrown:

```GCC Illegal Instruction——internal compiler error: Illegal instruction```

```min() _GLIBCXX_USE_NOEXCEPT { return FLT_MIN; }```

This occurred when updating from "mingw-w64-x86_64-gmp-6.2.0-1-any.pkg.tar.xz" to "mingw-w64-x86_64-gmp-6.2.0-3-any.pkg.tar.zst".

Downgrading back solves the issue.

Another report from a different person with some additional analysis can be found at https://nebula-graph.io/posts/segmentation-fault-gcc-illegal-instruction-trouble-shooting/

Searching on the web for the error message uncovers more cases.

**Comment by mati865** [comment]
Illegal instruction error also happens when panicking inside panic.
Backtrace could help here.

**Comment by ocroquette** [comment]
I wanted to create the backtrace but I cannot reproduce the issue anymore.

**Comment by ocroquette** [comment]
I had the problem again today. It seems to happen when I mix artifacts from MinGW 10.1 and MinGW 10.2.
Is that worth investigating ?
