### ISSUE TITLE
mingw64/mingw-w64-x86_64-cmake does not support building project in mingw64 environment

### ISSUE THREAD

**Issue by yasuhirokimura** [msys2/MINGW-packages#7240]
It seems mingw64/mingw-w64-x86_64-cmake does not support building project in mingw64 environment.

I committed sample project to explain the problem to following repository.

https://github.com/yasuhirokimura/cmaketest.git

This is very small and simple project. It contains only one C source file and one C++ source file. It compiles cmaketest1.exe from main.c and cmaketest2.exe from main.cpp.

There is no os/platform/compiler/libraries dependency to this project. So it should be able to be built on any envrioenment that provides cmake, C comppiler and C++ compiler.

If I try to build this project on MSYS environment, it succeeds without any problems.

```
(MSYS)yasu@rolling[1319]% type cmake
cmake is /usr/bin/cmake
(MSYS)yasu@rolling[1320]% ls
build/  CMakeLists.txt  main.c  main.cpp
(MSYS)yasu@rolling[1321]% cd build  
(MSYS)yasu@rolling[1322]% cmake ..
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
CMake Warning at /usr/share/cmake-3.18.4/Modules/Platform/MSYS.cmake:15 (message):
  CMake no longer defines WIN32 on MSYS!

  (1) If you are just trying to build this project, ignore this warning or
  quiet it by setting CMAKE_LEGACY_CYGWIN_WIN32=0 in your environment or in
  the CMake cache.  If later configuration or build errors occur then this
  project may have been written under the assumption that MSYS is WIN32.  In
  that case, set CMAKE_LEGACY_CYGWIN_WIN32=1 instead.

  (2) If you are developing this project, add the line

    set(CMAKE_LEGACY_CYGWIN_WIN32 0) # Remove when CMake >= 2.8.4 is required

  at the top of your top-level CMakeLists.txt file or set the minimum
  required version of CMake to 2.8.4 or higher.  Then teach your project to
  build on Cygwin without WIN32.
Call Stack (most recent call first):
  /usr/share/cmake-3.18.4/Modules/CMakeSystemSpecificInformation.cmake:27 (include)
  CMakeLists.txt:1 (project)


-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /c/Users/yasu/Work/cmaketest/build
(MSYS)yasu@rolling[1323]% make
Scanning dependencies of target cmaketest2
[ 25%] Building CXX object CMakeFiles/cmaketest2.dir/main.cpp.o
[ 50%] Linking CXX executable cmaketest2.exe
[ 50%] Built target cmaketest2
Scanning dependencies of target cmaketest1
[ 75%] Building C object CMakeFiles/cmaketest1.dir/main.c.o
[100%] Linking C executable cmaketest1.exe
[100%] Built target cmaketest1
(MSYS)yasu@rolling[1324]% ./cmaketest1.exe
Hello, World.
(MSYS)yasu@rolling[1325]% ./cmaketest2.exe
Hello, World.
(MSYS)yasu@rolling[1326]% 
```

But if I try it on MINGW64 environment, it fails as following.

```
(MINGW64)yasu@rolling[1005]% type cmake
cmake is /mingw64/bin/cmake
(MINGW64)yasu@rolling[1006]% ls
build/  CMakeLists.txt  main.c  main.cpp
(MINGW64)yasu@rolling[1007]% cd build
(MINGW64)yasu@rolling[1008]% cmake ..
-- Building for: NMake Makefiles
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:1 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:1 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/Users/yasu/Work/cmaketest/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/yasu/Work/cmaketest/build/CMakeFiles/CMakeError.log".
(MINGW64)yasu@rolling[1009]%
```

According to the error messages, it seems cmake looking for tools that are included in Microsoft Visual C++.  And if so it means mingw64/mingw-w64-x86_64-cmake does not support building project with tools that are provided in MINGW64 environment.

**Comment by 1480c1** [comment]
For the first one, as you noted, you are using the wrong cmake, for the second one, I'm not sure if cmake has the special checks for registry keys for the paths for cl etc when using NMake, I think you might need to use one of the visual studio solution generators if you want to use cl.exe etc, else, you need to use either the Ninja, Unix Makefiles, or MSYS Makefiles

**Comment by yasuhirokimura** [comment]
> For the first one, as you might have noted, you are using the wrong cmake

Do you mean that using `/usr/bin/cmake` (which is included in `msys/cmake` package) is wrong? If so what should be used to build project that uses cmake in MSYS environment?

> for the second one, I'm not sure if cmake has the special checks for registry keys for the paths for cl etc when using NMake, I think you might need to use one of the visual studio solution generators if you want to use cl.exe etc, else, you need to use either the Ninja, Unix Makefiles, or MSYS Makefiles as those are the only ones I know of that explicitly check for gcc/g++ on windows with mingw-w64

Sorry, my explanation might be poor. What I would like to do is to build this project on MINGW64 environment with tools native to MINGW64 such as `mingw64/mingw-w64-x86_64-gcc`. I took it for granted that `mingw64/mingw-w64-x86_64-cmake` uses `mingw64/mingw-w64-x86_64-gcc` as C/C++ compiler. Isn't it the case?

**Comment by 1480c1** [comment]
I am assuming your original post's question was `How do I use cmake to build a project in a mingw-w64 environment`, not an `msys2` environment, and so using `/usr/bin/cmake` which would target `msys2`/`cygwin` instead of mingw-w64 would be wrong, if the question is if you wanted to configure a project for `msys2` or `cygwin`, then `/usr/bin/cmake` would be "right"

cmake itself is not necessarily tied to any single environment, but rather the main things that influence what cmake looks for is the generator selected. The default generator (aka without any `-G` argument to cmake) will depend on the system and what cmake detects, based on your post, it seems it detected NMake as the default, but for my `/mingw64/bin/cmake`, it detects `Visual Studio 16 2019`.

This can be found by running `cmake -G` with nothing and finding the option with a `*` next to it.

Either way, by default, cmake has no idea of specifically using the gcc provided from msys2's mingw64 repo, you will need to do something like `cmake -G"Unix Makefiles" ..` or `cmake -GNinja ..` or `cmake -G"MSYS Makefiles" ..` depending on which generator you want to use and then cmake will look for either `x86_64-w64-mingw32-gcc` or just `gcc`.

`Unix Makefiles` uses `make` from the `make` package, `Ninja` uses `ninja` from the `mingw-w64-x86_64-ninja` package, and `MSYS Makefiles` uses `make` as well, but it has different semantics for its generation which I do not prefer, but the end choice is up to you

**Comment by 1480c1** [comment]
I guess an easy example would be opening a MINGW64 environment (not msys2 or MINGW32)
```bash
pacman -S --needed git mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-gcc
git clone https://github.com/yasuhirokimura/cmaketest.git
cmake -B build -S cmaketest -GNinja
ninja -C build
```

my output
```none
pacman -S --needed git mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-gcc
warning: git-2.28.0-1 is up to date -- skipping
warning: mingw-w64-x86_64-cmake-3.17.3-3 is up to date -- skipping
warning: mingw-w64-x86_64-ninja-1.10.1-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-10.2.0-4 is up to date -- skipping
 there is nothing to do

cddeg@ccom-laptop2 MINGW64 ~
$ git clone https://github.com/yasuhirokimura/cmaketest.git
Cloning into 'cmaketest'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 0), reused 7 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), 647 bytes | 71.00 KiB/s, done.

cddeg@ccom-laptop2 MINGW64 ~
$ cmake -B build -S cmaketest -GNinja
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Check for working C compiler: D:/msys64/mingw64/bin/cc.exe
-- Check for working C compiler: D:/msys64/mingw64/bin/cc.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/msys64/mingw64/bin/c++.exe
-- Check for working CXX compiler: D:/msys64/mingw64/bin/c++.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/msys64/home/cddeg/build

cddeg@ccom-laptop2 MINGW64 ~
$ ninja -C build
ninja: Entering directory `build'
[1/4] Building C object CMakeFiles/cmaketest1.dir/main.c.obj
[2/4] Linking C executable cmaketest1.exe
[3/4] Building CXX object CMakeFiles/cmaketest2.dir/main.cpp.obj
[4/4] Linking CXX executable cmaketest2.exe
```

**Comment by yasuhirokimura** [comment]
@1480c1 Thanks. I succeeded to reproduce same result on my MINGW64 environment.
Additionally I also succeeded to build this project with `make` by adding `-G 'Unix Makefiles'` option to `cmake`.
Then I have a question. Why default generator is not `Unix Makefiles` but `NMake Makefiles`?
For me it seems bug of `mingw64/mingw-w64-x86_64-cmake`.

**Comment by 1480c1** [comment]
if you consider it a bug, report it to cmake, that's not msys2's fault

**Comment by lazka** [comment]
The cmake generators that work with mingw64 are 'MSYS Makefiles' and 'Ninja'.

**Comment by 1480c1** [comment]
I would like to add that `Unix Makefiles` work perfectly fine as well and all you need to use is `msys/make` and `make`

**Comment by lazka** [comment]
'MSYS Makefiles' also sets CMAKE_GENERATOR_RC to windres it seems, so maybe .rc file handling doesn't work with the Unix one.. but not sure.
