### ISSUE TITLE
Build full libdazzle 

### ISSUE THREAD

**Issue by albfan** [msys2/MINGW-packages#7255]
Right now libdazzle is half builded to support  some pango utils related to font and css. See all the code discarted:

https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libdazzle/0001-windows-Build-pango_font_description_to_css-on-windo.patch#L60

There are some tries to adapt codebase to win32:

- https://gitlab.gnome.org/GNOME/libdazzle/-/merge_requests/37
- https://gitlab.gnome.org/GNOME/libdazzle/-/merge_requests/48

@taozuhong we should open a PR here, removing that patch and adding a win32 one until upstream code is merged.

**Comment by Biswa96** [comment]
downstream should 'generally' wait for upstream.

**Comment by albfan** [comment]
@Biswa96 there're no CI on upstream to test this
