### ISSUE TITLE
pkgconfig switch

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#7263]
I've looked into if we can move from pkg-config to pkgconf for mingw as well.

Current actions:

* I've added a third job to CI which builds everything with pkgconf instead of pkg-config, so far nothing has failed
* I've run the meson test suite with pkgconfig and various tests have failed: https://github.com/lazka/meson/runs/1349749205 We need to look into those.

**Comment by okhlybov** [comment]
What is the purpose for this switch? Is pkgconf any better than pkg-config?

**Comment by lazka** [comment]
See http://pkgconf.org/features.html (for pkg-config use the git column, most of it isn't that relevant though)

Nice things:

* Supports CFLAGS.private which might be handy for Windows static builds, see #2826
* Is at least somewhat maintained and open to adding new features
* Is recommended by the meson developers
* Fewer dependencies

**Comment by okhlybov** [comment]
What does the switch mean for the package maintainers?
Will it be the all-in switch or both tools are expected to coinstalled?
Will pkgconf come into the base-devel or it should be explicitly depended upon?

**Comment by lazka** [comment]
> What does the switch mean for the package maintainers?

Ideally, no changes.

>  Will it be the all-in switch or both tools are expected to be coinstalled?

all in, pkgconf provides the same executables

>  Will pkgconf come into the base-devel or it should be explicitly depended upon?

It will be in base-devel instead of pkg-config

See https://github.com/msys2/MSYS2-packages/pull/2197 for a similar switch

**Comment by okhlybov** [comment]
> all in, pkgconf provides the same executables

So we continue to use the pkg-config executable now coming from the pkgconf package, right?

**Comment by lazka** [comment]
yes

**Comment by lazka** [comment]
The meson test suite now passes with the latest fixes.

**Comment by rnicolas** [comment]
Just to cite that if you were using pkg-config (or you read any tutorial where pkg-config is cited), and you want to use pkgconf instead, you might need to replace `pkg-config` for `pkgconf `.
