### ISSUE TITLE
[gtk4] Programs cannot compile due to outdated Pango version

### ISSUE THREAD

**Issue by Mabi19** [msys2/MINGW-packages#7282]
GTK4 3.99.4 is in the package database, but one of its dependencies (Pango) has an outdated version.
This causes link errors every time you try to compile GTK4 programs and also makes programs compiled beforehand stop working, effectively making it non-functional.

**Comment by lazka** [comment]
Github CI had some issues last week which broke our automated builds and lead to pango being dropped. pango will be in the next repo update.
