### ISSUE TITLE
[spdlog] Missing definitions

### ISSUE THREAD

**Issue by Amphaal** [msys2/MINGW-packages#7284]
Hey @podsvirov,

Just been trying to use `spdlog` from the MSYS2 packages, and I found out that I must include manually theses definitions (`SPDLOG_COMPILED_LIB`, `SPDLOG_FMT_EXTERNAL`) to any CMake target linking to it.

Can we somehow hardcode these defines into the main header, or patch it in `spdlogConfig.cmake` so these flags propagate upstream automatically ? It would be much more convenient.

Cheers :D

**Comment by podsvirov** [comment]
Hm...
For example, at my PC file  `/mingw32/lib/cmake/spdlog/spdlogConfigTargets.cmake` starting on 56 line:
```cmake
set_target_properties(spdlog::spdlog PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SPDLOG_SHARED_LIB;SPDLOG_COMPILED_LIB;SPDLOG_FMT_EXTERNAL"
```
All should work automaticali, just link `spdlog::spdlog` to your target.

**Comment by Amphaal** [comment]
100% my bad : I just have not considered `spdlog::spdlog` instead of `spdlog` as a target name, which, as an `IMPORTED`, can indeed include `INTERFACE` properties. 

Well, I guess we never stop learning !

Many thanks for your quick answer, and sorry for the inconvenience.

**Comment by podsvirov** [comment]
@Amphaal, all good! Glad to be helpful :-)
