### ISSUE TITLE
[protobuf-c]

### ISSUE THREAD

**Issue by rene-d** [msys2/MINGW-packages#7302]
The version 1.3.3-1 causes an error when trying to generate a C binding:

```
protoc --c_out tmp dummy.proto
--c_out: protoc-gen-c: Plugin failed with status code 3221225477.
```

It works fine when I recompile proto-gen-c from https://github.com/protobuf-c/protobuf-c and use a command like:
```
protoc --c_out tmp --plugin=protoc-gen-c=path/to/fresh/protoc-gen-c.exe dummy.proto
```

**Comment by lazka** [comment]
A rebuild seems to fix it -> #7338

maybe there was an ABI break somewhere..
