### ISSUE TITLE
Lldb stdin/stdout issues

### ISSUE THREAD

**Issue by sab24** [msys2/MINGW-packages#7315]
Hi, 

The package mingw-w64-x86_64-lldb 11.0.0-4 has runtime issues, the (lldb) prompt is not displayed when running. Pressing a command and enter, it does show output, but not the correct one, like there is a line missing. There are issues printing output and inputting input. I don’t really know how to describe this better, but it looks like the output buffer is not flushed? 

The problem occurs on multiple computers, but does not occour when running from the microsoft cmd. Is this a runtime issue of Mingw? Or is this specific to this package?

Any help is appreciated.

**Comment by mati865** [comment]
LLDB expects Windows console and I have no idea if we can do anything with it right now.
You can use `winpty lldb` as the workaround for now.

**Comment by sab24** [comment]
Thanks, it works with winpty. Gdb also works just fine. Would this be a bug in lldb?

**Comment by mati865** [comment]
> Would this be a bug in lldb?

I have no idea.

**Comment by mingwandroid** [comment]
Native Windows software can detect cygwin pipes  attached to atdio and modify their behaviour based on that. Usually searching in the code for isatty is helpful.

**Comment by Biswa96** [comment]
Did anyone tests with `MSYS=enable_pcon` i.e. enabling conpty feature in msys2?

**Comment by sab24** [comment]
Setting MSYS=enable_pcon in mingw64.ini seems to make lldb work.

**Comment by mingwandroid** [comment]
Oh cool.

**Comment by mingwandroid** [comment]
What are the issues with us defaulting to that?

**Comment by Biswa96** [comment]
> What are the issues with us defaulting to that?

Maybe because the ConPTY feature is not suitable with all programs. For example, I have tried ConPTY with `cmake.exe -G "MSYS Makefiles"` and the _colored_ output is sometimes mixed up. But cygwin is defaulted to ConPTY. @dscho may provide more info.

**Comment by dscho** [comment]
@Biswa96 is the commit message of https://github.com/msys2/msys2-runtime/pull/6/commits/22ba7ac08035c470a3927fa53805bcdcdfe5fc21 not informative enough?

**Comment by Biswa96** [comment]
I didn't see that. But that gives me some excuse to dive into newlib-cygwin code 😉

**Comment by Biswa96** [comment]
ConPTY support in msys2 is now enabled by default. It can be disabled again by setting `MSYS=disable_pcon`. More information about the change can be found here https://www.msys2.org/news/#2022-09-24-two-cygwin-related-behavior-changes
