### ISSUE TITLE
[gedit]

### ISSUE THREAD

**Issue by mayd** [msys2/MINGW-packages#7322]
I built and installed gedit from package source using the instructions at <https://www.msys2.org/wiki/Creating-Packages/>.
When I launched the gedit app the following error message was displayed:

Failed to load 'C:\msys64\mingw64\lib\gedit\libgedit-3.38.dll': 'C:\msys64\mingw64\lib\gedit\libgedit-3.38.dll': The specified module could not be found.

The MSYS2 website file list for the package lists a path /mingw64/bin/libgedit-3.38.dll.
So I tried moving /mingw64/bin/libgedit-3.38.dll to /c/msys64/mingw64/lib/gedit/libgedit-3.38.dll.
Then I launched the gedit after this change and the message did not appear and the app seems to run normally.

**Comment by Biswa96** [comment]
The package is already available to download. As example, use `pacman -S --needed  mingw-w64-x86_64-gedit` for 64 bit one.

**Comment by mayd** [comment]
My bug report relates to the source-code package - not the binary package (which does work).  The MSYS2 project website
suggests that it should be possible for users to download and build packages from source. The website states:

Packages are built from programmatic recipes to ensure builds are reproducible.

**Comment by mingwandroid** [comment]
Did you use our recipe?

**Comment by revelator** [comment]
copy the dll to /mingw*/lib/gedit and things work as they should.

**Comment by lazka** [comment]
Afair gedit had support for loading the dll from /lib, but lost this when it as ported to meson. So the question is: does gedit work despite this error? If yes please file a bug upstream if you care..

**Comment by revelator** [comment]
works if you copy the dll, would probably be easy to make a small change in PKGBUILD to do this automatically.

**Comment by lazka** [comment]
the current package works fine here

**Comment by lazka** [comment]
I get the error too, but gedit opens just fine.

**Comment by revelator** [comment]
Oh it opens its just that the gedit program seems to look for the dll in the wrong place on windows hence the warning.

**Comment by lazka** [comment]
Feel free to open a bug upstream. It seems to link against libgedit, but then only dlopens it at runtime. I don't know how that works with the linker... (I guess it did at some point) -> https://gitlab.gnome.org/GNOME/gedit/-/blob/ab9ed4a19e9e3afdf83d6e054ae94c4af94302e0/gedit/gedit.c#L48

**Comment by revelator** [comment]
Hmm according to the code shown it first tries to load it from lib/gedit and if that fails it will try to load the dll from the same dir 
as the executable so the warning is a bit fubar. could probably just remove the first warning printf since it would only have failed if neither dir had the dll.

**Comment by lazka** [comment]
That code doesn't work anyway because for the .exe to run the linker needs to find the .dll.

How do you tell the linker that the exe will handle the linking itself on Windows?

**Comment by revelator** [comment]
not sure i follow ?

**Comment by revelator** [comment]
for gcc it would be something like this if you want to avoid using ld -> gcc file1.c file2.c -o myprogram.
but im not sure i understood your question correctly ?

**Comment by lazka** [comment]
`/mingw64/bin/gedit.exe` links against `libgedit-3.38.dll`, but that isn't in PATH. How is the gmodule code supposed to be reached if the linker at load time before it will 100% fail?

some quick google gives me that "delayed dll loading" might be what's needed here, but not sure.

**Comment by lazka** [comment]
ah, here: https://github.com/mesonbuild/meson/issues/5093

**Comment by revelator** [comment]
Ah yes now i see. Yes that might help.

**Comment by revelator** [comment]
`static gboolean
gedit_w32_load_private_dll (void)
{
	gchar *dllpath;
	gchar *prefix;

        // tries to get the installed directory
	prefix = g_win32_get_package_installation_directory_of_module (NULL);

	if (prefix != NULL)
	{
		/* Instead of g_module_open () it may be possible to do any of the
		 * following:
		 * A) Change PATH to "${dllpath}/lib/gedit;$PATH"
		 * B) Call SetDllDirectory ("${dllpath}/lib/gedit")
		 * C) Call AddDllDirectory ("${dllpath}/lib/gedit")
		 * But since we only have one library, and its name is known, may as well
		 * use gmodule.
		 */
                // bit like how python does things get installed directory then look for the dll in lib/gedit and load it
                // but as pointed out above its kinda moot since it allready knows the location
		dllpath = g_build_filename (prefix, "lib", "gedit", "lib" PACKAGE_STRING ".dll", NULL);
		g_free (prefix);

		libgedit_dll = g_module_open (dllpath, 0);
		if (libgedit_dll == NULL)
		{
			g_printerr ("Failed to load '%s': %s\n",
			            dllpath, g_module_error ());
		}

		g_free (dllpath);
	}
        // above failed so load it from the same directory as gedit.exe (should be default)
	if (libgedit_dll == NULL)
	{
		libgedit_dll = g_module_open ("lib" PACKAGE_STRING ".dll", 0);
		if (libgedit_dll == NULL)
		{
			g_printerr ("Failed to load 'lib" PACKAGE_STRING ".dll': %s\n",
			            g_module_error ());
		}
	}

	return (libgedit_dll != NULL);
}
`

But since it is allready linked to this dll this code seems a bit redundant no ?

**Comment by lazka** [comment]
see #7346

**Comment by revelator** [comment]
That would have been my suggestion to :) 👍
