### ISSUE TITLE
gstreamer-plugins-bad webrtcdsp plugin

### ISSUE THREAD

**Issue by Ralayax** [msys2/MINGW-packages#7327]
Hello,

I realized that the webrtcdsp plugin wasn't being build on this repo.
If I am not mistaken, there was an issue on windows preventing this plugin to be built : https://gitlab.freedesktop.org/gstreamer/cerbero/-/issues/32

The issue on windows seems to have been fixed, and the plugin is included in gstreamer's latest official mingw build.

The upstream fix can be found here.
https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/30

Dwebrtcdsp=disabled should maybe be removed now that upstream is fixed.

Cheers,
Ralayax

**Comment by Biswa96** [comment]
You can create a pull request for this change. Contributions are always welcomed! 🤗

**Comment by Ralayax** [comment]
Yep I'm on it. I'm just gonna check that the build actually works before trying to pull random changes onto your project.

**Comment by Biswa96** [comment]
This requires a [webrtc-audio-processing][1] package. But there are some compiler error. I am in discussion with upstream developers.

[1]: https://gitlab.freedesktop.org/pulseaudio/webrtc-audio-processing

**Comment by Ralayax** [comment]
Absolutely, sorry for the lack of follow up.
A webrtc-audio-processing package would also require Google's Abseil library.

The main compiler error is the usage of msvc's __try and __except which aren't supported in mingw if I'm not mistaken.

**Comment by Biswa96** [comment]
> A webrtc-audio-processing package would also require Google's Abseil library.

I have already done that but it also has some quirks. Abseil is also compiled in mingw-w64-grpc package, so only half was already done.

> The main compiler error is the usage of msvc's __try and __except which aren't supported in mingw if I'm not mistaken.

It is in `SetThreadName` function which is not so important, so can be enclosed within `#ifdef _MSC_VER` i.e. MSVC only.

**Comment by Ralayax** [comment]
Yes, I'm just afraid of rare and hard to fix glitches if we just remove those.
I found a guy that implemented a full MinGW version of the SetThreadName :
https://gist.github.com/rossy/7faf0ab90a54d6b5a46f

**Comment by mingwandroid** [comment]
Nice find! This would enable us to build chromium worth it's sandbox stuff poasibly?

**Comment by Biswa96** [comment]
I can not compile v1.0 due to linking errors with abseil-cpp project. v0.3.1 can be compiled but only in static library form (647 KB stripped) because of undefined symbols error.

* Will there be any issue if the package only provides static library?
* Can you test if gstreamer-plugins-bad working correctly after enabling webrtcdsp plugin?
* If there is any way to convince libtool to build shared library I can try with that idea.

**Comment by Biswa96** [comment]
@Ralayax Would you like to test the linked pull request to check webrtcdsp plugin?

**Comment by Ralayax** [comment]
Of course good sir, I'll do it tonight.

**Comment by lazka** [comment]
Here is the build result from CI: [MINGW64-packages.zip](https://github.com/msys2/MINGW-packages/files/5710015/MINGW64-packages.zip)
