### ISSUE TITLE
[qt-creator]

### ISSUE THREAD

**Issue by mayd** [msys2/MINGW-packages#7332]
I was hoping to build the QtCreator program and modify it to include the missing Examples feature.  However, it seems the 
current binary package for QtCreator cannot be built from the published MSYS2 package recipe.  When I run the package build
procedure as described on <https://www.msys2.org/wiki/Creating-Packages/> the build stops with the following errors:

make[1]: *** [Makefile:808: sub-plugins-release_ordered] Error 2
make[1]: Leaving directory '/home/david/MINGW-packages/mingw-w64-qt-creator/src/build-x86_64-w64-mingw32/src'
make: *** [Makefile:596: sub-src-release_ordered] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by mingwandroid** [comment]
It is likely that your check-out path is too long to build qt in. Try cloning MINGW-packages to e.g. C:\m instead and running the build from there.

**Comment by mingwandroid** [comment]
You didn't actually show the actual error here either, just the final error. The actual error is further up in the logs.

**Comment by mayd** [comment]
Moved the build directory to the root directory to shorten the path names. That fixed the build error.

**Comment by MehdiChinoune** [comment]
qt-creator builds successfully
