### ISSUE TITLE
Build MINGW-packages-dev/mingw-w64-gcc-git with jit enabled

### ISSUE THREAD

**Issue by deb75** [msys2/MINGW-packages#7355]
Hello,

I would like to build `MINGW-packages-dev/mingw-w64-gcc-git` with `libgccjit` enabled.

To do so, I added the corresponding options in the `build() - configure` part of the  PKGBUILD file, following this page : [libgccjit online doc](https://gcc.gnu.org/onlinedocs/jit/internals/index.html#working-on-the-jit-library).

Unfortunately compilation failed at one point. I thought in first place that the package  `MINGW-packages-dev/mingw-w64-gcc-git`  already had libgccjit enabled. Did anyone already succeded to compute gcc-git with jit enabled ?

Regards

PS: I would like to have libgccjit in order to compile gccemacs

**Comment by kirill-gerasimenko** [comment]
Not sure, but this might be related https://github.com/msys2/MINGW-packages/pull/7345.

I'm also looking forward to build Emacs native comp branch for Windows.

**Comment by deb75** [comment]
Glad to hear you are looking forward to build emacs.

Following your link, I noted `--enable-host-shared` is mentioned, option which is required to build `libgccjit`. However, I do not understand the purpose of making "two separate builds".

**Comment by deb75** [comment]
I tried to recompile.

The only changes I made in the `PKGBUILD ` are : 
- add the `--enable-host-shared` in the gcc configure script
- add `jit` in the list of enabled languages

The compilation fails with a Makefile error : "could not find any rule to build libiberty.a".

Any hints ?

**Comment by kirill-gerasimenko** [comment]
Look at the conversation I've referred to https://github.com/msys2/MINGW-packages/pull/7345

**Comment by lazka** [comment]
Fixed in #7345
