### ISSUE TITLE
[gkt3] regression, Ctrl+Shift+U doesn't work 

### ISSUE THREAD

**Issue by txe** [msys2/MINGW-packages#7356]
By default, gtk3 entry/textview controls understand <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>U</kbd> key combination  [(gtk3 doc)](https://developer.gnome.org/gtk3/stable/GtkIMContextSimple.html). For example, <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>U</kbd>, <kbd>2</kbd>, <kbd>2</kbd>, <kbd>4</kbd>, <kbd>8</kbd> results in `≈`.

This functionality works in gtk3 3.24.20 and doesn't work in gkt3 3.24.23 (I don't have .21 and .22 version and as result cannot try them). Also, when I replaced only libgtk3 file by 3.24.20 while other files from 3.24.23, <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>U</kbd> started working.

**Comment by lazka** [comment]
I'd guess this is https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/991

**Comment by txe** [comment]
Thanks a lot for pinpointing that merge request!  I created an issue there, https://gitlab.gnome.org/GNOME/gtk/-/issues/3412
