### ISSUE TITLE
Qt5 strange build error

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#7360]
`make[3]: Entering directory '/E/mingw-w64-qt5/src/x86_64/qtremoteobjects/mkspecs/features'
make -f Makefile.Release
Project ERROR: Library 'assimp' is not defined.`

At first i decided to check assimp for errors and as it turned out there is atleast one as the pkgconfig file has wrong include paths.
But even after fixing that the build error is the same ?!?

**Comment by Biswa96** [comment]
See the linked PR. I have added the change to fix the include dir in assimp pkgconfig file.

**Comment by Biswa96** [comment]
I have added the change to fix the include dir in assimp pkgconfig file. Would you like to test the linked PR?

**Comment by revelator** [comment]
Sure but as i said even with the path fixed qt5 still throws the same error :(

**Comment by lazka** [comment]
same error in CI: https://github.com/msys2/MINGW-packages/runs/1614542765

**Comment by lazka** [comment]
https://bugreports.qt.io/browse/QTBUG-84037 maybe

**Comment by revelator** [comment]
yep thats the problem i had at first libassimp not defined, turned out some updated packages broke abi. 
after rebuilding everything and removing the "-separate-debug-info" flag it started building again though it would later fail
because qt seemed to think i was cross compiling. Turned out you have to remove qt5 to rebuild it as well as removing the above flag as it is no longer supported on windows and will throw an error about it only being enabled if OS is darwin O_o.
