### ISSUE TITLE
arpack (old) 

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#7365]
I try to add old arpack from: https://www.caam.rice.edu/software/ARPACK/
I need this version for CalculiX (FEM program), the current version of arapck (ng) does not work properly with CalculiX.

```
_realname=arpack96
pkgver=2.1
```

I have problem with the exact path from ARmake.inc (line 28), I attach the ARmake.inc, Makefile and my PKGBUILD with patch in the archive:
[src.zip](https://github.com/msys2/MINGW-packages/files/5622488/src.zip)

```
home = $(HOME)/ARPACK
...
ARPACKLIB  = $(home)/libarpack_$(PLAT).a
```
If I give a local path where the source code is, everything is fine.

**Comment by okhlybov** [comment]
See my [arpack.zip](https://github.com/msys2/MINGW-packages/files/5622921/arpack.zip) quick hack of your recipe to get past the compilation stage.

**Comment by 3rav** [comment]
Hi,

Why did you skip BLAS and LAPACK compilation?:
```
-#DIRS         = $(UTILdir) $(SRCdir)
+DIRS         = $(UTILdir) $(SRCdir)
```
This version of arpack requires older versions of LAPACK (current packages is 3.9): ` # | NOTE: ARPACK assumes the use of LAPACK version 2 codes.           |`

I have a problem building the correct library:
1. Local compilation: `$ HOME=$(pwd)/.. make lib` -> libarpack96.a 1358KB
2. local compilation but makepkg: libarpack96.a 312KB

The source files are the same (same patch applied), the only difference is the compilation call (make lib vs makepkg).

**Comment by okhlybov** [comment]
There is no need for them.
One should link to msys2-provided openblas which covers the entire functionality.

**Comment by 3rav** [comment]
For versions without BLAS and LAPACK (later use of OpenBLAS):
1. Local compilation: $ HOME=$(pwd)/.. make lib -> libarpack96.a 575KB
2. local compilation but makepkg: libarpack96.a 205KB

The source files are the same (same patch applied), the only difference is the compilation call (make lib vs makepkg).

**Comment by sfhacker** [comment]
This closed (?) issue is over six months old!
@3rav Have you contacted us before?

Just downloaded arpack from here: https://www.caam.rice.edu/software/ARPACK/ and built it from source, both static and dynamic (Windows 10 x64). No issues at all. We also ran all the examples.

![image](https://user-images.githubusercontent.com/25817529/135619804-32362ddf-a672-4822-ae0d-36819c7222dd.png)
