### ISSUE TITLE
lib prefix in dll file from mingw-w64-x86_64-plasma-framework-qt5 package should be removed

### ISSUE THREAD

**Issue by BLumia** [msys2/MINGW-packages#7393]
Hi,

While working on a project using the `plasma-framework` package, I found some of the dll files from the package form MSYS2 ([`mingw-w64-x86_64-plasma-framework-qt5`](https://packages.msys2.org/package/mingw-w64-x86_64-plasma-framework-qt5)) have an extra "lib" prefix.

``` plain
Files:
...
/mingw64/share/qt5/qml/org/kde/plasma/calendar/libcalendarplugin.dll
...
/mingw64/share/qt5/qml/org/kde/plasma/components/libplasmacomponentsplugin.dll
...
/mingw64/share/qt5/qml/org/kde/plasma/core/libcorebindingsplugin.dll
...
/mingw64/share/qt5/qml/org/kde/plasma/extras/libplasmaextracomponentsplugin.dll
...
/mingw64/share/qt5/qml/org/kde/plasma/platformcomponents/libplatformcomponentsplugin.dll
...
```

The `*plugin.dll` files are native C++ QML plugin. The extra "lib" prefix will cause the QML engine won't be able to load those native C++ QML plugin, thus the projects rely on plasma-framework won't be able to run as intended.

Here is a simple test QML file you can use to test this issue by running `qmlscene /path/to/this/file.qml`.

``` qml
import QtQuick 2.13
import QtQuick.Window 2.13
import org.kde.plasma.core 2.0 as PlasmaCore

Window {
    visible: true
    width: 640
    height: 480
    title: qsTr("Example")

    Rectangle {
        color: PlasmaCore.Theme.backgroundColor
        anchors.fill: parent
    }
	
	Text {
		color: PlasmaCore.Theme.textColor
		horizontalAlignment: Text.AlignHCenter
		verticalAlignment: Text.AlignVCenter
		text: "Sample Text"
		anchors.fill: parent
	}
}
```

The `import org.kde.plasma.core` rely on plasma's `corebindingsplugin`, since the file installed from MSYS2 is `/mingw64/share/qt5/qml/org/kde/plasma/core/libcorebindingsplugin.dll`, it won't able to load, no window will be shown. If you rename the dll file and remove the "lib" prefix, it will work and you can see a window named "Example" and contains the text "Sample Text".

I'm not sure if it's an upstream issue or a package issue so I would like to report it here. Let me know if I got to the wrong place.

**Comment by BLumia** [comment]
- https://kde.org/announcements/frameworks/5/5.94.0/
- https://invent.kde.org/frameworks/extra-cmake-modules/-/merge_requests/170

Not tested but probably fixed from upstream on 5.94.0

**Comment by Biswa96** [comment]
> The extra "lib" prefix will cause the QML engine won't be able to load those native C++ QML plugin

Many DLLs naming scheme follow the 'lib' prefix in mingw packages. Should DLLs be renamed or the DLLs/plugins loader be fixed instead?

> Here is a simple test QML file you can use to test this issue by running qmlscene /path/to/this/file.qml.

What packages/programs does one need to reproduce that test?

**Comment by BLumia** [comment]
> Many DLLs naming scheme follow the 'lib' prefix in mingw packages. Should DLLs be renamed...

No, only the QML C++ plugins cannot use the 'lib' prefix.

> ...or the DLLs/plugins loader be fixed instead?

I'm not sure about this, but the 'lib' prefix is created since KDE is using their own way to build these QML C++ plugins (using ECM and their CMake script), so IMO this isn't something should be fixed from the Qt's side.

> What packages/programs does one need to reproduce that test?

`qmlscene`. Using the QML example provided in the description of this issue and use `qmlscene` to show it. `qmlscene` is in `mingw-w64-x86_64-qt5-declarative` package. Read the description of this issue for reason and detailed steps to reproduce this issue and let me know if you have any other questions.

**Comment by Biswa96** [comment]
> No, only the QML C++ plugins cannot use the 'lib' prefix.

Is that rule for mingw or Windows only? ArchLinux's [plasman framework][1] package has plugins with 'lib' prefix.

[1]: https://archlinux.org/packages/extra/x86_64/plasma-framework/

**Comment by BLumia** [comment]
> > No, only the QML C++ plugins cannot use the 'lib' prefix.
> 
> Is that rule for mingw or Windows only? ArchLinux's [plasman framework](https://archlinux.org/packages/extra/x86_64/plasma-framework/) package has plugins with 'lib' prefix.

I don't have a mac so not be able to test, but it's probably windows only.

**Comment by BLumia** [comment]
Update: This issue is still represented in [`mingw-w64-x86_64-plasma-framework-qt5 5.98.0-1`](https://packages.msys2.org/package/mingw-w64-x86_64-plasma-framework-qt5) from MSYS2, it seems the `Drop lib prefix when building for Windows (MinGW)` change just means there is a `ecm_add_qml_module()` to use but KDE projects still need to adapt to use that CMake API.

**Comment by Biswa96** [comment]
I agree. plasma-framework need same `ecm_add_qml_module()` modification as you did with kitemmodels. Feel free to upstream the changes.

**Comment by BLumia** [comment]
I don't have a fix to address the plasma-framework issue currently, and probably don't have enough time to work on that in maybe at least two weeks, so if you (or anyone else) plan to work on that then please feel free to do so and I'll be happy to help when needed :)

**Comment by Biswa96** [comment]
I have tried to compile plasma-framework from git repository https://invent.kde.org/frameworks/plasma-framework in mingw. It fails with the following error:

```
plasma-framework/src/declarativeimports/platformcomponents/icondialog.cpp:15:10: fatal error: KX11Extras: No such file or directory
```

Should plasma-framework be compiled for native Windows platform? Does any KDE program require plasma-framework for native Windows platform?

**Comment by Biswa96** [comment]
With this change https://invent.kde.org/frameworks/plasma-framework/-/merge_requests/659 plasma framework can not be compiled for native Windows platform. It requires KX11Extras header file.

**Comment by BLumia** [comment]
https://invent.kde.org/packaging/craft-blueprints-kde/-/blob/master/kde/frameworks/tier3/plasma-framework/plasma-framework.py#L6

https://invent.kde.org/packaging/craft-blueprints-kde/-/commit/8f79b33d4f8d97745004965770f0ef10620d1bf5

Seems KDE also disabled the plasma-framework build for Windows too.

**Comment by Biswa96** [comment]
So, can it be removed next KDE update? Kate is the only mingw package that depends on plasma-framework. Also plasma-framework is not present in Kate from Windows Store.

**Comment by BLumia** [comment]
I guess it can be removed if Kate is the only one that depends on that package. According to [here](https://invent.kde.org/packaging/craft-blueprints-kde/-/blob/master/kde/applications/kate/kate.py#L54), KDE uses `DCMAKE_DISABLE_FIND_PACKAGE_KF5Plasma` for building Kate on Windows at least if I understand correctly.

**Comment by Biswa96** [comment]
> Seems KDE also disabled the plasma-framework build for Windows.

mingw plasma-framework package has been removed with this commit https://github.com/msys2/MINGW-packages/commit/09fb32ef3bf386dea7f274d7e0fd1c9d74a78caf
