### ISSUE TITLE
harfbuzz.pc too many open files problem

### ISSUE THREAD

**Issue by arnabanimesh** [msys2/MINGW-packages#7399]
## Describe the issue
`harfbuzz.pc` is corrupted

## Steps to Reproduce the Problem
1. Compile a `Rust` project with `cairo-rs` dependency and set `PKG_CONFIG_PATH` to use `C:\msys64\mingw64\lib\pkgconfig`
2. The following error appears: **[Click here](https://gist.github.com/arnabanimesh/789dd5529fe9b1bd302f147480d432e1)**
3. Successful compilation should happen like what happens when I use the `gtk3` build used by the [`gvsbuild`](https://github.com/wingtk/gvsbuild). But it is dynamically compiled so I can't use it. I need statically compiled libs.

## Operating System
Windows 10 Home version 1909 64bit

**Comment by Biswa96** [comment]
> Compile a Rust project with cairo-rs dependency

Can you provide that project link?

**Comment by arnabanimesh** [comment]
> > Compile a Rust project with cairo-rs dependency
> 
> Can you provide that project link?

Source code is mentioned in this [Github Gist](https://gist.github.com/arnabanimesh/77d4c63ea710d2a72b26ea57ae922eda). Ignore the logs.

**Comment by Biswa96** [comment]
Your given example is compiled fine in my PC. Also the harfbuzz.pc file seems to be OK.

**Comment by lazka** [comment]
I guess something is leaking files

**Comment by arnabanimesh** [comment]
> Your given example is compiled fine in my PC. Also the harfbuzz.pc file seems to be OK.

Are you using normal cmd/powershell or mingw64 shell?

I was using powershell 7.1

I will try reinstalling the modules and will keep posted.

Anyway I can capture any verbose pedantic logs during compilation?

**Comment by arnabanimesh** [comment]
Well, I even tried installing i686 version of the packages using mingw32. Still the same issue.

Which cargo toolchain are you guys using? And are you guys compiling on Windows 10 1909?

I am using the latest packages.

**Comment by Biswa96** [comment]
Can you provide the steps to reproduce the issue? pkgconf commands are working fine with harfbuzz.pc.

**Comment by Biswa96** [comment]
There is a bug in gdk-3.0.pc file and it was not even reported 🤦‍♂️

**Comment by Biswa96** [comment]
What is rbxfile ?

**Comment by Biswa96** [comment]
@iocmet Is there any way to build/reproduce the issue with gotk3? I have run the command `go get github.com/gotk3/gotk3/gtk` and it shows 

```
$ go get github.com/gotk3/gotk3/gtk
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

**Comment by Biswa96** [comment]
@iocmet Is there any way to build/reproduce the issue with gotk3?

**Comment by Biswa96** [comment]
I have sent a patch to upstream to fix the gtk3 pkgconfig issue https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5458
