### ISSUE TITLE
luarocks for lua5.1 is using lua5.3 as interpreter?

### ISSUE THREAD

**Issue by xubury** [msys2/MINGW-packages#7402]
If you installed luarocks and lua5.3, you can't install package normally like https://github.com/msys2/MINGW-packages/issues/4492.
But if you uninstall lua5.3 and just keep lua5.1, luarocks works fine.
I suspect luarocks is using lua5.3 as interpreter. Because you will get a unpack error and `unpack` was removed in lua5.2 .
Is there any method to patch this or perhaps add a new luarocks package for lua5.3 https://github.com/msys2/MINGW-packages/issues/3434?

**Comment by ImperatorS79** [comment]
I can update the luarocks package to 3.4.0  and create two packages named luarocks and luarocks51 like there are lua and lua51.
