### ISSUE TITLE
Update Verilator package

### ISSUE THREAD

**Issue by ktbarrett** [msys2/MINGW-packages#7423]
Verilator [v4.106](https://github.com/verilator/verilator/releases/tag/v4.106) introduces fixes to serious bugs in Verilator's VPI implementation that has the potential to affect all VPI users; and is import for the support for [cocotb](https://github.com/cocotb/cocotb), which is an increasingly popular Python-based testbenching environment that supports verilator.

**Comment by lazka** [comment]
fixed in #7424
