### ISSUE TITLE
QT - UIC.exe error 

### ISSUE THREAD

**Issue by acotty** [msys2/MINGW-packages#7436]
Sometime in the last 4 months one of the MSYS2 updates has caused my current QT app to fail building. I am running the latest packages as of this morning 13-Dec-2020 (GMT + 10hrs, Australia). 

Hopefully the relevant versions of the packages are:
mingw-w64-x86_64-qt-creator 4.13.2-1
mingw-w64-x86_64-qt5 5.15.1-1
mingw-w64-x86_64-qt5-static 5.15.1-1
mingw-w64-x86_64-cmake 3.19.1-2
mingw-w64-x86_64-make 4.3-1

The problem is that it appears that the uic.exe is not generating the *.h from the *.ui form files. A snippet of the compile output is:
C:/msys64/mingw64/bin/mingw32-make.exe -f Makefile.Debug
mingw32-make[1]: Entering directory 'C:/GM_Work/NSW_X_Decoder_QT'
/C/msys64/mingw64/bin/uic.exe Forms/AGMMA_MultiGame_Form.ui -o build/debug/.ui/ui_AGMMA_MultiGame_Form.h
/C/msys64/mingw64/bin/uic.exe Forms/AGMMA_Peripheral_Form.ui -o build/debug/.ui/ui_AGMMA_Peripheral_Form.h
/C/msys64/mingw64/bin/uic.exe Forms/AGMMA_TITO_TIME_Form.ui -o build/debug/.ui/ui_AGMMA_TITO_TIME_Form.h
/C/msys64/mingw64/bin/uic.exe Forms/CCCE_Logger_Form.ui -o build/debug/.ui/ui_CCCE_Logger_Form.h
/C/msys64/mingw64/bin/uic.exe Forms/CCCE_Transfer_Form.ui -o build/debug/.ui/ui_CCCE_Transfer_Form.h
/C/msys64/mingw64/bin/uic.exe Forms/CDB_Form.ui -o build/debug/.ui/ui_CDB_Form.h
/C/msys64/mingw64/bin/uic.exe Forms/FDB_Form.ui -o build/debug/.ui/ui_FDB_Form.h
/usr/bin/sh: /C/msys64/mingw64/bin/uic.exe: No such file or directory
/usr/bin/sh: /C/msys64/mingw64/bin/uic.exe: No such file or directory
/C/msys64/mingw64/bin/uic.exe Forms/Message_Display_Form.ui -o build/debug/.ui/ui_Message_Display_Form.h
mingw32-make[1]: *** [Makefile.Debug:3974: build/debug/.ui/ui_AGMMA_MultiGame_Form.h] Error 127
mingw32-make[1]: *** Waiting for unfinished jobs....
mingw32-make[1]: *** [Makefile.Debug:3978: build/debug/.ui/ui_AGMMA_Peripheral_Form.h] Error 127
/usr/bin/sh: /C/msys64/mingw64/bin/uic.exe: No such file or directory
mingw32-make[1]: *** [Makefile.Debug:3982: build/debug/.ui/ui_AGMMA_TITO_TIME_Form.h] Error 127
/usr/bin/sh: /C/msys64/mingw64/bin/uic.exe: No such file or directory
mingw32-make[1]: *** [Makefile.Debug:3986: build/debug/.ui/ui_CCCE_Logger_Form.h] Error 127
/usr/bin/sh: /C/msys64/mingw64/bin/uic.exe: No such file or directory
mingw32-make[1]: *** [Makefile.Debug:3990: build/debug/.ui/ui_CCCE_Transfer_Form.h] Error 127
/usr/bin/sh: /C/msys64/mingw64/bin/uic.exe: No such file or directory
mingw32-make[1]: *** [Makefile.Debug:3994: build/debug/.ui/ui_CDB_Form.h] Error 127
/usr/bin/sh: /C/msys64/mingw64/bin/uic.exe: No such file or directory
mingw32-make[1]: *** [Makefile.Debug:3998: build/debug/.ui/ui_FDB_Form.h] Error 127
/usr/bin/sh: /C/msys64/mingw64/bin/uic.exe: No such file or directory
mingw32-make[1]: *** [Makefile.Debug:4002: build/debug/.ui/ui_Message_Display_Form.h] Error 127
mingw32-make[1]: Leaving directory 'C:/GM_Work/NSW_X_Decoder_QT'
mingw32-make: *** [Makefile:45: debug] Error 2

Any ideas on how to fix this?
Should I try and install the previous version of QT creator 4.12.4 and see if this fixes it?

**Comment by Biswa96** [comment]
`uic.exe` exists in my system. You can reinstall the qt5 package with `pacman -S mingw-w64-x86_64-qt5` command. Also check if there is any antivirus or antimalware program which may delete uic.exe.

**Comment by acotty** [comment]
/C/msys64/mingw64/bin/uic.exe exists in the directory specified and can be run from the command line. I use AVG Free and it has not quarantined the file.

I re-installed qt5 5.15.1-1 using the pacman -S mingw-w64-x86_64-qt5 command, but I still get the same error.

Running uic from command line example:
$ /C/msys64/mingw64/bin/uic.exe  -help
Usage: C:\msys64\mingw64\bin\uic.exe [options] [uifile]
Qt User Interface Compiler version 5.15.1
