### ISSUE TITLE
[headers] shlwapi.h missing IStream_* functions

### ISSUE THREAD

**Issue by mayd** [msys2/MINGW-packages#7451]
When I attempt to compile a win32 app with MSYS2/MINGW I see the following error:

 ... error: 'IStream_Size' was not declared in this scope; did you mean 'streamSize'?
  179 |                     VERIFY(S_OK == IStream_Size(stream, &streamSize));
      |                                    ^~~~~~~~~~~~

and similar errors relating to other IStream_* functions usually declared in a Microsoft SDK version of include file shlwapi.h.
If I copy the declarations from the Microsoft SDK in shlwapi.h into my program the MINGW compiler error does not occur.

The declarations are:

LWSTDAPI IStream_Read(_In_ IStream *pstm, _Out_writes_bytes_all_(cb) void *pv, _In_ ULONG cb);
LWSTDAPI IStream_Write(_In_ IStream *pstm, _In_reads_bytes_(cb) const void *pv, _In_ ULONG cb);
LWSTDAPI IStream_Reset(_In_ IStream *pstm);
LWSTDAPI IStream_Size(_In_ IStream *pstm, _Out_ ULARGE_INTEGER *pui);

**Comment by Biswa96** [comment]
Would you like to provide the project link so that new header changes can be verified?

**Comment by mayd** [comment]
Not sure exactly what you are asking for. There is an up-to-date version of shlwapi.h in my installation of Microsoft SDK.

The installed Microsoft SDK version of shlwapi.h is documented here:
[Microsoft shlwapi.h header](https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/).

Microsoft's source code for shlwapi.h does not appear to be published on the Web but I found several other versions, e.g.:
[winsdk-10/Include/10.0.16299.0/um/Shlwapi.h](https://github.com/tpn/winsdk-10/blob/master/Include/10.0.16299.0/um/Shlwapi.h).

All the above are more comprehensive than the MSYS2 version of shlwapi.h:
[mingw-w64/mingw-w64-headers/include/shlwapi.h ](https://github.com/Alexpux/mingw-w64/blob/master/mingw-w64-headers/include/shlwapi.h).

**Comment by Biswa96** [comment]
I mean, are you compiling any project that needs those APIs? Can you provide the project link. mingw-w64 works differently so one need to test a project before adding anything in mingw-w64 headers.

**Comment by mayd** [comment]
I have updated the MSYS2 version of shlwapi.h to include many missing functions and tested it using a set unit tests from the Wine Project.  

My work is on Github here: <https://github.com/mayd/shlwapi.git>

How can I add it to MSYS2?

**Comment by ZachBacon** [comment]
> I have updated the MSYS2 version of shlwapi.h to include many missing functions and tested it using a set unit tests from the Wine Project.  
> 
> My work is on Github here: <https://github.com/mayd/shlwapi.git>
> 
> How can I add it to MSYS2?
> 

Via the mingw-w64 mailing list as a patch https://sourceforge.net/projects/mingw-w64/lists/mingw-w64-public

**Comment by Biswa96** [comment]
Congratulations! Your change is now in upstream mingw-w64 https://sourceforge.net/p/mingw-w64/mingw-w64/ci/dc7ef298837d4581200a3bed660aed36818c1b00/ 🥳

**Comment by mayd** [comment]
I upgraded my installation of MSYS2. I reran my unit tests and the application which used shlwapi.h.
Everything works as expected with the new MSYS2 version of shlwapi.h.

Case closed.
