### ISSUE TITLE
`connect` package source code is unavailable

### ISSUE THREAD

**Issue by JiapengLi** [msys2/MINGW-packages#7453]
It looks like connect source code is unavailable. Is there any chance to get the latest package?
I use `connect` with git SSH protocol, and get speed limitation when using git push (git clone works just fine).

So I'd like to get the source code to see if there any chance to fix  it.

Thank you!

https://bitbucket.org/gotoh/connect/overview (unavailable)

https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-connect/PKGBUILD (reference)

**Comment by Biswa96** [comment]
Hi! @JiapengLi Thank you for notifying the issue. The upstream repository has changed to https://github.com/gotoh/ssh-connect. I have sent patch to fix this issue. See the linked pull request for further details.
