### ISSUE TITLE
rsvg2 library size

### ISSUE THREAD

**Issue by peterbud** [msys2/MINGW-packages#7455]
I have seen that the librsvg-2-2.dll is quite big: 8.7MB

I'm wondering why is that? E.g I have seen that introspection flag is enabled (--enable-introspection), while in the arch repo that is not enabled. Is that flag necessary?

Can we maybe reduce that lib size? Or is this normal?

**Comment by lazka** [comment]
Expected: https://gitlab.gnome.org/GNOME/librsvg/-/issues/589

**Comment by lazka** [comment]
introspection doesn't change the binary

**Comment by peterbud** [comment]
Thanks @lazka !

**Comment by lazka** [comment]
we can try enabling LTO as mentioned in one of the issues, but not sure if that changes the size in any way, but worth a try.
