### ISSUE TITLE
update parsec (version?)

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#7470]
I would like to update the parsec package to a newer version but I don't know where to get version numbers like?:
```
pkgver=1.1.0.r3811.ge3360fad5
```

Full version __commit I guess it comes from the address (https://bitbucket.org/icldistcomp/parsec/commits/e3360fad5ecfa91e7e090ecdee0dca37f5708326):

```
_commit='e3360fad5ecfa91e7e090ecdee0dca37f5708326'
```

**Comment by Biswa96** [comment]
The `pkgver` variable is automatically created by `pkgver()` function. At the time of packaging, a full git clone of that repo is done and then checkout to that specific `_commit`. A stable version is preferred over git commit version. Also your provided repository does not have a _stable version_ tag greater than 1.1.0.

**Comment by 3rav** [comment]
Thanks
