### ISSUE TITLE
mingw64/mingw-w64-x86_64-python  getpass.getpass() broken in msys2 console. msys/python works

### ISSUE THREAD

**Issue by chris-stones** [msys2/MINGW-packages#7472]
SOME builds of python (3.8.6) fail to read passwords under some shells.

| Python Package       | MSYS2 Shell     | cmd shell     |  Powershell |
| :------------- | :----------: | :-----------: | --------------:|
|  mingw32/mingw-w64-i686-python | BROKEN   | WORKS    |  WORKS |
| mingw64/mingw-w64-x86_64-python  | BROKEN | WORKS | WORKS |
| msys/python  | WORKS | WORKS | WORKS |

steps to reproduce.
Launch interpreter python.exe.

type and run following commands.
```python
import getpass
p = getpass.getpass("")
```

Then enter a password.

Correct behavior that password is NOT echoed to the screen.  
Password is assigned to p.  

BROKEN behavior is that password is echoed to screen.
upon pressing return, the function getpass() never returns.
lockup.

when hitting ctrl-c, python interpreter exits, then the console tries to execute my password as a command.

```bash
ChrisStones@W1029078 MSYS ~
$ /mingw64/bin/python
Python 3.8.6 (default, Nov  3 2020, 22:43:55)  [GCC 10.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import getpass
>>> a = getpass.getpass("")
MY PASSWORD
```
**(ctrl-c here!)**
```bash
ChrisStones@W1029078 MSYS ~
$ MY PASSWORD
-bash: MY: command not found
```

WORKAROUND - 
Everything works fine if python interpreter is run under `winpty`
```bash
ChrisStones@W1029078 MSYS ~
$ winpty /mingw64/bin/python
Python 3.8.6 (default, Nov  3 2020, 22:43:55)  [GCC 10.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import getpass
>>> getpass.getpass()
Password:
'HELLO'
>>> quit()
```

interestingly, regular input with `input()` function works correctly.

I discovered this bug while trying to use conan.io wth mingw.

**Comment by Biswa96** [comment]
Set `MSYS=enable_pcon` environment variable in control panel and do the tests exactly as you did here. Does it solve the issue?

**Comment by chris-stones** [comment]
@Biswa96 Yes! 
With this environment variable set, getpass.getpass works as expected.

**Comment by chris-stones** [comment]
strange that the msys/python package does not require it.

**Comment by Biswa96** [comment]
Here is another victim of this same thing https://github.com/msys2/MINGW-packages/issues/7315

**Comment by lazka** [comment]
> strange that the msys/python package does not require it.

Python has a Windows and a Unix implementation for getpass, msys will use the unix version.

**Comment by Biswa96** [comment]
ConPTY support in msys2 is now enabled by default. It can be disabled again by setting `MSYS=disable_pcon`. More information about the change can be found here https://www.msys2.org/news/#2022-09-24-two-cygwin-related-behavior-changes
