### ISSUE TITLE
Multiple mingw python packages have broken shebang

### ISSUE THREAD

**Issue by Artoria2e5** [msys2/MINGW-packages#7481]
## Describe the issue

The shebang on many of the mingw python packages are currently `#!D:/a/_temp/msys/msys64/mingw64/bin/python.exe`. This obviously doesn't run.

## Steps to Reproduce the Problem

1. Run 'pacman -S mingw-w64-x86_64-python-black'
2. Run 'black' and see 'bash: /mingw64/bin/cxfreeze-script.py: D:/a/_temp/msys/msys64/mingw64/bin/python.exe^M: bad interpreter: No such file or directory'
3. Run 'less $(which black)' under mingw64

## Additional Context: Operating System, Screenshots
mingw-w64-x86_64-python-black 20.8b1-1

**Comment by Biswa96** [comment]
@Schala As I predicted about this!

**Comment by Biswa96** [comment]
Hi @Artoria2e5 👋 Thank you for reporting this issue. I have sent a pull request to fix it. Packages will be uploaded after some days. Meanwhile, you could download the _unsigned_ package from GitHub Actions artifacts in the linked pull request.

**Comment by winterz** [comment]
Did I install something incorrectly? I'm seeing this in pylint
```

#!D:/a/_temp/msys/msys64/mingw64/bin/python.exe
from pylint import run_pylint

run_pylint()
```
I ran `pacman -S mingw-w64-x86_64-python-pylint`
and then tried `pacman -S mingw-w64-x86_64-python3-pylint`

**Comment by lazka** [comment]
That's likely a packaging bug

**Comment by Biswa96** [comment]
> That's likely a packaging bug

Yup. The PKGBUILD edits shebang for .py files only. The rest are:

```
$ grep -air msys64
bin/epylint:#!D:/a/_temp/msys/msys64/mingw64/bin/python.exe
bin/pylint:#!D:/a/_temp/msys/msys64/mingw64/bin/python.exe
bin/pyreverse:#!D:/a/_temp/msys/msys64/mingw64/bin/python.exe
bin/symilar:#!D:/a/_temp/msys/msys64/mingw64/bin/python.exe
````

**Comment by Artoria2e5** [comment]
It should be pretty safe to edit the shebang for all files regardless of name. As long as the sed command is made to only work on the first line — should be possible with putting a line number “1” in front of the “s/“ command IIRC.
