### ISSUE TITLE
QT5 strange build error

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#7489]
ERROR: Feature 'separate_debug_info' was enabled, but the pre-condition 'config.darwin || tests.separate_debug_info' failed.

Check config.log for details.
==> ERROR: A failure occurred in build().
    Aborting...

this happens no matter what i do, any ideas ?.

**Comment by revelator** [comment]
log unfurtunatly does not tell me anything ;/

**Comment by mingwandroid** [comment]
To debug these kind of failures I usually go into the directory with the Makefile, and open the Makefile (usually a .release one). There you can see the qmake command that created it. I think copy that into my terminal and add more and more -v (or is it -d) params to this invocation until it tells me something useful. Usually, you'll end up editing .pri files though to add debugging prints into them.

Painful. Roll on Qt6 when we can ditch qmake forever!

**Comment by revelator** [comment]
Looking forward to that indeed 🤕

**Comment by revelator** [comment]
sadly it prevents me from updating icu since it would break all tools dependant on qt5 (is linked against the 1.67 version atm).
My mainboard has developed some nastyness lately so i ordered a replacement which means i will have to reinstall my build environment anyway. Hopefully the build error is some kinda fluke caused by the compiler picking up stuff it should not, we will see when the new board arrives i hope.

**Comment by revelator** [comment]
does this per chance relate to the assimp problem that seems to have developed with qt5 lately ? though in that case why the strange error ? 🤦

**Comment by umarcor** [comment]
Ref #7360

**Comment by revelator** [comment]
Well after an extensive rebuild of all packages qt5 started building again though it still fails after a little while because it seems to think im cross compiling so windres gets prefixed with the host compiler string grrr ⚡ 🤦
