### ISSUE TITLE
mingw-w64-python-pywin32 is on git but not in the repos

### ISSUE THREAD

**Issue by dthpham** [msys2/MINGW-packages#751]
The `mingw-w64-python-pywin32` PKGBUILD is on GitHub ([here](https://github.com/Alexpux/MINGW-packages/tree/04ac84c2a9e2c130af6fd6028bd9e9dfe5ecb21e/mingw-w64-python-pywin32)) but the package is not found when I search for it in the repos: `pacman -Ss mingw-w64-python-pywin32` yields nothing and I can't install it. Can you add this package so it's available in one of the mirrors?

**Comment by Alexpux** [comment]
This is incomplete package. It don't build right now.

**Comment by fred-wang** [comment]
@renatosilva What is the status on this? Are you still working on this package?

**Comment by renatosilva** [comment]
Hi Frédéric, many extensions are building already. I stopped at some error about exception handling then switched to ctypes. Someone interested can try building the package and continue the work.

**Comment by fred-wang** [comment]
@renatosilva Thanks, I figured that out and arrived at the same error as you. Unfortunately, there does not seem to be a (good) way to rewrite the visual studio exception handling with MINGW-w32/MINGW-w64. My goal was to integrate buildbot in MSYS2. I already submitted packages for many dependencies, but pywin32 (this one) and cffi (#889) are still not working perfectly. At the moment, I'm just using the official "python for windows" to run buildbot in MINGW-w64 and MINGW-w32 shells, so that's enough for me.

**Comment by mingwandroid** [comment]
@fred-wang Implementing VC-style exception handling for MinGW-w64's GCC would be a worthwhile task for someone with enough time to look into. It's by no means an easy job though.

Google's sandbox - used by Chromium and Mozilla's Firefox needs it too.

**Comment by mingwandroid** [comment]
In general the "on git but not in the repos" is not something to be surprised about, the git repositories are the development area for our packages. The repositories will often contain less up to date (but more stable) binary versions of the software, and, as is the case here, the repos can contain stuff that's just not possible to be built yet (and stuff that may never reach that state unfortunately).

**Comment by podsvirov** [comment]
Hello to all! Any efforts to update and restore this package?

**Comment by Alexpux** [comment]
@podsvirov see https://github.com/msys2/MINGW-packages/pull/5615

**Comment by podsvirov** [comment]
Thanks for the link.

I had this question with the same attempt to use `emrun` ([Emscripten](https://emscripten.org)) via `python` from `MSYS2`.

**Comment by joankaradimov** [comment]
@podsvirov I'm [the latest person] trying to port pywin32 right now. My goal was using `emrun` too. And I'm confident I'll eventually get enough pywin32 running for emscripten to work.

However, node.js remains a problem. It's an emscripten dependency and MSYS2 no longer provides a node package. What's your approach?

**Comment by podsvirov** [comment]
@joankaradimov, thanks again for your efforts on `pywin32`. As for `node`, you can use a separately installed instance, but I was very happy if we could restore the package to the repository. Unfortunately, I currently do not have a powerful enough computer and free time to maintenance such a large package as `node`.

**Comment by el07694** [comment]
Hello we need this package (for docx2pdf module).
It would be great if we can install with a pacman command.
:)

**Comment by Biswa96** [comment]
This need some python trickery. The upstream https://github.com/mhammond/pywin32 has some pull request to support mingw-w64 build environment but was not merged. Let see what can be done. Opening this issue...

**Comment by Biswa96** [comment]
The pywin32 package is now in pacman repository https://packages.msys2.org/base/mingw-w64-python-pywin32. Can anyone test the package?

**Comment by el07694** [comment]
Target not found

Στις Κυρ, 7 Νοε 2021 στις 5:25 μ.μ., ο/η Biswapriyo Nath <
***@***.***> έγραψε:

**Comment by Biswa96** [comment]
Would you like to elaborate your statement?

**Comment by el07694** [comment]
```
Active code page: 1253

Χρήστος Παππάς@DESKTOP-8T1C1VF MSYS /g
$ pacman -S mingw-w64-x86_64-python-pywin32
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-python-pywin32-302-2

Total Download Size:    2.48 MiB
Total Installed Size:  13.45 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 mingw-w64-x86_64...     2.5 MiB  1496 KiB/s 00:02 [#####################] 100%
(1/1) checking keys in keyring                     [#####################] 100%
(1/1) checking package integrity                   [#####################] 100%
(1/1) loading package files                        [#####################] 100%
(1/1) checking for file conflicts                  [#####################] 100%
(1/1) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/1) installing mingw-w64-x86_64-python-pywin32   [#####################] 100%

Χρήστος Παππάς@DESKTOP-8T1C1VF MSYS /g

```


I have to run 

`sudo pacman -Syu`

first

**Comment by jeremyd2019** [comment]
For the record, I have tested the ifilter and bits win32comext modules in order to test mingw-w64 updates related to them.  They both work once mingw-w64 is updated with the changes necessary for them to build.  Testing bits, I did find a bug in "COM server" code that caused a crash when trying to implement a COM interface in Python, but that should be fixed in 302-3 (not yet in the repos but in staging).

**Comment by el07694** [comment]
This code:

```
'''
from docx2pdf import convert
import os
convert(os.path.abspath("111.docx"))
'''

import win32com.client as win32
import os

word = win32.gencache.EnsureDispatch('Word.Application')
word.Visible = True
doc_path = os.path.abspath("111.docx")
doc = word.Documents.Open(doc_path)
```

Throws this error:


```
$ python docx2pdfdemo.py
Traceback (most recent call last):
  File "C:\Users\Χρήστος Παππάς\Υπολογιστής\docx2pdfdemo.py", line 13, in <module>
    doc = word.Documents.Open(doc_path)
  File "C:/msys64\tmp\gen_py/3.9/00020905-0000-0000-C000-000000000046x0x8x5/Documents.py", line 93, in Open
    ret = self._oleobj_.InvokeTypes(19, LCID, 1, (13, 0), ((16396, 1), (16396, 17), (16396, 17), (16396, 17), (16396, 17), (16396, 17), (16396, 17), (16396, 17), (16396, 17), (16396, 17), (16396, 17), (16396, 17), (16396, 17), (16396, 17), (16396, 17), (16396, 17)),FileName
pywintypes.com_error: (-2147352567, 'Παρουσιάστηκε εξαίρεση.', (0, 'Microsoft Word', 'Δεν ήταν δυνατή η εύρεση του αρχείου.\r (C:\\//Users/Χρήστος%20Παππάς/Υπολογιστ...)', 'wdmain11.chm', 24654, -2146823114), None)

```

Greek to English translation:
Παρουσιάστηκε εξαίρεση = Exception occured
Δεν ήταν δυνατή η εύρεση του αρχείου. = The file can't be found.

**Comment by jeremyd2019** [comment]
I ran into an issue with BITS not liking forward slashes.  Can you try:
`$ MSYSTEM= python docx2pdfdemo.py` and see if it gives a different result?

**Comment by el07694** [comment]
`MSYSTEM= python docx2pdfdemo.py` opens the document successfully.

**Comment by jeremyd2019** [comment]
Great.  May need someone with more knowledge of the MINGW patches to Python to know how to make sure you get a backslashed, Windows-style path out of it, hopefully without the hack of clearing MSYSTEM on it.

**Comment by el07694** [comment]
I will try to ask in stackoverflow.
I will keep you in touch.

**Comment by el07694** [comment]
If i add `		FileName = os.path.abspath(FileName.replace("\\","")).replace("/","\\").replace("\\","\\\\",1)` before line 93 in file `C:/msys64\tmp\gen_py/3.9/00020905-0000-0000-C000-000000000046x0x8x5/Documents.py` (also with only filenames,absolute and relative paths i think). Also note you may import os at the top of the editted file.
That's a temporary solution i think :\

**Comment by jeremyd2019** [comment]
I would not recommend editing generated files

**Comment by MehdiChinoune** [comment]
python-pywin32 is now packaged https://packages.msys2.org/base/mingw-w64-python-pywin32
