### ISSUE TITLE
osgearth can be updated to version 3.1 with minimal fixes

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#7523]
Just updated the package, only requirement was stripping 
class OSGEARTH_EXPORT ShaderOptions : public ConfigOptions from patch since it is fixed upstream.
the refmap merge code from the patch is still useable.

PKGBUILD can also be cleaned a bit

```  for builddir in {Release,Debug}-${MINGW_CHOST}; do
    [[ -d ${builddir} ]] && rm -rf ${builddir}
    mkdir -p ${builddir}
    pushd ${builddir}

      msg "Building ${builddir%-${MINGW_CHOST}} version..."

      MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
      ${MINGW_PREFIX}/bin/cmake.exe \
        -G"MSYS Makefiles" \
        -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
        -DCMAKE_BUILD_TYPE=${builddir%-${MINGW_CHOST}} \
        -DOSG_DIR=${MINGW_PREFIX} \
        ../${_realname}-${_pkgver}

      make
    popd
  done`

**Comment by Biswa96** [comment]
Pull request is always welcomed!

**Comment by revelator** [comment]
Need to setup a fork first to make pull request from and im not at home atm.
osgbullet is a nogo unfortunatly last commit is 5 years old and the author has pointed out it needs a new maintainer so remove ?. osgworks while it builds is only used for osgbullet so might also be removed i guess ?.
changes to osgearth-3.1 are pretty trivial so if you dont want to wait for me to setup a fork for pull requests i can upload the new PKGBUILD and patch here.

**Comment by revelator** [comment]
pull request submitted.
