### ISSUE TITLE
qt5 broken by icu update

### ISSUE THREAD

**Issue by olafmandel** [msys2/MINGW-packages#7526]
After an update (`pacman -Suy`) that also included `mingw-w64-x86_64-icu 68.2-1`, the `uic.exe` no longer works as it is compiled against `libicuin67.dll` and `libicuuc67.dll`, but those were replaced by `libicuin68.dll` and `libicuuc68.dll`. I assume that a recompile of `mingw-w64-x86_64-qt5` will fix this (and that it is already in progress?).

But is there some way to prevent temporary breakages of packages like this, e.g. by extending the depends field to actually contain the version of the required libraries or by preventing an upload of new packages to the package mirrors until all packages depending on this are also recompiled)?

**Comment by Biswa96** [comment]
Qt is a huge package which requires +6h to build for each architecture. So it needs to be compiled in someone's machine. That process is going on (maybe). Meanwhile to downgrade icu version, you can download the old package tarball from pacman repository. Then install it with `pacman -U <file>` command. For example, here is the link of icu v67.1 https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-icu-67.1-1-any.pkg.tar.zst

**Comment by olafmandel** [comment]
@Biswa96 Thank you for the link, it helps while Qt is not yet recompiled. I was aware of the package size, this issue is mostly to make sure such a recompile is actually underway and to ask if these intermittend breakages in the system can be prevented in the future, e.g. by one of the two ideas I gave in the second paragraph.

**Comment by Biswa96** [comment]
The new Qt5 is in the pacman repository. You can now safely update it. The linked Qt5Core.dll is linked with icu 68.2.

```sh
$ ntldd /mingw64/bin/Qt5Core.dll | grep -i "icu"
        libicuin68.dll => F:\msys64\mingw64\bin\libicuin68.dll (0x0000000001cb0000)
        libicuuc68.dll => F:\msys64\mingw64\bin\libicuuc68.dll (0x0000000001400000)
```

**Comment by vasiliyaltunin** [comment]
Thanks, updated and worked just fine.
