### ISSUE TITLE
aws-sdk build error

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#7531]
fails on the git sync step for some reason i havent been able to determine.

**Comment by Biswa96** [comment]
There is not git command in the PKGBUILD file of that package.

**Comment by revelator** [comment]
no it seems to come from the source package itself, ill try and post the error when i do a build of it again.

**Comment by revelator** [comment]
```==> Starting build()...
-- Found Git: C:/Msys64/usr/bin/git.exe (found version "2.29.2") 
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as static objects
-- Generating windows build config
fatal: not a git repository: 'E:/mingw-w64-aws-sdk-cpp/src/aws-sdk-cpp-1.7.365/.git'
-- Building project version: 1.7.365
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Msys64/mingw32/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Msys64/mingw32/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: E:/mingw-w64-aws-sdk-cpp/src/build-i686-static/.deps
[1/24] Creating directories for 'AwsChecksums'
[2/24] Creating directories for 'AwsCCommon'
[3/24] Performing download step (git clone) for 'AwsChecksums'
Cloning into 'AwsChecksums'...
Note: switching to 'v0.1.5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 519d6d9 Don't return 0 on arm please (#22)
[4/24] No update step for 'AwsChecksums'
[5/24] Performing patch step for 'AwsChecksums'
FAILED: build/src/AwsChecksums-stamp/AwsChecksums-patch 
cmd.exe /C "cd /D E:\mingw-w64-aws-sdk-cpp\src\build-i686-static\.deps\build\src\AwsChecksums && patch -p1 < E:/mingw-w64-aws-sdk-cpp/src/aws-sdk-cpp-1.7.365/third-party/../../../BuildAwsChecksums.patch && C:\Msys64\mingw32\bin\cmake.exe -E touch E:/mingw-w64-aws-sdk-cpp/src/build-i686-static/.deps/build/src/AwsChecksums-stamp/AwsChecksums-patch"
Den angivne fil blev ikke fundet.
[6/24] Performing download step (git clone) for 'AwsCCommon'
Cloning into 'AwsCCommon'...
Note: switching to 'v0.4.42'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at fa67d3b IO handle ulimit stuff. (#637)
ninja: build stopped: subcommand failed.
CMake Error at CMakeLists.txt:224 (message):
  Failed to build third-party libraries.`

looks like a git submodule error ?.

**Comment by revelator** [comment]
There also seems to be some error with BuildAwsChecksums.patch not being found where it is supposed to be.

**Comment by revelator** [comment]
Ugh ok i found the culprit... this package cannot be built outside the PKGBUILD directory so setting BUILDDIR=somedir does not work.

**Comment by Biswa96** [comment]
In my PC that package build successfully. Those git warnings seems to be the side effect of the Patch-cmake-submodules.patch hack. /cc @kou

**Comment by revelator** [comment]
can you build it if you do BUILDDIR=/D makepkg-mingw -c -i --skippgp --nocheck ?
i can build it if i just do makepkg-mingw -c -i --skippgp --nocheck but it will fail if i set BUILDDIR

**Comment by kou** [comment]
aws-swk-cpp uses bundled (`externalproject` in CMake) aws-c-event-stream, aws-checksums and aws-c-common packages.
If we split them to each MINGW packages and use them as dependency, we will be able to fix this.

**Comment by Biswa96** [comment]
Those packages are seem to be small. I may try.

**Comment by Biswa96** [comment]
Those need some mingw style pampering in upstream. I will send discuss with upstream and add those packages after that.

**Comment by revelator** [comment]
thanks 👍

**Comment by Biswa96** [comment]
So, I have done this two ways. I am inclined towards second choice. But I would like to hear from you guys.

1. It is possible to create aws-c-event-stream, aws-checksums and aws-c-common packages and use to as dependencies. But those are little tiny packages ~100KB. I think this may create unnecessary traffic. And the dependencies are not shared with other packages.
2. Now this one is my choice. Download the tarball of aws-c-event-stream, aws-checksums and aws-c-common repositories at specific version. Patch the CMake file to use those instead of git. And we are good to go, no git error.

So, vote!

**Comment by Biswa96** [comment]
I have done this two ways. I am inclined towards second choice. But I would like to hear from you guys.

1. It is possible to create aws-c-event-stream, aws-checksums and aws-c-common packages and use to as dependencies. But those are little tiny packages ~100KB. I think this may create unnecessary traffic. And the dependencies are not shared with other packages.
2. Now this one is my choice. Download the tarball of aws-c-event-stream, aws-checksums and aws-c-common repositories at specific version. Patch the CMake file to use those instead of git. And we are good to go, no git error.

Now, select your option!

**Comment by kou** [comment]
Generally, I like 1. But 2. is OK with me if it works.

In other project (Apache Arrow), I selected 1. to pass more CMake flags (like ` CMAKE_INSTALL_LIBDIR`) to aws-c-event-stream, aws-checksums and aws-c-common. The current mingw-w64-aws-sdk-cpp package doesn't need to add more CMake flags to https://github.com/aws/aws-sdk-cpp/blob/master/CMakeLists.txt#L202-L214 for now. So we can select 2.
