### ISSUE TITLE
System header file <wtypes.h> uses "byte" instead of "BYTE", causing compiler errors

### ISSUE THREAD

**Issue by Dwedit** [msys2/MINGW-packages#7539]
I made a simple C program consisting only of this line:
`#include <dinput.h>`

After I try to build this with gcc, I get errors like this:
`/usr/include/w32api/wtypes.h:46:5: error: unknown type name ‘byte’`

When I look at wtypes.h, I see the type `byte` used for arrays.
But `byte` is not a standard type from Win32, `BYTE` is.

At the top of wtypes.h I see this line:
`/*** Autogenerated by WIDL 4.12.1 from include/wtypes.idl - Do not edit ***/`

So there must be a mistake somewhere in how the header files are being generated.
I see a pattern.  When it's plain, it's `BYTE`.  But if it's const, an array, or a pointer, its `byte`.

**Comment by Biswa96** [comment]
I made a simple C program only of these lines:

```c
#include <dinput.h>
int main() { }
```

And compiled it with `g++ -Wall test.cpp` without any error.

**Comment by Dwedit** [comment]
Okay, I am running "C:\msys64\mingw64.exe" to get the console.

I am using "gcc" as the command to compile the program.  I'm getting the problem.  I hope I don't need to reinstall the entire msys64 suite just to test this again.

**Comment by Biswa96** [comment]
I am not sure about your build environment. But your given error contains this `/usr/include/w32api/wtypes.h` file which is different than `/mingw64/x86_64-w64-mingw32/include` folder. There may be something mixed up.

**Comment by Dwedit** [comment]
Thanks, will investigate further to see what's going on.

**Comment by Dwedit** [comment]
Just checked, and if you execute this command: "pacman -S gcc" you get the files with that issue.

Meanwhile, if you use the command "pacman -S mingw64/mingw-w64-x86_64-gcc", you get gcc installed into "C:\msys64\mingw64\bin", and what appears to be Wine headers.

You also get a 'command not found' error if you simply type "gcc" into the msys2 command line.

**Comment by Biswa96** [comment]
Yes. msys2 and mingw are to different environment. You can find more information in main website https://www.msys2.org/

**Comment by Dwedit** [comment]
It's a bit deceptive that you run a file named "Mingw64.exe" and don't get a shell that runs mingw64 packages.
It appears that if you have to edit the .ini file, then uncomment the line `MSYS2_PATH_TYPE=inherit`, then suddenly mingw64 packages actually run.
Also a bit deceptive that if you use pacman to install a package named "gcc" you get a bugged installation.

Well, sorry, for posting a bug report about an unrelated package.  I just did what seemed logical (Install a package named "gcc"), and got a broken package.

**Comment by Biswa96** [comment]
> if you use pacman to install a package named "gcc" you get a bugged installation.

The "gcc" pacakge is for msys2 (like cygwin, an Unix _compatible layer_). It is not bugged. If you run the MSYS2 shortcut, the purple one that gcc will be used. Also there are difference between gcc and mingw-w64-*-gcc. For example:

* `/usr/bin/gcc.exe -v` has `Target: x86_64-pc-msys`
* `/mingw64/bin/gcc.exe -v` has `Target: x86_64-w64-mingw32`

**Comment by mingwandroid** [comment]
Where broken means something quite different from what you that it was..
