### ISSUE TITLE
about Python module support

### ISSUE THREAD

**Issue by juniorlove** [msys2/MINGW-packages#7543]
in MSYS2, Python has been downloaded via 'pacman' and so do its modules of 'numpy' and 'matplotlib'. Well, the .py file could not run for which the bash said 'No module named "numpy" or "matplotlib"'. On the other hand, the two modules of Python could either not install via 'pip' command. It is said that 'ERROR: Command errored out with exit status 1:' and so on.

So, the question is: how to deal with it? thx

**Comment by lazka** [comment]
make sure you are in the mingw64 shell when running python

**Comment by naveen521kk** [comment]
Works here for me. Everything should be inside of the mingw64 python though.
