### ISSUE TITLE
dlfcn shared lib no longer installed

### ISSUE THREAD

**Issue by ypsvlq** [msys2/MINGW-packages#7548]
c27ad107f7df624604c96f45d124b761b6fc0aa9 removes libdl.dll after it is built, this means that libtool will refuse to build shared libraries that use dlopen:

```
*** Warning: linker path does not have real file for library -ldl.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have
*** because I did check the linker path looking for a file starting
*** with libdl and none of the candidates passed a file format test
*** using a file magic. Last file checked: C:/msys64/mingw64/lib/libdl.a
```

Could it be restored, or at least made available in its own package?

**Comment by lazka** [comment]
Does it not use that static version then?

**Comment by ypsvlq** [comment]
It does, but it will then only build a static library.

**Comment by mingwandroid** [comment]
Why?

**Comment by mingwandroid** [comment]
Static libs can be linked to dlls and exes just fine..

**Comment by ypsvlq** [comment]
Yep, libtool just refuses to for reasons I don't understand.

**Comment by revelator** [comment]
lt_cv_deplibs_check_method=${lt_cv_deplibs_check_method='pass_all'} should shut it up.

**Comment by revelator** [comment]
it is a known problem with libtool on windows, on unix libtool uses file magic to get dependencies but this does not quite work on windows even though the tool can be build with mingw* it uses windows paths which confuses libtool so it is not normally included. The above is a workaround for cases like that, if you prefer to newer see this warning you can simply yank it into /mingw*/etc/config.site.

**Comment by ypsvlq** [comment]
Ah alright, thanks.

**Comment by lazka** [comment]
For some reason this now also affects gcc, it fails to build the libgomp DLL and outputs the same warning as above.
