### ISSUE TITLE
multiple definition error and others

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#7550]
I noticed a growing list of packages that fail to build because of this, ruby for one ->
`win32ole_method.o:win32ole_method.c:(.bss+0x18): multiple definition of `cWIN32OLE_VARIANT'; win32ole.o:win32ole.c:(.bss+0x18): first defined here`

also some packages that built previously have now suddenly turned up a list of undefined internal symbols ?!?
so i was wondering if anyone else sees this or if it is local to my installation.

**Comment by Alexpux** [comment]
@revelator yes I see this too and seems it related to patches for ALSR support

**Comment by revelator** [comment]
damn i thought i was going crazy 🤦 well that would probably need looking at i guess. Is martin storsjoe still on the job for the binutils package ?.

**Comment by jeremyd2019** [comment]
It kind of sounds like the [GCC 10 `-fcommon`](https://gcc.gnu.org/gcc-10/porting_to.html#common) thing.

**Comment by revelator** [comment]
hmm yeah i noticed that flag set in atleast one package, looks like we need it set in quite a few more then.

**Comment by revelator** [comment]
maybe set it globally via pacmans config files ? or would it possibly break other stuff.

**Comment by revelator** [comment]
yes atleast it fixes building boehm gc so should also work for the other packages.

**Comment by revelator** [comment]
from what i can read at the link you gave it seems some sources actually have there exports wrong and old gcc worked around that. I can understand this might happen since many of the tools and libraries we use are ports from nix so the devs might not be to used to how things are done on windows though it also means we would then have to supply patches to get around this or use compatibility flags like the one you pointed out.

**Comment by Alexpux** [comment]
@revelator I'm resolving multiple definitions by adding:
````
LDFLAGS+=" -Wl,--allow-multiple-definition"
````

**Comment by revelator** [comment]
Me2 in some cases atleast, though i had a few of those where it actually broke other things down the line so might not allways be safe i reckon.

**Comment by mati865** [comment]
> I can understand this might happen since many of the tools and libraries we use are ports from nix so the devs might not be to used to how things are done on windows though it also means we would then have to supply patches to get around this or use compatibility flags like the one you pointed out.

Lack of `extern` not Windows specific issue, nonconforming code will fail to build with GCC 10 on Linux too.

**Comment by revelator** [comment]
Oh it is not platform specific then, thats good to know.

**Comment by revelator** [comment]
If i figure out how to split pull requests i guess i know what ill be doing after new year.
