### ISSUE TITLE
libid3tag needs msys2 gperf

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#7551]
libid3tag turned up something weird it turned out it needs the msys2 gperf so if you have the mingw gperf in path it will fail to recreate the source files needed. 

I suggested that we create a conflicts flag for this package now that the issue is known.

**Comment by Alexpux** [comment]
@revelator we can't create conflict flag. Conflict is for resolving files conflicts installing in the same location. PacMan don't have flag for resolving build time conflicts

**Comment by revelator** [comment]
so it cannot remove a conflicting package ? ouch.
hmm would it be prudent to add a comment in the PKGBUILD script pointing out that mingw gperf breaks the build then ?.

**Comment by Alexpux** [comment]
Yes it cannot remove conflicting package at build time. Maybe better try to ask pacman developers.

**Comment by revelator** [comment]
Damn will do.

**Comment by mati865** [comment]
I doubt they will be able to help. Arch Linux packages are built in clean chroots (only packages from `{,make}dependencies` are installed) which is not doable on Windows.

**Comment by revelator** [comment]
guess we would have to leave a comment in the PKGBUILD script in case some user bangs his head on the same issue then.

**Comment by c72578** [comment]
Having this issue reported here is already valuable information. Searching the GitHub repo for keywords like libid3tag and gperf leads to the solution in here.

**Comment by revelator** [comment]
true enough.
