### ISSUE TITLE
libheif link error since update

### ISSUE THREAD

**Issue by lock042** [msys2/MINGW-packages#7554]
Since the last update of libheif there are several link issues with its dependencies:

[libheif.txt](https://github.com/msys2/MINGW-packages/files/5757006/libheif.txt)

**Comment by Biswa96** [comment]
Can you provide the project link that you are trying to build?

**Comment by lock042** [comment]
It happens with [GIMP](https://gitlab.gnome.org/GNOME/gimp/-/jobs/1066827), or my project [Siril](https://gitlab.com/free-astro/siril/-/jobs/942664060)

**Comment by Biswa96** [comment]
With `meson build; ninja`, Mine got linked with dynamic libheif.dll. How can I force to use static library?

**Comment by lock042** [comment]
I don't know. But what I can say is I can reproduce the issue trying to compile Siril on a msys2 environment.

**Comment by mati865** [comment]
This is what https://github.com/msys2/MINGW-packages/commit/f1c8c065208ec4a08b694c903d2e216d0534ba85 is trying to fix but it was not in the repo yet:
```
$ pacman -Ss heif
mingw32/mingw-w64-i686-libheif 1.10.0-1 [installed]
    HEIF image decoder/encoder library and tools (mingw-w64)
mingw64/mingw-w64-x86_64-libheif 1.10.0-1 [installed]
    HEIF image decoder/encoder library and tools (mingw-w64)
```

**Comment by lock042** [comment]
Ooooh. OK. I thought it was the opposite. I thought that this commit did introduced the bug.

**Comment by Biswa96** [comment]
Though the change in PKGBUILD introduce a sort of bug. I will add a PR quickly.

**Comment by Biswa96** [comment]
Now I can reproduce the output from your GitLab CI. In _my msys2 installation_, I don't know why, the libtool does not build dynamic library (.dll). It only builds static library shows this warning: linker path does not have real file for library. If I add `-laom -lde265 -lx265 -lrav1e -ldav1d` options in `Libs` list in `/minw64/lib/pkgconfig/libheif.pc` file siril compiles file. I am not sure if it has be done for static linking. Anyone deeply familiar with pkgconfig?

**Comment by Biswa96** [comment]
Now I can reproduce the output from your GitLab CI. In _my msys2 installation_, I don't know why, the libtool does not build dynamic library (.dll). It only builds static library and shows this warning: linker path does not have real file for library.

If I add `-laom -lde265 -lx265 -lrav1e -ldav1d` options in `Libs` list in `/mingw64/lib/pkgconfig/libheif.pc` file siril compiles fine. I am not sure if it has be done for static linking. Anyone deeply familiar with pkgconfig?

**Comment by novomesk** [comment]
FYI, the previous log from gimp build: https://github.com/strukturag/libheif/issues/414#issuecomment-753645943
