### ISSUE TITLE
[gedit]   dependencies  libicuin67.dll

### ISSUE THREAD

**Issue by zhujiang73** [msys2/MINGW-packages#7556]
gedit  dependencies  libicuin67.dll

mingw-w64-x86_64-gedit   dependencies   mingw-w64-x86_64-tepl5,   mingw-w64-x86_64-tepl5    dependencies   mingw-w64-x86_64-icu   

 pacman -Syu  update  mingw-w64-x86_64-icu 68.2,   gedit  dependencies  libicuin67.dll and libicuuc67.dll, but those were replaced by libicuin68.dll and libicuuc68.dll.

**Comment by revelator** [comment]
probably a lot of packages that need rebuilding.
