### ISSUE TITLE
problem in mingw64

### ISSUE THREAD

**Issue by maksim105** [msys2/MINGW-packages#7560]
make[1]: Entering directory '/c/Users/User/AppData/Roaming/OpenArena/baseoa/engine-master/engine-master'

Building in build/release-mingw64-x86_64:
  PLATFORM: mingw64
  ARCH: x86_64
  VERSION: 3.0.0a
  COMPILE_PLATFORM: mingw64
  COMPILE_ARCH: x86_64
  CC: cc

  CFLAGS:
    -std=gnu99 -DNO_VM_COMPILED -DNO_GZIP -Icode/zlib -DUSE_INTERNAL_JPEG
    -Icode/jpeg-8c -DUSE_LOCAL_HEADERS -DSTANDALONE -DPRODUCT_VERSION="3.0.0a"
    -Wformat=2 -Wno-format-zero-length -Wformat-security -Wno-format-nonliteral
    -Wstrict-aliasing=2 -Wmissing-format-attribute -Wdisabled-optimization
    -Werror-implicit-function-declaration -MMD -DNDEBUG -O3

  CLIENT_CFLAGS:
    -DUSE_OPENAL -DUSE_OPENAL_DLOPEN -DUSE_CURL -DUSE_CURL_DLOPEN
    -DUSE_CODEC_VORBIS -DUSE_CODEC_XMP -DUSE_CODEC_OPUS -DOPUS_BUILD
    -DHAVE_LRINTF -DFLOATING_POINT -DUSE_ALLOCA -Icode/opus-1.1/include
    -Icode/opus-1.1/celt -Icode/opus-1.1/silk -Icode/opus-1.1/silk/float
    -Icode/opusfile-0.5/include -Icode/libogg-1.3.1/include
    -DUSE_RENDERER_DLOPEN -DUSE_MUMBLE -DUSE_VOIP -DFLOATING_POINT -DUSE_ALLOCA
    -Icode/libspeex/include

  SERVER_CFLAGS:
    -DUSE_VOIP

  LDFLAGS:

  LIBS:

  CLIENT_LIBS:
    -lvorbisfile -lvorbis -lxmp

  Output:
    oa_ded.x86_64
    openarena.x86_64
    renderer_openarena1_x86_64.so
    renderer_opengl2_x86_64.so
    baseoa/cgamex86_64.so
    baseoa/qagamex86_64.so
    baseoa/uix86_64.so
    missionpack/cgamex86_64.so
    missionpack/qagamex86_64.so
    missionpack/uix86_64.so

make[2]: Entering directory '/c/Users/User/AppData/Roaming/OpenArena/baseoa/engine-master/engine-master'
DED_CC code/sys/con_tty.c
code/sys/con_tty.c:58:15: warning: useless storage class specifier in empty declaration
   58 | static struct termios ;
      |               ^~~~~~~
code/sys/con_tty.c: In function 'CON_Input':
code/sys/con_tty.c:514:56: warning: comparison between pointer and integer
  514 |   if( (STDIN_FILENO + 1, &fdset, NULL, NULL, &timeout) == -1 || !(STDIN_FILENO, &fdset))
      |                                                        ^~
LD build/release-mingw64-x86_64/oa_ded.x86_64
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x82): undefined reference to `__imp_getaddrinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0xfd): undefined reference to `__imp_freeaddrinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x173): undefined reference to `gai_strerrorA'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x19c): undefined reference to `__imp_freeaddrinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x316): undefined reference to `__imp_gethostname'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x399): undefined reference to `__imp_getaddrinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x3af): undefined reference to `__imp_freeaddrinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x54b): undefined reference to `__imp_getnameinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x736): undefined reference to `__imp_WSAGetLastError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0xda2): undefined reference to `__imp_getnameinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0xe92): undefined reference to `__imp_ntohs'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0xf12): undefined reference to `__imp_ntohs'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x10b2): undefined reference to `__WSAFDIsSet'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x10d4): undefined reference to `__WSAFDIsSet'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1104): undefined reference to `__WSAFDIsSet'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x113c): undefined reference to `__imp_recvfrom'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1220): undefined reference to `__imp_recvfrom'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1310): undefined reference to `__imp_recvfrom'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1382): undefined reference to `__imp_WSAGetLastError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1442): undefined reference to `__imp_WSAGetLastError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x14b2): undefined reference to `__imp_WSAGetLastError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1594): undefined reference to `__imp_sendto'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x15fe): undefined reference to `__imp_sendto'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x160a): undefined reference to `__imp_WSAGetLastError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x16f2): undefined reference to `__imp_sendto'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x19bf): undefined reference to `__imp_getnameinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1ad8): undefined reference to `__imp_socket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1af8): undefined reference to `__imp_ioctlsocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1b22): undefined reference to `__imp_setsockopt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1b6c): undefined reference to `__imp_bind'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1b95): undefined reference to `__imp_htons'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1be8): undefined reference to `__imp_closesocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1c22): undefined reference to `__imp_WSAGetLastError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1c66): undefined reference to `__imp_WSAGetLastError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1c78): undefined reference to `__imp_closesocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1d06): undefined reference to `__imp_socket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1d26): undefined reference to `__imp_ioctlsocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1d5b): undefined reference to `__imp_setsockopt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1dab): undefined reference to `__imp_bind'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1e0d): undefined reference to `__imp_htons'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1e63): undefined reference to `__imp_closesocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1e92): undefined reference to `__imp_WSAGetLastError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1ece): undefined reference to `__imp_WSAGetLastError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x1ee0): undefined reference to `__imp_closesocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x203c): undefined reference to `__imp_setsockopt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x204f): undefined reference to `__imp_setsockopt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x20c9): undefined reference to `__imp_ntohs'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x2112): undefined reference to `__imp_closesocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x2158): undefined reference to `__imp_closesocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x218c): undefined reference to `__imp_closesocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x21bc): undefined reference to `__imp_setsockopt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x220d): undefined reference to `__imp_socket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x222f): undefined reference to `__imp_gethostbyname'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x2254): undefined reference to `__imp_htons'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x228d): undefined reference to `__imp_connect'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x22d5): undefined reference to `__imp_send'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x22f4): undefined reference to `__imp_recv'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x2a67): undefined reference to `__imp_closesocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x2aa6): undefined reference to `__imp_closesocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x2ac4): undefined reference to `__imp_closesocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x2b7d): undefined reference to `__imp_closesocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x2bb2): undefined reference to `__imp_WSAStartup'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x2c37): undefined reference to `__imp_WSACleanup'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.text+0x2e23): undefined reference to `__imp_select'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/net_ip.o:net_ip.c:(.rdata$.refptr.in6addr_any[.refptr.in6addr_any]+0x0): undefined reference to `in6addr_any'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/release-mingw64-x86_64/ded/sys_unix.o:sys_unix.c:(.text+0x1a93): undefined reference to `wait'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:2343: build/release-mingw64-x86_64/oa_ded.x86_64] Error 1
make[2]: Leaving directory '/c/Users/User/AppData/Roaming/OpenArena/baseoa/engine-master/engine-master'
make[1]: *** [Makefile:1288: targets] Error 2
make[1]: Leaving directory '/c/Users/User/AppData/Roaming/OpenArena/baseoa/engine-master/engine-master'
make: *** [Makefile:1232: release] Error 2

**Comment by mingwandroid** [comment]
It needs to link to ws2_32

**Comment by mingwandroid** [comment]
But this is an upstream issue most likely and should be reported there.
