### ISSUE TITLE
Patching Python's tempfile module

### ISSUE THREAD

**Issue by naveen521kk** [msys2/MINGW-packages#7564]
I would like the python's module [`tempfile`](https://docs.python.org/3/library/tempfile.html), to create temp directories and files in the temp dir of msys2 and not that of the default one.

Currently it works like
```py
>>> import tempfile
>>> tempfile.mkdtemp()
'C:/Users/USER/AppData/Local/Temp/tmpzurle3ps'
```

My expectation is it should work like

```py
>>> import tempfile
>>> tempfile.mkdtemp()
'C:\msys64\tmp\tmpzurle3ps'
```

**Comment by Biswa96** [comment]
I am not Python expert but I think the output is somewhat correct. Programs in /mingw64 or /mingw32 are native to Windows so `$TEMP` becomes Windows' `%TEMP%`.

**Comment by lazka** [comment]
You have many options for changing the location of tempdir, see:https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir

We don't change the upstream behavior unless there is a good reason, so -1 from me.

**Comment by naveen521kk** [comment]
Thanks, I myself now things this isn't required.
