### ISSUE TITLE
does mingw scons actualy work ?

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#7584]
im getting an error that g++ cannot execute cc1plus when trying to build godot-cpp.

**Comment by lazka** [comment]
yeah, it worked here https://github.com/msys2/MINGW-packages/pull/7381 but then something broke it

**Comment by revelator** [comment]
Ok at first i was wondering if it picked up the msys2 g++ instead of the mingw version but even removing it still causes it to fail so it has to be something else.

**Comment by revelator** [comment]
argh it even picks up the cross compiler O_o in /opt have to remove both then it works again.
The problem is that scons does not accept path to compiler so it looks for any compiler on path and defaults to /usr even in mingw builds.

**Comment by lazka** [comment]
There is a new scons release, we should give it a try. https://github.com/SCons/scons/releases/tag/4.1.0

**Comment by revelator** [comment]
same error unfortunatly :/

**Comment by revelator** [comment]
It might have to do with this ->
`MINGW_DEFAULT_PATHS = []
if sys.platform == 'win32':
    MINGW_DEFAULT_PATHS = [
        r'C:\msys64',
        r'C:\msys'
    ]`

the cygwin default paths have it right

`CYGWIN_DEFAULT_PATHS = []
if sys.platform == 'win32':
    CYGWIN_DEFAULT_PATHS = [
        r'C:\cygwin64\bin',
        r'C:\cygwin\bin'
    ]`

without the mingw bin paths the scons program just randomly searches for default paths and sadly this means any compiler in /usr/bin will take precedence.

**Comment by lazka** [comment]
Fixed in #7848

**Comment by revelator** [comment]
hmm im getting a strange bug with 4.1.0 seems some man scripts dont exist or fail to build.

**Comment by revelator** [comment]
here is the error -> error: can't copy 'build/doc/man/scons.1': doesn't exist or not a regular file

**Comment by revelator** [comment]
got around it by disabling these in setup.cfg

```
[options.data_files]
. = build/doc/man/scons.1
    build/doc/man/scons-time.1
    build/doc/man/sconsign.1
```

**Comment by lazka** [comment]
do you build from the PKGBUILD?

**Comment by revelator** [comment]
yes

**Comment by revelator** [comment]
wait a sec... somehow this was not updated in the PKGBUILD -> ${MINGW_PREFIX}/bin/python scripts/scons.py doc
seems to work after adding it manually.

**Comment by lazka** [comment]
It's here https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-scons/PKGBUILD#L28 so a problem on your side?

Can this be closed then?

**Comment by revelator** [comment]
maybe a hickup from git ? did a git revert on the package and the rest of the changes where there after.

one small problem though, the man files are placed in the root of the mingw dir so i did a small change to put them where they need to be.

```
package() {
  cd "${srcdir}/${_realname}-${pkgver}"

  MSYS2_ARG_CONV_EXCL="--prefix=;--install-scripts=;--install-platlib=;--install-purelib=;--install-data=" \
    ${MINGW_PREFIX}/bin/python setup.py install --prefix=${MINGW_PREFIX} --root="${pkgdir}" --optimize=1

  PREFIX_WIN=$(cygpath -m ${MINGW_PREFIX})
  sed -s "s|${PREFIX_WIN}/bin/||g" -i "${pkgdir}${MINGW_PREFIX}/bin/scons-configure-cache-script.py"
  sed -s "s|${PREFIX_WIN}/bin/||g" -i "${pkgdir}${MINGW_PREFIX}/bin/scons-script.py"
  sed -s "s|${PREFIX_WIN}/bin/||g" -i "${pkgdir}${MINGW_PREFIX}/bin/sconsign-script.py"

  # scons seems to place these in the root of /mingw*
  mkdir -p ${pkgdir}${MINGW_PREFIX}/share/man/man1
  mv -f ${pkgdir}${MINGW_PREFIX}/scons-time.1 ${pkgdir}${MINGW_PREFIX}/share/man/man1/scons-time.1
  mv -f ${pkgdir}${MINGW_PREFIX}/scons.1 ${pkgdir}${MINGW_PREFIX}/share/man/man1/scons.1
  mv -f ${pkgdir}${MINGW_PREFIX}/sconsign.1 ${pkgdir}${MINGW_PREFIX}/share/man/man1/sconsign.1

  install -D -m644 LICENSE "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}/LICENSE"
}
```

**Comment by lazka** [comment]
ah, right, weird, let's leave this open then so we don't forget.

**Comment by revelator** [comment]
That seems reasonable 👍

**Comment by revelator** [comment]
found the fix on fedora.

```
build() {
  cd "${srcdir}/${_realname}-${pkgver}"

  # only need to build doc (or rather man) here.
  ${MINGW_PREFIX}/bin/python scripts/scons.py doc
}

package() {
  cd "${srcdir}/${_realname}-${pkgver}"
  # could probably do without setting scriptdir as scons allready puts these in the right place eg. ${MINGW_PREFIX}/bin.
  # datadir points to where the man files should be located (taken from fedora).
  MSYS2_ARG_CONV_EXCL="--prefix=;--install-scripts=;--install-platlib=;--install-purelib=;--install-data=" \
    ${MINGW_PREFIX}/bin/python setup.py install --prefix=${MINGW_PREFIX} --install-scripts=${MINGW_PREFIX}/bin --install-data=${MINGW_PREFIX}/share/man/man1 --root="${pkgdir}" --optimize=2

  PREFIX_WIN=$(cygpath -m ${MINGW_PREFIX})
  sed -s "s|${PREFIX_WIN}/bin/||g" -i "${pkgdir}${MINGW_PREFIX}/bin/scons-configure-cache-script.py"
  sed -s "s|${PREFIX_WIN}/bin/||g" -i "${pkgdir}${MINGW_PREFIX}/bin/scons-script.py"
  sed -s "s|${PREFIX_WIN}/bin/||g" -i "${pkgdir}${MINGW_PREFIX}/bin/sconsign-script.py"

  install -D -m644 LICENSE "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}/LICENSE"
}
```

build is mostly unnessesary only use it to prebuild the man files.
use --install-data to point to the man dir.
builds and works just fine after these changes.

**Comment by lazka** [comment]
yeah. but the man generation needs java, which we dont have

**Comment by revelator** [comment]
well i can build it no problem ?!? and i dont have java at all so wtf...

**Comment by revelator** [comment]
only builds the man files but that should be ok, pdf's are skipped automatically if tool is not found (which btw is weird since it seems to look for xpdf which we do have O_o). Only difference in my system from the official is that i use the older sgml based docbook tools in msys2 (ported from cygwin)

**Comment by lazka** [comment]
when it can't find the build tools it creates dummy empty man pages

**Comment by revelator** [comment]
ah ok, i see.
