### ISSUE TITLE
[nimble] Nimble complains about missing DLLs

### ISSUE THREAD

**Issue by Rummskartoffel** [msys2/MINGW-packages#7585]
After installing Nimble using `pacman -S mingw-w64-i686-nimble`, when trying to call it, it prints
```
$ nimble
could not load: (libcrypto-1_1|libeay32).dll
```
and exits. This can be fixed by manually installing `mingw-w64-i686-openssl`. Maybe that package should be added as a dependency for Nimble?

**Comment by Biswa96** [comment]
Hi! @Rummskartoffel Thank you for reporting this issue. I have sent a pull request to fix this issue and also to update nimble version. The actual package update will take time after the PR is accepted. You can watch this website for package update news https://packages.msys2.org/updates or you could download the _unsigned_ packages from the GitHub Actions artifacts in the linked pull request.
