### ISSUE TITLE
PYTHONHOME is hardcoded into python or one of its packages

### ISSUE THREAD

**Issue by ChinouneMehdi** [msys2/MINGW-packages#7599]
I tried to build a c++ program that uses sip (mingw-w64-x86_64-sip + mingw-w64-x86_64-python-pyqt5 ) for python bindings.
Build success but tests related to python bindings fails in my machine.
```
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'D:/dev/scidavis/build/mingw-orig/scidavis/scidavis.exe'
  sys.base_prefix = 'D:/a/_temp/msys/msys64/mingw64'
  sys.base_exec_prefix = 'D:/a/_temp/msys/msys64/mingw64'
  sys.executable = 'D:/dev/scidavis/build/mingw-orig/scidavis/scidavis.exe'
  sys.prefix = 'D:/a/_temp/msys/msys64/mingw64'
  sys.exec_prefix = 'D:/a/_temp/msys/msys64/mingw64'
  sys.path = [
    'D:/a/_temp/msys/msys64/mingw64/lib/python38.zip',
    'D:/a/_temp/msys/msys64/mingw64/lib/python3.8',
    'D:/a/_temp/msys/msys64/mingw64/lib/python3.8',
    'D:/a/_temp/msys/msys64/mingw64/lib/lib-dynload',
  ]
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001e98 (most recent call first):
<no Python frame>
```
I have decided to push it to GitHub and run it with github-actions. The tests passed!
I suspected that my msys2 installation is corrupted so I did a clean installation of it, but nothing changed. which led me to think that PYTHONHOME is somehow hardcoded into python or one of its packages. I reinstall msys2 under the same folder as GitHub actions `D:\a\_temp\msys\msys64`, the tests now passed.

the C++ project:
https://github.com/ChinouneMehdi/scidavis/tree/develop
the instructions to build it is in https://github.com/ChinouneMehdi/scidavis/blob/develop/.github/workflows/main.yml#L121

**Comment by Biswa96** [comment]
@lazka 

```sh
$ cd /mingw64/bin; grep -Iir _temp
...
python-config:prefix="D:/a/_temp/msys/msys64/mingw64"
python3-config:prefix="D:/a/_temp/msys/msys64/mingw64"
python3.8-config:prefix="D:/a/_temp/msys/msys64/mingw64"
...
```

**Comment by lazka** [comment]
@Biswa96 it replaces those at runtime, so shouldn't be a problem.

@ChinouneMehdi we'd need a smaller reproducer. Where is that output coming from?

**Comment by ChinouneMehdi** [comment]
> @ChinouneMehdi we'd need a smaller reproducer. Where is that output coming from?

After building the project and running the tests using : `ctest --output-on-failure` on my machine.

**Comment by ChinouneMehdi** [comment]
I have created a new branch `pythonhome` and run github-actions to demonstrate the failure.
the first build uses setup-msys action default installation folder `D:\a\_temp\msys\msys64` (release=true) while the second uses the preinstalled one `C:\msys64` (release=false), as you can see the tests passed on the first one and failed on the second.
https://github.com/ChinouneMehdi/scidavis/runs/1655727063?check_suite_focus=true#step:7:7

**Comment by ChinouneMehdi** [comment]
The tests passed after I set PYTHONPATH
```
export PYTHONPATH=/mingw64/lib/python3.8:/mingw64/lib/python3.8/site-packages:/mingw64/lib/python3.8/lib-dynload
```

**Comment by mingwandroid** [comment]
@lazka it's the executable that does this, or the dll. I suspect that @ChinouneMehdi  has placed the python dll alongside the other dlls instead of where it's meant to be? in FSH-like relative location to this qt linked exe or dll.

**Comment by lazka** [comment]
No idea what's the prefix path based on (haven't looked). But that could be it, yes.

**Comment by ChinouneMehdi** [comment]
I have created a small project to reproduce the bug.
https://github.com/ChinouneMehdi/python_mingw_bug
No dependencies other than python3.

**Comment by ChinouneMehdi** [comment]
Setting 'PYTHONHOME=/mingw64' either as an environment variable or by calling `Py_SetPythonHome` before `Py_Initialize` resolves the problem.

**Comment by mingwandroid** [comment]
I believe that is the correct approach here anyway. Closing. Thanks for the report and investigation!
