### ISSUE TITLE
python-distlib: has msvc compiled executables

### ISSUE THREAD

**Issue by naveen521kk** [msys2/MINGW-packages#7607]
for some reasons, [this](https://files.pythonhosted.org/packages/2f/83/1eba07997b8ba58d92b3e51445d5bf36f9fba9cb8166bcae99b9c3464841/distlib-0.3.1.zip) source archive contains msvc compiled executable, which are use in `pip` .
[source](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-python-distlib/PKGBUILD) doesn't compile the executable though.

**Comment by Biswa96** [comment]
In ArchLinux's [PKGBUILD][1], there is `rm distlib/*.exe` in prepare step.

[1]: https://github.com/archlinux/svntogit-community/blob/packages/python-distlib/trunk/PKGBUILD

**Comment by naveen521kk** [comment]
Those exe files are useless in Linux but those are used by Pip in windows.

**Comment by Biswa96** [comment]
Where are the source code of those executables? Is it possible to download and compile those source code in build step?

**Comment by naveen521kk** [comment]
It is included inside the tar archive just that we aren't compiling it.

**Comment by lazka** [comment]
We have a similar issue in setuptools. Note that we patch the launcher in setuptools to handle our directory layout, we might need to do something similar here.

@naveen521kk do you know when these executables are installed?

**Comment by naveen521kk** [comment]
> @naveen521kk do you know when these executables are installed?

`pip` uses this library internally, I think, I don't know exactly. What I can link now is this doc [here](https://distlib.readthedocs.io/en/stable/reference.html#the-distlib-scripts-package). I don't know anything more than this.

**Comment by lazka** [comment]
ok, thanks

**Comment by lazka** [comment]
Looks like it's used when installing wheels which have entry points, to create corresponding launchers.

**Comment by mingwandroid** [comment]
These are the 'standard' python launcher executables.

**Comment by mingwandroid** [comment]
On Anaconda Distro on Windows we build these exes (with GCC because well, I did it) and package them with conda-build: https://github.com/conda/conda-build/tree/master/conda_build/launcher_sources

When conda-build then builds a python package with entry points, these are used instead.

In general, on Windows, a Python entry point consists of two parts, <foo>-script.py and <foo>.exe. This is the foo.exe and the name of the excecutable file is used to determine the name of the script file which is then launched through python.

**Comment by mingwandroid** [comment]
.. usually you'll have two exes, one for cli scripts and one for GUI scripts that use the appropriate subsystem.

**Comment by naveen521kk** [comment]
@mingwandroid I think both the thing you are talking about and the one in python-distlib is different I think.
The one you are talking about is `py.exe` right? But python-distlib is about python scripts to exe files. I may be wrong though.

**Comment by naveen521kk** [comment]
Python-distlib launcher.c: https://bitbucket.org/pypa/distlib/src/master/PC/launcher.c
Python's `py.exe` `laucher.c` https://github.com/python/cpython/blob/master/PC/launcher.c

**Comment by mingwandroid** [comment]
They are more or less the same thing. They both create stub exes. One is just an earlier fork off the other. Same author.

**Comment by mingwandroid** [comment]
On conda we use a hybrid with our own changes. We compile the launchers for conda with mingw-w64 gcc actually because the exe is smaller that way.

**Comment by naveen521kk** [comment]
Tried compiling the included script using this bash script
```bash
#!/usr/bin/env bash
set -e
rm -f *.o
rm -f *.res
rm -f *.exe
RCFILE=$(dirname ${BASH_SOURCE[0]})/launcher.rc
for _BITS in 64 32; do
  [[ -f resources-${_BITS}.res ]] && rm -f resources-${_BITS}.res
  PATH=/mingw${_BITS}/bin:$PATH windres --input ${RCFILE} --output resources-${_BITS}.res --output-format=coff
  for _TYPE in cli gui; do
    if [[ ${_TYPE} == cli ]]; then
      CPPFLAGS="-D_CONSOLE -DNDEBUG -DWIN32"
      LDFLAGS=
      NAME=t
    else
      CPPFLAGS="-D_WINDOWS -DNDEBUG -DWIN32"
      LDFLAGS=""
      NAME=w
    fi
    PATH=/mingw${_BITS}/bin:$PATH gcc ${CPPFLAGS} launcher.c -c -o ${NAME}${_BITS}.o
    PATH=/mingw${_BITS}/bin:$PATH gcc -mcrtdll=msvcr120 ${LDFLAGS} ${NAME}${_BITS}.o resources-${_BITS}.res -o ${NAME}${_BITS}.exe -lshlwapi
  done
done
ls -l *.exe
echo "Debug this from cmd.exe via:"
echo "set PYLAUNCH_DEBUG=1"
```
see the attached zip file [distlib.zip](https://github.com/msys2/MINGW-packages/files/5888384/distlib.zip) for how my directory structure looks.
