### ISSUE TITLE
post install mingw-w64-x86_64-adwaita-icon-theme error

### ISSUE THREAD

**Issue by lygstate** [msys2/MINGW-packages#7611]
## Describe the issue

installing mingw-w64-x86_64-adwaita-icon-theme...
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_ukxpLS/.INSTALL; post_install 3.38.0-2 ) failed to execute correctly
clean install msys2
```

export PKG="diffutils git grep make pkg-config sed
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-sphinx
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_image
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-glib2
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-jemalloc
          mingw-w64-x86_64-lzo2
          mingw-w64-x86_64-zstd
          mingw-w64-x86_64-libjpeg-turbo
          mingw-w64-x86_64-pixman
          mingw-w64-x86_64-libgcrypt
          mingw-w64-x86_64-libpng
          mingw-w64-x86_64-libssh
          mingw-w64-x86_64-libxml2
          mingw-w64-x86_64-snappy
          mingw-w64-x86_64-libusb
          mingw-w64-x86_64-usbredir
          mingw-w64-x86_64-libtasn1
          mingw-w64-x86_64-nettle
          mingw-w64-x86_64-cyrus-sasl
          mingw-w64-x86_64-curl
          mingw-w64-x86_64-gnutls
          mingw-w64-x86_64-libnfs"
pacman  --noconfirm -S --needed $PKG


```

**Comment by lazka** [comment]
The error shouldn't cause any problems. I need to think about how to handle the cyclic dependency between adwaita and gtk for the update hook.

Arch doesn't handle this either sadly...

**Comment by lygstate** [comment]
> The error shouldn't cause any problems. I need to think about how to handle the cyclic dependency between adwaita and gtk for the update hook.
> 
> Arch doesn't handle this either sadly...

Yeap, it's doesn't cause problem, just for note there is such error: output

**Comment by lazka** [comment]
ok, my plan here is to add an install script to gtk-update-icon-cache and update the cache for all themes, and remove the install script from adwaita.

**Comment by revelator** [comment]
Quite a lot of cyclic dpendencies in the package base atm, makes it a living nightmare to create from scratch if needed.
