### ISSUE TITLE
gtk2 build problem

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#7614]
```
C:/Msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot export gdk_keyval_convert_case: symbol not defined
C:/Msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot export gdk_keyval_from_name: symbol not defined
C:/Msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot export gdk_keyval_name: symbol not defined
C:/Msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot export gdk_test_render_sync: symbol not defined
C:/Msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot export gdk_test_simulate_button: symbol not defined
C:/Msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot export gdk_test_simulate_key: symbol not defined
C:/Msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/gdk.o:gdk.c:(.text+0x3c6): undefined reference to `IA__gdk_display_open'
C:/Msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/gdk.o:gdk.c:(.text+0x422): undefined reference to `IA__gdk_display_open'
C:/Msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/gdkapplaunchcontext.o:gdkapplaunchcontext.c:(.text+0x10a): undefined reference to `IA__gdk_display_get_name'
C:/Msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/gdkapplaunchcontext.o:gdkapplaunchcontext.c:(.text+0x125): undefined reference to `IA__gdk_screen_make_display_name'
C:/Msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/gdkcolor.o:gdkcolor.c:(.text+0xce): undefined reference to `IA__gdk_colormap_get_type'
```

this is on win10 new install completely barebones with no other compiler in path.

**Comment by lazka** [comment]
with the PKGBUILD or what?

There is a new/final gtk2 release out: 2.24.33

**Comment by revelator** [comment]
Aye with PKGBUILD and it also happens with the latest version :/

**Comment by revelator** [comment]
If i understand the problem correctly from a few others who have had similar errors on linux it seems to be caused by the gtk3 package.

**Comment by lazka** [comment]
#7615 seems to work. also locally.

**Comment by revelator** [comment]
I can try building it  again but i doubt it it fixed here, since by the look of it it does not happen regularily.

**Comment by revelator** [comment]
Still the same but i found a workaround add this flag to configure and it works -> --disable-visibility.
--disable-visibility should only affect elf binaries from what i read but it works so huh ?!?.

**Comment by lazka** [comment]
I noticed the tarball ships some .def files, maybe deleting those helps?

**Comment by revelator** [comment]
tried that first but no cigar unfortunatly :/ the above flag works fine though i wonder why.

**Comment by lazka** [comment]
Not sure. I don't want to spend time looking into gtk2 tbh :)

**Comment by revelator** [comment]
well it is an easy enough fix and does not seem to affect anything negatively so might just add this flag to configure in PKGBUILD.
But ultimatly it is up to you :)

**Comment by lazka** [comment]
that seems to change some macros.. not sure.

another random guess: do you have mingw perl installed? try not to

**Comment by revelator** [comment]
Nope no mingw perl installed unfortunatly, might be libelf since i do have that one installed, but does gtk2 even try to add this as a dependency ?.

**Comment by revelator** [comment]
Should be safe i reckon --disable-visibility just removes the -PIC flag from the build and -PIC does not seem to work correctly on windows anyhow.

**Comment by mati865** [comment]
AFAIK `-fPIC` should do nothing on Windows.

**Comment by revelator** [comment]
Indeed which was also why i was a bit surprised that adding this flag allowed it to build.

**Comment by revelator** [comment]
Well something had screwed over my build environment it would seem, my replacement mainboard arrived a few days ago and after reinstalling win10 qt5 built again so maybe gtk2 will to. Still it is maybe worth holding onto in case someone else runs into the same problem.

**Comment by revelator** [comment]
And a hint to others, dont mix msvc compilers and msys2/mingw* even if you use a clean PATH cmake will in many cases still pick up msvc and then try to compile your code using msvc sdk's using gcc/g++ which wont work. Packages that are affected by this are numerous and it can be hell to figure out because the compiler is rather vague in some instances as to what the problem is.

**Comment by revelator** [comment]
sadly it still is failing even on a clean windows install :S adding the flag above fixes it though so now you need to figure out if you want to use it.

**Comment by revelator** [comment]
well it turns out setting -fPIC does in fact do something on windoze... it breaks compiling :facepalm:
not sure when this behaviour changed but as an experiment try setting it in a gcc build and watch the horror show :P
