### ISSUE TITLE
-G'Ninja' vs -G'MSYS Makefiles'

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#7620]
If I use 'Ninja' generator, I have error:

`kernels/core_dtrsmsp.c:23:10: fatal error: pastix_dlrcores.h: No such file or directory`

but if I use 'MSYS Makefiles' there is no this error.

How can I fix it for 'Ninja'?

**Comment by Biswa96** [comment]
Which package or program?

**Comment by 3rav** [comment]
This:
https://github.com/Kabbone/PaStiX4CalculiX/tree/cudaless

**Comment by mati865** [comment]
How is it related to MSYS2?

**Comment by 3rav** [comment]
Currently it is not, I am trying to build a package. I know Ninja is preferred, so I'm looking for a solution.

**Comment by mati865** [comment]
Ninja is preferred but it's not deal breaker, does that project build on Linux with Ninja?

**Comment by 3rav** [comment]
Related error: https://github.com/msys2/MINGW-packages/issues/6952

**Comment by 3rav** [comment]
Adding the code below to CMakeLists.txt helped:
```
add_dependencies (pastix_kernels
   kernels_headers_tgt
) 
```

**Comment by Biswa96** [comment]
If I stick to the topic CMake can not find wxWidgets with Ninja, but can find it with MSYS Makefiles.
