### ISSUE TITLE
[mathgl]  Cannot use MSYS2 build with FLTK

### ISSUE THREAD

**Issue by mayd** [msys2/MINGW-packages#7636]
Even though MSYS2 packages for MathGL and FLTK is installed I cannot compile a MathGL C program to use FLTK.
The following compiler error messageis displayed:

C:/msys64/mingw64/include/mgl2/Fl_MathGL.h:34:10: fatal error: mgl2/fltk.h: No such file or directory
   34 | #include <mgl2/fltk.h>
      |          ^~~~~~~~~~~~~
compilation terminated.

I was unable to rebuild the MSYS2 MathGL package with option "enable-fltk".

Can anyone suggest how to do this?

**Comment by Biswa96** [comment]
Would you like to check if the linked pull request fixes your issue?

**Comment by mayd** [comment]
After rebuilding the MathGL package with the updated PKGBUILD script you created, I found the following:

I tested some of the examples built as part of the MathGL package.

Initially I did find some problems with incorrect DLLs being loaded due to the PATH setting but I identified those 
using a dependency tracker and I believe they were all fixed.

The MathGL source included example which generates a set of files containing PNG images (mgl_example.exe) worked.

None of the other examples worked. Specifically, the FLTK example program (mgl_fltk_example.exe) hangs without
displaying anything.  The remaining examples also hang.

My own FLTK example which I copied from the MathGL documentation also does not build.

Compiler command line: 
g++ mgl_fltk_ex1.cpp -o mgl_fltk_ex1 -Wl,-subsystem,windows -lmgl2 -lmgl2-fltk

Result:
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): in function `main':
C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:4: mgl_fltk_ex1] Error 1

Possibly, there is an error in the above ommand line but it is similar to the one given in the MathGL documentation (which
also did not work)


(FYI MathGL 2.4.1 + FLTK 1.3.5 works as documented in MathGL documentation under Ubuntu Linux. )

**Comment by mayd** [comment]
To add to my earlier comments:

FYI The MSYS2 FLTK package itself works - I have built and successfully tested a number of small example programs with it.
Similarly, the MSYS2 Qt5 package also works - I have built and successfully tested nearly all of the QtCreator examples.

The updated MSYS2 MathGL package built using the updated PKGBUILD script only works for generating image files (PNG
format) - I successfully ran the supplied example mgl_example.exe.

The updated MSYS2 MathGL package does not work with any of the enabled GUI toolkits FLTK, Qt, OpenGL.  The suppplied
example programs: mgl_fltk_example.exe, mgl_glut_example.exe, mgl_qt_example.exe - all hang without displaying anything.
Also none of the compiled MathGL utilities work: mglconv.exe, mgllab.exe, mgltask.exe, mglview.exe, udav.exe all hang when 
started and no window is displayed.

**Comment by mayd** [comment]
I can report some success!

I experimented with a couple of non-working MathGL executables and that let me to try building the package
with OpenMP disabled. 

Both Mingw32 and Mingw64 versions of MathGL packages work under MSYS2 if built with OpenMP disabled.

**Comment by mayd** [comment]
I installed and tested latest version (2.4.4-3) of packages mingw-w64-i686-mathgl and mingw-w64-x86_64-mathgl
from packages.msys2.org. All the MathGL utilities and all the examples for FLTK, Qt5, OpenGL GUI toolkits, plus my
own examples, work under mingw32 and mingw64 - except for the multithreading examples, which was expected.
