### ISSUE TITLE
plplot-fortran missing in mingw-w64-x86_64-plplot

### ISSUE THREAD

**Issue by vmagnin** [msys2/MINGW-packages#7664]
Hi,
plplot-fortran and the Fortran examples seem to have disappeared from mingw-w64-x86_64-plplot:
https://packages.msys2.org/package/mingw-w64-x86_64-plplot?repo=mingw64
But they are available in the i686 package:
https://packages.msys2.org/package/mingw-w64-i686-plplot?repo=mingw32

I need plplot-fortran to interface my gtk-fortran project with plplot.
Thanks if you can help.

**Comment by Biswa96** [comment]
Yikes! There may be some glitch happen between package update and upload. The last GitHub Actions artifacts of plplot contains those Fortran files but not in the pacman repository.

**Comment by lazka** [comment]
Here is the build run: https://github.com/msys2/msys2-autobuild/runs/1683294647?check_suite_focus=true

for some reason it doesn't even look for fortran stuff

**Comment by MehdiChinoune** [comment]
likely fixed.
