### ISSUE TITLE
[v8] Needs Rebuilt Against ICU v68

### ISSUE THREAD

**Issue by neptoess** [msys2/MINGW-packages#7667]
v8 has [icu](https://packages.msys2.org/package/mingw-w64-x86_64-icu) as a dependency. The latest version in pacman was built against v67, i.e. libicu*67.dll. The icu package is now on v68, i.e. libicu*68.dll. Can the v8 package be updated to link against this new version? I currently have to use `pacman -U` to download to the v67 icu package for v8 to work.

**Comment by lazka** [comment]
looks like this was forgotten, thanks
