### ISSUE TITLE
python update (3.8.7-1 => 3.8.7-2) breaks python 

### ISSUE THREAD

**Issue by h-c-mueller** [msys2/MINGW-packages#7681]
I updated mingw-w64-i686-python from 3.8.7-1 => 3.8.7-2 and cannot anymore start python:
```
$ python
Fatal Python error: init_stdio_encoding: failed to get the Python codec name of the stdio encoding
Python runtime state: core initialized
LookupError: unknown encoding: cp28591

Current thread 0x00003ab4 (most recent call first):
<no Python frame>
```
Python works again after downgrading to 3.8.7-1.

**Comment by Biswa96** [comment]
I can not reproduce your issue in my setup. Python works as usual.

**Comment by lazka** [comment]
I guess this is my fault. I'll have a look

**Comment by lazka** [comment]
Do you have any idea why your console encoding is cp28591? It's not the default at least. Is this with a mintty terminal, or something g different?

**Comment by fabiangreffrath** [comment]
Similar error here:
```
# gedit
Fatal Python error: init_stdio_encoding: failed to get the Python codec name of the stdio encoding
Python runtime state: core initialized
LookupError: unknown encoding: cp0

Current thread 0x00004518 (most recent call first):
<no Python frame>
```

**Comment by fabiangreffrath** [comment]
This is from a mintty terminal with Locale set to C and Character set set to UTF-8 in the Text options.

**Comment by lazka** [comment]
ok, I'll revert.

what's your output of `chcp.com`?

**Comment by h-c-mueller** [comment]
I have mintty with ISO 8859-1, ref. picture. 
(But strangely since about three weeks the symbol in the task bar when started is not the usual one).
![mingw32-python](https://user-images.githubusercontent.com/22730269/104889495-9837cb00-596e-11eb-9ad7-ca065ef20e2b.png)

**Comment by h-c-mueller** [comment]
```
$ chcp.com
Aktive Codepage: 28591.
```

**Comment by lazka** [comment]
thanks.

**Comment by h-c-mueller** [comment]
I'm using Windows 10.

**Comment by fabiangreffrath** [comment]
```
# chcp.com
Aktive Codepage: 28605.
```
Windows 10

**Comment by h-c-mueller** [comment]
Can you please trigger building of 3.8.7-3. It is in git but no package is generated yet.
