### ISSUE TITLE
Qt5.14.2-3 C:/msys64/mingw64/bin/uic.exe: error while loading shared libraries: libstdc++-6.dll 

### ISSUE THREAD

**Issue by adisuciu** [msys2/MINGW-packages#7711]
I need qt5.14.2-3 because latest breaks another part of the build 
After installing qt5.14.2-3 using  

> pacman -U https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-qt5-5.14.2-3-any.pkg.tar.zst

I try to build the project and i get 
```
C:/msys64/mingw64/bin/uic.exe -o C:/build_64/ui_walkingpattern.h C:/projects/scopy/ui/patterns/walkingpattern.ui
C:/msys64/mingw64/bin/rcc.exe --name aboutpage --output C:/build_64/qrc_aboutpage.cpp C:/build_64/aboutpage.qrc
C:/msys64/mingw64/bin/uic.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

The uic error depends on where I run the uic executable from but it's either
> error while loading shared libraries: ?: cannot open shared object file: No such file or directory

or
> error while loading shared libraries: libstdc++-6.dll : cannot open shared object file: No such file or directory

This approach used to work just fine about a month ago. Do you know anything I could try ?

Full log for reference: https://ci.appveyor.com/project/adisuciu/scopy/builds/37353694

-Adrian

**Comment by mingwandroid** [comment]
There isn't much you can do here. MSYS2 is a rolling distro by design and sticking with old things will only work if you avoid updating or installing things with pacman.

If anyone has an old MSYS2 setup on which this stuff still works I'd recommend backing it up. Otherwise have a look at trying old packages from around the same date in your pacman package caches.

**Comment by adisuciu** [comment]
There were some issues in the past with libicu compatibility. The package is only 6 months old, I thought there was something we could do. 

Either way, we'll try either backing up a full msys2 system(we don't get latest and greatest), moving to latest qt(we'll have to patch other dependencies for it to work)  or worst case handpicking packages that used to work (this involves a lot of trial and error which we did in the past and I'd rather avoid)

If you have any more suggestions, let me know.
-Adrian

**Comment by mingwandroid** [comment]
> because latest breaks another part of the build

Do you have details about that?

**Comment by adisuciu** [comment]
The first roadblock is that we're using a feature branch of qwt called qwt-multiaxis ( https://github.com/osakared/qwt/tree/qwt-6.1-multiaxes ). Ideally this branch should be part of the qwt mainline.
This branch was not updated to qt5.15 and it gives out some include errors. I'll have to patch those manually to continue the build. There were some errors further down the line but I can't remember them right now (with qt 5.15). I'll let you know if I find anything else.

-Adrian
