### ISSUE TITLE
libunwind lead to glog can't use

### ISSUE THREAD

**Issue by cathaysia** [msys2/MINGW-packages#7804]
The first case:

```cmake
find_package(glog CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME}  libglog)
```

```cpp
#include <glog/logging.h>
int main(int argc, char** argv){
    google::InitGoogleLogging(argv[0]);
    LOG(FATAL) << "haha";
}
```

Then a runtime error:

```
libunwind:      pc not in table, pc=0xFFFFFFFFFFFFFFFF
F0125 17:14:27.198827  7324 main.cpp:7] haha
libunwind:      pc not in table, pc=0xFFFFFFFFFFFFFFFF
*** Check failure stack trace: ***
libunwind:      pc not in table, pc=0xFFFFFFFFFFFFFFFF
    @   00000000663079e0  _ZN6google10LogMessage9SendToLogEv
    @   0000000066303711  _ZN6google10LogMessage5FlushEv
    @   0000000066308229  _ZN6google15LogMessageFatalD1Ev
    @   00000000004015cd  (unknown)
    @   00000000004013c1  (unknown)
    @   00000000004014f6  (unknown)
    @   00007ffe85c67034  BaseThreadInitThunk
    @   00007ffe863bd0d1  RtlUserThreadStart
```
===========================================================================
The case 2：
```cmake
find_package(glog CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME}  glog::glog)
```
Then, when make it:

```
[proc] run command: C:/msys64/mingw64/bin/cmake.exe --build d:/***/build --config Debug --target *** -- -j 10
[build] ninja: error: '/mingw64/lib/libunwind.a', needed by '***.exe', missing and no known rule to make it
[build] generate over，return code is 1
```

But libunwind.a in its dir already.

**Comment by revelator** [comment]
move libunwind.dll.a and libunwind.a out of /mingw*/lib temporarily while building glog and use gcc/g++ instead.
only way to get around this it seems.

**Comment by cathaysia** [comment]
It not works when I using FetchContent also. I think it maybe a bug of glog or g++...
At the first case, I seem print FATAL only, not debug, info and warning although it can pass compile.
```cmake
include(FetchContent)
FetchContent_Declare(
   glog
   GIT_REPOSITORY git@gitee.com:mirrors/glog.git
   GIT_TAG v0.4.0
   SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/download_deps/glog
)
FetchContent_MakeAvailable(glog)
```

**Comment by revelator** [comment]
strange it works here if i do that ?!?.

**Comment by revelator** [comment]
Hmm i seem to remember some workaround for gcc to not use libunwind by default but it will have to be rebuilt, just need to find the correct flag to set again urgh...

**Comment by cathaysia** [comment]
emm, maybe it's a bug of Ninja, it seem that ninja had some problem on windows, but upstream has no plan to fixed it...

Here has a issues of this. Not about glog, but no different.
https://github.com/ninja-build/ninja/issues/1909

**Comment by cathaysia** [comment]
It works when I use MSVC +  NMake just now. But I not sure mingw has this problem yet still (I uninstall it....).

**Comment by cathaysia** [comment]
emm, I don't know how to build glog in msys2. But I guess libunwind are required by gflags? Maybe we can use -DWITH_GFLAGS=OFF ?

**Comment by cathaysia** [comment]
emm, I don't know how to build glog in msys, but may be we can remove:

```cmake
# line 122
find_library (UNWIND_LIBRARY NAMES unwind DOC "unwind library")
# line 475
  target_link_libraries (glog PUBLIC ${UNWIND_LIBRARY})
```
