### ISSUE TITLE
tox's dependency on virtualenv is commented out?

### ISSUE THREAD

**Issue by ktbarrett** [msys2/MINGW-packages#7815]
tox (the python package) depends on virtualenv, but that dependency was commented out in 08a0fc40a07ac54caaef73fd89ddd39660924c5d (see [here](https://github.com/msys2/MINGW-packages/blob/d32a248f2b780d556c7d09f6afe2f2f3dd037951/mingw-w64-python-tox/PKGBUILD#L18)).

Without this dependency tox fails to run.

```
kaleb@DESKTOP-2CHBMVI MINGW64 ~/cocotb
$ tox -e py38-linux
.tox create: C:/msys64/home/kaleb/cocotb/.tox/.tox
ERROR: invocation failed (exit code 1), logfile: C:/msys64/home/kaleb/cocotb/.tox/.tox/log/.tox-0.log
================================== log start ==================================
C:/msys64/mingw64/bin/python.exe: No module named virtualenv

=================================== log end ===================================
ERROR: InvocationError for command C:/msys64/mingw64/bin/python.exe -m virtualenv --no-download --python C:/msys64/mingw64/bin/python.exe .tox (exited with code 1)
```

**Comment by eine** [comment]
FTR, some recent issues with tox on MSYS2: #7014.

**Comment by ktbarrett** [comment]
Thanks for the info. I see this is still an ongoing issue that is being tracked. No need for duplicate issues.
