### ISSUE TITLE
ocaml update problem

### ISSUE THREAD

**Issue by Optiligence** [msys2/MINGW-packages#7816]
updating mingw-w64-x86_64-ocaml to 4.11.1-1 results in

>mingw-w64-x86_64-ocaml: /mingw64/bin/flexlink.exe exists in filesystem (owned by mingw-w64-x86_64-flexdll)

from
>mingw-w64-x86_64-ocaml 4.04.0-1
>mingw-w64-x86_64-flexdll 0.34-2

**Comment by lazka** [comment]
@ImperatorS79

**Comment by MehdiChinoune** [comment]
Should be fixed now.
