### ISSUE TITLE
python-numpy: Illegal instruction (x86_64)

### ISSUE THREAD

**Issue by podsvirov** [msys2/MINGW-packages#7827]
Illegal instruction when importing 64-bit package, but all good with 32-bit.

```bash
user@host MSYS ~
$ pacman -Ss python-numpy
mingw32/mingw-w64-i686-python-numpy 1.19.5-2 [installed]
    Scientific tools for Python (mingw-w64)
mingw64/mingw-w64-x86_64-python-numpy 1.19.5-2 [installed]
    Scientific tools for Python (mingw-w64)
```

```bash
user@host MINGW64 ~
$ python
Python 3.8.7 (default, Jan 18 2021, 21:09:34)  [GCC 10.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Illegal instruction

user@host MINGW64 ~
$
```

```bash
user@host MINGW32 ~
$ python
Python 3.8.7 (default, Jan 18 2021, 20:48:42)  [GCC 10.2.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.19.5'
>>>
```

**Comment by naveen521kk** [comment]
I can reproduce this.
Maybe does triggering a rebuild fix this?

**Comment by naveen521kk** [comment]
I wonder what does this `Illegal instruction` mean though.

**Comment by podsvirov** [comment]
I rebuilt the package locally, but that didn't fix the problem.

**Comment by mati865** [comment]
Cannot reproduce with up to date MSYS2. What CPUs do you have?

> 
> 
> I wonder what does this `Illegal instruction` mean though.

It often means the instruction is not supported by the CPU or panic inside panic (Rust terminology).

**Comment by Biswa96** [comment]
Disclaimer: I have zero idea how python works at low level.

So, I have run `F:\msys64\mingw64\bin\python3.exe -c "import numpy"` in debugger. I follow the libpython3.8.dll, into that Py_Main -> Py_RunMain -> PyRun_SimpleStringFlags -> PyRun_StringFlags, then bam! instruction pointer stops at libopenblas.dll. It stops at `vmovaps` instruction.

```asm
libopenblas:000000006EC58E63 vmovaps xmmword ptr [rsp+170h], xmm6
libopenblas:000000006EC58E6C vmovaps xmmword ptr [rsp+180h], xmm7
libopenblas:000000006EC58E75 vmovaps xmmword ptr [rsp+190h], xmm8
libopenblas:000000006EC58E7E vmovaps xmmword ptr [rsp+1A0h], xmm9
libopenblas:000000006EC58E87 vmovaps xmmword ptr [rsp+1B0h], xmm10
```

According to Intel, `vmovaps` instruction falls into AVX512 set, Icelake/Skylake CPUs ([link][1]). If `TARGET=CORE2` option is added in openblas make command it limits the specific CPU extensions. ArchLinux has that option enabled. Here is the commit https://github.com/archlinux/svntogit-community/commit/04b8c2abcf8300d294a1b85ca7de99af3e087678 and related issue https://github.com/xianyi/OpenBLAS/issues/3043

A pull request is sent to fix this issue ☝️ 

[1]: https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=vmovaps

**Comment by naveen521kk** [comment]
Now I wonder what CPU you use @mati865?
I use a pretty much old one... Mine is `Intel(R) Core(TM) i3-2100 CPU`.

**Comment by mati865** [comment]
> According to Intel, `vmovaps` instruction falls into AVX512 set, Icelake/Skylake CPUs ([link](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=vmovaps)).

Those are AVX instructions supported by Sandy Bridge/Bulldozer and newer.
In `naveen521kk` case they are supported by the CPU so there must be something else (or they are disabled in BIOS/UEFI), #7830 will help though.



> 
> 
> Now I wonder what CPU you use @mati865?
> I use a pretty much old one... Mine is `Intel(R) Core(TM) i3-2100 CPU`.

Ryzen 7 2700X

**Comment by ustsv** [comment]
- AMD K10 Illegal instruction
- Sandy Illegal instruction
- Skylake work fine
The problem is in openblas. I solved it by simply rebuilding it with the new libwinpthread.

**Comment by podsvirov** [comment]
Oops. @Biswa96 I did not notice your #7830 and created my #7841.

I confirm that simply rebuilding the package does not help. Specifying the `TARGET=CORE2` solves the problem for me. And this does not negatively affect the 32-bit package.

**Comment by podsvirov** [comment]
Thanka to all for solve the problem!

**Comment by podsvirov** [comment]
This is not really about this topic, but maybe you know someone who can help advance in resolving the [issue](https://github.com/coin3d/coin/issues/440)?
