### ISSUE TITLE
binutils 2.36 breaks ar when running from command prompt

### ISSUE THREAD

**Issue by xim** [msys2/MINGW-packages#7890]
Just upgraded binutils. All uses of `ar` result in this message when running from command prompt:

`c:\msys64\mingw64\lib\bfd-plugins\libdep.a is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000012f.`

Minimal reproduction:
```
# From msys or git bash
touch empty.c
gcc -c -o empty.o empty.c
ar -rc libempty.a empty.o # Great success!
# Then from command prompt in the same folder
ar -rc libempty.a empty.o
```

Running the command from a git bash / msys 2prompt works. Running it from a cmd window gives the message. Running it in msys2 invoking `cmd /c 'ar -rc [...]'` works fine, and surprisingly also when invoking `\msys64\usr\bin\bash -c "ar -rc [...]"` from the command prompt

Downgrading to binutils `2.35.1-3` resolves the issue. Both `2.36-1` and `2.36-3` exhibit this behaviour.

**Comment by Biswa96** [comment]
What is your current working directory aka. `$PWD`? How do you able to access `ar` from cmd? Did you add anything to `$PATH` or `%PATH%`?

**Comment by xim** [comment]
It happens in any folder I run it (`%TEMP%`, `C:\Users\xim\Desktop`...) and regardless of whether or not I have `ar` in my `PATH` or execute it using full path.

I move `ar.exe` to `ar_.exe` and made this horrible .bat file that I placed as `\msys64\mingw64\bin\ar.bat` to work around:

```
@set dirname=%~dp0
@set dirname=%dirname:\=/%
@set args=%*
@set args=%args:\=/%
@%dirname%..\..\usr\bin\bash -c "exec %dirname%ar_ %args%"
```

**Comment by xim** [comment]
Actually, just removing the `bfd-plugins` folder also works. Don't know if I'm missing out on anything important when I remove it, though?

**Comment by lazka** [comment]
I can't reproduce, this works

```
set PATH=C:/msys64/mingw64/bin;%PATH
ar -rc libempty.a empty.o
```

**Comment by oltolm** [comment]
Can confirm.

**Comment by Astrum-polaris** [comment]
libdep is a new plugin that is only present in binutils 2.36 (not exists in binutils 2.35)

> Actually, just removing the `bfd-plugins` folder also works. Don't know if I'm missing out on anything important when I remove it, though?

bfd-plugins folder also contains the lto plugin, so removing the entire folder may break lto

I can confirm removing `/mingw64/lib/bfd-plugins/libdep.a` solves this problem

If I remove `--disable-shared` in binutils PKGBUILD and rebuild, `libdep.dll` and `libdep.dll.a`  are installed instead of `libdep.a`

I guess if you try to run ar in command prompt, files in `/mingw64/lib/bfd-plugins` are loaded as dll, so if something that is not dll presents in that directory, it will fail with a error message like you posted.

**Comment by xim** [comment]
> bfd-plugins folder also contains the lto plugin, so removing the entire folder may break lto

Good that you pointed that out for those that use lto =)

We have a decent workaround, then, as it isn't likely that many use libdep yet.

**Comment by revelator** [comment]
hmm cant reproduce either though after the upgrade i now get a lot of warnings about dllwrap being deprecated especially when building python packages.

**Comment by PBfordev** [comment]
I confirm the issue.

**Comment by xim** [comment]
I don't have a bunch of Windows machines lying around, but the one I do have is a Windows 10 virtual machine with Windows 10 Enterprise version 20H2 build 19042.746. It's a fairly minimal install, and has the very latest MSYS64 updates. I can provide additional details as requested.

**Comment by zufuliu** [comment]
libdep.a is still in lib\bfd-plugins folder for mingw-w64-x86_64-binutils-2.36.1-1.
Reproduce the Windows error message dialog (in command prompt, Win10 20H2 19042.746):
```
git clone --depth=1 https://github.com/zufuliu/notepad2.git
cd build\mingw
mingw32-make -j4
```

**Comment by lazka** [comment]
Removed that plugin now. Sorry for the delay.

**Comment by abrodkin** [comment]
FWIW that's an entry in Bintuils' bug-tracker - https://sourceware.org/bugzilla/show_bug.cgi?id=27113.

**Comment by lazka** [comment]
Thanks

**Comment by TheBearodactyl** [comment]
having this error too (sorry for the necropost)

**Comment by TheBearodactyl** [comment]
> Actually, just removing the `bfd-plugins` folder also works. Don't know if I'm missing out on anything important when I remove it, though? **Edit**: Apparently, I don't use [libdep](https://sourceware.org/binutils/docs/ld/libdep-Plugin.html)

nvm, this worked, thanks
