### ISSUE TITLE
uasm: should this be a git package?

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#7893]
I just ran into a source file verification error trying to build uasm.  It was downloading a github archive, so I figured that something internally to github changed, but then I couldn't even find the tag.  Turns out that the PKGBUILD is downloading an archive for a branch, not a tag.  It seems like this should really be a git package (not sure on the current best practice for renaming to -git though).

**Comment by Biswa96** [comment]
You could use a commit hash from upstream. Also I think you don't have to change the package name. See thr ghdl package as example.
