### ISSUE TITLE
emacs print print-buffer gives permission denied

### ISSUE THREAD

**Issue by cppljevans** [msys2/MINGW-packages#7896]
$ uname -a
MINGW64_NT-10.0-19042 DESKTOP-INGIU3B 3.1.7-340.x86_64 2020-11-08 12:32 UTC x86_64 Msys

evansl@DESKTOP-INGIU3B MINGW64 /mingw64/share/emacs

I start emacs with:

  emacs&

then open a simple text file, and then hit the File>print, but then, on status line, it says
  'permission denied c:/<some_cryptic_file_name>'
What must I do to get print to work?  In windows FileExplorer, I open the .txt with Notepad
can print without problem to the default printer.

which lpr shows not found.

**Comment by dr-scsi** [comment]
This is not a bug related to Msys2 but to Emacs itself on Windows.  Please check [this thread](https://lists.gnu.org/archive/html/bug-gnu-emacs/2022-01/msg02209.html) which came up shortly.  This is the relevant part in [Emacs manual](https://www.gnu.org/software/emacs/manual/html_mono/emacs.html#Windows-Printing).

I think this report can be closed here.

**Comment by dr-scsi** [comment]
@lazka - See my comment above.  This is an Emacs issue and not related to Msys2.
