### ISSUE TITLE
How do I manually verify package signatures?

### ISSUE THREAD

**Issue by HolyBlackCat** [msys2/MINGW-packages#7897]
I'm on Linux, I use MSYS2 packages for cross-compiling.

Since none of the programs depending on `msys-2.0.dll` seem to run under Wine (including `pacman`), I made [a script](https://github.com/HolyBlackCat/quasi-msys2) that automates package downloading.

I was wondering, how can I verify package signatures without `pacman`? Would appreciate any help.

**Comment by Biswa96** [comment]
Have you tried with any GNU/Linux distribution with pacman as the main package manger? If you want to cross compile then using msys2's mingw compiler in wine seems to be heavier than running cross compiler which host is Linux platform. Also there is a huge lobby for mingw-w64 packages for pacman based distros here https://github.com/Martchus/PKGBUILDs

**Comment by jeremyd2019** [comment]
the files (package files and DBs) are PGP signed, in detached signatures with the same name + ".sig".  The trusted signing keys are in the `msys2-keyring` package, whose source is https://github.com/msys2/MSYS2-keyring

**Comment by HolyBlackCat** [comment]
@Biswa96 Normally I don't use the compilers, just the libraries. I compile with a native Clang.

@jeremyd2019 Thanks, will try it.

**Comment by HolyBlackCat** [comment]
Ended up with following commands:
`wget https://raw.githubusercontent.com/msys2/MSYS2-keyring/master/msys2.gpg` to download the keyring.
`gpg --batch --yes -o msys2.kbx --dearmor msys2.gpg` to convert it to a binary format.
`gpg --batch --yes --no-default-keyring --keyring ./msys2.kbx --trust-model always --verify FILE.sig FILE` to verify the file.
If the last command returns `0`, the signature is valid.

**Comment by jeremyd2019** [comment]
On Sat, 6 Feb 2021, Egor wrote:

> `wget https://raw.githubusercontent.com/msys2/MSYS2-keyring/master/msys2.gpg` to download the keyring.

Caution: I looked at this a bit, and I believe revoked keys are also
present in that keyring.  I am not sure how they are supposed to be
handled.
