### ISSUE TITLE
binutils-2.36 howto disable dynamicbase ?

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#7910]
noticed it now defaults to allways having nxcompat and dynamicbase on, but something strange here if i use -Wl,--disable-dynamicbase the resulting compile still has all flags set ?!? same if i use -Wl,--disable-dynamicbase,--disable-nxcompat. the flags refuse to turn off.

**Comment by jeremyd2019** [comment]
Works for me...

```
$ g++ -std=c++11 -o test.exe test.cpp
$ peflags -v test.exe
test.exe: coff(0x0106[+executable_image,+line_nums_stripped,+32bit_machine]) pe(0x0140[+dynamicbase,+nxcompat])
$ g++ -std=c++11 -Wl,--disable-dynamicbase,--disable-nxcompat -o test.exe test.cpp
$ peflags -v test.exe
test.exe: coff(0x0106[+executable_image,+line_nums_stripped,+32bit_machine]) pe(0x0000)
```

**Comment by revelator** [comment]
Thats strange then peview shows me that nxcompat and dynamicbase are on on my compiled executables even if i pass these flags.
I noticed some pkg-config files had saved these flags but my project does not use them so that should not be it unless some config files also saved these flags and passes them to my project.

**Comment by mati865** [comment]
Your build system is overriding your LDFLAGS.

**Comment by revelator** [comment]
Aye that seems to be it, since the makepkg conf files still have the old unnessesary flags.

**Comment by mati865** [comment]
`makepkg_mingw{32,64}.conf` do not affect any build system unless you are building through `makepkg-mingw` command.

**Comment by revelator** [comment]
i was, i was experimenting with a new package.

**Comment by lazka** [comment]
We will eventually remove the LDFLAGS from makepkg.conf, but I'd prefer to wait until things settle a bit.

**Comment by revelator** [comment]
Thats ok, at least i now know where it came from.
