### ISSUE TITLE
python: Unprefixed windres causing problems in cross-compiling

### ISSUE THREAD

**Issue by longnguyen2004** [msys2/MINGW-packages#7948]
In patch 1800, we hardcoded an unprefixed `windres` to compile the resource files.

https://github.com/msys2/MINGW-packages/blob/c72bdebdc0ee73918f73a924b3e8ecb9d621972d/mingw-w64-python/1800-link-win-resource-files-and-build-pythonw.patch#L31-L38

This is incorrect when we're cross-compiling, where it's required to use a prefixed `windres` to ensure the resulting object file is in the correct format. Instead, we should use autoconf to find the correct `windres`.

**Comment by Biswa96** [comment]
I think you are looking for similar thing here https://github.com/msys2/MINGW-packages/issues/6608

**Comment by longnguyen2004** [comment]
Currently we are working around it by symlinking the prefixed `windres`, but I would like to see it fixed the "proper" way, which is using autoconf detection. I can make a PR if you need, unless there is a specific reason why it is that way.

**Comment by lazka** [comment]
PR welcome. Please try to keep changes minimal though.

**Comment by Biswa96** [comment]
@Alexpux provided a reason in the linked issue.

**Comment by Biswa96** [comment]
Is this only for python? Mostly autoconf just figures out itself like following:

```
checking for x86_64-w64-mingw32-ranlib... no
checking for ranlib... ranlib
checking whether ln -s works... no, using cp -pR
checking whether make sets $(MAKE)... yes
checking for x86_64-w64-mingw32-ar... ar
checking for x86_64-w64-mingw32-strip... no
checking for strip... strip
checking for x86_64-w64-mingw32-nm... no
checking for nm... nm
checking if make is GNU make... yes
checking for dependency tracking method... gcc
checking for x86_64-w64-mingw32-windres... no
checking for windres... windres
```

**Comment by longnguyen2004** [comment]
Yes this is only for python, because someone has hardcoded the unprefixed `windres` in the Makefile (see above), and not detect it through autoconf.

**Comment by lazka** [comment]
I've created #7958

**Comment by longnguyen2004** [comment]
Thanks for the fix!
