### ISSUE TITLE
gtk4  gstreamer dependency?

### ISSUE THREAD

**Issue by peterbud** [msys2/MINGW-packages#7950]
I might be totally off, but as I see gtk4 package has a dependency on `gst-plugins-bad`, which alone means a 1GB dependency, while it seem to me that the build configuration actually disables gstreamer:
`-Dmedia-gstreamer=disabled`

So the question is: is it really needed to have the `gstreamer `dependency for this gtk4 package?

**Comment by lazka** [comment]
> I might be totally off, but as I see gtk4 package has a dependency on `gst-plugins-bad`, which alone means a 1GB dependency, while it seem to me that the build configuration actually disables gstreamer:
> `-Dmedia-gstreamer=disabled`

true, that's a bug

> So the question is: is it really needed to have the `gstreamer `dependency for this gtk4 package?

I'd say yes. But I doubt it needs all those plugins in gst-plugins-bad, probably only the libraries. Arch splits it up in libraries and plugins, maybe we should do that too.

Are you concerned for packaging reasons or for pacman download reasons? (The later will hopefully be fixed soon with a new server)

**Comment by peterbud** [comment]
Thanks @lazka. My primary concern was the packaging. I have tried to install gtk4 and suddenly I saw pacman wanted to install 1GB, so I went and checked what was behind that.

So if you could make sure that gtk4 package has the _real_ dependencies, and maybe a few optional dependencies (like the bunch of rarely needed plugins), that would be much appreciated by many people I believe.

**Comment by lazka** [comment]
ok. The thing is it's not always clear what *real* dependencies are. If you happen to use gtk4 to play a rare video format you might need some obscure plugin to decode it. But yeah, splitting like Arch seems worth it in this case.

In quodlibet where I have to deal with all of gstreamer I delete all plugins I don't need and then run a script: https://github.com/quodlibet/quodlibet/blob/master/dev-utils/win_installer/misc/depcheck.py which deletes all unreferenced DLLs.

**Comment by lazka** [comment]
I've fixed the gtk4 build in #7952, and there was a dependency pulling in the toolchain via libunwind which is fixed by #7959

**Comment by peterbud** [comment]
Many thanks for the quick replies. 

I was thinking how much sense would it make the following dependency structure for gtk4 with regards to gstreamer:
* gstreamer
* gst-plugins-base
* gst-plugins-good
* optional: gst-plugins-bad

This way you can ensure that OOB gtk4 would be able to use gstreamer and playback the most common video formats. If somebody is looking for obscure formats, they can install gst-plugins-bad or even gst-plugins-ugly.

Admittedly I don't know too much about gstreamer, so apologies if this above does not make sense.

PS: as a sidenote I have seen that gst-plugins-good is [dependent on gtk3](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gst-plugins-good/PKGBUILD#L22), which seems strange and I don't see similar dependency in Arch packages

**Comment by peterbud** [comment]
Many thanks for the quick replies. 

I was thinking how much sense would it make the following dependency structure for gtk4 with regards to gstreamer:
* gstreamer
* gst-plugins-base
* gst-plugins-good
* optional: gst-plugins-bad

This way you can ensure that OOB gtk4 would be able to use gstreamer and playback the most common video formats. If somebody is looking for obscure formats, they can install gst-plugins-bad or even gst-plugins-ugly.

Admittedly I don't know too much about gstreamer, so apologies if this above does not make sense.

PS: as a sidenote I have seent that gst-plugins-good is [dependent on gtk3](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gst-plugins-good/PKGBUILD#L22), which seems strange and I don't see similar dependency in Arch packages

**Comment by lazka** [comment]
Not having gst-plugins-bad installed makes gtk4 apps no start and quit with an error. So if that is wanted it needs to be fixed upstream.

**Comment by peterbud** [comment]
OK, thanks!

**Comment by lazka** [comment]
(Note that splitting plugins-bad into libs and plugins is still an option)

**Comment by lazka** [comment]
Fixed in #9120
