### ISSUE TITLE
mingw-w64-x86_64-python3-setuptools, sed error

### ISSUE THREAD

**Issue by mallgrab** [msys2/MINGW-packages#7953]
If the installation location of msys2 contains a space such as ```C:\Program Files\MSYS2\mingw64``` sed breaks and it wont find easy_install-script.py.

```
sed: can't read C:/Program: No such file or directory
sed: can't read Files/MSYS2/mingw64/bin/easy_install-script.py: No such file or directory
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_UGj9oo/.INSTALL; post_upgrade 51.3.1-1 51.3.1-1 ) failed to execute correctly
```

**Comment by Biswa96** [comment]
Try to install msys2 in a folder which does not contain space. In this case, `Program Files` has a space.

**Comment by naveen521kk** [comment]
If you are using the latest setuptools there shouldn't be a `easy_install-script.py`
