### ISSUE TITLE
[lua] Update Lua to 5.4.2

### ISSUE THREAD

**Issue by edubart** [msys2/MINGW-packages#7954]
Just asking to update Lua to 5.4.2, at the moment MSYS2 uses Lua 5.3.5, but there was released Lua 5.3.6, 5.4.0, 5.4.1 and 5.4.2.
Probably would be good to update LuaRocks to 3.5.0 too in the process, at the moment it uses 3.4.0.

**Comment by lazka** [comment]
lua is at 5.4.2 now. Could you give it a try?

**Comment by MehdiChinoune** [comment]
Fixed by #7984
