### ISSUE TITLE
Update wxpython to 4.x

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#7969]
There is now support upstream: https://github.com/wxWidgets/Phoenix/issues/1582

**Comment by Biswa96** [comment]
Are you looking to ditch py2? Is there any API breakage thingy with new version like wxWidgets 3.0.x vs 3.1.x? Arch seems to stick with same version as here now.

**Comment by lazka** [comment]
yes, py2 needs to go. we only have kicad as a user and they support wxpython 4

**Comment by Biswa96** [comment]
@umarcor's comment?

**Comment by umarcor** [comment]
@Biswa96, are you asking my opinion, since I'm the last contributor who updated the kicad recipe?

**Comment by Biswa96** [comment]
Yes. opinions + testing

**Comment by Biswa96** [comment]
Yes. opinions + testing + insights + any possibility of breaking things

**Comment by umarcor** [comment]
I'm pinging @orsonmmz and @marekr, who are the ones actually involved in kicad development. My opinion as a packager is that it's time to ditch py2 (it was a year ago already). However, kicad might have constraints which I'm not aware of.

**Comment by marekr** [comment]
> I'm pinging @orsonmmz and @marekr, who are the ones actually involved in kicad development. My opinion as a packager is that it's time to ditch py2 (it was a year ago already). However, kicad might have constraints which I'm not aware of.

We are moving kicad to MSVC.

**Comment by asmwarrior** [comment]
I try to run a python pretty printer in GDB, the python script includes wxPython related code for the GUI.

I use MSYS2 supplied GDB, and I see that GDB is built against python3, I found that currently, MSYS2's wxPython is still depend on python2, which causes an issue that I can't use wxPython inside the GDB.

I hope the MSYS2's wxPython should upgrade to python3, thanks!

**Comment by Biswa96** [comment]
[wxPython][1] may need some pampering for mingw. The build process in that project assumes if platform is Windows the compiler is MSVC.

[1]: https://github.com/wxWidgets/Phoenix.git

**Comment by lazka** [comment]
The linked issue has a WIP PKGBUILD: https://bitbucket.org/ustsv/testpkg_msys2/src/master/mingw-w64-wxpython-phoenix-git/PKGBUILD nto sure if it works though..

**Comment by jeremyd2019** [comment]
Has anyone pursued this yet?  I'm a user of wxPython, unfortunately not familiar with its build process.

**Comment by lazka** [comment]
I don't think so

**Comment by jeremyd2019** [comment]
I'm working on this now... should this update the wxPython package, or be a new (ie, wxPython4) package?  I started doing the latter, but given wxPython 'legacy' is python 2 only, it may not be necessary/helpful to keep it around.

**Comment by lazka** [comment]
the old package can go, kicad works with the newer one and is the only reverse dependency.
