### ISSUE TITLE
gimp : GEGL operation missing!

### ISSUE THREAD

**Issue by kerwinxu** [msys2/MINGW-packages#7980]
error:
GEGL operation missing!

GIMP requires the GEGL operation "gegl:introspect".
This operation cannot be found. Check your
GEGL install and ensure it has been compiled
with any dependencies required for GIMP.

GEGL-Message: 10:31:44.529: 模块“D:\msys64\mingw64\lib\gegl-0.4\ff-load.dll”加载错误：'D:\msys64\mingw64\lib\gegl-0.4\ff-load.dll': 找不到指定的模块。
GEGL-Message: 10:31:44.534: 模块“D:\msys64\mingw64\lib\gegl-0.4\ff-save.dll”加载错误：'D:\msys64\mingw64\lib\gegl-0.4\ff-save.dll': 找不到指定的模块。

but 
$ pacman -Ss gimp
mingw32/mingw-w64-i686-gimp 2.10.22-2
    GNU Image Manipulation Program (mingw-w64)
mingw32/mingw-w64-i686-gimp-ufraw 0.22-2 (mingw-w64-i686-gimp-plugins)
    Converter for raw files; utility and GIMP plugin (mingw-w64)
mingw64/mingw-w64-x86_64-gimp 2.10.22-2 [已安装]
    GNU Image Manipulation Program (mingw-w64)
mingw64/mingw-w64-x86_64-gimp-ufraw 0.22-2 (mingw-w64-x86_64-gimp-plugins)
    Converter for raw files; utility and GIMP plugin (mingw-w64)

$ pacman -Ss gegl
mingw32/mingw-w64-i686-gegl 0.4.28-1
    Generic Graphics Library (mingw-w64)
mingw64/mingw-w64-x86_64-gegl 0.4.28-1 [已安装]
    Generic Graphics Library (mingw-w64)

file "D:\msys64\mingw64\lib\gegl-0.4\ff-load.dll" and "D:\msys64\mingw64\lib\gegl-0.4\ff-save.dll" exist .

**Comment by Biswa96** [comment]
How can I reproduce your issue? If I just open GIMP it works fine.

**Comment by kerwinxu** [comment]
> How can I reproduce your issue? If I just open GIMP it works fine.

i don't know why ? it used to work . it show this error after "pacman -Syu" .

**Comment by kerwinxu** [comment]
> How can I reproduce your issue? If I just open GIMP it works fine.

step:

1. uninstall msys2.
2. install msys2
3. pacman -Syu
4. pacman -S mingw-w64-x86_64-gimp mingw-w64-x86_64-imagemagick

error . the last version is wrong .

**Comment by mati865** [comment]
Looks like missing dependency?

**Comment by naveen521kk** [comment]
I kinda reproduced this long back. See [this on discord](https://discord.com/channels/792780131906617355/794889490941476915/800779371262377984). What I did was to download https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gegl-0.4.26-2-any.pkg.tar.zst and install it. things worked.

**Comment by kerwinxu** [comment]
> Looks like missing dependency?

the program is what dependency ? 

- mingw-w64-x86_64-gegl installed
- D:\msys64\mingw64\lib\gegl-0.4\ff-load.dll exist
- D:\msys64\mingw64\lib\gegl-0.4\ff-save.dll exist 

at http://www17.plala.or.jp/KodamaDeveloped/LetsProgramming/details_gimp_application_icon.html
it said that missing :
avcodec-58.dll
avformat-58.dll
avutil-56.dll
swscale-5.dll
but it all exist in my computer . 

could you provide me your "pacman -Qqe" ?

the below is my 
pacman -Qqe
base
mingw-w64-x86_64-ffmpeg
mingw-w64-x86_64-gimp
mingw-w64-x86_64-imagemagick

**Comment by kerwinxu** [comment]
> I kinda reproduced this long back. See [this on discord](https://discord.com/channels/792780131906617355/794889490941476915/800779371262377984). What I did was to download https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gegl-0.4.26-2-any.pkg.tar.zst and install it. things worked.
> Even now I reproduce this and doing so fixes it

it work , thank you . could you tell me how to stop to update mingw-w64-x86_64-gegl 0.4.28-1 ?

**Comment by Biswa96** [comment]
Does installing mingw-w64-x86_64-ffmpeg solve your issue?

**Comment by kerwinxu** [comment]
> Does installing mingw-w64-x86_64-ffmpeg solve your issue?

no , i tried , it do not work .

pacman -Qqe
base
**mingw-w64-x86_64-ffmpeg** 
mingw-w64-x86_64-gimp
mingw-w64-x86_64-imagemagick

**Comment by Biswa96** [comment]
Interesting! I am getting the following message which is somewhat similar with OP:

```
$ gimp-console
GEGL operation missing!

GIMP requires the GEGL operation "gegl:introspect".
This operation cannot be found. Check your
GEGL install and ensure it has been compiled
with any dependencies required for GIMP.
```

BTW, tried with clean install of mingw-w64-gimp.
