### ISSUE TITLE
scipy build error sometimes

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#8006]
Not sure what gives but the python configure script seems to think i have the C11 feature and neither mingw-w64 nor gcc has that.

this leads to a build error in vodemodule.c and because of how the PKGBUILD script is setup it goes into infinite recursion.

SO heres a more permanent fix ->

in PKGBUILD replace build() with this

```
build() {
  cd ${srcdir}/python-build-${CARCH}
  # we do not have the C11 header threads.h (build error in vodemodule.c)
  CFLAGS+=" -D__STDC_NO_THREADS__=1"
  CXXFLAGS+=" -D__STDC_NO_THREADS__=1"
  # the correct flag here is LDSHARED not LDFLAGS.
  LDSHARED="${LDFLAGS} -Wall -shared"
  result="fail"
  while [ "$result" = "fail" ]; do
    MSYS2_ARG_CONV_EXCL="--prefix=;--install-scripts=;--install-platlib=" \
    ${MINGW_PREFIX}/bin/python setup.py config_fc --fcompiler=gnu95 build && result="success"
  done
}
```

**Comment by revelator** [comment]
Looks like scipy is picking up the Msys2 compiler since that one does have threads.h the above will fortunatly work around that case.

**Comment by naveen521kk** [comment]
Could you make a PR? 
Working with scipy raises a lot of warning because its using something depreciated in Numpy.

**Comment by revelator** [comment]
The warnings are ok or well they dont interfere with anything i have noticed, this ones a build error which only seems to happen if you have the Msys2 gcc compiler installed as most sources dont normally know about standard mingw-* paths they default to usr so unless explicitly set to ${MINGWDIR}/bin/gcc etc. they will in a lot of cases look for gcc in /usr/bin. This is known behaviour with mingw compilers on windows so we just have to hack around it. Bit harder with python since it seems many packages ignore setting a default compiler so i had to disable the missing C11 feature another way.

The LDSHARED part was actually from the fedora scipy package.

I cannot at this point make pull requests but feel free to change it on my behalf.

**Comment by naveen521kk** [comment]
This is fixed
