### ISSUE TITLE
Conflicts in enum values in  mingw-w64-i686-cairomm16

### ISSUE THREAD

**Issue by nnzur** [msys2/MINGW-packages#8011]
Hi, while compiling with this build I encountered some compilation errors due to enum values: 
region.h contains enum class Cairo::Region::Overlap::IN and Cairo::Region::Overlap::OUT
context.h contains enum class Operator Cairo::Context::Operator::IN and Cairo::Context::Operator::OUT
Both values are also defined by windows headers: wincrypt.h and minwindef.h

**Comment by lazka** [comment]
Please report upstream
