### ISSUE TITLE
gdal_edit and gdal_calc.py are missing from the gdal package

### ISSUE THREAD

**Issue by shaheen-git** [msys2/MINGW-packages#8013]
Hi there,

I just installed the latest version of GDAL package (mingw-w64-x86_64-gdal). However, the gdal_edit (https://gdal.org/programs/gdal_edit.html) and gdal_calc.py (https://gdal.org/programs/gdal_calc.html) are not included in the package (their man file can be found though; e.g.  /mingw64/share/man/man1/gdal_calc.1.gz ). Can you please include them in the package?

Thanks!

**Comment by Biswa96** [comment]
gdal_edit and gdal_calc both are provided by gdal-python package. See the file list here https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-python-gdal?repo=ucrt64

```
$ pacman -F $MINGW_PREFIX/bin/{gdal_edit.py,gdal_calc.py}
ucrt64/bin/gdal_edit.py is owned by ucrt64/mingw-w64-ucrt-x86_64-python-gdal 3.7.1-3
ucrt64/bin/gdal_calc.py is owned by ucrt64/mingw-w64-ucrt-x86_64-python-gdal 3.7.1-3
```
