### ISSUE TITLE
Missing file in mingw-w64-libmpcdec

### ISSUE THREAD

**Issue by drfiemost** [msys2/MINGW-packages#8014]
The package _mingw-w64-libmpcdec_ is missing the config_win32.h file and it's not possible to build software that use it:

```
/C/msys64/mingw64/bin/gcc.exe   -march=native -O2 -pipe  -o CMakeFiles/cmTC_0392f.dir/CheckIncludeFile.c.obj -c /C/msys64/home/user/test/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
In file included from C:/msys64/home/user/test/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:
C:/msys64/mingw64/include/mpcdec/mpcdec.h:52:10: fatal error: mpcdec/config_win32.h: No such file or directory
   52 | #include "mpcdec/config_win32.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by Biswa96** [comment]
The `config_win32.h` file is not include in the automake file (libmpcdec/include/Makefile.am) in libmpcdec source tarball. Is that file a private one? Should that be included in other projects? Do you have any project which includes config_win32.h file?

**Comment by Biswa96** [comment]
Would you like to check if the linked pull request fixes your issue? You can download the built artifacts from the 'Checks' tab there.

**Comment by drfiemost** [comment]
It's ok, the package is correctly detected now:

```
Determining if the include file mpcdec/mpcdec.h exists passed with the following output:
Change Dir: C:/msys64/home/user/test/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/msys64/usr/bin/make.exe cmTC_acf3d/fast && /usr/bin/make  -f CMakeFiles/cmTC_acf3d.dir/build.make CMakeFiles/cmTC_acf3d.dir/build
make[1]: Entering directory '/home/user/test/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_acf3d.dir/CheckIncludeFile.c.obj

/C/msys64/mingw64/bin/gcc.exe   -march=native -O2 -pipe  -o CMakeFiles/cmTC_acf3d.dir/CheckIncludeFile.c.obj -c /C/msys64/home/user/test/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
Linking C executable cmTC_acf3d.exe
```

Thank you!

**Comment by drfiemost** [comment]
BTW, this version is quite outdated, The most "recent" one is the SV8 lib (see https://musepack.net/index.php?pg=src)

**Comment by lazka** [comment]
Yeah, we should update to what arch does: https://archlinux.org/packages/extra/x86_64/libmpcdec/

Both are similarly unmaintained.. but sv8 support would be nice.

Contributions welcome.

**Comment by Biswa96** [comment]
I am not sure if there is any reason or issue for not updating the package. So, @Alexpux (original author) may provide some insights. Also Arch has many patches https://github.com/archlinux/svntogit-packages/tree/packages/musepack/trunk 😰
