### ISSUE TITLE
[pyside2-qt5] PySide2 package not listed via pip.exe list

### ISSUE THREAD

**Issue by jmoguillansky-gpsw** [msys2/MINGW-packages#8021]
Hi,
I tried to install pyside2 mingw package:
 pacman -S mingw-w64-x86_64-pyside2-qt5

I see PySide2 installed here:
 /c/msys64/mingw64/lib/python3.8/site-packages/PySide2
 
 But when I run pip.exe list, I don't see PySide2 listed?
 
 I see other packages listed though.
 
 $ pip.exe -v list
Package        Version    Location                                                                                            Installer
-------------- ---------- --------------------------------------------------------------------------------------------------- ---------
appdirs        1.4.3      c:/msys64/mingw64/lib/python3.8/site-packages
argh           0.26.2     c:/msys64/mingw64/lib/python3.8/site-packages
attrs          19.3.0     c:/msys64/mingw64/lib/python3.8/site-packages
...

Is PySide2 python module tested and working with mingw?

**Comment by lazka** [comment]
Looks like it's missing a egg-info directory, not sure why that's missing. It's there in Arch Linux for example.
