### ISSUE TITLE
Redundant redeclaration of builtins

### ISSUE THREAD

**Issue by flamewing** [msys2/MINGW-packages#8028]
Compiling code which transitively includes either of the following headers will cause massive spam of redundant redeclaration of intrinsics:

- `/mingw32/i686-w64-mingw32/include/intrin.h`: package `mingw-w64-i686-headers-git`
-  `/mingw64/x86_64-w64-mingw32/include/intrin.h`: package `mingw-w64-x86_64-headers-git`

This can be easily triggered by compiling any SDL2 program; the warnings appear on any translation unit where a SDL header is included:

```
<built-in>: warning: redundant redeclaration of 'unsigned int __builtin_ia32_crc32qi(unsigned int, unsigned char)' in same scope [-Wredundant-decls]
In file included from C:/msys64/mingw64/include/SDL2/SDL_cpuinfo.h:59,
                 from C:/msys64/mingw64/include/SDL2/SDL.h:38,
                 from ./audio/Audio.h:25,
                 from gamewin.cc:38:
C:/msys64/mingw64/x86_64-w64-mingw32/include/intrin.h:59:23: note: previous declaration of 'unsigned int __builtin_ia32_crc32qi(unsigned int, unsigned char)'
   59 |   extern unsigned int __builtin_ia32_crc32qi (unsigned int, unsigned char);
      |                       ^~~~~~~~~~~~~~~~~~~~~~
<built-in>: warning: redundant redeclaration of 'unsigned int __builtin_ia32_crc32hi(unsigned int, short unsigned int)' in same scope [-Wredundant-decls]
C:/msys64/mingw64/x86_64-w64-mingw32/include/intrin.h:60:23: note: previous declaration of 'unsigned int __builtin_ia32_crc32hi(unsigned int, short unsigned int)'
   60 |   extern unsigned int __builtin_ia32_crc32hi (unsigned int, unsigned short);
      |                       ^~~~~~~~~~~~~~~~~~~~~~
<built-in>: warning: redundant redeclaration of 'unsigned int __builtin_ia32_crc32si(unsigned int, unsigned int)' in same scope [-Wredundant-decls]
C:/msys64/mingw64/x86_64-w64-mingw32/include/intrin.h:61:23: note: previous declaration of 'unsigned int __builtin_ia32_crc32si(unsigned int, unsigned int)'
   61 |   extern unsigned int __builtin_ia32_crc32si (unsigned int, unsigned int);
      |                       ^~~~~~~~~~~~~~~~~~~~~~
```

The culprit of those warnings are the following lines:

```
  extern unsigned int __builtin_ia32_crc32qi (unsigned int, unsigned char);
  extern unsigned int __builtin_ia32_crc32hi (unsigned int, unsigned short);
  extern unsigned int __builtin_ia32_crc32si (unsigned int, unsigned int);
```

which are present on both mentioned headers. These are the **only** GCC builtins to be explicitly declared in headers. If try to use the intrinsics without passing `-msse4.2 -mcrc32` to GCC, I receive an error about these missing flags. This error happens regardless of the presence of the declarations above: having the declarations there or not seems to make no difference other than generate warnings that cannot be suppressed.

Is there a reason for those declarations?

**Comment by Biswa96** [comment]
Apology for late reply. I have sent a request to mingw-w64 mailing list. Here is the reply https://sourceforge.net/p/mingw-w64/mailman/message/37230915/. It will be handled soon. You can remove those declarations for now as a temporary workaround.

**Comment by Biswa96** [comment]
* Issue fixed in upstream.
* Patch sent in upstream mingw-w64 here https://sourceforge.net/p/mingw-w64/mailman/message/37232324/
* Git commit in upstream mingw-w64 here https://sourceforge.net/p/mingw-w64/mingw-w64/ci/62924d0cd8ea3422689023a5be546755fe73cbe0/

/cc @hgdagon same issue as yours with fheroes2. Now fixed.

**Comment by flamewing** [comment]
Thanks!

**Comment by lazka** [comment]
thx!
