### ISSUE TITLE
[mingw-w64-vulkan-validation-layers] Failed to find 'vkGetInstanceProcAddr' in layer

### ISSUE THREAD

**Issue by Amphaal** [msys2/MINGW-packages#8030]
I've been trying to use this package instead of the LunarG's MSVC binaries package, and I've had 2 issues with it so far : 

- The generated `VkLayer_khronos_validation.json` should be copied in the `bin` directory, along its associated `.dll` file (like in the MSVC package) and not in the `lib` directory.
- Trying to use `VkLayer_khronos_validation` in a Vulkan app has no effect, and outputs : 
```
loader_create_instance_chain: Failed to find 'vkGetInstanceProcAddr' in layer C:\msys64\mingw64\bin\.\libVkLayer_khronos_validation.dll
loader_create_device_chain: Failed to find 'vkGetInstanceProcAddr' in layer C:\msys64\mingw64\bin\.\libVkLayer_khronos_validation.dll.  Skipping layer.
```

Has anyone encountered this problem yet ?

**Comment by lazka** [comment]
We have two patches for this package: one to change symbol exports and one to fix the install location, so likely both things need further improvements.

(and you might be the first to use it)

**Comment by Amphaal** [comment]
I wish I could help on tweaking the script here, but I think I am not seasoned enough with mingw intrinsic mechanisms to be of any help with dynamic linkage issues :( 

This could be related to symbols beings exported to the habitual sister `dll.a` file, and not directly included into the `.dll` file, as the Vulkan loader might expect it ?

I'll have a look on fixing the `install()` destination location for the `.json` manifests.

**Comment by Biswa96** [comment]
`vkGetInstanceProcAddr` seems to be exported from libvulkan-1.dll. Though I am curious about if the vulkan package has that issue why the dependent package(s) can be built without any issue.

**Comment by Amphaal** [comment]
I ran both binaries into `dllexp.exe`, and here are the outputs [Exported Functions Lists.zip](https://github.com/msys2/MINGW-packages/files/6062090/Exported.Functions.Lists.zip)

Well, it looks like the expected functions layout from MSVC binaries differs radically from what is generated for MinGW. I wonder where the heck that comes from !

**Comment by Biswa96** [comment]
Can you provide a sample program to reproduce your issue?

**Comment by Amphaal** [comment]
OK, I can confirm that removing `002-proper-def-files-for-32bit.patch` altogether from the package fixes the generated `.dll` by exposing the correct functions, removes a bunch of GCC warnings at compile time and thus allows me to use `libVkLayer_khronos_validation.dll` from the `.json` manifest, just like the MSVC binaries !

Since iI am working with 64bits binaries and not 32bits ones, I do not know if this change could be harmful.

Maybe updates have been made upstream that make this particular patch obsolete ?

**Comment by Amphaal** [comment]
Since the CI passed for both x32 and x64 targets on my draft with the aforementioned disabling of `002-proper-def-files-for-32bit.patch`, @Biswa96 I'll save you the hassle of setting up a Vulkan app locally (with someting like my own https://github.com/Amphaal/Vulcain) to witness the magic happening :P

**Comment by Amphaal** [comment]
Do you guys need a reproducible env. to test the bugs before accepting my pull request ? If not, I'd gladly close this ticket once merging occurs. Cheers !

**Comment by lazka** [comment]
Sorry, for the delay, I'll have a look later.
