### ISSUE TITLE
Pip3 installation with requirements.txt fails

### ISSUE THREAD

**Issue by fauxpark** [msys2/MINGW-packages#8061]
When attempting to build the QMK CLI (https://github.com/qmk/qmk_cli) the `python3 -m pip install -r requirements.txt` step fails with this error:

```
Installing collected packages: setuptools-scm, pyrsistent, pyflakes, pycodestyle, mccabe, coverage, argcomplete, yapf, pygments, nose2, milc, jsonschema, hjson, flake8, dotty-dict, qmk
  Running setup.py develop for qmk
    ERROR: Command errored out with exit status 1:
     command: D:/a/_temp/msys/msys64/mingw64/bin/python3.exe -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:/a/qmk_cli/qmk_cli/setup.py'"'"'; __file__='"'"'D:/a/qmk_cli/qmk_cli/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: D:/a/qmk_cli/qmk_cli/
    Complete output (13 lines):
    running develop
    running egg_info
    creating qmk.egg-info
    writing qmk.egg-info/PKG-INFO
    writing dependency_links to qmk.egg-info/dependency_links.txt
    writing entry points to qmk.egg-info/entry_points.txt
    writing requirements to qmk.egg-info/requires.txt
    writing top-level names to qmk.egg-info/top_level.txt
    writing manifest file 'qmk.egg-info/SOURCES.txt'
    D:/a/_temp/msys/msys64/mingw64/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'requires_python'
      warnings.warn(msg)
    file milc.py (for module milc) not found
    error: [WinError 267] The directory name is invalid
    ----------------------------------------
ERROR: Command errored out with exit status 1: D:/a/_temp/msys/msys64/mingw64/bin/python3.exe -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:/a/qmk_cli/qmk_cli/setup.py'"'"'; __file__='"'"'D:/a/qmk_cli/qmk_cli/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

You can see it is failing CI here: https://github.com/qmk/qmk_cli/runs/1685728562

It doesn't look like a result of a change in the codebase itself, as the first failure occurred on a simple addition to requirements.txt (adding dotty-dict and jsonschema, which this error doesn't seem to be related to). Rolling back the repo to before that commit yields the same error locally. So, I have to assume the issue is somewhere in pip or setuptools. Any ideas?

**Comment by naveen521kk** [comment]
It looks like your projects setup.py is configured incorrectly.
First, it is `python_requires` and not `requires_python` that was the first warning about.
Next, is https://github.com/qmk/qmk_cli/blob/3b6c0fd058915df4e4a1ccfc76bcc3de1899b4d4/setup.py#L27 which causes `file milc.py (for module milc) not found`, which in turn results in an invalid directory and fails.

Also, does this project install on normal python on Windows?

**Comment by naveen521kk** [comment]
Also, a cause for this is that you install setuptools through pip. Why thought?
https://github.com/qmk/qmk_cli/runs/1685728562#step:4:2

**Comment by fauxpark** [comment]
Yep, looks like it was one or both of the `python_requires` and setuptools stuff. The workflow file was written before all the python packages were moved to pacman, I think. Sorry for the noise.
