### ISSUE TITLE
gcc bug ?!?

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#8079]
building binutils after the last gcc patch level now yields this ->
../../binutils-2.36.1/opcodes/i386-dis.c:12308:1: internal compiler error: in seh_cfa_adjust_cfa, at config/i386/winnt.c:1104
12308 | }

tried earlier versions like 2.35 and 2.30 and same error.

**Comment by revelator** [comment]
it is caused by this patch 0201-backport-49a714e.patch ...
i dont even use seh exceptions my gcc uses sjlj exceptions which makes me wonder why it polutes the other exception models.

**Comment by revelator** [comment]
hmm same commit id as this but you are missing a patch so here it is.

[0202-backport-357c435.zip](https://github.com/msys2/MINGW-packages/files/6096767/0202-backport-357c435.zip)

**Comment by revelator** [comment]
fixes an ICE if frame is larger than SEH_MAX_FRAME -> https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=2939b358936bb824330888def98ad848dea41483

**Comment by lazka** [comment]
thanks

**Comment by revelator** [comment]
yw ;)

**Comment by lazka** [comment]
Hit in CI as well now: https://github.com/msys2/MINGW-packages/pull/8083/checks?check_run_id=2050291078

So we have at least a test case to verify if the patch helps.
