### ISSUE TITLE
glade-gtk2 or glade3

### ISSUE THREAD

**Issue by Jillinger** [msys2/MINGW-packages#8084]
I just got this question, from MSYS, and I am not sure how to answer.

```
:: Starting full system upgrade...
:: Replace mingw-w64-x86_64-glade3 with mingw64/mingw-w64-x86_64-glade-gtk2? [Y/n]
```

Can someone please explain why I have received this option, and what's the best option, and why?
I'm using msys2 on a 64 bit system.

**Comment by lazka** [comment]
The package was just renamed to avoid confusion with the gtk3 version, and this happens through a "replace" in pacman. "Y" is the preferred answer if you don't know what it's about.
