### ISSUE TITLE
gexiv2 0.12.2

### ISSUE THREAD

**Issue by novomesk** [msys2/MINGW-packages#8117]
Hello,

when possible, can you please add new version of gexiv2?

The new version allows GIMP 2.99 to enable EXIF metadata export for HEIF and AVIF format.

**Comment by Biswa96** [comment]
I have sent a pull request to update the package. If you want to test new package you can download the GitHub Actions artifacts (.tar.zst) from the linked pull request and install it with `pacman -U` command.
