### ISSUE TITLE
Is it compiled with g++ (mingw-w64-x86_64)？

### ISSUE THREAD

**Issue by xingrui94** [msys2/MINGW-packages#8135]
the compiler error info：

```
$ g++ -L/mingw64/lib -lgdal test_gdal.cpp -o test_gdal.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc401XMj.o:test_gdal.cpp:(.text+0x154): undefined reference to `GDALAllRegister'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc401XMj.o:test_gdal.cpp:(.text+0x167): undefined reference to `CPLSetConfigOption'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc401XMj.o:test_gdal.cpp:(.text+0x17d): undefined reference to `GDALOpen'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc401XMj.o:test_gdal.cpp:(.text+0x1d9): undefined reference to `GDALDataset::GetRasterXSize()'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc401XMj.o:test_gdal.cpp:(.text+0x1e8): undefined reference to `GDALDataset::GetRasterYSize()'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc401XMj.o:test_gdal.cpp:(.text+0x1f7): undefined reference to `GDALDataset::GetRasterCount()'
```

**Comment by Biswa96** [comment]
Please provide the sample code to reproduce your issue.

**Comment by xingrui94** [comment]
> Please provide the sample code to reproduce your issue.

#include <iostream>
#include <string>
#include "gdal_priv.h"
#include "ogr_geometry.h"

using namespace std;

struct RasterInfo
{
    string spatialReference;
    int dimensionInfo[3];
    string coordinatesSystem;
    double spatialResolutions[2];
    double geometryInfo[3][2];
};


// 获取影像左下角和右上角的坐标
void get_raster_info(string filename, RasterInfo rasterInfo)
{
    GDALAllRegister();
    CPLSetConfigOption("GDAL_FILENAME_IS_UTF8","NO");

    GDALDataset *dataset = (GDALDataset *) GDALOpen(filename.c_str(), GA_ReadOnly);  
    double imgGeoTransform[6] = {0.0};
    dataset->GetGeoTransform(imgGeoTransform);

    //获取影像的维度信息（行列数和波段数）  
    unsigned int xSize = dataset->GetRasterXSize();  
    unsigned int ySize = dataset->GetRasterYSize();
    unsigned int zSize = dataset->GetRasterCount();
    rasterInfo.dimensionInfo[0] = xSize;
    rasterInfo.dimensionInfo[1] = ySize;
    rasterInfo.dimensionInfo[2] = zSize;
   
    // 获取影像的空间分辨率
    if(imgGeoTransform[1] < 0) rasterInfo.spatialResolutions[0] = -imgGeoTransform[1];   //lon方向的空间分辨率
    else rasterInfo.spatialResolutions[0] = imgGeoTransform[1];

    if(imgGeoTransform[5] < 0) rasterInfo.spatialResolutions[1] = -imgGeoTransform[5];   //lat方向的空间分辨率
    else rasterInfo.spatialResolutions[1] = imgGeoTransform[5];

    // 获取影像空间参考坐标
    unsigned int lastCol = xSize - 1;
    unsigned int lastRow = ySize - 1;
    
    // leftLowerX = imgGeoTransform[0] + imgGeoTransform[1] * 0 + imgGeoTransform[2] * lastRow;
    // leftLowerY = imgGeoTransform[3] + imgGeoTransform[4] * 0 + imgGeoTransform[5] * lastRow;
    double leftLowerX = imgGeoTransform[0] + imgGeoTransform[2] * lastRow;
    double leftLowerY = imgGeoTransform[3] + imgGeoTransform[5] * lastRow;
    rasterInfo.geometryInfo[0][0] = leftLowerX;
    rasterInfo.geometryInfo[0][1] = leftLowerY;

    // rightUpperX = imgGeoTransform[0] + imgGeoTransform[1] * lastCol + imgGeoTransform[2] * 0;
    // rightUpperY = imgGeoTransform[3] + imgGeoTransform[4] * lastCol + imgGeoTransform[5] * 0;
    double rightUpperX = imgGeoTransform[0] + imgGeoTransform[1] * lastCol;
    double rightUpperY = imgGeoTransform[3] + imgGeoTransform[4] * lastCol;
    rasterInfo.geometryInfo[1][0] = rightUpperX;
    rasterInfo.geometryInfo[1][1] = rightUpperY;

    // if ((leftLowerX >0 && rightUpperX > 0) || (leftLowerX < 0 && rightUpperX < 0))
    // {
    //     *(rasterInfo.geometryInfo + 4) = leftLowerX + (rightUpperX - leftLowerX) / 2;
    // }
    // else if (leftLowerX < 0 && rightUpperX > 0)
    // {
    //     *(rasterInfo.geometryInfo + 4) = leftLowerX + (rightUpperX - leftLowerX) / 2;
    // }
    // else if (leftLowerX > 0 && rightUpperX < 0)
    // {}
    rasterInfo.geometryInfo[2][0] = leftLowerX + (rightUpperX - leftLowerX) / 2;
    rasterInfo.geometryInfo[2][1] = leftLowerY + (rightUpperY - leftLowerY) / 2;
}

int main(int argc, char **argv)
{
    string filename = R"("D:\xingrui94\works\data\LC081200322018082501T1-SC20190510111047\LC08_SR_Band2345_TIF\LC08_SR_Band2345_8bit.tif")";
    RasterInfo raster_info;
    get_raster_info(filename, raster_info);
    cout << raster_info.dimensionInfo[0] << raster_info.dimensionInfo[1] << raster_info.dimensionInfo[2] << endl;
    cout << raster_info.spatialResolutions[0] << raster_info.spatialResolutions[1] << endl;
    cout << raster_info.geometryInfo[0][0] << raster_info.geometryInfo[0][1] << endl;
    cout << raster_info.geometryInfo[1][0] << raster_info.geometryInfo[1][1] << endl;
    cout << raster_info.geometryInfo[2][0] << raster_info.geometryInfo[2][1] << endl;
    //
    return 0;
}

**Comment by Biswa96** [comment]
Try these:
1. Download gdal package `pacman -S --needed mingw-w64-x86_64-gdal` (for 64 bit)
2. Compile `g++ test_gdal.c -lgdal`

**Comment by xingrui94** [comment]
> 2\. g++ test_gdal.c -lgdal

Thanks，it works. But I find a problem, the “-lgdal” compilation falg must be placed at the end of the compilation command.In Linux g++ compilation command, there is no such problem.Is that a bug of mingw-w64-x86_64's g++ tool chain?
![image](https://user-images.githubusercontent.com/29156275/111301123-cbf05200-868c-11eb-8676-62ed3328e0c5.png)

**Comment by lazka** [comment]
`-l ...` needs to come after the thing using it, see https://sourceware.org/binutils/docs/ld/Options.html#Options

**Comment by xingrui94** [comment]
> `-l ...` needs to come after the thing using it, see https://sourceware.org/binutils/docs/ld/Options.html#Options

Thanks, I get it!
