### ISSUE TITLE
adns old git path needs to be updated

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#8141]
it is now https://github.com/gpg/adns.git

**Comment by revelator** [comment]
also need to change the definition of struct pollfd in config.in.h or it will error out because it is allready defined in winsock2.h

**Comment by Biswa96** [comment]
That [gnupg adns repository][1] was "retired" many years ago. Is it possible to use the [actual git repo][2] here? It does not support Win32 or mingw platform but can be modified?

[1]: https://git.gnupg.org/cgi-bin/gitweb.cgi
[2]: http://www.chiark.greenend.org.uk/ucgi/~ianmdlvl/git?p=adns.git

**Comment by revelator** [comment]
possibly though it would need a lot of patching i reckon.

**Comment by lazka** [comment]
Looks like it was dropped in 2016: https://github.com/gpg/gnupg/blob/a788f2e8306d80f7f3df34eb62ec7ce1a62d48e1/NEWS#L1251

So we can remove adns

**Comment by lazka** [comment]
@revelator do you have any actual use for adns as it is now?

**Comment by revelator** [comment]
if it is not used kill it with fire :)
