### ISSUE TITLE
It puts GetTickCount64 in the code

### ISSUE THREAD

**Issue by yg8ijvjvjv** [msys2/MINGW-packages#8143]
## GetTickCount64

A thing that makes each application fail in Windows XP.

## Steps to Reproduce GetTickCount64

1. Compile C++ in MinGW32
2. Run in Windows XP
3. GetTickCount64
4. It should not have compiled GetTickCount64 in

## Additional Context: Windows XP, does not affect 2000 or Vista

How do I remove GetTickCount64 from the code?

**Comment by yg8ijvjvjv** [comment]
How else do I remove the GetTickCount64 then?

**Comment by revelator** [comment]
could try defining -D_WIN32_WINNT=0x0501 in CFLAGS but as the api targets win7 im not sure it will work.

**Comment by mati865** [comment]
It won't, winpthreads are already built for Win 7+.

> How else do I remove the GetTickCount64 then?

Rebuild mingw-w64 for XP target.

**Comment by yg8ijvjvjv** [comment]
So GetTickCount64 is now removed?

**Comment by lazka** [comment]
nothing changed. we don't support winxp
