### ISSUE TITLE
mingw_arch build limiter ineffective

### ISSUE THREAD

**Issue by Schala** [msys2/MINGW-packages#8155]
I updated OneDNN tonight and despite the presence of 'mingw_arch,' makepkg still proceeded to build a 32-bit package. Does this only work with the build bot?

**Comment by Biswa96** [comment]
This may provide the answer https://github.com/msys2/MINGW-packages/pull/8083

**Comment by lazka** [comment]
yeah, I haven't implemented it for CI yet

**Comment by Schala** [comment]
I see, thanks.
