### ISSUE TITLE
storage size of struct ip_mreg not known on 32 bit SDL2_net

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#8165]
SDLnetUDP.c:201:25: error: storage size of 'g' isn't known, anyone else get this witht the latest mingw-w64 api ?

**Comment by revelator** [comment]
hmm same exact problem with SDL_net

**Comment by revelator** [comment]
looks like a problem introduced with a change to the mingw-w64 api, guess ill have to report it upstream.

**Comment by Biswa96** [comment]
Are you having this issue now?

**Comment by revelator** [comment]
no  seems to work allright again :)
