### ISSUE TITLE
avrdude x86_64 segfault

### ISSUE THREAD

**Issue by nerdralph** [msys2/MINGW-packages#8178]
mingw-w64-x86_64-avrdude 6.3-2 installed via pacman, on MINGW64_NT-6.1-7601 3.1.7-340.x86_64.  avrdude always segfaults:
```
# avrdude -c usbasp -p t85
Segmentation fault
```

I tried both libusbK and libusb-w32 associations using Zadig,  avrdude 6.3-20190619 running on the same machine under mingw-w32 (MINGW32_NT-6.1) works fine.  The same avrdude exe works fine when run from the MSYS2 MinGW 64-bit shell.

**Comment by fauxpark** [comment]
Also seeing this. It appears to only occur when flashing with the `usbasp` programmer - at least, `avr109` (Caterina bootloader) has no issues. `mingw-w64-x86_64-avrdude` under the MINGW64 terminal and `mingw-w64-i686-avrdude` under MINGW32, and vice versa, both segfault.

**Comment by fauxpark** [comment]
I've done some digging around with gdb - the segfault is coming from `libusb_get_string_descriptor_ascii()`. It appears to be entirely unrelated to avrdude; I confirmed this is the case by compiling the example code from libusb: https://github.com/libusb/libusb/blob/master/examples/testlibusb.c. It segfaults too, but importantly only when it gets to the USBasp device - the `libusb_get_string_descriptor_ascii()` call functions normally for all other devices.

If I switch the device over to the WinUSB driver, the example code runs successfully, and avrdude also succeeds in flashing the device.

**Comment by fauxpark** [comment]
Now that I know the issue is with libusbK, I found this: https://github.com/libusb/libusb/issues/912

So it appears to be a matter of waiting for a new libusb release.
