### ISSUE TITLE
[sip] The mingw-w64-x86_64-sip5 package is missing

### ISSUE THREAD

**Issue by Suthiro** [msys2/MINGW-packages#8203]
Hello!
Recently sip v6 has been released and the package was updated. However, now there is no way to install sip v5 using MSYS2.
I'm not sure if it was intended, by doubt so, because the latest [sip package](https://packages.msys2.org/package/mingw-w64-x86_64-sip)'s description states that it replaces

> mingw-w64-x86_64-sip4
> mingw-w64-x86_64-sip5

and [mingw-w64-x86_64-sip4](https://packages.msys2.org/package/mingw-w64-x86_64-sip4) is available and [mingw-w64-x86_64-sip5](https://packages.msys2.org/package/mingw-w64-x86_64-sip5) is not.

Could someone please clarify whether this was intentional?

Thank you very much.

**Comment by Biswa96** [comment]
This happened https://github.com/msys2/MINGW-packages/pull/8162. Did you get any error after installing anything?

**Comment by lazka** [comment]
Why do you need sip v5?

**Comment by Suthiro** [comment]
> This happened #8162. Did you get any error after installing anything?

Yes. For example, see [this attempt](https://github.com/Suthiro/scidavis/runs/2197046709?check_suite_focus=true) to fix. I tried to change workflow to download existing package `mingw-w64-x86_64-sip` instead of missing `mingw-w64-x86_64-sip5`, but to no avail. I'm not sure what is the right way to search for sip now. Previously it was a simple lookup for the sip executable. And even if the executable will be found, would it work now?

>Why do you need sip v5?

Maybe I don't, but what is certain I don't know how to handle sip v6 in MinGW builds.
I suppose because of [this comment](https://github.com/msys2/MINGW-packages/pull/8162#issuecomment-803296313) from #8162:
> sip6 doesn't have a standalone tool to generate bindings.
> All features deprecated in SIP v5 have been removed.

**Comment by lazka** [comment]
@MehdiChinoune do you know what's the problem here by any chance?

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune do you know what's the problem here by any chance?

He should install sip4 with python-sip4. That's it.

**Comment by Suthiro** [comment]
> > @MehdiChinoune do you know what's the problem here by any chance?
> 
> He should install sip4 with python-sip4. That's it.

Thank you very much! Did it [already](https://github.com/Suthiro/scidavis/runs/2201697015?check_suite_focus=true), but something very subtle differs: everything builds, but one of the tests fails. However, not sure if it is related to sip version.
Thank you all very much again!

**Comment by Suthiro** [comment]
It is sip version related though.
[Tests with sip4](https://github.com/Suthiro/scidavis/runs/2202948563?check_suite_focus=true) fail.
[Tests with sip5](https://github.com/highperformancecoder/scidavis/actions/runs/628204728) pass.
The commits differ only in .yml file.

I tried to install `mingw-w64-x86_64-python-sip4` but it conflicts with `mingw-w64-x86_64-pyqt5-sip`, and the latter is a dependency for `mingw-w64-x86_64-python-pyqt5`.
