### ISSUE TITLE
mingw-w64: PMTUD_STATE/IP_PMTUDISC_DO missing

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#8232]
mingw-w64 recently added IP_MTU_DISCOVER: https://github.com/mirror/mingw-w64/commit/e30bff42ea26274e73d27bcbeae72815d1271aca

But the corresponding IP_PMTUDISC_DO is missing, which makes this fail: https://gitlab.com/gnutls/gnutls/-/blob/38b25e19f1835021557629b028dc9e666dc83acd/src/socket.c#L533

MS docs: https://docs.microsoft.com/en-us/windows/win32/winsock/ipproto-ip-socket-options

**Comment by lazka** [comment]
@Biswa96: Do you want to take a look? or should I?

**Comment by Biswa96** [comment]
I can try if you wish. The ws2* headers in mingw-w64 are somewhat entangled. One has to compile the project to test, even with -Wall, -Wpedantic (lessons from my past mistakes).

**Comment by lazka** [comment]
Someone should write a test suite :P

**Comment by Biswa96** [comment]
Technically every project here is an unique test suite for mingw-w64 :)

**Comment by Biswa96** [comment]
Patch sent.

**Comment by lazka** [comment]
Thanks!
