### ISSUE TITLE
undefined reference to `__memcpy_chk' with mingw-w64-x86_64-opus-1.3.1-2

### ISSUE THREAD

**Issue by thesword53** [msys2/MINGW-packages#8240]
```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libopus.a(encode_frame_FLP.o):(.text+0x6b0): undefined reference to `__memcpy_chk'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libopus.a(encode_frame_FLP.o):(.text+0x879): undefined reference to `__memcpy_chk'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libopus.a(encode_frame_FLP.o):(.text+0x971): undefined reference to `__memcpy_chk'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libopus.a(pitch_analysis_core_FLP.o):(.text+0x24a): undefined reference to `__memset_chk'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libopus.a(bands.o):(.text+0x3f01): undefined reference to `__memcpy_chk'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libopus.a(PLC.o):(.text+0x2ee): undefined reference to `__memcpy_chk'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libopus.a(decode_core.o):(.text+0x291): undefined reference to `__memcpy_chk'
collect2.exe: error: ld returned 1 exit status
```

I think it's related to https://github.com/msys2/MINGW-packages/commit/8823c24edfe290aa7208609d26728d249975be81

**Comment by Biswa96** [comment]
Please provide steps to reproduce your issue. Either link with mingw32 library or disable stack checking option.

**Comment by lazka** [comment]
Are you using pkg-config?

We might need to put `libssp` there as well for static linking..

**Comment by lity2k** [comment]
same problem， and I try many times today.
Finally downgrading package mingw-w64-i686-opus (1.3.1-2 => 1.3.1-1) ，compiled successfully。

**Comment by thesword53** [comment]
I compiled with -static -static-libgcc -lopus.
It compiles successfully with opus 1.3.1-1 but not with 1.3.1-2.

**Comment by lazka** [comment]
Then you need to pass `-lssp` aswell

**Comment by alex-tee** [comment]
same issue here, my builds suddenly break

**Comment by alex-tee** [comment]
it started happening again (mingw-w64-x86_64-opus-1.3.1-3-any.pkg.tar.zst):

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libopus.a(bands.o):(.text+0x3f01): undefined reference to `__memcpy_chk'
```

https://dev.azure.com/alex0266/zrythm/_build/results?buildId=1963&view=logs&j=acbd83ff-67a0-52c5-f8b0-3f079d748954&t=51bcedc9-6547-5a78-ac1c-a6921ca76bb2
https://dev.azure.com/alex0266/5d39a0cf-3c43-4666-958d-d10497d6b905/_apis/build/builds/1963/logs/11

it worked up to yesterday

**Comment by 1480c1** [comment]
Not sure where libopus is being searched for in your source code nor carla's, but you may want to try to find that and make it use pkg-config to provide the libs instead, as it should have `-lopus -lssp` or something along that line
