### ISSUE TITLE
mingw-w64-python-jsonschema missing dependency on six

### ISSUE THREAD

**Issue by imsodin** [msys2/MINGW-packages#8275]
Building darktable in msys2 fails because of six being required by jsonschema, but not installed through mingw-w64-python-jsonschema:

```
pkg_resources.DistributionNotFound: The 'six>=1.11.0' distribution was not found and is required by jsonschema
```
https://github.com/darktable-org/darktable/runs/2261989163?check_suite_focus=true#step:4:1094

jsonschema has dropped python2 support and thus doesn't require six anymore on their main branch, but the latest release (which is packaged by mingw) still requires it.

Adding an explicit dependency on `mingw-w64-x86_64-python3-six` fixes the problem as expected.

**Comment by Biswa96** [comment]
In ArchLinux, the dependencies goes like this python-jsonschema <- python-pyrsistent <- python-six.

**Comment by imsodin** [comment]
Possibly python-pyrsistent needs a dependency to python-six too (didn't check), nevertheless python-jsonschema has a direct dependency on python-six: https://github.com/Julian/jsonschema/blob/v3.2.0/setup.cfg#L34

> BTW, try not to use mingw-w64-python3 in package name. Those are being renamed to mingw-w64-python only.

Thanks for the pointer.

**Comment by kmilos** [comment]
pyrsistent no longer depends on six, so it should indeed be added to jsonschema

https://github.com/tobgu/pyrsistent/blob/fed6c1781a915b60b731051d294fe4b50d26de7a/CHANGES.txt#L17
