### ISSUE TITLE
[brotli] pkg-config reports incorrect library with --static parameter

### ISSUE THREAD

**Issue by thesword53** [msys2/MINGW-packages#8277]
`pkg-config --static --libs libbrotlidec` returns `-LC:/msys64/mingw64/lib -lbrotlidec -LC:/msys64/mingw64/lib -lbrotlicommon`
`pkg-config --static --libs libbrotlienc` returns `-LC:/msys64/mingw64/lib -lbrotlienc -LC:/msys64/mingw64/lib -lbrotlicommon`
`pkg-config --static --libs libbrotlicommon` returns `-LC:/msys64/mingw64/lib -lbrotlicommon`
But static libraries are named `libbrotli*-static.a` unlike non static: `libbrotli*-.dll.a`
The `-static` prefix should be removed.

**Comment by 1480c1** [comment]
You might want to take that upstream as that was their decision

**Comment by Biswa96** [comment]
The static libraries were renamed with this commit https://github.com/msys2/MINGW-packages/commit/eaa3618b8934924dcafcf52f7e345651b24af72c
