### ISSUE TITLE
Submit V8 patches to upstream?

### ISSUE THREAD

**Issue by cleiner** [msys2/MINGW-packages#8344]
I've been wondering if someone has tried to submit the patches in the mingw-w64-v8 package to upstream? Or is there a reason to believe they wouldn't be accepted?

Since V8 has frequent new releases, it would be easier to keep the package up-to-date and it would also be helpful for other downstream projects that want a different combination of the many build options (e.g. v8_monolithic=true).

**Comment by Kwizatz** [comment]
@cleiner I have asked about this on the [v8-dev group](https://groups.google.com/g/v8-dev/c/8vSg7rGTmwA/m/pGwhTNv1AwAJ), I saw the response as positive though lukewarm, however, the problem is not v8, there's mostly compilation fixes on the v8 repo, the problem is the 'build' repo where most of the intrusive changes reside. While I've done my best not to break any other platforms, the build patch adds a whole new toolchain, changes some .py scripts to support mingw's Python 3 and other intrusive changes in the way pkg-config is handled. The way mingw's system libz and libicu's gn build scripts are changed probably require more though to make them compatible with the original's.

(I was going to add here that I add a is_mingw gn variable which is frowned upon, but reading the comment again it is only frowned upon for lesser Unix systems... still is_mingw should be more like is_clang and less like is_win, which I hope I have achieved in some degree)

On top of that, the 'build' repo is not an independent repo, changes to it MUST be submitted to the chromium src repo which is huge, and for all I mentioned before, it may be harder to do that specially if the new toolchain is useless to build the whole of chromium. But I don't know, I have not gotten as far as to try.

**Comment by cleiner** [comment]
@Kwizatz Thanks for the quick and detailed response. Sounds like it would take a significant amount of effort to get the patches accepted (if at all), unfortunately.

> PS: monolithic=true should work by just changing the PKGBUILD file, I am not that familar with the PKGBUILD system in order to build and install both, monolith is a huge library to have around just wasting space in your hard drive though.

I've changed other GN args as well and had to make a (tiny) additional patch, so it seemed more appropriate to  evaluate the possibility of upstreaming the patches rather than introducing a purpose-built MSYS2 package.

**Comment by Kwizatz** [comment]
@cleiner for the time being if you need me to merge your patches with mine, I have no problem with that, just send them my way provided that the changes do not affect the shared library build and they only affect the build, no bug fixes, new features, etc.

The monolith library is ~1gb and is just dead weight if you only need the runtime, so I don't know what other solutions we could have, maybe split packages? v8-runtime v8-dev and v8-static?

**Comment by cleiner** [comment]
@Kwizatz The project I have contributed to was already on v8 8.9.255.20 for Linux/Mac, so I updated the patches accordingly. If you have no use for these updates, the tiny addition I made was [this patch](https://github.com/msys2/MINGW-packages/files/6306170/fix-mingw-unwind-tables.patch.txt) to the build repository which allows building with `exclude_unwind_tables=true`. If you included it in your patches, that would be great!

With the build options I'm using, the monolith library is about 84mb, so not too terrible. There's no ICU and no debug build though, so I'm not sure if it's suitable to be included in the PKGBUILD, even as a dedicated v8-static package. I would be ok with keeping the build in the other project for now.

**Comment by Kwizatz** [comment]
@cleiner I'll add the patch, thank you, while this setting may not be the default my goal is to support (IE: NOT break) as many features as possible.

There is an issue with debug builds, I am not sure if it is a linker/compiler bug or just a Windows limitation, the library is so big that the linker generates corrupt executable, stripping the debug symbols fixes them, but then you have no debug symbols, I tried extracting them and using them as a separate file, but did not work either, apparently the corruption is in the debug symbols.

Anyway, that is to say don't worry too much about debug builds, though if you managed to get an 82mb library, it may be worth a try.

**Comment by cleiner** [comment]
Thanks, @Kwizatz. In case you are interested, I just updated the patches for V8 9.0.257.17 (mini patch included):

[0000-add-mingw-main-code-changes.patch.txt](https://github.com/msys2/MINGW-packages/files/6321264/0000-add-mingw-main-code-changes.patch.txt)
[0001-add-mingw-toolchain.patch.txt](https://github.com/msys2/MINGW-packages/files/6321265/0001-add-mingw-toolchain.patch.txt)

**Comment by Kwizatz** [comment]
Sure am, if I am to submit a patch upstream it'll definitely have to be as close to master as possible.

Thanks!

**Comment by Biswa96** [comment]
Can anyone provide me a gist of v8 package history? Is there any mingw compliable project which uses v8? I shall try to upstream some common changes.

**Comment by Kwizatz** [comment]
> Can anyone provide me a gist of v8 package history? Is there any mingw compliable project which uses v8? I shall try to upstream some common changes.

I am not sure what do you mean, a package history for v8 MinGW builds?

You can follow the *-AG branches on my own repos, each branch contains the couple of patches needed to build:

https://github.com/AeonGames/v8
https://github.com/AeonGames/build

click on the branch combo and type -AG on the search box.

Last time I tried there were errors related to the Windows 11 SDK on the vcpkg branch, and I couldnt get to work easyly on MinGW, might try again soon.

Oh and sorry for the delayed reply.

**Comment by Biswa96** [comment]
The v8 package was updated or rebuilt recently. Bu the patches seems to be mingw specific. And upstream does not support mingw platform.

**Comment by Kwizatz** [comment]
Yes, that's the problem, they don't want to take in code not covered by their Continuous Integration because that means there is no one in charge to make sure the code does not break.

**Comment by Biswa96** [comment]
We have to rely on users feedback or who catch the issue first. Also it is not feasible to maintain our own fork with v8 like huge projects. Though the common fixes which can be reproduce with clang or msvc, can be sent to upstream.
