### ISSUE TITLE
[ucrt] sscanf not found via autotools

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#8374]
Example: https://github.com/msys2/MINGW-packages/commit/49e077c6b6ce45d670c7eb43654eabe9975e7a68

Workaround: `export ac_cv_func_sscanf=yes`

Known upstream: https://sourceforge.net/p/mingw-w64/mailman/message/37260466/

**Comment by jeroen** [comment]
Running into this problem as well for `gifsicle` : https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64-gcc10-UCRT/gifski-00install.html

**Comment by Biswa96** [comment]
Also in emacs, UCRT gcc can not link `_snprintf` (note the underscore)

According to [Microsoft][1]: 

> Beginning with the UCRT in Visual Studio 2015 and Windows 10, snprintf is no longer identical to _snprintf. 

[1]: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l

@lhmouse

**Comment by mati865** [comment]
Martin proposed patch at upstream: https://sourceforge.net/p/mingw-w64/mailman/message/37266372/

**Comment by Biswa96** [comment]
More source files 😟

**Comment by lazka** [comment]
This has been fixed upstream: https://github.com/mingw-w64/mingw-w64/commit/0dd9563a3ad71a
