### ISSUE TITLE
Hangs with OpenBLAS from 32-bit MinGW

### ISSUE THREAD

**Issue by szhorvat** [msys2/MINGW-packages#8399]
We see consistent hangs when using `mingw-w64-i686-openblas` and running the test suite of [igraph](https://github.com/igraph/igraph/) on GitHub Actions.  See here for more details:

https://groups.google.com/g/openblas-users/c/iRRfgOw8pKk/m/KfSs3njWAQAJ

I am reporting this here as well because it is possible that something is wrong with the 32-bit OpenBLAS that is included in MSYS2. For example, I notice that MSYS2's OpenBLAS is not built using USE_OPENMP=1, while all Linux distros I checked use this option. It is likely that at least some dependencies of OpenBLAS in MSYS2 are using OpenMP. While I have no evidence that the hang we see is related to this option, I thought this was useful to note. See also: https://github.com/xianyi/OpenBLAS/wiki/faq#multi-threaded

Currently, the reason why [igraph in MSYS2 MinGW](https://packages.msys2.org/package/mingw-w64-x86_64-igraph) uses vendored dependencies (which limit performance) is these hangs. (Ping @jannick0 who contributed igraph to MSYS2)

**Comment by lazka** [comment]
I have no idea, but I've created #8401

**Comment by lazka** [comment]
It built fine at least. We still need someone to say that this is an OK change to make though.

**Comment by jannick0** [comment]
> See also: https://github.com/xianyi/OpenBLAS/wiki/faq#multi-threaded

@szhorvat Wouldn't it be more efficient for universal use of the library to apply `openblas_set_num_threads(1)` at `igraph` runtime instead of hard-coding restrictive configs of the library build time here? 

> Currently, the reason why [igraph in MSYS2 MinGW](https://packages.msys2.org/package/mingw-w64-x86_64-igraph) uses vendored dependencies (which limit performance) is these hangs. (Ping @jannick0 who contributed igraph to MSYS2)

@szhorvat Well, not exactly. The reason for using internal libraries is to reduce dependencies which would potentially require `igraph` re-builds. Up and until now there was no complaint about performance issues, but I am open, of course. [Off-topic: The more pressing issue is to have a simple and stable procedure in place to build shared and static igraph libraries (with consistent header files working for both the shared and static library.)]

**Comment by szhorvat** [comment]
> @szhorvat Wouldn't it be more efficient for universal use of the library to apply `openblas_set_num_threads(1)` at `igraph` runtime instead of hard-coding restrictive configs of the library build time here?

Doing so would not be appropriate because:

 - igraph does not use OpenBLAS specifically, it just uses the BLAS API. It should not need to know what BLAS implementation is in use, and should not call anything OpenBLAS-specific. Some package systems, such as Anaconda, build packages against a generic BLAS and then make it possible to switch out the BLAS implementation later.
 - There is no reason to restrict OpenBLAS to a single thread when used with igraph. Up to the last released version, igraph itself does not directly use multi-threading features at all, so it does not have anything [that could conflict with igraph](https://github.com/xianyi/OpenBLAS/wiki/faq#how-can-i-use-openblas-in-multi-threaded-applications). (Whether any of its dependencies use multi-threading, I do not know. But I do not think they do.)
 - I expect that this problem is not igraph specific, it's just that we were the first to bring it up, as we run the test suite with MinGW 32-bit as well. We did not see this problem with OpenBLAS on other platforms.

> restrictive configs of the library

It's not clear to me if these are restrictive, or just ensuring compatibility. Is there no dependency of OpenBLAS in MSYS2 that uses OpenMP? There must be a reason why both Arch and Debian compile with `USE_OPENMP=1`.

> The reason for using internal libraries is to reduce dependencies which would potentially require `igraph` re-builds. Up and until now there was no complaint about performance issues, but I am open, of course. [

There is nothing wrong with using vendored libraries if that's what you prefer. You'd mostly miss out on this: Using external GLPK will bring significant performance improvements for the two functions that use it. Using external ARPACK will not only improve performance, but also numerical robustness (however, ARPACK in MSYS2 links to OpenBLAS and triggers this issue).

> The more pressing issue is to have a simple and stable procedure in place to build shared and static igraph libraries (with consistent header files working for both the shared and static library

Feel free to open an issue for this (so we can take the off-topic discussion there).

The shared lib headers are suitable for the static lib, but then users must `#define` `IGRAPH_STATIC` when compiling their programs that link to igraph statically. This is now mentioned in section 4.2 of the installation instructions. https://igraph.org/c/doc/igraph-Installation.html

**Comment by mati865** [comment]
You'd probably have to debug the hang to fix it for real.
With mingw-w64 GCC targets OpenMP is often the reason of hangs, not the fix for them.

**Comment by szhorvat** [comment]
> You'd probably have to debug the hang to fix it for real.

There's a slim chance of success given that we were unable to reproduce it locally (only on the CI).


> With mingw-w64 GCC targets OpenMP is often the reason of hangs, not the fix for them.

You might still want to check if any of the MSYS2 packages depending on OpenBLAS use OpenMP. If they do, not enabling USE_OPENMP goes against what the OpenBLAS folks say must be done.

**Comment by szhorvat** [comment]
FYI the hangs still happen consistently when all of the following are true:

 - igraph is compiled with OpenMP
 - OpenMP is not restricted to use a single thread
 - igraph links to OpenBLAS (even indirectly).

[The recommendation from OpenBLAS](https://github.com/xianyi/OpenBLAS/wiki/faq#multi-threaded) is clear: if using both OpenBLAS and OpenMP, OpenBLAS should be built with `USE_OPENMP=1`. This is not done in MSYS2.  Either this should be enabled, or OpenMP should be disabled for all packages that link to OpenBLAS.

**Comment by szhorvat** [comment]
I'll note that the setup in MSYS2 still goes straight against OpenBLAS's clearly documented requirements. That issue is not fixed, and can easily cause problems with other packages or other than 32-bit platforms.
