### ISSUE TITLE
[ucrt] msys2-ucrt64-gfortran 10.2.0: error compiling the _parameter_ variable in the module

### ISSUE THREAD

**Issue by zoziha** [msys2/MINGW-packages#8415]
`ff.f90` code:
```fortran
module ff
    real, parameter :: x = 1.0
end module
```
Command: gfortran -c ff.f90
Report an error: 
```
f951.exe: internal compiler error: Segmentation fault
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/msys2/MINGW-packages/issues> for instructions.
```
Error compiling the **parameter**(only for parameter) variable in the module, is it **a bug**?
![image](https://user-images.githubusercontent.com/32035096/115183265-09258500-a10e-11eb-9ae6-fcf61758c8ce.png)

![image](https://user-images.githubusercontent.com/32035096/115183253-ff9c1d00-a10d-11eb-8fc2-2c76c32687ea.png)

**Comment by lazka** [comment]
I can't reproduce. Maybe it depends on where the file is?

**Comment by Biswa96** [comment]
Is the screenshot of VSCode window?

**Comment by Brookszzh** [comment]
> I can't reproduce. Maybe it depends on where the file is?
---
I used msys2-**urct64**-fortran because of curiosity, and it had this error. When I used the same version of msys2-**mingw64**-fortran, the error did not appear.

**Comment by Brookszzh** [comment]
> Is the screenshot of VSCode window?
---
Yes, Windows-msys2-gfortran in VS Code.

**Comment by zoziha** [comment]
It seems that the issue of ucrt64-gfortran has not been fixed yet. 😜
![image](https://user-images.githubusercontent.com/32035096/126262938-e8c52006-80a3-45dd-89ea-67eebb16b779.png)
![image](https://user-images.githubusercontent.com/32035096/126263013-58d4558d-64fd-429b-a823-44589140d13b.png)

**Comment by jeremyd2019** [comment]
You're running ucrt64 binaries from a mingw64 shell.  That could mix in mingw64 dlls and cause issues.  Does this reproduce in a UCRT64 shell?

**Comment by zoziha** [comment]
Thank you, yes, I used `windows-git-bash`, which uses the mingw64 shell by default. I just tried to use the ucrt64 shell, the error disappeared, thank you very much @jeremyd2019 , I made a mistake myself (maybe I am used to using mingw64, I did not even realize this, I am very sorry), thank you all very much.
![image](https://user-images.githubusercontent.com/32035096/126264660-7f472ed2-c41b-4565-9048-63d7e633a8dd.png)
