### ISSUE TITLE
cmake can not work with ninja 

### ISSUE THREAD

**Issue by Maziar123** [msys2/MINGW-packages#8418]
I try use msys2 mingw64 tools : cmake(/mingw64/bin/cmake) with ninja(/usr/bin/ninja.exe) to compile hello world project

ninja 1.10.2
cmake  3.20.1
win10 x64 

CMake Error at CMakeLists.txt:3 (project):
  Running

   '/usr/bin/ninja.exe' '--version'

failed with:

   The system cannot find the file specified

**Comment by ZachBacon** [comment]
Have you installed the mingw-w64-x86_64-ninja package? (Assuming it's that and not the ucrt repo build) because ninja and cmake works just fine with me.

**Comment by Biswa96** [comment]
Please provide steps to reproduce your issue. FYI, this repository builds hundreds of packages with CMake and Ninja.

**Comment by Maziar123** [comment]
yes all done in msys2 shell D:\msys64\msys2_shell.cmd -mingw64

 pacman -S  ninja cmake

[
[helloworld.tar.gz](https://github.com/msys2/MINGW-packages/files/6337797/helloworld.tar.gz)
](url)

**Comment by ZachBacon** [comment]
> yes all done in msys2 shell D:\msys64\msys2_shell.cmd -mingw64
> 
>  pacman -S  ninja cmake
> 
> [
> [helloworld.tar.gz](https://github.com/msys2/MINGW-packages/files/6337797/helloworld.tar.gz)
> ](url)
> 
> 
> 
> 
> 
> 

Then yeah, you'd want most likely want mingw-w64-x86_64-cmake and mingw-w64-x86_64-ninja if you're going to use msys2_shell.cmd -mingw64

**Comment by Maziar123** [comment]
Yes in last i use ninja with mingw-w64-x86_64-cmake
 I remove ninja(pacman -R ninja)  and install mingw-w64-x86_64-ninja 

which ninja
/mingw64/bin/ninja

But i get same error seems cmake use last path ( '/usr/bin/ninja.exe' '--version')

**Comment by ZachBacon** [comment]
> Yes in last i use ninja with mingw-w64-x86_64-cmake
>  I remove ninja(pacman -R ninja)  and install mingw-w64-x86_64-ninja 
> 
> which ninja
> /mingw64/bin/ninja
> 
> But i get same error seems cmake use last path ( '/usr/bin/ninja.exe' '--version')

You need to regenerate your cmake cache now in your build directory so that it finds your ninja executable.

**Comment by Maziar123** [comment]
> > Yes in last i use ninja with mingw-w64-x86_64-cmake
> > I remove ninja(pacman -R ninja)  and install mingw-w64-x86_64-ninja
> > which ninja
> > /mingw64/bin/ninja
> > But i get same error seems cmake use last path ( '/usr/bin/ninja.exe' '--version')
> 
> You need to regenerate your cmake cache now in your build directory so that it finds your ninja executable.

of course 
before it Full clean cmake cashes folder but seems not found ninja path  

 cmake .
CMake Error at CMakeLists.txt:3 (project):
  Running

   '/usr/bin/ninja.exe' '--version'

  failed with:

   The system cannot find the file specified


-- Configuring incomplete, errors occurred!
See also "D:/sample-test/App/helloworld/CMakeFiles/CMakeOutput.log".

**Comment by ZachBacon** [comment]
Run which cmake and tell me the path of it.

**Comment by Maziar123** [comment]
$ which cmake
/mingw64/bin/cmake

**Comment by ZachBacon** [comment]
Do me a favour, try configuring from a clean source directory, even if you have to remove the project and extract it again and then run the cmake command, because I have a feeling you still have dirty build files from the previous attempt.

**Comment by Maziar123** [comment]
Do it full clean folder  Same error

**Comment by Maziar123** [comment]
note i use PreLoad.cmake : 

SET(CMAKE_GENERATOR "Ninja" CACHE INTERNAL "" FORCE)
SET(CMAKE_TOOLCHAIN_FILE "./ToolChainNinja.cmake" CACHE INTERNAL "" FORCE)

**Comment by ZachBacon** [comment]
That could be very well the case, if you can don't load that toolchain and manually set the generator using cmake -G"Ninja" and see how it goes.

**Comment by Maziar123** [comment]
Work well 
Thx i recheck my cross platform toolchain file  and see same problem Create new topic
