### ISSUE TITLE
The 'docutils<0.17,>=0.12' distribution was not found and is required by Sphinx

### ISSUE THREAD

**Issue by podsvirov** [msys2/MINGW-packages#8422]
I get this error when trying to build documentaion for `cglm` at #8421.
``` shell
    File "D:/a/_temp/msys/msys64/ucrt64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
      raise DistributionNotFound(req, requirers)
  pkg_resources.DistributionNotFound: The 'docutils<0.17,>=0.12' distribution was not found and is required by Sphinx
```
Current `mingw-w64-python-docutils` version in `pacman` repo is `0.17.1-1`.

**Comment by naveen521kk** [comment]
I think the updator should look for this or else it's going to cause problems. let me see.

**Comment by lazka** [comment]
not sure if helpful, but `pip check` can test for this after things are installed

**Comment by naveen521kk** [comment]
when updating I would be having the version of the dependencies needed. So, maybe it's just about cross-checking the pkgver of the reverse dependency and update only if it satisfies?

Or simply, rather than we doing the hard work, check the archlinux's version and update only when they update it?

**Comment by podsvirov** [comment]
@lazka, thanks fo fixing.
