### ISSUE TITLE
mingw-w64-libopenmpt-modplug?

### ISSUE THREAD

**Issue by mxmilkiib** [msys2/MINGW-packages#8435]
I see there is https://packages.msys2.org/base/mingw-w64-libopenmpt and https://packages.msys2.org/base/mingw-w64-libmodplug but there is also a shim method of using libopenmpt as libmodplug, which is used for https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libopenmpt-modplug and https://packages.debian.org/sid/libopenmpt-modplug-dev.

If this there were a libopenmpt-modplug package, I am informed that Mixxx should be able to build with module playback support for Windows for the first time.

pinging @drfiemost

**Comment by drfiemost** [comment]
Sure it can be done. But it's just a wrapper around libopenmpt that replaces libmodplug.
I don't get why Mixxx can't be built against the current libmodplug package.

**Comment by mxmilkiib** [comment]
Because it's not thread safe, where as libopenmpt is.

**Comment by drfiemost** [comment]
Package is available: https://packages.msys2.org/base/mingw-w64-libopenmpt-modplug
