### ISSUE TITLE
[opus] ERROR: opus not found using pkg-config

### ISSUE THREAD

**Issue by MarshalX** [msys2/MINGW-packages#8453]
pacman --noconfirm -Sy
pacman --noconfirm -S msys/make
pacman --noconfirm -S mingw64/mingw-w64-x86_64-opus
pacman --noconfirm -S diffutils
pacman --noconfirm -S pkg-config

Ref: [build_ffmpeg_win.sh](https://github.com/desktop-app/patches/blob/master/build_ffmpeg_win.sh)
Issue: https://stackoverflow.com/questions/67122637/error-on-windows-opus-not-found-using-pkg-config
GitHub workflow: [win.yml](https://github.com/telegramdesktop/tdesktop/blob/dev/.github/workflows/win.yml)

<details>
  <summary>Log</summary>

```
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 ucrt64 is up to date
 msys is up to date
resolving dependencies...
looking for conflicting packages...

Packages (1) make-4.3-1

Total Download Size:   0.45 MiB
Total Installed Size:  1.48 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
downloading make-4.3-1-x86_64.pkg.tar.xz...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing make...
:: Running post-transaction hooks...
(1/1) Updating the info directory file...
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-opus-1.3.1-3

Total Download Size:   0.28 MiB
Total Installed Size:  1.16 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
downloading mingw-w64-x86_64-opus-1.3.1-3-any.pkg.tar.zst...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing mingw-w64-x86_64-opus...
resolving dependencies...
looking for conflicting packages...

Packages (1) diffutils-3.7-1

Total Download Size:   0.33 MiB
Total Installed Size:  1.37 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
downloading diffutils-3.7-1-x86_64.pkg.tar.xz...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing diffutils...
:: Running post-transaction hooks...
(1/1) Updating the info directory file...
resolving dependencies...
looking for conflicting packages...

Packages (1) pkg-config-0.29.2-4

Total Download Size:   0.20 MiB
Total Installed Size:  0.55 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
downloading pkg-config-0.29.2-4-x86_64.pkg.tar.zst...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing pkg-config...
ERROR: opus not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
Error: Process completed with exit code 1.
```

</details>

**Comment by 1480c1** [comment]
could you try providing the `ffbuild/config.log` file?

**Comment by Biswa96** [comment]
`pacman -S mingw-w64-x86_64-pkg-config` may help.

**Comment by MarshalX** [comment]
> could you try providing the `ffbuild/config.log` file?

Its on github actions. No idea how to output it

**Comment by MarshalX** [comment]
> `pacman -S mingw-w64-x86_64-pkg-config` may help.

It doesnt help

**Comment by MarshalX** [comment]
How I can install `mingw-w64-x86_64-opu` with some hash of commit to rollback to prev version? https://github.com/msys2/MINGW-packages/commits/master/mingw-w64-opus

**Comment by c0re100** [comment]
> could you try providing the `ffbuild/config.log` file?

ffbuild/config.log
```
./ffconf.pvFYa9tf/test.c(3): warning C4311: 'type cast': pointer truncation from 'OpusMSEncoder *(__cdecl *)(opus_int32,int,int,int *,int *,unsigned char *,int,int *)' to 'long'
./compat/windows/mslink -libpath:/e/tdesktop/Libraries/win64/ffmpeg/../opus/win32/VS2015/x64/Release -nologo -I/mingw64/include/opus -libpath:/mingw64/lib -out:./ffconf.pvFYa9tf/test.exe ./ffconf.pvFYa9tf/test.o opus.lib m.lib ssp.lib
LINK : warning LNK4044: unrecognized option '/IE:/tdesktop/ThirdParty/msys64/mingw64/include/opus'; ignored
LINK : fatal error LNK1181: cannot open input file 'ssp.lib'
ERROR: opus not found using pkg-config
```

**Comment by 1480c1** [comment]
> > could you try providing the `ffbuild/config.log` file?
> 
> Its on github actions. No idea how to output it

You could do
```bash
./configure ... || {
    cat ffbuild/config.log
    exit 1
}
```



> How I can install `mingw-w64-x86_64-opus` with some hash of commit to rollback to prev version? https://github.com/msys2/MINGW-packages/commits/master/mingw-w64-opus

you can see if that package still exists in https://repo.msys2.org/mingw/x86_64/ and run `pacman -U url.tar.zst`, we do not keep a lot of the older versions because of size constraint on the server

**Comment by 1480c1** [comment]
> > could you try providing the `ffbuild/config.log` file?
> 
> ffbuild/config.log
> 
> ```
> ./ffconf.pvFYa9tf/test.c(3): warning C4311: 'type cast': pointer truncation from 'OpusMSEncoder *(__cdecl *)(opus_int32,int,int,int *,int *,unsigned char *,int,int *)' to 'long'
> ./compat/windows/mslink -libpath:/e/tdesktop/Libraries/win64/ffmpeg/../opus/win32/VS2015/x64/Release -nologo -I/mingw64/include/opus -libpath:/mingw64/lib -out:./ffconf.pvFYa9tf/test.exe ./ffconf.pvFYa9tf/test.o opus.lib m.lib ssp.lib
> LINK : warning LNK4044: unrecognized option '/IE:/tdesktop/ThirdParty/msys64/mingw64/include/opus'; ignored
> LINK : fatal error LNK1181: cannot open input file 'ssp.lib'
> ERROR: opus not found using pkg-config
> ```

Sounds like you are using a msvc toolchain, that is not compatible with a mingw-w64 toolchain and the libraries are not intercompatible from mingw-w64 -> msvc, mingw-w64 can handle msvc generated libraries though

**Comment by 1480c1** [comment]
Seems like https://github.com/telegramdesktop/tdesktop/blob/dev/.github/workflows/win.yml#L264 has the stuff for building opus with msvc

**Comment by MarshalX** [comment]
> Seems like https://github.com/telegramdesktop/tdesktop/blob/dev/.github/workflows/win.yml#L264 has the stuff for building opus with msvc

This is used to build webrtc. Not for ffmpeg

**Comment by c0re100** [comment]
> > > could you try providing the `ffbuild/config.log` file?
> > 
> > 
> > ffbuild/config.log
> > ```
> > ./ffconf.pvFYa9tf/test.c(3): warning C4311: 'type cast': pointer truncation from 'OpusMSEncoder *(__cdecl *)(opus_int32,int,int,int *,int *,unsigned char *,int,int *)' to 'long'
> > ./compat/windows/mslink -libpath:/e/tdesktop/Libraries/win64/ffmpeg/../opus/win32/VS2015/x64/Release -nologo -I/mingw64/include/opus -libpath:/mingw64/lib -out:./ffconf.pvFYa9tf/test.exe ./ffconf.pvFYa9tf/test.o opus.lib m.lib ssp.lib
> > LINK : warning LNK4044: unrecognized option '/IE:/tdesktop/ThirdParty/msys64/mingw64/include/opus'; ignored
> > LINK : fatal error LNK1181: cannot open input file 'ssp.lib'
> > ERROR: opus not found using pkg-config
> > ```
> 
> Sounds like you are using a msvc toolchain, that is not compatible with a mingw-w64 toolchain and the libraries are not intercompatible from mingw-w64 -> msvc (primarily because of differing naming conventions with certain things, you could in theory try getting it to work, but I don't think it's worth the hassle), mingw-w64 can handle msvc generated libraries though

But there is no problem without libssp (mingw-w64-x86_64-opus-1.3.1-1)🤔

**Comment by 1480c1** [comment]
Seems like it should use that instead though since it explicitly asks for `--toolchain=msvc` https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Patches/build_ffmpeg_win.sh#L15

In generally it is recommended to stick with one toolchain all the way through instead of mixing mingw-w64 and msvc since mingw-w64 normally links to msvcrt.dll (the one that has existed since windows XP days) and msvc will link to it's own specific versioned msvcrt and there is no guarantee from Microsoft that something linked to one will work with the other.

**Comment by MarshalX** [comment]
> You could do
> 
> ```shell
> ./configure ... || {
>     cat ffbuild/config.log
>     exit 1
> }
> ```

`LINK : fatal error LNK1181: cannot open input file 'ssp.lib'` mm? Did I copy right row?)

**Comment by 1480c1** [comment]
You might want to consider requesting that the https://github.com/telegramdesktop/opus/commits/tdesktop fork be updated to use opus 1.3.1 instead of 1.3 as a CMakeLists.txt is provided there, and it generates the required opus.pc file that ffmpeg looks for

**Comment by alex-tee** [comment]
not sure if related but my builds started failing today thanks to opus:

https://github.com/msys2/MINGW-packages/issues/8240#issuecomment-826479169

**Comment by MarshalX** [comment]
Telegram's fix: https://github.com/telegramdesktop/tdesktop/commit/8f031f67920997a109d0474ac8dbc13bf4ccb694 (added NuGet)
