### ISSUE TITLE
pkgconfig-1.7.4-1 with '--static' switch don't output anymore the 'Libs.private'

### ISSUE THREAD

**Issue by punesemu** [msys2/MINGW-packages#8473]
After updating the packages mingw-w64-i686-pkgconf-1.7.4-1, mingw-w64-x86_64-pkgconf-1.7.4-1and pkgconf-1.7.4-1 I can't compile my emulator anymore. After studying the causes I noticed that the pkgconfig with the '--static' option no longer output the 'Libs.private', which of course it did correctly with the previous version.

**Comment by lazka** [comment]
thanks

**Comment by punesemu** [comment]
For more help this is the output with version 1.7.3-2:
```bash
$ pkgconf --static --libs libarchive
-LC:/msys64/mingw64/lib -larchive -lregex -lexpat -llzma -lzstd -llz4 -lbz2 -lz -lbcrypt
```
and this with 1.7.4-1:
```bash
$ pkgconf --static --libs libarchive
-LC:/msys64/mingw64/lib -larchive
```
where the difference is precisely the 'Libs.private' which is no longer displayed.

**Comment by kleisauke** [comment]
This was fixed via commit https://github.com/pkgconf/pkgconf/commit/444846dd2dfc9e3a5ea4904826c1c7a4b9b5589b upstream.

**Comment by lazka** [comment]
thanks. #364 suggests that it's just broken differently now
