### ISSUE TITLE
opus crashes clang

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#8481]
building opus crashes jeremys clang compiler -> cannot pop empty stack followed by a stackdump.
tried disabling stack smashing to no avail so it does not seem to be the problem.

**Comment by revelator** [comment]
hmm another case of sse misdetection it seems.

adding CFLAGS+=" -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2" allows it to build.

**Comment by mati865** [comment]
> 
> 
> building opus crashes jeremys clang compiler -> cannot pop empty stack followed by a stackdump.
> tried disabling stack smashing to no avail so it does not seem to be the problem.

Is is 32-bit compiler?

**Comment by revelator** [comment]
yep seems this only happens in the 32 bit builds adding the above flags will allow it to build though.
kinda weird because other projects using sse does not seem to throw this.

**Comment by StarWitch** [comment]
@revelator Thanks for this issue. It was helpful for figuring out why my 32-bit compile (which also happened to involve an app using Opus) was failing with "cannot pop empty stack." Turns out SSE wasn't being properly enabled in the build, too.

**Comment by revelator** [comment]
np :) hmm the msys2 build system might not be appropriate for clang as gcc uses auto intrinsics which im not certain clang supports.

**Comment by revelator** [comment]
maybe set march to a minimum value of core2 or pentium4 ? for clang builds.
