### ISSUE TITLE
libheif not shipping cmake files

### ISSUE THREAD

**Issue by kmilos** [msys2/MINGW-packages#8494]
Probably because it is not being built w/ cmake ;)

Switch over from autotools?

**Comment by lazka** [comment]
any change that results in less autotools is a good change. Ideally there would still be a pkgconfig file though.

**Comment by kmilos** [comment]
The pkgconfig file is already there in the OOTB CMakeLists.txt, just some minor patching needed...

However, I noticed a few differences between the OOTB CMake installed files and OOTB autotools installed files, any thought if these are a problem?

1. Only shared library by default of course (don't think any existing dependants link statically anyway)
2. No SOVERSION in dll name any longer (no biggie I guess, just needs rebuild of dependants)
3. No linking against `libwinpthreads` and no `-lpthreads` in `Libs.private` of the pkgconfig file (don't see any code using pthread directly, so not sure why it was there in the first place?)
4. Quite a few more (private and unnecessary?) headers installed
5. No man pages
6. No mime types in ${MINGW_PREFIX}/share/mime/packages/[avif,heif].xml
7. No ${MINGW_PREFIX}/share/thumbnailers/heif.thumbnailer
