### ISSUE TITLE
[Request] Add a Compiler / Linker / Windres / Whatever Flag to DISABLE forced linking against default-manifest.o

### ISSUE THREAD

**Issue by MeerMusik** [msys2/MINGW-packages#8495]
I am in the middle of trying to compile wxWidgets (self-built). Everything works except that LD.exe ALWAYS FORCIBLY is linking against the 'default-manifest.o' - which already costed my a whole day trying to disable that behaviour. And also because I thought wxWidgets is broken.

The Problem is:

* My Resource File gets completely ignored!
* The wxWidgets Resource File gets completely ignored!

Why is this an Issue:

* I need to define Windows Versions, HiDPI and Feature Flags

That you are forcibly push the 'default-manifest.o' down our throats is an absolute no go! Especially when there is no known Flag to disable it or overwrite it. As much as I love what you do otherwise, these things make me want to go back to VC++. Please finally fix this! Or point the way and I would try to find my way through whatever config Files and take a look at it myself. It has been much too long already! Thank You!

**Comment by lazka** [comment]
!!!

**Comment by lazka** [comment]
hm, from what I understand this just mirrors what msvc produces.

Including my own manifest works fine here at least. What makes you think yours is getting ignored?

**Comment by mati865** [comment]
According to GCC devs adding any manifest will make GCC ignore `default-manifest.o`. Could you at least provide MWE/SSCCE/MCVE/(whatever else is it called)?

**Comment by Biswa96** [comment]
MCVE = a minimal, complete and verifiable example [link](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by MeerMusik** [comment]
Sorry about that. It turned out, whenever UNIX is defined, the call of 'windres.exe' is disabled. Is there a way to disable / enable / overwrite a Macro etc. on MinGW's end?

The Problem here lies either
* completely within the CodeLite IDE: As I use MSYS2 = Unix Path, I have to use the CodeLite Unix Generator
* or also with MinGW-w64

I have a Bug Hunt and Discussion with the CodeLite Maintainer currently. Even if it turns out, that CodeLite is unnecessarily setting whatever Macro / Flag, it would still be good to have such a Feature in case of "bad times like these". Currently, even switching on the Registry Flag to allow loading of external Manifest Files does not work, as it always links the default-manifest - which then disables loading of the externally provided one (copied into the Executable Directory). Very annoying.

I have tried countless other IDE's and MinGW-w64 and MSYS2 MinGW-w64 for 8 years (with breaks in between) and never had that Issue. So i assumed that LD is broken. But it looks more and more because some setting forcibly disables the call of 'windres.exe' on Windows when 'UNIX' or  whatever is set.

Again, sorry. Have a nice weekend
Olli

**Comment by mati865** [comment]
Maybe you are using wrong compiler?

MSYS2 susbystem compiler does define `unix` because it's not targetting Win32:

<details>
<summary>Spoiler</summary>

```
mateusz@DESKTOP-MATI MSYS /d/tmp
$ cat tmp.c
#include <stdio.h>

int main() {
#ifdef UNIX
  printf("UNIX\n");
#endif
#ifdef unix
  printf("unix\n");
#endif
#ifdef __unix
  printf("__unix\n");
#endif
#ifdef __unix__
  printf("__unix__");
#endif
  return 0;
}

mateusz@DESKTOP-MATI MSYS /d/tmp
$ /usr/bin/gcc tmp.c && ./a.exe
unix
__unix
__unix__
mateusz@DESKTOP-MATI MSYS /d/tmp
$ /mingw64/bin/gcc tmp.c && ./a.exe

```

</details>
