### ISSUE TITLE
I would suggest a GCC patch to put in the GCC 10.x which solveds the jumpy issue of debugging

### ISSUE THREAD

**Issue by asmwarrior** [msys2/MINGW-packages#8530]
Hi, an annoying issue when debugging with GDB is that when exit the function scope, it will jump to the definition of the variable.

This is the bug: 

[58123 – [4.8/4.9/5 Regression] debug line not tracked for last autovariable dtor](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58123)

[49951 – [4.5/4.6/4.7 Regression] Debug stepping behavior regarding g++ Class destructor has changed for the worse starting at gcc 4.5.0](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=49951)

While, this is recently fixed in the GCC trunk, and the GCC 11.

So, I would suggest adding this patch to GCC 10.x in msys2. See this patch:

https://gcc.gnu.org/g:006783f4b165dff25aae3697920fcf54754dddd4

The patch is simple, which only changes several lines in parser.c and semantics.c.

Another/alternative way to fix this would be: just update the GCC compiler to 11.1 release in msys2, and see it is fixed in this release.

Thanks.

**Comment by lazka** [comment]
GCC 11 progress is here: #8320

If there is no progress we might consider backporting. Thanks

**Comment by oltolm** [comment]
Can be closed. #8320 has been merged.
