### ISSUE TITLE
clang doesn't fail to link non-existent libstdc++

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#8549]
While diagnosing build failure of mingw-w64-mecab, I noticed that it was not linking dynamically because libtool couldn't find a corresponding DLL for `-lstdc++`.  I expected that libstdc++ wouldn't be present (clang prefix uses libc++ instead).  What I didn't expect is that configure already tests linking to `-lstdc++`, and that test **succeeds** on clang64.  This seems to be doing the right thing, but still falling into a trap.

```
clang -o /dev/null -lstdc++ -x c - <<<"int main() { return 0; }"
```
succeeds, but
```
find /clang64 -name libstdc++\*
```
finds nothing.  @mati865 ?

**Comment by jeremyd2019** [comment]
configure test:
https://github.com/taku910/mecab/blob/master/mecab/configure.in#L53

**Comment by mati865** [comment]
These lines detects when using `-lstdc++` and make Clang use it's configured C++ library (which means `-lc++` in our case): https://github.com/llvm/llvm-project/blob/36430d44edba9063a08493c89864edf5f071d08c/clang/lib/Driver/Driver.cpp#L389-L405

**Comment by jeremyd2019** [comment]
So what should this configure test do to really know if libstdc++ can be linked?

**Comment by mati865** [comment]
Why does it even check for c++ library? Calling c++ compiler without `-nodefaultlibs` would work for everyone.

**Comment by jeremyd2019** [comment]
I don't really know.  I assume some platform somewhere needed to link it explicitly.  But I do know that check is unnecessary here so we could just patch it out
