### ISSUE TITLE
[vlc] Compilation fix on MSYS2-MinGW-w64 toolchain

### ISSUE THREAD

**Issue by davide-prade** [msys2/MINGW-packages#8566]
I attach a patch to resolve a compilation issue when compile under MSYS2-MinGW-w64 toolchain.

```
In file included from C:/msys64/mingw64/include/vlc/plugins/vlc_common.h:409:
C:/msys64/mingw64/include/vlc/plugins/vlc_threads.h: In function 'int vlc_poll(pollfd*, unsigned int, int)':
C:/msys64/mingw64/include/vlc/plugins/vlc_threads.h:90:11: error: 'poll' was not declared in this scope
   90 |     val = poll(fds, nfds, timeout);
      |           ^~~~
C:/msys64/mingw64/include/vlc/plugins/vlc_threads.h:90:11: note: the macro 'poll' had not yet been defined
C:/msys64/mingw64/include/vlc/plugins/vlc_threads.h:95: note: it was later defined here
   95 | # define poll(u,n,t) vlc_poll(u, n, t)
```

[fix.zip](https://github.com/msys2/MINGW-packages/files/6422424/fix.zip)

**Comment by 1480c1** [comment]
Is this for compiling with libvlc or compiling vlc itself? Also is this present in the current vlc master branch or vlc-3.0?

**Comment by davalv** [comment]
This is for compiling with libvlc.
At the moment I am using "_mingw64/mingw-w64-x86_64-vlc 3.0.12-6_", but the problem also occurs in previous versions.
