### ISSUE TITLE
Proposal to enhance mingw-w64-qemu

### ISSUE THREAD

**Issue by heljkon** [msys2/MINGW-packages#8567]
Hi,

recently I prepared the mingw-w64-spice recipe. Of course I did this, because I want qemu to run with spice.

The current state of mingw-w64-qemu is not very good - it doesn't build. 

And even the last version has some issues in my opinion, because everything is just put into /mingw64/bin 
I guess the reason for /mingw64/bin is the strange behaviour of qemu configure. I presuse it works this way, because for windows configure is indented to prepare a windows package - make install puts it all in one dir, make installer uses this dir.

I would propose to create a recipe which would do the following
- Integrate more features by using build deps to activate and optional deps to select by user: this way the features wouldn't cause a huge amount of deps (see https://github.com/msys2/MINGW-packages/issues/8506)
- Use a different base location: put most binary stuff to /mingw64/lib/qemu and provide wrappers in /mingw64/bin, move other stuff to suitable locations in /mingw64/share/
- split the package in several binary packages
- repair the build problems: my local tests work 

This proposal wouldl turn the recipe upside down, which may not make everyone happy:
I would like to hear your opinion before, because I don't want to work for the bin.

Regards

**Comment by lazka** [comment]
Any fix to make it build/update are welcome. Note that we generally try to avoid splitting packages to keep things simple.

**Comment by lazka** [comment]
I'm going to revert qemu to 5.1 for starters, so we have a working base.

**Comment by heljkon** [comment]
> I'm going to revert qemu to 5.1 for starters, so we have a working base.

I would start with 5.2, because I already built it. Never tried 5.1

**Comment by lazka** [comment]
ok, I've create #8568 just to see if/how it works.

PRs welcome.
