### ISSUE TITLE
libc++: tries to use lgamma_r when it's not present

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#8588]
See https://github.com/msys2/MINGW-packages/issues/8587#issuecomment-833739884.

From https://github.com/llvm/llvm-project/blob/d480f968ad8b56d3ee4a6b6df5532d485b0ad01e/libcxx/include/random#L4149-L4159:

```C++
#ifndef _LIBCPP_MSVCRT_LIKE
extern "C" double lgamma_r(double, int *);
#endif

inline _LIBCPP_INLINE_VISIBILITY double __libcpp_lgamma(double __d) {
#if defined(_LIBCPP_MSVCRT_LIKE)
  return lgamma(__d);
#else
  int __sign;
  return lgamma_r(__d, &__sign);
#endif
```

Somehow `_LIBCPP_MSVCRT_LIKE` is not defined?

/cc @mati865

**Comment by jeremyd2019** [comment]
Should be defined at https://github.com/llvm/llvm-project/blob/49e7be2e5ba1759ae9d4ce9843ce2467cf7823a5/libcxx/include/__config#L281, #if defined(_WIN32).  Strange

**Comment by jeremyd2019** [comment]
Oops, https://github.com/llvm/llvm-project/commit/0d7bd72f5ab48b2f4a903e21985ae004c12ce265 was in llvm 12, not 11

**Comment by neheb** [comment]
Can it be backported?

**Comment by jeremyd2019** [comment]
This should be fixed now that LLVM 12 was merged and built
