### ISSUE TITLE
[gnome-latex] Failed to open file “/mingw64/share/gnome-latex/ui/ui.xml”: No such file or directory

### ISSUE THREAD

**Issue by alecn2002** [msys2/MINGW-packages#8589]
> $ gnome-latex
> 
> ** (gnome-latex.exe:21632): ERROR **: 21:02:15.955: main_window.vala:349: Failed to open file “/mingw64/share/gnome-latex/ui/ui.xml”: No such file or directory
> 
> 

Just installed, can not start it

**Comment by revelator** [comment]
looks like some windows path conversion issue, guess we need some patching here.

**Comment by naveen521kk** [comment]
Maybe report upstream?

**Comment by Biswa96** [comment]
I think this is a mingw specific issue. We may need to add relocation functions which reorder the paths, see mingw-w64-pathtools.

**Comment by alecn2002** [comment]
Yes, this is MinGW specific issue, that's why I've posted it in MINGW-packages.
I didn't see this issue under "true" Linux (more precize Ubuntu 18.04)

**Comment by naveen521kk** [comment]
I could see that upstream is dead https://gitlab.gnome.org/Archive/gnome-latex. Maybe if this is a problem in Vala we should fix them.

**Comment by revelator** [comment]
pathtools might do the trick, question would then be should we patch vala or glib2 ? i myself would opt for glib2 as i dont know vala 
and it might help with other tools using the same function. Whats your take on it ?.

**Comment by revelator** [comment]
this might help also as it seems vala should indeed spew out a windows path it might be because the vala files need to be regenerated with the mingw vala.

**Comment by Biswa96** [comment]
Which commit did fix it?
