### ISSUE TITLE
Create a Code Of Conduct

### ISSUE THREAD

**Issue by naveen521kk** [msys2/MINGW-packages#8597]
At the meeting on `2021-04-17`, we decided to come up with a Code Of Conduct. This issue is for discussion on what we can potentially copy for a CoC.

**Comment by lazka** [comment]
* Python: https://www.python.org/psf/conduct/
* Rust: https://www.rust-lang.org/policies/code-of-conduct
* Arch: https://gitlab.archlinux.org/archlinux/service-agreements/-/blob/master/code-of-conduct.md (imo this is too specific to Arch things, but ymmv)

**Comment by lazka** [comment]
Seems many are based on https://www.contributor-covenant.org/version/2/0/code_of_conduct/ which seems clear and straight forward.

It requires a contact email. I'd suggest to link to https://www.msys2.org/contact/ instead and have a section there for CoC, which one or more email addresses or other contact points.

Any thoughts on that?

**Comment by lazka** [comment]
no complains on discord either, so let's do this then.

**Comment by lazka** [comment]
Website changes: https://github.com/msys2/msys2.github.io/pull/137

**Comment by lazka** [comment]
all done I think
