### ISSUE TITLE
mingw-w64-i686-gcc-10.3.0-1: internal compiler error when using designated initializers in C++ code

### ISSUE THREAD

**Issue by mkolleck** [msys2/MINGW-packages#8602]
After updating from mingw-w64-i686-gcc-10.2.0-10 to mingw-w64-i686-gcc-10.3.0-1, the following code produces an internal compiler error:
```
union U
{
  struct
  {
    unsigned char a;
  };

  unsigned char b[1];
};

void f(unsigned char a)
{
  union U u = { .a = a };
}
```
Steps to Reproduce:
1. Store example code as `ice.cpp`.
2. Compiling with gcc-10.2 on a different machine that was not updated, yet, succeeds: `g++ -c -o /dev/null ice.cpp`.
3. Compiling with updated gcc-10.3 results in internal compiler error:
```
ice.cpp: In function 'void f(unsigned char)':
ice.cpp:13:26: internal compiler error: in get_or_insert_ctor_field, at cp/constexpr.c:3314
   13 |     union U u = { .a = a };
      |                          ^

ice.cpp:13:26: internal compiler error: Aborted
g++.exe: internal compiler error: Aborted signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/msys2/MINGW-packages/issues> for instructions.
```
This is probably a bug in GCC itself, but the output said to file the bug here.

With different compiler options, there are more interesting results:

* Adding `-ansi` to the command line lets the compilation succeed.
* Adding `-ansi -pedantic` to the command line lets the compilation succeed and produces the following warnings:
```
ice.cpp:4:5: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
    4 |     {
      |     ^
ice.cpp: In function 'void f(unsigned char)':
ice.cpp:13:19: warning: C++ designated initializers only available with '-std=c++2a' or '-std=gnu++2a' [-Wpedantic]
   13 |     union U u = { .a = a };
      |                   ^
```
* Adding `-ansi -pedantic -std=gnu++2a` to the command line causes the ICE, again.

**Comment by oscarfv** [comment]
Thank you. I can reproduce the problem on GNU/Linux, gcc >= 10.3. Please file a bug report on https://gcc.gnu.org/bugzilla/ explicitly stating on the summary that it is a regression vs. 10.2. Regressions have a high priority, more so when they are ICEs.

**Comment by oscarfv** [comment]
Forgot to mention: after filing the bugzilla PR please put a link to it here for future reference. Thanks again.

**Comment by mkolleck** [comment]
While I was waiting for my GCC Bugzilla account to get created, this was already reported by a Gentoo developer: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100489

**Comment by oltolm** [comment]
Fixed upstream, can be closed.
