### ISSUE TITLE
[mingw-w64-protobuf] No static library in package

### ISSUE THREAD

**Issue by davidgiven** [msys2/MINGW-packages#8609]
The package only contains dynamic libraries (*.dll.a), with no static libraries (*.a). This makes producing static executables impossible.

This got reported back in 2016 as #1692, but it looks like it got closed with no action.

**Comment by Biswa96** [comment]
Hi @davidgiven Thank you for bumping this issue. I have added a pull request to build static library here https://github.com/msys2/MINGW-packages/pull/8611. Would you like to test the CI artifacts from that PR? Click on the 'check' tab in that PR -> download the MINGW64-packages.zip if you are using mingw64 (the blue icon) -> extract the package from that zip file -> install it with `pacman -U` command.

**Comment by Biswa96** [comment]
The new package is in Pacman repo now and can be upgraded with `pacman -Syu` command. Please test.

**Comment by davidgiven** [comment]
Yes, I can confirm that this now works fine after upgrading. Thanks for the fast fix! (Although I'm a little worried about the gigantic executable size afterwards. I need to check my dead code elimination...)
