### ISSUE TITLE
[kirigami2-qt5] Programs are not able to use Kirigami because of library names

### ISSUE THREAD

**Issue by im-tem** [msys2/MINGW-packages#8610]
Because "kirigamiplugin" is called "libkirigamiplugin.dll" it is not possible to run programs that are written using Kirigami framework.

**Comment by Biswa96** [comment]
That how DLL names are prefixed with 'lib' in mingw and other shared libraries in GNU/Linux distributions. The program or build system of a program should automatically find the DLL name and link with it.

**Comment by Biswa96** [comment]
kirigami plugin shared library name was fixed. Here is the list of DLLs in kirigami2-qt5 mingw package.

```
$ pacman -Fl $MINGW_PACKAGE_PREFIX-kirigami2-qt5 | cut -d ' ' -f 2 | grep -i "\.dll"
mingw64/bin/libKF5Kirigami2.dll
mingw64/lib/libKF5Kirigami2.dll.a
mingw64/share/qt5/qml/org/kde/kirigami.2/KirigamiPlugin.dll
mingw64/share/qt5/qml/org/kde/kirigami.2/libKirigamiPlugin.dll.a
```
