### ISSUE TITLE
GDB won't load an x64 executable

### ISSUE THREAD

**Issue by YuliaS11** [msys2/MINGW-packages#8633]
When I try to run the compiled file, generated with g++ 10.3 with the associated GDB from the default precompiled package, it reports:

> 
> This GDB was configured as "x86_64-w64-mingw32".
> This GDB was configured as follows:
>    configure --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32
>              --with-auto-load-dir=$debugdir:$datadir/auto-load
>              --with-auto-load-safe-path=$debugdir:$datadir/auto-load
>              --with-expat
>              --with-gdb-datadir=/mingw64/share/gdb (relocatable)
>              --with-jit-reader-dir=/mingw64/lib/gdb (relocatable)
>              --without-libunwind-ia64
>              --with-lzma
>              --without-babeltrace
>              --without-intel-pt
>              --with-mpfr
>              --with-xxhash

And proceed to do nothing, likely due to the program created as x64. However, when compiling with the x86 x86_64-w64-mingw32-g++, it causes compile error. QT 5.12.2 is being used.
Do I need to build this for myself?

**Comment by Biswa96** [comment]
Would you like to share the solution with us?
