### ISSUE TITLE
Can't build Qt5 with latest Clang 12.0.0

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#8640]
yesterday, I have pushed some changes #8630 to fix building Qt5 on Clang64, the building completed successfully with clang 11.0.0
This morning after @lazka merged my changes, the building fails with Clang 12.0.0 throwing messages like:
```
lld-link: error: undefined symbol: pthread*
```

See: https://github.com/msys2/msys2-autobuild/commit/4ba4930f7e8893333ebf1d65c04342c7fa128faf/checks/2553346053/logs

**Comment by mati865** [comment]
It's a bug with libc++ configuration, I'll fix it in the evening.
