### ISSUE TITLE
[clang] clang12 fails to launch on ucrt - cannot open libstdc++-6.dll

### ISSUE THREAD

**Issue by treeofsteam** [msys2/MINGW-packages#8658]
$ clang -v
C:/msys/ucrt64/bin/clang.exe: error while loading shared libraries: libstdc++-6.dll: cannot open shared object file: No such file or directory

Upgrading clang, llvm, lld to 12.0.0-3 from 11.0.0-12 in the ucrt64 repo causes clang and lld to not launch.
The commands below are run in the shell located at C:/msys/ucrt64.exe

Command log and installed packages:
https://gist.github.com/treeofsteam/35e6316aef1056394b6b8955a8af9aa1

**Comment by lazka** [comment]
hm, works fine here.

**Comment by lazka** [comment]
Can you try `pacman -S mingw-w64-ucrt-x86_64-libxml2`

**Comment by lazka** [comment]
@Astrum-polaris the `llvm` needs to depend on libxml2 I think:

```
$ ntldd /ucrt64/bin/libLLVM.dll
        ADVAPI32.dll => C:\WINDOWS\SYSTEM32\ADVAPI32.dll (0x0000020873c00000)
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x0000020873cb0000)
        ole32.dll => C:\WINDOWS\SYSTEM32\ole32.dll (0x0000020873c00000)
        libwinpthread-1.dll => C:\msys64\ucrt64\bin\libwinpthread-1.dll (0x000002086da70000)
        SHELL32.dll => C:\WINDOWS\SYSTEM32\SHELL32.dll (0x0000020874b00000)
        libgcc_s_seh-1.dll => C:\msys64\ucrt64\bin\libgcc_s_seh-1.dll (0x000002086da70000)
        libstdc++-6.dll => C:\msys64\ucrt64\bin\libstdc++-6.dll (0x0000020873c00000)
        libffi-7.dll => C:\msys64\ucrt64\bin\libffi-7.dll (0x000002086da70000)
        libxml2-2.dll => C:\msys64\ucrt64\bin\libxml2-2.dll (0x0000020873c00000)
        zlib1.dll => C:\msys64\ucrt64\bin\zlib1.dll (0x000002086da70000)
```

**Comment by treeofsteam** [comment]
Wow I wasn't expecting a reply that fast, thanks.
You're right about installing libxml2, just installing that fixes the problem for me and my project builds fine now. I'm not sure if I should close this or not, let me know. Thanks again.

**Comment by lazka** [comment]
Thanks for confirming. We'll close this once it is fixed.

**Comment by Biswa96** [comment]
It seems rustfmt.exe also needs libxml2.

**Comment by mati865** [comment]
This is fixed already, https://packages.msys2.org/package/mingw-w64-x86_64-llvm now depends on libxml2.

**Comment by mati865** [comment]
Can somebody close this issue?
