### ISSUE TITLE
libwebp trips antivirus (false positive?)

### ISSUE THREAD

**Issue by BeefaloKing** [msys2/MINGW-packages#8681]
Installed the `mingw-w64-i686-libwebp 1.2.0-1` package and windows defender had a fit over webpinfo.exe. [VirusTotal](https://www.virustotal.com/gui/file/82848d1cb65dd3a902236c2301e3376e697cb0b30098952a1240544b2747aabe/detection) shows a few other antivirus also have issues with it. The analogous file in the `mingw-w64-x86_64-libwebp 1.2.0-1` package doesn't appear to trip any antivirus.

Any idea why it might look malicious?

![image](https://user-images.githubusercontent.com/9630438/118324811-c3b36800-b4bf-11eb-8dc0-6a9229285188.png)

**Comment by Biswa96** [comment]
Congratulations! You are the new lucky winner of 2021! 🥳 You can find other winners here https://github.com/msys2/MINGW-packages/issues?q=is%3Aissue+virus+is%3Aclosed

**Comment by BeefaloKing** [comment]
If there's no use reporting it here just let me know and close the issue.

**Comment by lazka** [comment]
There is sadly nothing we can do about this.  The only information we can give you is:

* https://packages.msys2.org/package/mingw-w64-i686-libwebp which states as "Packager" as `CI (msys2-autobuild/571bdbec/548905535)`
* This means it was built in GitHub Actions in this workflow: https://github.com/msys2/msys2-autobuild/actions/runs/548905535
* We assume the Microsoft provided VMs for GitHub Actions can be trusted

**Comment by lazka** [comment]
I've triggered a rebuild now.. though not sure if this helps.

**Comment by BeefaloKing** [comment]
That's alright. I thought a maintainer might have better say than just a random user when reporting a false positive. I'll just set an exclusion to keep defender happy until Microsoft, and other antivirus I guess, update their detection.

You can probably safely close this.

**Comment by lazka** [comment]
Rebuild didn't help. Nothing we can do otherwise.
