### ISSUE TITLE
what's the difference between the mingw-w64-x86_64-toolchain from msys2/mingw64 and the one from archlinux/community

### ISSUE THREAD

**Issue by xubury** [msys2/MINGW-packages#8683]
I was doing cross-compiling in WSL2 archlinux for windows apps and have been using AUR for mingw-packages.
But AUR needs to re-compile those package every time there's an update and it takes a hell of long time.

So to get prebuilt binary, I tried add `msys2/mingw64`  packages site to my WSL pacman.conf
And surprisingly it works! Well, for the most part.

To clarify, there's two set of  `mingw-w64-x86_64-toolchain` after I added the source. 
One from `msys2/mingw64`, the other from `archlinux/community`

The first issue is one of my project that use wxWidgets, 
the linker from `archlinux/community` doesn't understand `--default-image-base-high` flag.
```
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: unrecognized option '--default-image-base-high'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: use the --help option for usage information
```
The program runs after I removed the flag manually.
But the the linker from `msys2/mingw64` works fine with the flag.

The second issue is the `mingw-w64-x86_64-toolchain` from `msys2/mingw64` won't pass cmake compiler checks.
**EDIT: Somehow it is working for cmake, please ignore this one.**

So there's must be something different between these toolchain alougth they are both mingw64.
Anyone knows why?

**Comment by Alexpux** [comment]
You can't use our toolchain in Arch Linux because our toolchain is native Windows binaries, while in Linux you use cross-toolchain

**Comment by xubury** [comment]
> You can't use our toolchain in Arch Linux because our toolchain is native Windows binaries, while in Linux you use cross-toolchain

But I can run it directly in WSL. It just have issues with cmake.
```
$ /mingw64/bin/x86_64-w64-mingw32-g++.exe  -v && uname -a
Using built-in specs.
COLLECT_GCC=x86_64-w64-mingw32-g++.exe
COLLECT_LTO_WRAPPER=//wsl$/archlinux/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-10.3.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native
-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=x86-64 --with-tune=generic --enable-languages=c,lt
o,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-t
s=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls
--disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev2, Built by MSY
S2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --with-boot-ldflags='-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-ima
ge-base-high -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc' 'LDFLAGS_FOR_TARGET=-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high' --enable-linker
-plugin-flags='LDFLAGS=-static-libstdc++\ -static-libgcc\ -pipe\ -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high\ -Wl,--stack,12582912'
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.3.0 (Rev2, Built by MSYS2 project)
Linux DESKTOP-18IUEN2 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux
```

**Comment by xubury** [comment]
well, please ignore my second issue. Somehow it passes cmake tests now. I must have forgot to delete the cache.

**Comment by lazka** [comment]
afaik if you start a native Windows program in WSL is will be executed in Windows, you just get to see stdout in WSL.

**Comment by xubury** [comment]
> afaik if you start a native Windows program in WSL it will be executed in Windows, you just get to see stdout in WSL.

So what is `--default-image-base-high`, why does the cross-toolchain from archlinux doesn't recognize it?

**Comment by jeremyd2019** [comment]
`--default-image-base-{low,high}` were invented here to ease into the new binutils defaults for x86_64.  The old default image bases were below 4GB, and the new ones are above.  An image base above 4GB signals to Windows that the image supports such high addresses, so it can use more bits for ASLR.

**Comment by xubury** [comment]
> `--default-image-base-{low,high}` were invented here to ease into the new binutils defaults for x86_64. The old default image bases were below 4GB, and the new ones are above. An image base above 4GB signals to Windows that the image supports such high addresses, so it can use more bits for ASLR.

I see. I guess I should just use the tool-chain from this mingw-packges then.

**Comment by Biswa96** [comment]
We could add these information in wiki or docs. Many others may have same questions.
