### ISSUE TITLE
stlink new release

### ISSUE THREAD

**Issue by valentinpi** [msys2/MINGW-packages#8704]
A new version 1.7.0 is out: [https://github.com/stlink-org/stlink/releases/tag/v1.7.0](https://github.com/stlink-org/stlink/releases/tag/v1.7.0)

**Comment by Biswa96** [comment]
Hi! @valentinpi Thank you for the report. Would you like to test the package from the linked pull request? The packages can be found in the GitHub Actions artifacts in a zip archive.

**Comment by Biswa96** [comment]
Any reply?

**Comment by valentinpi** [comment]
Ah yes so sorry I've been busy, I'll try it in a sec
