### ISSUE TITLE
recent update to the package have appended the number 2 to headers and libraries causing build errors in my other [alure]

### ISSUE THREAD

**Issue by diabl0-NEMESIS** [msys2/MINGW-packages#8738]
### **description : recent update to the package have appended the number 2 to headers and libraries causing build errors in my projects**

```
Files:

    /mingw64/bin/libalure2.dll
    /mingw64/include/AL/alure2-alext.h
    /mingw64/include/AL/alure2-aliases.h
    /mingw64/include/AL/alure2-typeviews.h
    /mingw64/include/AL/alure2.h
    /mingw64/lib/cmake/Alure2/Alure2Config-noconfig.cmake
    /mingw64/lib/cmake/Alure2/Alure2Config.cmake
    /mingw64/lib/libalure2.dll.a
    /mingw64/lib/libalure2_s.a
    /mingw64/share/licenses/alure/LICENSE
```

**Comment by oscarfv** [comment]
This is what the contributor who updated `PKGBUILD` wrote on the commit message:

```
commit 603b0daa8e43be7939ca9ce246cfe27f32115a3b
Author: Christoph Reiter
Date:   Mon May 3 19:48:00 2021 +0200

    alure: build from git
    
    there is no new version in years and this is completely different
    in terms of library names and headers.. but better then removing
    the package I guess.
    
    The old one failed to compile in various places I couldn't fix.
```

So the change in file names comes from upstream. You can lock onto the previous version if you wish.

**Comment by fundies** [comment]
> This is what the contributor who updated `PKGBUILD` wrote on the commit message:
> 
> ```
> commit 603b0daa8e43be7939ca9ce246cfe27f32115a3b
> Author: Christoph Reiter
> Date:   Mon May 3 19:48:00 2021 +0200
> 
>     alure: build from git
>     
>     there is no new version in years and this is completely different
>     in terms of library names and headers.. but better then removing
>     the package I guess.
>     
>     The old one failed to compile in various places I couldn't fix.
> ```
> 
> So the change in file names comes from upstream. You can lock onto the previous version if you wish.

The file names are inconsistent with linux packages see https://archlinux.org/packages/community/x86_64/alure/

**Comment by kcat** [comment]
Just to clarify (Alure 2 dev here), The 2.x versions of Alure is a whole new API separate from the 1.x series. Alure 2 is designed to coexist with Alure 1; the headers and libraries don't conflict, so an app written for Alure 1 will use those headers and its lib, and an app written for Alure 2 will use those headers and its lib, without accidentally getting the headers or library/symbols from the other version.

**Comment by fundies** [comment]
> Just to clarify (Alure 2 dev here), the 2.x version of Alure is a whole new API separate from the 1.x series. Alure 2 is designed to coexist with Alure 1; the headers and libraries don't conflict, so an app written for Alure 1 will use those headers and its lib, and an app written for Alure 2 will use those headers and its lib, without accidentally getting the headers or library/symbols from the other version.

For that reason I suggest we move this build to alure2 and I will fix the errors in one similar to how sdl packages are named.

**Comment by lazka** [comment]
the old package failed to build, so not sure what to do.

**Comment by fundies** [comment]
> 
> 
> the old package failed to build, so not sure what to do.

I will work on a fix for it but I would consider your change a completely new package

**Comment by lazka** [comment]
ok, fine with me moving the current state to a new alure2 package

I remember that moving to Ninja with cmake helped, but there where more errors.
