### ISSUE TITLE
[texlive-bin] texlua invalid link to zziplib

### ISSUE THREAD

**Issue by gharveymn** [msys2/MINGW-packages#8742]
It seems that texlua.exe is trying to link to libzzip-0-13.dll, but zziplib is currently shipping libzzip-0.dll. Just looking at the history, this is probably due to that reversion a few days back. My issue came up with the mingw64 repo, but it looks like it affects the other repos too.

**Comment by naveen521kk** [comment]
Looks like missing rebuilds?

**Comment by Biswa96** [comment]
I will try to fix things asap.
