### ISSUE TITLE
python check fails due to pinned package versions

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#8749]
My tests have shown the new python check job fails spuriously due to the pinned version of llvm in the split packages.  This failure can be safely ignored.  @naveen521kk want to take a look at [the logs](https://github.com/msys2/MINGW-packages/pull/8648/checks?check_run_id=2637758425) from #8648?

_Originally posted by @jeremyd2019 in https://github.com/msys2/MINGW-packages/issues/8648#issuecomment-845601678_

**Comment by naveen521kk** [comment]
Maybe simply ignore the failure?

**Comment by jeremyd2019** [comment]
I did a mingw-w64-clang run again and it succeeded:
https://github.com/jeremyd2019/MINGW-packages/runs/2714325583?check_suite_focus=true
