### ISSUE TITLE
[SDL_net]: struct ip_mreq broken for 32 bit

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#8759]
looks like something we should report upstream ? breaks sdl_net and sdl2_net 32 bit builds.

**Comment by Biswa96** [comment]
Where is it? How to reproduce the issue?

**Comment by revelator** [comment]
ws2tcpip.h only the 64 bit builds pick it up, just try building mingw-w64-SDL_net in 32 bit and it should all be clear :)

**Comment by revelator** [comment]
`../SDL_net-1.2.8/SDLnetUDP.c: In function 'SDLNet_UDP_Open':
[38;05;9m../SDL_net-1.2.8/SDLnetUDP.c:203:18: error:[0m storage size of 'g' isn't known
  203 |   struct ip_mreq g;
      |                  ^`

**Comment by revelator** [comment]
i think it has something todo with the ipv6 changes as that one undefines ip_mreg then defines it to the ipv6 version but defines are strings by nature so getting the size like it complains about might be triggering a bug.

**Comment by revelator** [comment]
temporary workaround for sdl_net here but this patch must only be used in the 32 bit build 
[sdl_net-ip_mreg-bug.zip](https://github.com/msys2/MINGW-packages/files/6528852/sdl_net-ip_mreg-bug.zip)

and the same fix for sdl2_net here also only appliable in 32 bit builds
[SDL2_net-2.0.1.tar.gz](https://github.com/msys2/MINGW-packages/files/6528853/SDL2_net-2.0.1.tar.gz)

i use it like this ->

`prepare() {
  cd "${srcdir}/${_realname}-${pkgver}"

  case "${CARCH}" in
    i686)
    # mingw-w64-api's struct ip_mreg has a bug on 32 bit.
    patch -p1 -i ${srcdir}/ip_mreg-bug.patch
    ;;
  esac
}`

**Comment by Biswa96** [comment]
The question is, why does it fail in mingw32 only?

**Comment by revelator** [comment]
indeed i have no clue either :/

**Comment by revelator** [comment]
aye it has become a bit of a convoluted mess in there :S not sure what can be done about it besides recoding the entire mess.

**Comment by revelator** [comment]
as i said i think it has to do with the macro redirections they use for ipv6 compatibility, but then it should not compile on 64 bit either unless something screwy is going on behind our backs. I cant make heads or tails of the code in there im afraid :/

**Comment by revelator** [comment]
Or maybe this ? 

```
struct in_addr
#define s_addr				      S_un.S_addr
#define s_host				      S_un.S_un_b.s_b2
#define s_net				      S_un.S_un_b.s_b1
#define s_imp				      S_un.S_un_w.s_w2
#define s_impno 			      S_un.S_un_b.s_b4
#define s_lh				      S_un.S_un_b.s_b3
{ union
  { struct { u_char s_b1,s_b2,s_b3,s_b4; }	S_un_b;
    struct { u_short s_w1,s_w2; }		S_un_w;
    u_long					S_addr;
  }					      S_un;
};
```

this is the in_addr struct from mingw notice the difference to the one from mingw-w64 below

```
typedef struct in_addr {
  union {
    struct { u_char  s_b1, s_b2, s_b3, s_b4; } S_un_b;
    struct { u_short s_w1, s_w2; } S_un_w;
    u_long S_addr;
  } S_un;
} IN_ADDR, *PIN_ADDR, *LPIN_ADDR;

#define s_addr	S_un.S_addr
#define s_host	S_un.S_un_b.s_b2
#define s_net	S_un.S_un_b.s_b1
#define s_imp	S_un.S_un_w.s_w2
#define s_impno	S_un.S_un_b.s_b4
#define s_lh	S_un.S_un_b.s_b3
```

something is definatly screwy here...

**Comment by revelator** [comment]
Still trying to figure it out but so far no cigar :/

**Comment by jeremyd2019** [comment]
Any luck?  Anyone report this to mingw-w64?

**Comment by Biswa96** [comment]
Just give me one more day.

**Comment by Biswa96** [comment]
Feel free to blame me. Found the issue https://github.com/mingw-w64/mingw-w64/commit/0c7108c439fcf349ec172843b022ccec5cef5da4.

Also perl uses ip_mreq and ipv6_mreq. So, I get my test subjects.

**Comment by revelator** [comment]
no blame but good job finding the issue :)

**Comment by Biswa96** [comment]
Patch file sent to upstream to revert my mistake https://sourceforge.net/p/mingw-w64/mailman/message/37310369/

**Comment by Biswa96** [comment]
The revert patch is in upstream now https://sourceforge.net/p/mingw-w64/mingw-w64/ci/15dafe50afdbe36833552d00def1d9e16498effd/

**Comment by revelator** [comment]
nice device ;)

**Comment by jeremyd2019** [comment]
I kind of expected the latest mingw-w64 update to have solved this, but clang32 retried and still failed ☹️

**Comment by jeremyd2019** [comment]
Oops, spoke too soon, didn't look at more recent run.

**Comment by Biswa96** [comment]
Mischief managed! 🪄
