### ISSUE TITLE
configure scripts blocked at checking for ld used by gcc

### ISSUE THREAD

**Issue by neolib** [msys2/MINGW-packages#8785]
I found out that some configure scripts are blocked at a certain point:
`checking for ld used by gcc...`
CPU usage rockets high and stays constant ever since.

Packages found so far:
libxml2-2.9.12
curl-7.77.0

msys2/mingw32:
3.2.0-340.x86_64 2021-05-24 19:32 UTC x86_64 Msys
gcc version 10.3.0 (Rev2, Built by MSYS2 project)

**Comment by Biswa96** [comment]
I have compiled those packages without any such issue. Is there any antivirus program in your setup that can causes this issue?

**Comment by neolib** [comment]
It seems something went wrong with my msys2. I deleted the whole directory msys2 and downloaded the installer and reinstalled. The problem is gone.

**Comment by neolib** [comment]
Ah, the problem strikes again. I am having this same problem with grep-3.11.

**Comment by Biswa96** [comment]
Try not to use the mingw grep package. There are two types of grep packages. The msys2 grep should be used.

**Comment by neolib** [comment]
I am trying to build the latest grep from source. I am not trying to install grep package using pacman.

**Comment by neolib** [comment]
However, within a new installation on Windows 11, I am succesful with `./configure` and `make` using mingw32 terminal.

**Comment by Biswa96** [comment]
There are many issues with grep > 3.6. autotools were failing due to the grep update. Once I updated the msys2 grep package and it brought down a catastrophe of failures in many projects.

**Comment by Biswa96** [comment]
Whereas mingw grep is not used for packaging. So, mingw grep package is updated to latest version.

**Comment by neolib** [comment]
Again, I had to remove MSYS2 installation completely and did a clean install. Now `./configure` works.
