### ISSUE TITLE
pkg-config file for portaudio contains `-luuid`

### ISSUE THREAD

**Issue by mmuetzel** [msys2/MINGW-packages#8805]
IIUC, the portaudio that is packaged for MSYS2 is patched to not depend on libuuid.
However, the installed pkg-config file (`C:\msys64\mingw64\lib\pkgconfig\portaudio-2.0.pc`) contains the following:
```
Libs: -L${libdir} -lportaudio  -lwinmm -lm -ldsound -lole32 -lwinmm -lm -luuid -lsetupapi -lole32 -lwinmm -lm -lole32 -luuid -lwinmm -lm -lole32 -luuid
```
AFAICS, there is no package in MSYS2 that would provide libuuid for i686 targets.

That causes issues when projects that use pkg-config try to link to portaudio.

It would be nice if `-luuid` could be removed from the pkg-config file.

**Comment by Biswa96** [comment]
libuuid is provided by mingw-w64 crt import libraries. It exports the class IDs and interface IDs of COM interfaces. e.g.

```
$ pacman -F /mingw64/x86_64-w64-mingw32/lib/libuuid.a
mingw64/x86_64-w64-mingw32/lib/libuuid.a is owned by mingw64/mingw-w64-x86_64-crt-git 9.0.0.6215.788f57701-1
```

**Comment by mmuetzel** [comment]
Thanks. I'll try again after installing that package.

It might still be worth removing `-luuid` from the package config file to avoid over-linking.
Alternatively, it might help if that package would be installed automatically as a dependency of portaudio.

**Comment by Biswa96** [comment]
> Alternatively, it might help if that package would be installed automatically as a dependency of portaudio.

mingw-w64 headers, crt are installed at package build time. Those are in `$MINGW_PACKAGE_PREFIX-toolchain` package group.

**Comment by mmuetzel** [comment]
Aaah. So I had those libraries installed all along.
But they still can't be found by the linker.
Maybe because there is no `-Lmingw64/x86_64-w64-mingw32/lib` in the flags returned by pkg-config:
```
$ pkg-config --libs portaudio-2.0
-LC:/msys64/mingw64/lib -lportaudio -ldsound -lsetupapi -lwinmm -lm -lole32 -luuid
```

**Comment by mmuetzel** [comment]
Coming back to this: Even if I manually add `-Lmingw64/x86_64-w64-mingw32/lib` to the linker flags, linking still fails.

I forgot to mention that in the original report: The project is trying to link a dynamic library with portaudio. IIUC, this is failing because there is only a static library of `uuid` that it can find on the linker paths. There is no dynamic link library (`libuuid.dll.a`) afaict.

**Comment by mmuetzel** [comment]
I rebuilt portaudio with this changeset:
[uuid.zip](https://github.com/msys2/MINGW-packages/files/6794821/uuid.zip)

With that change the `Libs:` line in `portaudio.pc` reads:
`Libs: -L${libdir} -lportaudio  -lwinmm -lm -ldsound -lole32 -lwinmm -lm -lsetupapi -lole32 -lwinmm -lm -lole32 -lwinmm -lm -lole32`

Linking the project that was previously failing succeeds with this change and the resulting binaries seem to be working.

**Comment by mmuetzel** [comment]
Thank you for fixing this.
