### ISSUE TITLE
ffmpeg.exe is broken

### ISSUE THREAD

**Issue by omichel** [msys2/MINGW-packages#8819]
#8802 broke `ffmpeg.exe` which depends on `avcodec-58.dll` which depends on `libx264-159.dll`, however, this update replaced `libx264-159.dll` with `libx264-161.dll`. I guess we need a new `ffmpeg` package with fixed dependencies.

_Originally posted by @omichel in https://github.com/msys2/MINGW-packages/issues/8802#issuecomment-852841051_

**Comment by lazka** [comment]
should be fixed now. sorry

**Comment by omichel** [comment]
No problem. Thank you for the quick fix!
