### ISSUE TITLE
latexmk/runscript doesn't handle arguments correctly in mingw64

### ISSUE THREAD

**Issue by simonkines** [msys2/MINGW-packages#8821]
When trying to pass arguments to runscript or trying to call latexmk directly from command line, it can't seem to interpret the arguments correctly. I run this command directly where `main two.tex` is.
```
C:\Users\simon\Downloads\test\SSB Build>latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc  "main two.tex"
C:\SK\msys64\mingw64\bin\runscript.tlu:935: C:\SK\msys64\mingw64\bin\runscript.tlu:581: unknown option: -verbose
runscript wrapper utility (rev. 54353, 2020-03-16)
usage:   runscript script-name [arguments]
try -help [-v] for more information
```
this all happens while `mingw64/bin` is in PATH. I've tried to replicate the issue with a standalone texlive installation, but when I do that it compiles correctly. It also works if there are no space in my filenames so this works. So this:
```
C:\Users\simon\Downloads\test\SSB Build>latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc  "main.tex"
```
compiles correctly.

 I also seem to have the problem that I can't invoke `C:\SK\msys64\mingw64\bin\latexmk.exe` unless `ming64\bin` is in my PATH.

**Comment by naveen521kk** [comment]
hmm, that's weird. it's treating as if `runscript.exe` was directly invoked which isn't the case here. Also, does this happen only to `latexmk` or every other thing that uses `runscript.exe`?

> I also seem to have the problem that I can't invoke C:\SK\msys64\mingw64\bin\latexmk.exe unless ming64\bin is in my PATH.

That's expected though.

**Comment by simonkines** [comment]
> That's expected though.

I should clarify that I mean this is what I get when mingw64/bin is not in PATH:
```
C:\Users\simon\Downloads\test\SSB Build>C:\SK\msys64\mingw64\bin\latexmk.exe

C:\Users\simon\Downloads\test\SSB Build>
```

I only use the latexmk but I get the same problem for a2ping:
```
C:\Users\simon\Downloads\test\SSB Build>a2ping "main two.pdf"
C:\SK\msys64\mingw64\bin\runscript.tlu:935: C:\SK\msys64\mingw64\bin\runscript.tlu:858: no appropriate script or program found: main
```

Or for pslatex:
```
C:\Users\simon\Downloads\test\SSB Build>pslatex "main two.tex"
C:\SK\msys64\mingw64\bin\runscript.tlu:935: C:\SK\msys64\mingw64\bin\runscript.tlu:858: no appropriate script or program found: main
```

The original line I was trying to run came from Vim
```
C:\Users\simon\Downloads\test\SSB Build>set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e "$pdf_previewer = 'C:/SK/64bit/SumatraPDF/SumatraPDF.exe -reuse-instance'" -e "$success_cmd = 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = 'echo vimtex_compiler_callback_failure'" "main two.tex"
C:\SK\msys64\mingw64\bin\runscript.tlu:935: C:\SK\msys64\mingw64\bin\runscript.tlu:581: unknown option: -verbose
runscript wrapper utility (rev. 54353, 2020-03-16)
usage:   runscript script-name [arguments]
try -help [-v] for more information

C:\Users\simon\Downloads\test\SSB Build>

```

**Comment by naveen521kk** [comment]
Oh wait, maybe simply hooks failed while installing for you while installing? Can you run the script `mktexlsr` in `mingw64/bin`(you would need to launch bash for that)? After that can you run `a2ping` and other things?

**Comment by simonkines** [comment]
Tried running ``mktexlsr`` in the mingw64 terminal and got:
```
simon@DESKTOP MINGW64 ~
$ mktexlsr

simon@DESKTOP MINGW64 ~
$
```

Tried running:
```
C:\SK\msys64\mingw64\bin>bash

simon@DESKTOP  /mingw64/bin
$ mktexlsr
mktexlsr: Updating C:/SK/msys64/mingw64/etc/texmf...
mktexlsr: Updating C:/SK/msys64/mingw64/share/texmf-dist...
mktexlsr: Updating C:/SK/msys64/mingw64/var/lib/texmf...
mktexlsr: Done.

simon@DESKTOP  /mingw64/bin
$
```

Same error:
```
C:\Users\simon\Downloads\test\SSB Build>a2ping "main two.tex"
C:\SK\msys64\mingw64\bin\runscript.tlu:935: C:\SK\msys64\mingw64\bin\runscript.tlu:858: no appropriate script or program found: main

C:\Users\simon\Downloads\test\SSB Build>
```

**Comment by naveen521kk** [comment]
Hmm, looks like quoting issue or something similar to me. I will have a look at it later.

**Comment by naveen521kk** [comment]
@lazka can you assign me so that I wont forget about this?

**Comment by naveen521kk** [comment]
for the command
```sh
./runscript -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc  "main two.tex"
```
this is the arguments parsed in mingw one's 
```
H:\texlive\kpathsea\mingw64\bin\runscript.tlu
1       -verbose
2       -file-line-error
3       -synctex=1
4       -interaction=nonstopmode
5       -pdf
6       -pvc
7       main
8       two.tex
9       CUI_MODE

10      H:\texlive\kpathsea\mingw64\bin\runscript.exe
11      -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc main
12      two.tex
```
the one in normal win32 distribution
```
1       -verbose
2       -file-line-error
3       -synctex=1
4       -interaction=nonstopmode
5       -pdf
6       -pvc
7       main two.tex
8       CUI_MODE

9       H:\texlive\kpathsea\test\runscript.exe
10      -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc "main two.tex"
```
so I think I found the problem.

**Comment by naveen521kk** [comment]
@simonkines Can you try the build artifact of https://github.com/msys2/MINGW-packages/pull/8855 ?

**Comment by simonkines** [comment]
@naveen521kk is this done through the msys2 update or do I have to get it through git?

**Comment by lazka** [comment]
at this point you can wait for the repo update, likely tomorrow

**Comment by naveen521kk** [comment]
@simonkines you can download https://github.com/msys2/MINGW-packages/suites/2933265725/artifacts/65892052 and do `pacman -U <file>.zst` to upgrade and possibly try testing.

**Comment by naveen521kk** [comment]
Oh, other packages have to be rebuild now. Will do.

**Comment by simonkines** [comment]
@naveen521kk tried to install using ``pacman -U <file>.zst`` but same error occured.

**Comment by naveen521kk** [comment]
I had to rebuild everything as in https://github.com/msys2/MINGW-packages/pull/8858
You can try them from artifacts but it's ~1Gb download.

Otherwise, you can just rename `runscript.exe` to what you want in `/mingw64/bin`. If you need `a2ping.exe` then rename `/mingw64/bin/runscript.exe` to `/mingw64/bin/a2ping.exe` (delete previous one) and see if that works.

**Comment by simonkines** [comment]
I tried to do without the rebuild and just the renaming but got the same error again. I would try the rebuild but I don't know how, if it's the only way ill try to figure it out.

**Comment by simonkines** [comment]
Never-mind it worked after a reinstall.
