### ISSUE TITLE
[python] Change the Platform Tags

### ISSUE THREAD

**Issue by naveen521kk** [msys2/MINGW-packages#8843]
Currently, we have as many as 6 different python with the same platform tags which is super easy to mix and could cause problems. By "Platform Tags", I mean the file extension, Python's C extensions. (ie `*-cpython-38.dll`). Tbh, I don't know whether this is the exact term to use.

When working with multiple python's provided, there might be an issue of loading an extension that was compiled using (say ucrt) but loaded with another one (say mingw64), python will try to import them and could fail with an unexpected error. This is because all the python provided has the same platform tag; else python wouldn't have tried to import the wrong extension. So I would like to change those platform tags to something which will indicate which compiler was used to compile the extension.

I propose to have the following Platform Tags.

| MSYSTEM    | Platform Tags   |
| ------------- |:-----------------:|
| MINGW64   | `x86_64-38`       |
| MINGW32   | `i686-38`           | 
| CLANG64    | `x86_64-clang-38`  |
| CLANG32    | `i686-clang-38`  |
| UCRT64       | `x86_64-ucrt-38`  |
| CLANGARM64 | `aarch64-38`  |

Here the `38` at the end is the python version major string.

Suggestions welcome on better naming. Also, I would like this to happen before we get into python3.9.

**Comment by lazka** [comment]
That's https://docs.python.org/3/library/importlib.html#importlib.machinery.EXTENSION_SUFFIXES

Other related things that come to mind:

* The ABI tag which is used to pull things from pypi and how wheels are named: https://docs.python.org/3/library/sysconfig.html#sysconfig.get_platform and https://docs.python.org/3/distutils/apiref.html#distutils.util.get_platform
* Namespacing of the user install dir based on arch (can wait for 3.10 likely): https://bugs.python.org/issue43195

**Comment by naveen521kk** [comment]
> That's https://docs.python.org/3/library/importlib.html#importlib.machinery.EXTENSION_SUFFIXES

I was looking into where exactly it came from and found this patch relevant https://github.com/msys2/MINGW-packages/blob/86a6e4bad43939f153d8fc4957aeef716b943243/mingw-w64-python3.9/0310-MINGW-dynamic-loading-support.patch#L35

> The ABI tag which is used to pull things from pypi and how wheels are named: https://docs.python.org/3/library/sysconfig.html#sysconfig.get_platform and https://docs.python.org/3/distutils/apiref.html#distutils.util.get_platform

Yeah, that would help would pip caching the wheel for future use.

> Namespacing of the user install dir based on arch (can wait for 3.10 likely): https://bugs.python.org/issue43195

Hmm, can we backport it or something?

**Comment by lazka** [comment]
> > Namespacing of the user install dir based on arch (can wait for 3.10 likely): https://bugs.python.org/issue43195
> 
> Hmm, can we backport it or something?

That would be https://github.com/python/cpython/pull/22098/files but it uses `sys.winver` which is `3.9-32` for CPython and just `3.9` in our case. We could come up with something similar though.

**Comment by naveen521kk** [comment]
> That would be https://github.com/python/cpython/pull/22098/files but it uses sys.winver which is 3.9-32 for CPython and just 3.9 in our case. We could come up with something similar though.

How about simple appending the platform tags to the version? Like `3.9-x86_64` or `3.9-x86_64-clang` for example?

**Comment by naveen521kk** [comment]
> How about simple appending the platform tags to the version? Like `3.9-x86_64` or `3.9-x86_64-clang` for example?

Tbh, I don't know whether having letters could cause a problem, if that's only used while using `pip` that I think this is going to work.

**Comment by lazka** [comment]
hard to say if this will break stuff. Python 3.10 isn't that far out, so there is another chance for changing things.

So we need something for

* DLLs: we can choose, it needs to be different compared to cpython, currently `-cpython-38.dll`, cpython uses `.cp39-win_amd64.pyd`
* platform tag: used for pip, doesn't need to contain the python version, currently `mingw`, cpython uses `win-amd64` and `win32`
* py_version_nodot_plat: similar to platform tag but starts with a version, used for user dir namespacing, cpython uses `3.9` and `3.9-32`

**Comment by lazka** [comment]
> How about simple appending the platform tags to the version? Like `3.9-x86_64` or `3.9-x86_64-clang` for example?

yeah. Should we have something like mingw in there too, so it's different to CPython?

**Comment by Alexpux** [comment]
For what reason we need it? Every python is installed in its own prefix, so every python have its own site-packages path that not readable by other python.

**Comment by naveen521kk** [comment]
> For what reason we need it? Every python is installed in its own prefix, so every python have its own site-packages path that not readable by other python.

Like for user installation with `pip` ie) passing `--user` to pip while installing. It will install everything to `~/.local`.

**Comment by naveen521kk** [comment]
> yeah. Should we have something like mingw in there too, so it's different to CPython?

I don't think it is needed. We would be the only one using `x86_64` and `i686`.

**Comment by Alexpux** [comment]
64 bit python in any case can't load 32 bit extension really

**Comment by naveen521kk** [comment]
Yup. That was actually an upstream issue https://bugs.python.org/issue41627.

**Comment by raedrizqie** [comment]
Hi guys..

Good job on changing the platform tag and revert to pyd for extensions.

But still, python doesn't set plat_name right?
