### ISSUE TITLE
Can not "import wx" in python 3 after install  "mingw-w64-x86_64-wxPython"

### ISSUE THREAD

**Issue by leevawns** [msys2/MINGW-packages#8863]
i'm new user msys2, i don't know what i did wrong

Python 3.8.9 (default, Apr 13 2021, 15:54:59)  [GCC 10.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'wx'

**Comment by jeremyd2019** [comment]
> i'm new user msys2, i don't know what i did wrong

Nothing.  wxPython is one of the very few packages here still not updated to python3.  #7969

**Comment by leevawns** [comment]
> > i'm new user msys2, i don't know what i did wrong
> 
> Nothing. wxPython is one of the very few packages here still not updated to python3. #7969

Thankyou
