### ISSUE TITLE
mingw-w64-x86_64-python-lxml etree.find() gives more than the element

### ISSUE THREAD

**Issue by RoDuth** [msys2/MINGW-packages#8864]
I have an anomaly with lxml that seems to occur only in msys2 and MinGW (64 bit console at least, haven't tested in 32 bit).

Minimal example:

with 2 files:

`lxml_test.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<test>
  <this>
    <works id="here">Success</works>
  </this>
</test>
```

`lxml_test.py`
```python
from lxml import etree

xml = etree.parse('lxml_test.xml')
el = xml.find("//works[@id='here']")

print(etree.tostring(el))
```

running:
`$ python lxml_test.py`

I get:
`b'<works id="here">Success</works>\n  </this>\n</test>\n  '`

Expected result is:
`b'<works id="here">Success</works>\n  '`

The last time I used lxml on MinGW was roughly 6 months ago and I did not encounter this issue.  Has something changed since to cause it?

Any help would be greatly appreciated.

**Comment by lazka** [comment]
That's indeed weird. I can confirm the issue, and that it doesn't happen with the official wheel and CPython.

Either someone needs to debug this or report it upstream (maybe they can give some feedback on what the issue might be)

**Comment by RoDuth** [comment]
Thanks for taking a look.

In the code base I discover this in it appears twice, interestingly all other use of lxml (xpath, ElementTree, XMLSchema, etc.) seems to be working perfectly fine.

For the time being I found using the standard library xml.etree.ElementTree as a drop in replacement works.
e.g. using my example above:
```diff
-from lxml import etree
+from xml.etree import ElementTree as etree

xml = etree.parse('lxml_test.xml')
-el = xml.find("//works[@id='here']")
+el = xml.find(".//works[@id='here']")

print(etree.tostring(el))
```
This solves my problems and may be helpful to anyone looking here but not the greater issue.

If I get some time at a later date I will try following up further but right now I can't promise anything.
