### ISSUE TITLE
shared-mime-info upgrade to 2.1

### ISSUE THREAD

**Issue by novomesk** [msys2/MINGW-packages#8865]
[shared-mime-info](https://packages.msys2.org/package/mingw-w64-x86_64-shared-mime-info) seems to stay at version 2.0 but latest version is [2.1](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/releases)

When it is convenient for you, can you please upgrade to the 2.1 version?

**Comment by Biswa96** [comment]
Would you like to test the updated package from the GitHub Actions artifacts in the linked pull request?

**Comment by novomesk** [comment]
I tried mingw-w64-x86_64-shared-mime-info-2.1-1-any.pkg.tar.zst and it seems to work.
