### ISSUE TITLE
mingw-w64-x86_64-libpcap

### ISSUE THREAD

**Issue by giuspen** [msys2/MINGW-packages#8866]
It would be nice to have mingw-w64-x86_64-libpcap, at the moment we have only libpcap

**Comment by Biswa96** [comment]
Make a choice. What will be the DLL name - pcap.dll or libpcap.dll? Choose wisely because it will be remembered for entire human history.

**Comment by giuspen** [comment]
At the moment I'm building it manually and I see that by default it generates pcap.dll, I think I saw a comment about a possible conflict thus renaming to pcap. Maybe better to stick with the default... Personally I have not real preference, except that if possible having exactly the same name on multiple platforms may save an if in the CMakeLists.txt but only if sure it won't cause issues

**Comment by Alexpux** [comment]
I think better to follow mingw libraries name convention and use libpcap.dll

**Comment by giuspen** [comment]
I can test tomorrow (Europe) the package before it goes to the repo if can be useful to you and give feedback. Many thanks.

**Comment by Biswa96** [comment]
@Alexpux Done. Checked both libpcap.pc and pcap-config file. File list can be viewed in CI build log.

**Comment by giuspen** [comment]
Apologies @Biswa96 I haven't been able to test the new package today, I'll do it on monday

**Comment by giuspen** [comment]
Works great thanks again
