### ISSUE TITLE
git gui variable name incorrect

### ISSUE THREAD

**Issue by simonkines** [msys2/MINGW-packages#8872]
When trying to run ``git gui``  from the command line or from msys2 I get the error:
```
bitmap "/usr/share/git-gui/lib/git-gui.ico" not defined
  while executing
"wm iconbitmap . -default $oguilib/git-gui.ico"
  invoked from within
"if {[is_Windows]} {
	wm iconbitmap . -default $oguilib/git-gui.ico
	set ::tk::AlwaysShowSelection 1
	bind . <Control-F2> {console show}

	# Spoof an X..."
(file "C:/SK/msys64/usr/lib/git-core/git-gui" line 734)
```

I tried to replace: ``/usr/share/git-gui/lib`` with ``C:/SK/msys64/usr/share/git-gui/lib`` on line 54 of  ``msys64/usr/lib/git-core/git-gui``
(``C:/SK/msys64/`` is my msys64 install location)
which seems to have fixed it but I don't know how to change it permanently so it doesn't revert when I update it.

**Comment by lazka** [comment]
Is this similar to https://github.com/msys2/MSYS2-packages/pull/1912?

**Comment by simonkines** [comment]
I made mistake I meant I can't run it from command line or msys2 shell. The issues you suggested has a similar problem but @podsvirov seems to be able run it from the windows command line.

**Comment by simonkines** [comment]
I realized you can set the ``GIT_GUI_LIB_DIR`` environmental variable to the proper windows PATH
