### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by skjha1** [msys2/MINGW-packages#8894]
mingw-get: *** ERROR *** unpack: aborted due to previous download failure
mingw-get: *** INFO *** setup: unpacking mingw-get-setup-0.6.3-mingw32-pre-20170905-1-dll.tar.xz
mingw-get: *** ERROR *** unpack: required archive file is not available
mingw-get: *** ERROR *** unpack: aborted due to previous download failure
mingw-get: *** INFO *** setup: unpacking mingw-get-setup-0.6.3-mingw32-pre-20170905-1-xml.tar.xz
mingw-get: *** ERROR *** unpack: required archive file is not available
mingw-get: *** ERROR *** unpack: aborted due to previous download failure
mingw-get: *** ERROR *** setup: unable to continue

**Comment by Biswa96** [comment]
What is mingw-get? Which installer did you use to install msys2?

**Comment by ZachBacon** [comment]
Mingw-get is from the mingw.org project which also installs the original msys and it is not affiliated with msys2, therefore in this case it's an invalid bug since it's not our project.

**Comment by skjha1** [comment]
I am not getting how to resolve this issue I am trying to install mingw but the same error is displaying all the time which is stopping me work can you help me out with this?

**Comment by ZachBacon** [comment]
> I am not getting how to resolve this issue I am trying to install mingw but the same error is displaying all the time which is stopping me work can you help me out with this?

You are asking for help from the wrong project basically. https://www.msys2.org/ we use mingw from mingw-w64.org not mingw.org which mingw-get is from. That's not our installer so we can't help.
