### ISSUE TITLE
mingw-w64-waf: uses msys2 python

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#8896]
This is pretty clearly wrong.

**Comment by jeremyd2019** [comment]
Or not... I can't get it to work with mingw python because it doesn't think 'gcc' is executable.  And telling it to use 'gcc.exe' confuses it because it doesn't have a module for 'gcc.exe'

**Comment by jeremyd2019** [comment]
if it does actually depend on msys python, it may be better as a msys package

**Comment by shithappens2016** [comment]
same problem

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune
> 
> Please fix or close this issue if it has already been fixed

I wish I could, but I don't have access to this repo

**Comment by mati865** [comment]
Fixed in https://github.com/msys2/MINGW-packages/pull/11901
