### ISSUE TITLE
ffmpeg 4.4-5 weird error

### ISSUE THREAD

**Issue by thesword53** [msys2/MINGW-packages#8983]
`C:/msys64/mingw64/bin/ffmpeg.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory`

**Comment by lazka** [comment]
should be fixed shortly

**Comment by Biswa96** [comment]
Apology for the issue. CI is currently building it. You could see the progress here https://packages.msys2.org/queue. 

Duplicate of https://github.com/msys2/MINGW-packages/issues/8981

**Comment by Biswa96** [comment]
Fixed package is in pacman repository now. Use `pacman -Syyu` to update those.

**Comment by lazka** [comment]
thanks @Biswa96
