### ISSUE TITLE
[mingw-w64-(i686|x86_64)-lua-luarocks] 3.5.0-1 seems to be borked

### ISSUE THREAD

**Issue by SlySven** [msys2/MINGW-packages#9037]
I have previously used (and still have on a non-updated PC) the **2.4.4-2** versions of these packages and have been using those with the corresponding 5.1 **[mingw-w64-(i686|x86_64)-lua]** interpreters (**5.1.5-5**) version on that machine after fixing an issue with the 32-bit version (#5928, #6580). On a fresh machine (new install of Windows 10 Pro) this *new*, *improved* set of packages - which is supposed to support multiple Lua versions but which looks to come preset for Lua 5.1 and 5.4 - can't even find their own configuration files for any version. Using the `luarocks` command all on its own defaults to **5.4** (by default one has to also include a `--lua-version 5.x` option for a different version) - on the x86_64 side of things reports the following at the end of the output: 
```sh
   ...
   Configuration:
   Lua:
      Version    : 5.4
      Interpreter: C:\msys64\mingw64\bin/lua.exe (ok)
      LUA_DIR    : C:\msys64\mingw64 (ok)
      LUA_BINDIR : C:\msys64\mingw64\bin (ok)
      LUA_INCDIR : C:\msys64\mingw64/include (ok)
      LUA_LIBDIR : C:\msys64\mingw64/bin (ok)

   Configuration files:
      System  : /mingw64/etc/luarocks/config-5.4.lua (not found)
      User    : C:/msys64/home/stephen/.luarocks/config-5.4.lua (not found)

   Rocks trees in use:
      C:\msys64\home\stephen/.luarocks ("user")


stephen@Hunt MINGW64 ~
$
```

correspondingly for 5.1:
```sh
   ...
   Configuration:
   Lua:
      Version    : 5.1
      Interpreter: C:\msys64\mingw64\bin/lua5.1.exe (ok)
      LUA_DIR    : C:\msys64\mingw64 (ok)
      LUA_BINDIR : C:\msys64\mingw64\bin (ok)
      LUA_INCDIR : C:\msys64\mingw64/include/lua5.1 (ok)
      LUA_LIBDIR : C:\msys64\mingw64/bin (ok)

   Configuration files:
      System  : /mingw64/etc/luarocks/config-5.1.lua (not found)
      User    : C:/msys64/home/stephen/.luarocks/config-5.1.lua (not found)

   Rocks trees in use:
      C:\msys64\home\stephen/.luarocks ("user")
```

Note the file suggested by the output for the *system* "Configuration files:" **`/mingw64/etc/luarocks/config-5.4.lua (not found)`** and **`/mingw64/etc/luarocks/config-5.4.lua (not found)`** - yet strangely ***both files do exist and have content***:
```sh
stephen@Hunt MINGW64 ~
$ more /mingw64/etc/luarocks/config-5.?.lua
::::::::::::::
/mingw64/etc/luarocks/config-5.1.lua
::::::::::::::
-- LuaRocks configuration

rocks_trees = {
   { name = "user", root = home .. "/.luarocks" };
   { name = "system", root = "/mingw64" };
}
lua_interpreter = "lua5.1.exe";
variables = {
   LUA_DIR = "/mingw64";
   LUA_INCDIR = "/mingw64/include/lua5.1";
   LUA_BINDIR = "/mingw64/bin";
}
::::::::::::::
/mingw64/etc/luarocks/config-5.4.lua
::::::::::::::
-- LuaRocks configuration

rocks_trees = {
   { name = "user", root = home .. "/.luarocks" };
   { name = "system", root = "/mingw64" };
}
lua_interpreter = "lua.exe";
variables = {
   LUA_DIR = "/mingw64";
   LUA_BINDIR = "/mingw64/bin";
}
```

With this as a starting point it is not surprising that trying to install a rock fails miserably:
```sh
stephen@Hunt MINGW64 ~
$ luarocks --lua-version 5.1 install utf8
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/utf8-1.2-0.src.rock
Warning: Failed searching manifest: Failed extracting manifest file: failed extracting C:\msys64\home\stephen/.cache/luarocks/https___luarocks.org/manifest-5.1.zip

Error: Failed unpacking rock file: C:\msys64\tmp/luarocks_luarocks-rock-utf8-1.2-0-8831/utf8-1.2-0.src.rock: failed extracting C:\msys64\tmp/luarocks_luarocks-rock-utf8-1.2-0-8831/utf8-1.2-0.src.rock
```

The output from running the above again with an additional `--verbose` argument is this: [luarocks_install_ut8_rock_failure_log.txt](https://github.com/msys2/MINGW-packages/files/6744442/luarocks_install_ut8_rock_failure_log.txt) - superficially it *seems* that handling of Windows `\` path delimiters seems to be messed up... 😜 

Looking more closely at what upstream has been doing to Luarock since 3.x versions have been worked on it looks like the MSYS2/Mingw-w64 package build instructions are way out of date - since @kou 's actions in https://github.com/msys2/MINGW-packages/pull/7431#issuecomment-743451407 points out - the patch in https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-lua-luarocks (in https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-lua-luarocks/mingw32-msys2.patch ) must be re-examined to see if it is still relevant. Also in https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-lua-luarocks/luarocks-x86_64.install and https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-lua-luarocks/luarocks-i686.install both try to `sed` some paths in the corresponding `${MINGW_PREFIX}/etc/luarocks/config-5.1.lua` files (but it is not clear that that works now as there may be other files for other Lua versions (currently 5.4 by default) and similarly for `${MINGW_PREFIX}/share/lua/5.1/luarocks/site_config.lua` - and those files do not exist any more! {I tried to create one for Lua 5.1 to see if it would fix things - but it doesn't seem to...!}

**Comment by ImperatorS79** [comment]
The .install and .patch file are not used anymore during the build. What is interesting is that at the end of a luarocks command, every path is correctly prefixed except for the "system" configuration one. Could you edit your luarocks script and the config file and place the correct windows path (with C:/) like in the following:

In the luarocks file change  SYSCONFIGDIR, for example:
```
SYSCONFDIR = [[C:\msys64\mingw64\etc\luarocks]]
```

In the config-5.4.lua file, for example:
```lua
-- LuaRocks configuration

rocks_trees = {
   { name = "user", root = home .. "/.luarocks" };
   { name = "system", root = "C:/msys64/mingw64" };
}
lua_interpreter = "lua.exe";
variables = {
   LUA_DIR = "C:/msys64/mingw64/";
   LUA_BINDIR = "C:/msys64/mingw64//bin";
}
```

Doing that I obtain the following output of luarocks:
```
Configuration:
   Lua:
      Version    : 5.4
      Interpreter: C:/msys64/mingw64/bin/lua.exe (ok)
      LUA_DIR    : C:/msys64/mingw64/ (ok)
      LUA_BINDIR : C:/msys64/mingw64//bin (ok)
      LUA_INCDIR : C:/msys64/mingw64//include (ok)
      LUA_LIBDIR : C:/msys64/mingw64/bin (ok)

   Configuration files:
      System  : C:/msys64/mingw64/etc/luarocks/config-5.4.lua (ok)
      User    : C:/msys64/home/<top secret>/.luarocks/config-5.4.lua (not found)

   Rocks trees in use:
      C:\msys64\home\<top secret>/.luarocks ("user")
      C:/msys64/mingw64 ("system")
 ```
 
 Finally, can you install a luarocks package that way ?

**Comment by ImperatorS79** [comment]
There is also a beautifull
```
'7z' is not recognized as an internal or external command
```
I have the same locall, but p7zip is installed...

**Comment by SlySven** [comment]
As a test I've made the following changes:
* to the start of (the 32-bit) `/mingw32/bin/luarocks` (executable/script) file:
```diff
 #!/mingw32/bin/lua.exe
-package.loaded["luarocks.core.hardcoded"] = { SYSCONFDIR = [[/mingw32/etc/luarocks]] }
+package.loaded["luarocks.core.hardcoded"] = { SYSCONFDIR = [[C:/msys64/mingw32/etc/luarocks]] }
-package.path=[[/mingw32/share/lua/5.4/?.lua;]] .. package.path
+package.path=[[C:/msys64/mingw32/share/lua/5.4/?.lua;]] .. package.path
-local list = package.searchers or package.loaders; table.insert(list, 1, function(name) if name:match("^luarocks%.") then return loadfile([[/mingw32/share/lua/5.4/]] .. name:gsub([[%.]], [[/]]) .. [[.lua]]) end end)
+local list = package.searchers or package.loaders; table.insert(list, 1, function(name) if name:match("^luarocks%.") then return loadfile([[C:/mingw32/share/lua/5.4/]] .. name:gsub([[%.]], [[/]]) .. [[.lua]]) end end)
 
 -- Load cfg first so that the loader knows it is running inside LuaRocks
 local cfg = require("luarocks.core.cfg")
```
* to the start of (the 32-bit) `/mingw32/bin/luarocks-admin` (excutable/script) file:
```diff
 #!/mingw32/bin/lua.exe
-package.loaded["luarocks.core.hardcoded"] = { SYSCONFDIR = [[/mingw32/etc/luarocks]] }
+package.loaded["luarocks.core.hardcoded"] = { SYSCONFDIR = [[C:/msys64/mingw32/etc/luarocks]] }
-package.path=[[/mingw32/share/lua/5.4/?.lua;]] .. package.path
+package.path=[[C:/msys64/mingw32/share/lua/5.4/?.lua;]] .. package.path;
-local list = package.searchers or package.loaders; table.insert(list, 1, function(name) if name:match("^luarocks%.") then return loadfile([[/mingw32/share/lua/5.4/]] .. name:gsub([[%.]], [[/]]) .. [[.lua]]) end end)
+local list = package.searchers or package.loaders; table.insert(list, 1, function(name) if name:match("^luarocks%.") then return loadfile([[C:/msys64/mingw32/share/lua/5.4/]] .. name:gsub([[%.]], [[/]]) .. [[.lua]]) end end)
 
 -- Load cfg first so that luarocks.loader knows it is running inside LuaRocks
 local cfg = require("luarocks.core.cfg")
```
* to the (32-bit) Luarocks **5.1** `/mingw32/etc/luarocks/config-5.1.lua` config file:
```diff
 -- LuaRocks configuration
 
 rocks_trees = {
    { name = "user", root = home .. "/.luarocks" };
-   { name = "system", root = "/mingw32" };
+   { name = "system", root = "C:/msys64/mingw32" };
 }
 lua_interpreter = "lua5.1.exe";
 variables = {
-   LUA_DIR = "/mingw32";
+   LUA_DIR = "C:/msys64/mingw32";
-   LUA_INCDIR = "/mingw32/include/lua5.1";
+   LUA_INCDIR = "C:/msys64/mingw32/include/lua5.1";
-   LUA_BINDIR = "/mingw32/bin";
+   LUA_BINDIR = "C:/msys64/mingw32/bin";
 }
```
* to the (32-bit) Luarocks **5.4** `/mingw32/etc/luarocks/config-5.4.lua` config file:
```diff
 -- LuaRocks configuration
 
 rocks_trees = {
    { name = "user", root = home .. "/.luarocks" };
-   { name = "system", root = "/mingw32" };
+   { name = "system", root = "C:/msys64/mingw32" };
 }
 lua_interpreter = "lua.exe";
 variables = {
-   LUA_DIR = "/mingw32";
+   LUA_DIR = "C:/msys64/mingw32";
-   LUA_BINDIR = "/mingw32/bin";
+   LUA_BINDIR = "C:/msys64/mingw32/bin";
}
```

As you have found that at least gets the plain `luarocks` command to find things:
```sh
....
Configuration:
   Lua:
      Version    : 5.4
      Interpreter: C:/msys64/mingw32/bin/lua.exe (ok)
      LUA_DIR    : C:/msys64/mingw32 (ok)
      LUA_BINDIR : C:/msys64/mingw32/bin (ok)
      LUA_INCDIR : C:/msys64/mingw32/include (ok)
      LUA_LIBDIR : C:/msys64/mingw32/bin (ok)

   Configuration files:
      System  : C:/msys64/mingw32/etc/luarocks/config-5.4.lua (ok)
      User    : C:/msys64/home/stephen/.luarocks/config-5.4.lua (not found)

   Rocks trees in use:
      C:\msys64\home\stephen/.luarocks ("user")
      C:/msys64/mingw32 ("system")
```
and the same for the **5.1** version `luarocks --lua-version 5.1`:
```sh
...
Configuration:
   Lua:
      Version    : 5.1
      Interpreter: C:/msys64/mingw32/bin/lua5.1.exe (ok)
      LUA_DIR    : C:/msys64/mingw32 (ok)
      LUA_BINDIR : C:/msys64/mingw32/bin (ok)
      LUA_INCDIR : C:/msys64/mingw32/include/lua5.1 (ok)
      LUA_LIBDIR : C:/msys64/mingw32/bin (ok)

   Configuration files:
      System  : C:/msys64/mingw32/etc/luarocks/config-5.1.lua (ok)
      User    : C:/msys64/home/stephen/.luarocks/config-5.1.lua (not found)

   Rocks trees in use:
      C:\msys64\home\stephen/.luarocks ("user")
      C:/msys64/mingw32 ("system")
```

However I am still unable to make any headway with actually installing any rocks. Repeating the previous attempts to install the `utf8` rock for 5.1 in the verbose output I can see several bugs such as:
```sh
os.execute:     cd "\home\stephen" & mkdir -p  "C:\msys64\home\stephen\.cache\luarocks\https___luarocks.org"
The system cannot find the path specified.
A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file C:\msys64\home\stephen\.cache\luarocks\https___luarocks.org already exists.
Error occurred while processing: C:\msys64\home\stephen\.cache\luarocks\https___luarocks.org.
Results: 3
  1 (nil): nil
  2 (string): exit
  3 (number): 1
```
Here, the initial `cd "\home\stephen"` is not working and I had previously changed my `HOME` environmental variable from `/home/stephen` to `C:/msys64/home/stephen` and also temporarily tweaked the local (user) rocktree location in `config-5.1.lua`:
```diff
-{ name = "user", root = home .. "/.luarocks" };
+{ name = "user", root = "C:/msys64/home/stephen/.luarocks" };
```
so the path being used is not being generated (or parsed) correctly.

Also I too am having the broken `mkdir` behaviour - and I think I read somewhere recently that (some versions of) Luarocks (or or maybe `bash`) had a problem with the quoting of arguments/paths when it was being done at multiple levels (or maybe involved arguments that are command options that start with `-`)...?

**Comment by ImperatorS79** [comment]
I launched the command in the mingw64 shell:
```bash
mkdir -p  "C:\msys64\home\<top secret>\.cache\luarocks\https___luarocks.org"
```
and it worked. I think I will open an issue about it in the luarocks repository.

**Comment by SlySven** [comment]
I am wondering about the method that is being used by the Lua `os.execute` to assemble the command that it wants to run through an OS shell... - although I suppose it is also worth checking whether the `mkdir` being run ***is*** the one located at `C:/msys64/bin/mkdir` - imagine what might happen if the native **Windows** one was somehow being used instead...! :open_mouth:

**Comment by ImperatorS79** [comment]
Yes, my bad.

**Comment by ImperatorS79** [comment]
Indeed everything seems to be lauched in windows shell rather than msys shell. Adding the following code everywhere in fs:
```lua
local pipe = io.popen("cygpath --windows " .. pathname)
arg = pipe:read("*l")
pipe:close()
```

And modifying the luarocks cfg.lua to have windows path for the different executable seems to fix a lot of things. Time to open an issue on the luarocks repository

**Comment by jeremyd2019** [comment]
eww, this is a mingw package, right?  Shouldn't it be using Windows paths internally?

**Comment by ImperatorS79** [comment]
No, it is using path looking like this:
```
/c/msys64/mingw64
```
The path can be even more simplified , for exemple:
```
/home/dir/
```
Is a shortcut to:
```
/c/msys64/home/dir/
```
If I understood correctly.

**Comment by jeremyd2019** [comment]
Calling out to `cygpath` from a mingw package seems like a bad idea.  There is generally no guarantee that a mingw process is launched from an MSYS2 environment, so `cygpath` may not even be on the path.

For the select few packages that need to know about MSYS2 paths, see https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-pathtools

**Comment by ImperatorS79** [comment]
Normally luarocks should support msys2 -> https://github.com/luarocks/luarocks/pull/1230, so I will ask them.

**Comment by jeremyd2019** [comment]
ok, I see, that assumes it is running in an MSYS2 shell so calls MSYS2 things like `cygpath`.

**Comment by SlySven** [comment]
:warning: \<aside>This is a little off-topic but I will mention it here because it also is involved with paths and I don't think upstream havet spotted it - if one installed **both** the 32-bit (`-i686-`) and the 64-bit (`-x86_64-`) `luarocks` packages in the past - they put the user `--local` C binaries (I can't recall whether they were `xxx.dll`s or `libxxx.so`s) into the ***same*** user's sub-directory.

This was, I think, `home .. "/.luarocks/lib/lua/{lua version}"` which was no good as they messed up each other's records of what is installed.

Whilst most users might only need one bitness, those who need to build/test binary projects (say for/as distribution as self-contained archives) for others need to have/build both bitness rocks which was not handled by the 2.x luarocks packages as was and does not currently seem to be supported because the "user" rocktree entry is still the same for both bitnesses!\</aside>

**Comment by SlySven** [comment]
> No, it is using path looking like this:
>
>>/c/msys64/mingw64
>
>The path can be even more simplified , for exemple:
>
>>/home/dir/
>
>Is a shortcut to:
>
>>/c/msys64/home/dir/
>
>If I understood correctly.

Yeah, but at what point is the relevant conversion done? And haven't we determined that it was necessary to use:
> C:/msys64/mingw64

or is that just *another* equivalent (and which one is the one that eventually gets *used* - or is the answer to that ***it depends***? :roll_eyes: )

**Comment by ImperatorS79** [comment]
By using my trick with cygpath I managed to get a lot further in executing luarocks. Still it does not manage to install a rock correctly however. I think it is better to discuss this directly with luarocks devs (which I will do later this week).

**Comment by Alexpux** [comment]
@ImperatorS79 @jeremyd2019 using non-native tools or tools not provided by one of mingw package is completely bad idea. If you go to use cygpath then this packages must be MSYS package, rather then MINGW.

Stop doing such things in MINGW packages

**Comment by jeremyd2019** [comment]
That was my impression

**Comment by ImperatorS79** [comment]
@Alexpux I never said I will use cygpath in the final package. I am just using cygpath to debug the luarocks package and see at the end what works and what does not.

@kou You wrote the PR in the luarocks repository to support luarocks on msys' mingw. Any insight about this ?

**Comment by kou** [comment]
I'm busy recently. Could you wait for a few weeks...?

**Comment by ImperatorS79** [comment]
Yes I can, no worries.

**Comment by SlySven** [comment]
In the meantime users like myself can restore previous functionality by downloading and installing the previous (but renamed I think!) version manually with `wget` and `pacman -U`:

* 32-bit:
```sh
MSYS user@computer ~
$ wget https://repo.msys2.org/mingw/mingw32/mingw-w64-i686-lua51-luarocks-2.4.4-2-any.pkg.tar.zst
--2021-07-07 22:19:09--  https://repo.msys2.org/mingw/mingw32/mingw-w64-i686-lua51-luarocks-2.4.4-2-any.pkg.tar.zst
Resolving repo.msys2.org (repo.msys2.org)... 178.63.98.68
Connecting to repo.msys2.org (repo.msys2.org)|178.63.98.68|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 97905 (96K) [application/octet-stream]
Saving to: ‘mingw-w64-i686-lua51-luarocks-2.4.4-2-any.pkg.tar.zst’

mingw-w64-i686-lua51-luarocks-2.4.4-2- 100%[===========================================================================>]  95.61K  --.-KB/s    in 0.07s

2021-07-07 22:19:10 (1.43 MB/s) - ‘mingw-w64-i686-lua51-luarocks-2.4.4-2-any.pkg.tar.zst’ saved [97905/97905]


MSYS user@computer ~
$ pacman -U mingw-w64-i686-lua51-luarocks-2.4.4-2-any.pkg.tar.zst
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-i686-lua51-luarocks-2.4.4-2

Total Installed Size:  0.46 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                [#####################################################] 100%
(1/1) checking package integrity                                                              [#####################################################] 100%
(1/1) loading package files                                                                   [#####################################################] 100%
(1/1) checking for file conflicts                                                             [#####################################################] 100%
(1/1) checking available disk space                                                           [#####################################################] 100%
:: Processing package changes...
(1/1) installing mingw-w64-i686-lua51-luarocks                                                [#####################################################] 100%

MSYS user@computer ~
```

* 64-bit
```sh
MSYS user@computer ~
$ wget https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-lua51-luarocks-2.4.4-2-any.pkg.tar.zst
--2021-07-07 22:17:32--  https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-lua51-luarocks-2.4.4-2-any.pkg.tar.zst
Resolving repo.msys2.org (repo.msys2.org)... 178.63.98.68
Connecting to repo.msys2.org (repo.msys2.org)|178.63.98.68|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 97935 (96K) [application/octet-stream]
Saving to: ‘mingw-w64-x86_64-lua51-luarocks-2.4.4-2-any.pkg.tar.zst’

mingw-w64-x86_64-lua51-luarocks-2.4.4- 100%[===========================================================================>]  95.64K  --.-KB/s    in 0.07s

2021-07-07 22:17:32 (1.28 MB/s) - ‘mingw-w64-x86_64-lua51-luarocks-2.4.4-2-any.pkg.tar.zst’ saved [97935/97935]


MSYS user@computer ~
$ pacman -U mingw-w64-x86_64-lua51-luarocks-2.4.4-2-any.pkg.tar.zst
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-lua51-luarocks-2.4.4-2

Total Installed Size:  0.46 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                [#####################################################] 100%
(1/1) checking package integrity                                                              [#####################################################] 100%
(1/1) loading package files                                                                   [#####################################################] 100%
(1/1) checking for file conflicts                                                             [#####################################################] 100%
(1/1) checking available disk space                                                           [#####################################################] 100%
:: Processing package changes...
(1/1) installing mingw-w64-x86_64-lua51-luarocks                                              [#####################################################] 100%

MSYS user@computer ~
```

**Comment by kou** [comment]
LuaRocks (Lua interpreter) uses Windows shell (`cmd.exe`) (not MSYS2 shell) and Windows style path (`C:\\...`) internally because this is a MINGW package.

LuaRocks uses some external tools such as `mkdir`. In `cmd.exe`, `mkdir` is resolved as a built-in [`mkdir`/`md` command](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb490930(v=technet.10)?redirectedfrom=MSDN). `mkdir` in MSYS2 is never used. `cmd.exe`'s `mkdir` doesn't support `-p` option.

https://github.com/luarocks/luarocks/pull/1230 includes changes to use MSYS2 tools not tools in Windows. But it's not merged. https://github.com/luarocks/luarocks/pull/1231 is merged but it doesn't include the change. Because LuaRocks developers and I agreed with we use LuaRocks Windows package for MINGW package to reduce LuaRocks' maintenance cost: https://github.com/luarocks/luarocks/pull/1230#issuecomment-705335356
The LuaRocks Windows package includes tools such as `mkdir`.

But this approach isn't acceptable for MINGW package: https://github.com/msys2/MINGW-packages/pull/7431#issuecomment-743452765

The next action is that we consider the best way to install LuaRocks as MINGW package. But I don't work on this yet because I'm busy...

**Comment by ImperatorS79** [comment]
@SlySven I managed to install a rocks by using @kou patchset https://github.com/luarocks/luarocks/pull/1230. Would be great if you could test it too. Here is a link to the package -> https://www.mediafire.com/file/io5aomivtb2gy7w/mingw-w64-x86_64-lua-luarocks-3.7.0-1-any.pkg.tar.zst/file

If it works for you I will do a PR, then we could discuss about https://github.com/msys2/MINGW-packages/issues/9037#issuecomment-875162051.

**Comment by SlySven** [comment]
>LuaRocks (Lua interpreter) uses Windows shell (cmd.exe) (not MSYS2 shell) and Windows style path (C:\\...) internally because this is a MINGW package.

😕 I not convinced about that! The MSYS2/Mingw-w64 luarocks package has to come in two flavours i.e. `-i686-` and `-x86_64-` because it/they have to compile from source code - in some cases - to produce Lua binary library/module files - and that requires uses the relevant compiler/linking to other libraries. I am not sure that a MSYS2 package can accommodate compiling both 32 and 64-bit binary files simultaneously... 

I feel that upstream is overlooking the fact that their work with the original Mingw is only ever 32-bit, whereas Mingw-w64 supports both 32 and 64-bit and binaries for the large bitness will not work on 32-bit systems...

>@SlySven I managed to install a rocks by using @kou patchset luarocks/luarocks#1230. Would be great if you could test it too. Here is a link to the package -> https://www.mediafire.com/file/io5aomivtb2gy7w/mingw-w64-x86_64-lua-luarocks-3.7.0-1-any.pkg.tar.zst/file

I downloaded it and installed it (with a `pacman -U` on the downloaded file) - not surprisingly I had to uninstall the previous `mingw-w64-x86_64-lua51-luarocks` package first. It also pulled in `mingw-w64-x86_64-lua-5.4.2-2` - which I guess is expected. However when I tried a plain `luarocks` in a `MINGW64` shell it failed with a message:
```sh
stephen@Rachel MINGW64 ~
$ luarocks
bash: /mingw64/bin/luarocks: C:\\tools\\msys64\\mingw64\\bin/lua.exe: bad interpreter: No such file or directory

stephen@Rachel MINGW64 ~
$
```
looking into the config files I see they do not have the right paths as they refer to a non-existent `C:\tools\msys64\mingw64` location so I made the following changes:
* `C:\msys64\mingw64\etc\luarocks\config-5.1.lua`
```diff
 -- LuaRocks configuration
 
 rocks_trees = {
-   { name = "user", root = home .. "/.luarocks" };
+   { name = "user", root = home .. "/.luarocks-x64" }; -- Not directly related to this issue but I need it segregating building user (--local) versions of both 32 and 64 bit lua modules on the same system
-   { name = "system", root = [[C:\tools\msys64\mingw64]] };
+   { name = "system", root = [[/c/msys64/mingw64]] };
 }
 lua_interpreter = [[lua5.1.exe]];
 variables = {
-   LUA_DIR = [[C:\tools\msys64\mingw64]];
+   LUA_DIR = [[/c/msys64/mingw64]];
-   LUA_INCDIR = [[C:\tools\msys64\mingw64\include\lua5.1]];
+   LUA_INCDIR = [[/c/msys64/mingw64/include/lua5.1]];
-   LUA_BINDIR = [[C:\tools\msys64\mingw64\bin]];
+   LUA_BINDIR = [[/c/msys64/mingw64/bin]];
 }
```
* `C:\msys64\mingw64\etc\luarocks\config-5.4.lua`
```diff
 -- LuaRocks configuration
 
 rocks_trees = {
-   { name = "user", root = home .. "/.luarocks" };
+   { name = "user", root = home .. "/.luarocks-x64" }; -- Not directly related to this issue but I need it segregating building user (--local) versions of both 32 and 64 bit lua modules on the same system
-   { name = "system", root = [[C:\tools\msys64\mingw64]] };
+   { name = "system", root = [[/c/msys64/mingw64]] };
 }
 lua_interpreter = [[lua.exe]];
 variables = {
-   LUA_DIR = [[C:\tools\msys64\mingw64]];
+   LUA_DIR = [[/c/msys64/mingw64]];
-   LUA_BINDIR = [[C:\tools\msys64\mingw64\bin]];
+   LUA_BINDIR = [[/c/msys64/mingw64/bin]];
 }
```

That didn't make the `luarock` command work - then I remembered that it (and `luarocks-admin`) are (now?) Lua scripts and those too had these odd (wrong?) paths in the (identical) first few lines that needed *fixing* in the same manner:
```diff
-#!C:\\tools\\msys64\\mingw64\\bin/lua.exe
+#!/c/msys64/mingw64/bin/lua.exe
-package.loaded["luarocks.core.hardcoded"] = { SYSCONFDIR = [[C:\tools\msys64\mingw64\etc\luarocks]] }
+package.loaded["luarocks.core.hardcoded"] = { SYSCONFDIR = [[/c/msys64/mingw64/etc/luarocks]] }
-package.path=[[C:\tools\msys64\mingw64\share\lua\5.4\?.lua;]] .. package.path
+package.path=[[/c/msys64/mingw64/share/lua/5.4/?.lua;]] .. package.path
-local list = package.searchers or package.loaders; table.insert(list, 1, function(name) if name:match("^luarocks%%.") then return loadfile([[C:\tools\msys64\mingw64\share\lua\5.4\]] .. name:gsub([[%%.]], [[/]]) .. [[.lua]]) end end)
+local list = package.searchers or package.loaders; table.insert(list, 1, function(name) if name:match("^luarocks%%.") then return loadfile([[/c/msys64/mingw64/share/lua/5.4/]] .. name:gsub([[%%.]], [[/]]) .. [[.lua]]) end end)

```

After that things still didn't work:
```sh
$ luarocks
C:\msys64\mingw64\bin\lua.exe: C:/msys64/mingw64/bin/luarocks:7: module 'luarocks.core.cfg' not found:
        no field package.preload['luarocks.core.cfg']
        no file '/c/msys64/mingw64/share/lua/5.4/luarocks\core\cfg.lua'
        no file '.\luarocks\core\cfg.lua'
        no file 'C:\msys64\home\stephen\.luarocks-x64\share\lua\5.1\luarocks\core\cfg.lua'
        no file 'C:\msys64\home\stephen\.luarocks-x64\share\lua\5.1\luarocks\core\cfg\init.lua'
        no file 'C:\msys64\mingw64\share\lua\5.1\luarocks\core\cfg.lua'
        no file 'C:\msys64\mingw64\share\lua\5.1\luarocks\core\cfg\init.lua'
        no file 'C:\msys64\mingw64\lua\luarocks\core\cfg.lua'
        no file 'C:\msys64\mingw64\lib\lua\5.1\luarocks\core\cfg.lua'
        no file 'C:\msys64\mingw64\lib\lua\5.1\luarocks\core\cfg\init.lua'
        no file '.\luarocks\core\cfg.dll'
        no file 'C:\msys64\home\stephen\.luarocks-x64\lib\lua\5.1\luarocks\core\cfg.dll'
        no file 'C:\msys64\mingw64\lib\lua\5.1\luarocks\core\cfg.dll'
        no file 'C:\msys64\mingw64\lib\lua\5.1\loadall.dll'
        no file '.\luarocks.dll'
        no file 'C:\msys64\home\stephen\.luarocks-x64\lib\lua\5.1\luarocks.dll'
        no file 'C:\msys64\mingw64\lib\lua\5.1\luarocks.dll'
        no file 'C:\msys64\mingw64\lib\lua\5.1\loadall.dll'
stack traceback:
        [C]: in function 'require'
        C:/msys64/mingw64/bin/luarocks:7: in main chunk
        [C]: in ?

stephen@Rachel MINGW64 ~
$
```

so I gave up on this.

I also note that `mingw-w64-x86_64-lua-luarocks-3.7.0-1-any.pkg.tar.zst` is a 64-bit package (so I'd expect to use it in a MINGW64 shell) - is there a corresponding `mingw-w64-i686-lua-luarocks-3.7.0-1-any.pkg.tar.zst` ?

**Comment by ImperatorS79** [comment]
Okay, I will investigate further because it works on my end. "/c/tools/msys64" is where msys is installed on my computer, so I certainly made a mistake somewhere.
