### ISSUE TITLE
boost: context lacking asm implementation for MinGW ARM/ARM64

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#9045]
This is pretty expected, but entering here to record it.  It seems that context is still lacking an arm64 implementation for Windows, even with MSVC.

**Comment by Biswa96** [comment]
Do I have to I compile all the dependencies (e.g. Boost::assert, Boost::config, Boost::core etc.) for that target CPU architecture before porting boost context?

**Comment by olk** [comment]
Only the libraries boost.context depends on. If you compile boost.context
with the appropriate boost.build properties (architecture, binary format,
abi etc.) then all these libs are compiled automatically.

Biswapriyo Nath ***@***.***> schrieb am Do., 8. Juli 2021,
08:02:

**Comment by dennisameling** [comment]
> It seems that context is still lacking an arm64 implementation for Windows, even with MSVC.

FYI the MSVC version is available since a month or two: https://github.com/boostorg/context/pull/201

**Comment by olk** [comment]
> > It seems that context is still lacking an arm64 implementation for Windows, even with MSVC.
> 
> FYI the MSVC version is available since a month or two: [boostorg/context#201](https://github.com/boostorg/context/pull/201)

#201 merged

**Comment by mstorsjo** [comment]
I was pointed here... I'm not familiar with the libraries here or how to test them, but it looks like it shouldn't be too hard to make it build.

For mingw arm64 cases, it uses GAS style assembly, and there are very few ABI differences to generic AAPCS on other platforms. In many cases, ELF GAS work as is, or with very few modifications. There seems to be a few ELF specific assembly directives in those files; if they are wrapped with `#ifdef __ELF__`, I think it should work just fine. Looking at https://github.com/boostorg/context/blob/697299ea554c04ae8a5cfb1b5cc3ec9caf61724d/src/asm/jump_arm64_aapcs_elf_gas.S, the `.type`, `.size` and `.section` directives aren't needed/supported for COFF targets, so by wrapping them it should build.

That is, whatever ASM files are picked for the MSVC case, `*_pe_armasm.asm`, use the corresponding `*_elf_gas.S` files instead, and add ifdefs to them. But before doing that, it's kinda important to check that there aren't any functional differences in the assembly itself between the `_elf_gas.S` and `_pe_armasm` files; check with diff that the only differences are in the directives wrapping it, not the instructions themselves.

If there are differences, you may need to take the `*_pe_armasm.asm` files, rename them to `*_pe_gas.S` and replace the outer structure with that of the `*_elf_gas.S` files (minus unsupported directives).

I won't have time to try this myself, but I'm happy to provide input if someone tries.

**Comment by MehdiChinoune** [comment]
Fixed upstream by https://github.com/boostorg/context/commit/e878e8ed with patch to build with CMake https://github.com/msys2/MINGW-packages/commit/da4f4c37

**Comment by jeremyd2019** [comment]
> Fixed upstream by [boostorg/context@e878e8ed](https://github.com/boostorg/context/commit/e878e8ed) with patch to build with CMake [da4f4c37](https://github.com/msys2/MINGW-packages/commit/da4f4c37)

Maybe make a PR upstream, perhaps boostorg/context#275 could benefit from this too?

**Comment by MehdiChinoune** [comment]
> Maybe make a PR upstream, perhaps [boostorg/context#275](https://github.com/boostorg/context/pull/275) could benefit from this too?

 https://github.com/boostorg/context/pull/276
