### ISSUE TITLE
rust: doesn't support aarch64-windows-gnu

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#9046]

**Comment by dennisameling** [comment]
I'd like to look a bit into this as [I need Rust for `librsvg`](https://github.com/dennisameling/Signal-Desktop/issues/4#issuecomment-994032306):

https://github.com/msys2/MINGW-packages/blob/54e8257252708f1515227944654897eac2e98640/mingw-w64-librsvg/PKGBUILD#L16

Luckily, @mati865 already did an amazing job at [patching Rust to be built using Clang](https://github.com/msys2/MINGW-packages/commit/bd75a4306c37714fc49fcb3cd5494a57d86e534c). I have a feeling that `clangarm64` shouldn't be too far out for this, but am mainly worried about [the GCC requirement](https://github.com/msys2/MINGW-packages/commit/bd75a4306c37714fc49fcb3cd5494a57d86e534c#diff-f25a91ec6d7e12618da3085fa0581e0076247dff5610b75c6b999adf3bdf25d5R73-R81), as that's not available for Windows arm64.

Based on your knowledge and experience, would you say it's possible to:
- Create the bootstrap compiler (`x86_64-pc-windows-gnu`)
- [Create a new target specification](https://rustc-dev-guide.rust-lang.org/building/new-target.html#creating-a-target-specification) for `aarch64-pc-windows-gnu` and use the `x86_64` toolchain to build that (Rust [already seems to be using that MinGW toolchain for `aarch64-pc-windows-msvc`](https://github.com/rust-lang/rust/blob/0a4dc8bc161c68320a60a6bde525adae258b6252/src/ci/scripts/install-mingw.sh#L45-L51))

If I understand things correctly, this will allow us to create a `Stage 0` compiler for `aarch64-pc-windows-gnu` on a x86_64 host. Rust [already did this before](https://github.com/rust-lang/rust/pull/75914), where they built both `x86_64-pc-windows-msvc` and `aarch64-pc-windows-msvc` from the same host.

Thanks in advance!

**Comment by mati865** [comment]
> If I understand things correctly, this will allow us to create a Stage 0 compiler for aarch64-pc-windows-gnu on a x86_64 host.

I guess more things will require patching, like exceptions handling.

> I guess this will only be problematic until we're able to build a Stage 0 compiler for aarch64-pc-windows-gnu from a x86_64 device, correct?

We will always have to use local compiler for bootstrapping but that should be fine.

**Comment by Biswa96** [comment]
> I'd like to look a bit into this as I need Rust for librsvg

FYI, there is an older version of librsvg without Rust-ification https://packages.msys2.org/base/mingw-w64-librsvg-2.40

**Comment by jeremyd2019** [comment]
Keep in mind this is an older, unsupported version so may not be the best from a security standpoint.

**Comment by dennisameling** [comment]
Have been making some progress in https://github.com/dennisameling/rust/pull/1 - will follow up there

**Comment by dennisameling** [comment]
Have been working on getting a Rust upstream build to work using `clang64` over the weekend - [artifacts can be downloaded here](https://github.com/dennisameling/rust/releases/tag/windows-gnu-clang). Once the `stage0` compiler/toolchain will use Clang, it should also become much easier to create `clangarm64` builds as it no longer will try to link against `x86_64-w64-mingw32-gcc` for the stage0 compiler, but use `x86_64-w64-mingw32-clang` instead. Massive thanks to the MSYS2 team for [creating the necessary patches](https://github.com/msys2/MINGW-packages/blob/911622ebc606e15ae6a73dbecff93ea5b61bcd28/mingw-w64-rust/0007-clang-subsystem.patch) a while ago already 🙏🏼 

PR: https://github.com/rust-lang/rust/pull/92502

**Comment by mati865** [comment]
I've hacked together and cross compiled from Linux toolchain that might work on AArch64 but I couldn't setup usable AArch64 VM on my x86_64 system. Therefore I'm looking for brave tester willing to run my binary (native or VM AArch64 Windows) and share the results.

Steps to test it:
1. Prepare MSYS2 or llvm-mingw toolchain (I have used [20220209 with LLVM 14.0.0 RC1](https://github.com/mstorsjo/llvm-mingw/releases/tag/20220209) for the cross-compilation) and have AArch64 DLLs (libunwind and libc++) in `PATH`.
2. Download and extract https://1drv.ms/u/s!AgMYIlqTF8b9guht4mhJOcWOjIFXwg?e=42zVoh. Then add `bin/` from that archive to `PATH`.
3. Run `rustc -vV`
4. Run `rustc -Z unstable-options --print target-spec-json`
5. Build and run hello world with and without optimisations, example how to do it:
```
# Create hello world file
$ cat hello.rs
fn main() {
    println!("Hello, World!");
}

# Debug build
$ rustc hello.rs

$ ./hello.exe
# Should say `Hello, World!`

# Opt build
$ rustc -O hello.rs

$ ./hello.exe
# Should say `Hello, World!`
```
6. Share the results of steps 3, 4 and 5

**Comment by mstorsjo** [comment]
> 3. Run `rustc -vV`

```
rustc 1.61.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: aarch64-pc-windows-gnullvm
release: 1.61.0-dev
LLVM version: 14.0.0
```

> 4. Run `rustc -Z unstable-options --print target-spec-json`

```
{
  "abi": "llvm",
  "abi-return-struct-as-int": true,
  "allows-weak-linkage": false,
  "arch": "aarch64",
  "data-layout": "e-m:w-p:64:64-i32:32-i64:64-i128:128-n32:64-S128",
  "dll-prefix": "",
  "dll-suffix": ".dll",
  "dynamic-linking": true,
  "eh-frame-header": false,
  "emit-debug-gdb-scripts": false,
  "env": "gnu",
  "exe-suffix": ".exe",
  "executables": true,
  "features": "+neon,+fp-armv8",
  "is-builtin": true,
  "is-like-windows": true,
  "late-link-args": {
    "gcc": [
      "-lmingw32",
      "-lmingwex",
      "-lmsvcrt",
      "-lkernel32",
      "-luser32"
    ],
    "ld.lld": [
      "-lmingw32",
      "-lmingwex",
      "-lmsvcrt",
      "-lkernel32",
      "-luser32"
    ]
  },
  "late-link-args-dynamic": {
    "gcc": [
      "-lunwind"
    ],
    "ld.lld": [
      "-lunwind"
    ]
  },
  "late-link-args-static": {
    "gcc": [
      "-l:libunwind.a"
    ],
    "ld.lld": [
      "-l:libunwind.a"
    ]
  },
  "linker": "aarch64-w64-mingw32-clang",
  "llvm-target": "aarch64-pc-windows-gnu",
  "max-atomic-width": 64,
  "no-default-libraries": false,
  "os": "windows",
  "pre-link-args": {
    "gcc": [
      "-nolibc",
      "--unwindlib=none"
    ],
    "ld.lld": [
      "-m",
      "arm64pe"
    ]
  },
  "requires-uwtable": true,
  "target-family": [
    "windows"
  ],
  "target-pointer-width": "64",
  "vendor": "pc"
}
```

> 5. Build and run hello world with and without optimisations, example how to do it:

These steps work and behave just as expected.

**Comment by lazka** [comment]
The fwpuclnt fixes are now in the repo.

**Comment by mati865** [comment]
Thanks but I haven't yet found a way to bootstrap it on AArch64 Windows. I have ideas for few more hacks but I need to finish https://github.com/rust-lang/rust/pull/94872 first and I want to test upgrading our LLVM toolchain to version 14 since RC4 has been just released with fix for building from tarballs.

**Comment by mati865** [comment]
Update: LLVM still seems to have broken tarballs: https://github.com/llvm/llvm-project/issues/53281#issuecomment-1065842920
More time for Rust I guess 🤷🏻‍♂️
