### ISSUE TITLE
`dfu-util` dependency on `gcc-libs`

### ISSUE THREAD

**Issue by fauxpark** [msys2/MINGW-packages#9101]
Following on from discussion in #7400.

`dfu-util` depends on `libwinpthread-git` as well as libusb. The above PR solved this for the mingw64 build but mingw32 still does not work without `libgcc_s_dw2-1.dll` also being present (provided by [`gcc-libs`](https://packages.msys2.org/package/mingw-w64-i686-gcc-libs?repo=mingw32), which is not installed by default)

It is apparently pulled in by `libwinpthread-1.dll`, however the only way to force `libwinpthread-1.dll` to be statically linked seems to be to move `libpthread.dll.a` out of the way during the build. Static linking does not fix this anyway because the reference is embedded in libgcc itself:
https://github.com/gcc-mirror/gcc/blob/master/libgcc/config/i386/cygming-crtbegin.c#L114-L150

I don't know if this is a bug or intentional - I assume there is a good reason `LoadLibrary()` has to be used for 32-bit builds but not 64-bit. But this means `dfu-util` cannot be run without `libwinpthread-git`, and mingw32 without `gcc-libs` also, which doesn't seem correct to me.

**Comment by jeremyd2019** [comment]
OK, good, I was confused what you were talking about in the other discussion...

1. Yes, generally packages are dynamically linked, unless there's a *really* good reason not to.
2. That `LoadLibrary` call you referenced will only be invoked if `GetModuleHandle` returned non-null.  In effect, this means it will only use `LoadLibrary` if the library is already loaded.  It does this to increment the reference count, as the comment says.  If libgcc were statically linked, `GetModuleHandle` of the libgcc soname would return NULL and it would just use the plain function pointers in the else case.

**Comment by fauxpark** [comment]
Perhaps I should explain my initial problem. Over at QMK we have the [QMK Toolbox](https://github.com/qmk/qmk_toolbox), which bundles several microcontroller flashing tools and runs the appropriate one with the appropriate arguments when a device is plugged in. I'd like to use the binaries compiled by MSYS (taken from the `.zst`s) as a single source of truth, rather than have them compiled by some random person with who knows what added etc. 
I've been able to do this with everything but avrdude, which [segfaults under certain conditions](https://github.com/msys2/MINGW-packages/issues/8178), and dfu-util, because I found it also depends on `libwinpthread.dll`.
With that in mind...

> Yes, generally packages are dynamically linked, unless there's a really good reason not to.

Yep, I have no problem with that, however my confusion is over the fact that the [win32 dfu-util release on Sourceforge](http://dfu-util.sourceforge.net/releases/) (which the Toolbox is currently using) apparently only depends on libusb but not `libgcc_s_dw2-1.dll` or `libinwpthread-1.dll`.

> That LoadLibrary call you referenced will only be invoked if GetModuleHandle returned non-null. In effect, this means it will only use LoadLibrary if the DLL is already loaded. It does this to increment the reference count, as the comment says. If libgcc were statically linked, GetModuleHandle of the libgcc soname would return NULL (because a libgcc DLL would not be already loaded) and it would just use the plain function pointers in the else case.

The above code was the only thing I could find in the entire GCC source that seemed relevant. If I place dfu-util.exe in a folder outside of MSYS2, with libusb-1.0.dll and libwinpthread-1.dll, I get this error when running it in cmd:
![image](https://user-images.githubusercontent.com/4781841/124538427-f5f99a00-de5e-11eb-945d-cb0662ac11bc.png)
Place the libgcc DLL in there as well, and I get help text as expected.

> mingw-w64-gcc-libs is not installed by default?!? Just about everything depends on it... If this package doesn't, apparently it should.

From a fresh install in a fresh VM:
![image](https://user-images.githubusercontent.com/4781841/124538554-31946400-de5f-11eb-81fb-e75675495c23.png)
MSYS gcc-libs is installed by default, but mingw64/32 gcc-libs are not - they're part of the mingw-w64-{ARCH}-toolchain group.

**Comment by jeremyd2019** [comment]
yeah, no mingw-w64 packages are installed by default in a fresh install.

**Comment by jeremyd2019** [comment]
you need a statically linked libusb as well as a statically linked dfu-util (or you need dfu-util to statically link to libusb as well).

```
$ ntldd -R dfu-util.exe
... bunch of windows DLLs ...
        libwinpthread-1.dll (0x014d0000)
        libusb-1.0.dll (0x014d0000)
         libgcc_s_dw2-1.dll (0x01510000)
```

So dfu-util links to libwinpthread, and libusb links to libgcc_s_dw2-1.dll.

**Comment by fauxpark** [comment]
Looks like both dfu-util and libusb link to winpthread (the latter only on i686, and through `libgcc_s_dw2-1.dll`) because they both include `time.h`, which in turn includes `pthread_time.h`. This despite the fact that libusb will be using the Windows backend (and thus threading model), not the POSIX one. At least, that's how I understand it.

So I guess winpthreads is simply unavoidable under MSYS2, even if other parts are using Windows threads?

**Comment by jeremyd2019** [comment]
if it uses one of the posix-y time functions like nanosleep, then yeah.

**Comment by jeremyd2019** [comment]
yes, looks like clang32 variant doesn't depend on anything but libusb and windows dlls.

**Comment by tormodvolden** [comment]
Interesting. dfu-util will use nanosleep if available, otherwise it will use the win32 Sleep. It would be possible to invert this (in src/portable.h) so that it checks for Sleep first. It may then avoid the winpthread dependency.
