### ISSUE TITLE
windres (clang) fails to build windows-default-manifest.

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#9106]
```
windres -F pe-x86-64 default-manifest.rc -o default-manifest.o
  llvm-rc: Error parsing file: expected ',', got "<assembly xmlns=""urn:schemas-microsoft-com:asm.v1"" manifestVersion=""1.0"">\n"
  make: *** [Makefile:28: default-manifest.o] Error 1
  ==> ERROR: A failure occurred in build().
      Aborting...
```

**Comment by jeremyd2019** [comment]
Yep.  /cc @mstorsjo .  Limitations of LLVM's RC parser I think

**Comment by mstorsjo** [comment]
Can you share a copy of the input files (the rc file and the manifest file it references?) so I can test it out side by side standalone with gnu windres vs llvm-rc?

**Comment by jeremyd2019** [comment]
https://sourceware.org/git/?p=cygwin-apps/windows-default-manifest.git;a=blob;f=default-manifest.rc;h=2c4ddf4783b953afaf7df9473450bf95842d1911;hb=refs/heads/master

**Comment by mstorsjo** [comment]
Thanks, reproduced it. Both GNU windres and MS rc.exe handle this syntax, but llvm-rc doesn't.

**Comment by jeremyd2019** [comment]
FYI, I think this style of syntax is the main thing that fails with llvm-rc but succeeds with GNU windres in MINGW-packages.  windows-default-manifest is just the simplest version of it.

**Comment by Biswa96** [comment]
For extra test cases, package that fails to build with the same error as OP is https://packages.msys2.org/base/mingw-w64-chicken

```
llvm-rc: Error parsing file: expected ',', got "<assembly xmlns=""urn:schemas-microsoft-com:asm.v1"" manifestVersion=""1.0"">\r\n"
make: *** [rules.make:209: chicken-install.rc.o] Error 1
```

git repo https://code.call-cc.org/cgi-bin/gitweb.cgi?p=chicken-core.git

**Comment by mstorsjo** [comment]
https://github.com/llvm/llvm-project/commit/beb0e7e338d6c196362745ddebc24ae394bff6f2 should fix this.
