### ISSUE TITLE
[gtk4]

### ISSUE THREAD

**Issue by tasiek30** [msys2/MINGW-packages#9112]
Recently I decide to try GTK4 (currently I am using wxWidgets, but now i need something with more modern feel and look).

I’m working on Windows 10 Pro 64bit

I get library directly from MSYS:

    pacman -S mingw-w64-i686-gtk4

Succesfully i compile example with mingw32 (path variable have C:\msys64\mingw32\bin):

    gcc pkg-config --cflags gtk4 -o test test_c.c pkg-config --libs gtk4

test_c.c:

    #include <gtk/gtk.h>
    static void
    activate (GtkApplication* app, gpointer user_data)
    {
    GtkWidget *window;
    window = gtk_application_window_new (app);
    gtk_window_set_title (GTK_WINDOW (window), “Window”);
    gtk_window_set_default_size (GTK_WINDOW (window), 200, 200);
    gtk_widget_show (window);
    }
    int main (int argc, char **argv)
    {
    GtkApplication *app;
    int status;

    app = gtk_application_new (“org.gtk.example”, G_APPLICATION_FLAGS_NONE);
    g_signal_connect (app, “activate”, G_CALLBACK (activate), NULL);
    status = g_application_run (G_APPLICATION (app), argc, argv);
    g_object_unref (app);

    return status;
    }

But aplication won’t run:
![Przechwytywanie](https://user-images.githubusercontent.com/34631947/124919291-57a03c80-dff6-11eb-95b5-dc31a6b936be.PNG)

The procedure entry point vkAcquireNextImageKHR could not be located in the dynamic linked library C:/msys64/mingw32/bin/libgtk-4-1.dll

So i decide to try x64 version:

    pacman -S mingw-w64-x86_64-gtk4

and compile with mingw64 (path variable now have C:\msys64\mingw64\bin):

    gcc pkg-config --cflags gtk4 -o test test_c.c pkg-config --libs gtk4

and application sucessfully run.

Also i try to use mingw32 and GTK3 :

    gcc pkg-config --cflags gtk+-3.0 -o test test_c.c pkg-config --libs gtk+-3.0

and application sucessfully run.

Is it possible to run GTK4 32 bit application on 64 bit machine?

![Przechwytywanie2](https://user-images.githubusercontent.com/34631947/124919437-8d452580-dff6-11eb-8429-88bcdd9acc2c.PNG)

**Comment by ZachBacon** [comment]
It is, it just looks like gtk4 for 32 but needs to be rebuilt maybe.

**Comment by lazka** [comment]
Rebuild will be in the next update.
