### ISSUE TITLE
llvm dlltools does not support `--output-delaylib`

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#9115]
LLVM dlltool only support essentially one operation, taking a def file and generating an import library out of it. (GNU dlltool also supports e.g. generating a separate delay import library - LLVM dlltool doesn't support this, and instead allows you to tell the linker to link a specific DLL as delay loaded, without needing to create a separate import library for use with delay loading).

_Originally posted by @mstorsjo in https://github.com/msys2/MINGW-packages/issues/9055#issuecomment-864608930_

**Comment by jeremyd2019** [comment]
So far this has affected cx_Freeze.  They have some *interesting* logic to check `compiler_type` from python distutils, which can be either msvc or mingw32 for windows, and either using MSVC's `/delayload:` option (and adding delayimp.lib to the libs), or using dlltool to generate a delaylib and linking that.  I don't see an obvious way to 'know' that mingw32 is really clang/llvm and handling that differently than gcc/binutils-based mingw32.

https://github.com/marcelotduarte/cx_Freeze/blob/9b11b50027dacb2ed88724a5a25aef7f3a5ec869/setup.py#L51-L67

**Comment by mstorsjo** [comment]
FWIW the one case I know about that does this, is wine, and there they (at least originally) added a configure test that checks if `-Wl,-delayload,foo.dll` is supported, https://source.winehq.org/git/wine.git/commitdiff/3d19efae72bf0f10acad7db6fea183b10017dc58. (Later it was changed to be tied exactly to whether the compiler is clang though, but one could be using clang+ld.bfd or gcc+lld too.)

**Comment by jeremyd2019** [comment]
What is the exact command line options to use delayload with mingw lld?  Is there a 'direct' option or does it require passing through with `-Xlink`?  Does it require linking in `-ldelayimp` like MSVC?

**Comment by mstorsjo** [comment]
> What is the exact command line options to use delayload with mingw lld? Is there a 'direct' option or does it require passing through with `-Xlink`? Does it require linking in `-ldelayimp` like MSVC?

You can do e.g. `-Wl,--delayload=shell32.dll`, a mingw level option for it was added in https://reviews.llvm.org/D65728. It doesn't seem to need linking in `-ldelayimp` explicitly.

**Comment by marcelotduarte** [comment]
Thanks!

**Comment by ognevny** [comment]
,,,and llvm-dlltool still doesn't have support for `--output-delaylib`. it's required for rufus to work on CLANG* environments
