### ISSUE TITLE
poppler-qt6

### ISSUE THREAD

**Issue by sunderme** [msys2/MINGW-packages#9126]
Are there any plans to enable poppler-qt6 interface ?

**Comment by Biswa96** [comment]
It is possible to do that but there are some hurdles.
1. In same pkgbuild: poppler has qt5 as make depends. If we add qt6-base as make depends then qt6-base will conflict with qt5. 
2. In different pkgbuild no issue. But one has to change two pkgbuild files if there is an update or fix.

CC. @MehdiChinoune (qt6 package maintainer) Any thoughts?

**Comment by ZachBacon** [comment]
> It is possible to do that but there are some hurdles.
> 1. In same pkgbuild: poppler has qt5 as make depends. If we add qt6-base as make depends then qt6-base will conflict with qt5. 
> 2. In different pkgbuild no issue. But one has to change two pkgbuild files if there is an update or fix.
> 
> CC. @MehdiChinoune (qt6 package maintainer) Any thoughts?

Based on Arch's pkgbuild for qt6 you can change the bin directory for qt6 so that it doesn't conflict with qt5

**Comment by Biswa96** [comment]
> you can change the bin directory for qt6 so that it doesn't conflict with qt5

It's possible if qt6-base does not conflict with qt5. That trick was also done py2+py3 days. Those makedepends need to be installed before build. See the conflict here https://packages.msys2.org/package/mingw-w64-x86_64-qt6-base?repo=mingw64

**Comment by sunderme** [comment]
if qt6 can't be installed along with qt5, it may be simpler to have a poppler-qt6 package ?

**Comment by sunderme** [comment]
so, I have got homebrew to have poppler and poppler-qt5. (https://github.com/Homebrew/homebrew-core/pull/81248#event-50287520179)
Now, how do we proceed here ?

**Comment by MehdiChinoune** [comment]
I removed the conflcit between qt6-base and qt5.
#9268

**Comment by sunderme** [comment]
Thanks.
