### ISSUE TITLE
Windows 11 21H2 22000.51 breaks `tar` -> `makepkg-mingw`

### ISSUE THREAD

**Issue by galeksandrp** [msys2/MINGW-packages#9127]
It contains `tar.exe` `bsdtar 3.4.3 - libarchive 3.4.3 zlib/1.2.5.f-ipp bz2lib/1.0.6` in `C:\Windows\System32`. Maybe that isn't bad thing, but bad thing is that `22000.51` does not ship `xz` with it, resulting in calling `xz` from `MSYS`. Feel the `stdin/out` incompat? - and there it is, `xz` just hangs.

Fixed it by installing `MSYS` tar, and not sure what to do next - maybe attach `tar` as dependency to `base`?

P.S. `C:\Windows\System32\tar.exe` is installed by `TrustedInstaller`, so don't expect easy way of removing it - extreme trickery with `nsudo` is needed, risking destroying subsystem which installed `tar.exe` - probably `WSL`. And that will only hold until next `Windows Update`.

**Comment by Biswa96** [comment]
> P.S. C:\Windows\System32\tar.exe is installed by TrustedInstaller, so don't expect easy way of removing it

I have been doing the exact same thing since when Windows 10 OS keep shipping tar, curl, bash etc. Commands as administrator:

```bat
takeown /f "%SystemRoot%\System32\tar.exe"
icacls "%SystemRoot%\System32\tar.exe" /grant Everyone:F
del "%SystemRoot%\System32\tar.exe"
```

**Comment by jeremyd2019** [comment]
Windows has been providing `tar.exe` in system32 for a while now.  makepkg should generally be using `bsdtar` which is installed as part of `base`.  I have always seen MSYS2 tar installed too, maybe via `base-devel`?

**Comment by galeksandrp** [comment]
@Biswa96 Actually, I noticed `tar.exe` in `Windows.old`, indicating that `tar.exe` existed in `Windows 10`.

@jeremyd2019 Well, `makepkg-mingw` is using `tar`. And yes, `base-devel` contains `tar`.

**Comment by mati865** [comment]
Makepkg should be using bsdtar. Which package did you try to build?

Tar is present in Win 10 and there are no problems with that:
```
$ where tar
D:\msys64\usr\bin\tar.exe
C:\Windows\System32\tar.exe
```

**Comment by galeksandrp** [comment]
@mati865 `mingw-w64-x86_64-libvirt`.

**Comment by jeremyd2019** [comment]
> @jeremyd2019 Well, `makepkg-mingw` is using `tar`. And yes, `base-devel` contains `tar`.
> 
> Just surprised. Seems everyone installing `base-devel` first thing. If that's expected, well, I'm OK with it.

I thought packages in `base-devel` could be assumed to be present by PKGBUILDs (ie, not explicitly makedepending on them.  I could be wrong though.
