### ISSUE TITLE
llvm-windres fails on gtk2

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#9130]
@mstorsjo not sure the best place to report this but this seemed to work for the last one

Command: `windres --input gtk-update-icon-cache.rc --output gtk-update-icon-cache_manifest.o --output-format=coff`
Contents of `gtk-update-icon-cache.rc`:
```
#include <winbase.h>
CREATEPROCESS_MANIFEST_RESOURCE_ID RT_MANIFEST gtk-update-icon-cache.exe.manifest

```

Error:
```
llvm-rc: Error in RT_MANIFEST statement (ID CREATEPROCESS_MANIFEST_RESOURCE_ID):

error : file not found : gtk
```

Not including contents of manifest as it is not even being read.

**Comment by jeremyd2019** [comment]
This seems to come down to "why didn't they quote that filename?"  It succeeds if the manifest filename is quoted.

**Comment by jeremyd2019** [comment]
I'm going to try patching the makefile that generates that rc file to include quotes

**Comment by mstorsjo** [comment]
That fix sounds good to me.

FWIW, I did add support to llvm-rc to allow including files that are specified without quotes a long time ago, https://reviews.llvm.org/D46511, but I think filenames with dashes couldn't easily be handled there, and fixing that would probably require disproportionally large changes to the parser/lexer for something that is undocumented syntax for at least MS rc.exe.

**Comment by revelator** [comment]
sounds good :)

**Comment by jeremyd2019** [comment]
OK, I just wanted to make sure to point out things that work in windres but not in llvm-windres to you.

**Comment by mstorsjo** [comment]
> OK, I just wanted to make sure to point out things that work in windres but not in llvm-windres to you.

Yes - the syntax of including files without quoting their filenames work in both GNU windres and MS rc.exe. But I think it's an undocumented feature in MS rc.exe - if it'd be a documented feature, then a much more invasive patch fixing all the corner cases (e.g. filenames that contain dashes) would probably be acceptable in llvm-rc though.
