### ISSUE TITLE
harfbuzz 2.8.2 update broke Qt applications

### ISSUE THREAD

**Issue by omichel** [msys2/MINGW-packages#9136]
Our Qt-based application (Webots) was broken after the harfbuzz update in #9121. If I replace the current `/mingw64/bin/libharfbuzz-0.dll` (2.8.2) with the one from the [previous version](https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-harfbuzz-2.8.1-1-any.pkg.tar.zst) (2.8.1), it works again.

**Comment by Biswa96** [comment]
There is a mass rebuild going on for python update. Let wait and pray for some time.

**Comment by lazka** [comment]
What's the problem?

**Comment by lazka** [comment]
Reverted, I hope.

**Comment by omichel** [comment]
> What's the problem?

It simply crashes.

**Comment by omichel** [comment]
> Reverted, I hope.

Yes, it works again now. Thank you!

**Comment by elieux** [comment]
Looks like the issue is [Harfbuzz removing exported symbols](https://github.com/harfbuzz/harfbuzz/commit/b2070a509c6aabc5a275749979d140f8d78206e6#diff-0ed175486367eab57a67582c28e91f0f01412c0b1686f717427c940aa18ac560) while our DLLs still import those symbols.

**Comment by elieux** [comment]
List of dependents found so far:

- libgeany-0.dll
- libopencv_freetype452.dll
- Qt5Gui.dll

**Comment by elieux** [comment]
Dependents of harbuzz to check:

- [ ] adwaita-icon-theme
- [ ] appstream-glib
- [ ] cairo
- [ ] desktop-file-utils
- [ ] emacs
- [ ] evince
- [ ] ffmpeg
- [ ] ffms2
- [ ] fontconfig
- [ ] freetype
- [ ] frei0r-plugins
- [x] geany **NEEDS REBUILD**
- [ ] geany-plugins
- [ ] geoclue
- [ ] ghostscript
- [ ] graphviz
- [ ] gspell
- [ ] gst-plugins-base
- [ ] gtk2
- [ ] gtk3
- [ ] gtk-engine-unico
- [ ] gtkglext
- [ ] gtksourceview3
- [ ] gtksourceview4
- [ ] gtkspell
- [ ] gtkspell3
- [ ] gtk-update-icon-cache
- [ ] harfbuzz
- [ ] imagemagick
- [ ] libass
- [ ] libbluray
- [ ] libcaca
- [ ] libgd
- [ ] libglade
- [ ] libgxps
- [ ] libraqm
- [ ] librsvg
- [ ] libspectre
- [ ] libwmf
- [ ] meld3
- [ ] mpv
- [ ] ogre3d
- [x] opencv **NEEDS REBUILD**
- [ ] pango
- [ ] pinentry
- [ ] poppler
- [ ] python-cairo
- [ ] python-gobject
- [ ] qbs
- [ ] qca-qt5
- [x] qt5 **NEEDS REBUILD**
- [ ] qt-creator
- [ ] quassel
- [ ] scite
- [ ] scite-defaults
- [ ] snorenotify
- [ ] sonnet-qt5
- [ ] tesseract-ocr
- [ ] ttf-dejavu
- [ ] vala
- [ ] vapoursynth
- [ ] vlc
- [ ] webkitgtk2
- [ ] webkitgtk3
- [ ] x264

Special consideration owed to:

- [ ] libsynctex
- [ ] magnum-plugins
- [ ] openscad
- [ ] qt5-debug
- [ ] texlive-bin
- [ ] ttfautohint
- [ ] wt

**Comment by Biswa96** [comment]
Many packages were rebuild. Is this still an issue now?

**Comment by omichel** [comment]
It work fine now. No issue any more.
