### ISSUE TITLE
pacman unable to update -- msys2 fails to connect to interent

### ISSUE THREAD

**Issue by manugoswami** [msys2/MINGW-packages#9137]
Hi developers,

pacman fails to connect to internet.  Other softwares and browsers are able to do the same.

Please advise urgently how to give internet access to msys2. (Given all rights in firewall to msys2 still no update).

Very bad setup from msys2. 

Warm Regards,
Manu

**Comment by umarcor** [comment]
> Please advise urgently
> 
> Very bad setup from msys2.

- [How To Ask Questions The Smart Way by Eric Steven Raymond](http://www.catb.org/~esr/faqs/smart-questions.html)
  - [Don't rush to claim that you have found a bug](http://www.catb.org/~esr/faqs/smart-questions.html#idm368)
  - [Describe the problem's symptoms, not your guesses](http://www.catb.org/~esr/faqs/smart-questions.html#symptoms)
  - [Don't flag your question as “Urgent”, even if it is for you](http://www.catb.org/~esr/faqs/smart-questions.html#urgent)

**Comment by manugoswami** [comment]
********************************** U R G E N T *****************************************************

Hi developers,

Please inform how to know which packages to download for installing. For example how to know which packages to download to install gcc or python?

at least this information please share quickly.

Warm Regrds,

Manu

**Comment by umarcor** [comment]
> ********************************** U R G E N T *****************************************************

> Please inform how to know which packages to download for installing. For example how to know which packages to download to install gcc or python?
> 
> at least this information please share quickly.

Please, see the reference provided above:

> * [How To Ask Questions The Smart Way by Eric Steven Raymond](http://www.catb.org/~esr/faqs/smart-questions.html)
>   * [Don't flag your question as “Urgent”, even if it is for you](http://www.catb.org/~esr/faqs/smart-questions.html#urgent)

From [Be precise and informative about your problem](http://www.catb.org/~esr/faqs/smart-questions.html#beprecise) (bolds added by me):

> * Describe the symptoms of your problem or bug carefully and clearly.
> * Describe the environment in which it occurs (machine, OS, application, whatever).
> * **Describe the research you did to try and understand the problem before you asked the question**.
> * **Describe the diagnostic steps you took to try and pin down the problem yourself before you asked the question**.
> * Describe any possibly relevant recent changes in your computer or software configuration.
> * **If at all possible, provide a way to reproduce the problem in a controlled environment**. 

* [msys2.org: Package Management](https://www.msys2.org/docs/package-management/)
