### ISSUE TITLE
After recent update qt5 applications won't start anymore

### ISSUE THREAD

**Issue by ArrSeaJay** [msys2/MINGW-packages#9138]
## Describe the issue

After a recent update no Qt5 application is starting due to the following error:
"The procedure entry point _ZdaPv could not be located in the dynamic link library C:\msys64\mingw64\bin\Qt5Gui.dll."

## Steps to Reproduce the Problem

1. Run 'assistent.exe' from qt5 for instance
2. The above mentioned message pops up in a message box.

## Additional Context:

qt5 package:
Name            : mingw-w64-x86_64-qt5
Version         : 5.15.2-8

Tried on 2 different windows systems. Windows 10 Enterprise 20H2 build 19042.1052 and Windows 10 Home 2004 build 19041.1083

**Comment by Biswa96** [comment]
There is a mass rebuild going on for python update. Tracking it here https://github.com/msys2/MINGW-packages/issues/9136

**Comment by lazka** [comment]
Can you try again after a `pacman -Syuu`?

**Comment by ArrSeaJay** [comment]
Works after update. Thanks!
