### ISSUE TITLE
qemu-system-arm segfaults: can't find libzstd.dll

### ISSUE THREAD

**Issue by BrendanSimon** [msys2/MINGW-packages#9147]
$ /c/msys64/mingw64/bin/qemu-system-arm.exe --help
C:/msys64/mingw64/lib/qemu/qemu-system-arm.exe: error while loading shared libraries: libzstd.dll: cannot open shared object file: No such file or directory

$ find /c/msys64 -name "libzstd.dll"
/c/msys64/mingw64/bin/libzstd.dll

Is there possibly a path or environment variable issue?  Or a build bug?

**Comment by ZachBacon** [comment]
probably needs a rebuild

**Comment by BrendanSimon** [comment]
I also just discovered the ucrt environment and thought I'd give that a crack -- unfortunately that too had the same issue.

$ /ucrt64/bin/qemu-system-arm.exe --help
C:/msys64/ucrt64/lib/qemu/qemu-system-arm.exe: error while loading shared libraries: libzstd.dll: cannot open shared object file: No such file or directory

**Comment by jeremyd2019** [comment]
the report of which library fails to load has been known to lie.  Try using ntldd (mingw-w64-*-ntldd)

**Comment by BrendanSimon** [comment]
Not sure how to use "mingw-w64-*-ntldd".

I installed with `pacboy sync ntldd:x"

$ /mingw64/bin/ntldd.exe -R /mingw64/bin/qemu-system-arm.exe
C:/msys64/mingw64/bin/qemu-system-arm.exe: not found

**Comment by BrendanSimon** [comment]
I tried a rebuild using the instructions here:

https://www.msys2.org/wiki/Creating-Packages/

It fails to build :(

==> Verifying source file signatures with gpg...
    qemu-6.0.0.tar.xz ... FAILED (unknown public key 3353C9CEF108B584)
==> ERROR: One or more PGP signatures could not be verified!

**Comment by BrendanSimon** [comment]
`--skipinteg` is getting further ...

**Comment by jeremyd2019** [comment]
the missing dll is `libspice-server-1.dll`, part of `mingw-w64-x86_64-spice` package.  I guess mingw-w64-qemu needs to declare a dependency on that package.

**Comment by jeremyd2019** [comment]
It seems to be declared an optional dependency, but it seems a little more than optional.

**Comment by BrendanSimon** [comment]
I already have that installed.  I installed again, but still get the same error.  Must be another package perhaps ??

```
$ pacboy sync spice:x
warning: mingw-w64-x86_64-spice-0.15.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-spice-0.15.0-1

Total Installed Size:  2.08 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                                                                [#################################################################] 100%
(1/1) checking package integrity                                                                              [#################################################################] 100%
(1/1) loading package files                                                                                   [#################################################################] 100%
(1/1) checking for file conflicts                                                                             [#################################################################] 100%
(1/1) checking available disk space                                                                           [#################################################################] 100%
:: Processing package changes...
(1/1) reinstalling mingw-w64-x86_64-spice                                                                     [#################################################################] 100%


$ /mingw64/bin/qemu-system-arm.exe --help
C:/msys64/mingw64/lib/qemu/qemu-system-arm.exe: error while loading shared libraries: libzstd.dll: cannot open shared object file: No such file or directory
```

**Comment by jeremyd2019** [comment]
that is what was missing for me.  try `ntldd /mingw64/lib/qemu/qemu-system-arm.exe` and look for something missing

**Comment by BrendanSimon** [comment]
Actually, I was running from an msys shell and i get the errror.
If I run from an mingw64 shell then the error is not present.

```
brend@DESKTOP-NOJ2OKH MSYS ~
$ /mingw64/bin/qemu-system-arm.exe --version
C:/msys64/mingw64/lib/qemu/qemu-system-arm.exe: error while loading shared libraries: libzstd.dll: cannot open shared object file: No such file or directory
```

```
brend@DESKTOP-NOJ2OKH MINGW64 ~
$ qemu-system-arm.exe --version
QEMU emulator version 6.0.0
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
```

**Comment by jeremyd2019** [comment]
I guess that's a side-effect of the fact that `/mingw64/bin/qemu-system-arm.exe` is really a shell script wrapper that calls the real exes in `/mingw64/lib/qemu/`.  If `/mingw64/bin` is not on the path, the Windows default of looking in the same directory as the exe for the dll search path won't happen to save you like it would for exes in `/mingw64/bin`

**Comment by BrendanSimon** [comment]
ok.  not sure if that is bug/issue that needs to be addressed or whether it's normal experience.  I would say it's and issue but I'll let the maintainers decide ;-)

**Comment by jeremyd2019** [comment]
I think there is definitely an issue that the optdepends for spice needs to be promoted to a depends, but as for the path issue I don't know.  Should be easy enough to add `/mingw64/bin` to the shell wrapper's path, but I still don't like the shell script named `.exe`, seems like a good way to confuse Windows (good luck trying to make a shortcut to it)

**Comment by jeremyd2019** [comment]
The missing spice dll has been fixed now.  It looks like a different file layout is in the works for 6.1.0 that should help with the path issue too
