### ISSUE TITLE
Unable to install scikit-learn python package using mingw64 command line

### ISSUE THREAD

**Issue by akashdiphazra** [msys2/MINGW-packages#9153]
![image](https://user-images.githubusercontent.com/61003681/125958522-378afe7b-49ac-4706-929b-9709a58a3fee.png)

![image](https://user-images.githubusercontent.com/61003681/125958601-d0cfe429-5004-4d18-a043-9934c3bcfcd8.png)

**Comment by kmilos** [comment]
Both numpy and scikit-learn are available (as well as more recent pip) through the repo using pacman, please try using those.

**Comment by akashdiphazra** [comment]
Install python from source worked closing the issue.
