### ISSUE TITLE
Bump glib to 2.69.0?

### ISSUE THREAD

**Issue by Jehan** [msys2/MINGW-packages#9154]
Hi!

Just a small report to raise attention to the existence of glib 2.69.0.

This version brings a huuuge improvement in glib for Windows, which is getting rid of some usage of win32 API which could make an application hang for a long time (I am talking up to minutes, if not a dozen of minutes, according to what some people reported in GIMP, when opening file dialogs).

The corresponding fix is in 2.69.0 but not in any 2.68.x.

Alternatively (if for some reason 2.69.0 brings issues), you can build 2.68.x with patches from https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2020

It's fine too!
Thanks. 🙂

**Comment by lazka** [comment]
backporting the patch is definitely preferred

**Comment by Jehan** [comment]
Thanks!
