### ISSUE TITLE
lld 12.0.1-1: only includes data symbols in import lib for exe

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#9163]
PostgreSQL uses the following command to link their exe:
```
postgres: $(OBJS) $(WIN32RES)
        $(CC) $(CFLAGS) $(call expand_subsys,$(OBJS)) $(WIN32RES) $(LDFLAGS) $(LDFLAGS_EX) -Wl,--stack,$(WIN32_STACK_RLIMIT) -Wl,--export-all-symbols -Wl,--out-implib=libpostgres.dll.a $(LIBS) -o $@$(X)
```

First, I had to change `-Wl,--stack=` to `-Wl,--stack,`  Now, I am seeing the generated libpostgres.dll.a only seems to contain data symbols and no functions.

`-Wl,-Xlink=-linkrepro:.` output
[repro.tar.gz](https://github.com/msys2/MINGW-packages/files/6835367/repro.tar.gz)

`nm -B` output for libpostgres.dll.a
[libpostgres.dll.a.nmB.txt](https://github.com/msys2/MINGW-packages/files/6835368/libpostgres.dll.a.nmB.txt)

`nm -B` output for postgres.exe
[postgres.exe.nmB.txt](https://github.com/msys2/MINGW-packages/files/6835369/postgres.exe.nmB.txt)

/cc @mstorsjo 

Oh, this was on x86_64 in case that matters.

**Comment by jeremyd2019** [comment]
It looks like postgres is only explicitly using dllexport on their data symbols. and relying on `--export-all-symbols` to export the functions.

**Comment by mstorsjo** [comment]
> It looks like postgres is only explicitly using dllexport on their data symbols. and relying on `--export-all-symbols` to export the functions.

Hmm, that option is supposed to work: https://github.com/llvm/llvm-project/blob/main/lld/COFF/Driver.cpp#L1214-L1199

Thanks for the repro, I can try it later.

**Comment by mstorsjo** [comment]
Oh, I see - the config->dll flag not being set inhibits the export all behavior. That should be an easy fix if you want to try your hand at it :-)

**Comment by jeremyd2019** [comment]
I'd only be concerned that there was some reason I'm not aware of why that check was added.  Just that it didn't occur to whoever put it there that exes would try to export symbols?

**Comment by mstorsjo** [comment]
> I'd only be concerned that there was some reason I'm not aware of why that check was added. Just that it didn't occur to whoever put it there that exes would try to export symbols? Maybe what they _meant_ to do was put that inside the
> `if (!args.hasArg(OPT_export_all_symbols))`

Exactly, that should do the trick here. I think I’m the one who wrote that code, and this combination didn’t come to mind.

Such a patch should be straightforward to do, but it needs a small testcase to be committable upstream.

**Comment by jeremyd2019** [comment]
I'd need some help with the testcase, not familiar with how they do things there

**Comment by jeremyd2019** [comment]
BTW, should I be using llvm's bugzilla instead for these sorts of things?  I tend to prefer github, but it would probably be better to be able to cite a bug in future

**Comment by mstorsjo** [comment]
> BTW, should I be using llvm's bugzilla instead for these sorts of things? I tend to prefer github, but it would probably be better to be able to cite a bug in future

No big difference for me, although if it needs to involve more people from the LLVM side it might be nice to have an entry in their bugzilla.

> I'd need some help with the testcase, not familiar with how they do things there

Ok, I'll make it. Overall, for things like these, look for an existing test in `lld/test/COFF` that does something roughly similar to what you want to test, make a copy of it (or add to it) and run it with `bin/llvm-lit -a path/to/lld/test/COFF/testcase.s` (or `python bin/llvm-lit.py` on non-unix).

**Comment by mstorsjo** [comment]
> > BTW, should I be using llvm's bugzilla instead for these sorts of things? I tend to prefer github, but it would probably be better to be able to cite a bug in future
> 
> No big difference for me, although if it needs to involve more people from the LLVM side it might be nice to have an entry in their bugzilla.
> 
> > I'd need some help with the testcase, not familiar with how they do things there
> 
> Ok, I'll make it. Overall, for things like these, look for an existing test in `lld/test/COFF` that does something roughly similar to what you want to test, make a copy of it (or add to it) and run it with `bin/llvm-lit -a path/to/lld/test/COFF/testcase.s` (or `python bin/llvm-lit.py` on non-unix), and e.g. `bin/llvm-lit -s path/to/lld/test/COFF` to run all COFF tests, and `ninja check-lld` to run all of if (including the mingw/elf/wasm/macho ones).

**Comment by jeremyd2019** [comment]
https://reviews.llvm.org/D106245

**Comment by mstorsjo** [comment]
FWIW I didn't test with the repro package that you provided, but from our discussion and from reading the code, it seems like this would fix the issue. Feel free to comment on the phab review, it's a trivial enough change that I think it'd be ok to have someone of you guys do the approval (if it looks like it fixes the issue for you) :-)

**Comment by mati865** [comment]
I can quickly test it once I get my internet connection back - there were intensive storms in central Europe this week.

**Comment by jeremyd2019** [comment]
That seems to have fixed postgres.exe.  Now I'm onto another error on another dll, where the def file says `DllRegisterServer@0` and lld-link is reporting that undefined, as this is x86_64 and there is no stdcall mangling.

**Comment by jeremyd2019** [comment]
Oops, they already have a comment about that in their README, so there's something going wrong with their build system, not lld.
