### ISSUE TITLE
nextpnr: malformed rc file

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#9180]
nextpnr fails building on clang64 with error:
```
/C/msys64/clang64/bin/windres.exe -O coff -DNEXTPNR_NAMESPACE=nextpnr_ice40 -DWITH_HEAP -I /T/mingw-w64-nextpnr/src/nextpnr/common -I /T/mingw-w64-nextpnr/src/nextpnr/json -I /T/mingw-w64-nextpnr/src/nextpnr/frontend -I /T/mingw-w64-nextpnr/src/nextpnr/3rdparty/json11 -I /T/mingw-w64-nextpnr/src/nextpnr/3rdparty/pybind11/include -I /C/msys64/clang64/include -I /C/msys64/clang64/include/python3.9 -I /C/msys64/clang64/include/eigen3 -I /T/mingw-w64-nextpnr/src/nextpnr/ice40  /T/mingw-w64-nextpnr/src/nextpnr/ice40/resource/chipdb.rc CMakeFiles/chipdb-ice40.dir/ice40/resource/chipdb.rc.obj
llvm-rc: Error parsing file: Integer invalid or too large: 1k
```

The rc file in question appears to be malformed, missing `\n`s at least:
```rc
ice40/chipdb-384.bin RCDATA "T:/mingw-w64-nextpnr/src/nextpnr/ice40/chipdb/chipdb-384.bin"ice40/chipdb-1k.bin RCDATA "T:/mingw-w64-nextpnr/src/nextpnr/ice40/chipdb/chipdb-1k.bin"ice40/chipdb-5k.bin RCDATA "T:/mingw-w64-nextpnr/src/nextpnr/ice40/chipdb/chipdb-5k.bin"ice40/chipdb-u4k.bin RCDATA "T:/mingw-w64-nextpnr/src/nextpnr/ice40/chipdb/chipdb-u4k.bin"ice40/chipdb-8k.bin RCDATA "T:/mingw-w64-nextpnr/src/nextpnr/ice40/chipdb/chipdb-8k.bin"
```

I think we also already determined that unquoted dashes aren't appreciated by llvm-windres either.

**Comment by jeremyd2019** [comment]
llvm-windres seems to want really want the resource id to be an integer, not a "Unique name or a 16-bit unsigned integer value that identifies the resource." @mstorsjo ?

**Comment by jeremyd2019** [comment]
Even quoted, it says `llvm-rc: Error parsing file: expected int or identifier, got "ice40/chipdb-384.bin"`.  I swear I did something like this in MS rc.exe in the past...

**Comment by mstorsjo** [comment]
Yep, this seems to be tricky. Quoting the string isn't enough, as quotes don't count as delimiters here.

E.g. this example with MS rc.exe:
```
$ cat test.rc
"fooname" 24
BEGIN
  "contents"
END
$ rc test.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384 
Copyright (C) Microsoft Corporation.  All rights reserved.

$ llvm-readobj test.res
Resource type (int): MANIFEST (ID 24)
Resource name (string): "FOONAME"
Data version: 0
Memory flags: 0x30
Language ID: 1033
Version (major): 0 
Version (minor): 0
Characteristics: 0
Data size: 8
Data:: (63 6F 6E 74 65 6E 74 73)
```

So here the enclosing `"` end up as part of the resource name string (if I leave them out, I get plain `Resource name (string): FOONAME`).

It would seem that this indeed is a hole in llvm-rc's parser that would need to be plugged, and fixing it might also fix including unquoted filenames with dashes. Not sure how easy it is though. In the best case it might be not too hard, but in worst case it could be messy.

I think this (plus the case of unquoted filenames with dashes) might be good to have on the llvm bugtracker for llvm-rc, for more visibility as we're aware of the issues but don't have a good fix for now.

**Comment by jeremyd2019** [comment]
I saw this comment:
https://github.com/llvm/llvm-project/blob/main/llvm/tools/llvm-rc/ResourceScriptParser.cpp#L254-L255
```c++
  // We suggest that the correct resource name or type should be either an
  // identifier or an integer. The original RC tool is much more liberal.
```

**Comment by mstorsjo** [comment]
In the simplest form, I think this might fix the issue:

```
diff --git a/llvm/tools/llvm-rc/ResourceScriptToken.cpp b/llvm/tools/llvm-rc/ResourceScriptToken.cpp
index 6ce75f7e4bbb..a8f40abdf8a6 100644
--- a/llvm/tools/llvm-rc/ResourceScriptToken.cpp
+++ b/llvm/tools/llvm-rc/ResourceScriptToken.cpp
@@ -288,7 +288,7 @@ bool Tokenizer::canContinueIdentifier() const {
   assert(!streamEof());
   const char CurChar = Data[Pos];
   return std::isalnum(CurChar) || CurChar == '_' || CurChar == '.' ||
-         CurChar == '/' || CurChar == '\\';
+         CurChar == '/' || CurChar == '\\' || CurChar == '-';
 }
  
 bool Tokenizer::canStartInt() const {
```

Alternatively, there could be some logic in readTypeOrName or readFilename to join multiple tokens if they're exactly consecutive in the source file, with no whitespace inbetween, but I'm not sure if that's worth the distinction. That change in itself doesn't break any of the existing testcases though, so it might be tolerable.

If you have a go at it, post a patch with me and amccarth as reviewers. (I might be able to have a look in a couple days. Next week, on 27th, LLVM 13.0 is branched off - but minor fixes can still be backported a couple weeks after that.)

**Comment by jeremyd2019** [comment]
nextpnr successfully built with #9224, even with its lack of newlines
