### ISSUE TITLE
[avr-gcc] mingw-w64-i686-avr-toolchain fails to install: Maximum file size exceeded

### ISSUE THREAD

**Issue by maxgerhardt** [msys2/MINGW-packages#9183]
## Describe the issue

Installing `mingw-w64-i686-avr-toolchain` via `pacman` gives an error.

## Steps to Reproduce the Problem

1. Start the MSYS2 MinGW 32-bit shortcut
2. Execute `pacman -S mingw-w64-i686-avr-toolchain`

```
$ pacman -S mingw-w64-i686-avr-toolchain  -v
Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : mingw-w64-i686-avr-toolchain
:: There are 4 members in group mingw-w64-i686-avr-toolchain:
:: Repository mingw32
   1) mingw-w64-i686-avr-binutils  2) mingw-w64-i686-avr-gcc  3) mingw-w64-i686-avr-gdb  4) mingw-w64-i686-avr-libc

Enter a selection (default=all):
resolving dependencies...
looking for conflicting packages...

Packages (4) mingw-w64-i686-avr-binutils-2.35-3  mingw-w64-i686-avr-gcc-8.4.0-4  mingw-w64-i686-avr-gdb-9.2-3  mingw-w64-i686-avr-libc-2.0.0-3

Total Installed Size:  165.90 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 mingw-w64-i686-avr-binutils-2.35-3-any is up to date
 mingw-w64-i686-avr-gcc-8.4.0-4-any is up to date
 mingw-w64-i686-avr-gdb-9.2-3-any is up to date
 mingw-w64-i686-avr-libc-2.0.0-3-any is up to date
error: failed retrieving file 'mingw-w64-i686-avr-binutils-2.35-3-any.pkg.tar.zst?viasf=1.sig' from master.dl.sourceforge.net : Maximum file size exceeded
error: failed retrieving file 'mingw-w64-i686-avr-gcc-8.4.0-4-any.pkg.tar.zst?viasf=1.sig' from master.dl.sourceforge.net : Maximum file size exceeded
error: failed retrieving file 'mingw-w64-i686-avr-gdb-9.2-3-any.pkg.tar.zst?viasf=1.sig' from master.dl.sourceforge.net : Maximum file size exceeded
warning: too many errors from master.dl.sourceforge.net, skipping for the remainder of this transaction
error: failed retrieving file 'mingw-w64-i686-avr-libc-2.0.0-3-any.pkg.tar.zst?viasf=1.sig' from master.dl.sourceforge.net : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
```

## Additional Context: Operating System, Screenshots

Issue might be similiar in root cause to https://github.com/msys2/MSYS2-packages/issues/2564#issuecomment-871667703.

This issue does not occur with `pacman -S mingw-w64-x86_64-avr-toolchain` in the MinGW 64-bit environment.

- OS: Windows 10 Pro, x64, `Version 10.0.19043.1110` 

https://packages.msys2.org/package/mingw-w64-i686-avr-gcc?repo=mingw32 says @elieux signed it, maybe you can help?

**Comment by maxgerhardt** [comment]
Workaround similiar to linked issue: Build and install package yourself.

```sh
pacman -S  binutils make gcc
mkdir avr-binutils
cd avr-binutils/
wget https://raw.githubusercontent.com/msys2/MINGW-packages/master/mingw-w64-avr-binutils/PKGBUILD
wget https://raw.githubusercontent.com/msys2/MINGW-packages/master/mingw-w64-avr-binutils/01-avr-size.patch
gpg --recv-key 13FCEF89DD9E3C4F
gpg --lsign 13FCEF89DD9E3C4F
makepkg -sri

cd ..
mkdir avr-gcc
cd avr-gcc
wget https://raw.githubusercontent.com/msys2/MINGW-packages/master/mingw-w64-avr-gcc/PKGBUILD
makepkg -sri

cd ..
mkdir avr-libc
cd avr-libc
wget https://raw.githubusercontent.com/msys2/MINGW-packages/master/mingw-w64-avr-libc/PKGBUILD
nano PKGBUILD
# change  
#    ../configure \
#        --build=${MINGW_CHOST} \
#        --host=${_target} \
#        --prefix=${MINGW_PREFIX}
# to 
#    ../configure \
#        --build=${MINGW_CHOST} \
#        --host=${_target} \
#        --prefix=${MINGW_PREFIX} \
#       CC=avr-gcc \
#       CXX=avr-g++ 
# (otherwise can't find avr-gcc... CC and CXX env variable seem to be screwed)
makepkg -sri
```

Works for me.

**Comment by fauxpark** [comment]
Looks more like something's wrong with the mirror than an issue with the package itself - and it seems the packages you're trying to install are all up to date anyway.

**Comment by maxgerhardt** [comment]
Do you know how I can find the mirror that pacman uses to open an issue there? `-v` doesn't reveal it.

The "up to date" comes from running it a second time and it seing that it already downloaded the package files. That's not there on the first run.

**Comment by fauxpark** [comment]
Info on the mirror list can be found here: https://www.msys2.org/dev/mirrors/

**Comment by maxgerhardt** [comment]
Well doing

```
$ pacman -Sp mingw-w64-i686-avr-gcc
https://downloads.sourceforge.net/project/msys2/REPOS/MINGW/i686/mingw-w64-i686-avr-gcc-8.4.0-4-any.pkg.tar.zst
```
reveals that it comes from the official msys2 project, no secondary mirror, So Msys2 is broken?

**Comment by maxgerhardt** [comment]
When I manually download and unpack the above file..

```
$ tar xfv mingw-w64-i686-avr-gcc-8.4.0-4-any.pkg.tar.zst
$ cat .PKGINFO
# Generated by makepkg 5.2.2
pkgname = mingw-w64-i686-avr-gcc
pkgbase = mingw-w64-avr-gcc
pkgver = 8.4.0-4
pkgdesc = GNU compiler collection for AVR 8-bit and 32-bit microcontrollers (mingw-w64)
url = https://www.gnu.org/software/gcc/gcc.html
builddate = 1602486799
packager = CI (msys2-autobuild/ef81fcc3/301553843)
size = 109583571
..
```

It says `size = 109583571` but the `mingw-w64-i686-avr-gcc-8.4.0-4-any.pkg.tar.zst` file `14118853` bytes. Is that not the source of the error?

**Comment by lazka** [comment]
The sourceforge mirror is currently broken because of a regression in pacman 6, see https://github.com/msys2/msys2-pacman/issues/1

**Comment by maxgerhardt** [comment]
Wow that was really it. Opening `/etc/pacman.d/mirrorlist.mingw32` and commenting out the first mirror in the list really makes it work.

```
$ cat /etc/pacman.d/mirrorlist.mingw32
##
## 32-bit Mingw-w64 repository mirrorlist
##

## Primary
## msys2.org
#Server = https://downloads.sourceforge.net/project/msys2/REPOS/MINGW/i686/
Server = https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/
```
How could this ever work before if Pacman is that broken o_o? 

In any case, closing since this is pacman issue tracked elsewhere.

**Comment by jeremyd2019** [comment]
Sourceforge mirror has issues.  Mirrorlists have been updated with new better options, but it looks like you still had an old version.  Even if you have updated, it may have installed the new mirrorlist with `.pacnew`.

**Comment by maxgerhardt** [comment]
You are right, there are `/etc/pacman.d/*.pacnew` files, I deleted the old version and removed the `*.pacnew` extension and did a `pacman -Syu`, now I'm all up-to-date again. Didn't know that thing about the packet manager, thanks!
