### ISSUE TITLE
[enet] Update 1.3.17 available

### ISSUE THREAD

**Issue by gk7huki** [msys2/MINGW-packages#9184]
The latest version of ENet is 1.3.17 which was released in November 2020. Please consider updating the `mingw-w64-enet` package.

**Comment by ZachBacon** [comment]
Feel free to submit a pull request should you feel inclined, otherwise you maybe waiting a little bit

**Comment by Biswa96** [comment]
Hi! @gk7huki Thank you for the report. I have sent a pull request to update enet package. Would you like to test the package from the GitHub Actions artifact in linked pull request?

**Comment by gk7huki** [comment]
> Hi! @gk7huki Thank you for the report. I have sent a pull request to update enet package. Would you like to test the package from the GitHub Actions artifact in linked pull request?

I've tested the mingw32 and mingw64 packages and they work fine. Thank you!

**Comment by Biswa96** [comment]
The package will be updated after some time. You can see the new package here https://packages.msys2.org/updates when it will arrive.
