### ISSUE TITLE
Mingw64\bin\python.exe Problem in Environment Variable

### ISSUE THREAD

**Issue by DGamer007** [msys2/MINGW-packages#9238]
I have installed msys2 for gcc and g++ compilers ( as described [Here](https://code.visualstudio.com/docs/languages/cpp#_example-install-mingwx64) ) and in order to achieve that I needed to add "Mingw64/bin" path to my system Environment variables.
But, I also have python installed on my machine and I need to access python through console but now If I write python in console it is accessing python.exe (which is inside of "MinGW64\bin" folder ) and through it I am not able to interpret my python script.
So, I was hoping if there is a work around or If I can just uninstall those python packages...

**Comment by Biswa96** [comment]
> in order to achieve that I needed to add "Mingw64/bin" path to my system Environment variables.

What do you want to achieve? Why do you need to add the path in system environment variables?

**Comment by DGamer007** [comment]
I added "MinGW64\bin" to system Environment variables 'coz I wanna use **g++** and **gcc** in terminal !
and I want to keep that path as it is and also want to get rid of the problem that I am getting when I try to access python from terminal.

**Comment by Biswa96** [comment]
Whatever you do, if two same program exist in $PATH there will be always an conflict.

**Comment by DGamer007** [comment]
I reordered paths in environmental variables and now I am getting what I needed.
Sorry if it was a silly question !
and Thanks for the help !

**Comment by revelator** [comment]
newer silly to ask questions :) how else will we learn.
