### ISSUE TITLE
ruby: STATUS_BAD_STACK on longjmp with clang64

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#9271]
The attempt to longjmp back to the _setjmpex at https://github.com/ruby/ruby/blob/378e8cdad69e6ba995a024da2957719789f0679e/thread.c#L823 is raising `STATUS_BAD_STACK` from `RtlUnwindEx`.

> An invalid or unaligned stack was encountered during an unwind operation.

In order to get ruby to not crash during its own bootstrapping with clang, I had to switch it from trying to use `__builtin_setjmp` to use mingw-w64's setjmp/longjmp, so this may be an issue on GCC if using UCRT's implementation.

**Comment by jeremyd2019** [comment]
This works with GCC UCRT64 when switched to use `setjmp` rather than `__builtin_setjmp`

**Comment by jeremyd2019** [comment]
Aha, https://github.com/msys2-contrib/mingw-w64/blob/master/mingw-w64-headers/crt/setjmp.h#L233-L240.  clang is using the mingw_getsp variant, which is returning the sp at the time, not the bp which is different (there's an alloca call earlier in the function).  Going to try enabling the `__builtin_frame_address` branch for clang, hopefully they implement that.

**Comment by jeremyd2019** [comment]
Yep that fixes it.  Time to email a patch to mingw-w64!

**Comment by jeremyd2019** [comment]
https://sourceforge.net/p/mingw-w64/mailman/message/37329802/

**Comment by Biswa96** [comment]
Love your explanation 😍

**Comment by jeremyd2019** [comment]
This was fixed upstream (mingw-w64/mingw-w64@1db0f476fbfdbb54dc089284fc278957c73cdd05 as github linked above).
