### ISSUE TITLE
qemu: can't get efi firmware to work with qemu-system-x86_64

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#9276]
I've tried mingw64 from the repo, and clang64 from #9201 and got the same results from both.

I'm trying to get qemu-system-x86_64 to use efi firmware.  
`qemu-system-x86_64 -drive if=pflash,format=raw,unit=0,readonly=on,file=$(cygpath -m /mingw64/lib/qemu/edk2-x86_64-secure-code.fd) -drive if=pflash,format=raw,unit=1,file=$(cygpath -m /mingw64/lib/qemu/edk2-i386-vars.fd)`

And all other variants I could think to try, sit at "Guest has not initialized the display (yet)."  There is also no output on serial that I can see.

@heljkon any x86_64 efi in your tests?

**Comment by jeremyd2019** [comment]
I was able to get it to work with the firmware files from https://packages.debian.org/experimental/all/ovmf/download so I guess it's something with the version bundled with qemu?

**Comment by jeremyd2019** [comment]
Oops, it does work with the "live" qemu mingw64 with both firmwares with `-M q35`, but not with #9201 clang64 with either firmware

**Comment by heljkon** [comment]
My tests include 3 uefi test cases:

- QemuAdvent 2014/08 (provides own firmware)
- QemuAdvent 2020/15 (provides own firmware)
- LiveDVD/Uefi (uses qemu provided firmware)

2014/08 and 2020/15 worked as expected with mingw-w64-x86_64-qemu-**6.0.91**-1-any.pkg.tar.zst

LiveDVD/Uefi worked as expected with mingw-w64-x86_64-qemu-**6.0.90.rc0**-1-any.pkg.tar.zst, but not with mingw-w64-x86_64-qemu-**6.0.91**-1-any.pkg.tar.zst

Executing LiveDVD/Uefi in combination with firmware of QemuAdvent 2014/08 worked well on mingw-w64-x86_64-qemu-6.0.91-1-any.pkg.tar.zst, even with `-accel whpx,kernel-irqchip=off` (which never worked for qemu provided firmware, because of `WHPX: Failed to emulate MMIO access with EmulatorReturnStatus: 2 WHPX: Failed to exec a virtual processor`)

So my conclusion at this point - I will do some more tests - is the same as yours: _it's something with the version bundled with qemu_

**Comment by jeremyd2019** [comment]
Well, at least it's not just me.  It turns out I needed to run on Linux anyway for what I wanted to do (testing swtpm against Windows 11).  I ran into similar issues on Linux when trying to use edk2-x86_64-secure-code.fd, but the non-secure version worked, so I'm probably doing something wrong with that (I was going for secure boot, but in the debian images that's a "vars" not a "code" difference).

**Comment by jeremyd2019** [comment]
> even with `-accel whpx,kernel-irqchip=off` (which never worked for qemu provided firmware, because of `WHPX: Failed to emulate MMIO access with EmulatorReturnStatus: 2 WHPX: Failed to exec a virtual processor`)

I thought that was just me, too.  I get those two messages and then qemu crashes (in `ucrtbase!abort`).

**Comment by heljkon** [comment]
I've compared the firmware files, which I've put to dirs clang64-6.0.90, clang64-6.0.91, mingw64-6.0.90, mingw64-6.0.91:

```
$ ls mingw64-6.0.90 mingw64-6.0.91 clang64-6.0.90 clang64-6.0.91
clang64-6.0.90:
edk2-aarch64-code.fd  edk2-arm-code.fd  edk2-arm-vars.fd  edk2-i386-code.fd  edk2-i386-secure-code.fd  edk
clang64-6.0.91:
edk2-aarch64-code.fd  edk2-arm-code.fd  edk2-arm-vars.fd  edk2-i386-code.fd  edk2-i386-secure-code.fd  edk
mingw64-6.0.90:
edk2-aarch64-code.fd  edk2-arm-code.fd  edk2-arm-vars.fd  edk2-i386-code.fd  edk2-i386-secure-code.fd  edk
mingw64-6.0.91:
edk2-aarch64-code.fd  edk2-arm-code.fd  edk2-arm-vars.fd  edk2-i386-code.fd  edk2-i386-secure-code.fd  edk
$ DIRS="mingw64-6.0.90 mingw64-6.0.91 clang64-6.0.90"                                                                                           
$ for DIR in $DIRS ; do echo $DIR ; for FD in $(cd clang64-6.0.91 ; ls *.fd) ; do if ! cmp clang64-6.0.91/$FD $DIR/$FD ; then echo "DIFFERS" ; fi ; done ; done
mingw64-6.0.90
mingw64-6.0.91
clang64-6.0.90
```
There is no difference between the qemu delivered firmware files. Neither 6.0.90 vs 6.0.91 nor mingw64 vs clang64!

So there must be a difference in qemu code between 6.0.90 and 6.0.91

**Comment by heljkon** [comment]
So we've got a new regression introduced with 6.0.91 (qemu-6.1.0-rc1) which did not occur in 6.0.90 (qemu-6.1.0-rc0)

Freezes occur reproducable when using a UEFI firmware without acceleration.

I created testcases using UEFI firmware provided by https://www.qemu-advent-calendar.org/2014/download/qemu-xmas-uefi-zork.tar.xz as well as by Qemu Tarball:

1. Qemu provided firmware as pflash
`qemu-system-x86_64 -drive file=/mingw64/share/qemu/edk2-x86_64-code.fd,if=pflash,format=raw,readonly=on`
2. QemuAdventcalendar provided firmware as pflash
`qemu-system-x86_64 -drive file=qemu-advent-calendar/2014/qemu-xmas-uefi-zork/OVMF-pure-efi.fd,if=pflash,format=raw,readonly=on`
3. QemuAdventcalendar provided firmware as bios
`qemu-system-x86_64 -bios qemu-advent-calendar/2014/qemu-xmas-uefi-zork/OVMF-pure-efi.fd`

Sadly I wasn't able to reproduce these issues after compiling 6.0.90 and 6.0.91 on Debian/Buster, so the issue in https://gitlab.com/qemu-project/qemu/-/issues will have the Label "Windows".

**Comment by heljkon** [comment]
For the failures like

```
$ qemu-system-x86_64 -accel whpx,kernel-irqchip=off \
	-drive file=/mingw64/share/qemu/edk2-x86_64-code.fd,if=pflash,format=raw,readonly=on
Windows Hypervisor Platform accelerator is operational
D:\msys64\mingw64\bin\qemu-system-x86_64.exe: WHPX: Failed to emulate MMIO access with EmulatorReturnStatus: 2
D:\msys64\mingw64\bin\qemu-system-x86_64.exe: WHPX: Failed to exec a virtual processor
```

I created issue https://gitlab.com/qemu-project/qemu/-/issues/513

**Comment by heljkon** [comment]
[Patch  24d84c7e queued for qemu-6.1.0-rc4](https://gitlab.com/qemu-project/qemu/-/commit/24d84c7e4806da0c362edd2ee76678f15becd17d) will solve [the UEFI issue without WHPX](https://gitlab.com/qemu-project/qemu/-/issues/512).

For [the UEFI issue with WHPX](https://gitlab.com/qemu-project/qemu/-/issues/513) instead of using 

```
cp /mingw64/share/qemu/edk2-i386-vars.fd ./
qemu-system-x86_64 \
 -drive file=/mingw64/share/qemu/edk2-x86_64-code.fd,if=pflash,format=raw,readonly=on \
 -drive file=edk2-i386-vars.fd,if=pflash,format=raw,readonly=off

```
use (as WA)
```
cat /mingw64/share/qemu/edk2-i386-vars.fd /mingw64/share/qemu/edk2-x86_64-code.fd > edk-x86_64.fd
qemu-system-x86_64 \
 -bios edk-x86_64.fd
```
BTW: IHMO it is rather a Windows than a Qemu issue

**Comment by jeremyd2019** [comment]
Your workaround of concatenating the vars and code images and passing that to `-bios` works with the edk2 shipped with qemu, but not with edk2 from Debian packages.  The version shipped with qemu does not seem to have secure boot, which Windows 11 setup is upset about (as well as lack of TPM emulation on Windows).  Setting `BypassSecureBootCheck` and `BypassTPMCheck` in `HKLM\SYSTEM\Setup\LabConfig` when booted from the Windows 11 iso lets it install with the qemu-provided edk2 though.

**Comment by jeremyd2019** [comment]
There is a pre-existing combined firmware file in the debian package under `usr/share/OVMF/OVMF.fd`.  This does work with `-bios`, but does not come with MS keys pre-enrolled for secure boot.  However, it seems that Windows 11 is satisfied that this firmware is *capable* of secure boot, even though it is not enabled or configured.

**Comment by ttlns** [comment]
> I was able to get it to work with the firmware files from https://packages.debian.org/experimental/all/ovmf/download (adding `-M q35, which i know I tried with the other firmware files) so I guess it's something with the version bundled with qemu?

https://packages.debian.org/experimental/all/ovmf/download  doesn't appear to exist anymore. For mysys2, the following currently works for me.
```bash
pacman -S mingw-w64-ucrt-x86_64-qemu bsdtar
curl -o ovmf.deb http://security.debian.org/debian-security/pool/updates/main/e/edk2/ovmf_2020.11-2+deb11u3_all.deb
bsdtar -xf ovmf.deb -C . --to-stdout data.tar.xz > ovmf.tar.xz
tar -xJf ovmf.tar.xz -C /
ls /usr/share/OVMF/OVMF_CODE.fd
```

**Comment by heljkon** [comment]
> For mysys2, the following currently works for me.

There's nothing wrong with the firmware. It's the firmware bundled with the QEMU sources and it works:

```
# Prepare firmware
cat /ucrt64/share/qemu/edk2-i386-vars.fd /ucrt64/share/qemu/edk2-x86_64-code.fd > edk2-x86_64.fd

# Execute VM
CD=openSUSE-Leap-15.3-GNOME-Live-x86_64-Media.iso
qemu-system-x86_64 \
 -M q35 \
 -m 1536 \
 -audiodev id=audio0,driver=dsound \
 -device ich9-intel-hda \
 -device hda-output,audiodev=audio0 \
 -usb \
 -device usb-tablet \
 -accel whpx,kernel-irqchip=off \
 -boot menu=on \
 -bios edk2-x86_64.fd \
 -drive id=cd0,if=none,file=$CD,format=raw,read-only=on \
 -device ide-cd,drive=cd0,bus=ide.0,bootindex=0
```
