### ISSUE TITLE
More glib2 patches

### ISSUE THREAD

**Issue by Jehan** [msys2/MINGW-packages#9283]
Hi all!

More Windows weirdness with [GIMP crashing when some images are opened in other software](https://gitlab.gnome.org/GNOME/gimp/-/issues/6780).

It turned out to be fixed with the following patches:
* https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2205
* https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2210

(especially the later, but the [dev advised to backport both](https://gitlab.gnome.org/GNOME/gimp/-/issues/6780#note_1230372))

Could these be included in glib build on MSYS2? Thanks a lot! 🙂

**Comment by lazka** [comment]
sounds good

**Comment by lb90** [comment]
Hi! I can make a PR

**Comment by lb90** [comment]
Mmh...or maybe we should backport https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2210 to [glib-2-68](https://gitlab.gnome.org/GNOME/glib/-/tree/glib-2-68) and wait for a point release?

**Comment by Biswa96** [comment]
In my opinion, waiting for a official release would be better.

**Comment by Jehan** [comment]
If it is near, I definitely agree. Is it? (real question, I have no idea)

Otherwise I know that we will want to rebuild it for our own installers, if GIMP release happens before GLib's. This is cumbersome when we have to patch the dependencies. I really prefer when we can fully rely on MSYS2. 😛

**Comment by lb90** [comment]
Even Inkscape needs that patches: https://gitlab.com/inkscape/inbox/-/issues/5249

I'm going to open a MR in GLib to backport the patches, I'll also ask the maintainers if they plan to make a new release soon

**Comment by lb90** [comment]
Opened backport MR: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2220

**Comment by lb90** [comment]
Hi, everyone! Here's the response by Philipp Whitnall about a new stable point release: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2220#note_1244923
