### ISSUE TITLE
clang: undefined symbol `std::__1::chrono::system_clock::from_time_t(long long)`

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#9285]
Got this while trying to build clang on clang32:

```
  lld-link: error: undefined symbol: std::__1::chrono::system_clock::from_time_t(long long)
  >>> referenced by libLLVMSupport.a(VirtualFileSystem.cpp.obj):(llvm::vfs::InMemoryFileSystem::addFile(llvm::Twine const&, long long, std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >, llvm::Optional<unsigned int>, llvm::Optional<unsigned int>, llvm::Optional<llvm::sys::fs::file_type>, llvm::Optional<llvm::sys::fs::perms>, llvm::vfs::detail::InMemoryFile const*))
  >>> referenced by libLLVMSupport.a(VirtualFileSystem.cpp.obj):(llvm::vfs::InMemoryFileSystem::addFile(llvm::Twine const&, long long, std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >, llvm::Optional<unsigned int>, llvm::Optional<unsigned int>, llvm::Optional<llvm::sys::fs::file_type>, llvm::Optional<llvm::sys::fs::perms>, llvm::vfs::detail::InMemoryFile const*))
```

Looks to be fallout from #9259 change in `time_t` from 32 to 64 bits.

**Comment by jeremyd2019** [comment]
This is a hairy one.  Building libc++ first, and installing it, results in clang itself not being able to run due to a missing export from libc++.dll.  This being c++, it should be theoretically possible to provide both 32 and 64-bit overloads for that function... Might try that tomorrow.

**Comment by jeremyd2019** [comment]
Decided to try that tonight, and it's getting farther...  maybe have a new clang built in the morning

**Comment by revelator** [comment]
yep also got this one, was starting to think oh hell no xD

**Comment by jeremyd2019** [comment]
well, it built last night, now trying to get it in a form that can be in the PKGBUILD.  For some reason it's refusing to use my alternate libc++.dll.a in cmake, even though if I copy/paste the failed command line it succeeds.  Given this is a hack anyway, might just update the files under `/clang32`

**Comment by jeremyd2019** [comment]
> For some reason it's refusing to use my alternate libc++.dll.a in cmake, even though if I copy/paste the failed command line it succeeds. Given this is a hack anyway, might just update the files under `/clang32`

Luckily I figured it out and didn't have to do anything that gross... Path conversion (or lack thereof).  Had to do `" -L$(cygpath -m ...)"`.

**Comment by revelator** [comment]
so new clang version comming up i guess :)

**Comment by revelator** [comment]
a few other packages are also hit by this change -> filezilla and pybindll so far.

**Comment by jeremyd2019** [comment]
not surprised.  I'm doing a grep through clang32 packages looking for potential trouble - either `time_t` in includes or `time_tEl` in bin or lib (that's part of the mangling of the problematic function in libc++).  Hitting quite a few.  And the time_t include grep doesn't necessarily catch consumers of problematic APIs only providers...

**Comment by revelator** [comment]
aye i suspect there might be quite a few, hopefully these will get fixed when we get clang32 building again.
