### ISSUE TITLE
clang32 packages with time_t references

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#9295]
I'm doing a grep through clang32 packages looking for potential trouble - either `time_t` in includes or `time_tEl` in bin or lib (that's part of the mangling of the problematic function in libc++).  Hitting quite a few.  And the time_t include grep doesn't necessarily catch consumers of problematic APIs only providers...

_Originally posted by @jeremyd2019 in https://github.com/msys2/MINGW-packages/issues/9285#issuecomment-893173343_

The actual mangled name for 32-bit time_t from libc++ is `__ZNSt3__16chrono12system_clock11from_time_tEl` (the last letter is `x` for 64-bit time_t)

<details>
<summary>Quick grep script</summary>

```bash
#!/bin/bash

for pkg in ../clang32mirror/clang32/*.pkg.tar.zst; do
        flag=
        mkdir t
        tar -C t -xf "$pkg"
        grep -sqr time_tEl t/clang32/bin t/clang32/lib && flag=y
        grep -sqrE '\<time_t\>' t/clang32/include t/clang32/i686-w64-mingw32/include && flag=y
        if [[ -n "$flag" ]]; then
                basename "$pkg"
        fi
        rm -rf t
done
```
</details>

## List of packages from grep

- [x] mingw-w64-clang-i686-apr-1.6.5-3-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-aria2-1.35.0-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-aribb24-1.0.3-4-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-assimp-5.0.1-9-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-aws-c-common-0.5.5-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-boost-1.75.0-6-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-catch-2.13.7-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-cgal-5.2-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-chicken-4.12.0-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-clang-12.0.1-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-clustal-omega-1.2.4-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-cmake-3.21.1-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-crypto++-8.4.0-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-curl-7.77.0-3-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-curl-gnutls-7.77.0-3-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-curl-winssl-7.77.0-3-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-drmingw-0.9.3-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-fltk-1.3.7-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-fmt-8.0.1-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-fxc2-git-r15.5ace4c2-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-geographiclib-1.52-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-glib2-2.68.3-3-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-glibmm-2.66.1-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-glibmm-2.68-2.68.1-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-glog-0.5.0-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-gnutls-3.7.2-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-gpgme-1.15.1-5-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-grpc-1.35.0-4-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-gsoap-2.8.113-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-gtest-1.11.0-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-headers-git-9.0.0.6270.0e0eed623-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-icestorm-0.0.r777.c495861-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-ldns-1.7.1-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-lfcbase-1.16.0-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libarchive-3.5.1-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libbotan-2.17.3-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libc++-12.0.1-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libcdio-2.1.0-4-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libelf-0.8.13-5-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libevent-2.1.12-3-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libfilezilla-0.25.0-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libgadu-1.12.2-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libgit2-1.1.1-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libicsneo-0.1.2-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libidn-1.36-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libmetalink-0.1.3-3-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libmongoose-6.14-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libnfs-4.0.0-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libnova-0.15.0-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libotr-4.1.1-4-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libpng-1.6.37-4-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libpsl-0.21.1-3-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libressl-3.1.1-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-librsync-2.3.2-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libsoup-2.72.0-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libssh2-1.9.0-4-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libssh2-wincng-1.9.0-4-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libtorrent-rasterbar-2.0.2-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libwebm-1.0.0.27-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libwebsockets-4.1.6-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libxlsxwriter-1.0.0-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-libzip-1.7.3-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-lldb-12.0.1-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-llvm-12.0.1-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-mbedtls-2.26.0-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-minizip2-2.7.0-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-neon-0.31.2-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-nettle-3.7.3-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-ninja-1.10.2-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-nspr-4.31-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-openssl-1.1.1.k-3-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-podofo-0.9.6-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-poppler-20.12.1-3-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-postgresql-13.1-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-protobuf-3.16.0-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-pupnp-1.14.6-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-pybind11-2.6.0-4-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-python-3.9.6-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-python-llvmlite-0.37.0rc2-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-qt5-5.15.2-8-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-qt5-debug-5.15.2-8-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-qt6-base-6.1.2-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-readline-8.0.004-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-shaderc-2021.1-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-shishi-git-r3591.ffe64562-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-spandsp-0.0.6-3-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-spdlog-1.9.1-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-starpu-1.3.8-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-tcl-8.6.11-3-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-thrift-0.13.0-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-tkimg-1.4.13-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-verilator-4.210-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-vrpn-7.34-7-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-wxmsw3.1-3.1.5-3-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-wxWidgets-3.0.5.1-5-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-xerces-c-3.2.3-3-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-xlsxio-0.2.29-1-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-xmlsec-1.2.31-2-any.pkg.tar.zst
- [x] mingw-w64-clang-i686-zziplib-0.13.72-3-any.pkg.tar.zst

**Comment by jeremyd2019** [comment]
It's looking like this ABI change is pretty pervasive...  I think the only 'correct' solution is to bump pkgrel on all affected packages, but the trouble is identifying them.  For example #9298 clang32 build failed due to a missing function that's probably got a `time_t` in it, and the library it's from made my `grep` list, but qbittorrent did not.  It would need to be rebuilt after `libtorrent-rasterbar` or it would then be broken.  Does that mean all packages with `time_t` and packages that depend on them?  What about indirect dependencies (a depends on b depends on c which is on the list, or even more levels)?  Is this going to spiral into most or all of the 1300-ish packages in clang32?

**Comment by jeremyd2019** [comment]
<details>
<summary>Packages with just `time_tEl` in bin or lib</summary>

```
mingw-w64-clang-i686-aria2-1.35.0-2-any.pkg.tar.zst
mingw-w64-clang-i686-assimp-5.0.1-9-any.pkg.tar.zst
mingw-w64-clang-i686-boost-1.75.0-6-any.pkg.tar.zst
mingw-w64-clang-i686-clang-12.0.1-2-any.pkg.tar.zst
mingw-w64-clang-i686-cmake-3.21.1-1-any.pkg.tar.zst
mingw-w64-clang-i686-drmingw-0.9.3-1-any.pkg.tar.zst
mingw-w64-clang-i686-fxc2-git-r15.5ace4c2-1-any.pkg.tar.zst
mingw-w64-clang-i686-grpc-1.35.0-4-any.pkg.tar.zst
mingw-w64-clang-i686-gtest-1.11.0-2-any.pkg.tar.zst
mingw-w64-clang-i686-icestorm-0.0.r777.c495861-2-any.pkg.tar.zst
mingw-w64-clang-i686-libbotan-2.17.3-2-any.pkg.tar.zst
mingw-w64-clang-i686-libc++-12.0.1-2-any.pkg.tar.zst
mingw-w64-clang-i686-libwebm-1.0.0.27-2-any.pkg.tar.zst
mingw-w64-clang-i686-lldb-12.0.1-2-any.pkg.tar.zst
mingw-w64-clang-i686-llvm-12.0.1-2-any.pkg.tar.zst
mingw-w64-clang-i686-ninja-1.10.2-1-any.pkg.tar.zst
mingw-w64-clang-i686-python-llvmlite-0.37.0rc2-1-any.pkg.tar.zst
mingw-w64-clang-i686-qt5-debug-5.15.2-8-any.pkg.tar.zst
mingw-w64-clang-i686-shaderc-2021.1-1-any.pkg.tar.zst
mingw-w64-clang-i686-verilator-4.210-1-any.pkg.tar.zst
```
</details>

**Comment by revelator** [comment]
jesus Oo

**Comment by revelator** [comment]
some of these packages actually build even with the new abi but a few of them end up broken because of it, filezilla for one.

**Comment by revelator** [comment]
strange thing filezilla is not even in the list but fails because a library export relies on the old form.

**Comment by revelator** [comment]
fz::datetime::datetime(long, fz::datetime::accuracy) <- fail here.

**Comment by jeremyd2019** [comment]
libfilezilla was in the first grep, that's probably the problem there...

**Comment by revelator** [comment]
aye neeed to rebuild libfilezilla and filezilla works again now.

**Comment by jeremyd2019** [comment]
Yep, it's going to be like that for all of these... And that's for the C++ mangled named.  Unmangled names will just silently misinterpret the args.

**Comment by Biswa96** [comment]
So, if a package is rebuilt it solves the clang32 time_t issue. No need to rebuild whole dependency chain, right?

**Comment by jeremyd2019** [comment]
not necessarily.  For the case of libtorrent-rasterbar and qbittorrent, if qbittorrent hadn't already been updated and failed, it would still need to be rebuilt, or it would fail at runtime with a missing export error.  This is for C++ name mangling.  Without that, there would be misinterpretation of arguments at runtime, possibly crashing or getting garbage time values.

**Comment by jeremyd2019** [comment]
the main problem is I don't know any good way to tell which dependencies of these listed packages need to be rebuilt and which do not.

**Comment by jeremyd2019** [comment]
I think I've gotten through all of these now, but only the last couple of batches did I follow down the dependency chain to see if they also needed to be rebuilt, so there is a possibility that some packages will remain broken.

**Comment by revelator** [comment]
does clang32 build again with the time_t changes now ?.

**Comment by jeremyd2019** [comment]
it should
