### ISSUE TITLE
smpeg does not build with clang

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#9317]
not related though i found out why smpeg does not build with clang also, it seems to rely on gcc as the build horse and does not link by default to the clang rt builtins library leading to undefined symbols. I got around it temporarily by doing this ->

```
build() {
  [[ -d ${srcdir}/build-${MINGW_CHOST} ]] && rm -rf ${srcdir}/build-${MINGW_CHOST}
  mkdir -p "${srcdir}/build-${MINGW_CHOST}"
  cd "${srcdir}/build-${MINGW_CHOST}/" 
  case "${CARCH}" in
    i686)
      export LIBS+=" -lclang_rt.builtins-i386"
    ;;

    x86_64)
      export LIBS+=" -lclang_rt.builtins-x86_64"
    ;;
  esac
  CFLAGS+=" -Wno-error=narrowing"
  ../${_realname}/configure \
    --prefix=${MINGW_PREFIX} \
    --build=${MINGW_CHOST} \
    --host=${MINGW_CHOST} \
    --target=${MINGW_CHOST} \
    --mandir=${MINGW_PREFIX}/share/man \
    --enable-shared \
    --enable-static

  make
}
```

_Originally posted by @revelator in https://github.com/msys2/MINGW-packages/pull/9309#issuecomment-894637478_

**Comment by jeremyd2019** [comment]
Yes, the real problem is that it needs to be `autoreconf`-ed, because that's a matter of libtool not properly handling compiler-rt.  But, when I try to `autoreconf` it, I get link errors that `WinMain` isn't found...  This is from `smpeg2` but it's a similar situation with both.  344e671bfef59a55d7f17a58125416f48957d6b0
```
  libtool: link: g++ -march=x86-64 -mtune=generic -O2 -pipe -Wno-error=narrowing -ID:/a/_temp/msys/msys64/mingw64/include/SDL2 -Dmain=SDL_main -DTHREADED_AUDIO -DNDEBUG -Wall -I.. -DNOCONTROLS -I../smpeg2 -I../smpeg2/audio -I../smpeg2/video -pipe -Wl,--dynamicbase -Wl,--high-entropy-va -Wl,--nxcompat -Wl,--default-image-base-high -o .libs/plaympeg.exe plaympeg.o -mwindows  ./.libs/libsmpeg2.a -LD:/a/_temp/msys/msys64/mingw64/lib -lmingw32 -lSDL2main -lSDL2
  D:/a/_temp/msys/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/a/_temp/msys/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): in function `main':
  C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
  collect2.exe: error: ld returned 1 exit status
```

**Comment by revelator** [comment]
hmm sounds like a bad flag somewhere, in gcc this usually happend when someone tried to link a console executable using the -mwin flag.

**Comment by jeremyd2019** [comment]
It should be coming from `-lSDL2main`

**Comment by revelator** [comment]
true so it is a bit weird.

**Comment by revelator** [comment]
wonder if running libtoolize before ./autogen.sh will get us what we need ?

**Comment by jeremyd2019** [comment]
I tried all kinds of things, nothing seemed to work

**Comment by revelator** [comment]
damn :/

**Comment by revelator** [comment]
well my little trick lets it build but it is not the most pretty way to do it...

**Comment by revelator** [comment]
fixed it, the autoconf macro AC_TYPE_SOCKLEN_T was used in a most inappropriate way causing autoreconf to fail, the fixed version here ->

```
dnl Work around the lack of certain typedefs.
AC_DEFUN(AC_TYPE_SOCKLEN_T,
[AC_CACHE_CHECK([for socklen_t], ac_cv_type_socklen_t,
[
  AC_TRY_COMPILE(
  [#include <sys/types.h>
   #include <sys/socket.h>],
  [socklen_t len = 42; return len;],
  ac_cv_type_socklen_t=yes,
  ac_cv_type_socklen_t=no)
])
  if test $ac_cv_type_socklen_t != yes; then
    AC_DEFINE(socklen_t, int)
  fi
])
```

then run autoreconf -fi --include=${MINGW_PREFIX}/share/aclocal/ to pick up the autotool commands from the dependencies and away we go :)

**Comment by revelator** [comment]
[mingw-w64-smpeg.zip](https://github.com/msys2/MINGW-packages/files/6950308/mingw-w64-smpeg.zip)
 could you try with this ?

**Comment by revelator** [comment]
ah crap no still fails with the winmain shite :S

**Comment by revelator** [comment]
looks like the problem is with our libtool macros, copying over the libtool macros from our version breaks it instantly with the winmain problem. not sure what the icculus guys did with the included libtool macros, but something is amiss here.
also seems they define AC_TYPE_SOCKLEN_T in socklen.m4 which was why it failed when using our own macros as we dont have that. A nasty fix and not one i would recommend is to place a dummy winmain somewhere in the source, in retrospect my original fix is better than that.

**Comment by revelator** [comment]
hehe my first assumption was right look at sdlconfig :) especially these lines ->

```
    --libs)
      echo -L${exec_prefix}/lib  -lmingw32 -lSDLmain -lSDL  -mwindows
      ;;
    --static-libs)
#    --libs|--static-libs)
      echo -L${exec_prefix}/lib  -lmingw32 -lSDLmain -lSDL  -mwindows  -liconv -lm -luser32 -lgdi32 -lwinmm -ldxguid
      ;;
```

sdl-config sets -mwindows flag and smpeg uses that not the pkgconfig files it seems sigh.

**Comment by revelator** [comment]
smpeg itself also sets it so we need to patch that out but the library itself builds fine now if i remove the -mwindows flag from sdl-config.

**Comment by jeremyd2019** [comment]
Isn't it *supposed* to be `-mwindows`?

**Comment by revelator** [comment]
;) i see the light has gone up hehe

**Comment by jeremyd2019** [comment]
no, this is really stupid.  WinMain is defined in libSDLmain.a, but once libtool is updated it gives the linker error that WinMain is not defined.  At first it looked like libtool was unhappy because -lSDLmain didn't have a shared version, but even disabling that it still is not working.

**Comment by revelator** [comment]
indeed it is a conundrum, the wicked thing is i can build the dll version if i remove the -mwindows flag but the tools still pull it in from one of the dependencies it seems.

**Comment by revelator** [comment]
only thing i can think of right now is that either clangs linker does something behind our backs that the binutils linker does not, or that the libtool macros included with the source have been modified.

**Comment by jeremyd2019** [comment]
no it has to be libtool, because it also breaks the gcc-based builds once libtool is updated

**Comment by revelator** [comment]
one step closer then :) guess we need a copy of the unmodified libtool-2.2 sources and make a diff to see what is what then.

**Comment by jeremyd2019** [comment]
This is very strange.  The exes are in .libs

**Comment by jeremyd2019** [comment]
I'm going to work on hacking up the libtool files they provide for clang, rather than updating them with ours

**Comment by jeremyd2019** [comment]
Unless you can figure out why updating libtool causes issues, #9327 should work (just applying the patch to their libtool copy to allow linking compiler_rt).
