### ISSUE TITLE
Incorrect sysconfig paths in mingw-w64-python

### ISSUE THREAD

**Issue by uranusjr** [msys2/MINGW-packages#9319]
MINGW’s `python` package incorrectly patches `platlib` and `purelib` in `sysconfig.py`:

```python
'nt': {
    'stdlib': '{installed_base}/lib/python{py_version_short}',
    'platstdlib': '{base}/lib/python{py_version_short}',
    'purelib': '{base}/lib/python{py_version_short}',
    'platlib': '{base}/lib/python{py_version_short}',
    'include': '{installed_base}/include/python{py_version_short}',
    'platinclude': '{installed_base}/include/python{py_version_short}',
    'scripts': '{base}/bin',
    'data': '{base}',
    },
```

This `{base}/lib/python{py_version_short}` is the location to the Python standard library (notice how they match `stdlib` and `platstdlib` above). `purelib` and `platlib` should instead point to locations to *third-party* packages. This was surfaced by pip’s recent attempt to switch from distutils to sysconfig (pypa/pip#10251); when run on MINGW’s `python`, pip is unable to install and locate user-installed packages with `sysconfig`.

By contrast, MINGW does supply a working patch to `distutils` (an older module pip is currently depending on but will move away [due to its deprecation](https://www.python.org/dev/peps/pep-0632/). `distutils.command.install` correctly defines paths like this, with a `site-packages` part in both `purelib` and `platlib` entries:

```python
WINDOWS_SCHEME = {
    'purelib': '$base/lib/python$py_version_short/site-packages',
    'platlib': '$base/lib/python$py_version_short/site-packages',
    'headers': '$base/include/python$py_version_short$abiflags/$dist_name',
    'scripts': '$base/bin',
    'data'   : '$base',
}
```

**Comment by lazka** [comment]
Thanks

**Comment by lazka** [comment]
Does the check in pip require the path separators to match as well (`/`vs `\\`)?

**Comment by lazka** [comment]
Never mind, I'll just fix that too

**Comment by uranusjr** [comment]
pip normalises the path separators so either `/` or `\` will be fine.

**Comment by lazka** [comment]
https://github.com/msys2-contrib/cpython-mingw/pull/35

**Comment by lazka** [comment]
This is now in the repo.

Thanks again for the report.
