### ISSUE TITLE
baobab cannot open directories

### ISSUE THREAD

**Issue by mugiseyebrows** [msys2/MINGW-packages#9343]
Context menu -> Open Folder raises "Failed to open file" "No application is registered as handling this file" on directories.

**Comment by Biswa96** [comment]
Any screenshot of that context menu and the error?

**Comment by mugiseyebrows** [comment]
![baobab_2021-08-10_22-06-01](https://user-images.githubusercontent.com/11173592/128920442-29a5b6a8-f5fa-483b-9189-5985f607fb18.png)
![baobab_2021-08-10_22-06-18](https://user-images.githubusercontent.com/11173592/128920499-74475d33-efa7-4875-9d1e-0665b118120c.png)
