### ISSUE TITLE
Significant difference in starpu package size: 193MB 1.3.8-2 vs. 6.27MB 1.3.8-1

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#9360]
Why is such a difference in the size of file libstarpu-1.3.a after rebuild starpu package? 

![image](https://user-images.githubusercontent.com/24394573/129172435-e7c208aa-b703-4383-96f1-88efd2f43ec0.png)

**Comment by lazka** [comment]
it's due to `libstarpu-1.3.a` increasing in size. No idea why.

**Comment by 3rav** [comment]
I must add that I got a similar size of the package (~200MB) when I built the package locally (on my PC), however the built package on github (pr) had a small size (until now)

**Comment by sthibaul** [comment]
Could you perhaps upload libstarpu-1.3.a somewhere so we can see what's in it?

**Comment by lazka** [comment]
It's all in the repo

**Comment by Biswa96** [comment]
Old ones can be downloaded from here https://repo.msys2.org/mingw/mingw64/

**Comment by sthibaul** [comment]
> It's all in the repo

Which repo, where? I know nothing about the distribution of mingw, and https://repo.msys2.org/mingw/mingw64/ doesn't seem to contain the actual archive files, only some .zst files.

**Comment by Biswa96** [comment]
> doesn't seem to contain the actual archive files, only some .zst files

Yes, those are the ZSTandard compressed package file. If you open/extract that package file you will see familiar folders (bin, lib etc.). The lib folder contains all the library files.

**Comment by sthibaul** [comment]
Ah, the result is 200MB long indeed. Seeing a 3MB .zst file I had assumed that that was way too small to be it.

**Comment by sthibaul** [comment]
So each .o file in the .a file is >= 1.1M, even `libstarpu_1.3_la-openmp_runtime_support.o` which contains actually nothing useful. I guess it's simply the debug symbols which for some reason got very big.

**Comment by sthibaul** [comment]
You could try to use `--disable-gdb` to drop the debugging information.

**Comment by 3rav** [comment]
Please see this draft PR: https://github.com/msys2/MINGW-packages/pull/9393
