### ISSUE TITLE
mingw-w64-x86_64-innoextract does literally nothing

### ISSUE THREAD

**Issue by rivanfebrian123** [msys2/MINGW-packages#9397]
## Describe the issue
![Capture](https://user-images.githubusercontent.com/6300910/129484138-7234cab8-760a-4c10-a707-e075661a5a07.PNG)

**EDIT:** So I have to install the UCRT one instead :/

## Steps to Reproduce the Problem
I'm not sure tho... I just installed it and then run it, and nothing happen

**Comment by Biswa96** [comment]
Rebuilding the package solves the issue. The package will be rebuilt soon.

**Comment by rivanfebrian123** [comment]
Sorry, could you reopen this issue please? It still doesn't work

**Comment by Biswa96** [comment]
Is there any error message? I have tried the new package and it works.

**Comment by rivanfebrian123** [comment]
Oh yeah, sorry. Didn't refresh the database yet :D

![Capture](https://user-images.githubusercontent.com/6300910/129618866-34d2c187-d2af-4735-9919-826c741c5574.PNG)
