### ISSUE TITLE
Qt creator can not launch debug

### ISSUE THREAD

**Issue by rockydut** [msys2/MINGW-packages#9401]
I updated the packages and found the qt creator cannot launch debug mode.
My qtcreator version is mingw-w64-x86_64-qt-creator 4.5.2-2.
My Qt version is 5.15.2-9.

**Comment by MehdiChinoune** [comment]
> I updated the packages and found the qt creator cannot launch debug mode.
> My qtcreator version is mingw-w64-x86_64-qt-creator 4.5.2-2.
> My Qt version is 5.15.2-9.

What do you mean by "debug mode"?

**Comment by rockydut** [comment]
It means that When I click the "Start debugging of startup project" in qtcreator, the program cannot launch debugging. The tip of "launching debug" is red color.

**Comment by rockydut** [comment]
By the way, I update the msys2 by the command "pacman -Syu". My system is Win10.

**Comment by MehdiChinoune** [comment]
> It means that When I click the "Start debugging of startup project" in qtcreator, the program cannot launch debugging. The tip of "launching debug" is red color.

It worked well on my side, could you show me a reproducer (project+steps).

**Comment by rockydut** [comment]
For a simple project.
1. open qtcreator;
2. new a non-qt project, just Plain C++ Application;
3. just next; the code in main.cpp is :
 #include <iostream>
using namespace std;
int main()
{
    cout << "Hello World!" << endl;
    return 0;
}

For this code, It can "Run" by clicked "Run" button, but can not debugging by click "Start debugging of startup project" in qtcreator.

**Comment by rockydut** [comment]
qt-creator cannot launching debugger.

**Comment by rockydut** [comment]
Some debug informations:


129show version
130show debug-file-directory
131set breakpoint pending on
132set print elements 10000
133set unwindonsignal on
134set width 0
135set height 0
Setting up inferior...
136set substitute-path C:/work/build/qt5_workdir/w/s D:/Msys64/mingw64/../Src
137set substitute-path Q:/qt5_workdir/w/s D:/Msys64/mingw64/../Src
138set substitute-path c:/Users/qt/work/install D:/Msys64/mingw64/../Src
139set substitute-path c:/users/qt/work/qt D:/Msys64/mingw64/../Src
140python sys.path.insert(1, 'D:/Msys64/mingw64/share/qtcreator/debugger/')
141python sys.path.append('D:/Msys64/mingw64/bin/data-directory/python')
142python from gdbbridge import *
143python theDumper.loadDumpers({"token":143})
144-interpreter-exec console "set target-async off"
Debugging has failed.



------------------------------------------------------------------

wNote: This log contains possibly confidential information about your machine, environment variables, in-memory data of the processes you are debugging, and more. It is never transferred over the internet by Qt Creator, and only stored to disk if you manually use the respective option from the context menu, or through mechanisms that are not under the control of Qt Creator's Debugger plugin, for instance in swap files, or other plugins you might use.
wYou may be asked to share the contents of this log when reporting bugs related to debugger operation. In this case, make sure your submission does not contain data you do not want to or you are not allowed to share.
w
dStart parameters: 'ttt' mode: 1
dABI: x86-windows-msys-pe-64bit
dLanguages: c++ 
dExecutable: G:\program\build-ttt-Desktop_Qt_MinGW_w64_64bit_MSYS2-Debug\ttt.exe
dDirectory: G:\program\build-ttt-Desktop_Qt_MinGW_w64_64bit_MSYS2-Debug
dDebugger: D:\Msys64\mingw64\bin\gdb.exe
dProject: G:\program\ttt
dAdditional Search Directories:
dSysroot: 
dDebug Source Location: 
dDebugger settings:
dCDB2/AdditionalArguments:   (default: )
dCDB2/BreakEvent:   (default: )
dCDB2/BreakOnCrtDbgReport: false  (default: false)
dCDB2/BreakpointCorrection: true  (default: true)
dCDB2/CDB_Console: false  (default: false)
dCDB2/FirstChanceExceptionTaskEntry: true  (default: true)
dCDB2/IgnoreFirstChanceAccessViolation: false  (default: false)
dCDB2/SecondChanceExceptionTaskEntry: true  (default: true)
dCDB2/SourcePaths:   (default: )
dCDB2/SymbolPaths:   (default: )
dCDB2/UsePythonDumper: true  (default: true)
dDebugMode/AdjustBreakpointLocations: true  (default: true)
dDebugMode/AllPluginBreakpoints: true  (default: true)
dDebugMode/AlwaysAdjustColumnWidths: true  (default: true)
dDebugMode/AutoDerefPointers: true  (default: true)
dDebugMode/AutoEnrichParameters: true  (default: true)
dDebugMode/AutoQuit: false  (default: false)
dDebugMode/BreakOnAbort: false  (default: false)
dDebugMode/BreakOnCatch: false  (default: false)
dDebugMode/BreakOnFatal: false  (default: false)
dDebugMode/BreakOnThrow: false  (default: false)
dDebugMode/BreakOnWarning: false  (default: false)
dDebugMode/BreakpointsFullPath: false  (default: false)
dDebugMode/CloseBuffersOnExit: false  (default: false)
dDebugMode/CloseMemoryBuffersOnExit: true  (default: true)
dDebugMode/DisplayStringLimit: 100  (default: 100)
dDebugMode/EnableReverseDebugging: false  (default: false)
dDebugMode/ExtraDumperFile:   (default: )
dDebugMode/FontSizeFollowsEditor: false  (default: false)
dDebugMode/GdbCustomDumperCommands:   (default: )
dDebugMode/GdbPostAttachCommands:   (default: )
dDebugMode/GdbStartupCommands:   (default: )
dDebugMode/IntelFlavor: false  (default: false)
dDebugMode/LoadGdbDumpers2: false  (default: false)
dDebugMode/LoadGdbInit: true  (default: true)
dDebugMode/LogTimeStamps: false  (default: false)
dDebugMode/MaximalStackDepth: 20  (default: 20)
dDebugMode/MaximalStringLength: 10000  (default: 10000)
dDebugMode/MultiInferior: false  (default: false)
dDebugMode/NoPluginBreakpoints: false  (default: false)
dDebugMode/RaiseOnInterrupt: true  (default: true)
dDebugMode/RegisterForPostMortem: false  (default: false)
dDebugMode/SelectedPluginBreakpoints: false  (default: false)
dDebugMode/SelectedPluginBreakpointsPattern: .*  (default: .*)
dDebugMode/ShowQObjectNames2: true  (default: true)
dDebugMode/ShowQmlObjectTree: true  (default: true)
dDebugMode/ShowQtNamespace: true  (default: true)
dDebugMode/ShowStandardNamespace: true  (default: true)
dDebugMode/ShowThreadNames: false  (default: false)
dDebugMode/SkipKnownFrames: false  (default: false)
dDebugMode/SortStructMembers: true  (default: true)
dDebugMode/StationaryEditorWhileStepping: false  (default: false)
dDebugMode/SwitchModeOnExit: false  (default: false)
dDebugMode/TargetAsync: false  (default: false)
dDebugMode/UseAlternatingRowColours: false  (default: false)
dDebugMode/UseAnnotations: true  (default: true)
dDebugMode/UseCodeModel: true  (default: true)
dDebugMode/UseDebuggingHelper: true  (default: true)
dDebugMode/UseDynamicType: true  (default: true)
dDebugMode/UseMessageBoxForSignals: true  (default: true)
dDebugMode/UsePseudoTracepoints: true  (default: true)
dDebugMode/UseToolTips: true  (default: true)
dDebugMode/UseToolTipsInBreakpointsView: false  (default: false)
dDebugMode/UseToolTipsInLocalsView: false  (default: false)
dDebugMode/UseToolTipsInStackView: true  (default: true)
dDebugMode/WarnOnReleaseBuilds: true  (default: true)
dDebugMode/WatchdogTimeout: 20  (default: 20)
dQML.Inspector/QmlInspector.ShowAppOnTop: false  (default: false)
dState changed from DebuggerNotReady(0) to EngineSetupRequested(1)
dCALL: SETUP ENGINE
dTRYING TO START ADAPTER
dENABLING TEST CASE: 0
dSTARTING D:\Msys64\mingw64\bin\gdb.exe "--tty=\\.\pipe\creator-6348-21360" -i mi
dGDB STARTED, INITIALIZING IT
<129show version
<130show debug-file-directory
<131set breakpoint pending on
<132set print elements 10000
<133set unwindonsignal on
<134set width 0
<135set height 0
 Setting up inferior...
<136set substitute-path C:/work/build/qt5_workdir/w/s D:/Msys64/mingw64/../Src
<137set substitute-path Q:/qt5_workdir/w/s D:/Msys64/mingw64/../Src
<138set substitute-path c:/Users/qt/work/install D:/Msys64/mingw64/../Src
<139set substitute-path c:/users/qt/work/qt D:/Msys64/mingw64/../Src
<140python sys.path.insert(1, 'D:/Msys64/mingw64/share/qtcreator/debugger/')
<141python sys.path.append('D:/Msys64/mingw64/bin/data-directory/python')
<142python from gdbbridge import *
<143python theDumper.loadDumpers({"token":143})
dUNEXPECTED GDB STDERR: Python Exception <class 'ModuleNotFoundError'> No module named 'gdb': 
dD:\Msys64\mingw64\bin\gdb.exe: warning: 
dCould not load the Python gdb module from `d:\msys64\mingw64\share\gdb/python'.
dLimited Python support is available from the _gdb module.
dSuggest passing --data-directory=/path/to/gdb/data-directory.
dTraceback (most recent call last):
d  File "<string>", line 3, in <module>
dModuleNotFoundError: No module named 'libstdcxx'
>=thread-group-added,id="i1"
>~"GNU gdb (GDB) 10.2\n"
>~"Copyright (C) 2021 Free Software Foundation, Inc.\n"
>~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
>~"\nType \"show copying\" and \"show warranty\" for details.\n"
>~"This GDB was configured as \"x86_64-w64-mingw32\".\n"
>~"Type \"show configuration\" for configuration details.\n"
>~"For bug reporting instructions, please see:\n"
>~"<https://www.gnu.org/software/gdb/bugs/>.\n"
>~"Find the GDB manual and other documentation resources online at:\n    <http://www.gnu.org/software/gdb/documentation/>."
>~"\n\n"
>~"For help, type \"help\".\n"
>~"Type \"apropos word\" to search for commands related to \"word\".\n"
>&"d:\\msys64\\mingw64\\bin\\../etc/gdbinit:6: Error in sourced command file:\n"
>&"Error while executing Python code.\n"

>&"show version\n"
>~"GNU gdb (GDB) 10.2\n"
>~"Copyright (C) 2021 Free Software Foundation, Inc.\n"
>~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
>~"\nType \"show copying\" and \"show warranty\" for details.\n"
>~"This GDB was configured as \"x86_64-w64-mingw32\".\n"
>~"Type \"show configuration\" for configuration details.\n"
>~"For bug reporting instructions, please see:\n"
>~"<https://www.gnu.org/software/gdb/bugs/>.\n"
>~"Find the GDB manual and other documentation resources online at:\n    <http://www.gnu.org/software/gdb/documentation/>."
>~"\n\n"
>~"For help, type \"help\".\n"
>~"Type \"apropos word\" to search for commands related to \"word\".\n"
>129^done
dPARSING VERSION: 129^done
dSUPPORTED GDB VERSION GNU gdb (GDB) 10.2
dCopyright (C) 2021 Free Software Foundation, Inc.
dLicense GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
dThis is free software: you are free to change and redistribute it.
dThere is NO WARRANTY, to the extent permitted by law.
dType "show copying" and "show warranty" for details.
dThis GDB was configured as "x86_64-w64-mingw32".
dType "show configuration" for configuration details.
dFor bug reporting instructions, please see:
d<https://www.gnu.org/software/gdb/bugs/>.
dFind the GDB manual and other documentation resources online at:
d    <http://www.gnu.org/software/gdb/documentation/>.
d
dFor help, type "help".
dType "apropos word" to search for commands related to "word".
dGNU gdb (GDB) 10.2
dCopyright (C) 2021 Free Software Foundation, Inc.
dLicense GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
dThis is free software: you are free to change and redistribute it.
dThere is NO WARRANTY, to the extent permitted by law.
dType "show copying" and "show warranty" for details.
dThis GDB was configured as "x86_64-w64-mingw32".
dType "show configuration" for configuration details.
dFor bug reporting instructions, please see:
d<https://www.gnu.org/software/gdb/bugs/>.
dFind the GDB manual and other documentation resources online at:
d    <http://www.gnu.org/software/gdb/documentation/>.
d
dFor help, type "help".
dType "apropos word" to search for commands related to "word".
dUSING GDB VERSION: 100200, BUILD: 2021
<144-interpreter-exec console "set target-async off"

>&"show debug-file-directory\n"
>~"The directory where separate debug symbols are searched for is \"c:\\mingw64\\lib\\debug\".\n"
>130^done

>&"set breakpoint pending on\n"
>=cmd-param-changed,param="breakpoint pending",value="on"
>131^done

>&"set print elements 10000\n"
>=cmd-param-changed,param="print elements",value="10000"
>132^done

>&"set unwindonsignal on\n"
>=cmd-param-changed,param="unwindonsignal",value="on"
>133^done

>&"set width 0\n"
>=cmd-param-changed,param="width",value="4294967295"
>134^done

>&"set height 0\n"
>135^done

>&"set substitute-path C:/work/build/qt5_workdir/w/s D:/Msys64/mingw64/../Src\n"
>136^done

>&"set substitute-path Q:/qt5_workdir/w/s D:/Msys64/mingw64/../Src\n"
>137^done

>&"set substitute-path c:/Users/qt/work/install D:/Msys64/mingw64/../Src\n"
>138^done

>&"set substitute-path c:/users/qt/work/qt D:/Msys64/mingw64/../Src\n"
>139^done

>&"python sys.path.insert(1, 'D:/Msys64/mingw64/share/qtcreator/debugger/')\n"
>140^done

>&"python sys.path.append('D:/Msys64/mingw64/bin/data-directory/python')\n"
>141^done

>&"python from gdbbridge import *\n"
>&"Error while executing Python code.\n"
>142^error,msg="Error while executing Python code."

>&"python theDumper.loadDumpers({\"token\":143})\n"
dUNEXPECTED GDB STDERR: Traceback (most recent call last):
d  File "<string>", line 1, in <module>
d  File "D:\Msys64/mingw64/share/qtcreator/debugger\gdbbridge.py", line 31, in <module>
d    import gdb
dModuleNotFoundError: No module named 'gdb'
dTraceback (most recent call last):
d  File "<string>", line 1, in <module>
dUNEXPECTED GDB STDERR: NameError: name 'theDumper' is not defined
>&"Error while executing Python code.\n"
>143^error,msg="Error while executing Python code."
dNOTE: ENGINE SETUP FAILED
dState changed from EngineSetupRequested(1) to EngineSetupFailed(2)
<Debugging has failed.
dState changed from EngineSetupFailed(2) to DebuggerFinished(16)

**Comment by MehdiChinoune** [comment]
Could you uninstall qt5 and then reinstall qt-creator and see if the problem solved:
```
pacman -Rusc mingw-w64-x86_64-qt5
pacman -S mingw-w64-x86_64-qt-creator
```

**Comment by rockydut** [comment]
I try that as you said. but It still cannot start debugging.

**Comment by MehdiChinoune** [comment]
I can't reproduce the failure even after a clean installation.

**Comment by MehdiChinoune** [comment]
> I try that as you said. but It still cannot start debugging.

Did try lauching your app with gdb outside of qt-creator to see if the problem came from the debugger.

**Comment by rockydut** [comment]
Thank you for your help. I uninstall the MSYS2 in my WIN10 system and reinstall it with all of the packages. It can run well.
