### ISSUE TITLE
Invalid stub error generated by context.exe from the mingw-w64-x86_64-texlive-core package.

### ISSUE THREAD

**Issue by BenKey** [msys2/MINGW-packages#9418]
# Environment

* **OS:** Windows 10 Pro 64-bit Version 21H1 build 19043.1165 with Windows Feature Experience Pack 120.2212.3530.0.
* **Shell:** MSYS2 MinGW 64-bit

# Steps to Reproduce

1. Install the following texlive packages.
    * mingw-w64-i686-texlive-core
    * mingw-w64-i686-texlive-extra-utils
    * mingw-w64-i686-texlive-font-utils
    * mingw-w64-i686-texlive-fonts-recommended
    * mingw-w64-i686-texlive-lang-czechslovak
    * mingw-w64-i686-texlive-lang-english
    * mingw-w64-i686-texlive-lang-european
    * mingw-w64-i686-texlive-lang-french
    * mingw-w64-i686-texlive-lang-german
    * mingw-w64-i686-texlive-lang-italian
    * mingw-w64-i686-texlive-lang-polish
    * mingw-w64-i686-texlive-lang-portuguese
    * mingw-w64-i686-texlive-lang-spanish
    * mingw-w64-i686-texlive-latex-recommended
    * mingw-w64-i686-texlive-luatex
    * mingw-w64-i686-texlive-metapost
    * mingw-w64-i686-texlive-plain-generic
    * mingw-w64-i686-texlive-science
2. Open the MSYS2 MinGW 64-bit shell.
3. Run the following command:  `context --version`.
    a. **Expected Result:** The version information should be displayed.
    b. **Actual Result:** An "invalid stub" error.

**Comment by naveen521kk** [comment]
Can you send the expected output?

**Comment by BenKey** [comment]
For the `context --version` command, the output should be the usage text written to the console. For example, the context-win64 package from [ConText Garden](https://wiki.contextgarden.net/) produces the following output from the `context --version` command.

```
mtx-context     | ConTeXt Process Management 1.04
mtx-context     |
mtx-context     | main context file: c:/context-win64/tex/texmf-context/tex/context/base/mkiv/context.mkiv
mtx-context     | current version: 2021.08.24 22:16
mtx-context     | main context file: c:/context-win64/tex/texmf-context/tex/context/base/mkxl/context.mkxl
mtx-context     | current version: 2021.08.24 22:16
```

**Note:** It does not matter what command is used. They all fail with the same error. My best guess is that the package is missing a file or component that is loaded at runtime.

**Comment by naveen521kk** [comment]
I am trying to debug what's exactly happening here. Just running `context.exe` in `/mingw64/bin` executes `/mingw64/share/texmf-dist/scripts/context/stubs/unix/context` which can't be run on Windows directly (that's why it says `invalid stub`). Instead the one in `c/mingw64/share/texmf-dist/scripts/context/stubs/win64/context.exe` should be run. I'll look into how that file is compiled and if just copying the file to `/mingw64/bin` fixes the issue.

```sh
$ kpsewhich --format=texmfscripts context
c:/dev/texlive-2022/msys64/mingw64/share/texmf-dist/scripts/context/stubs/unix/context
$ "c:/dev/texlive-2022/msys64/mingw64/share/texmf-dist/scripts/context/stubs/win64/context.exe" --version
mtx-context     | ConTeXt Process Management 1.04
mtx-context     |
mtx-context     | main context file: C:/dev/texlive-2022/msys64/mingw64/share/texmf-dist/tex/context/base/mkiv/context.mkiv
mtx-context     | current version: 2021.03.05 19:11
mtx-context     | main context file: C:/dev/texlive-2022/msys64/mingw64/share/texmf-dist/tex/context/base/mkxl/context.mkxl
mtx-context     | current version: 2021.03.05 19:11
```
Thanks for reporting!
