### ISSUE TITLE
Config file broke in qwt-qt5 renaming

### ISSUE THREAD

**Issue by radioflash** [msys2/MINGW-packages#9448]
When the old "qwt" was renamed to qwt-qt5, one library renaming spot was missed:
This is in mingw64/share/qt5/mkspecs/features/qwt.prf:
Last line needs to be:
`qwtAddLibrary($${QWT_INSTALL_LIBS}, qwt-qt5)`

Consequence:
`CONFIG += qwt` no longer works from *.pro files (because it passes an incorrect library name to linker).

How should this be fixed?

1) Should I sumit a PR with a modified `005-rename-qwt-to-remove-qt5-qt6-conflict.patch` that also does this rename?
2) Should I submit a PR with an additional patch file where this step is done?
3) Something else (?)

**Comment by Biswa96** [comment]
Contributions are always welcomed 🤗 Make sure to discuss with @MehdiChinoune

**Comment by MehdiChinoune** [comment]
> When the old "qwt" was renamed to qwt-qt5, one library renaming spot was missed:
> This is in mingw64/share/qt5/mkspecs/features/qwt.prf:
> Last line needs to be:
> `qwtAddLibrary($${QWT_INSTALL_LIBS}, qwt-qt5)`
> 
> Consequence:
> `CONFIG += qwt` no longer works from *.pro files (because it passes an incorrect library name to linker).
> 
> How should this be fixed?
> 
> 1. Should I sumit a PR with a modified `005-rename-qwt-to-remove-qt5-qt6-conflict.patch` that also does this rename?
> 2. Should I submit a PR with an additional patch file where this step is done?
> 3. Something else (?)

the first, and don't forget to do the same with qwt-qt6.
