### ISSUE TITLE
Pacman Dependencies Fault on Clang x86_64 libtiff & libwebp

### ISSUE THREAD

**Issue by MarMerciless** [msys2/MINGW-packages#9459]
When I try installing clang it gives me the basic installation through online Pacman download and the directory files are never really installed.

I look in the directory nothing is there. When I try compiling with it it fails.

I did manual installation of the files by download from site an the code below until the dependencies fault was discovered.

----------------------------------------------------------------------------------------------
```
MSYS ~
# pacman -U 'I:/clang-x86_64/mingw-w64-clang-x86_64-libwebp-1.2.1-1-any.pkg.tar.zst'
loading packages...
resolving dependencies...
warning: cannot resolve "mingw-w64-clang-x86_64-libtiff", a dependency of "mingw-w64-clang-x86_64-libwebp"
:: The following package cannot be upgraded due to unresolvable dependencies:
      mingw-w64-clang-x86_64-libwebp

:: Do you want to skip the above package for this upgrade? [Y/n] y
looking for conflicting packages...
 there is nothing to do

 MSYS ~
# pacman -U --noconfirm 'I:/clang-x86_64/mingw-w64-clang-x86_64-libtiff-4.3.0-6-any.pkg.tar.zst'
loading packages...
resolving dependencies...
warning: cannot resolve "mingw-w64-clang-x86_64-libwebp", a dependency of "mingw-w64-clang-x86_64-libtiff"
:: The following package cannot be upgraded due to unresolvable dependencies:
      mingw-w64-clang-x86_64-libtiff

:: Do you want to skip the above package for this upgrade? [Y/n]
looking for conflicting packages...
 there is nothing to do
```

**Comment by jeremyd2019** [comment]
Yeah, there's a circular dependency there... and not just on clang64.  You need to install both in the same command.

**Comment by MarMerciless** [comment]
Like Flash Gordon,
Jeremy to the speedy rescue.♻️
[Animated GIF]

Thank you bro. It worked.
________________________________
