### ISSUE TITLE
[Feature / Web-related or View-related] Make it possible to easily view which packages are available

### ISSUE THREAD

**Issue by rubyFeedback** [msys2/MINGW-packages#9469]
Yo folks,

Going to github I get this here:

"Sorry, we had to truncate this directory to 1,000 files. 868 entries were omitted from the list."

Ok so ... what if someone would like to see which packages are available, and which ones may
be missing? That may be useful to know and find out.

I went to the homepage but could not find such a page or functionality. If it exists then perhaps
more links could be added to point to it. If it does not exist then perhaps it could be added.

What would be needed or useful?

Well, firstly: I think we need a page that may be either dynamically generated or generated
like every weekend or day or something. It should list which packages are available.

Yes pacman may show this but I refer to a web-page really, so that people can quickly
identify before having installed msys/mingw.

The list/table should be alphabetically sorted by default. Additionally a sort functionality
via javascript may be nice, such as on wikipedia where you can click on headers of
columns to sort, e. g. if you want to sort by "most recently updated". So ideally it
would be a dynamic page. But! To keep things simple, as first step I propose a static
page, really just to cover the "overview" aspect. At a later time this can become more
useful.

What I am interested mostly is to be able to see which packages are available and
which ones are missing.

IF too many results show then you could, say, group a per-100 entries view or something
like that, so you don't have to display +2000 packages in a single file if this is too much
to display.

A search functionality may also be useful but again - these are add-on ideas. My primary
goal with this request is to make it possible to be able to quickly view which packages
are available - a bit like what archlinux offers on their homepage, but in a more global
manner. (I forgot whether you can easily show all packages).

If you want to get fancy via a web-app such as sinatra or any python-based, you could
add something like:

    /view
    /view/gcc

or so to view all available GCC entries.

The main idea here is to see which packages are still missing, so perhaps new contributors
could want to add more entries or work on things that are missing. Probably some not-so-commonly
used code isn't yet added, but I would not know how to easily find out.

At any rate thanks for reading. Please feel free to close the issue at any moment in time, in particular
if the functionality already exists (but in that case a link to how to use it from the main README would
be helpful; I always use the main README as general entry point. It's ok to have documentation
available elsewhere, but I could not find it on the homepage of msys2 either so here I added an issue
request).

**Comment by MehdiChinoune** [comment]
already exist!
