### ISSUE TITLE
QT windeployqt.exe "Unable to locate ICU library icudt68.dll"

### ISSUE THREAD

**Issue by acotty** [msys2/MINGW-packages#9475]
Looks like the windeployqt.exe issue has raised it's head with the latest QT updates from a day or two ago that I just downloaded,

See the following for same "Unable to locate ICU library icudt68.dll" issue in the past:
    https://github.com/msys2/MINGW-packages/issues/221
    https://github.com/msys2/MINGW-packages/pull/1504

**Comment by lazka** [comment]
@acotty can you test again?

**Comment by acotty** [comment]
Just did an MSYS2 update and it's now working.  This issue can be closed.

**Comment by lazka** [comment]
Thanks for testing
