### ISSUE TITLE
CI-build and msys2-autobuild use different toolsets

### ISSUE THREAD

**Issue by heljkon** [msys2/MINGW-packages#9479]
With https://github.com/msys2/MINGW-packages/pull/9201 CI was able to build for CLANG64

QEMU build for CLANG64 [Logs](https://pipelines.actions.githubusercontent.com/jz302Jp6n2Ls4LxFeVGslDhpd6yjvpcP6IkHkrD1oqOYWum4cl/_apis/pipelines/1/runs/4485/signedlogcontent/19?urlExpires=2021-08-28T13%3A11%3A50.9255349Z&urlSigningMethod=HMACV1&urlSignature=U1EYwbiof3Py7gpYcObTQQLwlIcGhpH1kTlk%2FJytvnQ%3D) failed with:
```
2021-08-28T09:55:01.4448168Z ../qemu-6.1.0/meson.build:1:0: ERROR: Unknown linker(s): [['gcc-ar']]
2021-08-28T09:55:01.4449057Z The following exception(s) were encountered:
2021-08-28T09:55:01.4450430Z Running "gcc-ar --version" gave "[WinError 2] The system cannot find the file specified"
2021-08-28T09:55:01.4451148Z 
2021-08-28T09:55:01.4452019Z A full log can be found at C:/_/M/mingw-w64-qemu/src/build-x86_64/meson-logs/meson-log.txt
2021-08-28T09:55:01.5254990Z 
2021-08-28T09:55:01.5256197Z ERROR: meson setup failed
```

After installing CLANG64 toolchain I realized, gcc-ar and gcc-ranlib don't exist in CLANG64 toolchain, but in MSYS2 toolchain:
```
CLANG64 ~$ which gcc-ar
/usr/bin/gcc-ar
CLANG64 ~$ which ar
/clang64/bin/ar
CLANG64 ~$ which gcc-ranlib
/usr/bin/gcc-ranlib
CLANG64 ~$ which ranlib
/clang64/bin/ranlib
CLANG64 ~$ which nm
/clang64/bin/nm
CLANG64 ~$ which objcopy
/clang64/bin/objcopy
CLANG64 ~$ which strip
/clang64/bin/strip
CLANG64 ~$ which windres
/clang64/bin/windres
```

MSYS2 toolchain seems to be available on CI, but not on msys2-autobuild.

IHMO toolsets in CI and msys2-autobuild should not differ.

**Comment by Biswa96** [comment]
Compiler toochain from /usr/bin are not used for MINGW packages. If PKGBUILD is using those from /usr/bin it should be fixed quickly.

**Comment by heljkon** [comment]
Absolutely! I am working on this. But until msys2-autobuild I wasn't aware of it because of this issue.

**Comment by heljkon** [comment]
@Biswa96 
Because of https://github.com/msys2/MINGW-packages/issues/9480 I would leave PKGBUILD as is, because reconfiguring wouldn't enhance it...
