### ISSUE TITLE
gtkspell3 binary package contains libgtkspell3-2-0.dll and libgtkspell3-3-0.dll

### ISSUE THREAD

**Issue by eht16** [msys2/MINGW-packages#9500]
It seems the gtkspell3 packages (checked for i686 and x86_64) contain two versions of the library.

Not really a big issue but migt indicate a bug in the build script or build system.
To verify, I built the source tarball on a Linux machine and it builds only libgtkspell3-3.so.

Can be checked via the Files lists on:
https://packages.msys2.org/package/mingw-w64-i686-gtkspell3?repo=mingw32
https://packages.msys2.org/package/mingw-w64-x86_64-gtkspell3?repo=mingw64

**Comment by lazka** [comment]
one is likely the gtk2 variant. we can probably drop that now though
