### ISSUE TITLE
recent change to mingw-w64-dlfcn breaks using it from cmake

### ISSUE THREAD

**Issue by ddennedy** [msys2/MINGW-packages#9539]
Since Sept. 4 our nightly build that uses CMake to build with dlfcn-32 is broken:
https://github.com/mltframework/shotcut/runs/3516878028?check_suite_focus=true

I believe the change to `rm -rf ${pkgdir}${MINGW_PREFIX}/bin` in 7ef67ca is the culprit since the error complains about a missing `bin/test-dladdr.exe`:

```
CMake Error at D:/a/_temp/msys/msys64/mingw64/share/dlfcn-win32/dlfcn-win32-targets.cmake:76 (message):
  The imported target "dlfcn-win32::test-dladdr" references the file

     "D:/a/_temp/msys/msys64/mingw64/bin/test-dladdr.exe"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "D:/a/_temp/msys/msys64/mingw64/share/dlfcn-win32/dlfcn-win32-targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  D:/a/_temp/msys/msys64/mingw64/share/dlfcn-win32/dlfcn-win32-config.cmake:20 (include)
  CMakeLists.txt:148 (find_package)
```

**Comment by lazka** [comment]
thanks

**Comment by JPeterMugaas** [comment]
It was my decision when doing the cmake build.  My thinking was that it was simply a test executable that cmake was generating and I was running the tests.  Normally, test executables should not be redistributed and many build systems do NOT do so.  However, you have a compelling case that it should distributed in the packages.
