### ISSUE TITLE
[opencascade] Unevaluated variable in resulting cMake files

### ISSUE THREAD

**Issue by chennes** [msys2/MINGW-packages#9574]
When trying to compile against this version of OpenCASCADE (https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-opencascade-7.5.2-2-any.pkg.tar.zst), cMake throws the following error:
```
CMake Error at /mingw64/lib/cmake/opencascade/OpenCASCADEFoundationClassesTargets.cmake:85 (message):
  The imported target "TKernel" references the file

     "/mingw64/lib${OCCT_INSTALL_BIN_LETTER}/libTKernel.dll.a"

  but this file does not exist. 
```
If I examine the file /mingw64/lib/cmake/opencascade/OpenCASCADEFoundationClassesTargets-release.cmake, I see:
```
list(APPEND _IMPORT_CHECK_FILES_FOR_TKernel "${_IMPORT_PREFIX}/lib\${OCCT_INSTALL_BIN_LETTER}/libTKernel.dll.a" "${_IMPORT_PREFIX}/bin\${OCCT_INSTALL_BIN_LETTER}/libTKernel.dll" )
```
In my other installs of OpenCASCADE, that `\${OCCT_INSTALL_BIN_LETTER}` reference was evaluated during installation, and does not appear in the final file.

**Comment by Biswa96** [comment]
Is there any way to reproduce this issue?

**Comment by chennes** [comment]
Well, you need something that wants to compile against OCCT. Here's what I'm doing...
```
pacman -Su
pacman -S --needed base-devel mingw-w64-x86_64-toolchain cmake git 
pacman -S mingw-w64-x86_64-xerces-c mingw-w64-x86_64-opencascade
export PATH=$PATH:/mingw64/bin
git clone https://github.com/FreeCAD/FreeCAD
mkdir FreeCAD-build
cd FreeCAD-build
cmake ../FreeCAD
```
(Note that those are the minimum FreeCAD dependencies to reproduce this issue, they aren't enough to actually compile FreeCAD once this is resolved)

**Comment by ImperatorS79** [comment]
With gmsh there was not any problem, I thus assume that gmsh does not use a "standard" cmake way to detect OpenCascade...
Maybe one could write a .install that would modify the .cmake files accordingly.

**Comment by chennes** [comment]
It does not appear that gmsh is using `find_package` to locate OpenCASCADE, it's just got some built-in logic to locate it manually. In FreeCAD, the `find_package(OpenCASCADE CONFIG QUIET)` is the line that triggers this error. Here's a minimal CMakeLists.txt file that will trigger the problem:
```
cmake_minimum_required(VERSION 3.15)
project(TestOCCTCmake)
find_package(OpenCASCADE CONFIG)
```
(and yes, OCCT_INSTALL_BIN_LETTER should be unset, so the final installed line in  /mingw64/lib/cmake/opencascade/OpenCASCADEFoundationClassesTargets-release.cmake should read
```
list(APPEND _IMPORT_CHECK_FILES_FOR_TKernel "${_IMPORT_PREFIX}/lib/libTKernel.dll.a" "${_IMPORT_PREFIX}/bin/libTKernel.dll" )
```

**Comment by Biswa96** [comment]
@ImperatorS79 Shouldn't this issue be reported to upstream? If the `OCCT_INSTALL_BIN_LETTER` variable should be empty, then why is it present in cmake files?

**Comment by ImperatorS79** [comment]
No idea. I guess it could be reported upstream.

**Comment by chennes** [comment]
>  If the `OCCT_INSTALL_BIN_LETTER` variable should be empty, then why is it present in cmake files?

I believe that the OpenCASCADE installer should have done that replacement and that it should not ever appear in final installed cMake files. In a conventional Windows installation it's not empty, it's a character that indicates whether it's a debug or release installation. On Unix-like systems it's empty. For some reason on a MINGW installation OpenCASCADE's installer is not doing that replacement at all, however: it's neither replacing it with an empty string, nor a single character, it's just not doing it at all.

**Comment by MehdiChinoune** [comment]
@chennes @ImperatorS79 Could you download the artifacts from https://github.com/msys2/MINGW-packages/actions/runs/1227144810 and see if the issue is resolved or not.

**Comment by chennes** [comment]
@MehdiChinoune Yes, the cMake files in that artifact are correct, they don't have the extra un-evaluated variable in them.

**Comment by GreenTeaHua** [comment]
include_directories(C:/msys64/mingw64/include/opencascade)
set(OCCT_INSTALL_BIN_LETTER "")
find_package(OpenCASCADE REQUIRED)

**Comment by Biswa96** [comment]
@GreenTeaHua Please explain your issue. I can not find such reference in opencascade files. Also, please make sure all packages are updated.
