### ISSUE TITLE
[wxPython]

### ISSUE THREAD

**Issue by tforssen** [msys2/MINGW-packages#9587]
### Fail to import wx in python
I can not load module wx in python:

`$ python`
`Python 3.9.6 (default, Aug 15 2021, 14:49:43)  [GCC 10.3.0 64 bit (AMD64)] on win32`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import wx`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "C:/msys64/mingw64/lib/python3.9/site-packages/wx/__init__.py", line 17, in <module>`
`    from wx.core import *`
`  File "C:/msys64/mingw64/lib/python3.9/site-packages/wx/core.py", line 12, in <module>`
`    from ._core import *`
`ImportError: DLL load failed while importing _core: The specified procedure could not be found.`
`>>>`

I am using updated modules as of 20210913:
mingw-w64-x86_64-python 3.9.6-4
mingw-w64-x86_64-wxPython 4.1.1-2

To me it looks like a DLL-missing or DLL can't be found error. As I understand the failing import is inside:
`/c/msys64/mingw64/lib/python3.9/site-packages/wx/_core.cp39-mingw_x86_64.pyd`

Here my bug-tracking knowledge is starting to fade... I used an app `Dependencies` to list the imported modules inside the `.pdy` file. Some issues were reported when tying to load the following DLL:
`/c/msys64/mingw64/bin/wxmsw315u_core_gcc_custom.dll`
However, when trying to resolve the modules inside that DLL everything seams to be ok. (Here I used a simple `ldd`.)

Is it only me encountering this error? and, any suggestions resolving this would be most appreciated.
Thanks
/Tomas

**Comment by lazka** [comment]
looks like wxwidgets lost this symbol: `N/A, 4400 (0x00001130), wxGraphicsRenderer::GetDirect2DRenderer(), C:\msys64\mingw64\bin\wxmsw315u_core_gcc_custom.dll, False, Demumble`

**Comment by jeremyd2019** [comment]
#9396?

**Comment by lazka** [comment]
ah thanks

**Comment by tforssen** [comment]
Perfect! The wx module now loads without problems. Thanks
