### ISSUE TITLE
Every gtkmm program fails on updated msys

### ISSUE THREAD

**Issue by Samega7Cattac** [msys2/MINGW-packages#9593]
2 machines just updated the msys2.
Gtkmm4 had issues before, weird behaviors, but now it doesn't start at all
This happens on EVERY gtkmm projects, even on examples (so it's not a issue on our side, plus it was working before).

Example of output:
```
** (process:5032): WARNING **: 10:18:23.040: Can't set the global locale to the user's preferred locale.
   locale::facet::_S_create_c_locale name not valid
   The environment variable LANG may be wrong.


** (process:5032): WARNING **: 10:18:23.244: Can't make the global C++ locale equal to the C locale.
   locale::facet::_S_create_c_locale name not valid
   C locale = English_United States.1252


(3way_panned.exe:5032): Gdk-WARNING **: 10:18:23.493: GL implementation doesn't support any form of non-power-of-two textures
No provider of glCreateShader found.  Requires one of:
    Desktop OpenGL 2.0
    OpenGL ES 2.0
    GL_ARB_shader_objects
```

This happens on 2 diff machines since today

**Comment by Samega7Cattac** [comment]
Seems this only happens on Windows VM
QEMU (+ virt-manager), using QXL graphical driver

**Comment by lazka** [comment]
upstream report: https://gitlab.gnome.org/GNOME/gtk/-/issues/4257

**Comment by Samega7Cattac** [comment]
Well I created it after some discussion on discord

**Comment by naveen521kk** [comment]
Is this issue fixes?

**Comment by Samega7Cattac** [comment]
some did some not

**Comment by Samega7Cattac** [comment]
It can be closed bc these are warning and not errors (the original point of this issue)
