### ISSUE TITLE
Latest libboost 1.77.0 update breaks nextpnr

### ISSUE THREAD

**Issue by SiliconWizard** [msys2/MINGW-packages#9598]
Package: mingw-w64-x86_64-nextpnr

boost 1.77.0 breaks nextpnr.

It would appear to come from the fact that the new libboost_filesystem-mt.dll doesn't export a required function for nextpnr-*.exe :

_ZNK5boost10filesystem4path4stemEv

**Comment by jeremyd2019** [comment]
These packages import that symbol:
* mingw-w64-inkscape
* mingw-w64-innoextract
* mingw-w64-nextpnr
* mingw-w64-openscad

**Comment by jeremyd2019** [comment]
I believe nextpnr was/is being rebuilt anyway, for a normal update.  The other packages in that list probably need a rebuild if boost did indeed remove that as an exported symbol.

**Comment by lazka** [comment]
openscad fails to rebuild

**Comment by SiliconWizard** [comment]
Latest update fixes it.
