### ISSUE TITLE
rust 1.55.0 failed to auto build

### ISSUE THREAD

**Issue by filnet** [msys2/MINGW-packages#9600]
Apparently the new rust 1.55.0 package failed to auto build.
See https://packages.msys2.org/queue.

What is strange is that the links to the failed builds point to successful builds.

**Comment by filnet** [comment]
There are now less failed builds. I guess I have no idea how auto build works ;)

**Comment by naveen521kk** [comment]
Probably because of https://github.com/actions/virtual-environments/issues/4086
