### ISSUE TITLE
How to link app manifest using clang build in MSYS2

### ISSUE THREAD

**Issue by lovettchris** [msys2/MINGW-packages#9603]
## Describe the issue

I'm trying to add the following *.rc file to my cmake library

## Steps to Reproduce the Problem

1. Add "[manifest.rc](https://github.com/msys2/MSYS2-packages/files/7172991/manifest.zip)" to your `add_library(shell OBJECT main .cpp )`
2. Cmake and build your project.
3. The build compiles the RC using windres, great, `Building RC object shell/CMakeFiles/shell.dir/manifest.rc.obj` but the linker is unhappy with it `bash: line 1: C:/msys64/home/.../CMakeFiles/shell.dir/manifest.rc.obj: cannot execute binary file: Exec format error` even though the file is identical to the default-manifest.o that ships with gcc.
4. How to link a compiled resource containing an app manifest?

## Additional Context: Operating System, Screenshots

- OS: [ Windows 11 Pro version 21H2 build 22000.184]
- msys2: 20210725
- clang: pacman -S mingw-w64-x86_64-clang

**Comment by Biswa96** [comment]
Can you provide the cmake file? Generally, treat the .rc file as any other source code.

**Comment by lovettchris** [comment]
attached:
[test.zip](https://github.com/msys2/MINGW-packages/files/7173203/test.zip)

build using:
```
cmake .. -G "Unix Makefiles"
make
```
I get a different error in this little test, so not sure what is happening above for the exec format error.
```
Scanning dependencies of target foo
[ 33%] Building CXX object CMakeFiles/foo.dir/main.cpp.obj
[ 66%] Building RC object CMakeFiles/foo.dir/manifest.rc.obj
[100%] Linking CXX executable foo.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .rsrc merge failure: multiple non-default manifests
[100%] Built target foo
```

this version of ld.exe has version 2.36.1

**Comment by lazka** [comment]
Your example works fine here.

**Comment by Biswa96** [comment]
Yes, I agree with lazka. Here is the output of make command:

```
$ make
Scanning dependencies of target foo
[ 33%] Building CXX object CMakeFiles/foo.dir/main.cpp.obj
[ 66%] Building RC object CMakeFiles/foo.dir/manifest.rc.obj
[100%] Linking CXX executable foo.exe
[100%] Built target foo
```

**Comment by lovettchris** [comment]
Cool , but I only install MSYS2 the other day, so which version of MSYS2 do I need?

**Comment by Biswa96** [comment]
There is no version of msys2, just like rolling Linux distributions (e.g. ArchLinux). Make sure you have installed msys2 with [latest installer][1] and update all installed packages with `pacman -Syyu` command. You can search for any package details here https://packages.msys2.org/search

[1]: https://github.com/msys2/msys2-installer/releases

**Comment by lovettchris** [comment]
Ok, I ran "racman -Syyu" and recreated my build output and I still get this warning:
```
C:/msys64/mingw64/bin/c++.exe -Wl,--whole-archive CMakeFiles/foo.dir/objects.a -Wl,--no-whole-archive -o foo.exe -Wl,--out-implib,libfoo.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles/foo.dir/linklibs.rsp
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .rsrc merge failure: multiple non-default manifests
```
but it does produce a binary and the binary has one .rsrc section containing my updated manifest so all good, thanks.
