### ISSUE TITLE
[kimageformats-qt5] AVIF and HEIF plugins are not included.

### ISSUE THREAD

**Issue by novomesk** [msys2/MINGW-packages#9606]
kimageformats package has plug-ins for AVIF and HEIF formats. However they are not built now for MSYS2 packages, because `libavif` and `libheif` packages are not listed among dependencies.

HEIF/HEIC format plugin needs also `-DKIMAGEFORMATS_HEIF=ON` cmake  [parameter](https://invent.kde.org/frameworks/kimageformats/-/blob/v5.85.0/CMakeLists.txt#L59) in order to be enabled.

**Comment by Biswa96** [comment]
This has been added in this pull request https://github.com/msys2/MINGW-packages/pull/9607. Please test the packages from that pull request after build is completed.

**Comment by novomesk** [comment]
Thank you!
