### ISSUE TITLE
clang: windres does not seem to support MENUEX

### ISSUE THREAD

**Issue by waltje** [msys2/MINGW-packages#9611]
Resource scripts containing a MENUEX statement (and, with that, POPUP statements
that add a "id" parameter (third param) cannot be parsed.

Package version 12.0.0, Windows x64.

Running Clang binaries from within a (standard) command prompt, not from within MSYS2.

**Comment by jeremyd2019** [comment]
https://bugs.llvm.org/show_bug.cgi?id=40108  Thought there was already an issue here too, but I guess not

**Comment by mati865** [comment]
Fixed upstream by https://github.com/llvm/llvm-project/pull/67464
