### ISSUE TITLE
[ucrt] Couldn't build gdal on UCRT64 due to a broken at_quick_exit.

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#9617]

**Comment by jeremyd2019** [comment]
I missed this when it was open, but https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/88968391-3b2a-08e8-393f-8931a7137bb7%40126.com/.  You might want to talk to mingw-w64 about it if it is broken.
