### ISSUE TITLE
Patch cairo with MR 245

### ISSUE THREAD

**Issue by Jehan** [msys2/MINGW-packages#9618]
The following patch got into Cairo: https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/245

It fixes an issue we have had for years (11 y.o. report in our bugtracker: https://gitlab.gnome.org/GNOME/gimp/-/issues/325).

We are not sure there will be a new Cairo release containing this patch so we'd welcome a patched MSYS2 Cairo. 😉

P.S.: thanks all for the awesome job! It'd be much harder without MSYS2, awesome project! 👍

**Comment by Biswa96** [comment]
Please test the packages in linked pull request.
