### ISSUE TITLE
LLVM OpenMP is somehow broken

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#9624]
This happened with both libraw and tesseract-ocr packages. lld fails to link to libomp.
see:
https://github.com/MehdiChinoune/MINGW-packages/runs/3640806675?check_suite_focus=true
https://github.com/MehdiChinoune/MINGW-packages/runs/3640221826?check_suite_focus=true

@jeremyd2019 @mstorsjo

**Comment by jeremyd2019** [comment]
#8554?

**Comment by mati865** [comment]
Tesseract-ocr seems to also support CMake, maybe that would work better?
Libraw doesn't seem to support any sane build system OOTB but there is user contributed https://github.com/LibRaw/LibRaw-cmake . No idea if anybody tried it.

**Comment by MehdiChinoune** [comment]
> Tesseract-ocr seems to also support CMake, maybe that would work better?
> Libraw doesn't seem to support any sane build system OOTB but there is user contributed https://github.com/LibRaw/LibRaw-cmake . No idea if anybody tried it.

I tried to use to use CMake, but it failed.
https://github.com/MehdiChinoune/MINGW-packages/runs/3639915113?check_suite_focus=true

**Comment by revelator** [comment]
as jeremy said it is libtool fucking up :P you can get around it specifying -fopenmp=omp in CFLAGS CXXFLAGS and LDFLAGS

**Comment by MehdiChinoune** [comment]
> as jeremy said it is libtool ***** **messing** up :P you can get around it specifying -fopenmp=omp in CFLAGS CXXFLAGS and LDFLAGS

Please, Don't curse/swear.

**Comment by revelator** [comment]
old craftsman here, the jargon happens to be bit on the rude side when things mess up, nothing ment by it, it is just the jargon in my circles. 
But ill try to limit it.

**Comment by revelator** [comment]
comment corrected ;)
