### ISSUE TITLE
pkg-config returns too much data.

### ISSUE THREAD

**Issue by BillKek** [msys2/MINGW-packages#9631]
Hello everyone,

I am experiencing a very fundamental issue with pkg-config.

Steps:
1. Run `pkg-config --libs --static gtkmm-2.4`
2. Get about 75kB data. It's correct enough parameters.  Use it in `g++` call.
3. But `g++` does not accept such a long string. 
4. `getconf ARG_MAX` in `msys2-console` returns `32000` (It's typical limit for Windows).  I suppose limit could be as like in Linux (up to 2MB). Windows 11 has the same ~32000 limit.

**Comment by 1480c1** [comment]
One thing you could do is trying using response files
```bash
{
    pkg-config --cflags --static gtkmm-2.4 | tr ' ' '\n'
    printf '%s\n' source.c
    pkg-config --libs --static gtkmm-2.4 | tr ' ' '\n'
 } > gtkmmlibs.rsp
g++ @gtkmmlibs.rsp
```

https://gcc.gnu.org/wiki/Response_Files

**Comment by BillKek** [comment]
It's a really good workaround. This method is even more inclusive than simply increasing the parameter `ARG_MAX` in msys2 system. Very Thanks.

`$(shell sh.exe -c "{ pkg-config --libs --static gtkmm-2.4 | tr ' ' '\n'; } > LinkOptions1.rsp" )` and
`g++ ... @LinkOptions1.rsp` worked well.

Actually precompiled pack of `gtkmm-2.4` does not support static option wholly. But this is not a problem of `msys2`.
