### ISSUE TITLE
mingw-w64-x86_64-libuv 1.42 fails on Windows 7

### ISSUE THREAD

**Issue by ustsv** [msys2/MINGW-packages#9632]
cmake: not found GetHostNameW in WS2_32.dll
[ uv_os_gethostname on Windows 7 x64 #3260 ](https://github.com/libuv/libuv/issues/3260) Windows 7 RIP?

**Comment by Biswa96** [comment]
The [upstream commit][1], which changes gethostname -> GetHostNameW, does also fix an issue if the name contains non-ascii characters. It also seems to fix an issue in NodeJS. So, which one should be prioritize?

1. Windows 7 support.
Or
2. Reintroduce the non-ascii name issue in libuv.

[1]: https://github.com/libuv/libuv/commit/95f88f47f28b4686a6959377c8d2c31daa40bd64

**Comment by evpobr** [comment]
CMake uses libuv, it is critical issue IMHO.

**Comment by Biswa96** [comment]
OK, I have reverted the upstream commit which added GetHostNameW. Please test the packages from GitHub Actions artifacts in the linked pull request.

**Comment by evpobr** [comment]
Works for me, MinGW64, thank you.

**Comment by lazka** [comment]
> CMake uses libuv, it is critical issue IMHO.

cmake is a developer tool and not something you ship to users, so it's not critical at all to not have win7 support there.

**Comment by Biswa96** [comment]
What if the developer is using Windows 7? 😎

**Comment by evpobr** [comment]
I wouldn't say that. In the case of Node.js it was a case of an incorrect host name, not such a frequent case. But the `libuv ' bug is like a disease, all dependent applications and libraries will stop working in Windows 7, whether the developers want it or not.

**Comment by stanleyxu2005** [comment]
> CMake uses libuv, it is critical issue IMHO.

What's alternative library for CMake to use? I'm getting serious with libuv dropping off support for Windows 7 (and tactically dropping Windows 8)

**Comment by MehdiChinoune** [comment]
> What's alternative library for CMake to use?

There is no alternative.
