### ISSUE TITLE
python 3.9.7: failed to build _decimal module

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#9645]
I noticed this while clangarm64 was building python 3.9.7, but looking back at the [autobuild logs](https://github.com/msys2/msys2-autobuild/actions/runs/1260917937) this failed on ucrt64 too at least:
```
  In file included from ../Python-3.9.7/Include/unicodeobject.h:58,
                   from ../Python-3.9.7/Include/Python.h:106,
                   from C:/_/M/mingw-w64-python/src/Python-3.9.7/Modules/_decimal/_decimal.c:29:
  C:/_/M/mingw-w64-python/src/Python-3.9.7/Modules/_decimal/_decimal.c: In function 'dec_format':
  C:/_/M/mingw-w64-python/src/Python-3.9.7/Modules/_decimal/_decimal.c:3282:43: error: 'uchar' undeclared (first use in this function); did you mean 'char'?
   3282 |         if (n > 1 || (n == 1 && !isascii((uchar)spec.dot[0]))) {
        |                                           ^~~~~
```

Python doesn't fail the build if a module fails, it just lacks that module, so this was probably overlooked.

**Comment by jeremyd2019** [comment]
Same error in mingw64, so probably failed everywhere.

**Comment by lazka** [comment]
This code is changed in 3.10 upstream: https://github.com/python/cpython/pull/24962
