### ISSUE TITLE
cppcoro : broken_promise.hpp is an empty file

### ISSUE THREAD

**Issue by bjomp** [msys2/MINGW-packages#9650]

**Comment by revelator** [comment]
let me guess that is why it is called broken_promise XD, 
phun aside it might be intended as a stub include that its empty might mean
that the system does not need this file.

**Comment by revelator** [comment]
```
///////////////////////////////////////////////////////////////////////////////
// Copyright (c) Lewis Baker
// Licenced under MIT license. See LICENSE.txt for details.
///////////////////////////////////////////////////////////////////////////////
#ifndef CPPCORO_BROKEN_PROMISE_HPP_INCLUDED
#define CPPCORO_BROKEN_PROMISE_HPP_INCLUDED

#include <stdexcept>

namespace cppcoro
{
	/// \brief
	/// Exception thrown when you attempt to retrieve the result of
	/// a task that has been detached from its promise/coroutine.
	class broken_promise : public std::logic_error
	{
	public:
		broken_promise()
			: std::logic_error("broken promise")
		{}
	};
}

#endif
```

err ?!? this is the contents of mine so it should not be empty, i suspect something broken in your build system.

**Comment by Biswa96** [comment]
@bjomp Did you try to reinstall the package? Did you check if any antivirus (including Windows Defender) or antimalware program deleted/cleared that header file?

**Comment by Biswa96** [comment]
This issue may be fixed with this pull request https://github.com/msys2/MINGW-packages/pull/10582. Anyone would like to check?

**Comment by bustercopley** [comment]
Looks good to me. (No zero-length files are installed by the MINGW64 variant package from CI.)
