### ISSUE TITLE
headers-git: There is no prototype for GetHostNameW in winsock2.h.

### ISSUE THREAD

**Issue by erw7** [msys2/MINGW-packages#9667]
This causes mingw32 to fail to build libuv 1.42.0.

#### gethostname.c

```C
#include <stdio.h>
#include <winsock2.h>

#define MAXHOSTNAME 256

int main(void)
{
  WSADATA wsa_data;
  if (WSAStartup(MAKEWORD(2, 2), &wsa_data)) {
    wprintf(L"failed WSAStartup: %d\n", WSAGetLastError());
    return 1;
  }
  wchar_t buf[MAXHOSTNAME];
  if (GetHostNameW(buf, MAXHOSTNAME)) {
    wprintf(L"failed GetHostNameW: %d\n", WSAGetLastError());
    return 1;
  }
  wprintf(buf);

  return 0;
}
```

```
gcc gethostname.c -lws2_32
gethostname.c: In function 'main':
gethostname.c:14:7: warning: implicit declaration of function 'GetHostNameW'; did you mean 'gethostname'? [-Wimplicit-function-declaration]
   14 |   if (GetHostNameW(buf, MAXHOSTNAME)) {
      |       ^~~~~~~~~~~~
      |       gethostname
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cczBZjOw.o:gethostname.c:(.text+0xa4): undefined
 reference to `GetHostNameW'
collect2.exe: error: ld returned 1 exit status
```

**Comment by Biswa96** [comment]
I have added the header in upstream here https://sourceforge.net/p/mingw-w64/mailman/message/37352673/. The new header package is in pending area https://packages.msys2.org/queue.

BTW, in MINGW-packages/mingw-w64-libuv, the upstream commit which adds GetHostNameW has been reverted for Windows 7 support.

**Comment by erw7** [comment]
I'm sorry for posting the noise. 

> BTW, in MINGW-packages/mingw-w64-libuv, the upstream commit which adds GetHostNameW has been reverted for Windows 7 support.

In building neovim with CI, we build and use libuv from source instead of MINGW packages. Therefore, we tried to upgrade the libuv version to 1.42.0, but the build failed due to this issue (neovim/neovim/pull/15756).
