### ISSUE TITLE
[Documentation] Example how to compile from source and build a package for use via pacman?

### ISSUE THREAD

**Issue by rubyFeedback** [msys2/MINGW-packages#9668]
Could there be a separate document added to the main homepage, that shows
how to compile from source and create an installable package via pacman?

For example, sed: ftp://ftp.gnu.org/gnu/sed/sed-4.8.tar.xz

Say we just downloaded this and extracted it in the msys2 shell. Which steps
are the next? Would "./configure --prefix=/usr" work? What after "make install",
how to create a package for use in pacman?

**Comment by Biswa96** [comment]
The documentation had already been written decades ago https://wiki.archlinux.org/title/Creating_packages

**Comment by jeremyd2019** [comment]
Since you said msys2 shell and are using prefix /usr, I assume you are talking about MSYS2-packages not MINGW-packages?  https://github.com/msys2/MSYS2-packages/tree/master/sed/

**Comment by Biswa96** [comment]
Basic package building guidelines can be found here https://www.msys2.org/dev/new-package/
