### ISSUE TITLE
gcc segmentation fault in cc1plus (with upstream fix)

### ISSUE THREAD

**Issue by ulatekh** [msys2/MINGW-packages#9680]
I recently encountered a gcc crash, building a version of cmake from git.
The compiler was installed from the mingw-w64-i686-gcc-10.3.0-5 package (i.e. I was trying to make a 32-bit build of cmake).
I've successfully built the 64-bit version of the same sources and created my own package (which installed and ran fine).

[Enclosed](https://github.com/msys2/MINGW-packages/files/7254475/cmTimestamp.zip) is a zip archive with the preprocessed source file, and a shell script that shows how the original source file was built.

The minimum to reproduce the crash is `g++ -march=x86-64 cmTimestamp.ii` .
It also crashes under Fedora Core 33 (gcc 10.3.1-1) with `g++ -march=x86-64 -m32 cmTimestamp.ii` .

Reported upstream [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102548). They have a [patch](https://gcc.gnu.org/bugzilla/attachment.cgi?id=51548) available, which seems to apply to gcc 10 just fine.

**Comment by oltolm** [comment]
This has been fixed upstream in and can be closed.
