### ISSUE TITLE
DLLs not found when compiling from CMD

### ISSUE THREAD

**Issue by me21** [msys2/MINGW-packages#9686]
I have installed MSYS2 to C:\MSYS64 and installed mingw-w64-x86_64-toolchain.
I've noticed that when I try to compile a simple C++ program:

```
#ifndef __cplusplus
	# error "The CMAKE_CXX_COMPILER is set to a C compiler"
#endif
int main(){return 0;}
```

with command `c:\msys64\mingw64\bin\g++.exe -c main.cpp`,
I get errors from `cc1plus.exe` about missing DLLs: `zlib1.dll`, `libgmp-10.dll`, `libzstd.dll`, `libwinpthread-1.dll`. These files are located in `C:\msys64\mingw64\bin`, but `cc1plus.exe` is located in `C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\10.3.0`, hence it cannot find these DLLs.

When I compile from Mingw64 prompt, everything works because it alters the path.

I don't know whether this is a bug or unexpected behaviour, but it appears that Mingw64 compiler is unusable from third party programs like VSCode without modifying the PATH environment variable.

**Comment by Biswa96** [comment]
> When I compile from Mingw64 prompt, everything works because it alters the path

That's how it works :)

You can use command like this `C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64` to open mingw64 environment in VSCode terminal emulator. There is a guide about how to use in Windows Terminal here https://www.msys2.org/docs/terminals/#windows-terminal

**Comment by Biswa96** [comment]
I think that vscode guidelines can be added in that documentation. You can also help to add the VSCode section in that terminals page here https://github.com/msys2/msys2.github.io/blob/source/web/docs/terminals.md

**Comment by me21** [comment]
I'm actually trying to make it work with CMake-tools extension for VSCode, so it's really not about opening an interactive environment, rather make VSCode call CMake with correct environment.
Currently I prepend the path in the environments settings of the plugin and it works, but I'm not sure how right is this solution.
