### ISSUE TITLE
Make -j error after updating from 4.2.1 to 4.3

### ISSUE THREAD

**Issue by devdl11** [msys2/MINGW-packages#9689]
Hi!
I used an old installation of msys to build my numworks projects.
Yesterday I decided to reinstall msys to the last version (Because of some cpp build errors) and the make build command doesn't work anymore. 
I got this error:
![image](https://user-images.githubusercontent.com/54149885/135500163-3b7bfa1c-332f-4153-ba6a-ad8b4bfe9e96.png)

What's strange is that I don't have this error with the previous installation (from 2019) so I don't know what to do (I reinstalled several times msys and the packages)

**Comment by Biswa96** [comment]
Working here!
![Untitled](https://user-images.githubusercontent.com/31443074/135503976-561c4c5f-4931-425d-9579-6ecf8e460993.png)

Check any issue in makefile or the build system files.

**Comment by devdl11** [comment]
Thanks for the response ! How do I check if there is any build error or make issue? Because I checked every makefile with the `-j` argument and no file has a negative value ... (sorry if my english is not very good^^)

**Comment by Biswa96** [comment]
Probably search for the `-j` options like doing `grep -r "\-j"` in build directory. The following command reproduces your given error message:

```
$ make -j 0
make: the '-j' option requires a positive integer argument
Usage: make [options] [target] ...
```

**Comment by devdl11** [comment]
Thanks for the grep command ! saddly, there isn't a make -j with space in files.... It's very strange because I just ran the build command with the previous msys and all worked fine, but if I try with the new one, nothing works. I had this very strange error.
Older one with no error:
![image](https://user-images.githubusercontent.com/54149885/135508008-869f5014-ca96-4115-8dc4-ad764ef746d6.png)
New one with error:
![image](https://user-images.githubusercontent.com/54149885/135508049-d6882e99-70a9-4c00-a446-92460b0f4333.png)
