### ISSUE TITLE
libheif crash

### ISSUE THREAD

**Issue by novomesk** [msys2/MINGW-packages#9694]
Following command crashes:
```
$ heif-enc.exe --list-encoders
Segmentation fault
```
mingw-w64-libheif had a fix in the past which included `CPPFLAGS+=" -DX265_API_IMPORTS=1"` fix:
https://github.com/msys2/MINGW-packages/commit/31a11d8ce3c7420336c7be85cc20a2d1ba450a9a#diff-3a7de0803322c8cc4c8f0af678881974eda03b4158e928684bd083fa84f363f7

But the X265_API_IMPORTS define was removed later during the switch of build systems in
https://github.com/msys2/MINGW-packages/commit/e4fe777800b850ccc8584e68787eb90daa7b5bc1#diff-9e29ae9d45d8d80d08d53b989349827b01c2b7b5e3d00738f0c2e50c520a4a46R49
so the crash is occurring again.

Can you put the fix back please? GIMP 2.99 is affected by this too.

**Comment by Jehan** [comment]
Maybe put some comment next to the CPPFLAGS next time so that you won't remove it by mistake, next time someone doesn't remember what this was for. 😉

**Comment by kmilos** [comment]
That's exactly what happened, apologies - I (wrongly) assumed that the (more modern) cmake scripts would find all the necessary flags automagically but I guess not all libs export their configurations...

**Comment by Jehan** [comment]
No prob @kmilos. It happens. 🙂

**Comment by kleisauke** [comment]
FWIW, for those not subscribed to https://github.com/strukturag/libheif/issues/357, this:
https://github.com/msys2/MINGW-packages/blob/2281e09b1c904bf2eb2125f95fa753fbbd4e6d44/mingw-w64-libheif/PKGBUILD#L77

might no longer be needed once PR https://github.com/Multicorewareinc/x265/pull/946 lands.
