### ISSUE TITLE
Can't link SFML using GCC

### ISSUE THREAD

**Issue by antoniorand** [msys2/MINGW-packages#9696]
I use the flag -lsfml-graphics but it just won't find the DLL even though the dll should be in the system
![Captura](https://user-images.githubusercontent.com/31995251/135661897-d7dc0912-b08f-4654-90b1-77cfdfc3340c.PNG)
.

**Comment by Biswa96** [comment]
The path `/usr/lib/gcc/x86_64-pc-msys` suggests that the makefile is using GCC from MSYS2 environment. Try to use MINGW64 toolchain. Maybe the `rpath=lib/` is not required here.

**Comment by antoniorand** [comment]
It was a stupid code problem after all. Thank you so much for answering. The problem was about not having the -Llib flag stating that my libraries were to be found in that folder.

**Comment by Biswa96** [comment]
> not having the -Llib flag stating that my libraries were to be found in that folder

AFAIK, it is not required to add the library folder. linker automatically finds it. For example, here is the output from `ld` in ucrt64:

```
$ ld --verbose | grep SEARCH
SEARCH_DIR("=/ucrt64/x86_64-w64-mingw32/lib"); SEARCH_DIR("=/ucrt64/lib"); SEARCH_DIR("=/usr/local/lib"); SEARCH_DIR("=/lib"); SEARCH_DIR("=/usr/lib");
```

**Comment by podsvirov** [comment]
If all discussions are resolved, how about closing this issue?
