### ISSUE TITLE
Undefined reference to '_setjmp' when static linking using -mcrtdll=ucrt on MINGW64.

### ISSUE THREAD

**Issue by ikspress** [msys2/MINGW-packages#9712]
![GJE_QN3$OLPY(TO4I~LTTBR](https://user-images.githubusercontent.com/91833768/135880822-678dc6a9-d39b-46ee-abb5-bcab1c3d0182.png)

[This patch](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gcc/0006-Windows-New-feature-to-allow-overriding.patch) adds this feature,, but I think that allow overriding -lmsvcrt is useless.

**Comment by revelator** [comment]
i think it may be a leftover from when we first tried porting to ucrt but yeah it is pretty useless.
the idea is ok'ish but there are more factors to allow it to work you would also have to set some flags like -D_UCRT and then we hit the problem with every other library being linked to msvcrt which do not play well with being linked to the ucrt runtime.
one use could be linking to diffferent msvcrt versions but even then we would hit snags.

**Comment by MehdiChinoune** [comment]
You can't link to ucrt on MINGW64.
