### ISSUE TITLE
PETSc and his .pc file (pkgconfig)

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#9723]
Hi @okhlybov,

In file migw64/src/petsc-3.15.4/cmo/lib/pkgcongig/PETSc.pc header file paths are given, they look a bit dodgy (mingw-w64-petsc?). I have a problem with them when compiling the precice package: https://github.com/precice/precice/issues/903#issuecomment-934652530

like:
`prefix=/c/_/M/mingw-w64-petsc/src/build-x86_64-w64-mingw32/petsc-3.15.4/cmo`

`Cflags: -D__USE_MINGW_ANSI_STDIO=1  -I${includedir} -I/c/_/M/mingw-w64-petsc/src/build-x86_64-w64-mingw32/petsc-3.15.4/include`

**Comment by Biswa96** [comment]
The full build path reference can be removed with command like this

```sh
  local PREFIX_WIN=$(cygpath -wm ${MINGW_PREFIX})
  for pcfile in "${pkgdir}${MINGW_PREFIX}"/lib/pkgconfig/*.pc; do
    sed -s "s|${PREFIX_WIN}|${MINGW_PREFIX}|g" -i "${pcfile}"
  done
```

But in this case the command has to be done for both srcdir and pkgdir.
