### ISSUE TITLE
libgd update to 2.3.3 (improved windows support) and patch question

### ISSUE THREAD

**Issue by GitMensch** [msys2/MINGW-packages#9839]
warning: I don't use that package but as I've stumbled over it wanted to drop at least a note.

* libgd is currently at version 2.3.2 , [version 2.3.3 got released September 2021](https://github.com/libgd/libgd/releases/tag/gd-2.3.3) so it is likely reasonable to update
* the update claims to have improved windows support and explicit mentions fixing MSYS2 builds (which should allow dropping the getline and memalign patches)
* the current patch https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libgd/libgd-export-pkg-config-build-in-subdirs.patch looks quite suspicious in one place: it adds in getopt (who have thought so given the patch' name) which is included in libgd already - so there shouldn't be a need for that (maybe that patch can either be completely removed or replaced with a new minimal one if the "improvement" claims of 2.3.3 are true)

**Comment by MehdiChinoune** [comment]
Fixed by #12575

**Comment by GitMensch** [comment]
Thanks for the PR and nice to see that https://github.com/libgd/libgd/pull/828/files#diff-43f743482ff66216c96c5dd34e41f0f48d8d452ae183ca9c28d25251ed29f5fa will lead to no / much less patches on libgd 2.3.4
