### ISSUE TITLE
`rsvg-convert` produces invalid .png image

### ISSUE THREAD

**Issue by mmuetzel** [msys2/MINGW-packages#9906]
After a recent update, `rsvg-convert` no longer produces valid .png images from .svg files.

Steps to reproduce:
[octave-logo.zip](https://github.com/msys2/MINGW-packages/files/7432797/octave-logo.zip)
With the .svg file in that .zip archive, run:
```
pacman -S mingw-w64-x86_64-librsvg
rsvg-convert.exe -w 256 -f png ./octave-logo.svg > octave-logo-test.png
```

Expected result:
The resulting .png image can be opened in an image viewer and shows the logo from the .svg file.

Actual result:
Trying to open the resulting .png file leads to an error message. The phrasing of that error message depends on the image viewer. But it essentially says that the file is an invalid image.

This was still working a few days ago.

**Comment by federicomenaquintero** [comment]
If anyone knows the vagaries of `GetStdHandle()`, `WriteFile()`, etc. I'd love some help as noted in https://gitlab.gnome.org/GNOME/librsvg/-/issues/812#note_1305523

Thanks in advance!

**Comment by Biswa96** [comment]
@mmuetzel Thank you for working on this issue. One thing catches me that the Win32 libraries have to mentioned explicitly in PKGBUILD. Is it possible to add those libraries in autoconf scripts? The win32/config-msvc.mak.in file has those but it is for msvc.
