### ISSUE TITLE
File conflict between mingw-w64-qt6-scxml and mingw-w64-qt5-scxml

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#9947]
>  error: failed to commit transaction (conflicting files) > mingw-w64-i686-qt6-scxml: /mingw32/bin/qscxmlc.exe exists in filesystem (owned by mingw-w64-i686-qt5-scxml) > mingw-w64-x86_64-qt6-scxml: /mingw64/bin/qscxmlc.exe exists in filesystem (owned by mingw-w64-x86_64-qt5-scxml) > Errors occurred, no packages were upgraded.

@MehdiChinoune maybe?

**Comment by MehdiChinoune** [comment]
I will rename them.

**Comment by lazka** [comment]
Thanks!

**Comment by Biswa96** [comment]
Is there any official solution from upstream? Can I ask about this?

**Comment by MehdiChinoune** [comment]
> Is there any official solution from upstream? Can I ask about this?

They offer a solution, but It couldn't be applied to MinGW (Windows in general) before the shared libraries and the executabels share the same destination on Windows.
https://github.com/archlinux/svntogit-packages/blob/master/qt6-base/trunk/PKGBUILD#L46
https://github.com/archlinux/svntogit-packages/blob/master/qt6-base/trunk/PKGBUILD#L65
