### ISSUE TITLE
internal compiler error: in tsubst_pack_expansion

### ISSUE THREAD

**Issue by kaxhif** [msys2/MINGW-packages#9993]
I am receiving an internal compiler error: in tsubst_pack_expansion, at cp/pt.c:13123 while compiling the attached source code on Windows 10. Although the code snippet is working on the [gcc.godbolt.org/z/aG5dedPbn ](link)
[Source.zip](https://github.com/msys2/MINGW-packages/files/7475308/Source.zip)

**Comment by MehdiChinoune** [comment]
ICEs are in general bugs in the compiler itself, and should be reported upstream.

**Comment by oltolm** [comment]
I can not reproduce it anymore with GCC 13.2.0. I think we should close it.
